import type { Lesson } from '../../types';

const L = 'es.a1.l07';
const IV = ['es.g.ir-venir'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c2',
  order: 7,
  title: 'Verkehrsmittel – ir & venir',
  subtitle: 'en autobús, en metro, a pie · ¿Cuánto tarda? · ¿A qué hora sale?',
  icon: '🚇',
  minutes: 12,
  goal:
    'Du sagst, **wie** du irgendwohin kommst (`Voy al trabajo en metro.`), fragst nach **Fahrzeit** und **Abfahrt** (`¿Cuánto tarda?`, `¿A qué hora sale el tren?`) und lernst das Verb **venir** – und warum Spanisch oft `voy` sagt, wo wir „ich komme“ sagen.',
  canDo: [
    'Ich kann sagen, mit welchem Verkehrsmittel ich fahre: en autobús, en metro, a pie.',
    'Ich kann ir und venir im Präsens verwenden und richtig unterscheiden.',
    'Ich kann fragen, wie lange eine Fahrt dauert, und die Antwort verstehen.',
    'Ich kann nach Abfahrtszeiten fragen: ¿A qué hora sale el tren?',
  ],
  topicIds: IV,
  vocab: [
    { id: `${L}.v.autobus`, target: 'el autobús', german: 'der Bus', pos: 'noun', gender: 'm', plural: 'los autobuses', emoji: '🚌', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Voy al trabajo en autobús.', german: 'Ich fahre mit dem Bus zur Arbeit.' } },
    { id: `${L}.v.metro`, target: 'el metro', german: 'die U-Bahn, die Metro', pos: 'noun', gender: 'm', plural: 'los metros', emoji: '🚇', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Vamos en metro.', german: 'Wir fahren mit der U-Bahn.' } },
    { id: `${L}.v.tren`, target: 'el tren', german: 'der Zug', pos: 'noun', gender: 'm', plural: 'los trenes', emoji: '🚆', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'El tren sale a las nueve.', german: 'Der Zug fährt um neun ab.' } },
    { id: `${L}.v.avion`, target: 'el avión', german: 'das Flugzeug', pos: 'noun', gender: 'm', plural: 'los aviones', emoji: '✈️', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Vamos a Lima en avión.', german: 'Wir fliegen nach Lima.' } },
    { id: `${L}.v.coche`, target: 'el coche', german: 'das Auto', pos: 'noun', gender: 'm', plural: 'los coches', emoji: '🚗', variant: 'es-ES', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Mi padre va en coche.', german: 'Mein Vater fährt mit dem Auto.' } },
    { id: `${L}.v.carro`, target: 'el carro', german: 'das Auto (im Cono Sur: el auto)', pos: 'noun', gender: 'm', plural: 'los carros', emoji: '🚗', variant: 'es-LA', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Mi padre va en carro.', german: 'Mein Vater fährt mit dem Auto.' } },
    { id: `${L}.v.bicicleta`, target: 'la bicicleta', german: 'das Fahrrad', pos: 'noun', gender: 'f', plural: 'las bicicletas', emoji: '🚲', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Mi hermana va en bici.', german: 'Meine Schwester fährt mit dem Rad.' } },
    { id: `${L}.v.a-pie`, target: 'a pie', german: 'zu Fuß', pos: 'phrase', emoji: '🚶', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Voy al supermercado a pie.', german: 'Ich gehe zu Fuß zum Supermarkt.' } },
    { id: `${L}.v.venir`, target: 'venir', german: 'kommen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: '¿Vienes a la fiesta?', german: 'Kommst du zur Party?' } },
    { id: `${L}.v.tardar`, target: 'tardar', german: 'dauern; (Zeit) brauchen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: '¿Cuánto tarda el autobús?', german: 'Wie lange braucht der Bus?' } },
    { id: `${L}.v.salir`, target: 'salir', german: 'abfahren; hinausgehen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'El tren sale a las ocho.', german: 'Der Zug fährt um acht ab.' } },
    { id: `${L}.v.billete`, target: 'el billete', german: 'die Fahrkarte, das Ticket', pos: 'noun', gender: 'm', plural: 'los billetes', emoji: '🎫', variant: 'es-ES', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Un billete para Toledo, por favor.', german: 'Eine Fahrkarte nach Toledo, bitte.' } },
    { id: `${L}.v.boleto`, target: 'el boleto', german: 'die Fahrkarte, das Ticket', pos: 'noun', gender: 'm', plural: 'los boletos', emoji: '🎫', variant: 'es-LA', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'Un boleto para Puebla, por favor.', german: 'Eine Fahrkarte nach Puebla, bitte.' } },
    { id: `${L}.v.parada`, target: 'la parada', german: 'die Haltestelle', pos: 'noun', gender: 'f', plural: 'las paradas', emoji: '🚏', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: 'La parada está enfrente del banco.', german: 'Die Haltestelle ist gegenüber der Bank.' } },
    { id: `${L}.v.aeropuerto`, target: 'el aeropuerto', german: 'der Flughafen', pos: 'noun', gender: 'm', plural: 'los aeropuertos', emoji: '🛫', field: 'Verkehr', stageId: 'a1', lessonId: L, example: { target: '¿Cómo llego al aeropuerto?', german: 'Wie komme ich zum Flughafen?' } },
    { id: `${L}.v.minuto`, target: 'el minuto', german: 'die Minute', pos: 'noun', gender: 'm', plural: 'los minutos', emoji: '⏱️', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Tarda veinte minutos.', german: 'Es dauert zwanzig Minuten.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Verkehrsmittel stehen mit **en** und ohne Artikel: `en autobús`, `en metro`, `en tren`, `en avión`, `en bici`. Einzige wichtige Ausnahme: **zu Fuß** = `a pie`.\nDas **Ziel** steht mit `a` (`Voy a Madrid`, `Voy al trabajo`), der **Ausgangspunkt** mit `de` (`Vengo de casa`, `Vengo del trabajo`).\n`ir` kennst du schon: `voy, vas, va, vamos, vais, van`. Neu ist **venir** (kommen) – unregelmäßig wie `tener`: yo-Form auf `-go`, im betonten Stamm `ie`.',
    },
    {
      type: 'conjugation',
      verb: 'venir',
      translation: 'kommen',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'vengo', ending: 'go' },
        { person: 'tú', form: 'vienes', ending: 'es' },
        { person: 'él / ella / usted', form: 'viene', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'venimos', ending: 'imos' },
        { person: 'vosotros / vosotras', form: 'venís', ending: 'ís', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'vienen', ending: 'en' },
      ],
    },
    {
      type: 'compare',
      target: '¡Ya voy!',
      german: 'Ich komme schon!',
      md:
        'Spanisch denkt vom **Sprecher** aus: `venir` heißt „hierher kommen“ – dorthin, wo der Sprecher ist. Bewegst du dich zu jemand anderem hin, benutzt du `ir`, auch wenn wir auf Deutsch „kommen“ sagen. Ruft dich jemand zum Essen, antwortest du also `¡Ya voy!` Fragt eine Freundin `¿Vienes a mi casa?`, sagst du `Sí, voy a las ocho.`',
    },
    {
      type: 'mistake',
      wrong: 'Voy con el autobús.',
      right: 'Voy en autobús.',
      why:
        '„Mit dem Bus“ verleitet zu `con el`. Verkehrsmittel stehen auf Spanisch mit `en` und **ohne Artikel**: `en autobús`, `en tren`, `en metro`. Nur zu Fuß ist anders: `a pie` (nicht „en pie“).',
    },
    {
      type: 'colored',
      parts: [
        { text: '¿A qué hora', role: 'question' },
        { text: ' ' },
        { text: 'sale', role: 'verb' },
        { text: ' ' },
        { text: 'el tren', role: 'subject' },
        { text: ' ' },
        { text: 'a Sevilla', role: 'other' },
        { text: '?' },
      ],
      german: 'Um wie viel Uhr fährt der Zug nach Sevilla ab?',
    },
    {
      type: 'tip',
      md:
        'Merksatz: **sale** = fährt ab, **llega** = kommt an, **tarda** = dauert.\n- `¿A qué hora sale el autobús?` – `Sale a las ocho.`\n- `¿A qué hora llega?` – `Llega a las diez.`\n- `¿Cuánto tarda?` – `Tarda dos horas.` / über dich selbst: `Tardo quince minutos.`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'Das Auto heißt in Spanien `el coche`, in Mexiko, Kolumbien und Mittelamerika `el carro`, in Argentinien, Chile und Uruguay `el auto`. Die Fahrkarte ist in Spanien `el billete`, in Lateinamerika `el boleto`. Den Bus nennt man vielerorts einfach `el bus`, in Mexiko auch `el camión`, in Argentinien `el colectivo`.',
    },
    { type: 'audio', text: '¿Cuánto tarda el tren a Valencia? – Tarda dos horas y sale a las nueve y media.', label: 'Fahrzeit und Abfahrt' },
  ],
  examples: [
    {
      target: 'Voy al trabajo en metro.',
      german: 'Ich fahre mit der U-Bahn zur Arbeit.',
      parts: [
        { text: 'Voy', role: 'verb' },
        { text: ' ' },
        { text: 'al trabajo', role: 'object' },
        { text: ' ' },
        { text: 'en metro', role: 'adverb' },
        { text: '.' },
      ],
    },
    {
      target: 'Mis hijos van a la escuela a pie.',
      german: 'Meine Kinder gehen zu Fuß zur Schule.',
      parts: [
        { text: 'Mis hijos', role: 'subject' },
        { text: ' ' },
        { text: 'van', role: 'verb' },
        { text: ' ' },
        { text: 'a la escuela', role: 'object' },
        { text: ' ' },
        { text: 'a pie', role: 'adverb' },
        { text: '.' },
      ],
    },
    {
      target: '¿De dónde vienes? – Vengo del supermercado.',
      german: 'Wo kommst du gerade her? – Ich komme vom Supermarkt.',
      note: '`¿De dónde vienes?` fragt, woher jemand gerade kommt. Nach der Herkunft fragst du mit `¿De dónde eres?`',
    },
    {
      target: '¿Cuánto tarda el autobús al centro? – Tarda veinte minutos.',
      german: 'Wie lange braucht der Bus ins Zentrum? – Zwanzig Minuten.',
    },
    {
      target: '¿A qué hora sale el avión? – Sale a las seis y media.',
      german: 'Um wie viel Uhr fliegt das Flugzeug ab? – Um halb sieben.',
    },
    {
      target: '¿Vienes a la fiesta el sábado? – ¡Sí, voy!',
      german: 'Kommst du am Samstag zur Party? – Ja, ich komme!',
      note: 'Die Antwort steht mit `voy`: Du bewegst dich zur Party hin, weg von dir.',
    },
    { target: 'Mis padres vienen en coche.', german: 'Meine Eltern kommen mit dem Auto.', variant: 'es-ES' },
    { target: 'Mis padres vienen en carro.', german: 'Meine Eltern kommen mit dem Auto.', variant: 'es-LA', note: 'In Argentinien, Chile und Uruguay: `en auto`.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: IV,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Verkehrsmittel zu.',
      pairs: [
        { emoji: '🚌', word: 'el autobús' },
        { emoji: '🚇', word: 'el metro' },
        { emoji: '🚆', word: 'el tren' },
        { emoji: '✈️', word: 'el avión' },
        { emoji: '🚲', word: 'la bicicleta' },
        { emoji: '🚶', word: 'a pie' },
      ],
      feedback: {
        rule: 'Verkehrsmittel sind fast alle maskulin (`el autobús`, `el tren`, `el avión`); `la bicicleta` (kurz `la bici`) ist weiblich.',
        why: '`el metro` ist die U-Bahn (auch als Längenmaß „Meter“ – der Zusammenhang entscheidet).',
        avoid: 'Lerne jedes Verkehrsmittel gleich mit `en`: en autobús, en metro, en tren – und die Ausnahme `a pie`.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: IV,
      difficulty: 1,
      instruction: 'Ordne jedem Pronomen die passende Form von „venir“ zu.',
      pairs: [
        { left: 'yo', right: 'vengo' },
        { left: 'tú', right: 'vienes' },
        { left: 'usted', right: 'viene' },
        { left: 'nosotros', right: 'venimos' },
        { left: 'ellas', right: 'vienen' },
      ],
      feedback: {
        rule: '`venir`: vengo, vienes, viene, venimos, (venís), vienen – wie `tener`: yo auf -go, betonter Stamm mit ie.',
        why: '`venimos` wird oft zu „vienimos“ – bei nosotros liegt die Betonung auf der Endung, der Stamm bleibt `ven-`.',
        avoid: 'Lerne `tener` und `venir` als Zwillinge: tengo/vengo, tienes/vienes, tenemos/venimos.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: IV,
      difficulty: 2,
      prompt: 'Deine Mitbewohnerin ruft aus der Küche: `¡A comer!` (Essen ist fertig!). Du willst sagen: „Ich komme schon!“',
      options: [
        { text: '¡Ya voy!' },
        { text: '¡Ya vengo!', why: '`venir` heißt „hierher kommen“ – zum Sprecher hin. Du gehst aber zu ihr hin, also weg von dir → `ir`. `Ya vengo` versteht man eher als „Bin gleich zurück“.' },
        { text: '¡Ya vas!', why: '`vas` ist die du-Form – du sprichst aber von dir selbst.' },
        { text: '¡Ya viene!', why: '`viene` ist er/sie/usted – du sprichst von dir selbst (yo).' },
      ],
      answer: 0,
      feedback: {
        rule: 'Bewegung zum Gesprächspartner hin = `ir`: `¡Ya voy!` (Ich komme schon!)',
        why: 'Im Deutschen „kommt“ man zum anderen; Spanisch sieht die Bewegung von dir aus – du **gehst** hin.',
        avoid: 'Frage: Bewege ich mich dorthin, wo der Sprecher gerade ist? Dann `voy`. Kommt jemand zu mir hierher? Dann `viene`.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: IV,
      difficulty: 2,
      instruction: 'Setze die fehlenden kleinen Wörter ein.',
      sentence: 'Voy ___ trabajo ___ autobús, pero mi hermana va ___ pie.',
      answers: [['al'], ['en'], ['a']],
      bank: ['al', 'en', 'a', 'con', 'del'],
      german: 'Ich fahre mit dem Bus zur Arbeit, aber meine Schwester geht zu Fuß.',
      feedback: {
        rule: 'Ziel mit `a` (+ el = `al`), Verkehrsmittel mit `en`, zu Fuß = `a pie`.',
        why: '`con` („mit“) passt nicht zu Verkehrsmitteln; `del` bezeichnet den Ausgangspunkt, nicht das Ziel.',
        avoid: 'Drei feste Muster: `ir a/al …` – `en + Verkehrsmittel` – `a pie`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: IV,
      difficulty: 2,
      audio: 'El tren a Madrid sale a las nueve y cuarto y tarda dos horas y media.',
      question: 'Wann fährt der Zug ab und wie lange dauert die Fahrt?',
      options: ['um 9:15 Uhr, 2½ Stunden', 'um 9:45 Uhr, 2½ Stunden', 'um 9:15 Uhr, 1½ Stunden', 'um 10:15 Uhr, 2 Stunden'],
      answer: 0,
      feedback: {
        rule: '`las nueve y cuarto` = 9:15 Uhr; `tarda dos horas y media` = dauert zweieinhalb Stunden.',
        why: '9:45 wäre `las diez menos cuarto`. `y media` nach `dos horas` bedeutet „und eine halbe“.',
        avoid: 'Hör auf die Signalwörter: `sale` → Uhrzeit, `tarda` → Dauer.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: IV,
      difficulty: 2,
      verb: 'venir',
      tense: 'Präsens',
      person: 'nosotros',
      sentence: 'Nosotros ___ de la estación.',
      answers: ['venimos'],
      feedback: {
        rule: '`nosotros venimos` – ohne Stammwechsel und mit der -ir-Endung `-imos`.',
        why: '„vienimos“ ist falsch (kein ie bei nosotros); „venemos“ ist falsch, weil venir ein -ir-Verb ist.',
        avoid: 'Vergleiche: `vivir` → vivimos, `venir` → venimos.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'order',
      skills: ['grammar', 'speaking'],
      topicIds: IV,
      difficulty: 2,
      instruction: 'Bilde die Frage „Wie lange braucht die U-Bahn zum Flughafen?“.',
      tokens: ['¿Cuánto', 'tarda', 'el', 'metro', 'al', 'aeropuerto?'],
      extra: ['es', 'con'],
      german: 'Wie lange braucht die U-Bahn zum Flughafen?',
      feedback: {
        rule: 'Dauer: `¿Cuánto tarda + Verkehrsmittel + Ziel?` – Ziel mit `al` (a + el).',
        why: '`es` fragt nicht nach der Dauer, und `con` passt nicht zu Verkehrsmitteln.',
        avoid: 'Lerne `¿Cuánto tarda …?` als festen Fragebaustein.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: IV,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Ich fahre mit dem Zug nach Sevilla.',
      answers: [
        'Voy a Sevilla en tren.',
        'Voy en tren a Sevilla.',
        'Yo voy a Sevilla en tren.',
        'Yo voy en tren a Sevilla.',
        'Viajo a Sevilla en tren.',
        'Viajo en tren a Sevilla.',
      ],
      feedback: {
        rule: '„fahren“ = hier `ir`; Ziel mit `a`; Verkehrsmittel mit `en`: `Voy a Sevilla en tren.`',
        why: '`conduzco` hieße „ich fahre (selbst) ein Auto“ – im Zug fährst du nicht selbst. Und „mit dem Zug“ ist `en tren`, nicht `con el tren`.',
        avoid: 'Deutsches „fahren“ als Ortswechsel ist fast immer `ir`.',
      },
    },
  ],
  pronunciation: ['es.p.link.que-hora-es', 'es.p.link.vamos-a-la-playa', 'es.p.bv.vaca'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['speaking', 'grammar'],
      topicIds: IV,
      difficulty: 2,
      scenario: 'Du stehst am Busbahnhof in Madrid und willst wissen, **wann** der Bus nach Toledo abfährt. Was fragst du am Schalter?',
      options: [
        { text: 'Perdone, ¿a qué hora sale el autobús a Toledo?' },
        { text: 'Perdone, ¿cuánto tarda el autobús a Toledo?', why: 'Das fragt nach der **Dauer** der Fahrt, nicht nach der Abfahrtszeit.' },
        { text: 'Perdone, ¿qué hora es el autobús a Toledo?', why: '`¿Qué hora es?` heißt „Wie spät ist es?“ – für eine Abfahrtszeit brauchst du `¿A qué hora sale …?`' },
        { text: 'Perdone, ¿a qué hora llega el autobús de Toledo?', why: 'Das fragt, wann ein Bus **aus** Toledo **ankommt**.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Abfahrt: `¿A qué hora sale …?` – Ankunft: `¿A qué hora llega …?` – Dauer: `¿Cuánto tarda …?`',
        why: 'Die Verben entscheiden: sale (fährt ab), llega (kommt an), tarda (dauert).',
        avoid: 'Merke das `A` am Anfang: `¿A qué hora …?` = Um wie viel Uhr …?',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: IV,
      difficulty: 2,
      prompt: 'Beschreibe deinen Weg zur Arbeit, Uni oder zum Einkaufen: Wie fährst du? Wie lange brauchst du? Um wie viel Uhr fährt dein Bus oder Zug ab?',
      requirements: [
        { pattern: '\\b(voy|vamos|va|van)\\b', hint: 'eine Form von ir (z. B. „voy“)' },
        { pattern: '(\\ben (autob[uú]s|bus|metro|tren|coche|carro|auto|bici|bicicleta|avi[oó]n|taxi)\\b|\\ba pie\\b)', hint: 'ein Verkehrsmittel mit „en …“ oder „a pie“' },
        { pattern: '\\btard', hint: 'eine Form von tardar (z. B. „tardo“, „tarda“)' },
      ],
      samples: [
        'Voy al trabajo en metro. Tardo quince minutos. El metro sale a las ocho y cuarto y llega a las ocho y media. Mi hermana va a la universidad en bici.',
      ],
      minWords: 15,
      feedback: {
        rule: '`Voy a/al … en + Verkehrsmittel`; Dauer mit `tardar`; Abfahrt mit `salir`.',
        why: 'Typische Fehler: `con el metro` statt `en metro` und `en pie` statt `a pie`.',
        avoid: 'Prüfe jedes Verkehrsmittel: steht davor `en` (ohne Artikel)?',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: IV,
      difficulty: 2,
      prompt: 'Erzähl laut: Wie kommst du zur Arbeit oder zum Einkaufen, und wie lange brauchst du?',
      keywords: ['voy', 'autobús', 'bus', 'metro', 'tren', 'coche', 'carro', 'auto', 'bici', 'a pie', 'tardo', 'minutos'],
      minMatch: 3,
      sample: 'Voy al supermercado a pie. Tardo diez minutos. Al trabajo voy en metro.',
      feedback: {
        rule: '`Voy … en metro / a pie. Tardo … minutos.`',
        why: 'Fehlen Schlüsselwörter, war meist das Verkehrsmittel oder `tardo` nicht zu hören.',
        avoid: 'Das b in `autobús` und das v in `voy` klingen im Spanischen gleich – weich, mit fast geschlossenen Lippen.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: IV,
      difficulty: 2,
      scenarioId: 'es.sc.reise',
      goal: 'Plane mit deinem Gegenüber eine Fahrt: Frag, wie ihr hinkommt (Bus, Zug …), wie lange die Fahrt dauert und um wie viel Uhr der Zug oder Bus abfährt.',
      turns: 4,
      feedback: {
        rule: '`¿Vamos en tren o en autobús?` – `¿Cuánto tarda?` – `¿A qué hora sale?`',
        why: 'Wer die drei Fragen beherrscht, kommt auf jeder Reise zurecht.',
        avoid: 'Leg dir vorher die drei Fragebausteine zurecht und hör in der Antwort auf Zahlen und Uhrzeiten.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: ['es.g.imperative-tu'],
      difficulty: 2,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'Toma la segunda calle a la derecho.',
      answers: ['Toma la segunda calle a la derecha.'],
      german: 'Nimm die zweite Straße rechts.',
      feedback: {
        rule: '„rechts“ = `a la derecha` – weiblich, passend zu `la`.',
        why: '`derecho` bedeutet (in Lateinamerika) „geradeaus“ und passt nicht zum Artikel `la`.',
        avoid: 'a **la** derech**a** – Artikel und Endung passen zusammen.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.prepositions-place'],
      difficulty: 2,
      audio: 'La parada está enfrente del museo.',
      answers: ['La parada está enfrente del museo.'],
      german: 'Die Haltestelle ist gegenüber vom Museum.',
      feedback: {
        rule: '`enfrente del museo` – `del` = de + el.',
        why: 'Beim Hören verschwimmen `de` und `el` zu einem Wort – geschrieben wird es auch als ein Wort: `del`.',
        avoid: 'Denk an den Akzent auf `está` – ohne Akzent wäre es „diese“.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading'],
      topicIds: ['es.g.ir-a', 'es.g.ir-venir'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'Mañana vamos a ir al aeropuerto en taxi.',
      answers: [
        'Morgen fahren wir mit dem Taxi zum Flughafen.',
        'Wir fahren morgen mit dem Taxi zum Flughafen.',
        'Morgen werden wir mit dem Taxi zum Flughafen fahren.',
        'Wir werden morgen mit dem Taxi zum Flughafen fahren.',
        'Morgen fahren wir zum Flughafen mit dem Taxi.',
      ],
      feedback: {
        rule: '`vamos a ir` = wir werden fahren / wir fahren (nahe Zukunft); `en taxi` = mit dem Taxi; `al aeropuerto` = zum Flughafen.',
        why: '`vamos a` + Infinitiv drückt einen Plan aus – im Deutschen reicht meist das Präsens mit „morgen“.',
        avoid: 'Übersetze Zukunftspläne natürlich: „Morgen fahren wir …“ klingt deutscher als „Wir gehen zu fahren“.',
      },
    },
  ],
};

export default lesson;
