import type { Lesson } from '../../types';

const L = 'es.a1.l05';
const PREP = ['es.g.prepositions-place'];
const HAY = ['es.g.hay'];
const BOTH = ['es.g.prepositions-place', 'es.g.hay'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c2',
  order: 5,
  title: 'Orte in der Stadt',
  subtitle: 'hay, está und Ortsangaben wie al lado de, enfrente de, cerca de',
  icon: '🏙️',
  minutes: 12,
  goal:
    'Du sagst, **was es** in deinem Viertel gibt und **wo** etwas liegt: `Hay una farmacia cerca.` – `La farmacia está al lado del banco.` Dazu lernst du die wichtigsten Ortsangaben (neben, gegenüber, vor, hinter, zwischen …) und die Verschmelzungen `al` und `del`.',
  canDo: [
    'Ich kann sagen, welche Orte es in einem Viertel gibt (hay).',
    'Ich kann mit estar sagen, wo sich ein bestimmter Ort befindet.',
    'Ich kann Ortsangaben wie al lado de, enfrente de, cerca de und entre verwenden.',
    'Ich kann a + el zu al und de + el zu del zusammenziehen.',
  ],
  topicIds: BOTH,
  vocab: [
    { id: `${L}.v.banco`, target: 'el banco', german: 'die Bank (Geldinstitut)', pos: 'noun', gender: 'm', plural: 'los bancos', emoji: '🏦', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: 'El banco está en la plaza.', german: 'Die Bank ist am Platz.' } },
    { id: `${L}.v.farmacia`, target: 'la farmacia', german: 'die Apotheke', pos: 'noun', gender: 'f', plural: 'las farmacias', emoji: '💊', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: '¿Hay una farmacia cerca de aquí?', german: 'Gibt es hier in der Nähe eine Apotheke?' } },
    { id: `${L}.v.supermercado`, target: 'el supermercado', german: 'der Supermarkt', pos: 'noun', gender: 'm', plural: 'los supermercados', emoji: '🛒', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: '¿Dónde está el supermercado?', german: 'Wo ist der Supermarkt?' } },
    { id: `${L}.v.estacion`, target: 'la estación', german: 'der Bahnhof', pos: 'noun', gender: 'f', plural: 'las estaciones', emoji: '🚉', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: 'La estación está lejos del centro.', german: 'Der Bahnhof liegt weit weg vom Zentrum.' } },
    { id: `${L}.v.parque`, target: 'el parque', german: 'der Park', pos: 'noun', gender: 'm', plural: 'los parques', emoji: '🌳', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: 'Hay un parque detrás de mi casa.', german: 'Hinter meinem Haus gibt es einen Park.' } },
    { id: `${L}.v.museo`, target: 'el museo', german: 'das Museum', pos: 'noun', gender: 'm', plural: 'los museos', emoji: '🏛️', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: 'El museo está enfrente del parque.', german: 'Das Museum liegt gegenüber vom Park.' } },
    { id: `${L}.v.centro`, target: 'el centro', german: 'das Zentrum, die Innenstadt', pos: 'noun', gender: 'm', plural: 'los centros', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: 'Vivo en el centro.', german: 'Ich wohne im Zentrum.' } },
    { id: `${L}.v.barrio`, target: 'el barrio', german: 'das (Stadt-)Viertel', pos: 'noun', gender: 'm', plural: 'los barrios', emoji: '🏘️', field: 'Stadt', stageId: 'a1', lessonId: L, example: { target: 'En mi barrio hay un parque.', german: 'In meinem Viertel gibt es einen Park.' } },
    { id: `${L}.v.al-lado-de`, target: 'al lado de', german: 'neben', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'La farmacia está al lado del banco.', german: 'Die Apotheke ist neben der Bank.' } },
    { id: `${L}.v.enfrente-de`, target: 'enfrente de', german: 'gegenüber (von)', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'El banco está enfrente de la estación.', german: 'Die Bank liegt gegenüber vom Bahnhof.' } },
    { id: `${L}.v.delante-de`, target: 'delante de', german: 'vor (räumlich)', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'Estoy delante del museo.', german: 'Ich bin vor dem Museum.' } },
    { id: `${L}.v.detras-de`, target: 'detrás de', german: 'hinter', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'El parque está detrás del supermercado.', german: 'Der Park liegt hinter dem Supermarkt.' } },
    { id: `${L}.v.cerca-de`, target: 'cerca de', german: 'in der Nähe von, nah bei', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'Mi casa está cerca de la playa.', german: 'Mein Haus liegt nah am Strand.' } },
    { id: `${L}.v.lejos-de`, target: 'lejos de', german: 'weit weg von', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'El museo está lejos de aquí.', german: 'Das Museum ist weit weg von hier.' } },
    { id: `${L}.v.entre`, target: 'entre … y …', german: 'zwischen … und …', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'La farmacia está entre el banco y el supermercado.', german: 'Die Apotheke liegt zwischen der Bank und dem Supermarkt.' } },
    { id: `${L}.v.a-la-derecha-de`, target: 'a la derecha de', german: 'rechts von', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'El banco está a la derecha del museo.', german: 'Die Bank ist rechts vom Museum.' } },
    { id: `${L}.v.a-la-izquierda-de`, target: 'a la izquierda de', german: 'links von', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'El parque está a la izquierda de la estación.', german: 'Der Park liegt links vom Bahnhof.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        '**Wiederholung – hay oder está?**\n- `hay` sagt, **ob es etwas gibt**. Danach steht ein unbestimmter Artikel, eine Zahl oder gar kein Artikel: `Hay un banco en la plaza.` – `Hay dos farmacias.` `hay` bleibt immer gleich, auch im Plural.\n- `estar` sagt, **wo sich etwas Bestimmtes befindet**. Davor steht ein bestimmter Artikel, ein Name oder mi/tu …: `El banco está en la plaza.` – `Los bancos están en el centro.`',
    },
    {
      type: 'table',
      title: 'Ortsangaben (Präpositionen des Ortes)',
      headers: ['Spanisch', 'Deutsch', 'Beispiel'],
      rows: [
        ['al lado de', 'neben', 'al lado de la farmacia'],
        ['enfrente de', 'gegenüber (von)', 'enfrente del museo'],
        ['delante de', 'vor', 'delante de la estación'],
        ['detrás de', 'hinter', 'detrás del parque'],
        ['cerca de', 'in der Nähe von', 'cerca del centro'],
        ['lejos de', 'weit weg von', 'lejos de la playa'],
        ['entre … y …', 'zwischen … und …', 'entre el banco y el museo'],
        ['a la derecha de', 'rechts von', 'a la derecha del supermercado'],
        ['a la izquierda de', 'links von', 'a la izquierda de la farmacia'],
        ['en', 'in, an, auf', 'en la plaza, en el centro'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'La farmacia', role: 'subject' },
        { text: ' ' },
        { text: 'está', role: 'verb' },
        { text: ' ' },
        { text: 'al lado del', role: 'preposition' },
        { text: ' ' },
        { text: 'banco', role: 'noun' },
        { text: '.' },
      ],
      german: 'Die Apotheke ist neben der Bank.',
    },
    {
      type: 'tip',
      md:
        'Merksatz: **Nur `el` verschmilzt.** `a + el = al`, `de + el = del` – das ist Pflicht, nicht Umgangssprache: `al lado del banco`, `Voy al centro.` Mit `la`, `los`, `las` bleibt alles getrennt: `al lado de la plaza`, `cerca de los bancos`.',
    },
    {
      type: 'compare',
      target: 'El museo está enfrente del parque.',
      german: 'Das Museum liegt gegenüber vom Park.',
      md:
        'Vorsicht, falscher Freund: `enfrente de` heißt **gegenüber** (auf der anderen Seite), nicht „vor“. „Vor dem Museum“ ist `delante del museo`. Und wo das Deutsche „liegt“ oder „befindet sich“ sagt, reicht auf Spanisch ein einfaches `está`.',
    },
    {
      type: 'mistake',
      wrong: 'El banco hay en la plaza.',
      right: 'El banco está en la plaza.',
      why:
        'Es geht um **eine bestimmte** Bank (`el banco`) und darum, **wo** sie ist – dafür brauchst du `estar`. `hay` steht nie mit bestimmtem Subjekt davor. Richtig ist entweder `El banco está en la plaza.` oder `Hay un banco en la plaza.` (Es gibt eine Bank am Platz.)',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika fragt man nach Orten sehr oft mit `quedar`: `¿Dónde queda el banco?` – `Queda enfrente de la plaza.` Das bedeutet dasselbe wie `¿Dónde está …?` und wird auch in Spanien verstanden. Statt `enfrente de` hörst du dort außerdem oft `frente a`: `frente a la plaza`.',
    },
    { type: 'audio', text: '¿Hay un supermercado cerca de aquí? – Sí, hay uno al lado del banco.', label: 'Frage und Antwort' },
  ],
  examples: [
    {
      target: 'Hay un parque cerca de mi casa.',
      german: 'In der Nähe meines Hauses gibt es einen Park.',
      parts: [
        { text: 'Hay', role: 'verb' },
        { text: ' ' },
        { text: 'un parque', role: 'object' },
        { text: ' ' },
        { text: 'cerca de', role: 'preposition' },
        { text: ' ' },
        { text: 'mi casa', role: 'noun' },
        { text: '.' },
      ],
    },
    {
      target: 'El parque está cerca de mi casa.',
      german: 'Der Park ist in der Nähe meines Hauses.',
      parts: [
        { text: 'El parque', role: 'subject' },
        { text: ' ' },
        { text: 'está', role: 'verb' },
        { text: ' ' },
        { text: 'cerca de', role: 'preposition' },
        { text: ' ' },
        { text: 'mi casa', role: 'noun' },
        { text: '.' },
      ],
      note: 'Vergleiche mit dem Satz davor: `hay un parque` = es gibt einen Park; `el parque está` = der (bestimmte) Park befindet sich …',
    },
    {
      target: 'La farmacia está entre el banco y el supermercado.',
      german: 'Die Apotheke liegt zwischen der Bank und dem Supermarkt.',
      parts: [
        { text: 'La farmacia', role: 'subject' },
        { text: ' ' },
        { text: 'está', role: 'verb' },
        { text: ' ' },
        { text: 'entre', role: 'preposition' },
        { text: ' ' },
        { text: 'el banco', role: 'noun' },
        { text: ' y ' },
        { text: 'el supermercado', role: 'noun' },
        { text: '.' },
      ],
    },
    {
      target: '¿Dónde está la estación? – Está lejos del centro.',
      german: 'Wo ist der Bahnhof? – Er liegt weit weg vom Zentrum.',
      note: '`del` = `de` + `el`. Bei `la estación` bleibt es getrennt: `lejos de la estación`.',
    },
    {
      target: 'Estoy delante del museo.',
      german: 'Ich bin vor dem Museum.',
      note: '`delante de` = vor. Mit estar sagst du auch, wo **du** gerade bist.',
    },
    {
      target: 'El banco está a la derecha del museo.',
      german: 'Die Bank ist rechts vom Museum.',
    },
    {
      target: '¿Hay farmacias en el centro? – Sí, hay dos.',
      german: 'Gibt es Apotheken im Zentrum? – Ja, zwei.',
      note: '`hay` bleibt auch im Plural unverändert.',
    },
    {
      target: '¿Dónde queda el museo? – Queda frente a la plaza.',
      german: 'Wo ist das Museum? – Es liegt gegenüber vom Platz.',
      variant: 'es-LA',
      note: '`quedar` und `frente a` sind in Lateinamerika sehr verbreitet.',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: HAY,
      difficulty: 1,
      instruction: 'Ordne jedem Bild den passenden Ort zu.',
      pairs: [
        { emoji: '🏦', word: 'el banco' },
        { emoji: '💊', word: 'la farmacia' },
        { emoji: '🛒', word: 'el supermercado' },
        { emoji: '🚉', word: 'la estación' },
        { emoji: '🌳', word: 'el parque' },
        { emoji: '🏛️', word: 'el museo' },
      ],
      feedback: {
        rule: 'Lerne Orte immer mit Artikel: `el banco`, `la farmacia`, `la estación` (Wörter auf -ción sind weiblich).',
        why: '`el banco` ist die Bank zum Geldabheben; eine Sitzbank heißt auch `banco`, aber hier geht es um das Geldinstitut. `la estación` ist der Bahnhof, nicht die Tankstelle.',
        avoid: 'Stell dir deinen eigenen Weg durch die Stadt vor und benenne jeden Ort laut mit Artikel.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: HAY,
      difficulty: 1,
      prompt: 'Welche Form passt? `¿Dónde ___ el supermercado?`',
      options: [
        { text: 'está' },
        { text: 'hay', why: 'Nach `hay` steht kein bestimmter Artikel. Du fragst hier nach **dem** Supermarkt – also nach dem Ort eines bestimmten Supermarkts → `está`.' },
        { text: 'es', why: 'Den Ort von Gebäuden, Plätzen und Personen drückst du mit `estar` aus, nicht mit ser.' },
        { text: 'están', why: '`están` ist Plural. `el supermercado` ist Singular → `está`.' },
      ],
      answer: 0,
      feedback: {
        rule: '`¿Dónde está + bestimmter Artikel …?` fragt nach dem Ort von etwas Bestimmtem. `¿Hay un …?` fragt, ob es so etwas überhaupt gibt.',
        why: 'Wegen `el` ist der Supermarkt schon bekannt/bestimmt – dann ist `hay` ausgeschlossen.',
        avoid: 'Schau auf den Artikel nach der Lücke: el/la/los/las → `está/están`; un/una/Zahl → `hay`.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: PREP,
      difficulty: 2,
      instruction: 'Setze de oder del ein.',
      sentence: 'La farmacia está al lado ___ banco y enfrente ___ la plaza.',
      answers: [['del'], ['de']],
      bank: ['del', 'de', 'al', 'a'],
      german: 'Die Apotheke ist neben der Bank und gegenüber vom Platz.',
      feedback: {
        rule: '`de + el = del` (`al lado del banco`). Vor `la`, `los`, `las` bleibt `de` allein: `enfrente de la plaza`.',
        why: '`de el banco` ist falsch – die Verschmelzung ist Pflicht. Umgekehrt gibt es kein „dela“: `de la plaza` bleibt getrennt.',
        avoid: 'Frag dich: Folgt `el`? Dann verschmilzt es zu `del`. Sonst nicht.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: PREP,
      difficulty: 2,
      instruction: 'Ordne jeder Ortsangabe die deutsche Bedeutung zu.',
      pairs: [
        { left: 'al lado de', right: 'neben' },
        { left: 'enfrente de', right: 'gegenüber' },
        { left: 'delante de', right: 'vor' },
        { left: 'detrás de', right: 'hinter' },
        { left: 'lejos de', right: 'weit weg von' },
        { left: 'entre', right: 'zwischen' },
      ],
      feedback: {
        rule: 'Fast alle Ortsangaben enden auf `de`: al lado de, enfrente de, delante de, detrás de, cerca de, lejos de. Nur `entre` und `en` kommen ohne aus.',
        why: 'Am häufigsten werden `enfrente de` (gegenüber) und `delante de` (vor) verwechselt, weil „en frente“ nach „vorne“ klingt.',
        avoid: 'Merkbild: `enfrente` – Front an Front, man steht sich gegenüber. `delante` – direkt davor.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: BOTH,
      difficulty: 2,
      audio: 'Hay un banco enfrente de la estación y una farmacia al lado del parque.',
      question: 'Was liegt gegenüber vom Bahnhof?',
      options: ['eine Bank', 'eine Apotheke', 'ein Park', 'ein Supermarkt'],
      answer: 0,
      feedback: {
        rule: '`enfrente de la estación` = gegenüber vom Bahnhof; dort gibt es `un banco`. Die Apotheke liegt `al lado del parque` (neben dem Park).',
        why: 'Wer „Apotheke“ wählt, hat die zweite Satzhälfte gehört – dort geht es aber um den Park, nicht um den Bahnhof.',
        avoid: 'Achte auf die Reihenfolge: Ort (un banco) → Ortsangabe (enfrente de) → Bezugspunkt (la estación).',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: HAY,
      difficulty: 2,
      instruction: 'Bilde die Frage „Gibt es hier in der Nähe einen Supermarkt?“.',
      tokens: ['¿Hay', 'un', 'supermercado', 'cerca', 'de', 'aquí?'],
      extra: ['está', 'del'],
      alternatives: [['¿Hay', 'cerca', 'de', 'aquí', 'un', 'supermercado?']],
      german: 'Gibt es hier in der Nähe einen Supermarkt?',
      feedback: {
        rule: 'Fragst du, **ob es** etwas gibt, beginnst du mit `¿Hay …?` + unbestimmtem Artikel: `¿Hay un supermercado cerca de aquí?`',
        why: '`está` passt nicht zu `un supermercado`, und `del` ist falsch, weil vor `aquí` kein Artikel `el` steht.',
        avoid: 'Lerne `¿Hay un/una … cerca de aquí?` als festen Fragebaustein – er funktioniert für jeden Ort.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: BOTH,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Die Apotheke liegt neben dem Bahnhof.',
      answers: [
        'La farmacia está al lado de la estación.',
        'La farmacia queda al lado de la estación.',
        'La farmacia se encuentra al lado de la estación.',
      ],
      feedback: {
        rule: 'Bestimmter Ort → `estar`: `La farmacia está …`. „neben“ = `al lado de`; `la estación` ist weiblich → `de la estación`.',
        why: '„liegt“ verleitet zu einem eigenen Verb – auf Spanisch genügt `está`. `al lado del estación` ist falsch, weil `estación` weiblich ist (kein `el`, also kein `del`).',
        avoid: 'Erst das Geschlecht des Bezugsworts prüfen: el → del, la → de la.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: PREP,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'El museo está cerca de el parque.',
      answers: ['El museo está cerca del parque.'],
      german: 'Das Museum liegt in der Nähe des Parks.',
      feedback: {
        rule: '`de + el` verschmilzt immer zu `del`: `cerca del parque`.',
        why: 'Getrennt bleibt es nur vor dem Pronomen `él` (er, mit Akzent: `cerca de él`) und vor Namen wie `El Salvador`. Vor dem Artikel `el` ist `de el` immer ein Fehler.',
        avoid: 'Lies den Satz laut: „cerca de el“ stolpert – „cerca del“ fließt. Genauso `a el` → `al`.',
      },
    },
  ],
  pronunciation: ['es.p.link.esta-en-el-centro', 'es.p.ll.calle', 'es.p.stress.ciudad'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['speaking', 'grammar'],
      topicIds: HAY,
      difficulty: 2,
      scenario: 'Du bist in Sevilla unterwegs und brauchst eine Apotheke. Du weißt nicht, ob es hier in der Nähe überhaupt eine gibt. Was fragst du eine Passantin?',
      options: [
        { text: '¿Hay una farmacia cerca de aquí?' },
        { text: '¿Dónde hay la farmacia?', why: 'Nach `hay` steht kein bestimmter Artikel. Entweder `¿Dónde hay una farmacia?` oder `¿Dónde está la farmacia?`.' },
        { text: '¿Está una farmacia cerca de aquí?', why: '`estar` steht mit etwas Bestimmtem. Fragst du, ob es **eine** Apotheke gibt, brauchst du `hay`.' },
        { text: '¿Es una farmacia cerca de aquí?', why: 'Das hieße „Ist das eine Apotheke hier in der Nähe?“ – mit ser fragst du nicht nach der Existenz eines Ortes.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Ob es etwas gibt → `¿Hay un/una …?`. Wo etwas Bestimmtes ist → `¿Dónde está el/la …?`',
        why: 'Da du keine bestimmte Apotheke kennst, ist `hay` + `una` die natürliche Frage.',
        avoid: 'Merke das Paar: `¿Hay una farmacia cerca?` – `Sí, la farmacia está al lado del banco.`',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: BOTH,
      difficulty: 2,
      prompt: 'Beschreibe dein Viertel (`mi barrio`) in 3–4 Sätzen: Was gibt es dort (hay)? Und wo liegen die Orte (está + Ortsangabe)?',
      requirements: [
        { pattern: '\\bhay\\b', hint: 'mindestens einmal „hay“ (es gibt)' },
        { pattern: '\\best[aá]n?\\b', hint: 'mindestens einmal „está“ oder „están“ für den Ort' },
        { pattern: '(al lado|enfrente|delante|detr[aá]s|cerca|lejos|entre|a la (derecha|izquierda))', hint: 'mindestens eine Ortsangabe (al lado de, cerca de, entre …)' },
      ],
      samples: [
        'En mi barrio hay un supermercado, una farmacia y un parque. La farmacia está al lado del supermercado. El parque está detrás de mi casa y la estación está cerca del centro.',
      ],
      minWords: 15,
      feedback: {
        rule: '`Hay un/una …` = es gibt; `El/La … está + Ortsangabe` = befindet sich. Denk an `del` und `al`.',
        why: 'Typische Fehler sind `el parque hay …` statt `el parque está …` und `de el` statt `del`.',
        avoid: 'Prüfe jeden Satz: Steht vor dem Ort `un/una`? → hay. Steht `el/la`? → está.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: PREP,
      difficulty: 2,
      prompt: 'Erklär laut, wo dein Supermarkt oder dein Lieblingscafé liegt – mit mindestens zwei Ortsangaben.',
      keywords: ['está', 'hay', 'al lado', 'enfrente', 'cerca', 'lejos', 'delante', 'detrás', 'entre', 'derecha', 'izquierda'],
      minMatch: 3,
      sample: 'El supermercado está cerca de mi casa, al lado del banco. Enfrente hay un parque.',
      feedback: {
        rule: 'Ort + `está` + Ortsangabe: `El supermercado está al lado del banco.`',
        why: 'Findet die Spracherkennung zu wenige Schlüsselwörter, fehlen meist `está` oder die Ortsangabe.',
        avoid: 'Sprich die Ortsangabe als einen Block: `al-la-do-del`, `cer-ca-de`. Das d zwischen Vokalen ist ganz weich.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: BOTH,
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Unterhalte dich über eure Viertel: Frag, was es dort gibt (¿Hay …?) und wo es liegt (¿Dónde está …?), und beschreibe dein eigenes Viertel.',
      turns: 4,
      feedback: {
        rule: '`¿Hay un supermercado en tu barrio?` – `Sí, está al lado de …`',
        why: 'Im freien Gespräch rutscht leicht `hay` mit bestimmtem Artikel heraus – achte auf die Unterscheidung.',
        avoid: 'Leg dir vorher zwei Sätze über dein Viertel zurecht: einen mit hay, einen mit está.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.ir-a'],
      difficulty: 1,
      prompt: 'Wiederholung ir a + Infinitiv: `El sábado nosotros ___ ir al museo.`',
      options: [
        { text: 'vamos a' },
        { text: 'vamos', why: 'Zwischen der ir-Form und dem Infinitiv fehlt das `a`: `vamos a ir`.' },
        { text: 'van a', why: '`van` gehört zu ellos/ellas/ustedes. Subjekt ist aber `nosotros`.' },
        { text: 'estamos a', why: 'Die nahe Zukunft bildest du mit `ir a`, nicht mit estar.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Nahe Zukunft: `ir` (konjugiert) + `a` + Infinitiv: `vamos a ir`, `voy a comer`.',
        why: 'Das `a` ist fester Bestandteil der Konstruktion und darf nie fehlen.',
        avoid: 'Denk an `al`: `vamos a ir al museo` – einmal `a` vor dem Infinitiv, einmal `al` = a + el vor dem Ort.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.estar'],
      difficulty: 1,
      verb: 'estar',
      tense: 'Präsens',
      person: 'ellos / ellas',
      sentence: 'Los bancos ___ en el centro.',
      answers: ['están'],
      feedback: {
        rule: 'estar im Plural (3. Person): `están`. Singular: `está`.',
        why: '`los bancos` ist Plural – `está` wäre Singular, `hay` passt nicht zum bestimmten Artikel.',
        avoid: 'Endet das Subjekt auf -s, braucht auch das Verb die Pluralform: los bancos **están**.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading'],
      topicIds: ['es.g.gustar', 'es.g.hay'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'Me gusta mi barrio porque hay dos parques.',
      answers: [
        'Mir gefällt mein Viertel, weil es zwei Parks gibt.',
        'Mein Viertel gefällt mir, weil es zwei Parks gibt.',
        'Ich mag mein Viertel, weil es zwei Parks gibt.',
        'Mir gefällt mein Viertel, weil es dort zwei Parks gibt.',
        'Mein Viertel gefällt mir, weil es dort zwei Parks gibt.',
        'Ich mag mein Viertel, weil es dort zwei Parks gibt.',
        'Mir gefällt mein Stadtviertel, weil es zwei Parks gibt.',
        'Ich mag mein Stadtviertel, weil es zwei Parks gibt.',
        'Mir gefällt mein Viertel, denn es gibt zwei Parks.',
        'Ich mag mein Viertel, denn es gibt zwei Parks.',
        'Mein Viertel gefällt mir, denn es gibt zwei Parks.',
      ],
      feedback: {
        rule: '`Me gusta …` = mir gefällt …; `hay dos parques` = es gibt zwei Parks; `el barrio` = das Viertel.',
        why: '`hay` wird oft mit „habe“ verwechselt – es heißt aber immer „es gibt“.',
        avoid: 'Übersetze `hay` konsequent mit „es gibt“ und stelle den Satz danach ins natürliche Deutsch um.',
      },
    },
  ],
};

export default lesson;
