import type { Lesson } from '../../types';

const L = 'es.a1.l03';
const R = ['es.g.reflexive'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c1',
  order: 3,
  title: 'Mein Tag – Uhrzeit & reflexive Verben',
  subtitle: 'Tagesablauf beschreiben: me levanto, me ducho …',
  icon: '⏰',
  minutes: 12,
  goal:
    'Du lernst, die **Uhrzeit** zu sagen und zu erfragen (`¿Qué hora es?`) und deinen **Tagesablauf** mit reflexiven Verben zu beschreiben: `Me levanto a las siete y me ducho.`',
  canDo: [
    'Ich kann nach der Uhrzeit fragen und sie angeben.',
    'Ich kann sagen, um wie viel Uhr ich etwas mache.',
    'Ich kann reflexive Verben wie levantarse und ducharse im Präsens verwenden.',
    'Ich kann meinen typischen Tag in einfachen Sätzen beschreiben.',
  ],
  topicIds: R,
  vocab: [
    { id: `${L}.v.levantarse`, target: 'levantarse', german: 'aufstehen', pos: 'verb', emoji: '⏰', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Me levanto a las siete.', german: 'Ich stehe um sieben auf.' } },
    { id: `${L}.v.despertarse`, target: 'despertarse', german: 'aufwachen (ich: me despierto)', pos: 'verb', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Me despierto a las seis y media.', german: 'Ich wache um halb sieben auf.' } },
    { id: `${L}.v.ducharse`, target: 'ducharse', german: 'duschen', pos: 'verb', emoji: '🚿', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Me ducho por la mañana.', german: 'Ich dusche morgens.' } },
    { id: `${L}.v.lavarse-los-dientes`, target: 'lavarse los dientes', german: 'sich die Zähne putzen', pos: 'phrase', emoji: '🪥', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Me lavo los dientes.', german: 'Ich putze mir die Zähne.' } },
    { id: `${L}.v.acostarse`, target: 'acostarse', german: 'ins Bett gehen (ich: me acuesto)', pos: 'verb', emoji: '🛏️', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Me acuesto a las once.', german: 'Ich gehe um elf ins Bett.' } },
    { id: `${L}.v.desayunar`, target: 'desayunar', german: 'frühstücken', pos: 'verb', emoji: '🥐', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Desayuno a las ocho.', german: 'Ich frühstücke um acht.' } },
    { id: `${L}.v.cenar`, target: 'cenar', german: 'zu Abend essen', pos: 'verb', emoji: '🍽️', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Cenamos a las nueve.', german: 'Wir essen um neun zu Abend.' } },
    { id: `${L}.v.hora`, target: 'la hora', german: 'die Uhrzeit / die Stunde', pos: 'noun', gender: 'f', plural: 'las horas', emoji: '🕐', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: '¿Qué hora es?', german: 'Wie spät ist es?' } },
    { id: `${L}.v.la-manana`, target: 'la mañana', german: 'der Morgen / der Vormittag', pos: 'noun', gender: 'f', emoji: '🌅', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: 'a las ocho de la mañana', german: 'um acht Uhr morgens' } },
    { id: `${L}.v.la-tarde`, target: 'la tarde', german: 'der Nachmittag / der frühe Abend', pos: 'noun', gender: 'f', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: 'a las cinco de la tarde', german: 'um fünf Uhr nachmittags' } },
    { id: `${L}.v.la-noche`, target: 'la noche', german: 'der Abend / die Nacht', pos: 'noun', gender: 'f', emoji: '🌙', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: 'a las diez de la noche', german: 'um zehn Uhr abends' } },
    { id: `${L}.v.temprano`, target: 'temprano', german: 'früh', pos: 'adv', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: 'Me levanto temprano.', german: 'Ich stehe früh auf.' } },
    { id: `${L}.v.tarde-spaet`, target: 'tarde', german: 'spät', pos: 'adv', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: 'Me acuesto tarde.', german: 'Ich gehe spät ins Bett.' } },
    { id: `${L}.v.y-media`, target: 'y media', german: 'halb (… Uhr dreißig)', pos: 'phrase', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: 'Son las dos y media.', german: 'Es ist halb drei.' } },
    { id: `${L}.v.y-cuarto`, target: 'y cuarto', german: 'Viertel nach', pos: 'phrase', field: 'Uhrzeit', stageId: 'a1', lessonId: L, example: { target: 'Es la una y cuarto.', german: 'Es ist Viertel nach eins.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        '**Uhrzeit:** Gefragt wird mit `¿Qué hora es?`. Bei 1 Uhr steht der Singular – `Es la una.` –, ab 2 Uhr der Plural – `Son las dos.` Der Artikel ist weiblich, weil `la hora` gemeint ist.\nMinuten kommen mit `y` dazu (`Son las tres y diez`), vor der vollen Stunde mit `menos` (`Son las cuatro menos diez`). „Um … Uhr“ heißt `a las …` bzw. `a la una`.',
    },
    {
      type: 'table',
      title: 'Uhrzeiten',
      headers: ['Uhr', 'Spanisch', 'Deutsch'],
      rows: [
        ['1:00', 'Es la una.', 'Es ist eins.'],
        ['2:00', 'Son las dos.', 'Es ist zwei.'],
        ['3:15', 'Son las tres y cuarto.', 'Es ist Viertel nach drei.'],
        ['4:30', 'Son las cuatro y media.', 'Es ist halb fünf.'],
        ['5:45', 'Son las seis menos cuarto.', 'Es ist Viertel vor sechs.'],
        ['7:00 morgens', 'a las siete de la mañana', 'um sieben Uhr morgens'],
        ['21:00', 'a las nueve de la noche', 'um neun Uhr abends'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Son las cinco y media. (für 4:30)',
      right: 'Son las cuatro y media.',
      why: 'Das deutsche „halb fünf“ zählt zur **nächsten** Stunde hin. Spanisch geht von der **vergangenen** Stunde aus: 4:30 = `las cuatro y media` („vier und halb“). Rechne bei „halb“ also immer eine Stunde zurück.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Mexiko und weiten Teilen Lateinamerikas sagt man für „Viertel vor“ oder „zehn vor“ oft `Es un cuarto para las seis` bzw. `Son diez para las ocho`. Die Form mit `menos` wird trotzdem überall verstanden.',
    },
    {
      type: 'text',
      md:
        '**Reflexive Verben** erkennst du im Wörterbuch am angehängten `-se`: `levantarse` (aufstehen), `ducharse` (duschen). Beim Konjugieren wird aus `se` das passende Pronomen, und es steht **vor** dem Verb: `me levanto`, `te levantas`, `se levanta` … Eines kennst du schon: `me llamo` von `llamarse`.\n`despertarse` und `acostarse` ändern zusätzlich den Stammvokal – wie tener: `me despierto`, `me acuesto`, aber `nos despertamos`, `nos acostamos`. Lerne diese Formen vorerst als feste Wendungen.',
    },
    {
      type: 'conjugation',
      verb: 'levantarse',
      translation: 'aufstehen',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'me levanto', ending: 'o' },
        { person: 'tú', form: 'te levantas', ending: 'as' },
        { person: 'él / ella / usted', form: 'se levanta', ending: 'a' },
        { person: 'nosotros / nosotras', form: 'nos levantamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'os levantáis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'se levantan', ending: 'an' },
      ],
    },
    {
      type: 'compare',
      target: 'Me levanto a las siete.',
      german: 'Ich stehe um sieben Uhr auf.',
      md: 'Viele spanische Verben sind reflexiv, wo das Deutsche es nicht ist: `levantarse` = aufstehen, `despertarse` = aufwachen, `acostarse` = ins Bett gehen. Bei „ich dusche (mich)“ = `me ducho` sind sich beide Sprachen einig.',
    },
    {
      type: 'mistake',
      wrong: 'Levanto a las siete.',
      right: 'Me levanto a las siete.',
      why: 'Ohne `me` heißt `levantar` „etwas hochheben“: `Levanto la mano` = „Ich hebe die Hand“. Für „ich stehe auf“ brauchst du das Reflexivpronomen. Bei der Verneinung steht `no` **davor**: `No me levanto temprano.`',
    },
  ],
  examples: [
    {
      target: 'Son las ocho y media.',
      german: 'Es ist halb neun.',
      literal: 'Es sind die acht und halb.',
      parts: [
        { text: 'Son', role: 'verb' },
        { text: ' ' },
        { text: 'las ocho y media', role: 'other' },
        { text: '.' },
      ],
    },
    {
      target: 'Es la una y cuarto.',
      german: 'Es ist Viertel nach eins.',
      note: 'Bei eins steht der Singular: `es la una`.',
    },
    {
      target: 'Me levanto a las siete.',
      german: 'Ich stehe um sieben auf.',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' ' },
        { text: 'levanto', role: 'verb' },
        { text: ' ' },
        { text: 'a las siete', role: 'adverb' },
        { text: '.' },
      ],
    },
    {
      target: 'Mi hermana se ducha por la mañana.',
      german: 'Meine Schwester duscht morgens.',
      parts: [
        { text: 'Mi hermana', role: 'subject' },
        { text: ' ' },
        { text: 'se', role: 'pronoun' },
        { text: ' ' },
        { text: 'ducha', role: 'verb' },
        { text: ' ' },
        { text: 'por la mañana', role: 'adverb' },
        { text: '.' },
      ],
    },
    {
      target: '¿A qué hora te acuestas?',
      german: 'Um wie viel Uhr gehst du ins Bett?',
      note: '`¿A qué hora …?` fragt nach dem Zeitpunkt: „Um wie viel Uhr …?“',
    },
    {
      target: 'Nosotros no nos levantamos temprano.',
      german: 'Wir stehen nicht früh auf.',
      note: '`no` steht vor dem Reflexivpronomen: `no nos levantamos`.',
    },
    {
      target: 'Desayuno a las ocho y ceno a las nueve de la noche.',
      german: 'Ich frühstücke um acht und esse um neun Uhr abends zu Abend.',
      note: 'In Spanien isst man oft erst um 21 oder 22 Uhr zu Abend – deutlich später als in Deutschland.',
    },
    {
      target: 'Son veinte para las ocho.',
      german: 'Es ist zwanzig vor acht.',
      variant: 'es-LA',
      note: 'Typisch für Mexiko und Mittelamerika. In Spanien: `Son las ocho menos veinte.`',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary', 'grammar'],
      topicIds: R,
      difficulty: 1,
      instruction: 'Ordne jede Uhrzeit dem passenden Satz zu.',
      pairs: [
        { left: '1:00', right: 'Es la una.' },
        { left: '2:00', right: 'Son las dos.' },
        { left: '3:30', right: 'Son las tres y media.' },
        { left: '6:15', right: 'Son las seis y cuarto.' },
        { left: '8:45', right: 'Son las nueve menos cuarto.' },
      ],
      feedback: {
        rule: '1 Uhr: `Es la una`; sonst `Son las …`. `y cuarto` = Viertel nach, `y media` = halb (nach der Stunde), `menos cuarto` = Viertel vor.',
        why: 'Bei 3:30 denken Deutschsprachige an „halb vier“ und greifen zur Vier. Spanisch sagt aber `las tres y media`.',
        avoid: 'Lies die Uhr so, wie sie steht: Die erste Zahl (3) ist die spanische Stunde, dann kommt `y …`.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: R,
      difficulty: 1,
      prompt: 'Welches Pronomen fehlt? `Tú ___ levantas a las seis.`',
      options: [
        { text: 'te' },
        { text: 'se', why: '`se` gehört zu él/ella/usted und ellos/ellas/ustedes – nicht zu tú.' },
        { text: 'me', why: '`me` gehört zu yo: `me levanto`.' },
        { text: 'tu', why: '`tu` ist der Begleiter „dein“, kein Reflexivpronomen.' },
      ],
      answer: 0,
      feedback: {
        rule: 'yo → me · tú → te · él/ella/usted → se · nosotros → nos · (vosotros → os) · ellos/ustedes → se.',
        why: 'Das Pronomen muss zur Person der Verbform passen: `levantas` ist die tú-Form → `te`.',
        avoid: 'Pronomen und Verbendung gehören zusammen: te …-as, me …-o, se …-a / -an.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: R,
      difficulty: 1,
      instruction: 'Was passiert auf dem Bild?',
      pairs: [
        { emoji: '🚿', word: 'ducharse' },
        { emoji: '🛏️', word: 'acostarse' },
        { emoji: '🪥', word: 'lavarse los dientes' },
        { emoji: '🥐', word: 'desayunar' },
        { emoji: '🍽️', word: 'cenar' },
      ],
      feedback: {
        rule: 'Tagesablauf: `desayunar` (frühstücken), `ducharse` (duschen), `lavarse los dientes` (Zähne putzen), `cenar` (zu Abend essen), `acostarse` (ins Bett gehen).',
        why: '`desayunar` und `cenar` sind nicht reflexiv – das -se fehlt im Infinitiv.',
        avoid: 'Lerne die Verben in der Reihenfolge deines Tages – so bleiben sie leichter hängen.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'listening',
      skills: ['listening'],
      topicIds: R,
      difficulty: 2,
      audio: 'Me levanto a las siete menos cuarto y desayuno a las siete y media.',
      question: 'Wann steht die Person auf?',
      options: ['um Viertel vor sieben', 'um Viertel nach sieben', 'um halb sieben', 'um halb acht'],
      answer: 0,
      feedback: {
        rule: '`las siete menos cuarto` = 6:45 = Viertel vor sieben. `las siete y media` (7:30) ist die Frühstückszeit.',
        why: '„halb acht“ ist 7:30 – das ist im Satz der Zeitpunkt fürs Frühstück, nicht fürs Aufstehen.',
        avoid: 'Achte auf das Verb vor der Zeit: `me levanto a las …` = Aufstehen, `desayuno a las …` = Frühstück.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: R,
      difficulty: 2,
      instruction: 'Setze die passenden Reflexivpronomen ein.',
      sentence: 'Mis padres ___ levantan temprano, pero yo ___ levanto tarde.',
      answers: [['se'], ['me']],
      bank: ['me', 'te', 'se', 'nos'],
      german: 'Meine Eltern stehen früh auf, aber ich stehe spät auf.',
      feedback: {
        rule: '`mis padres` = ellos → `se levantan`; `yo` → `me levanto`.',
        why: '`se` steht für die 3. Person (Singular und Plural) – auch wenn es mehrere Personen sind.',
        avoid: 'Schau auf das Subjekt: Wer steht auf? Eltern = ellos → se; ich → me.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: R,
      difficulty: 2,
      verb: 'ducharse',
      tense: 'Präsens',
      person: 'nosotros',
      sentence: '___ por la mañana.',
      answers: ['nos duchamos', 'nosotros nos duchamos', 'nosotras nos duchamos'],
      feedback: {
        rule: 'nosotros: Pronomen `nos` + Verbform auf `-amos` → `nos duchamos`.',
        why: 'Ohne `nos` fehlt der reflexive Teil; „nos duchemos“ ist eine andere Form (Subjuntivo).',
        avoid: 'Reflexiv = zwei Teile: Pronomen + konjugiertes Verb. Beide müssen zur Person passen.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'order',
      skills: ['grammar'],
      topicIds: R,
      difficulty: 2,
      instruction: 'Bilde die Frage „Um wie viel Uhr gehst du ins Bett?“.',
      tokens: ['¿A', 'qué', 'hora', 'te', 'acuestas?'],
      extra: ['se'],
      german: 'Um wie viel Uhr gehst du ins Bett?',
      feedback: {
        rule: '`¿A qué hora …?` + Reflexivpronomen + Verb: `te acuestas` (tú).',
        why: '`se` passt nicht zur du-Form `acuestas`. Das `a` gehört an den Anfang: „**Um** wie viel Uhr“.',
        avoid: 'Merke den Frageblock `¿A qué hora …?` als Ganzes.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: R,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Ich stehe um halb acht auf.',
      answers: ['Me levanto a las siete y media.', 'Yo me levanto a las siete y media.'],
      feedback: {
        rule: '„halb acht“ = 7:30 = `las siete y media`. Aufstehen = `levantarse` → `me levanto`.',
        why: 'Die Falle: `a las ocho y media` wäre 8:30. Außerdem braucht „aufstehen“ das Pronomen `me`.',
        avoid: 'Rechne „halb X“ immer in „(X–1) y media“ um: halb acht → siete y media.',
      },
    },
  ],
  pronunciation: ['es.p.h.noche', 'es.p.ny.manana', 'es.p.h.hola'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['reading', 'vocabulary'],
      topicIds: R,
      difficulty: 2,
      scenario: 'Du bist in Madrid und möchtest wissen, wie spät es ist. Du sprichst eine ältere Dame auf der Straße an. Was sagst du?',
      options: [
        { text: 'Perdón, señora, ¿qué hora es?' },
        { text: 'Perdón, señora, ¿a qué hora es?', why: '`¿A qué hora es?` fragt, **um** wie viel Uhr etwas stattfindet – nicht, wie spät es gerade ist.' },
        { text: 'Perdón, señora, ¿qué tiempo es?', why: '`el tiempo` bedeutet Zeit im Sinne von Dauer oder das Wetter. Für die Uhrzeit sagt man `la hora`.' },
        { text: 'Perdón, señora, ¿cuántos años tiene?', why: 'Damit fragst du nach ihrem Alter – ziemlich unpassend auf der Straße!' },
      ],
      answer: 0,
      feedback: {
        rule: 'Uhrzeit erfragen: `¿Qué hora es?` Höflich einleiten mit `Perdón` und `señora` / `señor`.',
        why: '`¿A qué hora …?` fragt nach dem Zeitpunkt eines Ereignisses; `tiempo` ist nicht die Uhrzeit.',
        avoid: 'hora = Uhrzeit, tiempo = Zeit(dauer) / Wetter.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: R,
      difficulty: 2,
      prompt: 'Beschreibe deinen typischen Morgen in 3–4 Sätzen – mit Uhrzeiten.',
      requirements: [
        { pattern: '\\bme (levanto|despierto|ducho|lavo|acuesto)\\b', hint: 'mindestens ein reflexives Verb in der ich-Form (z. B. „me levanto“)' },
        { pattern: '\\ba las? ', hint: 'eine Uhrzeit mit „a la(s) …“' },
        { pattern: '(y media|y cuarto|menos cuarto|de la mañana|de la tarde|de la noche)', hint: 'eine genauere Zeitangabe (y media, y cuarto, menos cuarto oder de la mañana …)' },
      ],
      samples: [
        'Me despierto a las seis y media. Me levanto a las siete menos cuarto y me ducho. Desayuno a las siete y media y trabajo a las ocho y media de la mañana.',
      ],
      minWords: 15,
      feedback: {
        rule: 'Reflexiv: `me levanto`, `me ducho`; Zeit: `a las siete (y media)`.',
        why: 'Typisch sind ein fehlendes `me` (`levanto a las siete`) und die „halb“-Falle (halb acht = siete y media).',
        avoid: 'Schreib zuerst die Uhrzeiten als Zahlen auf und übersetze sie dann bewusst.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: R,
      difficulty: 2,
      prompt: 'Erzähl laut: Wann stehst du auf, wann frühstückst du und wann gehst du ins Bett?',
      keywords: ['me levanto', 'me despierto', 'me ducho', 'desayuno', 'me acuesto', 'a las', 'a la una'],
      minMatch: 3,
      sample: 'Me levanto a las siete, desayuno a las ocho y me acuesto a las once.',
      feedback: {
        rule: 'Tagesablauf in der ich-Form: `me levanto`, `desayuno`, `me acuesto` + `a las …`.',
        why: 'Fehlen Schlüsselwörter, wurde oft das Pronomen `me` verschluckt oder die Uhrzeit ohne `a las` genannt.',
        avoid: 'Sprich das `me` deutlich mit: me le-VAN-to.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: R,
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Sprich über euren Tagesablauf: Frag, wann dein Gegenüber aufsteht und ins Bett geht, und erzähl von deinem Tag mit Uhrzeiten.',
      turns: 4,
      feedback: {
        rule: 'Fragen: `¿A qué hora te levantas?` – Antworten: `Me levanto a las …`.',
        why: 'Im Gespräch wird das Reflexivpronomen leicht vergessen oder falsch gewählt (te/se).',
        avoid: 'Frage mit te, antworte mit me.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.gustar'],
      difficulty: 2,
      prompt: 'Wiederholung gustar: `A mis padres les ___ las películas españolas.`',
      options: [
        { text: 'gustan' },
        { text: 'gusta', why: '`las películas` ist Plural → `gustan`.' },
        { text: 'gustamos', why: 'Das Verb richtet sich nach dem, was gefällt – nie nach der Person.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Das Verb gustar richtet sich nach der Sache: mehrere Filme → `gustan`.',
        why: '`les` zeigt schon, wem es gefällt (den Eltern); das Verb hat damit nichts zu tun.',
        avoid: 'Frag: Was gefällt? → las películas (Plural) → gustan.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.tener'],
      difficulty: 1,
      sentence: 'Mi abuelo ___ ochenta años.',
      answers: [['tiene']],
      german: 'Mein Großvater ist achtzig Jahre alt.',
      feedback: {
        rule: 'Alter mit tener: `mi abuelo` (er) → `tiene … años`.',
        why: '`es ochenta años` ist falsch – das Alter „hat“ man.',
        avoid: 'Denk an „Er hat 80 Jahre“ → `tiene`.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: R,
      difficulty: 2,
      audio: 'Son las diez y media.',
      answers: ['Son las diez y media.', 'Son las 10 y media.'],
      german: 'Es ist halb elf.',
      feedback: {
        rule: 'Ab zwei Uhr: `Son las …`; 10:30 = `las diez y media`.',
        why: 'Wer „halb elf“ denkt, schreibt leicht `once`. Gesprochen wurde aber `diez` (10).',
        avoid: 'Schreib genau, was du hörst – nicht, was du auf Deutsch sagen würdest.',
      },
    },
  ],
};

export default lesson;
