import type { Lesson } from '../../types';

const L = 'es.a1.l02';
const G = ['es.g.gustar'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c1',
  order: 2,
  title: 'Gustar – was dir gefällt',
  subtitle: 'Vorlieben ausdrücken und nachfragen',
  icon: '❤️',
  minutes: 11,
  goal:
    'Du lernst, mit **gustar** über Vorlieben zu sprechen: `Me gusta el café.` Du verstehst, warum sich das Verb nach der **Sache** richtet (`Me gustan los perros.`), fragst andere nach ihren Vorlieben und reagierst mit `a mí también` oder `a mí tampoco`.',
  canDo: [
    'Ich kann sagen, was mir gefällt und was nicht.',
    'Ich kann gusta und gustan richtig unterscheiden.',
    'Ich kann mit ¿Te gusta …? und ¿Le gusta …? nach Vorlieben fragen.',
    'Ich kann auf Vorlieben anderer mit a mí también / a mí tampoco reagieren.',
  ],
  topicIds: G,
  vocab: [
    { id: `${L}.v.gustar`, target: 'gustar', german: 'gefallen / mögen', pos: 'verb', field: 'Vorlieben', stageId: 'a1', lessonId: L, example: { target: 'Me gusta el chocolate.', german: 'Ich mag Schokolade.' } },
    { id: `${L}.v.encantar`, target: 'encantar', german: 'sehr gefallen / lieben', pos: 'verb', field: 'Vorlieben', stageId: 'a1', lessonId: L, example: { target: 'Me encanta la playa.', german: 'Ich liebe den Strand.' } },
    { id: `${L}.v.musica`, target: 'la música', german: 'die Musik', pos: 'noun', gender: 'f', emoji: '🎵', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Me gusta mucho la música.', german: 'Ich mag Musik sehr.' } },
    { id: `${L}.v.deporte`, target: 'el deporte', german: 'der Sport', pos: 'noun', gender: 'm', plural: 'los deportes', emoji: '🏅', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿Te gusta el deporte?', german: 'Magst du Sport?' } },
    { id: `${L}.v.futbol`, target: 'el fútbol', german: 'der Fußball (Sport)', pos: 'noun', gender: 'm', emoji: '⚽', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'No me gusta nada el fútbol.', german: 'Ich mag Fußball überhaupt nicht.' } },
    { id: `${L}.v.pelicula`, target: 'la película', german: 'der Film', pos: 'noun', gender: 'f', plural: 'las películas', emoji: '🎬', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Me gustan las películas españolas.', german: 'Ich mag spanische Filme.' } },
    { id: `${L}.v.chocolate`, target: 'el chocolate', german: 'die Schokolade', pos: 'noun', gender: 'm', emoji: '🍫', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'A mi hija le encanta el chocolate.', german: 'Meine Tochter liebt Schokolade.' } },
    { id: `${L}.v.playa`, target: 'la playa', german: 'der Strand', pos: 'noun', gender: 'f', plural: 'las playas', emoji: '🏖️', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Nos encanta la playa.', german: 'Wir lieben den Strand.' } },
    { id: `${L}.v.leer`, target: 'leer', german: 'lesen', pos: 'verb', emoji: '📖', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Me gusta leer.', german: 'Ich lese gern.' } },
    { id: `${L}.v.bailar`, target: 'bailar', german: 'tanzen', pos: 'verb', emoji: '💃', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿Te gusta bailar?', german: 'Tanzt du gern?' } },
    { id: `${L}.v.cocinar`, target: 'cocinar', german: 'kochen', pos: 'verb', emoji: '🍳', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'A mi padre le gusta cocinar.', german: 'Mein Vater kocht gern.' } },
    { id: `${L}.v.viajar`, target: 'viajar', german: 'reisen', pos: 'verb', emoji: '✈️', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Nos gusta viajar.', german: 'Wir reisen gern.' } },
    { id: `${L}.v.mucho`, target: 'mucho', german: 'sehr / viel', pos: 'adv', field: 'Vorlieben', stageId: 'a1', lessonId: L, example: { target: 'Me gusta mucho.', german: 'Es gefällt mir sehr.' } },
    { id: `${L}.v.tambien`, target: 'también', german: 'auch', pos: 'adv', field: 'Vorlieben', stageId: 'a1', lessonId: L, example: { target: 'A mí también.', german: 'Mir auch. / Ich auch.' } },
    { id: `${L}.v.tampoco`, target: 'tampoco', german: 'auch nicht', pos: 'adv', field: 'Vorlieben', stageId: 'a1', lessonId: L, example: { target: 'A mí tampoco.', german: 'Mir auch nicht. / Ich auch nicht.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Für „mögen“ benutzt Spanisch meist **gustar** – wörtlich „gefallen“. Die Sache, die gefällt, ist das **Subjekt**; die Person steht als kleines Pronomen davor: `Me gusta el café.` = „Mir gefällt der Kaffee.“\nDeshalb richtet sich das Verb nach der Sache: **eine** Sache oder ein Verb → `gusta`, **mehrere** Sachen → `gustan`.',
    },
    {
      type: 'compare',
      target: 'Me gusta el café.',
      german: 'Ich mag Kaffee.',
      md: 'Denk an „**Mir** gefällt der Kaffee“ – genau so ist der spanische Satz gebaut. Beachte auch den Artikel: Allgemeine Vorlieben stehen mit bestimmtem Artikel (`el café`, `la música`), im Deutschen ohne.',
    },
    {
      type: 'table',
      title: 'Wem gefällt es?',
      headers: ['Person', 'eine Sache / Tätigkeit', 'mehrere Sachen', 'Deutsch'],
      rows: [
        ['(a mí)', 'me gusta', 'me gustan', 'mir gefällt / gefallen'],
        ['(a ti)', 'te gusta', 'te gustan', 'dir …'],
        ['(a él / ella / usted)', 'le gusta', 'le gustan', 'ihm / ihr / Ihnen …'],
        ['(a nosotros / nosotras)', 'nos gusta', 'nos gustan', 'uns …'],
        ['(a vosotros / vosotras) – Spanien', 'os gusta', 'os gustan', 'euch …'],
        ['(a ellos / ellas / ustedes)', 'les gusta', 'les gustan', 'ihnen / Ihnen / euch …'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' ' },
        { text: 'gustan', role: 'verb' },
        { text: ' ' },
        { text: 'las películas', role: 'subject' },
        { text: '.' },
      ],
      german: 'Mir gefallen die Filme. → Ich mag Filme.',
    },
    {
      type: 'mistake',
      wrong: 'Yo gusto el chocolate.',
      right: 'Me gusta el chocolate.',
      why: '`yo gusto` hieße „ich gefalle“. Für „ich mag …“ steht die Person als `me` **vor** dem Verb, und das Verb richtet sich nach der Sache (`el chocolate` → `gusta`).',
    },
    {
      type: 'mistake',
      wrong: 'Me gusta los perros.',
      right: 'Me gustan los perros.',
      why: '`los perros` ist Plural → `gustan`. Vor Tätigkeiten (Infinitiven) steht dagegen immer der Singular, auch bei mehreren: `Me gusta leer y bailar.`',
    },
    {
      type: 'tip',
      md:
        'Mit `a mí`, `a ti`, `a mi madre` … betonst du oder stellst klar, **wem** etwas gefällt: `A mi madre le gusta cocinar.`\n- Reagieren: `A mí también.` (mir auch) · `A mí tampoco.` (mir auch nicht)\n- Abstufen: `me gusta mucho` · `me encanta` (ich liebe es) · `no me gusta nada` (gar nicht)\n- `no` steht immer vor dem Pronomen: `No me gusta.`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika fragst du eine Gruppe – auch Freunde – mit **les**: `¿Les gusta bailar?` („Tanzt ihr gern?“). In Spanien heißt es unter Freunden `¿Os gusta bailar?`.',
    },
  ],
  examples: [
    {
      target: 'Me gusta el café.',
      german: 'Ich mag Kaffee.',
      literal: 'Mir gefällt der Kaffee.',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' ' },
        { text: 'gusta', role: 'verb' },
        { text: ' ' },
        { text: 'el café', role: 'subject' },
        { text: '.' },
      ],
    },
    {
      target: 'Me gustan los perros.',
      german: 'Ich mag Hunde.',
      literal: 'Mir gefallen die Hunde.',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' ' },
        { text: 'gustan', role: 'verb' },
        { text: ' ' },
        { text: 'los perros', role: 'subject' },
        { text: '.' },
      ],
    },
    {
      target: '¿Te gusta bailar?',
      german: 'Tanzt du gern?',
      literal: 'Gefällt dir Tanzen?',
      parts: [
        { text: '¿' },
        { text: 'Te', role: 'pronoun' },
        { text: ' ' },
        { text: 'gusta', role: 'verb' },
        { text: ' ' },
        { text: 'bailar', role: 'subject' },
        { text: '?' },
      ],
    },
    {
      target: 'A mi hermana le encanta viajar.',
      german: 'Meine Schwester reist unheimlich gern.',
      literal: 'Meiner Schwester gefällt Reisen sehr.',
      note: '`a mi hermana` sagt, wem es gefällt; `le` wiederholt die Person trotzdem – das ist im Spanischen Pflicht.',
    },
    {
      target: 'No me gusta nada el fútbol.',
      german: 'Ich mag Fußball überhaupt nicht.',
      note: '`no … nada` = gar nicht. Das `no` steht vor dem Pronomen `me`.',
    },
    {
      target: '¿Le gustan las películas españolas?',
      german: 'Mögen Sie spanische Filme?',
      note: 'Höfliche Frage an eine Person mit usted → `le`.',
    },
    { target: '¿Os gusta cocinar?', german: 'Kocht ihr gern?', variant: 'es-ES' },
    { target: '¿Les gusta cocinar?', german: 'Kocht ihr gern?', variant: 'es-LA' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: G,
      difficulty: 1,
      prompt: 'Welche Form passt? `Me ___ los perros.`',
      options: [
        { text: 'gustan' },
        { text: 'gusta', why: '`los perros` ist Plural – das Verb richtet sich nach der Sache, also `gustan`.' },
        { text: 'gusto', why: '`gusto` hieße „ich gefalle“. Die Person steht schon als `me` im Satz.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Das Verb richtet sich nach dem, was gefällt: ein Ding → `gusta`, mehrere Dinge → `gustan`.',
        why: 'Deutschsprachige denken an „ich mag“ und suchen eine Form für „ich“. Bei gustar ist aber die Sache das Subjekt.',
        avoid: 'Übersetze gedanklich: „Mir **gefallen** die Hunde“ – Plural → `gustan`.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: G,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '🎵', word: 'la música' },
        { emoji: '🍫', word: 'el chocolate' },
        { emoji: '⚽', word: 'el fútbol' },
        { emoji: '🏖️', word: 'la playa' },
        { emoji: '🎬', word: 'la película' },
      ],
      feedback: {
        rule: 'Freizeitwörter mit Artikel lernen: `la música`, `el fútbol`, `la playa`, `la película`.',
        why: '`el fútbol` meint den Sport, nicht den Ball (der heißt `el balón`). `la película` ist der Film im Kino oder Fernsehen.',
        avoid: 'Sag die Wörter laut mit einer Vorliebe: `Me gusta la playa.` So verbindest du Wort und Struktur.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: G,
      difficulty: 1,
      instruction: 'Setze das passende Pronomen ein.',
      sentence: '¿A ti ___ gusta el chocolate? – Sí, ___ gusta mucho.',
      answers: [['te'], ['me']],
      bank: ['me', 'te', 'le', 'nos'],
      german: 'Magst du Schokolade? – Ja, ich mag sie sehr.',
      feedback: {
        rule: '`a ti` → `te gusta`; in der Antwort sprichst du über dich → `me gusta`.',
        why: 'Wer in der Antwort `te gusta` wiederholt, sagt „dir gefällt“ – die Perspektive wechselt aber zu „mir“.',
        avoid: 'Frage mit te → Antwort mit me. Wie im Deutschen: „Gefällt es **dir**?“ – „Ja, **mir** gefällt es.“',
      },
    },
    {
      id: `${L}.g04`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: G,
      difficulty: 2,
      instruction: 'Welches Pronomen gehört zu welcher Person?',
      pairs: [
        { left: 'a mí', right: 'me gusta' },
        { left: 'a ti', right: 'te gusta' },
        { left: 'a usted', right: 'le gusta' },
        { left: 'a nosotros', right: 'nos gusta' },
        { left: 'a ellos', right: 'les gusta' },
      ],
      feedback: {
        rule: 'a mí → me · a ti → te · a él/ella/usted → le · a nosotros → nos · (a vosotros → os) · a ellos/ellas/ustedes → les.',
        why: '`usted` steht grammatisch in der 3. Person – deshalb `le`, obwohl man die Person direkt anspricht.',
        avoid: 'Merke: Alles, was mit él/ella/usted zu tun hat, bekommt `le`; im Plural `les`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: G,
      difficulty: 2,
      audio: 'A mi padre le gusta cocinar, pero no le gusta nada el fútbol.',
      question: 'Was stimmt über den Vater?',
      options: [
        'Er kocht gern, mag aber keinen Fußball.',
        'Er mag Fußball, kocht aber nicht gern.',
        'Er mag Kochen und Fußball.',
        'Er mag weder Kochen noch Fußball.',
      ],
      answer: 0,
      feedback: {
        rule: '`le gusta cocinar` = er kocht gern; `no le gusta nada` = er mag es überhaupt nicht.',
        why: 'Das kleine `no` vor `le` dreht die Aussage um – leicht zu überhören, wenn man nur auf die Nomen achtet.',
        avoid: 'Achte beim Hören auf `pero` (aber): Danach kommt oft ein Gegensatz.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: G,
      difficulty: 2,
      instruction: 'Bilde den Satz „Meine Mutter liebt Filme.“',
      tokens: ['A', 'mi', 'madre', 'le', 'encantan', 'las', 'películas.'],
      extra: ['encanta'],
      german: 'Meine Mutter liebt Filme.',
      feedback: {
        rule: '`a` + Person, dann `le`, dann das Verb passend zur Sache: `las películas` → `encantan`.',
        why: '`encanta` wäre Singular – `las películas` ist aber Plural. Und `le` darf trotz `a mi madre` nicht fehlen.',
        avoid: 'encantar funktioniert genau wie gustar: Das Verb richtet sich nach dem, was gefällt.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: G,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Wir reisen gern.',
      answers: ['Nos gusta viajar.', 'A nosotros nos gusta viajar.', 'A nosotras nos gusta viajar.'],
      feedback: {
        rule: '„gern + Verb“ → `gustar` + Infinitiv: `Nos gusta viajar.` Vor einem Infinitiv steht immer `gusta` (Singular).',
        why: '`Viajamos gern` gibt es nicht – „gern“ wird im Spanischen mit gustar ausgedrückt. `Nos gustan viajar` ist falsch, weil Tätigkeiten als Singular gelten.',
        avoid: 'Sobald du „gern“ übersetzt, denk an: `me / te / nos … gusta` + Infinitiv.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: G,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib ihn richtig.',
      sentence: 'Yo gusto los libros.',
      answers: ['Me gustan los libros.', 'A mí me gustan los libros.'],
      german: 'Ich mag Bücher.',
      feedback: {
        rule: 'Die Person steht als Pronomen vor dem Verb (`me`), das Verb richtet sich nach der Sache: `los libros` → `gustan`.',
        why: '`Yo gusto` bedeutet „ich gefalle“. Außerdem ist `los libros` Plural und braucht `gustan`.',
        avoid: 'Streiche gedanklich das deutsche „ich mag“ und denke „mir gefallen die Bücher“.',
      },
    },
  ],
  pronunciation: ['es.p.ll.playa', 'es.p.stress.telefono', 'es.p.into.que-bien'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['reading', 'grammar'],
      topicIds: G,
      difficulty: 2,
      scenario: 'Deine spanische Kollegin fragt: `¿Te gusta el fútbol?` Du magst Fußball überhaupt nicht, aber Tennis sehr. Was antwortest du?',
      options: [
        { text: 'No, no me gusta nada. Me gusta mucho el tenis.' },
        { text: 'No, no gusto el fútbol. Gusto el tenis.', why: '`gusto` heißt „ich gefalle“. Richtig ist `no me gusta` / `me gusta`.' },
        { text: 'No, no me gustan nada. Me gustan el tenis.', why: 'Fußball und Tennis sind jeweils eine Sache → `gusta`, nicht `gustan`.' },
        { text: 'Sí, me gusta mucho el fútbol.', why: 'Grammatisch richtig, aber inhaltlich falsch – du magst Fußball ja gar nicht.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Verneinung: `no me gusta nada`; Vorliebe: `me gusta mucho` + Sache im Singular.',
        why: 'Die falschen Antworten verwenden eine Form für „ich“ oder den Plural bei einer einzelnen Sache.',
        avoid: 'Zähle, was gefällt: eine Sache → gusta, mehrere → gustan.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: G,
      difficulty: 2,
      instruction: 'Wähle die passende Reaktion.',
      lines: [
        { speaker: 'Marco', text: 'Me encanta la música latina. ¿Y a ti?', german: 'Ich liebe lateinamerikanische Musik. Und du?' },
        { speaker: 'Du', text: 'A mí también. Me gusta mucho bailar.', german: 'Ich auch. Ich tanze sehr gern.' },
        { speaker: 'Marco', text: '¡Qué bien! A mí también me encanta bailar.', german: 'Wie schön! Ich tanze auch unheimlich gern.' },
      ],
      gapIndex: 1,
      options: [
        'A mí también. Me gusta mucho bailar.',
        'Yo también. Gusto mucho bailar.',
        'A mí también. Me gustan mucho bailar.',
        'A mí tampoco. Me gusta mucho bailar.',
      ],
      answer: 0,
      feedback: {
        rule: 'Zustimmung zu einer positiven Aussage: `A mí también.` Tätigkeit → `me gusta` + Infinitiv (Singular).',
        why: '`tampoco` passt nur zu einer verneinten Aussage; `gusto` und `gustan` + Infinitiv sind falsch.',
        avoid: 'Positiv → también, negativ → tampoco. Und nach gustar-Sätzen reagiert man mit `a mí`, nicht mit `yo`.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: G,
      difficulty: 2,
      prompt: 'Schreib 3–4 Sätze: Was magst du, was magst du gar nicht – und was mag jemand aus deiner Familie?',
      requirements: [
        { pattern: '\\bme (gusta|encanta)', hint: 'eine eigene Vorliebe mit „me gusta“ oder „me encanta“' },
        { pattern: '\\bno me gusta', hint: 'eine Verneinung mit „no me gusta …“' },
        { pattern: '\\bles? (gusta|encanta)', hint: 'die Vorliebe einer anderen Person („a mi … le gusta …“)' },
      ],
      samples: [
        'Me gusta mucho la música y me encanta bailar. No me gusta nada el fútbol. A mi hermano le gustan los deportes.',
      ],
      minWords: 12,
      feedback: {
        rule: 'Person als Pronomen vor dem Verb (me/te/le …), Verb nach der Sache (gusta/gustan), Verneinung mit `no` davor.',
        why: 'Häufige Fehler: `yo gusto`, `me gusta los …`, fehlendes `le` bei `a mi hermano`.',
        avoid: 'Prüfe jeden Satz: Was gefällt (Singular/Plural)? Wem gefällt es (me/te/le …)?',
      },
    },
    {
      id: `${L}.a04`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: G,
      difficulty: 2,
      prompt: 'Erzähl laut, was du in deiner Freizeit gern machst und was nicht (2–3 Sätze).',
      keywords: ['me gusta', 'me gustan', 'me encanta', 'no me gusta', 'leer', 'bailar', 'cocinar', 'viajar', 'música', 'deporte'],
      minMatch: 2,
      sample: 'Me gusta leer y me encanta viajar, pero no me gusta cocinar.',
      feedback: {
        rule: 'Vorlieben: `Me gusta` + Sache/Infinitiv, `Me encanta …`, `No me gusta …`.',
        why: 'Wurden zu wenige Schlüsselwörter erkannt, fehlte meist die Struktur `me gusta` – oder die Aufnahme war zu kurz.',
        avoid: 'Sprich `me GUS-ta` flüssig als eine Einheit, ohne Pause zwischen me und gusta.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.tener'],
      difficulty: 1,
      verb: 'tener',
      tense: 'Präsens',
      person: 'ellos',
      sentence: 'Mis abuelos ___ un perro.',
      answers: ['tienen'],
      feedback: {
        rule: '`ellos / ellas / ustedes tienen`.',
        why: '`tenen` gibt es nicht: In der betonten Stammsilbe steht `ie` (TIE-nen).',
        avoid: 'tengo – tienes – tiene – tenemos – (tenéis) – tienen: Nur nosotros/vosotros ohne ie.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.possessives'],
      difficulty: 2,
      prompt: 'Wie heißt „unsere Eltern“? `___ padres viven en Quito.`',
      options: [
        { text: 'Nuestros' },
        { text: 'Nuestro', why: '`padres` ist Plural – der Begleiter braucht ebenfalls die Pluralform.' },
        { text: 'Nuestras', why: '`los padres` ist maskulin; die weibliche Form passt nicht.' },
        { text: 'Mis', why: '`mis` heißt „meine“, nicht „unsere“.' },
      ],
      answer: 0,
      feedback: {
        rule: '`nuestro` passt sich in Geschlecht und Zahl an: `los padres` → `nuestros padres`.',
        why: 'nuestro hat vier Formen: nuestro, nuestra, nuestros, nuestras.',
        avoid: 'Setze gedanklich den Artikel ein: los padres → nuestr**os** padres.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.tener'],
      difficulty: 2,
      audio: '¿Cuántos años tienes?',
      answers: ['¿Cuántos años tienes?'],
      german: 'Wie alt bist du?',
      feedback: {
        rule: 'Fragewörter tragen einen Akzent: `¿Cuántos …?` Das ñ in `años` nicht vergessen.',
        why: '`anos` ohne Tilde ist ein anderes (unhöfliches) Wort – das ñ ist ein eigener Buchstabe.',
        avoid: 'Sprich beim Schreiben leise mit: A-ños – das „nj“ zeigt dir das ñ.',
      },
    },
  ],
};

export default lesson;
