import type { Lesson } from '../../types';

const L = 'es.a1.l01';
const TENER = ['es.g.tener'];
const POSS = ['es.g.possessives'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c1',
  order: 1,
  title: 'Tener – Familie & Alter',
  subtitle: 'Über dich, deine Familie und dein Alter sprechen',
  icon: '👨‍👩‍👧',
  minutes: 11,
  goal:
    'Du lernst das unregelmäßige Verb **tener** (haben), stellst deine **Familie** vor und sagst, wie alt du bist – auf Spanisch „hat“ man sein Alter: `Tengo treinta años.` Dazu kommen die Possessivbegleiter `mi`, `tu`, `su` und `nuestro`.',
  canDo: [
    'Ich kann tener im Präsens in allen Personen verwenden.',
    'Ich kann sagen, wie alt ich bin, und andere nach ihrem Alter fragen.',
    'Ich kann meine Familie in einfachen Sätzen vorstellen.',
    'Ich kann mi, tu, su und nuestro passend zum Nomen verwenden.',
  ],
  topicIds: ['es.g.tener', 'es.g.possessives'],
  vocab: [
    { id: `${L}.v.tener`, target: 'tener', german: 'haben', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Tengo dos hermanos.', german: 'Ich habe zwei Geschwister.' } },
    { id: `${L}.v.familia`, target: 'la familia', german: 'die Familie', pos: 'noun', gender: 'f', plural: 'las familias', emoji: '👨‍👩‍👧‍👦', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Mi familia es grande.', german: 'Meine Familie ist groß.' } },
    { id: `${L}.v.padre`, target: 'el padre', german: 'der Vater', pos: 'noun', gender: 'm', plural: 'los padres', emoji: '👨', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Mi padre tiene sesenta años.', german: 'Mein Vater ist sechzig Jahre alt.' } },
    { id: `${L}.v.madre`, target: 'la madre', german: 'die Mutter', pos: 'noun', gender: 'f', plural: 'las madres', emoji: '👩', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Tu madre es muy simpática.', german: 'Deine Mutter ist sehr nett.' } },
    { id: `${L}.v.padres`, target: 'los padres', german: 'die Eltern', pos: 'noun', gender: 'm', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Mis padres viven en Hamburgo.', german: 'Meine Eltern wohnen in Hamburg.' } },
    { id: `${L}.v.hermano`, target: 'el hermano', german: 'der Bruder', pos: 'noun', gender: 'm', plural: 'los hermanos (Brüder / Geschwister)', emoji: '👦', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: '¿Tienes hermanos?', german: 'Hast du Geschwister?' } },
    { id: `${L}.v.hermana`, target: 'la hermana', german: 'die Schwester', pos: 'noun', gender: 'f', plural: 'las hermanas', emoji: '👧', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Mi hermana tiene veinticinco años.', german: 'Meine Schwester ist fünfundzwanzig.' } },
    { id: `${L}.v.hijo`, target: 'el hijo', german: 'der Sohn', pos: 'noun', gender: 'm', plural: 'los hijos (Söhne / Kinder)', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Tenemos dos hijos.', german: 'Wir haben zwei Kinder.' } },
    { id: `${L}.v.hija`, target: 'la hija', german: 'die Tochter', pos: 'noun', gender: 'f', plural: 'las hijas', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Su hija vive en Lima.', german: 'Seine / Ihre Tochter wohnt in Lima.' } },
    { id: `${L}.v.abuelo`, target: 'el abuelo', german: 'der Großvater', pos: 'noun', gender: 'm', plural: 'los abuelos (Großväter / Großeltern)', emoji: '👴', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Mi abuelo tiene ochenta y cinco años.', german: 'Mein Großvater ist fünfundachtzig.' } },
    { id: `${L}.v.abuela`, target: 'la abuela', german: 'die Großmutter', pos: 'noun', gender: 'f', plural: 'las abuelas', emoji: '👵', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Nuestra abuela vive en Sevilla.', german: 'Unsere Großmutter wohnt in Sevilla.' } },
    { id: `${L}.v.ano`, target: 'el año', german: 'das Jahr', pos: 'noun', gender: 'm', plural: 'los años', emoji: '📅', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: '¿Cuántos años tienes?', german: 'Wie alt bist du?' } },
    { id: `${L}.v.perro`, target: 'el perro', german: 'der Hund', pos: 'noun', gender: 'm', plural: 'los perros', emoji: '🐶', field: 'Tiere', stageId: 'a1', lessonId: L, example: { target: 'Tenemos un perro.', german: 'Wir haben einen Hund.' } },
    { id: `${L}.v.mayor`, target: 'mayor', german: 'älter (bei Geschwistern)', pos: 'adj', gender: 'm/f', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Mi hermano mayor vive en Madrid.', german: 'Mein älterer Bruder wohnt in Madrid.' } },
    { id: `${L}.v.menor`, target: 'menor', german: 'jünger (bei Geschwistern)', pos: 'adj', gender: 'm/f', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Mi hermana menor tiene diez años.', german: 'Meine jüngere Schwester ist zehn.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        '**tener** heißt „haben“ und gehört zu den wichtigsten Verben überhaupt. Es ist **unregelmäßig**: Die yo-Form lautet `tengo`, und in den stammbetonten Formen wird aus dem `e` ein `ie` – `tienes`, `tiene`, `tienen`. Nur `tenemos` und `tenéis` bleiben regelmäßig.',
    },
    {
      type: 'conjugation',
      verb: 'tener',
      translation: 'haben',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'tengo', ending: 'go' },
        { person: 'tú', form: 'tienes', ending: 'es' },
        { person: 'él / ella / usted', form: 'tiene', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'tenemos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'tenéis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'tienen', ending: 'en' },
      ],
    },
    {
      type: 'compare',
      target: 'Tengo treinta años.',
      german: 'Ich bin dreißig Jahre alt.',
      md: 'Wörtlich: „Ich habe dreißig Jahre.“ Beim Alter benutzt Spanisch **tener**, nicht ser. Die passende Frage lautet `¿Cuántos años tienes?` – „Wie viele Jahre hast du?“',
    },
    {
      type: 'mistake',
      wrong: 'Soy treinta años.',
      right: 'Tengo treinta años.',
      why: 'Das deutsche „Ich bin 30“ verleitet zu `soy`. Auf Spanisch **hat** man sein Alter: `tener … años`. Mit ser klingt der Satz für Muttersprachler völlig falsch.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Mi', role: 'pronoun' },
        { text: ' ' },
        { text: 'hermano', role: 'subject' },
        { text: ' ' },
        { text: 'mayor', role: 'adjective' },
        { text: ' ' },
        { text: 'tiene', role: 'verb' },
        { text: ' ' },
        { text: 'treinta años', role: 'object' },
        { text: '.' },
      ],
      german: 'Mein älterer Bruder ist dreißig Jahre alt.',
    },
    {
      type: 'table',
      title: 'Possessivbegleiter (mein, dein, sein …)',
      headers: ['Besitzer', 'eine Sache', 'mehrere Sachen', 'Deutsch'],
      rows: [
        ['yo', 'mi', 'mis', 'mein / meine'],
        ['tú', 'tu', 'tus', 'dein / deine'],
        ['él / ella / usted', 'su', 'sus', 'sein, ihr / Ihr'],
        ['nosotros / nosotras', 'nuestro, nuestra', 'nuestros, nuestras', 'unser / unsere'],
        ['vosotros / vosotras (Spanien)', 'vuestro, vuestra', 'vuestros, vuestras', 'euer / eure'],
        ['ellos / ellas / ustedes', 'su', 'sus', 'ihr / Ihr'],
      ],
    },
    {
      type: 'tip',
      md:
        'Der Begleiter richtet sich nach dem **Besitz**, nicht nach dem Besitzer: `mi hermano` → `mis hermanos`. `nuestro` und `vuestro` passen sich zusätzlich im Geschlecht an: `nuestra familia`, `nuestros abuelos`.\nUnd Achtung: `tu` ohne Akzent = „dein“, `tú` mit Akzent = „du“.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika gibt es kein vosotros – auch zu mehreren Freunden sagst du `ustedes`: `¿Ustedes tienen hermanos?` Statt vuestro benutzt man `su` oder, wenn es eindeutig sein soll, `de ustedes`: `su casa` / `la casa de ustedes`.',
    },
  ],
  examples: [
    {
      target: 'Tengo treinta y dos años.',
      german: 'Ich bin zweiunddreißig Jahre alt.',
      literal: 'Ich habe zweiunddreißig Jahre.',
      parts: [
        { text: 'Tengo', role: 'verb' },
        { text: ' ' },
        { text: 'treinta y dos años', role: 'object' },
        { text: '.' },
      ],
    },
    {
      target: '¿Cuántos años tienes?',
      german: 'Wie alt bist du?',
      literal: 'Wie viele Jahre hast du?',
      parts: [
        { text: '¿Cuántos años', role: 'question' },
        { text: ' ' },
        { text: 'tienes', role: 'verb' },
        { text: '?' },
      ],
    },
    {
      target: 'Mi hermana tiene un perro.',
      german: 'Meine Schwester hat einen Hund.',
      parts: [
        { text: 'Mi', role: 'pronoun' },
        { text: ' ' },
        { text: 'hermana', role: 'subject' },
        { text: ' ' },
        { text: 'tiene', role: 'verb' },
        { text: ' ' },
        { text: 'un perro', role: 'object' },
        { text: '.' },
      ],
    },
    {
      target: 'Tenemos dos hijos: un hijo y una hija.',
      german: 'Wir haben zwei Kinder: einen Sohn und eine Tochter.',
      note: '`los hijos` kann „die Söhne“ oder „die Kinder“ heißen – der maskuline Plural schließt beide Geschlechter ein. Genauso: `los hermanos` = Brüder oder Geschwister.',
    },
    {
      target: 'Nuestros abuelos viven en Valencia.',
      german: 'Unsere Großeltern wohnen in Valencia.',
      note: '`nuestros` steht im maskulinen Plural, weil `abuelos` maskulin Plural ist.',
    },
    {
      target: 'Mis padres no tienen perro.',
      german: 'Meine Eltern haben keinen Hund.',
      note: 'Nach der Verneinung fällt der unbestimmte Artikel meist weg: nicht `no tienen un perro`, sondern `no tienen perro` – ähnlich wie das deutsche „keinen“.',
    },
    { target: '¿Vosotros tenéis hermanos?', german: 'Habt ihr Geschwister?', variant: 'es-ES' },
    { target: '¿Ustedes tienen hermanos?', german: 'Habt ihr Geschwister?', variant: 'es-LA', note: 'In Lateinamerika sagt man zu mehreren Personen immer `ustedes`.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: TENER,
      difficulty: 1,
      instruction: 'Ordne jedem Pronomen die passende Form von „tener“ zu.',
      pairs: [
        { left: 'yo', right: 'tengo' },
        { left: 'tú', right: 'tienes' },
        { left: 'ella', right: 'tiene' },
        { left: 'nosotros', right: 'tenemos' },
        { left: 'ellos', right: 'tienen' },
      ],
      feedback: {
        rule: '`tener`: tengo, tienes, tiene, tenemos, (tenéis), tienen. In den betonten Stammformen steht `ie`, nosotros bleibt bei `e`.',
        why: 'Häufig wird `tenemos` zu „tienemos“ oder `tengo` zu „teno“ vermischt. Die yo-Form hat das besondere `-go`, nosotros keinen Stammwechsel.',
        avoid: 'Merkhilfe: Nur wo die Betonung auf dem Stamm liegt (TIE-nes, TIE-ne, TIE-nen), wird aus e ein ie. Bei te-NE-mos liegt sie auf der Endung.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: POSS,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '👨', word: 'el padre' },
        { emoji: '👩', word: 'la madre' },
        { emoji: '👴', word: 'el abuelo' },
        { emoji: '👵', word: 'la abuela' },
        { emoji: '🐶', word: 'el perro' },
      ],
      feedback: {
        rule: 'Familienwörter haben meist eine männliche Form auf -o und eine weibliche auf -a: `abuelo` / `abuela`. Ausnahme: `padre` / `madre`.',
        why: 'Wer `el abuelo` und `la abuela` vertauscht, hat meist nur auf den Wortstamm geachtet – die Endung verrät das Geschlecht.',
        avoid: 'Lerne jedes Nomen mit Artikel: `el padre`, `la madre`. So prägt sich das Geschlecht automatisch ein.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: TENER,
      difficulty: 1,
      prompt: 'Welche Form passt? `¿Cuántos años ___ tu hermana?`',
      options: [
        { text: 'tiene' },
        { text: 'es', why: 'Das Alter drückt Spanisch mit **tener** aus, nicht mit ser: „Wie viele Jahre **hat** deine Schwester?“' },
        { text: 'tienes', why: '`tienes` ist die du-Form. Hier geht es aber um `tu hermana` – also die 3. Person (sie).' },
        { text: 'está', why: 'estar beschreibt Ort und Befinden, nie das Alter.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Alter: `tener … años`. Die Frage lautet `¿Cuántos años tiene …?` (3. Person für er/sie/usted).',
        why: '`tu` (dein) gehört zu `hermana` – das Subjekt des Satzes ist also „deine Schwester“ = ella → `tiene`.',
        avoid: 'Frag dich immer: Wer ist das Subjekt? `tu hermana` = sie → `tiene`. Nur bei `tú` (du, mit Akzent) heißt es `tienes`.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: POSS,
      difficulty: 2,
      instruction: 'Setze die passenden Possessivbegleiter für „meine“ ein.',
      sentence: '___ padres viven en Madrid y ___ hermana vive en Lima.',
      answers: [['mis'], ['mi']],
      bank: ['mi', 'mis', 'tu', 'nuestra'],
      german: 'Meine Eltern wohnen in Madrid und meine Schwester wohnt in Lima.',
      feedback: {
        rule: '`mi` steht vor einem Nomen im Singular, `mis` vor einem Nomen im Plural: `mis padres`, `mi hermana`.',
        why: 'Der Begleiter richtet sich nach dem Besitz (padres = Plural), nicht nach dem Besitzer (ich = eine Person).',
        avoid: 'Schau aufs Nomen: Endet es auf -s, braucht auch der Begleiter ein -s: `mis padres`, `tus hijos`, `sus abuelos`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: TENER,
      difficulty: 2,
      audio: 'Tengo cuarenta y cinco años y tengo tres hijos.',
      question: 'Wie alt ist die Person und wie viele Kinder hat sie?',
      options: ['45 Jahre, 3 Kinder', '55 Jahre, 3 Kinder', '45 Jahre, 2 Kinder', '40 Jahre, 5 Kinder'],
      answer: 0,
      feedback: {
        rule: '`cuarenta y cinco` = 45, `tres` = 3. Zehner und Einer werden ab 31 mit `y` verbunden.',
        why: '`cuarenta` (40) und `cincuenta` (50) klingen ähnlich – achte auf den Anfang: cua- = 4, cin- = 5.',
        avoid: 'Hör dir den Satz langsam noch einmal an und sprich die Zahlen mit: cua-REN-ta y CIN-co.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: ['es.g.tener', 'es.g.possessives'],
      difficulty: 2,
      instruction: 'Bilde die Frage „Wie alt ist deine Großmutter?“.',
      tokens: ['¿Cuántos', 'años', 'tiene', 'tu', 'abuela?'],
      extra: ['es'],
      german: 'Wie alt ist deine Großmutter?',
      feedback: {
        rule: 'Fragewort zuerst, dann Verb, dann Subjekt: `¿Cuántos años tiene tu abuela?`',
        why: '`es` passt nicht, weil das Alter mit tener ausgedrückt wird. Das Subjekt (`tu abuela`) steht in Fragen meist hinter dem Verb.',
        avoid: 'Lerne die Frage als festen Block: `¿Cuántos años tiene …?` – dahinter kommt die Person.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: TENER,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Ich bin 28 Jahre alt und habe einen Bruder.',
      answers: [
        'Tengo veintiocho años y tengo un hermano.',
        'Tengo veintiocho años y un hermano.',
        'Tengo 28 años y tengo un hermano.',
        'Tengo 28 años y un hermano.',
        'Yo tengo veintiocho años y tengo un hermano.',
        'Yo tengo veintiocho años y un hermano.',
        'Yo tengo 28 años y tengo un hermano.',
        'Yo tengo 28 años y un hermano.',
      ],
      feedback: {
        rule: 'Alter und Besitz drückst du beide mit **tener** aus: `Tengo 28 años` / `Tengo un hermano`.',
        why: '„Ich bin 28“ verleitet zu `soy 28` – das ist falsch. Auch `años` darf in der vollständigen Aussage nicht fehlen.',
        avoid: 'Übersetze gedanklich wörtlich: „Ich **habe** 28 Jahre.“ Dann kommst du automatisch auf `tengo`.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: POSS,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'Nuestro familia es muy grande.',
      answers: ['Nuestra familia es muy grande.'],
      german: 'Unsere Familie ist sehr groß.',
      feedback: {
        rule: '`nuestro` passt sich im Geschlecht an das Nomen an: `la familia` ist weiblich → `nuestra familia`.',
        why: 'Anders als `mi`, `tu`, `su` hat `nuestro` eine weibliche Form. `nuestro familia` mischt maskulin und feminin.',
        avoid: 'Prüfe bei nuestro/vuestro immer den Artikel des Nomens: el → nuestro, la → nuestra, los → nuestros, las → nuestras.',
      },
    },
  ],
  pronunciation: ['es.p.j.jamon', 'es.p.ny.nino', 'es.p.r.perro'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: TENER,
      difficulty: 2,
      instruction: 'Ergänze die fehlende Antwort im Gespräch.',
      lines: [
        { speaker: 'Lucía', text: '¿Tienes hermanos?', german: 'Hast du Geschwister?' },
        { speaker: 'Du', text: 'Sí, tengo una hermana.', german: 'Ja, ich habe eine Schwester.' },
        { speaker: 'Lucía', text: '¿Y cuántos años tiene?', german: 'Und wie alt ist sie?' },
        { speaker: 'Du', text: 'Tiene veintidós años.', german: 'Sie ist zweiundzwanzig.' },
      ],
      gapIndex: 3,
      options: ['Tiene veintidós años.', 'Es veintidós años.', 'Tengo veintidós años.', 'Está veintidós años.'],
      answer: 0,
      feedback: {
        rule: 'Es geht um das Alter der Schwester (sie) → `tiene … años`.',
        why: '`Es` und `Está` sind beim Alter falsch; `Tengo` wäre dein eigenes Alter, nicht das deiner Schwester.',
        avoid: 'Achte darauf, über wen gesprochen wird: die Schwester = 3. Person → `tiene`.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.tener', 'es.g.possessives'],
      difficulty: 2,
      prompt: 'Stell deine Familie in 3–4 Sätzen vor: Wie alt bist du? Hast du Geschwister oder Kinder? Wie alt sind sie?',
      requirements: [
        { pattern: '\\bteng(o|emos)\\b', hint: 'eine Form von tener (z. B. „tengo“)' },
        { pattern: 'años', hint: 'eine Altersangabe mit „… años“' },
        { pattern: '\\b(mi|mis|nuestr[oa]s?)\\b', hint: 'mindestens einen Possessivbegleiter (mi, mis, nuestro …)' },
        { pattern: '(padre|madre|herman|hij|abuel)', hint: 'mindestens ein Familienmitglied' },
      ],
      samples: [
        'Tengo treinta años. Tengo un hermano y una hermana. Mi hermano tiene veinticinco años y mi hermana tiene treinta y cinco. Mis padres viven en Colonia.',
      ],
      minWords: 15,
      feedback: {
        rule: 'Alter: `tengo … años`; Familie: `tengo un hermano / una hermana`; Besitz: `mi` (Singular), `mis` (Plural).',
        why: 'Typisch sind `soy … años` statt `tengo … años` und `mi` vor einem Plural (`mi padres`).',
        avoid: 'Lies deinen Text einmal nur auf tener-Formen und einmal nur auf mi/mis durch – so findest du die typischen Fehler schnell.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: TENER,
      difficulty: 2,
      prompt: 'Sag laut, wie alt du bist und ob du Geschwister, Kinder oder ein Haustier hast (2–3 Sätze).',
      keywords: ['tengo', 'años', 'hermano', 'hermana', 'hermanos', 'hermanas', 'hijo', 'hija', 'hijos', 'perro'],
      minMatch: 3,
      sample: 'Tengo treinta años y tengo una hermana. No tengo perro.',
      feedback: {
        rule: 'Sprich in ganzen Sätzen mit `tengo`: `Tengo … años.` / `Tengo un hermano.` / `No tengo hijos.`',
        why: 'Wenn die Spracherkennung zu wenige Schlüsselwörter findet, fehlen meist `tengo` oder `años` – oder die Sätze waren sehr kurz.',
        avoid: 'Sprich ruhig und deutlich, betone TEN-go und A-ños. Das ñ klingt wie „nj“ in „Cognac“.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.tener', 'es.g.possessives'],
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Erzähl deinem Gegenüber von deiner Familie: Frag nach Geschwistern und ihrem Alter und beantworte die Fragen zu deiner Familie mit tener.',
      turns: 4,
      feedback: {
        rule: 'Alter und Familie mit tener: `¿Tienes hermanos?` – `Sí, tengo …` / `¿Cuántos años tiene?`',
        why: 'Im freien Gespräch rutscht leicht `soy … años` heraus – achte bewusst auf tener.',
        avoid: 'Leg dir zwei Sätze zurecht, bevor du startest: dein Alter und deine Geschwister.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.ser-estar'],
      difficulty: 2,
      prompt: 'Wiederholung ser/estar: `Mi madre ___ profesora y hoy ___ en casa.`',
      options: [
        { text: 'es / está' },
        { text: 'está / es', why: 'Beruf → ser (`es profesora`), Ort → estar (`está en casa`). Hier ist es genau umgekehrt.' },
        { text: 'es / es', why: 'Für den Ort, an dem sich jemand befindet, brauchst du estar: `está en casa`.' },
        { text: 'tiene / está', why: 'Den Beruf drückst du mit ser aus, nicht mit tener.' },
      ],
      answer: 0,
      feedback: {
        rule: 'ser für Beruf, Herkunft, Identität; estar für Ort und Befinden.',
        why: 'Beide Verben heißen „sein“ – entscheidend ist, was ausgedrückt wird.',
        avoid: 'Frage: „Was ist sie?“ → ser. „Wo ist sie?“ → estar.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: TENER,
      difficulty: 1,
      verb: 'tener',
      tense: 'Präsens',
      person: 'nosotros',
      sentence: 'Nosotros ___ tres hijos.',
      answers: ['tenemos'],
      feedback: {
        rule: '`nosotros tenemos` – ohne Stammwechsel.',
        why: '„tienemos“ ist falsch: Bei nosotros liegt die Betonung auf der Endung (te-NE-mos), deshalb bleibt das e.',
        avoid: 'nosotros und vosotros sind bei Stammwechselverben fast immer regelmäßig.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading'],
      topicIds: POSS,
      difficulty: 1,
      direction: 'toGerman',
      source: 'Nuestra familia es grande.',
      answers: ['Unsere Familie ist groß.'],
      feedback: {
        rule: '`nuestra` = unsere (weiblich, weil `familia` weiblich ist); `es grande` = ist groß.',
        why: 'Eine Verwechslung mit „eure“ (vuestra) oder „ihre“ (su) liegt nahe – nuestro gehört zu nosotros.',
        avoid: 'Merke: **nos**otros → **nues**tro. Beide beginnen mit n.',
      },
    },
  ],
};

export default lesson;
