import type { Lesson } from '../../types';

const L = 'es.a1.l08';
const SC = ['es.g.stem-change'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c3',
  order: 8,
  title: 'Im Restaurant',
  subtitle: 'querer, preferir, pedir · de primero, de segundo, de postre',
  icon: '🍽️',
  minutes: 13,
  goal:
    'Du bestellst im Restaurant wie ein Profi: `De primero quiero una sopa y de segundo, pescado.` Dafür lernst du die **Stammwechselverben** `querer`, `preferir` (e → ie) und `pedir` (e → i), höfliche Bitten wie `¿Me trae la cuenta?` – und wie es mit dem Trinkgeld läuft.',
  canDo: [
    'Ich kann querer, preferir und pedir im Präsens verwenden.',
    'Ich kann ein Menü mit de primero, de segundo und de postre bestellen.',
    'Ich kann höflich um etwas bitten und die Rechnung verlangen.',
    'Ich weiß, wie man in Spanien und Lateinamerika Trinkgeld gibt.',
  ],
  topicIds: SC,
  vocab: [
    { id: `${L}.v.querer`, target: 'querer', german: 'wollen, möchten', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Quiero una ensalada, por favor.', german: 'Ich möchte einen Salat, bitte.' } },
    { id: `${L}.v.preferir`, target: 'preferir', german: 'lieber mögen, vorziehen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Prefiero agua sin gas.', german: 'Ich hätte lieber stilles Wasser.' } },
    { id: `${L}.v.pedir`, target: 'pedir', german: 'bestellen; bitten um', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: '¿Qué pides?', german: 'Was bestellst du?' } },
    { id: `${L}.v.carta`, target: 'la carta', german: 'die Speisekarte', pos: 'noun', gender: 'f', plural: 'las cartas', emoji: '📋', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: '¿Me trae la carta, por favor?', german: 'Bringen Sie mir bitte die Speisekarte?' } },
    { id: `${L}.v.menu-del-dia`, target: 'el menú del día', german: 'das Tagesmenü (Mittagsmenü zum Festpreis)', pos: 'noun', gender: 'm', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: 'Queremos el menú del día.', german: 'Wir möchten das Tagesmenü.' } },
    { id: `${L}.v.de-primero`, target: 'de primero', german: 'als Vorspeise / als ersten Gang', pos: 'phrase', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: 'De primero quiero una sopa.', german: 'Als Vorspeise möchte ich eine Suppe.' } },
    { id: `${L}.v.de-segundo`, target: 'de segundo', german: 'als Hauptgericht / als zweiten Gang', pos: 'phrase', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: 'De segundo prefiero el pescado.', german: 'Als Hauptgericht nehme ich lieber den Fisch.' } },
    { id: `${L}.v.postre`, target: 'el postre', german: 'der Nachtisch', pos: 'noun', gender: 'm', plural: 'los postres', emoji: '🍰', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: '¿Qué hay de postre?', german: 'Was gibt es zum Nachtisch?' } },
    { id: `${L}.v.sopa`, target: 'la sopa', german: 'die Suppe', pos: 'noun', gender: 'f', plural: 'las sopas', emoji: '🍲', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'La sopa está muy rica.', german: 'Die Suppe ist sehr lecker.' } },
    { id: `${L}.v.ensalada`, target: 'la ensalada', german: 'der Salat', pos: 'noun', gender: 'f', plural: 'las ensaladas', emoji: '🥗', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'Pido una ensalada mixta.', german: 'Ich bestelle einen gemischten Salat.' } },
    { id: `${L}.v.pescado`, target: 'el pescado', german: 'der Fisch (als Speise)', pos: 'noun', gender: 'm', plural: 'los pescados', emoji: '🐟', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: '¿Prefieres carne o pescado?', german: 'Magst du lieber Fleisch oder Fisch?' } },
    { id: `${L}.v.carne`, target: 'la carne', german: 'das Fleisch', pos: 'noun', gender: 'f', plural: 'las carnes', emoji: '🥩', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'No como carne.', german: 'Ich esse kein Fleisch.' } },
    { id: `${L}.v.vino`, target: 'el vino', german: 'der Wein', pos: 'noun', gender: 'm', plural: 'los vinos', emoji: '🍷', field: 'Getränke', stageId: 'a1', lessonId: L, example: { target: 'Prefiero vino tinto.', german: 'Ich trinke lieber Rotwein.' } },
    { id: `${L}.v.me-trae`, target: '¿Me trae …?', german: 'Bringen Sie mir …?', pos: 'phrase', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: '¿Me trae la cuenta, por favor?', german: 'Bringen Sie mir bitte die Rechnung?' } },
    { id: `${L}.v.propina`, target: 'la propina', german: 'das Trinkgeld', pos: 'noun', gender: 'f', plural: 'las propinas', emoji: '💶', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: 'En España la propina no es obligatoria.', german: 'In Spanien ist Trinkgeld nicht Pflicht.' } },
    { id: `${L}.v.mesero`, target: 'el mesero / la mesera', german: 'der Kellner / die Kellnerin (Spanien: el camarero)', pos: 'noun', gender: 'm/f', plural: 'los meseros', variant: 'es-LA', field: 'Restaurant', stageId: 'a1', lessonId: L, example: { target: 'El mesero trae el menú.', german: 'Der Kellner bringt die Speisekarte.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Bei manchen Verben ändert sich im Präsens der **Stammvokal**, sobald er betont ist – das kennst du schon von `tener` (`tienes`). Bei **querer** und **preferir** wird `e` zu `ie`, bei **pedir** wird `e` zu `i`. Die Endungen bleiben ganz regelmäßig.\n**Merksatz: Betonter Stamm → Wechsel.** `QUIE-ro`, `PI-do`, `pre-FIE-ro` – aber `que-RE-mos`, `pe-DI-mos`: Bei nosotros und vosotros liegt die Betonung auf der Endung, der Stamm bleibt unverändert.',
    },
    {
      type: 'conjugation',
      verb: 'querer',
      translation: 'wollen, möchten',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'quiero', ending: 'o' },
        { person: 'tú', form: 'quieres', ending: 'es' },
        { person: 'él / ella / usted', form: 'quiere', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'queremos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'queréis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'quieren', ending: 'en' },
      ],
    },
    {
      type: 'table',
      title: 'preferir (e → ie) und pedir (e → i)',
      headers: ['Person', 'preferir', 'pedir'],
      rows: [
        ['yo', 'prefiero', 'pido'],
        ['tú', 'prefieres', 'pides'],
        ['él / ella / usted', 'prefiere', 'pide'],
        ['nosotros / nosotras', 'preferimos', 'pedimos'],
        ['vosotros / vosotras (Spanien)', 'preferís', 'pedís'],
        ['ellos / ellas / ustedes', 'prefieren', 'piden'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'De primero', role: 'adverb' },
        { text: ' ' },
        { text: 'quiero', role: 'verb' },
        { text: ' ' },
        { text: 'una sopa', role: 'object' },
        { text: ' y ' },
        { text: 'de segundo', role: 'adverb' },
        { text: ', ' },
        { text: 'pescado', role: 'object' },
        { text: '.' },
      ],
      german: 'Als Vorspeise möchte ich eine Suppe und als Hauptgericht Fisch.',
    },
    {
      type: 'compare',
      target: '¿Me trae la cuenta, por favor?',
      german: 'Bringen Sie mir bitte die Rechnung?',
      md:
        'Eine Frage im Präsens ist auf Spanisch eine ganz normale, höfliche Bitte – genau wie im Deutschen „Bringen Sie mir …?“. `trae` ist die usted-Form von `traer` (bringen). Mit tú, z. B. unter Freunden: `¿Me traes …?` Und am Tisch gilt: `por favor` und `gracias` machen jede Bestellung freundlich.',
    },
    {
      type: 'mistake',
      wrong: 'Pregunto la cuenta.',
      right: 'Pido la cuenta.',
      why:
        'Im Deutschen „fragt man nach der Rechnung“. Auf Spanisch **bittet** man darum: `pedir la cuenta`. `pedir` heißt auch „bestellen“: `Pido una sopa.` `preguntar` bedeutet nur „eine Frage stellen“: `Pregunto el precio.` (Ich frage nach dem Preis.)',
    },
    {
      type: 'text',
      md:
        '**Kultur: Tagesmenü & Trinkgeld.** In Spanien bieten viele Restaurants mittags das `menú del día` an: `primero` (Vorspeise, z. B. Suppe oder Salat), `segundo` (Hauptgericht), `postre` (Nachtisch), dazu Brot und ein Getränk – zum Festpreis. Die Rechnung kommt erst, wenn du sie verlangst: `La cuenta, por favor.` ist völlig normal.\n`la propina` (Trinkgeld) ist in Spanien freiwillig: Man rundet auf oder lässt bei gutem Service etwa 5–10 % auf dem Tisch. In Mexiko sind 10–15 % üblich, in Argentinien rund 10 %. In manchen Ländern, z. B. Kolumbien oder Chile, steht ein Vorschlag von 10 % schon auf der Rechnung – ein kurzer Blick lohnt sich.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'Der Kellner heißt in Mexiko, Kolumbien und Mittelamerika `el mesero`, in Argentinien, Uruguay und Peru `el mozo`, in Spanien `el camarero`. Die Speisekarte ist in Lateinamerika meist `el menú` (in Spanien `la carta`). Statt `de primero` hörst du oft `de entrada` (als Vorspeise); in Mexiko heißt das Hauptgericht `el plato fuerte`.',
    },
  ],
  examples: [
    {
      target: 'Quiero la sopa del día, por favor.',
      german: 'Ich möchte die Tagessuppe, bitte.',
      parts: [
        { text: 'Quiero', role: 'verb' },
        { text: ' ' },
        { text: 'la sopa del día', role: 'object' },
        { text: ', ' },
        { text: 'por favor', role: 'other' },
        { text: '.' },
      ],
    },
    {
      target: '¿Qué prefieres, carne o pescado? – Prefiero pescado.',
      german: 'Was magst du lieber, Fleisch oder Fisch? – Lieber Fisch.',
    },
    {
      target: 'De primero pido una ensalada y de segundo, carne.',
      german: 'Als Vorspeise bestelle ich einen Salat und als Hauptgericht Fleisch.',
      parts: [
        { text: 'De primero', role: 'adverb' },
        { text: ' ' },
        { text: 'pido', role: 'verb' },
        { text: ' ' },
        { text: 'una ensalada', role: 'object' },
        { text: ' y ' },
        { text: 'de segundo', role: 'adverb' },
        { text: ', ' },
        { text: 'carne', role: 'object' },
        { text: '.' },
      ],
    },
    { target: '¿Qué hay de postre?', german: 'Was gibt es zum Nachtisch?' },
    {
      target: 'Nosotros queremos el menú del día.',
      german: 'Wir möchten das Tagesmenü.',
      note: 'nosotros ohne Stammwechsel: `queremos`, nicht „quieremos“.',
    },
    {
      target: 'Mis hijos siempre piden pizza.',
      german: 'Meine Kinder bestellen immer Pizza.',
      note: '`pedir` → `piden` (e → i).',
    },
    {
      target: 'El camarero trae la carta.',
      german: 'Der Kellner bringt die Speisekarte.',
      variant: 'es-ES',
    },
    {
      target: 'El mesero trae el menú.',
      german: 'Der Kellner bringt die Speisekarte.',
      variant: 'es-LA',
      note: 'In Argentinien, Uruguay und Peru: `el mozo`.',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: SC,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '🍲', word: 'la sopa' },
        { emoji: '🥗', word: 'la ensalada' },
        { emoji: '🐟', word: 'el pescado' },
        { emoji: '🥩', word: 'la carne' },
        { emoji: '🍰', word: 'el postre' },
        { emoji: '🍷', word: 'el vino' },
      ],
      feedback: {
        rule: '`el pescado` ist Fisch als Speise; der lebende Fisch im Wasser heißt `el pez`. `la carne` (Fleisch) ist weiblich.',
        why: 'Deutsche verwechseln oft `el pescado` und `la carne`, weil beide auf der Karte unter „Hauptgerichte“ stehen – lerne sie mit Bild.',
        avoid: 'Lerne Speisen mit Artikel und gleich in einem Bestellsatz: `Quiero la sopa.`',
      },
    },
    {
      id: `${L}.g02`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: SC,
      difficulty: 1,
      instruction: 'Ordne jeder Angabe die passende Verbform zu.',
      pairs: [
        { left: 'pedir (yo)', right: 'pido' },
        { left: 'preferir (tú)', right: 'prefieres' },
        { left: 'querer (nosotros)', right: 'queremos' },
        { left: 'pedir (ellas)', right: 'piden' },
        { left: 'querer (usted)', right: 'quiere' },
      ],
      feedback: {
        rule: 'querer/preferir: e → ie; pedir: e → i – aber nicht bei nosotros/vosotros: `queremos`, `pedimos`.',
        why: 'Wer bei nosotros den Stamm wechselt („quieremos“) oder bei pedir `ie` einsetzt („piedo“), mischt die beiden Muster.',
        avoid: 'Lerne je eine Leitform: `quiero` (ie) und `pido` (i).',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: SC,
      difficulty: 1,
      prompt: 'Welche Form passt? `Nosotros ___ el menú del día.`',
      options: [
        { text: 'queremos' },
        { text: 'quieremos', why: 'Bei nosotros liegt die Betonung auf der Endung (que-RE-mos) – deshalb kein Stammwechsel.' },
        { text: 'quieren', why: '`quieren` gehört zu ellos/ellas/ustedes, nicht zu nosotros.' },
        { text: 'queréis', why: '`queréis` ist die vosotros-Form (ihr).' },
      ],
      answer: 0,
      feedback: {
        rule: 'querer: quiero, quieres, quiere, **queremos**, queréis, quieren.',
        why: 'Das ie steht nur, wenn der Stamm betont ist. Bei nosotros/vosotros ist er unbetont.',
        avoid: 'Sprich die Form laut: que-RE-mos – betonte Endung, kein ie.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: SC,
      difficulty: 2,
      instruction: 'Setze die passenden Formen von „pedir“ ein.',
      sentence: '—¿Qué ___ tú de primero? —Yo ___ la sopa.',
      answers: [['pides'], ['pido']],
      bank: ['pides', 'pido', 'pedes', 'piden'],
      german: '„Was bestellst du als Vorspeise?“ – „Ich bestelle die Suppe.“',
      feedback: {
        rule: 'pedir: e → i in den betonten Formen: `pido`, `pides`, `pide`, `piden`.',
        why: '„pedes“ gibt es nicht – im Präsens ist der Stamm von pedir in diesen Formen immer `pid-`. `piden` wäre ellos/ellas.',
        avoid: 'Merke: pedir hat nur **i**, nie ie: `pido`, nicht „piedo“.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: SC,
      difficulty: 2,
      audio: 'De primero quiero una ensalada, de segundo prefiero el pescado y de postre, un flan.',
      question: 'Was bestellt der Gast als Hauptgericht?',
      options: ['Fisch', 'Salat', 'Fleisch', 'Flan'],
      answer: 0,
      feedback: {
        rule: '`de segundo` = als Hauptgericht → `el pescado` (Fisch).',
        why: 'Der Salat ist `de primero` (Vorspeise), der Flan `de postre` (Nachtisch). Fleisch (`carne`) kommt gar nicht vor.',
        avoid: 'Hör auf die Signalwörter primero – segundo – postre und notiere dir jeweils das Gericht danach.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: SC,
      difficulty: 2,
      verb: 'preferir',
      tense: 'Präsens',
      person: 'yo',
      sentence: 'Yo ___ agua sin gas.',
      answers: ['prefiero'],
      feedback: {
        rule: 'preferir: e → ie im betonten Stamm: `prefiero`.',
        why: 'Das zweite e (pre-**FE**-rir) wird betont und verwandelt sich: pre-FIE-ro. Das erste e bleibt.',
        avoid: 'Nur der Vokal direkt vor der Endung wechselt: pref**e**r- → pref**ie**r-.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'order',
      skills: ['grammar', 'speaking'],
      topicIds: SC,
      difficulty: 2,
      instruction: 'Bilde die höfliche Bitte „Bringen Sie mir bitte die Rechnung?“.',
      tokens: ['¿Me', 'trae', 'la', 'cuenta,', 'por', 'favor?'],
      extra: ['pido', 'el'],
      german: 'Bringen Sie mir bitte die Rechnung?',
      feedback: {
        rule: '`¿Me trae + Sache, por favor?` – `la cuenta` ist weiblich.',
        why: '`el cuenta` ist falsch (la cuenta). `pido` passt nicht in eine Frage mit `me trae`.',
        avoid: 'Lerne die Bitte als festen Block: `¿Me trae la cuenta, por favor?`',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: SC,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Als Nachtisch möchte ich einen Flan.',
      answers: [
        'De postre quiero un flan.',
        'De postre quisiera un flan.',
        'De postre yo quiero un flan.',
        'Quiero un flan de postre.',
        'Quisiera un flan de postre.',
        'Yo quiero un flan de postre.',
        'De postre me gustaría un flan.',
        'Me gustaría un flan de postre.',
        'Como postre quiero un flan.',
        'Quiero un flan como postre.',
        'Como postre quisiera un flan.',
        'Quisiera un flan como postre.',
        'Para postre quiero un flan.',
      ],
      feedback: {
        rule: '„als Nachtisch“ = `de postre`; „ich möchte“ = `quiero` (oder höflicher `quisiera`).',
        why: '„quero“ ist falsch – im betonten Stamm steht ie: `quiero`. Und „ein Flan“ ist maskulin: `un flan`, nicht `una flan`.',
        avoid: 'Merke die Bestellformel: `de primero … / de segundo … / de postre …`',
      },
    },
  ],
  pronunciation: ['es.p.link.un-cafe-con-leche', 'es.p.r.pero', 'es.p.cz.cerveza'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: SC,
      difficulty: 2,
      instruction: 'Wähle die passende Antwort des Gasts.',
      lines: [
        { speaker: 'Kellner', text: 'Buenas noches. ¿Qué va a tomar de primero?', german: 'Guten Abend. Was nehmen Sie als Vorspeise?' },
        { speaker: 'Du', text: 'De primero quiero la sopa, por favor.', german: 'Als Vorspeise möchte ich die Suppe, bitte.' },
        { speaker: 'Kellner', text: '¿Y de segundo?', german: 'Und als Hauptgericht?' },
        { speaker: 'Du', text: 'De segundo prefiero el pescado.', german: 'Als Hauptgericht nehme ich lieber den Fisch.' },
      ],
      gapIndex: 3,
      options: ['De segundo prefiero el pescado.', 'De segundo prefero el pescado.', 'De postre quiero el pescado.', 'De segundo pido la cuenta.'],
      answer: 0,
      feedback: {
        rule: 'Der Kellner fragt nach dem Hauptgericht (`de segundo`) → `De segundo prefiero …`.',
        why: '„prefero“ fehlt der Stammwechsel (prefiero); `de postre` ist der Nachtisch; die Rechnung passt hier noch nicht.',
        avoid: 'Greif die Frage des Kellners auf: `¿Y de segundo?` → `De segundo …`',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: SC,
      difficulty: 2,
      prompt: 'Du bist im Restaurant. Bestelle ein komplettes Menü (Vorspeise, Hauptgericht, Nachtisch, Getränk) und bitte am Ende um die Rechnung.',
      requirements: [
        { pattern: 'de primero|de entrada', hint: 'die Vorspeise mit „de primero“' },
        { pattern: 'de segundo|plato fuerte', hint: 'das Hauptgericht mit „de segundo“' },
        { pattern: 'postre', hint: 'einen Nachtisch („de postre“)' },
        { pattern: '\\b(quiero|prefiero|pido|quisiera)\\b', hint: 'eine Form von querer, preferir oder pedir' },
        { pattern: 'cuenta', hint: 'die Bitte um die Rechnung („la cuenta“)' },
      ],
      samples: [
        'De primero quiero una ensalada. De segundo prefiero el pescado. De postre pido un flan y para beber, agua sin gas. ¿Me trae la cuenta, por favor?',
      ],
      minWords: 15,
      feedback: {
        rule: 'Bestellen: `De primero quiero …`, `De segundo prefiero …`, `De postre pido …`; Rechnung: `¿Me trae la cuenta, por favor?`',
        why: 'Typische Fehler: `quero`/`prefero` ohne ie und `pedo` statt `pido`.',
        avoid: 'Kontrolliere jedes Verb: betonter Stamm → quie-, prefie-, pi-.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: SC,
      difficulty: 2,
      prompt: 'Du bist mit einer Freundin im Restaurant. Sag laut, was du bestellst und was du lieber magst (mindestens 2 Sätze).',
      keywords: ['quiero', 'prefiero', 'pido', 'de primero', 'de segundo', 'postre', 'carne', 'pescado', 'sopa', 'ensalada', 'agua', 'vino'],
      minMatch: 3,
      sample: 'De primero quiero una sopa. De segundo prefiero la carne y de postre pido un flan.',
      feedback: {
        rule: '`quiero` (ich möchte), `prefiero` (ich nehme lieber), `pido` (ich bestelle).',
        why: 'Werden zu wenige Schlüsselwörter erkannt, fehlt meist das Verb oder das Gericht.',
        avoid: 'Das r in `primero` und `quiero` ist ein kurzer Zungenschlag – nicht gerollt und nicht wie das deutsche Rachen-R.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: SC,
      difficulty: 2,
      scenarioId: 'es.sc.restaurant',
      goal: 'Bestelle im Restaurant ein Menü mit Vorspeise, Hauptgericht und Nachtisch, sag, was du lieber magst (prefiero …), und verlange zum Schluss die Rechnung.',
      turns: 5,
      feedback: {
        rule: '`De primero quiero …` – `Prefiero …` – `¿Me trae la cuenta, por favor?`',
        why: 'Im Gespräch rutschen leicht Formen ohne Stammwechsel heraus (`quero`) – achte bewusst auf quiero/prefiero/pido.',
        avoid: 'Leg dir vorher dein Menü zurecht: drei Gänge, ein Getränk, die Rechnung.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['reading'],
      topicIds: SC,
      difficulty: 1,
      prompt: 'Kultur: Du hast in Madrid gut gegessen. Wie ist es mit dem Trinkgeld (`la propina`)?',
      options: [
        { text: 'Freiwillig – man rundet auf oder lässt bei gutem Service etwa 5–10 % liegen.' },
        { text: 'Pflicht – mindestens 20 % werden erwartet.', why: 'Das gilt eher für die USA. In Spanien ist Trinkgeld freiwillig und meist kleiner.' },
        { text: 'Trinkgeld gilt in Spanien als Beleidigung.', why: 'Nein – ein kleines Trinkgeld wird gern angenommen, es ist nur keine Pflicht.' },
        { text: 'Man gibt es immer direkt dem Koch in der Küche.', why: 'Das Trinkgeld lässt man am Tisch oder gibt es beim Bezahlen dem Kellner.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Spanien: Trinkgeld freiwillig (aufrunden, ca. 5–10 %). Mexiko: 10–15 % üblich.',
        why: 'Die Gepflogenheiten unterscheiden sich stark von Land zu Land.',
        avoid: 'Schau auf die Rechnung: Steht dort schon ein Servicebetrag, ist das Trinkgeld oft bereits enthalten.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: ['es.g.gustar'],
      difficulty: 2,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'Me gustan el pescado.',
      answers: ['Me gusta el pescado.'],
      german: 'Ich mag Fisch.',
      feedback: {
        rule: '`gustar` richtet sich nach dem, was gefällt: ein Ding → `gusta`, mehrere → `gustan`.',
        why: '`el pescado` ist Singular, also `me gusta`. `me gustan` passt zu `las ensaladas` oder `los postres`.',
        avoid: 'Frag dich: Was gefällt? Eins → gusta. Mehrere → gustan.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading'],
      topicIds: ['es.g.ir-venir'],
      difficulty: 2,
      direction: 'toGerman',
      source: '¿Vienes al restaurante en metro o a pie?',
      answers: [
        'Kommst du mit der U-Bahn oder zu Fuß zum Restaurant?',
        'Kommst du mit der U-Bahn oder zu Fuß ins Restaurant?',
        'Kommst du mit der Metro oder zu Fuß zum Restaurant?',
        'Kommst du mit der Metro oder zu Fuß ins Restaurant?',
        'Kommst du mit der U-Bahn zum Restaurant oder zu Fuß?',
        'Kommst du zu Fuß oder mit der U-Bahn zum Restaurant?',
      ],
      feedback: {
        rule: '`venir` = kommen (zum Sprecher hin); `en metro` = mit der U-Bahn; `a pie` = zu Fuß.',
        why: '`en metro` wird manchmal als „in der Metro“ übersetzt – gemeint ist aber das Verkehrsmittel: „mit der U-Bahn“.',
        avoid: 'en + Verkehrsmittel = „mit dem/der …“.',
      },
    },
  ],
};

export default lesson;
