import type { Lesson } from '../../types';

const L = 'es.a1.l09';
const NUM = ['es.g.numbers-big'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c3',
  order: 9,
  title: 'Auf dem Markt – Mengen & Preise',
  subtitle: 'Kilo, Dutzend, Flasche und die Zahlen bis 1000',
  icon: '🧺',
  minutes: 12,
  goal:
    'Du kaufst auf dem Markt ein: Du nennst **Mengen** (`un kilo de tomates`, `medio kilo de queso`, `una docena de huevos`), fragst nach **Preisen** (`¿Cuánto cuesta?` / `¿Cuánto cuestan?`) und verstehst die **Zahlen von 100 bis 1000** – inklusive der Frage, wann es `cien` und wann `ciento` heißt.',
  canDo: [
    'Ich kann Mengen mit un kilo de, medio kilo de, una docena de, una botella de und una lata de angeben.',
    'Ich kann die Zahlen von 100 bis 1000 sagen, schreiben und in Preisen verstehen.',
    'Ich weiß, wann es cien und wann ciento heißt und wann die Hunderter weiblich werden.',
    'Ich kann auf dem Markt bestellen und nach dem Preis fragen.',
  ],
  topicIds: NUM,
  vocab: [
    { id: `${L}.v.mercado`, target: 'el mercado', german: 'der Markt', pos: 'noun', gender: 'm', plural: 'los mercados', emoji: '🧺', field: 'Einkaufen', stageId: 'a1', lessonId: L, example: { target: 'Los sábados voy al mercado.', german: 'Samstags gehe ich auf den Markt.' } },
    { id: `${L}.v.kilo`, target: 'el kilo', german: 'das Kilo', pos: 'noun', gender: 'm', plural: 'los kilos', emoji: '⚖️', field: 'Mengen', stageId: 'a1', lessonId: L, example: { target: 'Un kilo de tomates, por favor.', german: 'Ein Kilo Tomaten, bitte.' } },
    { id: `${L}.v.medio-kilo`, target: 'medio kilo', german: 'ein halbes Kilo', pos: 'phrase', field: 'Mengen', stageId: 'a1', lessonId: L, example: { target: 'Medio kilo de queso, por favor.', german: 'Ein halbes Kilo Käse, bitte.' } },
    { id: `${L}.v.docena`, target: 'la docena', german: 'das Dutzend', pos: 'noun', gender: 'f', plural: 'las docenas', emoji: '🥚', field: 'Mengen', stageId: 'a1', lessonId: L, example: { target: 'Una docena de huevos, por favor.', german: 'Ein Dutzend Eier, bitte.' } },
    { id: `${L}.v.botella`, target: 'la botella', german: 'die Flasche', pos: 'noun', gender: 'f', plural: 'las botellas', emoji: '🍾', field: 'Mengen', stageId: 'a1', lessonId: L, example: { target: 'Una botella de agua, por favor.', german: 'Eine Flasche Wasser, bitte.' } },
    { id: `${L}.v.lata`, target: 'la lata', german: 'die Dose', pos: 'noun', gender: 'f', plural: 'las latas', emoji: '🥫', field: 'Mengen', stageId: 'a1', lessonId: L, example: { target: 'Dos latas de atún, por favor.', german: 'Zwei Dosen Thunfisch, bitte.' } },
    { id: `${L}.v.tomate`, target: 'el tomate', german: 'die Tomate', pos: 'noun', gender: 'm', plural: 'los tomates', emoji: '🍅', field: 'Lebensmittel', stageId: 'a1', lessonId: L, example: { target: '¿Cuánto cuestan los tomates?', german: 'Was kosten die Tomaten?' } },
    { id: `${L}.v.huevo`, target: 'el huevo', german: 'das Ei', pos: 'noun', gender: 'm', plural: 'los huevos', emoji: '🥚', field: 'Lebensmittel', stageId: 'a1', lessonId: L, example: { target: 'Una docena de huevos cuesta tres euros.', german: 'Ein Dutzend Eier kostet drei Euro.' } },
    { id: `${L}.v.queso`, target: 'el queso', german: 'der Käse', pos: 'noun', gender: 'm', plural: 'los quesos', emoji: '🧀', field: 'Lebensmittel', stageId: 'a1', lessonId: L, example: { target: 'El queso de aquí es muy bueno.', german: 'Der Käse von hier ist sehr gut.' } },
    { id: `${L}.v.patata`, target: 'la patata', german: 'die Kartoffel', pos: 'noun', gender: 'f', plural: 'las patatas', emoji: '🥔', variant: 'es-ES', field: 'Lebensmittel', stageId: 'a1', lessonId: L, example: { target: 'Dos kilos de patatas, por favor.', german: 'Zwei Kilo Kartoffeln, bitte.' } },
    { id: `${L}.v.papa`, target: 'la papa', german: 'die Kartoffel', pos: 'noun', gender: 'f', plural: 'las papas', emoji: '🥔', variant: 'es-LA', field: 'Lebensmittel', stageId: 'a1', lessonId: L, example: { target: 'Dos kilos de papas, por favor.', german: 'Zwei Kilo Kartoffeln, bitte.' } },
    { id: `${L}.v.ciento`, target: 'ciento', german: 'hundert (mit weiterer Zahl: ciento uno, ciento veinte …)', pos: 'num', field: 'Zahlen', stageId: 'a1', lessonId: L, example: { target: 'Son ciento veinte euros.', german: 'Das macht hundertzwanzig Euro.' } },
    { id: `${L}.v.doscientos`, target: 'doscientos, doscientas', german: 'zweihundert', pos: 'num', field: 'Zahlen', stageId: 'a1', lessonId: L, example: { target: 'Hay doscientas personas en el mercado.', german: 'Auf dem Markt sind zweihundert Menschen.' } },
    { id: `${L}.v.quinientos`, target: 'quinientos, quinientas', german: 'fünfhundert', pos: 'num', field: 'Zahlen', stageId: 'a1', lessonId: L, example: { target: 'La bicicleta cuesta quinientos euros.', german: 'Das Fahrrad kostet fünfhundert Euro.' } },
    { id: `${L}.v.mil`, target: 'mil', german: 'tausend', pos: 'num', field: 'Zahlen', stageId: 'a1', lessonId: L, example: { target: 'Mil gracias.', german: 'Tausend Dank.' } },
    { id: `${L}.v.algo-mas`, target: '¿Algo más?', german: 'Sonst noch etwas?', pos: 'phrase', field: 'Einkaufen', stageId: 'a1', lessonId: L, example: { target: '¿Algo más? – No, nada más, gracias.', german: 'Sonst noch etwas? – Nein, nichts weiter, danke.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Auf dem Markt kaufst du fast immer mit einer **Mengenangabe** ein: `un kilo de`, `medio kilo de`, `una docena de`, `una botella de`, `una lata de`. Danach folgt das Produkt **ohne Artikel**: `un kilo de tomates`, `una botella de agua`.\nAchtung bei „ein halbes Kilo“: Vor `medio` steht **kein** `un` – es heißt einfach `medio kilo`. Ein Viertelkilo ist `un cuarto de kilo`, kleine Mengen gibt es in Gramm: `cien gramos de jamón`.',
    },
    {
      type: 'mistake',
      wrong: 'Un kilo tomates, por favor.',
      right: 'Un kilo de tomates, por favor.',
      why: 'Im Deutschen sagst du „ein Kilo Tomaten“ ohne Verbindungswort. Spanisch braucht zwischen Menge und Produkt immer `de`: `un kilo de tomates`, `una docena de huevos`, `dos latas de atún`.',
    },
    {
      type: 'table',
      title: 'Die Hunderter',
      headers: ['Zahl', 'Spanisch', 'Hinweis'],
      rows: [
        ['100', 'cien', 'allein und direkt vor einem Nomen: cien euros'],
        ['101–199', 'ciento uno … ciento noventa y nueve', 'mit weiterer Zahl: ciento veinte'],
        ['200', 'doscientos / doscientas', 'dos + cientos, in einem Wort'],
        ['300', 'trescientos / trescientas', ''],
        ['400', 'cuatrocientos / cuatrocientas', ''],
        ['500', 'quinientos / quinientas', 'unregelmäßig!'],
        ['600', 'seiscientos / seiscientas', ''],
        ['700', 'setecientos / setecientas', 'sete-, nicht siete-'],
        ['800', 'ochocientos / ochocientas', ''],
        ['900', 'novecientos / novecientas', 'nove-, nicht nueve-'],
        ['1000', 'mil', 'ohne un: mil euros, dos mil euros'],
      ],
    },
    {
      type: 'tip',
      md:
        'Merksatz: **cien steht allein, ciento hat Begleitung.** `cien euros`, aber `ciento cincuenta euros`.\nDie drei Ausreißer merkst du dir als **5 – 7 – 9**: `quinientos`, `setecientos`, `novecientos`.\nAb 200 passen sich die Hunderter an das Nomen an: `doscientos euros` (el euro), aber `doscientas personas` (la persona).',
    },
    {
      type: 'compare',
      target: 'ciento veinticinco euros',
      german: 'hundertfünfundzwanzig Euro',
      md: 'Die Zahl wird wie im Deutschen aneinandergereiht – aber in getrennten Wörtern und **ohne** `y` nach den Hundertern. `y` steht nur zwischen Zehner und Einer: `trescientos cuarenta y dos`. Außerdem steht `euros` im Plural, während man im Deutschen „zehn Euro“ sagt.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Quiero', role: 'verb' },
        { text: ' ' },
        { text: 'medio kilo', role: 'object' },
        { text: ' ' },
        { text: 'de', role: 'preposition' },
        { text: ' ' },
        { text: 'queso', role: 'noun' },
        { text: '.' },
      ],
      german: 'Ich möchte ein halbes Kilo Käse.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika bezahlst du in vielen Ländern mit **Pesos** (Mexiko, Argentinien, Kolumbien, Chile …): `Son quinientos pesos.` `el peso` ist maskulin – also `doscientos pesos`.\nDie Kartoffel heißt dort `la papa` statt `la patata`. Die Marktfrage `¿A cuánto está el kilo?` (Was kostet das Kilo gerade?) hörst du in Spanien wie in Lateinamerika.',
    },
    { type: 'audio', text: 'Un kilo de tomates, medio kilo de queso y una docena de huevos, por favor.', label: 'Bestellung am Marktstand' },
  ],
  examples: [
    {
      target: 'Un kilo de tomates, por favor.',
      german: 'Ein Kilo Tomaten, bitte.',
      parts: [
        { text: 'Un kilo', role: 'object' },
        { text: ' ' },
        { text: 'de', role: 'preposition' },
        { text: ' ' },
        { text: 'tomates', role: 'noun' },
        { text: ', por favor.' },
      ],
    },
    {
      target: '¿Cuánto cuestan las manzanas?',
      german: 'Was kosten die Äpfel?',
      parts: [
        { text: '¿Cuánto', role: 'question' },
        { text: ' ' },
        { text: 'cuestan', role: 'verb' },
        { text: ' ' },
        { text: 'las manzanas', role: 'subject' },
        { text: '?' },
      ],
      note: 'Plural (`las manzanas`) → `cuestan`; Singular (`el queso`) → `cuesta`.',
    },
    {
      target: 'Son ciento cincuenta euros.',
      german: 'Das macht hundertfünfzig Euro.',
      parts: [
        { text: 'Son', role: 'verb' },
        { text: ' ' },
        { text: 'ciento cincuenta', role: 'adjective' },
        { text: ' ' },
        { text: 'euros', role: 'noun' },
        { text: '.' },
      ],
      note: 'Nach 100 folgt noch eine Zahl – deshalb `ciento`, nicht `cien`.',
    },
    { target: 'Cien gramos de jamón, por favor.', german: 'Hundert Gramm Schinken, bitte.', note: '`cien` steht direkt vor dem Nomen – ohne `un`.' },
    { target: 'Hay doscientas personas en el mercado.', german: 'Auf dem Markt sind zweihundert Menschen.', note: '`la persona` ist feminin, deshalb `doscientas`.' },
    { target: 'Una botella de agua y dos latas de atún.', german: 'Eine Flasche Wasser und zwei Dosen Thunfisch.' },
    { target: 'Son quinientos pesos.', german: 'Das macht fünfhundert Pesos.', variant: 'es-LA' },
    { target: 'Mil gracias.', german: 'Tausend Dank.', note: '`mil` steht ohne `un` – anders als „eintausend“.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: NUM,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '🍅', word: 'el tomate' },
        { emoji: '🥚', word: 'el huevo' },
        { emoji: '🧀', word: 'el queso' },
        { emoji: '🥫', word: 'la lata' },
        { emoji: '🍾', word: 'la botella' },
      ],
      feedback: {
        rule: 'Marktwörter immer mit Artikel lernen: `el tomate`, `el huevo`, `el queso`, `la lata`, `la botella`.',
        why: '`el tomate` endet auf -e und ist trotzdem maskulin – das Geschlecht verrät hier nur der Artikel.',
        avoid: 'Sprich beim Lernen den Artikel immer mit: „el tomate, la lata“. So merkst du dir das Geschlecht automatisch.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: NUM,
      difficulty: 1,
      instruction: 'Ordne jeder Zahl das passende Zahlwort zu.',
      pairs: [
        { left: '100', right: 'cien' },
        { left: '200', right: 'doscientos' },
        { left: '500', right: 'quinientos' },
        { left: '700', right: 'setecientos' },
        { left: '900', right: 'novecientos' },
        { left: '1000', right: 'mil' },
      ],
      feedback: {
        rule: 'Die meisten Hunderter sind Zahl + `cientos` (`doscientos`, `ochocientos`). Unregelmäßig: `quinientos` (500), `setecientos` (700), `novecientos` (900).',
        why: 'Wer nach dem Muster „cinco → cincocientos“ oder „nueve → nuevecientos“ bildet, landet bei Formen, die es nicht gibt.',
        avoid: 'Merke die Ausreißer als Reihe: 5 – 7 – 9 = quinientos, setecientos, novecientos.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: NUM,
      difficulty: 1,
      prompt: 'Das Fahrrad kostet 100 Euro. Welche Form passt? `Son ___ euros.`',
      options: [
        { text: 'cien' },
        { text: 'ciento', why: '`ciento` steht nur, wenn noch eine Zahl folgt: `ciento diez euros`.' },
        { text: 'un cien', why: 'Vor `cien` steht nie `un` – anders als im deutschen „einhundert“.' },
        { text: 'cientos', why: '`cientos` bedeutet „Hunderte“ (`cientos de personas`), nicht 100.' },
      ],
      answer: 0,
      feedback: {
        rule: '100 allein oder direkt vor einem Nomen heißt `cien`: `cien euros`, `cien gramos`.',
        why: '`ciento` braucht eine weitere Zahl dahinter (`ciento uno`, `ciento veinte`).',
        avoid: 'Merksatz: cien steht allein, ciento hat Begleitung.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: NUM,
      difficulty: 2,
      instruction: 'Ergänze die Mengenangaben.',
      sentence: 'Quiero un kilo ___ tomates y ___ kilo de queso.',
      answers: [['de'], ['medio']],
      bank: ['de', 'medio', 'un medio', 'del'],
      german: 'Ich möchte ein Kilo Tomaten und ein halbes Kilo Käse.',
      feedback: {
        rule: 'Menge + `de` + Produkt ohne Artikel: `un kilo de tomates`. „Ein halbes Kilo“ heißt `medio kilo` – ohne `un`.',
        why: '`del` (= de + el) würde einen Artikel einführen, den es hier nicht gibt. `un medio kilo` ist eine wörtliche Übersetzung aus dem Deutschen.',
        avoid: 'Lerne die Mengen als feste Blöcke: `un kilo de …`, `medio kilo de …`, `una docena de …`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: NUM,
      difficulty: 2,
      audio: 'El jamón cuesta ciento ochenta euros.',
      question: 'Was kostet der Schinken?',
      options: ['180 €', '118 €', '108 €', '800 €'],
      answer: 0,
      feedback: {
        rule: '`ciento ochenta` = 100 + 80 = 180. `ciento dieciocho` wäre 118, `ochocientos` 800.',
        why: '`ochenta` (80) und `ochocientos` (800) beginnen gleich – entscheidend ist das Ende: -enta = Zehner, -cientos = Hunderter.',
        avoid: 'Hör auf die Endung: -enta → Zehner (ochenta = 80), -cientos → Hunderter (ochocientos = 800).',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: NUM,
      difficulty: 2,
      instruction: 'Bilde die Frage „Was kostet ein Kilo Tomaten?“.',
      tokens: ['¿Cuánto', 'cuesta', 'un', 'kilo', 'de', 'tomates?'],
      extra: ['cuestan'],
      german: 'Was kostet ein Kilo Tomaten?',
      feedback: {
        rule: 'Das Verb richtet sich nach `un kilo` (Singular): `¿Cuánto cuesta un kilo de tomates?`',
        why: '`cuestan` passt nicht, obwohl `tomates` im Plural steht – das Subjekt ist das eine Kilo.',
        avoid: 'Frag dich: Was kostet etwas? Das Kilo → `cuesta`. Die Tomaten (ohne Menge) → `cuestan`.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: NUM,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Ich möchte ein halbes Kilo Käse und eine Flasche Wasser.',
      answers: [
        'Quiero medio kilo de queso y una botella de agua.',
        'Yo quiero medio kilo de queso y una botella de agua.',
        'Quisiera medio kilo de queso y una botella de agua.',
        'Yo quisiera medio kilo de queso y una botella de agua.',
        'Me gustaría medio kilo de queso y una botella de agua.',
      ],
      feedback: {
        rule: '`medio kilo de queso` (ohne un), `una botella de agua` (mit de, ohne Artikel vor dem Produkt).',
        why: 'Typisch sind `un medio kilo` und das fehlende `de`: „una botella agua“.',
        avoid: 'Prüfe nach jeder Menge: Steht ein `de` dahinter? Und steht vor `medio` nichts?',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: NUM,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'Un medio kilo de queso, por favor.',
      answers: ['Medio kilo de queso, por favor.'],
      german: 'Ein halbes Kilo Käse, bitte.',
      feedback: {
        rule: '„Ein halbes …“ heißt `medio` / `media` – ohne unbestimmten Artikel: `medio kilo`, `media docena`.',
        why: 'Das deutsche „ein halbes“ verleitet zu `un medio`. `medio` enthält das „ein“ schon.',
        avoid: 'Denk an `media hora` (eine halbe Stunde) – auch dort steht kein `una`.',
      },
    },
  ],
  pronunciation: ['es.p.vowels.euro', 'es.p.cz.cinco', 'es.p.j.jamon'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: NUM,
      difficulty: 2,
      instruction: 'Ergänze deine Antwort am Marktstand.',
      lines: [
        { speaker: 'Vendedora', text: '¡Buenos días! ¿Qué desea?', german: 'Guten Morgen! Was darf es sein?' },
        { speaker: 'Du', text: 'Un kilo de tomates, por favor.', german: 'Ein Kilo Tomaten, bitte.' },
        { speaker: 'Vendedora', text: 'Aquí tiene. ¿Algo más?', german: 'Bitte schön. Sonst noch etwas?' },
        { speaker: 'Du', text: 'Sí, medio kilo de queso. ¿Cuánto es todo?', german: 'Ja, ein halbes Kilo Käse. Was macht das zusammen?' },
        { speaker: 'Vendedora', text: 'Son nueve euros con cincuenta.', german: 'Das macht neun Euro fünfzig.' },
      ],
      gapIndex: 3,
      options: [
        'Sí, medio kilo de queso. ¿Cuánto es todo?',
        'Sí, un medio kilo de queso. ¿Cuánto es todo?',
        'Sí, medio kilo queso. ¿Cuánto es todo?',
        'Sí, medio de kilo queso. ¿Cuánto es todo?',
      ],
      answer: 0,
      feedback: {
        rule: '`medio kilo de queso`: kein `un` vor medio, `de` zwischen Menge und Produkt. Mit `¿Cuánto es todo?` fragst du nach dem Gesamtpreis.',
        why: 'Die anderen Antworten haben ein überflüssiges `un`, ein fehlendes `de` oder eine falsche Wortstellung.',
        avoid: 'Lies die Menge laut als Block: „medio kilo de …“ – so klingt es richtig.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: NUM,
      difficulty: 2,
      prompt: 'Du stehst am Marktstand. Schreib 3–4 Sätze: Begrüße die Verkäuferin, bestelle mindestens zwei Produkte mit Mengenangabe und frag nach dem Preis.',
      requirements: [
        { pattern: '\\b(kilos?|docenas?|botellas?|latas?|gramos)\\b', hint: 'eine Mengenangabe (kilo, docena, botella, lata …)' },
        { pattern: '\\b(kilos?|docenas?|botellas?|latas?|gramos) de\\b', hint: 'Menge + de + Produkt (z. B. „un kilo de tomates“)' },
        { pattern: '(cu[aá]nto|cuesta|cuestan|vale|valen)', hint: 'eine Preisfrage (¿Cuánto cuesta …? / ¿Cuánto es?)' },
      ],
      samples: [
        'Buenos días. Quiero un kilo de tomates y una docena de huevos. También quiero medio kilo de queso. ¿Cuánto es?',
      ],
      minWords: 12,
      feedback: {
        rule: 'Menge + `de` + Produkt: `un kilo de tomates`; Preisfrage: `¿Cuánto cuesta …?` / `¿Cuánto es?`',
        why: 'Häufig fehlt das `de` nach der Menge oder vor `medio` steht ein überflüssiges `un`.',
        avoid: 'Unterstreiche in Gedanken jede Menge und prüfe, ob direkt danach `de` kommt.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: NUM,
      difficulty: 2,
      prompt: 'Bestelle laut auf dem Markt: zwei Produkte mit Mengenangabe und eine Frage nach dem Preis.',
      keywords: ['kilo', 'medio', 'docena', 'botella', 'lata', 'gramos', 'cuánto', 'cuesta', 'cuestan', 'favor'],
      minMatch: 3,
      sample: 'Un kilo de tomates y una docena de huevos, por favor. ¿Cuánto cuesta?',
      feedback: {
        rule: 'Bestellen: `Un kilo de …, por favor.` – Preis: `¿Cuánto cuesta?` / `¿Cuánto es?`',
        why: 'Wenn zu wenige Schlüsselwörter erkannt werden, fehlt meist die Menge (kilo, docena …) oder die Preisfrage.',
        avoid: 'Sprich die Menge deutlich und ohne Pause bis zum Produkt: „un-KI-lo-de-to-MA-tes“.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: NUM,
      difficulty: 2,
      scenarioId: 'es.sc.einkaufen',
      goal: 'Kauf auf dem Markt ein: Verlange mindestens zwei Produkte mit Mengenangabe (un kilo de …, una docena de …), frag nach dem Preis und bezahle.',
      turns: 4,
      feedback: {
        rule: 'Mengen mit `de`, Preisfragen mit `¿Cuánto cuesta / cuestan …?`, zum Schluss `¿Cuánto es todo?`',
        why: 'Im Gespräch rutscht leicht „un kilo tomates“ heraus – das `de` fehlt dann.',
        avoid: 'Leg dir vorher deine Einkaufsliste auf Spanisch zurecht, z. B. „un kilo de tomates, media docena de huevos“.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.stem-change'],
      difficulty: 1,
      verb: 'querer',
      tense: 'Präsens',
      person: 'nosotros',
      sentence: 'Nosotros ___ dos cafés con leche.',
      answers: ['queremos'],
      feedback: {
        rule: '`querer` (e → ie): quiero, quieres, quiere, **queremos**, queréis, quieren.',
        why: '„quieremos“ ist falsch: Bei nosotros liegt die Betonung auf der Endung (que-RE-mos), deshalb bleibt das e.',
        avoid: 'nosotros und vosotros sind bei Stammwechselverben fast immer regelmäßig – wie bei `tenemos`.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.numbers'],
      difficulty: 1,
      prompt: 'Wiederholung Zahlen: Wie schreibt man **75**?',
      options: [
        { text: 'setenta y cinco' },
        { text: 'sesenta y cinco', why: '`sesenta` ist 60 – das ergibt 65.' },
        { text: 'setenta cinco', why: 'Zwischen Zehner und Einer fehlt das `y`.' },
        { text: 'setecientos cinco', why: '`setecientos` ist 700 – das ergibt 705.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Ab 31 werden Zehner und Einer mit `y` verbunden: `setenta y cinco`.',
        why: '`setenta` (70), `sesenta` (60) und `setecientos` (700) klingen ähnlich – achte auf den genauen Wortanfang und die Endung.',
        avoid: 'sie-te → se-tenta → sete-cientos: Bei 70 und 700 fällt das i aus.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.gustar'],
      difficulty: 2,
      instruction: 'Wiederholung gustar: Setze die passende Form ein.',
      sentence: '¿Te ___ los tomates? – Sí, me ___ mucho.',
      answers: [['gustan'], ['gustan']],
      bank: ['gusta', 'gustan', 'gusto'],
      german: 'Magst du Tomaten? – Ja, ich mag sie sehr.',
      feedback: {
        rule: '`gustar` richtet sich nach dem, was gefällt: `los tomates` (Plural) → `gustan`.',
        why: '`gusta` passt nur zu einer Sache im Singular; `gusto` ist hier falsch, weil nicht „ich“ gefalle.',
        avoid: 'Such das Nomen nach dem Verb: Plural → gustan, Singular → gusta.',
      },
    },
  ],
};

export default lesson;
