import type { Lesson } from '../../types';

const L = 'es.a1.l04';
const IR = ['es.g.ir-a'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c1',
  order: 4,
  title: 'Pläne – ir a + Infinitiv',
  subtitle: 'Über morgen, das Wochenende und die nahe Zukunft sprechen',
  icon: '🗓️',
  minutes: 11,
  goal:
    'Du lernst das unregelmäßige Verb **ir** (gehen, fahren) und sprichst mit `ir a` + Infinitiv über **Pläne**: `Mañana voy a visitar a mis abuelos.` Außerdem sagst du, wohin du gehst – inklusive `a` + `el` = `al`.',
  canDo: [
    'Ich kann ir im Präsens konjugieren.',
    'Ich kann mit ir a + Infinitiv sagen, was ich vorhabe.',
    'Ich kann andere fragen, was sie am Wochenende machen.',
    'Ich kann sagen, wohin ich gehe, und a + el zu al zusammenziehen.',
  ],
  topicIds: IR,
  vocab: [
    { id: `${L}.v.ir`, target: 'ir', german: 'gehen / fahren', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Voy a Madrid.', german: 'Ich fahre nach Madrid.' } },
    { id: `${L}.v.hacer`, target: 'hacer', german: 'machen / tun', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: '¿Qué vas a hacer?', german: 'Was hast du vor?' } },
    { id: `${L}.v.manana-morgen`, target: 'mañana', german: 'morgen', pos: 'adv', field: 'Zeitangaben', stageId: 'a1', lessonId: L, example: { target: 'Mañana voy a trabajar.', german: 'Morgen arbeite ich.' } },
    { id: `${L}.v.esta-noche`, target: 'esta noche', german: 'heute Abend / heute Nacht', pos: 'phrase', emoji: '🌙', field: 'Zeitangaben', stageId: 'a1', lessonId: L, example: { target: 'Esta noche vamos a salir.', german: 'Heute Abend gehen wir aus.' } },
    { id: `${L}.v.fin-de-semana`, target: 'el fin de semana', german: 'das Wochenende', pos: 'noun', gender: 'm', plural: 'los fines de semana', field: 'Zeitangaben', stageId: 'a1', lessonId: L, example: { target: '¿Qué vas a hacer el fin de semana?', german: 'Was machst du am Wochenende?' } },
    { id: `${L}.v.sabado`, target: 'el sábado', german: 'der Samstag / am Samstag', pos: 'noun', gender: 'm', plural: 'los sábados', field: 'Zeitangaben', stageId: 'a1', lessonId: L, example: { target: 'El sábado vamos a la playa.', german: 'Am Samstag fahren wir an den Strand.' } },
    { id: `${L}.v.domingo`, target: 'el domingo', german: 'der Sonntag / am Sonntag', pos: 'noun', gender: 'm', plural: 'los domingos', field: 'Zeitangaben', stageId: 'a1', lessonId: L, example: { target: 'El domingo voy a descansar.', german: 'Am Sonntag ruhe ich mich aus.' } },
    { id: `${L}.v.proxima-semana`, target: 'la próxima semana', german: 'nächste Woche', pos: 'phrase', field: 'Zeitangaben', stageId: 'a1', lessonId: L, example: { target: 'La próxima semana voy a viajar.', german: 'Nächste Woche verreise ich.' } },
    { id: `${L}.v.descansar`, target: 'descansar', german: 'sich ausruhen', pos: 'verb', emoji: '🛋️', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Esta tarde voy a descansar.', german: 'Heute Nachmittag ruhe ich mich aus.' } },
    { id: `${L}.v.visitar`, target: 'visitar', german: 'besuchen', pos: 'verb', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Voy a visitar a mis abuelos.', german: 'Ich werde meine Großeltern besuchen.' } },
    { id: `${L}.v.salir`, target: 'salir', german: 'ausgehen / hinausgehen', pos: 'verb', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Esta noche no vamos a salir.', german: 'Heute Abend gehen wir nicht aus.' } },
    { id: `${L}.v.estudiar`, target: 'estudiar', german: 'lernen / studieren', pos: 'verb', emoji: '📚', field: 'Alltag', stageId: 'a1', lessonId: L, example: { target: 'Voy a estudiar español.', german: 'Ich werde Spanisch lernen.' } },
    { id: `${L}.v.cine`, target: 'el cine', german: 'das Kino', pos: 'noun', gender: 'm', plural: 'los cines', emoji: '🎬', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¡Vamos al cine!', german: 'Lass uns ins Kino gehen!' } },
    { id: `${L}.v.museo`, target: 'el museo', german: 'das Museum', pos: 'noun', gender: 'm', plural: 'los museos', emoji: '🏛️', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'El domingo vamos al museo.', german: 'Am Sonntag gehen wir ins Museum.' } },
    { id: `${L}.v.fiesta`, target: 'la fiesta', german: 'die Party / das Fest', pos: 'noun', gender: 'f', plural: 'las fiestas', emoji: '🎉', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'Esta noche hay una fiesta.', german: 'Heute Abend gibt es eine Party.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        '**ir** (gehen, fahren) ist völlig unregelmäßig. Mit `ir a` + **Infinitiv** sprichst du über Pläne und die nahe Zukunft – wie „Ich werde …“ oder „Ich habe vor, …“: `Voy a viajar.` = „Ich werde verreisen.“\nDas Beste daran: Das zweite Verb bleibt **immer im Infinitiv**. Du musst nur `ir` konjugieren.',
    },
    {
      type: 'conjugation',
      verb: 'ir',
      translation: 'gehen / fahren',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'voy' },
        { person: 'tú', form: 'vas' },
        { person: 'él / ella / usted', form: 'va' },
        { person: 'nosotros / nosotras', form: 'vamos' },
        { person: 'vosotros / vosotras', form: 'vais', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'van' },
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Mañana', role: 'adverb' },
        { text: ' ' },
        { text: 'voy', role: 'verb' },
        { text: ' ' },
        { text: 'a', role: 'preposition' },
        { text: ' ' },
        { text: 'visitar', role: 'verb' },
        { text: ' ' },
        { text: 'a mis abuelos', role: 'object' },
        { text: '.' },
      ],
      german: 'Morgen besuche ich meine Großeltern.',
    },
    {
      type: 'compare',
      target: 'El sábado voy a cocinar.',
      german: 'Am Samstag koche ich. / Am Samstag werde ich kochen.',
      md: 'Im Deutschen reicht für Pläne oft das Präsens mit Zeitangabe. Spanisch benutzt dafür im Alltag sehr häufig `ir a` + Infinitiv. Und: „am Samstag“ heißt einfach `el sábado` – ohne Präposition.',
    },
    {
      type: 'mistake',
      wrong: 'Voy cocinar.',
      right: 'Voy a cocinar.',
      why: 'Das kleine `a` zwischen ir und dem Infinitiv ist Pflicht. Genauso falsch: `Voy a cocino` – nach `a` folgt immer der Infinitiv.',
    },
    {
      type: 'text',
      md:
        '`ir a` + **Ort** heißt „zu / nach … gehen oder fahren“: `Voy a Madrid.` Trifft `a` auf den Artikel `el`, verschmelzen beide zu **al**: `Vamos al cine` (nicht „a el cine“). Mit `la` bleibt es getrennt: `Voy a la playa.`\nBeides lässt sich kombinieren: `Voy a ir al museo.` – „Ich werde ins Museum gehen.“',
    },
    {
      type: 'tip',
      md:
        '- `mañana` = morgen · `la mañana` = der Morgen · `mañana por la mañana` = morgen früh\n- `¡Vamos a …!` heißt auch „Lass(t) uns …!“: `¡Vamos a bailar!`\n- Verneinung vor ir: `No voy a trabajar.`',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md:
        'Unter Freunden fragt man in Spanien mit vosotros: `¿Qué vais a hacer el sábado?` – „Was habt ihr am Samstag vor?“ In Lateinamerika heißt es `¿Qué van a hacer el sábado?`',
    },
  ],
  examples: [
    {
      target: 'Voy a estudiar español.',
      german: 'Ich werde Spanisch lernen.',
      parts: [
        { text: 'Voy', role: 'verb' },
        { text: ' ' },
        { text: 'a', role: 'preposition' },
        { text: ' ' },
        { text: 'estudiar', role: 'verb' },
        { text: ' ' },
        { text: 'español', role: 'object' },
        { text: '.' },
      ],
    },
    {
      target: '¿Qué vas a hacer mañana?',
      german: 'Was machst du morgen? / Was hast du morgen vor?',
      parts: [
        { text: '¿Qué', role: 'question' },
        { text: ' ' },
        { text: 'vas', role: 'verb' },
        { text: ' ' },
        { text: 'a', role: 'preposition' },
        { text: ' ' },
        { text: 'hacer', role: 'verb' },
        { text: ' ' },
        { text: 'mañana', role: 'adverb' },
        { text: '?' },
      ],
    },
    {
      target: 'El sábado vamos a la playa.',
      german: 'Am Samstag fahren wir an den Strand.',
      note: 'Hier bedeutet `ir a` + Ort „fahren nach / gehen zu“ – keine Zukunftsform.',
    },
    {
      target: 'Mañana por la mañana voy a visitar a mi abuela.',
      german: 'Morgen früh besuche ich meine Großmutter.',
      note: 'Vor Personen als Objekt steht ein kleines `a`: `visitar a mi abuela`. Das lernst du später genauer.',
    },
    {
      target: 'No voy a trabajar el domingo.',
      german: 'Am Sonntag werde ich nicht arbeiten.',
      note: '`no` steht vor der konjugierten Form von ir.',
    },
    {
      target: '¡Vamos al cine!',
      german: 'Lass uns ins Kino gehen!',
      note: '`a` + `el` = `al`.',
    },
    {
      target: 'Esta noche mis amigos van a salir.',
      german: 'Heute Abend gehen meine Freunde aus.',
    },
    { target: '¿Vais a ir a la fiesta?', german: 'Geht ihr zur Party?', variant: 'es-ES' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: IR,
      difficulty: 1,
      instruction: 'Ordne jedem Pronomen die passende Form von „ir“ zu.',
      pairs: [
        { left: 'yo', right: 'voy' },
        { left: 'tú', right: 'vas' },
        { left: 'usted', right: 'va' },
        { left: 'nosotros', right: 'vamos' },
        { left: 'ellas', right: 'van' },
      ],
      feedback: {
        rule: '`ir`: voy, vas, va, vamos, (vais), van. Die Endungen ähneln denen der -ar-Verben.',
        why: '`usted` steht in der 3. Person → `va`, obwohl man die Person direkt anspricht.',
        avoid: 'Sprich die Reihe laut wie einen Rhythmus: voy – vas – va – vamos – van.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: IR,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '🎬', word: 'el cine' },
        { emoji: '🏛️', word: 'el museo' },
        { emoji: '🎉', word: 'la fiesta' },
        { emoji: '📚', word: 'estudiar' },
        { emoji: '🛋️', word: 'descansar' },
      ],
      feedback: {
        rule: 'Orte mit Artikel lernen: `el cine`, `el museo`, `la fiesta` – der Artikel entscheidet später über `al` oder `a la`.',
        why: '`descansar` heißt „sich ausruhen“, nicht „tanzen“ (bailar) oder „schlafen“ (dormir).',
        avoid: 'Bilde gleich einen Plan: `Voy a ir al cine.` / `Voy a descansar.`',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: IR,
      difficulty: 1,
      prompt: 'Welcher Satz bedeutet „Ich werde kochen“?',
      options: [
        { text: 'Voy a cocinar.' },
        { text: 'Voy cocinar.', why: 'Zwischen ir und dem Infinitiv fehlt das `a`.' },
        { text: 'Voy a cocino.', why: 'Nach `ir a` steht immer der Infinitiv: `cocinar`.' },
        { text: 'Va a cocinar.', why: '`va` ist er/sie/usted. Für „ich“ brauchst du `voy`.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Form: konjugiertes **ir** + **a** + **Infinitiv**.',
        why: 'Jede falsche Option verletzt genau einen der drei Bausteine.',
        avoid: 'Prüfe die drei Bausteine einzeln: voy? a? Infinitiv?',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: IR,
      difficulty: 2,
      instruction: 'Setze die passenden Formen von „ir“ ein.',
      sentence: '¿Qué ___ a hacer esta noche? – ___ a salir con mis amigos.',
      answers: [['vas'], ['voy']],
      bank: ['voy', 'vas', 'va', 'vamos', 'van'],
      german: 'Was machst du heute Abend? – Ich gehe mit meinen Freunden aus.',
      feedback: {
        rule: 'Frage an tú → `vas`; Antwort über dich selbst → `voy`.',
        why: 'Wer in der Antwort `vas` wiederholt, spricht über das Gegenüber statt über sich.',
        avoid: 'Frage mit „du“ → Antwort mit „ich“: vas → voy.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: IR,
      difficulty: 2,
      audio: 'El sábado voy a descansar, pero el domingo voy a visitar a mis abuelos.',
      question: 'Was plant die Person für Sonntag?',
      options: ['Sie besucht ihre Großeltern.', 'Sie ruht sich aus.', 'Sie geht ins Kino.', 'Sie arbeitet.'],
      answer: 0,
      feedback: {
        rule: '`el domingo voy a visitar a mis abuelos` = am Sonntag besuche ich meine Großeltern. Ausruhen ist für Samstag geplant.',
        why: 'Beide Tage kommen vor – wer nur auf das erste Verb achtet, ordnet `descansar` falsch zu.',
        avoid: 'Merke dir beim Hören Tag und Aktivität als Paar: sábado → descansar, domingo → visitar.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: IR,
      difficulty: 2,
      instruction: 'Bilde den Satz „Heute Abend gehen wir nicht aus.“',
      tokens: ['Esta', 'noche', 'no', 'vamos', 'a', 'salir.'],
      alternatives: [['No', 'vamos', 'a', 'salir', 'esta', 'noche.']],
      german: 'Heute Abend gehen wir nicht aus.',
      feedback: {
        rule: '`no` steht direkt vor der Form von ir: `no vamos a salir`. Die Zeitangabe kann am Anfang oder am Ende stehen.',
        why: '„vamos no a salir“ ist falsch – die Verneinung gehört vor das konjugierte Verb.',
        avoid: 'Denk an den Block `no + voy/vas/vamos … + a + Infinitiv`.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: IR,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib ihn richtig.',
      sentence: 'Mañana voy a el museo.',
      answers: ['Mañana voy al museo.', 'Mañana voy a ir al museo.'],
      german: 'Morgen gehe ich ins Museum.',
      feedback: {
        rule: '`a` + `el` wird immer zu `al`: `voy al museo`.',
        why: '`a el` ist im Spanischen nicht erlaubt (Ausnahme: Eigennamen wie `El Salvador`).',
        avoid: 'Bei Orten mit `el` automatisch `al` sagen: al cine, al museo, al parque. Mit `la` bleibt es: a la playa.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: IR,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Morgen werden wir ins Kino gehen.',
      answers: [
        'Mañana vamos a ir al cine.',
        'Mañana nosotros vamos a ir al cine.',
        'Mañana nosotras vamos a ir al cine.',
        'Vamos a ir al cine mañana.',
        'Nosotros vamos a ir al cine mañana.',
        'Nosotras vamos a ir al cine mañana.',
        'Mañana vamos al cine.',
        'Vamos al cine mañana.',
      ],
      feedback: {
        rule: 'Plan: `vamos a ir` + Ort mit `al` (a + el): `al cine`.',
        why: 'Häufige Fehler: `vamos ir` (a fehlt), `a el cine` statt `al cine`.',
        avoid: 'Zwei Mal „a“ prüfen: einmal nach vamos, einmal vor dem Ort – und a + el = al.',
      },
    },
  ],
  pronunciation: ['es.p.bv.vaca', 'es.p.ll.yo', 'es.p.into.como-te-llamas'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: IR,
      difficulty: 2,
      instruction: 'Wähle die passende Antwort.',
      lines: [
        { speaker: 'Sofía', text: 'Hola, ¿qué vas a hacer el sábado?', german: 'Hallo, was hast du am Samstag vor?' },
        { speaker: 'Du', text: 'Voy a ir a la playa con mi hermana.', german: 'Ich fahre mit meiner Schwester an den Strand.' },
        { speaker: 'Sofía', text: '¡Qué bien! Yo voy a descansar en casa.', german: 'Wie schön! Ich ruhe mich zu Hause aus.' },
      ],
      gapIndex: 1,
      options: [
        'Voy a ir a la playa con mi hermana.',
        'Voy ir a la playa con mi hermana.',
        'Vas a ir a la playa con mi hermana.',
        'Voy a voy a la playa con mi hermana.',
      ],
      answer: 0,
      feedback: {
        rule: 'Antwort über dich: `voy a` + Infinitiv (`ir`).',
        why: '`Voy ir` – das a fehlt; `Vas` – falsche Person; `voy a voy` – nach a muss der Infinitiv stehen.',
        avoid: 'Bau die Antwort aus der Frage: `¿Qué vas a hacer?` → `Voy a …`.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: IR,
      difficulty: 2,
      prompt: 'Schreib 3–4 Sätze über deine Pläne fürs Wochenende. Nenne mindestens zwei Aktivitäten und eine Zeitangabe.',
      requirements: [
        { pattern: '\\b(voy|vas|va|vamos|vais|van) a \\w*(ar|er|ir)\\b', hint: 'eine Form von ir + a + Infinitiv (z. B. „voy a descansar“)' },
        { pattern: '(el sábado|el domingo|el fin de semana|mañana|esta noche|esta tarde|la próxima semana)', hint: 'eine Zeitangabe (z. B. el sábado, mañana, esta noche)' },
        { pattern: '(\\ba \\w*(ar|er|ir)\\b[\\s\\S]*){2}', hint: 'mindestens zwei Pläne mit „a“ + Infinitiv' },
      ],
      samples: [
        'El sábado voy a visitar a mis abuelos. Por la tarde voy a descansar en casa y el domingo vamos a ir al cine.',
      ],
      minWords: 15,
      feedback: {
        rule: 'Pläne: `voy / vamos a` + Infinitiv; Orte mit `al` bzw. `a la`.',
        why: 'Typische Fehler: fehlendes `a`, konjugiertes zweites Verb (`voy a visito`) oder `a el`.',
        avoid: 'Unterstreiche in deinem Text jedes Verb nach `a` – es muss auf -ar, -er oder -ir enden.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: IR,
      difficulty: 2,
      prompt: 'Sag laut, was du morgen und am Wochenende vorhast (2–3 Sätze).',
      keywords: ['voy a', 'vamos a', 'mañana', 'el sábado', 'el domingo', 'fin de semana', 'esta noche'],
      minMatch: 2,
      sample: 'Mañana voy a trabajar y el sábado voy a ir al cine.',
      feedback: {
        rule: 'Zeitangabe + `voy a` + Infinitiv: `Mañana voy a …`.',
        why: 'Wurde zu wenig erkannt, fehlte meist das `a` nach voy – gesprochen verschmilzt es leicht mit dem nächsten Wort.',
        avoid: 'Sprich `voy a` bewusst als zwei Silben: VOY-a.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: IR,
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Verabrede dich fürs Wochenende: Frag, was dein Gegenüber vorhat, erzähl von deinen Plänen und schlag etwas Gemeinsames vor (¡Vamos a …!).',
      turns: 5,
      feedback: {
        rule: 'Fragen: `¿Qué vas a hacer …?` – Antworten: `Voy a …` – Vorschlag: `¡Vamos a …!`',
        why: 'Im Gespräch fällt das `a` nach ir leicht weg.',
        avoid: 'Halte dich an das Muster ir + a + Infinitiv und variiere nur Zeit und Aktivität.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.reflexive'],
      difficulty: 2,
      verb: 'levantarse',
      tense: 'Präsens',
      person: 'ella',
      sentence: 'Mi madre ___ a las seis.',
      answers: ['se levanta', 'ella se levanta'],
      feedback: {
        rule: 'él/ella/usted: `se` + Verbform auf `-a` → `se levanta`.',
        why: 'Ohne `se` hieße es „sie hebt (etwas) hoch“.',
        avoid: 'Reflexive Verben immer mit Pronomen üben: me levanto, te levantas, se levanta.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.gustar'],
      difficulty: 2,
      prompt: 'Welcher Satz bedeutet „Wir tanzen gern“?',
      options: [
        { text: 'Nos gusta bailar.' },
        { text: 'Nos gustan bailar.', why: 'Vor einem Infinitiv steht immer `gusta` (Singular).' },
        { text: 'Nosotros gustamos bailar.', why: 'gustar richtet sich nicht nach der Person; „wir“ wird durch `nos` ausgedrückt.' },
        { text: 'Vamos a bailar.', why: 'Das heißt „Wir werden tanzen“ oder „Lass uns tanzen!“ – nicht „wir tanzen gern“.' },
      ],
      answer: 0,
      feedback: {
        rule: '„gern tun“ → `gustar` + Infinitiv: `Nos gusta bailar.`',
        why: 'Die Verwechslung mit `vamos a` liegt nahe, weil beide mit Infinitiv stehen – die Bedeutung ist aber eine andere.',
        avoid: 'gern → gustar; vorhaben → ir a.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading'],
      topicIds: ['es.g.tener'],
      difficulty: 1,
      direction: 'toGerman',
      source: 'Mi hermano tiene veinte años.',
      answers: ['Mein Bruder ist zwanzig Jahre alt.', 'Mein Bruder ist 20 Jahre alt.', 'Mein Bruder ist zwanzig.', 'Mein Bruder ist 20.'],
      feedback: {
        rule: '`tener … años` wird im Deutschen mit „… Jahre alt sein“ übersetzt.',
        why: 'Die wörtliche Übersetzung „hat zwanzig Jahre“ ist kein natürliches Deutsch.',
        avoid: 'Übersetze Bedeutungen, nicht Wörter: tener años = alt sein.',
      },
    },
  ],
};

export default lesson;
