import type { Lesson } from '../../types';

const L = 'es.a1.l06';
const IMP = ['es.g.imperative-tu'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c2',
  order: 6,
  title: 'Nach dem Weg fragen',
  subtitle: 'Perdone, ¿cómo llego a …? – Sigue recto y gira a la derecha',
  icon: '🧭',
  minutes: 13,
  goal:
    'Du fragst höflich nach dem Weg (`Perdone, ¿cómo llego a la estación?`) und verstehst Wegbeschreibungen wie `Sigue recto y gira a la derecha.` Dafür lernst du den **Imperativ mit tú** – und die höflichen **usted-Formen** (`siga`, `gire`, `tome`) als feste Wendungen.',
  canDo: [
    'Ich kann Fremde höflich ansprechen und nach dem Weg fragen.',
    'Ich kann Wegbeschreibungen verstehen: geradeaus, rechts, links, die zweite Straße.',
    'Ich kann den tú-Imperativ regelmäßiger Verben bilden (gira, toma, cruza).',
    'Ich kann eine Wegbeschreibung mit primero, después und al final gliedern.',
  ],
  topicIds: IMP,
  vocab: [
    { id: `${L}.v.perdone`, target: 'perdone / perdona', german: 'Entschuldigen Sie / Entschuldige', pos: 'phrase', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'Perdone, ¿dónde está la estación?', german: 'Entschuldigen Sie, wo ist der Bahnhof?' } },
    { id: `${L}.v.como-llego`, target: '¿Cómo llego a …?', german: 'Wie komme ich zu / nach …?', pos: 'phrase', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: '¿Cómo llego al museo?', german: 'Wie komme ich zum Museum?' } },
    { id: `${L}.v.llegar`, target: 'llegar', german: 'ankommen, hinkommen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Llego a casa a las seis.', german: 'Ich komme um sechs nach Hause.' } },
    { id: `${L}.v.seguir`, target: 'seguir', german: 'weitergehen, weiterfahren', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Sigue recto hasta el semáforo.', german: 'Geh geradeaus bis zur Ampel.' } },
    { id: `${L}.v.todo-recto`, target: 'todo recto', german: 'geradeaus', pos: 'adv', variant: 'es-ES', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'Siga todo recto.', german: 'Gehen Sie geradeaus.' } },
    { id: `${L}.v.derecho`, target: 'derecho', german: 'geradeaus', pos: 'adv', variant: 'es-LA', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'Siga derecho dos cuadras.', german: 'Gehen Sie zwei Blocks geradeaus.' } },
    { id: `${L}.v.girar`, target: 'girar', german: 'abbiegen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Gira a la izquierda.', german: 'Bieg links ab.' } },
    { id: `${L}.v.tomar`, target: 'tomar', german: 'nehmen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Toma la segunda calle a la derecha.', german: 'Nimm die zweite Straße rechts.' } },
    { id: `${L}.v.cruzar`, target: 'cruzar', german: 'überqueren', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Cruza la plaza.', german: 'Geh über den Platz.' } },
    { id: `${L}.v.esquina`, target: 'la esquina', german: 'die Ecke', pos: 'noun', gender: 'f', plural: 'las esquinas', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'El banco está en la esquina.', german: 'Die Bank ist an der Ecke.' } },
    { id: `${L}.v.semaforo`, target: 'el semáforo', german: 'die Ampel', pos: 'noun', gender: 'm', plural: 'los semáforos', emoji: '🚦', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'En el semáforo, gira a la derecha.', german: 'An der Ampel bieg rechts ab.' } },
    { id: `${L}.v.hasta`, target: 'hasta', german: 'bis (zu)', pos: 'prep', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'Sigue hasta la plaza.', german: 'Geh weiter bis zum Platz.' } },
    { id: `${L}.v.primero`, target: 'primero', german: 'zuerst', pos: 'adv', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'Primero cruza la calle.', german: 'Überquere zuerst die Straße.' } },
    { id: `${L}.v.despues`, target: 'después', german: 'danach, dann', pos: 'adv', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'Después gira a la izquierda.', german: 'Dann bieg links ab.' } },
    { id: `${L}.v.al-final`, target: 'al final (de)', german: 'am Ende (von)', pos: 'phrase', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'La farmacia está al final de la calle.', german: 'Die Apotheke ist am Ende der Straße.' } },
    { id: `${L}.v.cuadra`, target: 'la cuadra', german: 'der Häuserblock (als Entfernungsangabe)', pos: 'noun', gender: 'f', plural: 'las cuadras', variant: 'es-LA', field: 'Wegbeschreibung', stageId: 'a1', lessonId: L, example: { target: 'El banco está a dos cuadras.', german: 'Die Bank ist zwei Blocks entfernt.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Für Wegbeschreibungen brauchst du den **Imperativ** (Befehlsform). Die gute Nachricht: Der **tú-Imperativ** regelmäßiger Verben sieht genauso aus wie die **er/sie-Form im Präsens**:\n- `él gira` → `¡Gira!` (Bieg ab!)\n- `él toma` → `¡Toma!` (Nimm!)\n- `él cruza` → `¡Cruza!` (Überquere!)\nAuch Verben mit Stammwechsel folgen dieser Regel: `seguir` → `él sigue` → `Sigue recto.` (Geh geradeaus weiter.)',
    },
    {
      type: 'conjugation',
      verb: 'girar',
      translation: 'abbiegen',
      tense: 'Imperativ',
      rows: [
        { person: 'tú', form: 'gira', ending: 'a' },
        { person: 'usted', form: 'gire', ending: 'e' },
        { person: 'vosotros / vosotras', form: 'girad', ending: 'ad', variant: 'es-ES' },
        { person: 'ustedes', form: 'giren', ending: 'en' },
      ],
    },
    {
      type: 'tip',
      md:
        'Merksatz: **du = er/sie-Form, Sie = Vokaltausch.** Fremde auf der Straße sprichst du meist mit **usted** an. Die usted-Formen lernst du vorerst als feste Paare: Bei -ar-Verben wird `a` zu `e`, bei -er/-ir-Verben `e` zu `a`.\n- `gira` → `gire`\n- `toma` → `tome`\n- `cruza` → `cruce` (vor e wird z zu c)\n- `sigue` → `siga` (vor a braucht das g kein stummes u)\n- `perdona` → `perdone`',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Primero', role: 'adverb' },
        { text: ' ' },
        { text: 'sigue', role: 'verb' },
        { text: ' ' },
        { text: 'recto', role: 'adverb' },
        { text: ', ' },
        { text: 'después', role: 'adverb' },
        { text: ' ' },
        { text: 'gira', role: 'verb' },
        { text: ' ' },
        { text: 'a la izquierda', role: 'preposition' },
        { text: '.' },
      ],
      german: 'Geh zuerst geradeaus, dann bieg links ab.',
    },
    {
      type: 'compare',
      target: 'Toma la segunda calle a la derecha.',
      german: 'Nimm die zweite Straße rechts.',
      md:
        'Wie im Deutschen „nimmt“ man eine Straße: `tomar la calle`. Ordnungszahlen stehen vor dem Nomen und passen sich an: `la primera calle`, `la segunda calle`, `la tercera calle`. Vor einem maskulinen Nomen im Singular wird `primero` zu `primer`: `el primer semáforo`. Das Adverb `primero` (zuerst) bleibt unverändert.',
    },
    {
      type: 'mistake',
      wrong: 'Gira derecho en la esquina.',
      right: 'Gira a la derecha en la esquina.',
      why:
        '„Rechts“ heißt `a la derecha` – immer mit `a la`. `derecho` bedeutet in Lateinamerika „geradeaus“ (`sigue derecho`). Wer `derecho` und `derecha` verwechselt, schickt Leute in die falsche Richtung!',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika sagt man für „geradeaus“ meist `derecho`: `Siga derecho dos cuadras.` – „Gehen Sie zwei Blocks geradeaus.“ Entfernungen gibt man dort gern in `cuadras` (Häuserblocks) an; in Spanien heißt es eher `Siga todo recto.` und man zählt `calles`. In Spanien hörst du auch `Coge la segunda calle.` (coger = nehmen) – in vielen Ländern Lateinamerikas ist `coger` aber vulgär. Nimm dort immer `tomar`.',
    },
    { type: 'audio', text: 'Perdone, ¿cómo llego a la estación? – Siga recto y tome la segunda calle a la izquierda.', label: 'Nach dem Weg fragen (usted)' },
  ],
  examples: [
    {
      target: 'Perdone, ¿cómo llego al museo?',
      german: 'Entschuldigen Sie, wie komme ich zum Museum?',
      parts: [
        { text: 'Perdone', role: 'verb' },
        { text: ', ' },
        { text: '¿cómo', role: 'question' },
        { text: ' ' },
        { text: 'llego', role: 'verb' },
        { text: ' ' },
        { text: 'al museo', role: 'object' },
        { text: '?' },
      ],
      note: '`al` = `a` + `el`. Zu einem weiblichen Ziel: `¿Cómo llego a la estación?`',
    },
    {
      target: 'Sigue recto hasta el semáforo.',
      german: 'Geh geradeaus bis zur Ampel.',
      parts: [
        { text: 'Sigue', role: 'verb' },
        { text: ' ' },
        { text: 'recto', role: 'adverb' },
        { text: ' ' },
        { text: 'hasta', role: 'preposition' },
        { text: ' ' },
        { text: 'el semáforo', role: 'noun' },
        { text: '.' },
      ],
    },
    {
      target: 'Gira a la derecha en la esquina.',
      german: 'Bieg an der Ecke rechts ab.',
      parts: [
        { text: 'Gira', role: 'verb' },
        { text: ' ' },
        { text: 'a la derecha', role: 'preposition' },
        { text: ' ' },
        { text: 'en la esquina', role: 'other' },
        { text: '.' },
      ],
    },
    {
      target: 'Toma la primera calle a la izquierda.',
      german: 'Nimm die erste Straße links.',
    },
    {
      target: 'Cruza la plaza y el banco está a la derecha.',
      german: 'Geh über den Platz, dann ist die Bank rechts.',
      note: 'Nach dem Imperativ beschreibst du mit `está` / `hay`, was man dann sieht.',
    },
    {
      target: 'Primero siga recto, después gire a la izquierda. La farmacia está al final de la calle.',
      german: 'Gehen Sie zuerst geradeaus, dann biegen Sie links ab. Die Apotheke ist am Ende der Straße.',
      note: 'Dieselbe Beschreibung höflich mit **usted**: `siga`, `gire`.',
    },
    {
      target: 'Coge la segunda calle a la derecha.',
      german: 'Nimm die zweite Straße rechts.',
      variant: 'es-ES',
      note: '`coger` = nehmen – in Spanien völlig normal.',
    },
    {
      target: 'Siga derecho dos cuadras y después gire a la derecha.',
      german: 'Gehen Sie zwei Blocks geradeaus und biegen Sie dann rechts ab.',
      variant: 'es-LA',
      note: '`derecho` = geradeaus, `a la derecha` = rechts.',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: IMP,
      difficulty: 1,
      instruction: 'Ordne jedem Infinitiv den tú-Imperativ zu.',
      pairs: [
        { left: 'girar', right: 'gira' },
        { left: 'tomar', right: 'toma' },
        { left: 'cruzar', right: 'cruza' },
        { left: 'seguir', right: 'sigue' },
        { left: 'comer', right: 'come' },
      ],
      feedback: {
        rule: 'tú-Imperativ = er/sie-Form im Präsens: `gira`, `toma`, `cruza`, `come`. Bei seguir mit Stammwechsel: `sigue`.',
        why: 'Wer `sigue` und `cruza` vertauscht, hat nur auf die Endungen geachtet. Achte auf den Stamm: sig-/seg- gehört zu seguir.',
        avoid: 'Sag dir die er/sie-Form laut vor („él toma“) – und lass das „él“ einfach weg: `¡Toma!`',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: IMP,
      difficulty: 1,
      prompt: 'Du erklärst einem älteren Herrn, den du mit **usted** ansprichst, den Weg: `___ la segunda calle a la derecha.`',
      options: [
        { text: 'Tome' },
        { text: 'Toma', why: '`toma` ist die tú-Form – für einen fremden älteren Herrn zu vertraut.' },
        { text: 'Tomar', why: 'Der Infinitiv ist keine Aufforderung an eine Person.' },
        { text: 'Tomas', why: '`tomas` ist das Präsens („du nimmst“), keine Aufforderung – und außerdem die du-Form.' },
      ],
      answer: 0,
      feedback: {
        rule: 'usted-Imperativ: bei -ar-Verben wird `a` zu `e`: `toma` → `tome`, `gira` → `gire`.',
        why: 'Die du-Form `toma` wäre grammatisch richtig gebildet, passt aber nicht zur Anrede usted.',
        avoid: 'Erst die Anrede klären (tú oder usted?), dann den Vokal wählen: tú → a, usted → e.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['listening', 'grammar'],
      topicIds: IMP,
      difficulty: 1,
      instruction: 'Hör genau hin: Welche Form wird gesagt?',
      options: ['Gira a la derecha.', 'Gire a la derecha.'],
      answer: 1,
      hint: 'Achte auf den letzten Vokal des Verbs: `gira` (du) endet auf -a, `gire` (Sie) auf -e.',
      feedback: {
        rule: '`gira` = tú-Imperativ, `gire` = usted-Imperativ. Nur der letzte Vokal unterscheidet Du und Sie.',
        why: 'Spanische Vokale werden am Wortende klar ausgesprochen, nicht verschluckt wie oft im Deutschen – deshalb ist der Unterschied gut hörbar.',
        avoid: 'Sprich beide Formen abwechselnd laut: GI-ra, GI-re. Das e klingt wie in „See“, nur kürzer.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: IMP,
      difficulty: 2,
      instruction: 'Ergänze die Wegbeschreibung.',
      sentence: 'Sigue ___ hasta el semáforo y después gira ___ la derecha.',
      answers: [['recto', 'todo recto', 'derecho'], ['a']],
      bank: ['recto', 'a', 'derecha', 'de'],
      german: 'Geh geradeaus bis zur Ampel und bieg dann rechts ab.',
      feedback: {
        rule: '„geradeaus“ = `recto` / `todo recto` (in Lateinamerika `derecho`); „rechts“ = `a la derecha`.',
        why: '`sigue derecha` ist falsch – `derecha` bedeutet „rechts“ und braucht immer `a la`. Und „nach rechts“ heißt `a la derecha`, nicht `de la derecha`.',
        avoid: 'recto/derecho = geradeaus (auf -o), a la derecha = rechts (auf -a).',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: IMP,
      difficulty: 2,
      audio: 'Primero sigue recto, después toma la segunda calle a la izquierda. El museo está al final de la calle.',
      question: 'Welche Straße soll man nehmen?',
      options: ['die zweite links', 'die zweite rechts', 'die erste links', 'die dritte links'],
      answer: 0,
      feedback: {
        rule: '`la segunda calle a la izquierda` = die zweite Straße links.',
        why: '`izquierda` (links) und `derecha` (rechts) werden leicht verwechselt. `segunda` = zweite, `primera` = erste, `tercera` = dritte.',
        avoid: 'Eselsbrücke: `derecha` klingt wie „direkt“ und „recht“ – also rechts. Zeig beim Zuhören mit der Hand in die Richtung und zähl die Straßen mit: primera, segunda, tercera.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: IMP,
      difficulty: 2,
      verb: 'cruzar',
      tense: 'Imperativ',
      person: 'tú',
      sentence: '___ la plaza y el banco está a la izquierda.',
      answers: ['cruza'],
      feedback: {
        rule: 'tú-Imperativ von cruzar = er/sie-Form: `cruza`.',
        why: '`cruzas` ist das Präsens („du überquerst“), `cruce` die usted-Form, `cruzar` der Infinitiv.',
        avoid: 'Kein -s am Ende: Der Imperativ ist die Form **ohne** das du-s.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'order',
      skills: ['grammar', 'speaking'],
      topicIds: ['es.g.imperative-tu', 'es.g.prepositions-place'],
      difficulty: 2,
      instruction: 'Bilde die Frage „Entschuldigen Sie, wie komme ich zum Bahnhof?“.',
      tokens: ['Perdone,', '¿cómo', 'llego', 'a', 'la', 'estación?'],
      extra: ['al', 'estoy'],
      german: 'Entschuldigen Sie, wie komme ich zum Bahnhof?',
      feedback: {
        rule: '`¿Cómo llego a + Ziel?` – `la estación` ist weiblich, also `a la estación` (keine Verschmelzung).',
        why: '`al` passt nur vor maskulinen Nomen (`al museo`). `estoy` fragt nicht nach dem Weg.',
        avoid: 'Merke das Muster: `¿Cómo llego al museo / a la plaza / a la estación?`',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: IMP,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Bieg an der Ampel links ab.',
      answers: [
        'Gira a la izquierda en el semáforo.',
        'En el semáforo gira a la izquierda.',
        'Gira en el semáforo a la izquierda.',
        'Dobla a la izquierda en el semáforo.',
        'En el semáforo dobla a la izquierda.',
      ],
      feedback: {
        rule: '„abbiegen“ = `girar` → tú-Imperativ `gira`; „links“ = `a la izquierda`; „an der Ampel“ = `en el semáforo`.',
        why: '`giras` ist Präsens, `gire` die Sie-Form – gefragt ist „Bieg“ (du). „an der Ampel“ ist `en el semáforo`, nicht `a el semáforo`.',
        avoid: 'Baue den Satz in Blöcken: Verb (`gira`) – Richtung (`a la izquierda`) – Ort (`en el semáforo`).',
      },
    },
  ],
  pronunciation: ['es.p.j.gente', 'es.p.r.rosa', 'es.p.cz.zapato'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: IMP,
      difficulty: 2,
      instruction: 'Wie fragst du höflich nach dem Weg? Wähle die passende Zeile.',
      lines: [
        { speaker: 'Du', text: 'Perdone, ¿cómo llego al museo?', german: 'Entschuldigen Sie, wie komme ich zum Museum?' },
        { speaker: 'Señora', text: 'Siga recto y tome la primera calle a la izquierda. El museo está al final de la calle.', german: 'Gehen Sie geradeaus und nehmen Sie die erste Straße links. Das Museum ist am Ende der Straße.' },
        { speaker: 'Du', text: '¡Muchas gracias!', german: 'Vielen Dank!' },
        { speaker: 'Señora', text: 'De nada.', german: 'Gern geschehen.' },
      ],
      gapIndex: 0,
      options: [
        'Perdone, ¿cómo llego al museo?',
        'Perdone, ¿cómo llego a el museo?',
        'Perdone, ¿dónde hay el museo?',
        'Perdone, ¿cómo llegas al museo?',
      ],
      answer: 0,
      feedback: {
        rule: 'Höflich ansprechen mit `Perdone`, dann `¿cómo llego + al/a la …?`.',
        why: '`a el` muss zu `al` verschmelzen; `hay` steht nicht mit bestimmtem Artikel; `llegas` hieße „wie kommst **du** hin“.',
        avoid: 'Lern die komplette Frage als Block auswendig – du brauchst sie auf jeder Reise.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: IMP,
      difficulty: 2,
      prompt: 'Beschreibe einer Freundin (tú) den Weg von deiner Wohnung zum nächsten Supermarkt oder Café – mit mindestens drei Schritten und primero / después.',
      requirements: [
        { pattern: '\\b(sigue|gira|toma|cruza|coge)\\b', hint: 'mindestens einen tú-Imperativ (sigue, gira, toma, cruza)' },
        { pattern: '\\bprimero\\b', hint: '„primero“ für den ersten Schritt' },
        { pattern: '\\bdespu[eé]s\\b', hint: '„después“ für den nächsten Schritt' },
        { pattern: '(derecha|izquierda|recto|derecho)', hint: 'eine Richtung (a la derecha, a la izquierda, recto)' },
      ],
      samples: [
        'Primero sigue recto hasta el semáforo. Después gira a la derecha y cruza la plaza. Al final toma la segunda calle a la izquierda. El supermercado está al lado del banco.',
      ],
      minWords: 15,
      feedback: {
        rule: 'tú-Imperativ = er/sie-Form: `sigue`, `gira`, `toma`, `cruza`. Gliedere mit `primero`, `después`, `al final`.',
        why: 'Typisch sind Formen mit -s (`giras`) – das ist das Präsens, keine Aufforderung.',
        avoid: 'Lies deinen Text einmal nur auf die Verben durch: Endet eines auf -s? Dann streich das s.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: IMP,
      difficulty: 3,
      prompt: 'Ein Tourist fragt dich (usted) nach dem Weg zur Apotheke. Erklär ihm laut den Weg – mit den usted-Formen siga, gire, tome oder cruce.',
      keywords: ['siga', 'gire', 'tome', 'cruce', 'recto', 'derecho', 'derecha', 'izquierda', 'primero', 'después', 'calle'],
      minMatch: 3,
      sample: 'Primero siga recto, después tome la segunda calle a la derecha. La farmacia está al lado del banco.',
      feedback: {
        rule: 'usted-Formen: `siga`, `gire`, `tome`, `cruce`.',
        why: 'Unter Druck rutscht oft die tú-Form heraus (`sigue`, `gira`) – bei Fremden ist usted höflicher.',
        avoid: 'Sprich zuerst langsam die Kette: `siga – gire – tome`. Das g in `gire` klingt wie das deutsche „ch“ in „ach“.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: IMP,
      difficulty: 2,
      scenarioId: 'es.sc.reise',
      goal: 'Du bist als Tourist unterwegs: Sprich jemanden höflich an, frag nach dem Weg zu einem Ort und wiederhole die Wegbeschreibung zur Kontrolle.',
      turns: 4,
      feedback: {
        rule: '`Perdone, ¿cómo llego a …?` – zum Wiederholen: `Entonces, sigo recto y giro a la derecha, ¿no?`',
        why: 'Wegbeschreibungen sind schnell – nachfragen und wiederholen ist völlig normal und höflich.',
        avoid: 'Hör auf die Schlüsselwörter: recto/derecho, derecha, izquierda, primera/segunda.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.prepositions-place'],
      difficulty: 1,
      prompt: 'Wiederholung Ortsangaben: `El museo está ___ parque.` (gegenüber vom Park)',
      options: [
        { text: 'enfrente del' },
        { text: 'delante del', why: '`delante de` heißt „vor“, nicht „gegenüber“.' },
        { text: 'enfrente de el', why: '`de` + `el` muss zu `del` verschmelzen.' },
        { text: 'al lado del', why: '`al lado de` heißt „neben“.' },
      ],
      answer: 0,
      feedback: {
        rule: '„gegenüber“ = `enfrente de`; mit `el parque` → `enfrente del parque`.',
        why: '`enfrente` klingt nach „vorne“, bedeutet aber „gegenüber“.',
        avoid: 'Front an Front = gegenüber = `enfrente de`.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'translate',
      skills: ['reading'],
      topicIds: IMP,
      difficulty: 2,
      direction: 'toGerman',
      source: 'Cruza la calle y gira a la izquierda.',
      answers: [
        'Überquere die Straße und bieg links ab.',
        'Überquere die Straße und biege links ab.',
        'Überquer die Straße und bieg links ab.',
        'Überquer die Straße und biege links ab.',
        'Geh über die Straße und bieg links ab.',
        'Geh über die Straße und biege links ab.',
        'Gehe über die Straße und biege links ab.',
      ],
      feedback: {
        rule: '`cruza` = überquere (du), `gira a la izquierda` = bieg links ab.',
        why: '`cruza` und `gira` sind hier Aufforderungen (Imperativ), keine Aussagen („er überquert“).',
        avoid: 'Steht das Verb ohne Subjekt am Satzanfang einer Wegbeschreibung, ist es fast immer ein Imperativ.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.reflexive'],
      difficulty: 2,
      verb: 'levantarse',
      tense: 'Präsens',
      person: 'tú',
      sentence: '¿A qué hora ___?',
      answers: ['te levantas'],
      feedback: {
        rule: 'Reflexive Verben: Pronomen + konjugiertes Verb: `te levantas` (du stehst auf).',
        why: '`levantas` ohne `te` hieße „du hebst (etwas) hoch“. `se levanta` wäre er/sie/usted.',
        avoid: 'Pronomen und Verbendung passen immer zusammen: te …-as, me …-o, se …-a.',
      },
    },
  ],
};

export default lesson;
