import type { Lesson } from '../../types';

const L = 'es.a1.l11';
const TD = ['es.g.time-dates'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c4',
  order: 11,
  title: 'Wochentage, Monate & Datum',
  subtitle: 'Wann? Am Montag, im Mai, am 5. Mai – und wann hast du Geburtstag?',
  icon: '📅',
  minutes: 12,
  goal:
    'Du nennst **Wochentage**, **Monate** und **Jahreszeiten**, fragst nach dem Datum (`¿Qué día es hoy?`) und sagst, wann du Geburtstag hast: `Mi cumpleaños es el cinco de mayo.` Außerdem lernst du den kleinen, aber wichtigen Unterschied zwischen `el lunes` (am Montag) und `los lunes` (montags).',
  canDo: [
    'Ich kann die Wochentage, Monate und Jahreszeiten nennen.',
    'Ich kann sagen und fragen, welcher Tag heute ist.',
    'Ich kann ein Datum nennen und sagen, wann ich Geburtstag habe.',
    'Ich kann mit el lunes / los lunes einmalige Termine von Gewohnheiten unterscheiden.',
  ],
  topicIds: TD,
  vocab: [
    { id: `${L}.v.lunes`, target: 'el lunes', german: 'der Montag / am Montag', pos: 'noun', gender: 'm', plural: 'los lunes', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'El lunes tengo clase.', german: 'Am Montag habe ich Unterricht.' } },
    { id: `${L}.v.martes`, target: 'el martes', german: 'der Dienstag / am Dienstag', pos: 'noun', gender: 'm', plural: 'los martes', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Hoy es martes.', german: 'Heute ist Dienstag.' } },
    { id: `${L}.v.miercoles`, target: 'el miércoles', german: 'der Mittwoch / am Mittwoch', pos: 'noun', gender: 'm', plural: 'los miércoles', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Los miércoles voy al mercado.', german: 'Mittwochs gehe ich auf den Markt.' } },
    { id: `${L}.v.jueves`, target: 'el jueves', german: 'der Donnerstag / am Donnerstag', pos: 'noun', gender: 'm', plural: 'los jueves', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'El jueves ceno con mis padres.', german: 'Am Donnerstag esse ich mit meinen Eltern zu Abend.' } },
    { id: `${L}.v.viernes`, target: 'el viernes', german: 'der Freitag / am Freitag', pos: 'noun', gender: 'm', plural: 'los viernes', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'El viernes voy al cine.', german: 'Am Freitag gehe ich ins Kino.' } },
    { id: `${L}.v.semana`, target: 'la semana', german: 'die Woche', pos: 'noun', gender: 'f', plural: 'las semanas', emoji: '🗓️', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Trabajo cinco días a la semana.', german: 'Ich arbeite fünf Tage pro Woche.' } },
    { id: `${L}.v.mes`, target: 'el mes', german: 'der Monat', pos: 'noun', gender: 'm', plural: 'los meses', emoji: '📆', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: '¿En qué mes es tu cumpleaños?', german: 'In welchem Monat hast du Geburtstag?' } },
    { id: `${L}.v.fecha`, target: 'la fecha', german: 'das Datum', pos: 'noun', gender: 'f', plural: 'las fechas', emoji: '📅', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: '¿Qué fecha es hoy?', german: 'Welches Datum ist heute?' } },
    { id: `${L}.v.cumpleanos`, target: 'el cumpleaños', german: 'der Geburtstag', pos: 'noun', gender: 'm', plural: 'los cumpleaños', emoji: '🎂', field: 'Feste', stageId: 'a1', lessonId: L, example: { target: '¡Feliz cumpleaños!', german: 'Alles Gute zum Geburtstag!' } },
    { id: `${L}.v.hoy`, target: 'hoy', german: 'heute', pos: 'adv', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Hoy es viernes.', german: 'Heute ist Freitag.' } },
    { id: `${L}.v.que-dia`, target: '¿Qué día es hoy?', german: 'Welcher Tag ist heute?', pos: 'phrase', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: '¿Qué día es hoy? – Hoy es jueves.', german: 'Welcher Tag ist heute? – Heute ist Donnerstag.' } },
    { id: `${L}.v.de-lunes-a-viernes`, target: 'de lunes a viernes', german: 'von Montag bis Freitag', pos: 'phrase', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Trabajo de lunes a viernes.', german: 'Ich arbeite von Montag bis Freitag.' } },
    { id: `${L}.v.primavera`, target: 'la primavera', german: 'der Frühling', pos: 'noun', gender: 'f', emoji: '🌸', field: 'Jahreszeiten', stageId: 'a1', lessonId: L, example: { target: 'Me encanta la primavera.', german: 'Ich liebe den Frühling.' } },
    { id: `${L}.v.verano`, target: 'el verano', german: 'der Sommer', pos: 'noun', gender: 'm', emoji: '☀️', field: 'Jahreszeiten', stageId: 'a1', lessonId: L, example: { target: 'En verano vamos a la playa.', german: 'Im Sommer fahren wir an den Strand.' } },
    { id: `${L}.v.otono`, target: 'el otoño', german: 'der Herbst', pos: 'noun', gender: 'm', emoji: '🍂', field: 'Jahreszeiten', stageId: 'a1', lessonId: L, example: { target: 'Mi cumpleaños es en otoño.', german: 'Ich habe im Herbst Geburtstag.' } },
    { id: `${L}.v.invierno`, target: 'el invierno', german: 'der Winter', pos: 'noun', gender: 'm', emoji: '❄️', field: 'Jahreszeiten', stageId: 'a1', lessonId: L, example: { target: 'En invierno me levanto tarde.', german: 'Im Winter stehe ich spät auf.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Die **Wochentage** sind maskulin und werden kleingeschrieben: `lunes, martes, miércoles, jueves, viernes, sábado, domingo`.\nFür „am Montag“ brauchst du **keine Präposition**, nur den Artikel: `el lunes`. Mit `los` wird daraus eine Gewohnheit: `los lunes` = montags, jeden Montag. `lunes` bis `viernes` bleiben im Plural gleich, `sábado` und `domingo` bekommen ein -s: `los sábados`, `los domingos`.\nNach `Hoy es …` steht kein Artikel: `Hoy es martes.`',
    },
    {
      type: 'table',
      title: 'Monate und Jahreszeiten (Nordhalbkugel)',
      headers: ['el invierno ❄️', 'la primavera 🌸', 'el verano ☀️', 'el otoño 🍂'],
      rows: [
        ['diciembre', 'marzo', 'junio', 'septiembre'],
        ['enero', 'abril', 'julio', 'octubre'],
        ['febrero', 'mayo', 'agosto', 'noviembre'],
      ],
    },
    {
      type: 'compare',
      target: 'el lunes / los lunes',
      german: 'am Montag / montags',
      md: '`El lunes voy al médico.` = Am (kommenden) Montag gehe ich zum Arzt – einmal. `Los lunes voy al gimnasio.` = Montags gehe ich ins Fitnessstudio – jede Woche. Im Deutschen machst du den Unterschied mit „am“ und „-s“, im Spanischen mit `el` und `los`.',
    },
    {
      type: 'mistake',
      wrong: 'Mi cumpleaños es el quinto de mayo.',
      right: 'Mi cumpleaños es el cinco de mayo.',
      why: 'Im Deutschen sagt man „der fünfte Mai“ – mit Ordnungszahl. Spanisch benutzt beim Datum die **Grundzahl**: `el cinco de mayo`, `el veinte de junio`. Nur beim Monatsersten hörst du auch `el primero`.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Mi', role: 'pronoun' },
        { text: ' ' },
        { text: 'cumpleaños', role: 'subject' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'el', role: 'article' },
        { text: ' ' },
        { text: 'doce', role: 'other' },
        { text: ' ' },
        { text: 'de', role: 'preposition' },
        { text: ' ' },
        { text: 'octubre', role: 'noun' },
        { text: '.' },
      ],
      german: 'Ich habe am 12. Oktober Geburtstag.',
    },
    {
      type: 'tip',
      md:
        'Merksatz: **am** Tag oder Datum → `el` (`el lunes`, `el cinco de mayo`); **im** Monat, Jahr oder in der Jahreszeit → `en` (`en mayo`, `en verano`, `en 2026`).\nMonate und Wochentage schreibst du klein. Jahreszahlen sprichst du wie normale Zahlen: `2026` = `dos mil veintiséis` – nicht „zwanzig sechsundzwanzig“.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika sagt man für den Monatsersten fast immer `el primero`: `el primero de enero`, `el primero de mayo`. In Spanien sagt man meist `el uno de enero` – `el primero` ist dort aber ebenfalls richtig.\nUnd denk daran: In Argentinien, Chile und Uruguay liegen die Jahreszeiten umgekehrt – dort ist im Dezember Sommer. Mehr dazu in der nächsten Lektion.',
    },
    { type: 'audio', text: 'Hoy es lunes, cinco de mayo.', label: 'Datum ansagen' },
  ],
  examples: [
    {
      target: 'Hoy es miércoles.',
      german: 'Heute ist Mittwoch.',
      parts: [
        { text: 'Hoy', role: 'adverb' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'miércoles', role: 'noun' },
        { text: '.' },
      ],
      note: 'Nach `Hoy es` steht der Wochentag ohne Artikel.',
    },
    {
      target: 'El viernes voy al cine.',
      german: 'Am Freitag gehe ich ins Kino.',
      parts: [
        { text: 'El viernes', role: 'adverb' },
        { text: ' ' },
        { text: 'voy', role: 'verb' },
        { text: ' ' },
        { text: 'al cine', role: 'object' },
        { text: '.' },
      ],
      note: '„Am Freitag“ = `el viernes` – ohne `en`.',
    },
    {
      target: 'Los domingos visito a mis abuelos.',
      german: 'Sonntags besuche ich meine Großeltern.',
      parts: [
        { text: 'Los domingos', role: 'adverb' },
        { text: ' ' },
        { text: 'visito', role: 'verb' },
        { text: ' ' },
        { text: 'a mis abuelos', role: 'object' },
        { text: '.' },
      ],
      note: '`los domingos` = jeden Sonntag.',
    },
    { target: 'Trabajo de lunes a viernes.', german: 'Ich arbeite von Montag bis Freitag.' },
    { target: 'Mi cumpleaños es el doce de octubre.', german: 'Ich habe am 12. Oktober Geburtstag.', literal: 'Mein Geburtstag ist der zwölf von Oktober.' },
    { target: '¿Cuándo es tu cumpleaños? – En marzo.', german: 'Wann hast du Geburtstag? – Im März.', note: 'Nur der Monat → `en marzo`; ein genaues Datum → `el …`.' },
    { target: 'En verano vamos a la playa.', german: 'Im Sommer fahren wir an den Strand.' },
    { target: 'El curso empieza el primero de septiembre.', german: 'Der Kurs beginnt am 1. September.', note: 'In Spanien hörst du auch `el uno de septiembre`.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary'],
      topicIds: TD,
      difficulty: 1,
      instruction: 'Ordne jedem Wochentag die deutsche Bedeutung zu.',
      pairs: [
        { left: 'lunes', right: 'Montag' },
        { left: 'martes', right: 'Dienstag' },
        { left: 'miércoles', right: 'Mittwoch' },
        { left: 'jueves', right: 'Donnerstag' },
        { left: 'viernes', right: 'Freitag' },
      ],
      feedback: {
        rule: 'lunes (Mo), martes (Di), miércoles (Mi), jueves (Do), viernes (Fr) – dazu sábado (Sa) und domingo (So).',
        why: '`martes` und `miércoles` werden oft vertauscht, weil beide mit m beginnen.',
        avoid: 'Eselsbrücke: Die Tage kommen von Himmelskörpern – **lu**nes (Mond, luna), **mar**tes (Mars), **mi**ércoles (Merkur), **jue**ves (Jupiter), **vier**nes (Venus).',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: TD,
      difficulty: 1,
      prompt: 'Wie sagst du „**am** Samstag“ (diesen einen Samstag)? `___ voy a Madrid.`',
      options: [
        { text: 'El sábado' },
        { text: 'En sábado', why: 'Vor Wochentagen steht keine Präposition, nur der Artikel.' },
        { text: 'Los sábados', why: '`los sábados` heißt „samstags“ – also jeden Samstag, nicht einmalig.' },
        { text: 'En el sábado', why: '„am“ ist hier einfach `el` – ein `en` davor ist falsch.' },
      ],
      answer: 0,
      feedback: {
        rule: '„am + Wochentag“ = `el` + Wochentag: `el sábado`. Gewohnheit („samstags“) = `los sábados`.',
        why: 'Das deutsche „am“ verleitet zu `en`. Bei Wochentagen reicht im Spanischen der Artikel.',
        avoid: 'Merksatz: am Tag → el, im Monat → en.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: TD,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '🌸', word: 'la primavera' },
        { emoji: '☀️', word: 'el verano' },
        { emoji: '🍂', word: 'el otoño' },
        { emoji: '❄️', word: 'el invierno' },
        { emoji: '🎂', word: 'el cumpleaños' },
      ],
      feedback: {
        rule: 'la primavera (Frühling), el verano (Sommer), el otoño (Herbst), el invierno (Winter), el cumpleaños (Geburtstag).',
        why: '`verano` und `invierno` werden leicht vertauscht. `primavera` ist als einzige Jahreszeit feminin.',
        avoid: 'Eselsbrücke: **in**vierno – da bleibt man **drin**nen.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: TD,
      difficulty: 2,
      instruction: 'Ergänze das Datum.',
      sentence: 'Mi cumpleaños es ___ ocho ___ julio.',
      answers: [['el'], ['de']],
      bank: ['el', 'en', 'de', 'a'],
      german: 'Ich habe am 8. Juli Geburtstag.',
      feedback: {
        rule: 'Datum: `el` + Zahl + `de` + Monat: `el ocho de julio`.',
        why: '`en` passt nur zum Monat allein (`en julio`), nicht zu einem genauen Datum.',
        avoid: 'Lies das Datum als Block: „el ocho de julio“ – der, acht, von, Juli.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: TD,
      difficulty: 2,
      audio: 'Mi cumpleaños es el veintitrés de noviembre.',
      question: 'Wann hat die Person Geburtstag?',
      options: ['am 23. November', 'am 13. November', 'am 23. September', 'am 3. November'],
      answer: 0,
      feedback: {
        rule: '`veintitrés` = 23 (veinte + tres), `noviembre` = November.',
        why: '`trece` wäre 13 und `tres` nur 3; `septiembre` und `noviembre` enden beide auf -iembre.',
        avoid: 'Achte auf den Anfang: veinti- = zwanzig-, sep- = September, no- = November.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: TD,
      difficulty: 2,
      instruction: 'Bilde den Satz „Ich arbeite von Montag bis Freitag.“.',
      tokens: ['Trabajo', 'de', 'lunes', 'a', 'viernes.'],
      extra: ['en'],
      german: 'Ich arbeite von Montag bis Freitag.',
      feedback: {
        rule: '„von … bis …“ = `de … a …`: `de lunes a viernes`.',
        why: '`en` passt hier nicht – die feste Wendung lautet `de lunes a viernes`, ohne Artikel.',
        avoid: 'Lerne die Wendung als Ganzes, genauso wie `de nueve a cinco` (von neun bis fünf).',
      },
    },
    {
      id: `${L}.g07`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: TD,
      difficulty: 3,
      instruction: 'Hör zu und schreib den Satz auf.',
      audio: 'Hoy es martes, catorce de febrero.',
      answers: ['Hoy es martes, catorce de febrero.', 'Hoy es martes, 14 de febrero.'],
      german: 'Heute ist Dienstag, der 14. Februar.',
      feedback: {
        rule: 'Wochentag und Monat klein: `martes`, `febrero`. Datum mit Grundzahl: `catorce de febrero`.',
        why: 'Häufige Fehler sind Großschreibung nach deutschem Vorbild und die Verwechslung von `catorce` (14) und `cuatro` (4).',
        avoid: 'Schreib erst die Zahl als Ziffer mit, dann das Wort: 14 = ca-TOR-ce.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: TD,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Montags arbeite ich nicht.',
      answers: [
        'Los lunes no trabajo.',
        'No trabajo los lunes.',
        'Los lunes yo no trabajo.',
        'Yo no trabajo los lunes.',
      ],
      feedback: {
        rule: '„montags“ (jede Woche) = `los lunes`. Die Verneinung `no` steht direkt vor dem Verb.',
        why: '`el lunes` würde „am (nächsten) Montag“ bedeuten, `en lunes` gibt es nicht.',
        avoid: 'Gewohnheit → Plural-Artikel `los`; einmaliger Termin → `el`.',
      },
    },
  ],
  pronunciation: ['es.p.j.julio', 'es.p.ny.manana', 'es.p.syl.buenos-dias'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: TD,
      difficulty: 2,
      instruction: 'Ergänze die fehlende Antwort im Gespräch.',
      lines: [
        { speaker: 'Ana', text: '¿Cuándo es tu cumpleaños?', german: 'Wann hast du Geburtstag?' },
        { speaker: 'Du', text: 'Es el diez de julio.', german: 'Am 10. Juli.' },
        { speaker: 'Ana', text: '¡Qué bien! Es en verano.', german: 'Wie schön! Das ist im Sommer.' },
      ],
      gapIndex: 1,
      options: ['Es el diez de julio.', 'Es el décimo de julio.', 'Es en el diez de julio.', 'Está el diez de julio.'],
      answer: 0,
      feedback: {
        rule: 'Datum mit Grundzahl und Artikel: `Es el diez de julio.`',
        why: '`décimo` ist eine Ordnungszahl (wie „zehnte“), `en el` ist doppelt, und `está` passt nicht zu einem Datum.',
        avoid: 'Beim Datum zählst du wie beim Preis: uno, dos, tres … – keine Ordnungszahlen.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: TD,
      difficulty: 2,
      prompt: 'Schreib 3–4 Sätze über deine Woche und dein Jahr: Was machst du an welchen Tagen? Wann hast du Geburtstag? Welche Jahreszeit magst du?',
      requirements: [
        { pattern: '\\b(lunes|martes|mi[eé]rcoles|jueves|viernes|s[aá]bados?|domingos?)\\b', hint: 'mindestens ein Wochentag' },
        { pattern: 'cumplea[nñ]os', hint: 'dein Geburtstag (cumpleaños)' },
        { pattern: '\\bde (enero|febrero|marzo|abril|mayo|junio|julio|agosto|sept?iembre|octubre|noviembre|diciembre)\\b', hint: 'ein Datum mit „de“ + Monat (z. B. „el 5 de mayo“)' },
        { pattern: '(primavera|verano|oto[nñ]o|invierno)', hint: 'eine Jahreszeit' },
      ],
      samples: [
        'Trabajo de lunes a viernes. Los sábados visito a mis padres. Mi cumpleaños es el doce de octubre. Me gusta mucho el otoño.',
      ],
      minWords: 18,
      feedback: {
        rule: '`el lunes` (einmal) / `los lunes` (immer); Datum: `el doce de octubre`; Monat/Jahreszeit: `en octubre`, `en otoño`.',
        why: 'Typisch sind Ordnungszahlen im Datum (`el quinto de mayo` statt `el cinco de mayo`) und großgeschriebene Wochentage oder Monate.',
        avoid: 'Prüfe am Ende: Stehen alle Wochentage und Monate klein? Hat jedes Datum ein `de` vor dem Monat?',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: TD,
      difficulty: 2,
      prompt: 'Sag laut, wann du Geburtstag hast und was du an bestimmten Wochentagen normalerweise machst (2–3 Sätze).',
      keywords: ['cumpleaños', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'sábados', 'domingo', 'domingos', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
      minMatch: 3,
      sample: 'Mi cumpleaños es el doce de octubre. Los lunes y los jueves trabajo en casa.',
      feedback: {
        rule: 'Geburtstag: `Mi cumpleaños es el … de …`; Gewohnheiten: `Los lunes …`',
        why: 'Wenn zu wenig erkannt wird, fehlen meist Monat oder Wochentag – oder sie gehen in einer schnellen Aussprache unter.',
        avoid: 'Betone die Tage deutlich: LU-nes, MIÉR-co-les, JUE-ves, VIER-nes.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: TD,
      difficulty: 2,
      scenarioId: 'es.sc.telefon',
      goal: 'Vereinbare am Telefon einen Termin: Nenne Wochentag und Datum, frag nach, ob der Tag passt, und bestätige am Ende das Datum.',
      turns: 4,
      feedback: {
        rule: 'Termin: `el viernes`, `el doce de mayo`, `a las cinco`; kein `en` vor Wochentag oder Datum.',
        why: 'Unter Zeitdruck rutscht leicht „en viernes“ oder „el doce mayo“ (ohne de) heraus.',
        avoid: 'Leg dir den Termin vorher als Satz zurecht: „¿El viernes, doce de mayo, a las cinco?“',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.ir-a'],
      difficulty: 1,
      prompt: 'Wiederholung ir a: `Yo ___ a visitar a mis abuelos el sábado.`',
      options: [
        { text: 'voy' },
        { text: 'va', why: '`va` ist die Form für er / sie / usted.' },
        { text: 'vas', why: '`vas` ist die du-Form.' },
        { text: 'ir', why: 'Der Infinitiv kann hier nicht stehen – ir muss konjugiert werden.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Pläne: konjugiertes `ir` + `a` + Infinitiv – `voy a visitar`.',
        why: 'Das Subjekt ist `yo`, also braucht es die yo-Form `voy`.',
        avoid: 'ir im Präsens: voy, vas, va, vamos, vais, van.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.numbers-big'],
      difficulty: 2,
      audio: 'El viaje cuesta setecientos euros.',
      question: 'Was kostet die Reise?',
      options: ['700 €', '600 €', '70 €', '170 €'],
      answer: 0,
      feedback: {
        rule: '`setecientos` = 700 (unregelmäßig: sete- statt siete-).',
        why: '`seiscientos` wäre 600, `setenta` 70 und `ciento setenta` 170.',
        avoid: 'Hör auf die Endung: -cientos = Hunderter, -enta = Zehner.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: ['es.g.gustar', 'es.g.demonstratives'],
      difficulty: 2,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'Me gusta esos zapatos.',
      answers: ['Me gustan esos zapatos.'],
      german: 'Mir gefallen die Schuhe da.',
      feedback: {
        rule: '`gustar` richtet sich nach dem, was gefällt: `esos zapatos` (Plural) → `gustan`.',
        why: 'Das deutsche „Ich mag“ verleitet dazu, gustar wie ein normales Verb mit „ich“ zu behandeln.',
        avoid: 'Such nach dem Nomen hinter gustar: Plural → gustan.',
      },
    },
  ],
};

export default lesson;
