import type { Lesson } from '../../types';

const L = 'es.a1.l14';
const PREP = ['es.g.prepositions-place'];
const HAY = ['es.g.hay'];

/** „In meiner Wohnung gibt es zwei Schlafzimmer und ein Bad.“ – alle Varianten für Wohnung/Schlafzimmer. */
const FLATS = ['apartamento', 'piso', 'departamento'];
const BEDROOMS = ['dormitorios', 'habitaciones', 'cuartos', 'recámaras'];
const FLAT_ANSWERS = FLATS.flatMap((f) =>
  BEDROOMS.flatMap((r) => [`En mi ${f} hay dos ${r} y un baño.`, `Mi ${f} tiene dos ${r} y un baño.`]),
);

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c5',
  order: 14,
  title: 'Die Wohnung',
  subtitle: 'Zimmer, Möbel und wo alles steht',
  icon: '🏠',
  minutes: 12,
  goal:
    'Du beschreibst deine Wohnung: welche Zimmer und Möbel es gibt (`En la cocina hay una mesa.`) und wo etwas steht (`La lámpara está encima de la mesa.`). Dabei festigst du den Unterschied zwischen **hay** + unbestimmtem Artikel und **estar** + bestimmtem Artikel – und lernst, dass die Wohnung in Spanien `el piso`, in Lateinamerika meist `el departamento` oder `el apartamento` heißt.',
  canDo: [
    'Ich kann die Zimmer meiner Wohnung und wichtige Möbel benennen.',
    'Ich kann mit hay sagen, was es in einem Zimmer gibt.',
    'Ich kann mit estar und Ortsangaben sagen, wo sich etwas befindet.',
    'Ich kann meine Wohnung in einigen Sätzen beschreiben.',
  ],
  topicIds: ['es.g.prepositions-place', 'es.g.hay'],
  vocab: [
    { id: `${L}.v.piso`, target: 'el piso', german: 'die Wohnung; das Stockwerk', pos: 'noun', gender: 'm', plural: 'los pisos', emoji: '🏢', variant: 'es-ES', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Mi piso tiene dos dormitorios.', german: 'Meine Wohnung hat zwei Schlafzimmer.' } },
    { id: `${L}.v.departamento`, target: 'el departamento', german: 'die Wohnung', pos: 'noun', gender: 'm', plural: 'los departamentos', emoji: '🏢', variant: 'es-LA', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Vivo en un departamento pequeño.', german: 'Ich wohne in einer kleinen Wohnung.' } },
    { id: `${L}.v.apartamento`, target: 'el apartamento', german: 'die Wohnung (Lateinamerika; in Spanien eher die kleine Ferienwohnung)', pos: 'noun', gender: 'm', plural: 'los apartamentos', emoji: '🏢', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Mi apartamento es pequeño.', german: 'Meine Wohnung ist klein.' } },
    { id: `${L}.v.habitacion`, target: 'la habitación', german: 'das Zimmer', pos: 'noun', gender: 'f', plural: 'las habitaciones', emoji: '🚪', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: '¿Cuántas habitaciones tiene la casa?', german: 'Wie viele Zimmer hat das Haus?' } },
    { id: `${L}.v.dormitorio`, target: 'el dormitorio', german: 'das Schlafzimmer', pos: 'noun', gender: 'm', plural: 'los dormitorios', emoji: '🛌', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'El dormitorio está al lado del baño.', german: 'Das Schlafzimmer ist neben dem Bad.' } },
    { id: `${L}.v.salon`, target: 'el salón', german: 'das Wohnzimmer', pos: 'noun', gender: 'm', plural: 'los salones', emoji: '📺', variant: 'es-ES', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'En el salón hay un sofá.', german: 'Im Wohnzimmer steht ein Sofa.' } },
    { id: `${L}.v.sala`, target: 'la sala', german: 'das Wohnzimmer', pos: 'noun', gender: 'f', plural: 'las salas', emoji: '📺', variant: 'es-LA', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'En la sala hay un sofá.', german: 'Im Wohnzimmer steht ein Sofa.' } },
    { id: `${L}.v.cocina`, target: 'la cocina', german: 'die Küche', pos: 'noun', gender: 'f', plural: 'las cocinas', emoji: '🍳', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'La cocina es pequeña pero bonita.', german: 'Die Küche ist klein, aber schön.' } },
    { id: `${L}.v.bano`, target: 'el baño', german: 'das Bad; die Toilette', pos: 'noun', gender: 'm', plural: 'los baños', emoji: '🛁', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: '¿Dónde está el baño?', german: 'Wo ist das Bad / die Toilette?' } },
    { id: `${L}.v.ducha`, target: 'la ducha', german: 'die Dusche', pos: 'noun', gender: 'f', plural: 'las duchas', emoji: '🚿', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'En el baño hay una ducha.', german: 'Im Bad gibt es eine Dusche.' } },
    { id: `${L}.v.cama`, target: 'la cama', german: 'das Bett', pos: 'noun', gender: 'f', plural: 'las camas', emoji: '🛏️', field: 'Möbel', stageId: 'a1', lessonId: L, example: { target: 'La cama está debajo de la ventana.', german: 'Das Bett steht unter dem Fenster.' } },
    { id: `${L}.v.silla`, target: 'la silla', german: 'der Stuhl', pos: 'noun', gender: 'f', plural: 'las sillas', emoji: '🪑', field: 'Möbel', stageId: 'a1', lessonId: L, example: { target: 'En la cocina hay cuatro sillas.', german: 'In der Küche gibt es vier Stühle.' } },
    { id: `${L}.v.sofa`, target: 'el sofá', german: 'das Sofa', pos: 'noun', gender: 'm', plural: 'los sofás', emoji: '🛋️', field: 'Möbel', stageId: 'a1', lessonId: L, example: { target: 'El gato está en el sofá.', german: 'Die Katze ist auf dem Sofa.' } },
    { id: `${L}.v.ventana`, target: 'la ventana', german: 'das Fenster', pos: 'noun', gender: 'f', plural: 'las ventanas', emoji: '🪟', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'La mesa está delante de la ventana.', german: 'Der Tisch steht vor dem Fenster.' } },
    { id: `${L}.v.lampara`, target: 'la lámpara', german: 'die Lampe', pos: 'noun', gender: 'f', plural: 'las lámparas', emoji: '💡', field: 'Möbel', stageId: 'a1', lessonId: L, example: { target: 'La lámpara está encima de la mesa.', german: 'Die Lampe steht auf dem Tisch.' } },
    { id: `${L}.v.encima-de`, target: 'encima de', german: 'auf, über (oben auf)', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'Las llaves están encima de la mesa.', german: 'Die Schlüssel liegen auf dem Tisch.' } },
    { id: `${L}.v.debajo-de`, target: 'debajo de', german: 'unter', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'El gato está debajo de la cama.', german: 'Die Katze ist unter dem Bett.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Für eine Wohnungsbeschreibung brauchst du drei Werkzeuge:\n- **tener** für die Ausstattung: `Mi piso tiene tres habitaciones.`\n- **hay** für das, was es gibt: `En la cocina hay una mesa.`\n- **estar** für den Ort: `La mesa está en la cocina.`\nZu den Ortsangaben aus Lektion 5 (`al lado de`, `delante de`, `detrás de`, `enfrente de`, `entre` …) kommen zwei neue dazu: `encima de` (auf, oben auf) und `debajo de` (unter). Denk an die Verschmelzung `de + el = del`: `encima del sofá`, aber `encima de la mesa`.',
    },
    {
      type: 'table',
      title: 'hay oder estar?',
      headers: ['', 'hay', 'estar'],
      rows: [
        ['Frage', '¿Qué hay …? – Was gibt es?', '¿Dónde está …? – Wo ist …?'],
        ['danach steht', 'un / una / unos / unas, eine Zahl oder kein Artikel', 'el / la / los / las, mi / tu / su …, ein Name'],
        ['Beispiel', 'En la cocina hay una mesa.', 'La mesa está en la cocina.'],
        ['Plural', 'Hay dos sillas. (hay bleibt immer gleich)', 'Las sillas están en la cocina.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'La lámpara', role: 'subject' },
        { text: ' ' },
        { text: 'está', role: 'verb' },
        { text: ' ' },
        { text: 'encima de', role: 'preposition' },
        { text: ' ' },
        { text: 'la mesa', role: 'noun' },
        { text: '.' },
      ],
      german: 'Die Lampe steht auf dem Tisch.',
    },
    {
      type: 'compare',
      target: 'Las llaves están en la mesa.',
      german: 'Die Schlüssel liegen auf dem Tisch.',
      md:
        'Im Deutschen unterscheidest du stehen, liegen, sitzen und hängen. Spanisch macht es dir leicht: Für den Ort reicht **estar** – egal, ob etwas steht, liegt oder hängt: `La lámpara está en el salón.` (steht) – `Las llaves están en la mesa.` (liegen). Und `en` kann „in“ und „auf“ heißen: `en la mesa` = auf dem Tisch, `en la cocina` = in der Küche.',
    },
    {
      type: 'mistake',
      wrong: 'En la cocina está una mesa.',
      right: 'En la cocina hay una mesa.',
      why:
        'Wird etwas zum ersten Mal erwähnt – mit `un`, `una`, einer Zahl oder ganz ohne Artikel –, steht **hay**. `estar` brauchst du für Dinge, die schon bekannt sind: `La mesa está en la cocina.` Umgekehrt ist auch „Hay la cama …“ falsch.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika heißt die Wohnung meist `el departamento` (z. B. Mexiko, Argentinien, Chile, Peru) oder `el apartamento` (z. B. Kolumbien, Venezuela, Karibik). Das Wohnzimmer ist `la sala`, das Schlafzimmer oft `el cuarto` – in Mexiko auch `la recámara`.\nIn Spanien sagt man `el piso` und `el salón`; `el apartamento` ist dort eher eine kleine (Ferien-)Wohnung. `el piso` heißt überall auch „Stockwerk“ – in Lateinamerika zusätzlich „Fußboden“.',
    },
    {
      type: 'tip',
      md:
        'Merksatz: **Was gibt es? → hay + ein/eine/Zahl. Wo ist es? → está(n) + der/die/das.**\n`Hay un sofá.` – `El sofá está delante de la ventana.`',
    },
    {
      type: 'audio',
      text: 'En mi casa hay una cocina grande, un baño y dos habitaciones. Mi habitación está al lado del baño.',
      label: 'Hör zu: eine Wohnung beschreiben',
    },
  ],
  examples: [
    {
      target: 'Mi piso tiene dos dormitorios y un salón grande.',
      german: 'Meine Wohnung hat zwei Schlafzimmer und ein großes Wohnzimmer.',
      variant: 'es-ES',
      parts: [
        { text: 'Mi piso', role: 'subject' },
        { text: ' ' },
        { text: 'tiene', role: 'verb' },
        { text: ' ' },
        { text: 'dos dormitorios y un salón grande', role: 'object' },
        { text: '.' },
      ],
    },
    {
      target: 'Mi departamento tiene dos dormitorios y una sala grande.',
      german: 'Meine Wohnung hat zwei Schlafzimmer und ein großes Wohnzimmer.',
      variant: 'es-LA',
    },
    {
      target: 'En la cocina hay una mesa y cuatro sillas.',
      german: 'In der Küche gibt es einen Tisch und vier Stühle.',
      parts: [
        { text: 'En', role: 'preposition' },
        { text: ' ' },
        { text: 'la cocina', role: 'noun' },
        { text: ' ' },
        { text: 'hay', role: 'verb' },
        { text: ' ' },
        { text: 'una mesa y cuatro sillas', role: 'object' },
        { text: '.' },
      ],
    },
    {
      target: 'El sofá está delante de la ventana.',
      german: 'Das Sofa steht vor dem Fenster.',
      parts: [
        { text: 'El sofá', role: 'subject' },
        { text: ' ' },
        { text: 'está', role: 'verb' },
        { text: ' ' },
        { text: 'delante de', role: 'preposition' },
        { text: ' ' },
        { text: 'la ventana', role: 'noun' },
        { text: '.' },
      ],
    },
    {
      target: 'El gato está debajo de la cama.',
      german: 'Die Katze ist unter dem Bett.',
    },
    {
      target: '¿Dónde está el baño? – Está al lado del dormitorio.',
      german: 'Wo ist das Bad? – Es ist neben dem Schlafzimmer.',
      note: '`de + el = del`. Mit `¿Dónde está el baño?` fragst du auch im Restaurant oder Café nach der Toilette.',
    },
    {
      target: 'En mi habitación no hay tele, pero hay muchos libros.',
      german: 'In meinem Zimmer gibt es keinen Fernseher, aber viele Bücher.',
      note: 'Nach `no hay` fällt der Artikel meist weg: `no hay tele`, `no hay balcón`.',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: HAY,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '🛏️', word: 'la cama' },
        { emoji: '🪑', word: 'la silla' },
        { emoji: '🛋️', word: 'el sofá' },
        { emoji: '🪟', word: 'la ventana' },
        { emoji: '💡', word: 'la lámpara' },
        { emoji: '🚿', word: 'la ducha' },
      ],
      feedback: {
        rule: 'Möbel lernst du am besten mit Artikel: `la cama`, `la silla`, `el sofá`, `la ventana`, `la lámpara`, `la ducha`.',
        why: '`el sofá` endet auf -á, ist aber maskulin – das Geschlecht erkennst du nicht immer an der Endung.',
        avoid: 'Beschrifte in Gedanken deine eigene Wohnung: Wohin du auch schaust, sag das Wort mit Artikel.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: HAY,
      difficulty: 1,
      prompt: 'Welche Form passt? `En el dormitorio ___ una cama y una lámpara.`',
      options: [
        { text: 'hay' },
        { text: 'está', why: 'Nach `una` (etwas Neues, Unbestimmtes) steht hay. estar bräuchte einen bestimmten Artikel: `La cama está en el dormitorio.`' },
        { text: 'están', why: 'Auch bei mehreren Dingen bleibt es bei hay – hay hat keine Pluralform.' },
        { text: 'es', why: 'ser beschreibt Eigenschaften, nicht, was sich in einem Raum befindet.' },
      ],
      answer: 0,
      feedback: {
        rule: '`hay` + unbestimmter Artikel / Zahl: `hay una cama`, `hay dos sillas`.',
        why: 'Das deutsche „steht“ oder „ist“ verleitet zu estar. Wird etwas aber neu genannt, sagt Spanisch „es gibt“ = hay.',
        avoid: 'Schau auf das Wort nach der Lücke: un/una/Zahl → hay.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'matchPairs',
      skills: ['vocabulary', 'grammar'],
      topicIds: PREP,
      difficulty: 1,
      instruction: 'Ordne die Ortsangaben ihrer deutschen Bedeutung zu.',
      pairs: [
        { left: 'encima de', right: 'auf (oben auf)' },
        { left: 'debajo de', right: 'unter' },
        { left: 'delante de', right: 'vor' },
        { left: 'detrás de', right: 'hinter' },
        { left: 'al lado de', right: 'neben' },
        { left: 'entre', right: 'zwischen' },
      ],
      feedback: {
        rule: 'Ortsangaben mit `de`: encima de, debajo de, delante de, detrás de, al lado de. `entre` steht ohne de: `entre la cama y la ventana`.',
        why: '`delante de` (vor) und `detrás de` (hinter) werden leicht vertauscht; `enfrente de` heißt „gegenüber“.',
        avoid: 'Bilder helfen: en**cima** – wie „la cima“ (der Gipfel) = oben; de**bajo** – wie „bajo“ (niedrig) = unten.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: [...HAY, ...PREP],
      difficulty: 2,
      instruction: 'hay oder estar? Setze die passende Form ein.',
      sentence: 'El sofá ___ delante de la ventana y encima del sofá ___ dos gatos.',
      answers: [['está'], ['hay']],
      bank: ['está', 'están', 'hay', 'es'],
      german: 'Das Sofa steht vor dem Fenster, und auf dem Sofa liegen zwei Katzen.',
      feedback: {
        rule: '`el sofá` (bestimmt, bekannt) → `está`; `dos gatos` (Zahl, neu erwähnt) → `hay`.',
        why: '`están` würde passen, wenn die Katzen schon bekannt wären (`los gatos están …`). Mit einer Zahl davor steht aber hay.',
        avoid: 'Schau auf das Wort nach dem Verb: el/la/los/las → estar; un/una/Zahl → hay.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: HAY,
      difficulty: 2,
      audio: 'Mi apartamento es pequeño: tiene un dormitorio, un baño y una cocina, pero no tiene balcón.',
      question: 'Was stimmt über die Wohnung?',
      options: ['1 Schlafzimmer, kein Balkon', '2 Schlafzimmer, kein Balkon', '1 Schlafzimmer, keine Küche', '2 Schlafzimmer, kein Bad'],
      answer: 0,
      feedback: {
        rule: '`tiene un dormitorio` = hat ein Schlafzimmer; `no tiene balcón` = hat keinen Balkon.',
        why: 'Küche und Bad werden ausdrücklich genannt – nur der Balkon fehlt (`no tiene`).',
        avoid: 'Achte beim Hören auf `no`: Es steht direkt vor dem Verb und dreht die Aussage um.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: PREP,
      difficulty: 2,
      instruction: 'Bilde den Satz „Die Lampe steht neben dem Bett.“',
      tokens: ['La', 'lámpara', 'está', 'al', 'lado', 'de', 'la', 'cama.'],
      extra: ['hay', 'del'],
      german: 'Die Lampe steht neben dem Bett.',
      feedback: {
        rule: 'Bekanntes Ding + `está` + Ortsangabe: `La lámpara está al lado de la cama.`',
        why: '`hay` passt nicht zu `la lámpara` (bestimmter Artikel). `del` = de + el – vor `la cama` bleibt es bei `de la`.',
        avoid: '`del` nur vor maskulinen Nomen: `al lado del sofá`, aber `al lado de la cama`.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: HAY,
      difficulty: 3,
      direction: 'toTarget',
      source: 'In meiner Wohnung gibt es zwei Schlafzimmer und ein Bad.',
      answers: FLAT_ANSWERS,
      feedback: {
        rule: '„es gibt“ = `hay`; „meine Wohnung“ = `mi piso` (Spanien) bzw. `mi departamento` / `mi apartamento` (Lateinamerika).',
        why: '„es hay“ oder „está dos dormitorios“ sind typische Fehler: hay steht allein – ohne es und ohne estar.',
        avoid: '„es gibt“ ist auf Spanisch immer nur ein Wort: `hay`.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: HAY,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'En la cocina está una mesa grande.',
      answers: ['En la cocina hay una mesa grande.'],
      german: 'In der Küche gibt es einen großen Tisch.',
      feedback: {
        rule: 'Neu erwähnte Dinge mit un/una → `hay`: `En la cocina hay una mesa grande.`',
        why: '`está` verlangt ein bestimmtes, bekanntes Ding (`la mesa`). Mit `una mesa` klingt der Satz für Muttersprachler falsch.',
        avoid: 'Übersetze „es gibt“ gedanklich mit – wo es passt, steht hay.',
      },
    },
  ],
  pronunciation: ['es.p.link.esta-en-el-centro', 'es.p.ny.espanol'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: [...PREP, ...HAY],
      difficulty: 2,
      instruction: 'Ergänze die fehlende Antwort im Gespräch.',
      lines: [
        { speaker: 'Pablo', text: '¡Qué bonito! ¿Cuántas habitaciones tiene tu apartamento?', german: 'Wie schön! Wie viele Zimmer hat deine Wohnung?' },
        { speaker: 'Du', text: 'Tiene dos dormitorios, un baño y una cocina.', german: 'Sie hat zwei Schlafzimmer, ein Bad und eine Küche.' },
        { speaker: 'Pablo', text: '¿Y dónde está la cocina?', german: 'Und wo ist die Küche?' },
        { speaker: 'Du', text: 'Está al lado del baño.', german: 'Sie ist neben dem Bad.' },
      ],
      gapIndex: 3,
      options: ['Está al lado del baño.', 'Hay al lado del baño.', 'Está al lado de el baño.', 'Es al lado del baño.'],
      answer: 0,
      feedback: {
        rule: 'Ort eines bekannten Raums → `está` + Ortsangabe; `de + el` wird immer zu `del`.',
        why: '`Hay` braucht etwas Neues danach, `Es` beschreibt keinen Ort, und „de el“ wird immer zu `del` zusammengezogen.',
        avoid: 'Frage mit `¿Dónde está …?` → Antwort mit `Está …`.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: [...HAY, ...PREP],
      difficulty: 2,
      prompt: 'Beschreibe deine Wohnung (oder deine Traumwohnung) in 4–5 Sätzen: Welche Zimmer gibt es? Welche Möbel stehen wo?',
      requirements: [
        { pattern: '\\bhay\\b', hint: 'hay (es gibt)' },
        { pattern: '\\best(a|á|an|án)\\b', hint: 'estar für den Ort (está / están)' },
        { pattern: '(encima|debajo|delante|detr[aá]s|al lado|enfrente|entre|cerca|lejos|derecha|izquierda)', hint: 'eine Ortsangabe (al lado de, encima de …)' },
        { pattern: '(cocina|ba[nñ]o|dormitorio|habitaci[oó]n|sal[oó]n|\\bsala\\b|cuarto|balc[oó]n)', hint: 'mindestens ein Zimmer' },
      ],
      samples: [
        'Vivo en un piso pequeño en el centro. Hay un salón, una cocina, un baño y un dormitorio. En el salón hay un sofá y una mesa. El sofá está delante de la ventana. La lámpara está al lado del sofá.',
      ],
      minWords: 20,
      feedback: {
        rule: 'Was es gibt → `hay` + un/una; wo es steht → `está` + Ortsangabe.',
        why: 'Typisch sind „está una mesa“ statt `hay una mesa` und „de el“ statt `del`.',
        avoid: 'Lies deinen Text einmal nur auf hay/está durch: Steht danach un/una → hay, steht el/la → está.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: [...HAY, ...PREP],
      difficulty: 2,
      prompt: 'Beschreib laut dein Zimmer: Was gibt es darin, und wo steht es? (3 Sätze)',
      keywords: ['hay', 'está', 'están', 'cama', 'mesa', 'silla', 'sofá', 'lámpara', 'ventana', 'al lado', 'encima', 'debajo', 'delante', 'detrás'],
      minMatch: 4,
      sample: 'En mi habitación hay una cama y una mesa. La lámpara está encima de la mesa. La cama está al lado de la ventana.',
      feedback: {
        rule: 'Erst sagen, was es gibt (`hay una cama`), dann, wo es steht (`la cama está al lado de …`).',
        why: 'Werden zu wenige Schlüsselwörter erkannt, fehlen meist die Ortsangaben oder die Sätze waren sehr kurz.',
        avoid: 'Sprich in ganzen Sätzen und betone die Möbelwörter deutlich: la CA-ma, la VEN-ta-na, la LÁM-pa-ra.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      audio: '¿Por qué no vamos al cine el sábado?',
      answers: ['¿Por qué no vamos al cine el sábado?'],
      german: 'Warum gehen wir nicht am Samstag ins Kino?',
      feedback: {
        rule: '`¿Por qué no …?` – getrennt und mit Akzent auf qué; `sábado` trägt den Akzent auf der ersten Silbe.',
        why: 'Wer `porque` schreibt, macht aus der Frage ein „weil“.',
        avoid: 'In Fragen: `por qué` (zwei Wörter, Akzent). In Antworten: `porque`.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.stem-change'],
      difficulty: 1,
      verb: 'poder',
      tense: 'Präsens',
      person: 'tú',
      sentence: '¿___ venir a mi casa el viernes?',
      answers: ['puedes'],
      feedback: {
        rule: 'poder (o→ue): puedo, puedes, puede, podemos, (podéis), pueden.',
        why: '„podes“ ohne Stammwechsel ist für tú falsch. (Die argentinische vos-Form heißt `podés` – mit Akzent und nur für vos.)',
        avoid: 'Liegt die Betonung auf dem Stamm, steht ue: PUE-des.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'mc',
      skills: ['vocabulary'],
      topicIds: ['es.g.numbers-big'],
      difficulty: 2,
      prompt: 'Das Sofa kostet 450 €. Wie sagst du den Preis?',
      options: [
        { text: 'cuatrocientos cincuenta euros' },
        { text: 'cuatrocientas cincuenta euros', why: '`euro` ist maskulin → `cuatrocientos`. Die Form auf -as brauchst du nur bei femininen Nomen: `cuatrocientas personas`.' },
        { text: 'cuatrocientos y cincuenta euros', why: 'Zwischen Hunderter und Zehner steht kein y. `y` steht nur zwischen Zehner und Einer: `cincuenta y cinco`.' },
        { text: 'cuarenta y cinco euros', why: 'Das sind 45 €, nicht 450 €.' },
      ],
      answer: 0,
      feedback: {
        rule: '450 = `cuatrocientos cincuenta`. Die Hunderter passen sich dem Nomen an (`cuatrocientos euros`, `cuatrocientas personas`).',
        why: 'Weil Spanisch bei `cincuenta y cinco` ein y hat, setzen viele es auch nach dem Hunderter. Dort steht aber nie ein y.',
        avoid: 'Merke: y nur ganz hinten – `cuatrocientos cincuenta y cinco` (455).',
      },
    },
  ],
};

export default lesson;
