import type { Lesson } from '../../types';

const L = 'es.a1.l16';
const POL = ['es.g.polite-requests'];

/** „Heute ist es kalt, aber morgen wird es sonnig.“ – Wortstellung von hoy und Zukunft mit/ohne ir a. */
const WEATHER_ANSWERS = ['Hoy hace frío', 'Hace frío hoy'].flatMap((a) =>
  ['mañana va a hacer sol', 'mañana hace sol', 'mañana va a estar soleado'].map((b) => `${a}, pero ${b}.`),
);

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c5',
  order: 16,
  title: 'Höflich bitten & A1-Rückblick',
  subtitle: 'Bitten, danken – und alles aus A1 noch einmal im Mix',
  icon: '🙏',
  minutes: 14,
  goal:
    'Du lernst, höflich um etwas zu bitten – `¿Puedes …?`, `¿Me pasas …?`, `Quisiera …` – und passend auf Dank zu reagieren. Danach wiederholst du im großen **A1-Mix** alles, was du in dieser Etappe gelernt hast: von tener und gustar über Wegbeschreibungen, Restaurant und Wetter bis zu Wohnung und Verabredungen. Du bist fast am Ziel – ¡ánimo!',
  canDo: [
    'Ich kann mit ¿Puedes …? / ¿Puede …? höflich um Hilfe bitten.',
    'Ich kann mit ¿Me pasas …? / ¿Me das …? um Dinge bitten und mit Quisiera … Wünsche äußern.',
    'Ich kann auf Bitten und Dank passend reagieren (claro, aquí tienes, de nada).',
    'Ich kann die wichtigsten A1-Strukturen in Alltagssituationen sicher anwenden.',
  ],
  topicIds: ['es.g.polite-requests'],
  vocab: [
    { id: `${L}.v.puedes`, target: '¿Puedes …?', german: 'Kannst du …?', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Puedes abrir la ventana?', german: 'Kannst du das Fenster aufmachen?' } },
    { id: `${L}.v.puede`, target: '¿Puede …?', german: 'Können Sie …?', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Puede repetir, por favor?', german: 'Können Sie das bitte wiederholen?' } },
    { id: `${L}.v.me-pasas`, target: '¿Me pasas …?', german: 'Reichst du mir …? / Gibst du mir mal …?', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Me pasas el pan?', german: 'Gibst du mir mal das Brot?' } },
    { id: `${L}.v.me-das`, target: '¿Me das …?', german: 'Gibst du mir …?', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Me das tu número de teléfono?', german: 'Gibst du mir deine Telefonnummer?' } },
    { id: `${L}.v.quisiera`, target: 'quisiera', german: 'ich hätte gern; ich würde gern', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: 'Quisiera un café con leche, por favor.', german: 'Ich hätte gern einen Milchkaffee, bitte.' } },
    { id: `${L}.v.ayudar`, target: 'ayudar', german: 'helfen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: '¿Me ayudas, por favor?', german: 'Hilfst du mir bitte?' } },
    { id: `${L}.v.no-entiendo`, target: 'No entiendo.', german: 'Ich verstehe (das) nicht. (entender, e → ie)', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: 'Perdone, no entiendo. ¿Puede repetir?', german: 'Entschuldigung, ich verstehe nicht. Können Sie das wiederholen?' } },
    { id: `${L}.v.repetir`, target: 'repetir', german: 'wiederholen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: '¿Puedes repetir, por favor?', german: 'Kannst du das bitte wiederholen?' } },
    { id: `${L}.v.mas-despacio`, target: 'más despacio', german: 'langsamer', pos: 'adv', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Puede hablar más despacio?', german: 'Können Sie langsamer sprechen?' } },
    { id: `${L}.v.por-favor`, target: 'por favor', german: 'bitte (wenn du um etwas bittest)', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Me das la sal, por favor?', german: 'Gibst du mir bitte das Salz?' } },
    { id: `${L}.v.de-nada`, target: 'de nada', german: 'gern geschehen, bitte (als Antwort auf Danke)', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: 'Gracias. – De nada.', german: 'Danke. – Gern geschehen.' } },
    { id: `${L}.v.aqui-tienes`, target: 'aquí tienes / aquí tiene', german: 'bitte schön, hier bitte (beim Überreichen)', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Me pasas el agua? – Sí, aquí tienes.', german: 'Reichst du mir das Wasser? – Ja, bitte schön.' } },
    { id: `${L}.v.claro`, target: '¡Claro!', german: 'Klar! Natürlich!', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: '¿Me ayudas? – ¡Claro!', german: 'Hilfst du mir? – Klar!' } },
    { id: `${L}.v.con-gusto`, target: 'con gusto', german: 'gern (geschehen)', pos: 'phrase', variant: 'es-LA', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: 'Muchas gracias. – Con gusto.', german: 'Vielen Dank. – Gern geschehen.' } },
    { id: `${L}.v.sal`, target: 'la sal', german: 'das Salz', pos: 'noun', gender: 'f', emoji: '🧂', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: '¿Me pasas la sal?', german: 'Reichst du mir das Salz?' } },
    { id: `${L}.v.pan`, target: 'el pan', german: 'das Brot', pos: 'noun', gender: 'm', emoji: '🍞', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'El pan está en la mesa.', german: 'Das Brot ist auf dem Tisch.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Auf Spanisch bittest du vor allem mit **Fragen**:\n- `¿Puedes …?` / `¿Puede …?` + Infinitiv: `¿Puedes abrir la ventana?` (du) – `¿Puede repetir, por favor?` (Sie)\n- Präsens-Frage mit `me` (mir): `¿Me pasas la sal?`, `¿Me das tu número?`, `¿Me ayudas?`\n- `Quisiera …` = „Ich hätte gern …“ / „Ich würde gern …“ – besonders höflich, ideal im Geschäft, im Hotel oder am Telefon: `Quisiera una habitación doble.`\nIn Spanien bestellt man an der Bar oft mit `poner`: `¿Me pones un café?` (du) / `¿Me pone un café?` (Sie).',
    },
    {
      type: 'colored',
      parts: [
        { text: '¿' },
        { text: 'Me', role: 'pronoun' },
        { text: ' ' },
        { text: 'pasas', role: 'verb' },
        { text: ' ' },
        { text: 'la sal', role: 'object' },
        { text: ', ' },
        { text: 'por favor', role: 'other' },
        { text: '?' },
      ],
      german: 'Gibst du mir bitte das Salz?',
    },
    {
      type: 'compare',
      target: '¿Me pasas el pan?',
      german: 'Könntest du mir bitte das Brot geben?',
      md:
        'Im Deutschen wirkt „Gibst du mir das Brot?“ schnell etwas knapp – man greift zu „könntest“ und „bitte“. Auf Spanisch ist die einfache Präsens-Frage am Tisch ganz normal und freundlich. Der Ton macht die Musik: Satzmelodie am Ende nach oben und gern ein `por favor` dazu.',
    },
    {
      type: 'table',
      title: 'Bitten, danken & reagieren',
      headers: ['Situation', 'Spanisch', 'Deutsch'],
      rows: [
        ['Du bekommst etwas', 'Gracias. / Muchas gracias.', 'Danke. / Vielen Dank.'],
        ['Jemand dankt dir', 'De nada. / No hay de qué.', 'Gern geschehen.'],
        ['Du gibst etwas', 'Aquí tienes. / Aquí tiene.', 'Bitte schön. / Hier, bitte.'],
        ['Du sagst zu', '¡Claro! / ¡Por supuesto!', 'Klar! / Selbstverständlich!'],
        ['Du verstehst nicht', 'Perdone, no entiendo. ¿Puede repetir?', 'Entschuldigung, ich verstehe nicht. Können Sie das wiederholen?'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Gracias. – Por favor.',
      right: 'Gracias. – De nada.',
      why:
        'Das deutsche „Bitte“ hat drei Aufgaben, Spanisch hat dafür drei Ausdrücke: `por favor` (wenn du um etwas bittest), `aquí tienes` / `aquí tiene` (wenn du etwas überreichst) und `de nada` (als Antwort auf „Danke“).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika antwortet man auf `gracias` gern mit `Con gusto.` oder `Con mucho gusto.` (z. B. Kolumbien, Mittelamerika); in Mexiko hört man auch `Para servirle.` In Kolumbien bittet man im Geschäft oft mit `¿Me regala …?` – wörtlich „Schenken Sie mir …?“, gemeint ist aber einfach „Geben Sie mir bitte …“. Bezahlt wird natürlich trotzdem!',
    },
    {
      type: 'tip',
      md:
        'Merksatz: **Drei deutsche „Bitte“ – drei spanische Ausdrücke:** bitten = `por favor`, geben = `aquí tienes`, auf Danke antworten = `de nada`.',
    },
    {
      type: 'text',
      md:
        '**Dein A1-Rückblick** – das hast du in dieser Etappe geschafft:\n- Familie und Alter mit `tener`, Vorlieben mit `gustar`\n- Tagesablauf mit reflexiven Verben, Pläne mit `ir a` + Infinitiv\n- Orte, Wege und Verkehrsmittel: `hay` / `está`, `siga recto`, `en metro`\n- Restaurant und Markt: `quiero`, `prefiero`, `pido`, Zahlen bis 1000\n- Kleidung mit `este / ese / aquel`, Datum und Wetter\n- Verabredungen mit `poder` und `hago, salgo …`, Wohnung und Menschen beschreiben\nDie Übungen dieser Lektion mischen alles bunt durch – das perfekte Aufwärmtraining für die A1-Abschlussprüfung.',
    },
  ],
  examples: [
    {
      target: '¿Puedes abrir la ventana, por favor?',
      german: 'Kannst du bitte das Fenster aufmachen?',
      parts: [
        { text: '¿' },
        { text: 'Puedes', role: 'verb' },
        { text: ' ' },
        { text: 'abrir', role: 'verb' },
        { text: ' ' },
        { text: 'la ventana', role: 'object' },
        { text: ', ' },
        { text: 'por favor', role: 'other' },
        { text: '?' },
      ],
    },
    {
      target: '¿Puede hablar más despacio, por favor?',
      german: 'Können Sie bitte langsamer sprechen?',
      note: 'Der wichtigste Satz für Sprachlernende – benutz ihn ohne Scheu!',
    },
    {
      target: '¿Me pasas la sal?',
      german: 'Reichst du mir mal das Salz?',
    },
    {
      target: 'Quisiera una habitación doble para dos noches.',
      german: 'Ich hätte gern ein Doppelzimmer für zwei Nächte.',
      parts: [
        { text: 'Quisiera', role: 'verb' },
        { text: ' ' },
        { text: 'una habitación doble', role: 'object' },
        { text: ' ' },
        { text: 'para dos noches', role: 'adverb' },
        { text: '.' },
      ],
      note: '`quisiera` ist eine besonders höfliche Form von querer – lern sie einfach als festen Ausdruck.',
    },
    {
      target: '¿Me pones un café con leche?',
      german: 'Einen Milchkaffee, bitte.',
      literal: 'Stellst du mir einen Milchkaffee hin?',
      variant: 'es-ES',
      note: 'In spanischen Bars völlig normal – dort wird auch das Personal oft geduzt.',
    },
    {
      target: '¿Me da dos kilos de tomates, por favor?',
      german: 'Ich hätte gern zwei Kilo Tomaten, bitte.',
      literal: 'Geben Sie mir bitte zwei Kilo Tomaten?',
    },
    {
      target: 'Muchas gracias. – De nada.',
      german: 'Vielen Dank. – Gern geschehen.',
    },
    {
      target: 'Muchas gracias. – Con gusto.',
      german: 'Vielen Dank. – Gern geschehen.',
      variant: 'es-LA',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary'],
      topicIds: POL,
      difficulty: 1,
      instruction: 'Welche spanische Wendung passt?',
      pairs: [
        { left: 'Hilfst du mir?', right: '¿Me ayudas?' },
        { left: 'Gern geschehen.', right: 'De nada.' },
        { left: 'Hier, bitte. (beim Überreichen)', right: 'Aquí tienes.' },
        { left: 'Ich hätte gern …', right: 'Quisiera …' },
        { left: 'Klar!', right: '¡Claro!' },
      ],
      feedback: {
        rule: '`¿Me ayudas?` = Hilfst du mir?, `De nada.` = Gern geschehen., `Aquí tienes.` = Bitte schön (beim Geben), `Quisiera …` = Ich hätte gern …, `¡Claro!` = Klar!',
        why: 'Das deutsche „bitte“ beim Überreichen ist `aquí tienes` – nicht `por favor` und nicht `de nada`.',
        avoid: 'Stell dir die Szene vor: Bitte ich? Gebe ich? Antworte ich auf Danke? Jede Szene hat ihren eigenen Ausdruck.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: POL,
      difficulty: 1,
      scenario: 'Du bist bei einer spanischen Familie zum Abendessen eingeladen. Das Brot steht vor Carmen, und du möchtest ein Stück. Was sagst du?',
      options: [
        { text: 'Carmen, ¿me pasas el pan, por favor?' },
        { text: 'Carmen, ¿te pasas el pan, por favor?', why: '`te pasas` hieße „reichst du dir“. Du möchtest das Brot für dich: `me` = mir.' },
        { text: 'Carmen, ¿me pasas el pan, de nada?', why: '`de nada` ist die Antwort auf „Danke“. Beim Bitten brauchst du `por favor`.' },
        { text: 'Carmen, ¿puedo el pan?', why: 'Nach `puedo` fehlt das Verb – und so fragst du, ob **du** etwas darfst. Viel natürlicher: `¿Me pasas el pan?`' },
      ],
      answer: 0,
      feedback: {
        rule: 'Um etwas bitten: `¿Me pasas …, por favor?` – `me` zeigt, dass es für dich ist.',
        why: '`te` bezieht sich auf die andere Person, `de nada` antwortet auf Dank, und `poder` braucht immer einen Infinitiv.',
        avoid: 'Merke die Formel: ¿Me + Verb (du-Form) + Sache + por favor?',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: [...POL, 'es.g.stem-change'],
      difficulty: 2,
      instruction: 'Setze die passenden Formen ein. Du siezt die Person („Perdone“).',
      sentence: 'Perdone, ¿___ hablar más despacio, por favor? Es que no ___ bien.',
      answers: [['puede'], ['entiendo']],
      bank: ['puede', 'puedes', 'entiendo', 'entendo'],
      german: 'Entschuldigen Sie, können Sie bitte langsamer sprechen? Ich verstehe nämlich nicht gut.',
      feedback: {
        rule: '`Perdone` ist die usted-Form → `¿Puede …?`. `entender` hat den Stammwechsel e→ie: `entiendo`.',
        why: '`puedes` passt zu `perdona` (du), nicht zu `perdone` (Sie). „entendo“ gibt es nicht – wie bei `quiero` wird das betonte e zu ie.',
        avoid: 'Bleib bei einer Anredeform: perdona + puedes (du) oder perdone + puede (Sie).',
      },
    },
    {
      id: `${L}.g04`,
      type: 'order',
      skills: ['grammar'],
      topicIds: POL,
      difficulty: 2,
      instruction: 'Bilde den Satz „Ich hätte gern einen Tisch für zwei Personen.“',
      tokens: ['Quisiera', 'una', 'mesa', 'para', 'dos', 'personas.'],
      extra: ['por'],
      german: 'Ich hätte gern einen Tisch für zwei Personen.',
      feedback: {
        rule: '`Quisiera` + Nomen = höfliche Bitte. „für zwei Personen“ = `para dos personas`.',
        why: '`por` passt hier nicht: Für wen oder wofür etwas bestimmt ist, drückt `para` aus.',
        avoid: 'Lern `una mesa para dos` als festen Block fürs Restaurant.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.imperative-tu'],
      difficulty: 2,
      audio: 'Perdone, ¿cómo llego a la estación? – Siga recto y tome la segunda calle a la derecha. Está a cinco minutos a pie.',
      question: 'Wie kommt man zum Bahnhof?',
      options: [
        'geradeaus, dann die zweite Straße rechts – 5 Minuten zu Fuß',
        'geradeaus, dann die zweite Straße links – 5 Minuten zu Fuß',
        'geradeaus, dann die erste Straße rechts – 15 Minuten zu Fuß',
        'mit dem Bus bis zur zweiten Haltestelle, dann rechts',
      ],
      answer: 0,
      feedback: {
        rule: '`siga recto` = gehen Sie geradeaus; `tome la segunda calle a la derecha` = nehmen Sie die zweite Straße rechts; `a cinco minutos a pie` = fünf Minuten zu Fuß.',
        why: '`derecha` (rechts) und `izquierda` (links) sowie `segunda` (zweite) und `primera` (erste) sind die typischen Stolperfallen.',
        avoid: 'Eselsbrücke: dere**ch**a – re**ch**ts, beide mit „ch“.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.reflexive'],
      difficulty: 2,
      verb: 'levantarse',
      tense: 'Präsens',
      person: 'yo',
      sentence: 'Los domingos ___ a las diez.',
      answers: ['me levanto'],
      feedback: {
        rule: 'Reflexive Verben: Das Pronomen steht vor dem Verb – `me levanto`, `te levantas`, `se levanta` …',
        why: '„levanto“ allein hieße „ich hebe (etwas) hoch“. Ohne `me` fehlt der Bezug auf dich selbst.',
        avoid: 'yo → me, tú → te, él/ella → se: Pronomen und Person gehören immer zusammen.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.weather', 'es.g.ir-a'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Heute ist es kalt, aber morgen wird es sonnig.',
      answers: WEATHER_ANSWERS,
      feedback: {
        rule: 'Wetter mit `hacer`: `hace frío`, `hace sol`. Für morgen: `va a hacer sol` (ir a + Infinitiv) – oder einfach Präsens: `mañana hace sol`.',
        why: '„es frío“ oder „está frío“ beschreiben kein Wetter: Auf Spanisch „macht“ es Kälte und Sonne.',
        avoid: 'Denk wörtlich: „Heute macht es Kälte, morgen wird es Sonne machen.“',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: ['es.g.gustar'],
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'A mí me gustan mucho el chocolate.',
      answers: ['A mí me gusta mucho el chocolate.', 'Me gusta mucho el chocolate.'],
      german: 'Ich mag Schokolade sehr.',
      feedback: {
        rule: '`gustar` richtet sich nach der Sache, die gefällt: eine Sache → `gusta`, mehrere → `gustan`.',
        why: '`el chocolate` ist Singular → `me gusta`. `gustan` bräuchtest du z. B. bei `los chocolates`.',
        avoid: 'Frag: Was gefällt? Das ist das Subjekt – danach richtet sich das Verb.',
      },
    },
  ],
  pronunciation: ['es.p.link.un-cafe-con-leche', 'es.p.cz.gracias'],
  application: [
    {
      id: `${L}.a01`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: [...POL, 'es.g.stem-change'],
      difficulty: 2,
      scenarioId: 'es.sc.restaurant',
      goal: 'Bestell im Restaurant höflich: Bitte um einen Tisch (Quisiera …), bestelle Essen und ein Getränk, frag nach der Rechnung (¿Me trae la cuenta, por favor?) und bedank dich.',
      turns: 5,
      feedback: {
        rule: 'Höflich bestellen: `Quisiera …`, `¿Me trae …, por favor?`, `Para mí …` – und am Ende `Muchas gracias`.',
        why: 'Ein nacktes „Quiero …“ ohne `por favor` wirkt schnell fordernd.',
        avoid: 'Leg dir drei Sätze zurecht: Tisch, Bestellung, Rechnung.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: POL,
      difficulty: 2,
      prompt: 'Du bist in einer Sprachschule in Sevilla. Bitte die Lehrerin laut und höflich, langsamer zu sprechen und etwas zu wiederholen, und frag, ob du das Fenster öffnen darfst.',
      keywords: ['puede', 'puedo', 'por favor', 'repetir', 'más despacio', 'abrir', 'ventana', 'gracias'],
      minMatch: 4,
      sample: 'Perdone, ¿puede hablar más despacio, por favor? ¿Puede repetir? Muchas gracias. ¿Puedo abrir la ventana?',
      feedback: {
        rule: 'Bitten an eine Person, die du siezt: `¿Puede …?` + Infinitiv. Für dich selbst: `¿Puedo …?` (darf ich?).',
        why: '`¿Puedes …?` wäre die du-Form – in der Sprachschule gegenüber der Lehrerin ist beides möglich, aber bleib bei einer Form.',
        avoid: 'Sprich die Frage mit steigender Melodie am Ende – so klingt sie freundlich.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.tener', 'es.g.gustar', 'es.g.ir-a', 'es.g.reflexive'],
      difficulty: 3,
      prompt: 'Dein A1-Steckbrief: Schreib 5–6 Sätze über dich – Alter, Familie, was du gern machst, deinen Tagesablauf oder deine Wohnung und einen Plan fürs Wochenende.',
      requirements: [
        { pattern: '\\btengo\\b', hint: 'tener (Alter oder Familie)' },
        { pattern: '\\bme (gusta|gustan|encanta|encantan)\\b', hint: 'gustar oder encantar (me gusta …)' },
        { pattern: '\\bvoy a\\b', hint: 'einen Plan mit ir a + Infinitiv (voy a …)' },
        { pattern: '\\b(me levanto|me acuesto|me ducho|hay|vivo)\\b', hint: 'deinen Tagesablauf (me levanto …) oder deine Wohnung (vivo en … / hay …)' },
      ],
      samples: [
        'Me llamo Julia y tengo treinta y cuatro años. Tengo un hermano y una hermana. Vivo en un piso pequeño en Colonia: hay un salón, una cocina y un dormitorio. Me encanta bailar y me gusta mucho el cine. Los lunes me levanto a las seis. El sábado voy a cenar con mis amigos.',
      ],
      minWords: 30,
      feedback: {
        rule: 'Alter mit `tengo … años`, Vorlieben mit `me gusta`, Tagesablauf mit `me levanto`, Pläne mit `voy a` + Infinitiv.',
        why: 'Typische A1-Fehler: „soy … años“, „me gustan el cine“, „levanto“ ohne me und „voy cenar“ ohne a.',
        avoid: 'Geh deinen Text Satz für Satz durch und prüf jeweils nur das eine Verb.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.stem-change'],
      difficulty: 1,
      prompt: 'Restaurant-Wiederholung: `¿Tú ___ café o té?`',
      options: [
        { text: 'prefieres' },
        { text: 'preferes', why: 'preferir hat den Stammwechsel e→ie: prefiero, prefieres, prefiere, prefieren.' },
        { text: 'prefiere', why: '`prefiere` ist die Form für él / ella / usted – hier steht aber tú.' },
        { text: 'prefiero', why: '`prefiero` ist die yo-Form.' },
      ],
      answer: 0,
      feedback: {
        rule: '`preferir` (e→ie): prefiero, prefieres, prefiere, preferimos, (preferís), prefieren.',
        why: 'Das zweite e von preferir ist betont und wird deshalb zu ie. Nur bei nosotros/vosotros bleibt es.',
        avoid: 'Denk an querer: quiero – quieres. preferir funktioniert genauso.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.demonstratives'],
      difficulty: 2,
      prompt: 'Die Verkäuferin hält eine Jacke in der Hand und fragt: `¿Te gusta ___ chaqueta?`',
      options: [
        { text: 'esta' },
        { text: 'este', why: '`chaqueta` ist feminin → `esta`, nicht este.' },
        { text: 'esto', why: '`esto` ist neutral und steht allein, nie vor einem Nomen.' },
        { text: 'aquella', why: '`aquella` zeigt auf etwas weit Entferntes – die Jacke ist aber direkt bei ihr.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Nah bei der sprechenden Person: `este` / `esta`; etwas weiter weg: `ese` / `esa`; weit weg: `aquel` / `aquella`.',
        why: 'Der Begleiter richtet sich nach Geschlecht und Zahl des Nomens: `la chaqueta` → `esta chaqueta`.',
        avoid: 'Merke: este/esta = hier bei mir.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.time-dates'],
      difficulty: 2,
      audio: 'Mi cumpleaños es el veinte de octubre.',
      answers: ['Mi cumpleaños es el veinte de octubre.', 'Mi cumpleaños es el 20 de octubre.'],
      german: 'Mein Geburtstag ist am 20. Oktober.',
      feedback: {
        rule: 'Datum: `el` + Zahl + `de` + Monat. `cumpleaños` schreibt man zusammen, mit ñ.',
        why: 'Häufig wird „cumple años“ getrennt oder ohne ñ geschrieben. Und: Monatsnamen schreibt man im Spanischen klein – `octubre`.',
        avoid: 'Hör auf die Struktur: el … de … – dann fehlt kein Wort.',
      },
    },
  ],
};

export default lesson;
