import type { Lesson } from '../../types';

const L = 'es.a1.l12';
const W = ['es.g.weather'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c4',
  order: 12,
  title: 'Das Wetter',
  subtitle: 'Hace sol, está nublado, llueve – und Weihnachten im Sommer',
  icon: '⛅',
  minutes: 11,
  goal:
    'Du sprichst über das **Wetter**: `Hace sol.` `Está nublado.` `Llueve.` `Hay niebla.` Du verstehst, warum Spanisch dafür „machen“ (`hacer`) benutzt, unterscheidest `hace frío` (das Wetter) von `tengo frío` (mir ist kalt) und erfährst, warum man in Buenos Aires Weihnachten im Sommer feiert.',
  canDo: [
    'Ich kann das Wetter mit hace, está, hay, llueve und nieva beschreiben.',
    'Ich kann nach dem Wetter fragen: ¿Qué tiempo hace?',
    'Ich kann zwischen hace frío, tengo frío und está frío unterscheiden.',
    'Ich weiß, dass die Jahreszeiten auf der Südhalbkugel umgekehrt sind.',
  ],
  topicIds: W,
  vocab: [
    { id: `${L}.v.tiempo`, target: 'el tiempo', german: 'das Wetter; die Zeit', pos: 'noun', gender: 'm', emoji: '⛅', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'Hoy hace buen tiempo.', german: 'Heute ist schönes Wetter.' } },
    { id: `${L}.v.que-tiempo-hace`, target: '¿Qué tiempo hace?', german: 'Wie ist das Wetter?', pos: 'phrase', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: '¿Qué tiempo hace en Madrid?', german: 'Wie ist das Wetter in Madrid?' } },
    { id: `${L}.v.buen-tiempo`, target: 'hace buen tiempo / hace mal tiempo', german: 'es ist schönes / schlechtes Wetter', pos: 'phrase', emoji: '😎', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'En mayo hace buen tiempo.', german: 'Im Mai ist schönes Wetter.' } },
    { id: `${L}.v.sol`, target: 'el sol', german: 'die Sonne', pos: 'noun', gender: 'm', emoji: '☀️', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'Hoy hace sol.', german: 'Heute scheint die Sonne.' } },
    { id: `${L}.v.calor`, target: 'el calor', german: 'die Hitze, die Wärme', pos: 'noun', gender: 'm', emoji: '🥵', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'En agosto hace mucho calor.', german: 'Im August ist es sehr heiß.' } },
    { id: `${L}.v.frio`, target: 'el frío', german: 'die Kälte', pos: 'noun', gender: 'm', emoji: '🥶', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'En enero hace frío.', german: 'Im Januar ist es kalt.' } },
    { id: `${L}.v.viento`, target: 'el viento', german: 'der Wind', pos: 'noun', gender: 'm', emoji: '💨', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'Hace mucho viento en la playa.', german: 'Am Strand ist es sehr windig.' } },
    { id: `${L}.v.nublado`, target: 'nublado, nublada', german: 'bewölkt', pos: 'adj', emoji: '☁️', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'Hoy está nublado.', german: 'Heute ist es bewölkt.' } },
    { id: `${L}.v.llover`, target: 'llover (llueve)', german: 'regnen (es regnet)', pos: 'verb', emoji: '🌧️', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'En otoño llueve mucho.', german: 'Im Herbst regnet es viel.' } },
    { id: `${L}.v.lluvia`, target: 'la lluvia', german: 'der Regen', pos: 'noun', gender: 'f', emoji: '☔', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'No me gusta la lluvia.', german: 'Ich mag keinen Regen.' } },
    { id: `${L}.v.nevar`, target: 'nevar (nieva)', german: 'schneien (es schneit)', pos: 'verb', emoji: '❄️', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'En invierno nieva poco en Madrid.', german: 'Im Winter schneit es in Madrid wenig.' } },
    { id: `${L}.v.niebla`, target: 'la niebla', german: 'der Nebel', pos: 'noun', gender: 'f', emoji: '🌫️', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'Por la mañana hay niebla.', german: 'Morgens ist es neblig.' } },
    { id: `${L}.v.tormenta`, target: 'la tormenta', german: 'das Gewitter, der Sturm', pos: 'noun', gender: 'f', plural: 'las tormentas', emoji: '⛈️', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'Esta noche hay tormenta.', german: 'Heute Nacht gibt es ein Gewitter.' } },
    { id: `${L}.v.grado`, target: 'el grado', german: 'der Grad', pos: 'noun', gender: 'm', plural: 'los grados', emoji: '🌡️', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'Hoy hace treinta grados.', german: 'Heute sind es dreißig Grad.' } },
    { id: `${L}.v.estacion`, target: 'la estación (del año)', german: 'die Jahreszeit', pos: 'noun', gender: 'f', plural: 'las estaciones', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: '¿Cuál es tu estación favorita?', german: 'Was ist deine Lieblingsjahreszeit?' } },
    { id: `${L}.v.clima`, target: 'el clima', german: 'das Klima; (in Lateinamerika auch) das Wetter', pos: 'noun', gender: 'm', emoji: '🌍', field: 'Wetter', stageId: 'a1', lessonId: L, example: { target: 'El clima de Canarias es muy agradable.', german: 'Das Klima auf den Kanaren ist sehr angenehm.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Fürs Wetter hat Spanisch vier Muster – und keines davon braucht ein Subjekt wie das deutsche „es“:\n- `hace` + Nomen: `hace sol`, `hace calor`, `hace frío`, `hace viento`, `hace buen tiempo`\n- `está` + Adjektiv: `está nublado`, `está despejado` (klar)\n- `hay` + Nomen: `hay niebla`, `hay tormenta`\n- eigene Verben: `llueve` (es regnet), `nieva` (es schneit)\nGefragt wird mit `¿Qué tiempo hace?` – und `el tiempo` heißt sowohl „das Wetter“ als auch „die Zeit“.',
    },
    {
      type: 'table',
      title: 'Wetter auf einen Blick',
      headers: ['Muster', 'Spanisch', 'Deutsch'],
      rows: [
        ['hace + Nomen', 'hace sol / calor / frío / viento', 'die Sonne scheint / es ist heiß / kalt / windig'],
        ['hace + buen / mal tiempo', 'hace buen tiempo', 'es ist schönes Wetter'],
        ['está + Adjektiv', 'está nublado / despejado', 'es ist bewölkt / klar'],
        ['hay + Nomen', 'hay niebla / tormenta', 'es ist neblig / es gibt ein Gewitter'],
        ['eigenes Verb', 'llueve / nieva', 'es regnet / es schneit'],
      ],
    },
    {
      type: 'compare',
      target: 'Hace frío.',
      german: 'Es ist kalt.',
      md: 'Wörtlich: „Es macht Kälte.“ `frío`, `calor`, `sol` und `viento` sind hier **Nomen** – deshalb steht `hace` davor. Ein eigenes Wort für das deutsche „es“ gibt es nicht: nicht `Es hace frío`, sondern einfach `Hace frío.`',
    },
    {
      type: 'mistake',
      wrong: 'Hace muy calor.',
      right: 'Hace mucho calor.',
      why: 'Weil `calor` ein Nomen ist („Hitze“), brauchst du `mucho` (viel) – wörtlich „Es macht viel Hitze“. `muy` steht nur vor Adjektiven und Adverbien: `Está muy nublado.`',
    },
    {
      type: 'tip',
      md:
        'Drei Verben, drei Blickwinkel:\n- Das Wetter **macht**: `Hace frío.` (Es ist kalt.)\n- Ich **habe**: `Tengo frío.` (Mir ist kalt.)\n- Eine Sache **ist**: `El café está frío.` (Der Kaffee ist kalt.)\nFür „Mir ist kalt“ also nicht `Estoy frío`, sondern `Tengo frío` – genau wie beim Alter hilft dir **tener**.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'En julio', role: 'adverb' },
        { text: ' ' },
        { text: 'hace', role: 'verb' },
        { text: ' ' },
        { text: 'mucho', role: 'adjective' },
        { text: ' ' },
        { text: 'calor', role: 'noun' },
        { text: ' ' },
        { text: 'en Sevilla', role: 'adverb' },
        { text: '.' },
      ],
      german: 'Im Juli ist es in Sevilla sehr heiß.',
    },
    {
      type: 'text',
      md:
        '**Jahreszeiten auf der Südhalbkugel:** In Argentinien, Chile, Uruguay und Paraguay ist alles umgekehrt. Der Sommer (`el verano`) dauert dort von Dezember bis Februar, der Winter (`el invierno`) von Juni bis August. Weihnachten feiert man also im Sommer – oft draußen und mit Grillen. `En Buenos Aires, en diciembre hace calor.`\nIn Ländern nahe am Äquator wie Kolumbien, Ecuador oder Venezuela gibt es kaum Jahreszeiten; man unterscheidet eher Regenzeit und Trockenzeit. Dort hängt das Wetter vor allem von der Höhe ab: In Bogotá ist es das ganze Jahr kühl, an der Küste heiß.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In vielen Ländern Lateinamerikas fragt man nach dem Wetter auch mit `clima`: `¿Cómo está el clima hoy?` In Spanien bedeutet `el clima` dagegen vor allem „das Klima“ auf lange Sicht, und man fragt `¿Qué tiempo hace?` – das versteht man aber auch in ganz Lateinamerika.',
    },
  ],
  examples: [
    {
      target: '¿Qué tiempo hace hoy?',
      german: 'Wie ist das Wetter heute?',
      parts: [
        { text: '¿Qué tiempo', role: 'question' },
        { text: ' ' },
        { text: 'hace', role: 'verb' },
        { text: ' ' },
        { text: 'hoy', role: 'adverb' },
        { text: '?' },
      ],
    },
    {
      target: 'Hoy hace sol y mucho calor.',
      german: 'Heute scheint die Sonne und es ist sehr heiß.',
      parts: [
        { text: 'Hoy', role: 'adverb' },
        { text: ' ' },
        { text: 'hace', role: 'verb' },
        { text: ' ' },
        { text: 'sol', role: 'noun' },
        { text: ' y ' },
        { text: 'mucho', role: 'adjective' },
        { text: ' ' },
        { text: 'calor', role: 'noun' },
        { text: '.' },
      ],
    },
    {
      target: 'Está nublado, pero no llueve.',
      german: 'Es ist bewölkt, aber es regnet nicht.',
      parts: [
        { text: 'Está', role: 'verb' },
        { text: ' ' },
        { text: 'nublado', role: 'adjective' },
        { text: ', pero ' },
        { text: 'no', role: 'negation' },
        { text: ' ' },
        { text: 'llueve', role: 'verb' },
        { text: '.' },
      ],
    },
    { target: 'En invierno nieva poco en Madrid.', german: 'Im Winter schneit es in Madrid wenig.' },
    { target: 'Tengo mucho calor.', german: 'Mir ist sehr heiß.', note: 'Wie fühlt sich eine Person? → `tener`: `tengo calor`, `tengo frío`.' },
    { target: 'Hoy hace treinta grados.', german: 'Heute sind es dreißig Grad.' },
    { target: 'En Buenos Aires, en diciembre hace calor.', german: 'In Buenos Aires ist es im Dezember heiß.', note: 'Südhalbkugel: Dezember ist Sommer.' },
    { target: '¿Cómo está el clima hoy?', german: 'Wie ist das Wetter heute?', variant: 'es-LA' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: W,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu.',
      pairs: [
        { emoji: '☀️', word: 'el sol' },
        { emoji: '☔', word: 'la lluvia' },
        { emoji: '💨', word: 'el viento' },
        { emoji: '🌫️', word: 'la niebla' },
        { emoji: '⛈️', word: 'la tormenta' },
      ],
      feedback: {
        rule: 'el sol (Sonne), la lluvia (Regen), el viento (Wind), la niebla (Nebel), la tormenta (Gewitter).',
        why: '`niebla` und `nieva` (es schneit) klingen ähnlich, bedeuten aber etwas ganz anderes.',
        avoid: 'Lerne die Wörter mit ihrem Muster: hace sol, hace viento, hay niebla, hay tormenta.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: W,
      difficulty: 1,
      prompt: 'Welches Verb passt? `Hoy ___ mucho viento.`',
      options: [
        { text: 'hace' },
        { text: 'es', why: '`ser` beschreibt kein Wetter. `Es mucho viento` klingt wie eine Übersetzung von „Es ist windig“.' },
        { text: 'está', why: '`está` steht beim Wetter nur vor Adjektiven (`está nublado`), `viento` ist ein Nomen.' },
        { text: 'tiene', why: '`tener` benutzt du für Personen (`tengo frío`), nicht fürs Wetter.' },
      ],
      answer: 0,
      feedback: {
        rule: '`hace` + Nomen: `hace viento`, `hace sol`, `hace calor`.',
        why: 'Das deutsche „es ist“ verleitet zu `es` oder `está`. Im Spanischen „macht“ das Wetter den Wind.',
        avoid: 'Merke: Wetter-Nomen (sol, calor, frío, viento) → immer mit `hace`.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: W,
      difficulty: 1,
      instruction: 'Ordne jedem deutschen Satz die spanische Entsprechung zu.',
      pairs: [
        { left: 'Es regnet.', right: 'Llueve.' },
        { left: 'Es schneit.', right: 'Nieva.' },
        { left: 'Es ist bewölkt.', right: 'Está nublado.' },
        { left: 'Es ist windig.', right: 'Hace viento.' },
        { left: 'Es ist neblig.', right: 'Hay niebla.' },
      ],
      feedback: {
        rule: 'Jedes Wetter hat sein Muster: `llueve`, `nieva`, `está nublado`, `hace viento`, `hay niebla`.',
        why: 'Im Deutschen beginnt fast alles mit „es“ – im Spanischen entscheidet das Wort, welches Verb davor steht.',
        avoid: 'Lerne jede Wetterangabe als festen Block, nicht Wort für Wort.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: W,
      difficulty: 2,
      instruction: 'Ergänze die Wetterangaben.',
      sentence: 'En verano ___ mucho calor, pero en invierno ___ y ___ frío.',
      answers: [['hace'], ['llueve'], ['hace']],
      bank: ['hace', 'llueve', 'está', 'es'],
      german: 'Im Sommer ist es sehr heiß, aber im Winter regnet es und es ist kalt.',
      feedback: {
        rule: '`hace` + Nomen (`calor`, `frío`); Regen hat ein eigenes Verb: `llueve`.',
        why: '`está` und `es` passen nicht vor die Nomen `calor` und `frío`.',
        avoid: 'Frag dich: Folgt ein Nomen? → hace. Regnet oder schneit es? → llueve / nieva.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: W,
      difficulty: 2,
      audio: 'Hoy está nublado y hace frío, pero no llueve.',
      question: 'Wie ist das Wetter heute?',
      options: [
        'bewölkt und kalt, aber es regnet nicht',
        'sonnig und kalt',
        'bewölkt, kalt und es regnet',
        'bewölkt und heiß, aber es regnet nicht',
      ],
      answer: 0,
      feedback: {
        rule: '`está nublado` = bewölkt, `hace frío` = kalt, `no llueve` = es regnet nicht.',
        why: 'Das kleine `no` vor `llueve` geht beim Hören leicht unter – und `frío` ist kalt, nicht heiß (`calor`).',
        avoid: 'Hör besonders auf `no` vor dem Verb: Es dreht die ganze Aussage um.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: W,
      difficulty: 2,
      instruction: 'Bilde die Frage „Wie ist das Wetter in Madrid?“.',
      tokens: ['¿Qué', 'tiempo', 'hace', 'en', 'Madrid?'],
      extra: ['es'],
      german: 'Wie ist das Wetter in Madrid?',
      feedback: {
        rule: 'Die Wetterfrage lautet `¿Qué tiempo hace …?` – wörtlich „Welches Wetter macht es?“',
        why: '`es` passt nicht: Nach dem Wetter fragt man mit `hacer`, nicht mit `ser`.',
        avoid: 'Lerne die Frage als Block: `¿Qué tiempo hace?` – dahinter der Ort.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.weather', 'es.g.tener'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Mir ist kalt, aber heute scheint die Sonne.',
      answers: [
        'Tengo frío, pero hoy hace sol.',
        'Yo tengo frío, pero hoy hace sol.',
        'Tengo frío, pero hace sol hoy.',
        'Yo tengo frío, pero hace sol hoy.',
        'Tengo frío, pero hoy hay sol.',
        'Yo tengo frío, pero hoy hay sol.',
      ],
      feedback: {
        rule: 'Person friert → `tengo frío`; Wetter → `hace sol`.',
        why: '„Mir ist kalt“ verleitet zu `estoy frío` oder `me es frío` – beides ist falsch. Das Gefühl drückst du mit tener aus.',
        avoid: 'Frag dich: Geht es um mich (tener) oder um das Wetter (hacer)?',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: W,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'Hoy hace muy calor.',
      answers: ['Hoy hace mucho calor.', 'Hace mucho calor hoy.'],
      german: 'Heute ist es sehr heiß.',
      feedback: {
        rule: 'Vor dem Nomen `calor` steht `mucho`, nicht `muy`: `hace mucho calor`.',
        why: 'Das deutsche „sehr heiß“ führt zu `muy`. Aber `calor` ist kein Adjektiv, sondern ein Nomen (Hitze).',
        avoid: 'muy + Adjektiv (`muy nublado`), mucho + Nomen (`mucho calor`, `mucho viento`).',
      },
    },
  ],
  pronunciation: ['es.p.ll.playa', 'es.p.h.hola', 'es.p.link.vamos-a-la-playa'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: W,
      difficulty: 2,
      scenario: 'Deine Freundin aus Buenos Aires ruft im Januar an und fragt: `¿Qué tiempo hace en Alemania?` Bei dir ist es sehr kalt und es schneit. Was antwortest du?',
      options: [
        { text: 'Hace mucho frío y nieva.' },
        { text: 'Es mucho frío y nieva.', why: 'Wetter-Nomen wie `frío` stehen mit `hace`, nicht mit `es`.' },
        { text: 'Está mucho frío y nieva.', why: '`está` + `mucho` + Nomen gibt es beim Wetter nicht – richtig ist `hace mucho frío`.' },
        { text: 'Hace mucho frío y es nieve.', why: '„Es schneit“ heißt einfach `nieva`.' },
      ],
      answer: 0,
      feedback: {
        rule: '`hace mucho frío` (Nomen + mucho), `nieva` (eigenes Verb).',
        why: 'Die falschen Antworten übertragen das deutsche „es ist …“ Wort für Wort.',
        avoid: 'Und denk dran: In Buenos Aires ist im Januar Hochsommer – deine Freundin schwitzt gerade!',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: W,
      difficulty: 2,
      prompt: 'Beschreib in 3–4 Sätzen das Wetter heute bei dir und das Wetter in deiner Lieblingsjahreszeit.',
      requirements: [
        { pattern: '\\bhace\\b', hint: 'eine Wetterangabe mit „hace“ (hace sol, hace frío …)' },
        { pattern: '(est[aá] nublado|\\bllueve\\b|\\bnieva\\b|\\bhay (niebla|tormenta)\\b)', hint: 'eine zweite Wetterangabe (está nublado, llueve, nieva oder hay …)' },
        { pattern: '(primavera|verano|oto[nñ]o|invierno)', hint: 'eine Jahreszeit' },
      ],
      samples: [
        'Hoy está nublado y hace frío, pero no llueve. En verano hace sol y mucho calor. Me gusta mucho el verano.',
      ],
      minWords: 15,
      feedback: {
        rule: '`hace` + Nomen, `está` + Adjektiv, `hay` + Nomen, `llueve` / `nieva` ohne weiteres Verb.',
        why: 'Typische Fehler: `hace muy calor`, `es frío` oder `hace nublado` statt `está nublado`.',
        avoid: 'Lies jeden Wettersatz noch einmal: Nomen → hace/hay, Adjektiv → está.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: W,
      difficulty: 2,
      prompt: 'Du telefonierst mit einer Freundin in Buenos Aires. Sag laut, wie das Wetter heute bei dir ist (2–3 Sätze).',
      keywords: ['hace', 'sol', 'calor', 'frío', 'viento', 'buen', 'mal', 'tiempo', 'nublado', 'llueve', 'nieva', 'niebla', 'grados'],
      minMatch: 3,
      sample: 'Hoy hace sol, pero hace viento. No llueve.',
      feedback: {
        rule: 'Wetter beschreiben: `Hoy hace …`, `Está nublado.`, `Llueve.`',
        why: 'Wenn zu wenig erkannt wird, fehlt meist `hace` – oder das h wurde hörbar ausgesprochen.',
        avoid: 'Das h in `hace` ist stumm: „A-se“ (in Spanien mit gelispeltem c wie im englischen „think“). Und das ll in `llueve` klingt meist wie das j in „ja“.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: W,
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Plaudere übers Wetter: Frag dein Gegenüber, wie das Wetter heute bei ihm ist, beschreib dein Wetter und sag, welche Jahreszeit du am liebsten magst.',
      turns: 4,
      feedback: {
        rule: 'Frage: `¿Qué tiempo hace?` – Antwort: `Hace …`, `Está nublado`, `Llueve`. Gefühl: `Tengo frío / calor`.',
        why: 'Im freien Gespräch rutscht leicht `es frío` oder `hace muy calor` heraus.',
        avoid: 'Leg dir zwei Sätze zurecht: einen mit `hace` und einen mit `está` oder `llueve`.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.time-dates'],
      difficulty: 1,
      prompt: 'Wiederholung Wochentage: Wie sagst du „**montags**“ (jede Woche)?',
      options: [
        { text: 'los lunes' },
        { text: 'el lunes', why: '`el lunes` heißt „am Montag“ – einmalig.' },
        { text: 'en lunes', why: 'Vor Wochentagen steht keine Präposition.' },
        { text: 'los luneses', why: '`lunes` bleibt im Plural unverändert.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Gewohnheit: `los` + Wochentag. `lunes` bis `viernes` sind im Plural unverändert.',
        why: 'Nur `sábado` und `domingo` bekommen im Plural ein -s.',
        avoid: 'einmal → el lunes; jede Woche → los lunes.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.demonstratives'],
      difficulty: 2,
      instruction: 'Wiederholung este/aquel: Setze die passenden Formen ein.',
      sentence: 'Quiero ___ pantalones y ___ camiseta.',
      answers: [['estos'], ['aquella']],
      bank: ['estos', 'estas', 'aquella', 'aquel'],
      german: 'Ich möchte diese Hose hier und das T-Shirt dort drüben.',
      feedback: {
        rule: 'hier → `este/esta/estos/estas`; dort drüben → `aquel/aquella/aquellos/aquellas`.',
        why: '`los pantalones` ist maskulin Plural (`estos`), `la camiseta` feminin Singular (`aquella`).',
        avoid: 'Erst die Entfernung, dann Genus und Zahl des spanischen Nomens prüfen.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.stem-change'],
      difficulty: 2,
      verb: 'preferir',
      tense: 'Präsens',
      person: 'tú',
      sentence: '¿Tú ___ el verano o el invierno?',
      answers: ['prefieres'],
      feedback: {
        rule: '`preferir` (e → ie): prefiero, prefieres, prefiere, preferimos, preferís, prefieren.',
        why: '„preferes“ vergisst den Stammwechsel. Er gilt in allen stammbetonten Formen (pre-FIE-res).',
        avoid: 'Das zweite e im Stamm wird betont – und genau dieses wird zu ie.',
      },
    },
  ],
};

export default lesson;
