import type { Lesson } from '../../types';

const L = 'es.a1.l13';
const YO = ['es.g.yo-irregular'];
const STEM = ['es.g.stem-change'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c4',
  order: 13,
  title: 'Sich verabreden',
  subtitle: 'Vorschläge machen, zusagen und höflich absagen',
  icon: '🤝',
  minutes: 13,
  goal:
    'Du lernst, dich mit Freunden zu verabreden: Vorschläge machen (`¿Por qué no vamos al cine?`, `¿Nos vemos el sábado?`), zusagen und höflich absagen (`Lo siento, no puedo.`). Dazu kommen **poder** (können, o→ue) und sechs Verben mit unregelmäßiger yo-Form: `hago`, `salgo`, `pongo`, `vengo`, `sé`, `conozco`.',
  canDo: [
    'Ich kann jemanden einladen und Vorschläge für eine Verabredung machen.',
    'Ich kann zusagen, höflich absagen und einen anderen Termin vorschlagen.',
    'Ich kann poder im Präsens verwenden: ¿Puedes el viernes? – No, no puedo.',
    'Ich kann die yo-Formen hago, salgo, pongo, vengo, sé und conozco bilden.',
  ],
  topicIds: ['es.g.yo-irregular', 'es.g.stem-change'],
  vocab: [
    { id: `${L}.v.quedar`, target: 'quedar', german: 'sich verabreden, sich treffen', pos: 'verb', variant: 'es-ES', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿Quedamos a las ocho?', german: 'Treffen wir uns um acht?' } },
    { id: `${L}.v.nos-vemos`, target: 'nos vemos', german: 'wir sehen uns', pos: 'phrase', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿Nos vemos mañana?', german: 'Sehen wir uns morgen?' } },
    { id: `${L}.v.poder`, target: 'poder', german: 'können (Zeit haben, dürfen, möglich sein)', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'El lunes no puedo.', german: 'Am Montag kann ich nicht.' } },
    { id: `${L}.v.hacer`, target: 'hacer', german: 'machen, tun', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: '¿Qué haces el sábado?', german: 'Was machst du am Samstag?' } },
    { id: `${L}.v.salir`, target: 'salir', german: 'ausgehen, weggehen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Los viernes salgo con mis amigos.', german: 'Freitags gehe ich mit meinen Freunden aus.' } },
    { id: `${L}.v.poner`, target: 'poner', german: 'legen, stellen; (Musik) anmachen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Pongo música.', german: 'Ich mache Musik an.' } },
    { id: `${L}.v.saber`, target: 'saber', german: 'wissen; können (gelernt)', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'No sé dónde está.', german: 'Ich weiß nicht, wo es ist.' } },
    { id: `${L}.v.conocer`, target: 'conocer', german: 'kennen; kennenlernen', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Conozco un bar muy bueno.', german: 'Ich kenne eine sehr gute Bar.' } },
    { id: `${L}.v.cine`, target: 'el cine', german: 'das Kino', pos: 'noun', gender: 'm', plural: 'los cines', emoji: '🎬', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿Vamos al cine?', german: 'Gehen wir ins Kino?' } },
    { id: `${L}.v.fiesta`, target: 'la fiesta', german: 'die Party, das Fest', pos: 'noun', gender: 'f', plural: 'las fiestas', emoji: '🎉', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: 'El sábado hay una fiesta en mi casa.', german: 'Am Samstag gibt es eine Party bei mir.' } },
    { id: `${L}.v.tener-ganas`, target: 'tener ganas de', german: 'Lust haben auf / zu', pos: 'phrase', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿Tienes ganas de tomar un café?', german: 'Hast du Lust auf einen Kaffee?' } },
    { id: `${L}.v.te-apetece`, target: '¿Te apetece …?', german: 'Hast du Lust auf / zu …?', pos: 'phrase', variant: 'es-ES', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿Te apetece tomar algo?', german: 'Hast du Lust, etwas trinken zu gehen?' } },
    { id: `${L}.v.vale`, target: '¡Vale!', german: 'Okay! Einverstanden!', pos: 'phrase', variant: 'es-ES', field: 'Freizeit', stageId: 'a1', lessonId: L, example: { target: '¿A las ocho? – ¡Vale!', german: 'Um acht? – Okay!' } },
    { id: `${L}.v.lo-siento`, target: 'lo siento', german: 'es tut mir leid', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: 'Lo siento, no puedo.', german: 'Tut mir leid, ich kann nicht.' } },
    { id: `${L}.v.es-que`, target: 'es que …', german: '… nämlich / weißt du, …', pos: 'phrase', field: 'Höflichkeit', stageId: 'a1', lessonId: L, example: { target: 'Es que tengo que trabajar.', german: 'Ich muss nämlich arbeiten.' } },
    { id: `${L}.v.tener-que`, target: 'tener que + Infinitiv', german: 'müssen', pos: 'phrase', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Tengo que estudiar.', german: 'Ich muss lernen.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Eine Verabredung läuft auf Spanisch meist in drei Schritten:\n- **Vorschlag:** `¿Por qué no vamos al cine?`, `¿Nos vemos el sábado?`, `¿Te gustaría …?`, `¿Tienes ganas de …?` – in Spanien auch `¿Quedamos?` und `¿Te apetece …?`\n- **Zusagen:** `¡Claro!`, `¡Perfecto!`, `¡De acuerdo!` – in Spanien sehr oft `¡Vale!`\n- **Höflich absagen:** `Lo siento, no puedo. Es que tengo que trabajar. ¿Qué tal otro día?`\n`¿Te gustaría …?` („Hättest du Lust …?“) lernst du als festen Block – danach folgt einfach der Infinitiv. Genauso `tener que` + Infinitiv = müssen: `Tengo que trabajar.`',
    },
    {
      type: 'conjugation',
      verb: 'poder',
      translation: 'können',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'puedo', ending: 'o' },
        { person: 'tú', form: 'puedes', ending: 'es' },
        { person: 'él / ella / usted', form: 'puede', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'podemos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'podéis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'pueden', ending: 'en' },
      ],
    },
    {
      type: 'table',
      title: 'Verben mit unregelmäßiger yo-Form',
      headers: ['Infinitiv', 'yo', 'tú', 'Deutsch'],
      rows: [
        ['hacer', 'hago', 'haces', 'machen, tun'],
        ['salir', 'salgo', 'sales', 'ausgehen, weggehen'],
        ['poner', 'pongo', 'pones', 'legen, stellen; anmachen'],
        ['venir', 'vengo', 'vienes', 'kommen'],
        ['saber', 'sé', 'sabes', 'wissen; können (gelernt)'],
        ['conocer', 'conozco', 'conoces', 'kennen; kennenlernen'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: '¿Por qué no', role: 'question' },
        { text: ' ' },
        { text: 'vamos', role: 'verb' },
        { text: ' ' },
        { text: 'al', role: 'preposition' },
        { text: ' ' },
        { text: 'cine', role: 'noun' },
        { text: ' ' },
        { text: 'el sábado', role: 'adverb' },
        { text: '?' },
      ],
      german: 'Warum gehen wir nicht am Samstag ins Kino?',
    },
    {
      type: 'compare',
      target: 'Sé dónde vive Marta, pero no conozco a su hermano.',
      german: 'Ich weiß, wo Marta wohnt, aber ihren Bruder kenne ich nicht.',
      md:
        'Wie im Deutschen: **saber** = wissen (Fakten, Informationen), **conocer** = kennen (Personen, Orte, Lokale). Vor Personen steht nach conocer ein kleines `a`: `conozco a Marta`.\n`saber` + Infinitiv heißt außerdem „etwas können, weil man es gelernt hat“: `Sé bailar salsa.` **poder** bedeutet dagegen „können“ im Sinne von Zeit haben, dürfen oder möglich sein: `Hoy no puedo.`',
    },
    {
      type: 'mistake',
      wrong: 'No podo venir el sábado.',
      right: 'No puedo venir el sábado.',
      why:
        '`poder` ist ein o→ue-Verb (wie `probarse`): In allen stammbetonten Formen wird aus o ein ue – `puedo`, `puedes`, `puede`, `pueden`. Nur `podemos` (und `podéis`) behalten das o, weil dort die Endung betont wird.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md:
        '`quedar` (sich verabreden), `¿Te apetece …?` und `¡Vale!` sind typisch für **Spanien**. In Lateinamerika fragt man eher `¿Nos vemos …?`, `¿Te gustaría …?` oder `¿Tienes ganas de …?` und sagt zu mit `¡Claro!`, `¡Perfecto!`, `¡Dale!` (z. B. Argentinien, Kolumbien) oder `¡Sale!` (Mexiko).',
    },
    {
      type: 'tip',
      md:
        'Merksatz: **Nur das „ich“ tanzt aus der Reihe.** Bei hacer, salir, poner, saber und conocer ist nur die yo-Form unregelmäßig – `hago`, aber ganz regelmäßig `haces`, `hace`, `hacemos` …\n`venir` ist ein Sonderfall wie `tener`: `vengo`, aber `vienes`, `viene`, `vienen`.',
    },
  ],
  examples: [
    {
      target: '¿Quedamos el viernes por la tarde?',
      german: 'Treffen wir uns am Freitagnachmittag?',
      variant: 'es-ES',
      parts: [
        { text: '¿Quedamos', role: 'verb' },
        { text: ' ' },
        { text: 'el viernes por la tarde', role: 'adverb' },
        { text: '?' },
      ],
    },
    {
      target: '¿Nos vemos mañana a las siete?',
      german: 'Sehen wir uns morgen um sieben?',
      note: 'Funktioniert überall – in Spanien wie in Lateinamerika.',
    },
    {
      target: '¿Te gustaría ir al concierto conmigo?',
      german: 'Hättest du Lust, mit mir ins Konzert zu gehen?',
      literal: 'Würde es dir gefallen, mit mir zum Konzert zu gehen?',
      note: '`conmigo` = mit mir (ein Wort!), `contigo` = mit dir.',
    },
    {
      target: 'Lo siento, no puedo. Es que tengo que trabajar.',
      german: 'Tut mir leid, ich kann nicht. Ich muss nämlich arbeiten.',
      parts: [
        { text: 'Lo siento', role: 'other' },
        { text: ', ' },
        { text: 'no', role: 'negation' },
        { text: ' ' },
        { text: 'puedo', role: 'verb' },
        { text: '. ' },
        { text: 'Es que', role: 'other' },
        { text: ' ' },
        { text: 'tengo que trabajar', role: 'verb' },
        { text: '.' },
      ],
      note: '`Es que …` leitet eine Begründung ein – so klingt eine Absage weich und freundlich.',
    },
    {
      target: '¿Qué haces el sábado? – Salgo con unos amigos.',
      german: 'Was machst du am Samstag? – Ich gehe mit ein paar Freunden aus.',
    },
    {
      target: 'Conozco un bar muy bueno en el centro.',
      german: 'Ich kenne eine sehr gute Bar im Zentrum.',
      parts: [
        { text: 'Conozco', role: 'verb' },
        { text: ' ' },
        { text: 'un bar muy bueno', role: 'object' },
        { text: ' ' },
        { text: 'en el centro', role: 'adverb' },
        { text: '.' },
      ],
      note: '`el bar` ist im Spanischen maskulin.',
    },
    {
      target: '¿Te apetece tomar algo?',
      german: 'Hast du Lust, etwas trinken zu gehen?',
      variant: 'es-ES',
      note: '`tomar algo` = etwas trinken (oder eine Kleinigkeit essen) gehen – die typische spanische Verabredung.',
    },
    {
      target: '¿Tienes ganas de ir a la playa?',
      german: 'Hast du Lust, an den Strand zu gehen?',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: YO,
      difficulty: 1,
      instruction: 'Ordne jedem Infinitiv die passende yo-Form zu.',
      pairs: [
        { left: 'hacer', right: 'hago' },
        { left: 'salir', right: 'salgo' },
        { left: 'poner', right: 'pongo' },
        { left: 'venir', right: 'vengo' },
        { left: 'saber', right: 'sé' },
        { left: 'conocer', right: 'conozco' },
      ],
      feedback: {
        rule: '`hacer → hago`, `salir → salgo`, `poner → pongo`, `venir → vengo`, `saber → sé`, `conocer → conozco`.',
        why: 'Wer das Muster der regelmäßigen Verben anwendet, bildet „haco“, „salo“ oder „sabo“ – diese Formen gibt es nicht.',
        avoid: 'Lern die Gruppe wie einen Reim: hago – salgo – pongo – vengo (alle auf -go), dazu sé und conozco.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: YO,
      difficulty: 1,
      instruction: 'Hör genau hin: Welches Wort wird gesprochen?',
      options: ['vengo', 'vendo'],
      answer: 0,
      hint: '`vengo` (ich komme): Nach dem n folgt ein g wie in „Tango“. `vendo` (ich verkaufe): Nach dem n folgt ein weiches d. Das v sprichst du in beiden Wörtern wie ein weiches b.',
      feedback: {
        rule: '`vengo` = ich komme (venir), `vendo` = ich verkaufe (vender). Der Unterschied liegt nur im Laut nach dem n.',
        why: 'Im schnellen Sprechen verschwimmen -ngo und -ndo leicht. Wer sie verwechselt, sagt „ich verkaufe“ statt „ich komme“.',
        avoid: 'Sprich beide Wörter langsam nach: VEN-go (Zunge hinten, wie bei „Tango“) – VEN-do (Zungenspitze vorne an den Zähnen).',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: [...YO, ...STEM],
      difficulty: 2,
      instruction: 'Setze zuerst eine Form von „salir“, dann eine Form von „poder“ ein.',
      sentence: 'El sábado ___ con mis amigos, pero el domingo no ___: tengo que trabajar.',
      answers: [['salgo'], ['puedo']],
      bank: ['salgo', 'puedo', 'salo', 'podo'],
      german: 'Am Samstag gehe ich mit meinen Freunden aus, aber am Sonntag kann ich nicht: Ich muss arbeiten.',
      feedback: {
        rule: 'yo-Formen: `salir → salgo` (unregelmäßiges -go), `poder → puedo` (o→ue).',
        why: '„salo“ und „podo“ entstehen, wenn man die Regeln für regelmäßige Verben anwendet – beide Formen gibt es nicht.',
        avoid: 'Bei salir hilft die -go-Gruppe (hago, salgo, pongo, vengo), bei poder das Stammwechsel-Muster: pUEdo, pUEdes, pUEde – aber podemos.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'listening',
      skills: ['listening'],
      topicIds: [...STEM, 'es.g.time-dates'],
      difficulty: 2,
      audio: 'Lo siento, el jueves no puedo. Es que tengo que trabajar. ¿Qué tal el viernes a las ocho?',
      question: 'Was schlägt die Person vor?',
      options: ['Freitag um 8 Uhr', 'Donnerstag um 8 Uhr', 'Freitag um 7 Uhr', 'Dienstag um 8 Uhr'],
      answer: 0,
      feedback: {
        rule: '`el jueves no puedo` = am Donnerstag kann ich nicht; `¿Qué tal el viernes a las ocho?` = Wie wäre es mit Freitag um acht?',
        why: 'Der Donnerstag wird zwar genannt, aber abgesagt – der neue Vorschlag kommt erst mit `¿Qué tal …?`. Außerdem klingen `jueves` und `martes` am Ende gleich.',
        avoid: 'Achte auf Signalwörter: `no puedo` = Absage, `¿Qué tal …?` = neuer Vorschlag.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'order',
      skills: ['grammar'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      instruction: 'Bilde den Vorschlag „Warum gehen wir nicht am Samstag ins Kino?“.',
      tokens: ['¿Por', 'qué', 'no', 'vamos', 'al', 'cine', 'el', 'sábado', '?'],
      extra: ['porque'],
      alternatives: [['¿Por', 'qué', 'no', 'vamos', 'el', 'sábado', 'al', 'cine', '?']],
      german: 'Warum gehen wir nicht am Samstag ins Kino?',
      feedback: {
        rule: 'Vorschlag mit `¿Por qué no …?` + Verb in der wir-Form: `¿Por qué no vamos …?` – wörtlich „Warum gehen wir nicht …?“',
        why: '`porque` (zusammen, ohne Akzent) heißt „weil“ und gehört in die Antwort. In der Frage schreibt man `por qué` – getrennt und mit Akzent.',
        avoid: 'Frage = zwei Wörter mit Akzent (`¿por qué?`), Antwort = ein Wort (`porque`).',
      },
    },
    {
      id: `${L}.g06`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: [...STEM, ...YO],
      difficulty: 2,
      scenario: 'Deine Kollegin Sofía fragt: `¿Te gustaría ir al cine el viernes?` Am Freitag hast du keine Zeit, am Samstag aber schon. Was antwortest du?',
      options: [
        { text: 'Lo siento, el viernes no puedo. ¿Qué tal el sábado?' },
        { text: 'Lo siento, el viernes no podo. ¿Qué tal el sábado?', why: '`podo` gibt es nicht – poder hat den Stammwechsel o→ue: `puedo`.' },
        { text: 'Lo siento, el viernes no sé. ¿Qué tal el sábado?', why: '`no sé` heißt „ich weiß nicht“. Für „ich kann nicht (keine Zeit)“ brauchst du `no puedo`.' },
        { text: '¡Claro! El viernes puedo.', why: 'Grammatisch richtig, aber inhaltlich falsch: Am Freitag hast du ja keine Zeit.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Höflich absagen: `Lo siento, … no puedo.` + Gegenvorschlag mit `¿Qué tal …?`',
        why: 'saber (wissen, gelernt können) und poder (können = Zeit haben, möglich sein) sind nicht austauschbar.',
        avoid: 'Bei Terminen immer `poder`: `¿Puedes?` – `Sí, puedo.` / `No, no puedo.`',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: STEM,
      difficulty: 3,
      direction: 'toTarget',
      source: 'Tut mir leid, am Montag kann ich nicht.',
      answers: [
        'Lo siento, el lunes no puedo.',
        'Lo siento, no puedo el lunes.',
        'Lo siento, el lunes yo no puedo.',
        'Lo siento, yo no puedo el lunes.',
      ],
      feedback: {
        rule: 'Absage: `Lo siento` + `no puedo`. Wochentage stehen mit Artikel und ohne Präposition: `el lunes` = am Montag.',
        why: 'Typische Fehler sind „en lunes“ (wörtlich „am“) und „no podo“. Auf Spanisch reicht der Artikel: `el lunes`.',
        avoid: '„am Montag“ = `el lunes`, „montags“ = `los lunes`.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: YO,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'No conoco este restaurante, pero sé dónde está.',
      answers: [
        'No conozco este restaurante, pero sé dónde está.',
        'Yo no conozco este restaurante, pero sé dónde está.',
      ],
      german: 'Ich kenne dieses Restaurant nicht, aber ich weiß, wo es ist.',
      feedback: {
        rule: '`conocer → conozco`: In der yo-Form kommt ein z vor das c.',
        why: '„conoco“ folgt dem regelmäßigen Muster – conocer gehört aber zu den Verben auf -cer, deren yo-Form auf -zco endet. `sé` ist dagegen richtig (saber → sé).',
        avoid: 'Merke dir `conozco` als Klangbild: co-NOZ-co. Der Rest ist regelmäßig: conoces, conoce, conocemos …',
      },
    },
  ],
  pronunciation: ['es.p.link.vamos-a-la-playa', 'es.p.link.que-hora-es'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: [...YO, ...STEM],
      difficulty: 2,
      prompt: 'Schreib einer Freundin eine kurze Nachricht (3–4 Sätze): Schlag etwas fürs Wochenende vor, nenne Tag, Uhrzeit und Treffpunkt und frag, ob sie kann.',
      requirements: [
        { pattern: '(quedamos|nos vemos|por qu[eé] no|te gustar[ií]a|te apetece|tienes ganas)', hint: 'einen Vorschlag (z. B. ¿Por qué no …?, ¿Te gustaría …?, ¿Nos vemos …?)' },
        { pattern: '(lunes|martes|mi[eé]rcoles|jueves|viernes|s[aá]bado|domingo|fin de semana|ma[nñ]ana)', hint: 'einen Tag (el sábado, mañana …)' },
        { pattern: '\\ba las? (una|dos|tres|cuatro|cinco|seis|siete|ocho|nueve|diez|once|doce|\\d)', hint: 'eine Uhrzeit (a las …)' },
        { pattern: '\\bpuedes\\b', hint: 'die Frage „¿Puedes?“' },
      ],
      samples: [
        '¡Hola, Marta! ¿Por qué no vamos al cine el sábado? Hay una película muy buena. ¿Nos vemos a las siete delante del cine? ¿Puedes?',
      ],
      minWords: 15,
      feedback: {
        rule: 'Vorschlag (`¿Por qué no …?` / `¿Te gustaría …?`), Zeit (`el sábado a las siete`), Ort (`delante del cine`) und Rückfrage (`¿Puedes?`).',
        why: 'Häufig fehlt die Rückfrage mit poder oder es rutscht „podes“ statt `puedes` heraus.',
        avoid: 'Prüfe am Ende: Tag? Uhrzeit? Ort? Frage mit `¿Puedes?` – dann ist deine Einladung komplett.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: STEM,
      difficulty: 2,
      prompt: 'Ein Freund lädt dich zu seiner Party am Samstag ein. Sag laut ab: Entschuldige dich, nenne einen Grund mit „Es que …“ und schlag einen anderen Tag vor.',
      keywords: ['lo siento', 'no puedo', 'es que', 'tengo que', 'qué tal', 'otro día', 'domingo', 'viernes'],
      minMatch: 3,
      sample: 'Lo siento, el sábado no puedo. Es que tengo que trabajar. ¿Qué tal el domingo?',
      feedback: {
        rule: 'Absage in drei Schritten: `Lo siento, no puedo.` – `Es que tengo que …` – `¿Qué tal …?`',
        why: 'Findet die Spracherkennung zu wenig, fehlen meist die festen Blöcke `lo siento` oder `no puedo`.',
        avoid: 'Sprich die Blöcke ruhig und deutlich: lo SIEN-to – no PUE-do – es que TEN-go que …',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: [...YO, ...STEM],
      difficulty: 3,
      scenarioId: 'es.sc.alltag',
      goal: 'Verabrede dich mit deinem Gegenüber: Mach einen Vorschlag (¿Por qué no …? / ¿Te gustaría …?), einigt euch auf Tag, Uhrzeit und Treffpunkt – oder sag höflich ab und schlag einen anderen Termin vor.',
      turns: 4,
      feedback: {
        rule: 'Vorschlag, Zusage oder Absage mit poder: `¿Puedes el viernes?` – `Sí, puedo.` / `Lo siento, no puedo.`',
        why: 'Im freien Gespräch rutscht leicht „podo“ oder „no sé“ (ich weiß nicht) statt `no puedo` heraus.',
        avoid: 'Leg dir vorher einen Vorschlag und eine Absage-Formel zurecht.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.ir-a'],
      difficulty: 1,
      verb: 'ir',
      tense: 'Präsens (ir a + Infinitiv)',
      person: 'yo',
      sentence: 'Mañana ___ a cenar con Ana.',
      answers: ['voy'],
      feedback: {
        rule: 'Pläne: `ir` (voy, vas, va …) + `a` + Infinitiv: `Voy a cenar con Ana.`',
        why: '„vo“ oder „iro“ gibt es nicht – ir ist ganz unregelmäßig: voy, vas, va, vamos, (vais), van.',
        avoid: 'Lern `voy a …` als Block für „ich werde …“ / „ich habe vor …“.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.weather'],
      difficulty: 1,
      prompt: 'Wiederholung Wetter: `¿Vamos a la playa? – Hoy no, ___ mucho frío.`',
      options: [
        { text: 'hace' },
        { text: 'está', why: 'estar steht z. B. bei `está nublado`, aber nicht bei frío oder calor.' },
        { text: 'hay', why: '`hay` passt zu `hay niebla` – Kälte und Hitze drückst du mit hacer aus.' },
        { text: 'es', why: 'ser beschreibt nicht das aktuelle Wetter.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Temperatur und Wetter mit hacer: `hace frío`, `hace calor`, `hace sol`, `hace viento`.',
        why: 'Das deutsche „es ist kalt“ verleitet zu `es` oder `está` – auf Spanisch „macht“ es Kälte.',
        avoid: 'Denk wörtlich: „Es macht viel Kälte.“ → `Hace mucho frío.`',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading'],
      topicIds: ['es.g.time-dates'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'Mi cumpleaños es el doce de mayo.',
      answers: [
        'Mein Geburtstag ist am 12. Mai.',
        'Mein Geburtstag ist am zwölften Mai.',
        'Ich habe am 12. Mai Geburtstag.',
        'Ich habe am zwölften Mai Geburtstag.',
        'Mein Geburtstag ist der 12. Mai.',
        'Mein Geburtstag ist der zwölfte Mai.',
      ],
      feedback: {
        rule: 'Datum: `el` + Zahl + `de` + Monat – `el doce de mayo` = am 12. Mai.',
        why: 'Das `el` vor dem Datum entspricht dem deutschen „am“. `doce` (12) nicht mit `dos` (2) verwechseln.',
        avoid: 'Lies Datumsangaben immer als Block: el … de …',
      },
    },
  ],
};

export default lesson;
