import type { Lesson } from '../../types';

const L = 'es.a1.l10';
const DEM = ['es.g.demonstratives'];
const STEM = ['es.g.stem-change'];

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c3',
  order: 10,
  title: 'Kleidung & Farben',
  subtitle: 'Este, ese, aquel – zeigen, anprobieren, nach der Größe fragen',
  icon: '👕',
  minutes: 13,
  goal:
    'Du sprichst über **Kleidung** und **Farben**, zeigst mit `este`, `ese` und `aquel` auf Dinge in der Nähe oder in der Ferne und kommst im Geschäft zurecht: `Quiero probarme esta chaqueta.` – `¿Qué talla tienes?` Dabei passt du Farben an das Nomen an: `una camisa roja`, `unos zapatos negros`.',
  canDo: [
    'Ich kann mit este, ese und aquel auf Dinge in unterschiedlicher Entfernung zeigen.',
    'Ich kann Kleidungsstücke mit Farben beschreiben und die Farbe richtig anpassen.',
    'Ich kann sagen, dass ich etwas anprobieren möchte (probarse, o → ue).',
    'Ich kann im Geschäft nach Größe und Preis fragen.',
  ],
  topicIds: ['es.g.demonstratives', 'es.g.stem-change'],
  vocab: [
    { id: `${L}.v.camisa`, target: 'la camisa', german: 'das Hemd; die Bluse', pos: 'noun', gender: 'f', plural: 'las camisas', emoji: '👔', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Esta camisa blanca es muy bonita.', german: 'Dieses weiße Hemd ist sehr schön.' } },
    { id: `${L}.v.camiseta`, target: 'la camiseta', german: 'das T-Shirt', pos: 'noun', gender: 'f', plural: 'las camisetas', emoji: '👕', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: '¿Cuánto cuesta esta camiseta?', german: 'Was kostet dieses T-Shirt?' } },
    { id: `${L}.v.pantalones`, target: 'los pantalones', german: 'die Hose', pos: 'noun', gender: 'm', emoji: '👖', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Estos pantalones son muy cómodos.', german: 'Diese Hose ist sehr bequem.' } },
    { id: `${L}.v.vestido`, target: 'el vestido', german: 'das Kleid', pos: 'noun', gender: 'm', plural: 'los vestidos', emoji: '👗', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Me gusta aquel vestido rojo.', german: 'Mir gefällt das rote Kleid dort drüben.' } },
    { id: `${L}.v.zapatos`, target: 'los zapatos', german: 'die Schuhe', pos: 'noun', gender: 'm', emoji: '👞', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Esos zapatos negros son caros.', german: 'Die schwarzen Schuhe da sind teuer.' } },
    { id: `${L}.v.chaqueta`, target: 'la chaqueta', german: 'die Jacke', pos: 'noun', gender: 'f', plural: 'las chaquetas', emoji: '🧥', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Me pruebo la chaqueta azul.', german: 'Ich probiere die blaue Jacke an.' } },
    { id: `${L}.v.jersey`, target: 'el jersey', german: 'der Pullover', pos: 'noun', gender: 'm', plural: 'los jerséis', emoji: '🧶', variant: 'es-ES', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Este jersey gris es de mi hermano.', german: 'Dieser graue Pullover gehört meinem Bruder.' } },
    { id: `${L}.v.sueter`, target: 'el suéter', german: 'der Pullover', pos: 'noun', gender: 'm', plural: 'los suéteres', emoji: '🧶', variant: 'es-LA', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Este suéter gris es de mi hermano.', german: 'Dieser graue Pullover gehört meinem Bruder.' } },
    { id: `${L}.v.talla`, target: 'la talla', german: 'die (Kleider-)Größe', pos: 'noun', gender: 'f', plural: 'las tallas', emoji: '📏', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: '¿Qué talla tienes?', german: 'Welche Größe hast du?' } },
    { id: `${L}.v.probarse`, target: 'probarse', german: 'anprobieren (ich: me pruebo)', pos: 'verb', field: 'Kleidung', stageId: 'a1', lessonId: L, example: { target: 'Quiero probarme estos pantalones.', german: 'Ich möchte diese Hose anprobieren.' } },
    { id: `${L}.v.rojo`, target: 'rojo, roja', german: 'rot', pos: 'adj', emoji: '🔴', field: 'Farben', stageId: 'a1', lessonId: L, example: { target: 'una camisa roja', german: 'ein rotes Hemd' } },
    { id: `${L}.v.azul`, target: 'azul', german: 'blau', pos: 'adj', gender: 'm/f', plural: 'azules', emoji: '🔵', field: 'Farben', stageId: 'a1', lessonId: L, example: { target: 'unos pantalones azules', german: 'eine blaue Hose' } },
    { id: `${L}.v.verde`, target: 'verde', german: 'grün', pos: 'adj', gender: 'm/f', plural: 'verdes', emoji: '🟢', field: 'Farben', stageId: 'a1', lessonId: L, example: { target: 'una chaqueta verde', german: 'eine grüne Jacke' } },
    { id: `${L}.v.negro`, target: 'negro, negra', german: 'schwarz', pos: 'adj', emoji: '⚫', field: 'Farben', stageId: 'a1', lessonId: L, example: { target: 'unos zapatos negros', german: 'schwarze Schuhe' } },
    { id: `${L}.v.blanco`, target: 'blanco, blanca', german: 'weiß', pos: 'adj', emoji: '⚪', field: 'Farben', stageId: 'a1', lessonId: L, example: { target: 'una camiseta blanca', german: 'ein weißes T-Shirt' } },
    { id: `${L}.v.amarillo`, target: 'amarillo, amarilla', german: 'gelb', pos: 'adj', emoji: '🟡', field: 'Farben', stageId: 'a1', lessonId: L, example: { target: 'un vestido amarillo', german: 'ein gelbes Kleid' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Mit **Demonstrativbegleitern** zeigst du auf Dinge. Das Deutsche kommt mit „dieser“ oder „der da“ aus, das Spanische unterscheidet **drei Entfernungen**:\n- `este` – hier, bei mir (`aquí`)\n- `ese` – da, bei dir (`ahí`)\n- `aquel` – dort drüben, weit weg von uns beiden (`allí`)\nSie stehen **vor** dem Nomen und passen sich wie Adjektive an Geschlecht und Zahl an: `esta camisa`, `esos zapatos`. Im Alltag benutzen viele Sprecher `ese` auch für weiter Entferntes – `aquel` betont ausdrücklich „dort drüben“. Für etwas ohne Namen gibt es die neutrale Form: `¿Cuánto cuesta esto?` (Was kostet das hier?)',
    },
    {
      type: 'table',
      title: 'Demonstrativbegleiter',
      headers: ['Entfernung', 'männlich Sg.', 'weiblich Sg.', 'männlich Pl.', 'weiblich Pl.'],
      rows: [
        ['hier (aquí)', 'este', 'esta', 'estos', 'estas'],
        ['da (ahí)', 'ese', 'esa', 'esos', 'esas'],
        ['dort drüben (allí)', 'aquel', 'aquella', 'aquellos', 'aquellas'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Esta', role: 'pronoun' },
        { text: ' ' },
        { text: 'camisa', role: 'subject' },
        { text: ' ' },
        { text: 'roja', role: 'adjective' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'muy bonita', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Dieses rote Hemd ist sehr schön.',
    },
    {
      type: 'tip',
      md:
        'Farben stehen **hinter** dem Nomen und passen sich an:\n- Farben auf **-o** haben vier Formen: `rojo, roja, rojos, rojas` (ebenso `negro`, `blanco`, `amarillo`).\n- Farben auf **-e** oder **Konsonant** haben nur zwei: `verde / verdes`, `azul / azules`, `gris / grises`, `marrón / marrones`.\n- `rosa` und `naranja` bleiben meist unverändert: `una camisa rosa`, `un vestido naranja`.',
    },
    {
      type: 'mistake',
      wrong: 'Quiero la roja camisa.',
      right: 'Quiero la camisa roja.',
      why: 'Im Deutschen steht die Farbe vor dem Nomen („das rote Hemd“). Im Spanischen steht sie **dahinter**: `la camisa roja`, `los zapatos negros`. Und nicht vergessen: `camisa` ist feminin, also `roja`.',
    },
    {
      type: 'conjugation',
      verb: 'probarse',
      translation: 'anprobieren',
      tense: 'Präsens (o → ue)',
      rows: [
        { person: 'yo', form: 'me pruebo', ending: 'o' },
        { person: 'tú', form: 'te pruebas', ending: 'as' },
        { person: 'él / ella / usted', form: 'se prueba', ending: 'a' },
        { person: 'nosotros / nosotras', form: 'nos probamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'os probáis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'se prueban', ending: 'an' },
      ],
    },
    {
      type: 'compare',
      target: '¿Qué talla tienes? – La treinta y ocho.',
      german: 'Welche Größe hast du? – 38.',
      md: 'Die Kleidergröße heißt `la talla`, die Schuhgröße `el número`: `¿Qué número tienes?` Nützliche Sätze im Geschäft: `Quiero probarme esta camisa.` und `¿Dónde están los probadores?` (Wo sind die Umkleidekabinen?). Die Frage `¿Puedo probarme …?` (Darf ich … anprobieren?) lernst du hier als feste Wendung – das Verb `poder` kommt in Lektion 13.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'Der Pullover heißt in Lateinamerika meist `el suéter` statt `el jersey`. Beim T-Shirt gibt es regionale Wörter – `la playera` (Mexiko), `la remera` (Argentinien, Uruguay), `la polera` (Chile) –, `la camiseta` verstehen aber alle. Braun heißt in Mexiko oft `café`. Nach der Größe fragt man auch mit `¿Qué talla usas?`, und die Umkleidekabinen heißen in Mexiko auch `los vestidores`.',
    },
  ],
  examples: [
    {
      target: 'Esta camiseta es muy bonita.',
      german: 'Dieses T-Shirt ist sehr schön.',
      parts: [
        { text: 'Esta', role: 'pronoun' },
        { text: ' ' },
        { text: 'camiseta', role: 'subject' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'muy bonita', role: 'adjective' },
        { text: '.' },
      ],
    },
    {
      target: '¿Cuánto cuesta ese vestido?',
      german: 'Was kostet das Kleid da?',
      parts: [
        { text: '¿Cuánto', role: 'question' },
        { text: ' ' },
        { text: 'cuesta', role: 'verb' },
        { text: ' ' },
        { text: 'ese', role: 'pronoun' },
        { text: ' ' },
        { text: 'vestido', role: 'subject' },
        { text: '?' },
      ],
    },
    {
      target: 'Aquellos zapatos negros son muy caros.',
      german: 'Die schwarzen Schuhe dort drüben sind sehr teuer.',
      parts: [
        { text: 'Aquellos', role: 'pronoun' },
        { text: ' ' },
        { text: 'zapatos', role: 'subject' },
        { text: ' ' },
        { text: 'negros', role: 'adjective' },
        { text: ' ' },
        { text: 'son', role: 'verb' },
        { text: ' ' },
        { text: 'muy caros', role: 'adjective' },
        { text: '.' },
      ],
      note: '`zapatos` ist maskulin Plural – deshalb `aquellos`, `negros` und `caros`.',
    },
    { target: 'Quiero probarme estos pantalones.', german: 'Ich möchte diese Hose anprobieren.', note: '`los pantalones` steht meist im Plural, obwohl es im Deutschen „die Hose“ heißt. Das `me` hängt am Infinitiv: `probarme`.' },
    { target: 'Me pruebo la chaqueta azul.', german: 'Ich probiere die blaue Jacke an.', note: 'o → ue wie bei `acostarse` (me acuesto).' },
    { target: '¿Dónde están los probadores?', german: 'Wo sind die Umkleidekabinen?' },
    { target: 'Me gusta este jersey verde.', german: 'Mir gefällt dieser grüne Pullover.', variant: 'es-ES' },
    { target: 'Me gusta este suéter verde.', german: 'Mir gefällt dieser grüne Pullover.', variant: 'es-LA' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: DEM,
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Kleidungsstück zu.',
      pairs: [
        { emoji: '👕', word: 'la camiseta' },
        { emoji: '👖', word: 'los pantalones' },
        { emoji: '👗', word: 'el vestido' },
        { emoji: '👞', word: 'los zapatos' },
        { emoji: '🧥', word: 'la chaqueta' },
      ],
      feedback: {
        rule: 'Kleidung mit Artikel lernen: `la camiseta`, `los pantalones`, `el vestido`, `los zapatos`, `la chaqueta`.',
        why: 'Das Genus weicht oft vom Deutschen ab: „das Kleid“ = `el vestido`, „die Hose“ = `los pantalones` (maskulin Plural).',
        avoid: 'Merke dir besonders die Wörter, deren Artikel anders ist als im Deutschen – dort passieren später die Anpassungsfehler.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: DEM,
      difficulty: 1,
      prompt: 'Du zeigst auf ein Kleid ganz hinten im Laden – weit weg von dir und von der Verkäuferin. Was passt? `¿Cuánto cuesta ___ vestido?`',
      options: [
        { text: 'aquel' },
        { text: 'este', why: '`este` bedeutet „hier, bei mir“ – das Kleid ist aber weit weg.' },
        { text: 'aquella', why: '`vestido` ist maskulin (`el vestido`), also nicht die weibliche Form.' },
        { text: 'esto', why: '`esto` ist neutral und steht nie vor einem Nomen.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Weit weg von beiden Sprechern: `aquel` (m), `aquella` (f), `aquellos`, `aquellas`.',
        why: 'Entscheidend sind zwei Dinge: die Entfernung (dort drüben → aquel) und das Genus des Nomens (el vestido → maskulin).',
        avoid: 'Frag dich zuerst „Wo ist es?“ (hier / da / dort) und dann „el oder la?“.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: DEM,
      difficulty: 2,
      instruction: 'Die Sachen liegen direkt vor dir. Setze die passenden Formen ein.',
      sentence: 'Quiero ___ camisa blanca y ___ pantalones ___.',
      answers: [['esta'], ['estos'], ['negros']],
      bank: ['esta', 'este', 'estos', 'estas', 'negros', 'negras'],
      german: 'Ich möchte dieses weiße Hemd (hier) und diese schwarze Hose (hier).',
      feedback: {
        rule: 'Demonstrativbegleiter und Farbe richten sich nach dem Nomen: `la camisa` → `esta … blanca`; `los pantalones` → `estos … negros`.',
        why: 'Das Deutsche „die Hose“ ist feminin Singular – `los pantalones` ist aber maskulin Plural. Deshalb `estos` und `negros`, nicht `esta` oder `negras`.',
        avoid: 'Schau immer auf den spanischen Artikel, nicht auf den deutschen: los → estos, -os.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: STEM,
      difficulty: 2,
      verb: 'probarse',
      tense: 'Präsens',
      person: 'yo',
      sentence: 'Yo ___ la camisa verde.',
      answers: ['me pruebo'],
      feedback: {
        rule: '`probarse` (o → ue): me pruebo, te pruebas, se prueba, nos probamos, os probáis, se prueban.',
        why: '„me probo“ vergisst den Stammwechsel; ohne `me` fehlt das Reflexivpronomen.',
        avoid: 'Denk an `acostarse` → me acuesto: gleiches Muster o → ue, gleiches `me` davor.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: DEM,
      difficulty: 2,
      audio: 'Quiero una chaqueta negra de la talla cuarenta.',
      question: 'Was möchte die Kundin?',
      options: [
        'eine schwarze Jacke in Größe 40',
        'eine schwarze Jacke in Größe 14',
        'ein schwarzes Kleid in Größe 40',
        'eine weiße Jacke in Größe 40',
      ],
      answer: 0,
      feedback: {
        rule: '`una chaqueta negra` = eine schwarze Jacke; `la talla cuarenta` = Größe 40.',
        why: '`cuarenta` (40) und `catorce` (14) werden gern verwechselt; `negra` (schwarz) ist nicht `blanca` (weiß).',
        avoid: 'Achte auf die Endung -enta: Sie steht immer für einen Zehner (treinta, cuarenta, cincuenta …).',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: DEM,
      difficulty: 2,
      instruction: 'Bilde die Frage „Was kosten die roten Schuhe dort drüben?“.',
      tokens: ['¿Cuánto', 'cuestan', 'aquellos', 'zapatos', 'rojos?'],
      extra: ['aquellas'],
      german: 'Was kosten die roten Schuhe dort drüben?',
      feedback: {
        rule: 'Demonstrativbegleiter vor dem Nomen, Farbe dahinter: `aquellos zapatos rojos`.',
        why: '`aquellas` ist weiblich – `zapatos` ist aber maskulin.',
        avoid: 'Reihenfolge merken: zeigen (aquellos) – Ding (zapatos) – Farbe (rojos).',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['reading', 'vocabulary'],
      topicIds: STEM,
      difficulty: 2,
      direction: 'toGerman',
      source: 'Me pruebo esta chaqueta azul.',
      answers: [
        'Ich probiere diese blaue Jacke an.',
        'Ich probiere diese blaue Jacke hier an.',
        'Ich probiere die blaue Jacke hier an.',
      ],
      feedback: {
        rule: '`me pruebo` = ich probiere an; `esta chaqueta azul` = diese blaue Jacke (hier).',
        why: '`probarse` heißt bei Kleidung „anprobieren“, nicht „probieren“ (kosten) oder „anziehen“.',
        avoid: 'probar = probieren/kosten; probarse (+ Kleidung) = anprobieren.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: DEM,
      difficulty: 3,
      instruction: 'Im Satz steckt ein Fehler. Schreib den Satz richtig.',
      sentence: 'Estas pantalones son muy bonitos.',
      answers: ['Estos pantalones son muy bonitos.'],
      german: 'Diese Hose ist sehr schön.',
      feedback: {
        rule: '`los pantalones` ist maskulin Plural → `estos pantalones`.',
        why: 'Das deutsche „diese Hose“ (feminin) lenkt zu `estas`. Entscheidend ist aber das spanische Genus.',
        avoid: 'Prüfe, ob Begleiter und Adjektiv zusammenpassen: `estos … bonitos` – beide auf -os.',
      },
    },
  ],
  pronunciation: ['es.p.cz.zapato', 'es.p.r.rosa', 'es.p.r.caro'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: DEM,
      difficulty: 2,
      scenario: 'Die Verkäuferin hält eine Hose in der Hand und zeigt sie dir. Du möchtest genau diese Hose anprobieren. Was sagst du?',
      options: [
        { text: '¿Puedo probarme esos pantalones?' },
        { text: '¿Puedo probarme esas pantalones?', why: '`pantalones` ist maskulin – `esas` ist die weibliche Form.' },
        { text: '¿Puedo probarme eso pantalones?', why: '`eso` ist neutral und steht nie vor einem Nomen.' },
        { text: '¿Puedo probarme esos pantalón?', why: '`esos` ist Plural, das Nomen muss also auch im Plural stehen: `pantalones`.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Bei deinem Gegenüber: `ese / esa / esos / esas`. `los pantalones` → `esos pantalones`.',
        why: 'Begleiter und Nomen müssen in Genus und Zahl übereinstimmen.',
        avoid: 'Begleiter, Nomen, Farbe – alle drei im gleichen Genus und in der gleichen Zahl.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.demonstratives', 'es.g.stem-change'],
      difficulty: 2,
      prompt: 'Du bist im Kleidungsgeschäft. Schreib 3–4 Sätze: Was gefällt dir (mit Farbe)? Was möchtest du anprobieren? Welche Größe hast du? Frag nach dem Preis.',
      requirements: [
        { pattern: '\\b(este|esta|estos|estas|ese|esa|esos|esas|aquel|aquella|aquellos|aquellas)\\b', hint: 'ein Demonstrativbegleiter (este, ese, aquel …)' },
        { pattern: '\\b(roj[oa]s?|negr[oa]s?|blanc[oa]s?|amarill[oa]s?|azul(es)?|verdes?|gris(es)?|marr[oó]n(es)?|rosa|naranja)\\b', hint: 'eine Farbe' },
        { pattern: 'talla', hint: 'deine Größe (talla)' },
        { pattern: '(cu[aá]nto|cuesta|cuestan)', hint: 'eine Frage nach dem Preis' },
      ],
      samples: [
        'Me gusta mucho esta chaqueta negra. Quiero probarme estos pantalones azules. Tengo la talla cuarenta. ¿Cuánto cuesta la chaqueta?',
      ],
      minWords: 15,
      feedback: {
        rule: 'Begleiter vor dem Nomen, Farbe dahinter, beide angepasst: `esta chaqueta negra`, `estos pantalones azules`.',
        why: 'Typische Fehler: Farbe vor dem Nomen (`la negra chaqueta`) oder falsches Genus nach deutschem Vorbild (`estas pantalones`).',
        avoid: 'Lies deinen Text einmal nur auf die Endungen: Passen Begleiter, Nomen und Farbe zusammen?',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: DEM,
      difficulty: 2,
      prompt: 'Du stehst im Geschäft. Sag laut, welche Kleidungsstücke dir in welcher Farbe gefallen – mit este, ese oder aquel (2–3 Sätze).',
      keywords: ['este', 'esta', 'estos', 'estas', 'ese', 'esa', 'esos', 'esas', 'aquel', 'aquella', 'aquellos', 'aquellas', 'camisa', 'camiseta', 'pantalones', 'vestido', 'zapatos', 'chaqueta', 'rojo', 'roja', 'negro', 'negra', 'negros', 'blanco', 'blanca', 'azul', 'azules', 'verde', 'gusta', 'gustan'],
      minMatch: 4,
      sample: 'Me gusta esta camiseta azul. Aquellos zapatos negros también me gustan.',
      feedback: {
        rule: '`Me gusta` + Singular, `Me gustan` + Plural; Begleiter vor, Farbe hinter dem Nomen.',
        why: 'Werden zu wenige Schlüsselwörter erkannt, fehlen meist der Begleiter oder die Farbe.',
        avoid: 'Zeig beim Sprechen wirklich auf etwas – das hilft, este / ese / aquel automatisch zu wählen.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.demonstratives', 'es.g.stem-change'],
      difficulty: 2,
      scenarioId: 'es.sc.einkaufen',
      goal: 'Kauf ein Kleidungsstück: Sag, was du suchst (Farbe und Größe), frag, ob du es anprobieren kannst, und frag nach dem Preis.',
      turns: 4,
      feedback: {
        rule: 'Größe: `Tengo la talla …`; anprobieren: `Quiero probarme …` / `¿Puedo probarme …?`; Preis: `¿Cuánto cuesta …?`',
        why: 'Im Gespräch geht leicht die Anpassung der Farbe verloren – `una chaqueta negro` statt `negra`.',
        avoid: 'Leg dir vorher einen Satz zurecht: „Quiero una chaqueta negra de la talla …“.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.numbers-big'],
      difficulty: 2,
      prompt: 'Wiederholung große Zahlen: Wie sagt man **450 €**?',
      options: [
        { text: 'cuatrocientos cincuenta euros' },
        { text: 'cuatrocientos y cincuenta euros', why: 'Nach den Hundertern steht kein `y` – nur zwischen Zehner und Einer.' },
        { text: 'cuatrocientas cincuenta euros', why: '`el euro` ist maskulin, also `cuatrocientos`.' },
        { text: 'cuatro cientos cincuenta euros', why: 'Die Hunderter schreibt man in einem Wort: `cuatrocientos`.' },
      ],
      answer: 0,
      feedback: {
        rule: '450 = `cuatrocientos cincuenta`: Hunderter in einem Wort, angepasst an das Nomen, ohne `y` danach.',
        why: 'Das `y` gehört nur zwischen Zehner und Einer (`cincuenta y dos`).',
        avoid: 'Denk an „vierhundertfünfzig“: Auch im Deutschen kommt nach „hundert“ kein „und“.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.ser-estar'],
      difficulty: 2,
      instruction: 'Wiederholung ser/estar: Setze die passende Form ein.',
      sentence: 'La tienda ___ en el centro y ___ muy grande.',
      answers: [['está'], ['es']],
      bank: ['es', 'está', 'hay', 'son'],
      german: 'Das Geschäft ist im Zentrum und es ist sehr groß.',
      feedback: {
        rule: 'Ort einer bestimmten Sache → `estar` (`está en el centro`); Eigenschaft → `ser` (`es muy grande`).',
        why: '`hay` steht bei unbestimmten Dingen (`hay una tienda`), nicht bei `la tienda`.',
        avoid: 'Frage: „Wo ist es?“ → estar. „Wie ist es?“ (Eigenschaft) → ser.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.reflexive'],
      difficulty: 2,
      verb: 'levantarse',
      tense: 'Präsens',
      person: 'nosotros',
      sentence: 'Nosotros ___ a las siete.',
      answers: ['nos levantamos'],
      feedback: {
        rule: 'Reflexive Verben: Pronomen + Verbform – `nos levantamos`.',
        why: 'Das Reflexivpronomen passt zur Person: yo → me, nosotros → nos. Ohne `nos` hieße es „wir heben (etwas) hoch“.',
        avoid: 'Merke das Paar: nosotros ↔ nos, genau wie bei `nos probamos`.',
      },
    },
  ],
};

export default lesson;
