import type { Lesson } from '../../types';

const L = 'es.a1.l15';
const MM = ['es.g.muy-mucho'];
const SE = ['es.g.ser-estar'];

/** „Sie ist sehr nett, aber heute ist sie müde.“ – mit/ohne Pronomen, Synonyme für „nett“, Stellung von hoy. */
const NICE_ANSWERS = ['', 'Ella '].flatMap((subj) =>
  ['simpática', 'amable', 'maja'].flatMap((adj) =>
    ['hoy está cansada', 'hoy ella está cansada', 'está cansada hoy'].map((tail) => {
      const s = `${subj}es muy ${adj}, pero ${tail}.`;
      return s.charAt(0).toUpperCase() + s.slice(1);
    }),
  ),
);

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'a1',
  chapterId: 'es.a1.c5',
  order: 15,
  title: 'Menschen beschreiben',
  subtitle: 'Aussehen, Charakter und der Unterschied zwischen muy und mucho',
  icon: '🧑‍🦱',
  minutes: 13,
  goal:
    'Du beschreibst Menschen: ihr Aussehen (`Es alta y tiene el pelo largo.`, `Lleva gafas.`) und ihren Charakter (`Es muy simpático.`). Außerdem lernst du den Unterschied zwischen **muy** (sehr) und **mucho** (viel) und wiederholst ser und estar bei Charakter und Stimmung.',
  canDo: [
    'Ich kann das Aussehen einer Person mit ser, tener und llevar beschreiben.',
    'Ich kann den Charakter einer Person mit passenden Adjektiven beschreiben.',
    'Ich kann muy und mucho richtig verwenden.',
    'Ich kann ser (Charakter) und estar (Stimmung) auseinanderhalten.',
  ],
  topicIds: ['es.g.muy-mucho', 'es.g.ser-estar'],
  vocab: [
    { id: `${L}.v.alto`, target: 'alto, alta', german: 'groß (Körpergröße); hoch', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi padre es muy alto.', german: 'Mein Vater ist sehr groß.' } },
    { id: `${L}.v.bajo`, target: 'bajo, baja', german: 'klein (Körpergröße); niedrig', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi abuela es baja y delgada.', german: 'Meine Großmutter ist klein und schlank.' } },
    { id: `${L}.v.delgado`, target: 'delgado, delgada', german: 'schlank, dünn', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Carlos es alto y delgado.', german: 'Carlos ist groß und schlank.' } },
    { id: `${L}.v.rubio`, target: 'rubio, rubia', german: 'blond', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi hermana es rubia.', german: 'Meine Schwester ist blond.' } },
    { id: `${L}.v.moreno`, target: 'moreno, morena', german: 'dunkelhaarig; braun gebrannt', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Pablo es moreno y tiene los ojos negros.', german: 'Pablo ist dunkelhaarig und hat dunkle Augen.' } },
    { id: `${L}.v.pelo`, target: 'el pelo', german: 'die Haare (auf dem Kopf)', pos: 'noun', gender: 'm', emoji: '💇', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Tiene el pelo largo.', german: 'Er / Sie hat lange Haare.' } },
    { id: `${L}.v.largo`, target: 'largo, larga', german: 'lang', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi hermana tiene el pelo largo.', german: 'Meine Schwester hat lange Haare.' } },
    { id: `${L}.v.corto`, target: 'corto, corta', german: 'kurz', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi hermano tiene el pelo corto.', german: 'Mein Bruder hat kurze Haare.' } },
    { id: `${L}.v.ojos`, target: 'los ojos', german: 'die Augen', pos: 'noun', gender: 'm', emoji: '👀', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Tiene los ojos azules.', german: 'Er / Sie hat blaue Augen.' } },
    { id: `${L}.v.llevar`, target: 'llevar', german: 'tragen (Brille, Bart, Kleidung)', pos: 'verb', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi abuelo lleva barba.', german: 'Mein Großvater trägt einen Bart.' } },
    { id: `${L}.v.barba`, target: 'la barba', german: 'der Bart', pos: 'noun', gender: 'f', plural: 'las barbas', emoji: '🧔', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi abuelo tiene barba.', german: 'Mein Großvater hat einen Bart.' } },
    { id: `${L}.v.gafas`, target: 'las gafas', german: 'die Brille', pos: 'noun', gender: 'f', emoji: '👓', variant: 'es-ES', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Llevo gafas para leer.', german: 'Zum Lesen trage ich eine Brille.' } },
    { id: `${L}.v.lentes`, target: 'los lentes', german: 'die Brille', pos: 'noun', gender: 'm', emoji: '👓', variant: 'es-LA', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Mi mamá usa lentes.', german: 'Meine Mama trägt eine Brille.' } },
    { id: `${L}.v.simpatico`, target: 'simpático, simpática', german: 'nett, sympathisch', pos: 'adj', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Tu hermano es muy simpático.', german: 'Dein Bruder ist sehr nett.' } },
    { id: `${L}.v.divertido`, target: 'divertido, divertida', german: 'lustig, unterhaltsam', pos: 'adj', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Mis amigos son muy divertidos.', german: 'Meine Freunde sind sehr lustig.' } },
    { id: `${L}.v.timido`, target: 'tímido, tímida', german: 'schüchtern', pos: 'adj', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Es un poco tímida.', german: 'Sie ist ein bisschen schüchtern.' } },
    { id: `${L}.v.mucho`, target: 'mucho, mucha, muchos, muchas', german: 'viel, viele; (nach Verben) sehr', pos: 'adv', field: 'Beschreiben', stageId: 'a1', lessonId: L, example: { target: 'Tiene muchos amigos y trabaja mucho.', german: 'Er / Sie hat viele Freunde und arbeitet viel.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Für die Beschreibung einer Person brauchst du drei Verben:\n- **ser** + Adjektiv für Aussehen und Charakter: `Es alta y muy simpática.`\n- **tener** für Haare und Augen: `Tiene el pelo corto y los ojos verdes.`\n- **llevar** für Brille, Bart und Kleidung: `Lleva gafas y barba.`\nDie Adjektive passen sich wie immer an: `Pablo es alto` – `Lucía es alta` – `Son altos`. Adjektive auf -e oder auf Konsonant haben eine Form für beide Geschlechter: `inteligente`, `amable`, `joven`.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Mi hermana', role: 'subject' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'alta', role: 'adjective' },
        { text: ' y ' },
        { text: 'tiene', role: 'verb' },
        { text: ' ' },
        { text: 'el pelo', role: 'object' },
        { text: ' ' },
        { text: 'largo', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Meine Schwester ist groß und hat lange Haare.',
    },
    {
      type: 'compare',
      target: 'Tiene el pelo largo.',
      german: 'Sie hat lange Haare.',
      md:
        'Deutsch sagt „die Haare“ (Plural), Spanisch `el pelo` (Singular) – mit bestimmtem Artikel und dem Adjektiv dahinter: `el pelo largo`, `los ojos azules`.\nVorsicht, falscher Freund: `largo` heißt „lang“, nicht „large“ (groß)! Groß (Körpergröße) ist `alto`.',
    },
    {
      type: 'table',
      title: 'muy oder mucho?',
      headers: ['Wort', 'steht …', 'Beispiel', 'Deutsch'],
      rows: [
        ['muy (unveränderlich)', 'vor Adjektiv oder Adverb', 'Es muy simpática.', 'Sie ist sehr nett.'],
        ['mucho (unveränderlich)', 'nach einem Verb', 'Trabaja mucho.', 'Er arbeitet viel.'],
        ['mucho, mucha, muchos, muchas', 'vor einem Nomen', 'Tiene muchos amigos.', 'Sie hat viele Freunde.'],
        ['mucho (allein)', 'als kurze Antwort', '¿Te gusta? – Sí, mucho.', 'Gefällt es dir? – Ja, sehr.'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Me gusta muy.',
      right: 'Me gusta mucho.',
      why:
        'Deutsch „sehr“ klappt bei Adjektiven (sehr nett = `muy simpático`), aber nach einem Verb steht auf Spanisch `mucho`: `Me gusta mucho.` `muy` steht nie allein – es braucht immer ein Adjektiv oder Adverb dahinter.',
    },
    {
      type: 'text',
      md:
        '**ser oder estar?** Charakter und Aussehen beschreibst du mit **ser** – so ist jemand grundsätzlich. Stimmungen und Zustände mit **estar** – so geht es jemandem gerade: `Marta es tranquila, pero hoy está nerviosa.`\nAuch die Fragen unterscheiden sich: `¿Cómo es tu hermano?` = Wie ist dein Bruder (Aussehen, Charakter)? – `¿Cómo está tu hermano?` = Wie geht es deinem Bruder?',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'Statt `las gafas` sagt man in Lateinamerika `los lentes` (in Argentinien auch `los anteojos`) und oft `usar` statt `llevar`: `Usa lentes.` Braune Augen sind in Spanien `ojos marrones`, in vielen Ländern Lateinamerikas `ojos cafés`. Für „dunkelhaarig“ hört man in Argentinien `morocho`; `moreno` kann in Lateinamerika auch „dunkelhäutig“ bedeuten.',
    },
    {
      type: 'tip',
      md:
        'Merksatz: **muy vor Eigenschaften, mucho nach Verben und vor Dingen** – `muy alto`, `trabaja mucho`, `muchos amigos`.\nUnd: **ser** sagt, wie jemand _ist_, **estar**, wie es jemandem _geht_. Übrigens: Über das Gewicht anderer spricht man auch auf Spanisch lieber nicht direkt – `delgado` (schlank) ist unproblematisch.',
    },
  ],
  examples: [
    {
      target: 'Mi padre es alto y delgado.',
      german: 'Mein Vater ist groß und schlank.',
      parts: [
        { text: 'Mi padre', role: 'subject' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'alto', role: 'adjective' },
        { text: ' y ' },
        { text: 'delgado', role: 'adjective' },
        { text: '.' },
      ],
    },
    {
      target: 'Lucía tiene el pelo rizado y los ojos verdes.',
      german: 'Lucía hat lockige Haare und grüne Augen.',
      note: '`rizado` = lockig, `liso` = glatt. Das Adjektiv steht hinter dem Nomen.',
    },
    {
      target: 'Mi abuelo lleva gafas y barba.',
      german: 'Mein Großvater trägt eine Brille und einen Bart.',
      variant: 'es-ES',
      note: '`las gafas` steht immer im Plural – wie englisch „glasses“.',
    },
    {
      target: 'Mi abuelo usa lentes y tiene barba.',
      german: 'Mein Großvater trägt eine Brille und hat einen Bart.',
      variant: 'es-LA',
    },
    {
      target: 'Marta es muy simpática y tiene muchos amigos.',
      german: 'Marta ist sehr nett und hat viele Freunde.',
      parts: [
        { text: 'Marta', role: 'subject' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'muy', role: 'adverb' },
        { text: ' ' },
        { text: 'simpática', role: 'adjective' },
        { text: ' y ' },
        { text: 'tiene', role: 'verb' },
        { text: ' ' },
        { text: 'muchos', role: 'adjective' },
        { text: ' ' },
        { text: 'amigos', role: 'noun' },
        { text: '.' },
      ],
      note: '`muy` bleibt immer gleich, `muchos` passt sich an `amigos` an.',
    },
    {
      target: 'Pablo trabaja mucho, pero es muy divertido.',
      german: 'Pablo arbeitet viel, aber er ist sehr lustig.',
    },
    {
      target: 'Normalmente es tranquila, pero hoy está nerviosa.',
      german: 'Normalerweise ist sie ruhig, aber heute ist sie nervös.',
      note: 'Charakter (ser) gegenüber momentaner Stimmung (estar).',
    },
    {
      target: '¿Cómo es tu hermano? – Es alto, moreno y muy simpático.',
      german: 'Wie ist dein Bruder? – Er ist groß, dunkelhaarig und sehr nett.',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary'],
      topicIds: SE,
      difficulty: 1,
      instruction: 'Ordne die Adjektive ihrer Bedeutung zu. Achtung, falscher Freund!',
      pairs: [
        { left: 'alto', right: 'groß' },
        { left: 'bajo', right: 'klein' },
        { left: 'largo', right: 'lang' },
        { left: 'corto', right: 'kurz' },
        { left: 'delgado', right: 'schlank' },
        { left: 'divertido', right: 'lustig' },
      ],
      feedback: {
        rule: '`alto` = groß (Körpergröße), `bajo` = klein, `largo` = lang, `corto` = kurz.',
        why: '`largo` sieht aus wie englisch „large“, bedeutet aber „lang“. „Groß“ heißt bei Menschen `alto`, bei Dingen `grande`.',
        avoid: 'Merke: `el pelo largo` = lange Haare; `una persona alta` = ein großer Mensch.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: MM,
      difficulty: 1,
      prompt: 'Welches Wort passt? `Mi hermana es ___ simpática.`',
      options: [
        { text: 'muy' },
        { text: 'mucho', why: '`mucho` steht nach Verben oder vor Nomen – vor einem Adjektiv wie simpática brauchst du `muy`.' },
        { text: 'mucha', why: 'Auch die angepasste Form `mucha` steht nur vor Nomen: `mucha paciencia`.' },
        { text: 'muchos', why: '`muchos` steht vor Nomen im Plural: `muchos amigos`.' },
      ],
      answer: 0,
      feedback: {
        rule: '`muy` + Adjektiv oder Adverb: `muy simpática`, `muy bien`. `muy` verändert sich nie.',
        why: 'Deutsch „sehr“ vor einem Adjektiv entspricht `muy`. „viel“ (mucho) passt vor Adjektiven nicht.',
        avoid: 'Folgt ein Adjektiv? → `muy`.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 1,
      instruction: 'Hör genau hin: Welches Wort wird gesprochen?',
      options: ['pelo', 'pero'],
      answer: 0,
      hint: '`pelo` (Haare) hat ein l: Die Zunge liegt ruhig oben an. `pero` (aber) hat ein einfaches r: Die Zungenspitze schlägt einmal kurz an.',
      feedback: {
        rule: '`pelo` = Haare (l), `pero` = aber (einfaches r).',
        why: 'Das spanische einfache r ist ein einziger kurzer Zungenschlag – fast wie das „tt“ in amerikanisch „better“. Mit deutschem Rachen-r wirst du schlecht verstanden.',
        avoid: 'Sprich beide Wörter im Wechsel: PE-lo – PE-ro. Übe `pelo` im Aussprachelabor.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: SE,
      difficulty: 2,
      instruction: 'Setze ser, tener oder llevar in der passenden Form ein.',
      sentence: 'Mi abuelo ___ muy simpático. ___ el pelo blanco y ___ barba.',
      answers: [['es'], ['tiene'], ['lleva', 'tiene']],
      bank: ['es', 'está', 'tiene', 'lleva'],
      german: 'Mein Großvater ist sehr nett. Er hat weiße Haare und trägt einen Bart.',
      feedback: {
        rule: 'Charakter mit `ser` (`es simpático`), Haare mit `tener` (`tiene el pelo blanco`), Bart und Brille mit `llevar` (`lleva barba`) – `tiene barba` geht auch.',
        why: '`está` beschreibt eine Stimmung, nicht den Charakter. Und Haare „ist“ man nicht, man „hat“ sie: `tiene el pelo …`.',
        avoid: 'Frag dich: Ist das sein Wesen (ser)? Hat er es am Körper (tener)? Trägt er es (llevar)?',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: SE,
      difficulty: 2,
      audio: 'Mi hermano es bajo y rubio. Tiene el pelo corto y los ojos azules. Es un poco tímido, pero muy simpático.',
      question: 'Wie ist der Bruder?',
      options: [
        'klein, blond, kurze Haare, blaue Augen, etwas schüchtern',
        'groß, blond, kurze Haare, blaue Augen, etwas schüchtern',
        'klein, blond, lange Haare, blaue Augen, sehr lustig',
        'klein, dunkelhaarig, kurze Haare, grüne Augen, etwas schüchtern',
      ],
      answer: 0,
      feedback: {
        rule: '`bajo` = klein, `rubio` = blond, `el pelo corto` = kurze Haare, `los ojos azules` = blaue Augen, `un poco tímido` = etwas schüchtern.',
        why: '`bajo` (klein) und `alto` (groß) werden oft vertauscht, ebenso `corto` (kurz) und `largo` (lang).',
        avoid: 'Mach dir beim Hören Stichpunkte in zwei Spalten: Aussehen | Charakter.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar'],
      topicIds: MM,
      difficulty: 2,
      instruction: 'Bilde den Satz „Sie hat viele Freunde, weil sie sehr lustig ist.“',
      tokens: ['Tiene', 'muchos', 'amigos', 'porque', 'es', 'muy', 'divertida.'],
      extra: ['mucho', 'está'],
      german: 'Sie hat viele Freunde, weil sie sehr lustig ist.',
      feedback: {
        rule: '`muchos` + Nomen im Plural (`muchos amigos`), `muy` + Adjektiv (`muy divertida`).',
        why: '`mucho` passt nicht vor `amigos` (Plural → muchos). `está` passt nicht, weil es um den Charakter geht (ser).',
        avoid: '`mucho` passt sich an wie ein Adjektiv – `muy` nie.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: [...SE, ...MM],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Sie ist sehr nett, aber heute ist sie müde.',
      answers: NICE_ANSWERS,
      feedback: {
        rule: 'Charakter → `ser` (`es muy simpática`), Zustand heute → `estar` (`está cansada`).',
        why: '„es cansada“ ist falsch, weil Müdigkeit ein Zustand ist. Und „nett“ ist eine Eigenschaft – also `es`, nicht `está`.',
        avoid: 'Wörter wie `hoy` oder `ahora` sind Signale für estar.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: ['es.g.gender-plural'],
      difficulty: 3,
      instruction: 'Im Satz steckt ein typischer Fehler Deutschsprachiger. Schreib den Satz richtig.',
      sentence: 'Mi hermana tiene los pelos largos.',
      answers: ['Mi hermana tiene el pelo largo.'],
      german: 'Meine Schwester hat lange Haare.',
      feedback: {
        rule: 'Die Haare auf dem Kopf = `el pelo` (Singular): `tiene el pelo largo`.',
        why: 'Das deutsche „Haare“ steht im Plural – `los pelos` sind auf Spanisch aber einzelne Haare, z. B. in der Suppe oder auf dem Sofa.',
        avoid: 'Lerne den Block `tener el pelo` + Adjektiv: el pelo largo, corto, rubio, rizado.',
      },
    },
  ],
  pronunciation: ['es.p.vowels.pelo', 'es.p.link.mis-amigos'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: [...SE, ...MM],
      difficulty: 2,
      prompt: 'Beschreibe eine Person, die dir wichtig ist (4–5 Sätze): Aussehen, Charakter – und wie es ihr gerade geht.',
      requirements: [
        { pattern: '\\b(es|son)\\b', hint: 'ser für Aussehen oder Charakter (es …)' },
        { pattern: '\\b(tiene|tienen)\\b.*\\b(pelo|ojos)\\b', hint: 'tener + el pelo / los ojos' },
        { pattern: '\\bmuy\\b', hint: 'muy + Adjektiv' },
        { pattern: '\\b(esta|está|estan|están)\\b', hint: 'estar für die Stimmung (hoy está …)' },
      ],
      samples: [
        'Mi amiga Carmen es alta y delgada. Tiene el pelo largo y los ojos verdes. Es muy simpática y trabaja mucho. Hoy está cansada.',
      ],
      minWords: 18,
      feedback: {
        rule: 'Aussehen/Charakter → `es` + Adjektiv; Haare/Augen → `tiene el pelo / los ojos …`; Stimmung → `está`; `muy` vor Adjektiven.',
        why: 'Typische Fehler: „tiene los pelos“, „es cansada“ und „mucho simpática“.',
        avoid: 'Lies deinen Text einmal nur auf muy/mucho und einmal nur auf ser/estar durch.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: [...SE, ...MM],
      difficulty: 2,
      prompt: 'Beschreib laut eine berühmte oder erfundene Person, ohne ihren Namen zu nennen (3–4 Sätze): Aussehen und Charakter.',
      keywords: ['es', 'tiene', 'lleva', 'pelo', 'ojos', 'alto', 'alta', 'bajo', 'baja', 'muy', 'rubio', 'rubia', 'moreno', 'morena', 'simpático', 'simpática'],
      minMatch: 4,
      sample: 'Es alta y morena. Tiene el pelo largo y los ojos verdes. Es muy simpática.',
      feedback: {
        rule: 'Beschreibung mit `es` + Adjektiv, `tiene el pelo / los ojos …` und `lleva …`.',
        why: 'Werden zu wenige Schlüsselwörter erkannt, waren die Sätze meist zu kurz oder das Adjektiv fehlte.',
        avoid: 'Denk an die Endung: Frau → -a (`alta`, `morena`), Mann → -o (`alto`, `moreno`).',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: [...SE, ...MM],
      difficulty: 3,
      scenarioId: 'es.sc.alltag',
      goal: 'Erzähl deinem Gegenüber von einer Freundin oder einem Familienmitglied: Beschreibe Aussehen und Charakter und beantworte Rückfragen wie „¿Cómo es?“ oder „¿Qué tal está?“.',
      turns: 4,
      feedback: {
        rule: '`¿Cómo es?` → Aussehen/Charakter mit ser; `¿Cómo está?` → Befinden mit estar.',
        why: 'Die beiden Fragen klingen fast gleich, fragen aber nach ganz Verschiedenem.',
        avoid: 'Hör genau auf das Verb der Frage und antworte mit demselben Verb.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.hay'],
      difficulty: 1,
      prompt: 'Wiederholung: `¿Dónde ___ el baño, por favor?`',
      options: [
        { text: 'está' },
        { text: 'hay', why: 'Nach `el baño` (bestimmt) fragst du mit `¿Dónde está …?`. Mit hay fragst du, ob es etwas überhaupt gibt: `¿Hay un baño por aquí?`' },
        { text: 'es', why: 'Den Ort drückst du mit estar aus, nicht mit ser.' },
        { text: 'tiene', why: '`tiene` heißt „hat“ – damit fragst du nicht nach einem Ort.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Ort von etwas Bestimmtem: `¿Dónde está …?` + el / la.',
        why: '`hay` steht vor un/una oder Zahlen, nicht vor dem bestimmten Artikel.',
        avoid: '¿Dónde …? verlangt fast immer `está` / `están`.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.yo-irregular'],
      difficulty: 2,
      verb: 'conocer',
      tense: 'Präsens',
      person: 'yo',
      sentence: '___ un restaurante muy bueno cerca de aquí.',
      answers: ['conozco'],
      feedback: {
        rule: '`conocer → conozco`: In der yo-Form wird aus -c- ein -zc-.',
        why: '„conoco“ folgt dem regelmäßigen Muster – das gibt es nicht.',
        avoid: 'Merke das Klangbild co-NOZ-co; alle anderen Formen sind regelmäßig.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading'],
      topicIds: ['es.g.gustar', 'es.g.muy-mucho'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'A mi hermano le gusta mucho bailar.',
      answers: [
        'Mein Bruder tanzt sehr gern.',
        'Mein Bruder tanzt sehr gerne.',
        'Mein Bruder tanzt wirklich gern.',
        'Meinem Bruder gefällt es sehr zu tanzen.',
        'Meinem Bruder gefällt es sehr, zu tanzen.',
        'Mein Bruder mag Tanzen sehr.',
      ],
      feedback: {
        rule: '`le gusta mucho` + Infinitiv = er macht etwas sehr gern. `mucho` steht hier nach dem Verb gustar.',
        why: '`a mi hermano` ist die Person, der etwas gefällt – nicht das Subjekt des spanischen Satzes.',
        avoid: 'Übersetze gustar + Infinitiv am natürlichsten mit „gern“: `Me gusta bailar.` = Ich tanze gern.',
      },
    },
  ],
};

export default lesson;
