import type { Lesson } from '../../types';

const L = 'es.s0.l02';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c1',
  order: 2,
  title: 'Laute & Alphabet',
  subtitle: 'So klingt Spanisch – und so schreibt man es',
  icon: '🔤',
  minutes: 12,
  goal:
    'Du lernst die wichtigsten Regeln, wie spanische Buchstaben klingen, und wo ein Wort betont wird. Danach kannst du fast jedes Wort, das du liest, richtig aussprechen – Spanisch spricht man nämlich (fast) so, wie man es schreibt.',
  canDo: [
    'Ich kann die fünf Vokale klar und rein aussprechen.',
    'Ich weiß, wie h, j, g, ll, y, ñ, r/rr, c, z und qu klingen.',
    'Ich kann die Betonung eines Wortes aus der Schreibung ableiten.',
    'Ich weiß, wofür das Akzentzeichen steht.',
  ],
  topicIds: ['es.g.alphabet-sounds', 'es.g.stress'],
  vocab: [
    { id: `${L}.v.perro`, target: 'el perro', german: 'der Hund', pos: 'noun', gender: 'm', plural: 'los perros', emoji: '🐶', field: 'Tiere', stageId: 'stage0', lessonId: L, example: { target: '¡Hola, perro!', german: 'Hallo, Hund!' } },
    { id: `${L}.v.pero`, target: 'pero', german: 'aber', pos: 'other', field: 'Bindewörter', stageId: 'stage0', lessonId: L, example: { target: 'Bien, pero…', german: 'Gut, aber …' } },
    { id: `${L}.v.jamon`, target: 'el jamón', german: 'der Schinken', pos: 'noun', gender: 'm', plural: 'los jamones', emoji: '🍖', field: 'Essen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.gente`, target: 'la gente', german: 'die Leute', pos: 'noun', gender: 'f', emoji: '👥', field: 'Menschen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.guitarra`, target: 'la guitarra', german: 'die Gitarre', pos: 'noun', gender: 'f', plural: 'las guitarras', emoji: '🎸', field: 'Musik', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.llave`, target: 'la llave', german: 'der Schlüssel', pos: 'noun', gender: 'f', plural: 'las llaves', emoji: '🔑', field: 'Alltagsgegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.playa`, target: 'la playa', german: 'der Strand', pos: 'noun', gender: 'f', plural: 'las playas', emoji: '🏖️', field: 'Orte', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.nino`, target: 'el niño', german: 'das Kind / der Junge', pos: 'noun', gender: 'm', plural: 'los niños', emoji: '👦', field: 'Menschen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.queso`, target: 'el queso', german: 'der Käse', pos: 'noun', gender: 'm', plural: 'los quesos', emoji: '🧀', field: 'Essen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.cerveza`, target: 'la cerveza', german: 'das Bier', pos: 'noun', gender: 'f', plural: 'las cervezas', emoji: '🍺', field: 'Getränke', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.vaca`, target: 'la vaca', german: 'die Kuh', pos: 'noun', gender: 'f', plural: 'las vacas', emoji: '🐄', field: 'Tiere', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.cafe`, target: 'el café', german: 'der Kaffee', pos: 'noun', gender: 'm', plural: 'los cafés', emoji: '☕', field: 'Getränke', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.telefono`, target: 'el teléfono', german: 'das Telefon', pos: 'noun', gender: 'm', plural: 'los teléfonos', emoji: '📞', field: 'Alltagsgegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.zapato`, target: 'el zapato', german: 'der Schuh', pos: 'noun', gender: 'm', plural: 'los zapatos', emoji: '👞', field: 'Kleidung', stageId: 'stage0', lessonId: L },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Das spanische Alphabet hat **27 Buchstaben** – einen mehr als das deutsche: `ñ` (eñe). `ch` und `ll` sind Buchstabenkombinationen.\n' +
        'Die fünf **Vokale** a, e, i, o, u klingen immer gleich: klar, eher kurz und nie verschluckt. Ein End-e wie in `gente` ist ein volles „e“, kein gemurmeltes „e“ wie in „Leute“. Und `eu` spricht man e-u (`euro` = „e-u-ro“, nicht „oiro“).\n' +
        'Buchstabieren: h = _hache_, j = _jota_, ñ = _eñe_, q = _cu_, r = _erre_, v = _uve_, y = _ye_, z = _zeta_.',
    },
    {
      type: 'table',
      title: 'Die wichtigsten Laut-Regeln',
      headers: ['Schreibung', 'Aussprache', 'Beispiel'],
      rows: [
        ['h', 'immer stumm', 'hola → „ola“'],
        ['j · g vor e/i', 'rau wie „ch“ in „Bach“', 'jamón, gente'],
        ['g vor a/o/u · gu vor e/i', 'wie deutsches g (u bleibt stumm)', 'gato, guitarra'],
        ['ll · y', 'wie „j“ in „ja“', 'llave, yo, playa'],
        ['ñ', 'wie „nj“ in „Champagner“', 'niño, mañana'],
        ['r', 'ein kurzer Zungenschlag', 'pero'],
        ['rr · r am Wortanfang', 'gerollt, mehrere Zungenschläge', 'perro, Rosa'],
        ['c vor a/o/u · qu vor e/i', 'wie k (u bleibt stumm)', 'café, queso'],
        ['c vor e/i · z', 'Spanien: wie engl. „th“ in „think“ · Lateinamerika: scharfes s', 'cerveza, gracias, zapato'],
        ['b · v', 'gleich: am Anfang wie b, zwischen Vokalen weicher – nie wie deutsches w oder f', 'vaca, beber'],
        ['s', 'scharf wie in „Haus“, nie summend wie in „Rose“', 'casa, rosa'],
        ['ch', 'wie „tsch“', 'chico, noche'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'zapato → „tsa-PA-to“',
      right: 'zapato → „tha-PA-to“ (Spanien) / „sa-PA-to“ (Lateinamerika)',
      why: 'Im Deutschen ist z ein „ts“. Im Spanischen gibt es diesen Laut nicht: `z` (und c vor e/i) klingt in Spanien wie das englische „th“, in Lateinamerika wie ein scharfes s. Genauso verführerisch: `v` wie deutsches w oder f – richtig ist ein weiches b: `vaca` ≈ „BA-ka“.',
    },
    {
      type: 'text',
      md:
        '**Betonung – drei Regeln, die immer gelten:**\n' +
        '- Endet ein Wort auf **Vokal, -n oder -s**, ist die **vorletzte** Silbe betont: `ca-sa`, `gen-te`, `pe-rros`.\n' +
        '- Endet es auf einen **anderen Konsonanten**, ist die **letzte** Silbe betont: `ciu-dad`, `es-pa-ñol`.\n' +
        '- Weicht ein Wort davon ab, zeigt ein **Akzent** (´) die betonte Silbe: `ca-fé`, `ja-món`, `te-lé-fo-no`.\n' +
        'Der Akzent ändert nie den Klang des Vokals – er zeigt nur die Betonung. Manchmal unterscheidet er auch Wörter: `tú` (du) – `tu` (dein), `sí` (ja) – `si` (wenn), `él` (er) – `el` (der).',
    },
    {
      type: 'compare',
      target: 'café',
      german: 'Kaffee',
      md: 'Im Deutschen betonst du meist die erste Silbe: „KAF-fee“. Im Spanischen liegt die Betonung hier auf der letzten Silbe: „ka-FE“ – das verrät dir der Akzent auf dem é.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In **Lateinamerika** klingen `c` (vor e/i), `z` und `s` gleich: `cerveza` ≈ „ser-BE-sa“ (das gilt auch für Teile Andalusiens und die Kanaren). In Argentinien und Uruguay klingen `ll` und `y` wie „sch“: `yo` ≈ „scho“, `playa` ≈ „PLA-scha“. Das `j` ist in vielen Ländern weicher, fast wie ein deutsches h.',
    },
    {
      type: 'tip',
      md: '**Spanisch spricht man, wie man es schreibt.** Wer diese Regeln kennt, kann jedes neue Wort vorlesen – und aus der Aussprache fast immer die Schreibung ableiten.',
    },
    { type: 'audio', text: 'pero, perro, pero, perro', label: 'Hören: einfaches r (pero) und gerolltes rr (perro)' },
  ],
  examples: [
    { target: 'hola', german: 'hallo', note: 'h ist stumm: „O-la“.' },
    { target: 'gente', german: 'Leute', note: 'g vor e klingt wie „ch“ in „Bach“; das End-e ist ein klares e: „CHEN-te“.' },
    { target: 'guitarra', german: 'Gitarre', note: 'gu vor i: das u ist stumm, g hart. rr gerollt: „gi-TA-rra“.' },
    { target: 'llave', german: 'Schlüssel', note: 'll wie „j“, v zwischen Vokalen ganz weich: „JA-be“.' },
    { target: 'niño', german: 'Kind / Junge', note: 'ñ wie „nj“: „NI-njo“.' },
    { target: 'cerveza', german: 'Bier', note: 'Spanien: „ther-BE-tha“ · Lateinamerika: „ser-BE-sa“.' },
    { target: 'teléfono', german: 'Telefon', note: 'Der Akzent zeigt die Betonung: te-LÉ-fo-no.' },
    {
      target: 'Buenas noches, Rosa.',
      german: 'Guten Abend, Rosa.',
      parts: [{ text: 'Buenas', role: 'adjective' }, { text: ' ' }, { text: 'noches', role: 'noun' }, { text: ', ' }, { text: 'Rosa', role: 'noun' }, { text: '.' }],
      note: 'ch = „tsch“; das R am Wortanfang wird gerollt wie rr.',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary', 'reading'],
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort zu – und sprich es dabei leise mit.',
      pairs: [
        { emoji: '🐶', word: 'el perro' },
        { emoji: '🔑', word: 'la llave' },
        { emoji: '🧀', word: 'el queso' },
        { emoji: '🎸', word: 'la guitarra' },
        { emoji: '🍺', word: 'la cerveza' },
      ],
      feedback: {
        rule: 'perro = Hund, llave = Schlüssel, queso = Käse, guitarra = Gitarre, cerveza = Bier.',
        avoid: 'Verknüpfe jedes Wort mit seinem Laut: pe-RR-o, LL-ave, QU-eso, GU-itarra, cer-VE-za.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['pronunciation', 'reading'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 1,
      prompt: 'Wie klingt das j in `jamón`?',
      options: [
        { text: 'wie das deutsche j in „ja“', why: 'Den Laut „j“ wie in „ja“ schreibt man im Spanischen mit ll oder y.' },
        { text: 'wie „ch“ in „Bach“' },
        { text: 'wie das französische j in „Journal“', why: 'So weich klingt der Buchstabe j im Spanischen nie – er ist immer ein rauer Reibelaut.' },
      ],
      answer: 1,
      feedback: {
        rule: '`j` (und g vor e/i) klingt rau wie „ch“ in „Bach“: `jamón` ≈ „cha-MON“.',
        why: 'Das deutsche „j“ entspricht im Spanischen `ll`/`y` – nicht dem Buchstaben j.',
        avoid: 'Denk an „Bach“ und „Jota“: der Buchstabe heißt _jota_ und klingt „CHO-ta“.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 1,
      instruction: 'Hör genau hin: Welches Wort wird gesprochen?',
      options: ['pero', 'perro'],
      answer: 1,
      hint: 'Einfaches `r` = ein einziger kurzer Zungenschlag. `rr` = deutlich gerollt, mehrere Schläge.',
      feedback: {
        rule: '`pero` (aber) hat ein kurzes r, `perro` (Hund) ein gerolltes rr.',
        why: 'Der Unterschied ist bedeutungsentscheidend – wer nicht rollt, sagt „aber“ statt „Hund“.',
        avoid: 'Übe `perro` im Aussprachelabor: Zungenspitze locker hinter die oberen Schneidezähne und flattern lassen.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'matchPairs',
      skills: ['pronunciation', 'reading'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 2,
      instruction: 'Welcher Laut gehört zu welcher Schreibung?',
      pairs: [
        { left: 'h', right: 'stumm' },
        { left: 'j', right: '„ch“ wie in „Bach“' },
        { left: 'ñ', right: '„nj“ wie in „Champagner“' },
        { left: 'll', right: '„j“ wie in „ja“' },
        { left: 'qu (vor e/i)', right: '„k“' },
      ],
      feedback: {
        rule: 'h stumm · j = „ch“ · ñ = „nj“ · ll = „j“ · qu = „k“.',
        why: 'Viele Buchstaben sehen aus wie im Deutschen, klingen aber anders – besonders j und ll werden leicht verwechselt.',
        avoid: 'Merksatz: **J**amón klingt nach Bach, **LL**ave klingt nach „ja“.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'mc',
      skills: ['pronunciation', 'grammar'],
      topicIds: ['es.g.stress'],
      difficulty: 2,
      prompt: 'Welche Silbe ist in `ciudad` (Stadt) betont?',
      options: [
        { text: 'ciu-', why: 'Die vorletzte Silbe wäre nur betont, wenn das Wort auf Vokal, -n oder -s endete.' },
        { text: '-dad' },
      ],
      answer: 1,
      feedback: {
        rule: 'Wörter, die auf einen Konsonanten außer -n/-s enden, werden auf der letzten Silbe betont: ciu-DAD.',
        why: '`ciudad` endet auf -d und hat keinen Akzent – also gilt die Grundregel: letzte Silbe.',
        avoid: 'Schau zuerst auf den letzten Buchstaben, dann auf einen möglichen Akzent.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['es.g.stress'],
      difficulty: 2,
      instruction: 'Welches Wort hörst du?',
      options: ['papa', 'papá'],
      answer: 1,
      hint: 'Achte auf die Betonung: „PA-pa“ oder „pa-PA“?',
      feedback: {
        rule: '`papá` (Papa) wird auf der letzten Silbe betont – deshalb der Akzent. `papa` wird auf der ersten betont (der Papst: _el papa_; in Lateinamerika auch: Kartoffel).',
        why: 'Die Betonung allein unterscheidet hier zwei Wörter.',
        avoid: 'Ein Akzent bedeutet immer: Hier liegt die Betonung.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.stress'],
      difficulty: 2,
      prompt: 'Das Wort wird „te-LE-fo-no“ ausgesprochen (Betonung auf der drittletzten Silbe). Welche Schreibung ist korrekt?',
      options: [
        { text: 'telefono', why: 'Ohne Akzent läge die Betonung auf der vorletzten Silbe: „te-le-FO-no“.' },
        { text: 'teléfono' },
        { text: 'telefóno', why: 'Der Akzent muss auf der Silbe stehen, die betont wird – das ist -lé-, nicht -fó-.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Liegt die Betonung auf der drittletzten Silbe, steht **immer** ein Akzent: te-LÉ-fo-no.',
        why: 'Ohne Akzent würde man das Wort nach der Grundregel auf der vorletzten Silbe betonen.',
        avoid: 'Sprich das Wort langsam in Silben und setz den Akzent genau auf die Silbe mit dem Nachdruck.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 3,
      instruction: 'Schreib das Wort, das du hörst.',
      audio: 'queso',
      answers: ['queso'],
      german: 'Käse',
      feedback: {
        rule: 'Den Laut „k“ vor e und i schreibt man `qu`: `queso`, `quién`. Vor a, o, u schreibt man `c`: `café`.',
        why: '„keso“ oder „ceso“ wären hier falsch: k kommt fast nur in Fremdwörtern vor, und `ce` würde „the“/„se“ klingen.',
        avoid: 'Merke das Paar: ca – que – qui – co – cu.',
      },
    },
  ],
  pronunciation: ['es.p.r.perro', 'es.p.j.gente', 'es.p.stress.telefono'],
  application: [
    {
      id: `${L}.a01`,
      type: 'speakFree',
      skills: ['pronunciation', 'speaking'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 2,
      prompt: 'Lies diese Wörter laut vor: `hola` · `gente` · `perro` · `llave` · `niño` · `queso`',
      keywords: ['hola', 'gente', 'perro', 'llave', 'niño', 'queso'],
      minMatch: 4,
      sample: 'hola, gente, perro, llave, niño, queso',
      feedback: {
        rule: 'h stumm („ola“), g vor e = „ch“ („CHEN-te“), rr gerollt, ll = „j“, ñ = „nj“, qu = „k“.',
        why: 'Wenn die Spracherkennung ein Wort nicht versteht, war meist genau einer dieser Laute unklar – oft das rr oder das j/g.',
        avoid: 'Sprich langsam, Silbe für Silbe, und übertreib das rr am Anfang ruhig.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'situation',
      skills: ['listening', 'reading'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 2,
      scenario: 'Ein Freund aus Buenos Aires sagt „scho“, wenn er `yo` (ich) meint, und „PLA-scha“ für `playa`. Was steckt dahinter?',
      options: [
        { text: 'Er spricht falsch – richtig wäre nur „jo“.', why: 'Es gibt nicht die eine richtige Aussprache: Die argentinische Variante ist korrektes Spanisch.' },
        { text: 'In Argentinien und Uruguay klingen ll und y oft wie „sch“ – das ist dort ganz normal.' },
        { text: 'Er meint ein anderes Wort.', why: 'Es ist dasselbe Wort, nur mit regionaler Aussprache.' },
      ],
      answer: 1,
      feedback: {
        rule: '`ll` und `y` klingen in den meisten Regionen wie „j“ in „ja“, am Río de la Plata (Argentinien, Uruguay) wie „sch“.',
        why: 'Spanisch hat mehrere gleichwertige Aussprachenormen – regionale Unterschiede sind kein Fehler.',
        avoid: 'Bleib bei deiner gewählten Variante, aber rechne beim Hören mit regionalen Klängen.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'freeText',
      skills: ['writing', 'pronunciation'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 2,
      prompt: 'Schreib drei spanische Wörter aus dieser Lektion: eins mit **ñ**, eins mit **rr** und eins mit **ll**.',
      requirements: [
        { pattern: 'ñ', hint: 'Es fehlt ein Wort mit ñ (z. B. niño).' },
        { pattern: 'rr', hint: 'Es fehlt ein Wort mit rr (z. B. perro).' },
        { pattern: 'll', hint: 'Es fehlt ein Wort mit ll (z. B. llave).' },
      ],
      samples: ['niño, perro, llave', 'mañana, guitarra, llave'],
      minWords: 3,
      feedback: {
        rule: 'ñ, rr und ll sind eigene Laute mit eigener Schreibung: niño, perro, llave.',
        avoid: 'Auf dem iPhone bekommst du ñ, indem du das n gedrückt hältst.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'listening',
      skills: ['listening'],
      difficulty: 1,
      audio: 'Buenas tardes.',
      question: 'Was hörst du?',
      options: ['Buenas tardes.', 'Buenas noches.', 'Buenos días.'],
      answer: 0,
      feedback: {
        rule: '`buenas tardes` = guten Tag (nachmittags).',
        why: 'Achte auf das zweite Wort: tardes, noches oder días.',
        avoid: 'Hör auf den Laut „t“ am Anfang von tardes.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'cloze',
      skills: ['writing', 'vocabulary'],
      difficulty: 1,
      instruction: 'Ergänze.',
      sentence: '¡Hasta ___!',
      answers: [['mañana']],
      german: 'Bis morgen!',
      feedback: {
        rule: '„Bis morgen“ = `hasta mañana` – mit ñ.',
        why: '`hasta luego` bedeutet „bis später“.',
        avoid: 'Sprich es aus: ma-NJA-na – das „nj“ ist das ñ.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'mc',
      skills: ['grammar', 'pronunciation'],
      topicIds: ['es.g.stress'],
      difficulty: 2,
      prompt: 'Warum hat `jamón` einen Akzent?',
      options: [
        { text: 'Es endet auf -n und würde daher auf der vorletzten Silbe betont – betont wird aber die letzte.' },
        { text: 'Weil das o lang gesprochen wird.', why: 'Der Akzent zeigt nur die Betonung, nie die Länge oder Farbe eines Vokals.' },
        { text: 'Weil es ein Nomen ist.', why: 'Die Wortart spielt für den Akzent keine Rolle.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Wörter auf Vokal, -n oder -s sind auf der vorletzten Silbe betont. Weicht die Betonung ab, steht ein Akzent: ja-MÓN.',
        why: 'Ohne Akzent würde man „JA-mon“ sagen.',
        avoid: 'Frag dich immer: Worauf endet das Wort – und passt die Betonung zur Grundregel?',
      },
    },
  ],
};

export default lesson;
