import type { Lesson } from '../../types';

const L = 'es.s0.l07';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c3',
  order: 7,
  title: 'Der, die, ein – Artikel',
  subtitle: 'el, la, los, las · un, una, unos, unas',
  icon: '📦',
  minutes: 11,
  goal:
    'Du lernst die **bestimmten** (el, la, los, las) und **unbestimmten** Artikel (un, una, unos, unas) und erkennst an der Endung eines Nomens meist schon, ob es männlich oder weiblich ist.',
  canDo: [
    'Ich kann el, la, los und las richtig verwenden.',
    'Ich kann un, una, unos und unas richtig verwenden.',
    'Ich erkenne an den Endungen -o und -a meist das Genus.',
    'Ich weiß, dass das spanische Genus oft vom deutschen abweicht.',
  ],
  topicIds: ['es.g.articles'],
  vocab: [
    { id: `${L}.v.libro`, target: 'el libro', german: 'das Buch', pos: 'noun', gender: 'm', plural: 'los libros', emoji: '📖', field: 'Alltagsgegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.casa`, target: 'la casa', german: 'das Haus', pos: 'noun', gender: 'f', plural: 'las casas', emoji: '🏠', field: 'Wohnen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.silla`, target: 'la silla', german: 'der Stuhl', pos: 'noun', gender: 'f', plural: 'las sillas', emoji: '🪑', field: 'Wohnen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.gato`, target: 'el gato', german: 'die Katze / der Kater', pos: 'noun', gender: 'm', plural: 'los gatos', emoji: '🐱', field: 'Tiere', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.manzana`, target: 'la manzana', german: 'der Apfel', pos: 'noun', gender: 'f', plural: 'las manzanas', emoji: '🍎', field: 'Essen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.flor`, target: 'la flor', german: 'die Blume', pos: 'noun', gender: 'f', plural: 'las flores', emoji: '🌸', field: 'Natur', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.dia`, target: 'el día', german: 'der Tag', pos: 'noun', gender: 'm', plural: 'los días', emoji: '📅', field: 'Zeit', stageId: 'stage0', lessonId: L, example: { target: 'Buenos días.', german: 'Guten Morgen.' } },
    { id: `${L}.v.mano`, target: 'la mano', german: 'die Hand', pos: 'noun', gender: 'f', plural: 'las manos', emoji: '✋', field: 'Körper', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ciudad`, target: 'la ciudad', german: 'die Stadt', pos: 'noun', gender: 'f', plural: 'las ciudades', emoji: '🏙️', field: 'Orte', stageId: 'stage0', lessonId: L, example: { target: 'Madrid es una ciudad.', german: 'Madrid ist eine Stadt.' } },
    { id: `${L}.v.chico`, target: 'el chico', german: 'der Junge', pos: 'noun', gender: 'm', plural: 'los chicos', emoji: '👦', field: 'Menschen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.chica`, target: 'la chica', german: 'das Mädchen, die junge Frau', pos: 'noun', gender: 'f', plural: 'las chicas', emoji: '👧', field: 'Menschen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.coche`, target: 'el coche', german: 'das Auto', pos: 'noun', gender: 'm', plural: 'los coches', emoji: '🚗', variant: 'es-ES', field: 'Verkehr', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.carro`, target: 'el carro', german: 'das Auto', pos: 'noun', gender: 'm', plural: 'los carros', emoji: '🚗', variant: 'es-LA', field: 'Verkehr', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.por-favor`, target: 'por favor', german: 'bitte', pos: 'phrase', field: 'Höflichkeit', stageId: 'stage0', lessonId: L, example: { target: 'Unas manzanas, por favor.', german: 'Ein paar Äpfel, bitte.' } },
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Artikel',
      headers: ['', 'männlich', 'weiblich'],
      rows: [
        ['bestimmt, Singular (der/die/das)', 'el libro', 'la casa'],
        ['bestimmt, Plural (die)', 'los libros', 'las casas'],
        ['unbestimmt, Singular (ein/eine)', 'un libro', 'una casa'],
        ['unbestimmt, Plural (einige, ein paar)', 'unos libros', 'unas casas'],
      ],
    },
    {
      type: 'text',
      md:
        'Spanisch hat nur **zwei Genera**: männlich und weiblich – kein „das“. Die Endung hilft fast immer:\n' +
        '- **-o** → meist männlich: `el libro`, `el gato`\n' +
        '- **-a** → meist weiblich: `la casa`, `la silla`\n' +
        '- **-dad** und **-ción** → weiblich: `la ciudad`\n' +
        '- andere Endungen (z. B. -e, Konsonant) → mitlernen: `el coche`, `la flor`, `la llave`\n' +
        'Bei Personen zählt das natürliche Geschlecht: `el chico`, `la chica`. Und es gibt Ausnahmen, die du kennen musst: `el día` (männlich trotz -a) und `la mano` (weiblich trotz -o).\n' +
        'Den **Plural** bildest du so: Vokal + **s** (`los libros`), Konsonant + **es** (`las flores`, `las ciudades`).',
    },
    {
      type: 'compare',
      target: 'la chica · la manzana · el gato',
      german: 'das Mädchen · der Apfel · die Katze',
      md: 'Das deutsche Genus hilft dir nicht weiter – es weicht oft ab. Lerne deshalb jedes Nomen **mit** Artikel und verlass dich auf die spanische Endung, nicht auf dein deutsches Gefühl.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Los', role: 'article' }, { text: ' ' }, { text: 'gatos', role: 'noun' }, { text: ' y ' },
        { text: 'las', role: 'article' }, { text: ' ' }, { text: 'flores', role: 'noun' },
      ],
      german: 'Die Katzen und die Blumen',
    },
    {
      type: 'mistake',
      wrong: 'la día',
      right: 'el día',
      why: '`día` endet auf -a, ist aber **männlich** – das kennst du schon aus `buenos días`. Umgekehrt ist `la mano` weiblich, obwohl es auf -o endet. Diese Ausnahmen musst du einfach mitlernen.',
    },
    {
      type: 'text',
      md:
        '**Noch drei Dinge:**\n' +
        '- `de` + `el` wird zu `del`: `la casa del chico` (das Haus des Jungen). Mit la, los, las passiert das nicht.\n' +
        '- Weibliche Wörter mit betontem a- am Anfang bekommen im Singular `el`: `el agua` (das Wasser) – sie bleiben aber weiblich (`las aguas`).\n' +
        '- Bei Berufen fällt `un`/`una` weg: `Soy profesora.` (siehe Lektion 4)',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Auto heißt in **Lateinamerika** meist `el carro` (Mexiko, Kolumbien, Venezuela) oder `el auto` (Argentinien, Chile, Uruguay), in Spanien `el coche`. Beim Computer ändert sich sogar das Genus: Spanien `el ordenador`, Lateinamerika meist `la computadora` (in Chile und Kolumbien auch `el computador`).',
    },
    {
      type: 'tip',
      md: '**Lerne Nomen nie ohne Artikel:** nicht „libro“, sondern „el libro“ – nicht „mano“, sondern „la mano“.',
    },
  ],
  examples: [
    {
      target: 'Un libro y una manzana.',
      german: 'Ein Buch und ein Apfel.',
      parts: [
        { text: 'Un', role: 'article' }, { text: ' ' }, { text: 'libro', role: 'noun' }, { text: ' y ' },
        { text: 'una', role: 'article' }, { text: ' ' }, { text: 'manzana', role: 'noun' }, { text: '.' },
      ],
    },
    {
      target: 'La chica y el chico.',
      german: 'Das Mädchen und der Junge.',
      parts: [
        { text: 'La', role: 'article' }, { text: ' ' }, { text: 'chica', role: 'noun' }, { text: ' y ' },
        { text: 'el', role: 'article' }, { text: ' ' }, { text: 'chico', role: 'noun' }, { text: '.' },
      ],
    },
    { target: 'Los gatos y las flores.', german: 'Die Katzen und die Blumen.' },
    { target: 'Unas manzanas, por favor.', german: 'Ein paar Äpfel, bitte.', note: '`unas` = einige, ein paar.' },
    { target: 'Madrid es una ciudad.', german: 'Madrid ist eine Stadt.' },
    { target: 'Es la casa del chico.', german: 'Das ist das Haus des Jungen.', note: 'de + el = `del`.' },
    { target: '¿Dónde está el coche?', german: 'Wo ist das Auto?', variant: 'es-ES' },
    { target: '¿Dónde está el carro?', german: 'Wo ist das Auto?', variant: 'es-LA' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary', 'reading'],
      topicIds: ['es.g.articles'],
      difficulty: 1,
      instruction: 'Ordne jedem Bild das passende Wort mit Artikel zu.',
      pairs: [
        { emoji: '📖', word: 'el libro' },
        { emoji: '🐱', word: 'el gato' },
        { emoji: '🍎', word: 'la manzana' },
        { emoji: '🪑', word: 'la silla' },
        { emoji: '✋', word: 'la mano' },
      ],
      feedback: {
        rule: 'el libro (Buch), el gato (Katze), la manzana (Apfel), la silla (Stuhl), la mano (Hand).',
        why: 'Achtung: Das Genus weicht oft vom Deutschen ab – der Apfel = la manzana, die Katze = el gato.',
        avoid: 'Sprich jedes Wort immer zusammen mit seinem Artikel.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.articles'],
      difficulty: 1,
      instruction: 'Ergänze den bestimmten Artikel.',
      sentence: '___ libro y ___ casa',
      answers: [['el'], ['la']],
      bank: ['el', 'la', 'los', 'las'],
      german: 'das Buch und das Haus',
      feedback: {
        rule: '-o → meist männlich → `el libro`; -a → meist weiblich → `la casa`.',
        why: '`los`/`las` sind Pluralformen – hier steht jeweils nur ein Ding.',
        avoid: 'Schau auf die Endung des Nomens und auf die Anzahl.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['es.g.articles'],
      difficulty: 2,
      prompt: 'Welcher Artikel passt zu `día` (Tag)?',
      options: [
        { text: 'la', why: '`día` endet zwar auf -a, ist aber eine Ausnahme und männlich.' },
        { text: 'el' },
      ],
      answer: 1,
      feedback: {
        rule: '`el día` ist männlich – eine wichtige Ausnahme zur -a-Regel.',
        why: 'Deshalb heißt es auch `buenos días` (nicht „buenas días“).',
        avoid: 'Eselsbrücke: Buen**os** días → el día.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.articles'],
      difficulty: 2,
      instruction: 'Ergänze den unbestimmten Artikel.',
      sentence: '___ chica y ___ chicos',
      answers: [['una'], ['unos']],
      bank: ['un', 'una', 'unos', 'unas'],
      german: 'ein Mädchen und ein paar Jungen',
      feedback: {
        rule: 'Weiblich Singular → `una`; männlich Plural → `unos` (= ein paar, einige).',
        why: '`un` ist männlich Singular, `unas` weiblich Plural.',
        avoid: 'Zwei Fragen: männlich oder weiblich? Einer oder mehrere?',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.articles'],
      difficulty: 2,
      audio: 'Unas manzanas, por favor.',
      question: 'Was möchte die Person?',
      options: ['einen Apfel', 'ein paar Äpfel', 'die Äpfel'],
      answer: 1,
      feedback: {
        rule: '`unas manzanas` = ein paar Äpfel; `una manzana` = ein Apfel; `las manzanas` = die Äpfel.',
        why: 'Du hast `unas` und das Plural-s von `manzanas` gehört.',
        avoid: 'Achte auf den Anfang (un-/l-) und das Ende (-s) der Wörter.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.articles', 'es.g.estar'],
      difficulty: 2,
      instruction: 'Bilde den Satz.',
      tokens: ['El', 'gato', 'está', 'en', 'la', 'silla.'],
      extra: ['los', 'es'],
      german: 'Die Katze ist auf dem Stuhl.',
      feedback: {
        rule: '`el gato` (männlich), `la silla` (weiblich); Ort → estar.',
        why: '`los` wäre Plural, `es` (ser) passt nicht zu einem Ort.',
        avoid: 'Das deutsche „die Katze / der Stuhl“ ist hier genau umgekehrt – vertrau der spanischen Endung.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.articles'],
      difficulty: 3,
      instruction: 'Im Satz steckt ein Artikelfehler. Korrigiere ihn.',
      sentence: 'El chica está en casa.',
      answers: ['La chica está en casa.'],
      german: 'Das Mädchen ist zu Hause.',
      feedback: {
        rule: '`chica` ist weiblich → `la chica`.',
        why: 'Im Deutschen heißt es „das Mädchen“ – Spanisch hat aber kein Neutrum, und bei Personen zählt das natürliche Geschlecht.',
        avoid: 'Personen: Mann → el, Frau/Mädchen → la.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.articles'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'die Hand und der Tag',
      answers: ['la mano y el día'],
      feedback: {
        rule: 'Zwei Ausnahmen: `la mano` (weiblich trotz -o), `el día` (männlich trotz -a).',
        why: 'Hier führt die Endungsregel in die Irre – diese Wörter musst du mit Artikel lernen.',
        avoid: 'Merksatz: „La mano da los buenos días.“ – Die Hand sagt Guten Morgen.',
      },
    },
  ],
  pronunciation: ['es.p.cz.zapato', 'es.p.ll.calle', 'es.p.stress.arbol'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.articles', 'es.g.estar'],
      difficulty: 2,
      scenario: 'Deine Mitbewohnerin fragt: `¿Dónde está el gato?` Die Katze sitzt auf dem Stuhl. Was antwortest du?',
      options: [
        { text: 'El gato está en la silla.' },
        { text: 'La gato está en el silla.', why: '`gato` ist männlich (el), `silla` weiblich (la) – die Artikel sind vertauscht.' },
        { text: 'El gato es en la silla.', why: 'Für den Ort brauchst du estar, nicht ser.' },
      ],
      answer: 0,
      feedback: {
        rule: '`el gato`, `la silla`; Ort → `está`.',
        why: 'Artikel und Verb müssen beide stimmen.',
        avoid: 'Übernimm den Artikel aus der Frage: el gato → el gato.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.articles'],
      difficulty: 2,
      instruction: 'Du kaufst auf dem Markt ein. Ergänze deine Antwort.',
      lines: [
        { speaker: 'Vendedora', text: 'Buenos días. ¿Qué tal?', german: 'Guten Morgen. Wie geht’s?' },
        { speaker: 'Tú', text: 'Bien, gracias. Unas manzanas, por favor.', german: 'Gut, danke. Ein paar Äpfel, bitte.' },
        { speaker: 'Vendedora', text: 'Muy bien. ¿Algo más?', german: 'Sehr gut. Noch etwas?' },
      ],
      gapIndex: 1,
      options: ['Bien, gracias. Unas manzanas, por favor.', 'Bien, gracias. Unos manzanas, por favor.', 'Bien, gracias. Una manzanas, por favor.'],
      answer: 0,
      feedback: {
        rule: '`manzana` ist weiblich, mehrere → `unas manzanas`.',
        why: '`unos` ist männlich, `una` Singular – beides passt nicht zu „manzanas“.',
        avoid: 'Artikel und Nomen stimmen in Genus **und** Zahl überein: unas manzanas.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.articles'],
      difficulty: 2,
      prompt: 'Schau dich um: Nenne fünf Dinge oder Personen mit dem richtigen Artikel (z. B. `el libro`, `una silla`). Nutze auch mindestens einen unbestimmten oder einen Plural-Artikel.',
      requirements: [
        { pattern: '\\b(el|la)\\b', hint: 'Verwende bestimmte Artikel (el/la).' },
        { pattern: '\\b(un|una|unos|unas|los|las)\\b', hint: 'Verwende auch un/una/unos/unas oder los/las.' },
      ],
      samples: ['el libro, la silla, una manzana, el gato, unas flores', 'la mesa, el teléfono, un libro, las llaves, el café'],
      minWords: 8,
      feedback: {
        rule: 'Jedes Nomen mit passendem Artikel: el/la, un/una, Plural los/las, unos/unas.',
        why: 'Der Artikel richtet sich nach Genus und Zahl des Nomens.',
        avoid: 'Unsicher beim Genus? Schau auf die Endung: -o meist el, -a meist la.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['es.g.articles'],
      difficulty: 2,
      prompt: 'Sag laut, was du siehst – mit Artikel: 📖 🐱 🍎 🪑',
      keywords: ['el libro', 'un libro', 'el gato', 'un gato', 'la manzana', 'una manzana', 'la silla', 'una silla'],
      minMatch: 3,
      sample: 'El libro, el gato, la manzana y la silla.',
      feedback: {
        rule: '📖 el libro · 🐱 el gato · 🍎 la manzana · 🪑 la silla.',
        why: 'Die Spracherkennung hat zu wenige Wörter mit passendem Artikel erkannt.',
        avoid: '`silla` spricht man „SI-ja“ (ll = j), `gato` mit hartem g.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.ser-estar'],
      difficulty: 2,
      prompt: 'Welcher Satz ist korrekt?',
      options: [
        { text: 'Madrid es en España.', why: 'Die Lage eines Ortes beschreibst du mit estar – auch wenn sie sich nie ändert.' },
        { text: 'Madrid está en España.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Lage von Orten, Personen und Dingen → estar.',
        why: '„Dauerhaft“ ist kein Grund für ser: Wo etwas liegt, ist immer estar (Ausnahme: Ereignisse).',
        avoid: 'Frage „Wo?“ → estar.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser', 'es.g.formality'],
      difficulty: 1,
      verb: 'ser',
      tense: 'Präsens',
      person: 'usted',
      sentence: '¿Usted ___ de aquí?',
      answers: ['es'],
      feedback: {
        rule: 'usted → `es` (3. Person Singular, wie él/ella).',
        why: '`eres` gehört zu tú.',
        avoid: 'usted = höflich, aber grammatisch wie „er/sie“.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.pronouns', 'es.g.estar'],
      difficulty: 2,
      audio: '¿Cómo están ustedes?',
      question: 'Wer wird gefragt?',
      options: ['eine Person, die man duzt', 'mehrere Personen', 'eine Person, die man siezt'],
      answer: 1,
      feedback: {
        rule: '`ustedes` + `están` = mehrere Personen. Eine Person: `¿Cómo estás?` (tú) oder `¿Cómo está usted?`',
        why: 'Du hast die Pluralformen `están` und `ustedes` gehört.',
        avoid: 'Achte auf das End-n bei `están` – es zeigt den Plural.',
      },
    },
  ],
};

export default lesson;
