import type { Lesson } from '../../types';

const L = 'es.s0.l03';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c1',
  order: 3,
  title: 'Ich, du, wir – Personalpronomen',
  subtitle: 'yo, tú, usted, él, ella …',
  icon: '🧑‍🤝‍🧑',
  minutes: 10,
  goal:
    'Du lernst alle spanischen **Subjektpronomen** – inklusive der Höflichkeitsformen `usted`/`ustedes` und des spanischen `vosotros` – und erfährst, warum Spanierinnen und Spanier das Pronomen oft einfach weglassen.',
  canDo: [
    'Ich kenne alle Subjektpronomen und ihre Bedeutung.',
    'Ich kann zwischen tú, usted, vosotros und ustedes wählen.',
    'Ich verwende nosotras, vosotras und ellas für rein weibliche Gruppen.',
    'Ich verstehe, warum das Pronomen im Spanischen oft fehlt.',
  ],
  topicIds: ['es.g.pronouns', 'es.g.formality'],
  vocab: [
    { id: `${L}.v.yo`, target: 'yo', german: 'ich', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.tu`, target: 'tú', german: 'du', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.usted`, target: 'usted', german: 'Sie (eine Person, höflich)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.el`, target: 'él', german: 'er', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ella`, target: 'ella', german: 'sie (eine Frau)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.nosotros`, target: 'nosotros', german: 'wir (Männer / gemischte Gruppe)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.nosotras`, target: 'nosotras', german: 'wir (nur Frauen)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.vosotros`, target: 'vosotros', german: 'ihr (Männer / gemischte Gruppe)', pos: 'pron', variant: 'es-ES', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.vosotras`, target: 'vosotras', german: 'ihr (nur Frauen)', pos: 'pron', variant: 'es-ES', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ustedes`, target: 'ustedes', german: 'Sie (mehrere, höflich) · in Lateinamerika auch: ihr', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ellos`, target: 'ellos', german: 'sie (Männer / gemischte Gruppe)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ellas`, target: 'ellas', german: 'sie (nur Frauen)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.y`, target: 'y', german: 'und', pos: 'other', field: 'Bindewörter', stageId: 'stage0', lessonId: L, example: { target: 'Ana y yo', german: 'Ana und ich' } },
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Subjektpronomen',
      headers: ['Person', 'Singular', 'Plural'],
      rows: [
        ['1. Person', 'yo (ich)', 'nosotros / nosotras (wir)'],
        ['2. Person vertraut', 'tú (du)', 'vosotros / vosotras (ihr) – nur Spanien'],
        ['2. Person höflich', 'usted (Sie)', 'ustedes (Sie · in Lateinamerika auch: ihr)'],
        ['3. Person', 'él (er) · ella (sie)', 'ellos / ellas (sie)'],
      ],
    },
    {
      type: 'text',
      md:
        '**-os oder -as?** Die Formen auf -as (`nosotras`, `vosotras`, `ellas`) verwendest du nur für Gruppen, die ausschließlich aus Frauen bestehen. Sobald ein Mann dabei ist, gilt grammatisch die Form auf -os.\n' +
        '**Achte auf den Akzent:** `él` (er) – `el` (der, Artikel); `tú` (du) – `tu` (dein). Gesprochen klingen sie gleich, geschrieben unterscheidet sie das Akzentzeichen.',
    },
    {
      type: 'compare',
      target: 'usted',
      german: 'Sie',
      md: 'Wie das deutsche „Sie“ steht `usted` grammatisch in der **3. Person** – allerdings im **Singular**: Das Verb verhält sich wie bei `él`/`ella`. `ustedes` verhält sich wie `ellos`. (Historisch kommt `usted` von _vuestra merced_, „Euer Gnaden“.)',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In **Spanien** ist `vosotros`/`vosotras` das normale „ihr“ für Freunde, Familie und Kollegen. `ustedes` benutzt du nur als höfliches „Sie“ gegenüber mehreren Personen. (Ausnahme: Auf den Kanaren und in Teilen Andalusiens sagt man auch unter Freunden `ustedes`.)',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In **Lateinamerika** gibt es kein `vosotros`: `ustedes` ist dort das „ihr“ für jede Gruppe – ob Freunde oder Fremde. In Argentinien, Uruguay, Paraguay und Teilen Mittelamerikas hörst du außerdem `vos` statt `tú` (mit eigenen Verbformen, z. B. `vos sos` = du bist). Das lernst du später.',
    },
    {
      type: 'mistake',
      wrong: 'Yo soy Ana. Yo soy de Berlín.',
      right: 'Soy Ana. Soy de Berlín.',
      why: 'Im Deutschen ist das Pronomen Pflicht („ich bin“). Im Spanischen zeigt schon die Verbform, wer gemeint ist: `soy` kann nur „ich bin“ heißen. Ein ständiges `yo` klingt deshalb nachdrücklich, fast wie „**ich** jedenfalls …“. Verwende `yo` nur zur Betonung oder als Kontrast: `Yo soy de Berlín, ¿y tú?`',
    },
    {
      type: 'colored',
      parts: [{ text: '(Yo)', role: 'pronoun' }, { text: ' ' }, { text: 'soy', role: 'verb' }, { text: ' ' }, { text: 'Ana', role: 'noun' }, { text: '.' }],
      german: '(Ich) bin Ana. – Das Pronomen ist freiwillig.',
    },
    {
      type: 'tip',
      md: '**Ein Mann in der Gruppe → -os. Nur Frauen → -as.** Und: Sprich jemanden direkt an? → tú/usted, vosotros/ustedes. Sprichst du **über** jemanden? → él/ella, ellos/ellas.',
    },
  ],
  examples: [
    {
      target: '¿Y tú?',
      german: 'Und du? / Und dir?',
      parts: [{ text: '¿Y ', role: 'question' }, { text: 'tú', role: 'pronoun' }, { text: '?', role: 'question' }],
      note: 'Kennst du aus Lektion 1 – hier siehst du das Pronomen `tú`.',
    },
    { target: '¿Y usted, señora?', german: 'Und Ihnen?', literal: 'Und Sie, Frau?' },
    {
      target: 'Ella es Lucía y él es Marcos.',
      german: 'Das ist Lucía und das ist Marcos.',
      literal: 'Sie ist Lucía und er ist Marcos.',
      parts: [
        { text: 'Ella', role: 'pronoun' }, { text: ' ' }, { text: 'es', role: 'verb' }, { text: ' ' }, { text: 'Lucía', role: 'noun' },
        { text: ' y ' }, { text: 'él', role: 'pronoun' }, { text: ' ' }, { text: 'es', role: 'verb' }, { text: ' ' }, { text: 'Marcos', role: 'noun' }, { text: '.' },
      ],
      note: '`es` = ist – das Verb _ser_ lernst du in der nächsten Lektion.',
    },
    { target: 'Nosotras somos Ana y Marta.', german: 'Wir sind Ana und Marta.', note: 'Nur Frauen → `nosotras`.' },
    {
      target: 'Soy Pablo.',
      german: 'Ich bin Pablo.',
      literal: 'Bin Pablo.',
      parts: [{ text: 'Soy', role: 'verb' }, { text: ' ' }, { text: 'Pablo', role: 'noun' }, { text: '.' }],
      note: 'Ohne `yo` – `soy` zeigt schon, dass „ich“ gemeint ist.',
    },
    { target: 'Vosotros sois de Madrid, ¿no?', german: 'Ihr seid aus Madrid, oder?', variant: 'es-ES' },
    { target: 'Ustedes son de Lima, ¿no?', german: 'Ihr seid aus Lima, oder? / Sie sind aus Lima, oder?', note: 'In Lateinamerika das normale „ihr“, in Spanien das höfliche „Sie“ (Plural).' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['es.g.pronouns'],
      difficulty: 1,
      pairs: [
        { left: 'yo', right: 'ich' },
        { left: 'tú', right: 'du' },
        { left: 'él', right: 'er' },
        { left: 'ella', right: 'sie (eine Frau)' },
        { left: 'nosotros', right: 'wir' },
      ],
      feedback: {
        rule: 'yo = ich · tú = du · él = er · ella = sie · nosotros = wir.',
        why: 'Achte auf den Akzent: `él` (er) ist etwas anderes als `el` (der).',
        avoid: 'Sag die Paare laut: „yo – ich, tú – du …“',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.pronouns'],
      difficulty: 1,
      prompt: 'Du sprichst **über** Ana und Pablo. Welches Pronomen passt?',
      options: [
        { text: 'ellas', why: '`ellas` nur für Gruppen aus ausschließlich Frauen – Pablo ist ein Mann.' },
        { text: 'ellos' },
        { text: 'ustedes', why: '`ustedes` benutzt du, wenn du die Personen **direkt ansprichst**, nicht wenn du über sie sprichst.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Gemischte Gruppe → Form auf -os: `ellos`.',
        why: 'Sobald ein Mann zur Gruppe gehört, verwendet man grammatisch die männliche Form.',
        avoid: 'Frage 1: Spreche ich über sie oder mit ihnen? Frage 2: Nur Frauen oder nicht?',
      },
    },
    {
      id: `${L}.g03`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.pronouns'],
      difficulty: 2,
      audio: '¿Y ellas?',
      question: 'Nach wem wird gefragt?',
      options: ['nach einer Frau', 'nach mehreren Frauen', 'nach einem Mann'],
      answer: 1,
      feedback: {
        rule: '`ella` = sie (eine Frau), `ellas` = sie (mehrere Frauen), `él` = er.',
        why: 'Das hörbare -s am Ende macht den Plural: ella**s**.',
        avoid: 'Achte beim Hören auf das End-s – im Spanischen wird es deutlich gesprochen.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.formality', 'es.g.pronouns'],
      difficulty: 2,
      instruction: 'Du sprichst mit einer älteren Dame, die du nicht kennst. Ergänze das passende Pronomen.',
      sentence: 'Bien, gracias. ¿Y ___, señora?',
      answers: [['usted']],
      bank: ['tú', 'usted', 'ella'],
      german: 'Gut, danke. Und Ihnen?',
      feedback: {
        rule: 'Eine ältere, unbekannte Person sprichst du höflich mit `usted` an.',
        why: '`tú` wäre zu vertraulich, `ella` heißt „sie“ – damit würdest du über eine dritte Person sprechen.',
        avoid: 'Die Anrede `señora`/`señor` ist ein guter Hinweis auf `usted`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.pronouns', 'es.g.formality'],
      difficulty: 2,
      variant: 'es-ES',
      prompt: 'Du bist in Madrid und sprichst zwei Freunde direkt an („ihr“). Welches Pronomen verwendest du?',
      options: [
        { text: 'vosotros' },
        { text: 'ustedes', why: 'In Spanien ist `ustedes` das höfliche „Sie“ – unter Freunden klingt das distanziert.' },
        { text: 'ellos', why: '`ellos` heißt „sie“ – damit sprichst du über die beiden, nicht mit ihnen.' },
      ],
      answer: 0,
      feedback: {
        rule: 'In Spanien: vertrautes „ihr“ = `vosotros` (nur Frauen: `vosotras`).',
        why: '`ustedes` ist in Spanien höflich-distanziert, `ellos` die 3. Person.',
        avoid: 'Denk an die Tabelle: vertraut → vosotros, höflich → ustedes.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.pronouns', 'es.g.formality'],
      difficulty: 2,
      variant: 'es-LA',
      prompt: 'Du bist in Mexiko-Stadt und sprichst zwei Freunde direkt an („ihr“). Welches Pronomen verwendest du?',
      options: [
        { text: 'vosotros', why: '`vosotros` wird in Lateinamerika im Alltag nicht verwendet.' },
        { text: 'ustedes' },
        { text: 'ellos', why: '`ellos` heißt „sie“ – damit sprichst du über die beiden, nicht mit ihnen.' },
      ],
      answer: 1,
      feedback: {
        rule: 'In Lateinamerika ist `ustedes` das „ihr“ für jede Gruppe – vertraut oder höflich.',
        why: '`vosotros` gibt es nur in Spanien, `ellos` ist die 3. Person.',
        avoid: 'Lateinamerika: mehrere Personen ansprechen → immer `ustedes`.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.pronouns'],
      difficulty: 2,
      direction: 'toTarget',
      source: 'Und ihr? (zu Freunden)',
      answers: ['¿Y vosotros?', '¿Y vosotras?', '¿Y ustedes?'],
      feedback: {
        rule: '„ihr“ = `vosotros`/`vosotras` (Spanien) bzw. `ustedes` (Lateinamerika).',
        why: '`ellos` wäre „sie“, `tú` nur eine Person.',
        avoid: 'Frag dich: Wie viele Personen spreche ich an – und in welcher Variante?',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.formality', 'es.g.pronouns'],
      difficulty: 3,
      instruction: 'Die Anrede passt nicht zur Situation. Korrigiere den Satz.',
      sentence: 'Buenas tardes, señor. ¿Y tú?',
      answers: ['Buenas tardes, señor. ¿Y usted?'],
      german: 'Guten Tag. Und Ihnen?',
      feedback: {
        rule: 'Wer jemanden mit `señor`/`señora` anspricht, siezt ihn: `¿Y usted?`',
        why: '`señor` ist eine höfliche Anrede – dazu passt das vertraute `tú` nicht.',
        avoid: 'Anrede und Pronomen müssen zusammenpassen: señor/señora → usted, Vorname unter Freunden → tú.',
      },
    },
  ],
  pronunciation: ['es.p.ll.yo', 'es.p.ll.calle'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.formality', 'es.g.pronouns'],
      difficulty: 2,
      scenario: 'Auf einem Empfang begrüßt du ein älteres Ehepaar, das du nicht kennst. Beide antworten: „Bien, gracias.“ Wie fragst du höflich zurück?',
      options: [
        { text: '¿Y ustedes?' },
        { text: '¿Y vosotros?', why: '`vosotros` ist vertraut – für ein unbekanntes älteres Paar zu locker (und in Lateinamerika unüblich).' },
        { text: '¿Y usted?', why: '`usted` ist Singular – du sprichst aber zwei Personen an.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Mehrere Personen höflich ansprechen → `ustedes` – in Spanien und Lateinamerika.',
        why: '`vosotros` ist vertraut, `usted` gilt nur für eine Person.',
        avoid: 'Zwei Fragen: Wie viele? Wie vertraut? – mehrere + höflich = ustedes.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.pronouns'],
      difficulty: 2,
      variant: 'es-ES',
      instruction: 'Carmen trifft ihre Freundinnen Marta und Lucía in Valencia. Ergänze Carmens Antwort.',
      lines: [
        { speaker: 'Marta', text: '¡Hola, Carmen! ¿Qué tal?', german: 'Hallo Carmen! Wie geht’s?' },
        { speaker: 'Carmen', text: 'Muy bien, gracias. ¿Y vosotras?', german: 'Sehr gut, danke. Und euch?' },
        { speaker: 'Lucía', text: '¡Bien, bien!', german: 'Gut, gut!' },
      ],
      gapIndex: 1,
      options: ['Muy bien, gracias. ¿Y vosotros?', 'Muy bien, gracias. ¿Y vosotras?', 'Muy bien, gracias. ¿Y ellas?'],
      answer: 1,
      feedback: {
        rule: 'Vertrautes „ihr“ an eine Gruppe nur aus Frauen → `vosotras`.',
        why: '`vosotros` gilt für Männer oder gemischte Gruppen; `ellas` heißt „sie“ – Carmen spricht aber direkt mit ihnen.',
        avoid: 'Zuerst: mit ihnen oder über sie? Dann: nur Frauen → -as.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.pronouns'],
      difficulty: 2,
      variant: 'es-LA',
      instruction: 'Carmen trifft ihre Freundinnen Marta und Lucía in Bogotá. Ergänze Carmens Antwort.',
      lines: [
        { speaker: 'Marta', text: '¡Hola, Carmen! ¿Qué tal?', german: 'Hallo Carmen! Wie geht’s?' },
        { speaker: 'Carmen', text: 'Muy bien, gracias. ¿Y ustedes?', german: 'Sehr gut, danke. Und euch?' },
        { speaker: 'Lucía', text: '¡Bien, bien!', german: 'Gut, gut!' },
      ],
      gapIndex: 1,
      options: ['Muy bien, gracias. ¿Y vosotras?', 'Muy bien, gracias. ¿Y ustedes?', 'Muy bien, gracias. ¿Y ellas?'],
      answer: 1,
      feedback: {
        rule: 'In Lateinamerika ist `ustedes` das „ihr“ – auch unter Freundinnen.',
        why: '`vosotras` wird in Lateinamerika nicht verwendet; `ellas` heißt „sie“ – Carmen spricht aber direkt mit ihnen.',
        avoid: 'Lateinamerika: mehrere Personen ansprechen → `ustedes`.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['es.g.pronouns'],
      difficulty: 2,
      prompt: 'Sag laut auf Spanisch, in dieser Reihenfolge: ich – du – er – sie (eine Frau) – wir – sie (gemischte Gruppe).',
      keywords: ['yo', 'tú', 'él', 'ella', 'nosotros', 'ellos'],
      minMatch: 5,
      sample: 'yo, tú, él, ella, nosotros, ellos',
      feedback: {
        rule: 'ich = yo · du = tú · er = él · sie = ella · wir = nosotros · sie (Plural, gemischt) = ellos.',
        why: 'Die Spracherkennung hat nicht genug Pronomen erkannt. Häufige Ursache: `yo` und `ella` mit deutschem „j“ bzw. „l“ gesprochen.',
        avoid: '`ll` und `y` klingen wie „j“ in „ja“: `yo` ≈ „jo“, `ella` ≈ „E-ja“.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.pronouns'],
      difficulty: 1,
      prompt: 'Warum sagt man meist nur `Soy Ana.` statt `Yo soy Ana.`?',
      options: [
        { text: 'Die Verbform soy zeigt schon, dass „ich“ gemeint ist.' },
        { text: 'yo ist unhöflich.', why: '`yo` ist nicht unhöflich – nur oft überflüssig. Zur Betonung ist es richtig.' },
        { text: 'yo gibt es nur in Lateinamerika.', why: '`yo` gibt es überall – und überall kann man es weglassen, wenn die Verbform die Person schon zeigt.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Das Subjektpronomen kann wegfallen, wenn die Verbform die Person eindeutig zeigt.',
        why: 'Anders als im Deutschen trägt die spanische Verbendung die Information „wer“.',
        avoid: 'Setz `yo` nur, wenn du dich betonen oder abgrenzen willst.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.formality'],
      difficulty: 2,
      instruction: 'Es ist 21 Uhr. Du sprichst einen älteren Herrn an. Ergänze.',
      sentence: 'Buenas ___, señor. ¿Y ___?',
      answers: [['noches', 'tardes'], ['usted']],
      german: 'Guten Abend. Und Ihnen?',
      feedback: {
        rule: 'Abends grüßt man mit `buenas noches` (früher Abend: auch `buenas tardes`); einen älteren Herrn siezt man: `usted`.',
        why: '`días` passt nur morgens, `tú` wäre zu vertraulich.',
        avoid: 'Tageszeit bestimmt den Gruß, die Beziehung bestimmt tú oder usted.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['es.g.alphabet-sounds'],
      difficulty: 2,
      instruction: 'Welches Wort hörst du?',
      options: ['caro', 'carro'],
      answer: 0,
      hint: '`caro` (teuer) mit einem kurzen Zungenschlag, `carro` (Karren; in Lateinamerika: Auto) mit gerolltem rr.',
      feedback: {
        rule: 'Einfaches r zwischen Vokalen = ein Schlag; rr = gerollt.',
        why: 'Ein einzelner kurzer Schlag bedeutet `caro`.',
        avoid: 'Übe im Aussprachelabor abwechselnd: caro – carro – caro – carro.',
      },
    },
  ],
};

export default lesson;
