import type { Lesson } from '../../types';

const L = 'es.s0.l05';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c2',
  order: 5,
  title: 'Estar – wo & wie du bist',
  subtitle: 'Ort und Befinden',
  icon: '📍',
  minutes: 11,
  goal:
    'Du lernst das zweite „sein“: **estar**. Damit sagst du, **wo** jemand ist und **wie es** jemandem geht – und fragst mit `¿Cómo estás?` nach dem Befinden.',
  canDo: [
    'Ich kann fragen, wie es jemandem geht, und darauf antworten.',
    'Ich kann sagen, wo ich oder andere gerade sind.',
    'Ich kann alle Präsensformen von estar bilden.',
    'Ich passe Wörter wie cansado/cansada an die Person an.',
  ],
  topicIds: ['es.g.estar'],
  vocab: [
    { id: `${L}.v.estar`, target: 'estar', german: 'sein (Ort, Befinden), sich befinden', pos: 'verb', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Estoy en casa.', german: 'Ich bin zu Hause.' } },
    { id: `${L}.v.como-estas`, target: '¿Cómo estás?', german: 'Wie geht es dir?', pos: 'phrase', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Hola, Ana, ¿cómo estás?', german: 'Hallo Ana, wie geht es dir?' } },
    { id: `${L}.v.como-esta-usted`, target: '¿Cómo está usted?', german: 'Wie geht es Ihnen?', pos: 'phrase', field: 'Befinden', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.donde`, target: '¿dónde?', german: 'wo?', pos: 'other', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: '¿Dónde estás?', german: 'Wo bist du?' } },
    { id: `${L}.v.mal`, target: 'mal', german: 'schlecht', pos: 'adv', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Estoy mal.', german: 'Mir geht es schlecht.' } },
    { id: `${L}.v.regular`, target: 'regular', german: 'so lala, mittelmäßig', pos: 'adv', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Estoy regular.', german: 'Es geht mir so lala.' } },
    { id: `${L}.v.cansado`, target: 'cansado / cansada', german: 'müde', pos: 'adj', gender: 'm/f', emoji: '😴', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Estoy muy cansada.', german: 'Ich bin sehr müde.' } },
    { id: `${L}.v.contento`, target: 'contento / contenta', german: 'froh, zufrieden', pos: 'adj', gender: 'm/f', emoji: '😊', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Pablo está contento.', german: 'Pablo ist froh.' } },
    { id: `${L}.v.enfermo`, target: 'enfermo / enferma', german: 'krank', pos: 'adj', gender: 'm/f', emoji: '🤒', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Lucía está enferma.', german: 'Lucía ist krank.' } },
    { id: `${L}.v.ocupado`, target: 'ocupado / ocupada', german: 'beschäftigt', pos: 'adj', gender: 'm/f', field: 'Befinden', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.en-casa`, target: 'en casa', german: 'zu Hause', pos: 'phrase', emoji: '🏠', field: 'Orte', stageId: 'stage0', lessonId: L, example: { target: 'Estamos en casa.', german: 'Wir sind zu Hause.' } },
    { id: `${L}.v.aqui`, target: 'aquí', german: 'hier', pos: 'adv', field: 'Orte', stageId: 'stage0', lessonId: L, example: { target: 'Estoy aquí.', german: 'Ich bin hier.' } },
    { id: `${L}.v.en-el-trabajo`, target: 'en el trabajo', german: 'bei der Arbeit', pos: 'phrase', emoji: '💼', field: 'Orte', stageId: 'stage0', lessonId: L, example: { target: 'Pablo está en el trabajo.', german: 'Pablo ist bei der Arbeit.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        '`estar` ist das zweite spanische „sein“. Du brauchst es vor allem für zwei Dinge:\n' +
        '- **Ort** – wo jemand oder etwas ist: `Estoy en casa.` (Ich bin zu Hause.)\n' +
        '- **Befinden und Zustand** – wie es jemandem gerade geht: `Estoy cansada.` (Ich bin müde.)\n' +
        'Deshalb fragt man auch mit estar nach dem Befinden: `¿Cómo estás?`',
    },
    {
      type: 'conjugation',
      verb: 'estar',
      translation: 'sein (Ort, Befinden)',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'estoy', ending: 'oy' },
        { person: 'tú', form: 'estás', ending: 'ás' },
        { person: 'él / ella / usted', form: 'está', ending: 'á' },
        { person: 'nosotros / nosotras', form: 'estamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'estáis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'están', ending: 'án' },
      ],
    },
    {
      type: 'colored',
      parts: [{ text: 'Estoy', role: 'verb' }, { text: ' ' }, { text: 'en', role: 'preposition' }, { text: ' ' }, { text: 'casa', role: 'noun' }, { text: '.' }],
      german: 'Ich bin zu Hause.',
    },
    {
      type: 'mistake',
      wrong: 'Soy en casa.',
      right: 'Estoy en casa.',
      why: 'Das deutsche „sein“ verteilt sich auf zwei Verben. Für den **Ort** einer Person oder Sache steht immer `estar` – auch wenn jemand „immer“ dort ist: `Madrid está en España.`',
    },
    {
      type: 'text',
      md:
        '**Anpassen:** Wörter wie `cansado` richten sich nach der Person – Mann: `cansado`, Frau: `cansada`; mehrere: `cansados` / `cansadas` (nur Frauen).\n' +
        '`bien`, `mal` und `regular` bleiben dagegen immer gleich: `Estamos bien.`',
    },
    {
      type: 'compare',
      target: '¿Cómo estás? – Estoy bien.',
      german: 'Wie geht es dir? – Mir geht es gut.',
      md: 'Das Deutsche fragt mit „gehen“ und antwortet mit „mir“. Im Spanischen sagst du einfach „Wie bist du?“ – „Ich bin gut“: `Estoy bien`. Höflich: `¿Cómo está usted?`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In **Lateinamerika** sagst du zu einer Gruppe immer `ustedes están`: `¿Cómo están?` Mit `vos` (Argentinien, Uruguay) heißt es `vos estás` – dieselbe Form wie bei `tú`.',
    },
    {
      type: 'tip',
      md: '**Wo? oder Wie geht’s? → estar.** Und die Formen mit Akzent nicht vergessen: `estás`, `está`, `están` – die Betonung liegt auf der letzten Silbe.',
    },
  ],
  examples: [
    {
      target: '¿Cómo estás?',
      german: 'Wie geht es dir?',
      literal: 'Wie bist du?',
      parts: [{ text: '¿Cómo', role: 'question' }, { text: ' ' }, { text: 'estás', role: 'verb' }, { text: '?', role: 'question' }],
    },
    { target: 'Estoy muy bien, gracias.', german: 'Mir geht es sehr gut, danke.', literal: 'Ich bin sehr gut, danke.' },
    {
      target: '¿Dónde está Pablo?',
      german: 'Wo ist Pablo?',
      parts: [{ text: '¿Dónde', role: 'question' }, { text: ' ' }, { text: 'está', role: 'verb' }, { text: ' ' }, { text: 'Pablo', role: 'subject' }, { text: '?', role: 'question' }],
    },
    { target: 'Pablo está en el trabajo.', german: 'Pablo ist bei der Arbeit.' },
    { target: 'Estamos en Madrid.', german: 'Wir sind in Madrid.' },
    {
      target: 'Laura está cansada.',
      german: 'Laura ist müde.',
      parts: [{ text: 'Laura', role: 'subject' }, { text: ' ' }, { text: 'está', role: 'verb' }, { text: ' ' }, { text: 'cansad', role: 'adjective' }, { text: 'a', role: 'ending' }, { text: '.' }],
      note: 'Laura ist eine Frau → Endung -a.',
    },
    { target: '¿Cómo está usted, señora?', german: 'Wie geht es Ihnen?' },
    { target: '¿Estáis en casa?', german: 'Seid ihr zu Hause?', variant: 'es-ES' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: ['es.g.estar'],
      difficulty: 1,
      instruction: 'Welche Form von estar gehört zu welchem Pronomen?',
      pairs: [
        { left: 'yo', right: 'estoy' },
        { left: 'tú', right: 'estás' },
        { left: 'usted', right: 'está' },
        { left: 'nosotros', right: 'estamos' },
        { left: 'ellas', right: 'están' },
      ],
      feedback: {
        rule: 'yo estoy · tú estás · él/ella/usted está · nosotros estamos · vosotros estáis · ellos/ellas/ustedes están.',
        why: '`usted` wird wie él/ella konjugiert: `usted está`.',
        avoid: 'Nur `estoy` fällt aus der Reihe – alle anderen Formen folgen dem Muster est- + -ás/-á/-amos/-áis/-án.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.estar'],
      difficulty: 1,
      verb: 'estar',
      tense: 'Präsens',
      person: 'yo',
      sentence: '___ en casa.',
      answers: ['estoy', 'Estoy'],
      feedback: {
        rule: 'yo → `estoy`.',
        why: 'Die yo-Form endet auf -oy, genau wie `soy`.',
        avoid: 'Merkpaar: soy – estoy.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.estar'],
      difficulty: 1,
      audio: 'Hola. Estoy muy cansada.',
      question: 'Wie geht es der Sprecherin?',
      options: ['Sie ist müde.', 'Sie ist froh.', 'Sie ist krank.'],
      answer: 0,
      feedback: {
        rule: '`cansada` = müde (Frau). Froh wäre `contenta`, krank `enferma`.',
        why: 'Du hast `cansada` gehört.',
        avoid: 'Lerne die Befindlichkeiten als Gruppe: cansado, contento, enfermo – jeweils mit -a für Frauen.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      instruction: 'Ergänze die Formen von estar.',
      sentence: '¿Dónde ___ Pablo? – ___ en el trabajo.',
      answers: [['está'], ['está']],
      bank: ['está', 'estás', 'es', 'están'],
      german: 'Wo ist Pablo? – Er ist bei der Arbeit.',
      feedback: {
        rule: 'Ort → estar; Pablo (er) → `está`.',
        why: '`es` (ser) passt nicht zum Ort, `estás` ist die du-Form, `están` Plural.',
        avoid: 'Frage „wo?“ → Antwort mit estar.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      prompt: 'Lucía ist müde. Welcher Satz ist korrekt?',
      options: [
        { text: 'Lucía está cansado.', why: '`cansado` ist die männliche Form – Lucía ist eine Frau.' },
        { text: 'Lucía está cansada.' },
        { text: 'Lucía es cansada.', why: 'Müdigkeit ist ein Zustand → estar. `ser cansado` bedeutet eher „ermüdend, anstrengend“.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Befinden → estar; Frau → Endung -a: `Lucía está cansada.`',
        why: 'Verb (estar) und Endung (-a) müssen beide stimmen.',
        avoid: 'Erst das Verb wählen (Zustand = estar), dann die Endung an die Person anpassen.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      variant: 'es-ES',
      verb: 'estar',
      tense: 'Präsens',
      person: 'vosotros',
      sentence: '¿___ en casa?',
      answers: ['estáis'],
      feedback: {
        rule: 'vosotros/vosotras → `estáis` (mit Akzent auf dem á).',
        why: '`están` gehört zu ellos/ustedes.',
        avoid: 'vosotros-Formen enden auf -is: sois, estáis.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      variant: 'es-LA',
      verb: 'estar',
      tense: 'Präsens',
      person: 'ustedes',
      sentence: '¿Ustedes ___ en casa?',
      answers: ['están'],
      feedback: {
        rule: 'ustedes → `están` (wie ellos/ellas).',
        why: '`ustedes` ist grammatisch 3. Person Plural.',
        avoid: 'usted = está, ustedes = están.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.estar'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Wir sind müde.',
      answers: ['Estamos cansados.', 'Estamos cansadas.', 'Nosotros estamos cansados.', 'Nosotras estamos cansadas.'],
      feedback: {
        rule: 'Zustand → estar: `estamos`; mehrere → `cansados` (nur Frauen: `cansadas`).',
        why: '`somos` (ser) passt nicht zu einem Zustand, und das Adjektiv braucht die Pluralendung -s.',
        avoid: 'Bei mehreren Personen hängt auch am Adjektiv ein -s.',
      },
    },
    {
      id: `${L}.g09`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.estar', 'es.g.ser-estar'],
      difficulty: 3,
      instruction: 'Korrigiere den Satz.',
      sentence: 'Soy en Berlín.',
      answers: ['Estoy en Berlín.', 'Yo estoy en Berlín.'],
      german: 'Ich bin in Berlin.',
      feedback: {
        rule: 'Ort einer Person → estar: `Estoy en Berlín.`',
        why: '`soy` (ser) beschreibt, wer oder was du bist – nicht, wo du bist.',
        avoid: 'Frag dich: Geht es um „wo“? Dann estar.',
      },
    },
  ],
  pronunciation: ['es.p.stress.hablo-pasado', 'es.p.into.que-bien'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      instruction: 'Carlos und Marta sind Freunde. Ergänze Martas Antwort.',
      lines: [
        { speaker: 'Carlos', text: '¡Hola, Marta! ¿Cómo estás?', german: 'Hallo Marta! Wie geht es dir?' },
        { speaker: 'Marta', text: 'Estoy bien, gracias. ¿Y tú?', german: 'Mir geht es gut, danke. Und dir?' },
        { speaker: 'Carlos', text: 'Regular. Estoy muy cansado.', german: 'So lala. Ich bin sehr müde.' },
      ],
      gapIndex: 1,
      options: ['Estoy bien, gracias. ¿Y tú?', 'Soy bien, gracias. ¿Y tú?', 'Estoy bien, gracias. ¿Y usted?'],
      answer: 0,
      feedback: {
        rule: 'Befinden → `Estoy bien`. Unter Freunden fragt man mit `¿Y tú?` zurück.',
        why: '`Soy bien` ist falsch (Befinden = estar), `¿Y usted?` passt nicht zu Freunden.',
        avoid: 'Auf `¿Cómo estás?` antwortest du immer mit `estoy`.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      scenario: 'Eine Freundin ruft an und fragt: `¿Dónde estás?` Du bist gerade zu Hause. Was antwortest du?',
      options: [
        { text: 'Soy en casa.', why: 'Für den Ort brauchst du estar, nicht ser.' },
        { text: 'Estoy en casa.' },
        { text: 'Estás en casa.', why: '`estás` heißt „du bist“ – du sprichst aber über dich.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Ort → estar; über dich selbst → `estoy`.',
        why: 'Die Frage `¿Dónde estás?` enthält schon das richtige Verb – du musst nur die Person wechseln.',
        avoid: 'Frage mit `estás` → Antwort mit `estoy`.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      prompt: 'Antworte laut auf `¿Cómo estás?` und sag auch, wo du gerade bist.',
      keywords: ['estoy', 'bien', 'mal', 'regular', 'cansado', 'cansada', 'contento', 'contenta', 'en casa', 'aquí', 'en el trabajo'],
      minMatch: 2,
      sample: 'Estoy bien, gracias. Estoy en casa.',
      feedback: {
        rule: 'Befinden und Ort mit `estoy`: `Estoy bien. Estoy en casa.`',
        why: 'Die Spracherkennung hat zu wenige passende Wörter gefunden.',
        avoid: 'Betonung auf der letzten Silbe: es-TOY – kein Akzent nötig, weil das Wort auf -y endet.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.estar'],
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Frag mit `¿Cómo estás?` nach dem Befinden, antworte selbst mit estar und sag, wo du gerade bist.',
      turns: 4,
      feedback: {
        rule: 'Befinden: `Estoy bien / cansado / contenta …` · Ort: `Estoy en casa / aquí / en el trabajo`.',
        avoid: 'Denk an die Endung: Frau → cansada, contenta.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      verb: 'ser',
      tense: 'Präsens',
      person: 'nosotros',
      sentence: '___ de Alemania.',
      answers: ['somos', 'Somos'],
      feedback: {
        rule: 'Herkunft → ser; nosotros → `somos`.',
        why: '`estamos` (estar) beschreibt Ort oder Befinden, nicht die Herkunft.',
        avoid: 'Herkunft mit `de` → immer ser.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      audio: '¿De dónde eres?',
      question: 'Was wirst du gefragt?',
      options: ['wie es dir geht', 'woher du kommst', 'wo du gerade bist'],
      answer: 1,
      feedback: {
        rule: '`¿De dónde eres?` = Woher kommst du? · `¿Cómo estás?` = Wie geht es dir? · `¿Dónde estás?` = Wo bist du?',
        why: '`de dónde` + ser fragt nach der Herkunft.',
        avoid: 'Hör auf das Verb: eres (ser) → Herkunft; estás (estar) → Ort/Befinden.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      instruction: 'Ergänze die Formen von ser.',
      sentence: 'Ella ___ médica y ___ de Colombia.',
      answers: [['es'], ['es']],
      german: 'Sie ist Ärztin und kommt aus Kolumbien.',
      feedback: {
        rule: 'Beruf und Herkunft → ser; ella → `es`.',
        why: '`está` wäre estar – das passt weder zum Beruf noch zur Herkunft.',
        avoid: 'Wer? Was? Woher? → ser.',
      },
    },
  ],
};

export default lesson;
