import type { Lesson } from '../../types';

const L = 'es.s0.l09';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c3',
  order: 9,
  title: 'Satzstellung & Verneinung',
  subtitle: 'Wer tut was – und wie man „nicht“ sagt',
  icon: '🧩',
  minutes: 10,
  goal:
    'Du baust einfache spanische Sätze in der richtigen Reihenfolge, stellst Adjektive hinter das Nomen und verneinst mit **no** direkt vor dem Verb.',
  canDo: [
    'Ich kann einfache Sätze nach dem Muster Subjekt – Verb – Ergänzung bilden.',
    'Ich weiß, dass Adjektive meist hinter dem Nomen stehen.',
    'Ich kann Sätze mit no verneinen.',
    'Ich verstehe Sätze mit doppelter Verneinung wie „No entiendo nada“.',
  ],
  topicIds: ['es.g.word-order-negation', 'es.g.adjectives'],
  vocab: [
    { id: `${L}.v.no`, target: 'no', german: 'nein; nicht, kein', pos: 'adv', field: 'Verneinung', stageId: 'stage0', lessonId: L, example: { target: 'No, no soy de Madrid.', german: 'Nein, ich bin nicht aus Madrid.' } },
    { id: `${L}.v.nada`, target: 'nada', german: 'nichts', pos: 'pron', field: 'Verneinung', stageId: 'stage0', lessonId: L, example: { target: 'No entiendo nada.', german: 'Ich verstehe nichts.' } },
    { id: `${L}.v.nunca`, target: 'nunca', german: 'nie, niemals', pos: 'adv', field: 'Verneinung', stageId: 'stage0', lessonId: L, example: { target: 'Nunca estoy en casa.', german: 'Ich bin nie zu Hause.' } },
    { id: `${L}.v.tambien`, target: 'también', german: 'auch', pos: 'adv', field: 'Verneinung', stageId: 'stage0', lessonId: L, example: { target: 'Yo también soy de Berlín.', german: 'Ich bin auch aus Berlin.' } },
    { id: `${L}.v.tampoco`, target: 'tampoco', german: 'auch nicht', pos: 'adv', field: 'Verneinung', stageId: 'stage0', lessonId: L, example: { target: 'Yo tampoco.', german: 'Ich auch nicht.' } },
    { id: `${L}.v.muy`, target: 'muy', german: 'sehr', pos: 'adv', field: 'Eigenschaften', stageId: 'stage0', lessonId: L, example: { target: 'Ana es muy simpática.', german: 'Ana ist sehr nett.' } },
    { id: `${L}.v.hoy`, target: 'hoy', german: 'heute', pos: 'adv', emoji: '📅', field: 'Zeit', stageId: 'stage0', lessonId: L, example: { target: 'Hoy estoy en casa.', german: 'Heute bin ich zu Hause.' } },
    { id: `${L}.v.perro`, target: 'el perro', german: 'der Hund', pos: 'noun', gender: 'm', plural: 'los perros', emoji: '🐶', field: 'Tiere', stageId: 'stage0', lessonId: L, example: { target: 'El perro no es grande.', german: 'Der Hund ist nicht groß.' } },
    { id: `${L}.v.gato`, target: 'el gato', german: 'die Katze, der Kater', pos: 'noun', gender: 'm', plural: 'los gatos', emoji: '🐱', field: 'Tiere', stageId: 'stage0', lessonId: L, example: { target: 'Es un gato pequeño.', german: 'Das ist eine kleine Katze.' } },
    { id: `${L}.v.cafe`, target: 'el café', german: 'der Kaffee; das Café', pos: 'noun', gender: 'm', plural: 'los cafés', emoji: '☕', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L, example: { target: 'El café no es muy grande.', german: 'Der Kaffee ist nicht sehr groß.' } },
    { id: `${L}.v.simpatico`, target: 'simpático, simpática', german: 'nett, sympathisch', pos: 'adj', field: 'Eigenschaften', stageId: 'stage0', lessonId: L, example: { target: 'un perro muy simpático', german: 'ein sehr netter Hund' } },
    { id: `${L}.v.no-entiendo`, target: 'No entiendo.', german: 'Ich verstehe (das) nicht.', pos: 'phrase', field: 'Verständigung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.no-se`, target: 'No sé.', german: 'Ich weiß (es) nicht.', pos: 'phrase', field: 'Verständigung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.hablo`, target: 'Hablo alemán.', german: 'Ich spreche Deutsch.', pos: 'phrase', field: 'Verständigung', stageId: 'stage0', lessonId: L, example: { target: 'No hablo inglés.', german: 'Ich spreche kein Englisch.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Der spanische Aussagesatz folgt meist dem Muster **Subjekt – Verb – Ergänzung** – wie ein einfacher deutscher Hauptsatz: `Ana es simpática.` Zwei Unterschiede solltest du kennen:\n' +
        '- Das Subjektpronomen fällt meist weg, weil die Verbform die Person schon zeigt: `Soy de Berlín.` statt `Yo soy de Berlín.`\n' +
        '- Es gibt keine Regel „Verb an zweiter Stelle“. Beginnt der Satz mit einer Zeitangabe, bleibt der Rest unverändert: `Hoy Ana está en casa.` (Heute _ist Ana_ zu Hause.)',
    },
    {
      type: 'colored',
      parts: [
        { text: 'El perro', role: 'subject' },
        { text: ' ' },
        { text: 'no', role: 'negation' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'grande', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Der Hund ist nicht groß.',
    },
    {
      type: 'text',
      md:
        'Adjektive stehen im Spanischen normalerweise **hinter** dem Nomen: `un perro simpático`, `un gato pequeño`, `las flores rojas`. Davor stehen dagegen Zahlen und Mengenwörter: `dos gatos`, `mucho café`. Einige häufige Adjektive können auch vorne stehen – das lernst du später Schritt für Schritt.',
    },
    {
      type: 'compare',
      target: 'No hablo inglés.',
      german: 'Ich spreche kein Englisch.',
      md:
        'Deutsch hat zwei Verneinungen („nicht“ und „kein“) und schiebt „nicht“ oft weit nach hinten. Spanisch hat für beides nur **`no`** – und das steht immer direkt **vor dem Verb**. Auf eine Frage antwortet man deshalb oft mit doppeltem no: `¿Eres de Madrid? – No, no soy de Madrid.` Das erste `no` heißt „nein“, das zweite „nicht“.',
    },
    {
      type: 'mistake',
      wrong: 'Estoy no cansado.',
      right: 'No estoy cansado.',
      why: 'Im Deutschen steht „nicht“ hinter dem Verb („Ich bin nicht müde“). Im Spanischen muss `no` **vor** das konjugierte Verb – nie dahinter und nie ans Satzende.',
    },
    {
      type: 'table',
      title: 'Doppelte Verneinung (Ausblick)',
      headers: ['Spanisch', 'Deutsch', 'Muster'],
      rows: [
        ['No entiendo nada.', 'Ich verstehe nichts.', 'no + Verb + nada'],
        ['No estoy nunca en casa.', 'Ich bin nie zu Hause.', 'no + Verb + nunca'],
        ['Nunca estoy en casa.', 'Ich bin nie zu Hause.', 'nunca vor dem Verb → kein no'],
        ['– No hablo inglés. – Yo tampoco.', '– Ich spreche kein Englisch. – Ich auch nicht.', 'tampoco = auch nicht'],
      ],
    },
    {
      type: 'tip',
      md:
        'Merksatz: **`no` klebt vor dem Verb.** Steht `nada` oder `nunca` _hinter_ dem Verb, braucht der Satz zusätzlich `no`. Zwei Verneinungen heben sich im Spanischen nicht auf – sie verstärken sich.',
    },
    { type: 'audio', text: '¿Eres de Madrid? No, no soy de Madrid.', label: 'Doppeltes no: „Nein, ich bin nicht …“' },
  ],
  examples: [
    {
      target: 'Ana es muy simpática.',
      german: 'Ana ist sehr nett.',
      parts: [
        { text: 'Ana', role: 'subject' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'muy', role: 'adverb' },
        { text: ' ' },
        { text: 'simpática', role: 'adjective' },
        { text: '.' },
      ],
    },
    {
      target: 'El perro no es grande.',
      german: 'Der Hund ist nicht groß.',
      parts: [
        { text: 'El perro', role: 'subject' },
        { text: ' ' },
        { text: 'no', role: 'negation' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'grande', role: 'adjective' },
        { text: '.' },
      ],
    },
    { target: 'No entiendo.', german: 'Ich verstehe (das) nicht.', note: 'Einer der nützlichsten Sätze überhaupt – gern kombiniert mit `¿Más despacio, por favor?` (Langsamer, bitte?).' },
    {
      target: 'Es un gato pequeño.',
      german: 'Das ist eine kleine Katze.',
      parts: [
        { text: 'Es', role: 'verb' },
        { text: ' ' },
        { text: 'un', role: 'article' },
        { text: ' ' },
        { text: 'gato', role: 'noun' },
        { text: ' ' },
        { text: 'pequeño', role: 'adjective' },
        { text: '.' },
      ],
      note: '`el gato` ist maskulin (eine Katze ausdrücklich weiblich: `la gata`). Das Adjektiv steht hinter dem Nomen.',
    },
    { target: 'No entiendo nada.', german: 'Ich verstehe gar nichts.', literal: 'Nicht verstehe-ich nichts.' },
    { target: 'Nunca estoy en casa.', german: 'Ich bin nie zu Hause.', note: 'Gleichbedeutend: `No estoy nunca en casa.`' },
    { target: 'No hablo inglés. – Yo tampoco.', german: 'Ich spreche kein Englisch. – Ich auch nicht.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 1,
      prompt: 'Welcher Satz bedeutet „Ich bin nicht müde“?',
      options: [
        { text: 'No estoy cansado.' },
        { text: 'Estoy no cansado.', why: '`no` steht nie hinter dem Verb, sondern direkt davor.' },
        { text: 'Estoy cansado no.', why: 'Ein „nicht“ am Satzende wie im Deutschen gibt es im Spanischen nicht.' },
      ],
      answer: 0,
      feedback: {
        rule: '`no` steht direkt vor dem konjugierten Verb: `No estoy cansado.`',
        why: 'Die falschen Varianten übertragen die deutsche Stellung von „nicht“ ins Spanische.',
        avoid: 'Merksatz: `no` klebt vor dem Verb.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'matchPairs',
      skills: ['vocabulary'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 1,
      instruction: 'Ordne die Wörter ihrer Bedeutung zu.',
      pairs: [
        { left: 'no', right: 'nicht / nein' },
        { left: 'nada', right: 'nichts' },
        { left: 'nunca', right: 'nie' },
        { left: 'también', right: 'auch' },
        { left: 'tampoco', right: 'auch nicht' },
      ],
      feedback: {
        rule: '`también` bestätigt eine positive Aussage (auch), `tampoco` eine verneinte (auch nicht).',
        why: 'Leicht verwechselt: `también` und `tampoco`. `tampoco` enthält „poco“ – es ist die verneinte Form.',
        avoid: 'Lerne die Reaktionen als Paar: `Yo también.` (Ich auch.) – `Yo tampoco.` (Ich auch nicht.)',
      },
    },
    {
      id: `${L}.g03`,
      type: 'order',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 1,
      tokens: ['El', 'perro', 'no', 'es', 'grande.'],
      extra: ['nada'],
      german: 'Der Hund ist nicht groß.',
      feedback: {
        rule: 'Subjekt – `no` – Verb – Ergänzung: `El perro no es grande.`',
        why: '`nada` bedeutet „nichts“ und passt hier nicht. Und `no` gehört vor `es`, nicht dahinter.',
        avoid: 'Zuerst das Subjekt, dann `no` direkt vor das Verb setzen.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 2,
      sentence: '___ entiendo ___.',
      answers: [['no'], ['nada']],
      bank: ['no', 'nada', 'nunca', 'tampoco'],
      german: 'Ich verstehe nichts.',
      feedback: {
        rule: 'Steht `nada` hinter dem Verb, braucht der Satz zusätzlich `no` davor: `No entiendo nada.`',
        why: '`Entiendo nada` ohne `no` ist im Spanischen falsch – die doppelte Verneinung ist hier Pflicht.',
        avoid: 'Denke: `no` + Verb + `nada` gehören zusammen wie ein Rahmen.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 2,
      audio: 'Nunca estoy en casa.',
      question: 'Was bedeutet der Satz?',
      options: ['Ich bin immer zu Hause.', 'Ich bin nie zu Hause.', 'Ich bin heute nicht zu Hause.'],
      answer: 1,
      feedback: {
        rule: '`nunca` = nie. Steht es vor dem Verb, braucht der Satz kein zusätzliches `no`.',
        why: '„Heute nicht“ wäre `Hoy no estoy en casa.` – „immer“ heißt `siempre`.',
        avoid: 'Achte auf das erste Wort: `nunca` am Satzanfang verneint den ganzen Satz.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 2,
      audio: 'No soy de Madrid.',
      answers: ['No soy de Madrid.'],
      german: 'Ich bin nicht aus Madrid.',
      feedback: {
        rule: 'Verneinung mit `no` vor dem Verb: `No soy de Madrid.`',
        why: 'Das kurze `no` am Anfang geht beim Hören leicht unter – ohne es kehrt sich die Bedeutung um.',
        avoid: 'Hör dir den Satzanfang zweimal an: Beginnt er mit `no`?',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 3,
      sentence: 'Soy no de Alemania, soy de Austria.',
      answers: ['No soy de Alemania, soy de Austria.'],
      german: 'Ich bin nicht aus Deutschland, ich bin aus Österreich.',
      feedback: {
        rule: '`no` gehört vor das Verb: `No soy de Alemania.`',
        why: '„Ich bin nicht aus …“ verleitet dazu, `no` hinter `soy` zu stellen – im Spanischen ist das falsch.',
        avoid: 'Prüfe bei jedem verneinten Satz: Steht `no` unmittelbar vor dem Verb?',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.word-order-negation', 'es.g.adjectives'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Die Katze ist nicht klein.',
      answers: ['El gato no es pequeño.', 'La gata no es pequeña.'],
      feedback: {
        rule: 'Subjekt + `no` + `es` + Adjektiv mit passender Endung: `El gato no es pequeño.`',
        why: '_Die_ Katze ist im Deutschen feminin, `el gato` aber maskulin – daher `pequeño`. Größe ist eine Eigenschaft, also `es`, nicht `está`.',
        avoid: 'Nie das deutsche Genus übernehmen: erst den spanischen Artikel klären, dann die Adjektivendung anpassen.',
      },
    },
  ],
  pronunciation: ['es.p.r.perro', 'es.p.stress.cafe'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 2,
      lines: [
        { speaker: 'Lucía', text: '¿Eres de Madrid?', german: 'Bist du aus Madrid?' },
        { speaker: 'Du', text: 'No, no soy de Madrid. Soy de Berlín.', german: 'Nein, ich bin nicht aus Madrid. Ich bin aus Berlin.' },
        { speaker: 'Lucía', text: '¡Ah, de Alemania! Yo tampoco soy de Madrid, soy de Sevilla.', german: 'Ah, aus Deutschland! Ich bin auch nicht aus Madrid, ich bin aus Sevilla.' },
      ],
      gapIndex: 1,
      options: ['No, no soy de Madrid. Soy de Berlín.', 'No, soy no de Madrid. Soy de Berlín.', 'Sí, no soy de Madrid. Soy de Berlín.'],
      answer: 0,
      feedback: {
        rule: 'Antwort auf eine Ja/Nein-Frage: `No` (nein) + `no` vor dem Verb (nicht): `No, no soy de Madrid.`',
        why: '`soy no` hat die falsche Stellung, und `Sí, no soy …` widerspricht sich selbst.',
        avoid: 'Das doppelte „No, no …“ klingt für Deutsche ungewohnt, ist aber völlig normal.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 2,
      prompt: 'Jemand fragt dich: `¿Eres de Londres?` Widersprich laut in zwei Sätzen: Sag, dass du nicht aus London bist, und woher du wirklich kommst.',
      keywords: ['no', 'soy', 'de'],
      minMatch: 3,
      sample: 'No, no soy de Londres. Soy de Múnich.',
      feedback: {
        rule: '`No, no soy de …` – erst „nein“, dann die Verneinung vor dem Verb.',
        why: 'Wenn die Erkennung nur ein `no` findet, hast du das zweite vielleicht verschluckt. Beide sind wichtig.',
        avoid: 'Sprich das doppelte no mit kleiner Pause: „No, … no soy de Londres.“',
      },
    },
    {
      id: `${L}.a03`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 3,
      prompt: 'Schreibe drei verneinte Sätze über dich. Verwende in einem Satz `nada`, `nunca` oder `tampoco`.',
      requirements: [
        { pattern: '\\bno\\b', hint: 'Verneine mindestens einmal mit no vor dem Verb.' },
        { pattern: '\\b(nada|nunca|tampoco)\\b', hint: 'Baue nada, nunca oder tampoco ein.' },
      ],
      samples: ['No soy de Madrid. No estoy cansada. Nunca estoy en casa.', 'No hablo inglés. No entiendo nada. Yo tampoco soy de España.'],
      minWords: 8,
      feedback: {
        rule: '`no` steht vor dem Verb; `nada`/`nunca` hinter dem Verb brauchen zusätzlich `no`.',
        why: 'Typisch sind `Estoy no …` (falsche Stellung) und `Entiendo nada` (fehlendes no).',
        avoid: 'Lies jeden Satz noch einmal und suche das Verb: Direkt davor muss `no` stehen.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.gender-plural', 'es.g.adjectives'],
      difficulty: 2,
      instruction: 'Setze den Plural von „la flor“ und die passende Form von „rojo“ ein.',
      sentence: 'Las ___ son ___.',
      answers: [['flores'], ['rojas']],
      german: 'Die Blumen sind rot.',
      feedback: {
        rule: 'Konsonant → + es: `flores`. Das Adjektiv folgt dem Nomen (f. Pl.): `rojas`.',
        why: '`flors` fehlt das -e-; `rojos` wäre maskulin, `flor` ist aber feminin.',
        avoid: 'Erst den Plural des Nomens bilden, dann die Endung des Adjektivs angleichen.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.ser-estar'],
      difficulty: 1,
      prompt: '„Ich bin zu Hause.“ – Welches Verb passt? `Yo ___ en casa.`',
      options: [
        { text: 'soy', why: '`ser` beschreibt, wer oder was jemand ist – nicht, wo er sich befindet.' },
        { text: 'estoy' },
      ],
      answer: 1,
      feedback: {
        rule: 'Aufenthaltsort → `estar`: `Estoy en casa.`',
        why: '`soy` steht für Identität, Herkunft und Eigenschaften, nicht für den Ort.',
        avoid: 'Frage „Wo?“ → estar.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.estar'],
      difficulty: 1,
      verb: 'estar',
      tense: 'Präsens',
      person: 'tú',
      answers: ['estás'],
      sentence: '¿Tú ___ en casa?',
      feedback: {
        rule: '`estar`: estoy, **estás**, está, estamos, estáis, están.',
        why: 'Ohne Akzent (`estas`) bedeutet es „diese“ – die Verbform wird auf der letzten Silbe betont.',
        avoid: 'Alle Formen von estar außer estoy und estamos tragen einen Akzent.',
      },
    },
  ],
};

export default lesson;
