import type { Lesson } from '../../types';

const L = 'es.s0.l04';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c2',
  order: 4,
  title: 'Ser – wer du bist',
  subtitle: 'Name, Herkunft & Beruf',
  icon: '🪪',
  minutes: 12,
  goal:
    'Du lernst das Verb **ser** (sein) in allen Personen und kannst sagen, **wer** du bist, **woher** du kommst und **was** du beruflich machst – und andere danach fragen.',
  canDo: [
    'Ich kann mich mit Namen vorstellen.',
    'Ich kann sagen, woher ich komme, und andere danach fragen.',
    'Ich kann meinen Beruf nennen.',
    'Ich kann alle Präsensformen von ser bilden.',
  ],
  topicIds: ['es.g.ser'],
  vocab: [
    { id: `${L}.v.ser`, target: 'ser', german: 'sein (Identität, Herkunft, Beruf)', pos: 'verb', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Soy Laura.', german: 'Ich bin Laura.' } },
    { id: `${L}.v.de`, target: 'de', german: 'aus, von', pos: 'prep', field: 'Herkunft', stageId: 'stage0', lessonId: L, example: { target: 'Soy de Hamburgo.', german: 'Ich komme aus Hamburg.' } },
    { id: `${L}.v.de-donde`, target: '¿de dónde?', german: 'woher?', pos: 'phrase', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: '¿De dónde eres?', german: 'Woher kommst du?' } },
    { id: `${L}.v.alemania`, target: 'Alemania', german: 'Deutschland', pos: 'noun', gender: 'f', emoji: '🇩🇪', field: 'Länder', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.aleman`, target: 'alemán / alemana', german: 'Deutscher / Deutsche; deutsch', pos: 'adj', gender: 'm/f', field: 'Nationalitäten', stageId: 'stage0', lessonId: L, example: { target: 'Anna es alemana.', german: 'Anna ist Deutsche.' } },
    { id: `${L}.v.espana`, target: 'España', german: 'Spanien', pos: 'noun', gender: 'f', emoji: '🇪🇸', field: 'Länder', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.espanol`, target: 'español / española', german: 'Spanier / Spanierin; spanisch', pos: 'adj', gender: 'm/f', field: 'Nationalitäten', stageId: 'stage0', lessonId: L, example: { target: 'Carmen es española.', german: 'Carmen ist Spanierin.' } },
    { id: `${L}.v.mexico`, target: 'México', german: 'Mexiko', pos: 'noun', gender: 'm', emoji: '🇲🇽', field: 'Länder', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.mexicano`, target: 'mexicano / mexicana', german: 'Mexikaner / Mexikanerin; mexikanisch', pos: 'adj', gender: 'm/f', field: 'Nationalitäten', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.estudiante`, target: 'el / la estudiante', german: 'der Student / die Studentin; Schüler/in', pos: 'noun', gender: 'm/f', emoji: '🎓', field: 'Berufe', stageId: 'stage0', lessonId: L, example: { target: 'Soy estudiante.', german: 'Ich bin Student/in.' } },
    { id: `${L}.v.profesor`, target: 'el profesor / la profesora', german: 'der Lehrer / die Lehrerin', pos: 'noun', gender: 'm/f', emoji: '🧑‍🏫', field: 'Berufe', stageId: 'stage0', lessonId: L, example: { target: 'Ella es profesora.', german: 'Sie ist Lehrerin.' } },
    { id: `${L}.v.medico`, target: 'el médico / la médica', german: 'der Arzt / die Ärztin', pos: 'noun', gender: 'm/f', emoji: '🩺', field: 'Berufe', stageId: 'stage0', lessonId: L, example: { target: 'Él es médico.', german: 'Er ist Arzt.' } },
    { id: `${L}.v.tambien`, target: 'también', german: 'auch', pos: 'adv', field: 'Kleine Wörter', stageId: 'stage0', lessonId: L, example: { target: 'Yo también soy estudiante.', german: 'Ich bin auch Student/in.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Das Deutsche hat ein Verb „sein“ – das Spanische hat zwei: **ser** und **estar**. Heute geht es um `ser`. Es beschreibt, **was oder wer** jemand ist:\n' +
        '- Name und Identität: `Soy Laura.`\n' +
        '- Herkunft (mit `de`): `Soy de Alemania.`\n' +
        '- Nationalität: `Soy alemana.`\n' +
        '- Beruf: `Soy profesora.` – wie im Deutschen **ohne** Artikel.\n' +
        '`ser` ist unregelmäßig: Die Formen musst du auswendig lernen – es lohnt sich, denn du brauchst sie ständig.',
    },
    {
      type: 'conjugation',
      verb: 'ser',
      translation: 'sein',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'soy' },
        { person: 'tú', form: 'eres' },
        { person: 'él / ella / usted', form: 'es' },
        { person: 'nosotros / nosotras', form: 'somos' },
        { person: 'vosotros / vosotras', form: 'sois', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'son' },
      ],
    },
    {
      type: 'colored',
      parts: [{ text: 'Soy', role: 'verb' }, { text: ' ' }, { text: 'de', role: 'preposition' }, { text: ' ' }, { text: 'Alemania', role: 'noun' }, { text: '.' }],
      german: 'Ich komme aus Deutschland. (wörtlich: Ich bin aus Deutschland.)',
    },
    {
      type: 'compare',
      target: 'Soy de Berlín.',
      german: 'Ich komme aus Berlin.',
      md: 'Für die Herkunft sagt man im Deutschen meist „kommen aus“. Im Spanischen nimmst du einfach `ser` + `de`. Die Frage dazu: `¿De dónde eres?` – wörtlich „Von wo bist du?“.',
    },
    {
      type: 'mistake',
      wrong: 'Anna es alemán.',
      right: 'Anna es alemana.',
      why: 'Nationalitäten richten sich nach der Person: Frau → **-a** (`alemana`, `española`, `mexicana`). Achte auf den Akzent: `alemán` braucht ihn (Betonung auf der letzten Silbe trotz -n), `alemana` nicht. Und: Nationalitäten schreibt man im Spanischen **klein** – nur Ländernamen groß (`Alemania`).',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In **Spanien** sagst du zu Freunden `vosotros sois`: `¿Sois de aquí?` – Seid ihr von hier?',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In **Lateinamerika** heißt „ihr seid“ immer `ustedes son`: `¿Ustedes son de aquí?` In Argentinien und Uruguay sagt man statt `tú eres` meist `vos sos`.',
    },
    {
      type: 'tip',
      md: '**ser beantwortet: Wer? Was? Woher?** – `Soy Ana. Soy estudiante. Soy de Viena.`',
    },
  ],
  examples: [
    {
      target: 'Soy Laura.',
      german: 'Ich bin Laura.',
      parts: [{ text: 'Soy', role: 'verb' }, { text: ' ' }, { text: 'Laura', role: 'noun' }, { text: '.' }],
    },
    {
      target: '¿De dónde eres?',
      german: 'Woher kommst du?',
      literal: 'Von wo bist du?',
      parts: [{ text: '¿De dónde', role: 'question' }, { text: ' ' }, { text: 'eres', role: 'verb' }, { text: '?', role: 'question' }],
    },
    { target: 'Soy de Alemania, de Hamburgo.', german: 'Ich komme aus Deutschland, aus Hamburg.' },
    {
      target: 'Él es médico y ella es profesora.',
      german: 'Er ist Arzt und sie ist Lehrerin.',
      parts: [
        { text: 'Él', role: 'pronoun' }, { text: ' ' }, { text: 'es', role: 'verb' }, { text: ' ' }, { text: 'médico', role: 'noun' },
        { text: ' y ' }, { text: 'ella', role: 'pronoun' }, { text: ' ' }, { text: 'es', role: 'verb' }, { text: ' ' }, { text: 'profesora', role: 'noun' }, { text: '.' },
      ],
      note: 'Beruf ohne Artikel – wie im Deutschen.',
    },
    { target: 'Somos estudiantes.', german: 'Wir sind Studenten.' },
    { target: '¿Usted es de México?', german: 'Sind Sie aus Mexiko?', note: '`usted` → `es` (wie él/ella). Das x in `México` spricht man wie j: „ME-chi-ko“.' },
    { target: 'Vosotros sois españoles, ¿verdad?', german: 'Ihr seid Spanier, oder?', variant: 'es-ES' },
    { target: 'Ustedes son mexicanos, ¿verdad?', german: 'Ihr seid Mexikaner, oder? / Sie sind Mexikaner, oder?' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      instruction: 'Welche Form von ser gehört zu welchem Pronomen?',
      pairs: [
        { left: 'yo', right: 'soy' },
        { left: 'tú', right: 'eres' },
        { left: 'usted', right: 'es' },
        { left: 'nosotras', right: 'somos' },
        { left: 'ellos', right: 'son' },
      ],
      feedback: {
        rule: 'yo soy · tú eres · él/ella/usted es · nosotros/-as somos · vosotros/-as sois · ellos/ellas/ustedes son.',
        why: '`usted` wird wie él/ella konjugiert: `usted es` – nicht `eres`.',
        avoid: 'Lerne die Reihe als Rhythmus: soy – eres – es – somos – sois – son.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      verb: 'ser',
      tense: 'Präsens',
      person: 'tú',
      sentence: '¿De dónde ___?',
      answers: ['eres'],
      feedback: {
        rule: 'tú → `eres`: `¿De dónde eres?` = Woher kommst du?',
        why: '`es` gehört zu él/ella/usted, `soy` zu yo.',
        avoid: 'Merke die Frage als festen Block: ¿De dónde eres?',
      },
    },
    {
      id: `${L}.g03`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      audio: 'Hola, soy Carmen. Soy de España, de Sevilla.',
      question: 'Woher kommt Carmen?',
      options: ['aus Mexiko', 'aus Spanien', 'aus Deutschland'],
      answer: 1,
      feedback: {
        rule: '`Soy de …` nennt die Herkunft: `Soy de España` = Ich komme aus Spanien.',
        why: 'Du hast `España` gehört – Mexiko wäre `México`, Deutschland `Alemania`.',
        avoid: 'Achte auf das Wort direkt nach `soy de`.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      instruction: 'Ergänze die passenden Formen von ser.',
      sentence: 'Ella ___ profesora y yo ___ estudiante.',
      answers: [['es'], ['soy']],
      bank: ['es', 'soy', 'eres', 'son'],
      german: 'Sie ist Lehrerin und ich bin Student/in.',
      feedback: {
        rule: 'ella → `es`, yo → `soy`.',
        why: '`eres` gehört zu tú, `son` zu ellos/ellas/ustedes.',
        avoid: 'Schau zuerst aufs Subjekt, dann wähle die Form.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      prompt: 'Carmen kommt aus Spanien. Welcher Satz ist korrekt?',
      options: [
        { text: 'Carmen es español.', why: '`español` ist die männliche Form – Carmen ist eine Frau.' },
        { text: 'Carmen es española.' },
        { text: 'Carmen son española.', why: '`son` ist Plural (sie sind) – Carmen ist eine Person: `es`.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Eine Person → `es`; Frau → Nationalität auf -a: `española`.',
        why: 'Verbform und Adjektivendung müssen beide zur Person passen.',
        avoid: 'Prüfe zwei Dinge: Wie viele Personen (es/son)? Mann oder Frau (-o/-a)?',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      variant: 'es-ES',
      verb: 'ser',
      tense: 'Präsens',
      person: 'vosotros',
      sentence: 'Vosotros ___ estudiantes, ¿no?',
      answers: ['sois'],
      feedback: {
        rule: 'vosotros/vosotras → `sois`.',
        why: '`son` gehört zu ellos/ustedes, `somos` zu nosotros.',
        avoid: 'Die vosotros-Formen enden fast immer auf -is: sois, estáis …',
      },
    },
    {
      id: `${L}.g07`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      variant: 'es-LA',
      verb: 'ser',
      tense: 'Präsens',
      person: 'ustedes',
      sentence: 'Ustedes ___ estudiantes, ¿no?',
      answers: ['son'],
      feedback: {
        rule: 'ustedes → `son` (wie ellos/ellas).',
        why: '`ustedes` ist grammatisch 3. Person Plural – die Form ist dieselbe wie bei „sie“.',
        avoid: 'usted = es, ustedes = son – wie él/ellos.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.ser', 'es.g.formality'],
      difficulty: 2,
      instruction: 'Bilde die höfliche Frage.',
      tokens: ['¿De', 'dónde', 'es', 'usted?'],
      extra: ['eres'],
      german: 'Woher kommen Sie?',
      feedback: {
        rule: 'Fragewort vorne: `¿De dónde` + Verb + Subjekt. Zu `usted` gehört `es`.',
        why: '`eres` ist die tú-Form und passt nicht zu `usted`.',
        avoid: 'In Fragen mit Fragewort steht das Verb direkt dahinter: ¿De dónde es usted?',
      },
    },
    {
      id: `${L}.g09`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.ser'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Wir kommen aus Deutschland.',
      answers: ['Somos de Alemania.', 'Nosotros somos de Alemania.', 'Nosotras somos de Alemania.'],
      feedback: {
        rule: 'Herkunft = `ser de`: wir → `somos de Alemania`.',
        why: '„kommen“ wird hier nicht wörtlich übersetzt – im Spanischen sagt man „wir sind aus“.',
        avoid: 'Herkunft? Denk an „Soy de …“ und setz die passende Form von ser ein.',
      },
    },
  ],
  pronunciation: ['es.p.into.de-donde-eres', 'es.p.ny.espanol'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      prompt: 'Stell dich in 2–3 kurzen Sätzen vor: Name, Herkunft und Beruf (oder Studium).',
      requirements: [
        { pattern: '\\bsoy\\b', hint: 'Verwende `soy` (ich bin).' },
        { pattern: '\\bsoy de\\b', hint: 'Nenne deine Herkunft mit `soy de …`.' },
        { pattern: 'soy[\\s\\S]*soy[\\s\\S]*soy', hint: 'Bilde drei Sätze mit `soy`: Name, Herkunft, Beruf.' },
      ],
      samples: ['Hola, soy Laura. Soy de Alemania, de Colonia. Soy profesora.', 'Soy Tom. Soy de Viena. Soy estudiante.'],
      minWords: 6,
      feedback: {
        rule: 'Name: `Soy …` · Herkunft: `Soy de …` · Beruf: `Soy …` (ohne Artikel).',
        why: 'Für alle drei Angaben verwendest du ser.',
        avoid: 'Kein `yo` nötig – und Berufe ohne `un`/`una`: Soy médica.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      instruction: 'Ana lernt Jonas auf einem Sprachkurs kennen. Ergänze Jonas’ Antwort.',
      lines: [
        { speaker: 'Ana', text: 'Hola, soy Ana. ¿De dónde eres?', german: 'Hallo, ich bin Ana. Woher kommst du?' },
        { speaker: 'Jonas', text: 'Soy de Alemania, de Múnich. ¿Y tú?', german: 'Ich komme aus Deutschland, aus München. Und du?' },
        { speaker: 'Ana', text: 'Soy de México. Soy profesora.', german: 'Ich komme aus Mexiko. Ich bin Lehrerin.' },
      ],
      gapIndex: 1,
      options: ['Soy de Alemania, de Múnich. ¿Y tú?', 'Eres de Alemania, de Múnich. ¿Y tú?', 'Es de Alemania, de Múnich. ¿Y usted?'],
      answer: 0,
      feedback: {
        rule: 'Über dich selbst → `soy`. Ana duzt Jonas, also fragt er mit `¿Y tú?` zurück.',
        why: '`eres` heißt „du bist“, `es` „er/sie ist“ – und `usted` passt nicht zu Anas lockerem Ton.',
        avoid: 'Über mich = soy. Über dich = eres.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      prompt: 'Stell dich laut vor: Wie heißt du, woher kommst du, was machst du beruflich?',
      keywords: ['soy', 'de'],
      minMatch: 2,
      sample: 'Hola, soy Max. Soy de Alemania, de Berlín. Soy estudiante.',
      feedback: {
        rule: 'Nutze `soy` für Name und Beruf und `soy de` für die Herkunft.',
        why: 'Die Spracherkennung hat `soy` oder `de` nicht erkannt.',
        avoid: '`soy` spricht man „ßoi“ – mit scharfem s, wie ein kurzer Doppellaut.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      scenarioId: 'es.sc.gefuehrt',
      goal: 'Stell dich vor (Name, Herkunft, Beruf) und frag dein Gegenüber mit `¿De dónde eres?` nach seiner Herkunft.',
      turns: 4,
      feedback: {
        rule: 'Vorstellen mit `soy …`, `soy de …`; nachfragen mit `¿De dónde eres?` bzw. höflich `¿De dónde es usted?`.',
        avoid: 'Wenn dir ein Wort fehlt: Sag einfach `Soy de …` + Stadtname.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.pronouns'],
      difficulty: 1,
      prompt: 'Du sprichst über Marta und Lucía (zwei Frauen). Welches Pronomen passt?',
      options: [
        { text: 'ellos', why: '`ellos` steht für Männer oder gemischte Gruppen.' },
        { text: 'ellas' },
        { text: 'nosotras', why: '`nosotras` heißt „wir“ – du gehörst aber nicht dazu.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Über eine Gruppe nur aus Frauen → `ellas`.',
        why: 'Nur wenn ausschließlich Frauen gemeint sind, steht die Form auf -as.',
        avoid: 'Nur Frauen → -as, sonst -os.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      difficulty: 2,
      instruction: 'Schreib, was du hörst.',
      audio: 'Buenos días, ¿qué tal?',
      answers: ['Buenos días, ¿qué tal?'],
      german: 'Guten Morgen, wie geht’s?',
      feedback: {
        rule: '`Buenos días` (männlich wegen día) und `¿qué tal?` mit Fragezeichen am Anfang und Ende.',
        why: 'Häufige Fehler: `buenas días` oder `que tal` ohne Akzent (Fragewörter tragen einen Akzent).',
        avoid: 'Fragewörter wie `qué`, `dónde` haben immer einen Akzent.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      instruction: 'Korrigiere den Satz.',
      sentence: 'Yo es de Alemania.',
      answers: ['Yo soy de Alemania.', 'Soy de Alemania.'],
      german: 'Ich komme aus Deutschland.',
      feedback: {
        rule: 'yo → `soy`.',
        why: '`es` ist die Form für él/ella/usted.',
        avoid: 'Denk an die Reihe: soy – eres – es – somos – sois – son.',
      },
    },
  ],
};

export default lesson;
