import type { Lesson } from '../../types';

const L = 'es.s0.l08';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c3',
  order: 8,
  title: 'Genus & Plural',
  subtitle: 'el oder la, -s oder -es – und Adjektive, die mitziehen',
  icon: '⚖️',
  minutes: 11,
  goal:
    'Du erkennst das Genus spanischer Nomen meist an der Endung, bildest den Plural mit **-s** oder **-es** und passt Adjektive in **Genus und Zahl** an ihr Nomen an.',
  canDo: [
    'Ich kann bei den meisten Nomen das Genus an der Endung erkennen.',
    'Ich kenne die wichtigen Ausnahmen el día, la mano, el problema und la foto.',
    'Ich kann den Plural mit -s, -es und z → ces bilden.',
    'Ich kann Adjektive an Genus und Zahl des Nomens anpassen.',
  ],
  topicIds: ['es.g.gender-plural', 'es.g.adjectives'],
  vocab: [
    { id: `${L}.v.libro`, target: 'el libro', german: 'das Buch', pos: 'noun', gender: 'm', plural: 'los libros', emoji: '📖', field: 'Dinge & Orte', stageId: 'stage0', lessonId: L, example: { target: 'El libro es nuevo.', german: 'Das Buch ist neu.' } },
    { id: `${L}.v.casa`, target: 'la casa', german: 'das Haus', pos: 'noun', gender: 'f', plural: 'las casas', emoji: '🏠', field: 'Dinge & Orte', stageId: 'stage0', lessonId: L, example: { target: 'La casa es pequeña.', german: 'Das Haus ist klein.' } },
    { id: `${L}.v.dia`, target: 'el día', german: 'der Tag', pos: 'noun', gender: 'm', plural: 'los días', emoji: '☀️', field: 'Zeit', stageId: 'stage0', lessonId: L, example: { target: '¡Buenos días!', german: 'Guten Morgen! / Guten Tag!' } },
    { id: `${L}.v.mano`, target: 'la mano', german: 'die Hand', pos: 'noun', gender: 'f', plural: 'las manos', emoji: '✋', field: 'Körper', stageId: 'stage0', lessonId: L, example: { target: 'La mano está fría.', german: 'Die Hand ist kalt.' } },
    { id: `${L}.v.problema`, target: 'el problema', german: 'das Problem', pos: 'noun', gender: 'm', plural: 'los problemas', field: 'Allgemein', stageId: 'stage0', lessonId: L, example: { target: 'El problema es grande.', german: 'Das Problem ist groß.' } },
    { id: `${L}.v.foto`, target: 'la foto', german: 'das Foto', pos: 'noun', gender: 'f', plural: 'las fotos', emoji: '📷', field: 'Dinge & Orte', stageId: 'stage0', lessonId: L, example: { target: 'Las fotos son nuevas.', german: 'Die Fotos sind neu.' } },
    { id: `${L}.v.ciudad`, target: 'la ciudad', german: 'die Stadt', pos: 'noun', gender: 'f', plural: 'las ciudades', emoji: '🏙️', field: 'Dinge & Orte', stageId: 'stage0', lessonId: L, example: { target: 'Madrid es una ciudad grande.', german: 'Madrid ist eine große Stadt.' } },
    { id: `${L}.v.lapiz`, target: 'el lápiz', german: 'der Bleistift', pos: 'noun', gender: 'm', plural: 'los lápices', emoji: '✏️', field: 'Dinge & Orte', stageId: 'stage0', lessonId: L, example: { target: 'Los lápices son rojos.', german: 'Die Bleistifte sind rot.' } },
    { id: `${L}.v.flor`, target: 'la flor', german: 'die Blume', pos: 'noun', gender: 'f', plural: 'las flores', emoji: '🌸', field: 'Natur', stageId: 'stage0', lessonId: L, example: { target: 'La flor es roja.', german: 'Die Blume ist rot.' } },
    { id: `${L}.v.tren`, target: 'el tren', german: 'der Zug', pos: 'noun', gender: 'm', plural: 'los trenes', emoji: '🚆', field: 'Verkehr', stageId: 'stage0', lessonId: L, example: { target: 'El tren es nuevo.', german: 'Der Zug ist neu.' } },
    { id: `${L}.v.nuevo`, target: 'nuevo, nueva', german: 'neu', pos: 'adj', field: 'Eigenschaften', stageId: 'stage0', lessonId: L, example: { target: 'una casa nueva', german: 'ein neues Haus' } },
    { id: `${L}.v.pequeno`, target: 'pequeño, pequeña', german: 'klein', pos: 'adj', field: 'Eigenschaften', stageId: 'stage0', lessonId: L, example: { target: 'un libro pequeño', german: 'ein kleines Buch' } },
    { id: `${L}.v.grande`, target: 'grande', german: 'groß', pos: 'adj', field: 'Eigenschaften', stageId: 'stage0', lessonId: L, example: { target: 'las ciudades grandes', german: 'die großen Städte' } },
    { id: `${L}.v.rojo`, target: 'rojo, roja', german: 'rot', pos: 'adj', emoji: '🔴', field: 'Farben', stageId: 'stage0', lessonId: L, example: { target: 'las flores rojas', german: 'die roten Blumen' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Jedes spanische Nomen ist **maskulin** oder **feminin** – ein Neutrum wie „das“ gibt es nicht. Die Endung verrät das Genus meistens:\n' +
        '- auf **-o** → fast immer maskulin: `el libro`, `el vaso`\n' +
        '- auf **-a** → meist feminin: `la casa`, `la mesa`\n' +
        '- auf **-ción, -sión, -dad, -tad** → immer feminin: `la canción`, `la ciudad`\n' +
        '- auf **-e** oder Konsonant → beides möglich: `el tren`, `la flor`, `el café`, `la calle`. Hier hilft nur eins: **mit Artikel lernen**.',
    },
    {
      type: 'mistake',
      wrong: 'la problema',
      right: 'el problema',
      why:
        'Nicht jedes Wort folgt der Endungsregel. Diese Ausnahmen brauchst du ständig:\n' +
        '- `el día` und `el problema` enden auf -a, sind aber **maskulin** – wie viele Wörter auf **-ma** aus dem Griechischen: `el idioma`, `el tema`, `el sistema`.\n' +
        '- `la mano` endet auf -o, ist aber **feminin**.\n' +
        '- `la foto` ist die Kurzform von `la fotografía` und bleibt deshalb feminin (genauso `la moto`).',
    },
    {
      type: 'table',
      title: 'Plural bilden',
      headers: ['Wortende', 'Regel', 'Beispiel'],
      rows: [
        ['Vokal', '+ s', 'el libro → los libros · la calle → las calles'],
        ['Konsonant', '+ es', 'la flor → las flores · la ciudad → las ciudades'],
        ['-z', 'z → c + es', 'el lápiz → los lápices · la luz → las luces'],
        ['-ión', '+ es, Akzent entfällt', 'la canción → las canciones'],
      ],
    },
    {
      type: 'text',
      md:
        'Adjektive passen sich in **Genus und Zahl** an ihr Nomen an und stehen meist **dahinter**. Der Artikel zieht mit: `el` → `los`, `la` → `las`.\n' +
        '- Adjektive auf **-o** haben vier Formen: `rojo, roja, rojos, rojas`.\n' +
        '- Adjektive auf **-e** oder Konsonant haben nur zwei: `grande, grandes` · `difícil, difíciles`.\n' +
        '- Ausnahme Nationalitäten – sie haben eine weibliche Form: `alemán → alemana`, `español → española`.\n' +
        'Maßgeblich ist das Genus des **Nomens**, nicht seine Endung: `la mano pequeña`, `el problema grande`.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Las', role: 'article' },
        { text: ' ' },
        { text: 'cas', role: 'noun' },
        { text: 'as', role: 'ending' },
        { text: ' ' },
        { text: 'nuev', role: 'adjective' },
        { text: 'as', role: 'ending' },
        { text: ' ' },
        { text: 'son', role: 'verb' },
        { text: ' ' },
        { text: 'pequeñ', role: 'adjective' },
        { text: 'as', role: 'ending' },
        { text: '.' },
      ],
      german: 'Die neuen Häuser sind klein.',
    },
    {
      type: 'compare',
      target: 'la casa roja – las casas rojas',
      german: 'das rote Haus – die roten Häuser',
      md:
        'Im Deutschen ändert sich die Adjektivendung mit Artikel und Fall (rote, roten, rotes). Im Spanischen gibt es keine Fälle: Das Adjektiv richtet sich **nur** nach Genus und Zahl. Verlass dich aber nie auf das deutsche Genus: _das_ Haus heißt `la casa`, _das_ Problem `el problema`.',
    },
    {
      type: 'tip',
      md:
        'Lerne jedes Nomen **mit Artikel** – `el día`, nicht nur `día`. Und stell dir bei jedem Adjektiv zwei Fragen: **männlich oder weiblich? Einzahl oder Mehrzahl?** Eselsbrücke für `día`: Man sagt `¡Buenos días!` – mit `buenos`, also maskulin.',
    },
    { type: 'audio', text: 'el día, la mano, el problema, la foto', label: 'Die vier wichtigsten Ausnahmen anhören' },
  ],
  examples: [
    {
      target: 'el libro nuevo',
      german: 'das neue Buch',
      parts: [
        { text: 'el', role: 'article' },
        { text: ' ' },
        { text: 'libro', role: 'noun' },
        { text: ' ' },
        { text: 'nuevo', role: 'adjective' },
      ],
    },
    {
      target: 'La casa es pequeña.',
      german: 'Das Haus ist klein.',
      parts: [
        { text: 'La', role: 'article' },
        { text: ' ' },
        { text: 'casa', role: 'noun' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'pequeña', role: 'adjective' },
        { text: '.' },
      ],
      note: 'Im Deutschen neutral, im Spanischen feminin – deshalb `pequeña`.',
    },
    { target: 'El problema es grande.', german: 'Das Problem ist groß.', note: '`problema` endet auf -a, ist aber maskulin. `grande` hat ohnehin nur eine Singularform.' },
    { target: 'Las manos están frías.', german: 'Die Hände sind kalt.', note: '`la mano` endet auf -o, ist aber feminin – deshalb `las` und `frías` (`frío, fría` = kalt).' },
    { target: 'Las fotos son nuevas.', german: 'Die Fotos sind neu.', note: '`la foto` ist die Kurzform von `la fotografía` – daher feminin.' },
    {
      target: 'los lápices rojos',
      german: 'die roten Bleistifte',
      parts: [
        { text: 'los', role: 'article' },
        { text: ' ' },
        { text: 'lápic', role: 'noun' },
        { text: 'es', role: 'ending' },
        { text: ' ' },
        { text: 'roj', role: 'adjective' },
        { text: 'os', role: 'ending' },
      ],
      note: 'Aus z wird vor -es ein c: `lápiz → lápices`.',
    },
    { target: 'las ciudades grandes', german: 'die großen Städte', note: '`grande` ist für m und f gleich; im Plural wird es zu `grandes`.' },
    { target: 'un tren nuevo y una flor roja', german: 'ein neuer Zug und eine rote Blume' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: ['es.g.gender-plural'],
      difficulty: 1,
      instruction: 'Ordne jedes Bild dem Wort mit Artikel zu.',
      pairs: [
        { emoji: '📖', word: 'el libro' },
        { emoji: '🏠', word: 'la casa' },
        { emoji: '✋', word: 'la mano' },
        { emoji: '📷', word: 'la foto' },
        { emoji: '🌸', word: 'la flor' },
        { emoji: '✏️', word: 'el lápiz' },
      ],
      feedback: {
        rule: 'Lerne Nomen immer zusammen mit ihrem Artikel – er zeigt dir das Genus.',
        why: '`la mano` und `la foto` enden auf -o, sind aber feminin. Wer nur auf die Endung schaut, liegt hier falsch.',
        avoid: 'Sprich beim Lernen immer Artikel + Nomen laut: „la mano, la foto“ – so prägt sich das Genus automatisch mit ein.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['es.g.gender-plural'],
      difficulty: 1,
      prompt: 'Welcher Artikel passt? `___ día` (der Tag)',
      options: [
        { text: 'el' },
        { text: 'la', why: '`día` endet zwar auf -a, gehört aber zu den wichtigen Ausnahmen: Es ist maskulin.' },
      ],
      answer: 0,
      feedback: {
        rule: '`día` ist maskulin: `el día`, Plural `los días`.',
        why: 'Die Faustregel „-a = feminin“ hat Ausnahmen: `el día`, `el mapa` und viele Wörter auf -ma wie `el problema` oder `el idioma`.',
        avoid: 'Denk an den Gruß `¡Buenos días!` – `buenos` ist maskulin, also ist auch `día` maskulin.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['es.g.gender-plural'],
      difficulty: 2,
      instruction: 'Ordne jeder Einzahl die passende Mehrzahl zu.',
      pairs: [
        { left: 'el lápiz', right: 'los lápices' },
        { left: 'la ciudad', right: 'las ciudades' },
        { left: 'el día', right: 'los días' },
        { left: 'la flor', right: 'las flores' },
        { left: 'el tren', right: 'los trenes' },
      ],
      feedback: {
        rule: 'Vokal → + s (`días`), Konsonant → + es (`flores`, `trenes`, `ciudades`), -z → -ces (`lápices`). Der Artikel wird zu `los` bzw. `las`.',
        why: 'Häufiger Fehler: nur -s anhängen (`flors`, `lápizs`). Nach einem Konsonanten braucht Spanisch ein -e- dazwischen, sonst ließe sich das Wort kaum aussprechen.',
        avoid: 'Frag dich: Endet das Wort auf einen Vokal? Dann reicht -s. Sonst -es – und aus z wird c.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.adjectives', 'es.g.gender-plural'],
      difficulty: 2,
      instruction: 'Setze die passende Form ein (Grundformen: nuevo, pequeño).',
      sentence: 'Las fotos son ___ y el libro es ___.',
      answers: [['nuevas'], ['pequeño']],
      bank: ['nuevas', 'nuevos', 'nueva', 'pequeño', 'pequeña', 'pequeños'],
      german: 'Die Fotos sind neu und das Buch ist klein.',
      feedback: {
        rule: 'Das Adjektiv übernimmt Genus und Zahl seines Nomens: `las fotos` (f. Pl.) → `nuevas`; `el libro` (m. Sg.) → `pequeño`.',
        why: '`nuevos` wäre maskulin – `foto` ist aber feminin (Kurzform von `la fotografía`), obwohl es auf -o endet.',
        avoid: 'Schau zuerst auf den Artikel: `las` → Endung -as, `el` → Endung -o.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['es.g.gender-plural'],
      difficulty: 2,
      audio: 'Los problemas son grandes.',
      question: 'Was hörst du?',
      options: ['Das Problem ist groß.', 'Die Probleme sind groß.', 'Die Probleme sind klein.'],
      answer: 1,
      feedback: {
        rule: 'Den Plural hörst du gleich dreimal: `los`, `problemas` und `son grandes`.',
        why: '„Das Problem ist groß“ wäre `El problema es grande.` – ohne -s und mit `es` statt `son`. „Klein“ hieße `pequeños`.',
        avoid: 'Achte beim Hören auf das -s am Wortende und auf `son` statt `es` – im Spanischen wird das -s deutlich ausgesprochen.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.adjectives'],
      difficulty: 2,
      tokens: ['Las', 'casas', 'nuevas', 'son', 'grandes.'],
      extra: ['nuevos', 'la'],
      alternatives: [['Las', 'nuevas', 'casas', 'son', 'grandes.']],
      german: 'Die neuen Häuser sind groß.',
      feedback: {
        rule: 'Artikel – Nomen – Adjektiv – Verb – Adjektiv. Das Adjektiv steht normalerweise hinter dem Nomen und hat dieselbe Endung.',
        why: '`nuevos` ist maskulin und `la` steht im Singular – beides passt nicht zu `casas` (feminin Plural).',
        avoid: 'Baue zuerst Artikel + Nomen, dann hängst du das Adjektiv mit derselben Endung (-as) an.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.gender-plural', 'es.g.adjectives'],
      difficulty: 3,
      instruction: 'Der Satz enthält zwei Fehler. Schreibe ihn richtig.',
      sentence: 'Los manos son pequeños.',
      answers: ['Las manos son pequeñas.'],
      german: 'Die Hände sind klein.',
      feedback: {
        rule: '`mano` ist feminin (`la mano`), obwohl es auf -o endet. Also: `las manos` und das Adjektiv im Feminin Plural: `pequeñas`.',
        why: 'Die Endung -o hat dich zu maskulin verleitet. `la mano` ist eine der wenigen Ausnahmen.',
        avoid: 'Eselsbrücke: _die_ Hand – `la mano`. Hier stimmt das deutsche Genus zufällig mit dem spanischen überein.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.adjectives', 'es.g.gender-plural'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Die roten Blumen sind klein.',
      answers: ['Las flores rojas son pequeñas.'],
      feedback: {
        rule: '`flor` ist feminin (`la flor`), Plural `flores` (Konsonant → + es). Beide Adjektive stehen im Feminin Plural: `rojas`, `pequeñas`. Die Farbe steht hinter dem Nomen.',
        why: 'Typische Fehler: `las flors` (nur -s), `las rojas flores` (Farbadjektive stehen praktisch immer hinter dem Nomen) oder `pequeños` (maskulin).',
        avoid: 'Reihenfolge merken: Artikel + Nomen + Farbe. Dann jede Endung prüfen – hier überall -as.',
      },
    },
  ],
  pronunciation: ['es.p.stress.ciudad', 'es.p.cz.zapato'],
  application: [
    {
      id: `${L}.a01`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: ['es.g.adjectives'],
      difficulty: 2,
      prompt: 'Schau dich um und beschreibe laut zwei oder drei Dinge: Artikel + Nomen + `es`/`son` + Adjektiv (z. B. Buch, Haus, Blumen, Fotos).',
      keywords: ['es', 'son', 'nuevo', 'nueva', 'nuevos', 'nuevas', 'pequeño', 'pequeña', 'pequeños', 'pequeñas', 'grande', 'grandes', 'rojo', 'roja', 'rojos', 'rojas'],
      minMatch: 3,
      sample: 'El libro es nuevo. Las flores son rojas y la casa es pequeña.',
      feedback: {
        rule: 'Beschreibung = Artikel + Nomen + `es` (Singular) / `son` (Plural) + Adjektiv mit passender Endung.',
        why: 'Wird ein Adjektiv nicht erkannt, liegt es oft an einer verschluckten Endung. Die Endungen -o/-a/-os/-as tragen die Grammatik – sprich sie deutlich.',
        avoid: 'Bilde erst einen Satz im Kopf, prüfe die Endungen und sprich ihn dann in Ruhe.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.gender-plural', 'es.g.adjectives'],
      difficulty: 2,
      prompt: 'Beschreibe in drei kurzen Sätzen Dinge aus deiner Wohnung oder deiner Stadt. Verwende Artikel, `es`/`son` und Adjektive – mindestens ein Nomen im Plural.',
      requirements: [
        { pattern: '\\b(el|la|los|las)\\b', hint: 'Verwende bestimmte Artikel (el, la, los, las).' },
        { pattern: '\\b(los|las)\\b', hint: 'Schreibe mindestens ein Nomen im Plural mit los oder las.' },
        { pattern: '\\b(es|son)\\b', hint: 'Verbinde Nomen und Adjektiv mit es oder son.' },
      ],
      samples: ['La ciudad es grande. Las casas son pequeñas. Los trenes son nuevos.'],
      minWords: 9,
      feedback: {
        rule: 'Nomen und Adjektiv stimmen in Genus und Zahl überein; im Plural verwendest du `son`.',
        why: 'Häufige Fehler sind `los casas` (casa ist feminin) oder `las casas es` (Plural braucht `son`).',
        avoid: 'Lies jeden Satz noch einmal und unterstreiche im Kopf: Artikel, Nomen und Adjektiv müssen dieselbe Endung „-os/-as“ zeigen.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.gender-plural', 'es.g.adjectives'],
      difficulty: 2,
      scenario: 'Du zeigst einer spanischen Freundin deine Urlaubsfotos und willst sagen: „Die Fotos sind neu.“ Welcher Satz ist richtig?',
      options: [
        { text: 'Las fotos son nuevas.' },
        { text: 'Los fotos son nuevos.', why: '`foto` ist feminin – die Kurzform von `la fotografía`.' },
        { text: 'Las fotos es nueva.', why: 'Plural braucht `son` und die Pluralendung `nuevas`.' },
      ],
      answer: 0,
      feedback: {
        rule: '`la foto` → `las fotos`, dazu `son` und das Adjektiv im Feminin Plural: `nuevas`.',
        why: 'Das -o am Wortende täuscht: `foto` ist abgekürzt aus `fotografía` und behält dessen Genus.',
        avoid: 'Merke dir das Paar `la foto, la moto` – beide feminin, beide Kurzformen.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.articles', 'es.g.gender-plural'],
      difficulty: 1,
      instruction: 'Setze den bestimmten Artikel ein.',
      sentence: '___ problema, ___ mano, ___ días',
      answers: [['el'], ['la'], ['los']],
      bank: ['el', 'la', 'los', 'las'],
      german: 'das Problem, die Hand, die Tage',
      feedback: {
        rule: '`el problema` (m), `la mano` (f), `los días` (m. Pl.) – drei Ausnahmen von der Endungsregel.',
        why: 'Nach der Endung würde man `la problema`, `el mano` und `las días` raten – genau das ist bei diesen Wörtern falsch.',
        avoid: 'Diese Ausnahmen immer als feste Paare wiederholen: el día, el problema, la mano, la foto.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.ser-estar'],
      difficulty: 1,
      prompt: 'Welches Verb passt? `La ciudad ___ grande.` (Die Stadt ist groß.)',
      options: [
        { text: 'es' },
        { text: 'está', why: '`estar` beschreibt Zustände und den Ort. Die Größe einer Stadt ist eine Eigenschaft → `ser`.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Dauerhafte Eigenschaften (Größe, Aussehen, Charakter) → `ser`: `La ciudad es grande.`',
        why: '`está` wäre richtig für einen Ort oder vorübergehenden Zustand, z. B. `La ciudad está en España.`',
        avoid: 'Frage: Was ist die Stadt? (Eigenschaft → es) oder Wo/Wie geht es ihr gerade? (→ está).',
      },
    },
    {
      id: `${L}.r03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      verb: 'ser',
      tense: 'Präsens',
      person: 'nosotros',
      answers: ['somos'],
      sentence: 'Nosotros ___ de Alemania.',
      feedback: {
        rule: '`ser` ist unregelmäßig: soy, eres, es, **somos**, sois, son.',
        why: 'Formen wie `semos` oder `sois` gehören nicht zu nosotros – `sois` ist die vosotros-Form (ihr).',
        avoid: 'Merke das Paar `soy – somos` (ich bin – wir sind): beide beginnen mit so-.',
      },
    },
  ],
};

export default lesson;
