import type { Lesson } from '../../types';

const L = 'es.s0.l14';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c5',
  order: 14,
  title: 'Im Café & beim Einkaufen',
  subtitle: 'Bestellen, nach dem Preis fragen, bezahlen',
  icon: '☕',
  minutes: 12,
  goal:
    'Du bestellst höflich im Café, fragst nach Preisen, verstehst den Betrag und bittest um die Rechnung. Außerdem unterscheidest du **hay** (es gibt) und **está** (befindet sich).',
  canDo: [
    'Ich kann im Café höflich etwas bestellen.',
    'Ich kann nach dem Preis fragen und die Antwort verstehen.',
    'Ich kann um die Rechnung bitten.',
    'Ich kann hay und está richtig verwenden.',
  ],
  topicIds: ['es.g.hay', 'es.g.numbers', 'es.g.questions'],
  vocab: [
    { id: `${L}.v.quiero`, target: 'Quiero …', german: 'Ich möchte … / Ich will …', pos: 'phrase', field: 'Café & Einkaufen', stageId: 'stage0', lessonId: L, example: { target: 'Quiero un café.', german: 'Ich möchte einen Kaffee.' } },
    { id: `${L}.v.quisiera`, target: 'Quisiera …', german: 'Ich hätte gern …', pos: 'phrase', field: 'Café & Einkaufen', stageId: 'stage0', lessonId: L, example: { target: 'Quisiera un café con leche, por favor.', german: 'Ich hätte gern einen Milchkaffee, bitte.' } },
    { id: `${L}.v.por-favor`, target: 'por favor', german: 'bitte', pos: 'phrase', field: 'Café & Einkaufen', stageId: 'stage0', lessonId: L, example: { target: 'La cuenta, por favor.', german: 'Die Rechnung, bitte.' } },
    { id: `${L}.v.cuenta`, target: 'la cuenta', german: 'die Rechnung', pos: 'noun', gender: 'f', plural: 'las cuentas', emoji: '🧾', field: 'Café & Einkaufen', stageId: 'stage0', lessonId: L, example: { target: 'La cuenta, por favor.', german: 'Die Rechnung, bitte.' } },
    { id: `${L}.v.cuanto-cuesta`, target: '¿Cuánto cuesta …?', german: 'Was kostet …?', pos: 'phrase', field: 'Café & Einkaufen', stageId: 'stage0', lessonId: L, example: { target: '¿Cuánto cuestan las manzanas?', german: 'Was kosten die Äpfel?' } },
    { id: `${L}.v.hay`, target: 'hay', german: 'es gibt', pos: 'verb', field: 'Café & Einkaufen', stageId: 'stage0', lessonId: L, example: { target: '¿Hay leche?', german: 'Gibt es Milch?' } },
    { id: `${L}.v.cafe-con-leche`, target: 'el café con leche', german: 'der Milchkaffee', pos: 'noun', gender: 'm', emoji: '☕', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.agua`, target: 'el agua', german: 'das Wasser', pos: 'noun', gender: 'f', plural: 'las aguas', emoji: '💧', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L, example: { target: 'El agua está fría.', german: 'Das Wasser ist kalt.' } },
    { id: `${L}.v.leche`, target: 'la leche', german: 'die Milch', pos: 'noun', gender: 'f', emoji: '🥛', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.zumo`, target: 'el zumo', german: 'der Saft', pos: 'noun', gender: 'm', plural: 'los zumos', emoji: '🧃', variant: 'es-ES', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L, example: { target: 'un zumo de naranja', german: 'ein Orangensaft' } },
    { id: `${L}.v.jugo`, target: 'el jugo', german: 'der Saft', pos: 'noun', gender: 'm', plural: 'los jugos', emoji: '🧃', variant: 'es-LA', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L, example: { target: 'un jugo de naranja', german: 'ein Orangensaft' } },
    { id: `${L}.v.pan`, target: 'el pan', german: 'das Brot', pos: 'noun', gender: 'm', plural: 'los panes', emoji: '🍞', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.manzana`, target: 'la manzana', german: 'der Apfel', pos: 'noun', gender: 'f', plural: 'las manzanas', emoji: '🍎', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.tienda`, target: 'la tienda', german: 'der Laden, das Geschäft', pos: 'noun', gender: 'f', plural: 'las tiendas', emoji: '🏪', field: 'Café & Einkaufen', stageId: 'stage0', lessonId: L, example: { target: 'Hay una tienda en la plaza.', german: 'Es gibt einen Laden am Platz.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Zum Bestellen gibt es drei Stufen:\n' +
        '- **direkt:** `Quiero un café.` (Ich möchte / will einen Kaffee.) – unter Freunden völlig normal, gegenüber Fremden mit `por favor`.\n' +
        '- **höflich:** `Quisiera un café, por favor.` (Ich hätte gern …) – passt immer.\n' +
        '- **kurz:** `Un café con leche, por favor.` – Nomen + bitte, im Café ganz üblich.\n' +
        'Achtung: `el agua` ist **feminin**. Das `el` steht nur, weil das Wort mit betontem a- beginnt: `el agua fría`, aber `las aguas`.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Quisiera', role: 'verb' },
        { text: ' ' },
        { text: 'un', role: 'article' },
        { text: ' ' },
        { text: 'café con leche', role: 'object' },
        { text: ', ' },
        { text: 'por favor', role: 'other' },
        { text: '.' },
      ],
      german: 'Ich hätte gern einen Milchkaffee, bitte.',
    },
    {
      type: 'table',
      title: 'Preis & Bezahlen',
      headers: ['Spanisch', 'Deutsch', 'Hinweis'],
      rows: [
        ['¿Cuánto cuesta el pan?', 'Was kostet das Brot?', 'eine Sache → cuesta'],
        ['¿Cuánto cuestan las manzanas?', 'Was kosten die Äpfel?', 'mehrere → cuestan'],
        ['¿Cuánto es?', 'Wie viel macht das?', 'beim Bezahlen'],
        ['Son tres euros.', 'Das macht drei Euro.', 'Antwort mit son'],
        ['La cuenta, por favor.', 'Die Rechnung, bitte.', 'im Café / Restaurant'],
      ],
    },
    {
      type: 'text',
      md:
        '**hay** heißt „es gibt / gibt es?“ und ändert sich nie – egal ob Singular oder Plural: `¿Hay leche?`, `Hay dos tiendas en la calle.` Nach `hay` steht ein Nomen **ohne Artikel**, mit `un/una` oder mit einer Zahl.\n' +
        '**está / están** sagt, **wo** sich etwas Bestimmtes befindet – mit `el/la` oder einem Namen: `La tienda está en la plaza.`, `Las manzanas están allí.`',
    },
    {
      type: 'compare',
      target: '¿Hay leche? – Sí, la leche está en la mesa.',
      german: 'Gibt es Milch? – Ja, die Milch steht auf dem Tisch.',
      md: 'Existenz (gibt es das überhaupt?) → `hay`. Ort von etwas Bekanntem (wo ist es?) → `está`. Das Deutsche sagt „steht“, „liegt“ oder „ist“ – Spanisch nimmt für den Ort einfach `estar`.',
    },
    {
      type: 'mistake',
      wrong: 'Está una tienda en la plaza.',
      right: 'Hay una tienda en la plaza.',
      why: 'Mit unbestimmtem Artikel (`un`, `una`), ohne Artikel oder mit Zahl → `hay`. Mit bestimmtem Artikel (`el`, `la`) → `está`: `La tienda está en la plaza.` Und nie `hay` mit `el/la`: nicht `Hay la tienda`.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien rufst du die Bedienung mit `¡Perdone!`; den Kellner nennt man `el camarero`, die Kellnerin `la camarera`. Saft heißt `zumo`, ein belegtes Brötchen `bocadillo`. In der Bar hörst du beim Bestellen oft `¿Me pone un café?` (wörtlich: „Stellen Sie mir einen Kaffee hin?“). Trinkgeld ist freiwillig – meist rundet man etwas auf.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika sagt man `jugo` statt zumo; die Bedienung heißt z. B. in Mexiko und Kolumbien `el mesero / la mesera`. Höflich bestellen: `Quisiera …` oder `¿Me trae …, por favor?` (Bringen Sie mir …?). In Mexiko ist ein Trinkgeld (`la propina`) von etwa 10–15 % üblich.',
    },
  ],
  examples: [
    { target: 'Un café con leche, por favor.', german: 'Einen Milchkaffee, bitte.' },
    { target: 'Quisiera un agua, por favor.', german: 'Ich hätte gern ein Wasser, bitte.', note: '`agua` ist feminin, trotzdem `un agua` – wegen des betonten a- am Wortanfang.' },
    { target: '¿Cuánto cuesta el pan? – Cuesta dos euros.', german: 'Was kostet das Brot? – Es kostet zwei Euro.', variant: 'es-ES' },
    { target: '¿Cuánto cuesta el pan? – Cuesta veinte pesos.', german: 'Was kostet das Brot? – Es kostet zwanzig Pesos.', variant: 'es-LA' },
    { target: '¿Cuánto cuestan las manzanas?', german: 'Was kosten die Äpfel?' },
    { target: '¿Hay zumo de naranja?', german: 'Gibt es Orangensaft?', variant: 'es-ES' },
    { target: '¿Hay jugo de naranja?', german: 'Gibt es Orangensaft?', variant: 'es-LA' },
    {
      target: 'La tienda está en la plaza.',
      german: 'Der Laden ist am Platz.',
      parts: [
        { text: 'La tienda', role: 'subject' },
        { text: ' ' },
        { text: 'está', role: 'verb' },
        { text: ' ' },
        { text: 'en la plaza', role: 'other' },
        { text: '.' },
      ],
    },
    { target: 'La cuenta, por favor.', german: 'Die Rechnung, bitte.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary'],
      topicIds: ['es.g.hay'],
      difficulty: 1,
      instruction: 'Ordne jedes Bild dem Wort mit Artikel zu.',
      pairs: [
        { emoji: '☕', word: 'el café' },
        { emoji: '💧', word: 'el agua' },
        { emoji: '🍞', word: 'el pan' },
        { emoji: '🍎', word: 'la manzana' },
        { emoji: '🥛', word: 'la leche' },
        { emoji: '🧾', word: 'la cuenta' },
      ],
      feedback: {
        rule: 'Café-Wortschatz immer mit Artikel lernen: `el café`, `el agua` (feminin!), `el pan`, `la manzana`, `la leche`, `la cuenta`.',
        why: 'Stolperfalle: `el agua` sieht maskulin aus, ist aber feminin (`el agua fría`). Und bei `el pan` (Konsonant am Ende) verrät die Endung das Genus nicht – hier hilft nur Auswendiglernen.',
        avoid: 'Merke dir `el agua fría` als feste Kombination.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['vocabulary', 'speaking'],
      topicIds: ['es.g.questions'],
      difficulty: 1,
      prompt: 'Welche Bestellung ist gegenüber einer fremden Bedienung am höflichsten?',
      options: [
        { text: 'Quiero un café.', why: 'Grammatisch richtig, ohne `por favor` aber recht direkt.' },
        { text: 'Quisiera un café, por favor.' },
        { text: 'Un café.', why: 'Ohne `por favor` klingt das knapp und kann unhöflich wirken.' },
      ],
      answer: 1,
      feedback: {
        rule: '`Quisiera …, por favor` ist die höflichste Standardform (wie „Ich hätte gern …, bitte“).',
        why: '`Quiero` ist nicht falsch, aber direkter – mit `por favor` ist es im Alltag auch in Ordnung.',
        avoid: 'Im Zweifel immer `por favor` anhängen – das passt in jeder Situation.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.questions', 'es.g.numbers'],
      difficulty: 2,
      sentence: '¿Cuánto ___ el pan? ¿Y cuánto ___ las manzanas?',
      answers: [['cuesta'], ['cuestan']],
      bank: ['cuesta', 'cuestan', 'es', 'hay'],
      german: 'Was kostet das Brot? Und was kosten die Äpfel?',
      feedback: {
        rule: 'Das Verb richtet sich nach der Sache: `el pan` (eins) → `cuesta`, `las manzanas` (mehrere) → `cuestan`.',
        why: 'Im Deutschen ändert sich „kostet/kosten“ genauso – im Spanischen wird das oft übersehen, weil die Frage mit `cuánto` beginnt.',
        avoid: 'Schau auf das Nomen hinter dem Verb: Plural → -n.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.hay'],
      difficulty: 2,
      sentence: '¿___ leche? – Sí, la leche ___ en la mesa.',
      answers: [['hay'], ['está']],
      bank: ['hay', 'está', 'es', 'están'],
      german: 'Gibt es Milch? – Ja, die Milch steht auf dem Tisch.',
      feedback: {
        rule: 'Existenz → `hay` (Nomen ohne Artikel). Ort von etwas Bestimmtem (`la leche`) → `está`.',
        why: '`Está leche?` fragt nicht nach der Existenz; `la leche es en la mesa` verwechselt ser mit estar – für den Ort gilt estar.',
        avoid: 'Kein Artikel oder un/una → hay. el/la → está.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      variant: 'es-ES',
      audio: '¿Cuánto es? Son ocho euros con cincuenta.',
      question: 'Wie viel musst du zahlen?',
      options: ['8,50 €', '18,50 €', '8,15 €'],
      answer: 0,
      feedback: {
        rule: '`ocho euros con cincuenta` = 8,50 €. Nach `con` folgen die Cent.',
        why: '18 wäre `dieciocho`, 15 Cent `quince`.',
        avoid: 'Zuerst die Euro-Zahl heraushören, dann auf `con` warten.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      variant: 'es-LA',
      audio: '¿Cuánto es? Son ochenta y cinco pesos.',
      question: 'Wie viel musst du zahlen?',
      options: ['85 Pesos', '58 Pesos', '95 Pesos'],
      answer: 0,
      feedback: {
        rule: '`ochenta y cinco` = 85: erst der Zehner, dann der Einer.',
        why: '58 wäre `cincuenta y ocho`, 95 `noventa y cinco`.',
        avoid: 'Zehner erkennst du an der Endung -enta.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'order',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      tokens: ['Quisiera', 'un', 'café', 'con', 'leche,', 'por', 'favor.'],
      extra: ['la'],
      german: 'Ich hätte gern einen Milchkaffee, bitte.',
      feedback: {
        rule: '`Quisiera` + Bestellung + `, por favor`: `Quisiera un café con leche, por favor.`',
        why: '`café` ist maskulin – `la` passt nicht.',
        avoid: 'Bestellung = Verb + un/una + Nomen, `por favor` ans Ende.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.hay'],
      difficulty: 3,
      sentence: 'Está una tienda en la plaza.',
      answers: ['Hay una tienda en la plaza.'],
      german: 'Es gibt einen Laden am Platz.',
      feedback: {
        rule: 'Mit `un/una` sagt man, dass es etwas gibt → `hay`: `Hay una tienda en la plaza.`',
        why: '`está` braucht ein bestimmtes Subjekt: `La tienda está en la plaza.` – mit `una` klingt es falsch.',
        avoid: 'un/una → hay; el/la → está.',
      },
    },
    {
      id: `${L}.g09`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.questions', 'es.g.numbers'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Was kostet der Saft?',
      answers: ['¿Cuánto cuesta el zumo?', '¿Cuánto cuesta el jugo?'],
      feedback: {
        rule: 'Preisfrage: `¿Cuánto cuesta` + bestimmter Artikel + Nomen? Saft = `zumo` (Spanien) bzw. `jugo` (Lateinamerika).',
        why: '`¿Qué cuesta el zumo?` ist ein wörtlich übersetztes „Was kostet …?“ – auf Spanisch fragt man „Wie viel kostet …?“.',
        avoid: 'Preisfragen beginnen immer mit `¿Cuánto …?`',
      },
    },
  ],
  pronunciation: ['es.p.stress.cafe', 'es.p.cz.gracias'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['vocabulary', 'reading'],
      topicIds: ['es.g.questions'],
      difficulty: 1,
      scenario: 'Du sitzt in einer Bar und möchtest bezahlen. Was sagst du zur Bedienung?',
      options: [
        { text: 'La cuenta, por favor.' },
        { text: 'El cuento, por favor.', why: '`el cuento` ist eine Geschichte oder ein Märchen – nicht die Rechnung.' },
        { text: '¿Hay la cuenta?', why: '`hay` steht nie mit dem bestimmten Artikel. Und so fragt man nicht nach der Rechnung.' },
      ],
      answer: 0,
      feedback: {
        rule: '`La cuenta, por favor.` – die Standardformel zum Bezahlen.',
        why: '`cuenta` (Rechnung) und `cuento` (Geschichte) unterscheiden sich nur im letzten Vokal.',
        avoid: 'Eselsbrücke: `la cuenta` kommt von `contar` (zählen) – die Rechnung zählt alles zusammen. `el cuento` erzählt eine Geschichte.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['vocabulary', 'reading'],
      topicIds: ['es.g.questions', 'es.g.hay'],
      difficulty: 2,
      lines: [
        { speaker: 'Bedienung', text: 'Hola, buenos días. ¿Qué desea?', german: 'Hallo, guten Tag. Was möchten Sie?' },
        { speaker: 'Du', text: 'Quisiera un café con leche, por favor.', german: 'Ich hätte gern einen Milchkaffee, bitte.' },
        { speaker: 'Bedienung', text: 'Muy bien. ¿Algo más?', german: 'Sehr gut. Noch etwas?' },
        { speaker: 'Du', text: 'No, gracias. ¿Cuánto es?', german: 'Nein, danke. Wie viel macht das?' },
      ],
      gapIndex: 1,
      options: ['Quisiera un café con leche, por favor.', 'Hay un café con leche, por favor.', 'Estoy un café con leche, por favor.'],
      answer: 0,
      feedback: {
        rule: 'Auf `¿Qué desea?` antwortest du mit `Quisiera …` oder `Quiero …, por favor`.',
        why: '`Hay un café` bedeutet „Es gibt einen Kaffee“, `Estoy un café` „Ich befinde mich ein Kaffee“ – beides passt nicht.',
        avoid: 'Bestellen = quisiera/quiero + Nomen.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.questions', 'es.g.numbers'],
      difficulty: 2,
      scenarioId: 'es.sc.restaurant',
      goal: 'Bestelle ein Getränk und etwas zu essen, frage nach dem Preis (`¿Cuánto es?`) und bitte um die Rechnung.',
      turns: 6,
      feedback: {
        rule: 'Bestellen mit `Quisiera …, por favor`, Preis mit `¿Cuánto es?`, Rechnung mit `La cuenta, por favor.`',
        why: 'Wer nur `Quiero` ohne `por favor` sagt, wirkt schnell zu direkt.',
        avoid: 'Zu jeder Bitte gehört ein `por favor`, zu jeder Antwort ein `gracias`.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['es.g.hay', 'es.g.questions'],
      difficulty: 3,
      prompt: 'Du bist auf dem Markt. Frag laut, ob es Äpfel gibt, was sie kosten, und bestelle ein Kilo.',
      keywords: ['hay', 'manzanas', 'cuánto', 'cuestan', 'quisiera', 'quiero', 'kilo', 'favor'],
      minMatch: 3,
      sample: '¿Hay manzanas? ¿Cuánto cuestan? Quisiera un kilo, por favor.',
      feedback: {
        rule: '`¿Hay manzanas?` (Existenz) – `¿Cuánto cuestan?` (Plural!) – `Quisiera un kilo, por favor.`',
        why: 'Häufig kommt `¿Cuánto cuesta?` – bei mehreren Äpfeln braucht es aber `cuestan`.',
        avoid: 'Sprich `cuestan` mit deutlichem -n am Ende – daran hört man den Plural.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.questions'],
      difficulty: 1,
      sentence: '¿De ___ eres?',
      answers: [['dónde']],
      german: 'Woher kommst du?',
      feedback: {
        rule: 'woher = `de dónde` – mit Akzent, weil es ein Fragewort ist.',
        why: '`donde` ohne Akzent ist kein Fragewort; `qué` oder `cómo` fragen nicht nach der Herkunft.',
        avoid: 'Fragewörter tragen immer einen Akzent.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      instruction: 'Schreibe die Zahl, die du hörst, in Buchstaben.',
      audio: 'noventa y nueve',
      answers: ['noventa y nueve'],
      german: '99',
      feedback: {
        rule: '99 = `noventa y nueve` – drei Wörter.',
        why: '`noventa` (90) und `nueve` (9) beginnen gleich – die Endung -enta zeigt den Zehner.',
        avoid: 'Ab 31: Zehner + y + Einer.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 1,
      verb: 'comer',
      tense: 'Präsens',
      person: 'nosotros',
      answers: ['comemos'],
      sentence: '¿Dónde ___ hoy?',
      feedback: {
        rule: '-er-Verben, nosotros: Stamm + **-emos**: `comemos`.',
        why: '`comimos` wäre Vergangenheit, `comen` die Form für ellos/ustedes.',
        avoid: 'wir → -mos; bei -er-Verben mit e davor.',
      },
    },
  ],
};

export default lesson;
