import type { Lesson } from '../../types';

const L = 'es.s0.l10';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c4',
  order: 10,
  title: 'Regelmäßige Verben im Präsens',
  subtitle: 'hablar, comer, vivir – drei Muster für Hunderte Verben',
  icon: '🗣️',
  minutes: 12,
  goal:
    'Du konjugierst regelmäßige Verben auf **-ar**, **-er** und **-ir** im Präsens in allen Personen und sagst damit, was du und andere tun.',
  canDo: [
    'Ich kann regelmäßige Verben auf -ar, -er und -ir im Präsens konjugieren.',
    'Ich weiß, wann ich das Subjektpronomen weglassen kann.',
    'Ich kann sagen, wo ich wohne, was ich lerne und welche Sprachen ich spreche.',
    'Ich kenne den Unterschied vosotros (Spanien) und ustedes (Lateinamerika).',
  ],
  topicIds: ['es.g.present-regular'],
  vocab: [
    { id: `${L}.v.hablar`, target: 'hablar', german: 'sprechen, reden', pos: 'verb', emoji: '🗣️', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'Hablo alemán y español.', german: 'Ich spreche Deutsch und Spanisch.' } },
    { id: `${L}.v.trabajar`, target: 'trabajar', german: 'arbeiten', pos: 'verb', emoji: '💼', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: '¿Trabajas mucho?', german: 'Arbeitest du viel?' } },
    { id: `${L}.v.estudiar`, target: 'estudiar', german: 'studieren; lernen', pos: 'verb', emoji: '📚', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'Estudio español.', german: 'Ich lerne Spanisch.' } },
    { id: `${L}.v.escuchar`, target: 'escuchar', german: '(zu)hören', pos: 'verb', emoji: '🎧', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'Escuchamos música.', german: 'Wir hören Musik.' } },
    { id: `${L}.v.comer`, target: 'comer', german: 'essen', pos: 'verb', emoji: '🍽️', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L, example: { target: 'Comemos en casa.', german: 'Wir essen zu Hause.' } },
    { id: `${L}.v.beber`, target: 'beber', german: 'trinken', pos: 'verb', emoji: '🥤', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L, example: { target: 'No bebo café.', german: 'Ich trinke keinen Kaffee.' } },
    { id: `${L}.v.leer`, target: 'leer', german: 'lesen', pos: 'verb', emoji: '📖', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'Leo un libro.', german: 'Ich lese ein Buch.' } },
    { id: `${L}.v.aprender`, target: 'aprender', german: 'lernen', pos: 'verb', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'Aprendemos español.', german: 'Wir lernen Spanisch.' } },
    { id: `${L}.v.vivir`, target: 'vivir', german: 'leben, wohnen', pos: 'verb', emoji: '🏡', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'Vivo en Berlín.', german: 'Ich wohne in Berlin.' } },
    { id: `${L}.v.escribir`, target: 'escribir', german: 'schreiben', pos: 'verb', emoji: '✍️', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'Escribo en español.', german: 'Ich schreibe auf Spanisch.' } },
    { id: `${L}.v.musica`, target: 'la música', german: 'die Musik', pos: 'noun', gender: 'f', emoji: '🎵', field: 'Freizeit', stageId: 'stage0', lessonId: L, example: { target: 'Ellos escuchan música.', german: 'Sie hören Musik.' } },
    { id: `${L}.v.espanol`, target: 'el español', german: 'Spanisch (die Sprache)', pos: 'noun', gender: 'm', field: 'Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Aprendo español.', german: 'Ich lerne Spanisch.' } },
    { id: `${L}.v.mucho`, target: 'mucho', german: 'viel', pos: 'adv', field: 'Alltag', stageId: 'stage0', lessonId: L, example: { target: 'No leo mucho.', german: 'Ich lese nicht viel.' } },
    { id: `${L}.v.todos-los-dias`, target: 'todos los días', german: 'jeden Tag', pos: 'phrase', emoji: '📅', field: 'Zeit', stageId: 'stage0', lessonId: L, example: { target: 'Estudio todos los días.', german: 'Ich lerne jeden Tag.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Spanische Verben enden im Infinitiv auf **-ar**, **-er** oder **-ir**. Für das Präsens nimmst du den **Stamm** (Infinitiv ohne Endung: `habl-`, `com-`, `viv-`) und hängst die Personalendung an.\n' +
        'Weil die Endung die Person verrät, lässt man das Subjektpronomen meist weg: `Hablo español.` Das Pronomen setzt man nur zur Betonung oder Gegenüberstellung: `Yo hablo español, ¿y tú?`\n' +
        'Die große Mehrheit der Verben ist regelmäßig – mit diesen drei Mustern kannst du also sofort Hunderte Verben bilden.',
    },
    {
      type: 'conjugation',
      verb: 'hablar',
      translation: 'sprechen',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'hablo', ending: 'o' },
        { person: 'tú', form: 'hablas', ending: 'as' },
        { person: 'él/ella/usted', form: 'habla', ending: 'a' },
        { person: 'nosotros/nosotras', form: 'hablamos', ending: 'amos' },
        { person: 'vosotros/vosotras', form: 'habláis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos/ellas/ustedes', form: 'hablan', ending: 'an' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'comer',
      translation: 'essen',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'como', ending: 'o' },
        { person: 'tú', form: 'comes', ending: 'es' },
        { person: 'él/ella/usted', form: 'come', ending: 'e' },
        { person: 'nosotros/nosotras', form: 'comemos', ending: 'emos' },
        { person: 'vosotros/vosotras', form: 'coméis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos/ellas/ustedes', form: 'comen', ending: 'en' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'vivir',
      translation: 'leben, wohnen',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'vivo', ending: 'o' },
        { person: 'tú', form: 'vives', ending: 'es' },
        { person: 'él/ella/usted', form: 'vive', ending: 'e' },
        { person: 'nosotros/nosotras', form: 'vivimos', ending: 'imos' },
        { person: 'vosotros/vosotras', form: 'vivís', ending: 'ís', variant: 'es-ES' },
        { person: 'ellos/ellas/ustedes', form: 'viven', ending: 'en' },
      ],
    },
    {
      type: 'tip',
      md:
        '**-er** und **-ir** unterscheiden sich nur bei `nosotros` und `vosotros`: `comemos` – `vivimos`, `coméis` – `vivís`. Die yo-Form endet bei allen drei Gruppen auf **-o**. Betont wird meist die vorletzte Silbe: `HA-blo`, `ha-BLA-mos` – nur die vosotros-Formen tragen die Betonung auf der Endung: `ha-BLÁIS`.',
    },
    {
      type: 'mistake',
      wrong: 'Yo vivir en Berlín.',
      right: 'Vivo en Berlín.',
      why: 'Der Infinitiv ist nur die Wörterbuchform. Im Satz braucht das Verb immer eine Personalendung: `vivo`, `vives`, `vive` … Das `yo` ist nicht falsch, aber meist überflüssig.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md:
        'In Spanien sprichst du mehrere Personen, die du duzt, mit **vosotros/vosotras** an: `¿Vosotros habláis alemán?` Die Endungen tragen einen Akzent: `-áis`, `-éis`, `-ís`. Mehrere Personen, die du siezt, sprichst du mit `ustedes` an – mit der Verbform der 3. Person Plural: `¿Ustedes hablan alemán?`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika gibt es kein vosotros: Für mehrere Personen sagt man immer **ustedes** – auch zu Freunden: `¿Ustedes hablan alemán?` Die Verbform ist dieselbe wie bei ellos/ellas: `hablan`, `comen`, `viven`. In Argentinien, Uruguay und Teilen Mittelamerikas hörst du statt tú oft `vos` (`vos hablás`, `vos comés`, `vos vivís`) – das lernst du später.',
    },
  ],
  examples: [
    {
      target: 'Hablo español y alemán.',
      german: 'Ich spreche Spanisch und Deutsch.',
      parts: [
        { text: 'Habl', role: 'verb' },
        { text: 'o', role: 'ending' },
        { text: ' ' },
        { text: 'español y alemán', role: 'object' },
        { text: '.' },
      ],
      note: 'Die Endung -o zeigt „ich“ – ein `yo` ist nicht nötig.',
    },
    { target: '¿Trabajas mucho?', german: 'Arbeitest du viel?' },
    {
      target: 'Ana come en casa.',
      german: 'Ana isst zu Hause.',
      parts: [
        { text: 'Ana', role: 'subject' },
        { text: ' ' },
        { text: 'com', role: 'verb' },
        { text: 'e', role: 'ending' },
        { text: ' ' },
        { text: 'en casa', role: 'other' },
        { text: '.' },
      ],
    },
    { target: 'Aprendemos español todos los días.', german: 'Wir lernen jeden Tag Spanisch.' },
    { target: 'Ellos escuchan música.', german: 'Sie hören Musik.' },
    { target: '¿Vivís en Madrid?', german: 'Wohnt ihr in Madrid?', variant: 'es-ES', note: 'vosotros-Form: `vivís` – so fragt man in Spanien Freunde.' },
    { target: '¿Ustedes viven en Bogotá?', german: 'Wohnt ihr in Bogotá?', variant: 'es-LA', note: 'In Lateinamerika ist `ustedes` das normale „ihr“ – auch unter Freunden.' },
    { target: 'No leo mucho.', german: 'Ich lese nicht viel.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 1,
      instruction: 'Ordne jedem Pronomen die passende Form von „hablar“ zu.',
      pairs: [
        { left: 'yo', right: 'hablo' },
        { left: 'tú', right: 'hablas' },
        { left: 'usted', right: 'habla' },
        { left: 'nosotros', right: 'hablamos' },
        { left: 'ellos', right: 'hablan' },
      ],
      feedback: {
        rule: '-ar-Verben: -o, -as, -a, -amos, (-áis), -an. `usted` steht grammatisch in der 3. Person: `usted habla`.',
        why: 'Häufig verwechselt: `usted` (Sie) und `tú` (du). Obwohl man mit usted jemanden direkt anspricht, nimmt man die Form von él/ella.',
        avoid: 'Merke: usted = „der Herr / die Dame“ – deshalb 3. Person.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 1,
      prompt: 'Welche Form passt? `Nosotros ___ en Berlín.` (vivir)',
      options: [
        { text: 'vivimos' },
        { text: 'vivemos', why: '-emos gehört zu den -er-Verben (`comemos`). `vivir` ist ein -ir-Verb.' },
        { text: 'viven', why: '`viven` heißt „sie wohnen“ bzw. „ihr wohnt“ (ustedes).' },
      ],
      answer: 0,
      feedback: {
        rule: '-ir-Verben bilden die nosotros-Form auf **-imos**: `vivimos`.',
        why: '`vivemos` mischt das Muster der -er-Verben ein – nur bei nosotros/vosotros unterscheiden sich -er und -ir.',
        avoid: 'Der Vokal des Infinitivs taucht bei nosotros wieder auf: habl**a**r → habl**a**mos, com**e**r → com**e**mos, viv**i**r → viv**i**mos.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 2,
      verb: 'comer',
      tense: 'Präsens',
      person: 'tú',
      answers: ['comes'],
      sentence: 'Tú ___ mucho.',
      feedback: {
        rule: '-er-Verben: tú → Stamm + **-es**: `comes`.',
        why: '`comas` wäre das Muster der -ar-Verben (hablas) – bei comer ist der Endungsvokal ein e.',
        avoid: 'Faustregel: -ar-Verben haben a-Endungen, -er- und -ir-Verben e-Endungen. Ausnahmen: yo endet immer auf -o, und -ir-Verben haben bei nosotros/vosotros -imos/-ís.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 2,
      instruction: 'Setze die Verben in der ich-Form ein.',
      sentence: 'Yo ___ (trabajar) en Berlín y ___ (vivir) en Potsdam.',
      answers: [['trabajo'], ['vivo']],
      german: 'Ich arbeite in Berlin und wohne in Potsdam.',
      feedback: {
        rule: 'Die yo-Form endet bei allen regelmäßigen Verben auf **-o**: `trabajo`, `vivo`.',
        why: 'Den Infinitiv (`trabajar`, `vivir`) im Satz stehen zu lassen, ist der häufigste Anfängerfehler.',
        avoid: 'Endung abschneiden (-ar/-er/-ir), -o anhängen – fertig.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 2,
      audio: 'Comemos en casa.',
      question: 'Wer isst zu Hause?',
      options: ['ich', 'wir', 'sie (mehrere Personen)'],
      answer: 1,
      feedback: {
        rule: 'Die Endung **-emos** bedeutet „wir“ (nosotros) – auch ohne Pronomen.',
        why: '„ich“ wäre `como`, „sie“ (Plural) wäre `comen`.',
        avoid: 'Hör auf das Wortende: -o = ich, -mos = wir, -n = sie/ihr (ustedes).',
      },
    },
    {
      id: `${L}.g06`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 3,
      variant: 'es-ES',
      verb: 'beber',
      tense: 'Präsens',
      person: 'vosotros',
      answers: ['bebéis'],
      sentence: '¿Vosotros ___ café?',
      feedback: {
        rule: 'vosotros bei -er-Verben: Stamm + **-éis**: `bebéis` – mit Akzent auf dem é.',
        why: '`bebís` wäre das Muster der -ir-Verben (vivís), `beben` ist die Form für ellos/ustedes.',
        avoid: 'vosotros-Endungen: -áis (hablar), -éis (comer), -ís (vivir) – immer mit Akzent.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 3,
      variant: 'es-LA',
      verb: 'beber',
      tense: 'Präsens',
      person: 'ustedes',
      answers: ['beben'],
      sentence: '¿Ustedes ___ café?',
      feedback: {
        rule: '`ustedes` nimmt die Form der 3. Person Plural: `beben`.',
        why: '`bebemos` wäre „wir“. In Lateinamerika ist `ustedes` das normale „ihr“ – die Verbform bleibt trotzdem die von ellos.',
        avoid: 'ustedes = ellos-Form (-an / -en).',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.present-regular'],
      difficulty: 3,
      sentence: 'Ellos vive en Madrid y leen mucho.',
      answers: ['Ellos viven en Madrid y leen mucho.'],
      german: 'Sie wohnen in Madrid und lesen viel.',
      feedback: {
        rule: '`ellos` verlangt die 3. Person Plural mit **-n**: `viven`.',
        why: '`vive` ist Singular (er/sie wohnt). Das zweite Verb `leen` war bereits richtig.',
        avoid: 'Bei Plural-Subjekten immer auf das -n am Verbende achten.',
      },
    },
    {
      id: `${L}.g09`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.present-regular'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Wir lernen jeden Tag Spanisch.',
      answers: [
        'Aprendemos español todos los días.',
        'Nosotros aprendemos español todos los días.',
        'Nosotras aprendemos español todos los días.',
        'Todos los días aprendemos español.',
        'Estudiamos español todos los días.',
        'Nosotros estudiamos español todos los días.',
        'Nosotras estudiamos español todos los días.',
        'Todos los días estudiamos español.',
      ],
      feedback: {
        rule: '„lernen“ = `aprender` (-er) oder `estudiar` (-ar). wir → `aprendemos` / `estudiamos`. Sprachnamen stehen nach diesen Verben ohne Artikel: `español`.',
        why: 'Häufige Fehler: Infinitiv stehen lassen (`aprender`), die -ir-Endung (`aprendimos` – das wäre Vergangenheit) oder `el español` mit Artikel.',
        avoid: 'Erst den Infinitiv bestimmen, dann die passende nosotros-Endung: -amos oder -emos.',
      },
    },
  ],
  pronunciation: ['es.p.h.hablar', 'es.p.bv.vivir', 'es.p.bv.beber'],
  application: [
    {
      id: `${L}.a01`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 2,
      prompt: 'Erzähl in zwei oder drei Sätzen von deinem Alltag: Wo wohnst du? Arbeitest oder studierst du? Welche Sprachen sprichst du?',
      keywords: ['vivo', 'trabajo', 'estudio', 'hablo', 'aprendo', 'leo', 'escribo', 'como', 'bebo', 'escucho'],
      minMatch: 2,
      sample: 'Vivo en Hamburgo. Trabajo mucho y aprendo español todos los días.',
      feedback: {
        rule: 'Über dich selbst sprichst du mit der yo-Form auf **-o**: `vivo`, `trabajo`, `hablo`.',
        why: 'Wird kein Verb erkannt, hast du vielleicht den Infinitiv benutzt (`vivir`) oder die Endung verschluckt.',
        avoid: 'Betone die vorletzte Silbe klar: `VI-vo`, `tra-BA-jo`, `HA-blo`.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 2,
      prompt: 'Schreibe drei Sätze über eine Person, die du kennst: Wo wohnt sie? Was macht sie? Welche Sprachen spricht sie?',
      requirements: [
        { pattern: '\\bvive\\b', hint: 'Sag mit „vive“, wo die Person wohnt.' },
        { pattern: '\\b(trabaja|estudia|habla|aprende|come|bebe|lee|escribe|escucha)\\b', hint: 'Verwende mindestens ein weiteres Verb in der 3. Person Singular (z. B. trabaja, habla).' },
      ],
      samples: ['Lena vive en Colonia. Trabaja mucho y habla inglés. Aprende español todos los días.'],
      minWords: 10,
      feedback: {
        rule: 'Er/sie: -ar-Verben auf **-a** (`trabaja`), -er/-ir-Verben auf **-e** (`aprende`, `vive`).',
        why: 'Typisch ist die yo-Form (`Lena vivo`) oder die Pluralform (`Lena viven`) für eine einzelne Person.',
        avoid: 'Frage dich bei jedem Verb: Wer tut es? Eine Person (nicht ich, nicht du) → -a / -e.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.present-regular'],
      difficulty: 2,
      scenarioId: 'es.sc.gefuehrt',
      goal: 'Erzähle deinem Gesprächspartner, wo du wohnst, ob du arbeitest oder studierst und welche Sprachen du sprichst – mit Verben in der ich-Form.',
      turns: 4,
      feedback: {
        rule: 'yo-Form (-o) für dich selbst, tú-Form (-as/-es) für Rückfragen: `¿Y tú? ¿Dónde vives?`',
        why: 'Im Gespräch rutscht leicht der Infinitiv durch – die Endung ist aber die Information „wer“.',
        avoid: 'Lieber kurze, korrekte Sätze als lange mit Infinitiven.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 1,
      sentence: 'Hablo no inglés.',
      answers: ['No hablo inglés.'],
      german: 'Ich spreche kein Englisch.',
      feedback: {
        rule: '`no` steht direkt vor dem Verb: `No hablo inglés.`',
        why: 'Das deutsche „kein“/„nicht“ steht hinter dem Verb – im Spanischen ist das falsch.',
        avoid: 'Merksatz aus Lektion 9: `no` klebt vor dem Verb.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.adjectives'],
      difficulty: 1,
      instruction: 'Setze „nuevo“ in der richtigen Form ein.',
      sentence: 'Los libros son ___.',
      answers: [['nuevos']],
      german: 'Die Bücher sind neu.',
      feedback: {
        rule: '`los libros` ist maskulin Plural → `nuevos`.',
        why: '`nuevo` ist Singular, `nuevas` feminin – beides passt nicht zu `libros`.',
        avoid: 'Artikel und Adjektiv tragen dieselbe Endung: los … -os.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.ser-estar'],
      difficulty: 1,
      prompt: 'Welches Verb passt? `Madrid ___ en España.`',
      options: [
        { text: 'es', why: '`ser` steht für Eigenschaften und Identität, nicht für die Lage.' },
        { text: 'está' },
      ],
      answer: 1,
      feedback: {
        rule: 'Lage und Ort → `estar`: `Madrid está en España.`',
        why: 'Auch wenn sich die Lage einer Stadt nie ändert: Für „wo?“ nimmt man immer estar.',
        avoid: 'Frage „Wo liegt/ist …?“ → está.',
      },
    },
  ],
};

export default lesson;
