import type { Lesson } from '../../types';

const L = 'es.s0.l12';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c5',
  order: 12,
  title: 'Sich vorstellen',
  subtitle: 'Name, Herkunft, Wohnort, Alter, Sprachen',
  icon: '🙋',
  minutes: 11,
  goal:
    'Du stellst dich in ganzen Sätzen vor – mit Name, Herkunft, Wohnort, Alter und Sprachen – und reagierst höflich, wenn sich jemand vorstellt.',
  canDo: [
    'Ich kann meinen Namen, meine Herkunft und meinen Wohnort nennen.',
    'Ich kann mein Alter mit „Tengo … años“ sagen.',
    'Ich kann sagen, welche Sprachen ich spreche.',
    'Ich kann auf eine Vorstellung mit Encantado/Encantada oder Mucho gusto reagieren.',
  ],
  topicIds: ['es.g.ser', 'es.g.present-regular'],
  vocab: [
    { id: `${L}.v.me-llamo`, target: 'Me llamo …', german: 'Ich heiße …', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L, example: { target: 'Me llamo Julia.', german: 'Ich heiße Julia.' } },
    { id: `${L}.v.soy-de`, target: 'Soy de …', german: 'Ich komme aus …', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L, example: { target: 'Soy de Alemania.', german: 'Ich komme aus Deutschland.' } },
    { id: `${L}.v.vivo-en`, target: 'Vivo en …', german: 'Ich wohne in …', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L, example: { target: 'Vivo en Múnich.', german: 'Ich wohne in München.' } },
    { id: `${L}.v.tengo-anos`, target: 'Tengo … años.', german: 'Ich bin … Jahre alt.', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L, example: { target: 'Tengo treinta años.', german: 'Ich bin dreißig Jahre alt.' } },
    { id: `${L}.v.encantado`, target: 'Encantado. / Encantada.', german: 'Freut mich. (Mann / Frau spricht)', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.mucho-gusto`, target: 'Mucho gusto.', german: 'Sehr erfreut. / Freut mich.', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.igualmente`, target: 'Igualmente.', german: 'Gleichfalls.', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ano`, target: 'el año', german: 'das Jahr', pos: 'noun', gender: 'm', plural: 'los años', field: 'Zeit', stageId: 'stage0', lessonId: L, example: { target: 'Tengo veinte años.', german: 'Ich bin zwanzig Jahre alt.' } },
    { id: `${L}.v.idioma`, target: 'el idioma', german: 'die Sprache', pos: 'noun', gender: 'm', plural: 'los idiomas', field: 'Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Hablo dos idiomas.', german: 'Ich spreche zwei Sprachen.' } },
    { id: `${L}.v.un-poco`, target: 'un poco (de)', german: 'ein bisschen', pos: 'phrase', field: 'Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Hablo un poco de español.', german: 'Ich spreche ein bisschen Spanisch.' } },
    { id: `${L}.v.aleman`, target: 'alemán, alemana', german: 'deutsch; Deutscher, Deutsche', pos: 'adj', emoji: '🇩🇪', field: 'Länder & Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Soy alemana.', german: 'Ich bin Deutsche.' } },
    { id: `${L}.v.austriaco`, target: 'austriaco, austriaca', german: 'österreichisch; Österreicher(in)', pos: 'adj', emoji: '🇦🇹', field: 'Länder & Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Soy austriaco.', german: 'Ich bin Österreicher.' } },
    { id: `${L}.v.suizo`, target: 'suizo, suiza', german: 'schweizerisch; Schweizer(in)', pos: 'adj', emoji: '🇨🇭', field: 'Länder & Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Soy suiza.', german: 'Ich bin Schweizerin.' } },
    { id: `${L}.v.alemania`, target: 'Alemania', german: 'Deutschland', pos: 'noun', field: 'Länder & Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Soy de Alemania.', german: 'Ich komme aus Deutschland.' } },
    { id: `${L}.v.estudiante`, target: 'el estudiante, la estudiante', german: 'der Student, die Studentin', pos: 'noun', gender: 'm/f', plural: 'los estudiantes', emoji: '🎓', field: 'Beruf', stageId: 'stage0', lessonId: L, example: { target: 'Soy estudiante.', german: 'Ich bin Student(in).' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Mit fünf Bausteinen kannst du dich vorstellen:\n' +
        '- **Name:** `Me llamo Julia.` – oder kurz `Soy Julia.`\n' +
        '- **Herkunft:** `Soy de Alemania.` oder `Soy alemana.` – Herkunft gehört zur Identität, also **ser**.\n' +
        '- **Wohnort:** `Vivo en Múnich.` – das regelmäßige Verb vivir.\n' +
        '- **Alter:** `Tengo treinta años.` – feste Wendung mit **tener** (haben).\n' +
        '- **Sprachen:** `Hablo alemán e inglés.` – vor einem i-Laut wird `y` zu `e`.\n' +
        'Nationalitäten und Sprachen schreibt man im Spanischen **klein**: `alemán`, `español`. Beim Beruf steht kein Artikel: `Soy estudiante.`',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' ' },
        { text: 'llamo', role: 'verb' },
        { text: ' ' },
        { text: 'Julia', role: 'noun' },
        { text: ', ' },
        { text: 'soy', role: 'verb' },
        { text: ' ' },
        { text: 'de', role: 'preposition' },
        { text: ' ' },
        { text: 'Alemania', role: 'noun' },
        { text: ' y ' },
        { text: 'vivo', role: 'verb' },
        { text: ' ' },
        { text: 'en', role: 'preposition' },
        { text: ' ' },
        { text: 'Múnich', role: 'noun' },
        { text: '.' },
      ],
      german: 'Ich heiße Julia, komme aus Deutschland und wohne in München.',
    },
    {
      type: 'compare',
      target: 'Tengo treinta años.',
      german: 'Ich bin dreißig Jahre alt.',
      md: 'Wörtlich: „Ich habe dreißig Jahre.“ Beim Alter benutzt Spanisch **tener** (haben), nicht ser. Merke dir `Tengo … años` als feste Wendung – das Verb tener lernst du in A1 vollständig. Die passende Frage lautet `¿Cuántos años tienes?` (Wie alt bist du?).',
    },
    {
      type: 'mistake',
      wrong: 'Soy treinta años.',
      right: 'Tengo treinta años.',
      why: 'Das deutsche „Ich bin … alt“ verleitet zu `soy`. Im Spanischen „hat“ man sein Alter: `tengo`. Ebenso falsch: `Estoy de Alemania` – Herkunft immer mit ser: `Soy de Alemania.`',
    },
    {
      type: 'table',
      title: 'Länder, Nationalitäten, Sprachen',
      headers: ['Land', 'er ist …', 'sie ist …', 'Sprache'],
      rows: [
        ['Alemania', 'alemán', 'alemana', 'alemán'],
        ['Austria', 'austriaco', 'austriaca', 'alemán'],
        ['Suiza', 'suizo', 'suiza', 'alemán, francés, italiano'],
        ['España', 'español', 'española', 'español'],
        ['México', 'mexicano', 'mexicana', 'español'],
      ],
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien begrüßt man sich beim Kennenlernen in lockerem Rahmen meist mit **zwei Wangenküssen** (`dos besos`) – unter Männern ist eher ein Handschlag üblich, im Beruf ebenfalls. Typische Antwort auf eine Vorstellung: `Encantado` / `Encantada`.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In vielen Ländern Lateinamerikas gibt man zur Begrüßung **einen** Wangenkuss (unter Frauen sowie zwischen Frau und Mann); Männer geben sich meist die Hand. Sehr verbreitet ist `Mucho gusto` – die Antwort darauf: `Igualmente` oder ebenfalls `Mucho gusto`.',
    },
    {
      type: 'tip',
      md: '`Encantado` sagen Männer, `Encantada` sagen Frauen – die Form richtet sich nach **dir**, nicht nach deinem Gegenüber. `Mucho gusto` passt für alle.',
    },
  ],
  examples: [
    {
      target: 'Me llamo Tobias.',
      german: 'Ich heiße Tobias.',
      literal: 'Ich nenne mich Tobias.',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' ' },
        { text: 'llamo', role: 'verb' },
        { text: ' ' },
        { text: 'Tobias', role: 'noun' },
        { text: '.' },
      ],
    },
    { target: 'Soy alemana, de Hamburgo.', german: 'Ich bin Deutsche, aus Hamburg.' },
    { target: 'Vivo en Viena, pero soy de Suiza.', german: 'Ich wohne in Wien, aber ich komme aus der Schweiz.', note: '`pero` = aber. Städtenamen haben oft eigene spanische Formen: Viena (Wien), Múnich (München), Colonia (Köln), Zúrich.' },
    { target: 'Tengo veintiocho años.', german: 'Ich bin 28 Jahre alt.', literal: 'Ich habe achtundzwanzig Jahre.' },
    { target: 'Hablo alemán, inglés y un poco de español.', german: 'Ich spreche Deutsch, Englisch und ein bisschen Spanisch.' },
    { target: 'Soy estudiante y vivo en Berlín.', german: 'Ich bin Student(in) und wohne in Berlin.', note: 'Beim Beruf kein Artikel: `Soy estudiante`, nicht `Soy un estudiante`.' },
    { target: '–Mucho gusto, soy Carlos. –Igualmente.', german: '– Sehr erfreut, ich bin Carlos. – Gleichfalls.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 1,
      instruction: 'Ordne die Bausteine ihrer Bedeutung zu.',
      pairs: [
        { left: 'Me llamo …', right: 'Ich heiße …' },
        { left: 'Soy de …', right: 'Ich komme aus …' },
        { left: 'Vivo en …', right: 'Ich wohne in …' },
        { left: 'Tengo … años.', right: 'Ich bin … Jahre alt.' },
        { left: 'Hablo …', right: 'Ich spreche …' },
      ],
      feedback: {
        rule: 'Name → llamarse, Herkunft → ser de, Wohnort → vivir en, Alter → tener … años, Sprachen → hablar.',
        why: '`Soy de` (Herkunft) und `Vivo en` (Wohnort) werden leicht vertauscht – de = aus, en = in.',
        avoid: 'Merke die Präpositionen mit: soy **de** (aus), vivo **en** (in).',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      prompt: 'Wie sagst du „Ich bin 25 Jahre alt“?',
      options: [
        { text: 'Soy veinticinco años.', why: 'Alter wird nicht mit ser ausgedrückt.' },
        { text: 'Tengo veinticinco años.' },
        { text: 'Estoy veinticinco años.', why: 'estar beschreibt Zustände und Orte – nicht das Alter.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Alter = `tener` + Zahl + `años`: `Tengo veinticinco años.`',
        why: 'Das deutsche „Ich bin … alt“ legt `soy` nahe – im Spanischen „hat“ man seine Jahre.',
        avoid: 'Denk an „Ich **habe** 25 Jahre“ – dann greifst du automatisch zu `tengo`.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 2,
      sentence: 'Me ___ Laura, ___ de Austria y ___ en Graz.',
      answers: [['llamo'], ['soy'], ['vivo']],
      bank: ['llamo', 'soy', 'vivo', 'estoy', 'tengo'],
      german: 'Ich heiße Laura, komme aus Österreich und wohne in Graz.',
      feedback: {
        rule: '`Me llamo` + Name, `soy de` + Herkunft, `vivo en` + Wohnort.',
        why: '`estoy de Austria` ist falsch – Herkunft ist Identität (ser). `tengo` passt nur zum Alter.',
        avoid: 'Frage dich: Wer bin ich (ser)? Wo wohne ich (vivir)? Wie alt bin ich (tener)?',
      },
    },
    {
      id: `${L}.g04`,
      type: 'order',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 2,
      tokens: ['Soy', 'de', 'Suiza', 'y', 'hablo', 'alemán.'],
      extra: ['estoy'],
      german: 'Ich komme aus der Schweiz und spreche Deutsch.',
      feedback: {
        rule: '`Soy de` + Land; `hablo` + Sprache ohne Artikel: `Soy de Suiza y hablo alemán.`',
        why: '`estoy` ist hier ein Ablenker: Herkunft drückt man mit ser aus.',
        avoid: 'Ländernamen stehen meist ohne Artikel: `Suiza`, nicht `la Suiza`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 2,
      audio: 'Hola, me llamo Marta. Soy de Sevilla y vivo en Valencia. Tengo treinta y cuatro años.',
      question: 'Wo wohnt Marta?',
      options: ['in Sevilla', 'in Valencia', 'in Madrid'],
      answer: 1,
      feedback: {
        rule: '`Vivo en Valencia` = Ich wohne in Valencia. `Soy de Sevilla` nennt nur die Herkunft.',
        why: 'Sevilla wird zuerst genannt – aber mit `soy de` (Herkunft), nicht mit `vivo en`.',
        avoid: 'Achte auf das Verb vor dem Ortsnamen: `soy de` = woher, `vivo en` = wo.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'speak',
      skills: ['pronunciation', 'speaking'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      text: 'Mucho gusto. Me llamo Ana y soy de Alemania.',
      german: 'Sehr erfreut. Ich heiße Ana und komme aus Deutschland.',
      phonetic: 'MU-tscho GUS-to. me JA-mo A-na i soi de a-le-MA-nja',
      pronItemId: 'es.p.ll.llamo',
      feedback: {
        rule: '`ll` in `llamo` klingt in den meisten Regionen wie ein weiches deutsches „j“; `ch` in `mucho` wie „tsch“.',
        why: 'Deutschsprachige sprechen `ll` oft als „l“ aus („la-mo“) – dann versteht man „lamo“ statt „llamo“.',
        avoid: 'Denk an „Jamo“ – nicht an „Lamo“. Und: `Alemania` hat vier Silben mit Betonung auf MA: a-le-MA-nja.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 3,
      instruction: 'Der Satz enthält zwei Fehler. Schreibe ihn richtig.',
      sentence: 'Estoy de Alemania y soy treinta años.',
      answers: ['Soy de Alemania y tengo treinta años.'],
      german: 'Ich komme aus Deutschland und bin dreißig Jahre alt.',
      feedback: {
        rule: 'Herkunft mit ser (`Soy de …`), Alter mit tener (`Tengo … años`).',
        why: 'Das deutsche „ich bin“ steckt hinter beiden Fehlern – im Spanischen braucht jede Information ihr eigenes Verb.',
        avoid: 'Vor dem Schreiben kurz zuordnen: Herkunft → soy, Alter → tengo.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Ich heiße Paul, bin 40 Jahre alt und wohne in Zürich.',
      answers: [
        'Me llamo Paul, tengo cuarenta años y vivo en Zúrich.',
        'Me llamo Paul, tengo 40 años y vivo en Zúrich.',
        'Soy Paul, tengo cuarenta años y vivo en Zúrich.',
        'Soy Paul, tengo 40 años y vivo en Zúrich.',
        'Yo me llamo Paul, tengo cuarenta años y vivo en Zúrich.',
        'Yo me llamo Paul, tengo 40 años y vivo en Zúrich.',
      ],
      feedback: {
        rule: 'Name: `Me llamo …` (oder `Soy …`); Alter: `tengo … años`; Wohnort: `vivo en …`. Zürich heißt auf Spanisch `Zúrich`.',
        why: 'Typische Fehler: `soy cuarenta años` (Alter braucht tener) oder `vivir en` (Infinitiv statt vivo).',
        avoid: 'Die drei Bausteine einzeln bilden und dann mit Komma und `y` verbinden.',
      },
    },
  ],
  pronunciation: ['es.p.ll.llamo', 'es.p.syl.encantado', 'es.p.into.me-llamo-ana'],
  application: [
    {
      id: `${L}.a01`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 2,
      prompt: 'Stell dich laut vor: Name, Herkunft, Wohnort, Alter und Sprachen.',
      keywords: ['llamo', 'soy', 'vivo', 'tengo', 'años', 'hablo'],
      minMatch: 4,
      sample: 'Hola, me llamo Tobias. Soy de Alemania y vivo en Leipzig. Tengo treinta y dos años. Hablo alemán, inglés y un poco de español.',
      feedback: {
        rule: 'Fünf Bausteine: `Me llamo …`, `Soy de …`, `Vivo en …`, `Tengo … años`, `Hablo …`.',
        why: 'Fehlt ein Baustein in der Auswertung, wurde er nicht erkannt oder ausgelassen – oft `tengo`, weil man spontan `soy` sagt.',
        avoid: 'Übe die Vorstellung ein paarmal, bis sie flüssig sitzt – sie brauchst du auf jeder Reise.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.ser'],
      difficulty: 2,
      scenario: 'Auf einer Feier in Madrid stellt sich Pablo bei Lena vor: `Hola, soy Pablo. Encantado.` Was antwortet Lena am besten?',
      options: [
        { text: 'Encantada. Yo soy Lena.' },
        { text: 'Encantado. Yo soy Lena.', why: 'Lena ist eine Frau – sie sagt `encantada`. Die Form richtet sich nach der Sprecherin, nicht nach Pablo.' },
        { text: 'Estoy Lena, encantada.', why: 'Beim Namen benutzt man `Soy Lena` oder `Me llamo Lena` – nie estar.' },
      ],
      answer: 0,
      feedback: {
        rule: '`Encantado/Encantada` richtet sich nach der Person, die spricht. Name mit `Soy …` oder `Me llamo …`.',
        why: 'Viele übernehmen einfach die Form, die sie gerade gehört haben – hier also fälschlich `encantado`.',
        avoid: 'Frauen: encantad**a**, Männer: encantad**o**. Im Zweifel: `Mucho gusto`.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 3,
      prompt: 'Schreibe einen kurzen Steckbrief über dich in vier Sätzen: Name, Herkunft, Wohnort und Alter.',
      requirements: [
        { pattern: '\\bme llamo\\b|\\bsoy [a-záéíóúñ]+', hint: 'Nenne deinen Namen mit Me llamo … oder Soy …' },
        { pattern: '\\bsoy de\\b|\\bsoy (alem|austr|suiz|español|mexican)', hint: 'Sag, woher du kommst: Soy de … oder Soy alemán/alemana …' },
        { pattern: '\\bvivo en\\b', hint: 'Sag, wo du wohnst: Vivo en …' },
        { pattern: '\\btengo\\b.*\\baños\\b', hint: 'Nenne dein Alter mit Tengo … años.' },
      ],
      samples: ['Me llamo Sophie. Soy de Austria. Vivo en Salzburgo. Tengo veintinueve años.'],
      minWords: 12,
      feedback: {
        rule: 'Name (llamarse/ser), Herkunft (ser de), Wohnort (vivir en), Alter (tener … años).',
        why: 'Die häufigsten Fehler: `soy … años`, `estoy de …` und Infinitive wie `vivir en`.',
        avoid: 'Kontrolliere am Ende jedes Verb: Endet es auf -o bzw. ist es `soy`?',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.ser', 'es.g.present-regular'],
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Stell dich vor (Name, Herkunft, Wohnort, Alter) und reagiere höflich mit `Encantado/-a` oder `Mucho gusto`.',
      turns: 5,
      feedback: {
        rule: 'Kurze Sätze mit den fünf Bausteinen genügen; höfliche Reaktion: `Encantado/-a`, `Mucho gusto`, `Igualmente`.',
        why: 'Im Gespräch fällt man leicht ins Deutsche Muster „Ich bin … alt“ zurück.',
        avoid: 'Leg dir die Sätze vorher zurecht – im Gespräch dann Schritt für Schritt abrufen.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.numbers'],
      difficulty: 1,
      audio: 'cuarenta y ocho',
      question: 'Welche Zahl hörst du?',
      options: ['48', '84', '44'],
      answer: 0,
      feedback: {
        rule: '`cuarenta` (40) + `y` + `ocho` (8) = 48. Spanisch nennt zuerst den Zehner.',
        why: '84 wäre `ochenta y cuatro` – hier dreht sich die Reihenfolge der Wörter um.',
        avoid: 'Zehner (-enta) zuerst hören, dann den Einer.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 1,
      verb: 'hablar',
      tense: 'Präsens',
      person: 'tú',
      answers: ['hablas'],
      sentence: '¿Tú ___ alemán?',
      feedback: {
        rule: '-ar-Verben, tú: Stamm + **-as**: `hablas`.',
        why: '`habla` ist die Form für er/sie/usted, `hablo` für ich.',
        avoid: 'Die tú-Form endet fast immer auf -s.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.word-order-negation'],
      difficulty: 1,
      prompt: 'Wie verneinst du `Soy de Madrid.`?',
      options: [
        { text: 'No soy de Madrid.' },
        { text: 'Soy no de Madrid.', why: '`no` steht vor dem Verb, nicht dahinter.' },
        { text: 'Soy de Madrid no.', why: 'Ein „nicht“ am Satzende gibt es im Spanischen nicht.' },
      ],
      answer: 0,
      feedback: {
        rule: '`no` steht direkt vor dem konjugierten Verb.',
        why: 'Die deutsche Stellung von „nicht“ lässt sich nicht übertragen.',
        avoid: '`no` klebt vor dem Verb.',
      },
    },
  ],
};

export default lesson;
