import type { Lesson } from '../../types';

const L = 'es.s0.l11';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c4',
  order: 11,
  title: 'Zahlen von 0 bis 100',
  subtitle: 'Preise, Hausnummern, Telefonnummern',
  icon: '🔢',
  minutes: 11,
  goal:
    'Du verstehst und sagst die Zahlen von **0 bis 100**, nennst Preise und Telefonnummern und vermeidest die typischen Stolperfallen wie `dieciséis`, `veintiuno` und `treinta y uno`.',
  canDo: [
    'Ich kann die Zahlen von 0 bis 100 sagen und schreiben.',
    'Ich weiß, wann eine Zahl ein Wort ist und wann man „y“ braucht.',
    'Ich kann Preise verstehen und nennen.',
    'Ich kann eine Telefonnummer auf Spanisch diktieren und verstehen.',
  ],
  topicIds: ['es.g.numbers'],
  vocab: [
    { id: `${L}.v.cero`, target: 'cero', german: 'null', pos: 'num', emoji: '0️⃣', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.uno`, target: 'uno', german: 'eins', pos: 'num', emoji: '1️⃣', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'un euro, una casa', german: 'ein Euro, ein Haus' } },
    { id: `${L}.v.diez`, target: 'diez', german: 'zehn', pos: 'num', emoji: '🔟', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.quince`, target: 'quince', german: 'fünfzehn', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.dieciseis`, target: 'dieciséis', german: 'sechzehn', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'Somos dieciséis.', german: 'Wir sind zu sechzehnt.' } },
    { id: `${L}.v.veinte`, target: 'veinte', german: 'zwanzig', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.veintiuno`, target: 'veintiuno', german: 'einundzwanzig', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'Son veintiún euros.', german: 'Das macht 21 Euro.' } },
    { id: `${L}.v.treinta`, target: 'treinta', german: 'dreißig', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'treinta y uno', german: 'einunddreißig' } },
    { id: `${L}.v.cincuenta`, target: 'cincuenta', german: 'fünfzig', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.cien`, target: 'cien', german: 'hundert', pos: 'num', emoji: '💯', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'cien euros', german: 'hundert Euro' } },
    { id: `${L}.v.mas`, target: 'más', german: 'plus; mehr', pos: 'adv', emoji: '➕', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'Dos más dos son cuatro.', german: 'Zwei plus zwei ist vier.' } },
    { id: `${L}.v.numero`, target: 'el número', german: 'die Nummer, die Zahl', pos: 'noun', gender: 'm', plural: 'los números', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'Vivo en el número cuarenta y cinco.', german: 'Ich wohne in Nummer 45.' } },
    { id: `${L}.v.telefono`, target: 'el teléfono', german: 'das Telefon; die Telefonnummer', pos: 'noun', gender: 'm', plural: 'los teléfonos', emoji: '📞', field: 'Kommunikation', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.euro`, target: 'el euro', german: 'der Euro', pos: 'noun', gender: 'm', plural: 'los euros', emoji: '💶', field: 'Geld', stageId: 'stage0', lessonId: L, example: { target: 'Son tres euros.', german: 'Das macht drei Euro.' } },
    { id: `${L}.v.peso`, target: 'el peso', german: 'der Peso (Währung)', pos: 'noun', gender: 'm', plural: 'los pesos', emoji: '💵', variant: 'es-LA', field: 'Geld', stageId: 'stage0', lessonId: L, example: { target: 'Son cincuenta pesos.', german: 'Das macht 50 Pesos.' } },
  ],
  explanation: [
    {
      type: 'table',
      title: '0 bis 15 – einfach auswendig lernen',
      headers: ['Zahl', 'Spanisch', 'Zahl', 'Spanisch'],
      rows: [
        ['0', 'cero', '8', 'ocho'],
        ['1', 'uno', '9', 'nueve'],
        ['2', 'dos', '10', 'diez'],
        ['3', 'tres', '11', 'once'],
        ['4', 'cuatro', '12', 'doce'],
        ['5', 'cinco', '13', 'trece'],
        ['6', 'seis', '14', 'catorce'],
        ['7', 'siete', '15', 'quince'],
      ],
    },
    {
      type: 'table',
      title: '16 bis 100 – mit System',
      headers: ['Zahl', 'Spanisch', 'Muster'],
      rows: [
        ['16', 'dieciséis', 'dieci + seis (Akzent!)'],
        ['17', 'diecisiete', 'dieci + siete'],
        ['20', 'veinte', ''],
        ['21', 'veintiuno', 'veinti + uno'],
        ['22', 'veintidós', 'Akzent!'],
        ['23', 'veintitrés', 'Akzent!'],
        ['26', 'veintiséis', 'Akzent!'],
        ['30', 'treinta', ''],
        ['31', 'treinta y uno', 'Zehner + y + Einer'],
        ['40', 'cuarenta', ''],
        ['50', 'cincuenta', ''],
        ['60', 'sesenta', ''],
        ['70', 'setenta', ''],
        ['80', 'ochenta', ''],
        ['90', 'noventa', ''],
        ['100', 'cien', ''],
      ],
    },
    {
      type: 'text',
      md:
        '**16–19** und **21–29** schreibt man als ein Wort: `dieci-` bzw. `veinti-` + Einer: `diecisiete`, `veinticuatro`. Ab **31** sind es drei Wörter mit `y` (und): `treinta y uno`, `cuarenta y cinco`, `noventa y nueve`.\n' +
        '`uno` wird vor einem männlichen Nomen zu **un**, vor einem weiblichen zu **una**: `un euro`, `una casa`, `veintiún euros`, `treinta y una casas`.\n' +
        'Genau 100 heißt `cien`: `cien euros`.',
    },
    {
      type: 'compare',
      target: 'treinta y cinco',
      german: 'fünfunddreißig',
      md: 'Deutsch nennt zuerst die Einer („fünf-und-dreißig“), Spanisch liest wie die Ziffern von links nach rechts: erst der Zehner, dann der Einer – `treinta y cinco` = „dreißig und fünf“. Zahlendreher gibt es damit kaum noch.',
    },
    {
      type: 'mistake',
      wrong: 'veinte y uno',
      right: 'veintiuno',
      why: 'Von 21 bis 29 ist die Zahl **ein Wort** mit `veinti-`. Die Form mit `y` verwendet man erst ab 31: `treinta y uno` (`veinte y uno` ist veraltet). Umgekehrt ist `treintiuno` falsch.',
    },
    {
      type: 'text',
      md:
        '**Telefonnummern** liest man meist paarweise, oft mit der ersten Ziffer einzeln: 612 34 56 78 → `seis, doce, treinta y cuatro, cincuenta y seis, setenta y ocho`. Einzelne Ziffern (`seis, uno, dos …`) versteht man aber immer.\n' +
        '**Preise:** Beim Bezahlen hörst du `Son …` (Das macht …). In Spanien: 3,50 € → `tres euros con cincuenta` oder kurz `tres cincuenta`.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md:
        'In Lateinamerika zahlst du in der Landeswährung, z. B. in `pesos` (Mexiko, Kolumbien, Argentinien, Chile), `soles` (Peru) oder `dólares` (Ecuador). In Mexiko steht vor Peso-Preisen das Zeichen $ und man schreibt einen Dezimalpunkt: $45.50 → `cuarenta y cinco pesos con cincuenta`.',
    },
    {
      type: 'tip',
      md: 'Merksatz: **Bis 30 ein Wort, ab 31 mit `y`.** Einen Akzent tragen `dieciséis`, `veintidós`, `veintitrés`, `veintiséis` – und `veintiún` vor einem männlichen Nomen.',
    },
  ],
  examples: [
    { target: 'Son tres euros.', german: 'Das macht drei Euro.' },
    { target: 'Son veintiún euros.', german: 'Das macht 21 Euro.', note: 'Vor einem männlichen Nomen wird `veintiuno` zu `veintiún`.' },
    { target: 'Es el número quince.', german: 'Das ist die Nummer 15.' },
    { target: 'Somos dieciséis.', german: 'Wir sind zu sechzehnt.' },
    {
      target: 'Vivo en el número cuarenta y cinco.',
      german: 'Ich wohne in Nummer 45.',
      parts: [
        { text: 'Vivo', role: 'verb' },
        { text: ' ' },
        { text: 'en', role: 'preposition' },
        { text: ' ' },
        { text: 'el', role: 'article' },
        { text: ' ' },
        { text: 'número', role: 'noun' },
        { text: ' ' },
        { text: 'cuarenta', role: 'other' },
        { text: ' y ' },
        { text: 'cinco', role: 'other' },
        { text: '.' },
      ],
    },
    { target: 'El teléfono es el seis, doce, treinta y cuatro, cincuenta y seis, setenta y ocho.', german: 'Die Telefonnummer ist 612 34 56 78.' },
    { target: 'Son cinco euros con cincuenta.', german: 'Das macht 5,50 Euro.', variant: 'es-ES' },
    { target: 'Son setenta y cinco pesos.', german: 'Das macht 75 Pesos.', variant: 'es-LA' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary'],
      topicIds: ['es.g.numbers'],
      difficulty: 1,
      instruction: 'Ordne die Ziffern den Zahlwörtern zu.',
      pairs: [
        { left: '15', right: 'quince' },
        { left: '16', right: 'dieciséis' },
        { left: '21', right: 'veintiuno' },
        { left: '31', right: 'treinta y uno' },
        { left: '100', right: 'cien' },
      ],
      feedback: {
        rule: '11–15 sind eigene Wörter (`once` … `quince`), 16–29 zusammengesetzt (`dieciséis`, `veintiuno`), ab 31 mit `y` (`treinta y uno`).',
        why: '`quince` (15) und `cincuenta` (50) klingen für Anfänger ähnlich – beide enthalten „cin/quin“ für fünf.',
        avoid: 'Lerne die Reihe 11–15 als Block: once, doce, trece, catorce, quince.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['es.g.numbers'],
      difficulty: 1,
      audio: 'sesenta y siete',
      question: 'Welche Zahl hörst du?',
      options: ['67', '76', '77', '57'],
      answer: 0,
      feedback: {
        rule: 'Erst der Zehner, dann der Einer: `sesenta` (60) `y` `siete` (7) = 67.',
        why: '76 wäre `setenta y seis` – der deutsche Zahlendreher („sieben-und-sechzig“) führt hier in die Irre.',
        avoid: 'Schreib beim Hören einfach die Ziffern in der Reihenfolge mit, in der du sie hörst.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['pronunciation', 'listening'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      options: ['sesenta', 'setenta'],
      answer: 1,
      hint: '`sesenta` = 60 (mit s wie in `seis`), `setenta` = 70 (mit t wie in `siete`).',
      feedback: {
        rule: '60 = `sesenta` (se-SEN-ta), 70 = `setenta` (se-TEN-ta). Der Unterschied liegt nur im Mittelkonsonanten s/t.',
        why: 'Beide Wörter haben dieselbe Silbenzahl und Betonung – man hört sie leicht falsch.',
        avoid: 'Verknüpfe: seis → sesenta, siete → setenta.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'mc',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      prompt: 'Wie schreibt man **22**?',
      options: [
        { text: 'veinte y dos', why: 'Zwischen 21 und 29 schreibt man ein Wort ohne `y`.' },
        { text: 'veintidós' },
        { text: 'veintedos', why: 'Die Vorsilbe heißt `veinti-` (mit i), und `dós` trägt einen Akzent.' },
      ],
      answer: 1,
      feedback: {
        rule: '21–29: `veinti-` + Einer in einem Wort. 22, 23 und 26 tragen einen Akzent: `veintidós`, `veintitrés`, `veintiséis`.',
        why: '`veinte y dos` überträgt das Muster ab 31 auf die Zwanziger – diese Schreibung ist veraltet und heute nicht mehr üblich.',
        avoid: 'Bis 30 ein Wort, ab 31 mit y.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      instruction: 'Rechne und schreibe das Ergebnis als Wort.',
      sentence: 'Diez más seis son ___ y veinte más once son ___.',
      answers: [['dieciséis'], ['treinta y uno']],
      german: '10 + 6 = 16 und 20 + 11 = 31',
      feedback: {
        rule: '16 = `dieciséis` (ein Wort, Akzent auf é), 31 = `treinta y uno` (drei Wörter).',
        why: 'Häufig: `diez y seis` (veraltet) oder `treintiuno` (falsch). Die Grenze liegt bei 30.',
        avoid: 'Bei 16–29 alles zusammenschreiben, ab 31 Zehner + `y` + Einer.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      instruction: 'Schreibe die Zahl, die du hörst, in Buchstaben.',
      audio: 'treinta y ocho',
      answers: ['treinta y ocho'],
      german: '38',
      feedback: {
        rule: '38 = `treinta y ocho` – drei Wörter, alle klein.',
        why: 'Wer `treintiocho` schreibt, überträgt das Muster der Zwanziger. Ab 31 wird getrennt geschrieben.',
        avoid: 'Hör auf das kleine `y` in der Mitte – es zeigt dir, dass drei Wörter folgen.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.numbers'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Das macht 21 Euro.',
      answers: ['Son veintiún euros.'],
      feedback: {
        rule: 'Preisangabe mit `Son …`; vor einem männlichen Nomen wird `veintiuno` zu `veintiún`: `veintiún euros`.',
        why: '`veintiuno euros` klingt für Muttersprachler falsch – `uno` verkürzt sich vor männlichen Nomen immer (`un euro`, `veintiún euros`; weiblich: `veintiuna personas`). Und `Es` passt nicht zu einem Plural-Betrag.',
        avoid: 'Merke: uno + männliches Nomen → un. Das gilt auch in 21, 31, 41 …',
      },
    },
    {
      id: `${L}.g08`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.numbers'],
      difficulty: 3,
      audio: 'El teléfono es el seis, cuarenta y cinco, doce, noventa, treinta y tres.',
      question: 'Welche Telefonnummer hörst du?',
      options: ['6 45 12 90 33', '6 54 12 19 33', '6 45 02 90 23'],
      answer: 0,
      feedback: {
        rule: 'Telefonnummern werden meist paarweise gelesen: seis · cuarenta y cinco · doce · noventa · treinta y tres.',
        why: '54 wäre `cincuenta y cuatro`, 19 `diecinueve`, 23 `veintitrés` – jede Gruppe hat einen eigenen, klar unterscheidbaren Klang.',
        avoid: 'Notiere Gruppe für Gruppe – nicht erst am Ende die ganze Nummer.',
      },
    },
  ],
  pronunciation: ['es.p.cz.cinco', 'es.p.vowels.euro', 'es.p.r.tres'],
  application: [
    {
      id: `${L}.a01`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      prompt: 'Diktiere eine (ausgedachte) Telefonnummer auf Spanisch – Ziffer für Ziffer oder in Paaren.',
      keywords: ['cero', 'uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve', 'diez', 'once', 'doce', 'trece', 'catorce', 'quince', 'veinte', 'treinta', 'cuarenta', 'cincuenta', 'sesenta', 'setenta', 'ochenta', 'noventa'],
      minMatch: 4,
      sample: 'El teléfono es el seis, cero, dos, cuarenta y cinco, doce, treinta y ocho.',
      feedback: {
        rule: 'Nummern in Paaren: Zehner + `y` + Einer (`cuarenta y cinco`), einzelne Ziffern gehen immer.',
        why: 'Die Spracherkennung schreibt Zahlen oft als Ziffern; zählt dein Versuch nicht, sprich langsamer und mit kurzen Pausen zwischen den Gruppen.',
        avoid: 'Übe die schwierigen Laute: `cinco` und `doce` (c/z je nach Region wie englisches th oder s).',
      },
    },
    {
      id: `${L}.a02`,
      type: 'situation',
      skills: ['listening', 'vocabulary'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      variant: 'es-ES',
      scenario: 'Du bezahlst in einem Café in Madrid. Die Kellnerin sagt: `Son cuatro euros con setenta.` Wie viel legst du hin?',
      options: [
        { text: '4,70 €' },
        { text: '4,17 €', why: '17 hieße `diecisiete`.' },
        { text: '14,70 €', why: '14 hieße `catorce`.' },
        { text: '7,40 €', why: 'Zuerst kommen die Euro (`cuatro`), nach `con` die Cent (`setenta`).' },
      ],
      answer: 0,
      feedback: {
        rule: 'Preis = Euro + `con` + Cent: `cuatro euros con setenta` = 4,70 €.',
        why: 'setenta (70) und sesenta (60), cuatro (4) und catorce (14) werden leicht verwechselt.',
        avoid: 'Merke das Muster: … euros **con** … – was nach „con“ kommt, sind die Cent.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'situation',
      skills: ['listening', 'vocabulary'],
      topicIds: ['es.g.numbers'],
      difficulty: 2,
      variant: 'es-LA',
      scenario: 'Du bezahlst an einem Taco-Stand in Mexiko-Stadt. Der Verkäufer sagt: `Son ochenta y cinco pesos.` Wie viel kostet es?',
      options: [
        { text: '85 Pesos' },
        { text: '58 Pesos', why: '58 hieße `cincuenta y ocho`.' },
        { text: '95 Pesos', why: '95 hieße `noventa y cinco`.' },
        { text: '80,50 Pesos', why: 'Nach dem `y` folgt der Einer (5), nicht eine Kommastelle.' },
      ],
      answer: 0,
      feedback: {
        rule: '`ochenta` (80) + `y` + `cinco` (5) = 85.',
        why: '`ochenta` (80) und `ocho` (8) beginnen gleich – die Endung -enta zeigt den Zehner.',
        avoid: 'Zehner erkennst du an -enta/-inta (treinta, cuarenta … noventa).',
      },
    },
    {
      id: `${L}.a04`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['es.g.numbers'],
      difficulty: 3,
      prompt: 'Schreibe zwei Sätze mit Zahlen in Buchstaben: deine Hausnummer (`Vivo en el número …`) und eine ausgedachte Telefonnummer in Zweiergruppen.',
      requirements: [
        { pattern: 'n[uú]mero', hint: 'Verwende das Wort número.' },
        { pattern: '(once|doce|trece|catorce|quince|dieci|veint|treinta|cuarenta|cincuenta|sesenta|setenta|ochenta|noventa|cien)', hint: 'Schreibe mindestens eine Zahl ab 11 in Buchstaben aus.' },
      ],
      samples: ['Vivo en el número treinta y dos. El teléfono es el seis, doce, cuarenta y cinco, setenta y ocho, noventa.'],
      minWords: 8,
      feedback: {
        rule: '16–29 in einem Wort, ab 31 mit `y`; Akzent bei dieciséis, veintidós, veintitrés, veintiséis.',
        why: 'Häufige Fehler: `treintiuno`, `veintedos`, fehlende Akzente (`dieciseis`). Veraltet und heute unüblich: `diez y seis`, `veinte y uno`.',
        avoid: 'Kontrolliere jede Zahl mit der Regel „bis 30 ein Wort, ab 31 mit y“.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 1,
      verb: 'vivir',
      tense: 'Präsens',
      person: 'yo',
      answers: ['vivo'],
      sentence: '___ en el número veinte.',
      feedback: {
        rule: 'yo-Form regelmäßiger Verben: Stamm + **-o**: `vivo`.',
        why: '`vivir` ist der Infinitiv, `vive` die Form für er/sie.',
        avoid: 'Über dich selbst: immer -o.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'fixError',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 2,
      sentence: 'Nosotros comen en casa.',
      answers: ['Nosotros comemos en casa.', 'Comemos en casa.'],
      german: 'Wir essen zu Hause.',
      feedback: {
        rule: 'nosotros → **-emos** bei -er-Verben: `comemos`.',
        why: '`comen` ist die Form für ellos/ustedes.',
        avoid: 'wir = -mos. Diese Endung gilt in allen drei Verbgruppen.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.gender-plural'],
      difficulty: 2,
      instruction: 'Setze den Plural ein: lápiz, flor.',
      sentence: 'dos ___ y tres ___',
      answers: [['lápices'], ['flores']],
      german: 'zwei Bleistifte und drei Blumen',
      feedback: {
        rule: '-z → -ces (`lápices`), Konsonant → + es (`flores`).',
        why: '`lápizs` und `flors` sind im Spanischen nicht möglich.',
        avoid: 'Nach Konsonant immer -es, und aus z wird c.',
      },
    },
  ],
};

export default lesson;
