import type { Lesson } from '../../types';

const L = 'es.s0.l13';

const lesson: Lesson = {
  id: L,
  courseId: 'es',
  stageId: 'stage0',
  chapterId: 'es.s0.c5',
  order: 13,
  title: 'Einfache Fragen',
  subtitle: 'qué, quién, dónde, cómo, cuándo, cuánto, por qué',
  icon: '❓',
  minutes: 12,
  goal:
    'Du stellst einfache Fragen mit den wichtigsten Fragewörtern, setzt **¿ ?** und die Akzente richtig und unterscheidest **por qué** (warum) von **porque** (weil).',
  canDo: [
    'Ich kann Fragen mit qué, quién, dónde, de dónde, cómo, cuándo und cuánto stellen.',
    'Ich kann Ja/Nein-Fragen allein durch die Satzmelodie bilden.',
    'Ich passe cuánto an das Nomen an (cuántos años, cuántas personas).',
    'Ich unterscheide por qué (warum) und porque (weil).',
  ],
  topicIds: ['es.g.questions'],
  vocab: [
    { id: `${L}.v.que`, target: '¿qué?', german: 'was?', pos: 'pron', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Qué estudias?', german: 'Was studierst du?' } },
    { id: `${L}.v.quien`, target: '¿quién? / ¿quiénes?', german: 'wer? (Singular / Plural)', pos: 'pron', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Quién es?', german: 'Wer ist das?' } },
    { id: `${L}.v.donde`, target: '¿dónde?', german: 'wo?', pos: 'adv', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Dónde vives?', german: 'Wo wohnst du?' } },
    { id: `${L}.v.de-donde`, target: '¿de dónde?', german: 'woher?', pos: 'adv', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿De dónde eres?', german: 'Woher kommst du?' } },
    { id: `${L}.v.como`, target: '¿cómo?', german: 'wie?; wie bitte?', pos: 'adv', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Cómo te llamas?', german: 'Wie heißt du?' } },
    { id: `${L}.v.cuando`, target: '¿cuándo?', german: 'wann?', pos: 'adv', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Cuándo trabajas?', german: 'Wann arbeitest du?' } },
    { id: `${L}.v.cuanto`, target: '¿cuánto? / ¿cuánta?', german: 'wie viel?', pos: 'pron', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Cuánto es?', german: 'Wie viel macht das?' } },
    { id: `${L}.v.cuantos`, target: '¿cuántos? / ¿cuántas?', german: 'wie viele?', pos: 'pron', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Cuántos años tienes?', german: 'Wie alt bist du?' } },
    { id: `${L}.v.por-que`, target: '¿por qué?', german: 'warum?', pos: 'adv', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: '¿Por qué aprendes español?', german: 'Warum lernst du Spanisch?' } },
    { id: `${L}.v.porque`, target: 'porque', german: 'weil', pos: 'other', field: 'Fragewörter', stageId: 'stage0', lessonId: L, example: { target: 'Porque vivo en Barcelona.', german: 'Weil ich in Barcelona wohne.' } },
    { id: `${L}.v.pregunta`, target: 'la pregunta', german: 'die Frage', pos: 'noun', gender: 'f', plural: 'las preguntas', emoji: '❓', field: 'Verständigung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.respuesta`, target: 'la respuesta', german: 'die Antwort', pos: 'noun', gender: 'f', plural: 'las respuestas', emoji: '💬', field: 'Verständigung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.persona`, target: 'la persona', german: 'die Person, der Mensch', pos: 'noun', gender: 'f', plural: 'las personas', emoji: '🧑', field: 'Menschen', stageId: 'stage0', lessonId: L, example: { target: '¿Cuántas personas?', german: 'Wie viele Personen?' } },
    { id: `${L}.v.manana`, target: 'mañana', german: 'morgen', pos: 'adv', emoji: '🌅', field: 'Zeit', stageId: 'stage0', lessonId: L, example: { target: 'Trabajo mañana.', german: 'Ich arbeite morgen.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Spanische Fragen haben **zwei Fragezeichen**: ein umgedrehtes am Anfang und ein normales am Ende: `¿Dónde vives?` So weißt du beim Lesen sofort, dass eine Frage kommt.\n' +
        'Fragewörter tragen **immer einen Akzent**: `qué`, `quién`, `dónde`, `cómo`, `cuándo`, `cuánto`. Ohne Akzent sind es Verbindungswörter: `que` (dass), `donde` (wo – im Relativsatz), `como` (wie – im Vergleich), `porque` (weil).',
    },
    {
      type: 'table',
      title: 'Die wichtigsten Fragewörter',
      headers: ['Fragewort', 'Deutsch', 'Beispiel'],
      rows: [
        ['¿Qué?', 'Was?', '¿Qué estudias?'],
        ['¿Quién? / ¿Quiénes?', 'Wer? (Sg. / Pl.)', '¿Quién es? · ¿Quiénes son?'],
        ['¿Dónde?', 'Wo?', '¿Dónde vives?'],
        ['¿De dónde?', 'Woher?', '¿De dónde eres?'],
        ['¿Cómo?', 'Wie?', '¿Cómo te llamas?'],
        ['¿Cuándo?', 'Wann?', '¿Cuándo trabajas?'],
        ['¿Cuánto/-a/-os/-as?', 'Wie viel? Wie viele?', '¿Cuánto es? · ¿Cuántos años tienes?'],
        ['¿Por qué?', 'Warum?', '¿Por qué aprendes español?'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: '¿' },
        { text: 'De dónde', role: 'question' },
        { text: ' ' },
        { text: 'es', role: 'verb' },
        { text: ' ' },
        { text: 'Carlos', role: 'subject' },
        { text: '?' },
      ],
      german: 'Woher kommt Carlos?',
    },
    {
      type: 'text',
      md:
        'Nach dem Fragewort folgt meist direkt das **Verb**, das Subjekt steht dahinter: `¿Dónde vive Ana?` (Wo wohnt Ana?). Präpositionen stehen **vor** dem Fragewort – das deutsche „Wo kommst du her?“ wird zu `¿De dónde eres?`\n' +
        '**Ja/Nein-Fragen** brauchen oft gar keine Umstellung – nur die Satzmelodie ändert sich: `Vives en Madrid.` (Aussage, Stimme fällt) → `¿Vives en Madrid?` (Frage, Stimme **steigt** am Ende). Bei Fragen mit Fragewort fällt die Stimme am Ende meist wieder. `¿Cómo?` allein heißt übrigens auch „Wie bitte?“.',
    },
    {
      type: 'compare',
      target: '¿Por qué estudias español? – Porque vivo en Madrid.',
      german: 'Warum lernst du Spanisch? – Weil ich in Madrid wohne.',
      md: '**por qué** (zwei Wörter, Akzent) = warum; **porque** (ein Wort, kein Akzent) = weil. Nach `porque` bleibt die normale Wortstellung – das Verb wandert **nicht** ans Ende wie im deutschen Nebensatz.',
    },
    {
      type: 'mistake',
      wrong: '¿Cuánto años tienes?',
      right: '¿Cuántos años tienes?',
      why: '`cuánto` passt sich wie ein Adjektiv an sein Nomen an: `cuánto café` (m. Sg.), `cuánta leche` (f. Sg.), `cuántos años` (m. Pl.), `cuántas personas` (f. Pl.). Ohne Nomen fragt man nach Preis oder Menge einfach mit `¿Cuánto es?` (Wie viel macht das?).',
    },
    {
      type: 'tip',
      md: 'Merksatz: **Wer fragt, trägt einen Akzent.** Und schreib das `¿` gleich zu Beginn – so vergisst du es nicht. Auf dem Handy findest du ¿ und ¡ durch langes Drücken auf ? bzw. !.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Mexiko fragt man bei „Wie bitte?“ oft höflich `¿Mande?` – in Spanien und vielen anderen Ländern sagt man `¿Cómo?` oder `¿Perdón?`. Verstanden wird `¿Cómo?` überall.',
    },
  ],
  examples: [
    { target: '¿Cómo te llamas?', german: 'Wie heißt du?', literal: 'Wie nennst du dich?' },
    { target: '¿De dónde eres?', german: 'Woher kommst du?', literal: 'Von wo bist du?' },
    {
      target: '¿Dónde vive Ana?',
      german: 'Wo wohnt Ana?',
      parts: [
        { text: '¿' },
        { text: 'Dónde', role: 'question' },
        { text: ' ' },
        { text: 'vive', role: 'verb' },
        { text: ' ' },
        { text: 'Ana', role: 'subject' },
        { text: '?' },
      ],
    },
    { target: '¿Quiénes son ellos?', german: 'Wer sind sie?', note: 'Fragt man nach mehreren Personen, steht `quiénes` im Plural.' },
    { target: '¿Cuántas personas hablan español?', german: 'Wie viele Menschen sprechen Spanisch?', note: '`cuántas`, weil `la persona` feminin ist.' },
    { target: '¿Por qué aprendes español? – Porque vivo en Barcelona.', german: 'Warum lernst du Spanisch? – Weil ich in Barcelona wohne.' },
    { target: '¿Cuándo trabajas? – Mañana.', german: 'Wann arbeitest du? – Morgen.' },
    { target: '¿Hablas inglés?', german: 'Sprichst du Englisch?', note: 'Ja/Nein-Frage: keine Umstellung nötig – die Stimme steigt am Ende.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary'],
      topicIds: ['es.g.questions'],
      difficulty: 1,
      instruction: 'Ordne die Fragewörter ihrer Bedeutung zu.',
      pairs: [
        { left: '¿qué?', right: 'was?' },
        { left: '¿quién?', right: 'wer?' },
        { left: '¿dónde?', right: 'wo?' },
        { left: '¿cuándo?', right: 'wann?' },
        { left: '¿por qué?', right: 'warum?' },
      ],
      feedback: {
        rule: 'qué = was, quién = wer, dónde = wo, cuándo = wann, por qué = warum.',
        why: 'Leicht verwechselt: `qué` (was) und `quién` (wer) beginnen beide mit qu-; `cuándo` (wann) und `cuánto` (wie viel) unterscheiden sich nur durch d/t.',
        avoid: 'Lerne jedes Fragewort mit einer Mini-Frage: `¿Quién es?` – Wer ist das?',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar'],
      topicIds: ['es.g.questions'],
      difficulty: 1,
      prompt: 'Du willst wissen, woher jemand kommt. Welche Frage passt?',
      options: [
        { text: '¿Dónde eres?', why: 'Ohne `de` fehlt das „woher“ – die Frage ist so nicht korrekt.' },
        { text: '¿De dónde eres?' },
        { text: '¿Dónde vives?', why: 'Das fragt nach dem Wohnort (wo wohnst du?), nicht nach der Herkunft.' },
      ],
      answer: 1,
      feedback: {
        rule: 'woher = `de dónde`: Die Präposition `de` steht vor dem Fragewort. Herkunft → ser: `¿De dónde eres?`',
        why: 'Das deutsche „Wo … her?“ teilt das Fragewort auf – Spanisch hält `de dónde` zusammen und stellt es an den Anfang.',
        avoid: 'Die Antwort lautet `Soy de …` – das `de` aus der Antwort gehört auch in die Frage.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      sentence: '¿___ te llamas? – Me llamo Eva. ¿Y ___ vives? – En Colonia.',
      answers: [['cómo'], ['dónde']],
      bank: ['cómo', 'dónde', 'qué', 'cuándo', 'quién'],
      german: 'Wie heißt du? – Ich heiße Eva. Und wo wohnst du? – In Köln.',
      feedback: {
        rule: 'Nach dem Namen fragt man mit `¿Cómo te llamas?`, nach dem Wohnort mit `¿Dónde vives?`',
        why: '`¿Qué te llamas?` ist ein häufiger Fehler (beeinflusst vom englischen „What is your name?“). Spanisch fragt wie das Deutsche mit „wie“: `cómo`.',
        avoid: 'Schau auf die Antwort: Name → cómo; Ort → dónde; Zeit → cuándo.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar'],
      topicIds: ['es.g.questions', 'es.g.gender-plural'],
      difficulty: 2,
      sentence: '¿___ años tienes? ¿Y ___ personas viven en Madrid?',
      answers: [['cuántos'], ['cuántas']],
      bank: ['cuánto', 'cuánta', 'cuántos', 'cuántas'],
      german: 'Wie alt bist du? Und wie viele Menschen leben in Madrid?',
      feedback: {
        rule: '`cuánto` richtet sich nach dem Nomen: `años` (m. Pl.) → `cuántos`, `personas` (f. Pl.) → `cuántas`.',
        why: '`cuánto años` oder `cuántos personas` ignorieren Genus und Zahl des Nomens.',
        avoid: 'Behandle `cuánto` wie ein Adjektiv mit vier Formen – genau wie `rojo, roja, rojos, rojas`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      audio: '¿Por qué estudias español? Porque trabajo en Valencia.',
      question: 'Warum lernt die Person Spanisch?',
      options: ['Weil sie in Valencia arbeitet.', 'Weil sie in Valencia wohnt.', 'Weil sie aus Valencia kommt.'],
      answer: 0,
      feedback: {
        rule: '`porque trabajo en Valencia` = weil ich in Valencia arbeite. `porque` leitet die Begründung ein.',
        why: '„wohnt“ wäre `vivo`, „kommt aus“ wäre `soy de`.',
        avoid: 'Achte nach `porque` auf das Verb – es trägt die eigentliche Information.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      tokens: ['¿De', 'dónde', 'es', 'Carlos?'],
      extra: ['está'],
      german: 'Woher kommt Carlos?',
      feedback: {
        rule: 'Präposition + Fragewort – Verb – Subjekt: `¿De dónde es Carlos?`',
        why: '`está` beschreibt den Aufenthaltsort, nicht die Herkunft.',
        avoid: 'Bei Fragen mit Fragewort steht das Subjekt meist hinter dem Verb.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.questions'],
      difficulty: 3,
      instruction: 'Hier sind „warum“ und „weil“ vertauscht. Schreibe beides richtig.',
      sentence: '¿Porque aprendes español? – Por qué vivo en Madrid.',
      answers: ['¿Por qué aprendes español? – Porque vivo en Madrid.'],
      german: 'Warum lernst du Spanisch? – Weil ich in Madrid wohne.',
      feedback: {
        rule: 'warum = `por qué` (zwei Wörter, Akzent), weil = `porque` (ein Wort, ohne Akzent).',
        why: 'Beide klingen fast gleich – der Unterschied ist nur in der Schrift sichtbar (und in der Betonung von `qué`).',
        avoid: 'Fragt es? → Akzent und getrennt. Antwortet es? → zusammen und ohne Akzent.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.questions', 'es.g.present-regular'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Wo wohnt Pedro?',
      answers: ['¿Dónde vive Pedro?'],
      feedback: {
        rule: 'Fragewort – Verb – Subjekt: `¿Dónde vive Pedro?` Dazu ¿ am Anfang und Akzent auf `Dónde`.',
        why: '`¿Dónde está Pedro?` hieße „Wo ist Pedro (gerade)?“; `¿Dónde Pedro vive?` klingt mit dem Subjekt vor dem Verb unnatürlich.',
        avoid: 'Merke das Muster aus der Lektion: `¿Dónde vive Ana?`',
      },
    },
  ],
  pronunciation: ['es.p.into.de-donde-eres', 'es.p.into.como-te-llamas', 'es.p.ny.manana'],
  application: [
    {
      id: `${L}.a01`,
      type: 'dialogue',
      skills: ['grammar', 'reading'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      lines: [
        { speaker: 'Diego', text: 'Hola, me llamo Diego. ¿Y tú?', german: 'Hallo, ich heiße Diego. Und du?' },
        { speaker: 'Du', text: 'Me llamo Sara. ¿De dónde eres?', german: 'Ich heiße Sara. Woher kommst du?' },
        { speaker: 'Diego', text: 'Soy de Chile, de Santiago. ¿Y tú?', german: 'Ich komme aus Chile, aus Santiago. Und du?' },
        { speaker: 'Du', text: 'Soy de Alemania, de Leipzig.', german: 'Ich komme aus Deutschland, aus Leipzig.' },
      ],
      gapIndex: 1,
      options: ['Me llamo Sara. ¿De dónde eres?', 'Me llamo Sara. ¿Dónde eres?', 'Me llamo Sara. ¿Por qué eres?'],
      answer: 0,
      feedback: {
        rule: 'Nach der Herkunft fragt man mit `¿De dónde eres?` – Diegos Antwort `Soy de Chile` passt genau dazu.',
        why: '`¿Dónde eres?` ist unvollständig, `¿Por qué eres?` („Warum bist du?“) ergibt keinen Sinn.',
        avoid: 'Lies die Antwort des Partners: Sie verrät dir, welches Fragewort gefragt war.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      prompt: 'Du lernst jemanden kennen. Stelle laut drei Fragen: nach dem Namen, der Herkunft und dem Wohnort. Achte auf die Satzmelodie.',
      keywords: ['cómo', 'llamas', 'dónde', 'eres', 'vives'],
      minMatch: 3,
      sample: '¿Cómo te llamas? ¿De dónde eres? ¿Y dónde vives?',
      feedback: {
        rule: '`¿Cómo te llamas?` – `¿De dónde eres?` – `¿Dónde vives?`',
        why: 'Wird eine Frage nicht erkannt, fehlt oft ein Wort (`te` in „te llamas“ oder `de` in „de dónde“).',
        avoid: 'Sprich das Fragewort betont und lass die Stimme am Ende natürlich fallen.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['es.g.questions'],
      difficulty: 2,
      scenarioId: 'es.sc.alltag',
      goal: 'Stelle deinem Gesprächspartner mindestens drei Fragen (z. B. `¿Cómo te llamas?`, `¿De dónde eres?`, `¿Dónde vives?`) und beantworte seine Fragen.',
      turns: 6,
      feedback: {
        rule: 'Fragewort (mit Akzent) + Verb in der tú-Form: `¿Dónde vives?`, `¿Qué estudias?`',
        why: 'Im Gespräch fehlt leicht das `de` in `¿De dónde …?` oder die tú-Endung -s.',
        avoid: 'Hör auf die Fragen deines Partners – du kannst sie mit `¿Y tú?` einfach zurückgeben.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'translate',
      skills: ['grammar', 'writing'],
      topicIds: ['es.g.ser'],
      difficulty: 1,
      direction: 'toTarget',
      source: 'Ich komme aus Österreich.',
      answers: ['Soy de Austria.', 'Yo soy de Austria.', 'Soy austriaco.', 'Soy austriaca.', 'Soy austríaco.', 'Soy austríaca.', 'Yo soy austriaco.', 'Yo soy austriaca.'],
      feedback: {
        rule: 'Herkunft mit ser: `Soy de Austria.` oder mit Nationalität: `Soy austriaco/austriaca.`',
        why: '`Estoy de Austria` ist falsch – estar beschreibt nie die Herkunft.',
        avoid: 'Herkunft = Identität = ser.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'listening',
      skills: ['listening'],
      topicIds: ['es.g.numbers'],
      difficulty: 1,
      audio: 'setenta y cinco',
      question: 'Welche Zahl hörst du?',
      options: ['75', '57', '65', '76'],
      answer: 0,
      feedback: {
        rule: '`setenta` (70) + `y` + `cinco` (5) = 75.',
        why: '65 wäre `sesenta y cinco`, 57 `cincuenta y siete`.',
        avoid: 'setenta – siete (t), sesenta – seis (s).',
      },
    },
    {
      id: `${L}.r03`,
      type: 'conjugate',
      skills: ['grammar'],
      topicIds: ['es.g.present-regular'],
      difficulty: 1,
      verb: 'vivir',
      tense: 'Präsens',
      person: 'ella',
      answers: ['vive'],
      sentence: '¿Dónde ___ Ana?',
      feedback: {
        rule: '-ir-Verben, er/sie: Stamm + **-e**: `vive`.',
        why: '`vivo` heißt „ich wohne“, `viven` „sie wohnen“ – Ana ist eine einzelne Person.',
        avoid: '-er- und -ir-Verben: er/sie endet auf -e.',
      },
    },
  ],
};

export default lesson;
