import type { Lesson } from '../../types';

const L = 'pt.a1.l03';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'a1',
  chapterId: 'pt.a1.c1',
  order: 3,
  title: 'Como ele é? – Menschen beschreiben',
  subtitle: 'Aussehen & Charakter · Adjektive angleichen · muito, um pouco',
  icon: '🧑‍🦱',
  minutes: 12,
  goal:
    'Du kannst **Menschen beschreiben** – Aussehen und Charakter. Du lernst, wie sich Adjektive an Genus und Zahl anpassen (`alto/alta`, `legal/legais`, `feliz/felizes`), wo sie im Satz stehen und wie du mit `muito` und `um pouco` abstufst.',
  canDo: [
    'Ich kann mit „Como ele/ela é?“ nach einer Person fragen und sie beschreiben.',
    'Ich kann Adjektive in Genus und Zahl an das Nomen angleichen.',
    'Ich kann das Aussehen mit ter beschreiben (Ela tem olhos azuis).',
    'Ich kann Eigenschaften mit muito und um pouco abstufen.',
  ],
  topicIds: ['pt.g.adjectives'],
  vocab: [
    { id: `${L}.v.alto`, target: 'alto / alta', german: 'groß (Körpergröße), hoch', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Meu irmão é muito alto.', german: 'Mein Bruder ist sehr groß.' } },
    { id: `${L}.v.baixo`, target: 'baixo / baixa', german: 'klein (Körpergröße), niedrig', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Minha avó é baixa.', german: 'Meine Oma ist klein.' } },
    { id: `${L}.v.bonito`, target: 'bonito / bonita', german: 'schön, hübsch', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'A casa é muito bonita.', german: 'Das Haus ist sehr schön.' } },
    { id: `${L}.v.jovem`, target: 'jovem', german: 'jung', pos: 'adj', plural: 'jovens', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Meus tios são jovens.', german: 'Mein Onkel und meine Tante sind jung.' } },
    { id: `${L}.v.velho`, target: 'velho / velha', german: 'alt', pos: 'adj', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'O carro é velho.', german: 'Das Auto ist alt.' } },
    { id: `${L}.v.legal`, target: 'legal', german: 'nett, cool, toll', pos: 'adj', plural: 'legais', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Seus amigos são muito legais!', german: 'Deine Freunde sind echt nett!' } },
    { id: `${L}.v.engracado`, target: 'engraçado / engraçada', german: 'lustig, witzig', pos: 'adj', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Minha prima é muito engraçada.', german: 'Meine Cousine ist sehr lustig.' } },
    { id: `${L}.v.inteligente`, target: 'inteligente', german: 'intelligent, klug', pos: 'adj', plural: 'inteligentes', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Ela é inteligente e trabalhadora.', german: 'Sie ist klug und fleißig.' } },
    { id: `${L}.v.timido`, target: 'tímido / tímida', german: 'schüchtern', pos: 'adj', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Sou um pouco tímido.', german: 'Ich bin ein bisschen schüchtern.' } },
    { id: `${L}.v.trabalhador`, target: 'trabalhador / trabalhadora', german: 'fleißig', pos: 'adj', plural: 'trabalhadores / trabalhadoras', field: 'Charakter', stageId: 'a1', lessonId: L, example: { target: 'Meu pai é muito trabalhador.', german: 'Mein Vater ist sehr fleißig.' } },
    { id: `${L}.v.cabelo`, target: 'o cabelo', german: 'die Haare (im Portugiesischen meist Singular)', pos: 'noun', gender: 'm', emoji: '💇', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Ela tem cabelo castanho.', german: 'Sie hat braune Haare.' } },
    { id: `${L}.v.olhos`, target: 'os olhos', german: 'die Augen', pos: 'noun', gender: 'm', emoji: '👀', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Ele tem olhos verdes.', german: 'Er hat grüne Augen.' } },
    { id: `${L}.v.azul`, target: 'azul', german: 'blau', pos: 'adj', plural: 'azuis', emoji: '🔵', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Ela tem olhos azuis.', german: 'Sie hat blaue Augen.' } },
    { id: `${L}.v.castanho`, target: 'castanho / castanha', german: 'braun (Haare, Augen)', pos: 'adj', emoji: '🟤', field: 'Aussehen', stageId: 'a1', lessonId: L, example: { target: 'Tenho olhos castanhos.', german: 'Ich habe braune Augen.' } },
    { id: `${L}.v.muito`, target: 'muito', german: 'sehr (vor Adjektiven); viel, viele (vor Nomen: muitos, muitas)', pos: 'adv', field: 'Abstufung', stageId: 'a1', lessonId: L, example: { target: 'Ela é muito legal e tem muitos amigos.', german: 'Sie ist sehr nett und hat viele Freunde.' } },
    { id: `${L}.v.um-pouco`, target: 'um pouco', german: 'ein bisschen, etwas', pos: 'adv', field: 'Abstufung', stageId: 'a1', lessonId: L, example: { target: 'Ele é um pouco tímido.', german: 'Er ist ein bisschen schüchtern.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        '`Como ele é?` fragt, **wie jemand ist** – Aussehen und Charakter. Die Antwort bildest du mit `ser` + Adjektiv: `Ele é alto e simpático.`\n' +
        'Für Augen und Haare nimmst du `ter`: `Ela tem olhos azuis e cabelo castanho.`\n' +
        'Vorsicht: `Como ele está?` fragt dagegen, **wie es ihm geht** (`estar` = Befinden).',
    },
    {
      type: 'table',
      title: 'Adjektive passen sich an',
      headers: ['Endung', 'm. Sg.', 'f. Sg.', 'm. Pl.', 'f. Pl.'],
      rows: [
        ['-o / -a', 'alto', 'alta', 'altos', 'altas'],
        ['-or / -ora', 'trabalhador', 'trabalhadora', 'trabalhadores', 'trabalhadoras'],
        ['-e', 'inteligente', 'inteligente', 'inteligentes', 'inteligentes'],
        ['-l', 'legal', 'legal', 'legais', 'legais'],
        ['-z', 'feliz', 'feliz', 'felizes', 'felizes'],
        ['-m', 'jovem', 'jovem', 'jovens', 'jovens'],
      ],
    },
    {
      type: 'text',
      md:
        '`muito` vor einem Adjektiv heißt „sehr“ und ist **unveränderlich**: `Ela é muito alta.` · `Eles são muito legais.`\n' +
        'Vor einem Nomen heißt es „viel/viele“ und passt sich an: `muitos amigos`, `muitas fotos`.\n' +
        '`um pouco` = ein bisschen: `Sou um pouco tímido.` · `poucos/poucas` vor einem Nomen = wenige: `Tenho poucos amigos aqui.`',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Minha irmã', role: 'subject' },
        { text: ' ' },
        { text: 'é', role: 'verb' },
        { text: ' ' },
        { text: 'uma mulher', role: 'noun' },
        { text: ' ' },
        { text: 'muito', role: 'adverb' },
        { text: ' ' },
        { text: 'bonita', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Meine Schwester ist eine sehr schöne Frau.',
    },
    {
      type: 'compare',
      target: 'um homem alto · uma casa grande',
      german: 'ein großer Mann · ein großes Haus',
      md:
        'Im Portugiesischen steht das Adjektiv meist **hinter** dem Nomen. Seine Endung hängt nur von **Genus und Zahl** ab – nicht vom Fall wie im Deutschen („ein großer Mann“, „einen großen Mann“).\n' +
        'Achtung: Deutsches „groß“ bei Menschen (Körpergröße) = `alto`, „klein“ = `baixo`. `grande` und `pequeno` beschreiben die Größe von Dingen: `uma casa grande`, `um quarto pequeno`.',
    },
    {
      type: 'mistake',
      wrong: 'Ela é muita alta.',
      right: 'Ela é muito alta.',
      why: '`muito` vor einem Adjektiv bedeutet „sehr“ und verändert sich nie. Nur vor einem Nomen passt es sich an: `muitas amigas`.',
    },
    {
      type: 'tip',
      md: 'Merksatz: **Das Adjektiv läuft hinter dem Nomen her und zieht sich an wie das Nomen** (Genus, Zahl): `uma amiga alta`, `dois amigos altos`. Nur `muito` vor dem Adjektiv bleibt immer gleich.',
    },
    { type: 'audio', text: 'Como ela é? – Ela é alta, tem cabelo castanho e olhos azuis. E é muito legal!', label: 'Personenbeschreibung anhören' },
  ],
  examples: [
    { target: 'Como ele é? – Ele é alto, jovem e muito simpático.', german: 'Wie ist er? – Er ist groß, jung und sehr sympathisch.' },
    {
      target: 'Minha avó é baixa e muito engraçada.',
      german: 'Meine Oma ist klein und sehr lustig.',
      parts: [{ text: 'Minha avó', role: 'subject' }, { text: ' ' }, { text: 'é', role: 'verb' }, { text: ' ' }, { text: 'baixa', role: 'adjective' }, { text: ' e ' }, { text: 'muito', role: 'adverb' }, { text: ' ' }, { text: 'engraçada', role: 'adjective' }, { text: '.' }],
    },
    {
      target: 'Ela tem olhos azuis e cabelo castanho.',
      german: 'Sie hat blaue Augen und braune Haare.',
      parts: [{ text: 'Ela', role: 'subject' }, { text: ' ' }, { text: 'tem', role: 'verb' }, { text: ' ' }, { text: 'olhos', role: 'noun' }, { text: ' ' }, { text: 'azuis', role: 'adjective' }, { text: ' e ' }, { text: 'cabelo', role: 'noun' }, { text: ' ' }, { text: 'castanho', role: 'adjective' }, { text: '.' }],
      note: '`cabelo` steht meist im Singular – anders als „Haare“. `azul` wird im Plural zu `azuis`.',
    },
    {
      target: 'Meus amigos são muito legais.',
      german: 'Meine Freunde sind sehr nett.',
      note: '`legal` → `legais` (-l wird im Plural zu -is); `muito` bleibt unverändert. `legal` ist das brasilianische Alltagswort für „nett, cool, super“.',
    },
    { target: 'O Rafael é trabalhador e muito inteligente.', german: 'Rafael ist fleißig und sehr klug.' },
    {
      target: 'Sou um pouco tímida, mas aqui sou muito feliz.',
      german: 'Ich bin ein bisschen schüchtern, aber hier bin ich sehr glücklich.',
      note: 'Eine Frau sagt `tímida`, ein Mann `tímido`. `feliz` bleibt für beide gleich.',
    },
    {
      target: 'A casa é velha, mas é muito bonita.',
      german: 'Das Haus ist alt, aber sehr schön.',
      note: 'Über Menschen gesagt klingt `velho` schnell unhöflich. Höflicher: `mais velho` (älter) – `meu irmão mais velho` = mein älterer Bruder.',
    },
    {
      target: 'O Tiago é gente boa!',
      german: 'Tiago ist ein echt feiner Kerl!',
      note: 'Typisch brasilianisch: `gente boa` = ein netter, feiner Mensch. Die Wendung bleibt unverändert – auch für Frauen: `A Ana é gente boa.`',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.adjectives'],
      difficulty: 1,
      instruction: 'Ordne die Adjektive ihrer Bedeutung zu.',
      pairs: [
        { left: 'alto', right: 'groß (Person)' },
        { left: 'baixo', right: 'klein (Person)' },
        { left: 'jovem', right: 'jung' },
        { left: 'velho', right: 'alt' },
        { left: 'engraçado', right: 'lustig' },
        { left: 'trabalhador', right: 'fleißig' },
      ],
      feedback: {
        rule: 'alto ↔ baixo (Körpergröße), jovem ↔ velho (Alter), engraçado = lustig, trabalhador = fleißig.',
        why: '`alto` heißt bei Menschen „groß“ – nicht „alt“. „alt“ heißt `velho`.',
        avoid: 'Lerne Adjektive als Gegensatzpaare: alto/baixo, jovem/velho.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.adjectives'],
      difficulty: 1,
      prompt: 'Minha irmã é muito ___.',
      options: [
        { text: 'alto', why: '`alto` ist die männliche Form – `irmã` ist aber feminin.' },
        { text: 'alta' },
        { text: 'altas', why: '`altas` ist Plural – es geht um eine Schwester.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Das Adjektiv richtet sich nach dem Nomen: `minha irmã` (f. Sg.) → `alta`.',
        why: '`muito` davor ändert nichts – es bleibt immer `muito`, das Adjektiv passt sich trotzdem an.',
        avoid: 'Schau auf die Person: eine Frau → -a, ein Mann → -o, mehrere → -s.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.adjectives', 'pt.g.sounds'],
      difficulty: 2,
      options: ['bonito', 'bonita'],
      answer: 1,
      hint: 'Unbetontes -o am Wortende klingt wie ein kurzes „u“: `bonito` ≈ „bo-NI-tu“. Unbetontes -a bleibt ein schwaches „a“: `bonita` ≈ „bo-NI-ta“.',
      feedback: {
        rule: 'Am Wortende: -o → [u], -a → schwaches [a]. Daran hörst du, ob die Form männlich oder weiblich ist.',
        why: 'Die betonte Silbe `-ni-` ist in beiden Wörtern gleich – nur der Endvokal unterscheidet sie.',
        avoid: 'Hör genau auf den letzten Laut: „u“ = männlich, „a“ = weiblich.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.adjectives', 'pt.g.plural'],
      difficulty: 2,
      instruction: 'Setze die Adjektive in der richtigen Form ein: legal, feliz.',
      sentence: 'Meus pais são ___ e muito ___.',
      answers: [['legais'], ['felizes']],
      german: 'Meine Eltern sind nett und sehr glücklich.',
      feedback: {
        rule: 'Plural: -l → **-is** (`legal` → `legais`), -z → **-zes** (`feliz` → `felizes`).',
        why: '„legals“ oder „felizs“ gibt es nicht. Und `muito` bleibt vor dem Adjektiv unverändert.',
        avoid: 'Wie bei den Nomen: o hotel → os hotéis, a flor → as flores – Adjektive folgen denselben Pluralregeln.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.adjectives'],
      difficulty: 2,
      tokens: ['Tenho', 'uma', 'amiga', 'muito', 'engraçada.'],
      extra: ['muita'],
      german: 'Ich habe eine sehr lustige Freundin.',
      feedback: {
        rule: 'Nomen + `muito` + Adjektiv: `uma amiga muito engraçada`. Das Adjektiv steht hinter dem Nomen.',
        why: '`muita` wäre „viel“ vor einem Nomen – vor einem Adjektiv heißt „sehr“ immer `muito`.',
        avoid: 'Anders als im Deutschen: erst das Nomen (amiga), dann die Beschreibung (muito engraçada).',
      },
    },
    {
      id: `${L}.g06`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['pt.g.adjectives'],
      difficulty: 2,
      audio: 'Meu irmão é baixo e tem cabelo castanho. Ele é muito tímido.',
      question: 'Wie ist der Bruder?',
      options: ['groß und schüchtern', 'klein und schüchtern', 'klein und lustig'],
      answer: 1,
      feedback: {
        rule: '`baixo` = klein (Körpergröße), `tímido` = schüchtern.',
        why: '„groß“ wäre `alto`, „lustig“ wäre `engraçado`.',
        avoid: 'Lerne Adjektive als Gegensatzpaare – dann erkennst du auch das Gegenteil sofort.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.adjectives', 'pt.g.plural'],
      difficulty: 2,
      sentence: 'Ela tem olhos azul.',
      answers: ['Ela tem olhos azuis.', 'Ela tem os olhos azuis.'],
      german: 'Sie hat blaue Augen.',
      feedback: {
        rule: '`olhos` ist Plural → das Adjektiv auch: `azul` → `azuis`.',
        why: 'Im Deutschen ändert sich „blau“ nur je nach Fall. Im Portugiesischen muss das Adjektiv immer die Zahl des Nomens übernehmen.',
        avoid: 'Endet das Adjektiv auf -l, wird im Plural -is daraus: azul → azuis, legal → legais.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.adjectives', 'pt.g.possessives'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Mein Vater ist groß und sehr nett.',
      answers: [
        'Meu pai é alto e muito legal.',
        'O meu pai é alto e muito legal.',
        'Meu pai é alto e muito simpático.',
        'O meu pai é alto e muito simpático.',
        'Meu pai é alto e muito gentil.',
        'O meu pai é alto e muito gentil.',
      ],
      feedback: {
        rule: 'Körpergröße → `alto`; „sehr nett“ → `muito legal` oder `muito simpático`.',
        why: '`grande` beschreibt eher die Statur („kräftig, massig“) oder Dinge – für „groß gewachsen“ sagt man `alto`.',
        avoid: 'Menschen: alto/baixo. Dinge: grande/pequeno.',
      },
    },
  ],
  pronunciation: ['pt.p.l-final.alto', 'pt.p.l-final.legal'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.adjectives'],
      difficulty: 3,
      prompt: 'Beschreib eine Person, die dir wichtig ist – Aussehen und Charakter – in drei bis vier Sätzen.',
      requirements: [
        {
          pattern: '\\b(alt[oa]s?|baix[oa]s?|bonit[oa]s?|jove(m|ns)|velh[oa]s?|lega(l|is)|engraçad[oa]s?|inteligentes?|tímid[oa]s?|trabalhador(a|es|as)?|simpátic[oa]s?|feliz(es)?)\\b',
          hint: 'Verwende mindestens ein Adjektiv (z. B. alto, legal, engraçado).',
        },
        { pattern: '\\bmuito\\b', hint: 'Verwende „muito“ (sehr).' },
        { pattern: '\\b(tem|tenho)\\b.*\\b(olhos|cabelo)\\b', hint: 'Beschreib das Aussehen mit ter: „Ela tem olhos …“ oder „Ele tem cabelo …“.' },
      ],
      samples: ['Minha amiga Carla é alta e tem cabelo castanho e olhos azuis. Ela é muito engraçada e inteligente. É um pouco tímida, mas é muito legal.'],
      minWords: 15,
      feedback: {
        rule: 'Bausteine: … é + Adjektiv · … tem olhos/cabelo + Adjektiv · muito / um pouco + Adjektiv.',
        why: 'Häufige Fehler: `muita alta` statt `muito alta`, `olhos azul` statt `olhos azuis` und die männliche Endung bei einer Frau.',
        avoid: 'Prüfe jedes Adjektiv: Passt es in Genus und Zahl zu seinem Nomen?',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['pt.g.adjectives'],
      difficulty: 3,
      prompt: 'Beschreib dich selbst: Wie siehst du aus, wie bist du? Nutze ser, ter und muito oder um pouco.',
      keywords: ['sou', 'tenho', 'muito', 'pouco', 'olhos', 'cabelo', 'alto', 'alta', 'baixo', 'baixa'],
      minMatch: 3,
      sample: 'Sou alta, tenho cabelo castanho e olhos azuis. Sou um pouco tímida, mas sou muito trabalhadora.',
      feedback: {
        rule: 'Aussehen: `Sou alto/alta`, `Tenho olhos …`; Charakter: `Sou muito …` / `Sou um pouco …`.',
        why: 'Fehlen Schlüsselwörter, hat die Spracherkennung sie nicht gehört – oder sie fehlen in deiner Beschreibung.',
        avoid: 'Sprich das -l in `legal` und `alto` wie ein kurzes u: „le-GAU“, „AU-tu“.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'situation',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.adjectives', 'pt.g.ser-estar'],
      difficulty: 2,
      scenario: 'Deine brasilianische Freundin fragt: „Como é o seu irmão?“ Was antwortest du?',
      options: [
        { text: 'Ele é alto e muito engraçado.' },
        { text: 'Ele está bem, obrigado.', why: 'Das antwortet auf „Como ele está?“ – also wie es ihm geht, nicht wie er ist.' },
        { text: 'Ele é muito alta e engraçada.', why: 'Die Adjektive haben die weibliche Endung – dein Bruder ist aber ein Mann.' },
      ],
      answer: 0,
      feedback: {
        rule: '`Como ele é?` fragt nach Aussehen und Charakter → `ser` + Adjektiv in der passenden Form: `Ele é alto e muito engraçado.`',
        why: '`Como ele está?` (estar) wäre die Frage nach dem Befinden. Und zu `ele` gehören männliche Endungen.',
        avoid: 'é → wie jemand ist; está → wie es jemandem geht.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.tem-haver'],
      difficulty: 1,
      prompt: 'Onde ___ a cozinha? – Ao lado da sala.',
      options: [
        { text: 'tem', why: '`tem` = es gibt – damit fragst du nicht, wo ein bestimmter Raum liegt.' },
        { text: 'fica' },
        { text: 'têm', why: '`têm` heißt „sie haben“.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Wo liegt ein fester Ort? → `Onde fica …?`',
        why: '`tem` fragt, ob es etwas gibt – `a cozinha` ist aber ein bestimmter, bekannter Raum.',
        avoid: 'Gibt es das? → tem. Wo ist das? → fica.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.ter'],
      difficulty: 1,
      verb: 'ter',
      tense: 'Präsens',
      person: 'eu',
      sentence: 'Eu ___ três primos.',
      answers: ['tenho'],
      feedback: {
        rule: '`ter` ist unregelmäßig: eu **tenho**.',
        why: '`tem` ist die Form für você/ele/ela. „teno“ gibt es nicht – das nh gehört dazu.',
        avoid: 'tenho – mit nh wie in banheiro.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading', 'vocabulary'],
      topicIds: ['pt.g.estar', 'pt.g.contractions'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'O gato está no quarto.',
      answers: ['Die Katze ist im Schlafzimmer.', 'Die Katze ist im Zimmer.', 'Der Kater ist im Schlafzimmer.', 'Der Kater ist im Zimmer.', 'Die Katze liegt im Schlafzimmer.', 'Die Katze liegt im Zimmer.'],
      feedback: {
        rule: '`estar` + Ort: wo etwas gerade ist. `no quarto` = em + o quarto = im Schlafzimmer.',
        why: '`quarto` ist hier das Zimmer, nicht die Zahl vier (`quatro`).',
        avoid: 'quarto = Zimmer, quatro = vier.',
      },
    },
  ],
};

export default lesson;
