import type { Lesson } from '../../types';

const L = 'pt.a1.l04';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'a1',
  chapterId: 'pt.a1.c2',
  order: 4,
  title: 'A rotina – mein Tagesablauf',
  subtitle: 'eu me levanto · sempre, às vezes, nunca',
  icon: '⏰',
  minutes: 13,
  goal:
    'Du kannst deinen **Tagesablauf** beschreiben: aufwachen, aufstehen, duschen, frühstücken, arbeiten, schlafen gehen. Dazu lernst du die **reflexiven Verben** mit der brasilianischen Pronomenstellung (`eu me levanto`) und sagst mit `sempre`, `geralmente`, `às vezes` und `nunca`, wie oft du etwas tust.',
  canDo: [
    'Ich kann meinen Tagesablauf in einfachen Sätzen beschreiben.',
    'Ich kann reflexive Verben mit me, se und nos vor dem Verb verwenden (eu me levanto).',
    'Ich kann mit sempre, geralmente, às vezes und nunca sagen, wie oft ich etwas tue.',
    'Ich kenne die Sonderformen eu durmo und eu me visto.',
  ],
  topicIds: ['pt.g.reflexive'],
  vocab: [
    { id: `${L}.v.acordar`, target: 'acordar', german: 'aufwachen', pos: 'verb', emoji: '⏰', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Eu acordo cedo.', german: 'Ich wache früh auf.' } },
    { id: `${L}.v.levantar-se`, target: 'levantar-se', german: 'aufstehen (eu me levanto)', pos: 'verb', emoji: '🧍', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Eu me levanto cedo.', german: 'Ich stehe früh auf.' } },
    { id: `${L}.v.tomar-banho`, target: 'tomar banho', german: 'duschen', pos: 'phrase', emoji: '🚿', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Sempre tomo banho depois do trabalho.', german: 'Ich dusche immer nach der Arbeit.' } },
    { id: `${L}.v.escovar-os-dentes`, target: 'escovar os dentes', german: 'Zähne putzen', pos: 'phrase', emoji: '🪥', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Eu escovo os dentes três vezes por dia.', german: 'Ich putze mir dreimal am Tag die Zähne.' } },
    { id: `${L}.v.vestir-se`, target: 'vestir-se', german: 'sich anziehen (eu me visto)', pos: 'verb', emoji: '👕', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Eu me visto rápido.', german: 'Ich ziehe mich schnell an.' } },
    { id: `${L}.v.cafe-da-manha`, target: 'o café da manhã', german: 'das Frühstück (tomar café da manhã = frühstücken)', pos: 'noun', gender: 'm', emoji: '☕', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'Tomo café da manhã em casa.', german: 'Ich frühstücke zu Hause.' } },
    { id: `${L}.v.almocar`, target: 'almoçar', german: 'zu Mittag essen', pos: 'verb', emoji: '🍽️', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'A gente almoça no trabalho.', german: 'Wir essen auf der Arbeit zu Mittag.' } },
    { id: `${L}.v.jantar`, target: 'jantar', german: 'zu Abend essen; das Abendessen (o jantar)', pos: 'verb', emoji: '🍲', field: 'Essen', stageId: 'a1', lessonId: L, example: { target: 'Nós jantamos tarde.', german: 'Wir essen spät zu Abend.' } },
    { id: `${L}.v.deitar-se`, target: 'deitar-se', german: 'sich hinlegen, ins Bett gehen (eu me deito)', pos: 'verb', emoji: '🛏️', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Geralmente me deito tarde.', german: 'Normalerweise gehe ich spät ins Bett.' } },
    { id: `${L}.v.dormir`, target: 'dormir', german: 'schlafen (eu durmo)', pos: 'verb', emoji: '😴', field: 'Tagesablauf', stageId: 'a1', lessonId: L, example: { target: 'Eu durmo pouco.', german: 'Ich schlafe wenig.' } },
    { id: `${L}.v.cedo-tarde`, target: 'cedo · tarde', german: 'früh · spät', pos: 'adv', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Ele acorda cedo, mas se deita tarde.', german: 'Er wacht früh auf, geht aber spät ins Bett.' } },
    { id: `${L}.v.depois`, target: 'depois', german: 'danach, später', pos: 'adv', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Primeiro tomo banho, depois me visto.', german: 'Zuerst dusche ich, danach ziehe ich mich an.' } },
    { id: `${L}.v.sempre`, target: 'sempre', german: 'immer', pos: 'adv', field: 'Häufigkeit', stageId: 'a1', lessonId: L, example: { target: 'Eu sempre tomo café da manhã.', german: 'Ich frühstücke immer.' } },
    { id: `${L}.v.geralmente`, target: 'geralmente', german: 'normalerweise, meistens', pos: 'adv', field: 'Häufigkeit', stageId: 'a1', lessonId: L, example: { target: 'Geralmente eu almoço em casa.', german: 'Normalerweise esse ich zu Hause zu Mittag.' } },
    { id: `${L}.v.as-vezes`, target: 'às vezes', german: 'manchmal', pos: 'adv', field: 'Häufigkeit', stageId: 'a1', lessonId: L, example: { target: 'Às vezes eu me deito tarde.', german: 'Manchmal gehe ich spät ins Bett.' } },
    { id: `${L}.v.nunca`, target: 'nunca', german: 'nie', pos: 'adv', field: 'Häufigkeit', stageId: 'a1', lessonId: L, example: { target: 'Eu nunca me levanto tarde.', german: 'Ich stehe nie spät auf.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Ein reflexives Verb kennst du schon: `Me chamo Rafael.` Im Wörterbuch stehen solche Verben mit **-se**: `levantar-se` (aufstehen), `vestir-se` (sich anziehen), `deitar-se` (sich hinlegen, ins Bett gehen). Im brasilianischen Satz steht das Pronomen **vor dem Verb**: `eu me levanto`.\n' +
        'Nicht reflexiv sind dagegen `acordar` (aufwachen: `eu acordo`), `tomar banho` (duschen), `tomar café da manhã` (frühstücken), `almoçar`, `jantar` und `dormir`.\n' +
        'Zwei Verben haben bei **eu** eine Sonderform:\n' +
        '- `dormir` → `eu durmo` (aber `você dorme`, `nós dormimos`, `eles dormem`)\n' +
        '- `vestir-se` → `eu me visto` (aber `você se veste`, `nós nos vestimos`, `eles se vestem`)',
    },
    {
      type: 'conjugation',
      verb: 'levantar-se',
      translation: 'aufstehen',
      tense: 'Präsens',
      rows: [
        { person: 'eu', form: 'me levanto', ending: 'o' },
        { person: 'você / ele / ela / a gente', form: 'se levanta', ending: 'a' },
        { person: 'nós', form: 'nos levantamos', ending: 'amos' },
        { person: 'vocês / eles / elas', form: 'se levantam', ending: 'am' },
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Eu', role: 'subject' },
        { text: ' ' },
        { text: 'sempre', role: 'adverb' },
        { text: ' ' },
        { text: 'me', role: 'pronoun' },
        { text: ' ' },
        { text: 'levant', role: 'verb' },
        { text: 'o', role: 'ending' },
        { text: ' ' },
        { text: 'cedo', role: 'adverb' },
        { text: '.' },
      ],
      german: 'Ich stehe immer früh auf.',
    },
    {
      type: 'compare',
      target: 'Eu me levanto cedo. · Eu não me levanto cedo.',
      german: 'Ich stehe früh auf. · Ich stehe nicht früh auf.',
      md:
        'Im Deutschen steht „mich/sich“ **hinter** dem Verb („ich ziehe **mich** an“). Im brasilianischen Portugiesisch steht das Pronomen **direkt vor dem Verb** – auch nach `não`, `sempre` und `nunca`: `Ela nunca se deita cedo.`\n' +
        'Die Form mit Bindestrich (`levanto-me`) findest du in Wörterbüchern und sehr formellen Texten – im brasilianischen Alltag klingt sie steif.\n' +
        'Im lockeren Gespräch hörst du bei `levantar` auch oft `Eu levanto cedo` ganz ohne `me`. Mit `eu me levanto` liegst du aber immer richtig.',
    },
    {
      type: 'table',
      title: 'Wie oft? – Häufigkeitswörter',
      headers: ['Português', 'Deutsch', 'Beispiel'],
      rows: [
        ['sempre', 'immer', 'Eu sempre tomo café da manhã.'],
        ['geralmente', 'normalerweise, meistens', 'Geralmente eu almoço em casa.'],
        ['às vezes', 'manchmal', 'Às vezes eu me deito tarde.'],
        ['nunca', 'nie', 'Eu nunca me levanto tarde.'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Eu levanto me cedo.',
      right: 'Eu me levanto cedo.',
      why: 'Das deutsche „ich stehe auf“ / „ich ziehe mich an“ verleitet dazu, das Pronomen hinter das Verb zu setzen. Ohne Bindestrich ist `levanto me` immer falsch – in Brasilien gilt: **Pronomen vor das Verb**: `eu me levanto`, `você se veste`.',
    },
    {
      type: 'tip',
      md: 'Merksatz: **Die kleinen Wörter stehen vor dem Verb.** Pronomen (`me`, `se`, `nos`), Verneinung (`não`) und `sempre`/`nunca` kommen **vor** das Verb: `Eu não me levanto cedo.` · `Ela nunca se deita tarde.` `Geralmente` und `às vezes` stehen meist am Satzanfang.',
    },
    { type: 'audio', text: 'Eu acordo cedo, me levanto, tomo banho e tomo café da manhã.', label: 'Mein Morgen' },
  ],
  examples: [
    {
      target: 'Eu me levanto cedo e tomo banho.',
      german: 'Ich stehe früh auf und dusche.',
      parts: [{ text: 'Eu', role: 'subject' }, { text: ' ' }, { text: 'me', role: 'pronoun' }, { text: ' ' }, { text: 'levanto', role: 'verb' }, { text: ' ' }, { text: 'cedo', role: 'adverb' }, { text: ' e ' }, { text: 'tomo banho', role: 'verb' }, { text: '.' }],
    },
    {
      target: 'Geralmente eu acordo cedo, mas me levanto tarde.',
      german: 'Normalerweise wache ich früh auf, stehe aber spät auf.',
      note: '`acordar` = aufwachen (nicht reflexiv), `levantar-se` = aufstehen (reflexiv).',
    },
    {
      target: 'Minha filha se veste muito rápido.',
      german: 'Meine Tochter zieht sich sehr schnell an.',
      parts: [{ text: 'Minha filha', role: 'subject' }, { text: ' ' }, { text: 'se', role: 'pronoun' }, { text: ' ' }, { text: 'veste', role: 'verb' }, { text: ' ' }, { text: 'muito rápido', role: 'adverb' }, { text: '.' }],
    },
    { target: 'A gente se deita tarde e dorme pouco.', german: 'Wir gehen spät ins Bett und schlafen wenig.', note: '`a gente` verlangt die 3. Person: `se deita`, `dorme`.' },
    { target: 'Eu sempre durmo bem, mas nunca acordo cedo.', german: 'Ich schlafe immer gut, wache aber nie früh auf.', note: '`durmo` – Sonderform von `dormir` bei eu.' },
    { target: 'Às vezes ele almoça em casa.', german: 'Manchmal isst er zu Hause zu Mittag.' },
    {
      target: 'Ela não se levanta cedo: ela trabalha em casa.',
      german: 'Sie steht nicht früh auf – sie arbeitet zu Hause.',
      parts: [{ text: 'Ela', role: 'subject' }, { text: ' ' }, { text: 'não', role: 'negation' }, { text: ' ' }, { text: 'se', role: 'pronoun' }, { text: ' ' }, { text: 'levanta', role: 'verb' }, { text: ' ' }, { text: 'cedo', role: 'adverb' }, { text: ': ela trabalha em casa.' }],
    },
    { target: 'Primeiro eu tomo banho, depois me visto.', german: 'Zuerst dusche ich, danach ziehe ich mich an.', note: '`primeiro` = zuerst, `depois` = danach.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 1,
      pairs: [
        { emoji: '⏰', word: 'acordar' },
        { emoji: '🚿', word: 'tomar banho' },
        { emoji: '🪥', word: 'escovar os dentes' },
        { emoji: '👕', word: 'vestir-se' },
        { emoji: '🍽️', word: 'almoçar' },
        { emoji: '😴', word: 'dormir' },
      ],
      feedback: {
        rule: 'acordar = aufwachen, tomar banho = duschen, escovar os dentes = Zähne putzen, vestir-se = sich anziehen, almoçar = zu Mittag essen, dormir = schlafen.',
        why: '`acordar` (aufwachen) und `dormir` (schlafen) sind Gegensätze und werden leicht vertauscht.',
        avoid: 'Sprich beim Zuordnen einen Mini-Satz, z. B. „Eu tomo banho.“ – im Satz bleibt das Wort besser hängen.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 1,
      prompt: 'Wie sagt man in Brasilien natürlich: „Ich stehe auf.“?',
      options: [
        { text: 'Eu levanto me.', why: 'Ohne Bindestrich darf das Pronomen nicht hinter dem Verb stehen – und in Brasilien steht es ohnehin davor.' },
        { text: 'Eu me levanto.' },
        { text: 'Eu se levanto.', why: '`se` gehört zu você/ele/ela/a gente – zu `eu` passt nur `me`.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Brasilianische Stellung: Pronomen vor dem Verb – `eu me levanto`.',
        why: 'Das deutsche „ich stehe auf“ / „ich ziehe mich an“ verleitet dazu, das Pronomen hinter das Verb zu setzen.',
        avoid: 'eu → me, você/ele/ela → se, nós → nos – und immer vor das Verb.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 2,
      sentence: 'Eu ___ levanto cedo, mas o Pedro ___ levanta tarde. Depois nós ___ vestimos rápido.',
      answers: [['me'], ['se'], ['nos']],
      bank: ['me', 'se', 'nos', 'eu', 'ele'],
      german: 'Ich stehe früh auf, aber Pedro steht spät auf. Danach ziehen wir uns schnell an.',
      feedback: {
        rule: 'Reflexivpronomen je Person: eu → `me`, você/ele/ela → `se`, nós → `nos`, vocês/eles → `se`.',
        why: '`eu` und `ele` sind Subjektpronomen – vor das Verb gehört hier aber das Reflexivpronomen.',
        avoid: 'Frag zuerst: Wer tut es? eu → **me**, o Pedro (= ele) → **se**, nós → **nos**.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 2,
      verb: 'vestir-se',
      tense: 'Präsens',
      person: 'eu',
      sentence: 'Eu ___ rápido.',
      answers: ['me visto'],
      feedback: {
        rule: '`vestir-se` hat bei eu eine Sonderform: `eu me visto` (aber `você se veste`, `nós nos vestimos`).',
        why: 'Das e im Stamm wird nur bei eu zu i. `me veste` gibt es nicht – `se veste` wäre die Form für você/ele/ela.',
        avoid: 'Lern das Paar: **me visto – se veste**. Genauso bei dormir: **durmo – dorme**.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 2,
      tokens: ['Eu', 'nunca', 'me', 'levanto', 'tarde.'],
      extra: ['se'],
      german: 'Ich stehe nie spät auf.',
      feedback: {
        rule: 'Reihenfolge: Subjekt – nunca – Pronomen – Verb – Rest: `Eu nunca me levanto tarde.`',
        why: '`se` passt nicht zu `eu`. Und `nunca` steht vor Pronomen und Verb – nicht dahinter wie im Deutschen („stehe nie“).',
        avoid: 'Die kleinen Wörter (não, nunca, me) stehen vor dem Verb.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 2,
      audio: 'Eu sempre tomo café da manhã, mas nunca almoço em casa.',
      question: 'Was stimmt?',
      options: [
        'Die Person frühstückt immer, isst aber nie zu Hause zu Mittag.',
        'Die Person frühstückt nie, isst aber immer zu Hause zu Mittag.',
        'Die Person frühstückt manchmal und isst oft zu Hause zu Mittag.',
      ],
      answer: 0,
      feedback: {
        rule: '`sempre` = immer, `nunca` = nie; `tomar café da manhã` = frühstücken, `almoçar` = zu Mittag essen.',
        why: 'Die anderen Antworten vertauschen `sempre` und `nunca` oder machen daraus „manchmal/oft“ (`às vezes`, `geralmente`).',
        avoid: 'Achte beim Hören auf das Wort direkt vor dem Verb – dort stehen sempre und nunca.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 3,
      sentence: 'Eu não levanto me cedo.',
      answers: ['Eu não me levanto cedo.', 'Não me levanto cedo.', 'Eu não levanto cedo.', 'Não levanto cedo.'],
      german: 'Ich stehe nicht früh auf.',
      feedback: {
        rule: 'In Brasilien steht das Pronomen vor dem Verb – auch nach `não`: `Eu não me levanto cedo.`',
        why: '`levanto me` (Pronomen ohne Bindestrich hinter dem Verb) gibt es nicht. Umgangssprachlich geht bei levantar auch `Eu não levanto cedo` ohne `me`.',
        avoid: 'Merk dir die Kette: **não + me + Verb**.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Ich stehe immer früh auf, aber ich schlafe wenig.',
      answers: [
        'Eu sempre me levanto cedo, mas durmo pouco.',
        'Eu sempre me levanto cedo, mas eu durmo pouco.',
        'Sempre me levanto cedo, mas durmo pouco.',
        'Sempre me levanto cedo, mas eu durmo pouco.',
        'Eu me levanto sempre cedo, mas durmo pouco.',
        'Eu me levanto sempre cedo, mas eu durmo pouco.',
        'Eu sempre levanto cedo, mas durmo pouco.',
        'Eu sempre levanto cedo, mas eu durmo pouco.',
        'Sempre levanto cedo, mas durmo pouco.',
      ],
      feedback: {
        rule: '`levantar-se` → `eu me levanto`, `dormir` → `eu durmo` (Sonderform). `sempre` steht vor Pronomen und Verb.',
        why: 'Häufige Fehler: `dormo` statt `durmo`, `levanto me` statt `me levanto` und `um pouco` („ein bisschen“) statt `pouco` („wenig“).',
        avoid: 'Bau den Satz Stück für Stück: Eu – sempre – me levanto – cedo, mas – durmo – pouco.',
      },
    },
  ],
  pronunciation: ['pt.p.rhythm.eu-me-levanto', 'pt.p.lh-nh.banheiro', 'pt.p.d-t.dia'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 3,
      prompt: 'Beschreibe deinen typischen Tag in 4–5 Sätzen. Nutze mindestens ein reflexives Verb (`me levanto`, `me visto`, `me deito`) und zwei Häufigkeitswörter (`sempre`, `geralmente`, `às vezes`, `nunca`).',
      requirements: [
        { pattern: '\\bme (levanto|visto|deito)\\b', hint: 'Nutze ein reflexives Verb mit „me“ vor dem Verb, z. B. „me levanto“.' },
        { pattern: '(sempre|geralmente|vezes|nunca).*(sempre|geralmente|vezes|nunca)', hint: 'Nutze mindestens zwei Häufigkeitswörter (sempre, geralmente, às vezes, nunca).' },
        { pattern: '\\b(acordo|tomo|almoço|almoco|janto|trabalho|durmo|escovo)\\b', hint: 'Beschreibe weitere Tätigkeiten in der eu-Form, z. B. „acordo“, „tomo banho“, „almoço“, „durmo“.' },
      ],
      samples: ['Geralmente eu acordo cedo, mas me levanto tarde. Primeiro tomo banho e me visto. Depois tomo café da manhã em casa. Às vezes almoço no trabalho. Eu nunca me deito cedo, mas durmo bem.'],
      minWords: 20,
      feedback: {
        rule: 'Beschreibe deinen Tag in der eu-Form: acordo, me levanto, tomo banho, me visto, almoço, janto, me deito, durmo.',
        why: 'Typische Fehler: `levanto me` statt `me levanto`, `dormo` statt `durmo` und ein überflüssiges `me` bei `acordo` (aufwachen ist nicht reflexiv).',
        avoid: 'Erzähl der Reihe nach mit `primeiro …, depois …` – so vergisst du keinen Schritt.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 3,
      prompt: 'Erzähl laut, wie dein Morgen aussieht: Wachst du früh auf? Was machst du zuerst, was danach?',
      keywords: ['acordo', 'me levanto', 'tomo banho', 'me visto', 'café da manhã', 'sempre', 'geralmente', 'depois'],
      minMatch: 3,
      sample: 'Geralmente eu acordo cedo. Primeiro me levanto e tomo banho, depois me visto e tomo café da manhã.',
      feedback: {
        rule: 'Nutze mindestens drei Bausteine: acordo, me levanto, tomo banho, me visto, café da manhã, sempre, geralmente, depois.',
        why: 'Fehlen Schlüsselwörter, hat die Spracherkennung sie nicht gehört – oder sie fehlen in deiner Antwort.',
        avoid: 'Sprich `me` wie „mi“ und hänge es eng an das Verb: „mi-le-WÃN-tu“.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'dialogue',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 2,
      instruction: 'Luana antwortet auf Toms Frage. Was sagt sie?',
      lines: [
        { speaker: 'Luana', text: 'Você acorda cedo?', german: 'Wachst du früh auf?' },
        { speaker: 'Tom', text: 'Sim, eu sempre acordo cedo. E você?', german: 'Ja, ich wache immer früh auf. Und du?' },
        { speaker: 'Luana', text: '…' },
        { speaker: 'Tom', text: 'Que sorte!', german: 'Was für ein Glück!' },
      ],
      gapIndex: 2,
      options: [
        'Eu não. Trabalho em casa, então levanto me tarde.',
        'Eu não. Trabalho em casa, então se levanto tarde.',
        'Eu não. Trabalho em casa, então me levanto tarde.',
      ],
      answer: 2,
      feedback: {
        rule: 'Mit eu: `me levanto` – das Pronomen steht vor dem Verb. (`então` = also, deshalb)',
        why: '`levanto me` hat das Pronomen an der falschen Stelle, `se levanto` die falsche Person.',
        avoid: 'eu und me gehören zusammen – denk sie immer als Paar.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.reflexive'],
      difficulty: 3,
      scenarioId: 'pt.sc.alltag',
      goal: 'Erzähl deiner neuen Nachbarin von deinem Alltag: ob du früh aufwachst, wann du aufstehst und was du morgens machst. Nutze `sempre`, `geralmente` oder `nunca` – und frag zurück: `E você? Você acorda cedo?`',
      turns: 5,
      feedback: {
        rule: 'Tagesablauf in der eu-Form mit reflexiven Verben (me levanto, me visto) und Häufigkeitswörtern.',
        avoid: 'Stell auch Gegenfragen – mit você und der 3. Person: `Você se levanta cedo?`',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'translate',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.reflexive', 'pt.g.possessives'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'Minha irmã se levanta cedo, mas nunca toma café da manhã.',
      answers: [
        'Meine Schwester steht früh auf, frühstückt aber nie.',
        'Meine Schwester steht früh auf, aber sie frühstückt nie.',
        'Meine Schwester steht früh auf, aber frühstückt nie.',
        'Meine Schwester steht früh auf, isst aber nie Frühstück.',
      ],
      feedback: {
        rule: '`minha irmã` = meine Schwester; `se levanta` = steht auf; `nunca toma café da manhã` = frühstückt nie.',
        why: '`tomar café da manhã` ist eine feste Wendung für „frühstücken“ – nicht „Kaffee trinken am Morgen“.',
        avoid: 'Übersetze feste Wendungen als Ganzes: tomar banho = duschen, tomar café da manhã = frühstücken.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.adjectives'],
      difficulty: 1,
      prompt: 'Meus irmãos são muito ___.',
      options: [
        { text: 'alto', why: 'Singular – `meus irmãos` ist Plural.' },
        { text: 'altas', why: 'Feminin – `irmãos` ist maskulin.' },
        { text: 'altos' },
      ],
      answer: 2,
      feedback: {
        rule: 'Adjektive richten sich in Genus und Zahl nach dem Nomen: `meus irmãos` (m. Pl.) → `altos`.',
        why: 'Im Deutschen bleibt das Adjektiv nach „sein“ unverändert („sie sind groß“) – im Portugiesischen nicht.',
        avoid: 'Schau auf das Nomen: männlich/weiblich? Einzahl/Mehrzahl? Dann -o, -a, -os oder -as.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.tem-haver'],
      difficulty: 2,
      sentence: 'No meu quarto ___ uma cama e uma mesa.',
      answers: [['tem', 'há']],
      german: 'In meinem Zimmer gibt es ein Bett und einen Tisch.',
      feedback: {
        rule: '„es gibt“ heißt im brasilianischen Alltag `tem` (formeller: `há`).',
        why: '`é` oder `está` sagen, was etwas ist oder wo es sich befindet – nicht, dass es etwas gibt.',
        avoid: 'es gibt = tem – unveränderlich, auch im Plural: `tem duas camas`.',
      },
    },
  ],
};

export default lesson;
