import type { Lesson } from '../../types';

const L = 'pt.a1.l02';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'a1',
  chapterId: 'pt.a1.c1',
  order: 2,
  title: 'Minha casa – mein Zuhause',
  subtitle: 'Zimmer & Möbel · tem = es gibt · fica, perto de, ao lado de',
  icon: '🏠',
  minutes: 13,
  goal:
    'Du kannst deine **Wohnung beschreiben**: welche Zimmer und Möbel es gibt, wo sich etwas befindet und was in der Nähe liegt. Du lernst das brasilianische `tem` = „es gibt“, `ficar` für feste Orte und die Ortsangaben `perto de`, `ao lado de` und `em frente de`.',
  canDo: [
    'Ich kann Zimmer und Möbel benennen.',
    'Ich kann mit tem sagen, was es gibt (Na sala tem um sofá).',
    'Ich kann mit fica und está sagen, wo etwas ist, und nach dem Bad fragen.',
    'Ich kann perto de, ao lado de und em frente de mit do/da verbinden.',
  ],
  topicIds: ['pt.g.tem-haver', 'pt.g.contractions'],
  vocab: [
    { id: `${L}.v.apartamento`, target: 'o apartamento', german: 'die Wohnung (in einem Gebäude)', pos: 'noun', gender: 'm', plural: 'apartamentos', emoji: '🏢', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Meu apartamento tem dois quartos.', german: 'Meine Wohnung hat zwei Schlafzimmer.' } },
    { id: `${L}.v.quarto`, target: 'o quarto', german: 'das Schlafzimmer, das Zimmer', pos: 'noun', gender: 'm', plural: 'quartos', emoji: '🛌', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'O quarto fica ao lado do banheiro.', german: 'Das Schlafzimmer liegt neben dem Bad.' } },
    { id: `${L}.v.sala`, target: 'a sala', german: 'das Wohnzimmer', pos: 'noun', gender: 'f', plural: 'salas', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Na sala tem um sofá.', german: 'Im Wohnzimmer gibt es ein Sofa.' } },
    { id: `${L}.v.cozinha`, target: 'a cozinha', german: 'die Küche', pos: 'noun', gender: 'f', plural: 'cozinhas', emoji: '🍳', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Na cozinha tem uma mesa.', german: 'In der Küche gibt es einen Tisch.' } },
    { id: `${L}.v.banheiro`, target: 'o banheiro', german: 'das Badezimmer, die Toilette', pos: 'noun', gender: 'm', plural: 'banheiros', emoji: '🚿', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Onde fica o banheiro?', german: 'Wo ist das Bad / die Toilette?' } },
    { id: `${L}.v.varanda`, target: 'a varanda', german: 'der Balkon, die Veranda', pos: 'noun', gender: 'f', plural: 'varandas', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'O apartamento não tem varanda.', german: 'Die Wohnung hat keinen Balkon.' } },
    { id: `${L}.v.cama`, target: 'a cama', german: 'das Bett', pos: 'noun', gender: 'f', plural: 'camas', emoji: '🛏️', field: 'Möbel', stageId: 'a1', lessonId: L, example: { target: 'O gato está na cama.', german: 'Die Katze ist auf dem Bett.' } },
    { id: `${L}.v.sofa`, target: 'o sofá', german: 'das Sofa', pos: 'noun', gender: 'm', plural: 'sofás', emoji: '🛋️', field: 'Möbel', stageId: 'a1', lessonId: L, example: { target: 'O sofá está na sala.', german: 'Das Sofa steht im Wohnzimmer.' } },
    { id: `${L}.v.armario`, target: 'o armário', german: 'der Schrank', pos: 'noun', gender: 'm', plural: 'armários', emoji: '🗄️', field: 'Möbel', stageId: 'a1', lessonId: L, example: { target: 'Tem um armário no quarto.', german: 'Im Schlafzimmer gibt es einen Schrank.' } },
    { id: `${L}.v.janela`, target: 'a janela', german: 'das Fenster', pos: 'noun', gender: 'f', plural: 'janelas', emoji: '🪟', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'A sala tem duas janelas.', german: 'Das Wohnzimmer hat zwei Fenster.' } },
    { id: `${L}.v.praia`, target: 'a praia', german: 'der Strand', pos: 'noun', gender: 'f', plural: 'praias', emoji: '🏖️', field: 'Umgebung', stageId: 'a1', lessonId: L, example: { target: 'Moro perto da praia.', german: 'Ich wohne in der Nähe vom Strand.' } },
    { id: `${L}.v.ficar`, target: 'ficar', german: 'liegen, sich befinden (Ort); auch: bleiben', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'A cozinha fica ao lado da sala.', german: 'Die Küche liegt neben dem Wohnzimmer.' } },
    { id: `${L}.v.tem`, target: 'tem …', german: 'es gibt …', pos: 'phrase', field: 'Wohnen', stageId: 'a1', lessonId: L, example: { target: 'Tem um mercado perto daqui?', german: 'Gibt es hier in der Nähe einen Supermarkt?' } },
    { id: `${L}.v.perto-de`, target: 'perto de', german: 'in der Nähe von, nah bei', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'Moro perto do centro.', german: 'Ich wohne in der Nähe vom Zentrum.' } },
    { id: `${L}.v.ao-lado-de`, target: 'ao lado de', german: 'neben', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'O banheiro fica ao lado da cozinha.', german: 'Das Bad liegt neben der Küche.' } },
    { id: `${L}.v.em-frente-de`, target: 'em frente de', german: 'gegenüber von, vor', pos: 'prep', field: 'Ortsangaben', stageId: 'a1', lessonId: L, example: { target: 'Meu apartamento fica em frente do parque.', german: 'Meine Wohnung liegt gegenüber vom Park.' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        '`tem` heißt in Brasilien nicht nur „hat“, sondern auch **„es gibt“**:\n' +
        '- `Na minha casa tem dois banheiros.` – In meinem Haus gibt es zwei Bäder.\n' +
        '- `Tem um mercado perto daqui?` – Gibt es hier in der Nähe einen Supermarkt?\n' +
        '- `Não tem janela no banheiro.` – Im Bad gibt es kein Fenster.\n' +
        'In Büchern, Nachrichten und Formularen liest du dafür `há` (von haver): `Há dois quartos.` Das solltest du verstehen – im Gespräch sagen Brasilianer aber fast immer `tem`.',
    },
    {
      type: 'compare',
      target: 'Tem dois quartos no apartamento.',
      german: 'Es gibt zwei Schlafzimmer in der Wohnung.',
      md:
        'Genau wie „es gibt“ hat `tem` in dieser Bedeutung **kein Subjekt** und bleibt **immer im Singular** – auch bei mehreren Dingen: `tem dois quartos`. Nach `não tem` fällt der Artikel meist weg: `Não tem varanda.`',
    },
    {
      type: 'table',
      title: 'Gibt es …? oder Wo ist …?',
      headers: ['Du willst sagen …', 'Verb', 'Beispiel'],
      rows: [
        ['dass es etwas gibt (neu, unbestimmt: um/uma, Zahl)', 'tem', 'Tem um sofá na sala.'],
        ['wo ein fester Ort liegt (Zimmer, Gebäude, Stadt)', 'ficar', 'O banheiro fica ao lado do quarto.'],
        ['wo etwas Bewegliches gerade ist (Dinge, Personen, Tiere)', 'estar', 'O gato está no sofá.'],
      ],
    },
    {
      type: 'conjugation',
      verb: 'ficar',
      translation: 'liegen, sich befinden (Ort)',
      tense: 'Präsens',
      rows: [
        { person: 'eu', form: 'fico', ending: 'o' },
        { person: 'você / ele / ela / a gente', form: 'fica', ending: 'a' },
        { person: 'nós', form: 'ficamos', ending: 'amos' },
        { person: 'vocês / eles / elas', form: 'ficam', ending: 'am' },
      ],
    },
    {
      type: 'table',
      title: 'Wo? – Ortsangaben mit em und de',
      headers: ['Präposition', '+ o', '+ a', 'Beispiel'],
      rows: [
        ['em – in, auf', 'no', 'na', 'O livro está na mesa.'],
        ['perto de – in der Nähe von', 'perto do', 'perto da', 'Moro perto da praia.'],
        ['ao lado de – neben', 'ao lado do', 'ao lado da', 'A cozinha fica ao lado da sala.'],
        ['em frente de – gegenüber, vor', 'em frente do', 'em frente da', 'O mercado fica em frente do parque.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'A cozinha', role: 'subject' },
        { text: ' ' },
        { text: 'fica', role: 'verb' },
        { text: ' ' },
        { text: 'ao lado da', role: 'preposition' },
        { text: ' ' },
        { text: 'sala', role: 'noun' },
        { text: '.' },
      ],
      german: 'Die Küche liegt neben dem Wohnzimmer.',
    },
    {
      type: 'mistake',
      wrong: 'Na sala têm duas janelas.',
      right: 'Na sala tem duas janelas.',
      why: '`tem` = „es gibt“ bleibt immer Singular – genau wie im Deutschen („es gibt zwei Fenster“, nicht „es geben“). `têm` ist die ter-Form für eles/elas („sie haben“): `Meus pais têm uma casa.`',
    },
    {
      type: 'tip',
      md: 'Merksatz: **Gibt es das? → `tem`. Wo ist das? → `fica` (fester Ort) oder `está` (beweglich).** Und `de`/`em` verschmelzen mit dem Artikel: ao lado **do** quarto, perto **da** praia, **no** sofá, **na** sala.',
    },
  ],
  examples: [
    {
      target: 'Na minha casa tem três quartos e dois banheiros.',
      german: 'In meinem Haus gibt es drei Schlafzimmer und zwei Bäder.',
      parts: [{ text: 'Na', role: 'preposition' }, { text: ' ' }, { text: 'minha casa', role: 'noun' }, { text: ' ' }, { text: 'tem', role: 'verb' }, { text: ' ' }, { text: 'três quartos', role: 'object' }, { text: ' e ' }, { text: 'dois banheiros', role: 'object' }, { text: '.' }],
    },
    {
      target: 'Tem um mercado perto daqui?',
      german: 'Gibt es hier in der Nähe einen Supermarkt?',
      note: '`daqui` = de + aqui (von hier). `mercado` ist in Brasilien der Supermarkt um die Ecke.',
    },
    {
      target: 'Onde fica o banheiro? – Fica ao lado da cozinha.',
      german: 'Wo ist das Bad? – Neben der Küche.',
      parts: [{ text: 'Onde', role: 'question' }, { text: ' ' }, { text: 'fica', role: 'verb' }, { text: ' ' }, { text: 'o banheiro', role: 'subject' }, { text: '? – ' }, { text: 'Fica', role: 'verb' }, { text: ' ' }, { text: 'ao lado da', role: 'preposition' }, { text: ' ' }, { text: 'cozinha', role: 'noun' }, { text: '.' }],
    },
    { target: 'O gato está no sofá.', german: 'Die Katze ist auf dem Sofa.', note: '`em` heißt „in“ **und** „auf“: `no sofá` = auf dem Sofa, `na sala` = im Wohnzimmer.' },
    {
      target: 'Meu apartamento fica em frente do parque.',
      german: 'Meine Wohnung liegt gegenüber vom Park.',
      note: 'Im Alltag hörst du auch `em frente ao parque` und `na frente do parque` (direkt vor dem Park).',
    },
    { target: 'Não tem janela no banheiro.', german: 'Im Bad gibt es kein Fenster.' },
    {
      target: 'Moro perto da praia, mas longe do centro.',
      german: 'Ich wohne in der Nähe vom Strand, aber weit weg vom Zentrum.',
      note: '`longe de` = weit weg von – das Gegenteil von `perto de`. Umgangssprachlich auch: `É perto!` – Das ist nah!',
    },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.articles-gender'],
      difficulty: 1,
      instruction: 'Ordne die Bilder den Wörtern zu.',
      pairs: [
        { emoji: '🛋️', word: 'o sofá' },
        { emoji: '🛏️', word: 'a cama' },
        { emoji: '🪟', word: 'a janela' },
        { emoji: '🍳', word: 'a cozinha' },
        { emoji: '🚿', word: 'o banheiro' },
        { emoji: '🗄️', word: 'o armário' },
      ],
      feedback: {
        rule: 'Lerne Zimmer und Möbel mit Artikel: o sofá, a cama, a janela, a cozinha, o banheiro, o armário.',
        why: 'Das Genus weicht oft vom Deutschen ab: das Bett → `a cama`, das Fenster → `a janela`, die Küche → `a cozinha`, das Bad → `o banheiro`.',
        avoid: 'Sprich jedes Wort mit Artikel laut – so bleibt das Genus hängen.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.tem-haver'],
      difficulty: 1,
      prompt: 'Na cozinha ___ uma mesa e quatro cadeiras.',
      options: [
        { text: 'tem' },
        { text: 'têm', why: '`tem` = es gibt bleibt immer Singular. `têm` heißt „sie haben“.' },
        { text: 'está', why: '`estar` sagt, wo ein bestimmtes Ding ist – hier geht es darum, was es gibt.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Was es irgendwo gibt → `tem` (unpersönlich, immer Singular): `Na cozinha tem uma mesa e quatro cadeiras.`',
        why: 'Die vier Stühle verleiten zum Plural `têm` – aber wie „es gibt“ hat `tem` kein Subjekt, das den Plural auslösen könnte.',
        avoid: 'Übersetze im Kopf mit „es gibt“: Passt es, nimm `tem`.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      options: ['quarto', 'quatro'],
      answer: 0,
      hint: '`quarto` (Zimmer): Das r steht **vor** dem t – „KUAR-tu“. `quatro` (vier): Das r steht **nach** dem t – „KUA-tru“.',
      feedback: {
        rule: '`quarto` = Zimmer, `quatro` = vier. Entscheidend ist, wo das r sitzt.',
        why: 'Die Wörter haben dieselben Buchstaben – nur r und t tauschen die Plätze.',
        avoid: 'Hör auf die zweite Silbe: „-tu“ (quarto) oder „-tru“ (quatro)?',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.contractions', 'pt.g.tem-haver'],
      difficulty: 2,
      sentence: 'O banheiro fica ao lado ___ cozinha e o sofá está ___ sala.',
      answers: [['da'], ['na']],
      bank: ['da', 'do', 'na', 'no', 'de', 'em'],
      german: 'Das Bad liegt neben der Küche und das Sofa steht im Wohnzimmer.',
      feedback: {
        rule: '`ao lado de` + `a cozinha` → `ao lado da cozinha`; `em` + `a sala` → `na sala`.',
        why: '`do`/`no` passen nur zu männlichen Nomen. `de`/`em` allein reichen nicht – vor dem Artikel verschmelzen sie immer.',
        avoid: 'Erst das Genus des Nomens klären (a cozinha, a sala), dann verschmelzen: de + a = da, em + a = na.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['pt.g.tem-haver'],
      difficulty: 2,
      audio: 'Meu apartamento tem dois quartos, uma sala, uma cozinha e um banheiro. Não tem varanda.',
      question: 'Was hat die Wohnung **nicht**?',
      options: ['ein Bad', 'einen Balkon', 'eine Küche'],
      answer: 1,
      feedback: {
        rule: '`Não tem varanda.` = Es gibt keinen Balkon.',
        why: '`um banheiro` (Bad) und `uma cozinha` (Küche) werden ausdrücklich genannt.',
        avoid: 'Achte auf `não tem` – danach kommt, was fehlt.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.tem-haver'],
      difficulty: 2,
      tokens: ['Tem', 'um', 'sofá', 'na', 'sala.'],
      alternatives: [['Na', 'sala', 'tem', 'um', 'sofá.']],
      extra: ['têm'],
      german: 'Im Wohnzimmer gibt es ein Sofa.',
      feedback: {
        rule: '`tem` + unbestimmtes Nomen + Ort: `Tem um sofá na sala.` – oder mit dem Ort vorne: `Na sala tem um sofá.`',
        why: '`têm` ist Plural („sie haben“) und passt hier nicht.',
        avoid: 'Es gibt = tem, immer Singular.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['pt.g.questions'],
      difficulty: 2,
      audio: 'Onde fica o banheiro?',
      answers: ['Onde fica o banheiro?'],
      german: 'Wo ist das Bad?',
      feedback: {
        rule: '`Onde fica …?` – so fragst du nach einem festen Ort.',
        why: 'Häufige Schreibfehler: „banhero“ ohne i oder „bainheiro“. Das nh klingt wie das „gn“ in „Champignon“.',
        avoid: 'banh-ei-ro: nh + ei + ro.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.contractions', 'pt.g.possessives'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Meine Wohnung liegt in der Nähe vom Strand.',
      answers: [
        'Meu apartamento fica perto da praia.',
        'O meu apartamento fica perto da praia.',
        'Meu apartamento é perto da praia.',
        'O meu apartamento é perto da praia.',
        'Meu apartamento está perto da praia.',
        'O meu apartamento está perto da praia.',
      ],
      feedback: {
        rule: '`o apartamento` ist männlich → `meu apartamento`; fester Ort → `fica`; perto de + a praia → `perto da praia`.',
        why: '„Wohnung“ ist im Deutschen weiblich, `apartamento` aber männlich – daher nicht `minha`. `perto de praia` ohne Artikel klingt unvollständig.',
        avoid: 'Genus immer vom portugiesischen Nomen nehmen, nicht vom deutschen.',
      },
    },
  ],
  pronunciation: ['pt.p.lh-nh.banheiro', 'pt.p.s-x.casa', 'pt.p.r.porta'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.tem-haver', 'pt.g.contractions'],
      difficulty: 3,
      prompt: 'Beschreib deine Wohnung oder dein Haus: Welche Zimmer gibt es? Was liegt wo? Was gibt es in der Nähe?',
      requirements: [
        { pattern: '\\btem\\b', hint: 'Sag mit „tem“, was es gibt (z. B. „Tem dois quartos“).' },
        { pattern: '\\b(fica|ficam|está|estão)\\b', hint: 'Sag mit „fica“ oder „está“, wo etwas ist.' },
        { pattern: '(perto d|ao lado d|em frente d|na frente d)', hint: 'Verwende eine Ortsangabe: perto de, ao lado de oder em frente de.' },
      ],
      samples: ['Moro em um apartamento em Hamburgo. Tem dois quartos, uma sala, uma cozinha e um banheiro. A cozinha fica ao lado da sala. Tem um mercado perto de casa.'],
      minWords: 15,
      feedback: {
        rule: 'Bausteine: Tem … (es gibt) · … fica ao lado do/da … · Tem … perto de casa / perto daqui.',
        why: 'Häufige Fehler: `têm` statt `tem` bei „es gibt“ und `ao lado de a sala` statt `ao lado da sala`.',
        avoid: 'Erst sagen, was es gibt (tem), dann, wo es ist (fica/está).',
      },
    },
    {
      id: `${L}.a02`,
      type: 'situation',
      skills: ['reading', 'vocabulary'],
      topicIds: ['pt.g.questions'],
      difficulty: 2,
      scenario: 'Du bist zum ersten Mal bei brasilianischen Freunden zu Hause und musst zur Toilette. Was fragst du?',
      options: [
        { text: 'Onde fica o banheiro?' },
        { text: 'Onde fica a cozinha?', why: 'Du suchst das Bad, nicht die Küche.' },
        { text: 'O banheiro tem janela?', why: 'Damit fragst du, ob das Bad ein Fenster hat.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Nach einem Raum fragen: `Onde fica o banheiro?` – `banheiro` ist Bad und Toilette zugleich.',
        why: 'Die anderen Fragen sind korrekt gebildet, passen aber nicht zu deinem Anliegen.',
        avoid: 'Merke dir den ganzen Satz als Baustein: Onde fica o banheiro?',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.tem-haver'],
      difficulty: 3,
      scenarioId: 'pt.sc.alltag',
      goal: 'Du bist neu im Haus und triffst deine Nachbarin Luana. Erzähl ihr von deiner Wohnung (`Meu apartamento tem …`) und frag, was es in der Nähe gibt: `Tem um mercado perto daqui?`',
      turns: 5,
      feedback: {
        rule: 'Was es gibt → `tem`; wo etwas liegt → `fica` + perto de / ao lado de / em frente de.',
        avoid: 'Nimm Wörter aus Luanas Antworten auf – so bleibt das Gespräch im Fluss.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'cloze',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.possessives'],
      difficulty: 2,
      sentence: 'A Ana é casada. O marido ___ se chama Tiago.',
      answers: [['dela']],
      bank: ['dela', 'dele', 'sua', 'seu'],
      german: 'Ana ist verheiratet. Ihr Mann heißt Tiago.',
      feedback: {
        rule: 'Besitzerin ist Ana (ela) → `o marido dela`.',
        why: '`dele` würde auf einen Mann verweisen. `seu/sua` versteht man in Brasilien als „dein“ – und `sua` passt nicht zu `marido`.',
        avoid: 'dele/dela schaut auf den Besitzer, nicht auf das Nomen.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.ter', 'pt.g.tem-haver'],
      difficulty: 2,
      prompt: 'Meus pais ___ uma casa na praia.',
      options: [
        { text: 'tem', why: '`tem` wäre „er/sie hat“ oder „es gibt“ – das Subjekt `meus pais` ist aber Plural.' },
        { text: 'têm' },
        { text: 'temos', why: '`temos` gehört zu `nós`.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Hier ist `ter` = haben mit Subjekt im Plural: `meus pais têm` (sie haben).',
        why: 'Nur „es gibt“ bleibt immer Singular. Hat der Satz ein Subjekt im Plural, braucht ter die Pluralform `têm`.',
        avoid: 'Gibt es ein Subjekt? Dann konjugieren. Kein Subjekt („es gibt“)? Dann `tem`.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.contractions'],
      difficulty: 1,
      sentence: 'O livro está em a mesa.',
      answers: ['O livro está na mesa.'],
      german: 'Das Buch liegt auf dem Tisch.',
      feedback: {
        rule: '`em` + `a` = `na`. Die Verschmelzung ist Pflicht.',
        why: '`em a` darf nie getrennt stehen – genauso wenig wie `em o` (→ `no`).',
        avoid: 'em + o = no, em + a = na, de + o = do, de + a = da.',
      },
    },
  ],
};

export default lesson;
