import type { Lesson } from '../../types';

const L = 'pt.a1.l01';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'a1',
  chapterId: 'pt.a1.c1',
  order: 1,
  title: 'Minha família – meine Familie',
  subtitle: 'ter · meu, minha · dele, dela',
  icon: '👨‍👩‍👧',
  minutes: 13,
  goal:
    'Du kannst deine **Familie vorstellen**: wer dazugehört, wie die Leute heißen, wie alt sie sind und wo sie wohnen. Dazu lernst du alle Präsensformen von **ter** (haben), die **Possessivbegleiter** `meu`, `minha`, `seu`, `sua` und die brasilianische Lösung für „sein/ihr“: `dele`, `dela`.',
  canDo: [
    'Ich kann sagen, welche Familienmitglieder und Haustiere ich habe.',
    'Ich kann ter in allen Personen des Präsens verwenden (tenho, tem, temos, têm).',
    'Ich kann meu/minha/meus/minhas und seu/sua an das Nomen angleichen.',
    'Ich kann mit dele/dela eindeutig sagen, wem etwas gehört (a casa dele).',
  ],
  topicIds: ['pt.g.ter', 'pt.g.possessives'],
  vocab: [
    { id: `${L}.v.familia`, target: 'a família', german: 'die Familie', pos: 'noun', gender: 'f', plural: 'famílias', emoji: '👨‍👩‍👧', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Minha família mora em Recife.', german: 'Meine Familie wohnt in Recife.' } },
    { id: `${L}.v.pai`, target: 'o pai', german: 'der Vater', pos: 'noun', gender: 'm', plural: 'pais', emoji: '👨', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Meu pai é médico.', german: 'Mein Vater ist Arzt.' } },
    { id: `${L}.v.mae`, target: 'a mãe', german: 'die Mutter', pos: 'noun', gender: 'f', plural: 'mães', emoji: '👩', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Minha mãe se chama Helena.', german: 'Meine Mutter heißt Helena.' } },
    { id: `${L}.v.pais`, target: 'os pais', german: 'die Eltern', pos: 'noun', gender: 'm', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Meus pais moram em Colônia.', german: 'Meine Eltern wohnen in Köln.' } },
    { id: `${L}.v.irmao`, target: 'o irmão / a irmã', german: 'der Bruder / die Schwester', pos: 'noun', gender: 'm/f', plural: 'irmãos (auch: Geschwister) / irmãs', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Tenho dois irmãos.', german: 'Ich habe zwei Brüder (oder: zwei Geschwister).' } },
    { id: `${L}.v.filhos`, target: 'os filhos', german: 'die Kinder (Söhne und Töchter)', pos: 'noun', gender: 'm', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Você tem filhos?', german: 'Hast du Kinder?' } },
    { id: `${L}.v.marido`, target: 'o marido', german: 'der Ehemann', pos: 'noun', gender: 'm', plural: 'maridos', emoji: '🤵', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'O marido dela é alemão.', german: 'Ihr Mann ist Deutscher.' } },
    { id: `${L}.v.esposa`, target: 'a esposa', german: 'die Ehefrau (im Alltag auch: a mulher)', pos: 'noun', gender: 'f', plural: 'esposas', emoji: '👰', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'A esposa dele é professora.', german: 'Seine Frau ist Lehrerin.' } },
    { id: `${L}.v.avos`, target: 'os avós', german: 'die Großeltern', pos: 'noun', gender: 'm', emoji: '👵', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Meus avós moram no interior.', german: 'Meine Großeltern wohnen auf dem Land.' } },
    { id: `${L}.v.tio`, target: 'o tio / a tia', german: 'der Onkel / die Tante', pos: 'noun', gender: 'm/f', plural: 'tios / tias', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Minha tia mora em Salvador.', german: 'Meine Tante wohnt in Salvador.' } },
    { id: `${L}.v.primo`, target: 'o primo / a prima', german: 'der Cousin / die Cousine', pos: 'noun', gender: 'm/f', plural: 'primos / primas', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'Tenho três primos e uma prima.', german: 'Ich habe drei Cousins und eine Cousine.' } },
    { id: `${L}.v.namorado`, target: 'o namorado / a namorada', german: 'der (feste) Freund / die (feste) Freundin', pos: 'noun', gender: 'm/f', plural: 'namorados / namoradas', emoji: '💑', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'A Paula é a namorada do meu irmão.', german: 'Paula ist die Freundin meines Bruders.' } },
    { id: `${L}.v.casado`, target: 'casado / casada', german: 'verheiratet', pos: 'adj', emoji: '💍', field: 'Familie', stageId: 'a1', lessonId: L, example: { target: 'A Carla é casada.', german: 'Carla ist verheiratet.' } },
    { id: `${L}.v.cachorro`, target: 'o cachorro', german: 'der Hund', pos: 'noun', gender: 'm', plural: 'cachorros', emoji: '🐶', field: 'Haustiere', stageId: 'a1', lessonId: L, example: { target: 'A gente tem um cachorro.', german: 'Wir haben einen Hund.' } },
    { id: `${L}.v.gato`, target: 'o gato', german: 'die Katze, der Kater', pos: 'noun', gender: 'm', plural: 'gatos', emoji: '🐱', field: 'Haustiere', stageId: 'a1', lessonId: L, example: { target: 'Meus pais têm dois gatos.', german: 'Meine Eltern haben zwei Katzen.' } },
    { id: `${L}.v.dele-dela`, target: 'dele / dela', german: 'sein, seine / ihr, ihre (wörtl. von ihm / von ihr)', pos: 'pron', field: 'Possessiva', stageId: 'a1', lessonId: L, example: { target: 'o carro dele, a casa dela', german: 'sein Auto, ihr Haus' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Mit `ter` (haben) sprichst du über deine Familie: `Tenho dois irmãos.` – Ich habe zwei Brüder. `Você tem filhos?` – Hast du Kinder?\n' +
        'Die männliche Pluralform steht auch für gemischte Gruppen:\n' +
        '- `os pais` = die Eltern (nicht „die Väter“)\n' +
        '- `os irmãos` = Brüder **oder** Geschwister\n' +
        '- `os filhos` = Söhne **oder** Kinder\n' +
        '- `os avós` = die Großeltern\n' +
        'Auf Ja/Nein-Fragen antworten Brasilianer gern mit dem Verb: `Você tem irmãos? – Tenho, sim.` bzw. `Não, não tenho.`',
    },
    {
      type: 'conjugation',
      verb: 'ter',
      translation: 'haben',
      tense: 'Präsens',
      rows: [
        { person: 'eu', form: 'tenho' },
        { person: 'você / ele / ela / a gente', form: 'tem' },
        { person: 'nós', form: 'temos', ending: 'mos' },
        { person: 'vocês / eles / elas', form: 'têm' },
      ],
    },
    {
      type: 'table',
      title: 'Possessivbegleiter',
      headers: ['Besitzer', 'm. Sg.', 'f. Sg.', 'm. Pl.', 'f. Pl.'],
      rows: [
        ['eu', 'meu pai', 'minha mãe', 'meus irmãos', 'minhas irmãs'],
        ['você', 'seu pai', 'sua mãe', 'seus irmãos', 'suas irmãs'],
        ['ele', 'o pai dele', 'a mãe dele', 'os irmãos dele', 'as irmãs dele'],
        ['ela', 'o pai dela', 'a mãe dela', 'os irmãos dela', 'as irmãs dela'],
        ['nós / a gente', 'nosso pai', 'nossa mãe', 'nossos irmãos', 'nossas irmãs'],
        ['eles / elas', 'o pai deles/delas', 'a mãe deles/delas', 'os irmãos deles/delas', 'as irmãs deles/delas'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'A', role: 'article' },
        { text: ' ' },
        { text: 'mãe', role: 'noun' },
        { text: ' ' },
        { text: 'dela', role: 'pronoun' },
        { text: ' ' },
        { text: 'é', role: 'verb' },
        { text: ' ' },
        { text: 'professora', role: 'noun' },
        { text: '.' },
      ],
      german: 'Ihre Mutter ist Lehrerin.',
    },
    {
      type: 'compare',
      target: 'o pai dele · o pai dela',
      german: 'sein Vater · ihr Vater',
      md:
        '`dele`/`dela` funktioniert wie das deutsche „sein/ihr“: Es richtet sich nach dem **Besitzer** (ele → `dele`, ela → `dela`). Es steht aber **hinter** dem Nomen, und das Nomen bekommt seinen Artikel: `o pai dela`.\n' +
        '`meu/minha` und `seu/sua` richten sich dagegen nach dem **Nomen**: `minha mãe`, `meu pai` – egal, ob ein Mann oder eine Frau spricht.',
    },
    {
      type: 'mistake',
      wrong: 'A Ana é casada. O marido dele é alemão.',
      right: 'A Ana é casada. O marido dela é alemão.',
      why: 'Der Besitzer ist Ana (ela) → `dela`. Viele Lernende passen `dele/dela` fälschlich an das Nomen an (`marido` ist männlich) – das gilt aber nur für `meu/minha`, `seu/sua`.',
    },
    {
      type: 'variant',
      variant: 'pt-BR',
      md:
        'In Brasilien bedeutet `seu/sua` im Alltag fast immer **dein/Ihr** (zu você): `Como se chama a sua irmã?` = Wie heißt deine Schwester? Für „sein/ihr“ sagt man deshalb `dele/dela`: `a irmã dele`.\n' +
        'Der Artikel vor dem Possessiv ist freiwillig: `minha mãe` und `a minha mãe` sind beide richtig.',
    },
    {
      type: 'tip',
      md: 'Merksatz: **meu/minha schaut auf das Ding, dele/dela schaut auf den Besitzer.** `minha casa` – `a casa dela`. Und bei ter: **tenho, tem, temos, têm** – das Dach auf `têm` zeigt den Plural.',
    },
  ],
  examples: [
    {
      target: 'Tenho dois irmãos e uma irmã.',
      german: 'Ich habe zwei Brüder und eine Schwester.',
      parts: [{ text: 'Tenho', role: 'verb' }, { text: ' ' }, { text: 'dois irmãos', role: 'object' }, { text: ' e ' }, { text: 'uma irmã', role: 'object' }, { text: '.' }],
    },
    {
      target: 'Você tem filhos? – Tenho, sim. Tenho uma filha.',
      german: 'Hast du Kinder? – Ja. Ich habe eine Tochter.',
      note: 'Statt nur `sim` wiederholt man in Brasilien gern das Verb: `Tenho, sim.`',
    },
    {
      target: 'Minha mãe se chama Helena e meu pai se chama Jorge.',
      german: 'Meine Mutter heißt Helena und mein Vater heißt Jorge.',
      parts: [{ text: 'Minha', role: 'pronoun' }, { text: ' ' }, { text: 'mãe', role: 'noun' }, { text: ' ' }, { text: 'se chama', role: 'verb' }, { text: ' Helena e ' }, { text: 'meu', role: 'pronoun' }, { text: ' ' }, { text: 'pai', role: 'noun' }, { text: ' ' }, { text: 'se chama', role: 'verb' }, { text: ' Jorge.' }],
    },
    {
      target: 'Meus avós moram no interior.',
      german: 'Meine Großeltern wohnen auf dem Land.',
      note: '`o interior` – so nennen Brasilianer alles außerhalb der großen Städte und der Küste.',
    },
    { target: 'A gente tem um cachorro e dois gatos.', german: 'Wir haben einen Hund und zwei Katzen.', note: '`a gente` hat die Verbform von ele/ela: `a gente tem`.' },
    {
      target: 'A Paula é a namorada do meu irmão.',
      german: 'Paula ist die Freundin meines Bruders.',
      note: '`do meu irmão` = de + o meu irmão. `namorada` ist die feste Freundin – eine gute Freundin ist `uma amiga`.',
    },
    {
      target: 'A Carla é casada. O marido dela é alemão.',
      german: 'Carla ist verheiratet. Ihr Mann ist Deutscher.',
      parts: [{ text: 'A Carla', role: 'subject' }, { text: ' ' }, { text: 'é', role: 'verb' }, { text: ' ' }, { text: 'casada', role: 'adjective' }, { text: '. ' }, { text: 'O marido', role: 'subject' }, { text: ' ' }, { text: 'dela', role: 'pronoun' }, { text: ' ' }, { text: 'é', role: 'verb' }, { text: ' ' }, { text: 'alemão', role: 'adjective' }, { text: '.' }],
    },
    { target: 'Nossos pais têm uma casa em Curitiba.', german: 'Unsere Eltern haben ein Haus in Curitiba.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.articles-gender'],
      difficulty: 1,
      instruction: 'Ordne die Bilder den Wörtern zu.',
      pairs: [
        { emoji: '👨', word: 'o pai' },
        { emoji: '👩', word: 'a mãe' },
        { emoji: '👴', word: 'o avô' },
        { emoji: '👵', word: 'a avó' },
        { emoji: '🐶', word: 'o cachorro' },
        { emoji: '🐱', word: 'o gato' },
      ],
      feedback: {
        rule: 'Lerne Familienwörter immer mit Artikel: o pai, a mãe, o avô, a avó – dazu die Haustiere o cachorro und o gato.',
        why: '`avô` (Opa) und `avó` (Oma) unterscheiden sich nur im Akzent: ^ = geschlossenes o, ´ = offenes o.',
        avoid: 'Eselsbrücke: Das Dach ^ auf avô ist wie ein Hut – der Opa trägt Hut.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.possessives'],
      difficulty: 1,
      prompt: '___ mãe se chama Helena.',
      options: [
        { text: 'Meu', why: '`meu` steht vor männlichen Nomen: `meu pai`.' },
        { text: 'Minha' },
        { text: 'Minhas', why: '`minhas` ist Plural: `minhas irmãs`.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Das Possessiv richtet sich nach dem Nomen: `mãe` ist feminin Singular → `minha`.',
        why: '`meu` passt nur zu männlichen Nomen, `minhas` nur zum Plural.',
        avoid: 'Schau auf das Nomen dahinter: o pai → meu, a mãe → minha.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.ter'],
      difficulty: 1,
      verb: 'ter',
      tense: 'Präsens',
      person: 'nós',
      sentence: 'Nós ___ dois filhos.',
      answers: ['temos'],
      feedback: {
        rule: '`ter` im Präsens: tenho, tem, **temos**, têm. Zu `nós` gehört `temos`.',
        why: '`tem` gehört zu você/ele/ela/a gente, `têm` zu vocês/eles/elas.',
        avoid: 'nós → immer **-mos** am Ende, auch bei unregelmäßigen Verben.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      options: ['irmã', 'irmão'],
      answer: 1,
      hint: '`irmã` (Schwester) endet auf einem nasalen a – „ir-MÃ“. `irmão` (Bruder) gleitet danach noch in ein nasales u – „ir-MÃUN“.',
      feedback: {
        rule: '`ã` = nasales a; `ão` = nasales a + nasales u als Gleitlaut.',
        why: 'Beide Wörter klingen bis zum Ende gleich – nur der u-Nachklang unterscheidet Bruder und Schwester.',
        avoid: 'Achte auf das Ende: Rundet sich der Mund zum u? Dann ist es `irmão`.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.ter', 'pt.g.pronouns'],
      difficulty: 2,
      sentence: 'Eu ___ uma irmã e a gente ___ um cachorro.',
      answers: [['tenho'], ['tem']],
      bank: ['tenho', 'tem', 'temos', 'têm'],
      german: 'Ich habe eine Schwester und wir haben einen Hund.',
      feedback: {
        rule: 'eu → `tenho`; `a gente` (wir, Alltagssprache) hat die Verbform von ele/ela → `tem`.',
        why: '`temos` gehört zu `nós`, nicht zu `a gente`. `têm` ist die Form für eles/elas.',
        avoid: 'a gente = wir, aber grammatisch wie „er/sie“: a gente tem, a gente mora.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['pt.g.possessives', 'pt.g.numbers'],
      difficulty: 2,
      audio: 'Minha irmã tem vinte e seis anos e o marido dela tem trinta.',
      question: 'Wie alt ist der Mann der Schwester?',
      options: ['26', '30', '36'],
      answer: 1,
      feedback: {
        rule: '`o marido dela` = ihr Mann (der Mann der Schwester) – er ist `trinta` = 30.',
        why: '26 (`vinte e seis`) ist das Alter der Schwester selbst. 36 wäre `trinta e seis`.',
        avoid: 'Hör auf `dela`: Es verweist zurück auf die Schwester.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.possessives'],
      difficulty: 2,
      tokens: ['O', 'pai', 'dele', 'é', 'médico.'],
      extra: ['dela'],
      german: 'Sein Vater ist Arzt.',
      feedback: {
        rule: '„sein“ = von ihm → `dele`, hinter dem Nomen: `o pai dele`.',
        why: '`dela` hieße „ihr Vater“ (von ihr). Und `dele` steht nie vor dem Nomen.',
        avoid: 'Frag dich: Wem gehört es? Einem Mann → dele, einer Frau → dela.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.ter', 'pt.g.possessives'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Meine Schwester hat zwei Kinder.',
      answers: [
        'Minha irmã tem dois filhos.',
        'A minha irmã tem dois filhos.',
        'Minha irmã tem 2 filhos.',
        'A minha irmã tem 2 filhos.',
        'Minha irmã tem duas crianças.',
        'A minha irmã tem duas crianças.',
      ],
      feedback: {
        rule: '`minha irmã` (feminin) + `tem` (sie hat) + `dois filhos` (Kinder = filhos).',
        why: '`meu irmã` passt nicht zum femininen Nomen. „Kinder“ im Sinne von Söhne und Töchter heißt `filhos` – männlicher Plural für die gemischte Gruppe.',
        avoid: 'Possessiv nach dem Nomen richten: irmã → minha.',
      },
    },
  ],
  pronunciation: ['pt.p.lh-nh.filho', 'pt.p.open-closed.avo-aberto', 'pt.p.open-closed.avo-fechado'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.ter', 'pt.g.possessives'],
      difficulty: 3,
      prompt: 'Beschreib deine Familie in drei bis vier Sätzen: Wen hast du? Wie heißen die Leute, wie alt sind sie, wo wohnen sie?',
      requirements: [
        { pattern: '\\b(tenho|tem|temos|têm)\\b', hint: 'Verwende ter, z. B. „Tenho um irmão“.' },
        { pattern: '\\b(meu|minha|meus|minhas|nosso|nossa|nossos|nossas)\\b', hint: 'Verwende mindestens ein Possessiv (meu, minha, meus, minhas).' },
        {
          pattern: '\\b(pai|mãe|pais|irmão|irmã|irmãos|irmãs|filho|filha|filhos|filhas|avô|avó|avós|marido|esposa|mulher|tio|tia|tios|primo|prima|primos|namorado|namorada)\\b',
          hint: 'Nenne Familienmitglieder (pai, mãe, irmão …).',
        },
      ],
      samples: ['Tenho um irmão e uma irmã. Meu irmão se chama Paulo e tem vinte anos. Minha irmã mora em Berlim com o marido dela. Meus pais moram em Colônia e a gente tem um gato.'],
      minWords: 15,
      feedback: {
        rule: 'Bausteine: Tenho … · Meu/Minha … se chama … · … tem … anos · … mora em … · o marido dela / a esposa dele.',
        why: 'Häufige Fehler: `meu irmã` statt `minha irmã`, `o marido dele` statt `o marido dela` (wenn es um eine Frau geht) und `sou … anos` statt `tenho … anos`.',
        avoid: 'Lies jeden Satz noch einmal: Passt das Possessiv zum Nomen – und dele/dela zum Besitzer?',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['pt.g.ter', 'pt.g.possessives'],
      difficulty: 3,
      prompt: 'Stell dir ein Familienfoto vor und erzähl: Wer ist das? Wie heißt die Person, wie alt ist sie? Nenne auch ihren Partner oder ihre Partnerin (dele/dela).',
      keywords: ['minha', 'meu', 'tem', 'anos', 'chama', 'dele', 'dela', 'irmã', 'irmão'],
      minMatch: 4,
      sample: 'É a minha irmã, a Júlia. Ela tem vinte e oito anos. O marido dela se chama Tiago.',
      feedback: {
        rule: 'Nutze: minha/meu + Familienwort, tem … anos, se chama …, o marido dela / a esposa dele.',
        why: 'Fehlen Schlüsselwörter, hat die Spracherkennung sie nicht gehört – oder sie fehlen in deiner Beschreibung.',
        avoid: 'Sprich in kurzen Sätzen – ein Satz pro Information.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'dialogue',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.possessives'],
      difficulty: 2,
      instruction: 'Lukas antwortet auf Anas Frage. Was sagt er?',
      lines: [
        { speaker: 'Ana', text: 'Você tem irmãos?', german: 'Hast du Geschwister?' },
        { speaker: 'Lukas', text: 'Tenho, sim. Tenho uma irmã. E você?', german: 'Ja. Ich habe eine Schwester. Und du?' },
        { speaker: 'Ana', text: 'Tenho dois irmãos. E como se chama a sua irmã?', german: 'Ich habe zwei Brüder. Und wie heißt deine Schwester?' },
        { speaker: 'Lukas', text: '…' },
      ],
      gapIndex: 3,
      options: ['O nome dela é Marie.', 'O nome dele é Marie.', 'Meu nome é Marie.'],
      answer: 0,
      feedback: {
        rule: 'Es geht um den Namen der Schwester (ela) → `o nome dela`.',
        why: '`o nome dele` hieße „sein Name“ – die Schwester ist aber eine Frau. `Meu nome é Marie` würde bedeuten, dass Lukas selbst Marie heißt.',
        avoid: 'dele/dela richtet sich nach dem Besitzer, nicht nach `nome`.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.possessives'],
      difficulty: 2,
      sentence: 'Meu irmã tem vinte anos.',
      answers: ['Minha irmã tem vinte anos.', 'A minha irmã tem vinte anos.', 'Minha irmã tem 20 anos.', 'A minha irmã tem 20 anos.'],
      german: 'Meine Schwester ist zwanzig Jahre alt.',
      feedback: {
        rule: '`irmã` ist feminin → `minha irmã`.',
        why: '`meu` passt nur zu männlichen Nomen wie `meu irmão`.',
        avoid: 'Endet das Nomen auf -a/-ã, ist es meistens feminin → minha.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.ter', 'pt.g.ser-estar'],
      difficulty: 1,
      prompt: 'Meu avô ___ oitenta anos.',
      options: [
        { text: 'é', why: 'Das Alter drückt man nicht mit ser aus.' },
        { text: 'tem' },
        { text: 'está', why: '`estar` beschreibt Zustand oder Ort, nicht das Alter.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Alter mit `ter`: `Meu avô tem oitenta anos.` – wörtlich „hat achtzig Jahre“.',
        why: 'Das deutsche „ist … alt“ verleitet zu `é` – im Portugiesischen „hat“ man sein Alter.',
        avoid: 'Alter hat man: tenho, tem, temos, têm … anos.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.possessives', 'pt.g.contractions'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'Os pais dele moram no Rio.',
      answers: ['Seine Eltern wohnen in Rio.', 'Seine Eltern leben in Rio.', 'Seine Eltern wohnen in Rio de Janeiro.', 'Seine Eltern leben in Rio de Janeiro.'],
      feedback: {
        rule: '`os pais` = die Eltern; `dele` = sein (von ihm); `no Rio` = em + o Rio.',
        why: '`pais` heißt nicht „Väter“, sondern „Eltern“. `dele` zeigt einen männlichen Besitzer → „seine“, nicht „ihre“.',
        avoid: 'os pais = Eltern, os avós = Großeltern, os filhos = Kinder.',
      },
    },
  ],
};

export default lesson;
