import type { Lesson } from '../../types';

const L = 'pt.a1.l06';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'a1',
  chapterId: 'pt.a1.c2',
  order: 6,
  title: 'O que você está fazendo? – gerade jetzt',
  subtitle: 'estou falando · Alô? · Tô chegando!',
  icon: '📱',
  minutes: 13,
  goal:
    'Du kannst sagen, **was gerade passiert**: `Estou trabalhando.` – `Ela está dormindo.` Dazu lernst du **estar + Gerundium**, die typisch brasilianische Verlaufsform, und meisterst kurze **Telefonate und Nachrichten**: abheben, nach jemandem fragen und sagen, was jemand gerade macht.',
  canDo: [
    'Ich kann das Gerundium von Verben auf -ar, -er und -ir bilden (falando, comendo, dormindo).',
    'Ich kann mit estar + Gerundium sagen, was ich oder andere gerade tun.',
    'Ich kann ein kurzes Telefonat beginnen und nach jemandem fragen.',
    'Ich verstehe lockere Nachrichten wie „Tô chegando!“ und kann selbst welche schreiben.',
  ],
  topicIds: ['pt.g.gerund'],
  vocab: [
    { id: `${L}.v.fazer`, target: 'fazer', german: 'machen, tun (fazendo)', pos: 'verb', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'O que você está fazendo?', german: 'Was machst du gerade?' } },
    { id: `${L}.v.agora`, target: 'agora', german: 'jetzt', pos: 'adv', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Agora estou almoçando.', german: 'Ich esse gerade zu Mittag.' } },
    { id: `${L}.v.ainda`, target: 'ainda', german: 'noch', pos: 'adv', field: 'Zeit', stageId: 'a1', lessonId: L, example: { target: 'Ainda estou trabalhando.', german: 'Ich arbeite noch.' } },
    { id: `${L}.v.celular`, target: 'o celular', german: 'das Handy', pos: 'noun', gender: 'm', plural: 'celulares', emoji: '📱', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Onde está meu celular?', german: 'Wo ist mein Handy?' } },
    { id: `${L}.v.ligar`, target: 'ligar (para)', german: 'anrufen', pos: 'verb', emoji: '📞', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Eu ligo para você depois.', german: 'Ich rufe dich später an.' } },
    { id: `${L}.v.atender`, target: 'atender (o telefone)', german: 'rangehen, abheben', pos: 'verb', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Ela não está atendendo.', german: 'Sie geht nicht ran.' } },
    { id: `${L}.v.alo`, target: 'Alô?', german: 'Hallo? (am Telefon)', pos: 'phrase', emoji: '☎️', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Alô? Quem fala?', german: 'Hallo? Wer ist dran?' } },
    { id: `${L}.v.quem-fala`, target: 'Quem fala?', german: 'Wer ist dran? / Wer spricht da?', pos: 'phrase', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Alô, quem fala? – É a Júlia.', german: 'Hallo, wer ist dran? – Hier ist Júlia.' } },
    { id: `${L}.v.mensagem`, target: 'a mensagem', german: 'die Nachricht', pos: 'noun', gender: 'f', plural: 'mensagens', emoji: '💬', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Estou escrevendo uma mensagem.', german: 'Ich schreibe gerade eine Nachricht.' } },
    { id: `${L}.v.mandar`, target: 'mandar', german: 'schicken', pos: 'verb', emoji: '📤', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Eu mando uma mensagem para você.', german: 'Ich schicke dir eine Nachricht.' } },
    { id: `${L}.v.escrever`, target: 'escrever', german: 'schreiben (escrevendo)', pos: 'verb', emoji: '✍️', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Ela está escrevendo uma mensagem.', german: 'Sie schreibt gerade eine Nachricht.' } },
    { id: `${L}.v.ler`, target: 'ler', german: 'lesen (lendo)', pos: 'verb', emoji: '📖', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Estou lendo um livro.', german: 'Ich lese gerade ein Buch.' } },
    { id: `${L}.v.esperar`, target: 'esperar', german: 'warten (auf)', pos: 'verb', emoji: '⏳', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Estou esperando o ônibus.', german: 'Ich warte gerade auf den Bus.' } },
    { id: `${L}.v.cozinhar`, target: 'cozinhar', german: 'kochen', pos: 'verb', emoji: '🍳', field: 'Verben', stageId: 'a1', lessonId: L, example: { target: 'Meu pai está cozinhando.', german: 'Mein Vater kocht gerade.' } },
    { id: `${L}.v.ocupado`, target: 'ocupado / ocupada', german: 'beschäftigt', pos: 'adj', field: 'Befinden', stageId: 'a1', lessonId: L, example: { target: 'Agora estou ocupada, estou trabalhando.', german: 'Ich bin gerade beschäftigt, ich arbeite.' } },
    { id: `${L}.v.to-chegando`, target: 'Tô chegando!', german: 'Bin gleich da! (wörtl.: Ich komme gerade an.)', pos: 'phrase', field: 'Telefon', stageId: 'a1', lessonId: L, example: { target: 'Tô chegando! Cinco minutos!', german: 'Bin gleich da! Fünf Minuten!' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Was passiert **gerade jetzt**? Dafür nimmt man im brasilianischen Portugiesisch **estar + Gerundium**. Das Gerundium bildest du ganz einfach: **-r des Infinitivs weg, -ndo dran**:\n' +
        '- -ar → **-ando**: `falar` → `falando`, `trabalhar` → `trabalhando`\n' +
        '- -er → **-endo**: `comer` → `comendo`, `fazer` → `fazendo`, `ler` → `lendo`\n' +
        '- -ir → **-indo**: `dormir` → `dormindo`, `abrir` → `abrindo`\n' +
        'Das Gerundium ist **unveränderlich** – nur `estar` zeigt die Person. Auch Verben mit Sonderformen sind hier regelmäßig: `eu durmo`, aber `estou dormindo`.',
    },
    {
      type: 'conjugation',
      verb: 'estar + falando',
      translation: 'gerade sprechen',
      tense: 'Verlaufsform (Präsens)',
      rows: [
        { person: 'eu', form: 'estou falando', ending: 'ando' },
        { person: 'você / ele / ela / a gente', form: 'está falando', ending: 'ando' },
        { person: 'nós', form: 'estamos falando', ending: 'ando' },
        { person: 'vocês / eles / elas', form: 'estão falando', ending: 'ando' },
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Eu', role: 'subject' },
        { text: ' ' },
        { text: 'estou', role: 'verb' },
        { text: ' ' },
        { text: 'trabalh', role: 'verb' },
        { text: 'ando', role: 'ending' },
        { text: ' ' },
        { text: 'agora', role: 'adverb' },
        { text: '.' },
      ],
      german: 'Ich arbeite gerade.',
    },
    {
      type: 'compare',
      target: 'Eu trabalho em casa. · Agora estou trabalhando.',
      german: 'Ich arbeite (meistens) zu Hause. · Ich arbeite gerade.',
      md:
        'Das Deutsche hat keine eigene Verlaufsform – wir sagen „gerade“ oder umgangssprachlich „ich bin am Arbeiten“. Portugiesisch unterscheidet klar: **Präsens** für Gewohnheiten und Tatsachen (`Eu trabalho em casa.`), **estar + Gerundium** für das, was jetzt läuft (`Estou trabalhando.`). In Brasilien nutzt man die Verlaufsform auch für „zurzeit“: `Estou estudando português.`\n' +
        'Bei reflexiven Verben steht das Pronomen vor dem Gerundium: `Estou me vestindo.` (Ich ziehe mich gerade an.)\n' +
        'In Portugal hörst du stattdessen `estou a falar` – in Brasilien sagt man immer `estou falando`.',
    },
    {
      type: 'text',
      md:
        '**Am Telefon und in Nachrichten**\n' +
        '- `Alô?` – so meldet man sich in Brasilien am Telefon, meist ohne Namen.\n' +
        '- `Quem fala?` – Wer ist dran? · Antwort: `É a Marina.` / `Aqui é o Tom.`\n' +
        '- `O Paulo está?` – Ist Paulo da? · `Não, ele não está.` oder `Está, mas está tomando banho.`\n' +
        '- `Um momento!` – Einen Moment! · `Eu ligo depois.` – Ich rufe später an.\n' +
        '- Im Gespräch und in Nachrichten wird `estou` zu **`tô`** und `está` zu **`tá`**: `Tô chegando!` (Bin gleich da!), `Tá bom!` (Okay!). Schreib `tô`/`tá` nur locker, nie in formellen Texten.\n' +
        '**Kultur:** `Tô chegando!` heißt wörtlich „Ich komme gerade an“ – Brasilianer sagen das gern auch dann, wenn sie noch gar nicht losgegangen sind. Und beim Diktieren von Telefonnummern sagt man für die 6 oft `meia` (von `meia dúzia`, einem halben Dutzend).',
    },
    {
      type: 'mistake',
      wrong: 'Eu estou trabalhar.',
      right: 'Eu estou trabalhando.',
      why: 'Nach `estar` folgt in Brasilien das Gerundium auf **-ndo**, nicht der Infinitiv. Auch `Eu sou trabalhando` ist falsch: Die Verlaufsform bildet man immer mit `estar`, nie mit `ser`.',
    },
    {
      type: 'tip',
      md: 'Merksatz: **-r weg, -ndo dran** – `fala-r` → `falando`, `come-r` → `comendo`, `dormi-r` → `dormindo`. Und davor immer `estar`: „gerade jetzt“ = **estar + -ndo**.',
    },
    { type: 'audio', text: 'Alô? Oi, Pedro! Estou esperando o ônibus. Tô chegando!', label: 'Kurz am Telefon' },
  ],
  examples: [
    {
      target: 'O que você está fazendo? – Estou cozinhando.',
      german: 'Was machst du gerade? – Ich koche gerade.',
      parts: [{ text: 'O que', role: 'question' }, { text: ' ' }, { text: 'você', role: 'subject' }, { text: ' ' }, { text: 'está', role: 'verb' }, { text: ' ' }, { text: 'fazendo', role: 'verb' }, { text: '? – ' }, { text: 'Estou', role: 'verb' }, { text: ' ' }, { text: 'cozinhando', role: 'verb' }, { text: '.' }],
    },
    { target: 'A Júlia está dormindo.', german: 'Júlia schläft gerade.' },
    { target: 'A gente está jantando agora.', german: 'Wir essen gerade zu Abend.', note: '`a gente` + `está` (3. Person Singular).' },
    {
      target: 'Estou me vestindo. Um momento!',
      german: 'Ich ziehe mich gerade an. Einen Moment!',
      parts: [{ text: 'Estou', role: 'verb' }, { text: ' ' }, { text: 'me', role: 'pronoun' }, { text: ' ' }, { text: 'vest', role: 'verb' }, { text: 'indo', role: 'ending' }, { text: '. Um momento!' }],
    },
    { target: 'Alô? Quem fala? – Oi, é a Marina.', german: 'Hallo? Wer ist dran? – Hi, hier ist Marina.' },
    { target: 'O Paulo está? – Não, ele está trabalhando.', german: 'Ist Paulo da? – Nein, er ist gerade bei der Arbeit.', literal: 'Ist (der) Paulo (da)? – Nein, er ist arbeitend.' },
    { target: 'Tô chegando! Estou no ônibus.', german: 'Bin gleich da! Ich sitze im Bus.', note: '`tô` = gesprochenes `estou`.' },
    { target: 'Estou estudando português.', german: 'Ich lerne zurzeit Portugiesisch.', note: 'Die Verlaufsform geht auch für „in dieser Zeit“, nicht nur für „genau jetzt“.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['pt.g.gerund'],
      difficulty: 1,
      instruction: 'Ordne jedem Infinitiv sein Gerundium zu.',
      pairs: [
        { left: 'falar', right: 'falando' },
        { left: 'comer', right: 'comendo' },
        { left: 'dormir', right: 'dormindo' },
        { left: 'fazer', right: 'fazendo' },
        { left: 'esperar', right: 'esperando' },
      ],
      feedback: {
        rule: '-ar → -ando, -er → -endo, -ir → -indo.',
        why: 'Der Vokal vor der Endung bleibt erhalten: fal**a**r → fal**a**ndo, com**e**r → com**e**ndo, dorm**i**r → dorm**i**ndo.',
        avoid: 'Einfach das -r gegen -ndo tauschen: fala-r → fala-ndo.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.gerund'],
      difficulty: 1,
      verb: 'escrever',
      tense: 'estar + Gerundium',
      person: 'ela',
      sentence: 'Ela ___ uma mensagem.',
      answers: ['está escrevendo', 'tá escrevendo'],
      feedback: {
        rule: 'ela → `está` + Gerundium: `escrever` → `escrevendo`.',
        why: '`estou` ist die eu-Form; `escreve` wäre das normale Präsens („sie schreibt“ allgemein, nicht gerade jetzt).',
        avoid: 'Zwei Teile: estar in der richtigen Person + -ndo-Form.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['pronunciation', 'listening'],
      topicIds: ['pt.g.gerund'],
      difficulty: 2,
      options: ['está', 'estão'],
      answer: 1,
      hint: '`está` endet auf ein betontes, offenes „a“ (is-TA), `estão` auf ein nasales „ãu“ (is-TÃU) – daran hörst du Singular oder Plural.',
      feedback: {
        rule: '`está` = er/sie/du (ist gerade …), `estão` = sie/ihr (sind gerade …) – der Unterschied liegt nur im nasalen Schluss.',
        why: 'Ohne Nasal klingt `estão` wie `está` – dann versteht man den Singular.',
        avoid: 'Lass die Luft bei `estão` am Ende durch die Nase strömen und runde die Lippen zu einem kurzen „u“.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.gerund', 'pt.g.estar'],
      difficulty: 2,
      sentence: 'Agora eu ___ trabalhando e meus filhos ___ dormindo.',
      answers: [['estou', 'tô'], ['estão', 'tão']],
      bank: ['estou', 'estão', 'está', 'sou', 'são'],
      german: 'Ich arbeite gerade, und meine Kinder schlafen.',
      feedback: {
        rule: 'Verlaufsform: estar in der passenden Person + Gerundium: eu → `estou`, meus filhos (= eles) → `estão`.',
        why: '`sou`/`são` sind Formen von ser – die Verlaufsform geht nur mit estar. `está` ist Singular.',
        avoid: 'Erst das Subjekt bestimmen, dann die estar-Form: estou – está – estamos – estão.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.gerund'],
      difficulty: 2,
      prompt: 'Deine Freundin ruft an: `O que você está fazendo?` Du sitzt gerade beim Abendessen. Was antwortest du?',
      options: [
        { text: 'Eu janto.', why: 'Das normale Präsens beschreibt Gewohnheiten („ich esse zu Abend“ allgemein) – für „gerade jetzt“ nimmt man estar + Gerundium.' },
        { text: 'Estou jantar.', why: 'Nach estar steht das Gerundium auf -ndo, nicht der Infinitiv.' },
        { text: 'Estou jantando.' },
      ],
      answer: 2,
      feedback: {
        rule: 'Was gerade passiert: `estar` + Gerundium → `Estou jantando.`',
        why: 'Die Frage `O que você está fazendo?` fragt nach dem Moment – die Antwort nimmt die Verlaufsform auf.',
        avoid: 'Hör auf die Frage: está fazendo? → Estou …ndo.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.gerund', 'pt.g.reflexive'],
      difficulty: 2,
      tokens: ['Eu', 'estou', 'me', 'vestindo.'],
      extra: ['visto'],
      german: 'Ich ziehe mich gerade an.',
      feedback: {
        rule: 'Reflexive Verben in der Verlaufsform: estar + Pronomen + Gerundium – `Eu estou me vestindo.`',
        why: '`visto` ist das normale Präsens (ich ziehe mich an) und passt nicht zu `estou`.',
        avoid: 'Das Pronomen steht direkt vor der -ndo-Form: estou **me** vestindo.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['pt.g.gerund'],
      difficulty: 2,
      audio: 'Alô? Oi, Carla! O Marcos está tomando banho agora. Ele liga depois.',
      question: 'Warum kann Marcos gerade nicht ans Telefon?',
      options: ['Er duscht gerade.', 'Er schläft gerade.', 'Er kocht gerade.'],
      answer: 0,
      feedback: {
        rule: '`está tomando banho` = duscht gerade (`tomar banho` = duschen).',
        why: '„schläft“ wäre `está dormindo`, „kocht“ `está cozinhando`.',
        avoid: 'Hör auf das Wort nach `está`: Die -ndo-Form verrät, was gerade passiert.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.gerund'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Was machst du gerade? – Ich warte auf den Bus.',
      answers: [
        'O que você está fazendo? – Estou esperando o ônibus.',
        'O que você está fazendo? – Eu estou esperando o ônibus.',
        'O que você está fazendo? – Estou esperando pelo ônibus.',
        'O que você está fazendo? – Eu estou esperando pelo ônibus.',
        'O que você está fazendo agora? – Estou esperando o ônibus.',
        'O que é que você está fazendo? – Estou esperando o ônibus.',
        'Você está fazendo o quê? – Estou esperando o ônibus.',
        'O que você tá fazendo? – Tô esperando o ônibus.',
        'O que você está fazendo? – Tô esperando o ônibus.',
        'O que você tá fazendo? – Estou esperando o ônibus.',
        'O que você está fazendo agora? – Tô esperando o ônibus.',
        'O que você tá fazendo agora? – Tô esperando o ônibus.',
      ],
      feedback: {
        rule: 'Frage: `O que você está fazendo?` Antwort: `Estou esperando o ônibus.` – `esperar` braucht kein „auf“: esperar **o** ônibus (auch: esperar **pelo** ônibus).',
        why: 'Häufige Fehler: `esperando para o ônibus` (wörtlich „auf“) und `Eu espero o ônibus` (Präsens statt Verlaufsform).',
        avoid: '„gerade“ im deutschen Satz ist das Signal für estar + -ndo.',
      },
    },
  ],
  pronunciation: ['pt.p.ao.estao', 'pt.p.nasal.cinco', 'pt.p.r.mar'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.gerund'],
      difficulty: 3,
      prompt: 'Schreib einer Freundin eine kurze Nachricht: Was machst du gerade, und was machen die anderen bei dir zu Hause gerade? (3–4 Sätze)',
      requirements: [
        { pattern: '\\b(estou|tô|to)\\s+(me\\s+)?[a-zà-ú]+ndo\\b', hint: 'Sag, was du gerade machst: „Estou …ndo“.' },
        { pattern: '\\b(está|tá|estão|tão|estamos)\\s+(se\\s+|nos\\s+)?[a-zà-ú]+ndo\\b', hint: 'Sag, was eine andere Person gerade macht: „… está …ndo“ oder „… estão …ndo“.' },
      ],
      samples: ['Oi, Bia! Tudo bem? Estou em casa e estou cozinhando. Meu marido está trabalhando e as crianças estão dormindo. Depois eu ligo para você!'],
      minWords: 12,
      feedback: {
        rule: 'Du: `Estou …ndo`; andere: `está …ndo` (eine Person) oder `estão …ndo` (mehrere).',
        why: 'Häufige Fehler: Infinitiv statt Gerundium (`estou cozinhar`) oder die falsche estar-Form (`eles está`).',
        avoid: 'Prüfe jeden Satz: passende estar-Form + -ndo.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['pt.g.gerund'],
      difficulty: 3,
      prompt: 'Dein Handy klingelt: Melde dich, frag, wer dran ist, und sag, was du gerade machst.',
      keywords: ['alô', 'quem fala', 'estou', 'tô', 'agora', 'ligo depois'],
      minMatch: 3,
      sample: 'Alô? Quem fala? Oi, Ana! Agora estou cozinhando. Eu ligo depois, tá bom?',
      feedback: {
        rule: 'Melden mit `Alô?`, nachfragen mit `Quem fala?`, erklären mit `Estou …ndo`.',
        why: 'Fehlen Schlüsselwörter, hat die Spracherkennung sie nicht gehört – oder sie fehlen in deiner Antwort.',
        avoid: 'Betone `Alô` auf der zweiten Silbe (a-LÔ) und sprich die -ndo-Formen mit nasalem Vokal.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'dialogue',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.gerund'],
      difficulty: 2,
      instruction: 'Du rufst bei deiner Freundin Mariana an. Ihre Mutter nimmt ab. Was sagt sie?',
      lines: [
        { speaker: 'Dona Lúcia', text: 'Alô?', german: 'Hallo?' },
        { speaker: 'Você', text: 'Alô, boa tarde! A Mariana está?', german: 'Hallo, guten Tag! Ist Mariana da?' },
        { speaker: 'Dona Lúcia', text: '…' },
        { speaker: 'Você', text: 'Tudo bem, eu ligo mais tarde. Tchau!', german: 'Alles klar, ich rufe später noch mal an. Tschüss!' },
      ],
      gapIndex: 2,
      options: [
        'Está, mas está tomar banho agora.',
        'Está, mas é tomando banho agora.',
        'Está, mas está tomando banho agora.',
      ],
      answer: 2,
      feedback: {
        rule: '`Está` = sie ist da; was sie gerade macht: `está tomando banho`.',
        why: '`está tomar` benutzt den Infinitiv statt des Gerundiums; `é tomando` nimmt ser statt estar.',
        avoid: 'Verlaufsform = estar + -ndo – immer beide Teile prüfen.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.gerund', 'pt.g.time-dates'],
      difficulty: 3,
      scenarioId: 'pt.sc.telefon',
      goal: 'Telefoniere mit deiner Freundin Júlia: Melde dich mit `Alô?`, sag, was du gerade machst (`Estou …ndo`), und verabrede einen Tag und eine Uhrzeit.',
      turns: 5,
      feedback: {
        rule: 'Am Telefon: `Alô?` – `Estou …ndo` für das, was gerade passiert – Tag mit na/no, Uhrzeit mit às.',
        avoid: 'Wenn du etwas nicht verstehst, frag nach: `Pode repetir, por favor?`',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'translate',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.reflexive', 'pt.g.time-dates'],
      difficulty: 2,
      direction: 'toGerman',
      source: 'Às vezes eu me deito à meia-noite.',
      answers: [
        'Manchmal gehe ich um Mitternacht ins Bett.',
        'Manchmal gehe ich erst um Mitternacht ins Bett.',
        'Manchmal lege ich mich um Mitternacht hin.',
        'Manchmal gehe ich um Mitternacht schlafen.',
        'Um Mitternacht gehe ich manchmal ins Bett.',
      ],
      feedback: {
        rule: '`às vezes` = manchmal, `me deito` = ich gehe ins Bett / lege mich hin, `à meia-noite` = um Mitternacht.',
        why: '`deitar-se` heißt nicht „schlafen“ (`dormir`), sondern „sich hinlegen, ins Bett gehen“.',
        avoid: 'Uhrzeit-Signal `à`/`às` = „um“.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.time-dates'],
      difficulty: 2,
      prompt: 'Wie sagt man „Es ist halb sieben.“?',
      options: [
        { text: 'São seis e meia.' },
        { text: 'São sete e meia.', why: 'Das wäre 7:30 – auf Deutsch „halb acht“.' },
        { text: 'É seis e meia.', why: 'Ab 2 Uhr steht der Plural `são`.' },
      ],
      answer: 0,
      feedback: {
        rule: '„halb sieben“ = 6:30 = `seis e meia` – Portugiesisch zählt ab der vollen Stunde.',
        why: 'Wer „halb sieben“ wörtlich denkt, landet bei `sete` – das ist eine Stunde zu spät.',
        avoid: 'Denk digital: 6:30 → seis e meia.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.tem-haver'],
      difficulty: 2,
      sentence: 'Na minha casa ___ dois banheiros. O banheiro grande ___ ao lado do quarto.',
      answers: [['tem', 'há'], ['fica', 'está', 'é']],
      german: 'In meinem Haus gibt es zwei Badezimmer. Das große Bad liegt neben dem Schlafzimmer.',
      feedback: {
        rule: '„es gibt“ = `tem` (formeller `há`); wo sich etwas befindet = `fica` (auch `está`, umgangssprachlich `é`).',
        why: '`tem` sagt, dass es etwas gibt; `fica` sagt, wo es sich befindet. Mit `tem` in der zweiten Lücke hieße der Satz „das Bad hat neben dem Schlafzimmer“.',
        avoid: 'Gibt es das? → tem. Wo ist es? → fica/está.',
      },
    },
  ],
};

export default lesson;
