import type { Lesson } from '../../types';

const L = 'pt.s0.l05';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'stage0',
  chapterId: 'pt.s0.c2',
  order: 5,
  title: 'Artigos & plural – Dinge benennen',
  subtitle: 'o/a, um/uma, Plural, do/da/no/na',
  icon: '🧩',
  minutes: 12,
  goal:
    'Du kannst Nomen mit dem richtigen **Artikel** verwenden (o, a, os, as, um, uma), bildest den **Plural** und verschmilzt `de` und `em` mit dem Artikel zu **do, da, no, na** – so sagst du z. B. `Sou da Alemanha` und `Estou no Brasil`.',
  canDo: [
    'Ich kenne die bestimmten und unbestimmten Artikel.',
    'Ich erkenne das Genus vieler Nomen an der Endung – und kenne wichtige Ausnahmen.',
    'Ich bilde den Plural regelmäßiger Nomen.',
    'Ich verwende do, da, no, na korrekt, z. B. bei Ländern.',
  ],
  topicIds: ['pt.g.articles-gender', 'pt.g.plural', 'pt.g.contractions'],
  vocab: [
    { id: `${L}.v.livro`, target: 'o livro', german: 'das Buch', pos: 'noun', gender: 'm', plural: 'livros', emoji: '📖', field: 'Gegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.mesa`, target: 'a mesa', german: 'der Tisch', pos: 'noun', gender: 'f', plural: 'mesas', field: 'Gegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.cadeira`, target: 'a cadeira', german: 'der Stuhl', pos: 'noun', gender: 'f', plural: 'cadeiras', emoji: '🪑', field: 'Gegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.homem`, target: 'o homem', german: 'der Mann', pos: 'noun', gender: 'm', plural: 'homens', emoji: '👨', field: 'Personen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.mulher`, target: 'a mulher', german: 'die Frau', pos: 'noun', gender: 'f', plural: 'mulheres', emoji: '👩', field: 'Personen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.amigo`, target: 'o amigo / a amiga', german: 'der Freund / die Freundin', pos: 'noun', gender: 'm/f', plural: 'amigos / amigas', field: 'Personen', stageId: 'stage0', lessonId: L, example: { target: 'Os amigos estão no hotel.', german: 'Die Freunde sind im Hotel.' } },
    { id: `${L}.v.cidade`, target: 'a cidade', german: 'die Stadt', pos: 'noun', gender: 'f', plural: 'cidades', emoji: '🏙️', field: 'Orte', stageId: 'stage0', lessonId: L, example: { target: 'Estou na cidade.', german: 'Ich bin in der Stadt.' } },
    { id: `${L}.v.estacao`, target: 'a estação', german: 'der Bahnhof; die Station', pos: 'noun', gender: 'f', plural: 'estações', emoji: '🚉', field: 'Orte', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.hotel`, target: 'o hotel', german: 'das Hotel', pos: 'noun', gender: 'm', plural: 'hotéis', emoji: '🏨', field: 'Orte', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.dia`, target: 'o dia', german: 'der Tag', pos: 'noun', gender: 'm', plural: 'dias', field: 'Zeit', stageId: 'stage0', lessonId: L, example: { target: 'Bom dia!', german: 'Guten Morgen!' } },
    { id: `${L}.v.problema`, target: 'o problema', german: 'das Problem', pos: 'noun', gender: 'm', plural: 'problemas', field: 'Allgemein', stageId: 'stage0', lessonId: L, example: { target: 'Não tem problema.', german: 'Kein Problem.' } },
    { id: `${L}.v.mapa`, target: 'o mapa', german: 'die Landkarte, der Stadtplan', pos: 'noun', gender: 'm', plural: 'mapas', emoji: '🗺️', field: 'Gegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.foto`, target: 'a foto', german: 'das Foto', pos: 'noun', gender: 'f', plural: 'fotos', emoji: '📷', field: 'Gegenstände', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.flor`, target: 'a flor', german: 'die Blume', pos: 'noun', gender: 'f', plural: 'flores', emoji: '🌸', field: 'Natur', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.alemanha`, target: 'a Alemanha', german: 'Deutschland', pos: 'noun', gender: 'f', emoji: '🇩🇪', field: 'Länder', stageId: 'stage0', lessonId: L, example: { target: 'Sou da Alemanha.', german: 'Ich komme aus Deutschland.' } },
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Artikel',
      headers: ['', 'männlich', 'weiblich'],
      rows: [
        ['bestimmt, Singular (der/die/das)', 'o livro', 'a mesa'],
        ['bestimmt, Plural (die)', 'os livros', 'as mesas'],
        ['unbestimmt, Singular (ein/eine)', 'um livro', 'uma mesa'],
        ['unbestimmt, Plural (einige)', 'uns livros', 'umas mesas'],
      ],
    },
    {
      type: 'text',
      md:
        'Portugiesisch hat nur **zwei** Geschlechter – kein Neutrum. Die Endung hilft oft:\n' +
        '- auf **-o** meist männlich: `o livro`, `o carro`\n' +
        '- auf **-a** meist weiblich: `a mesa`, `a casa`\n' +
        '- auf **-dade** und **-ção** praktisch immer weiblich: `a cidade`, `a estação` (seltene Ausnahme: `o coração`)\n' +
        'Wichtige Ausnahmen: `o dia`, `o mapa`, `o problema` sind männlich; `a foto`, `a mão` sind weiblich. Bei anderen Endungen (`o hotel`, `a flor`, `a mulher`) hilft nur: mit Artikel lernen.',
    },
    {
      type: 'compare',
      target: 'a mesa · o livro · a flor · o problema',
      german: 'der Tisch · das Buch · die Blume · das Problem',
      md: 'Das deutsche Genus hilft dir nicht: „der Tisch“ ist weiblich (`a mesa`), „das Buch“ männlich (`o livro`). Lerne jedes Nomen **mit Artikel** – so wie im Deutschen auch.',
    },
    {
      type: 'table',
      title: 'Plural',
      headers: ['Wortende', 'Regel', 'Beispiel'],
      rows: [
        ['Vokal', '+ s', 'casa → casas, café → cafés'],
        ['-r, -z', '+ es', 'flor → flores, mulher → mulheres'],
        ['-m', '-m → -ns', 'homem → homens'],
        ['-l', '-l → -is', 'hotel → hotéis'],
        ['-ão', 'meist → -ões', 'estação → estações (aber: pão → pães, mão → mãos)'],
      ],
    },
    {
      type: 'table',
      title: 'Kontraktionen: de / em + Artikel',
      headers: ['', '+ o', '+ a', '+ os', '+ as'],
      rows: [
        ['de (von, aus)', 'do', 'da', 'dos', 'das'],
        ['em (in, an, auf)', 'no', 'na', 'nos', 'nas'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Sou', role: 'verb' },
        { text: ' ' },
        { text: 'da', role: 'preposition' },
        { text: ' ' },
        { text: 'Alemanha', role: 'noun' },
        { text: ' e ' },
        { text: 'estou', role: 'verb' },
        { text: ' ' },
        { text: 'no', role: 'preposition' },
        { text: ' ' },
        { text: 'Brasil', role: 'noun' },
        { text: '.' },
      ],
      german: 'Ich komme aus Deutschland und bin in Brasilien.',
    },
    {
      type: 'mistake',
      wrong: 'Sou de a Alemanha. / Estou em o hotel.',
      right: 'Sou da Alemanha. / Estou no hotel.',
      why: '`de` und `em` verschmelzen **immer** mit dem bestimmten Artikel – das ist Pflicht, nicht Stil. Die meisten Länder haben einen Artikel (`o Brasil`, `a Alemanha`), Städte meist nicht (`de Berlim`, `em São Paulo`; Ausnahme: `no Rio`).',
    },
    {
      type: 'tip',
      md: 'Merksätze: **Nomen nie allein lernen** – immer `o dia`, `a cidade`. Und: **de + o = do, em + a = na** – kleine Wörter kleben zusammen.',
    },
  ],
  examples: [
    { target: 'o livro, os livros', german: 'das Buch, die Bücher' },
    { target: 'Um homem e uma mulher.', german: 'Ein Mann und eine Frau.' },
    {
      target: 'Sou do Brasil.',
      german: 'Ich komme aus Brasilien.',
      literal: 'Ich bin aus dem Brasilien.',
      parts: [{ text: 'Sou', role: 'verb' }, { text: ' ' }, { text: 'do', role: 'preposition' }, { text: ' ' }, { text: 'Brasil', role: 'noun' }, { text: '.' }],
    },
    {
      target: 'Estou na cidade.',
      german: 'Ich bin in der Stadt.',
      parts: [{ text: 'Estou', role: 'verb' }, { text: ' ' }, { text: 'na', role: 'preposition' }, { text: ' ' }, { text: 'cidade', role: 'noun' }, { text: '.' }],
    },
    { target: 'Os amigos estão no hotel.', german: 'Die Freunde sind im Hotel.' },
    { target: 'As flores são da Ana.', german: 'Die Blumen sind von Ana.', note: 'In São Paulo und im Süden steht vor Vornamen oft ein Artikel (`a Ana`, `o Pedro`) – im Nordosten eher nicht. Beides ist korrekt.' },
    { target: 'As mulheres e os homens.', german: 'Die Frauen und die Männer.', note: 'Plural: mulher → mulheres, homem → homens.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'imageMatch',
      skills: ['vocabulary', 'reading'],
      difficulty: 1,
      pairs: [
        { emoji: '📖', word: 'o livro' },
        { emoji: '🪑', word: 'a cadeira' },
        { emoji: '👨', word: 'o homem' },
        { emoji: '👩', word: 'a mulher' },
        { emoji: '🗺️', word: 'o mapa' },
        { emoji: '📷', word: 'a foto' },
      ],
      feedback: {
        rule: 'Lerne die Nomen mit Artikel: o livro, a cadeira, o homem, a mulher, o mapa, a foto.',
        why: '`o mapa` (männlich, trotz -a) und `a foto` (weiblich, trotz -o) sind Ausnahmen.',
        avoid: 'Sprich den Artikel beim Lernen immer mit.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.articles-gender'],
      difficulty: 1,
      prompt: 'Welcher Artikel passt? ___ dia',
      options: [{ text: 'o' }, { text: 'a', why: '`dia` endet auf -a, ist aber männlich.' }, { text: 'os', why: '`os` ist Plural – `dia` steht im Singular.' }],
      answer: 0,
      feedback: {
        rule: '`dia` ist männlich: `o dia` (deshalb auch `bom dia`).',
        why: 'Die Endung -a ist nur eine Faustregel – `dia`, `mapa`, `problema` sind Ausnahmen.',
        avoid: 'Denk an `bom dia`: bom (männlich) → o dia.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.articles-gender'],
      difficulty: 2,
      sentence: '___ cidade e ___ problema',
      answers: [['a'], ['o']],
      bank: ['o', 'a', 'os', 'as'],
      german: 'die Stadt und das Problem',
      feedback: {
        rule: 'Wörter auf **-dade** sind weiblich (`a cidade`); `problema` ist männlich (`o problema`).',
        why: '`problema` endet auf -a, ist aber eine Ausnahme (wie viele Wörter auf -ma aus dem Griechischen).',
        avoid: 'Merke: -dade/-ção → a; -ma (problema, sistema, tema) → o.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['pt.g.plural'],
      difficulty: 2,
      instruction: 'Ordne jedem Wort seinen Plural zu.',
      pairs: [
        { left: 'flor', right: 'flores' },
        { left: 'homem', right: 'homens' },
        { left: 'hotel', right: 'hotéis' },
        { left: 'estação', right: 'estações' },
        { left: 'café', right: 'cafés' },
      ],
      feedback: {
        rule: 'Vokal + s; -r → -res; -m → -ns; -l → -is; -ão → meist -ões.',
        why: '`homem` wird nicht zu „homems“, weil m vor s zu n wird. `hotel` wird zu `hotéis`.',
        avoid: 'Schau zuerst auf den letzten Buchstaben – er bestimmt die Pluralregel.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.contractions'],
      difficulty: 2,
      sentence: 'Sou ___ Alemanha e estou ___ Brasil.',
      answers: [['da'], ['no']],
      bank: ['da', 'do', 'na', 'no', 'de', 'em'],
      german: 'Ich komme aus Deutschland und bin in Brasilien.',
      feedback: {
        rule: '`de` + `a` (Alemanha) = `da`; `em` + `o` (Brasil) = `no`.',
        why: 'Länder haben meist einen Artikel: `a Alemanha`, `o Brasil`. `de`/`em` allein wären hier falsch.',
        avoid: 'Frage: Welcher Artikel gehört zum Land? Dann verschmelzen: de/em + o/a.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.contractions', 'pt.g.plural'],
      difficulty: 2,
      tokens: ['Os', 'amigos', 'estão', 'no', 'hotel.'],
      extra: ['em', 'são'],
      german: 'Die Freunde sind im Hotel.',
      feedback: {
        rule: '„im Hotel“ = `no hotel` (em + o). Ort → `estar`: `estão`.',
        why: '`em o` verschmilzt immer zu `no`; `são` (ser) passt nicht zu einer Ortsangabe.',
        avoid: 'Sobald nach `em` ein o/a folgt: verschmelzen!',
      },
    },
    {
      id: `${L}.g07`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['pt.g.contractions'],
      difficulty: 2,
      audio: 'Estou na estação.',
      question: 'Wo ist die Person?',
      options: ['im Hotel', 'am Bahnhof', 'in der Stadt'],
      answer: 1,
      feedback: {
        rule: '`na estação` = am/im Bahnhof (em + a estação).',
        why: '„im Hotel“ wäre `no hotel`, „in der Stadt“ `na cidade`.',
        avoid: 'Hör auf das Nomen nach `no`/`na` – der kleine Artikel verrät dir auch das Genus.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.contractions'],
      difficulty: 3,
      sentence: 'Eu sou de o Brasil.',
      answers: ['Eu sou do Brasil.', 'Sou do Brasil.'],
      german: 'Ich komme aus Brasilien.',
      feedback: {
        rule: '`de` + `o` wird immer zu `do`: `Sou do Brasil.`',
        why: '`de o` getrennt ist im Portugiesischen nicht möglich.',
        avoid: 'Merke die Paare: do/da (von), no/na (in).',
      },
    },
  ],
  pronunciation: ['pt.p.nasal.um', 'pt.p.s-x.casa', 'pt.p.l-final.brasil'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.contractions'],
      difficulty: 2,
      prompt: 'Schreib 2–3 Sätze: Woher kommst du (Land und Stadt) und wo bist du gerade? Nutze mindestens eine Kontraktion (do/da/no/na).',
      requirements: [
        { pattern: '\\b(do|da|dos|das|no|na|nos|nas)\\b', hint: 'Verwende mindestens eine Kontraktion wie „da Alemanha“ oder „no hotel“.' },
        { pattern: '\\b(sou|estou)\\b', hint: 'Nutze „sou“ (Herkunft) und/oder „estou“ (Ort).' },
      ],
      samples: ['Sou da Alemanha, sou de Munique. Estou no Rio de Janeiro, no hotel.'],
      minWords: 6,
      feedback: {
        rule: 'Land mit Artikel → `da Alemanha`, `do Brasil`; Stadt ohne Artikel → `de Munique`; Ort → `estou no/na …`.',
        why: '`de a`/`em o` wären falsch – sie müssen verschmelzen.',
        avoid: 'Überlege vor jedem `de`/`em`: Folgt ein Artikel?',
      },
    },
    {
      id: `${L}.a02`,
      type: 'situation',
      skills: ['grammar', 'speaking'],
      topicIds: ['pt.g.contractions', 'pt.g.estar'],
      difficulty: 2,
      scenario: 'Du wartest am Bahnhof. Eine Freundin ruft an und fragt: „Onde você está?“ (Wo bist du?)',
      options: [
        { text: 'Estou na estação.' },
        { text: 'Estou em a estação.', why: '`em` + `a` muss zu `na` verschmelzen.' },
        { text: 'Sou na estação.', why: 'Aufenthaltsort → `estar`, nicht `ser`.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Ort → `estar`; `em` + `a` = `na`: `Estou na estação.`',
        why: 'Beide falschen Antworten enthalten je einen typischen Fehler: fehlende Kontraktion bzw. falsches Verb.',
        avoid: 'Wo? → estar + no/na.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: ['pt.g.contractions'],
      difficulty: 2,
      prompt: 'Sag laut, aus welchem Land du kommst und wo du gerade bist (z. B. zu Hause, in der Stadt, im Hotel).',
      keywords: ['sou', 'da', 'do', 'estou', 'na', 'no', 'em casa'],
      minMatch: 3,
      sample: 'Sou da Alemanha e estou em casa.',
      feedback: {
        rule: 'Herkunft: `Sou da/do …`; Ort: `Estou no/na …` oder `Estou em casa`.',
        why: '`em casa` („zu Hause“) steht ohne Artikel – das ist eine feste Wendung.',
        avoid: 'Sprich die Kontraktion mit dem Land in einem Fluss: `da Alemanha` ≈ „da-le-MÃ-nja“ – die beiden a verschmelzen.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.estar', 'pt.g.pronouns'],
      difficulty: 2,
      verb: 'estar',
      tense: 'Präsens',
      person: 'a gente',
      sentence: 'A gente ___ em casa.',
      answers: ['está', 'tá'],
      feedback: {
        rule: '`a gente` bekommt die Verbform der 3. Person Singular: `a gente está` (umgangssprachlich `tá`).',
        why: '`estamos` gehört zu `nós`, nicht zu `a gente`.',
        avoid: 'a gente = wir, aber grammatisch wie `ele`.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 1,
      prompt: 'Ela ___ professora.',
      options: [{ text: 'é' }, { text: 'está', why: 'Der Beruf gehört zum Steckbrief → `ser`.' }, { text: 'são', why: '`são` ist Plural.' }],
      answer: 0,
      feedback: {
        rule: 'Beruf → `ser`: `Ela é professora.`',
        why: '`está` beschreibt Zustände, `são` ist die Pluralform.',
        avoid: 'Steckbrief → ser.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      audio: 'mão',
      question: 'Was bedeutet das Wort?',
      options: ['Hand', 'Brot', 'nein'],
      answer: 0,
      feedback: {
        rule: '`mão` = Hand, `pão` = Brot, `não` = nein – alle mit nasalem „ãu“.',
        why: 'Nur der erste Laut unterscheidet die drei Wörter.',
        avoid: 'Konzentrier dich auf den Anfang: m – p – n.',
      },
    },
  ],
};

export default lesson;
