import type { Lesson } from '../../types';

const L = 'pt.s0.l02';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'stage0',
  chapterId: 'pt.s0.c1',
  order: 2,
  title: 'Sons do português – der brasilianische Klang',
  subtitle: 'Nasalvokale, ão, lh/nh, R, t/d vor i',
  icon: '🗣️',
  minutes: 12,
  goal:
    'Du lernst die Laute kennen, die das brasilianische Portugiesisch so typisch klingen lassen: **Nasalvokale** und **-ão**, **lh/nh**, die zwei **R-Laute**, **t/d vor i** („tsch“/„dsch“), das **L am Silbenende** und die abgeschwächten Endvokale.',
  canDo: [
    'Ich erkenne Nasalvokale und spreche não richtig aus.',
    'Ich kann lh und nh aussprechen.',
    'Ich weiß, wann ein R wie ein deutsches h klingt.',
    'Ich spreche t und d vor i wie „tsch“ und „dsch“.',
    'Ich weiß, dass -o am Wortende wie u und -e wie i klingt.',
  ],
  topicIds: ['pt.g.sounds'],
  vocab: [
    { id: `${L}.v.nao`, target: 'não', german: 'nein; nicht', pos: 'adv', field: 'Grundwörter', stageId: 'stage0', lessonId: L, example: { target: 'Não, obrigado.', german: 'Nein, danke.' } },
    { id: `${L}.v.sim`, target: 'sim', german: 'ja', pos: 'adv', field: 'Grundwörter', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.pao`, target: 'o pão', german: 'das Brot', pos: 'noun', gender: 'm', plural: 'pães', emoji: '🍞', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.mao`, target: 'a mão', german: 'die Hand', pos: 'noun', gender: 'f', plural: 'mãos', emoji: '✋', field: 'Körper', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.filho`, target: 'o filho / a filha', german: 'der Sohn / die Tochter', pos: 'noun', gender: 'm/f', field: 'Familie', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.vinho`, target: 'o vinho', german: 'der Wein', pos: 'noun', gender: 'm', emoji: '🍷', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L, example: { target: 'Vinho? Não, obrigada.', german: 'Wein? Nein, danke.' } },
    { id: `${L}.v.carro`, target: 'o carro', german: 'das Auto', pos: 'noun', gender: 'm', emoji: '🚗', field: 'Verkehr', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.caro`, target: 'caro / cara', german: 'teuer', pos: 'adj', field: 'Einkaufen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.rio`, target: 'o rio', german: 'der Fluss', pos: 'noun', gender: 'm', emoji: '🏞️', field: 'Natur', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.leite`, target: 'o leite', german: 'die Milch', pos: 'noun', gender: 'm', emoji: '🥛', field: 'Essen & Trinken', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.tia`, target: 'a tia', german: 'die Tante', pos: 'noun', gender: 'f', field: 'Familie', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.brasil`, target: 'o Brasil', german: 'Brasilien', pos: 'noun', gender: 'm', emoji: '🇧🇷', field: 'Länder', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.casa`, target: 'a casa', german: 'das Haus; das Zuhause', pos: 'noun', gender: 'f', emoji: '🏠', field: 'Wohnen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.avo-f`, target: 'a avó', german: 'die Oma, Großmutter', pos: 'noun', gender: 'f', emoji: '👵', field: 'Familie', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.avo-m`, target: 'o avô', german: 'der Opa, Großvater', pos: 'noun', gender: 'm', emoji: '👴', field: 'Familie', stageId: 'stage0', lessonId: L },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Gute Nachricht: Portugiesisch wird ziemlich regelmäßig ausgesprochen – wenn du ein paar Regeln kennst. Die meisten deutschen Laute passen. Schwierig sind vor allem die Laute, die es im Deutschen **nicht** gibt, und Buchstaben, die **anders** klingen als bei uns. Die Übersicht unten ist deine Landkarte – die Details übst du im Aussprache-Labor.',
    },
    {
      type: 'table',
      title: 'Die wichtigsten Laute',
      headers: ['Schreibung', 'Klang (ungefähr)', 'Beispiel'],
      rows: [
        ['ã, am, an, em, en, im, om, um', 'Vokal durch Mund und Nase', 'sim, bom, manhã'],
        ['ão (und -am am Wortende)', 'nasales „au“', 'não, pão, mão'],
        ['lh', '„lj“ wie in „Familie“ – ein Laut', 'filho'],
        ['nh', '„nj“ wie in „Champagner“', 'vinho'],
        ['r am Wortanfang, rr', 'gehauchtes „h“', 'Rio, carro'],
        ['r zwischen Vokalen', 'kurz mit der Zungenspitze getippt', 'caro'],
        ['t / d vor i (auch vor -e am Ende)', '„tsch“ / „dsch“', 'tia, dia, leite'],
        ['l am Silbenende', 'wie „u“', 'Brasil'],
        ['-o / -e am Wortende (unbetont)', 'wie „u“ / „i“', 'carro, leite'],
        ['s zwischen Vokalen', 'summendes „s“ wie in „Rose“', 'casa'],
      ],
    },
    {
      type: 'text',
      md:
        '**Nasalvokale** sind der Schlüssel zum brasilianischen Klang: Die Luft strömt gleichzeitig durch Mund und Nase – ähnlich wie im Französischen „bon“. Ein `m` oder `n` am Silbenende wird **nicht** als eigener Laut gesprochen, es zeigt nur an, dass der Vokal davor nasal ist: `sim` ≈ „ßĩ“, `bom` ≈ „bõ“.\n' +
        'Die Tilde (~) auf `ã` und `õ` bedeutet ebenfalls „nasal“. `ão` klingt wie ein „au“ durch die Nase: `não` ≈ „nãu“.',
    },
    {
      type: 'compare',
      target: 'tia · dia · leite',
      german: '„TSCHI-a“ · „DSCHI-a“ · „LEI-tschi“',
      md: 'In fast ganz Brasilien werden `t` und `d` vor einem i-Laut zu „tsch“ und „dsch“ – auch vor einem unbetonten `-e` am Wortende, das ja wie „i“ klingt. Vor a, o, u bleiben sie normal: `tudo` ≈ „TU-du“.',
    },
    {
      type: 'mistake',
      wrong: 'caro = carro (beide mit deutschem Reibe-R)',
      right: 'caro [ˈkaɾu] ≠ carro [ˈkahu]',
      why: 'Ein einzelnes `r` zwischen Vokalen ist ein kurzer Zungenschlag (wie ein schnelles „d“). `rr` und `r` am Wortanfang klingen wie ein kräftiges deutsches **h**. Wer beides gleich spricht, sagt statt „teuer“ plötzlich „Auto“.',
    },
    {
      type: 'tip',
      md: 'Merksätze: **Tilde = Nase.** – **Doppel-R = h.** – **t/d vor i = tsch/dsch.** – **L am Ende = u.** Und das unbetonte -o am Wortende ist fast immer ein „u“: `obrigado` ≈ „o-bri-GA-du“.',
    },
    {
      type: 'variant',
      variant: 'pt-BR',
      md:
        'Brasilien ist groß – die Aussprache variiert: In **Rio de Janeiro** klingt `s` am Silbenende wie „sch“ (`mesmo` ≈ „MESCH-mu“), in Teilen des **Nordostens** sprechen viele `t`/`d` vor i ohne „tsch“. Das R am Silbenende reicht von „h“ (Rio, Nordosten) bis zum getippten oder amerikanisch klingenden R (São Paulo, Landesinneres). Die App übt eine überregional verständliche Aussprache.',
    },
    { type: 'audio', text: 'não, pão, mão', label: 'Nasales „ão“ anhören' },
  ],
  examples: [
    {
      target: 'Não, obrigado.',
      german: 'Nein, danke.',
      parts: [{ text: 'Não', role: 'negation' }, { text: ', ' }, { text: 'obrigado', role: 'other' }, { text: '.' }],
      note: '`não` ist nasal, `obrigado` endet auf „-du“.',
    },
    { target: 'Bom dia, tia!', german: 'Guten Morgen, Tante!', note: '`dia` ≈ „DSCHI-a“, `tia` ≈ „TSCHI-a“.' },
    { target: 'Vinho? Não, obrigada.', german: 'Wein? Nein, danke.', note: '`nh` in `vinho` wie „nj“ – hier spricht eine Frau: **obrigada**.' },
    { target: 'Leite? Sim!', german: 'Milch? Ja!', note: '`leite` ≈ „LEI-tschi“, `sim` ≈ „ßĩ“ (nasal, ohne hörbares m).' },
    { target: 'O carro é caro.', german: 'Das Auto ist teuer.', note: '`carro` ≈ „KA-hu“, `caro` ≈ „KA-ru“ mit getipptem R.' },
    { target: 'A avó e o avô.', german: 'Die Oma und der Opa.', note: '`avó` mit offenem o (wie „Sonne“), `avô` mit geschlossenem o (wie „Sohn“). Das `e` (und) klingt wie „i“.' },
    { target: 'Brasil', german: 'Brasilien', note: '≈ „bra-SIU“ – das L am Ende klingt wie u, das s dazwischen summt.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'mc',
      skills: ['pronunciation', 'reading'],
      topicIds: ['pt.g.sounds'],
      difficulty: 1,
      prompt: 'Wie klingt das `t` in `leite` (Milch)?',
      options: [
        { text: 'wie „tsch“: „LEI-tschi“' },
        { text: 'wie deutsches t: „LEI-te“', why: 'Das unbetonte -e am Ende klingt wie i – und vor i wird t zu „tsch“.' },
        { text: 'wie „ts“: „LEI-tse“', why: '„ts“ gibt es hier nicht; richtig ist „tsch“.' },
      ],
      answer: 0,
      feedback: {
        rule: '`t` vor einem i-Laut (auch vor unbetontem -e am Wortende) klingt wie „tsch“.',
        why: '`leite` endet auf ein unbetontes -e, das wie „i“ klingt – deshalb „LEI-tschi“.',
        avoid: 'Sprich zuerst das Wortende als „i“, dann kommt das „tsch“ fast von selbst.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'matchPairs',
      skills: ['pronunciation', 'reading'],
      topicIds: ['pt.g.sounds'],
      difficulty: 1,
      instruction: 'Ordne jeder Schreibung ihren Klang zu.',
      pairs: [
        { left: 'lh', right: '„lj“ wie in „Familie“' },
        { left: 'nh', right: '„nj“ wie in „Champagner“' },
        { left: 'ão', right: 'nasales „au“' },
        { left: 'rr', right: 'gehauchtes „h“' },
        { left: 'l am Silbenende', right: 'wie „u“' },
      ],
      feedback: {
        rule: 'lh = „lj“, nh = „nj“, ão = nasales „au“, rr = „h“, l am Silbenende = „u“.',
        why: 'Diese Buchstabenkombinationen stehen jeweils für **einen** Laut – nicht für zwei getrennte Buchstaben.',
        avoid: 'Lies `h` nach l oder n nie als eigenen Laut: Es macht aus l → „lj“ und aus n → „nj“.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'imageMatch',
      skills: ['vocabulary', 'pronunciation'],
      difficulty: 1,
      instruction: 'Ordne die Bilder den Wörtern zu – und sprich jedes Wort laut mit.',
      pairs: [
        { emoji: '🍞', word: 'pão' },
        { emoji: '✋', word: 'mão' },
        { emoji: '🍷', word: 'vinho' },
        { emoji: '🚗', word: 'carro' },
        { emoji: '🏠', word: 'casa' },
        { emoji: '🥛', word: 'leite' },
      ],
      feedback: {
        rule: 'pão = Brot, mão = Hand, vinho = Wein, carro = Auto, casa = Haus, leite = Milch.',
        why: '`pão` und `mão` unterscheiden sich nur im ersten Laut – beide enden auf nasales „ãu“.',
        avoid: 'Sprich jedes Wort beim Zuordnen einmal laut aus – so verknüpfst du Bild, Schrift und Klang.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      options: ['avó', 'avô'],
      answer: 0,
      hint: '`avó` (Oma) hat ein **offenes** o wie in „Sonne“, `avô` (Opa) ein **geschlossenes** o wie in „Sohn“.',
      feedback: {
        rule: 'Akzent ´ = offener Vokal (ó wie „Sonne“), Akzent ^ = geschlossener Vokal (ô wie „Sohn“).',
        why: 'Beide Wörter werden auf der letzten Silbe betont – nur die Öffnung des o unterscheidet Oma und Opa.',
        avoid: 'Offen = Mund weiter auf (Kiefer runter), geschlossen = Lippen runder und enger.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      options: ['caro', 'carro'],
      answer: 1,
      hint: '`carro` (Auto) hat ein gehauchtes „h“ in der Mitte, `caro` (teuer) einen kurzen Zungenschlag.',
      feedback: {
        rule: '`rr` klingt wie ein kräftiges h („KA-hu“), ein einzelnes r zwischen Vokalen ist ein kurzer Zungenschlag („KA-ru“).',
        why: 'Wer die beiden verwechselt, sagt „teuer“ statt „Auto“ – oder umgekehrt.',
        avoid: 'Für `caro`: Sprich „ka-du“ ganz schnell – der Zungenschlag ist fast derselbe.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'listening',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      audio: 'Brasil',
      question: 'Wie klingt das Wortende von `Brasil`?',
      options: ['„-sil“ mit deutschem L', '„-siu“ – das L klingt wie u', '„-si“ – das L fällt ganz weg'],
      answer: 1,
      feedback: {
        rule: 'Ein `l` am Silbenende klingt im brasilianischen Portugiesisch wie ein kurzes „u“.',
        why: 'Das L verschwindet nicht, es wird zu einem u-Laut: „bra-SIU“.',
        avoid: 'Denk an „Brasil“ = „Bra-siu“. Die Zungenspitze berührt am Ende nicht den Gaumen.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'speak',
      skills: ['pronunciation', 'speaking'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      text: 'Bom dia, tia!',
      german: 'Guten Morgen, Tante!',
      phonetic: 'bõ DSCHI-a, TSCHI-a',
      ipa: '[bõ ˈdʒiɐ ˈtʃiɐ]',
      pronItemId: 'pt.p.d-t.dia',
      feedback: {
        rule: '`bom` ist nasal (kein hörbares m), `dia` ≈ „DSCHI-a“, `tia` ≈ „TSCHI-a“.',
        why: 'Deutschsprachige sprechen oft „bomm di-a“ – das klingt stark nach Akzent.',
        avoid: 'Übe langsam: erst „bõ“, dann „dschi-a“, dann „tschi-a“ – danach alles zusammen.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['pt.g.sounds'],
      difficulty: 3,
      audio: 'Não, obrigada.',
      answers: ['Não, obrigada.', 'Não obrigada'],
      german: 'Nein, danke. (Frau spricht)',
      feedback: {
        rule: 'Der Laut „nãu“ wird `não` geschrieben – mit Tilde auf dem a. Eine Frau sagt `obrigada`.',
        why: 'Typische Fehler: „nao“ ohne Tilde, „nau“ oder „obrigado“ statt „obrigada“.',
        avoid: 'Hörst du ein nasales „au“ am Wortende, schreib `-ão`.',
      },
    },
  ],
  pronunciation: ['pt.p.ao.nao', 'pt.p.d-t.dia', 'pt.p.lh-nh.filho'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['speaking', 'reading'],
      difficulty: 1,
      scenario: 'Im Café fragt dich die Bedienung: „Leite?“ Du möchtest keine Milch. Was sagst du (als Mann)?',
      options: [
        { text: 'Não, obrigado.' },
        { text: 'Sim, obrigado.', why: '`Sim` heißt „ja“ – dann bekämst du Milch.' },
        { text: 'De nada.', why: '`De nada` antwortet auf ein Danke („gern geschehen“).' },
      ],
      answer: 0,
      feedback: {
        rule: 'Höflich ablehnen: `Não, obrigado.` (Mann) / `Não, obrigada.` (Frau).',
        why: '`Sim` bedeutet Zustimmung, `De nada` passt nur nach einem Dank.',
        avoid: 'Merke die Formel „Nein, danke“ = `Não, obrigado/a` – mit nasalem „nãu“.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'freeText',
      skills: ['writing', 'pronunciation'],
      difficulty: 2,
      prompt: 'Jemand bietet dir Wein an: „Vinho?“ Lehne höflich ab und schreib deine Antwort auf.',
      requirements: [
        { pattern: '\\bn[aã]o\\b', hint: 'Verneine mit „não“.' },
        { pattern: '\\bobrigad[oa]\\b', hint: 'Bedanke dich mit „obrigado“ bzw. „obrigada“.' },
      ],
      samples: ['Não, obrigado.', 'Não, obrigada.'],
      feedback: {
        rule: 'Ablehnen = `Não` + `obrigado/obrigada`.',
        why: 'Ohne `obrigado/a` klingt ein bloßes „Não!“ im Brasilianischen schnell unhöflich.',
        avoid: 'Schreib `não` mit Tilde – ohne sie ist das Wort falsch geschrieben.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      difficulty: 2,
      prompt: 'Sag laut: „Guten Morgen! Wein? Nein, danke.“ – achte auf das „dsch“ in dia, das nh in vinho und das nasale não.',
      keywords: ['bom dia', 'vinho', 'não', 'obrigado', 'obrigada'],
      minMatch: 3,
      sample: 'Bom dia! Vinho? Não, obrigado.',
      feedback: {
        rule: '`Bom dia` (dsch), `vinho` (nj), `não` (nasales au), `obrigado/a` (-o klingt wie u).',
        why: 'Wenn die Spracherkennung ein Wort nicht versteht, liegt es oft an einem dieser Laute.',
        avoid: 'Sprich langsam und deutlich – Tempo kommt später von allein.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'cloze',
      skills: ['vocabulary', 'grammar'],
      difficulty: 1,
      sentence: '___ dia! Tudo bem?',
      answers: [['Bom']],
      bank: ['Bom', 'Boa', 'Oi'],
      german: 'Guten Morgen! Wie geht’s?',
      feedback: {
        rule: '`dia` ist männlich → `Bom dia`.',
        why: '`Boa` passt zu weiblichen Wörtern wie `tarde` und `noite`.',
        avoid: 'Merke die Formel als Ganzes: **bom dia**.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      difficulty: 1,
      audio: 'Boa tarde!',
      question: 'Was hörst du?',
      options: ['Boa tarde!', 'Boa noite!', 'Bom dia!'],
      answer: 0,
      feedback: {
        rule: '`Boa tarde` = guten Tag (nachmittags).',
        why: 'Achte auf das zweite Wort: `tarde` ≈ „TAH-dschi“, `noite` ≈ „NOI-tschi“.',
        avoid: 'Das „dsch“ am Ende von `tarde` hilft dir beim Erkennen.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'mc',
      skills: ['pronunciation', 'reading'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      prompt: 'In welchem Wort hörst du ein „tsch“?',
      options: [{ text: 'tudo' }, { text: 'noite' }, { text: 'obrigado' }],
      answer: 1,
      feedback: {
        rule: '„tsch“ entsteht nur, wenn auf `t` ein i-Laut folgt: `noite` ≈ „NOI-tschi“.',
        why: 'In `tudo` folgt ein u – das t bleibt normal. `obrigado` hat gar kein t, sondern ein d vor o.',
        avoid: 'Schau auf den Buchstaben nach t/d: i oder unbetontes -e am Ende → „tsch“/„dsch“.',
      },
    },
  ],
};

export default lesson;
