import type { Lesson } from '../../types';

const L = 'pt.s0.l06';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'stage0',
  chapterId: 'pt.s0.c3',
  order: 6,
  title: 'Números – Zahlen von 0 bis 100',
  subtitle: 'Zählen, Preise, Telefonnummern',
  icon: '🔢',
  minutes: 12,
  goal:
    'Du kannst die Zahlen von **0 bis 100** verstehen und sagen, Preise in **Reais** nennen und eine Telefonnummer so diktieren, wie man es in Brasilien macht – inklusive der berühmten `meia` für die Sechs.',
  canDo: [
    'Ich kann von 0 bis 100 zählen.',
    'Ich unterscheide um/uma und dois/duas.',
    'Ich verstehe und nenne einfache Preise (Quanto é? – São vinte reais.).',
    'Ich kann eine Telefonnummer auf brasilianische Art diktieren.',
  ],
  topicIds: ['pt.g.numbers'],
  vocab: [
    { id: `${L}.v.zero`, target: 'zero', german: 'null', pos: 'num', emoji: '0️⃣', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.um`, target: 'um / uma', german: 'eins; ein / eine', pos: 'num', emoji: '1️⃣', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'uma casa', german: 'ein Haus' } },
    { id: `${L}.v.dois`, target: 'dois / duas', german: 'zwei', pos: 'num', emoji: '2️⃣', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'duas mulheres', german: 'zwei Frauen' } },
    { id: `${L}.v.tres`, target: 'três', german: 'drei', pos: 'num', emoji: '3️⃣', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.cinco`, target: 'cinco', german: 'fünf', pos: 'num', emoji: '5️⃣', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.dez`, target: 'dez', german: 'zehn', pos: 'num', emoji: '🔟', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.dezesseis`, target: 'dezesseis', german: 'sechzehn', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.vinte`, target: 'vinte', german: 'zwanzig', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'vinte e cinco', german: 'fünfundzwanzig' } },
    { id: `${L}.v.cinquenta`, target: 'cinquenta', german: 'fünfzig', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.cem`, target: 'cem', german: 'hundert', pos: 'num', emoji: '💯', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.meia`, target: 'meia', german: 'sechs (beim Diktieren von Nummern)', pos: 'num', field: 'Zahlen', stageId: 'stage0', lessonId: L, example: { target: 'nove, oito, meia', german: '9-8-6' } },
    { id: `${L}.v.numero`, target: 'o número', german: 'die Nummer, die Zahl', pos: 'noun', gender: 'm', plural: 'números', field: 'Zahlen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.telefone`, target: 'o telefone', german: 'das Telefon', pos: 'noun', gender: 'm', plural: 'telefones', emoji: '☎️', field: 'Kommunikation', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.real`, target: 'o real / os reais', german: 'der Real / die Reais (brasilianische Währung)', pos: 'noun', gender: 'm', plural: 'reais', emoji: '💵', field: 'Geld', stageId: 'stage0', lessonId: L, example: { target: 'São dez reais.', german: 'Das macht zehn Reais.' } },
    { id: `${L}.v.quanto-e`, target: 'Quanto é?', german: 'Wie viel macht das? / Was kostet das?', pos: 'phrase', field: 'Einkaufen', stageId: 'stage0', lessonId: L, example: { target: 'Quanto é? – São vinte reais.', german: 'Was macht das? – 20 Reais.' } },
  ],
  explanation: [
    {
      type: 'table',
      title: '0–10',
      headers: ['Zahl', 'Portugiesisch', 'Aussprache-Hilfe'],
      rows: [
        ['0', 'zero', 'SÄ-ru (offenes e)'],
        ['1', 'um / uma', 'ũ / U-ma'],
        ['2', 'dois / duas', 'doiss / DU-as'],
        ['3', 'três', 'tress'],
        ['4', 'quatro', 'KWA-tru'],
        ['5', 'cinco', 'ßĨ-ku'],
        ['6', 'seis', 'ßeiss'],
        ['7', 'sete', 'ßÄ-tschi'],
        ['8', 'oito', 'OI-tu'],
        ['9', 'nove', 'NO-wi (offenes o)'],
        ['10', 'dez', 'däss'],
      ],
    },
    {
      type: 'table',
      title: '11–19',
      headers: ['Zahl', 'Portugiesisch', 'Aussprache-Hilfe'],
      rows: [
        ['11', 'onze', 'ÕN-si'],
        ['12', 'doze', 'DO-si'],
        ['13', 'treze', 'TRE-si'],
        ['14', 'catorze / quatorze', 'ka-TOR-si'],
        ['15', 'quinze', 'KĨN-si'],
        ['16', 'dezesseis', 'de-se-ßEISS'],
        ['17', 'dezessete', 'de-se-ßÄ-tschi'],
        ['18', 'dezoito', 'de-SOI-tu'],
        ['19', 'dezenove', 'de-se-NO-wi'],
      ],
    },
    {
      type: 'table',
      title: 'Zehner & 100',
      headers: ['Zahl', 'Portugiesisch', 'Aussprache-Hilfe'],
      rows: [
        ['20', 'vinte', 'WĨN-tschi'],
        ['21', 'vinte e um', 'WĨN-tschi i ũ'],
        ['30', 'trinta', 'TRĨN-ta'],
        ['40', 'quarenta', 'kwa-RẼN-ta'],
        ['50', 'cinquenta', 'ßĩ-KWẼN-ta'],
        ['60', 'sessenta', 'ße-ßẼN-ta'],
        ['70', 'setenta', 'ße-TẼN-ta'],
        ['80', 'oitenta', 'oi-TẼN-ta'],
        ['90', 'noventa', 'no-WẼN-ta'],
        ['100', 'cem', 'ßẽi'],
      ],
    },
    {
      type: 'compare',
      target: 'vinte e cinco',
      german: 'fünfundzwanzig',
      md: 'Die Reihenfolge ist **umgekehrt** wie im Deutschen: erst der Zehner, dann `e` (und), dann der Einer – `vinte e cinco` = „zwanzig und fünf“. Genau 100 heißt `cem`; ab 101 sagt man `cento e um` usw.\n(In der Aussprache-Hilfe steht „ß“ für ein stimmloses s, „s“ für ein summendes wie in „Rose“.)',
    },
    {
      type: 'mistake',
      wrong: 'dois casas · vinte e um mulheres',
      right: 'duas casas · vinte e uma mulheres',
      why: '**1 und 2** haben eine weibliche Form: `um/uma`, `dois/duas` – auch in zusammengesetzten Zahlen (`vinte e duas`). Alle anderen Zahlen bis 100 bleiben unverändert.',
    },
    {
      type: 'variant',
      variant: 'pt-BR',
      md:
        'Brasilianische Besonderheit: Beim Diktieren von Telefon-, Haus- oder Kontonummern sagt man für die Sechs oft `meia` (von `meia dúzia` = ein halbes Dutzend). So verwechselt niemand `seis` und `três`. Beispiel: 98 6 = `nove, oito, meia`.\n' +
        'Für 14 sind in Brasilien `quatorze` und `catorze` beide korrekt.',
    },
    {
      type: 'tip',
      md: 'Merksatz: **Zehner – e – Einer**: `vinte e um`, `noventa e nove`. Und am Telefon ist die Sechs eine **meia**.',
    },
    { type: 'audio', text: 'Quanto é? – São vinte e cinco reais.', label: 'Preis anhören' },
  ],
  examples: [
    { target: 'Quanto é? – São vinte e cinco reais.', german: 'Was macht das? – 25 Reais.', literal: 'Wie viel ist? – Sind 25 Reais.' },
    {
      target: 'Dois cafés e duas águas.',
      german: 'Zwei Kaffee und zwei Wasser.',
      parts: [{ text: 'Dois', role: 'other' }, { text: ' ' }, { text: 'cafés', role: 'noun' }, { text: ' e ' }, { text: 'duas', role: 'other' }, { text: ' ' }, { text: 'águas', role: 'noun' }, { text: '.' }],
      note: '`café` ist männlich → dois; `água` ist weiblich → duas.',
    },
    { target: 'O número é nove, nove, meia, dois, três.', german: 'Die Nummer ist 9-9-6-2-3.', note: '`meia` = sechs beim Diktieren.' },
    { target: 'dezesseis, dezessete, dezoito', german: 'sechzehn, siebzehn, achtzehn' },
    { target: 'sessenta e sete', german: 'siebenundsechzig' },
    { target: 'Um real, dois reais, cem reais.', german: 'Ein Real, zwei Reais, hundert Reais.', note: 'Plural von `real`: `reais` (-l → -is).' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.numbers'],
      difficulty: 1,
      instruction: 'Ordne die Zahlen zu.',
      pairs: [
        { left: '7', right: 'sete' },
        { left: '12', right: 'doze' },
        { left: '15', right: 'quinze' },
        { left: '40', right: 'quarenta' },
        { left: '100', right: 'cem' },
      ],
      feedback: {
        rule: '7 = sete, 12 = doze, 15 = quinze, 40 = quarenta, 100 = cem.',
        why: '`doze` (12) und `dois` (2) sehen ähnlich aus – achte auf die Endung -ze bei 11–15.',
        avoid: 'Die Zahlen 11–15 enden alle auf **-ze**: onze, doze, treze, catorze, quinze.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['pt.g.numbers'],
      difficulty: 1,
      audio: 'dezesseis',
      question: 'Welche Zahl hörst du?',
      options: ['6', '16', '60'],
      answer: 1,
      feedback: {
        rule: '`dezesseis` = 16 (wörtlich „zehn und sechs“).',
        why: '6 wäre `seis`, 60 wäre `sessenta`.',
        avoid: '16–19 beginnen mit **deze-**: dezesseis, dezessete, dezoito, dezenove.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      options: ['sessenta', 'setenta'],
      answer: 1,
      hint: '`sessenta` (60) hat in der Mitte ein „ss“, `setenta` (70) ein „t“.',
      feedback: {
        rule: '60 = `sessenta` (ße-ßẼN-ta), 70 = `setenta` (ße-TẼN-ta).',
        why: 'Die beiden Zahlen unterscheiden sich nur in einem Laut – eine klassische Verwechslung bei Preisen.',
        avoid: 'Denk an `seis` (6) → sessenta und `sete` (7) → setenta.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      instruction: 'Der Preis ist R$ 38. Schreib die Zahl aus.',
      sentence: 'Quanto é? – São ___ e ___ reais.',
      answers: [['trinta'], ['oito']],
      german: 'Was macht das? – 38 Reais.',
      feedback: {
        rule: '38 = `trinta e oito`: Zehner + `e` + Einer.',
        why: 'Nicht wie im Deutschen „achtunddreißig“ – der Zehner kommt zuerst.',
        avoid: 'Lies die Ziffern von links nach rechts: 3 → trinta, 8 → oito.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      direction: 'toTarget',
      source: '52',
      answers: ['cinquenta e dois'],
      feedback: {
        rule: '52 = `cinquenta e dois` (Zehner + e + Einer).',
        why: '„dois e cinquenta“ wäre die deutsche Reihenfolge – im Portugiesischen falsch.',
        avoid: 'Schreib `cinquenta` mit **qu**: „ßĩ-KWẼN-ta“.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      tokens: ['São', 'vinte', 'e', 'cinco', 'reais.'],
      extra: ['real'],
      german: 'Das macht 25 Reais.',
      feedback: {
        rule: 'Preis: `São` + Zahl + `reais`. Ab zwei heißt es `reais` (Plural von `real`).',
        why: '`real` ist Singular und passt nur zu `um real`.',
        avoid: 'Merke: um real – dois reais.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      instruction: 'Schreib die Zahl, die du hörst – als Wort oder in Ziffern.',
      audio: 'noventa e nove',
      answers: ['noventa e nove', '99'],
      feedback: {
        rule: '99 = `noventa e nove`.',
        why: '`noventa` (90) nicht mit `nove` (9) oder `novecentos` (900) verwechseln.',
        avoid: 'Die Zehner ab 30 enden alle auf **-enta** bzw. -inta: trinta, quarenta … noventa.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.numbers', 'pt.g.articles-gender'],
      difficulty: 3,
      sentence: 'Dois amigas estão aqui.',
      answers: ['Duas amigas estão aqui.'],
      german: 'Zwei Freundinnen sind hier.',
      feedback: {
        rule: 'Vor weiblichen Nomen: `duas` (und `uma`).',
        why: '`amigas` ist weiblich Plural – `dois` passt nur zu männlichen Nomen.',
        avoid: 'Bei 1 und 2 (auch 21, 22, 31 …) immer auf das Genus des Nomens achten.',
      },
    },
  ],
  pronunciation: ['pt.p.nasal.cinco', 'pt.p.d-t.vinte'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      prompt: 'Schreib diese Preise als Wörter aus: **R$ 15**, **R$ 42** und **R$ 100**.',
      requirements: [
        { pattern: 'quinze', hint: '15 = quinze' },
        { pattern: 'quarenta\\s+e\\s+dois', hint: '42 = quarenta e dois' },
        { pattern: '\\bcem\\b', hint: '100 = cem' },
      ],
      samples: ['quinze reais, quarenta e dois reais, cem reais'],
      feedback: {
        rule: '15 = quinze, 42 = quarenta e dois, 100 = cem.',
        why: '`real` ist männlich – deshalb `dois` (nicht `duas`) reais. Für genau 100 sagt man `cem`, nicht „cento“.',
        avoid: 'Zehner + e + Einer – und `cem` nur für die glatte 100.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['listening', 'reading'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      instruction: 'Du bezahlst am Kiosk. Welche Rückfrage passt zum Preis?',
      lines: [
        { speaker: 'Você', text: 'Quanto é?', german: 'Was macht das?' },
        { speaker: 'Atendente', text: 'São dezoito reais.', german: 'Das macht 18 Reais.' },
        { speaker: 'Você', text: '…' },
        { speaker: 'Atendente', text: 'Isso! Obrigado.', german: 'Genau! Danke.' },
      ],
      gapIndex: 2,
      options: ['Dezoito reais? Aqui.', 'Oitenta reais? Aqui.', 'Oito reais? Aqui.'],
      answer: 0,
      feedback: {
        rule: '`dezoito` = 18 („zehn und acht“).',
        why: '`oitenta` = 80, `oito` = 8 – beide klingen ähnlich, bedeuten aber etwas anderes.',
        avoid: 'Achte auf den Anfang `deze-`/`dezo-` für 16–19.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      prompt: 'Spiel beide Rollen: Frag nach dem Preis und nenne dann einen Betrag, z. B. „Quanto é? – São vinte reais.“',
      keywords: ['quanto', 'são', 'reais'],
      minMatch: 2,
      sample: 'Quanto é? – São trinta e cinco reais.',
      feedback: {
        rule: 'Frage: `Quanto é?` – Antwort: `São … reais.`',
        why: 'Ab zwei Reais heißt es `reais` – und der Preis wird mit `são` (sie sind) genannt.',
        avoid: 'Sprich das Wort `reais` deutlich: „he-AIS“ (R am Anfang wie h).',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      scenarioId: 'pt.sc.restaurant',
      goal: 'Bestelle etwas zu trinken, frag mit `Quanto é?` nach dem Preis und wiederhole den Betrag, den du hörst.',
      turns: 4,
      feedback: {
        rule: 'Preise verstehen: Zehner + `e` + Einer, Währung `reais`.',
        avoid: 'Wiederhole den Preis laut – so merkst du sofort, ob du ihn richtig verstanden hast.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.contractions'],
      difficulty: 2,
      sentence: 'Estou ___ cidade.',
      answers: [['na']],
      german: 'Ich bin in der Stadt.',
      feedback: {
        rule: '`em` + `a cidade` = `na cidade`.',
        why: '`em a` muss verschmelzen; `no` wäre die männliche Form.',
        avoid: 'Genus des Nomens prüfen: a cidade → na.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.ser'],
      difficulty: 2,
      verb: 'ser',
      tense: 'Präsens',
      person: 'eles',
      sentence: 'Eles ___ do Brasil.',
      answers: ['são'],
      feedback: {
        rule: '`ser`: sou, é, somos, **são**. Herkunft → ser.',
        why: '`estão` gehört zu estar und passt nicht zur Herkunft.',
        avoid: 'Beachte die Tilde: `são` ist nasal wie `não`.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'mc',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.formality'],
      difficulty: 1,
      prompt: 'Du bedankst dich – du bist ein Mann.',
      options: [{ text: 'Obrigado!' }, { text: 'Obrigada!', why: 'Diese Form verwenden Frauen.' }, { text: 'De nada!', why: 'Das heißt „gern geschehen“.' }],
      answer: 0,
      feedback: {
        rule: 'Männer sagen `obrigado`, Frauen `obrigada`.',
        why: 'Die Form richtet sich nach der Person, die sich bedankt.',
        avoid: 'Sprecher = Mann → -o.',
      },
    },
  ],
};

export default lesson;
