import type { Lesson } from '../../types';

const L = 'pt.s0.l04';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'stage0',
  chapterId: 'pt.s0.c2',
  order: 4,
  title: 'Ser e estar – zweimal „sein“',
  subtitle: 'Wer du bist und wie es dir geht',
  icon: '⚖️',
  minutes: 12,
  goal:
    'Du lernst die beiden Verben für „sein“: **ser** für das, was jemand **ist** (Name, Herkunft, Beruf, Charakter), und **estar** für das, wie oder wo jemand **gerade** ist (Befinden, Zustand, Ort) – mit allen Präsensformen.',
  canDo: [
    'Ich kann alle Präsensformen von ser und estar bilden.',
    'Ich kann sagen, wer ich bin, woher ich komme und was ich beruflich mache.',
    'Ich kann sagen, wie es mir geht und wo ich gerade bin.',
    'Ich entscheide sicher zwischen ser und estar in einfachen Sätzen.',
  ],
  topicIds: ['pt.g.ser', 'pt.g.estar', 'pt.g.ser-estar'],
  vocab: [
    { id: `${L}.v.ser`, target: 'ser', german: 'sein (Identität, Herkunft, Beruf, Eigenschaft)', pos: 'verb', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Eu sou de Berlim.', german: 'Ich komme aus Berlin.' } },
    { id: `${L}.v.estar`, target: 'estar', german: 'sein (Befinden, Zustand, Ort)', pos: 'verb', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Eu estou bem.', german: 'Mir geht es gut.' } },
    { id: `${L}.v.de`, target: 'de', german: 'aus, von', pos: 'prep', field: 'Herkunft', stageId: 'stage0', lessonId: L, example: { target: 'Sou de Munique.', german: 'Ich komme aus München.' } },
    { id: `${L}.v.alemao`, target: 'alemão / alemã', german: 'Deutscher / Deutsche; deutsch', pos: 'adj', gender: 'm/f', field: 'Nationalitäten', stageId: 'stage0', lessonId: L, example: { target: 'Ela é alemã.', german: 'Sie ist Deutsche.' } },
    { id: `${L}.v.brasileiro`, target: 'brasileiro / brasileira', german: 'Brasilianer / Brasilianerin; brasilianisch', pos: 'adj', gender: 'm/f', field: 'Nationalitäten', stageId: 'stage0', lessonId: L, example: { target: 'Você é brasileiro?', german: 'Bist du Brasilianer?' } },
    { id: `${L}.v.estudante`, target: 'o / a estudante', german: 'der Student / die Studentin', pos: 'noun', gender: 'm/f', emoji: '🎓', field: 'Berufe', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.professor`, target: 'o professor / a professora', german: 'der Lehrer / die Lehrerin', pos: 'noun', gender: 'm/f', emoji: '🧑‍🏫', field: 'Berufe', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.medico`, target: 'o médico / a médica', german: 'der Arzt / die Ärztin', pos: 'noun', gender: 'm/f', emoji: '🩺', field: 'Berufe', stageId: 'stage0', lessonId: L, example: { target: 'Ela é médica.', german: 'Sie ist Ärztin.' } },
    { id: `${L}.v.cansado`, target: 'cansado / cansada', german: 'müde', pos: 'adj', emoji: '😴', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Estou cansada.', german: 'Ich bin müde.' } },
    { id: `${L}.v.feliz`, target: 'feliz', german: 'glücklich, froh', pos: 'adj', emoji: '😊', field: 'Befinden', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.simpatico`, target: 'simpático / simpática', german: 'nett, sympathisch', pos: 'adj', field: 'Eigenschaften', stageId: 'stage0', lessonId: L, example: { target: 'Ele é simpático.', german: 'Er ist nett.' } },
    { id: `${L}.v.bem`, target: 'bem', german: 'gut (Befinden)', pos: 'adv', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Estou bem, obrigado.', german: 'Mir geht’s gut, danke.' } },
    { id: `${L}.v.aqui`, target: 'aqui', german: 'hier', pos: 'adv', field: 'Ort', stageId: 'stage0', lessonId: L, example: { target: 'Estou aqui!', german: 'Ich bin hier!' } },
    { id: `${L}.v.em-casa`, target: 'em casa', german: 'zu Hause', pos: 'phrase', emoji: '🏠', field: 'Ort', stageId: 'stage0', lessonId: L, example: { target: 'Vocês estão em casa?', german: 'Seid ihr zu Hause?' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Das Deutsche hat ein „sein“ – das Portugiesische hat zwei:\n' +
        '- `ser` beschreibt, **wer oder was** jemand ist: Name (`Sou Ana.`), Herkunft (`Sou de Berlim.`), Nationalität (`Sou alemã.`), Beruf (`Sou professora.`), Charakter (`Ele é simpático.`).\n' +
        '- `estar` beschreibt, **wie oder wo** jemand gerade ist: Befinden (`Estou bem.`), Zustand (`Estou cansado.`), Ort (`Estou em casa.`).\n' +
        'Bei Ländern braucht das Portugiesische einen Artikel (`Sou da Alemanha`) – das lernst du in Lektion 5. Mit Städten geht es schon jetzt: `Sou de Hamburgo.`',
    },
    {
      type: 'conjugation',
      verb: 'ser',
      translation: 'sein (Identität, Herkunft, Beruf, Eigenschaft)',
      tense: 'Präsens',
      rows: [
        { person: 'eu', form: 'sou' },
        { person: 'você / ele / ela / a gente', form: 'é' },
        { person: 'nós', form: 'somos' },
        { person: 'vocês / eles / elas', form: 'são' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'estar',
      translation: 'sein (Befinden, Zustand, Ort)',
      tense: 'Präsens',
      rows: [
        { person: 'eu', form: 'estou', ending: 'ou' },
        { person: 'você / ele / ela / a gente', form: 'está', ending: 'á' },
        { person: 'nós', form: 'estamos', ending: 'amos' },
        { person: 'vocês / eles / elas', form: 'estão', ending: 'ão' },
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Eu', role: 'subject' },
        { text: ' ' },
        { text: 'sou', role: 'verb' },
        { text: ' ' },
        { text: 'professora', role: 'noun' },
        { text: ' e ' },
        { text: 'estou', role: 'verb' },
        { text: ' ' },
        { text: 'cansada', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Ich bin Lehrerin und (gerade) müde.',
    },
    {
      type: 'compare',
      target: 'Sou médico. – Estou cansado.',
      german: 'Ich bin Arzt. – Ich bin müde.',
      md: 'Im Deutschen zweimal „bin“, im Portugiesischen zwei Verben: Der Beruf gehört zum **Steckbrief** (`ser`), die Müdigkeit ist eine **Statusmeldung** (`estar`). Wie im Deutschen steht vor dem Beruf **kein** Artikel.',
    },
    {
      type: 'mistake',
      wrong: 'Eu sou cansado.',
      right: 'Eu estou cansado.',
      why: 'Müdigkeit ist ein Zustand, der sich ändert – dafür steht `estar`. `Eu sou cansado` klingt, als wärst du von Natur aus ein müder Mensch.',
    },
    {
      type: 'variant',
      variant: 'pt-BR',
      md:
        'Im gesprochenen Brasilianisch wird `estar` fast immer verkürzt: `tô` (estou), `tá` (está), `tamo` (estamos), `tão` (estão). `Tô cansado.` · `Tá tudo bem?` Du solltest diese Formen verstehen; in Chats sind sie normal, in formellen Texten schreibst du die Langform.\n' +
        'Außerdem typisch: Auf Ja/Nein-Fragen antwortet man gern mit dem Verb statt mit `sim`: `Você é brasileira? – Sou, sim!`',
    },
    {
      type: 'tip',
      md: 'Merksatz: **ser = Steckbrief** (Name, Herkunft, Beruf, Charakter) – **estar = Statusmeldung** (Befinden, Zustand, Ort, gerade jetzt).',
    },
  ],
  examples: [
    {
      target: 'Eu sou Ana. Sou de Berlim.',
      german: 'Ich bin Ana. Ich komme aus Berlin.',
      literal: 'Ich bin Ana. Ich bin aus Berlin.',
      parts: [{ text: 'Eu', role: 'subject' }, { text: ' ' }, { text: 'sou', role: 'verb' }, { text: ' Ana. ' }, { text: 'Sou', role: 'verb' }, { text: ' ' }, { text: 'de', role: 'preposition' }, { text: ' Berlim.' }],
    },
    { target: 'Você é brasileira? – Sou, sim!', german: 'Bist du Brasilianerin? – Ja, bin ich!', note: 'Typisch brasilianisch: mit dem Verb antworten.' },
    { target: 'Ela é médica.', german: 'Sie ist Ärztin.', note: 'Beruf → `ser`, ohne Artikel.' },
    { target: 'Nós somos estudantes.', german: 'Wir sind Studenten.' },
    {
      target: 'Estou cansada.',
      german: 'Ich bin müde.',
      parts: [{ text: 'Estou', role: 'verb' }, { text: ' ' }, { text: 'cansada', role: 'adjective' }, { text: '.' }],
      note: 'Eine Frau spricht: **cansada**.',
    },
    { target: 'Vocês estão em casa?', german: 'Seid ihr zu Hause?' },
    { target: 'Ele é simpático, mas está cansado.', german: 'Er ist nett, aber (gerade) müde.', note: '`mas` = aber. Charakter → ser, Zustand → estar.' },
    { target: 'Tô bem, e você?', german: 'Mir geht’s gut, und dir?', note: 'Umgangssprachlich: `tô` = `estou`.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 1,
      instruction: 'Ordne die Sätze ihrer Bedeutung zu.',
      pairs: [
        { left: 'Sou de Berlim.', right: 'Ich komme aus Berlin.' },
        { left: 'Estou em casa.', right: 'Ich bin zu Hause.' },
        { left: 'Sou alemão.', right: 'Ich bin Deutscher.' },
        { left: 'Estou bem.', right: 'Mir geht es gut.' },
        { left: 'Sou estudante.', right: 'Ich bin Student.' },
      ],
      feedback: {
        rule: 'Herkunft, Nationalität und Beruf → `ser` (sou). Ort und Befinden → `estar` (estou).',
        why: '„Mir geht es gut“ und „zu Hause sein“ beschreiben den aktuellen Zustand bzw. Ort.',
        avoid: 'Frag dich: Steckbrief (ser) oder Statusmeldung (estar)?',
      },
    },
    {
      id: `${L}.g02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.ser'],
      difficulty: 1,
      verb: 'ser',
      tense: 'Präsens',
      person: 'nós',
      sentence: 'Nós ___ estudantes.',
      answers: ['somos'],
      feedback: {
        rule: '`ser` im Präsens: sou, é, somos, são. Zu `nós` gehört `somos`.',
        why: '`são` ist die Form für vocês/eles/elas, `é` für você/ele/ela/a gente.',
        avoid: 'Die nós-Form endet fast immer auf **-mos** – auch bei `somos`.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 1,
      prompt: 'Wie sagst du „Ich bin müde“?',
      options: [
        { text: 'Eu sou cansado.', why: '`ser` beschreibt dauerhafte Eigenschaften – Müdigkeit ist ein Zustand.' },
        { text: 'Eu estou cansado.' },
        { text: 'Eu é cansado.', why: '`é` ist die Form für você/ele/ela, nicht für eu.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Zustände und Befinden → `estar`: `Eu estou cansado/cansada.`',
        why: 'Müdigkeit ist vorübergehend – eine Statusmeldung.',
        avoid: 'Gefühle und körperliche Zustände fast immer mit `estar`.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.estar'],
      difficulty: 2,
      verb: 'estar',
      tense: 'Präsens',
      person: 'eles',
      sentence: 'Eles ___ em casa.',
      answers: ['estão'],
      feedback: {
        rule: '`estar` im Präsens: estou, está, estamos, estão. Zu `eles` gehört `estão`.',
        why: '`está` ist Singular (você/ele/ela), `são` gehört zu `ser`.',
        avoid: 'Plural-Formen für vocês/eles/elas enden bei estar auf **-ão**: estão (nasal!).',
      },
    },
    {
      id: `${L}.g05`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 2,
      sentence: 'Ela ___ médica e hoje ___ cansada.',
      answers: [['é'], ['está', 'tá']],
      bank: ['é', 'está', 'são', 'estou'],
      german: 'Sie ist Ärztin und heute müde.',
      feedback: {
        rule: 'Beruf → `ser` (ela **é**), Zustand → `estar` (ela **está**).',
        why: '`são` und `estou` passen nicht zur Person `ela`.',
        avoid: 'Zwei Fragen stellen: Welches Verb (ser/estar)? Welche Person (ela → 3. Singular)?',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.estar'],
      difficulty: 2,
      tokens: ['Vocês', 'estão', 'em', 'casa?'],
      extra: ['são'],
      german: 'Seid ihr zu Hause?',
      feedback: {
        rule: 'Ort → `estar`: `Vocês estão em casa?`',
        why: '`são` ist eine Form von `ser` und passt nicht zu einer Ortsangabe wie „zu Hause“.',
        avoid: 'Wo sich jemand gerade befindet → immer `estar`.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['pt.g.estar'],
      difficulty: 2,
      audio: 'Nós estamos em casa.',
      question: 'Was sagt die Person?',
      options: ['Wir sind zu Hause.', 'Wir sind Studenten.', 'Sie sind zu Hause.'],
      answer: 0,
      feedback: {
        rule: '`estamos` = wir sind (gerade), `em casa` = zu Hause.',
        why: '„Sie sind“ wäre `estão`, „Studenten“ wäre `estudantes`.',
        avoid: 'Die Endung **-mos** verrät dir immer: „wir“.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 3,
      sentence: 'Eu estou de Berlim.',
      answers: ['Eu sou de Berlim.', 'Sou de Berlim.'],
      german: 'Ich komme aus Berlin.',
      feedback: {
        rule: 'Herkunft → `ser de`: `Eu sou de Berlim.`',
        why: 'Deine Herkunft ändert sich nicht – sie gehört in den Steckbrief, nicht in die Statusmeldung.',
        avoid: '`ser de` = „kommen aus“. Merke: `Sou de …` am Anfang jeder Vorstellung.',
      },
    },
  ],
  pronunciation: ['pt.p.open-closed.e-aberto', 'pt.p.ao.estao', 'pt.p.stress.voce'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 2,
      prompt: 'Stell dich schriftlich vor: Name, Stadt, Beruf oder Studium – und wie es dir gerade geht.',
      requirements: [
        { pattern: '\\bsou\\b', hint: 'Nutze „sou“ für Name, Herkunft oder Beruf.' },
        { pattern: '\\bde\\s+\\S+', hint: 'Nenne deine Stadt mit „de …“ (z. B. „Sou de Hamburgo“).' },
        { pattern: '\\b(estou|to)\\b', hint: 'Sag mit „estou …“, wie es dir geht.' },
      ],
      samples: ['Oi! Eu sou Lena. Sou de Hamburgo e sou estudante. Estou bem, mas estou cansada.'],
      minWords: 8,
      feedback: {
        rule: 'Steckbrief mit `sou` (Name, `de` + Stadt, Beruf), Befinden mit `estou`.',
        why: 'Herkunft mit `estou` oder Befinden mit `sou` wären die typischen Verwechslungen.',
        avoid: 'Schreib zuerst alle `sou`-Sätze, dann einen `estou`-Satz.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.ser'],
      difficulty: 2,
      instruction: 'Du bist Tom aus Köln (Colônia). Wähle deine Antwort.',
      lines: [
        { speaker: 'Júlia', text: 'Oi! Você é brasileiro?', german: 'Hi! Bist du Brasilianer?' },
        { speaker: 'Tom', text: '…' },
        { speaker: 'Júlia', text: 'Ah, legal! Eu sou de Salvador.', german: 'Ah, cool! Ich komme aus Salvador.' },
      ],
      gapIndex: 1,
      options: ['Não, sou alemão. Sou de Colônia.', 'Não, estou alemão. Estou de Colônia.', 'Não, é alemão. É de Colônia.'],
      answer: 0,
      feedback: {
        rule: 'Nationalität und Herkunft → `ser`: `Sou alemão. Sou de Colônia.`',
        why: '`estou` beschreibt Zustände, nicht Herkunft. `é` ist die Form für você/ele/ela.',
        avoid: 'Über dich selbst: `sou` (ser) oder `estou` (estar) – nie `é`.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 2,
      prompt: 'Sag laut, woher du kommst, was du bist (Beruf/Studium) und wie es dir heute geht.',
      keywords: ['sou', 'estou', 'tô'],
      minMatch: 2,
      sample: 'Eu sou Jonas. Sou de Colônia, sou estudante e estou bem.',
      feedback: {
        rule: 'Mindestens ein Satz mit `sou` (ser) und einer mit `estou` (estar).',
        why: 'Die Aufgabe prüft, ob du beide Verben passend einsetzt.',
        avoid: 'Denk an die Reihenfolge: erst Steckbrief (sou …), dann Status (estou …).',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 1,
      pairs: [
        { left: 'a gente', right: 'wir (Alltag)' },
        { left: 'vocês', right: 'ihr' },
        { left: 'elas', right: 'sie (nur Frauen)' },
        { left: 'comigo', right: 'mit mir' },
      ],
      feedback: {
        rule: 'a gente = wir, vocês = ihr, elas = sie (nur Frauen), comigo = mit mir.',
        why: '`elas` gilt nur, wenn keine Männer dabei sind.',
        avoid: 'Wiederhole die Pronomen-Tabelle aus Lektion 3, wenn du unsicher bist.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.ser'],
      difficulty: 2,
      direction: 'toTarget',
      source: 'Bist du Brasilianerin?',
      answers: ['Você é brasileira?', 'É brasileira?'],
      feedback: {
        rule: 'Nationalität → `ser`: `Você é brasileira?` (zu einer Frau: -a).',
        why: '`está` passt nicht zur Nationalität; `brasileiro` wäre die männliche Form.',
        avoid: 'Ja/Nein-Fragen bilden sich nur über die Satzmelodie – die Wortstellung bleibt gleich.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['pt.g.formality'],
      difficulty: 2,
      audio: 'Tudo bem com a senhora?',
      question: 'Mit wem spricht die Person?',
      options: ['mit einem jungen Freund', 'höflich mit einer (älteren) Frau', 'mit mehreren Leuten'],
      answer: 1,
      feedback: {
        rule: '`a senhora` = höfliches „Sie“ gegenüber einer Frau.',
        why: 'Zu einem Freund würde man `você` sagen, zu mehreren `vocês`.',
        avoid: 'Hör auf den Artikel: `a senhora` (Frau), `o senhor` (Mann).',
      },
    },
  ],
};

export default lesson;
