import type { Lesson } from '../../types';

const L = 'pt.s0.l03';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'stage0',
  chapterId: 'pt.s0.c1',
  order: 3,
  title: 'Pronomes – ich, du, wir',
  subtitle: 'eu, você, ele, ela, a gente …',
  icon: '👥',
  minutes: 10,
  goal:
    'Du kennst alle **Personalpronomen** des brasilianischen Portugiesisch, weißt, warum `a gente` im Alltag „wir“ bedeutet, wann du `eles` und wann `elas` sagst – und wie Pronomen nach `com` (mit) aussehen: `com você`, aber `comigo`.',
  canDo: [
    'Ich kenne die Personalpronomen und ihre Bedeutung.',
    'Ich kann über eine Gruppe mit eles oder elas sprechen.',
    'Ich verstehe und benutze a gente für „wir“.',
    'Ich kann fragen und sagen, wie es jemandem geht: Tudo bem com vocês? – Comigo tudo bem.',
  ],
  topicIds: ['pt.g.pronouns'],
  vocab: [
    { id: `${L}.v.eu`, target: 'eu', german: 'ich', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L, example: { target: 'Eu também.', german: 'Ich auch.' } },
    { id: `${L}.v.voce`, target: 'você', german: 'du (auch: Sie im lockeren Kontakt)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L, example: { target: 'E você?', german: 'Und du?' } },
    { id: `${L}.v.ele`, target: 'ele', german: 'er', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ela`, target: 'ela', german: 'sie (eine Frau)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.a-gente`, target: 'a gente', german: 'wir (Alltagssprache)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L, example: { target: 'A gente também!', german: 'Wir auch!' } },
    { id: `${L}.v.nos`, target: 'nós', german: 'wir (neutral, schriftlich)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.voces`, target: 'vocês', german: 'ihr; Sie (mehrere Personen)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L, example: { target: 'Tudo bem com vocês?', german: 'Geht’s euch gut?' } },
    { id: `${L}.v.eles`, target: 'eles', german: 'sie (Männer oder gemischte Gruppe)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.elas`, target: 'elas', german: 'sie (nur Frauen)', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.com`, target: 'com', german: 'mit', pos: 'prep', field: 'Kleine Wörter', stageId: 'stage0', lessonId: L, example: { target: 'Tudo bem com ela?', german: 'Geht es ihr gut?' } },
    { id: `${L}.v.comigo`, target: 'comigo', german: 'mit mir', pos: 'pron', field: 'Pronomen', stageId: 'stage0', lessonId: L, example: { target: 'Comigo tudo bem.', german: 'Mir geht’s gut.' } },
    { id: `${L}.v.e`, target: 'e', german: 'und', pos: 'other', field: 'Kleine Wörter', stageId: 'stage0', lessonId: L, example: { target: 'eu e você', german: 'ich und du' } },
    { id: `${L}.v.tambem`, target: 'também', german: 'auch', pos: 'adv', field: 'Kleine Wörter', stageId: 'stage0', lessonId: L, example: { target: 'Eu também!', german: 'Ich auch!' } },
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Personalpronomen',
      headers: ['Person', 'Portugiesisch', 'Deutsch', 'Hinweis'],
      rows: [
        ['1. Singular', 'eu', 'ich', 'klingt wie „e-u“ (zwei Laute)'],
        ['2. Singular', 'você', 'du', 'Standardanrede in Brasilien'],
        ['3. Singular', 'ele / ela', 'er / sie', 'ele ≈ „E-li“, ela ≈ „Ä-la“'],
        ['1. Plural', 'a gente / nós', 'wir', 'a gente im Alltag, nós neutral/schriftlich'],
        ['2. Plural', 'vocês', 'ihr / Sie (mehrere)', 'für jede Gruppe, locker oder höflich'],
        ['3. Plural', 'eles / elas', 'sie', 'elas nur für reine Frauengruppen'],
        ['höflich', 'o senhor / a senhora', 'Sie (eine Person)', 'Plural: os senhores / as senhoras'],
      ],
    },
    {
      type: 'text',
      md:
        '`você` ist in Brasilien das normale „du“. Historisch kommt es von `Vossa Mercê` („Euer Gnaden“) – deshalb verhält es sich grammatisch wie **er/sie**: In Lektion 4 wirst du sehen, dass `você` und `ele` dieselbe Verbform haben (`você é`, `ele é`). Dasselbe gilt für `o senhor` / `a senhora`.\n' +
        '**Gruppen:** `eles` für Männer **und** für gemischte Gruppen – sobald ein Mann dabei ist. `elas` nur, wenn ausschließlich Frauen gemeint sind.',
    },
    {
      type: 'compare',
      target: 'a gente',
      german: 'wir (wörtlich: „die Leute“)',
      md:
        'Im gesprochenen Brasilianisch hörst du `a gente` viel häufiger als `nós`. Wichtig: `a gente` ist grammatisch **Singular** und bekommt später die Verbform von `ele` (`a gente é`, aber `nós somos`). Vergleichbar mit dem deutschen „man“ – nur dass es klar „wir“ bedeutet.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Tudo bem', role: 'other' },
        { text: ' ' },
        { text: 'com', role: 'preposition' },
        { text: ' ' },
        { text: 'vocês', role: 'pronoun' },
        { text: '?' },
      ],
      german: 'Geht’s euch gut? (wörtl. Alles gut mit euch?)',
    },
    {
      type: 'text',
      md:
        '**Pronomen nach `com` (mit):** Meist bleibt das Pronomen unverändert: `com você`, `com ele`, `com ela`, `com a gente`, `com vocês`, `com eles`. Eine wichtige Ausnahme: **mit mir** heißt `comigo` (nie „com eu“). Das förmliche „mit uns“ lautet `conosco` – im Alltag sagt man meist `com a gente`.\n' +
        'Typischer Wortwechsel: `Tudo bem com você?` – `Comigo tudo bem, e com você?`',
    },
    {
      type: 'mistake',
      wrong: 'Pedro e Ana? Elas …',
      right: 'Pedro e Ana? Eles …',
      why: 'Sobald ein Mann zur Gruppe gehört, verwendest du `eles` – egal, wie viele Frauen dabei sind. `elas` nur für reine Frauengruppen.',
    },
    {
      type: 'tip',
      md: 'Merksätze: **Ein Mann dabei → eles.** – **Im Gespräch „a gente“, im Formular „nós“.** – **Mit mir = comigo.**',
    },
    { type: 'audio', text: 'Tudo bem com vocês? – Com a gente tudo bem! E com você?', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: 'E você? – Eu também.',
      german: 'Und du? – Ich auch.',
      parts: [{ text: 'E', role: 'other' }, { text: ' ' }, { text: 'você', role: 'pronoun' }, { text: '? – ' }, { text: 'Eu', role: 'pronoun' }, { text: ' ' }, { text: 'também', role: 'adverb' }, { text: '.' }],
    },
    {
      target: 'Tudo bem com vocês?',
      german: 'Geht’s euch gut?',
      literal: 'Alles gut mit euch?',
      parts: [{ text: 'Tudo bem', role: 'other' }, { text: ' ' }, { text: 'com', role: 'preposition' }, { text: ' ' }, { text: 'vocês', role: 'pronoun' }, { text: '?' }],
    },
    { target: 'A gente também!', german: 'Wir auch!', note: 'Alltagssprache – `nós também` ist ebenfalls korrekt, klingt aber etwas förmlicher.' },
    { target: 'Comigo tudo bem, e com você?', german: 'Mir geht’s gut, und dir?', literal: 'Mit mir alles gut, und mit dir?' },
    { target: 'Ela não, ele sim.', german: 'Sie nicht, er schon.' },
    { target: 'Boa tarde! Tudo bem com os senhores?', german: 'Guten Tag! Geht es Ihnen gut?', note: 'Höflich an mehrere Personen (oder eine gemischte Gruppe).' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 1,
      instruction: 'Ordne die Pronomen zu.',
      pairs: [
        { left: 'eu', right: 'ich' },
        { left: 'você', right: 'du' },
        { left: 'ele', right: 'er' },
        { left: 'a gente', right: 'wir' },
        { left: 'vocês', right: 'ihr' },
        { left: 'comigo', right: 'mit mir' },
      ],
      feedback: {
        rule: 'eu = ich, você = du, ele = er, a gente = wir (Alltag), vocês = ihr, comigo = mit mir.',
        why: '`a gente` sieht aus wie „die Leute“, bedeutet aber „wir“.',
        avoid: 'Lerne `a gente` und `nós` als Paar: beide = wir.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 1,
      prompt: 'Du sprichst über **Ana und Maria**. Welches Pronomen passt?',
      options: [
        { text: 'eles', why: '`eles` steht für Männer oder gemischte Gruppen.' },
        { text: 'elas' },
        { text: 'vocês', why: '`vocês` sprichst du an („ihr“) – hier sprichst du **über** die beiden.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Reine Frauengruppe → `elas`.',
        why: 'Ana und Maria sind zwei Frauen, über die du sprichst (3. Person Plural).',
        avoid: 'Frage 1: Spreche ich mit ihnen (vocês) oder über sie (eles/elas)? Frage 2: Ist ein Mann dabei?',
      },
    },
    {
      id: `${L}.g03`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 2,
      prompt: 'Du sprichst über **Pedro, Ana und Maria**. Welches Pronomen passt?',
      options: [
        { text: 'elas', why: 'Pedro ist ein Mann – dann ist `elas` nicht möglich.' },
        { text: 'eles' },
        { text: 'a gente', why: '`a gente` bedeutet „wir“ – du gehörst aber nicht zur Gruppe.' },
      ],
      answer: 1,
      feedback: {
        rule: 'Gemischte Gruppe → `eles`, auch wenn nur ein Mann dabei ist.',
        why: 'Das männliche Plural-Pronomen gilt im Portugiesischen für alle gemischten Gruppen.',
        avoid: 'Merksatz: Ein Mann dabei → eles.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 2,
      sentence: 'Comigo tudo bem, e com ___?',
      answers: [['você']],
      bank: ['você', 'eu', 'comigo'],
      german: 'Mir geht’s gut, und dir?',
      feedback: {
        rule: 'Nach `com` steht bei „du“ einfach `você`: `com você`.',
        why: '`com eu` gibt es nicht (dafür `comigo`), und `comigo` bedeutet „mit mir“ – du fragst aber nach dem anderen.',
        avoid: 'Nur „mit mir“ ist besonders: `comigo`. Alle anderen: `com` + Pronomen.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'listening',
      skills: ['listening', 'grammar'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 2,
      audio: 'A gente também.',
      question: 'Wer ist gemeint?',
      options: ['ich', 'wir', 'ihr'],
      answer: 1,
      feedback: {
        rule: '`a gente` = wir (Alltagssprache).',
        why: '„ich“ wäre `eu`, „ihr“ wäre `vocês`.',
        avoid: 'Wenn du `a gente` hörst, denk sofort an „wir“.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 2,
      instruction: 'Frag zwei Freunde, wie es ihnen geht.',
      tokens: ['Tudo', 'bem', 'com', 'vocês?'],
      extra: ['comigo', 'você'],
      german: 'Geht’s euch gut?',
      feedback: {
        rule: 'Mehrere Personen ansprechen → `vocês`. Die Frage: `Tudo bem com vocês?`',
        why: '`você` spricht nur eine Person an, `comigo` heißt „mit mir“.',
        avoid: 'Zähle, mit wie vielen Menschen du sprichst: eine → você, mehrere → vocês.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 2,
      direction: 'toTarget',
      source: 'Wir auch!',
      answers: ['A gente também!', 'Nós também!'],
      feedback: {
        rule: '„wir“ = `a gente` (Alltag) oder `nós`; „auch“ = `também`.',
        why: 'Beide Varianten sind richtig – `a gente` ist im Gespräch üblicher.',
        avoid: 'Achte auf den Akzent: `também` wird auf der letzten Silbe betont.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 3,
      sentence: 'Com eu, tudo bem.',
      answers: ['Comigo, tudo bem.', 'Comigo tudo bem.'],
      german: 'Mir geht’s gut.',
      feedback: {
        rule: '„mit mir“ heißt immer `comigo` – nie `com eu`.',
        why: '`com` + `eu` verschmilzt zu einer Sonderform, ähnlich wie im Deutschen „mit ich“ falsch ist.',
        avoid: 'Merke: `comigo` = mit mir. (Förmlich „mit uns“: `conosco`, im Alltag `com a gente`.)',
      },
    },
  ],
  pronunciation: ['pt.p.open-closed.ele', 'pt.p.open-closed.nos', 'pt.p.rhythm.a-gente'],
  application: [
    {
      id: `${L}.a01`,
      type: 'situation',
      skills: ['reading', 'speaking'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 2,
      scenario: 'Du bist mit zwei Freundinnen unterwegs. Jemand sagt: „Comigo tudo bem! E vocês?“ Du antwortest für euch drei: „Uns auch!“',
      options: [
        { text: 'A gente também!' },
        { text: 'Eles também!', why: '`eles` bedeutet „sie“ – du sprichst aber über euch selbst.' },
        { text: 'Vocês também!', why: '`vocês` bedeutet „ihr“ – das wäre eine Aussage über die andere Person.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Für dich und deine Gruppe sagst du `a gente` (oder `nós`).',
        why: 'Die Frage `E vocês?` richtet sich an euch – die Antwort muss „wir“ enthalten.',
        avoid: 'Auf `vocês?` (ihr?) antwortest du mit `a gente` / `nós` (wir).',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'grammar'],
      topicIds: ['pt.g.pronouns', 'pt.g.formality'],
      difficulty: 2,
      prompt: 'Du triffst zwei Bekannte auf der Straße. Begrüße sie und frag, wie es ihnen (beiden) geht.',
      keywords: ['vocês', 'tudo bem', 'tudo bom'],
      minMatch: 2,
      sample: 'Oi! Tudo bem com vocês?',
      feedback: {
        rule: 'Zwei Personen → `vocês`: `Tudo bem com vocês?`',
        why: '`com você` würde nur eine Person ansprechen.',
        avoid: 'Bei Gruppen immer `vocês` – egal ob locker oder höflich.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.pronouns'],
      difficulty: 2,
      scenarioId: 'pt.sc.gefuehrt',
      goal: 'Begrüße deinen Gesprächspartner, frag `Tudo bem com você?` und antworte auf seine Gegenfrage mit `Comigo tudo bem` oder `Eu também`.',
      turns: 4,
      feedback: {
        rule: 'Nutze die Pronomen aus dieser Lektion: `você`, `comigo`, `eu também`, `a gente`.',
        avoid: 'Wenn du hängen bleibst: `Comigo tudo bem, e com você?` passt fast immer.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'situation',
      skills: ['reading', 'vocabulary'],
      topicIds: ['pt.g.formality'],
      difficulty: 1,
      scenario: 'Du verabschiedest dich abends von Kollegen, die du morgen wiedersiehst.',
      options: [
        { text: 'Boa noite! Até amanhã!' },
        { text: 'Bom dia! Até logo!', why: '`Bom dia` sagt man morgens.' },
        { text: 'Oi, tudo bem?', why: 'Das ist eine Begrüßung, kein Abschied.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Abends: `Boa noite!` – und für morgen: `Até amanhã!`',
        why: '`Bom dia` passt nicht zur Tageszeit, `Oi, tudo bem?` ist eine Begrüßung.',
        avoid: 'Abschied = Tageszeit + `até …`.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'minimalPair',
      skills: ['listening', 'pronunciation'],
      topicIds: ['pt.g.sounds'],
      difficulty: 2,
      options: ['avó', 'avô'],
      answer: 1,
      hint: '`avô` (Opa) hat ein geschlossenes o wie in „Sohn“, `avó` (Oma) ein offenes wie in „Sonne“.',
      feedback: {
        rule: 'ô = geschlossen (wie „Sohn“), ó = offen (wie „Sonne“).',
        why: 'Die Wörter unterscheiden sich nur in der Öffnung des betonten o.',
        avoid: 'Beim geschlossenen ô die Lippen runder und enger machen.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.formality'],
      difficulty: 1,
      direction: 'toGerman',
      source: 'Tudo bem com o senhor?',
      answers: ['Geht es Ihnen gut?', 'Geht’s Ihnen gut?', 'Wie geht es Ihnen?', 'Wie geht’s Ihnen?', 'Alles gut bei Ihnen?', 'Ist bei Ihnen alles gut?', 'Ist alles gut bei Ihnen?', 'Alles in Ordnung bei Ihnen?'],
      feedback: {
        rule: '`o senhor` ist die höfliche Anrede an einen Mann = „Sie“.',
        why: 'Wörtlich „Alles gut mit dem Herrn?“ – gemeint ist die höfliche Frage nach dem Befinden.',
        avoid: 'Übersetze `o senhor` / `a senhora` in der Anrede immer mit „Sie“.',
      },
    },
  ],
};

export default lesson;
