import type { Lesson } from '../../types';

const L = 'pt.s0.l01';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'stage0',
  chapterId: 'pt.s0.c1',
  order: 1,
  title: 'Saudações – Hallo, Brasilien!',
  subtitle: 'Grüßen, nachfragen, verabschieden',
  icon: '👋',
  minutes: 10,
  goal:
    'Du kannst Menschen in Brasilien zu jeder Tageszeit **begrüßen**, fragen, **wie es geht**, darauf antworten und dich **verabschieden** – locker mit `você` oder respektvoll mit `o senhor` / `a senhora`.',
  canDo: [
    'Ich kann zu jeder Tageszeit passend grüßen.',
    'Ich kann fragen, wie es jemandem geht, und selbst antworten.',
    'Ich kann mich bedanken und verabschieden.',
    'Ich weiß, wann ich você und wann o senhor / a senhora verwende.',
  ],
  topicIds: ['pt.g.formality'],
  vocab: [
    { id: `${L}.v.oi`, target: 'oi', german: 'hallo, hi', pos: 'phrase', emoji: '👋', field: 'Begrüßung', stageId: 'stage0', lessonId: L, example: { target: 'Oi, tudo bem?', german: 'Hi, wie geht’s?' } },
    { id: `${L}.v.ola`, target: 'olá', german: 'hallo (etwas neutraler, oft geschrieben)', pos: 'phrase', field: 'Begrüßung', stageId: 'stage0', lessonId: L, example: { target: 'Olá! Boa tarde!', german: 'Hallo! Guten Tag!' } },
    { id: `${L}.v.bom-dia`, target: 'bom dia', german: 'guten Morgen / guten Tag (bis mittags)', pos: 'phrase', emoji: '🌅', field: 'Begrüßung', stageId: 'stage0', lessonId: L, example: { target: 'Bom dia, tudo bem?', german: 'Guten Morgen, alles gut?' } },
    { id: `${L}.v.boa-tarde`, target: 'boa tarde', german: 'guten Tag / Nachmittag (ca. 12–18 Uhr)', pos: 'phrase', emoji: '☀️', field: 'Begrüßung', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.boa-noite`, target: 'boa noite', german: 'guten Abend / gute Nacht', pos: 'phrase', emoji: '🌙', field: 'Begrüßung', stageId: 'stage0', lessonId: L, example: { target: 'Boa noite, até amanhã!', german: 'Gute Nacht, bis morgen!' } },
    { id: `${L}.v.tudo-bem`, target: 'tudo bem?', german: 'wie geht’s? (wörtl. alles gut?)', pos: 'phrase', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Oi, tudo bem?', german: 'Hi, wie geht’s?' } },
    { id: `${L}.v.tudo-bom`, target: 'tudo bom', german: 'alles gut (Antwort oder Frage)', pos: 'phrase', field: 'Befinden', stageId: 'stage0', lessonId: L, example: { target: 'Tudo bom, e você?', german: 'Gut, und dir?' } },
    { id: `${L}.v.e-voce`, target: 'e você?', german: 'und du? / und dir?', pos: 'phrase', field: 'Befinden', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.obrigado`, target: 'obrigado / obrigada', german: 'danke (Mann / Frau spricht)', pos: 'phrase', emoji: '🙏', field: 'Höflichkeit', stageId: 'stage0', lessonId: L, example: { target: 'Obrigada! – De nada.', german: 'Danke! – Gern geschehen.' } },
    { id: `${L}.v.de-nada`, target: 'de nada', german: 'gern geschehen, bitte', pos: 'phrase', field: 'Höflichkeit', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.tchau`, target: 'tchau', german: 'tschüss', pos: 'phrase', field: 'Abschied', stageId: 'stage0', lessonId: L, example: { target: 'Tchau, até logo!', german: 'Tschüss, bis später!' } },
    { id: `${L}.v.ate-logo`, target: 'até logo', german: 'bis später, bis bald', pos: 'phrase', field: 'Abschied', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.ate-amanha`, target: 'até amanhã', german: 'bis morgen', pos: 'phrase', field: 'Abschied', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.voce`, target: 'você', german: 'du (Standardanrede in Brasilien)', pos: 'pron', field: 'Anrede', stageId: 'stage0', lessonId: L, example: { target: 'E você?', german: 'Und du?' } },
    { id: `${L}.v.o-senhor`, target: 'o senhor / a senhora', german: 'Sie (zu einem Mann / einer Frau)', pos: 'pron', gender: 'm/f', field: 'Anrede', stageId: 'stage0', lessonId: L, example: { target: 'Tudo bem com a senhora?', german: 'Geht es Ihnen gut?' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'In Brasilien grüßt man herzlich und unkompliziert. Die häufigste Begrüßung ist `Oi!` (klingt wie „oi“ in „ahoi“). Fast immer folgt `Tudo bem?` – wörtlich „Alles gut?“. Das ist keine echte Frage nach deiner Gesundheit, sondern wie „Na, alles klar?“.\n' +
        'Die typische Antwort: `Tudo bem!` oder `Tudo bom!` – und dann die Gegenfrage `E você?` (Und du?).\n' +
        'Zur Tageszeit passend sagst du `bom dia`, `boa tarde` oder `boa noite`. Achtung: `dia` ist männlich (**bom**), `tarde` und `noite` sind weiblich (**boa**).',
    },
    {
      type: 'table',
      title: 'Grüßen & Verabschieden',
      headers: ['Portugiesisch', 'Deutsch', 'Wann?'],
      rows: [
        ['Oi! / Olá!', 'Hi! / Hallo!', 'immer; olá etwas neutraler'],
        ['Bom dia!', 'Guten Morgen!', 'bis ca. 12 Uhr'],
        ['Boa tarde!', 'Guten Tag!', 'ca. 12 Uhr bis zur Dunkelheit'],
        ['Boa noite!', 'Guten Abend! / Gute Nacht!', 'abends – zum Grüßen und zum Abschied'],
        ['Tchau!', 'Tschüss!', 'immer'],
        ['Até logo! / Até amanhã!', 'Bis später! / Bis morgen!', 'beim Abschied'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Oi', role: 'other' },
        { text: ', ' },
        { text: 'tudo', role: 'pronoun' },
        { text: ' ' },
        { text: 'bem', role: 'adverb' },
        { text: '?' },
      ],
      german: 'Hi, alles gut? (= Wie geht’s?)',
    },
    {
      type: 'text',
      md:
        '**Du oder Sie?** In Brasilien ist `você` die normale Anrede – für Freunde, Kollegen, im Laden, oft auch bei Fremden. Respektvoll-distanziert sprichst du ältere Menschen oder Respektspersonen mit `o senhor` (zu einem Mann) bzw. `a senhora` (zu einer Frau) an: `Bom dia! Tudo bem com a senhora?` – „Guten Morgen! Geht es Ihnen gut?“\n' +
        'Regionaler Hinweis: Im Süden und in Teilen des Nordostens hörst du auch `tu`. Du musst es verstehen, aber nicht benutzen – mit `você` liegst du überall in Brasilien richtig.',
    },
    {
      type: 'compare',
      target: 'Obrigado! / Obrigada!',
      german: 'Danke!',
      md: 'Anders als im Deutschen hängt das Wort vom **Sprecher** ab: Männer sagen `obrigado`, Frauen `obrigada` – egal, wem sie danken. Wörtlich heißt es etwa „(dir) verbunden“. Die Antwort ist `De nada.` – „Gern geschehen.“',
    },
    {
      type: 'mistake',
      wrong: 'Boa dia!',
      right: 'Bom dia!',
      why: '`dia` endet zwar auf -a, ist aber **männlich** – deshalb `bom`. `tarde` und `noite` sind weiblich: `boa tarde`, `boa noite`.',
    },
    {
      type: 'tip',
      md: 'Merksatz: **Bom dia** bis zum Mittagessen, **boa tarde** bis es dunkel wird, **boa noite** danach – und **tchau** passt immer.',
    },
    { type: 'audio', text: 'Oi, tudo bem? – Tudo bom! E você?', label: 'Mini-Dialog anhören' },
  ],
  examples: [
    {
      target: 'Oi, tudo bem?',
      german: 'Hi, wie geht’s?',
      literal: 'Hi, alles gut?',
      parts: [{ text: 'Oi', role: 'other' }, { text: ', ' }, { text: 'tudo', role: 'pronoun' }, { text: ' ' }, { text: 'bem', role: 'adverb' }, { text: '?' }],
    },
    { target: 'Tudo bom, e você?', german: 'Gut, und dir?', literal: 'Alles gut, und du?' },
    {
      target: 'Bom dia! Tudo bem com o senhor?',
      german: 'Guten Morgen! Geht es Ihnen gut?',
      literal: 'Guter Tag! Alles gut mit dem Herrn?',
      note: 'Respektvoll gegenüber einem älteren Mann.',
    },
    { target: 'Boa tarde! Tudo bem com a senhora?', german: 'Guten Tag! Geht es Ihnen gut?', note: 'Respektvoll gegenüber einer älteren Frau.' },
    { target: 'Obrigada! – De nada.', german: 'Danke! – Gern geschehen.', note: 'Hier bedankt sich eine Frau: **obrigada**.' },
    { target: 'Boa noite! Até amanhã!', german: 'Gute Nacht! Bis morgen!' },
    { target: 'Tchau, até logo!', german: 'Tschüss, bis später!' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'mc',
      skills: ['vocabulary', 'reading'],
      topicIds: ['pt.g.formality'],
      difficulty: 1,
      prompt: 'Es ist 9 Uhr morgens. Wie grüßt du?',
      options: [
        { text: 'Bom dia!' },
        { text: 'Boa tarde!', why: '`Boa tarde` sagt man ab etwa 12 Uhr.' },
        { text: 'Boa noite!', why: '`Boa noite` sagt man abends.' },
        { text: 'Boa dia!', why: '`dia` ist männlich – es heißt `bom dia`.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Bis etwa 12 Uhr grüßt man mit `Bom dia!`.',
        why: '`Boa tarde` gilt nachmittags, `boa noite` abends. `Boa dia` ist falsch, weil `dia` männlich ist.',
        avoid: 'Denk an das Mittagessen als Grenze: davor `bom dia`, danach `boa tarde`.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'matchPairs',
      skills: ['vocabulary', 'reading'],
      difficulty: 1,
      instruction: 'Ordne die Ausdrücke ihrer Bedeutung zu.',
      pairs: [
        { left: 'Oi!', right: 'Hi!' },
        { left: 'Tchau!', right: 'Tschüss!' },
        { left: 'Obrigado!', right: 'Danke!' },
        { left: 'De nada.', right: 'Gern geschehen.' },
        { left: 'Até amanhã!', right: 'Bis morgen!' },
      ],
      feedback: {
        rule: 'Grundwortschatz: `oi` (hi), `tchau` (tschüss), `obrigado/obrigada` (danke), `de nada` (gern geschehen), `até amanhã` (bis morgen).',
        why: '`Até` heißt „bis“, `amanhã` „morgen“ – zusammen „bis morgen“.',
        avoid: 'Lerne Ausdrücke als Paar: `Obrigado!` – `De nada.`',
      },
    },
    {
      id: `${L}.g03`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      difficulty: 1,
      audio: 'Boa noite!',
      question: 'Zu welcher Tageszeit passt dieser Gruß?',
      options: ['Morgens', 'Nachmittags', 'Abends'],
      answer: 2,
      feedback: {
        rule: '`Boa noite` sagt man abends – zur Begrüßung und zum Abschied.',
        why: 'Morgens heißt es `bom dia`, nachmittags `boa tarde`.',
        avoid: 'Hör auf das zweite Wort: `dia` (Tag/Morgen), `tarde` (Nachmittag), `noite` (Abend/Nacht).',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'vocabulary'],
      topicIds: ['pt.g.formality'],
      difficulty: 2,
      instruction: 'Maria bedankt sich. Ergänze.',
      sentence: 'Maria: ___! – Pedro: De nada.',
      answers: [['Obrigada']],
      bank: ['Obrigado', 'Obrigada', 'Tchau'],
      german: 'Maria: Danke! – Pedro: Gern geschehen.',
      feedback: {
        rule: 'Frauen sagen `obrigada`, Männer `obrigado` – entscheidend ist, **wer spricht**.',
        why: '`Obrigado` wäre die Form für einen männlichen Sprecher. Maria ist eine Frau.',
        avoid: 'Frag dich: Wer bedankt sich gerade? Frau → -a, Mann → -o.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'situation',
      skills: ['reading', 'speaking'],
      topicIds: ['pt.g.formality'],
      difficulty: 2,
      scenario: 'Du triffst morgens im Treppenhaus deine ältere Nachbarin (etwa 75). Was sagst du am passendsten?',
      options: [
        { text: 'Bom dia! Tudo bem com a senhora?' },
        { text: 'Oi! E aí, tudo bom?', why: 'Das ist sehr locker – unter Freunden super, bei einer älteren Nachbarin eher unpassend.' },
        { text: 'Boa noite! Tudo bem com o senhor?', why: 'Falsche Tageszeit und `o senhor` spricht einen Mann an.' },
      ],
      answer: 0,
      feedback: {
        rule: 'Ältere Menschen und Respektspersonen sprichst du mit `o senhor` (Mann) / `a senhora` (Frau) an.',
        why: 'Die Nachbarin ist eine Frau → `a senhora`. Morgens → `bom dia`.',
        avoid: 'Prüfe zwei Dinge: Tageszeit (bom dia / boa tarde / boa noite) und Anrede (você oder o senhor / a senhora).',
      },
    },
    {
      id: `${L}.g06`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.formality'],
      difficulty: 2,
      instruction: 'Bilde die höfliche Begrüßung an einen älteren Herrn.',
      tokens: ['Bom', 'dia!', 'Tudo', 'bem', 'com', 'o', 'senhor?'],
      extra: ['boa', 'a'],
      german: 'Guten Morgen! Geht es Ihnen gut?',
      feedback: {
        rule: 'Höfliche Frage: `Tudo bem com o senhor?` (zu einem Mann) – wörtlich „Alles gut mit dem Herrn?“.',
        why: '`a` gehört zu `a senhora` (Frau). `boa` passt nicht zu `dia`, weil `dia` männlich ist.',
        avoid: 'Merke das Paar: `o senhor` – `a senhora`. Der Artikel zeigt das Geschlecht.',
      },
    },
    {
      id: `${L}.g07`,
      type: 'translate',
      skills: ['writing', 'vocabulary'],
      difficulty: 2,
      direction: 'toTarget',
      source: 'Gute Nacht! Bis morgen!',
      answers: ['Boa noite! Até amanhã!', 'Boa noite, até amanhã!'],
      feedback: {
        rule: '„Gute Nacht“ = `boa noite` (weiblich, weil `noite` weiblich ist). „Bis morgen“ = `até amanhã`.',
        why: '`Bom noite` ist falsch (noite ist weiblich). `Até logo` hieße „bis später“.',
        avoid: 'Denk an die Tilde: `amanhã` endet nasal – „a-ma-NJÃ“.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      difficulty: 3,
      audio: 'Tchau, até logo!',
      answers: ['Tchau, até logo!', 'Tchau até logo'],
      german: 'Tschüss, bis später!',
      feedback: {
        rule: '`Tchau` schreibt man mit **tch** (aus dem Italienischen „ciao“). `Até` hat einen Akzent auf dem e.',
        why: 'Häufige Fehler: „Chau“, „Tschau“ oder „ate“ ohne Akzent.',
        avoid: 'Merke: tch = „tsch“. Und `até` wird auf der letzten Silbe betont – deshalb der Akzent.',
      },
    },
  ],
  pronunciation: ['pt.p.rhythm.tudo-bem', 'pt.p.rhythm.bom-dia', 'pt.p.stress.voce'],
  application: [
    {
      id: `${L}.a01`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['pt.g.formality'],
      difficulty: 2,
      prompt: 'Es ist 15 Uhr. Begrüße eine Freundin und frag, wie es ihr geht.',
      keywords: ['oi', 'boa tarde', 'tudo bem', 'tudo bom'],
      minMatch: 2,
      sample: 'Oi, boa tarde! Tudo bem?',
      feedback: {
        rule: 'Begrüßung + Frage nach dem Befinden: `Oi!` oder `Boa tarde!` + `Tudo bem?`',
        why: 'Um 15 Uhr passt `boa tarde`, nicht `bom dia` oder `boa noite`.',
        avoid: 'Bau dir eine feste Formel: Gruß + `tudo bem?` – die passt fast immer.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'dialogue',
      skills: ['reading', 'speaking'],
      difficulty: 2,
      instruction: 'Vervollständige den Dialog.',
      lines: [
        { speaker: 'Lucas', text: 'Bom dia! Tudo bem?', german: 'Guten Morgen! Wie geht’s?' },
        { speaker: 'Ana', text: 'Tudo bom! E você?', german: 'Gut! Und dir?' },
        { speaker: 'Lucas', text: '…' },
        { speaker: 'Ana', text: 'Tchau, até logo!', german: 'Tschüss, bis später!' },
      ],
      gapIndex: 2,
      options: ['Tudo bem, obrigado!', 'De nada!', 'Boa noite, até amanhã!'],
      answer: 0,
      feedback: {
        rule: 'Auf `E você?` antwortest du mit deinem Befinden: `Tudo bem, obrigado/obrigada!`',
        why: '`De nada` antwortet auf ein Danke. `Boa noite, até amanhã` ist ein Abschied am Abend – es ist aber Morgen.',
        avoid: 'Achte auf das Frage-Antwort-Paar: `Tudo bem? – Tudo bem!`',
      },
    },
    {
      id: `${L}.a03`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.formality'],
      difficulty: 2,
      scenarioId: 'pt.sc.alltag',
      goal: 'Begrüße deinen Gesprächspartner passend zur Tageszeit, frag mit `Tudo bem?`, wie es ihm geht, antworte auf seine Gegenfrage und verabschiede dich.',
      turns: 4,
      feedback: {
        rule: 'Ein kurzes Alltagsgespräch: Gruß → `Tudo bem?` → Antwort + `E você?` → Abschied (`Tchau!`, `Até logo!`).',
        avoid: 'Wenn dir etwas fehlt, nutze die Bausteine aus der Tabelle dieser Lektion.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'mc',
      skills: ['vocabulary', 'reading'],
      difficulty: 1,
      prompt: 'Welche Begrüßung passt um 15 Uhr?',
      options: [{ text: 'Boa tarde!' }, { text: 'Bom dia!' }, { text: 'Boa noite!' }],
      answer: 0,
      feedback: {
        rule: 'Nachmittags (ca. 12–18 Uhr) grüßt man mit `Boa tarde!`.',
        why: '`Bom dia` gilt bis mittags, `boa noite` ab dem Abend.',
        avoid: 'Drei Tageszeiten, drei Grüße: dia – tarde – noite.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      difficulty: 2,
      sentence: 'Boa dia!',
      answers: ['Bom dia!'],
      german: 'Guten Morgen!',
      feedback: {
        rule: '`dia` ist männlich → `bom dia`.',
        why: 'Viele denken wegen der Endung -a an ein weibliches Wort. `dia` ist eine wichtige Ausnahme.',
        avoid: 'Merke dir die Formel als Ganzes: **bom dia** – **boa tarde** – **boa noite**.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'translate',
      skills: ['reading', 'vocabulary'],
      difficulty: 1,
      direction: 'toGerman',
      source: 'Até amanhã!',
      answers: ['Bis morgen!', 'Bis morgen'],
      feedback: {
        rule: '`até` = bis, `amanhã` = morgen.',
        why: '`Até logo` wäre „bis später“.',
        avoid: 'Verbinde `amanhã` mit dem „Morgen“ im Sinne von „der nächste Tag“.',
      },
    },
  ],
};

export default lesson;
