import type { Lesson } from '../../types';

const L = 'pt.s0.l07';

const lesson: Lesson = {
  id: L,
  courseId: 'pt-BR',
  stageId: 'stage0',
  chapterId: 'pt.s0.c3',
  order: 7,
  title: 'Se apresentar – sich vorstellen & fragen',
  subtitle: 'Meu nome é … · Moro em … · Onde? Quem? Quanto?',
  icon: '🙋',
  minutes: 12,
  goal:
    'Du kannst dich vollständig vorstellen – **Name, Herkunft, Wohnort, Alter, Sprachen** – und anderen die passenden Fragen stellen. Dazu lernst du die **regelmäßigen Verben** im Präsens (-ar, -er, -ir) und die wichtigsten **Fragewörter**.',
  canDo: [
    'Ich kann mich mit Name, Herkunft, Wohnort, Alter und Sprachen vorstellen.',
    'Ich kann regelmäßige Verben auf -ar, -er und -ir im Präsens bilden.',
    'Ich kann Fragen mit o que, quem, onde, como, quando und quanto stellen.',
    'Ich weiß, dass man das Alter mit „ter“ (haben) angibt.',
  ],
  topicIds: ['pt.g.present-regular', 'pt.g.questions'],
  vocab: [
    { id: `${L}.v.meu-nome`, target: 'Meu nome é …', german: 'Mein Name ist …', pos: 'phrase', field: 'Vorstellung', stageId: 'stage0', lessonId: L, example: { target: 'Meu nome é Lukas.', german: 'Mein Name ist Lukas.' } },
    { id: `${L}.v.morar`, target: 'morar', german: 'wohnen', pos: 'verb', emoji: '🏡', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Moro em Hamburgo.', german: 'Ich wohne in Hamburg.' } },
    { id: `${L}.v.falar`, target: 'falar', german: 'sprechen', pos: 'verb', emoji: '💬', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Falo alemão e inglês.', german: 'Ich spreche Deutsch und Englisch.' } },
    { id: `${L}.v.trabalhar`, target: 'trabalhar', german: 'arbeiten', pos: 'verb', emoji: '💼', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Trabalho em casa.', german: 'Ich arbeite zu Hause.' } },
    { id: `${L}.v.estudar`, target: 'estudar', german: 'lernen, studieren', pos: 'verb', emoji: '📚', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'O que você estuda?', german: 'Was studierst du?' } },
    { id: `${L}.v.aprender`, target: 'aprender', german: 'lernen (sich aneignen)', pos: 'verb', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Aprendo português.', german: 'Ich lerne Portugiesisch.' } },
    { id: `${L}.v.ter`, target: 'ter (tenho, tem)', german: 'haben', pos: 'verb', field: 'Verben', stageId: 'stage0', lessonId: L, example: { target: 'Tenho trinta anos.', german: 'Ich bin dreißig Jahre alt.' } },
    { id: `${L}.v.ano`, target: 'o ano', german: 'das Jahr', pos: 'noun', gender: 'm', plural: 'anos', emoji: '📅', field: 'Zeit', stageId: 'stage0', lessonId: L },
    { id: `${L}.v.portugues`, target: 'o português', german: 'Portugiesisch (Sprache); auch: o alemão = Deutsch, o inglês = Englisch', pos: 'noun', gender: 'm', field: 'Sprachen', stageId: 'stage0', lessonId: L, example: { target: 'Falo um pouco de português.', german: 'Ich spreche ein bisschen Portugiesisch.' } },
    { id: `${L}.v.o-que`, target: 'o que?', german: 'was?', pos: 'pron', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: 'O que você estuda?', german: 'Was studierst du?' } },
    { id: `${L}.v.quem`, target: 'quem?', german: 'wer?', pos: 'pron', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: 'Quem é ela?', german: 'Wer ist sie?' } },
    { id: `${L}.v.onde`, target: 'onde?', german: 'wo?', pos: 'adv', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: 'Onde você mora?', german: 'Wo wohnst du?' } },
    { id: `${L}.v.como`, target: 'como?', german: 'wie?', pos: 'adv', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: 'Como você se chama?', german: 'Wie heißt du?' } },
    { id: `${L}.v.quando`, target: 'quando?', german: 'wann?', pos: 'adv', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: 'Quando você trabalha?', german: 'Wann arbeitest du?' } },
    { id: `${L}.v.quanto`, target: 'quanto? / quantos?', german: 'wie viel? / wie viele?', pos: 'pron', field: 'Fragen', stageId: 'stage0', lessonId: L, example: { target: 'Quantos anos você tem?', german: 'Wie alt bist du?' } },
  ],
  explanation: [
    {
      type: 'text',
      md:
        'Mit fünf Bausteinen stellst du dich vor:\n' +
        '- `Meu nome é …` – Mein Name ist …\n' +
        '- `Sou de …` / `Sou da Alemanha.` – Ich komme aus …\n' +
        '- `Moro em …` – Ich wohne in …\n' +
        '- `Tenho … anos.` – Ich bin … Jahre alt. (wörtlich: Ich **habe** … Jahre)\n' +
        '- `Falo …` – Ich spreche …\n' +
        '`ter` (haben) ist unregelmäßig: `eu tenho`, `você/ele/ela/a gente tem`, `nós temos`, `vocês/eles/elas têm`.',
    },
    {
      type: 'conjugation',
      verb: 'falar',
      translation: 'sprechen',
      tense: 'Präsens',
      rows: [
        { person: 'eu', form: 'falo', ending: 'o' },
        { person: 'você / ele / ela / a gente', form: 'fala', ending: 'a' },
        { person: 'nós', form: 'falamos', ending: 'amos' },
        { person: 'vocês / eles / elas', form: 'falam', ending: 'am' },
      ],
    },
    {
      type: 'table',
      title: 'Regelmäßige Verben: -ar, -er, -ir',
      headers: ['Person', '-ar: morar', '-er: aprender', '-ir: abrir (öffnen)'],
      rows: [
        ['eu', 'moro', 'aprendo', 'abro'],
        ['você / ele / ela / a gente', 'mora', 'aprende', 'abre'],
        ['nós', 'moramos', 'aprendemos', 'abrimos'],
        ['vocês / eles / elas', 'moram', 'aprendem', 'abrem'],
      ],
    },
    {
      type: 'table',
      title: 'Fragewörter',
      headers: ['Fragewort', 'Deutsch', 'Beispiel'],
      rows: [
        ['o que', 'was', 'O que você estuda?'],
        ['quem', 'wer', 'Quem é ela?'],
        ['onde', 'wo', 'Onde você mora?'],
        ['de onde', 'woher', 'De onde você é?'],
        ['como', 'wie', 'Como você se chama?'],
        ['quando', 'wann', 'Quando você trabalha?'],
        ['quanto / quanta / quantos / quantas', 'wie viel / wie viele', 'Quantos anos você tem?'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Onde', role: 'question' },
        { text: ' ' },
        { text: 'você', role: 'subject' },
        { text: ' ' },
        { text: 'mora', role: 'verb' },
        { text: '?' },
      ],
      german: 'Wo wohnst du?',
    },
    {
      type: 'compare',
      target: 'Onde você mora? · Você fala inglês?',
      german: 'Wo wohnst du? · Sprichst du Englisch?',
      md:
        'Im Deutschen tauschen Verb und Subjekt in der Frage die Plätze („wohnst du“). Im brasilianischen Portugiesisch bleibt die normale Reihenfolge: **Fragewort + você + Verb**. Ja/Nein-Fragen erkennt man nur an der **Satzmelodie** – die Stimme geht am Ende hoch.\n' +
        '`quanto` richtet sich nach dem Nomen: `quantos anos` (m. Pl.), `quantas línguas` (f. Pl.).',
    },
    {
      type: 'mistake',
      wrong: 'Eu sou 30 anos.',
      right: 'Eu tenho 30 anos.',
      why: 'Das Alter „hat“ man im Portugiesischen: `Tenho 30 anos` = „Ich habe 30 Jahre“. Mit `ser` oder `estar` ist der Satz falsch.',
    },
    {
      type: 'tip',
      md: 'Merksatz für die Endungen: **eu -o, você -a/-e, nós -mos, vocês -m.** Und: **Alter hat man** – `tenho … anos`.',
    },
  ],
  examples: [
    {
      target: 'Meu nome é Lukas. Sou de Colônia.',
      german: 'Mein Name ist Lukas. Ich komme aus Köln.',
      parts: [{ text: 'Meu nome', role: 'subject' }, { text: ' ' }, { text: 'é', role: 'verb' }, { text: ' Lukas. ' }, { text: 'Sou', role: 'verb' }, { text: ' ' }, { text: 'de', role: 'preposition' }, { text: ' Colônia.' }],
    },
    { target: 'Moro em Hamburgo e trabalho em casa.', german: 'Ich wohne in Hamburg und arbeite zu Hause.' },
    {
      target: 'Tenho trinta e dois anos.',
      german: 'Ich bin 32 Jahre alt.',
      literal: 'Ich habe 32 Jahre.',
      parts: [{ text: 'Tenho', role: 'verb' }, { text: ' ' }, { text: 'trinta e dois', role: 'other' }, { text: ' ' }, { text: 'anos', role: 'noun' }, { text: '.' }],
    },
    { target: 'Falo alemão, inglês e um pouco de português.', german: 'Ich spreche Deutsch, Englisch und ein bisschen Portugiesisch.', note: '`um pouco de` = ein bisschen.' },
    {
      target: 'Quantos anos você tem?',
      german: 'Wie alt bist du?',
      literal: 'Wie viele Jahre hast du?',
      parts: [{ text: 'Quantos', role: 'question' }, { text: ' ' }, { text: 'anos', role: 'noun' }, { text: ' ' }, { text: 'você', role: 'subject' }, { text: ' ' }, { text: 'tem', role: 'verb' }, { text: '?' }],
    },
    { target: 'O que você estuda? – Estudo medicina.', german: 'Was studierst du? – Ich studiere Medizin.' },
    { target: 'Quem é ela? – É a Júlia, uma amiga.', german: 'Wer ist sie? – Das ist Júlia, eine Freundin.' },
    { target: 'Como você se chama? – Me chamo Rafael.', german: 'Wie heißt du? – Ich heiße Rafael.', note: 'Im brasilianischen Alltag beginnt man den Satz gern mit `Me chamo …` – eine feste Wendung.' },
  ],
  guided: [
    {
      id: `${L}.g01`,
      type: 'matchPairs',
      skills: ['vocabulary', 'grammar'],
      topicIds: ['pt.g.questions'],
      difficulty: 1,
      instruction: 'Ordne die Fragewörter zu.',
      pairs: [
        { left: 'onde', right: 'wo' },
        { left: 'quem', right: 'wer' },
        { left: 'quando', right: 'wann' },
        { left: 'como', right: 'wie' },
        { left: 'o que', right: 'was' },
      ],
      feedback: {
        rule: 'onde = wo, quem = wer, quando = wann, como = wie, o que = was.',
        why: '`quem` (wer) und `quando` (wann) beginnen beide mit „qu“ – achte auf den Rest.',
        avoid: 'Eselsbrücke: qu**em** – „wem/wer“; qu**ando** – „wann“.',
      },
    },
    {
      id: `${L}.g02`,
      type: 'conjugate',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.present-regular'],
      difficulty: 1,
      verb: 'falar',
      tense: 'Präsens',
      person: 'nós',
      sentence: 'Nós ___ português.',
      answers: ['falamos'],
      feedback: {
        rule: 'Regelmäßig auf -ar: Stamm `fal-` + Endung **-amos** für nós.',
        why: '`falam` ist die Form für vocês/eles, `fala` für você/ele/a gente.',
        avoid: 'nós → immer **-mos** am Ende.',
      },
    },
    {
      id: `${L}.g03`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.present-regular'],
      difficulty: 2,
      sentence: 'Eu sou vinte e cinco anos.',
      answers: ['Eu tenho vinte e cinco anos.', 'Tenho vinte e cinco anos.', 'Eu tenho 25 anos.', 'Tenho 25 anos.'],
      german: 'Ich bin 25 Jahre alt.',
      feedback: {
        rule: 'Alter mit `ter`: `Tenho … anos.`',
        why: 'Wörtlich aus dem Deutschen übersetzt („ich bin … alt“) entsteht ein falscher Satz mit `sou`.',
        avoid: 'Alter hat man: tenho – tem – temos – têm.',
      },
    },
    {
      id: `${L}.g04`,
      type: 'cloze',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.questions', 'pt.g.present-regular'],
      difficulty: 2,
      sentence: '___ você mora? – Moro ___ Hamburgo.',
      answers: [['Onde'], ['em']],
      bank: ['Onde', 'Quando', 'Quem', 'em', 'de', 'no'],
      german: 'Wo wohnst du? – Ich wohne in Hamburg.',
      feedback: {
        rule: 'Nach dem Ort fragen: `Onde …?`; Städte ohne Artikel: `em Hamburgo`.',
        why: '`no` wäre em + o – Städte wie Hamburgo haben aber keinen Artikel. `de` hieße „aus“.',
        avoid: 'Wohnort → morar **em** + Stadt.',
      },
    },
    {
      id: `${L}.g05`,
      type: 'order',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.questions'],
      difficulty: 2,
      tokens: ['De', 'onde', 'você', 'é?'],
      alternatives: [['Você', 'é', 'de', 'onde?']],
      extra: ['está'],
      german: 'Woher kommst du?',
      feedback: {
        rule: 'Herkunft erfragen: `De onde você é?` – umgangssprachlich auch `Você é de onde?`.',
        why: '`está` (estar) passt nicht zur Herkunft – die ist Teil des Steckbriefs (`ser`).',
        avoid: 'Fragewort vorne, dann `você` + Verb – keine Umstellung wie im Deutschen.',
      },
    },
    {
      id: `${L}.g06`,
      type: 'listening',
      skills: ['listening', 'vocabulary'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      audio: 'Tenho vinte e oito anos.',
      question: 'Wie alt ist die Person?',
      options: ['18', '28', '38'],
      answer: 1,
      feedback: {
        rule: '`vinte e oito` = 28.',
        why: '18 wäre `dezoito`, 38 `trinta e oito`.',
        avoid: 'Hör zuerst auf den Zehner: vinte (20), trinta (30).',
      },
    },
    {
      id: `${L}.g07`,
      type: 'dictation',
      skills: ['listening', 'writing'],
      topicIds: ['pt.g.questions'],
      difficulty: 2,
      audio: 'Onde você mora?',
      answers: ['Onde você mora?'],
      german: 'Wo wohnst du?',
      feedback: {
        rule: '`Onde você mora?` – Fragewort + Subjekt + Verb.',
        why: 'Häufige Schreibfehler: „voce“ ohne Zirkumflex oder „onte“ statt `onde`.',
        avoid: 'Das „dsch“ in `onde` („ÕN-dschi“) entsteht aus d + unbetontem -e – geschrieben wird `de`.',
      },
    },
    {
      id: `${L}.g08`,
      type: 'translate',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.present-regular'],
      difficulty: 3,
      direction: 'toTarget',
      source: 'Ich wohne in Berlin und spreche Deutsch.',
      answers: ['Moro em Berlim e falo alemão.', 'Eu moro em Berlim e falo alemão.', 'Eu moro em Berlim e eu falo alemão.'],
      feedback: {
        rule: '`morar` und `falar` in der eu-Form: `moro`, `falo`. Berlin = `Berlim`, Deutsch = `alemão`.',
        why: '`mora`/`fala` wären die Formen für você/ele. Sprachen schreibt man klein: `alemão`.',
        avoid: 'eu → Endung **-o**. Das Subjekt `eu` kannst du weglassen, die Endung zeigt die Person.',
      },
    },
  ],
  pronunciation: ['pt.p.rhythm.meu-nome-e', 'pt.p.rhythm.de-onde-voce-e', 'pt.p.ao.falam'],
  application: [
    {
      id: `${L}.a01`,
      type: 'freeText',
      skills: ['writing', 'grammar'],
      topicIds: ['pt.g.present-regular'],
      difficulty: 3,
      prompt: 'Schreib eine kurze Vorstellung: Name, Herkunft, Wohnort, Alter und Sprachen.',
      requirements: [
        { pattern: '(meu nome [eé]|me chamo|\\bsou\\b)', hint: 'Nenne deinen Namen („Meu nome é …“).' },
        { pattern: '\\bmoro\\b', hint: 'Sag, wo du wohnst („Moro em …“).' },
        { pattern: '\\btenho\\b.*\\banos\\b', hint: 'Nenne dein Alter („Tenho … anos“).' },
        { pattern: '\\bfalo\\b', hint: 'Sag, welche Sprachen du sprichst („Falo …“).' },
      ],
      samples: ['Oi! Meu nome é Lena. Sou da Alemanha, de Munique, mas moro em Hamburgo. Tenho vinte e nove anos. Falo alemão, inglês e um pouco de português.'],
      minWords: 12,
      feedback: {
        rule: 'Fünf Bausteine: Meu nome é … · Sou de/da … · Moro em … · Tenho … anos · Falo …',
        why: 'Die häufigsten Fehler: `sou … anos` statt `tenho … anos` und `Moro no Hamburgo` statt `Moro em Hamburgo`.',
        avoid: 'Geh die Bausteine der Reihe nach durch – wie eine Checkliste.',
      },
    },
    {
      id: `${L}.a02`,
      type: 'speakFree',
      skills: ['speaking', 'pronunciation'],
      topicIds: ['pt.g.present-regular'],
      difficulty: 3,
      prompt: 'Stell dich mündlich vor: Name, Herkunft, Wohnort, Alter und Sprachen.',
      keywords: ['nome', 'sou', 'moro', 'tenho', 'anos', 'falo'],
      minMatch: 4,
      sample: 'Meu nome é Jonas. Sou da Alemanha, moro em Colônia, tenho trinta anos e falo alemão e inglês.',
      feedback: {
        rule: 'Nutze mindestens vier der Bausteine: nome, sou, moro, tenho … anos, falo.',
        why: 'Fehlen Schlüsselwörter, hat die Spracherkennung sie nicht gehört – oder sie fehlen in deiner Vorstellung.',
        avoid: 'Übe die Sätze erst einzeln, dann im Fluss.',
      },
    },
    {
      id: `${L}.a03`,
      type: 'dialogue',
      skills: ['reading', 'grammar'],
      topicIds: ['pt.g.present-regular', 'pt.g.questions'],
      difficulty: 2,
      instruction: 'Rafael antwortet auf Lenas Frage. Was sagt er?',
      lines: [
        { speaker: 'Lena', text: 'Oi! Como você se chama?', german: 'Hi! Wie heißt du?' },
        { speaker: 'Rafael', text: 'Meu nome é Rafael. E você?', german: 'Ich heiße Rafael. Und du?' },
        { speaker: 'Lena', text: 'Meu nome é Lena. Onde você mora?', german: 'Ich heiße Lena. Wo wohnst du?' },
        { speaker: 'Rafael', text: '…' },
      ],
      gapIndex: 3,
      options: ['Moro em São Paulo. E você?', 'Tenho São Paulo. E você?', 'Sou em São Paulo. E você?'],
      answer: 0,
      feedback: {
        rule: 'Auf `Onde você mora?` antwortet man mit `Moro em …`.',
        why: '`tenho` heißt „ich habe“, `sou em` ist keine korrekte Ortsangabe.',
        avoid: 'Nimm das Verb der Frage auf: mora? → moro.',
      },
    },
    {
      id: `${L}.a04`,
      type: 'aiChat',
      skills: ['speaking', 'listening'],
      topicIds: ['pt.g.questions', 'pt.g.present-regular'],
      difficulty: 3,
      scenarioId: 'pt.sc.alltag',
      goal: 'Stell dich vor (Name, Herkunft, Wohnort) und stell deinem Gegenüber mindestens zwei Fragen, z. B. `Onde você mora?` und `Quantos anos você tem?`.',
      turns: 5,
      feedback: {
        rule: 'Vorstellen mit den fünf Bausteinen, Fragen mit Fragewort + você + Verb.',
        avoid: 'Hör auf die Verbform in der Frage und nimm sie in deiner Antwort auf: mora? → moro.',
      },
    },
  ],
  review: [
    {
      id: `${L}.r01`,
      type: 'cloze',
      skills: ['vocabulary', 'writing'],
      topicIds: ['pt.g.numbers'],
      difficulty: 2,
      instruction: 'Schreib die Zahl 21 aus.',
      sentence: 'Tenho ___ anos.',
      answers: [['vinte e um']],
      german: 'Ich bin 21 Jahre alt.',
      feedback: {
        rule: '21 = `vinte e um` (ano ist männlich → um).',
        why: '`vinte e uma` wäre die weibliche Form, z. B. `vinte e uma mulheres`.',
        avoid: 'Bei 1 und 2 aufs Genus achten: o ano → um.',
      },
    },
    {
      id: `${L}.r02`,
      type: 'mc',
      skills: ['grammar', 'reading'],
      topicIds: ['pt.g.ser-estar'],
      difficulty: 1,
      prompt: 'Onde você está? – ___ em casa.',
      options: [{ text: 'Sou', why: 'Aufenthaltsort → `estar`.' }, { text: 'Estou' }, { text: 'É', why: '`é` gehört zu você/ele/ela und zu ser.' }],
      answer: 1,
      feedback: {
        rule: 'Wo man gerade ist → `estar`: `Estou em casa.`',
        why: '`sou` (ser) beschreibt Identität und Herkunft.',
        avoid: 'Wo? → estar.',
      },
    },
    {
      id: `${L}.r03`,
      type: 'fixError',
      skills: ['grammar', 'writing'],
      topicIds: ['pt.g.contractions'],
      difficulty: 2,
      sentence: 'Estou em o Rio.',
      answers: ['Estou no Rio.'],
      german: 'Ich bin in Rio.',
      feedback: {
        rule: '`em` + `o` = `no`. Rio de Janeiro hat – anders als die meisten Städte – einen Artikel: `o Rio`.',
        why: '`em o` darf nie getrennt stehen.',
        avoid: 'Merke: no Rio, em São Paulo.',
      },
    },
  ],
};

export default lesson;
