import type { Exam } from '../types';

// ───────────────────────── Stufe 0 – Zwischentest (Lektionen 1–6) ─────────────────────────
const MID = 'es.exam.s0.mid';

const mid: Exam = {
  id: MID,
  courseId: 'es',
  stageId: 'stage0',
  kind: 'midterm',
  title: 'Zwischentest: Begrüßen, ser & estar',
  description:
    'Prüft den Stoff der Kapitel 1 und 2: begrüßen und verabschieden, **tú** oder **usted**, spanische Laute, Personalpronomen sowie **ser**, **estar** und ihren Unterschied. Du brauchst **60 %**. Du kannst den Test beliebig oft wiederholen – jeder Fehler wird dir erklärt.',
  passPct: 60,
  sections: [
    {
      title: 'Begrüßen & Anrede',
      skill: 'vocabulary',
      exercises: [
        {
          id: `${MID}.01`,
          type: 'situation',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.formality'],
          difficulty: 1,
          scenario: 'Es ist 22 Uhr. Du betrittst ein Restaurant und begrüßt den Kellner. Was sagst du?',
          options: [
            { text: 'Buenas noches.' },
            { text: 'Buenos días.', why: '`Buenos días` sagt man nur bis etwa zum Mittagessen.' },
            { text: 'Hasta mañana.', why: '`Hasta mañana` ist eine Verabschiedung („bis morgen“), keine Begrüßung.' },
            { text: 'Buenas tardes.', why: '`Buenas tardes` passt vom Mittagessen bis etwa zum Einbruch der Dunkelheit – um 22 Uhr ist es dafür zu spät.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Tageszeiten: `buenos días` (bis mittags), `buenas tardes` (nachmittags bis zum Abend), `buenas noches` (spätabends, zur Begrüßung und zum Abschied).',
            why: 'Anders als „gute Nacht“ im Deutschen ist `buenas noches` auch eine ganz normale Begrüßung am Abend.',
            avoid: 'Merke: Ist es dunkel, sagst du `buenas noches` – egal, ob du kommst oder gehst.',
          },
        },
        {
          id: `${MID}.02`,
          type: 'mc',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.formality', 'es.g.estar'],
          difficulty: 1,
          prompt: 'Du sprichst einen älteren Herrn an, den du nicht kennst. Welche Frage passt?',
          options: [
            { text: '¿Cómo está usted?' },
            { text: '¿Cómo estás?', why: 'Das ist die vertraute du-Form (tú) – für Fremde, besonders ältere Menschen, eher zu locker.' },
            { text: '¿Cómo es usted?', why: '`¿Cómo es?` fragt nach dem Charakter oder Aussehen („Wie ist er?“), nicht nach dem Befinden.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Höfliche Anrede: `usted` + Verbform der 3. Person: `¿Cómo está usted?` Befinden immer mit **estar**.',
            why: '`estás` ist die tú-Form; `es` (ser) fragt nach Eigenschaften statt nach dem Befinden.',
            avoid: 'Bei Unbekannten, älteren Menschen und im Beruf im Zweifel `usted` wählen.',
          },
        },
        {
          id: `${MID}.03`,
          type: 'matchPairs',
          skills: ['vocabulary'],
          topicIds: ['es.g.formality'],
          difficulty: 1,
          instruction: 'Ordne die Ausdrücke ihrer Bedeutung zu.',
          pairs: [
            { left: 'hola', right: 'hallo' },
            { left: 'adiós', right: 'tschüss / auf Wiedersehen' },
            { left: 'hasta mañana', right: 'bis morgen' },
            { left: 'buenos días', right: 'guten Morgen' },
            { left: 'muy bien', right: 'sehr gut' },
          ],
          feedback: {
            rule: 'Grundwortschatz Begrüßung: hola, buenos días – Verabschiedung: adiós, hasta mañana – Befinden: muy bien.',
            why: '`hasta mañana` und `buenos días` enthalten beide Zeitwörter – das eine verabschiedet, das andere begrüßt.',
            avoid: '`hasta …` leitet immer eine Verabschiedung ein: hasta luego, hasta mañana, hasta pronto.',
          },
        },
      ],
    },
    {
      title: 'Pronomen, ser & estar',
      skill: 'grammar',
      exercises: [
        {
          id: `${MID}.04`,
          type: 'matchPairs',
          skills: ['grammar'],
          topicIds: ['es.g.ser', 'es.g.pronouns'],
          difficulty: 1,
          instruction: 'Ordne jedem Pronomen die passende Form von „ser“ zu.',
          pairs: [
            { left: 'yo', right: 'soy' },
            { left: 'tú', right: 'eres' },
            { left: 'él', right: 'es' },
            { left: 'nosotros', right: 'somos' },
            { left: 'ellos', right: 'son' },
          ],
          feedback: {
            rule: '`ser`: soy, eres, es, somos, (sois), son – komplett unregelmäßig.',
            why: '`es` (er ist) und `eres` (du bist) werden oft vertauscht.',
            avoid: 'Sprich die Reihe laut: soy – eres – es – somos – son.',
          },
        },
        {
          id: `${MID}.05`,
          type: 'cloze',
          skills: ['grammar'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 2,
          sentence: 'Yo ___ de Alemania, pero ahora ___ en Madrid.',
          answers: [['soy'], ['estoy']],
          bank: ['soy', 'estoy', 'es', 'está'],
          german: 'Ich komme aus Deutschland, aber jetzt bin ich in Madrid.',
          feedback: {
            rule: 'Herkunft → **ser** (`soy de`); Ort, an dem man sich gerade befindet → **estar** (`estoy en`).',
            why: 'Beides heißt „sein“. Entscheidend ist: Woher? (dauerhaft, ser) oder Wo gerade? (estar).',
            avoid: 'Merkhilfe: „de“ (woher) → ser, „en“ (wo) bei Personen → estar.',
          },
        },
        {
          id: `${MID}.06`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.ser-estar', 'es.g.estar'],
          difficulty: 2,
          prompt: 'Der Kaffee ist (gerade) kalt. `El café ___ frío.`',
          options: [
            { text: 'está' },
            { text: 'es', why: '`es frío` würde eine grundsätzliche Eigenschaft beschreiben. Hier geht es um einen momentanen Zustand.' },
            { text: 'estás', why: '`estás` ist die tú-Form. `el café` ist 3. Person Singular.' },
            { text: 'son', why: '`son` ist Plural; `el café` ist eine einzelne Sache.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Zustände und Veränderungen → **estar**: `El café está frío.`',
            why: 'Der Kaffee war heiß und ist jetzt kalt – ein veränderlicher Zustand, keine Eigenschaft.',
            avoid: 'Frag dich: Kann sich das bald ändern? Dann meist estar.',
          },
        },
        {
          id: `${MID}.07`,
          type: 'conjugate',
          skills: ['grammar'],
          topicIds: ['es.g.estar'],
          difficulty: 2,
          verb: 'estar',
          tense: 'Präsens',
          person: 'nosotros',
          sentence: '___ muy bien, gracias.',
          answers: ['estamos', 'nosotros estamos', 'nosotras estamos'],
          feedback: {
            rule: '`estar`: estoy, estás, está, estamos, (estáis), están.',
            why: 'Typisch sind „estámos“ (überflüssiger Akzent) oder die ser-Form `somos` – beim Befinden steht aber immer estar.',
            avoid: 'Akzente stehen nur bei estás, está, estáis, están.',
          },
        },
        {
          id: `${MID}.08`,
          type: 'fixError',
          skills: ['grammar'],
          topicIds: ['es.g.ser-estar', 'es.g.ser'],
          difficulty: 2,
          instruction: 'Im Satz steckt ein Fehler. Schreib ihn richtig.',
          sentence: 'Ella está profesora.',
          answers: ['Ella es profesora.', 'Es profesora.'],
          german: 'Sie ist Lehrerin.',
          feedback: {
            rule: 'Beruf → **ser**: `Ella es profesora.` (ohne Artikel vor dem Beruf).',
            why: 'Der Beruf beschreibt, wer oder was jemand ist – eine Identität, kein Zustand.',
            avoid: 'Wer? Was? Woher? → ser. Wo? Wie geht’s? → estar.',
          },
        },
        {
          id: `${MID}.09`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.pronouns'],
          difficulty: 1,
          prompt: 'Eine Gruppe von Frauen spricht über sich: „wir“ heißt …',
          options: [
            { text: 'nosotras' },
            { text: 'nosotros', why: '`nosotros` benutzt man für Männer oder gemischte Gruppen.' },
            { text: 'vosotras', why: '`vosotras` heißt „ihr“ (Frauen) – und wird nur in Spanien verwendet.' },
            { text: 'ellas', why: '`ellas` heißt „sie“ (mehrere Frauen), nicht „wir“.' },
          ],
          answer: 0,
          feedback: {
            rule: '„wir“: `nosotros` (männlich/gemischt), `nosotras` (nur weiblich).',
            why: 'Spanische Pluralpronomen zeigen das Geschlecht der Gruppe.',
            avoid: 'Endung -as = nur Frauen, -os = Männer oder gemischt.',
          },
        },
      ],
    },
    {
      title: 'Hören & Aussprache',
      skill: 'listening',
      exercises: [
        {
          id: `${MID}.10`,
          type: 'listening',
          skills: ['listening'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          audio: 'Buenas tardes, señora Díaz. ¿Cómo está usted?',
          question: 'Wie wird Frau Díaz begrüßt?',
          options: ['höflich (usted), am Nachmittag', 'vertraut (tú), am Nachmittag', 'höflich (usted), am Morgen', 'vertraut (tú), am Abend'],
          answer: 0,
          feedback: {
            rule: '`buenas tardes` = Nachmittag/früher Abend; `¿Cómo está usted?` = höfliche Form.',
            why: 'Die vertraute Form wäre `¿Cómo estás?` – hier ist `usted` deutlich zu hören.',
            avoid: 'Achte auf `usted` oder `señora/señor` – beides signalisiert Höflichkeit.',
          },
        },
        {
          id: `${MID}.11`,
          type: 'minimalPair',
          skills: ['listening', 'pronunciation'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 2,
          instruction: 'Welches Wort hörst du?',
          options: ['pero', 'perro'],
          answer: 1,
          hint: '`pero` (aber) hat ein einfaches r – ein kurzer Zungenschlag. `perro` (Hund) hat ein rr – mehrere schnelle Schläge, gerollt.',
          feedback: {
            rule: 'Einfaches r zwischen Vokalen = ein Schlag; rr = gerolltes Zungenspitzen-R.',
            why: 'Deutsche Ohren sind das Rachen-R gewohnt und hören den Unterschied zwischen einem und mehreren Schlägen anfangs kaum.',
            avoid: 'Übe im Aussprache-Labor: Sag schnell „edda“ – so fühlt sich das einfache r an; für rr die Zunge länger flattern lassen.',
          },
        },
        {
          id: `${MID}.12`,
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.estar', 'es.g.questions'],
          difficulty: 2,
          audio: '¿Dónde estás?',
          answers: ['¿Dónde estás?'],
          german: 'Wo bist du?',
          feedback: {
            rule: 'Fragewörter tragen einen Akzent (`dónde`), die Verbform `estás` ebenfalls.',
            why: 'Ohne Akzent wäre `estas` ein anderes Wort („diese“, Plural).',
            avoid: 'Die betonte Silbe am Wortende (es-TÁS) verlangt bei Wörtern auf -s einen Akzent.',
          },
        },
        {
          id: `${MID}.13`,
          type: 'speak',
          skills: ['pronunciation', 'speaking'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          text: 'Buenos días, ¿cómo está usted?',
          german: 'Guten Morgen, wie geht es Ihnen?',
          phonetic: 'BUE-nos DI-as, KO-mo es-TA us-TED',
          ipa: '[ˈbwe.noz ˈði.as ˈko.mo esˈta usˈteð]',
          pronItemId: 'es.p.syl.buenos-dias',
          feedback: {
            rule: 'Klare, kurze Vokale; Betonung auf DI-as, es-TÁ und us-TED.',
            why: 'Deutschsprachige ziehen Vokale oft in die Länge oder sprechen das d in `días` zu hart.',
            avoid: 'Das d zwischen Vokalen und am Wortende weich sprechen – fast wie das englische „th“ in „this“.',
          },
        },
      ],
    },
  ],
};

// ───────────────────────── Stufe 0 – Abschlussprüfung ─────────────────────────
const FIN = 'es.exam.s0.final';

const final: Exam = {
  id: FIN,
  courseId: 'es',
  stageId: 'stage0',
  kind: 'final',
  title: 'Abschlussprüfung Stufe 0',
  description:
    'Die große Prüfung über die ganze Stufe 0: Grammatik, Wortschatz, Hören, Lesen & Schreiben und Sprechen. Du brauchst **70 %**. Danach wartet der Endgegner auf dich. Nimm dir Zeit – es gibt kein Zeitlimit.',
  passPct: 70,
  sections: [
    {
      title: 'Grammatik',
      skill: 'grammar',
      exercises: [
        {
          id: `${FIN}.01`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.articles', 'es.g.gender-plural'],
          difficulty: 1,
          prompt: 'Welcher Artikel passt? `___ ciudad es muy bonita.`',
          options: [
            { text: 'La' },
            { text: 'El', why: 'Wörter auf **-dad** sind weiblich: `la ciudad`, `la universidad`.' },
            { text: 'Los', why: '`los` ist Plural und maskulin – `ciudad` ist eine einzelne, weibliche Sache.' },
            { text: 'Un', why: '`un` ist maskulin; außerdem zeigt `bonita` (auf -a), dass das Nomen weiblich ist.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Nomen auf -dad, -ción, -sión sind weiblich: `la ciudad`, `la estación`.',
            why: 'Das Adjektiv `bonita` verrät das Geschlecht: Endung -a → weiblich.',
            avoid: 'Lerne Nomen immer mit Artikel und achte auf typische Endungen.',
          },
        },
        {
          id: `${FIN}.02`,
          type: 'cloze',
          skills: ['grammar'],
          topicIds: ['es.g.gender-plural', 'es.g.adjectives'],
          difficulty: 2,
          instruction: 'Setze die Wörter in Klammern in die richtige Form.',
          sentence: 'Los ___ (libro) son ___ (nuevo).',
          answers: [['libros'], ['nuevos']],
          german: 'Die Bücher sind neu.',
          feedback: {
            rule: 'Nomen auf Vokal bilden den Plural mit **-s**; das Adjektiv passt sich in Geschlecht und Zahl an: `los libros nuevos`.',
            why: 'Das Adjektiv bleibt im Deutschen nach „sind“ unverändert („neu“) – im Spanischen nicht.',
            avoid: 'Artikel, Nomen und Adjektiv bilden ein Team: alle drei im Plural (los … -s … -s).',
          },
        },
        {
          id: `${FIN}.03`,
          type: 'order',
          skills: ['grammar'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 2,
          instruction: 'Bilde den Satz „Ana und Pablo sprechen kein Englisch.“',
          tokens: ['Ana', 'y', 'Pablo', 'no', 'hablan', 'inglés.'],
          alternatives: [['Pablo', 'y', 'Ana', 'no', 'hablan', 'inglés.']],
          german: 'Ana und Pablo sprechen kein Englisch.',
          feedback: {
            rule: 'Verneinung: `no` steht direkt **vor** dem Verb: `no hablan`.',
            why: 'Das deutsche „kein“ steht beim Nomen – im Spanischen wird das Verb verneint.',
            avoid: 'Setze `no` immer unmittelbar vor das konjugierte Verb.',
          },
        },
        {
          id: `${FIN}.04`,
          type: 'conjugate',
          skills: ['grammar'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          verb: 'vivir',
          tense: 'Präsens',
          person: 'nosotros',
          sentence: '___ en una ciudad pequeña.',
          answers: ['vivimos', 'nosotros vivimos', 'nosotras vivimos'],
          feedback: {
            rule: '-ir-Verben: -o, -es, -e, **-imos**, (-ís), -en → `vivimos`.',
            why: '„vivemos“ mischt das Muster der -er-Verben ein. Nur bei nosotros/vosotros unterscheiden sich -er und -ir.',
            avoid: 'Der Infinitiv-Vokal kehrt bei nosotros zurück: viv**i**r → viv**i**mos.',
          },
        },
        {
          id: `${FIN}.05`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.ser-estar', 'es.g.estar'],
          difficulty: 2,
          prompt: '`Madrid ___ en España.`',
          options: [
            { text: 'está' },
            { text: 'es', why: 'Die Lage eines Ortes drückt man mit **estar** aus – auch wenn sie sich nie ändert.' },
            { text: 'hay', why: '`hay` (es gibt) steht vor unbestimmten Dingen (`hay un café`), nicht vor Eigennamen.' },
            { text: 'son', why: '`son` ist Plural; Madrid ist eine Stadt.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Lage / Ort → **estar**: `Madrid está en España.`',
            why: 'Viele denken „dauerhaft = ser“. Beim Ort gilt aber immer estar – egal wie dauerhaft.',
            avoid: 'Merksatz: „Wo etwas ist, sagt estar.“',
          },
        },
        {
          id: `${FIN}.06`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.hay'],
          difficulty: 2,
          prompt: '`En la calle ___ dos cafeterías.`',
          options: [
            { text: 'hay' },
            { text: 'están', why: '`están` braucht bestimmte Dinge mit Artikel: `Las cafeterías están en la calle.`' },
            { text: 'son', why: '`son` (ser) beschreibt, was etwas ist – nicht, ob es etwas irgendwo gibt.' },
            { text: 'es', why: '`es` ist Singular und fragt nicht nach der Existenz.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Existenz von unbestimmten Dingen (ein, zwei, viele …) → **hay**: `Hay dos cafeterías.`',
            why: '`hay` ist unveränderlich – es gibt keine Pluralform.',
            avoid: 'hay + un/una/Zahl/ohne Artikel · está(n) + el/la/los/las.',
          },
        },
        {
          id: `${FIN}.07`,
          type: 'fixError',
          skills: ['grammar'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 2,
          instruction: 'Im Satz steckt ein Fehler. Schreib ihn richtig.',
          sentence: 'Soy cansado hoy.',
          answers: ['Estoy cansado hoy.', 'Hoy estoy cansado.', 'Estoy cansada hoy.', 'Hoy estoy cansada.'],
          german: 'Ich bin heute müde.',
          feedback: {
            rule: 'Befinden und Zustände → **estar**: `Estoy cansado/cansada.`',
            why: '`soy cansado` klänge wie „ich bin ein ermüdender Mensch“ – das ist eine Eigenschaft, kein Zustand.',
            avoid: 'Gefühle und körperliche Zustände (müde, krank, zufrieden) fast immer mit estar.',
          },
        },
        {
          id: `${FIN}.08`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.questions', 'es.g.ser'],
          difficulty: 2,
          prompt: 'Wie fragst du „Woher kommst du?“',
          options: [
            { text: '¿De dónde eres?' },
            { text: '¿Dónde eres?', why: '`dónde` allein heißt „wo“. Für „woher“ brauchst du `de dónde`.' },
            { text: '¿De dónde estás?', why: 'Herkunft wird mit **ser** ausgedrückt: `eres`.' },
            { text: '¿Dónde de eres?', why: 'Die Präposition `de` steht vor dem Fragewort: `¿De dónde …?`' },
          ],
          answer: 0,
          feedback: {
            rule: 'Herkunft: `¿De dónde eres?` – Präposition vor das Fragewort, Verb ser.',
            why: 'Im Deutschen steckt „her“ im Fragewort, im Spanischen die Präposition `de`.',
            avoid: 'Präpositionen wandern im Spanischen immer mit nach vorn: ¿De dónde? ¿Con quién? ¿A qué hora?',
          },
        },
      ],
    },
    {
      title: 'Wortschatz',
      skill: 'vocabulary',
      exercises: [
        {
          id: `${FIN}.09`,
          type: 'matchPairs',
          skills: ['vocabulary'],
          topicIds: ['es.g.numbers'],
          difficulty: 2,
          instruction: 'Ordne die Zahlen zu.',
          pairs: [
            { left: '15', right: 'quince' },
            { left: '21', right: 'veintiuno' },
            { left: '40', right: 'cuarenta' },
            { left: '67', right: 'sesenta y siete' },
            { left: '99', right: 'noventa y nueve' },
          ],
          feedback: {
            rule: '16–29 schreibt man zusammen (`veintiuno`), ab 31 mit `y` getrennt (`sesenta y siete`).',
            why: '`sesenta` (60) und `setenta` (70) werden leicht verwechselt – ses- = sechs, set- = sieben.',
            avoid: 'Denk an „seis → sesenta“, „siete → setenta“.',
          },
        },
        {
          id: `${FIN}.10`,
          type: 'imageMatch',
          skills: ['vocabulary'],
          topicIds: ['es.g.hay'],
          difficulty: 1,
          instruction: 'Was gibt es im Café?',
          pairs: [
            { emoji: '☕', word: 'el café' },
            { emoji: '🍵', word: 'el té' },
            { emoji: '💧', word: 'el agua' },
            { emoji: '🍺', word: 'la cerveza' },
            { emoji: '🥛', word: 'la leche' },
          ],
          feedback: {
            rule: '`el agua` ist weiblich, bekommt aber im Singular den Artikel `el`, weil es mit betontem a- beginnt.',
            why: '`el té` (Tee) trägt einen Akzent, um es von `te` (dich/dir) zu unterscheiden.',
            avoid: 'Lerne Getränke direkt mit einer Bestellung: `Un café con leche, por favor.`',
          },
        },
        {
          id: `${FIN}.11`,
          type: 'mc',
          skills: ['vocabulary'],
          topicIds: ['es.g.questions'],
          difficulty: 1,
          prompt: 'Wie fragst du im Laden „Was kostet das?“',
          options: [
            { text: '¿Cuánto cuesta?' },
            { text: '¿Qué cuesta?', why: '`¿Qué?` fragt nach dem „Was“, nicht nach der Menge. Nach dem Preis fragt `¿Cuánto?`.' },
            { text: '¿Cuántos cuesta?', why: '`cuántos` (wie viele) passt nur vor Plural-Nomen, nicht zu einer Preisfrage.' },
            { text: '¿Cuánto es costa?', why: 'Die Verbform heißt `cuesta` (von costar) – ein `es` davor ist überflüssig.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Preis erfragen: `¿Cuánto cuesta?` (eine Sache) · `¿Cuánto cuestan?` (mehrere) · `¿Cuánto es?` (Gesamtbetrag).',
            why: 'Das deutsche „Was kostet …?“ verleitet zu `qué` – Spanisch fragt „Wie viel …?“.',
            avoid: 'Preis = Menge an Geld → `cuánto`.',
          },
        },
        {
          id: `${FIN}.12`,
          type: 'translate',
          skills: ['vocabulary', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Guten Tag! Einen Kaffee mit Milch, bitte.',
          answers: [
            'Buenos días. Un café con leche, por favor.',
            'Buenas tardes. Un café con leche, por favor.',
            'Hola, buenos días. Un café con leche, por favor.',
            'Hola, buenas tardes. Un café con leche, por favor.',
            'Buen día. Un café con leche, por favor.',
          ],
          feedback: {
            rule: '„Guten Tag“ = `buenos días` (vormittags) oder `buenas tardes` (nachmittags). Milchkaffee = `café con leche`; bitte = `por favor`.',
            why: '„mit“ heißt `con`; eine Übersetzung wie „café de leche“ ist falsch.',
            avoid: 'Lerne die Bestellung als festen Satz: `Un café con leche, por favor.`',
          },
        },
      ],
    },
    {
      title: 'Hören',
      skill: 'listening',
      exercises: [
        {
          id: `${FIN}.13`,
          type: 'listening',
          skills: ['listening'],
          topicIds: ['es.g.hay'],
          difficulty: 2,
          audio: 'Un café con leche y un agua, por favor.',
          question: 'Was bestellt die Person?',
          options: ['einen Milchkaffee und ein Wasser', 'einen Kaffee und eine Milch', 'zwei Milchkaffees', 'einen Tee und ein Wasser'],
          answer: 0,
          feedback: {
            rule: '`café con leche` = Milchkaffee, `un agua` = ein Wasser.',
            why: '`con leche` gehört zum Kaffee – es ist keine zweite Bestellung.',
            avoid: 'Achte auf `y` (und): Es trennt die einzelnen Bestellungen.',
          },
        },
        {
          id: `${FIN}.14`,
          type: 'listening',
          skills: ['listening'],
          topicIds: ['es.g.numbers'],
          difficulty: 2,
          audio: 'Son cuarenta y ocho euros.',
          question: 'Wie viel kostet es?',
          options: ['48 €', '58 €', '84 €', '18 €'],
          answer: 0,
          feedback: {
            rule: '`cuarenta y ocho` = 40 + 8 = 48. Zehner zuerst, dann `y`, dann Einer.',
            why: 'Im Deutschen hört man zuerst die Einer („acht-und-vierzig“) – im Spanischen umgekehrt. Daher die Verwechslung mit 84.',
            avoid: 'Schreib beim Hören zuerst die Zehnerziffer auf, dann die Einer.',
          },
        },
        {
          id: `${FIN}.15`,
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          audio: 'Vivimos en Sevilla.',
          answers: ['Vivimos en Sevilla.'],
          german: 'Wir wohnen in Sevilla.',
          feedback: {
            rule: '`b` und `v` klingen im Spanischen gleich – `vivimos` schreibt man mit v, weil es von `vivir` kommt.',
            why: 'Wer nach Gehör schreibt, landet schnell bei „bibimos“.',
            avoid: 'Leite die Schreibung vom Infinitiv ab: vivir → vivimos.',
          },
        },
        {
          id: `${FIN}.16`,
          type: 'minimalPair',
          skills: ['listening', 'pronunciation'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 2,
          instruction: 'Welches Wort hörst du?',
          options: ['caro', 'carro'],
          answer: 0,
          hint: '`caro` (teuer) hat ein einfaches r – ein einziger kurzer Zungenschlag. `carro` (Wagen) hat ein gerolltes rr.',
          feedback: {
            rule: 'r zwischen Vokalen = ein Schlag; rr = mehrere Schläge.',
            why: 'Das einfache r ist so kurz, dass es fast wie ein d klingt – das überrascht deutsche Ohren.',
            avoid: 'Hör auf die Länge des R-Lauts: kurz = caro, lang und schnurrend = carro.',
          },
        },
      ],
    },
    {
      title: 'Lesen & Schreiben',
      skill: 'reading',
      exercises: [
        {
          id: `${FIN}.17`,
          type: 'dialogue',
          skills: ['reading', 'grammar'],
          topicIds: ['es.g.numbers', 'es.g.ser'],
          difficulty: 2,
          instruction: 'Ergänze die Antwort des Kellners.',
          lines: [
            { speaker: 'Camarero', text: 'Buenas tardes. ¿Qué desea?', german: 'Guten Tag. Was möchten Sie?' },
            { speaker: 'Cliente', text: 'Un té y una botella de agua, por favor. ¿Cuánto es?', german: 'Einen Tee und eine Flasche Wasser, bitte. Was macht das?' },
            { speaker: 'Camarero', text: 'Son cuatro euros con cincuenta.', german: 'Das macht vier Euro fünfzig.' },
          ],
          gapIndex: 2,
          options: ['Son cuatro euros con cincuenta.', 'Es cuatro euros con cincuenta.', 'Hay cuatro euros con cincuenta.', 'Están cuatro euros con cincuenta.'],
          answer: 0,
          feedback: {
            rule: 'Preise im Plural mit **ser**: `Son cuatro euros.` (Nur bei einem Euro: `Es un euro.`)',
            why: '`hay` fragt nach Existenz, `están` nach dem Ort – beides passt nicht zu einem Betrag.',
            avoid: 'Beim Bezahlen: `Son …` + Betrag.',
          },
        },
        {
          id: `${FIN}.18`,
          type: 'situation',
          skills: ['reading', 'grammar'],
          topicIds: ['es.g.ser', 'es.g.present-regular'],
          difficulty: 2,
          scenario: 'Du bist neu im Sprachkurs und möchtest dich einer Mitschülerin vorstellen. Was sagst du?',
          options: [
            { text: 'Hola, me llamo Tom. Soy de Alemania.' },
            { text: 'Hola, soy llamo Tom. Estoy de Alemania.', why: '`soy llamo` vermischt zwei Strukturen; Herkunft braucht ser: `soy de`.' },
            { text: 'Hola, me llamo Tom. Estoy de Alemania.', why: 'Herkunft wird mit **ser** ausgedrückt: `Soy de Alemania.`' },
            { text: 'Hola, llamo Tom. Soy de Alemania.', why: 'Ohne `me` hieße `llamo` „ich rufe (an)“. Richtig: `me llamo`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Vorstellen: `Me llamo …` / `Soy …` + `Soy de …` (Herkunft).',
            why: 'Die typischen Fehler: `me` vergessen und Herkunft mit estar.',
            avoid: 'Lerne den Doppelsatz auswendig: `Me llamo … Soy de …`',
          },
        },
        {
          id: `${FIN}.19`,
          type: 'translate',
          skills: ['reading'],
          topicIds: ['es.g.ser-estar', 'es.g.adjectives'],
          difficulty: 2,
          direction: 'toGerman',
          source: 'La casa es grande y bonita, pero no está en el centro.',
          answers: [
            'Das Haus ist groß und schön, aber es ist nicht im Zentrum.',
            'Das Haus ist groß und schön, aber es liegt nicht im Zentrum.',
            'Das Haus ist groß und hübsch, aber es ist nicht im Zentrum.',
            'Das Haus ist groß und hübsch, aber es liegt nicht im Zentrum.',
            'Das Haus ist groß und schön, aber es liegt nicht in der Innenstadt.',
            'Das Haus ist groß und schön, aber es ist nicht in der Innenstadt.',
            'Das Haus ist groß und schön, liegt aber nicht im Zentrum.',
            'Das Haus ist groß und schön, aber nicht im Zentrum.',
          ],
          feedback: {
            rule: '`es grande y bonita` = Eigenschaften (ser); `no está en el centro` = Lage (estar).',
            why: 'Beide Verben werden mit „sein“ übersetzt – bei der Lage passt im Deutschen auch „liegen“.',
            avoid: 'Übersetze estar bei Orten ruhig mit „liegen“ oder „sich befinden“ – das klingt natürlicher.',
          },
        },
        {
          id: `${FIN}.20`,
          type: 'freeText',
          skills: ['writing', 'grammar'],
          topicIds: ['es.g.ser', 'es.g.present-regular'],
          difficulty: 2,
          prompt: 'Stell dich in 3–4 Sätzen vor: Name, Herkunft, Wohnort und Sprachen, die du sprichst.',
          requirements: [
            { pattern: '(me llamo|mi nombre es|\\bsoy (?!de\\b)[a-záéíóúñ])', hint: 'deinen Namen (me llamo …)' },
            { pattern: '\\bsoy de\\b', hint: 'deine Herkunft (soy de …)' },
            { pattern: '\\bviv(o|imos) en\\b', hint: 'deinen Wohnort (vivo en …)' },
            { pattern: '\\bhablo\\b', hint: 'eine Sprache (hablo …)' },
          ],
          samples: ['Hola, me llamo Laura. Soy de Alemania, pero vivo en Valencia. Hablo alemán, inglés y un poco de español.'],
          minWords: 12,
          feedback: {
            rule: 'Vorstellung: `me llamo` + `soy de` (ser) + `vivo en` (-ir-Verb) + `hablo` (-ar-Verb).',
            why: 'Häufig: `estoy de Alemania` oder `vivo in Berlín` (deutsches „in“ statt `en`).',
            avoid: 'Prüfe jede Präposition: Herkunft `de`, Wohnort `en`.',
          },
        },
      ],
    },
    {
      title: 'Sprechen',
      skill: 'speaking',
      exercises: [
        {
          id: `${FIN}.21`,
          type: 'speak',
          skills: ['pronunciation', 'speaking'],
          topicIds: ['es.g.questions'],
          difficulty: 1,
          text: '¿Cómo te llamas?',
          german: 'Wie heißt du?',
          phonetic: 'KO-mo te JA-mas',
          ipa: '[ˈko.mo te ˈʝa.mas]',
          pronItemId: 'es.p.into.como-te-llamas',
          feedback: {
            rule: 'Fragen mit Fragewort: Die Stimme fällt am Satzende leicht ab. `ll` klingt wie ein weiches deutsches j.',
            why: 'Deutschsprachige sprechen `ll` oft als „l“ aus – das ist ein ganz anderer Laut.',
            avoid: 'Denk bei `llamas` an „Jamas“ – mit weichem j wie in „ja“.',
          },
        },
        {
          id: `${FIN}.22`,
          type: 'speak',
          skills: ['pronunciation', 'speaking'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 2,
          text: 'El perro es grande.',
          german: 'Der Hund ist groß.',
          phonetic: 'el PE-rro es GRAN-de',
          ipa: '[el ˈpe.ro ez ˈɣɾan.de]',
          pronItemId: 'es.p.r.perro',
          feedback: {
            rule: '`rr` wird mit der Zungenspitze gerollt, das r in `grande` ist ein kurzer Schlag.',
            why: 'Das deutsche Rachen-R wird von der Spracherkennung oft nicht als spanisches r erkannt.',
            avoid: 'Zungenspitze hinter die oberen Schneidezähne, Luft darüber strömen lassen – übe im Aussprache-Labor.',
          },
        },
        {
          id: `${FIN}.23`,
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.ser', 'es.g.present-regular'],
          difficulty: 2,
          prompt: 'Stell dich laut vor: Name, Herkunft, Wohnort und eine Sprache, die du sprichst.',
          keywords: ['me llamo', 'soy', 'soy de', 'vivo en', 'hablo'],
          minMatch: 3,
          sample: 'Me llamo Jonas, soy de Alemania y vivo en Berlín. Hablo alemán y un poco de español.',
          feedback: {
            rule: 'Bausteine: `Me llamo …`, `Soy de …`, `Vivo en …`, `Hablo …`.',
            why: 'Fehlen Schlüsselwörter, wurden meist ganze Bausteine ausgelassen oder zu leise gesprochen.',
            avoid: 'Sprich in vier kurzen Sätzen – einer pro Baustein.',
          },
        },
        {
          id: `${FIN}.24`,
          type: 'speakFree',
          skills: ['speaking', 'vocabulary'],
          topicIds: ['es.g.hay', 'es.g.numbers'],
          difficulty: 2,
          prompt: 'Du bist im Café: Bestelle laut ein Getränk und frag, was es kostet.',
          keywords: ['por favor', 'cuánto', 'cuesta', 'café', 'agua', 'té', 'cerveza', 'quiero', 'quisiera'],
          minMatch: 3,
          sample: 'Hola, un café con leche, por favor. ¿Cuánto cuesta?',
          feedback: {
            rule: 'Bestellen: Getränk + `por favor`; Preis: `¿Cuánto cuesta?` / `¿Cuánto es?`',
            why: 'Wer nur das Getränk nennt, vergisst oft die Höflichkeitsformel oder die Preisfrage.',
            avoid: 'Merke die Reihenfolge: Gruß → Bestellung → por favor → Preisfrage.',
          },
        },
      ],
    },
  ],
};

// ───────────────────────── Stufe 0 – Endgegner ─────────────────────────
const BOSS = 'es.exam.s0.boss';

const boss: Exam = {
  id: BOSS,
  courseId: 'es',
  stageId: 'stage0',
  kind: 'boss',
  title: 'Endgegner: El Guardián de la Plaza',
  description:
    'Die Boss-Challenge von Stufe 0: gemischte, anspruchsvolle Aufgaben aus allen Kompetenzen – inklusive Hören und Sprechen. Du brauchst **70 %**, das großzügige Zeitlimit beträgt 25 Minuten.',
  passPct: 70,
  timeLimitSec: 1500,
  boss: {
    name: 'El Guardián de la Plaza',
    emoji: '🦁',
    intro:
      'Mitten auf der alten Plaza wacht ein steinerner Löwe: **El Guardián de la Plaza**. Seit Jahrhunderten lässt er nur Reisende in die Altstadt, die ihn höflich auf Spanisch begrüßen, von sich erzählen und seine Rätsel lösen.\nHeute öffnet er ein Auge und brummt: `¡Hola! ¿Empezamos?` – „Hallo! Wollen wir anfangen?“\nZeig ihm alles, was du in Stufe 0 gelernt hast.',
    defeat:
      'Der Guardián schließt langsam die Augen: `¡Casi! Pero todavía no.` – „Fast! Aber noch nicht.“\nKein Grund zur Sorge: Sieh dir die Erklärungen zu deinen Fehlern an, übe die schwachen Themen im Fehlerarchiv oder in der Wiederholung und fordere ihn erneut heraus. Er wartet geduldig auf dich.',
    victory:
      'Der steinerne Löwe erhebt sich, verneigt sich tief und gibt das Tor frei: `¡Felicidades! La ciudad es tuya.` – „Herzlichen Glückwunsch! Die Stadt gehört dir.“\nDu hast den Endgegner von Stufe 0 besiegt – ein großer Schritt in Richtung A1.',
  },
  sections: [
    {
      title: 'Der Gruß am Tor',
      skill: 'speaking',
      exercises: [
        {
          id: `${BOSS}.01`,
          type: 'speak',
          skills: ['speaking', 'pronunciation'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          instruction: 'Begrüße den Guardián höflich.',
          text: 'Buenas tardes, señor. ¿Cómo está usted?',
          german: 'Guten Tag, mein Herr. Wie geht es Ihnen?',
          phonetic: 'BUE-nas TAR-des, se-NJOR. KO-mo es-TA us-TED',
          ipa: '[ˈbwe.nas ˈtaɾ.ðes seˈɲoɾ ˈko.mo esˈta usˈteð]',
          feedback: {
            rule: 'Höflich: `señor` + `usted`. ñ = „nj“, d zwischen Vokalen und am Ende weich.',
            why: 'Das ñ in `señor` wird oft als einfaches n gesprochen – dann klingt es wie `senor`.',
            avoid: 'Sprich se-NJOR wie das „gn“ in „Champagner“.',
          },
        },
        {
          id: `${BOSS}.02`,
          type: 'situation',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ser', 'es.g.present-regular'],
          difficulty: 2,
          scenario: 'Der Guardián fragt: `¿De dónde eres y dónde vives?` Was antwortest du?',
          options: [
            { text: 'Soy de Alemania y vivo en Hamburgo.' },
            { text: 'Estoy de Alemania y vivo en Hamburgo.', why: 'Herkunft wird mit **ser** ausgedrückt: `soy de`.' },
            { text: 'Soy de Alemania y soy en Hamburgo.', why: 'Wohnen heißt `vivir`: `vivo en`. `soy en` ist falsch.' },
            { text: 'Soy Alemania y vivo Hamburgo.', why: 'Es fehlen die Präpositionen: `soy **de** Alemania`, `vivo **en** Hamburgo`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Herkunft: `ser de`; Wohnort: `vivir en`.',
            why: 'Die falschen Antworten verwechseln ser/estar oder lassen die Präpositionen weg.',
            avoid: 'Antworte mit denselben Verben wie die Frage: eres → soy, vives → vivo.',
          },
        },
        {
          id: `${BOSS}.03`,
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.ser', 'es.g.estar', 'es.g.present-regular'],
          difficulty: 3,
          prompt: 'Der Guardián will wissen, wer du bist. Erzähl laut: Name, Herkunft, Wohnort, Beruf oder Studium – und wie es dir heute geht.',
          keywords: ['me llamo', 'soy', 'soy de', 'vivo', 'estoy', 'trabajo', 'estudio', 'hablo'],
          minMatch: 4,
          sample: 'Me llamo Lena, soy de Alemania y vivo en Leipzig. Soy profesora y hoy estoy muy contenta.',
          feedback: {
            rule: 'Identität mit ser (`soy de`, `soy profesora`), Befinden mit estar (`estoy bien`), Tätigkeiten mit regelmäßigen Verben (`vivo`, `trabajo`).',
            why: 'Für die volle Punktzahl braucht es mindestens vier Bausteine – oft fehlt das Befinden mit estar.',
            avoid: 'Plane vorher fünf kurze Sätze und sprich sie ruhig nacheinander.',
          },
        },
      ],
    },
    {
      title: 'Die Rätsel des Wächters',
      skill: 'grammar',
      exercises: [
        {
          id: `${BOSS}.04`,
          type: 'cloze',
          skills: ['grammar'],
          topicIds: ['es.g.hay', 'es.g.ser-estar'],
          difficulty: 3,
          instruction: 'hay, ser oder estar? Setze die richtigen Formen ein.',
          sentence: 'En la plaza ___ una fuente. La fuente ___ muy antigua y ___ en el centro.',
          answers: [['hay'], ['es'], ['está']],
          bank: ['hay', 'es', 'está', 'son', 'están'],
          german: 'Auf dem Platz gibt es einen Brunnen. Der Brunnen ist sehr alt und steht in der Mitte.',
          feedback: {
            rule: 'Existenz (una fuente) → `hay`; Eigenschaft (antigua) → `es`; Lage (en el centro) → `está`.',
            why: 'Alle drei entsprechen im Deutschen „es gibt / ist / steht“ – Spanisch trennt Existenz, Eigenschaft und Ort streng.',
            avoid: 'Drei Fragen: Gibt es das? → hay. Wie ist es? → ser. Wo ist es? → estar.',
          },
        },
        {
          id: `${BOSS}.05`,
          type: 'fixError',
          skills: ['grammar'],
          topicIds: ['es.g.articles', 'es.g.gender-plural', 'es.g.ser'],
          difficulty: 3,
          instruction: 'In diesem Satz stecken zwei Fehler. Schreib ihn richtig.',
          sentence: 'Los chicas españolas es muy simpáticas.',
          answers: ['Las chicas españolas son muy simpáticas.'],
          german: 'Die spanischen Mädchen sind sehr nett.',
          feedback: {
            rule: 'Artikel passt sich an: `las chicas` (weiblich Plural); Verb passt sich an das Subjekt an: Plural → `son`.',
            why: '`los` ist maskulin, `es` ist Singular – beides passt nicht zu `chicas`.',
            avoid: 'Prüfe bei jedem Satz: Stimmen Artikel, Nomen, Adjektiv und Verb in Geschlecht und Zahl überein?',
          },
        },
        {
          id: `${BOSS}.06`,
          type: 'conjugate',
          skills: ['grammar'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          verb: 'aprender',
          tense: 'Präsens',
          person: 'nosotros',
          sentence: '___ español en la plaza.',
          answers: ['aprendemos', 'nosotros aprendemos', 'nosotras aprendemos'],
          feedback: {
            rule: '-er-Verben: -o, -es, -e, **-emos**, (-éis), -en → `aprendemos`.',
            why: '„aprendimos“ wäre die Vergangenheit bzw. das Muster der -ir-Verben.',
            avoid: 'Infinitiv-Vokal bei nosotros: aprend**e**r → aprend**e**mos.',
          },
        },
        {
          id: `${BOSS}.07`,
          type: 'order',
          skills: ['grammar'],
          topicIds: ['es.g.questions', 'es.g.estar'],
          difficulty: 3,
          instruction: 'Bilde die Frage „Wo sind Anas Bücher?“.',
          tokens: ['¿Dónde', 'están', 'los', 'libros', 'de', 'Ana?'],
          extra: ['son'],
          german: 'Wo sind Anas Bücher?',
          feedback: {
            rule: 'Fragewort + estar (Ort) + Subjekt. Besitz mit `de`: `los libros de Ana`.',
            why: 'Das deutsche Genitiv-s gibt es nicht; `son` passt nicht, weil nach dem Ort gefragt wird.',
            avoid: '„Anas Bücher“ = „die Bücher von Ana“ → `los libros de Ana`.',
          },
        },
        {
          id: `${BOSS}.08`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.gender-plural', 'es.g.adjectives'],
          difficulty: 2,
          prompt: 'Welche Form bedeutet „die großen Städte“?',
          options: [
            { text: 'las ciudades grandes' },
            { text: 'los ciudades grandes', why: '`ciudad` ist weiblich → `las`.' },
            { text: 'las ciudads grandes', why: 'Nomen auf Konsonant bilden den Plural mit **-es**: `ciudades`.' },
            { text: 'las ciudades grandas', why: '`grande` hat keine eigene weibliche Form – der Plural ist immer `grandes`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Plural: Vokal + -s, Konsonant + -es. Adjektive auf -e ändern sich nur in der Zahl: grande → grandes.',
            why: 'Jede falsche Option verletzt genau eine dieser Regeln.',
            avoid: 'Adjektive auf -e und auf Konsonant (grande, azul) haben für beide Geschlechter dieselbe Form.',
          },
        },
      ],
    },
    {
      title: 'Die Stimmen der Plaza',
      skill: 'listening',
      exercises: [
        {
          id: `${BOSS}.09`,
          type: 'listening',
          skills: ['listening'],
          topicIds: ['es.g.ser-estar', 'es.g.present-regular'],
          difficulty: 3,
          audio: 'Hola, soy Marta. Soy de México, pero ahora vivo en Madrid. Estoy un poco cansada porque trabajo mucho.',
          question: 'Welche Aussage stimmt?',
          options: [
            'Marta kommt aus Mexiko und lebt jetzt in Madrid.',
            'Marta kommt aus Madrid und lebt jetzt in Mexiko.',
            'Marta ist Mexikanerin und arbeitet wenig.',
            'Marta lebt in Mexiko und ist müde.',
          ],
          answer: 0,
          feedback: {
            rule: '`soy de México` = Herkunft; `ahora vivo en Madrid` = aktueller Wohnort; `trabajo mucho` = ich arbeite viel.',
            why: 'Die Ablenker vertauschen Herkunft und Wohnort oder drehen `mucho` um.',
            avoid: 'Achte auf Signalwörter: `pero ahora` (aber jetzt) leitet eine Veränderung ein.',
          },
        },
        {
          id: `${BOSS}.10`,
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.hay', 'es.g.numbers'],
          difficulty: 3,
          audio: 'Hay setenta y cinco personas en la plaza.',
          answers: ['Hay setenta y cinco personas en la plaza.', 'Hay 75 personas en la plaza.'],
          german: 'Es sind fünfundsiebzig Menschen auf dem Platz.',
          feedback: {
            rule: '`hay` beginnt mit stummem h. `setenta` (70) – nicht `sesenta` (60).',
            why: 'Das h hört man nicht und vergisst es leicht; set-/ses- klingen ähnlich.',
            avoid: 'hay = „es gibt“ immer mit h schreiben; siete → setenta.',
          },
        },
        {
          id: `${BOSS}.11`,
          type: 'minimalPair',
          skills: ['listening', 'pronunciation'],
          topicIds: ['es.g.stress'],
          difficulty: 3,
          instruction: 'Welches Wort hörst du? Achte auf die Betonung.',
          options: ['hablo', 'habló'],
          answer: 1,
          hint: '`hablo` (ich spreche) wird auf der ersten Silbe betont: HA-blo. `habló` (er/sie sprach) auf der letzten: ha-BLÓ – der Akzent zeigt es an.',
          feedback: {
            rule: 'Die Betonung kann im Spanischen die Bedeutung ändern; ein geschriebener Akzent markiert eine abweichende Betonung.',
            why: 'Deutschsprachige hören vor allem die Laute, weniger die Betonung – hier sind die Laute identisch.',
            avoid: 'Klatsche beim Hören die betonte Silbe mit: HA-blo oder ha-BLÓ?',
          },
        },
      ],
    },
    {
      title: 'Das letzte Tor',
      skill: 'reading',
      exercises: [
        {
          id: `${BOSS}.12`,
          type: 'dialogue',
          skills: ['reading', 'grammar'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          instruction: 'Antworte dem Guardián.',
          lines: [
            { speaker: 'El Guardián', text: '¿Hablas español?', german: 'Sprichst du Spanisch?' },
            { speaker: 'Du', text: 'Sí, hablo un poco de español.', german: 'Ja, ich spreche ein bisschen Spanisch.' },
            { speaker: 'El Guardián', text: '¡Perfecto! Tu español es muy bueno.', german: 'Perfekt! Dein Spanisch ist sehr gut.' },
          ],
          gapIndex: 1,
          options: ['Sí, hablo un poco de español.', 'Sí, hablas un poco de español.', 'Sí, estoy un poco español.', 'Sí, hablo un poco del español.'],
          answer: 0,
          feedback: {
            rule: 'Antwort in der ich-Form: `hablo`; „ein bisschen“ = `un poco de` + Sprache ohne Artikel.',
            why: '`hablas` ist die du-Form; `del español` setzt einen überflüssigen Artikel; estar passt nicht.',
            avoid: 'Frage mit -as (hablas) → Antwort mit -o (hablo).',
          },
        },
        {
          id: `${BOSS}.13`,
          type: 'situation',
          skills: ['reading', 'grammar'],
          topicIds: ['es.g.hay', 'es.g.estar'],
          difficulty: 3,
          scenario: 'Neben dem Tor ist ein Café. Du möchtest wissen, ob es Wasser gibt und wo die Toilette ist. Was fragst du?',
          options: [
            { text: '¿Hay agua? ¿Y dónde está el baño?' },
            { text: '¿Está agua? ¿Y dónde hay el baño?', why: 'Genau vertauscht: Existenz → `hay`, Ort einer bestimmten Sache → `está`.' },
            { text: '¿Es agua? ¿Y dónde es el baño?', why: 'ser fragt nach Identität, nicht nach Existenz oder Ort.' },
            { text: '¿Hay agua? ¿Y dónde hay el baño?', why: 'Vor bestimmten Dingen mit Artikel (`el baño`) steht nie `hay`, sondern `está`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`hay` + unbestimmte Sache (agua, un baño); `está` + bestimmte Sache (el baño).',
            why: 'Nach dem Ort einer bestimmten Sache fragt man immer mit `¿Dónde está …?`',
            avoid: 'Artikel el/la/los/las → estar. Kein Artikel, un/una oder Zahl → hay.',
          },
        },
        {
          id: `${BOSS}.14`,
          type: 'translate',
          skills: ['writing', 'grammar'],
          topicIds: ['es.g.estar', 'es.g.word-order-negation'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Wir sind nicht müde, wir sind zufrieden.',
          answers: [
            'No estamos cansados, estamos contentos.',
            'No estamos cansadas, estamos contentas.',
            'Nosotros no estamos cansados, estamos contentos.',
            'Nosotras no estamos cansadas, estamos contentas.',
            'No estamos cansados, estamos satisfechos.',
            'No estamos cansadas, estamos satisfechas.',
          ],
          feedback: {
            rule: 'Befinden → estar: `estamos`; Verneinung mit `no` vor dem Verb; Adjektive im Plural: `cansados`, `contentos`.',
            why: '`somos cansados` wäre eine Charaktereigenschaft; die Adjektive müssen zum „wir“ im Plural passen.',
            avoid: 'Bei Stimmungen und Zuständen: estar + Adjektiv mit passender Endung.',
          },
        },
      ],
    },
    {
      title: 'Der Abschied',
      skill: 'speaking',
      exercises: [
        {
          id: `${BOSS}.15`,
          type: 'speakFree',
          skills: ['speaking', 'vocabulary'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          prompt: 'Bedanke dich beim Guardián und verabschiede dich höflich für heute Abend.',
          keywords: ['gracias', 'muchas gracias', 'adiós', 'hasta luego', 'hasta mañana', 'hasta pronto', 'buenas noches'],
          minMatch: 2,
          sample: 'Muchas gracias, señor. ¡Buenas noches y hasta mañana!',
          feedback: {
            rule: 'Dank: `(muchas) gracias`; Abschied am Abend: `buenas noches`, `hasta mañana`, `adiós`.',
            why: 'Für die Aufgabe braucht es sowohl den Dank als auch einen Abschiedsgruß.',
            avoid: 'Kombiniere immer zwei Bausteine: Dank + Gruß.',
          },
        },
      ],
    },
  ],
};

// ───────────────────────── A1 – Kapiteltest „Mein Leben“ ─────────────────────────
const A1C1 = 'es.exam.a1.c1';

const a1c1: Exam = {
  id: A1C1,
  courseId: 'es',
  stageId: 'a1',
  kind: 'midterm',
  title: 'Kapiteltest: Mein Leben',
  description:
    'Prüft Kapitel 1 von A1: **tener** und Possessivbegleiter, **gustar**, Uhrzeit und reflexive Verben sowie Pläne mit **ir a** + Infinitiv. Du brauchst **60 %**.',
  passPct: 60,
  sections: [
    {
      title: 'Grammatik',
      skill: 'grammar',
      exercises: [
        {
          id: `${A1C1}.01`,
          type: 'mc',
          skills: ['grammar'],
          topicIds: ['es.g.tener', 'es.g.possessives'],
          difficulty: 1,
          prompt: 'Wie fragst du „Wie alt ist dein Vater?“',
          options: [
            { text: '¿Cuántos años tiene tu padre?' },
            { text: '¿Cuántos años es tu padre?', why: 'Das Alter drückt man mit **tener** aus.' },
            { text: '¿Cuántos años tienes tu padre?', why: '`tu padre` ist 3. Person → `tiene`, nicht `tienes`.' },
            { text: '¿Qué años tiene tu padre?', why: 'Nach einer Anzahl fragt man mit `cuántos`, nicht mit `qué`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Alter: `¿Cuántos años tiene …?` – tener in der Person des Subjekts.',
            why: 'Das deutsche „ist … alt“ verleitet zu ser.',
            avoid: 'Denk wörtlich: „Wie viele Jahre hat dein Vater?“',
          },
        },
        {
          id: `${A1C1}.02`,
          type: 'cloze',
          skills: ['grammar'],
          topicIds: ['es.g.possessives'],
          difficulty: 2,
          instruction: 'Setze „unsere“ und „meine“ in der richtigen Form ein.',
          sentence: '___ abuela vive en Toledo y ___ hermanos viven en Berlín.',
          answers: [['nuestra'], ['mis']],
          bank: ['nuestro', 'nuestra', 'mi', 'mis'],
          german: 'Unsere Großmutter wohnt in Toledo und meine Geschwister wohnen in Berlin.',
          feedback: {
            rule: '`nuestro` passt sich in Geschlecht und Zahl an (`nuestra abuela`), `mi` nur in der Zahl (`mis hermanos`).',
            why: '`abuela` ist weiblich → nuestra; `hermanos` ist Plural → mis.',
            avoid: 'Schau immer auf das Nomen dahinter, nie auf den Besitzer.',
          },
        },
        {
          id: `${A1C1}.03`,
          type: 'cloze',
          skills: ['grammar'],
          topicIds: ['es.g.gustar'],
          difficulty: 3,
          sentence: 'A mi madre le ___ los perros, pero a mí no me ___ nada.',
          answers: [['gustan', 'encantan'], ['gustan']],
          german: 'Meine Mutter mag Hunde, aber ich mag sie überhaupt nicht.',
          feedback: {
            rule: 'gustar richtet sich nach der Sache: `los perros` (Plural) → `gustan` – in beiden Satzteilen.',
            why: 'Im zweiten Teil ist `los perros` nicht mehr ausgesprochen, aber weiterhin gemeint – deshalb auch dort `gustan`.',
            avoid: 'Frag dich bei jeder gustar-Form: Was gefällt (nicht) – eine Sache oder mehrere?',
          },
        },
        {
          id: `${A1C1}.04`,
          type: 'conjugate',
          skills: ['grammar'],
          topicIds: ['es.g.reflexive'],
          difficulty: 2,
          verb: 'acostarse',
          tense: 'Präsens',
          person: 'yo',
          sentence: '___ a las once.',
          answers: ['me acuesto', 'yo me acuesto'],
          feedback: {
            rule: 'Reflexiv + Stammwechsel o → ue: `me acuesto`.',
            why: '„me acosto“ vergisst den Stammwechsel, „acuesto“ allein das Pronomen.',
            avoid: 'Lerne die Wendung als Ganzes: `me acuesto` – ich gehe ins Bett.',
          },
        },
        {
          id: `${A1C1}.05`,
          type: 'order',
          skills: ['grammar'],
          topicIds: ['es.g.ir-a', 'es.g.possessives'],
          difficulty: 2,
          instruction: 'Bilde die Frage „Was machen deine Eltern am Samstag?“.',
          tokens: ['¿Qué', 'van', 'a', 'hacer', 'tus', 'padres', 'el', 'sábado?'],
          alternatives: [['¿Qué', 'van', 'a', 'hacer', 'el', 'sábado', 'tus', 'padres?']],
          german: 'Was machen deine Eltern am Samstag?',
          feedback: {
            rule: 'Fragewort + ir + a + Infinitiv + Subjekt: `¿Qué van a hacer tus padres …?`',
            why: 'In Fragen mit Fragewort steht das Subjekt meist hinter dem Verb.',
            avoid: 'Der Block `van a hacer` bleibt zusammen.',
          },
        },
        {
          id: `${A1C1}.06`,
          type: 'fixError',
          skills: ['grammar'],
          topicIds: ['es.g.ir-a'],
          difficulty: 2,
          instruction: 'Im Satz steckt ein Fehler. Schreib ihn richtig.',
          sentence: 'Mañana vamos visitar a nuestros abuelos.',
          answers: ['Mañana vamos a visitar a nuestros abuelos.'],
          german: 'Morgen besuchen wir unsere Großeltern.',
          feedback: {
            rule: 'ir **a** + Infinitiv: `vamos a visitar`.',
            why: 'Das `a` nach ir ist Pflicht – ohne es ist der Satz ungrammatisch.',
            avoid: 'Nach voy/vas/va/vamos/van folgt immer zuerst `a`.',
          },
        },
      ],
    },
    {
      title: 'Hören',
      skill: 'listening',
      exercises: [
        {
          id: `${A1C1}.07`,
          type: 'listening',
          skills: ['listening'],
          topicIds: ['es.g.tener', 'es.g.reflexive', 'es.g.ir-a'],
          difficulty: 3,
          audio: 'Me llamo Diego y tengo treinta y cuatro años. Me levanto a las seis y media porque trabajo en un hospital. El sábado voy a ir al cine con mi hermana.',
          question: 'Was macht Diego am Samstag?',
          options: ['Er geht mit seiner Schwester ins Kino.', 'Er arbeitet im Krankenhaus.', 'Er steht um halb sieben auf.', 'Er besucht seinen Bruder.'],
          answer: 0,
          feedback: {
            rule: '`El sábado voy a ir al cine con mi hermana` = Am Samstag geht er mit seiner Schwester ins Kino.',
            why: 'Die anderen Aussagen stimmen teilweise für Diegos Alltag, beantworten aber nicht die Frage nach Samstag.',
            avoid: 'Hör gezielt auf das Signalwort der Frage – hier `el sábado`.',
          },
        },
        {
          id: `${A1C1}.08`,
          type: 'listening',
          skills: ['listening'],
          topicIds: ['es.g.reflexive'],
          difficulty: 2,
          audio: 'Son las ocho menos cuarto.',
          question: 'Wie spät ist es?',
          options: ['7:45', '8:15', '8:45', '7:15'],
          answer: 0,
          feedback: {
            rule: '`las ocho menos cuarto` = acht minus Viertel = 7:45.',
            why: '`menos` zieht ab; 8:15 wäre `las ocho y cuarto`.',
            avoid: 'y = plus, menos = minus – rechne einfach mit.',
          },
        },
      ],
    },
    {
      title: 'Schreiben',
      skill: 'writing',
      exercises: [
        {
          id: `${A1C1}.09`,
          type: 'translate',
          skills: ['writing', 'grammar'],
          topicIds: ['es.g.gustar'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Ich mag Bücher, aber meine Schwester liebt Filme.',
          answers: [
            'Me gustan los libros, pero a mi hermana le encantan las películas.',
            'A mí me gustan los libros, pero a mi hermana le encantan las películas.',
          ],
          feedback: {
            rule: 'Plural → `gustan` / `encantan`; andere Person: `a mi hermana le …`.',
            why: 'Häufig fehlt `le` nach `a mi hermana` oder es steht der Singular vor einem Plural-Nomen.',
            avoid: 'Bei jeder Person zwei Teile: `a + Person` und das passende Pronomen (le).',
          },
        },
        {
          id: `${A1C1}.10`,
          type: 'freeText',
          skills: ['writing', 'grammar'],
          topicIds: ['es.g.tener', 'es.g.gustar', 'es.g.reflexive', 'es.g.ir-a'],
          difficulty: 3,
          prompt: 'Schreib einer neuen Brieffreundin eine kurze Nachricht (4–6 Sätze): Stell deine Familie vor, nenne eine Vorliebe, beschreibe kurz deinen Morgen und einen Plan fürs Wochenende.',
          requirements: [
            { pattern: '\\bteng(o|emos)\\b', hint: 'tener (z. B. „tengo un hermano“ oder „tengo … años“)' },
            { pattern: '\\b(me|nos|le|les) (gusta|gustan|encanta|encantan)\\b', hint: 'eine Vorliebe mit gustar oder encantar' },
            { pattern: '\\bme (levanto|despierto|ducho|acuesto|lavo)\\b', hint: 'ein reflexives Verb (z. B. „me levanto“)' },
            { pattern: '\\b(voy|vamos) a \\w*(ar|er|ir)\\b', hint: 'einen Plan mit ir a + Infinitiv' },
          ],
          samples: [
            '¡Hola, Carmen! Me llamo Lukas y tengo veintinueve años. Tengo una hermana y un perro. Me gusta mucho cocinar. Me levanto a las siete y desayuno a las siete y media. El sábado voy a ir a la playa con mi hermana.',
          ],
          minWords: 25,
          feedback: {
            rule: 'Vier Strukturen: tener, gustar, reflexive Verben, ir a + Infinitiv.',
            why: 'Wird eine Anforderung nicht erkannt, fehlt meist die genaue Form (z. B. `levanto` ohne `me`).',
            avoid: 'Schreib für jede Anforderung zuerst einen eigenen Satz und verbinde sie danach.',
          },
        },
      ],
    },
    {
      title: 'Sprechen',
      skill: 'speaking',
      exercises: [
        {
          id: `${A1C1}.11`,
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.gustar', 'es.g.reflexive', 'es.g.ir-a'],
          difficulty: 3,
          prompt: 'Beschreibe laut deinen Alltag: Wann stehst du auf, was machst du gern und was hast du am Wochenende vor?',
          keywords: ['me levanto', 'me gusta', 'me gustan', 'me encanta', 'voy a', 'tengo', 'a las'],
          minMatch: 3,
          sample: 'Me levanto a las siete. Me gusta mucho leer y el sábado voy a visitar a mis padres.',
          feedback: {
            rule: 'Bausteine: `me levanto a las …`, `me gusta …`, `voy a …`.',
            why: 'Wurde zu wenig erkannt, fehlten meist ganze Bausteine oder das `me` wurde verschluckt.',
            avoid: 'Sprich drei Sätze – einen pro Baustein.',
          },
        },
      ],
    },
  ],
};

export const exams: Exam[] = [mid, final, boss, a1c1];
