import type { PlacementTest } from '../types';

export const placement: PlacementTest = {
  courseId: 'es',
  intro:
    'Du kannst schon etwas Spanisch? Dann finde in etwa **5 Minuten** heraus, wo du am besten einsteigst. Die Fragen werden nach und nach schwieriger – wenn du etwas nicht weißt, ist das völlig in Ordnung, genau dafür ist der Test da.\nDas Ergebnis ist ein **Vorschlag** für deinen Startpunkt. Dein Sprachniveau weist du später mit Prüfungen nach. Du kannst die Einstufung auch überspringen und ganz entspannt bei Stufe 0 beginnen.',
  questions: [
    // ───────── Stufe 0 ─────────
    {
      level: 'stage0',
      exercise: {
        id: 'es.pl.01',
        type: 'mc',
        skills: ['vocabulary'],
        topicIds: ['es.g.formality'],
        difficulty: 1,
        prompt: 'Wie sagst du „Guten Morgen“?',
        options: [
          { text: 'Buenos días' },
          { text: 'Buenas noches', why: '`Buenas noches` sagt man spätabends – „guten Abend / gute Nacht“.' },
          { text: 'Buenas tardes', why: '`Buenas tardes` gilt ab dem Mittagessen bis zum Abend.' },
          { text: 'Hasta luego', why: '`Hasta luego` ist eine Verabschiedung („bis später“).' },
        ],
        answer: 0,
        feedback: {
          rule: 'Begrüßung nach Tageszeit: buenos días – buenas tardes – buenas noches.',
          why: 'Nur `buenos días` ist maskulin (el día), die anderen beiden sind feminin (la tarde, la noche).',
          avoid: 'Lerne die drei Grüße zusammen mit der Uhrzeit.',
        },
      },
    },
    {
      level: 'stage0',
      exercise: {
        id: 'es.pl.02',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.ser'],
        difficulty: 1,
        prompt: '`Yo ___ de Alemania.`',
        options: [
          { text: 'soy' },
          { text: 'estoy', why: 'Herkunft drückt man mit **ser** aus, nicht mit estar.' },
          { text: 'es', why: '`es` ist er/sie/es – für „ich“ heißt es `soy`.' },
          { text: 'eres', why: '`eres` ist die du-Form.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Herkunft: `ser de` → `Soy de Alemania.`',
          why: 'Beide Verben heißen „sein“; die Herkunft gehört zur Identität → ser.',
          avoid: 'Woher? → ser de.',
        },
      },
    },
    {
      level: 'stage0',
      exercise: {
        id: 'es.pl.03',
        type: 'listening',
        skills: ['listening'],
        topicIds: ['es.g.numbers'],
        difficulty: 1,
        audio: 'Sesenta y ocho.',
        question: 'Welche Zahl hörst du?',
        options: ['68', '78', '86', '58'],
        answer: 0,
        feedback: {
          rule: '`sesenta` = 60, `setenta` = 70; `y ocho` = und acht → 68.',
          why: 'sesenta/setenta klingen ähnlich; außerdem nennt Spanisch zuerst die Zehner.',
          avoid: 'seis → sesenta, siete → setenta.',
        },
      },
    },
    {
      level: 'stage0',
      exercise: {
        id: 'es.pl.04',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.articles'],
        difficulty: 1,
        prompt: '`___ casa es grande.`',
        options: [
          { text: 'La' },
          { text: 'El', why: '`casa` endet auf -a und ist weiblich → `la`.' },
          { text: 'Los', why: '`los` ist maskulin Plural.' },
          { text: 'Unos', why: '`unos` ist maskulin Plural („einige“).' },
        ],
        answer: 0,
        feedback: {
          rule: 'Nomen auf -a sind meist weiblich: `la casa`.',
          why: 'Der Artikel richtet sich nach Geschlecht und Zahl des Nomens.',
          avoid: 'Lerne Nomen immer mit Artikel.',
        },
      },
    },
    {
      level: 'stage0',
      exercise: {
        id: 'es.pl.05',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.estar'],
        difficulty: 1,
        prompt: '„Wie geht es dir?“ – `¿Cómo ___?`',
        options: [
          { text: 'estás' },
          { text: 'eres', why: '`¿Cómo eres?` fragt nach dem Charakter („Wie bist du so?“).' },
          { text: 'está', why: '`está` ist die Form für usted/él/ella, nicht für du.' },
          { text: 'es', why: '`es` (ser) fragt nicht nach dem Befinden.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Befinden → estar: `¿Cómo estás?` (tú) / `¿Cómo está usted?`',
          why: 'ser beschreibt Eigenschaften, estar Zustände wie das Befinden.',
          avoid: 'Wie geht’s? → estar.',
        },
      },
    },
    {
      level: 'stage0',
      exercise: {
        id: 'es.pl.06',
        type: 'cloze',
        skills: ['grammar'],
        topicIds: ['es.g.present-regular'],
        difficulty: 1,
        instruction: 'Setze „hablar“ in der richtigen Form ein.',
        sentence: 'Nosotros ___ español.',
        answers: [['hablamos']],
        german: 'Wir sprechen Spanisch.',
        feedback: {
          rule: '-ar-Verben, nosotros: Endung `-amos` → `hablamos`.',
          why: '`hablan` wäre „sie sprechen“, `hablo` „ich spreche“.',
          avoid: 'nosotros-Formen enden immer auf -mos.',
        },
      },
    },
    // ───────── A1 ─────────
    {
      level: 'a1',
      exercise: {
        id: 'es.pl.07',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.tener'],
        difficulty: 2,
        prompt: '`Mi hermana ___ veinte años.`',
        options: [
          { text: 'tiene' },
          { text: 'es', why: 'Das Alter drückt man mit **tener** aus: „Sie hat zwanzig Jahre.“' },
          { text: 'está', why: 'estar steht für Ort und Befinden, nicht für das Alter.' },
          { text: 'tienes', why: '`tienes` ist die du-Form; `mi hermana` ist 3. Person.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Alter: `tener … años`.',
          why: 'Das deutsche „sie ist 20“ verleitet zu ser.',
          avoid: 'Denk wörtlich: „Sie hat 20 Jahre.“',
        },
      },
    },
    {
      level: 'a1',
      exercise: {
        id: 'es.pl.08',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.gustar'],
        difficulty: 2,
        prompt: '`Me ___ los perros.`',
        options: [
          { text: 'gustan' },
          { text: 'gusta', why: '`los perros` ist Plural – das Verb richtet sich nach der Sache.' },
          { text: 'gusto', why: '`gusto` hieße „ich gefalle“.' },
          { text: 'gustas', why: '`gustas` hieße „du gefällst“.' },
        ],
        answer: 0,
        feedback: {
          rule: 'gustar richtet sich nach dem, was gefällt: Plural → `gustan`.',
          why: 'Die Person steht als Pronomen davor (me), das Verb gehört zur Sache.',
          avoid: '„Mir gefallen die Hunde“ → gustan.',
        },
      },
    },
    {
      level: 'a1',
      exercise: {
        id: 'es.pl.09',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.reflexive'],
        difficulty: 2,
        prompt: '`Yo ___ levanto a las siete.`',
        options: [
          { text: 'me' },
          { text: 'se', why: '`se` gehört zu él/ella/usted und ellos/ustedes.' },
          { text: 'te', why: '`te` gehört zu tú.' },
          { text: 'mi', why: '`mi` ist der Begleiter „mein“, kein Reflexivpronomen.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Reflexive Verben: yo → `me levanto`.',
          why: 'Das Pronomen muss zur Person passen.',
          avoid: 'me – te – se – nos – os – se.',
        },
      },
    },
    {
      level: 'a1',
      exercise: {
        id: 'es.pl.10',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.ir-a'],
        difficulty: 2,
        prompt: 'Welcher Satz bedeutet „Morgen werde ich arbeiten“?',
        options: [
          { text: 'Mañana voy a trabajar.' },
          { text: 'Mañana voy trabajar.', why: 'Zwischen ir und Infinitiv fehlt das `a`.' },
          { text: 'Mañana voy a trabajo.', why: 'Nach `ir a` steht der Infinitiv: `trabajar`.' },
          { text: 'Mañana va a trabajar.', why: '`va` ist er/sie/usted.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Nahe Zukunft: ir + a + Infinitiv.',
          why: 'Jede falsche Option verletzt einen der drei Bausteine.',
          avoid: 'voy + a + -ar/-er/-ir.',
        },
      },
    },
    {
      level: 'a1',
      exercise: {
        id: 'es.pl.11',
        type: 'listening',
        skills: ['listening'],
        topicIds: ['es.g.numbers'],
        difficulty: 2,
        audio: 'Son las cuatro y media.',
        question: 'Wie spät ist es?',
        options: ['4:30', '3:30', '4:15', '5:30'],
        answer: 0,
        feedback: {
          rule: '`las cuatro y media` = vier und halb = 4:30.',
          why: 'Das deutsche „halb fünf“ zählt zur nächsten Stunde – Spanisch zur vergangenen.',
          avoid: 'y media = Stunde + 30 Minuten.',
        },
      },
    },
    {
      level: 'a1',
      exercise: {
        id: 'es.pl.12',
        type: 'mc',
        skills: ['grammar'],
        topicIds: ['es.g.possessives'],
        difficulty: 2,
        prompt: 'Wie heißt „unsere Eltern“?',
        options: [
          { text: 'nuestros padres' },
          { text: 'nuestras padres', why: '`los padres` ist maskulin.' },
          { text: 'nuestro padres', why: 'Vor einem Plural-Nomen braucht nuestro die Pluralendung.' },
          { text: 'sus padres', why: '`sus` heißt „seine / ihre / Ihre“.' },
        ],
        answer: 0,
        feedback: {
          rule: '`nuestro` passt sich in Geschlecht und Zahl an: `nuestros padres`.',
          why: 'Anders als mi/tu/su hat nuestro vier Formen.',
          avoid: 'Setze den Artikel ein: los padres → nuestros.',
        },
      },
    },
    // ───────── A2 ─────────
    {
      level: 'a2',
      exercise: {
        id: 'es.pl.13',
        type: 'mc',
        skills: ['grammar'],
        difficulty: 2,
        prompt: '`Ayer ___ (yo) con mi madre por teléfono.`',
        options: [
          { text: 'hablé' },
          { text: 'hablo', why: '`hablo` ist Präsens – `ayer` (gestern) verlangt eine Vergangenheitsform.' },
          { text: 'hablaré', why: '`hablaré` ist Futur.' },
          { text: 'hablado', why: '`hablado` ist das Partizip und braucht ein Hilfsverb (`he hablado`).' },
        ],
        answer: 0,
        feedback: {
          rule: 'Abgeschlossene Handlung zu einem bestimmten Zeitpunkt in der Vergangenheit (ayer) → pretérito indefinido: `hablé`.',
          why: 'Zeitangaben wie ayer, la semana pasada, en 2020 verlangen das Indefinido.',
          avoid: 'Merke die Endung -é für yo bei -ar-Verben: hablé, trabajé, viajé.',
        },
      },
    },
    {
      level: 'a2',
      exercise: {
        id: 'es.pl.14',
        type: 'mc',
        skills: ['grammar'],
        difficulty: 2,
        prompt: '„Siehst du das Buch?“ – „Ja, ich sehe es.“ `Sí, ___ veo.`',
        options: [
          { text: 'lo' },
          { text: 'le', why: '`le` ist das indirekte Objekt („ihm/ihr“). Für eine Sache als direktes Objekt steht `lo`.' },
          { text: 'la', why: '`el libro` ist maskulin → `lo`.' },
          { text: 'se', why: '`se` ist reflexiv oder ersetzt le vor lo/la.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Direktes Objektpronomen: lo (maskulin), la (feminin), los, las. Es steht vor dem konjugierten Verb.',
          why: '`el libro` ist maskulin Singular → `lo`.',
          avoid: 'Frag: Wen oder was? → lo/la. Wem? → le.',
        },
      },
    },
    {
      level: 'a2',
      exercise: {
        id: 'es.pl.15',
        type: 'mc',
        skills: ['grammar'],
        difficulty: 2,
        prompt: '„Madrid ist größer als Sevilla.“ `Madrid es ___ grande ___ Sevilla.`',
        options: [
          { text: 'más … que' },
          { text: 'más … como', why: '`como` benutzt man beim Gleichheitsvergleich: `tan grande como`.' },
          { text: 'tan … que', why: '`tan … que` heißt „so …, dass“ (eine Folge). „so groß wie“ wäre `tan grande como` – beides ist kein „größer als“.' },
          { text: 'mucho … de', why: 'Der Komparativ wird mit `más … que` gebildet.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Komparativ: `más` + Adjektiv + `que`; Gleichheit: `tan` + Adjektiv + `como`.',
          why: 'Das deutsche „als“ wird zu `que`, „wie“ zu `como`.',
          avoid: 'más → que, tan → como.',
        },
      },
    },
    {
      level: 'a2',
      exercise: {
        id: 'es.pl.16',
        type: 'mc',
        skills: ['grammar'],
        difficulty: 2,
        prompt: '`Mientras yo ___ la cena, sonó el teléfono.`',
        options: [
          { text: 'preparaba' },
          { text: 'preparé', why: 'Die Handlung lief gerade ab, als etwas anderes passierte – dafür steht das Imperfecto.' },
          { text: 'preparo', why: 'Präsens passt nicht zu `sonó` (Vergangenheit).' },
          { text: 'prepararé', why: 'Futur passt nicht in eine Erzählung über die Vergangenheit.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Imperfecto = laufende Hintergrundhandlung; Indefinido = neu eintretendes Ereignis (`sonó`).',
          why: '`mientras` (während) kündigt fast immer eine andauernde Handlung an.',
          avoid: 'Stell dir einen Film vor: Kulisse → Imperfecto, plötzliches Ereignis → Indefinido.',
        },
      },
    },
    // ───────── B1 ─────────
    {
      level: 'b1',
      exercise: {
        id: 'es.pl.17',
        type: 'mc',
        skills: ['grammar'],
        difficulty: 3,
        prompt: '`Espero que ___ (tú) bien.`',
        options: [
          { text: 'estés' },
          { text: 'estás', why: 'Nach Ausdrücken des Wünschens und Hoffens mit Subjektwechsel (`espero que …`) steht der Subjuntivo.' },
          { text: 'estarás', why: 'Futur steht nicht nach `espero que`.' },
          { text: 'estar', why: 'Der Infinitiv ginge nur ohne Subjektwechsel: `Espero estar bien.`' },
        ],
        answer: 0,
        feedback: {
          rule: 'Wunsch/Hoffnung + que + anderes Subjekt → presente de subjuntivo: `espero que estés`.',
          why: 'Das Deutsche hat hier keinen eigenen Modus – deshalb wirkt der Indikativ zunächst natürlich.',
          avoid: 'Signalwörter für den Subjuntivo: esperar que, querer que, ojalá.',
        },
      },
    },
    {
      level: 'b1',
      exercise: {
        id: 'es.pl.18',
        type: 'mc',
        skills: ['grammar'],
        difficulty: 3,
        prompt: '„Wenn ich mehr Zeit hätte, würde ich durch Südamerika reisen.“ `Si ___ más tiempo, viajaría por Sudamérica.`',
        options: [
          { text: 'tuviera' },
          { text: 'tengo', why: '`si tengo` beschreibt eine reale Bedingung und passt nicht zu `viajaría`.' },
          { text: 'tendría', why: 'Das Konditional steht im Hauptsatz, nie direkt nach `si`.' },
          { text: 'tenga', why: 'Nach `si` steht nie der presente de subjuntivo.' },
        ],
        answer: 0,
        feedback: {
          rule: 'Irrealer Bedingungssatz: `si` + imperfecto de subjuntivo, Hauptsatz im condicional.',
          why: 'Im Deutschen steht in beiden Teilen oft „würde“ – im Spanischen nie das Konditional nach si.',
          avoid: 'Merke das Paar: si tuviera … viajaría.',
        },
      },
    },
  ],
};
