import type { PronCategory, PronItem } from '../types';

/**
 * Aussprache-Labor Spanisch.
 * IPA: breite phonetische Umschrift mit den wichtigsten Allophonen ([β ð ɣ] zwischen Vokalen, [ɾ] vs. [r]).
 * Wo Spanien und Lateinamerika hörbar abweichen, stehen beide Umschriften bzw. ein variantNote.
 */
const item = (p: Omit<PronItem, 'courseId'>): PronItem => ({ courseId: 'es', ...p });

// ───────────────────────── Vokale ─────────────────────────
const vowels: PronItem[] = [
  item({
    id: 'es.p.vowels.mama',
    categoryId: 'es.pc.vowels',
    text: 'mamá',
    german: 'Mama',
    helper: 'ma-MA – beide a gleich hell und kurz',
    ipa: '[maˈma]',
    syllables: ['ma', 'má'],
    stress: 1,
    mouth: 'Mund weit öffnen, Zunge liegt flach und entspannt unten. Beide a klingen gleich hell – wie in „Mann“, nur etwas länger als ein deutsches kurzes a.',
    mistakes: [
      'Betonung auf der ersten Silbe („MA-ma“) – das wäre `mama` (Brust).',
      'Das letzte a abschwächen oder verschlucken.',
    ],
    tips: ['Klatsche beim Sprechen auf die zweite Silbe: ma-MÁ.', 'Beide Silben gleich deutlich, nur die zweite lauter.'],
    issueCodes: ['vowels', 'stress'],
    level: 1,
  }),
  item({
    id: 'es.p.vowels.pelo',
    categoryId: 'es.pc.vowels',
    text: 'pelo',
    german: 'Haar',
    helper: 'PE-lo – e zwischen „See“ und „Bett“, o zwischen „Boot“ und „Post“',
    ipa: '[ˈpe.lo]',
    syllables: ['pe', 'lo'],
    stress: 0,
    mouth: 'Beim e sind die Lippen leicht gespreizt, der Mund halb offen. Beim o runden sich die Lippen – aber nicht so stark wie beim deutschen „oh“.',
    mistakes: [
      'Das e zu geschlossen wie in „See“ (klingt dann fast wie `pilo`).',
      'Das End-o zu einem dumpfen „e“ oder „u“ abschwächen.',
      'Das p stark behauchen („Phelo“).',
    ],
    tips: [
      'Spanische Vokale liegen genau in der Mitte zwischen den deutschen langen und kurzen Vokalen.',
      'p ohne Hauchen: Halte ein Blatt Papier vor den Mund – es sollte sich kaum bewegen.',
    ],
    issueCodes: ['vowels'],
    level: 1,
  }),
  item({
    id: 'es.p.vowels.libro',
    categoryId: 'es.pc.vowels',
    text: 'libro',
    german: 'Buch',
    helper: 'LI-bro – kurzes, klares i; b ganz weich; r nur einmal antippen',
    ipa: '[ˈli.βɾo]',
    syllables: ['li', 'bro'],
    stress: 0,
    mouth: 'i mit breit gezogenen Lippen wie beim Lächeln. Für das b schließen sich die Lippen nicht ganz – sie nähern sich nur. Die Zungenspitze tippt für das r einmal kurz hinter die oberen Schneidezähne.',
    mistakes: [
      'Das i zu kurz und offen wie in „Mitte“ (klingt nach `lebro`).',
      'Hartes deutsches b und Zäpfchen-r („Libbro“ mit Rachen-R).',
    ],
    tips: ['Denk an „Lido“, nur mit br: „LI-bro“.', 'Das r im br ist nur ein winziger Zungenschlag, wie das tt in amerikanisch „better“.'],
    issueCodes: ['vowels', 'b-v', 'r'],
    level: 1,
  }),
  item({
    id: 'es.p.vowels.todo',
    categoryId: 'es.pc.vowels',
    text: 'todo',
    german: 'alles',
    helper: 'TO-do – zwei gleiche o; das d ganz weich wie englisch „th“ in „this“',
    ipa: '[ˈto.ðo]',
    syllables: ['to', 'do'],
    stress: 0,
    mouth: 'Lippen leicht gerundet, beide o gleich. Beim d berührt die Zungenspitze nur leicht die Unterkante der oberen Zähne – ein weicher, summender Laut.',
    mistakes: [
      'Das zweite o abschwächen („TO-de“).',
      'Hartes deutsches d zwischen den Vokalen.',
      'Das t behauchen.',
    ],
    tips: ['Zwischen zwei Vokalen wird d im Spanischen immer weich.', 'Sprich es langsam: „to – ðo“, dann schneller.'],
    issueCodes: ['vowels'],
    level: 1,
  }),
  item({
    id: 'es.p.vowels.luna',
    categoryId: 'es.pc.vowels',
    text: 'luna',
    german: 'Mond',
    helper: 'LU-na – u wie in „Mut“, aber kürzer',
    ipa: '[ˈlu.na]',
    syllables: ['lu', 'na'],
    stress: 0,
    mouth: 'Für das u die Lippen deutlich runden und nach vorn schieben. Das a am Ende mit offenem Mund, nicht verschlucken.',
    mistakes: ['Das u zu offen wie in „Mutter“ (klingt nach `lona`).', 'Das End-a zu einem „e“ abschwächen („Lune“).'],
    tips: ['Stell dir vor, du pustest eine Kerze aus – so rund sind die Lippen beim u.'],
    issueCodes: ['vowels'],
    level: 1,
  }),
  item({
    id: 'es.p.vowels.euro',
    categoryId: 'es.pc.vowels',
    text: 'euro',
    german: 'Euro',
    helper: 'E-u-ro – e und u getrennt hörbar, NICHT „Oiro“',
    ipa: '[ˈeu̯.ɾo]',
    syllables: ['eu', 'ro'],
    stress: 0,
    mouth: 'Mit gespreizten Lippen beim e beginnen und in einer Bewegung zu gerundeten Lippen beim u gleiten. Danach tippt die Zunge einmal für das r.',
    mistakes: [
      'Deutsches „Oiro“ – im Spanischen hört man ein echtes e und ein echtes u.',
      'Rachen-R statt Zungen-R.',
    ],
    tips: ['Sprich zuerst „e – u“ langsam getrennt, dann immer schneller zusammen.', 'Spanisch liest jeden Vokal so, wie er geschrieben ist.'],
    issueCodes: ['vowels', 'r'],
    level: 1,
  }),
];

// ───────────────────────── R / RR ─────────────────────────
const rr: PronItem[] = [
  item({
    id: 'es.p.r.pero',
    categoryId: 'es.pc.r',
    text: 'pero',
    german: 'aber',
    helper: 'PE-ro – das r ist ein einziger kurzer Zungenschlag',
    ipa: '[ˈpe.ɾo]',
    syllables: ['pe', 'ro'],
    stress: 0,
    mouth: 'Die Zungenspitze tippt ein einziges Mal blitzschnell an den Zahndamm hinter den oberen Schneidezähnen – wie das schnelle „tt“ im amerikanischen „better“ oder „water“.',
    mistakes: [
      'Rachen-R wie im Deutschen („Pe-Ro“ mit Gurgeln).',
      'Das r rollen – dann klingt es wie `perro` (Hund).',
    ],
    tips: [
      'Sag schnell hintereinander „e-de, e-de, e-de“ – das flüchtige d wird dabei fast von selbst zum spanischen r.',
      'Das einfache r ist kürzer als ein d.',
    ],
    issueCodes: ['r'],
    level: 1,
  }),
  item({
    id: 'es.p.r.perro',
    categoryId: 'es.pc.r',
    text: 'perro',
    german: 'Hund',
    helper: 'PE-rrro – Zungenspitze mehrmals flattern lassen',
    ipa: '[ˈpe.ro]',
    syllables: ['pe', 'rro'],
    stress: 0,
    mouth: 'Zungenspitze locker an den Zahndamm legen, die Zunge seitlich an den oberen Backenzähnen abstützen und kräftig Luft darüber blasen, sodass die Spitze mehrmals (2–4 Schläge) flattert. Der Kiefer bleibt ruhig.',
    mistakes: [
      'Nur ein Schlag – dann versteht man `pero` (aber).',
      'Rachen-R oder Zäpfchen-R (klingt französisch/deutsch).',
      'Zu viel Spannung in der Zunge – dann flattert sie nicht.',
    ],
    tips: [
      'Übe mit „tr“ und „dr“: Sag schnell „drrr“ wie ein Motor – die Zunge startet leichter aus dem d.',
      'Brummen wie ein Motorrad („brrrm“) mit der Zungenspitze statt den Lippen.',
      'Übergangslösung: Ein kräftig verlängertes, geschlagenes r wird verstanden – das Rollen kommt mit Übung.',
    ],
    issueCodes: ['rr'],
    level: 2,
  }),
  item({
    id: 'es.p.r.caro',
    categoryId: 'es.pc.r',
    text: 'caro',
    german: 'teuer',
    helper: 'KA-ro – ein kurzer Zungenschlag',
    ipa: '[ˈka.ɾo]',
    syllables: ['ca', 'ro'],
    stress: 0,
    mouth: 'k ohne Hauch, dann Mund offen für das a, Zungenspitze tippt einmal kurz hinter die oberen Zähne, Lippen runden sich für das o.',
    mistakes: ['Behauchtes k („Kharo“).', 'Gerolltes r – dann heißt es `carro`.', 'Rachen-R.'],
    tips: ['Stell dir „Kado“ mit einem superkurzen d vor.', 'Kontrast üben: caro – carro – caro.'],
    issueCodes: ['r'],
    level: 1,
  }),
  item({
    id: 'es.p.r.carro',
    categoryId: 'es.pc.r',
    text: 'carro',
    german: 'Karren, Wagen (Lateinamerika: Auto)',
    helper: 'KA-rrro – mehrere Zungenschläge',
    ipa: '[ˈka.ro]',
    syllables: ['ca', 'rro'],
    stress: 0,
    mouth: 'Wie bei `perro`: Zungenspitze locker an den Zahndamm, kräftiger Luftstrom, die Spitze vibriert mehrmals.',
    mistakes: ['Nur ein Schlag – man hört `caro` (teuer).', 'Rachen-R.'],
    tips: ['Halte das rr bewusst etwas länger als nötig.', 'Minimalpaar laut üben: „Es caro.“ – „Es un carro.“'],
    issueCodes: ['rr'],
    variantNotes: [
      { variant: 'es-LA', note: 'In weiten Teilen Lateinamerikas ist `carro` das normale Wort für „Auto“.' },
      { variant: 'es-ES', note: 'In Spanien sagt man für „Auto“ `coche`; `carro` ist dort eher ein Karren oder Einkaufswagen.' },
    ],
    level: 2,
  }),
  item({
    id: 'es.p.r.rosa',
    categoryId: 'es.pc.r',
    text: 'rosa',
    german: 'Rose; rosa',
    helper: 'RRRO-ßa – r am Wortanfang wird gerollt; s stimmlos',
    ipa: '[ˈro.sa]',
    syllables: ['ro', 'sa'],
    stress: 0,
    mouth: 'Direkt mit flatternder Zungenspitze starten – ohne Vorlaut. Das s ist scharf und stimmlos wie „ß“.',
    mistakes: [
      'Anfangs-r nur einmal schlagen – am Wortanfang wird r immer gerollt, obwohl man nur ein r schreibt.',
      'Stimmhaftes s wie in deutsch „Rose“.',
    ],
    tips: ['Setze ein unhörbares „d“ davor: „(d)rrrosa“ hilft beim Start.', 'Merke: r am Wortanfang und nach n, l, s klingt wie rr.'],
    issueCodes: ['rr'],
    level: 2,
  }),
  item({
    id: 'es.p.r.tres',
    categoryId: 'es.pc.r',
    text: 'tres',
    german: 'drei',
    helper: 'TRES – t + kurzer Zungenschlag, s stimmlos',
    ipa: '[ˈtɾes]',
    syllables: ['tres'],
    stress: 0,
    mouth: 'Zunge für das t an die oberen Zähne, dann direkt einmal schnell antippen für das r. Keine Pause, kein Vokal dazwischen.',
    mistakes: ['Rachen-R („Tʁes“).', 'Einen Vokal einschieben („te-res“).', 'Stimmhaftes s am Ende.'],
    tips: ['Das t schiebt die Zunge schon in die richtige Position – einfach „weiterschnalzen“.'],
    issueCodes: ['r'],
    level: 2,
  }),
  item({
    id: 'es.p.r.comer',
    categoryId: 'es.pc.r',
    text: 'comer',
    german: 'essen',
    helper: 'ko-MER – r am Ende wirklich sprechen, nicht „ko-mäa“',
    ipa: '[koˈmeɾ]',
    syllables: ['co', 'mer'],
    stress: 1,
    mouth: 'Zweite Silbe betont. Am Ende tippt die Zungenspitze hörbar an den Zahndamm – das r darf nicht zu einem „a“ werden.',
    mistakes: ['Das End-r vokalisieren wie im Deutschen („Kommaa“).', 'Betonung auf der ersten Silbe.'],
    tips: ['Alle Infinitive enden auf r – übe gleich mit: hablar, comer, vivir.', 'Das End-r darf ruhig kräftig sein – manche rollen es sogar leicht.'],
    issueCodes: ['r', 'stress'],
    level: 2,
  }),
  item({
    id: 'es.p.r.ramon-corre',
    categoryId: 'es.pc.r',
    text: 'Ramón corre rápido con el perro.',
    german: 'Ramón rennt schnell mit dem Hund.',
    helper: 'rrra-MON KO-rrre RRRA-pi-do kon el PE-rrro',
    ipa: '[raˈmon ˈko.re ˈra.pi.ðo kon el ˈpe.ro]',
    syllables: ['Ra', 'món', 'co', 'rre', 'rá', 'pi', 'do', 'con', 'el', 'pe', 'rro'],
    stress: 9,
    mouth: 'Vier gerollte r in einem Satz: am Wortanfang (Ramón, rápido) und bei rr (corre, perro). Zwischen den r-Lauten Zunge locker lassen.',
    mistakes: ['Nur die rr-Schreibungen rollen und das Anfangs-r vergessen.', 'Aus Anstrengung alle Vokale verkürzen.'],
    tips: ['Erst langsam Wort für Wort, dann in normalem Tempo.', 'Lieber etwas langsamer und dafür jedes rr sauber.'],
    issueCodes: ['rr', 'r'],
    level: 3,
  }),
];

// ───────────────────────── J / G ─────────────────────────
const jg: PronItem[] = [
  item({
    id: 'es.p.j.jamon',
    categoryId: 'es.pc.j-g',
    text: 'jamón',
    german: 'Schinken',
    helper: 'cha-MON – ch wie in „Bach“',
    ipa: '[xaˈmon]',
    syllables: ['ja', 'món'],
    stress: 1,
    mouth: 'Hinterer Zungenrücken nähert sich dem weichen Gaumen, die Luft reibt hörbar hindurch – genau wie beim deutschen „ach“.',
    mistakes: ['Deutsches j wie in „ja“ („Jamon“).', 'Englisches j wie in „John“.', 'Betonung auf der ersten Silbe.'],
    tips: ['Sag „Bach“ und halte das ch – dann hänge „-amón“ an.'],
    issueCodes: ['j', 'stress'],
    variantNotes: [
      { variant: 'es-ES', note: 'In Nord- und Zentralspanien ist das j oft besonders kräftig und kratzig.' },
      { variant: 'es-LA', note: 'In der Karibik, Kolumbien und Mittelamerika klingt j oft nur wie ein gehauchtes deutsches h: „ha-MON“.' },
    ],
    level: 1,
  }),
  item({
    id: 'es.p.j.gente',
    categoryId: 'es.pc.j-g',
    text: 'gente',
    german: 'Leute',
    helper: 'CHEN-te – g vor e klingt wie „ch“ in „Bach“',
    ipa: '[ˈxen.te]',
    syllables: ['gen', 'te'],
    stress: 0,
    mouth: 'Wie beim j: Reibelaut hinten im Mund. Das e danach ist klar und halboffen, das End-e wird nicht verschluckt.',
    mistakes: ['Hartes g wie in „Gent“.', 'Weiches j wie in „Jens“.', 'End-e als dumpfes „ə“.'],
    tips: ['Regel: g + e/i = ch-Laut, g + a/o/u = hartes g.'],
    issueCodes: ['g', 'j'],
    level: 2,
  }),
  item({
    id: 'es.p.j.gato',
    categoryId: 'es.pc.j-g',
    text: 'gato',
    german: 'Katze, Kater',
    helper: 'GA-to – hartes g, t ohne Hauch',
    ipa: '[ˈɡa.to]',
    syllables: ['ga', 'to'],
    stress: 0,
    mouth: 'Hinterer Zungenrücken schließt kurz am weichen Gaumen (wie deutsches g), dann offen für das a. Das t entsteht an den Zähnen, ohne Luftstoß.',
    mistakes: ['Behauchtes t („Gatho“).', 'Kurzes, offenes a wie in „Gatter“ – das spanische a ist etwas voller.'],
    tips: ['Zwischen Vokalen (z. B. `el gato`) wird das g weicher: [el ˈɣa.to] – die Zunge schließt nicht ganz.'],
    issueCodes: ['g'],
    level: 1,
  }),
  item({
    id: 'es.p.j.guitarra',
    categoryId: 'es.pc.j-g',
    text: 'guitarra',
    german: 'Gitarre',
    helper: 'gi-TA-rrra – u stumm, rr gerollt',
    ipa: '[ɡiˈta.ra]',
    syllables: ['gui', 'ta', 'rra'],
    stress: 1,
    mouth: 'gui wie „gi“ – das u bleibt stumm. Zweite Silbe betont, am Ende mehrere Zungenschläge für das rr.',
    mistakes: ['Das u sprechen („gu-i-tarra“).', 'Einfaches r statt rr.', 'Betonung auf der letzten Silbe („gi-ta-RRA“) – betont wird die mittlere Silbe.'],
    tips: ['gue/gui schreiben – g hart sprechen, u vergessen.'],
    issueCodes: ['g', 'rr'],
    level: 2,
  }),
  item({
    id: 'es.p.j.julio',
    categoryId: 'es.pc.j-g',
    text: 'julio',
    german: 'Juli',
    helper: 'CHU-ljo – ch wie in „Bach“, „lio“ als eine Silbe',
    ipa: '[ˈxu.ljo]',
    syllables: ['ju', 'lio'],
    stress: 0,
    mouth: 'Reibelaut hinten im Mund, dann Lippen rund für das u. „lio“ in einem Zug: das i ist nur ein kurzer Gleitlaut.',
    mistakes: ['Deutsches j („Juli-o“).', '„li-o“ als zwei Silben mit Betonung auf dem i.'],
    tips: ['Die Monatsnamen schreibt man klein: `julio`, `junio`.'],
    issueCodes: ['j'],
    level: 1,
  }),
];

// ───────────────────────── LL / Y ─────────────────────────
const lly: PronItem[] = [
  item({
    id: 'es.p.ll.llamo',
    categoryId: 'es.pc.ll-y',
    text: 'me llamo',
    german: 'ich heiße',
    helper: 'me JA-mo – ll klingt wie deutsches j',
    ipa: '[me ˈʝa.mo]',
    syllables: ['me', 'lla', 'mo'],
    stress: 1,
    mouth: 'Zungenrücken hebt sich zum harten Gaumen wie beim deutschen j in „ja“ – eventuell mit etwas mehr Reibung.',
    mistakes: ['Zwei l sprechen („lamo“ / „l-lamo“).', 'Wie „lj“ in „Ljubljana“ – das ist veraltet bzw. regional.'],
    tips: ['Denk einfach „me jamo“.'],
    issueCodes: ['ll-y'],
    variantNotes: [
      { variant: 'es-LA', note: 'In Argentinien und Uruguay klingt ll/y wie „sch“: „me SCHA-mo“ ([ˈʃa.mo]). Das ist dort Standard.' },
      { variant: 'es-ES', note: 'In ganz Spanien ist heute der j-Laut üblich (yeísmo); nur wenige ältere Sprecher unterscheiden noch ein „lj“.' },
    ],
    level: 1,
  }),
  item({
    id: 'es.p.ll.calle',
    categoryId: 'es.pc.ll-y',
    text: 'calle',
    german: 'Straße',
    helper: 'KA-je – ll wie j, End-e klar',
    ipa: '[ˈka.ʝe]',
    syllables: ['ca', 'lle'],
    stress: 0,
    mouth: 'Nach dem offenen a hebt sich der Zungenrücken zum j-Laut, das e am Ende mit leicht gespreizten Lippen.',
    mistakes: ['„Kalle“ wie der deutsche Vorname.', 'End-e verschlucken („Kaj“).'],
    tips: ['ll ist ein eigener Laut – nie wie zwei l.'],
    issueCodes: ['ll-y'],
    variantNotes: [{ variant: 'es-LA', note: 'Rioplatense (Buenos Aires, Montevideo): „KA-sche“ ([ˈka.ʃe]).' }],
    level: 1,
  }),
  item({
    id: 'es.p.ll.yo',
    categoryId: 'es.pc.ll-y',
    text: 'yo',
    german: 'ich',
    helper: 'JO – wie deutsch „jo“, etwas mehr Reibung',
    ipa: '[ʝo]',
    syllables: ['yo'],
    stress: 0,
    mouth: 'Zungenrücken nah am harten Gaumen; mit Nachdruck gesprochen kann ein leichtes „dj“ entstehen ([ɟʝo]).',
    mistakes: ['Wie englisch „yo“ mit Gleitlaut ohne Reibung – das geht, klingt aber schwach.', 'Als „i-o“ in zwei Silben.'],
    tips: ['Sag „jo!“ wie im Norddeutschen – das passt sehr gut.'],
    issueCodes: ['ll-y'],
    variantNotes: [{ variant: 'es-LA', note: 'Rioplatense: „scho“ ([ʃo]).' }],
    level: 1,
  }),
  item({
    id: 'es.p.ll.playa',
    categoryId: 'es.pc.ll-y',
    text: 'playa',
    german: 'Strand',
    helper: 'PLA-ja – pl ohne Vokal dazwischen',
    ipa: '[ˈpla.ʝa]',
    syllables: ['pla', 'ya'],
    stress: 0,
    mouth: 'p und l direkt verbinden, dann offenes a, der Zungenrücken hebt sich zum j, zweites a wieder offen.',
    mistakes: ['Behauchtes p.', 'y als i („Pla-i-a“).'],
    tips: ['Beide a gleich klingen lassen.'],
    issueCodes: ['ll-y'],
    variantNotes: [{ variant: 'es-LA', note: 'Rioplatense: „PLA-scha“.' }],
    level: 2,
  }),
];

// ───────────────────────── B / V ─────────────────────────
const bv: PronItem[] = [
  item({
    id: 'es.p.bv.vaca',
    categoryId: 'es.pc.b-v',
    text: 'vaca',
    german: 'Kuh',
    helper: 'BA-ka – v klingt wie b, nie wie „w“ oder „f“',
    ipa: '[ˈba.ka]',
    syllables: ['va', 'ca'],
    stress: 0,
    mouth: 'Am Wortanfang schließen beide Lippen wie bei b. Die oberen Zähne berühren die Unterlippe NICHT.',
    mistakes: ['Deutsches w („Waka“).', 'Englisches v mit Zähnen auf der Unterlippe.', 'Deutsches f.'],
    tips: ['Schreib „v“, denk „b“.', 'Kontrollier im Spiegel: Bei v sind die Zähne nicht zu sehen.'],
    issueCodes: ['b-v'],
    level: 1,
  }),
  item({
    id: 'es.p.bv.beber',
    categoryId: 'es.pc.b-v',
    text: 'beber',
    german: 'trinken',
    helper: 'be-BER – erstes b fest, zweites b ganz weich',
    ipa: '[beˈβeɾ]',
    syllables: ['be', 'ber'],
    stress: 1,
    mouth: 'Erstes b mit geschlossenen Lippen. Zwischen den Vokalen nähern sich die Lippen nur an, ohne sich zu schließen – ein weicher Reibelaut. Am Ende ein kurzer Zungenschlag für das r.',
    mistakes: ['Beide b gleich hart.', 'Das zweite b als w („be-WER“).', 'Das End-r zu „a“ vokalisieren.'],
    tips: ['Stell dir vor, du bläst leicht durch fast geschlossene Lippen.'],
    issueCodes: ['b-v', 'r'],
    level: 2,
  }),
  item({
    id: 'es.p.bv.vivir',
    categoryId: 'es.pc.b-v',
    text: 'vivir',
    german: 'leben, wohnen',
    helper: 'bi-BIR – beide v wie b, das zweite weich',
    ipa: '[biˈβiɾ]',
    syllables: ['vi', 'vir'],
    stress: 1,
    mouth: 'Erstes v: Lippen schließen. Zweites v (zwischen Vokalen): Lippen nur annähern. Lippen beim i breit, Betonung auf der zweiten Silbe.',
    mistakes: ['„wi-WIR“ wie im Deutschen.', 'Betonung auf der ersten Silbe.'],
    tips: ['Merksatz: „b und v sind Zwillinge.“'],
    issueCodes: ['b-v', 'r'],
    level: 2,
  }),
  item({
    id: 'es.p.bv.uva',
    categoryId: 'es.pc.b-v',
    text: 'uva',
    german: 'Traube',
    helper: 'U-ba – v ganz weich zwischen den Vokalen',
    ipa: '[ˈu.βa]',
    syllables: ['u', 'va'],
    stress: 0,
    mouth: 'Aus dem runden u gleiten die Lippen nur leicht zusammen (nicht schließen) und öffnen sich dann weit für das a.',
    mistakes: ['„U-wa“ mit deutschem w.', 'Hartes, geschlossenes b.'],
    tips: ['Der weiche Laut liegt zwischen b und w – aber mit beiden Lippen, ohne Zähne.'],
    issueCodes: ['b-v', 'vowels'],
    level: 2,
  }),
];

// ───────────────────────── C / Z / S ─────────────────────────
const cz: PronItem[] = [
  item({
    id: 'es.p.cz.gracias',
    categoryId: 'es.pc.c-z',
    text: 'gracias',
    german: 'danke',
    helper: 'Spanien: GRA-thjas · Lateinamerika: GRA-ßjas',
    ipa: '[ˈɡɾa.θjas] (Spanien) · [ˈɡɾa.sjas] (Lateinamerika)',
    syllables: ['gra', 'cias'],
    stress: 0,
    mouth: 'gr: hartes g + ein Zungenschlag. Für ci (Spanien) liegt die Zungenspitze leicht zwischen den Zähnen wie beim englischen „th“; in Lateinamerika ein scharfes s hinter den Zähnen. „cias“ ist eine Silbe.',
    mistakes: ['„Gra-zi-as“ mit deutschem z (ts) und drei Silben.', 'Rachen-R im gr.', 'Stimmhaftes s am Ende.'],
    tips: ['Wähle eine Variante und bleib dabei – beide sind korrekt.', '„cias“ in einem Zug: „thjas“ bzw. „ßjas“.'],
    issueCodes: ['c-z', 'r'],
    variantNotes: [
      { variant: 'es-ES', note: 'Distinción: z und c vor e/i = [θ] („th“), s = [s].' },
      { variant: 'es-LA', note: 'Seseo: z, ce, ci und s klingen alle gleich wie [s].' },
    ],
    level: 1,
  }),
  item({
    id: 'es.p.cz.cerveza',
    categoryId: 'es.pc.c-z',
    text: 'cerveza',
    german: 'Bier',
    helper: 'Spanien: ther-BE-tha · Lateinamerika: ßer-BE-ßa',
    ipa: '[θeɾˈβe.θa] (Spanien) · [seɾˈβe.sa] (Lateinamerika)',
    syllables: ['cer', 've', 'za'],
    stress: 1,
    mouth: 'Zweimal derselbe Laut für c und z (th bzw. s), dazwischen ein weiches b (Lippen nur angenähert) und ein kurzer Zungenschlag für das r.',
    mistakes: ['Deutsches z („Tser-we-tsa“).', 'v als w.', 'Betonung auf der ersten Silbe.'],
    tips: ['Übe erst „ce – za“ mit deinem gewählten Laut, dann das ganze Wort.'],
    issueCodes: ['c-z', 'b-v', 'r'],
    variantNotes: [
      { variant: 'es-ES', note: 'Spanien: beide Laute als „th“.' },
      { variant: 'es-LA', note: 'Lateinamerika: beide Laute als „ß“.' },
    ],
    level: 3,
  }),
  item({
    id: 'es.p.cz.zapato',
    categoryId: 'es.pc.c-z',
    text: 'zapato',
    german: 'Schuh',
    helper: 'Spanien: tha-PA-to · Lateinamerika: ßa-PA-to',
    ipa: '[θaˈpa.to] (Spanien) · [saˈpa.to] (Lateinamerika)',
    syllables: ['za', 'pa', 'to'],
    stress: 1,
    mouth: 'Spanien: Zungenspitze zwischen die Zähne, Luft entweichen lassen. Lateinamerika: scharfes s. p und t ohne Hauch.',
    mistakes: ['Deutsches z („Tsa-pa-to“).', 'Stimmhaftes s („Sa“ wie in „Sahne“).', 'Behauchte p und t.'],
    tips: ['Das spanische z ist nie „ts“.'],
    issueCodes: ['c-z'],
    variantNotes: [
      { variant: 'es-ES', note: 'Distinción: [θ].' },
      { variant: 'es-LA', note: 'Seseo: [s].' },
    ],
    level: 2,
  }),
  item({
    id: 'es.p.cz.cinco',
    categoryId: 'es.pc.c-z',
    text: 'cinco',
    german: 'fünf',
    helper: 'Spanien: THING-ko · Lateinamerika: ßING-ko',
    ipa: '[ˈθiŋ.ko] (Spanien) · [ˈsiŋ.ko] (Lateinamerika)',
    syllables: ['cin', 'co'],
    stress: 0,
    mouth: 'Erstes c weich (th bzw. s), zweites c hart (k). Das n vor k wird wie „ng“ in „Bank“ gesprochen.',
    mistakes: ['Beide c gleich („kinko“ oder „thintho“).', 'Deutsches z („Tsinko“).'],
    tips: ['c + i = weich, c + o = hart – in einem Wort beides.'],
    issueCodes: ['c-z'],
    variantNotes: [
      { variant: 'es-ES', note: 'Distinción: [θ].' },
      { variant: 'es-LA', note: 'Seseo: [s].' },
    ],
    level: 1,
  }),
];

// ───────────────────────── Ñ ─────────────────────────
const ny: PronItem[] = [
  item({
    id: 'es.p.ny.espanol',
    categoryId: 'es.pc.ny',
    text: 'español',
    german: 'Spanisch; spanisch',
    helper: 'es-pa-NJOL – ñ wie „gn“ in „Champagner“',
    ipa: '[es.paˈɲol]',
    syllables: ['es', 'pa', 'ñol'],
    stress: 2,
    mouth: 'Für das ñ drückt der mittlere Zungenrücken flächig gegen den harten Gaumen, die Zungenspitze liegt unten hinter den Zähnen. Ein einziger Laut, kein „n + j“ nacheinander.',
    mistakes: ['„Espanol“ ohne ñ.', 'Betonung vorn („ES-pa-ñol“).', 'Deutsches „Sch“ am Anfang („Schpanjol“).'],
    tips: ['Das s am Anfang ist scharf wie ß – kein „sch“.', 'Endet auf -l, darum Betonung auf der letzten Silbe.'],
    issueCodes: ['ny', 'stress'],
    level: 2,
  }),
  item({
    id: 'es.p.ny.manana',
    categoryId: 'es.pc.ny',
    text: 'mañana',
    german: 'morgen; Morgen',
    helper: 'ma-NJA-na',
    ipa: '[maˈɲa.na]',
    syllables: ['ma', 'ña', 'na'],
    stress: 1,
    mouth: 'Dreimal offenes a. In der Mitte der Zungenrücken flächig am Gaumen (ñ), am Ende die Zungenspitze hinter den Zähnen (n).',
    mistakes: ['ñ und n gleich sprechen („ma-na-na“).', 'End-a abschwächen.'],
    tips: ['Spür den Unterschied: Bei ñ liegt die Zungenspitze unten, bei n oben.'],
    issueCodes: ['ny'],
    level: 2,
  }),
  item({
    id: 'es.p.ny.nino',
    categoryId: 'es.pc.ny',
    text: 'niño',
    german: 'Kind, Junge',
    helper: 'NI-njo',
    ipa: '[ˈni.ɲo]',
    syllables: ['ni', 'ño'],
    stress: 0,
    mouth: 'Erstes n mit der Zungenspitze oben, dann für ñ der Zungenrücken am harten Gaumen – als würdest du „nj“ zu einem Laut verschmelzen.',
    mistakes: ['„Nino“ ohne ñ (das ist ein Name).', '„Nin-jo“ mit zwei getrennten Lauten und Pause.'],
    tips: ['Übe mit „Kognak“ oder „Champagner“ – dort steckt der Laut schon drin.'],
    issueCodes: ['ny'],
    level: 1,
  }),
];

// ───────────────────────── H / CH ─────────────────────────
const hch: PronItem[] = [
  item({
    id: 'es.p.h.hola',
    categoryId: 'es.pc.h-ch',
    text: 'hola',
    german: 'hallo',
    helper: 'O-la – das h ist stumm',
    ipa: '[ˈo.la]',
    syllables: ['ho', 'la'],
    stress: 0,
    mouth: 'Direkt mit gerundeten Lippen beim o beginnen, kein Hauch davor. Das l ist hell (Zungenspitze oben), das a offen.',
    mistakes: ['Gehauchtes deutsches h („Hola“).', 'Englisch-dunkles l.'],
    tips: ['Tu so, als stünde nur „ola“ da.'],
    issueCodes: ['h'],
    level: 1,
  }),
  item({
    id: 'es.p.h.hablar',
    categoryId: 'es.pc.h-ch',
    text: 'hablar',
    german: 'sprechen',
    helper: 'a-BLAR – h stumm, b weich, r am Ende hörbar',
    ipa: '[aˈβlaɾ]',
    syllables: ['ha', 'blar'],
    stress: 1,
    mouth: 'Mit offenem a beginnen, Lippen nähern sich für das weiche b, Zungenspitze für l und am Ende ein kurzer Schlag für r.',
    mistakes: ['Gehauchtes h.', 'Betonung vorn („HA-blar“).', 'End-r vokalisiert („a-bla“).'],
    tips: ['Infinitive werden immer auf der letzten Silbe betont.'],
    issueCodes: ['h', 'b-v', 'r'],
    level: 1,
  }),
  item({
    id: 'es.p.h.chico',
    categoryId: 'es.pc.h-ch',
    text: 'chico',
    german: 'Junge; klein',
    helper: 'TSCHI-ko',
    ipa: '[ˈt͡ʃi.ko]',
    syllables: ['chi', 'co'],
    stress: 0,
    mouth: 'ch wie im deutschen „tsch“ in „Tschüss“: Zunge kurz am Gaumen, dann Reibung. Lippen leicht nach vorn.',
    mistakes: ['Wie deutsches „ch“ in „ich“ („Chiko“).', 'Wie „sch“ ohne t.'],
    tips: ['Denk an „Tschico“.'],
    issueCodes: ['h'],
    variantNotes: [{ variant: 'es-ES', note: 'In Andalusien hört man ch teils weicher, fast wie „sch“.' }],
    level: 1,
  }),
  item({
    id: 'es.p.h.noche',
    categoryId: 'es.pc.h-ch',
    text: 'noche',
    german: 'Nacht',
    helper: 'NO-tsche – End-e klar',
    ipa: '[ˈno.t͡ʃe]',
    syllables: ['no', 'che'],
    stress: 0,
    mouth: 'o mit gerundeten Lippen, dann „tsch“, und ein klares e mit leicht gespreizten Lippen.',
    mistakes: ['Das e am Ende verschlucken („notsch“).', 'ch wie in „Nacht“.'],
    tips: ['`Buenas noches`: Das Grußwort übt gleich alles auf einmal.'],
    issueCodes: ['h', 'vowels'],
    level: 1,
  }),
];

// ───────────────────────── Betonung ─────────────────────────
const stress: PronItem[] = [
  item({
    id: 'es.p.stress.hablo',
    categoryId: 'es.pc.stress',
    text: 'hablo',
    german: 'ich spreche',
    helper: 'A-blo – Betonung vorn',
    ipa: '[ˈa.βlo]',
    syllables: ['ha', 'blo'],
    stress: 0,
    mouth: 'Erste Silbe lauter und etwas höher, die zweite klar, aber leiser. h stumm, b weich.',
    mistakes: ['Endbetonung – das wäre `habló` (er/sie sprach).'],
    tips: ['Regel: endet auf Vokal → vorletzte Silbe betont.'],
    issueCodes: ['stress'],
    level: 1,
  }),
  item({
    id: 'es.p.stress.hablo-pasado',
    categoryId: 'es.pc.stress',
    text: 'habló',
    german: 'er/sie sprach',
    helper: 'a-BLO – Betonung hinten',
    ipa: '[aˈβlo]',
    syllables: ['ha', 'bló'],
    stress: 1,
    mouth: 'Erste Silbe kurz und leise, die zweite lauter und höher – die Stimme „landet“ auf dem ó.',
    mistakes: ['Wie `hablo` vorn betonen – dann ändert sich die Bedeutung (ich spreche).'],
    tips: ['Der Akzentstrich zeigt die betonte Silbe.', 'Übe im Paar: HA-blo – ha-BLÓ.'],
    issueCodes: ['stress'],
    level: 2,
  }),
  item({
    id: 'es.p.stress.cafe',
    categoryId: 'es.pc.stress',
    text: 'café',
    german: 'Kaffee; Café',
    helper: 'ka-FE',
    ipa: '[kaˈfe]',
    syllables: ['ca', 'fé'],
    stress: 1,
    mouth: 'k ohne Hauch, zweite Silbe betont, e halboffen – nicht so geschlossen wie deutsches „Kaffee“.',
    mistakes: ['Betonung vorn wie im Deutschen („KAF-fee“).', 'e zu lang und geschlossen.'],
    tips: ['Akzent auf dem é = Betonung am Ende.'],
    issueCodes: ['stress'],
    level: 1,
  }),
  item({
    id: 'es.p.stress.arbol',
    categoryId: 'es.pc.stress',
    text: 'árbol',
    german: 'Baum',
    helper: 'AR-bol',
    ipa: '[ˈaɾ.βol]',
    syllables: ['ár', 'bol'],
    stress: 0,
    mouth: 'Erste Silbe betont, r als kurzer Zungenschlag, b weich, l hell am Ende.',
    mistakes: ['Endbetonung („ar-BOL“) – Wörter auf -l sind normalerweise endbetont, hier zeigt der Akzent die Ausnahme.', 'Rachen-R.'],
    tips: ['Akzent schlägt Regel.'],
    issueCodes: ['stress', 'r'],
    level: 2,
  }),
  item({
    id: 'es.p.stress.telefono',
    categoryId: 'es.pc.stress',
    text: 'teléfono',
    german: 'Telefon',
    helper: 'te-LE-fo-no',
    ipa: '[teˈle.fo.no]',
    syllables: ['te', 'lé', 'fo', 'no'],
    stress: 1,
    mouth: 'Vier klare Silben, die zweite lauter. Alle Vokale gleich deutlich, kein Verschlucken am Ende.',
    mistakes: ['Deutsche Betonung „te-le-FON“.', 'Letzte Silben verschlucken („te-LE-fon“).'],
    tips: ['Drittletzte Silbe betont = immer Akzent.', 'Klopfe den Rhythmus: ta-TAM-ta-ta.'],
    issueCodes: ['stress'],
    level: 2,
  }),
  item({
    id: 'es.p.stress.ciudad',
    categoryId: 'es.pc.stress',
    text: 'ciudad',
    german: 'Stadt',
    helper: 'Spanien: thju-DAD · Lateinamerika: ßju-DAD',
    ipa: '[θjuˈðað] (Spanien) · [sjuˈðað] (Lateinamerika)',
    syllables: ['ciu', 'dad'],
    stress: 1,
    mouth: '„ciu“ ist eine Silbe: das i gleitet schnell zum u. Das d zwischen den Vokalen ist weich; das End-d sehr schwach, fast nur angedeutet.',
    mistakes: ['Drei Silben („ci-u-dad“).', 'Betonung vorn.', 'Hartes, lautes End-d wie im Deutschen „Stadt“ (dort auch t).'],
    tips: ['Endet auf -d → letzte Silbe betont (Regel 2).'],
    issueCodes: ['stress', 'c-z'],
    variantNotes: [
      { variant: 'es-ES', note: 'In Madrid klingt das End-d oft wie ein leises „th“ („ciudath“) oder fällt fast weg.' },
      { variant: 'es-LA', note: 'Seseo am Anfang: „ßju-DAD“; das End-d ist schwach.' },
    ],
    level: 3,
  }),
];

// ───────────────────────── Silben & Bindung ─────────────────────────
const syllables: PronItem[] = [
  item({
    id: 'es.p.syl.buenos-dias',
    categoryId: 'es.pc.syllables',
    text: '¡Buenos días!',
    german: 'Guten Morgen! / Guten Tag!',
    helper: 'BUE-nos DI-as – „bue“ ist eine Silbe, „dí-as“ zwei',
    ipa: '[ˈbwe.noz ˈði.as]',
    syllables: ['bue', 'nos', 'dí', 'as'],
    stress: 2,
    mouth: '„bue“ in einem Zug: Lippen rund für das u, dann sofort zum e. Das s vor d wird leicht stimmhaft, das d ist weich. Der Akzent auf í trennt i und a in zwei Silben.',
    mistakes: ['„Bu-e-nos“ in drei Silben.', '„Dias“ als eine Silbe („djas“).', 'Hartes d.'],
    tips: ['Klatsche den Rhythmus: BUE-nos DÍ-as – vier Silben.'],
    issueCodes: ['vowels', 'stress'],
    level: 1,
  }),
  item({
    id: 'es.p.syl.encantado',
    categoryId: 'es.pc.syllables',
    text: 'encantado',
    german: 'freut mich (Mann spricht)',
    helper: 'en-kan-TA-do – vier klare Silben',
    ipa: '[eŋ.kanˈta.ðo]',
    syllables: ['en', 'can', 'ta', 'do'],
    stress: 2,
    mouth: 'Jede Silbe offen und deutlich. Das erste n vor k klingt wie „ng“, das d am Ende weich zwischen den Vokalen.',
    mistakes: ['Silben zusammenziehen („en-kan-TAD“).', 'End-o verschlucken.'],
    tips: ['Frauen sagen `encantada` – gleiche Betonung.', 'Spanisch ist silbengetaktet: Jede Silbe bekommt etwa gleich viel Zeit.'],
    issueCodes: ['vowels', 'stress'],
    variantNotes: [{ variant: 'es-LA', note: 'In vielen Ländern Lateinamerikas sagt man zur Begrüßung auch oft `Mucho gusto`.' }],
    level: 2,
  }),
  item({
    id: 'es.p.syl.los-amigos',
    categoryId: 'es.pc.syllables',
    text: 'los amigos',
    german: 'die Freunde',
    helper: 'lo-sa-MI-gos – das s rutscht zum nächsten Vokal',
    ipa: '[lo.saˈmi.ɣos]',
    syllables: ['lo', 'sa', 'mi', 'gos'],
    stress: 2,
    mouth: 'Keine Pause zwischen den Wörtern: Endkonsonant + Anfangsvokal verschmelzen zu einer Silbe („sa“). Das g zwischen Vokalen ist weich.',
    mistakes: ['Deutscher Knacklaut vor „amigos“ („los | Amigos“).', 'Hartes g.'],
    tips: ['Sprich es, als wäre es ein Wort: „losamigos“.', 'Genauso: `mis amigos` → „mi-sa-MI-gos“.'],
    issueCodes: ['vowels'],
    level: 2,
  }),
];

// ───────────────────────── Satzmelodie ─────────────────────────
const intonation: PronItem[] = [
  item({
    id: 'es.p.into.como-te-llamas',
    categoryId: 'es.pc.intonation',
    text: '¿Cómo te llamas?',
    german: 'Wie heißt du?',
    helper: 'KO-mo te JA-mas ↘ – Stimme am Ende fallend',
    ipa: '[ˈko.mo te ˈʝa.mas]',
    syllables: ['có', 'mo', 'te', 'lla', 'mas'],
    stress: 0,
    mouth: 'Starte etwas höher auf `Cómo` und lass die Stimme bis zum Ende ruhig sinken. ll wie j.',
    mistakes: ['Am Ende die Stimme heben wie bei einer Ja/Nein-Frage – klingt überrascht.', 'll als l.'],
    tips: ['W-Fragen: hoch anfangen, tief enden.'],
    issueCodes: ['intonation', 'll-y'],
    level: 1,
  }),
  item({
    id: 'es.p.into.me-llamo-ana',
    categoryId: 'es.pc.intonation',
    text: 'Me llamo Ana.',
    german: 'Ich heiße Ana.',
    helper: 'me JA-mo A-na ↘ – ruhig fallend, Wörter verbunden',
    ipa: '[me ˈʝa.mo ˈa.na]',
    syllables: ['me', 'lla', 'mo', 'A', 'na'],
    stress: 3,
    mouth: 'Gleichmäßiger Rhythmus, die Stimme fällt am Ende. `llamo Ana` ohne Knacklaut verbinden.',
    mistakes: ['Knacklaut vor „Ana“.', 'Stimme steigt am Ende (klingt wie eine Frage).'],
    tips: ['Aussagen enden tief – wie ein Punkt, den man hört.'],
    issueCodes: ['intonation', 'll-y'],
    level: 1,
  }),
  item({
    id: 'es.p.into.que-bien',
    categoryId: 'es.pc.intonation',
    text: '¡Qué bien!',
    german: 'Wie schön! / Super!',
    helper: 'KE BJEN! – lebhaft, hoch einsetzen und kräftig fallen',
    ipa: '[ˈke ˈβjen]',
    syllables: ['qué', 'bien'],
    stress: 1,
    mouth: 'qu = k, das u stumm. „bien“ ist eine Silbe mit Gleitlaut j; b nach Vokal weich.',
    mistakes: ['„Kwe“ mit hörbarem u.', '„bi-en“ in zwei Silben.', 'Zu flach und monoton – Ausrufe dürfen im Spanischen emotional klingen.'],
    tips: ['Übertreibe anfangs die Melodie ruhig – spanische Ausrufe haben einen großen Tonumfang.'],
    issueCodes: ['intonation'],
    level: 2,
  }),
  item({
    id: 'es.p.into.de-donde-eres',
    categoryId: 'es.pc.intonation',
    text: '¿De dónde eres?',
    german: 'Woher kommst du?',
    helper: 'de DON-de E-res ↘ – Fragewort betont, dann fallend',
    ipa: '[de ˈðon.de ˈe.ɾes]',
    syllables: ['de', 'dón', 'de', 'e', 'res'],
    stress: 1,
    mouth: 'Höchster Ton auf `dón`, dann sinkt die Stimme. Das d in „dónde“ nach Vokal ist weich, das zweite d nach n hart. `dónde eres` ohne Pause verbinden.',
    mistakes: ['Stimme am Ende heben.', 'Harte d überall.', 'Pause zwischen „dónde“ und „eres“.'],
    tips: ['Vergleiche: `¿Eres de Madrid?` (Ja/Nein-Frage) endet steigend ↗, `¿De dónde eres?` fallend ↘.'],
    issueCodes: ['intonation'],
    level: 2,
  }),
];

// ───────────────────────── Verbindung im Redefluss ─────────────────────────
const linking: PronItem[] = [
  item({
    id: 'es.p.link.mis-amigos',
    categoryId: 'es.pc.linking',
    text: 'mis amigos',
    german: 'meine Freunde',
    helper: 'mi-sa-MI-gos – das s wandert zum a',
    ipa: '[mi.saˈmi.ɣos]',
    syllables: ['mi', 'sa', 'mi', 'gos'],
    stress: 2,
    mouth: 'Keine Pause und kein Knacklaut vor „amigos“: Das s von `mis` eröffnet schon die nächste Silbe („sa“). Es bleibt scharf und stimmlos wie „ß“, auch zwischen Vokalen. Das g zwischen i und o ist weich – der Zungenrücken nähert sich dem Gaumen nur an.',
    mistakes: ['Deutscher Knacklaut: „mis | Amigos“.', 'Summendes s wie in „Rose“ („mi-za-MI-gos“).', 'Hartes g wie in „Gast“.'],
    tips: ['Sprich es zuerst langsam wie ein einziges Wort: „mi-sa-mi-gos“ – dann schneller.', 'Genauso: `los amigos` („lo-sa-MI-gos“), `tus hermanos` („tu-ser-MA-nos“ – das h ist stumm).'],
    issueCodes: ['vowels', 'g'],
    level: 1,
  }),
  item({
    id: 'es.p.link.vamos-a-la-playa',
    categoryId: 'es.pc.linking',
    text: 'Vamos a la playa.',
    german: 'Wir gehen an den Strand. / Lass uns an den Strand gehen.',
    helper: 'BA-mo-sa-la-PLA-ja – ein einziger Fluss',
    ipa: '[ˈba.mo.sa.laˈpla.ʝa]',
    syllables: ['va', 'mo', 'sa', 'la', 'pla', 'ya'],
    stress: 4,
    mouth: 'Das v am Satzanfang ist ein b mit beiden Lippen. Das s von `vamos` bindet an das `a`: „mo-sa“. `a la` ohne Pause anschließen. In `playa` klingt y wie ein deutsches j mit etwas Reibung; p ohne Hauch.',
    mistakes: ['„Wamos“ mit deutschem w.', 'Knacklaut und Pause vor dem a: „vamos | a la playa“.', 'Das kleine `a` verschlucken („vamos la playa“) – dann fehlt die Präposition.', '„Pla-i-a“ in drei Silben.'],
    tips: ['Klatsch sechs gleichmäßige Silben: va-mo-sa-la-pla-ya.', 'Das `a` ist kurz, aber hörbar – es ist die Präposition „nach/zu“.'],
    issueCodes: ['b-v', 'll-y', 'vowels'],
    variantNotes: [{ variant: 'es-LA', note: 'In Argentinien und Uruguay klingt `playa` wie „PLA-scha“: [ˈpla.ʃa].' }],
    level: 1,
  }),
  item({
    id: 'es.p.link.que-hora-es',
    categoryId: 'es.pc.linking',
    text: '¿Qué hora es?',
    german: 'Wie spät ist es?',
    helper: 'KE-o-ra-es ↘ – h stumm, die Vokale fließen ineinander',
    ipa: '[ˈke‿ˈo.ɾa‿ˈes]',
    syllables: ['qué', 'ho', 'ra', 'es'],
    stress: 0,
    mouth: '`qu` = k, das u bleibt stumm. Das h von `hora` ist stumm, deshalb trifft das e von `qué` direkt auf das o – im normalen Tempo verschmelzen beide fast zu einer Silbe („keo“, _sinalefa_). Auch `-ra` und `es` verbinden sich. Das r ist ein einziger kurzer Zungenschlag. Die Stimme beginnt hoch auf `qué` und fällt bis zum Ende.',
    mistakes: ['Das h aussprechen („ke Hora“).', 'Knacklaut vor „hora“ und vor „es“.', 'Stimme am Ende heben – klingt wie eine Ja/Nein-Frage.', 'Rachen-R.'],
    tips: ['Übe in Stufen: „ke-o“ ohne Lücke → „keo-ra“ → „keo-ra-es“.', 'Die Antwort wird genauso gebunden: `Son las ocho.` → „son-la-SO-cho“.'],
    issueCodes: ['h', 'r', 'intonation'],
    level: 1,
  }),
  item({
    id: 'es.p.link.un-cafe-con-leche',
    categoryId: 'es.pc.linking',
    text: 'un café con leche',
    german: 'ein Milchkaffee',
    helper: 'ung-ka-FE-kon-LE-tsche – alles in einem Atemzug',
    ipa: '[uŋ.kaˈfe.konˈle.t͡ʃe]',
    syllables: ['un', 'ca', 'fé', 'con', 'le', 'che'],
    stress: 4,
    mouth: 'Das n von `un` passt sich dem folgenden k an und klingt wie „ng“ in „Bank“ – die Zunge ist schon in k-Stellung. c/k ohne Hauch. `café` wird hinten betont. `ch` klingt wie „tsch“. Die Wörter ohne Pause aneinanderreihen, als wäre es ein langes Wort.',
    mistakes: ['Behauchtes k („k-ha-FE“).', 'Betonung vorn: „KA-fe“ wie im Deutschen.', 'Pausen zwischen den Wörtern.', '`ch` wie im deutschen „ich“ statt „tsch“.'],
    tips: ['Bestell ruhig so: `Un café con leche, por favor.` – ein Atemzug, keine Lücken.', 'Das „ng“ entsteht von selbst, wenn du nicht absetzt.'],
    issueCodes: ['stress', 'h'],
    level: 2,
  }),
  item({
    id: 'es.p.link.esta-en-el-centro',
    categoryId: 'es.pc.linking',
    text: 'Está en el centro.',
    german: 'Es ist im Zentrum.',
    helper: 'Spanien: es-TA-e-nel-THEN-tro · Lateinamerika: es-TA-e-nel-SEN-tro',
    ipa: '[esˈta‿e.nelˈθen.tɾo] (Spanien) · [esˈta‿e.nelˈsen.tɾo] (Lateinamerika)',
    syllables: ['es', 'tá', 'e', 'nel', 'cen', 'tro'],
    stress: 4,
    mouth: '`st` mit scharfem s – nie „scht“ wie in „Stein“. Das betonte á von `está` gleitet ohne Pause in das e von `en`. Das n von `en` rutscht zum `el`: „e-nel“. `ce` in Spanien mit der Zungenspitze zwischen den Zähnen („th“), in Lateinamerika als scharfes s. `tr`: t mit der Zungenspitze an den Zähnen, direkt danach ein kurzer Zungenschlag.',
    mistakes: ['„Schta“ wie im deutschen „Stein“.', 'Knacklaut vor „en“ und vor „el“: „está | en | el“.', 'Betonung vorn („ES-ta“) – das wäre `esta` (diese).', 'Deutsches z („Tsentro“).'],
    tips: ['Sprich „e-nel“ wie ein Wort.', 'Achte auf den Akzent: `está` (ist) wird hinten betont, `esta` (diese) vorne.'],
    issueCodes: ['c-z', 'stress', 'r'],
    variantNotes: [
      { variant: 'es-ES', note: 'Distinción: `ce` = [θ].' },
      { variant: 'es-LA', note: 'Seseo: `ce` = [s].' },
    ],
    level: 2,
  }),
];

export const pronItems: PronItem[] = [
  ...vowels, ...rr, ...jg, ...lly, ...bv, ...cz, ...ny, ...hch, ...stress, ...syllables, ...intonation, ...linking,
];

const idsOf = (list: PronItem[]) => list.map((i) => i.id);

export const pronCategories: PronCategory[] = [
  {
    id: 'es.pc.vowels',
    courseId: 'es',
    title: 'Vokale',
    icon: '🅰️',
    description: 'Spanisch hat nur **fünf Vokale** – `a, e, i, o, u` – und sie klingen immer gleich: klar, mittellang, nie verschluckt. Anders als im Deutschen gibt es keine langen und kurzen Varianten und kein dumpfes „e“ wie in „bitte“. Doppelvokale wie `eu` oder `au` spricht man als zwei hörbare Teile: `euro` ist „E-u-ro“, nicht „Oiro“.',
    itemIds: idsOf(vowels),
    minimalPairs: [['peso', 'piso'], ['mesa', 'misa'], ['todo', 'toda'], ['luna', 'lona']],
  },
  {
    id: 'es.pc.r',
    courseId: 'es',
    title: 'Einfaches R und gerolltes RR',
    icon: '🌀',
    description: 'Das Spanische kennt zwei r-Laute, beide mit der **Zungenspitze** (nie im Rachen):\n- **einfaches r** (`pero`, `caro`, `tres`): ein einziger kurzer Zungenschlag\n- **gerolltes rr** (`perro`, `carro`) und **r am Wortanfang** (`rosa`) sowie nach n, l, s: mehrere Schläge\nDer Unterschied verändert die Bedeutung: `pero` (aber) – `perro` (Hund).',
    itemIds: idsOf(rr),
    minimalPairs: [['pero', 'perro'], ['caro', 'carro'], ['coro', 'corro'], ['para', 'parra']],
  },
  {
    id: 'es.pc.j-g',
    courseId: 'es',
    title: 'J- und G-Laute',
    icon: '🔥',
    description: '`j` sowie `g` vor e/i klingen wie das deutsche **„ch“ in „Bach“**: `jamón`, `gente`. Vor a/o/u ist `g` hart wie im Deutschen: `gato`. Für ein hartes g vor e/i schreibt man `gue`/`gui` – das u bleibt stumm: `guitarra`. Zwischen Vokalen wird das harte g weicher (`el gato`).',
    itemIds: idsOf(jg),
    minimalPairs: [['gota', 'jota'], ['higo', 'hijo']],
  },
  {
    id: 'es.pc.ll-y',
    courseId: 'es',
    title: 'LL und Y',
    icon: '🦙',
    description: '`ll` und `y` klingen heute fast überall gleich – ungefähr wie das **deutsche j** in „ja“, oft mit etwas mehr Reibung (_yeísmo_). In Argentinien und Uruguay (rioplatense) klingen beide wie **„sch“**: `me llamo` ≈ „me schamo“. Wichtig: `ll` ist nie ein doppeltes l.',
    itemIds: idsOf(lly),
    minimalPairs: [['llama', 'lama'], ['pollo', 'polo']],
  },
  {
    id: 'es.pc.b-v',
    courseId: 'es',
    title: 'B und V',
    icon: '🍇',
    description: '`b` und `v` sind im Spanischen **derselbe Laut**. Am Wortanfang und nach m/n schließen beide Lippen (wie deutsches b), zwischen Vokalen nähern sie sich nur an – ein weicher Laut. Ein deutsches **w** oder **f** gibt es dafür nicht, und die Zähne berühren die Lippe nie.',
    itemIds: idsOf(bv),
    minimalPairs: [['beso', 'peso'], ['vino', 'pino'], ['bala', 'pala']],
  },
  {
    id: 'es.pc.c-z',
    courseId: 'es',
    title: 'C, Z und S',
    icon: '🦓',
    description: '`z` sowie `c` vor e/i klingen in **Spanien** wie das englische **„th“** in „think“ (_distinción_), in **Lateinamerika** wie ein scharfes **s** (_seseo_). `c` vor a/o/u und `qu` sind ein k. Das spanische `s` ist stimmlos wie „ß“ – nie summend wie in „Rose“. Nie wie das deutsche z („ts“)!',
    itemIds: idsOf(cz),
    minimalPairs: [['cita', 'quita'], ['cena', 'quena']],
  },
  {
    id: 'es.pc.ny',
    courseId: 'es',
    title: 'Ñ',
    icon: '〰️',
    description: '`ñ` ist ein eigener Buchstabe und ein eigener Laut – wie **„gn“ in „Champagner“** oder „Kognak“. Der mittlere Zungenrücken liegt flächig am Gaumen. n und ñ unterscheiden Wörter: `cana` (graues Haar) – `caña` (Rohr); und ganz wichtig `año` (Jahr) – `ano` (After).',
    itemIds: idsOf(ny),
    minimalPairs: [['cana', 'caña'], ['pena', 'peña'], ['mono', 'moño']],
  },
  {
    id: 'es.pc.h-ch',
    courseId: 'es',
    title: 'H und CH',
    icon: '🤫',
    description: 'Das `h` ist im Spanischen **immer stumm**: `hola` = „ola“. Nur in der Verbindung `ch` zählt es mit – und `ch` klingt wie **„tsch“** in „Tschüss“: `chico`, `noche`.',
    itemIds: idsOf(hch),
    minimalPairs: [['ocho', 'oso'], ['chapa', 'capa']],
  },
  {
    id: 'es.pc.stress',
    courseId: 'es',
    title: 'Betonungsregeln',
    icon: '🎯',
    description: 'Drei Regeln bestimmen die betonte Silbe:\n- Wortende **Vokal, -n, -s** → vorletzte Silbe (`CA-sa`, `HA-blan`)\n- **anderer Konsonant** → letzte Silbe (`ha-BLAR`, `ciu-DAD`)\n- **Akzentstrich** → genau dort (`ca-FÉ`, `ÁR-bol`, `te-LÉ-fo-no`)\nDie Betonung kann die Bedeutung ändern: `hablo` (ich spreche) – `habló` (er/sie sprach).',
    itemIds: idsOf(stress),
    minimalPairs: [['hablo', 'habló'], ['papa', 'papá'], ['esta', 'está'], ['termino', 'terminó']],
  },
  {
    id: 'es.pc.syllables',
    courseId: 'es',
    title: 'Silbentrennung',
    icon: '🔗',
    description: 'Spanisch ist **silbengetaktet**: Jede Silbe bekommt ungefähr gleich viel Zeit, nichts wird verschluckt. Silben enden bevorzugt auf Vokal (`ca-sa`, `a-mi-go`). `i`/`u` neben einem anderen Vokal bilden meist eine Silbe mit ihm (`bue-nos`, `ciu-dad`), ein Akzent trennt sie (`dí-as`). Über Wortgrenzen wird verbunden: `los amigos` → „lo-sa-mi-gos“ – ohne deutschen Knacklaut.',
    itemIds: idsOf(syllables),
  },
  {
    id: 'es.pc.intonation',
    courseId: 'es',
    title: 'Satzmelodie',
    icon: '🎵',
    description: '**Aussagen** enden mit fallender Stimme ↘. **Ja/Nein-Fragen** steigen am Ende ↗ – oft ist das der einzige Unterschied zur Aussage: `Hablas español.` / `¿Hablas español?`. **Fragen mit Fragewort** beginnen hoch und fallen am Ende ↘. Ausrufe (`¡Qué bien!`) haben einen großen Tonumfang.',
    itemIds: idsOf(intonation),
    minimalPairs: [['Hablas español.', '¿Hablas español?'], ['Es de Madrid.', '¿Es de Madrid?']],
  },  {
    id: 'es.pc.linking',
    courseId: 'es',
    title: 'Verbindung im Redefluss',
    icon: '🌊',
    description: 'Im Spanischen fließen die Wörter ineinander – **ohne den deutschen Knacklaut** vor Vokalen:\n- **Konsonant + Vokal** wird über die Wortgrenze gebunden: `mis amigos` → „mi-sa-MI-gos“, `en el centro` → „e-nel-CEN-tro“.\n- **Vokal + Vokal** verschmelzen oft zu einer Silbe (_sinalefa_): `qué hora es` → „keo-ra-es“. Das stumme h stört dabei nicht.\n- **Gleiche Vokale** werden zu einem etwas längeren Laut: `va a comer` → „ba-ko-MER“.\n- Ein **n** passt sich dem nächsten Laut an: `un café` → „ung-ka-FE“.\nDer Rhythmus bleibt gleichmäßig: Jede Silbe bekommt ungefähr gleich viel Zeit. Deshalb klingen `las alas` (die Flügel) und `la sala` (der Saal) fast gleich – nur das End-s unterscheidet sie.',
    itemIds: idsOf(linking),
    minimalPairs: [['las alas', 'la sala'], ['un amigo', 'una miga']],
  },
];
