import type { Stage } from '../types';

export const stages: Stage[] = [
  // ───────────────────────── Stufe 0 ─────────────────────────
  {
    id: 'stage0',
    courseId: 'es',
    title: 'Stufe 0 – Grundlagen & erste Laute',
    short: 'Stufe 0',
    description:
      'Der Einstieg ohne Vorkenntnisse: Du lernst das spanische **Lautsystem**, begrüßt Menschen passend mit **tú** oder **usted**, stellst dich vor und bestellst im Café. Grammatisch legst du das Fundament: **ser** und **estar**, Artikel, Genus und Plural, Satzbau, Verneinung und die regelmäßigen Verben im Präsens.',
    goals: [
      'Menschen zu jeder Tageszeit begrüßen und sich verabschieden',
      'Die spanischen Laute erkennen und verständlich aussprechen',
      'Sich vorstellen: Name, Herkunft, Wohnort, Beruf, Sprachen',
      'ser und estar sicher unterscheiden',
      'Einfache Sätze bilden, verneinen und Fragen stellen',
      'Zahlen von 0 bis 100 verstehen und nennen',
      'Im Café bestellen und nach Preisen fragen',
    ],
    grammarTopics: [
      'Alphabet, Laute & Betonung',
      'Anrede: tú und usted',
      'Personalpronomen',
      'ser',
      'estar',
      'ser oder estar?',
      'Bestimmte und unbestimmte Artikel',
      'Genus & Plural',
      'Adjektive und ihre Anpassung',
      'Satzstellung & Verneinung',
      'Regelmäßige Verben im Präsens (-ar, -er, -ir)',
      'Zahlen 0–100',
      'Fragewörter',
      'hay und está',
    ],
    vocabFields: ['Begrüßung & Verabschiedung', 'Befinden', 'Länder & Herkunft', 'Berufe', 'Alltagsgegenstände', 'Zahlen', 'Café & Getränke', 'Einkaufen & Preise'],
    pronFocus: [
      'Die fünf klaren Vokale a, e, i, o, u',
      'Einfaches r und gerolltes rr',
      'Stummes h, ch und j',
      'ñ und ll/y',
      'Wortbetonung und Akzentzeichen',
      'Satzmelodie bei Fragen',
    ],
    dialogues: [
      'Erste Begrüßung unter Nachbarn',
      'Sich im Sprachkurs vorstellen',
      'Woher kommst du? – Smalltalk',
      'Bestellung im Café',
      'Preise erfragen im kleinen Laden',
    ],
    chapters: [
      {
        id: 'es.s0.c1',
        title: 'Hallo & erste Laute',
        description: 'Begrüßen und verabschieden, tú oder usted, das spanische Alphabet mit seinen Lauten und die Personalpronomen.',
        lessonIds: ['es.s0.l01', 'es.s0.l02', 'es.s0.l03'],
      },
      {
        id: 'es.s0.c2',
        title: 'Sein & Befinden',
        description: 'Wer du bist mit ser, wo und wie du bist mit estar – und der wichtige Unterschied zwischen beiden.',
        lessonIds: ['es.s0.l04', 'es.s0.l05', 'es.s0.l06'],
        examId: 'es.exam.s0.mid',
      },
      {
        id: 'es.s0.c3',
        title: 'Wörter & Sätze bauen',
        description: 'Artikel, Genus und Plural, Adjektive, die richtige Satzstellung und die Verneinung mit no.',
        lessonIds: ['es.s0.l07', 'es.s0.l08', 'es.s0.l09'],
      },
      {
        id: 'es.s0.c4',
        title: 'Handeln & zählen',
        description: 'Die regelmäßigen Verben auf -ar, -er und -ir im Präsens und die Zahlen von 0 bis 100.',
        lessonIds: ['es.s0.l10', 'es.s0.l11'],
      },
      {
        id: 'es.s0.c5',
        title: 'Erste Gespräche',
        description: 'Sich vorstellen, Fragen stellen und im Café oder Laden mit hay und está zurechtkommen.',
        lessonIds: ['es.s0.l12', 'es.s0.l13', 'es.s0.l14'],
      },
    ],
    finalExamId: 'es.exam.s0.final',
    bossExamId: 'es.exam.s0.boss',
    mastery: {
      finalPct: 70,
      bossPct: 70,
      minSkills: { grammar: 50, vocabulary: 50, listening: 45, pronunciation: 45, speaking: 45 },
    },
    available: true,
  },

  // ───────────────────────── A1 ─────────────────────────
  {
    id: 'a1',
    courseId: 'es',
    title: 'A1 – Mein Alltag auf Spanisch',
    short: 'A1',
    description:
      'Auf A1 sprichst du über dein **Leben**: Familie, Vorlieben, Tagesablauf und Pläne. Du findest dich in der Stadt zurecht, kaufst ein, verabredest dich und beschreibst Menschen und Wohnungen. Neu sind wichtige unregelmäßige Verben wie **tener** und **ir**, **gustar**, reflexive Verben und die nahe Zukunft mit **ir a**.',
    goals: [
      'Über Familie, Alter und Vorlieben sprechen',
      'Den eigenen Tagesablauf mit Uhrzeiten beschreiben',
      'Pläne mit ir a + Infinitiv ausdrücken',
      'Nach dem Weg fragen und Wegbeschreibungen verstehen',
      'Im Restaurant bestellen und Kleidung kaufen',
      'Verabredungen treffen und über das Wetter sprechen',
      'Wohnung und Personen beschreiben',
    ],
    grammarTopics: [
      'tener',
      'Possessivbegleiter',
      'gustar und encantar',
      'Reflexive Verben',
      'ir a + Infinitiv',
      'Uhrzeit',
      'Stammwechselverben (e→ie, o→ue, e→i)',
      'Unregelmäßige yo-Formen (hago, salgo, pongo …)',
      'Demonstrativbegleiter (este, ese, aquel)',
      'Präpositionen des Ortes',
      'Wetter mit hacer',
      'muy oder mucho',
      'Höfliche Bitten mit poder und querer',
    ],
    vocabFields: ['Familie', 'Freizeit & Hobbys', 'Tagesablauf', 'Uhrzeit & Wochentage', 'Stadt & Verkehr', 'Essen & Restaurant', 'Kleidung & Farben', 'Wetter & Jahreszeiten', 'Wohnung & Möbel', 'Aussehen & Charakter'],
    pronFocus: [
      'j und g vor e/i (hijo, gente)',
      'ñ in año, mañana, España',
      'b und v – ein Laut',
      'c und z in Spanien und Lateinamerika',
      'Verbindung von Wörtern im Redefluss',
    ],
    dialogues: [
      'Die Familie auf Fotos vorstellen',
      'Was machst du gern in deiner Freizeit?',
      'Ein typischer Tag',
      'Pläne fürs Wochenende',
      'Nach dem Weg fragen',
      'Im Restaurant bestellen',
      'Kleidung kaufen und anprobieren',
      'Eine Wohnung besichtigen',
    ],
    chapters: [
      {
        id: 'es.a1.c1',
        title: 'Mein Leben',
        description: 'Familie und Alter mit tener, Vorlieben mit gustar, der Tagesablauf mit Uhrzeit und reflexiven Verben sowie Pläne mit ir a.',
        lessonIds: ['es.a1.l01', 'es.a1.l02', 'es.a1.l03', 'es.a1.l04'],
        examId: 'es.exam.a1.c1',
      },
      {
        id: 'es.a1.c2',
        title: 'Unterwegs in der Stadt',
        description: 'Orte in der Stadt, nach dem Weg fragen, Wegbeschreibungen verstehen, Verkehrsmittel und Präpositionen des Ortes.',
        lessonIds: [],
      },
      {
        id: 'es.a1.c3',
        title: 'Essen, Einkaufen & Preise',
        description: 'Im Restaurant bestellen, auf dem Markt einkaufen, Kleidung und Farben, este/ese/aquel und Stammwechselverben wie querer und preferir.',
        lessonIds: [],
      },
      {
        id: 'es.a1.c4',
        title: 'Freizeit, Wetter & Verabredungen',
        description: 'Wochentage, Monate und Datum, das Wetter mit hacer, sich verabreden, Vorschläge machen und höflich absagen.',
        lessonIds: [],
      },
      {
        id: 'es.a1.c5',
        title: 'Wohnen & Beschreiben',
        description: 'Wohnung und Möbel, wo sich etwas befindet, Aussehen und Charakter von Personen beschreiben, muy und mucho.',
        lessonIds: [],
      },
    ],
    mastery: {
      finalPct: 70,
      bossPct: 70,
      minSkills: { grammar: 55, vocabulary: 55, listening: 50, pronunciation: 50, speaking: 50, reading: 45, writing: 45 },
    },
    available: true,
  },

  // ───────────────────────── A2 ─────────────────────────
  {
    id: 'a2',
    courseId: 'es',
    title: 'A2 – Erlebtes erzählen',
    short: 'A2',
    description:
      'Auf A2 erzählst du von **Vergangenem**: was du heute erlebt hast, was letztes Jahr passiert ist und wie es früher war. Du vergleichst, gehst zum Arzt, organisierst Reisen und ersetzt Wörter elegant durch **Objektpronomen**.',
    goals: [
      'Von Erlebnissen und Erfahrungen berichten',
      'Eine kurze Biografie erzählen',
      'Beschreiben, wie etwas früher war',
      'Dinge und Personen vergleichen',
      'Beim Arzt Beschwerden schildern',
      'Reisen planen, buchen und reklamieren',
    ],
    grammarTopics: [
      'Pretérito perfecto (he comido)',
      'Pretérito indefinido – regelmäßig und unregelmäßig',
      'Pretérito imperfecto',
      'Indefinido oder Imperfecto?',
      'Direkte und indirekte Objektpronomen',
      'Komparativ und Superlativ',
      'estar + Gerundium',
      'doler und Ausdrücke mit tener (tener que, tener ganas de)',
      'Futuro simple (Einstieg)',
      'Unpersönliches se',
    ],
    vocabFields: ['Reisen & Unterkunft', 'Biografie & Lebensstationen', 'Kindheit & Erinnerungen', 'Körper & Gesundheit', 'Einkaufen & Reklamation', 'Feste & Traditionen', 'Natur & Umwelt'],
    pronFocus: [
      'Betonung in Vergangenheitsformen (hablo – habló)',
      'Diphthonge (ie, ue, ai)',
      'Satzmelodie beim Erzählen',
      'Weiches d und g zwischen Vokalen',
    ],
    dialogues: [
      'Was hast du heute gemacht?',
      'Mein letzter Urlaub',
      'Als ich ein Kind war …',
      'Beim Arzt',
      'Check-in im Hotel',
      'Eine Reklamation im Geschäft',
    ],
    chapters: [
      { id: 'es.a2.c1', title: 'Was ich erlebt habe', description: 'Pretérito perfecto für Erfahrungen und das Heute: ya, todavía no, alguna vez. In Spanien für heute Geschehenes, in Lateinamerika seltener.', lessonIds: [] },
      { id: 'es.a2.c2', title: 'Gestern & letztes Jahr', description: 'Pretérito indefinido mit den wichtigsten unregelmäßigen Formen (fui, tuve, hice), Zeitangaben der Vergangenheit und Lebensläufe.', lessonIds: [] },
      { id: 'es.a2.c3', title: 'Früher war alles anders', description: 'Pretérito imperfecto für Gewohnheiten und Beschreibungen – und der Kontrast zum Indefinido beim Erzählen.', lessonIds: [] },
      { id: 'es.a2.c4', title: 'Vergleichen & Einkaufen', description: 'Komparativ und Superlativ, Objektpronomen (lo, la, le), Geschäfte, Größen und Reklamationen.', lessonIds: [] },
      { id: 'es.a2.c5', title: 'Gesundheit & Körper', description: 'Körperteile, Beschwerden mit doler, beim Arzt und in der Apotheke, Ratschläge mit tener que und deber.', lessonIds: [] },
      { id: 'es.a2.c6', title: 'Reisen & Unterkünfte', description: 'Verkehrsmittel, Hotel und Bahnhof, laufende Handlungen mit estar + Gerundium und ein erster Blick auf das Futur.', lessonIds: [] },
    ],
    mastery: {
      finalPct: 70,
      bossPct: 70,
      minSkills: { grammar: 55, vocabulary: 55, listening: 55, pronunciation: 50, speaking: 50, reading: 50, writing: 50 },
    },
    available: false,
  },

  // ───────────────────────── B1 ─────────────────────────
  {
    id: 'b1',
    courseId: 'es',
    title: 'B1 – Selbstständig kommunizieren',
    short: 'B1',
    description:
      'Auf B1 drückst du **Wünsche, Gefühle und Meinungen** aus und begründest sie. Du lernst den **Subjuntivo**, sprichst über Zukunft und Bedingungen und meisterst Alltag, Arbeit und Studium weitgehend selbstständig.',
    goals: [
      'Wünsche, Hoffnungen und Gefühle ausdrücken',
      'Die eigene Meinung begründen und auf andere eingehen',
      'Erlebnisse lebendig und zusammenhängend erzählen',
      'Über Zukunftspläne und Bedingungen sprechen',
      'Sich schriftlich und mündlich bewerben',
      'Nachrichten und Alltagsmedien in groben Zügen verstehen',
    ],
    grammarTopics: [
      'Presente de subjuntivo – Formen',
      'Subjuntivo nach Wünschen, Gefühlen und Aufforderungen',
      'Meinung: creo que / no creo que',
      'Imperativ (bejaht und verneint)',
      'Pluscuamperfecto',
      'Futuro simple und Condicional',
      'Bedingungssätze (real und irreal)',
      'Relativsätze mit que, donde, lo que',
      'Passiv mit se',
      'Konnektoren (sin embargo, además, por eso)',
    ],
    vocabFields: ['Gefühle & Beziehungen', 'Arbeit & Bewerbung', 'Studium & Ausbildung', 'Medien & Nachrichten', 'Umwelt & Gesellschaft', 'Wohnen & Nachbarschaft'],
    pronFocus: ['Flüssiges Sprechen in längeren Sätzen', 'Bindungen zwischen Wörtern (sinalefa)', 'Emotionale Intonation', 'Regionale Aussprachen erkennen: seseo, yeísmo'],
    dialogues: ['Einer Freundin Mut machen', 'Eine Meinungsdiskussion unter Kollegen', 'Vorstellungsgespräch', 'Telefonat mit einer Behörde', 'Pläne für die Zukunft'],
    chapters: [
      { id: 'es.b1.c1', title: 'Wünsche & Gefühle', description: 'Formen des Presente de subjuntivo und seine Verwendung nach quiero que, espero que, me alegra que und ojalá.', lessonIds: [] },
      { id: 'es.b1.c2', title: 'Meinungen äußern', description: 'Zustimmen, widersprechen und begründen: creo que vs. no creo que, Konnektoren und höfliche Einwände.', lessonIds: [] },
      { id: 'es.b1.c3', title: 'Erzählen wie im Leben', description: 'Pluscuamperfecto und das Zusammenspiel aller Vergangenheitszeiten in Anekdoten und Berichten.', lessonIds: [] },
      { id: 'es.b1.c4', title: 'Zukunft & Bedingungen', description: 'Futuro simple, Condicional, Vermutungen und Bedingungssätze – von si tengo tiempo bis si tuviera tiempo.', lessonIds: [] },
      { id: 'es.b1.c5', title: 'Arbeit & Studium', description: 'Lebenslauf, Bewerbung und Vorstellungsgespräch, formelle E-Mails und Telefonate im Beruf.', lessonIds: [] },
      { id: 'es.b1.c6', title: 'Medien & Gesellschaft', description: 'Nachrichten verstehen, Relativsätze, das Passiv mit se und aktuelle Themen diskutieren.', lessonIds: [] },
    ],
    mastery: {
      finalPct: 70,
      bossPct: 70,
      minSkills: { grammar: 60, vocabulary: 55, listening: 55, pronunciation: 55, speaking: 55, reading: 55, writing: 55 },
    },
    available: false,
  },

  // ───────────────────────── B2 ─────────────────────────
  {
    id: 'b2',
    courseId: 'es',
    title: 'B2 – Diskutieren & argumentieren',
    short: 'B2',
    description:
      'Auf B2 diskutierst du **überzeugend**, formulierst Hypothesen über Vergangenes, gibst Gespräche in **indirekter Rede** wieder und bewegst dich sicher in Beruf und Kultur. Du verstehst auch schnellere, authentische Sprache.',
    goals: [
      'Standpunkte klar vertreten und Gegenargumente entkräften',
      'Hypothesen über Vergangenheit und Gegenwart formulieren',
      'Aussagen anderer in indirekter Rede wiedergeben',
      'Präsentationen halten und Besprechungen leiten',
      'Filme, Reportagen und längere Texte verstehen',
    ],
    grammarTopics: [
      'Imperfecto de subjuntivo',
      'Pluscuamperfecto de subjuntivo und Condicional compuesto',
      'Irreale Bedingungssätze der Vergangenheit',
      'Indirekte Rede und Zeitenfolge',
      'Subjuntivo in Konzessiv-, Final- und Temporalsätzen (aunque, para que, cuando)',
      'Verbalperiphrasen (llevar + Gerundium, acabar de, volver a)',
      'Passiv mit ser und estar',
      'Nuancen der Präpositionen por und para',
    ],
    vocabFields: ['Politik & Gesellschaft', 'Wirtschaft & Arbeitswelt', 'Wissenschaft & Technik', 'Kunst, Film & Literatur', 'Gesundheit & Psychologie'],
    pronFocus: ['Rhythmus und Tempo in langen Beiträgen', 'Betonte und unbetonte Satzteile', 'Akzente verstehen: Karibik, Andalusien, Río de la Plata'],
    dialogues: ['Eine Debatte über Stadtpolitik', 'Verhandlung mit einem Kunden', 'Eine Filmkritik besprechen', 'Ein Missverständnis klären'],
    chapters: [
      { id: 'es.b2.c1', title: 'Diskutieren & überzeugen', description: 'Argumentationsstrukturen, Einwände, Zugeständnisse mit aunque und der Subjuntivo in Nebensätzen.', lessonIds: [] },
      { id: 'es.b2.c2', title: 'Was wäre gewesen, wenn …', description: 'Imperfecto und Pluscuamperfecto de subjuntivo, Condicional compuesto und Hypothesen über die Vergangenheit.', lessonIds: [] },
      { id: 'es.b2.c3', title: 'Er sagte, dass …', description: 'Indirekte Rede, Zeitenfolge und das Wiedergeben von Fragen, Bitten und Aufforderungen.', lessonIds: [] },
      { id: 'es.b2.c4', title: 'Beruf & Präsentation', description: 'Präsentieren, verhandeln, moderieren – im formellen Register sicher und klar.', lessonIds: [] },
      { id: 'es.b2.c5', title: 'Kultur & Gesellschaft', description: 'Film, Literatur und Debatten aus Spanien und Lateinamerika; Umgangssprache erkennen und einordnen.', lessonIds: [] },
    ],
    mastery: {
      finalPct: 70,
      bossPct: 70,
      minSkills: { grammar: 60, vocabulary: 60, listening: 60, pronunciation: 55, speaking: 60, reading: 60, writing: 55 },
    },
    available: false,
  },

  // ───────────────────────── C1 ─────────────────────────
  {
    id: 'c1',
    courseId: 'es',
    title: 'C1 – Nuanciert & souverän',
    short: 'C1',
    description:
      'Auf C1 wechselst du mühelos zwischen **Registern**, formulierst präzise und idiomatisch und verstehst anspruchsvolle, auch implizite Inhalte – in Studium, Beruf und Alltag.',
    goals: [
      'Register bewusst wählen: formell, neutral, umgangssprachlich',
      'Komplexe Sachverhalte strukturiert darstellen',
      'Idiomatische Wendungen natürlich einsetzen',
      'Authentische Podcasts, Radio und Fachtexte verstehen',
      'Akademische und berufliche Texte verfassen',
    ],
    grammarTopics: [
      'Subjuntivo in Relativsätzen und nach Konjunktionen',
      'Feine Aspektunterschiede in den Vergangenheitszeiten',
      'Nominalisierung und Nominalstil',
      'Erweiterte Verbalperiphrasen',
      'Betonung und Informationsstruktur (Satzstellung, lo que pasa es que …)',
      'Diskursmarker für Argumentation und Textkohärenz',
    ],
    vocabFields: ['Redewendungen & Kollokationen', 'Akademische Sprache', 'Recht & Verwaltung', 'Medien & Meinungsbildung', 'Gefühle präzise benennen'],
    pronFocus: ['Natürliche Satzmelodie in Argumentationen', 'Emphase und Ironie über die Stimme', 'Sicheres Verstehen verschiedener Akzente'],
    dialogues: ['Podiumsdiskussion', 'Wissenschaftlicher Vortrag mit Fragerunde', 'Ein heikles Gespräch taktvoll führen'],
    chapters: [
      { id: 'es.c1.c1', title: 'Stil & Register', description: 'Formell, neutral, umgangssprachlich: dieselbe Aussage passend für jede Situation formulieren.', lessonIds: [] },
      { id: 'es.c1.c2', title: 'Feine Grammatik', description: 'Subjuntivo in Relativsätzen, Aspektnuancen und Verbalperiphrasen für präzise Aussagen.', lessonIds: [] },
      { id: 'es.c1.c3', title: 'Idiomatik', description: 'Redewendungen, Sprichwörter und Kollokationen, die Texte natürlich klingen lassen.', lessonIds: [] },
      { id: 'es.c1.c4', title: 'Akademisch & beruflich', description: 'Essays, Berichte, Protokolle und Fachsprache – klar gegliedert und überzeugend.', lessonIds: [] },
      { id: 'es.c1.c5', title: 'Authentisch hören', description: 'Podcasts, Radio und Interviews in natürlichem Tempo und mit unterschiedlichen Akzenten.', lessonIds: [] },
    ],
    mastery: {
      finalPct: 70,
      bossPct: 70,
      minSkills: { grammar: 65, vocabulary: 65, listening: 65, pronunciation: 60, speaking: 60, reading: 65, writing: 60 },
    },
    available: false,
  },

  // ───────────────────────── C2 ─────────────────────────
  {
    id: 'c2',
    courseId: 'es',
    title: 'C2 – Präzision & Stil',
    short: 'C2',
    description:
      'Auf C2 geht es um **Feinheiten**: kleinste Bedeutungsunterschiede, Stilmittel, Ironie und die Vielfalt der spanischsprachigen Welt. Du vermittelst Inhalte zwischen Deutsch und Spanisch und schreibst stilsicher.',
    goals: [
      'Feinste Bedeutungs- und Stilunterschiede ausdrücken',
      'Literarische und rhetorische Texte verstehen und analysieren',
      'Regionale Varietäten sicher verstehen',
      'Inhalte zwischen Deutsch und Spanisch sprachmitteln',
      'Anspruchsvolle Texte stilsicher verfassen',
    ],
    grammarTopics: [
      'Stilistische Wahl zwischen grammatischen Alternativen',
      'Seltene Zeiten und Formen (futuro de subjuntivo in festen Wendungen)',
      'Voseo und regionale Grammatik',
      'Rhetorische Figuren und ihre sprachlichen Mittel',
      'Kohärenz und Kohäsion in langen Texten',
    ],
    vocabFields: ['Synonyme & Konnotationen', 'Literatur & Rhetorik', 'Regionale Wortschätze', 'Fach- und Wissenschaftssprache'],
    pronFocus: ['Varietäten im Vergleich: Spanien, Mexiko, Karibik, Anden, Río de la Plata', 'Vortrag und Rezitation', 'Feinsteuerung von Tempo und Pausen'],
    dialogues: ['Literarisches Gespräch', 'Dolmetschen in einer Besprechung', 'Eine Rede halten'],
    chapters: [
      { id: 'es.c2.c1', title: 'Präzision', description: 'Synonyme, Konnotationen und kleinste Bedeutungsunterschiede – das treffende Wort finden.', lessonIds: [] },
      { id: 'es.c2.c2', title: 'Literatur & Rhetorik', description: 'Literarische Texte, Stilmittel, Ironie und Anspielungen erkennen und selbst einsetzen.', lessonIds: [] },
      { id: 'es.c2.c3', title: 'Sprachvarietäten', description: 'Voseo, Rioplatense, Karibik, Andalusien, Mexiko: Grammatik, Wortschatz und Aussprache verstehen.', lessonIds: [] },
      { id: 'es.c2.c4', title: 'Sprachmittlung', description: 'Inhalte zwischen Deutsch und Spanisch sinngemäß übertragen – mündlich und schriftlich.', lessonIds: [] },
      { id: 'es.c2.c5', title: 'Souverän schreiben', description: 'Rezensionen, Kommentare und längere Texte mit eigenem Stil.', lessonIds: [] },
    ],
    mastery: {
      finalPct: 70,
      bossPct: 70,
      minSkills: { grammar: 70, vocabulary: 70, listening: 70, pronunciation: 65, speaking: 65, reading: 70, writing: 65 },
    },
    available: false,
  },

  // ───────────────────────── Native Mastery ─────────────────────────
  {
    id: 'native',
    courseId: 'es',
    title: 'Native Mastery – Feinschliff für echte Gespräche',
    short: 'Native Mastery',
    description:
      '**Native Mastery ist eine Trainingsstufe, kein Versprechen**, wie ein Muttersprachler zu klingen. Hier trainierst du, was Lehrbücher selten zeigen: **Redewendungen**, **Umgangssprache**, **Akzente**, **Humor**, **kulturelle Feinheiten** und den letzten Schliff an deiner **Aussprache** – damit du echte Gespräche entspannter verstehst und natürlicher reagierst.',
    goals: [
      'Gängige Redewendungen und Sprichwörter im Kontext verstehen und passend verwenden',
      'Umgangssprache aus Spanien und Lateinamerika erkennen und richtig einordnen',
      'Verschiedene Akzente sicherer verstehen',
      'Humor, Ironie und Wortspiele erkennen',
      'Kulturelle Gesprächsregeln und Höflichkeitsnuancen beachten',
      'Intonation, Rhythmus und Lautverbindungen weiter verfeinern',
    ],
    grammarTopics: [
      'Gesprochene Grammatik: Ellipsen, Verkürzungen und Füllwörter',
      'Diskursmarker der Alltagssprache (o sea, pues, bueno, vale, órale)',
      'Diminutive und Augmentative mit emotionaler Färbung',
      'Regionale Anredeformen (vos, ustedes, usted unter Freunden)',
    ],
    vocabFields: ['Redewendungen', 'Umgangssprache & Jugendsprache', 'Regionalismen', 'Humor & Wortspiele', 'Gesten & Körpersprache', 'Tabus & Höflichkeit'],
    pronFocus: ['Lautverbindungen im schnellen Sprechen (sinalefa)', 'Intonation für Ironie, Überraschung und Nachdruck', 'Akzentnuancen: Madrid, Andalusien, Mexiko, Karibik, Argentinien', 'Rhythmus und Silbentiming'],
    dialogues: ['Tapas-Runde unter Freunden', 'Familienessen mit vielen Gesprächen gleichzeitig', 'Witze und Anekdoten erzählen', 'Small Talk in verschiedenen Ländern'],
    chapters: [
      { id: 'es.native.c1', title: 'Redewendungen & Sprichwörter', description: 'Modismos und refranes, die im Alltag wirklich vorkommen – mit Bedeutung, Herkunft und passender Situation.', lessonIds: [] },
      { id: 'es.native.c2', title: 'Umgangssprache', description: 'Alltags- und Jugendsprache aus Spanien und Lateinamerika (vale, guay, chévere, chido, bacán …) und wann sie passt – oder nicht.', lessonIds: [] },
      { id: 'es.native.c3', title: 'Akzente verstehen', description: 'Hörtraining mit typischen Merkmalen aus Madrid, Andalusien, Mexiko, der Karibik, den Anden und dem Río de la Plata.', lessonIds: [] },
      { id: 'es.native.c4', title: 'Humor & Ironie', description: 'Wortspiele, Doppeldeutigkeiten, Ironie und Situationskomik erkennen – und selbst vorsichtig einsetzen.', lessonIds: [] },
      { id: 'es.native.c5', title: 'Kulturelle Feinheiten', description: 'Höflichkeit, Direktheit, Einladungen, Tabuthemen und Gesprächskultur in verschiedenen Ländern.', lessonIds: [] },
      { id: 'es.native.c6', title: 'Aussprache-Feinschliff', description: 'Satzmelodie, Rhythmus, Lautverbindungen und die letzten typischen deutschen Spuren in der Aussprache.', lessonIds: [] },
    ],
    mastery: {
      finalPct: 75,
      bossPct: 75,
      minSkills: { grammar: 70, vocabulary: 70, listening: 75, pronunciation: 70, speaking: 70, reading: 70, writing: 65 },
    },
    available: false,
  },
];
