import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.adjectives',
  courseId: 'es',
  stageId: 'stage0',
  order: 10,
  category: 'Adjektive',
  title: 'Adjektive – Angleichung & Stellung',
  summary: 'Adjektive passen sich in Genus und Zahl an ihr Nomen an und stehen meistens dahinter.',
  keywords: [
    'Adjektiv', 'Eigenschaftswort', 'Angleichung', 'Übereinstimmung', 'Stellung', 'nach dem Nomen', 'Farben', 'Nationalität',
    'bueno buen', 'grande gran', 'alto alta', 'männlich weiblich', 'Plural', 'Kongruenz',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Spanische Adjektive sind wie ein **Schatten** des Nomens: Sie übernehmen **Genus und Zahl**. Im Deutschen ändert sich die Endung je nach Fall und Artikel („ein großer Hund, der große Hund“) – im Spanischen nur nach männlich/weiblich und Singular/Plural.',
    },
    {
      type: 'table',
      title: 'Die Formen',
      headers: ['Typ', 'm. Sg.', 'f. Sg.', 'm. Pl.', 'f. Pl.'],
      rows: [
        ['auf -o', 'alto', 'alta', 'altos', 'altas'],
        ['auf -e', 'grande', 'grande', 'grandes', 'grandes'],
        ['auf Konsonant', 'azul', 'azul', 'azules', 'azules'],
        ['Nationalität', 'alemán', 'alemana', 'alemanes', 'alemanas'],
        ['auf -or', 'trabajador', 'trabajadora', 'trabajadores', 'trabajadoras'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'una', role: 'article' },
        { text: ' amiga', role: 'noun' },
        { text: ' mexicana', role: 'adjective' },
        { text: ' y ' },
        { text: 'dos', role: 'other' },
        { text: ' libros', role: 'noun' },
        { text: ' interesantes', role: 'adjective' },
      ],
      german: 'eine mexikanische Freundin und zwei interessante Bücher',
    },
    {
      type: 'text',
      md: '**Stellung:** Normalerweise steht das Adjektiv **hinter** dem Nomen – Farben, Nationalitäten und Formen immer: `una casa blanca`, `un chico alemán`. Einige häufige Adjektive stehen auch davor und werden dann vor männlichem Singular gekürzt: `bueno` → `un buen día`, `malo` → `un mal momento`.',
    },
    {
      type: 'text',
      md: '`grande` wird vor jedem Singular-Nomen zu `gran` und ändert die Bedeutung: `un gran amigo` (ein großartiger Freund) – `un amigo grande` (ein großer, kräftiger Freund).',
    },
    {
      type: 'text',
      md: 'Beschreibt ein Adjektiv männliche **und** weibliche Nomen zusammen, steht es im **männlichen Plural**: `Pedro y Ana son altos.`',
    },
    {
      type: 'mistake',
      wrong: 'la casa blanco',
      right: 'la casa blanca',
      why: 'Das Adjektiv richtet sich nach dem Nomen: `casa` ist weiblich → `blanca`.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Für „hübsch/schön“ hörst du in Lateinamerika sehr oft `lindo/linda`. In Spanien sagt man eher `bonito/bonita` (Dinge, Orte) und `guapo/guapa` (Personen). Alle Formen werden überall verstanden.',
    },
    { type: 'tip', md: '**Das Adjektiv folgt dem Nomen – in der Stellung und in der Form.**' },
    { type: 'audio', text: 'Tengo una amiga mexicana muy simpática.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: 'un chico alto',
      german: 'ein großer Junge',
      parts: [{ text: 'un', role: 'article' }, { text: ' chico', role: 'noun' }, { text: ' alto', role: 'adjective' }],
    },
    {
      target: 'unas chicas altas',
      german: 'ein paar große Mädchen',
      parts: [{ text: 'unas', role: 'article' }, { text: ' chicas', role: 'noun' }, { text: ' altas', role: 'adjective' }],
    },
    { target: 'una ciudad grande', german: 'eine große Stadt' },
    { target: 'los ojos azules', german: 'die blauen Augen' },
    { target: 'una profesora alemana', german: 'eine deutsche Lehrerin' },
    { target: 'Hoy es un buen día.', german: 'Heute ist ein guter Tag.', note: '`bueno` → `buen` vor männlichem Singular.' },
    { target: 'Es un gran amigo.', german: 'Er ist ein großartiger Freund.' },
    { target: 'Mis padres son muy trabajadores.', german: 'Meine Eltern sind sehr fleißig.' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'la casa blanca',
      german: 'das weiße Haus',
      md: 'Deutsch: Adjektiv **vor** dem Nomen. Spanisch: meist **dahinter**.',
    },
    {
      type: 'compare',
      target: 'El perro es negro. / un perro negro',
      german: 'Der Hund ist schwarz. / ein schwarzer Hund',
      md: 'Deutsch dekliniert nur vor dem Nomen („schwarzer“), nach „ist“ bleibt es unverändert („schwarz“). Spanisch passt **immer** an: `La casa es blanca.`',
    },
    {
      type: 'compare',
      target: 'Las chicas son simpáticas.',
      german: 'Die Mädchen sind sympathisch.',
      md: 'Auch nach `ser`/`estar` braucht das Adjektiv die passende Endung.',
    },
    {
      type: 'text',
      md: 'Die gute Nachricht: Keine Fälle, keine Unterschiede nach Artikel. Nur zwei Fragen – **männlich oder weiblich? Singular oder Plural?**',
    },
  ],
  mistakes: [
    { wrong: 'La casa es blanco.', right: 'La casa es blanca.', why: 'Auch nach `ser` passt sich das Adjektiv an – anders als im Deutschen.' },
    { wrong: 'un rojo libro', right: 'un libro rojo', why: 'Farben stehen hinter dem Nomen.' },
    { wrong: 'Mis amigas son simpáticos.', right: 'Mis amigas son simpáticas.', why: 'Nur Frauen → weiblicher Plural.' },
    { wrong: 'un bueno día', right: 'un buen día', why: 'Vor männlichem Singular wird `bueno` zu `buen`.' },
    { wrong: 'Ana es alemán.', right: 'Ana es alemana.', why: 'Nationalitäten auf Konsonant bekommen im Femininum ein -a.' },
  ],
  mnemonic: '**Das Adjektiv ist der Schatten des Nomens:** Es steht dahinter und trägt dieselbe Form.',
  levels: [
    {
      level: 1,
      title: 'Die richtige Endung',
      exercises: [
        {
          id: 'es.g.adjectives.L1.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.adjectives'],
          difficulty: 1,
          prompt: 'la casa ___ (weiß)',
          options: [
            { text: 'blanco', why: '`blanco` ist männlich – `casa` ist weiblich.' },
            { text: 'blanca', why: 'Richtig: weiblich Singular.' },
            { text: 'blancas', why: '`blancas` ist Plural – es geht um ein Haus.' },
          ],
          answer: 1,
          feedback: {
            rule: 'Adjektiv = Genus und Zahl des Nomens: `la casa` → `blanca`.',
            why: 'Die Grundform im Wörterbuch (`blanco`) ist immer männlich Singular.',
            avoid: 'Erst das Nomen anschauen, dann die Endung wählen.',
          },
        },
        {
          id: 'es.g.adjectives.L1.02',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.adjectives'],
          difficulty: 1,
          instruction: 'Welche Form von „alto“ passt?',
          pairs: [
            { left: 'el chico', right: 'alto' },
            { left: 'la chica', right: 'alta' },
            { left: 'los chicos', right: 'altos' },
            { left: 'las chicas', right: 'altas' },
          ],
          feedback: {
            rule: '-o (m. Sg.), -a (f. Sg.), -os (m. Pl.), -as (f. Pl.).',
            why: 'Adjektive auf -o haben vier Formen.',
            avoid: 'Die Endung des Adjektivs spiegelt meist die Endung des Nomens.',
          },
        },
        {
          id: 'es.g.adjectives.L1.03',
          type: 'imageMatch',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.adjectives'],
          difficulty: 1,
          instruction: 'Ordne die Farben zu.',
          pairs: [
            { emoji: '🔴', word: 'rojo' },
            { emoji: '🟢', word: 'verde' },
            { emoji: '🔵', word: 'azul' },
            { emoji: '⚪', word: 'blanco' },
            { emoji: '⚫', word: 'negro' },
          ],
          feedback: {
            rule: 'rojo/roja, blanco/blanca, negro/negra haben vier Formen; verde und azul nur zwei (Singular/Plural).',
            why: 'Adjektive auf -e und auf Konsonant unterscheiden kein Genus.',
            avoid: 'Merke: la casa verde, el libro verde – bei -e ändert sich nichts.',
          },
        },
        {
          id: 'es.g.adjectives.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.adjectives'],
          difficulty: 1,
          audio: 'Las casas son grandes y bonitas.',
          question: 'Wie sind die Häuser?',
          options: ['groß und hübsch', 'klein und hübsch', 'groß und alt'],
          answer: 0,
          feedback: {
            rule: '`grandes` = groß (Pl.), `bonitas` = hübsch (f. Pl.).',
            why: '„klein“ wäre `pequeñas`, „alt“ wäre `viejas`.',
            avoid: 'Hör auf die Adjektive nach `son` – sie tragen die Plural-Endungen -es und -as.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Anpassen und anordnen',
      exercises: [
        {
          id: 'es.g.adjectives.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 2,
          instruction: 'Setze das Adjektiv in der richtigen Form ein.',
          sentence: 'Tengo dos amigas muy ___ (simpático).',
          german: 'Ich habe zwei sehr sympathische Freundinnen.',
          answers: [['simpáticas']],
          feedback: {
            rule: '`amigas` = weiblich Plural → `simpáticas`.',
            why: '`simpáticos` wäre männlich Plural.',
            avoid: 'Endung -as beim Nomen → -as beim Adjektiv.',
          },
        },
        {
          id: 'es.g.adjectives.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 2,
          instruction: 'Setze das Adjektiv in der richtigen Form ein.',
          sentence: 'Los ejercicios son ___ (fácil).',
          german: 'Die Übungen sind leicht.',
          answers: [['fáciles']],
          feedback: {
            rule: 'Konsonant + es: `fácil` → `fáciles` (Akzent bleibt: drittletzte Silbe).',
            why: '`fácils` gibt es nicht; ohne Akzent würde man „fa-CI-les“ lesen.',
            avoid: 'Plural von Adjektiven funktioniert wie bei Nomen.',
          },
        },
        {
          id: 'es.g.adjectives.L2.03',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 2,
          tokens: ['Tengo', 'un', 'perro', 'negro', 'muy', 'simpático.'],
          extra: ['negra', 'simpática'],
          german: 'Ich habe einen sehr netten schwarzen Hund.',
          feedback: {
            rule: 'Nomen + Adjektiv(e): `un perro negro muy simpático`.',
            why: '`negra`/`simpática` sind weiblich – `perro` ist männlich.',
            avoid: 'Adjektive hinter das Nomen – und Endung prüfen.',
          },
        },
        {
          id: 'es.g.adjectives.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 2,
          sentence: 'Mi hermana es muy alto.',
          german: 'Meine Schwester ist sehr groß.',
          answers: ['Mi hermana es muy alta.'],
          feedback: {
            rule: 'Auch nach `ser` passt sich das Adjektiv an: `hermana` → `alta`.',
            why: 'Im Deutschen bleibt „groß“ nach „ist“ unverändert – im Spanischen nicht.',
            avoid: 'Bei `ser`/`estar` + Adjektiv immer zurück zum Subjekt schauen.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Stellung und Sonderformen',
      exercises: [
        {
          id: 'es.g.adjectives.L3.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.adjectives'],
          difficulty: 3,
          prompt: 'Was bedeutet `Es un gran amigo.`?',
          options: [
            { text: 'Er ist ein großartiger Freund.', why: 'Richtig: `gran` vor dem Nomen = großartig, bedeutend.' },
            { text: 'Er ist ein großer (großgewachsener) Freund.', why: 'Das wäre `un amigo grande`.' },
            { text: 'Er ist ein alter Freund.', why: '„alt“ hieße `viejo`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`gran` + Nomen = großartig; Nomen + `grande` = groß (Größe).',
            why: 'Die Stellung ändert bei einigen Adjektiven die Bedeutung.',
            avoid: 'Vor dem Nomen: Bewertung. Hinter dem Nomen: Beschreibung.',
          },
        },
        {
          id: 'es.g.adjectives.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 3,
          sentence: 'Hoy es un ___ día.',
          german: 'Heute ist ein guter Tag.',
          answers: [['buen']],
          bank: ['bueno', 'buen', 'buena'],
          feedback: {
            rule: '`bueno` → `buen` direkt vor einem männlichen Nomen im Singular.',
            why: '`buena` ist weiblich – `día` ist männlich (`el día`).',
            avoid: 'Hinter dem Nomen bleibt es `bueno`: `un día bueno` (seltener).',
          },
        },
        {
          id: 'es.g.adjectives.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Pedro und Ana sind sehr sympathisch.',
          answers: ['Pedro y Ana son muy simpáticos.'],
          feedback: {
            rule: 'Gemischte Gruppe → männlicher Plural: `simpáticos`.',
            why: '`simpáticas` gilt nur für reine Frauengruppen; `simpático` ist Singular.',
            avoid: 'Ein Mann in der Gruppe → -os.',
          },
        },
        {
          id: 'es.g.adjectives.L3.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'eine deutsche Lehrerin und zwei spanische Lehrer',
          answers: [
            'una profesora alemana y dos profesores españoles',
            'una maestra alemana y dos maestros españoles',
          ],
          feedback: {
            rule: 'Nationalitäten stehen hinter dem Nomen und passen sich an: `alemana`, `españoles`.',
            why: '`alemán` hat im Femininum ein -a und verliert den Akzent: `alemana`; `español` → Plural `españoles`.',
            avoid: 'Konsonant-Nationalitäten: +a (f.), +es (m. Pl.), +as (f. Pl.).',
          },
        },
        {
          id: 'es.g.adjectives.L3.05',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.adjectives'],
          difficulty: 3,
          sentence: 'Vivo en una blanca casa grande.',
          german: 'Ich wohne in einem großen weißen Haus.',
          answers: ['Vivo en una casa blanca grande.', 'Vivo en una casa grande y blanca.', 'Vivo en una casa blanca y grande.', 'Vivo en una gran casa blanca.'],
          feedback: {
            rule: 'Farben stehen hinter dem Nomen: `una casa blanca`.',
            why: 'Vorangestellte Farben klingen poetisch und sind im Alltag falsch.',
            avoid: 'Faustregel: Farbe, Herkunft, Form → immer hinter das Nomen.',
          },
        },
      ],
    },
  ],
  related: ['es.g.gender-plural', 'es.g.ser-estar', 'es.g.articles'],
};
