import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.alphabet-sounds',
  courseId: 'es',
  stageId: 'stage0',
  order: 2,
  category: 'Aussprache & Schrift',
  title: 'Alphabet & Laut-Regeln',
  summary: 'Spanisch spricht man fast genau so, wie man es schreibt – mit wenigen festen Regeln für h, j, g, c, qu, ll, ñ, ch und r/rr.',
  keywords: [
    'Alphabet', 'abecedario', 'Buchstaben', 'buchstabieren', 'Aussprache', 'Laute', 'Lautregeln', 'Vokale',
    'h stumm', 'j', 'jota', 'g', 'c', 'z', 'qu', 'gu', 'll', 'y', 'ñ', 'eñe', 'ch', 'r', 'rr', 'b', 'v', 's', 'seseo', 'ceceo',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Gute Nachricht: Spanisch ist fast **lautgetreu**. Wer die Regeln kennt, kann jedes Wort vorlesen – auch unbekannte. Die fünf Vokale `a, e, i, o, u` klingen immer gleich: kurz, klar und deutlich. Anders als im Deutschen wird kein Vokal „verschluckt“: Das `e` in `noche` klingt wie in „Echo“, nie wie das dumpfe e in „bitte“.',
    },
    {
      type: 'table',
      title: 'Die wichtigsten Laut-Regeln',
      headers: ['Schreibung', 'So klingt es', 'Beispiel'],
      rows: [
        ['h', 'stumm – man hört es nie', 'hola → „ola“'],
        ['j · g vor e/i', 'rau wie „ch“ in „Bach“', 'jamón, gente'],
        ['g vor a/o/u · gue · gui', 'wie deutsches g (u bleibt stumm)', 'gato, guitarra'],
        ['c vor a/o/u · qu', 'wie k (u bleibt stumm)', 'casa, queso'],
        ['c vor e/i · z', 'Spanien: wie engl. „th“ · Lateinamerika: wie ß', 'gracias, zapato'],
        ['ll · y', 'meist wie deutsches j', 'llamo, yo'],
        ['ñ', 'wie „gn“ in „Champagner“', 'España'],
        ['ch', 'wie „tsch“', 'chico'],
        ['r (einfach)', 'ein kurzer Zungenschlag', 'pero'],
        ['rr · r am Wortanfang', 'gerollt, mehrere Schläge', 'perro, rosa'],
        ['b · v', 'identisch, wie b (zwischen Vokalen weicher)', 'vino, beber'],
        ['s', 'stimmlos wie ß – nie summend wie in „Rose“', 'casa'],
      ],
    },
    {
      type: 'tip',
      md: '**Vor e und i wird es weich:** `c` → th/s, `g` → ch. **Vor a, o, u bleibt es hart:** k und g. Willst du den harten Laut vor e/i, schreibst du `qu` bzw. `gu`: `queso`, `guitarra`.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Hola', role: 'other' },
        { text: ', ' },
        { text: 'me', role: 'pronoun' },
        { text: ' llamo', role: 'verb' },
        { text: ' Hugo', role: 'noun' },
        { text: '.' },
      ],
      german: 'Hallo, ich heiße Hugo. – Beide h sind stumm, ll klingt wie j: „Ola, me jamo Ugo.“',
    },
    {
      type: 'table',
      title: 'Buchstabennamen zum Buchstabieren (Auswahl)',
      headers: ['Buchstabe', 'Name', 'Buchstabe', 'Name'],
      rows: [
        ['b', 'be', 'j', 'jota'],
        ['c', 'ce', 'ñ', 'eñe'],
        ['g', 'ge', 'q', 'cu'],
        ['h', 'hache', 'r', 'erre'],
        ['v', 'uve', 'w', 'uve doble'],
        ['y', 'ye (i griega)', 'z', 'zeta'],
      ],
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In großen Teilen Spaniens klingen `z` sowie `c` vor e/i wie das englische „th“ in „think“: `gracias` ≈ „GRA-thjas“, `zapato` ≈ „tha-PA-to“. Das nennt man _distinción_.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In ganz Lateinamerika (und in Teilen Südspaniens) klingen `z` und `c` vor e/i wie ein stimmloses s: `gracias` ≈ „GRA-ßjas“ (_seseo_). Buchstabennamen: Viele sagen `ve` oder `ve corta` für v und `be larga` für b, für w `doble ve` oder `doble u`.',
    },
    {
      type: 'mistake',
      wrong: 'vino wie deutsch „Wino“',
      right: 'vino wie „bino“',
      why: 'Ein deutsches w oder f gibt es für `v` im Spanischen nicht. `v` und `b` klingen genau gleich.',
    },
    { type: 'audio', text: 'Hola, me llamo Hugo. Jorge toca la guitarra.', label: 'Laute im Satz anhören' },
  ],
  examples: [
    { target: 'hola', german: 'hallo', note: 'Das h ist stumm: „O-la“.' },
    { target: 'gente', german: 'Leute', note: 'g vor e wie „ch“ in „Bach“: „CHEN-te“.' },
    { target: 'guitarra', german: 'Gitarre', note: 'gui = „gi“, das u bleibt stumm; rr wird gerollt.' },
    { target: 'queso', german: 'Käse', note: 'qu = k, das u hört man nicht: „KE-so“.' },
    { target: 'chico', german: 'Junge', note: 'ch = „tsch“: „TSCHI-ko“.' },
    { target: 'España', german: 'Spanien', note: 'ñ = „nj“: „es-PA-nja“.' },
    { target: 'me llamo', german: 'ich heiße', note: 'll klingt meist wie deutsches j: „me JA-mo“.' },
    { target: 'zapato', german: 'Schuh', variant: 'es-ES', note: 'Spanien: „tha-PA-to“ (z wie engl. th).' },
    { target: 'zapato', german: 'Schuh', variant: 'es-LA', note: 'Lateinamerika: „ßa-PA-to“ (z wie stimmloses s).' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'jamón',
      german: 'Schinken',
      md: 'Spanisches `j` ist immer ein rauer Reibelaut wie in „Bach“ – nie das deutsche j aus „ja“.',
    },
    {
      type: 'compare',
      target: 'yo',
      german: 'ich',
      md: 'Das deutsche j aus „ja“ steckt stattdessen in `y` und `ll`: `yo` ≈ „jo“, `llamo` ≈ „JA-mo“.',
    },
    {
      type: 'compare',
      target: 'casa',
      german: 'Haus',
      md: '`s` ist immer stimmlos wie in „Haus“ – auch am Wortanfang und zwischen Vokalen, wo das Deutsche summt („Sonne“, „Rose“).',
    },
    {
      type: 'compare',
      target: 'Hugo',
      german: 'Hugo',
      md: 'Deutsch haucht das H, Spanisch nicht: „U-go“.',
    },
    {
      type: 'text',
      md: 'Deutsch unterscheidet lange und kurze Vokale („Miete“ – „Mitte“). Spanisch nicht: Alle Vokale sind mittellang und gleich klar – ob betont oder unbetont.',
    },
  ],
  mistakes: [
    { wrong: 'hola mit gehauchtem H', right: 'hola = „ola“', why: 'Das `h` ist im Spanischen immer stumm (außer in der Verbindung `ch`).' },
    { wrong: 'gente mit hartem g wie „Gent“', right: 'gente = „CHEN-te“', why: 'Vor e und i klingt g wie das deutsche „ch“ in „Bach“.' },
    { wrong: 'queso mit hörbarem u („kwe-so“)', right: 'queso = „KE-so“', why: 'In `que`/`qui` und `gue`/`gui` ist das u nur ein Schreibzeichen und bleibt stumm.' },
    { wrong: 'casa mit summendem s („ka-za“)', right: 'casa mit stimmlosem s („KA-ßa“)', why: 'Am Wortanfang und zwischen Vokalen ist das spanische s immer stimmlos – ein summendes „s“ wie in „Rose“ klingt falsch. (Nur direkt vor b, d, g, l, m, n wird es leicht stimmhaft: `mismo`, `buenos días`.)' },
    { wrong: 'vino wie „Wino“', right: 'vino = „BI-no“', why: '`v` klingt wie `b`; der deutsche w-Laut existiert im Spanischen nicht.' },
  ],
  mnemonic: '**H hört man nie, J kratzt wie in „Bach“ – und vor e/i werden c und g weich.**',
  levels: [
    {
      level: 1,
      title: 'Laute erkennen',
      exercises: [
        {
          id: 'es.g.alphabet-sounds.L1.01',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 1,
          prompt: 'Wie spricht man das `h` in `hola` aus?',
          options: [
            { text: 'gar nicht – es ist stumm', why: 'Richtig: `hola` klingt wie „ola“.' },
            { text: 'wie das deutsche h in „Haus“', why: 'Das gehauchte h gibt es im Spanischen nicht.' },
            { text: 'wie „ch“ in „Bach“', why: 'Diesen Laut schreibt man mit `j` (oder g vor e/i).' },
          ],
          answer: 0,
          feedback: {
            rule: 'Das spanische `h` ist immer stumm.',
            why: 'Der raue ch-Laut wird mit `j` geschrieben, ein gehauchtes h existiert nicht.',
            avoid: 'Stell dir vor, das h wäre nicht da: `hablar` = „ablar“.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L1.02',
          type: 'matchPairs',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 1,
          instruction: 'Welcher Buchstabe klingt wie?',
          pairs: [
            { left: 'ñ', right: 'wie „nj“' },
            { left: 'j', right: 'wie „ch“ in „Bach“' },
            { left: 'll', right: 'meist wie deutsches j' },
            { left: 'ch', right: 'wie „tsch“' },
            { left: 'h', right: 'stumm' },
          ],
          feedback: {
            rule: '`ñ` = nj, `j` = ch (Bach), `ll` = j, `ch` = tsch, `h` = stumm.',
            why: 'Gerade `j` und `ll` werden oft vertauscht, weil das deutsche j anders klingt als das spanische.',
            avoid: 'Eselsbrücke: `yo` und `llamo` klingen „deutsch-j“, `jamón` klingt „Bach“.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L1.03',
          type: 'listening',
          skills: ['listening', 'pronunciation'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 1,
          audio: 'gente',
          question: 'Wie klingt der erste Laut von `gente`?',
          options: ['wie g in „Garten“', 'wie ch in „Bach“', 'wie j in „ja“'],
          answer: 1,
          feedback: {
            rule: '`g` vor e und i klingt wie das deutsche „ch“ in „Bach“.',
            why: 'Das harte g gibt es nur vor a, o, u (oder als gue/gui).',
            avoid: 'Merke das Paar: `gato` (hart) – `gente` (rau).',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L1.04',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 1,
          prompt: 'In welchem Wort hört man das `u` **nicht**?',
          options: [
            { text: 'queso', why: 'Richtig: In `que` ist das u stumm – „KE-so“.' },
            { text: 'uno', why: 'Hier ist u ein normaler Vokal: „U-no“.' },
            { text: 'luna', why: 'Hier klingt das u deutlich: „LU-na“.' },
          ],
          answer: 0,
          feedback: {
            rule: 'In `que`, `qui`, `gue`, `gui` ist das u stumm.',
            why: 'In allen anderen Positionen wird u ganz normal ausgesprochen.',
            avoid: 'qu = k. Immer.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Regeln anwenden',
      exercises: [
        {
          id: 'es.g.alphabet-sounds.L2.01',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 2,
          prompt: 'In welchem Wort klingt das `g` wie „ch“ in „Bach“?',
          options: [
            { text: 'gato', why: 'g vor a ist hart: „GA-to“.' },
            { text: 'guitarra', why: 'gui ist hart: „gi-TA-rra“ – das u schützt das g.' },
            { text: 'gente', why: 'Richtig: g vor e ist rau – „CHEN-te“.' },
            { text: 'gusto', why: 'g vor u ist hart: „GUS-to“.' },
          ],
          answer: 2,
          feedback: {
            rule: '`g` + e/i = rauer ch-Laut; `g` + a/o/u sowie `gue`/`gui` = hartes g.',
            why: 'Bei `guitarra` steht ein stummes u zwischen g und i – genau damit das g hart bleibt.',
            avoid: 'Schau auf den Buchstaben direkt nach dem g.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L2.02',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 2,
          instruction: 'Hör zu und schreib das Wort.',
          audio: 'hola',
          german: 'hallo',
          answers: ['hola'],
          feedback: {
            rule: 'Das stumme `h` wird trotzdem geschrieben: `hola`.',
            why: 'Man hört „ola“ – die Schreibung musst du dir merken.',
            avoid: 'Präge dir die häufigsten h-Wörter ein: `hola`, `hablar`, `hoy`, `hotel`, `hasta`.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L2.03',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 2,
          instruction: 'Hör zu und schreib das Wort.',
          audio: 'queso',
          german: 'Käse',
          answers: ['queso'],
          feedback: {
            rule: 'Der k-Laut vor e und i wird `qu` geschrieben: `queso`.',
            why: '„keso“ oder „ceso“ sind falsch: `k` kommt fast nur in Fremdwörtern vor, und `ce` würde weich klingen.',
            avoid: 'k-Laut + e/i → qu; k-Laut + a/o/u → c.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L2.04',
          type: 'speak',
          skills: ['pronunciation', 'speaking'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 2,
          text: 'Hola, me llamo Hugo.',
          german: 'Hallo, ich heiße Hugo.',
          phonetic: 'O-la, me JA-mo U-go',
          ipa: '[ˈo.la me ˈʝa.mo ˈu.ɣo]',
          pronItemId: 'es.p.h.hola',
          feedback: {
            rule: 'Beide `h` bleiben stumm, `ll` klingt wie deutsches j.',
            why: 'Ein gehauchtes h oder ein „l-l“ macht den Satz für Muttersprachler schwerer verständlich.',
            avoid: 'Sprich zuerst langsam „O-la – me JA-mo – U-go“, dann im normalen Tempo.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Lesen wie ein Profi',
      exercises: [
        {
          id: 'es.g.alphabet-sounds.L3.01',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 3,
          variant: 'es-ES',
          prompt: 'Wie liest man `cerveza` (Bier) im Standard Spaniens?',
          options: [
            { text: '„ther-BE-tha“', why: 'Richtig: c vor e und z klingen in Spanien wie engl. th, v wie b.' },
            { text: '„ker-WE-za“', why: 'c vor e ist nie k, v nie w, z nie summend.' },
            { text: '„tser-FE-za“', why: 'Das deutsche z (ts) und f gibt es hier nicht.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Spanien: `ce`, `ci`, `z` = th-Laut; `v` = b.',
            why: 'Deutsche lesen c und z gern wie im Deutschen (ts) – das ist im Spanischen nie richtig.',
            avoid: 'Zunge leicht zwischen die Zähne bei ce/ci/z; Lippen zusammen bei v.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L3.02',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 3,
          variant: 'es-LA',
          prompt: 'Wie liest man `cerveza` (Bier) in Lateinamerika?',
          options: [
            { text: '„ßer-BE-ßa“', why: 'Richtig: seseo – c vor e und z klingen wie ein stimmloses s, v wie b.' },
            { text: '„ker-WE-za“', why: 'c vor e ist nie k, v nie w, z nie summend.' },
            { text: '„tser-FE-za“', why: 'Das deutsche z (ts) und f gibt es hier nicht.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Lateinamerika: `ce`, `ci`, `z` = stimmloses s (seseo); `v` = b.',
            why: 'Deutsche lesen c und z gern wie im Deutschen (ts) – das ist im Spanischen nie richtig.',
            avoid: 'Denk an „ß“, wann immer du ce, ci oder z siehst.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L3.03',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 3,
          instruction: 'Hör zu und schreib das Wort.',
          audio: 'guitarra',
          german: 'Gitarre',
          answers: ['guitarra'],
          feedback: {
            rule: 'Hartes g vor i schreibt man `gui`; der gerollte Laut zwischen Vokalen ist `rr`.',
            why: '„gitarra“ würde „chi-TA-rra“ klingen; mit einem r wäre es nur ein kurzer Schlag.',
            avoid: 'Hartes g vor e/i → gu. Gerolltes r zwischen Vokalen → rr.',
          },
        },
        {
          id: 'es.g.alphabet-sounds.L3.04',
          type: 'speak',
          skills: ['pronunciation', 'speaking'],
          topicIds: ['es.g.alphabet-sounds'],
          difficulty: 3,
          text: 'Jorge toca la guitarra.',
          german: 'Jorge spielt Gitarre.',
          phonetic: 'CHOR-che TO-ka la gi-TA-rra',
          ipa: '[ˈxoɾ.xe ˈto.ka la ɣiˈta.ra]',
          pronItemId: 'es.p.j.guitarra',
          feedback: {
            rule: '`j` und `g` vor e = rauer ch-Laut; `gui` = hartes g; `rr` gerollt.',
            why: 'In `Jorge` stecken zwei ch-Laute – Deutschsprachige sprechen das zweite oft als hartes g.',
            avoid: 'Übe `Jorge` isoliert: „CHOR – che“, beide Male rau aus dem Rachen.',
          },
        },
      ],
    },
  ],
  related: ['es.g.stress'],
};
