import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.articles',
  courseId: 'es',
  stageId: 'stage0',
  order: 8,
  category: 'Artikel & Nomen',
  title: 'Artikel – el, la, un, una',
  summary: 'Bestimmte und unbestimmte Artikel, die Verschmelzungen al und del – und wann der Artikel im Spanischen anders als im Deutschen steht.',
  keywords: [
    'Artikel', 'bestimmter Artikel', 'unbestimmter Artikel', 'el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas',
    'al', 'del', 'der die das', 'ein eine', 'Genus', 'männlich', 'weiblich', 'el agua',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Spanisch hat nur **zwei** Geschlechter: männlich und weiblich – kein Neutrum. Dafür gibt es keine Fälle: Der Artikel bleibt gleich, egal ob Subjekt oder Objekt (kein „der/den/dem/des“).',
    },
    {
      type: 'table',
      title: 'Die Artikel',
      headers: ['', 'männlich Sg.', 'weiblich Sg.', 'männlich Pl.', 'weiblich Pl.'],
      rows: [
        ['bestimmt (der/die)', 'el', 'la', 'los', 'las'],
        ['unbestimmt (ein/eine)', 'un', 'una', 'unos', 'unas'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'El', role: 'article' },
        { text: ' chico', role: 'noun' },
        { text: ' y ' },
        { text: 'la', role: 'article' },
        { text: ' chica', role: 'noun' },
        { text: ' tienen', role: 'verb' },
        { text: ' unos', role: 'article' },
        { text: ' libros', role: 'noun' },
        { text: '.' },
      ],
      german: 'Der Junge und das Mädchen haben ein paar Bücher.',
    },
    {
      type: 'text',
      md: '**Verschmelzungen:** `a` + `el` = `al`, `de` + `el` = `del`. Mit `la`, `los`, `las` verschmilzt nichts.\n- `Voy al centro.` (Ich gehe ins Zentrum.)\n- `la casa del profesor` (das Haus des Lehrers)\n- aber: `la casa de la profesora`',
    },
    {
      type: 'text',
      md: '`unos`/`unas` bedeutet „ein paar, einige“: `unos amigos` = ein paar Freunde. Oft lässt man den Artikel im Plural ganz weg: `Tengo amigos en Chile.`',
    },
    {
      type: 'mistake',
      wrong: 'la problema',
      right: 'el problema',
      why: 'Nicht jedes Wort auf -a ist weiblich. Viele Wörter auf **-ma** aus dem Griechischen sind männlich: `el problema`, `el tema`, `el idioma`, `el sistema`. Auch `el día` und `el mapa`.',
    },
    {
      type: 'tip',
      md: 'Weibliche Wörter, die mit **betontem a-** beginnen, bekommen im Singular `el` statt `la`, bleiben aber weiblich: `el agua fría`, aber `las aguas`. So stoßen nicht zwei a aufeinander.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika sagt man zu manchen Alltagsdingen andere Wörter – das Genus bleibt Lernstoff: `el jugo` (Saft, Spanien: `el zumo`), `la computadora` (Computer, Spanien: `el ordenador`), `el celular` (Handy, Spanien: `el móvil`).',
    },
    { type: 'audio', text: 'El café, la leche y el agua, por favor.', label: 'Artikel im Satz anhören' },
  ],
  examples: [
    {
      target: 'el libro y la mesa',
      german: 'das Buch und der Tisch',
      parts: [
        { text: 'el', role: 'article' },
        { text: ' libro', role: 'noun' },
        { text: ' y ' },
        { text: 'la', role: 'article' },
        { text: ' mesa', role: 'noun' },
      ],
      note: 'Das Genus stimmt oft nicht mit dem Deutschen überein!',
    },
    { target: 'un café y una cerveza', german: 'ein Kaffee und ein Bier' },
    { target: 'los chicos y las chicas', german: 'die Jungen und die Mädchen' },
    { target: 'Hay unas sillas en el patio.', german: 'Im Hof gibt es ein paar Stühle.' },
    {
      target: 'Vamos al mercado.',
      german: 'Wir gehen auf den Markt.',
      parts: [
        { text: 'Vamos', role: 'verb' },
        { text: ' al', role: 'preposition' },
        { text: ' mercado', role: 'noun' },
        { text: '.' },
      ],
      note: '`a` + `el` = `al`.',
    },
    { target: 'la casa del profesor', german: 'das Haus des Lehrers' },
    { target: 'el agua fría', german: 'das kalte Wasser', note: '`agua` ist weiblich, bekommt aber `el` (betontes a-).' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'la leche · el sol · la luna',
      german: 'die Milch · die Sonne · der Mond',
      md: 'Das Genus stimmt oft **nicht** mit dem Deutschen überein – lerne jedes Nomen mit Artikel.',
    },
    {
      type: 'compare',
      target: 'el libro',
      german: 'das Buch',
      md: 'Ein Neutrum gibt es nicht. Deutsche „das“-Wörter sind im Spanischen männlich oder weiblich.',
    },
    {
      type: 'compare',
      target: 'Veo al perro. / Veo el libro.',
      german: 'Ich sehe den Hund. / Ich sehe das Buch.',
      md: 'Keine Fälle: `el` bleibt `el` – kein „den/dem“. (Das `a` vor dem Hund ist ein Extra bei Lebewesen, das du später lernst.)',
    },
    {
      type: 'compare',
      target: 'Me gusta el café.',
      german: 'Ich mag Kaffee.',
      md: 'Bei allgemeinen Aussagen steht im Spanischen **mit** Artikel, wo Deutsch ihn weglässt.',
    },
    {
      type: 'compare',
      target: 'el señor López',
      german: 'Herr López',
      md: 'Wenn man **über** jemanden spricht, steht vor señor/señora ein Artikel – in der direkten Anrede nicht: `Buenos días, señor López.`',
    },
  ],
  mistakes: [
    { wrong: 'la problema', right: 'el problema', why: 'Wörter auf -ma griechischen Ursprungs sind männlich.' },
    { wrong: 'Voy a el centro.', right: 'Voy al centro.', why: '`a` + `el` verschmilzt immer zu `al`.' },
    { wrong: 'el libro de el profesor', right: 'el libro del profesor', why: '`de` + `el` verschmilzt immer zu `del`.' },
    { wrong: 'Me gusta café.', right: 'Me gusta el café.', why: 'Allgemeine Vorlieben stehen mit bestimmtem Artikel.' },
    { wrong: 'la agua', right: 'el agua', why: 'Betontes a- am Anfang: im Singular `el`, das Wort bleibt aber weiblich (`el agua fría`).' },
  ],
  mnemonic: '**Kein Neutrum, keine Fälle – aber a + el = al und de + el = del.**',
  levels: [
    {
      level: 1,
      title: 'Den richtigen Artikel wählen',
      exercises: [
        {
          id: 'es.g.articles.L1.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.articles'],
          difficulty: 1,
          prompt: 'Welcher Artikel passt zu `casa` (Haus)?',
          options: [
            { text: 'el', why: '`el` steht vor männlichen Nomen.' },
            { text: 'la', why: 'Richtig: `casa` endet auf -a und ist weiblich.' },
            { text: 'los', why: '`los` ist männlich Plural.' },
          ],
          answer: 1,
          feedback: {
            rule: 'Nomen auf -a sind meist weiblich → `la`.',
            why: 'Das deutsche „das Haus“ hilft nicht – Spanisch hat kein Neutrum.',
            avoid: 'Lerne jedes Nomen gleich mit Artikel: `la casa`.',
          },
        },
        {
          id: 'es.g.articles.L1.02',
          type: 'imageMatch',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.articles'],
          difficulty: 1,
          instruction: 'Ordne Bild und Wort (mit Artikel) zu.',
          pairs: [
            { emoji: '📖', word: 'el libro' },
            { emoji: '🏠', word: 'la casa' },
            { emoji: '☀️', word: 'el sol' },
            { emoji: '🌙', word: 'la luna' },
            { emoji: '💧', word: 'el agua' },
          ],
          feedback: {
            rule: 'el libro, la casa, el sol, la luna, el agua (weiblich, aber mit el).',
            why: 'Sonne und Mond haben im Spanischen das umgekehrte Genus wie im Deutschen.',
            avoid: 'Merke: `el sol` und `la luna` – genau andersherum als im Deutschen.',
          },
        },
        {
          id: 'es.g.articles.L1.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 1,
          sentence: 'Quiero ___ café y ___ cerveza, por favor.',
          german: 'Ich möchte einen Kaffee und ein Bier, bitte.',
          answers: [['un'], ['una']],
          bank: ['un', 'una', 'unos'],
          feedback: {
            rule: 'unbestimmter Artikel: `un` (männlich), `una` (weiblich).',
            why: '`café` ist männlich, `cerveza` weiblich – im Deutschen „das Bier“, im Spanischen `la cerveza`.',
            avoid: 'Endung -a → meist `una`, sonst prüfen.',
          },
        },
        {
          id: 'es.g.articles.L1.04',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.articles'],
          difficulty: 1,
          instruction: 'Welcher Plural gehört zu welchem Singular?',
          pairs: [
            { left: 'el', right: 'los' },
            { left: 'la', right: 'las' },
            { left: 'un', right: 'unos' },
            { left: 'una', right: 'unas' },
          ],
          feedback: {
            rule: 'el → los, la → las, un → unos, una → unas.',
            why: '`el` und `un` bekommen im Plural nicht einfach nur ein -s: `el` → `los`, `un` → `unos`.',
            avoid: 'Merke: `el` wird zu `los` (nicht „els“).',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Verschmelzungen & Ausnahmen',
      exercises: [
        {
          id: 'es.g.articles.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 2,
          sentence: 'Voy ___ centro y después ___ playa.',
          german: 'Ich gehe ins Zentrum und danach an den Strand.',
          answers: [['al'], ['a la']],
          bank: ['al', 'a el', 'a la'],
          feedback: {
            rule: '`a` + `el` = `al`; mit `la` verschmilzt nichts: `a la playa`.',
            why: '`a el` gibt es nicht; `centro` ist männlich, `playa` weiblich.',
            avoid: 'Nur der männliche Singular-Artikel `el` verschmilzt.',
          },
        },
        {
          id: 'es.g.articles.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 2,
          sentence: 'Es la casa ___ profesor.',
          german: 'Es ist das Haus des Lehrers.',
          answers: [['del']],
          bank: ['de el', 'del', 'de la'],
          feedback: {
            rule: '`de` + `el` = `del`.',
            why: '`de el` wird im Spanischen immer zusammengezogen; `de la` passt nicht zu `profesor`.',
            avoid: 'Sobald `de el` oder `a el` entsteht: zusammenziehen.',
          },
        },
        {
          id: 'es.g.articles.L2.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.articles'],
          difficulty: 2,
          prompt: 'Welcher Ausdruck ist korrekt?',
          options: [
            { text: 'la problema', why: '`problema` ist männlich, obwohl es auf -a endet.' },
            { text: 'el problema', why: 'Richtig: Wörter auf -ma griechischen Ursprungs sind männlich.' },
            { text: 'lo problema', why: '`lo` ist kein Artikel für Nomen.' },
          ],
          answer: 1,
          feedback: {
            rule: '`el problema`, `el tema`, `el idioma`, `el sistema`, `el programa` – männlich trotz -a.',
            why: 'Die Regel „-a = weiblich“ hat bekannte Ausnahmen.',
            avoid: 'Lerne die -ma-Wörter als eigene Gruppe.',
          },
        },
        {
          id: 'es.g.articles.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 2,
          sentence: 'Vamos a el mercado.',
          german: 'Wir gehen auf den Markt.',
          answers: ['Vamos al mercado.'],
          feedback: {
            rule: '`a` + `el` = `al`.',
            why: '`a el` ist im geschriebenen und gesprochenen Spanisch falsch.',
            avoid: 'Nur bei `el` verschmelzen: `a la playa` bleibt getrennt.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Artikel wie Muttersprachler',
      exercises: [
        {
          id: 'es.g.articles.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Ich mag Kaffee.',
          answers: ['Me gusta el café.', 'A mí me gusta el café.'],
          feedback: {
            rule: 'Allgemeine Vorlieben stehen mit bestimmtem Artikel: `el café`.',
            why: '„Me gusta café“ fehlt der Artikel – im Deutschen steht keiner, im Spanischen schon.',
            avoid: 'Nach `me gusta` fast immer `el/la/los/las`.',
          },
        },
        {
          id: 'es.g.articles.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 3,
          sentence: '___ agua está muy ___.',
          german: 'Das Wasser ist sehr kalt.',
          answers: [['El'], ['fría']],
          bank: ['El', 'La', 'frío', 'fría'],
          feedback: {
            rule: 'Betontes a- am Wortanfang: im Singular `el` – das Wort bleibt aber weiblich, also `fría`.',
            why: '`la agua` ist falsch (das a von `la` und das betonte a- von `agua` stoßen zusammen); `frío` ist falsch, weil `agua` weiblich ist.',
            avoid: 'Adjektive verraten das echte Genus: `el agua fría`, im Plural `las aguas`.',
          },
        },
        {
          id: 'es.g.articles.L3.03',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 3,
          tokens: ['El', 'hotel', 'está', 'al', 'lado', 'del', 'museo.'],
          extra: ['a', 'de', 'la'],
          german: 'Das Hotel ist neben dem Museum.',
          feedback: {
            rule: '`al lado de` + `el museo` → `al lado del museo`.',
            why: 'Die getrennten Formen `a el` / `de el` gibt es nicht.',
            avoid: 'Zweimal zusammenziehen: `al` und `del`.',
          },
        },
        {
          id: 'es.g.articles.L3.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.articles'],
          difficulty: 3,
          sentence: 'La tema de la clase es interesante.',
          german: 'Das Thema des Unterrichts ist interessant.',
          answers: ['El tema de la clase es interesante.'],
          feedback: {
            rule: '`tema` ist männlich: `el tema`.',
            why: 'Wie `problema`, `idioma`, `sistema` – griechische -ma-Wörter sind männlich.',
            avoid: 'Bei -ma am Ende kurz innehalten: Ist es ein -ma-Wort griechischen Ursprungs?',
          },
        },
      ],
    },
  ],
  related: ['es.g.gender-plural', 'es.g.adjectives', 'es.g.hay'],
};
