import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.demonstratives',
  courseId: 'es',
  stageId: 'a1',
  order: 11,
  category: 'Pronomen',
  title: 'Este, ese, aquel – dieser, der da, jener',
  summary: 'Drei Entfernungen statt zwei: este (hier bei mir), ese (da bei dir), aquel (dort drüben) – mit Genus und Zahl. Dazu das neutrale esto/eso für „das“.',
  keywords: [
    'Demonstrativ', 'Demonstrativpronomen', 'Demonstrativbegleiter', 'hinweisend', 'dieser', 'diese', 'dieses', 'jener', 'der da',
    'este', 'esta', 'estos', 'estas', 'ese', 'esa', 'esos', 'esas', 'aquel', 'aquella', 'aquellos', 'aquellas', 'esto', 'eso',
    'aquello', 'aquí', 'ahí', 'allí', 'hier', 'da', 'dort', 'Entfernung', 'Einkaufen', 'Kleidung', 'esta vs. está',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Spanisch zeigt mit **drei Entfernungsstufen** auf Dinge – passend zu den Ortswörtern `aquí` (hier), `ahí` (da) und `allí` (dort):\n- `este` – nah bei mir (hier)\n- `ese` – nah bei dir oder etwas weiter weg (da)\n- `aquel` – weit weg von uns beiden (dort drüben)',
    },
    {
      type: 'table',
      title: 'Alle Formen',
      headers: ['', 'hier (aquí)', 'da (ahí)', 'dort (allí)'],
      rows: [
        ['männlich Singular', 'este', 'ese', 'aquel'],
        ['weiblich Singular', 'esta', 'esa', 'aquella'],
        ['männlich Plural', 'estos', 'esos', 'aquellos'],
        ['weiblich Plural', 'estas', 'esas', 'aquellas'],
        ['neutral („das“)', 'esto', 'eso', 'aquello'],
      ],
    },
    {
      type: 'text',
      md: 'Die Formen passen sich wie Adjektive an das Nomen an: `este vestido`, `esta camiseta`, `estos zapatos`, `estas camisas`. Sie können auch **allein** stehen, wenn klar ist, was gemeint ist: `Quiero esta.` (Ich möchte diese hier.) – heute ohne Akzent geschrieben.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Esta', role: 'pronoun' },
        { text: ' camiseta', role: 'noun' },
        { text: ' es', role: 'verb' },
        { text: ' bonita', role: 'adjective' },
        { text: ', pero ' },
        { text: 'esos', role: 'pronoun' },
        { text: ' pantalones', role: 'noun' },
        { text: ' son', role: 'verb' },
        { text: ' caros', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Dieses T-Shirt (hier) ist schön, aber die Hose da ist teuer.',
    },
    {
      type: 'text',
      md: '**esto, eso, aquello** sind neutral. Sie stehen **nie vor einem Nomen**, sondern allein – für Dinge, deren Namen man nicht kennt oder nicht nennt, und für ganze Situationen: `¿Qué es esto?` (Was ist das?), `Eso es.` (Genau.), `Eso no es verdad.` (Das stimmt nicht.)',
    },
    {
      type: 'mistake',
      wrong: 'Me gusta esto vestido.',
      right: 'Me gusta este vestido.',
      why: '`esto` steht nie vor einem Nomen. Vor `vestido` (männlich) steht `este`.',
    },
    {
      type: 'mistake',
      wrong: 'La camiseta esta aquí.',
      right: 'La camiseta está aquí.',
      why: '`esta` (diese) und `está` (ist) klingen verschieden: `ES-ta` vs. `es-TÁ`. Das Verb braucht den Akzent.',
    },
    {
      type: 'text',
      md: '**Mit Zeitangaben** bedeutet `este/esta` „dieser/diese … hier“ im Sinne von „jetzt“: `esta semana` (diese Woche), `este año` (dieses Jahr), `esta noche` (heute Abend), `esta mañana` (heute Morgen).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika sagt man statt `aquí/allí` oft `acá/allá`: `Ese restaurante de allá es muy bueno.` Im lockeren Gespräch ersetzt `ese` außerdem häufig `aquel` – `aquel` klingt etwas gehobener, ist aber überall verständlich.',
    },
    { type: 'tip', md: '**Mit t – ganz dicht (este). Ohne t – bei dir (ese). aquel – der längste Weg, das längste Wort.**' },
    { type: 'audio', text: 'Este vestido es bonito, ese es caro y aquel es perfecto.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: 'Esta camiseta es muy bonita.',
      german: 'Dieses T-Shirt ist sehr schön.',
      parts: [
        { text: 'Esta', role: 'pronoun' },
        { text: ' camiseta', role: 'noun' },
        { text: ' es', role: 'verb' },
        { text: ' muy bonita', role: 'adjective' },
        { text: '.' },
      ],
    },
    {
      target: '¿Cuánto cuestan esos zapatos?',
      german: 'Was kosten die Schuhe da?',
      parts: [
        { text: '¿Cuánto', role: 'question' },
        { text: ' cuestan', role: 'verb' },
        { text: ' esos', role: 'pronoun' },
        { text: ' zapatos', role: 'noun' },
        { text: '?' },
      ],
    },
    { target: 'Aquella casa blanca es de mi abuela.', german: 'Das weiße Haus dort drüben gehört meiner Großmutter.' },
    { target: '—¿Qué es esto? —Es un regalo para ti.', german: '„Was ist das?“ – „Das ist ein Geschenk für dich.“' },
    { target: 'Estos pantalones son muy largos.', german: 'Diese Hose ist sehr lang.', note: '`pantalones` steht im Spanischen meist im Plural – wie die deutsche „Hose“ im Singular.' },
    { target: 'Me gusta ese vestido rojo.', german: 'Mir gefällt das rote Kleid da.' },
    { target: 'Esta semana trabajo mucho.', german: 'Diese Woche arbeite ich viel.' },
    { target: 'Ese restaurante de allá es muy bueno.', german: 'Das Restaurant dort drüben ist sehr gut.', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'este libro · ese libro · aquel libro',
      german: 'dieses Buch · das Buch da · das Buch dort drüben',
      md: 'Im Alltagsdeutsch sagt man meist nur „das hier“ und „das da“. Spanisch unterscheidet drei Entfernungen – wie hier, da, dort.',
    },
    {
      type: 'compare',
      target: '¿Qué es esto?',
      german: 'Was ist das?',
      md: 'Für Unbekanntes ohne Nomen: `esto/eso` (neutral) – nie `este`.',
    },
    {
      type: 'compare',
      target: 'esta noche · esta mañana',
      german: 'heute Abend · heute Morgen',
      md: 'Das deutsche „heute“ wird bei Tageszeiten oft zu `esta …`.',
    },
    {
      type: 'compare',
      target: 'estos pantalones',
      german: 'diese Hose',
      md: 'Nicht jedes Nomen hat dieselbe Zahl: `los pantalones` (Plural) = die Hose (Singular). Der Demonstrativ folgt dem spanischen Nomen.',
    },
  ],
  mistakes: [
    { wrong: 'este camiseta', right: 'esta camiseta', why: '`camiseta` ist weiblich → `esta`.' },
    { wrong: 'esto libro', right: 'este libro', why: '`esto` steht nie vor einem Nomen.' },
    { wrong: 'estes zapatos', right: 'estos zapatos', why: 'Männlicher Plural: `estos` (nicht „estes“).' },
    { wrong: 'aquel casa', right: 'aquella casa', why: 'Weiblich: `aquella`.' },
    { wrong: 'La tienda esta cerca.', right: 'La tienda está cerca.', why: 'Das Verb `está` hat einen Akzent; `esta` heißt „diese“.' },
  ],
  mnemonic: '**Mit t – ganz dicht (este). Ohne t – bei dir (ese). aquel – weit weg.**',
  levels: [
    {
      level: 1,
      title: 'Formen und Entfernungen',
      exercises: [
        {
          id: 'es.g.demonstratives.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 1,
          instruction: 'Welche Form passt zu welchem Ort?',
          pairs: [
            { left: 'aquí (hier bei mir)', right: 'este' },
            { left: 'ahí (da bei dir)', right: 'ese' },
            { left: 'allí (dort drüben)', right: 'aquel' },
          ],
          feedback: {
            rule: 'este ↔ aquí, ese ↔ ahí, aquel ↔ allí.',
            why: '`ese` und `aquel` werden oft verwechselt: `aquel` ist weit weg von beiden Sprechern.',
            avoid: 'Mit t – ganz dicht; ohne t – bei dir; aquel – weit weg.',
          },
        },
        {
          id: 'es.g.demonstratives.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 1,
          sentence: '___ camiseta es bonita.',
          german: 'Dieses T-Shirt (hier) ist schön.',
          answers: [['Esta']],
          bank: ['Este', 'Esta', 'Esto'],
          feedback: {
            rule: '`la camiseta` ist weiblich → `esta`.',
            why: '`este` ist männlich, `esto` steht nie vor Nomen.',
            avoid: 'Erst den Artikel denken: la camiseta → esta camiseta.',
          },
        },
        {
          id: 'es.g.demonstratives.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 1,
          prompt: 'Welche Form passt? „___ zapatos“ (die Schuhe da bei dir)',
          options: [
            { text: 'esos', why: 'Richtig: männlich Plural, Entfernung „da“.' },
            { text: 'esas', why: '`zapatos` ist männlich.' },
            { text: 'eso', why: '`eso` ist neutral und steht nie vor Nomen.' },
            { text: 'estos', why: '`estos` wären die Schuhe hier bei mir.' },
          ],
          answer: 0,
          feedback: {
            rule: 'ese → esos (m. Pl.), esa → esas (f. Pl.).',
            why: 'Plural von `ese` ist `esos`, nicht „eses“.',
            avoid: 'Die Pluralformen enden auf -os/-as wie Adjektive.',
          },
        },
        {
          id: 'es.g.demonstratives.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 1,
          audio: 'Quiero aquella camiseta, la azul.',
          question: 'Wo ist das T-Shirt, das die Person möchte?',
          options: ['weiter weg, dort drüben', 'direkt bei der Person selbst', 'die Person trägt es schon'],
          answer: 0,
          feedback: {
            rule: '`aquella` = weit weg von beiden Sprechern.',
            why: 'Nah bei der Person selbst wäre `esta`.',
            avoid: 'aquel/aquella – das längste Wort für die weiteste Entfernung.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Genus, Zahl und neutral',
      exercises: [
        {
          id: 'es.g.demonstratives.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 2,
          sentence: '¿Cuánto cuestan ___ pantalones?',
          german: 'Was kostet die Hose da (bei dir)?',
          answers: [['esos']],
          bank: ['esos', 'esas', 'eso', 'ese'],
          feedback: {
            rule: '`los pantalones` → männlich Plural → `esos`.',
            why: 'Im Deutschen ist „die Hose“ weiblich und Singular – im Spanischen männlich und Plural.',
            avoid: 'Richte dich immer nach dem spanischen Nomen.',
          },
        },
        {
          id: 'es.g.demonstratives.L2.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 2,
          prompt: 'Welcher Satz bedeutet „Das T-Shirt ist hier“?',
          options: [
            { text: 'La camiseta está aquí.', why: 'Richtig: `está` = ist (Verb, mit Akzent).' },
            { text: 'La camiseta esta aquí.', why: 'Ohne Akzent ist `esta` = diese – dann fehlt das Verb.' },
            { text: 'La camiseta este aquí.', why: '`este` ist ein Demonstrativ (dieser), kein Verb.' },
          ],
          answer: 0,
          feedback: {
            rule: '`está` (Verb estar) trägt einen Akzent und wird hinten betont.',
            why: '`esta` ohne Akzent wird vorne betont und heißt „diese“.',
            avoid: 'Sprich laut: es-TÁ (ist) vs. ES-ta (diese).',
          },
        },
        {
          id: 'es.g.demonstratives.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 2,
          sentence: 'Me gusta esto vestido.',
          german: 'Mir gefällt dieses Kleid.',
          answers: ['Me gusta este vestido.'],
          feedback: {
            rule: 'Vor einem männlichen Nomen: `este`. `esto` steht nie vor Nomen.',
            why: '`esto` ist die neutrale Form für „das (hier)“ ohne Nomen.',
            avoid: 'Folgt ein Nomen? → este/esta/estos/estas.',
          },
        },
        {
          id: 'es.g.demonstratives.L2.04',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 2,
          sentence: '___ semana trabajo mucho, pero ___ fin de semana voy a la playa.',
          german: 'Diese Woche arbeite ich viel, aber dieses Wochenende fahre ich an den Strand.',
          answers: [['Esta'], ['este']],
          bank: ['Esta', 'este', 'esto', 'estos'],
          feedback: {
            rule: '`la semana` → `esta semana`; `el fin de semana` → `este fin de semana`.',
            why: '`esto` ist neutral und passt nie vor ein Nomen.',
            avoid: 'Zeitangaben mit este/esta = „diese/dieses … (jetzt)“.',
          },
        },
        {
          id: 'es.g.demonstratives.L2.05',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Was ist das?',
          answers: ['¿Qué es esto?', '¿Qué es eso?', '¿Qué es aquello?'],
          feedback: {
            rule: 'Für ein unbekanntes Ding: neutral `esto` / `eso` / `aquello`.',
            why: '`¿Qué es este?` ist falsch – ohne Nomen und bei Unbekanntem steht die neutrale Form.',
            avoid: 'Unbekannt → neutral: esto, eso, aquello.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Im Geschäft',
      exercises: [
        {
          id: 'es.g.demonstratives.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Diese Schuhe (hier) sind sehr schön.',
          answers: ['Estos zapatos son muy bonitos.', 'Estos zapatos son muy lindos.'],
          feedback: {
            rule: '`los zapatos` → `estos`; das Adjektiv passt sich ebenfalls an: `bonitos`.',
            why: '`Estas` wäre weiblich, `Esos` die Schuhe da bei dir.',
            avoid: 'Demonstrativ, Nomen und Adjektiv – alle drei im gleichen Genus und in der gleichen Zahl.',
          },
        },
        {
          id: 'es.g.demonstratives.L3.02',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 3,
          tokens: ['Aquella', 'casa', 'blanca', 'es', 'muy', 'grande', '.'],
          german: 'Das weiße Haus dort drüben ist sehr groß.',
          feedback: {
            rule: 'Demonstrativ vor dem Nomen, Farbadjektiv danach: `aquella casa blanca`.',
            why: 'Farben stehen im Spanischen hinter dem Nomen.',
            avoid: 'Reihenfolge: aquella + Nomen + Farbe.',
          },
        },
        {
          id: 'es.g.demonstratives.L3.03',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 3,
          scenario: 'Die Verkäuferin hält ein Kleid in der Hand. Du fragst nach dem Preis genau dieses Kleides.',
          options: [
            { text: '¿Cuánto cuesta ese vestido?', why: 'Richtig: Das Kleid ist bei ihr (da) → `ese`.' },
            { text: '¿Cuánto cuesta este vestido?', why: '`este` wäre ein Kleid, das du selbst in der Hand hältst.' },
            { text: '¿Cuánto cuesta eso vestido?', why: '`eso` steht nie vor einem Nomen.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Bei der anderen Person → `ese/esa`.',
            why: 'Die Entfernung zählt vom Sprecher aus.',
            avoid: 'hier bei mir → este · da bei dir → ese.',
          },
        },
        {
          id: 'es.g.demonstratives.L3.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 3,
          sentence: 'Estas pantalones son caros.',
          german: 'Diese Hose ist teuer.',
          answers: ['Estos pantalones son caros.'],
          feedback: {
            rule: '`los pantalones` ist männlich → `estos`.',
            why: 'Das deutsche „die Hose“ verleitet zur weiblichen Form.',
            avoid: 'Schau auf das Adjektiv: `caros` zeigt schon männlich Plural.',
          },
        },
        {
          id: 'es.g.demonstratives.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.demonstratives'],
          difficulty: 3,
          prompt: 'Du bist in einem Kleidungsgeschäft. Zeig auf drei Dinge in verschiedener Entfernung und sag, was dir gefällt oder was es kostet.',
          keywords: ['este', 'esta', 'estos', 'estas', 'ese', 'esa', 'esos', 'esas', 'aquel', 'aquella', 'aquellos', 'aquellas'],
          minMatch: 2,
          sample: 'Me gusta esta camiseta. ¿Cuánto cuestan esos pantalones? Y aquel vestido, ¿qué talla es?',
          feedback: {
            rule: 'este (hier), ese (da), aquel (dort) – immer passend zum Nomen.',
            why: 'Häufig passt die Form nicht zum Genus (`este camiseta`).',
            avoid: 'Denk zuerst an den Artikel: la camiseta → esta.',
          },
        },
      ],
    },
  ],
  related: ['es.g.gender-plural', 'es.g.adjectives', 'es.g.prepositions-place'],
};
