import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.estar',
  courseId: 'es',
  stageId: 'stage0',
  order: 6,
  category: 'Verben',
  title: 'Estar – wo und wie du bist',
  summary: 'Das zweite „sein“: estar für Ort, Befinden und vorübergehende Zustände – mit allen Formen.',
  keywords: [
    'estar', 'sein', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'Ort', 'Befinden', 'Zustand', 'Gefühl',
    'wie geht es', 'cómo estás', 'bien', 'mal', 'cansado', 'wo ist', 'dónde está',
  ],
  explanation: [
    {
      type: 'text',
      md: '`estar` beschreibt, **wo** sich etwas befindet und **wie** es jemandem gerade geht. Es geht um die aktuelle Lage – nicht um die Identität.',
    },
    {
      type: 'conjugation',
      verb: 'estar',
      translation: 'sein, sich befinden',
      tense: 'Präsens (unregelmäßig in der yo-Form, Akzente beachten)',
      rows: [
        { person: 'yo', form: 'estoy', ending: 'oy' },
        { person: 'tú', form: 'estás', ending: 'ás' },
        { person: 'él / ella / usted', form: 'está', ending: 'á' },
        { person: 'nosotros / nosotras', form: 'estamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'estáis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'están', ending: 'án' },
      ],
    },
    {
      type: 'table',
      title: 'Wofür man estar benutzt',
      headers: ['Verwendung', 'Beispiel', 'Deutsch'],
      rows: [
        ['Befinden', '¿Cómo estás? – Estoy bien.', 'Wie geht es dir? – Mir geht es gut.'],
        ['Ort / Lage', 'Estoy en casa.', 'Ich bin zu Hause.'],
        ['Lage von Orten', 'Sevilla está en Andalucía.', 'Sevilla liegt in Andalusien.'],
        ['vorübergehender Zustand', 'Estoy cansada.', 'Ich bin müde.'],
        ['Stimmung', 'Pablo está contento.', 'Pablo ist froh.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Hoy', role: 'adverb' },
        { text: ' estoy', role: 'verb' },
        { text: ' en', role: 'preposition' },
        { text: ' Madrid', role: 'noun' },
        { text: ' y ' },
        { text: 'estoy', role: 'verb' },
        { text: ' muy', role: 'adverb' },
        { text: ' contento', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Heute bin ich in Madrid und ich bin sehr froh.',
    },
    {
      type: 'text',
      md: 'Achte auf die **Akzente**: `está` (er/sie ist) wird hinten betont. Ohne Akzent ist `esta` ein anderes Wort („diese“). `bien` (gut) ist ein Adverb und bleibt immer gleich: `Estamos bien.`',
    },
    {
      type: 'mistake',
      wrong: 'Estoy bueno.',
      right: 'Estoy bien.',
      why: 'Auf „Wie geht’s?“ antwortest du mit dem Adverb `bien`. `Estoy bueno` heißt umgangssprachlich „Ich bin heiß/attraktiv“ – peinlich!',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: `¿Dónde estáis?` – „Wo seid ihr?“ (vosotros).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: `¿Dónde están?` (ustedes). Unter Freunden hörst du in Mexiko neben `¿Cómo estás?` auch locker `¿Qué onda?`, in Argentinien `¿Cómo andás?` – die Grundform mit estar verstehen aber alle.',
    },
    { type: 'tip', md: '**Wie du dich fühlst und wo du bist, das sagst du mit estar.**' },
    { type: 'audio', text: '¿Dónde estás? – Estoy en casa, pero estoy muy cansada.', label: 'Mini-Dialog anhören' },
  ],
  examples: [
    { target: '¿Cómo estás?', german: 'Wie geht es dir?' },
    {
      target: 'Estoy bien, gracias.',
      german: 'Mir geht es gut, danke.',
      parts: [{ text: 'Estoy', role: 'verb' }, { text: ' bien', role: 'adverb' }, { text: ', gracias.' }],
    },
    {
      target: 'El museo está en el centro.',
      german: 'Das Museum ist (liegt) im Zentrum.',
      parts: [
        { text: 'El', role: 'article' },
        { text: ' museo', role: 'subject' },
        { text: ' está', role: 'verb' },
        { text: ' en', role: 'preposition' },
        { text: ' el', role: 'article' },
        { text: ' centro', role: 'noun' },
        { text: '.' },
      ],
    },
    { target: 'Estamos en la playa.', german: 'Wir sind am Strand.' },
    { target: 'Laura está cansada hoy.', german: 'Laura ist heute müde.' },
    { target: '¿Dónde está el baño?', german: 'Wo ist die Toilette?' },
    { target: '¿Estáis bien, chicas?', german: 'Geht es euch gut, Mädels?', variant: 'es-ES' },
    { target: '¿Están bien, chicas?', german: 'Geht es euch gut, Mädels?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Estoy bien.',
      german: 'Mir geht es gut.',
      md: 'Deutsch sagt „es geht mir“, Spanisch „ich bin gut (dran)“ – mit `estar` + `bien`.',
    },
    {
      type: 'compare',
      target: 'Berlín está en Alemania.',
      german: 'Berlin liegt in Deutschland.',
      md: 'Für „liegen/sich befinden“ nimmt Spanisch einfach `estar`.',
    },
    {
      type: 'compare',
      target: 'Estoy en casa.',
      german: 'Ich bin zu Hause.',
      md: '„zu Hause“ = `en casa` – ohne Artikel, wenn das eigene Zuhause gemeint ist.',
    },
    {
      type: 'text',
      md: 'Im Deutschen reicht „sein“ für alles. Frag dich im Spanischen: **Wo?** oder **Wie geht es gerade?** → `estar`. **Wer/was?** → `ser`.',
    },
  ],
  mistakes: [
    { wrong: 'Soy cansado.', right: 'Estoy cansado.', why: 'Müdigkeit ist ein momentaner Zustand → `estar`.' },
    { wrong: 'Madrid es en España.', right: 'Madrid está en España.', why: 'Die Lage eines Ortes drückt man mit `estar` aus.' },
    { wrong: 'Estoy bueno.', right: 'Estoy bien.', why: 'Befinden mit dem Adverb `bien`; `bueno` beschreibt Eigenschaften (und ist hier missverständlich).' },
    { wrong: 'Yo esto en casa.', right: 'Yo estoy en casa.', why: 'Die yo-Form ist unregelmäßig: `estoy` (wie `soy`, `voy`).' },
  ],
  mnemonic: '**Wie du dich fühlst und wo du bist, das sagst du mit estar.**',
  levels: [
    {
      level: 1,
      title: 'Formen kennen',
      exercises: [
        {
          id: 'es.g.estar.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.estar'],
          difficulty: 1,
          instruction: 'Welche Form gehört zu welchem Pronomen?',
          pairs: [
            { left: 'yo', right: 'estoy' },
            { left: 'tú', right: 'estás' },
            { left: 'usted', right: 'está' },
            { left: 'nosotras', right: 'estamos' },
            { left: 'ustedes', right: 'están' },
          ],
          feedback: {
            rule: 'estar: estoy, estás, está, estamos, (estáis), están.',
            why: '`usted` steht mit der 3. Person Singular (`está`), `ustedes` mit dem Plural (`están`).',
            avoid: 'Die yo-Form endet auf -oy wie bei `soy`.',
          },
        },
        {
          id: 'es.g.estar.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 1,
          sentence: '—¿Cómo estás? —___ bien, gracias.',
          german: '„Wie geht es dir?“ – „Mir geht es gut, danke.“',
          answers: [['Estoy']],
          bank: ['Estoy', 'Soy', 'Está'],
          feedback: {
            rule: 'Befinden → `estar`; für dich selbst `estoy`.',
            why: '`soy` (ser) beschreibt Identität, `está` ist die er/sie-Form.',
            avoid: 'Die Frage enthält schon das Verb: `estás` → Antwort `estoy`.',
          },
        },
        {
          id: 'es.g.estar.L1.03',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.estar'],
          difficulty: 1,
          audio: 'Estamos en el hotel.',
          question: 'Wo sind die Sprechenden?',
          options: ['im Hotel', 'am Strand', 'zu Hause'],
          answer: 0,
          feedback: {
            rule: '`estar en` + Ort: `Estamos en el hotel` = Wir sind im Hotel.',
            why: '„am Strand“ wäre `en la playa`, „zu Hause“ `en casa`.',
            avoid: 'Nach `estar en` kommt der Ort – achte auf das Nomen danach.',
          },
        },
        {
          id: 'es.g.estar.L1.04',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.estar'],
          difficulty: 1,
          prompt: 'Welche Antwort passt auf `¿Cómo está usted?`',
          options: [
            { text: 'Estoy bien, gracias.', why: 'Richtig: Befinden mit estar + bien.' },
            { text: 'Soy bien, gracias.', why: '`ser` beschreibt Identität – kein Befinden. `bien` passt nicht zu ser.' },
            { text: 'Estoy bueno, gracias.', why: '`bueno` ist ein Adjektiv – hier missverständlich („attraktiv“).' },
          ],
          answer: 0,
          feedback: {
            rule: 'Befinden: `estar` + `bien`/`mal`/`regular`.',
            why: '`ser bien` gibt es nicht; `estar bueno` bedeutet etwas anderes.',
            avoid: 'Auf `¿Cómo está(s)?` immer mit `Estoy …` antworten.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Ort und Befinden ausdrücken',
      exercises: [
        {
          id: 'es.g.estar.L2.01',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 2,
          verb: 'estar',
          tense: 'Präsens',
          person: 'ella',
          sentence: 'Ella ___ en la oficina.',
          answers: ['está'],
          feedback: {
            rule: 'él/ella/usted → `está` (Betonung auf der letzten Silbe).',
            why: '`estás` wäre die du-Form, `están` der Plural.',
            avoid: 'Akzent nicht vergessen: `está` – ohne ihn wäre es „esta“ (diese).',
          },
        },
        {
          id: 'es.g.estar.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 2,
          sentence: 'Los niños ___ cansados.',
          german: 'Die Kinder sind müde.',
          answers: [['están']],
          bank: ['están', 'son', 'estamos'],
          feedback: {
            rule: 'Momentaner Zustand → `estar`; Plural (ellos) → `están`.',
            why: '`son cansados` ist falsch (Zustand, nicht Eigenschaft), `estamos` wäre „wir“.',
            avoid: 'Adjektive wie cansado, contento, enfermo → fast immer estar.',
          },
        },
        {
          id: 'es.g.estar.L2.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Wo ist das Hotel?',
          answers: ['¿Dónde está el hotel?'],
          feedback: {
            rule: 'Nach dem Ort fragen: `¿Dónde está …?`',
            why: '`¿Dónde es el hotel?` ist falsch – Lage wird mit estar ausgedrückt.',
            avoid: '`dónde` + `estar` – eine feste Kombination.',
          },
        },
        {
          id: 'es.g.estar.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 2,
          sentence: 'Barcelona es en Cataluña.',
          german: 'Barcelona liegt in Katalonien.',
          answers: ['Barcelona está en Cataluña.'],
          feedback: {
            rule: 'Die Lage eines Ortes → `estar`.',
            why: 'Deutsche denken „ist in“ und greifen zu `es`. Für die Lage braucht es aber `está`.',
            avoid: 'Frage dich: Geht es um „wo“? → estar.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Frei anwenden',
      exercises: [
        {
          id: 'es.g.estar.L3.01',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 3,
          tokens: ['Hoy', 'estoy', 'en', 'casa', 'porque', 'estoy', 'enferma.'],
          extra: ['soy', 'la'],
          alternatives: [['Estoy', 'en', 'casa', 'hoy', 'porque', 'estoy', 'enferma.']],
          german: 'Heute bin ich zu Hause, weil ich krank bin. (Eine Frau spricht.)',
          feedback: {
            rule: 'Ort (`en casa`) und Zustand (`enferma`) – beides mit `estar`.',
            why: '`soy` passt zu keinem der beiden; „zu Hause“ heißt `en casa` ohne Artikel.',
            avoid: 'Nach `porque` bleibt die Wortstellung normal – anders als bei „weil“ im Deutschen.',
          },
        },
        {
          id: 'es.g.estar.L3.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 3,
          variant: 'es-ES',
          verb: 'estar',
          tense: 'Präsens',
          person: 'vosotros',
          sentence: '¿Dónde ___ vosotros?',
          answers: ['estáis'],
          feedback: {
            rule: 'vosotros → `estáis`.',
            why: '`están` gehört zu ustedes.',
            avoid: 'vosotros-Endung -áis mit Akzent.',
          },
        },
        {
          id: 'es.g.estar.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Wir sind in Sevilla und es geht uns sehr gut.',
          answers: [
            'Estamos en Sevilla y estamos muy bien.',
            'Nosotros estamos en Sevilla y estamos muy bien.',
            'Nosotras estamos en Sevilla y estamos muy bien.',
            'Estamos en Sevilla y estamos muy bien, gracias.',
          ],
          feedback: {
            rule: 'Ort und Befinden → zweimal `estar`: `estamos en …`, `estamos muy bien`.',
            why: '„es geht uns“ wird nicht wörtlich übersetzt – es heißt „wir sind gut“ (`estamos bien`).',
            avoid: 'Deutsches „es geht mir/uns …“ → `estoy/estamos …`.',
          },
        },
        {
          id: 'es.g.estar.L3.04',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.estar'],
          difficulty: 3,
          audio: '¿Dónde están mis amigos?',
          german: 'Wo sind meine Freunde?',
          answers: ['¿Dónde están mis amigos?'],
          feedback: {
            rule: 'Mehrere Personen/Dinge → `están`.',
            why: '„está“ wäre Singular und passt nicht zu `mis amigos`.',
            avoid: 'Hör auf das -n am Verb: Es zeigt den Plural.',
          },
        },
      ],
    },
  ],
  related: ['es.g.ser', 'es.g.ser-estar', 'es.g.hay'],
};
