import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.formality',
  courseId: 'es',
  stageId: 'stage0',
  order: 1,
  category: 'Kommunikation & Anrede',
  title: 'Du oder Sie? – tú, usted & Begrüßungen',
  summary: 'Wann du tú und wann usted sagst, welche Verbform dazugehört und was in Spanien und Lateinamerika anders ist.',
  keywords: [
    'tú', 'usted', 'ustedes', 'vosotros', 'vos', 'voseo', 'duzen', 'siezen', 'Anrede', 'Höflichkeit',
    'formell', 'informell', 'Begrüßung', 'Verabschiedung', 'hola', 'buenos días', 'buenas tardes',
    'buenas noches', 'qué tal', 'Sie', 'du', 'ihr',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Wie im Deutschen gibt es im Spanischen eine vertraute Anrede (`tú` = du) und eine höfliche (`usted` = Sie). **Aber:** Man duzt viel schneller als in Deutschland. Unter Gleichaltrigen, im Kollegenkreis, im Café oder im Laden hörst du in Spanien fast immer `tú`. `usted` verwendest du bei deutlich älteren Menschen, auf Ämtern, im Hotel an der Rezeption oder in sehr formellen Situationen.',
    },
    {
      type: 'text',
      md: 'Der wichtigste Punkt für die Grammatik: `usted` ist grammatisch **3. Person Singular**. Das Verb steht also genauso wie bei „er“ oder „sie“ – nicht wie bei „du“ und auch nicht im Plural wie das deutsche „Sie sind“.',
    },
    {
      type: 'colored',
      parts: [{ text: '¿Cómo', role: 'question' }, { text: ' estás', role: 'verb' }, { text: '?' }],
      german: 'Wie geht es dir? (tú – die Endung -s zeigt „du“)',
    },
    {
      type: 'colored',
      parts: [{ text: '¿Cómo', role: 'question' }, { text: ' está', role: 'verb' }, { text: ' usted', role: 'pronoun' }, { text: '?' }],
      german: 'Wie geht es Ihnen? (usted – Verb wie bei „er/sie“)',
    },
    {
      type: 'table',
      title: 'Die Anredeformen im Überblick',
      headers: ['Wen sprichst du an?', 'Spanien', 'Lateinamerika'],
      rows: [
        ['eine Person, vertraut', 'tú', 'tú (in Argentinien, Uruguay u. a.: vos)'],
        ['eine Person, höflich', 'usted', 'usted'],
        ['mehrere, vertraut', 'vosotros / vosotras', 'ustedes'],
        ['mehrere, höflich', 'ustedes', 'ustedes'],
      ],
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien sprichst du eine Gruppe von Freunden mit `vosotros` an: `¿Cómo estáis?` („Wie geht es euch?“). `ustedes` ist dort nur die höfliche Mehrzahl.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika gibt es kein `vosotros`. Für jede Gruppe – Freunde wie Fremde – sagst du `ustedes`: `¿Cómo están?`. In Argentinien und Uruguay (und Teilen Mittelamerikas) hörst du statt `tú` oft `vos`, z. B. `¿Vos sos de acá?` („Bist du von hier?“). Du musst `vos` nicht aktiv benutzen, solltest es aber erkennen.',
    },
    {
      type: 'mistake',
      wrong: '¿Cómo estás, señor García?',
      right: '¿Cómo está, señor García?',
      why: 'Wer jemanden mit `señor`/`señora` + Nachname anspricht, siezt. Dann braucht das Verb die usted-Form (3. Person) – ohne -s.',
    },
    {
      type: 'tip',
      md: 'Tageszeit-Grüße: `Buenos días` (bis zum Mittagessen), `Buenas tardes` (nachmittags, bis es dunkel wird), `Buenas noches` (abends – als Gruß **und** zum Abschied). `día` ist männlich, `tarde` und `noche` sind weiblich – daher buen**os** días, aber buen**as** tardes.',
    },
    { type: 'audio', text: 'Buenos días, señora López. ¿Cómo está usted?', label: 'Höfliche Begrüßung anhören' },
  ],
  examples: [
    {
      target: '¡Hola! ¿Qué tal?',
      german: 'Hallo! Wie geht’s?',
      note: 'Locker, aber nie unhöflich – passt fast immer, wenn du unsicher bist.',
    },
    {
      target: 'Buenos días, ¿cómo está usted?',
      german: 'Guten Morgen, wie geht es Ihnen?',
      parts: [
        { text: 'Buenos días, ' },
        { text: '¿cómo', role: 'question' },
        { text: ' está', role: 'verb' },
        { text: ' usted', role: 'pronoun' },
        { text: '?' },
      ],
    },
    {
      target: '¿Cómo estás, Lucía?',
      german: 'Wie geht es dir, Lucía?',
      parts: [{ text: '¿Cómo', role: 'question' }, { text: ' estás', role: 'verb' }, { text: ', Lucía?' }],
    },
    { target: 'Mucho gusto, señora Ruiz.', german: 'Freut mich, Frau Ruiz.' },
    {
      target: 'Disculpe, ¿habla usted alemán?',
      german: 'Entschuldigen Sie, sprechen Sie Deutsch?',
      note: '`disculpe` ist die höfliche Form; unter Freunden sagt man `disculpa` oder `perdona`.',
    },
    { target: '¿Cómo estáis, chicos?', german: 'Wie geht es euch, Leute?', variant: 'es-ES' },
    { target: '¿Cómo están, chicos?', german: 'Wie geht es euch, Leute?', variant: 'es-LA' },
    { target: 'Hasta luego, ¡buenas noches!', german: 'Bis später, gute Nacht!' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: '¿Cómo está usted?',
      german: 'Wie geht es Ihnen?',
      md: 'Das deutsche „Sie“ ist grammatisch Plural („Sie sind“). Das spanische `usted` ist **Singular** wie „er/sie“: `usted está`, `usted habla`.',
    },
    {
      type: 'compare',
      target: '¿Cómo están ustedes?',
      german: 'Wie geht es Ihnen (allen)?',
      md: 'Erst bei mehreren Personen kommt der Plural: `ustedes están`.',
    },
    {
      type: 'compare',
      target: 'Hola, Carmen, ¿qué tal?',
      german: 'Hallo Carmen, wie geht’s? (statt „Guten Tag, Frau Díaz, wie geht es Ihnen?“)',
      md: 'Wo Deutsche siezen (Kollegin, Nachbarin, Verkäufer), duzt man in Spanien oft schon beim Vornamen. In Lateinamerika ist `usted` insgesamt häufiger – in Kolumbien oder Costa Rica hört man es teils sogar unter Freunden.',
    },
    {
      type: 'text',
      md: 'Faustregel: Wenn dich jemand duzt, darfst du zurückduzen. Wenn du unsicher bist, beginne mit `usted` – dein Gegenüber sagt dir oft von selbst: `Puedes tutearme` („Du kannst mich duzen“).',
    },
  ],
  mistakes: [
    {
      wrong: '¿Cómo estás, señor Ruiz?',
      right: '¿Cómo está, señor Ruiz?',
      why: '`señor` + Nachname = Siezen. Die Verbform muss zur usted-Form passen (3. Person, ohne -s).',
    },
    {
      wrong: '¿Cómo están usted?',
      right: '¿Cómo está usted?',
      why: 'Deutsche übertragen „Sie sind“ (Plural). `usted` ist aber Singular – nur `ustedes` steht mit Pluralverb.',
    },
    {
      wrong: '¿Cómo estáis, chicos? (in Mexiko)',
      right: '¿Cómo están, chicos?',
      why: '`vosotros` gibt es nur in Spanien. In Lateinamerika sagt man zu jeder Gruppe `ustedes`.',
    },
    {
      wrong: 'Buenos tardes.',
      right: 'Buenas tardes.',
      why: '`tarde` ist feminin, deshalb `buenas`. Nur `día` ist maskulin: `buenos días`.',
    },
  ],
  mnemonic: '**Usted** ist höflich, aber grammatisch „er/sie“: `usted está` – nie „usted estás“.',
  levels: [
    {
      level: 1,
      title: 'Anrede erkennen',
      exercises: [
        {
          id: 'es.g.formality.L1.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.formality'],
          difficulty: 1,
          prompt: 'Du fragst eine ältere Dame, die du nicht kennst, nach dem Weg. Welche Anrede passt?',
          options: [
            { text: 'tú', why: '`tú` ist vertraut – bei einer fremden älteren Person wirkt das zu locker.' },
            { text: 'usted', why: 'Richtig: fremd + deutlich älter = höfliche Anrede.' },
            { text: 'vosotros', why: '`vosotros` ist Plural (ihr) und nur in Spanien üblich.' },
          ],
          answer: 1,
          feedback: {
            rule: '`usted` ist die höfliche Anrede für eine Person – bei Fremden, deutlich Älteren und in formellen Situationen.',
            why: '`tú` ist vertraut, `vosotros` meint mehrere Personen.',
            avoid: 'Frage dich: Würde ich auf Deutsch siezen und ist die Person deutlich älter oder in offizieller Rolle? Dann `usted`.',
          },
        },
        {
          id: 'es.g.formality.L1.02',
          type: 'matchPairs',
          skills: ['grammar', 'vocabulary'],
          topicIds: ['es.g.formality'],
          difficulty: 1,
          instruction: 'Ordne jede Anrede ihrer Bedeutung zu.',
          pairs: [
            { left: 'tú', right: 'du' },
            { left: 'usted', right: 'Sie (eine Person)' },
            { left: 'ustedes', right: 'Sie / ihr (mehrere)' },
            { left: 'vosotros', right: 'ihr (nur Spanien)' },
          ],
          feedback: {
            rule: 'Singular: `tú` (vertraut), `usted` (höflich). Plural: `ustedes` (überall), `vosotros` (vertraut, nur Spanien).',
            why: '`ustedes` deckt in Lateinamerika sowohl „ihr“ als auch „Sie“ (Plural) ab.',
            avoid: 'Merke: Alles mit **ust-** ist höflich bzw. in Lateinamerika Standard für Gruppen.',
          },
        },
        {
          id: 'es.g.formality.L1.03',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.formality'],
          difficulty: 1,
          audio: 'Buenos días, ¿cómo está usted?',
          question: 'Wird die Person geduzt oder gesiezt?',
          options: ['geduzt (tú)', 'gesiezt (usted)', 'mehrere Personen (ustedes)'],
          answer: 1,
          feedback: {
            rule: '`está` + `usted` = höfliche Frage an eine Person.',
            why: 'Beim Duzen hieße es `estás` (mit -s), bei mehreren `están`.',
            avoid: 'Hör auf das Ende des Verbs: -s → du; kein -s → usted; -n → mehrere.',
          },
        },
        {
          id: 'es.g.formality.L1.04',
          type: 'situation',
          skills: ['grammar', 'speaking'],
          topicIds: ['es.g.formality'],
          difficulty: 1,
          scenario: 'Es ist 9 Uhr morgens. Du betrittst in Madrid ein Hotel und begrüßt den Herrn an der Rezeption.',
          options: [
            { text: 'Buenos días.', why: 'Richtig: passender Gruß für den Vormittag, neutral-höflich.' },
            { text: 'Buenas noches.', why: '`Buenas noches` sagt man erst abends – oder beim Verabschieden in der Nacht.' },
            { text: 'Buenas tardes.', why: '`Buenas tardes` sagt man erst nach dem Mittagessen.' },
          ],
          answer: 0,
          feedback: {
            rule: '`Buenos días` gilt bis zum Mittagessen, `buenas tardes` am Nachmittag, `buenas noches` am Abend.',
            why: 'Die Tageszeit entscheidet über den Gruß.',
            avoid: 'Denke an die Mahlzeiten: vor dem Mittagessen días, danach tardes, nach Einbruch der Dunkelheit noches.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Die passende Verbform',
      exercises: [
        {
          id: 'es.g.formality.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          sentence: '¿Cómo ___ usted, señora Díaz?',
          german: 'Wie geht es Ihnen, Frau Díaz?',
          answers: [['está']],
          bank: ['estás', 'está', 'están'],
          feedback: {
            rule: '`usted` verlangt die Verbform der 3. Person Singular: `está`.',
            why: '`estás` ist die du-Form, `están` die Pluralform (ustedes).',
            avoid: '`usted` = „er/sie“-Form. Kein -s, kein -n.',
          },
        },
        {
          id: 'es.g.formality.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          sentence: '¡Hola, Pablo! ¿Cómo ___?',
          german: 'Hallo Pablo! Wie geht es dir?',
          answers: [['estás']],
          bank: ['estás', 'está', 'están'],
          feedback: {
            rule: 'Beim Duzen (`tú`) endet das Verb auf -s: `estás`.',
            why: 'Mit Vornamen und `hola` sprichst du Pablo vertraut an – `está` wäre die Sie-Form.',
            avoid: 'Das -s am Ende ist das Erkennungszeichen für „du“.',
          },
        },
        {
          id: 'es.g.formality.L2.03',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          verb: 'estar',
          tense: 'Präsens',
          person: 'ustedes',
          sentence: '¿Cómo ___ ustedes?',
          answers: ['están'],
          feedback: {
            rule: '`ustedes` steht mit der 3. Person Plural: `están`.',
            why: '`está` ist Singular (usted), `estáis` gehört zu vosotros.',
            avoid: 'Mehrere Personen mit `ustedes` → Verb auf -n.',
          },
        },
        {
          id: 'es.g.formality.L2.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Guten Morgen, wie geht es Ihnen?',
          answers: [
            'Buenos días, ¿cómo está usted?',
            'Buenos días, ¿cómo está?',
            'Buenos días, ¿qué tal está usted?',
            'Buenos días, ¿qué tal está?',
          ],
          feedback: {
            rule: 'Höflich fragen: `¿Cómo está (usted)?` – Verb in der 3. Person Singular.',
            why: '`¿Cómo estás?` wäre geduzt, `¿Cómo están?` wäre an mehrere gerichtet.',
            avoid: '„Ihnen“ an eine Person → `usted` → `está`.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Sicher in jeder Situation',
      exercises: [
        {
          id: 'es.g.formality.L3.01',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 3,
          instruction: 'Die Person wird gesiezt. Korrigiere den Satz.',
          sentence: '¿Cómo estás, señora Ortega?',
          german: 'Wie geht es Ihnen, Frau Ortega?',
          answers: ['¿Cómo está, señora Ortega?', '¿Cómo está usted, señora Ortega?'],
          feedback: {
            rule: '`señora` + Nachname = höfliche Anrede → `está` (usted-Form).',
            why: '`estás` ist die vertraute du-Form und passt nicht zu `señora Ortega`.',
            avoid: 'Titel wie `señor`, `señora`, `doctor` sind ein Signal für `usted`.',
          },
        },
        {
          id: 'es.g.formality.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 3,
          variant: 'es-ES',
          instruction: 'Spanien: Du sprichst eine Gruppe von Freunden an.',
          sentence: '¡Hola, chicos! ¿Cómo ___?',
          german: 'Hallo Leute! Wie geht es euch?',
          answers: [['estáis']],
          bank: ['estás', 'estáis', 'están'],
          feedback: {
            rule: 'In Spanien sprichst du mehrere Freunde mit `vosotros` an: `estáis`.',
            why: '`estás` meint nur eine Person; `están` klingt in Spanien bei Freunden förmlich (ustedes).',
            avoid: 'vosotros-Formen enden auf **-áis / -éis / -ís**.',
          },
        },
        {
          id: 'es.g.formality.L3.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 3,
          variant: 'es-LA',
          instruction: 'Lateinamerika: Du sprichst eine Gruppe von Freunden an.',
          sentence: '¡Hola, chicos! ¿Cómo ___?',
          german: 'Hallo Leute! Wie geht es euch?',
          answers: [['están']],
          bank: ['estás', 'estáis', 'están'],
          feedback: {
            rule: 'In Lateinamerika gilt `ustedes` für jede Gruppe: `están`.',
            why: '`estáis` (vosotros) benutzt man nur in Spanien, `estás` meint eine Person.',
            avoid: 'Lateinamerika: mehrere Personen → immer Verb auf -n.',
          },
        },
        {
          id: 'es.g.formality.L3.04',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.formality'],
          difficulty: 3,
          tokens: ['Buenas', 'tardes,', '¿cómo', 'están', 'ustedes?'],
          extra: ['estás', 'buenos'],
          german: 'Guten Tag, wie geht es Ihnen (allen)?',
          feedback: {
            rule: '`Buenas tardes` (feminin) + `¿cómo están ustedes?` (Plural, 3. Person).',
            why: '`buenos` passt nicht zu `tardes`; `estás` passt nicht zu `ustedes`.',
            avoid: 'Erst den Gruß, dann das Fragewort, dann Verb + Pronomen.',
          },
        },
        {
          id: 'es.g.formality.L3.05',
          type: 'translate',
          skills: ['reading', 'grammar'],
          topicIds: ['es.g.formality'],
          difficulty: 3,
          direction: 'toGerman',
          source: '¿Cómo están ustedes?',
          answers: ['Wie geht es Ihnen?', 'Wie geht es euch?', 'Wie geht’s euch?', 'Wie geht es Ihnen allen?', 'Wie geht es euch allen?'],
          feedback: {
            rule: '`ustedes` = mehrere Personen: in Spanien höflich („Sie“), in Lateinamerika auch vertraut („ihr“).',
            why: '„Wie geht es dir?“ wäre `¿Cómo estás?` – eine einzelne Person.',
            avoid: 'Die Endung -n im Verb verrät: Es sind mehrere Personen gemeint.',
          },
        },
      ],
    },
  ],
  related: ['es.g.pronouns', 'es.g.estar', 'es.g.questions'],
};
