import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.gender-plural',
  courseId: 'es',
  stageId: 'stage0',
  order: 9,
  category: 'Artikel & Nomen',
  title: 'Genus & Plural der Nomen',
  summary: 'Woran du männliche und weibliche Nomen erkennst und wie du den Plural bildest – inklusive der wichtigsten Ausnahmen.',
  keywords: [
    'Genus', 'Geschlecht', 'männlich', 'weiblich', 'maskulin', 'feminin', 'Plural', 'Mehrzahl', '-s', '-es', '-ces',
    '-ción', '-dad', 'el día', 'la mano', 'Endungen', 'Nomen', 'Substantiv',
  ],
  explanation: [
    {
      type: 'table',
      title: 'Genus an der Endung erkennen',
      headers: ['Endung', 'meist', 'Beispiele', 'wichtige Ausnahmen'],
      rows: [
        ['-o', 'männlich', 'el libro, el vaso', 'la mano, la foto, la moto, la radio'],
        ['-a', 'weiblich', 'la mesa, la casa', 'el día, el mapa, el problema, el idioma'],
        ['-ción, -sión, -dad, -tad', 'weiblich', 'la canción, la ciudad, la libertad', '–'],
        ['-or, -aje', 'männlich', 'el color, el viaje', 'la flor'],
        ['-e, andere Konsonanten', 'beides möglich', 'el café, la noche, el hotel, la sal', 'einfach mitlernen'],
      ],
    },
    {
      type: 'text',
      md: 'Bei Personen folgt das Genus meist dem natürlichen Geschlecht: `el amigo` → `la amiga`, `el profesor` → `la profesora`. Wörter auf **-ista** und **-nte** haben oft nur eine Form: `el/la periodista`, `el/la estudiante`.',
    },
    {
      type: 'table',
      title: 'So bildest du den Plural',
      headers: ['Singular endet auf', 'Plural', 'Beispiele'],
      rows: [
        ['Vokal', '+ s', 'casa → casas, café → cafés'],
        ['Konsonant (auch -y)', '+ es', 'hotel → hoteles, ciudad → ciudades, ley → leyes'],
        ['-z', '-ces', 'lápiz → lápices, vez → veces'],
        ['-s nach unbetonter Silbe', 'unverändert', 'el lunes → los lunes, la crisis → las crisis'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'la', role: 'article' },
        { text: ' canci' },
        { text: 'ón', role: 'ending' },
        { text: ' → ' },
        { text: 'las', role: 'article' },
        { text: ' canci' },
        { text: 'ones', role: 'ending' },
      ],
      german: 'das Lied → die Lieder: Der Akzent fällt weg, weil die Betonung jetzt regelgerecht auf der vorletzten Silbe liegt.',
    },
    {
      type: 'text',
      md: '**Akzente im Plural:** Durch die zusätzliche Silbe kann ein Akzent wegfallen (`canción` → `canciones`, `inglés` → `ingleses`) oder neu nötig werden (`examen` → `exámenes`, `joven` → `jóvenes`). Die betonte Silbe bleibt dieselbe.',
    },
    {
      type: 'text',
      md: 'Gemischte Gruppen stehen im **Maskulinum Plural**: `los padres` = die Eltern (oder: die Väter), `los hermanos` = die Geschwister (oder: die Brüder), `los chicos` = die Kinder/Jugendlichen.',
    },
    {
      type: 'mistake',
      wrong: 'la día',
      right: 'el día',
      why: '`día` endet auf -a, ist aber männlich – daher auch `buenos días`.',
    },
    {
      type: 'tip',
      md: '**-o meist männlich, -a meist weiblich, -ción und -dad immer weiblich.** Alles andere: Artikel gleich mitlernen.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Kleine Genus-Unterschiede gibt es regional: In Lateinamerika sagt man zum Sender/Gerät meist `el radio`, in Spanien `la radio`.',
    },
    { type: 'audio', text: 'Una canción, dos canciones. Un lápiz, tres lápices.', label: 'Plural anhören' },
  ],
  examples: [
    { target: 'el libro → los libros', german: 'das Buch → die Bücher' },
    { target: 'la ciudad → las ciudades', german: 'die Stadt → die Städte' },
    { target: 'el lápiz → los lápices', german: 'der Bleistift → die Bleistifte', note: '-z wird zu -ces.' },
    { target: 'el examen → los exámenes', german: 'die Prüfung → die Prüfungen', note: 'Neuer Akzent, damit die Betonung auf „xa“ bleibt.' },
    {
      target: 'Mis padres viven en Madrid.',
      german: 'Meine Eltern wohnen in Madrid.',
      parts: [
        { text: 'Mis', role: 'pronoun' },
        { text: ' padres', role: 'subject' },
        { text: ' viven', role: 'verb' },
        { text: ' en', role: 'preposition' },
        { text: ' Madrid', role: 'noun' },
        { text: '.' },
      ],
      note: '`los padres` = Vater + Mutter.',
    },
    { target: 'la mano, las manos', german: 'die Hand, die Hände', note: 'Weiblich trotz -o.' },
    { target: 'el/la estudiante', german: 'der Student / die Studentin', note: 'Nur der Artikel zeigt das Geschlecht.' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'el problema · la foto',
      german: 'das Problem · das Foto',
      md: 'Deutsche Neutra verteilen sich im Spanischen auf männlich und weiblich – ohne feste Entsprechung.',
    },
    {
      type: 'compare',
      target: 'la casa → las casas',
      german: 'das Haus → die Häuser',
      md: 'Der deutsche Plural hat viele Formen (-e, -er, -n, Umlaut …). Der spanische hat im Kern zwei: **-s** oder **-es**.',
    },
    {
      type: 'compare',
      target: 'los padres',
      german: 'die Eltern',
      md: 'Wo Deutsch eigene Wörter hat (Eltern, Geschwister), nutzt Spanisch den männlichen Plural.',
    },
    {
      type: 'text',
      md: 'Das Genus steckt im Spanischen oft in der Endung. Das ist leichter als im Deutschen, wo „der Löffel, die Gabel, das Messer“ keinem Muster folgen.',
    },
  ],
  mistakes: [
    { wrong: 'la día', right: 'el día', why: 'Ausnahme: `día` ist männlich.' },
    { wrong: 'el mano', right: 'la mano', why: 'Ausnahme: `mano` ist weiblich.' },
    { wrong: 'los hotels', right: 'los hoteles', why: 'Nach Konsonant: Plural auf **-es**.' },
    { wrong: 'los lápizes', right: 'los lápices', why: '-z wird im Plural zu -ces.' },
    { wrong: 'las canciónes', right: 'las canciones', why: 'Der Akzent fällt weg: `can-cio-nes` ist regelgerecht auf der vorletzten Silbe betont.' },
  ],
  mnemonic: '**Vokal + s, Konsonant + es, z wird c.** Und: -ción und -dad sind immer weiblich.',
  levels: [
    {
      level: 1,
      title: 'Genus erkennen',
      exercises: [
        {
          id: 'es.g.gender-plural.L1.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 1,
          prompt: 'Welches Wort ist **weiblich**?',
          options: [
            { text: 'libro', why: 'Endung -o → männlich: `el libro`.' },
            { text: 'ciudad', why: 'Richtig: Wörter auf -dad sind immer weiblich: `la ciudad`.' },
            { text: 'hotel', why: '`el hotel` ist männlich.' },
          ],
          answer: 1,
          feedback: {
            rule: 'Endungen -dad, -tad, -ción, -sión → immer weiblich.',
            why: 'Das deutsche „die Stadt“ passt hier zufällig – verlass dich lieber auf die Endung.',
            avoid: 'Merke dir die „sicheren“ weiblichen Endungen: -ción, -sión, -dad, -tad.',
          },
        },
        {
          id: 'es.g.gender-plural.L1.02',
          type: 'imageMatch',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 1,
          instruction: 'Ordne zu – achte auf die Artikel.',
          pairs: [
            { emoji: '✋', word: 'la mano' },
            { emoji: '🗺️', word: 'el mapa' },
            { emoji: '📷', word: 'la foto' },
            { emoji: '🏍️', word: 'la moto' },
            { emoji: '🌸', word: 'la flor' },
          ],
          feedback: {
            rule: 'Ausnahmen: `la mano`, `la foto`, `la moto` (weiblich trotz -o), `el mapa` (männlich trotz -a), `la flor` (weiblich trotz -or).',
            why: '`foto` und `moto` sind Kurzformen von `la fotografía` und `la motocicleta` – daher weiblich.',
            avoid: 'Lerne diese Ausnahmen als kleine Gruppe auswendig.',
          },
        },
        {
          id: 'es.g.gender-plural.L1.03',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 1,
          instruction: 'Ordne Singular und Plural zu.',
          pairs: [
            { left: 'la casa', right: 'las casas' },
            { left: 'el hotel', right: 'los hoteles' },
            { left: 'el lápiz', right: 'los lápices' },
            { left: 'la canción', right: 'las canciones' },
          ],
          feedback: {
            rule: 'Vokal + s, Konsonant + es, -z → -ces.',
            why: '`hotel` endet auf Konsonant, daher -es; `canción` verliert im Plural den Akzent.',
            avoid: 'Schau immer auf den letzten Buchstaben des Singulars.',
          },
        },
        {
          id: 'es.g.gender-plural.L1.04',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 1,
          sentence: '___ días.',
          german: 'Guten Morgen.',
          answers: [['Buenos']],
          bank: ['Buenos', 'Buenas'],
          feedback: {
            rule: '`día` ist männlich – trotz der Endung -a. Deshalb: `buenos días`.',
            why: '`buenas` passt zu weiblichen Nomen wie `tardes` und `noches`.',
            avoid: 'Merke den Gruß als Beweis: bu**enos** días → el día.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Plural bilden',
      exercises: [
        {
          id: 'es.g.gender-plural.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 2,
          instruction: 'Setze den Plural ein.',
          sentence: 'En Madrid hay muchos ___ (hotel) y muchas ___ (universidad).',
          german: 'In Madrid gibt es viele Hotels und viele Universitäten.',
          answers: [['hoteles'], ['universidades']],
          feedback: {
            rule: 'Nach Konsonant: + es → `hoteles`, `universidades`.',
            why: '„hotels“ ist Englisch/Deutsch – im Spanischen braucht es ein -e- dazwischen.',
            avoid: 'Konsonant am Ende? → -es anhängen.',
          },
        },
        {
          id: 'es.g.gender-plural.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 2,
          instruction: 'Setze den Plural von „lápiz“ ein.',
          sentence: 'Dos ___, por favor.',
          german: 'Zwei Bleistifte, bitte.',
          answers: [['lápices']],
          feedback: {
            rule: 'Endet ein Wort auf -z, wird im Plural daraus -ces: `lápiz` → `lápices`.',
            why: 'Im Spanischen steht vor e und i normalerweise c statt z.',
            avoid: 'z + es → ces (wie `vez` → `veces`).',
          },
        },
        {
          id: 'es.g.gender-plural.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 2,
          sentence: 'Me duele el mano.',
          german: 'Mir tut die Hand weh.',
          answers: ['Me duele la mano.'],
          feedback: {
            rule: '`mano` ist weiblich: `la mano`.',
            why: 'Die Endung -o verleitet zu `el` – `mano` ist eine der wenigen Ausnahmen.',
            avoid: 'Merksatz: „Die Hand ist weiblich – la mano.“',
          },
        },
        {
          id: 'es.g.gender-plural.L2.04',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 2,
          prompt: 'Was bedeutet `Mis padres son de Chile.`?',
          options: [
            { text: 'Meine Eltern kommen aus Chile.', why: 'Richtig: `los padres` = Vater und Mutter.' },
            { text: 'Meine Väter kommen aus Chile.', why: 'Möglich wäre das nur in einem ganz besonderen Kontext – normalerweise sind die Eltern gemeint.' },
            { text: 'Mein Vater kommt aus Chile.', why: '`padres` ist Plural – `mi padre` wäre der Vater allein.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Männlicher Plural steht auch für gemischte Gruppen: `padres` = Eltern, `hermanos` = Geschwister.',
            why: 'Spanisch hat für „Eltern“ kein eigenes Wort.',
            avoid: 'Denk bei männlichem Plural immer an „gemischt“.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Akzente und Ausnahmen',
      exercises: [
        {
          id: 'es.g.gender-plural.L3.01',
          type: 'mc',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 3,
          prompt: 'Wie lautet der Plural von `examen` (Prüfung)?',
          options: [
            { text: 'exámenes', why: 'Richtig: Die Betonung bleibt auf „xa“, jetzt drittletzte Silbe → Akzent nötig.' },
            { text: 'examenes', why: 'Ohne Akzent läge die Betonung auf „me“ – falsch.' },
            { text: 'exámens', why: 'Nach Konsonant immer -es.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Die betonte Silbe bleibt im Plural gleich; wird sie zur drittletzten, braucht sie einen Akzent.',
            why: 'e-XA-men → e-XÁ-me-nes: vier Silben, Betonung auf der drittletzten.',
            avoid: 'Betonung beibehalten und danach die Akzentregeln neu prüfen.',
          },
        },
        {
          id: 'es.g.gender-plural.L3.02',
          type: 'mc',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 3,
          prompt: 'Wie lautet der Plural von `inglés` (Engländer)?',
          options: [
            { text: 'ingléses', why: 'Der Akzent ist im Plural überflüssig.' },
            { text: 'ingleses', why: 'Richtig: in-gle-ses – vorletzte Silbe, endet auf -s → kein Akzent nötig.' },
            { text: 'inglés', why: 'Wörter auf betontes -és bilden den Plural mit -es.' },
          ],
          answer: 1,
          feedback: {
            rule: 'Endbetonte Wörter auf -n/-s verlieren im Plural den Akzent: `inglés` → `ingleses`, `canción` → `canciones`.',
            why: 'Durch die neue Silbe wird die betonte Silbe zur vorletzten – das ist der Normalfall.',
            avoid: 'Faustregel: -ón/-és/-án im Singular → im Plural ohne Akzent.',
          },
        },
        {
          id: 'es.g.gender-plural.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'die Lieder und die Städte',
          answers: ['las canciones y las ciudades'],
          feedback: {
            rule: '`la canción` → `las canciones`; `la ciudad` → `las ciudades` – beide weiblich.',
            why: '„los canciones“ wäre falsch: -ción ist immer weiblich.',
            avoid: 'Weibliche Endungen -ción/-dad → Artikel `las`.',
          },
        },
        {
          id: 'es.g.gender-plural.L3.04',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gender-plural'],
          difficulty: 3,
          tokens: ['Los', 'lunes', 'mis', 'hermanos', 'tienen', 'exámenes.'],
          extra: ['tiene', 'examen'],
          alternatives: [['Mis', 'hermanos', 'tienen', 'exámenes', 'los', 'lunes.']],
          german: 'Montags haben meine Geschwister Prüfungen.',
          feedback: {
            rule: '`los lunes` = montags (Plural gleich Singular); `hermanos` = Geschwister; `exámenes` mit Akzent.',
            why: '`tiene` ist Singular und passt nicht zu `mis hermanos`; „Prüfungen“ verlangt den Plural `exámenes`.',
            avoid: 'Wochentage auf -s bleiben im Plural unverändert.',
          },
        },
      ],
    },
  ],
  related: ['es.g.articles', 'es.g.adjectives', 'es.g.stress'],
};
