import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.gustar',
  courseId: 'es',
  stageId: 'a1',
  order: 2,
  category: 'Verben',
  title: 'Gustar – was dir gefällt',
  summary: 'me gusta, te gustan, a Ana le gusta: Vorlieben ausdrücken wie mit dem deutschen „gefallen“.',
  keywords: [
    'gustar', 'gefallen', 'mögen', 'gern', 'me gusta', 'me gustan', 'te gusta', 'le gusta', 'nos gusta', 'os gusta', 'les gusta',
    'encantar', 'me encanta', 'Vorlieben', 'a mí también', 'a mí tampoco', 'indirektes Objektpronomen', 'Dativ',
  ],
  explanation: [
    {
      type: 'text',
      md: '`gustar` funktioniert wie das deutsche **„gefallen“**: Das, was gefällt, ist das Subjekt; die Person, der es gefällt, steht als Pronomen davor. `Me gusta el café.` = wörtlich „Mir gefällt der Kaffee.“',
    },
    {
      type: 'table',
      title: 'Wem gefällt es?',
      headers: ['Betonung (optional)', 'Pronomen', 'Beispiel'],
      rows: [
        ['a mí', 'me', 'Me gusta el café.'],
        ['a ti', 'te', '¿Te gusta el café?'],
        ['a él / a ella / a usted', 'le', 'Le gusta el café.'],
        ['a nosotros / a nosotras', 'nos', 'Nos gusta el café.'],
        ['a vosotros / a vosotras (Spanien)', 'os', 'Os gusta el café.'],
        ['a ellos / a ellas / a ustedes', 'les', 'Les gusta el café.'],
      ],
    },
    {
      type: 'text',
      md: 'Das Verb richtet sich nach dem, **was** gefällt:\n- eine Sache oder eine Tätigkeit → `gusta`: `Me gusta la música.` · `Me gusta bailar.`\n- mehrere Sachen → `gustan`: `Me gustan los perros.`',
    },
    {
      type: 'colored',
      parts: [
        { text: 'A Ana', role: 'object' },
        { text: ' le', role: 'pronoun' },
        { text: ' gustan', role: 'verb' },
        { text: ' los', role: 'article' },
        { text: ' gatos', role: 'subject' },
        { text: '.' },
      ],
      german: 'Ana mag Katzen. (Wörtlich: „Ana gefallen die Katzen.“) – `gatos` ist das Subjekt, deshalb `gustan`.',
    },
    {
      type: 'text',
      md: 'Bei Namen oder Nomen brauchst du `a` + Person **und** das Pronomen: `A Ana le gusta…`, `A mis padres les gusta…`. `a mí`, `a ti` usw. benutzt du zur Betonung oder als Kurzantwort: `—Me gusta el jazz. —¡A mí también!` / `—No me gusta el té. —A mí tampoco.`',
    },
    {
      type: 'text',
      md: 'Ebenso funktioniert `encantar` („lieben, total gut finden“): `Me encanta el mar.` · `Nos encantan las fiestas.` `Me encanta` ist schon stark – „me encanta mucho“ hört man zwar, gilt aber als doppelt gemoppelt; besser nur `me encanta`.',
    },
    {
      type: 'mistake',
      wrong: 'Yo gusto el café.',
      right: 'Me gusta el café.',
      why: '`Yo gusto` hieße „Ich gefalle“. Die Person steht als Pronomen (`me`), das Gemochte ist das Subjekt.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: `¿Os gusta la paella?` – „Mögt ihr Paella?“ (vosotros → `os`).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: `¿Les gusta la comida mexicana?` – `les` gilt für jede Gruppe (ustedes).',
    },
    { type: 'tip', md: '**gustar = gefallen.** Was gefällt, bestimmt das Verb: eine Sache → gusta, mehrere → gustan.' },
    { type: 'audio', text: 'Me gusta la música, me gustan los libros y me encanta bailar.', label: 'Beispiele anhören' },
  ],
  examples: [
    {
      target: 'Me gusta el chocolate.',
      german: 'Ich mag Schokolade.',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' gusta', role: 'verb' },
        { text: ' el', role: 'article' },
        { text: ' chocolate', role: 'subject' },
        { text: '.' },
      ],
    },
    {
      target: 'Me gustan los perros.',
      german: 'Ich mag Hunde.',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' gustan', role: 'verb' },
        { text: ' los', role: 'article' },
        { text: ' perros', role: 'subject' },
        { text: '.' },
      ],
    },
    { target: '¿Te gusta bailar?', german: 'Tanzt du gern?' },
    { target: 'A mi hermano le gusta mucho la música.', german: 'Mein Bruder mag Musik sehr.' },
    { target: 'No nos gusta el frío.', german: 'Wir mögen die Kälte nicht.' },
    { target: '—Me encanta esta ciudad. —¡A mí también!', german: '„Ich liebe diese Stadt.“ – „Ich auch!“' },
    { target: '¿Os gusta la paella?', german: 'Mögt ihr Paella?', variant: 'es-ES' },
    { target: '¿Les gusta la paella?', german: 'Mögt ihr Paella?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Me gusta el libro.',
      german: 'Mir gefällt das Buch.',
      md: 'Gleiche Struktur wie „gefallen“: Das Buch ist Subjekt, „mir“ = `me`.',
    },
    {
      type: 'compare',
      target: 'Me gustan los libros.',
      german: 'Mir gefallen die Bücher.',
      md: 'Auch im Deutschen richtet sich das Verb nach dem Gemochten: „gefallen“ (Plural).',
    },
    {
      type: 'compare',
      target: 'Me gusta nadar.',
      german: 'Ich schwimme gern.',
      md: 'Deutsches „gern + Verb“ → `me gusta` + Infinitiv.',
    },
    {
      type: 'compare',
      target: 'Me gusta el café.',
      german: 'Ich mag Kaffee.',
      md: 'Bei allgemeinen Vorlieben steht im Spanischen der bestimmte Artikel.',
    },
  ],
  mistakes: [
    { wrong: 'Yo gusto el café.', right: 'Me gusta el café.', why: 'Die Person steht als Pronomen, nicht als Subjekt.' },
    { wrong: 'Me gusta los libros.', right: 'Me gustan los libros.', why: 'Mehrere Dinge gefallen → `gustan`.' },
    { wrong: 'Ana le gusta bailar.', right: 'A Ana le gusta bailar.', why: 'Vor dem Namen steht `a`.' },
    { wrong: 'Me gusta café.', right: 'Me gusta el café.', why: 'Allgemeine Vorlieben mit Artikel.' },
    { wrong: 'Me gustan bailar y cantar.', right: 'Me gusta bailar y cantar.', why: 'Tätigkeiten (Infinitive) stehen immer mit `gusta` – auch mehrere.' },
  ],
  mnemonic: '**gustar = gefallen.** Eine Sache oder Tätigkeit → gusta. Mehrere Sachen → gustan.',
  levels: [
    {
      level: 1,
      title: 'Me gusta / me gustan',
      exercises: [
        {
          id: 'es.g.gustar.L1.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.gustar'],
          difficulty: 1,
          prompt: '„Ich mag Schokolade.“',
          options: [
            { text: 'Me gusta el chocolate.', why: 'Richtig: „Mir gefällt die Schokolade.“' },
            { text: 'Yo gusto el chocolate.', why: '`yo gusto` = „ich gefalle“.' },
            { text: 'Me gustan el chocolate.', why: 'Eine Sache → `gusta`, nicht `gustan`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'me + gusta + Sache (Singular).',
            why: 'Die Person ist bei gustar nie das Subjekt.',
            avoid: 'Denk „Mir gefällt …“ statt „Ich mag …“.',
          },
        },
        {
          id: 'es.g.gustar.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 1,
          sentence: 'Me ___ los gatos.',
          german: 'Ich mag Katzen.',
          answers: [['gustan']],
          bank: ['gusta', 'gustan'],
          feedback: {
            rule: 'Mehrere Dinge gefallen → `gustan`.',
            why: '`los gatos` ist Plural und Subjekt des Satzes.',
            avoid: 'Schau auf das Nomen nach dem Verb: Plural → gustan.',
          },
        },
        {
          id: 'es.g.gustar.L1.03',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.gustar'],
          difficulty: 1,
          instruction: 'Welches Pronomen gehört dazu?',
          pairs: [
            { left: 'a mí', right: 'me' },
            { left: 'a ti', right: 'te' },
            { left: 'a ella', right: 'le' },
            { left: 'a nosotros', right: 'nos' },
            { left: 'a ellos', right: 'les' },
          ],
          feedback: {
            rule: 'me, te, le, nos, (os), les.',
            why: '`le` gilt für er, sie und Sie – `les` für den Plural.',
            avoid: 'le/les = 3. Person – wie bei `usted`/`ustedes`.',
          },
        },
        {
          id: 'es.g.gustar.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.gustar'],
          difficulty: 1,
          audio: 'A Pedro no le gusta el fútbol.',
          question: 'Was stimmt?',
          options: ['Pedro mag keinen Fußball.', 'Pedro mag Fußball.', 'Ich mag keinen Fußball.'],
          answer: 0,
          feedback: {
            rule: '`A Pedro no le gusta …` = Pedro gefällt … nicht.',
            why: 'Das `no` steht vor dem Pronomen `le`.',
            avoid: 'Verneinung: no + Pronomen + gusta.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Für andere sprechen',
      exercises: [
        {
          id: 'es.g.gustar.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 2,
          sentence: '¿___ gusta bailar?',
          german: 'Tanzt du gern?',
          answers: [['Te']],
          bank: ['Te', 'Me', 'Le'],
          feedback: {
            rule: 'Frage an „du“ → `te`.',
            why: '`me` = mir, `le` = ihm/ihr/Ihnen.',
            avoid: 'tú → te.',
          },
        },
        {
          id: 'es.g.gustar.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 2,
          sentence: 'A mis padres ___ ___ viajar.',
          german: 'Meine Eltern reisen gern.',
          answers: [['les'], ['gusta']],
          bank: ['le', 'les', 'gusta', 'gustan'],
          feedback: {
            rule: 'Mehrere Personen → `les`; Tätigkeit (Infinitiv) → `gusta`.',
            why: 'Die Eltern sind nicht das Subjekt – `viajar` ist es. Deshalb Singular `gusta`.',
            avoid: 'Das Pronomen richtet sich nach der Person, das Verb nach dem Gemochten.',
          },
        },
        {
          id: 'es.g.gustar.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 2,
          sentence: 'Me gusta los perros.',
          german: 'Ich mag Hunde.',
          answers: ['Me gustan los perros.'],
          feedback: {
            rule: 'Plural-Subjekt (`los perros`) → `gustan`.',
            why: 'Deutsche denken „Ich mag“ (Singular) – entscheidend ist aber, was gefällt.',
            avoid: 'Hinter gusta(n) steht das Subjekt – prüfe dessen Zahl.',
          },
        },
        {
          id: 'es.g.gustar.L2.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Ich tanze gern.',
          answers: ['Me gusta bailar.', 'A mí me gusta bailar.'],
          feedback: {
            rule: '„gern + Verb“ = `me gusta` + Infinitiv.',
            why: '„Bailo gern“ – `gern` gibt es im Spanischen nicht als Wort.',
            avoid: 'Tätigkeiten, die du magst → me gusta + Infinitiv.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Sicher reagieren',
      exercises: [
        {
          id: 'es.g.gustar.L3.01',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 3,
          sentence: 'Ana le gusta la música clásica.',
          german: 'Ana mag klassische Musik.',
          answers: ['A Ana le gusta la música clásica.'],
          feedback: {
            rule: 'Person als Name oder Nomen → `a` + Name + `le`.',
            why: 'Ohne `a` sieht Ana wie das Subjekt aus – das ist aber `la música`.',
            avoid: '`A` vor Personen bei gustar nie vergessen.',
          },
        },
        {
          id: 'es.g.gustar.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 3,
          sentence: '—No me gusta el café. —A mí ___.',
          german: '„Ich mag keinen Kaffee.“ – „Ich auch nicht.“',
          answers: [['tampoco']],
          bank: ['también', 'tampoco'],
          feedback: {
            rule: 'Auf eine Verneinung zustimmen: `A mí tampoco`.',
            why: '`A mí también` passt nur zu bejahten Aussagen.',
            avoid: 'Bei gustar korrekt mit `a mí`, nicht `yo`: „Yo tampoco“ hört man im Alltag zwar oft, standardsprachlich korrekt ist aber `A mí tampoco`.',
          },
        },
        {
          id: 'es.g.gustar.L3.03',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 3,
          tokens: ['A', 'mis', 'amigos', 'les', 'encantan', 'las', 'películas', 'españolas.'],
          extra: ['le', 'encanta'],
          german: 'Meine Freunde lieben spanische Filme.',
          feedback: {
            rule: '`a` + Personen + `les` + `encantan` (Plural, weil `las películas`).',
            why: '`le` ist Singular, `encanta` passt nicht zu den Filmen im Plural.',
            avoid: 'encantar funktioniert exakt wie gustar.',
          },
        },
        {
          id: 'es.g.gustar.L3.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.gustar'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Wir mögen den Regen nicht.',
          answers: ['No nos gusta la lluvia.', 'A nosotros no nos gusta la lluvia.', 'A nosotras no nos gusta la lluvia.'],
          feedback: {
            rule: 'Verneinung: `no` + `nos` + `gusta` + Subjekt mit Artikel.',
            why: '„Nos no gusta“ ist falsch: `no` steht vor dem Pronomen.',
            avoid: 'Reihenfolge merken: no – nos – gusta.',
          },
        },
        {
          id: 'es.g.gustar.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.gustar'],
          difficulty: 3,
          prompt: 'Erzähle, was du magst und was nicht: Nenne mindestens eine Sache, die dir gefällt, und eine, die dir nicht gefällt.',
          keywords: ['me gusta', 'me gustan', 'me encanta', 'me encantan', 'no me gusta', 'no me gustan'],
          minMatch: 2,
          sample: 'Me gusta mucho la música y me encantan los libros, pero no me gusta el frío.',
          feedback: {
            rule: 'Eine Sache/Tätigkeit → `me gusta`; mehrere Sachen → `me gustan`; Verneinung → `no me gusta(n)`.',
            why: 'Häufig hört man „Yo gusto…“ – die Person gehört aber als `me` vor das Verb.',
            avoid: 'Beginne jeden Satz mit `Me …` oder `No me …`.',
          },
        },
      ],
    },
  ],
  related: ['es.g.articles', 'es.g.pronouns', 'es.g.word-order-negation'],
};
