import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.hay',
  courseId: 'es',
  stageId: 'stage0',
  order: 15,
  category: 'Verben',
  title: 'Hay – es gibt',
  summary: 'Mit hay sagst du, dass etwas existiert oder vorhanden ist – eine einzige Form für Singular und Plural. Und wann du stattdessen estar brauchst.',
  keywords: [
    'hay', 'es gibt', 'haber', 'no hay', 'gibt es', 'da ist', 'da sind', 'vorhanden', 'hay oder está', 'hay vs estar',
    'Existenz', 'Ort', 'Einkaufen', 'Café',
  ],
  explanation: [
    {
      type: 'text',
      md: '`hay` bedeutet **„es gibt“** bzw. **„da ist / da sind“**. Es hat **nur diese eine Form** – egal, ob danach ein oder zwanzig Dinge kommen: `Hay un bar.` · `Hay tres bares.`',
    },
    {
      type: 'colored',
      parts: [
        { text: 'En', role: 'preposition' },
        { text: ' mi', role: 'pronoun' },
        { text: ' calle', role: 'noun' },
        { text: ' hay', role: 'verb' },
        { text: ' un', role: 'article' },
        { text: ' bar', role: 'object' },
        { text: ' y ' },
        { text: 'dos', role: 'other' },
        { text: ' farmacias', role: 'object' },
        { text: '.' },
      ],
      german: 'In meiner Straße gibt es eine Bar und zwei Apotheken.',
    },
    {
      type: 'table',
      title: 'Was nach hay stehen kann',
      headers: ['nach hay ✔', 'Beispiel'],
      rows: [
        ['un / una / unos / unas', 'Hay una farmacia aquí.'],
        ['Zahlen', 'Hay dos baños.'],
        ['mucho / poco …', 'Hay mucha gente.'],
        ['Nomen ohne Artikel', 'Hay pan y queso. · No hay leche.'],
        ['✘ el / la / los / las, mi, tu …', '→ dann estar: El bar está aquí.'],
      ],
    },
    {
      type: 'text',
      md: '**hay oder está?**\n- `hay` fragt/sagt, **ob** etwas existiert – oft etwas Unbestimmtes: `¿Hay un banco por aquí?` (Gibt es hier eine Bank?)\n- `está/están` sagt, **wo** sich ein bestimmtes, bekanntes Ding befindet: `El banco está en la plaza.` (Die Bank ist am Platz.)',
    },
    {
      type: 'mistake',
      wrong: 'Hay el museo en el centro.',
      right: 'El museo está en el centro.',
      why: 'Nach `hay` steht kein bestimmter Artikel. Wenn du über ein bestimmtes Ding sprichst und seinen Ort nennst, brauchst du `estar`.',
    },
    {
      type: 'tip',
      md: '**hay = es gibt – eine Form für alles.** Bestimmter Artikel dahinter? Dann nimm `estar`.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Im Café in Spanien: `¿Hay zumo de naranja?` („Gibt es Orangensaft?“)',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Im Café in Lateinamerika: `¿Hay jugo de naranja?` – `jugo` statt `zumo`.',
    },
    { type: 'audio', text: '¿Hay un supermercado cerca? – Sí, hay uno al lado del banco.', label: 'Mini-Dialog anhören' },
  ],
  examples: [
    {
      target: '¿Hay un supermercado cerca?',
      german: 'Gibt es einen Supermarkt in der Nähe?',
      parts: [
        { text: '¿Hay', role: 'verb' },
        { text: ' un', role: 'article' },
        { text: ' supermercado', role: 'object' },
        { text: ' cerca', role: 'adverb' },
        { text: '?' },
      ],
    },
    { target: 'En mi barrio hay dos parques.', german: 'In meinem Viertel gibt es zwei Parks.' },
    {
      target: 'No hay leche.',
      german: 'Es gibt keine Milch.',
      parts: [{ text: 'No', role: 'negation' }, { text: ' hay', role: 'verb' }, { text: ' leche', role: 'object' }, { text: '.' }],
      note: '„keine“ → `no hay` ohne Artikel.',
    },
    { target: 'Hay mucha gente en la playa.', german: 'Am Strand sind viele Leute.' },
    { target: '¿Qué hay de postre?', german: 'Was gibt es zum Nachtisch?' },
    { target: 'El supermercado está al lado del banco.', german: 'Der Supermarkt ist neben der Bank.', note: 'Bestimmtes Ding + Ort → estar.' },
    { target: '¿Hay zumo de naranja?', german: 'Gibt es Orangensaft?', variant: 'es-ES' },
    { target: '¿Hay jugo de naranja?', german: 'Gibt es Orangensaft?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Hay un bar.',
      german: 'Es gibt eine Bar.',
      md: 'Wie „es gibt“ hat `hay` kein echtes Subjekt und ändert sich nicht.',
    },
    {
      type: 'compare',
      target: 'Hay dos bares.',
      german: 'Da sind zwei Bars.',
      md: 'Deutsch wechselt bei „da ist/da sind“ in den Plural. `hay` bleibt `hay`.',
    },
    {
      type: 'compare',
      target: 'No hay pan.',
      german: 'Es gibt kein Brot.',
      md: '„kein“ wird zu `no` vor `hay` – das Nomen steht ohne Artikel.',
    },
    {
      type: 'compare',
      target: '¿Dónde está la estación?',
      german: 'Wo ist der Bahnhof?',
      md: 'Nach dem Ort eines **bestimmten** Dings fragt man mit `estar`, nicht mit `hay`.',
    },
  ],
  mistakes: [
    { wrong: 'Hay el museo cerca.', right: 'El museo está cerca.', why: 'Bestimmter Artikel → estar.' },
    { wrong: 'Son dos bancos en esta calle.', right: 'Hay dos bancos en esta calle.', why: '„Es sind/da sind“ im Sinne von „es gibt“ → `hay`.' },
    { wrong: 'No hay un pan.', right: 'No hay pan.', why: 'Nach `no hay` steht das Nomen meist ohne Artikel.' },
    { wrong: '¿Dónde hay el baño?', right: '¿Dónde está el baño?', why: 'Ort eines bestimmten Dings → `estar`.' },
    { wrong: 'Hay mis amigos en el bar.', right: 'Mis amigos están en el bar.', why: 'Nach Possessivbegleitern (mi, tu …) nie `hay`.' },
  ],
  mnemonic: '**hay = es gibt – eine Form für alles.** Bestimmtes Ding + Ort → estar.',
  levels: [
    {
      level: 1,
      title: 'Es gibt …',
      exercises: [
        {
          id: 'es.g.hay.L1.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.hay'],
          difficulty: 1,
          prompt: '„Gibt es hier ein Café?“',
          options: [
            { text: '¿Hay un café aquí?', why: 'Richtig: Existenz → `hay` + unbestimmter Artikel.' },
            { text: '¿Está un café aquí?', why: '`estar` steht nicht mit unbestimmtem Artikel für „gibt es“.' },
            { text: '¿Es un café aquí?', why: '`ser` fragt „Ist das hier ein Café?“ – nicht „gibt es“.' },
          ],
          answer: 0,
          feedback: {
            rule: '„Gibt es …?“ = `¿Hay …?`',
            why: '`ser` und `estar` drücken keine Existenz aus.',
            avoid: 'Suchst du etwas Unbestimmtes? → hay.',
          },
        },
        {
          id: 'es.g.hay.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.hay'],
          difficulty: 1,
          sentence: 'En la mesa ___ tres libros.',
          german: 'Auf dem Tisch liegen drei Bücher.',
          answers: [['hay']],
          bank: ['hay', 'están', 'son'],
          feedback: {
            rule: 'Zahl + Nomen (unbestimmt) → `hay`, auch im Plural.',
            why: '„Están tres libros“ ist falsch; `son` bedeutet „sie sind (Identität)“.',
            avoid: 'Kein bestimmter Artikel dahinter → hay.',
          },
        },
        {
          id: 'es.g.hay.L1.03',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.hay'],
          difficulty: 1,
          audio: 'No hay leche, pero hay agua.',
          question: 'Was gibt es?',
          options: ['Wasser, aber keine Milch', 'Milch, aber kein Wasser', 'Milch und Wasser'],
          answer: 0,
          feedback: {
            rule: '`no hay` = es gibt kein …; `hay` = es gibt.',
            why: 'Das `no` steht vor dem ersten `hay` – also fehlt die Milch.',
            avoid: 'Achte auf das kleine `no` vor `hay`.',
          },
        },
        {
          id: 'es.g.hay.L1.04',
          type: 'imageMatch',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.hay'],
          difficulty: 1,
          instruction: 'Was gibt es im Café? Ordne zu.',
          pairs: [
            { emoji: '☕', word: 'el café' },
            { emoji: '🥛', word: 'la leche' },
            { emoji: '🍞', word: 'el pan' },
            { emoji: '🍊', word: 'la naranja' },
            { emoji: '🧀', word: 'el queso' },
          ],
          feedback: {
            rule: 'el café, la leche, el pan, la naranja, el queso.',
            why: '`la leche` ist weiblich wie „die Milch“, aber `el pan` ist männlich (anders als „das Brot“) – das Deutsche hilft nicht immer.',
            avoid: 'Lerne jedes Wort mit Artikel – dann klappt später auch `hay una…/hay un…`.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'hay oder estar?',
      exercises: [
        {
          id: 'es.g.hay.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.hay'],
          difficulty: 2,
          sentence: '—¿___ un banco por aquí? —Sí, el banco ___ en la plaza.',
          german: '„Gibt es hier eine Bank?“ – „Ja, die Bank ist am Platz.“',
          answers: [['Hay'], ['está']],
          bank: ['Hay', 'está', 'es'],
          feedback: {
            rule: 'Existenz (unbestimmt) → `hay`; Ort eines bestimmten Dings → `está`.',
            why: 'In der Antwort ist es schon „die“ Bank (`el banco`) – also estar.',
            avoid: 'un/una → hay; el/la → está.',
          },
        },
        {
          id: 'es.g.hay.L2.02',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.hay'],
          difficulty: 2,
          sentence: 'Hay el museo en el centro.',
          german: 'Das Museum ist im Zentrum.',
          answers: ['El museo está en el centro.'],
          feedback: {
            rule: 'Bestimmtes Ding + Ortsangabe → `estar`.',
            why: 'Nach `hay` darf kein `el/la/los/las` stehen.',
            avoid: 'Stell dir die Frage: Existenz oder Lage? Lage → estar.',
          },
        },
        {
          id: 'es.g.hay.L2.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.hay'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Es gibt keine Milch.',
          answers: ['No hay leche.'],
          feedback: {
            rule: '„kein“ → `no hay` + Nomen ohne Artikel.',
            why: '„Hay no leche“ oder „No hay una leche“ sind falsch.',
            avoid: '`no` immer direkt vor `hay`.',
          },
        },
        {
          id: 'es.g.hay.L2.04',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.hay'],
          difficulty: 2,
          prompt: '„In Sevilla sind viele Touristen.“ – Welcher Satz passt?',
          options: [
            { text: 'En Sevilla hay muchos turistas.', why: 'Richtig: Existenz einer unbestimmten Menge → hay.' },
            { text: 'En Sevilla son muchos turistas.', why: '`ser` passt hier nicht – es geht nicht um Identität.' },
            { text: 'En Sevilla hayn muchos turistas.', why: '`hay` hat keine Pluralform.' },
          ],
          answer: 0,
          feedback: {
            rule: '„es gibt / da sind viele …“ → `hay muchos/muchas …`',
            why: 'Das deutsche „sind“ verleitet zu `son` oder zu einer Pluralform.',
            avoid: 'Mengenwörter (mucho, poco, dos …) + Nomen → hay.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Im Alltag',
      exercises: [
        {
          id: 'es.g.hay.L3.01',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.hay'],
          difficulty: 3,
          scenario: 'Du bist in einer fremden Stadt und brauchst eine Apotheke – egal welche. Du fragst eine Passantin:',
          options: [
            { text: 'Perdone, ¿hay una farmacia por aquí?', why: 'Richtig: Du suchst irgendeine Apotheke → hay + una.' },
            { text: 'Perdone, ¿está una farmacia por aquí?', why: '`estar` passt nicht zu einer unbestimmten Apotheke.' },
            { text: 'Perdone, ¿es una farmacia por aquí?', why: 'Das fragt eher „Ist das hier eine Apotheke?“.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Etwas Unbestimmtes suchen → `¿Hay un/una … por aquí?`',
            why: 'Erst wenn du eine bestimmte Apotheke meinst, fragst du `¿Dónde está la farmacia?`.',
            avoid: 'Merke die Formel: `Perdone, ¿hay un/una … por aquí?`',
          },
        },
        {
          id: 'es.g.hay.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.hay'],
          difficulty: 3,
          sentence: 'En mi ciudad ___ un museo muy bonito. El museo ___ cerca del río.',
          german: 'In meiner Stadt gibt es ein sehr schönes Museum. Das Museum liegt in der Nähe des Flusses.',
          answers: [['hay'], ['está']],
          feedback: {
            rule: 'Einführen mit `hay` (un museo), danach Ort mit `estar` (el museo).',
            why: 'Sobald das Museum bekannt ist (`el museo`), wird aus „es gibt“ ein „befindet sich“.',
            avoid: 'Erste Erwähnung: hay + un. Weitere Erwähnung: el + está.',
          },
        },
        {
          id: 'es.g.hay.L3.03',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.hay'],
          difficulty: 3,
          tokens: ['¿Qué', 'hay', 'de', 'postre?'],
          extra: ['está', 'es'],
          german: 'Was gibt es zum Nachtisch?',
          feedback: {
            rule: '„Was gibt es …?“ = `¿Qué hay …?`',
            why: '`está`/`es` drücken kein „es gibt“ aus.',
            avoid: 'Speisekarte, Angebot, Programm → `¿Qué hay…?`',
          },
        },
        {
          id: 'es.g.hay.L3.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.hay'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Gibt es hier in der Nähe einen Supermarkt?',
          answers: [
            '¿Hay un supermercado cerca?',
            '¿Hay un supermercado por aquí?',
            '¿Hay un supermercado aquí cerca?',
            '¿Hay un supermercado cerca de aquí?',
            '¿Hay algún supermercado cerca?',
            '¿Hay algún supermercado por aquí?',
            '¿Hay un supermercado por aquí cerca?',
            '¿Hay algún supermercado aquí cerca?',
          ],
          feedback: {
            rule: '`¿Hay un …?` + Ortsangabe (`cerca`, `por aquí`).',
            why: '„¿Está un supermercado…?“ ist falsch – unbestimmte Dinge stehen mit hay.',
            avoid: '„Gibt es …?“ fängt auf Spanisch immer mit `¿Hay…?` an.',
          },
        },
      ],
    },
  ],
  related: ['es.g.estar', 'es.g.numbers', 'es.g.articles'],
};
