import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.imperative-tu',
  courseId: 'es',
  stageId: 'a1',
  order: 7,
  category: 'Verben',
  title: 'Imperativ mit tú – Anweisungen & Wege',
  summary: 'Der bejahte tú-Imperativ ist einfach die er/sie-Form: sigue, gira, toma, cruza. Dazu die usted-Formen siga, gire, tome, cruce als feste Wendungen für höfliche Wegbeschreibungen.',
  keywords: [
    'Imperativ', 'Befehlsform', 'Aufforderung', 'Anweisung', 'Wegbeschreibung', 'nach dem Weg fragen', 'tú', 'usted',
    'sigue', 'siga', 'gira', 'gire', 'toma', 'tome', 'cruza', 'cruce', 'recto', 'geradeaus', 'derecha', 'izquierda',
    'rechts', 'links', 'primero', 'después', 'al final', 'perdone', 'perdona', 'cómo llego', 'Ordnungszahlen', 'segunda',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Der **bejahte Imperativ für tú** ist leicht: Nimm die Präsensform von **él/ella** – fertig. `tomar → toma`, `comer → come`, `subir → sube`. Das gilt für alle regelmäßigen Verben und auch für Stammwechsler: `seguir → sigue`.',
    },
    {
      type: 'table',
      title: 'tú- und usted-Imperativ',
      headers: ['Infinitiv', 'él/ella (Präsens)', 'Imperativ tú', 'Imperativ usted'],
      rows: [
        ['tomar (nehmen)', 'toma', 'toma', 'tome'],
        ['girar (abbiegen)', 'gira', 'gira', 'gire'],
        ['cruzar (überqueren)', 'cruza', 'cruza', 'cruce'],
        ['hablar (sprechen)', 'habla', 'habla', 'hable'],
        ['comer (essen)', 'come', 'come', 'coma'],
        ['subir (hinaufgehen)', 'sube', 'sube', 'suba'],
        ['seguir (weitergehen)', 'sigue', 'sigue', 'siga'],
      ],
    },
    {
      type: 'text',
      md: 'Die **usted-Formen** lernst du am besten als feste Wendungen (Chunks). Das Muster: Der Endvokal „tauscht“ – **-ar**-Verben bekommen **-e** (`gire`, `tome`), **-er/-ir**-Verben bekommen **-a** (`coma`, `siga`). Aus `z` wird vor `e` ein `c`: `cruce`. Mit usted klingt jede Anweisung automatisch höflich.',
    },
    {
      type: 'table',
      title: 'Wegbeschreibung – die wichtigsten Chunks',
      headers: ['tú', 'usted', 'Deutsch'],
      rows: [
        ['Perdona, ¿cómo llego a …?', 'Perdone, ¿cómo llego a …?', 'Entschuldigung, wie komme ich zu …?'],
        ['Sigue (todo) recto.', 'Siga (todo) recto.', 'Geradeaus (weiter).'],
        ['Gira a la derecha.', 'Gire a la derecha.', 'Rechts abbiegen.'],
        ['Gira a la izquierda.', 'Gire a la izquierda.', 'Links abbiegen.'],
        ['Toma la segunda calle.', 'Tome la segunda calle.', 'Die zweite Straße nehmen.'],
        ['Cruza la plaza.', 'Cruce la plaza.', 'Den Platz überqueren.'],
        ['Al final de la calle, gira …', 'Al final de la calle, gire …', 'Am Ende der Straße abbiegen …'],
      ],
    },
    {
      type: 'text',
      md: 'Die Schritte ordnest du mit `primero` (zuerst), `después` oder `luego` (danach, dann) und `al final` (am Ende, zum Schluss). Diese Wörter sind für tú und usted gleich.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Primero', role: 'adverb' },
        { text: ' sigue', role: 'verb' },
        { text: ' recto', role: 'adverb' },
        { text: ' y' },
        { text: ' después', role: 'adverb' },
        { text: ' gira', role: 'verb' },
        { text: ' a la derecha', role: 'preposition' },
        { text: '.' },
      ],
      german: 'Geh zuerst geradeaus und bieg dann rechts ab.',
    },
    {
      type: 'text',
      md: 'Für Straßen zählt man mit **Ordnungszahlen**, die vor dem Nomen stehen: `la primera calle`, `la segunda`, `la tercera`, `la cuarta`. **Verneinte** Befehle („Bieg nicht ab!“) haben eine andere Form – die lernst du später. Ebenso ein paar kurze Ausnahmen wie `ven` (komm!).',
    },
    {
      type: 'mistake',
      wrong: 'Perdone, señor: cruza la calle y gira a la derecha.',
      right: 'Perdone, señor: cruce la calle y gire a la derecha.',
      why: 'Wer `usted` anspricht (`perdone`, `señor`), sollte auch bei den Anweisungen bei usted bleiben – sonst mischst du „Sie“ und „du“.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien sagt man für Verkehrsmittel oft `coger`: `Coge el metro.` In vielen Ländern Lateinamerikas ist `coger` vulgär – dort immer `toma`/`tome`.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika zählt man Häuserblocks: `Camine dos cuadras y doble a la derecha.` (`doblar` = abbiegen). In Argentinien und Uruguay (vos) klingt der Imperativ anders und ist hinten betont: `seguí`, `girá`, `tomá`, `cruzá`.',
    },
    { type: 'tip', md: '**tú-Imperativ = er/sie-Form.** usted-Imperativ = „Vokaltausch“: gira → gire, sigue → siga.' },
    { type: 'audio', text: 'Perdone, ¿cómo llego a la estación? Siga todo recto, cruce la plaza y tome la segunda calle a la derecha.', label: 'Wegbeschreibung anhören' },
  ],
  examples: [
    {
      target: 'Sigue todo recto y gira a la derecha.',
      german: 'Geh immer geradeaus und bieg rechts ab.',
      parts: [
        { text: 'Sigue', role: 'verb' },
        { text: ' todo recto', role: 'adverb' },
        { text: ' y' },
        { text: ' gira', role: 'verb' },
        { text: ' a la derecha', role: 'preposition' },
        { text: '.' },
      ],
    },
    { target: 'Toma la segunda calle a la izquierda.', german: 'Nimm die zweite Straße links.' },
    {
      target: '—Perdone, ¿cómo llego a la estación? —Siga recto y cruce la plaza.',
      german: '„Entschuldigung, wie komme ich zum Bahnhof?“ – „Gehen Sie geradeaus und überqueren Sie den Platz.“',
    },
    {
      target: 'Primero cruza el puente y después gira a la izquierda.',
      german: 'Überquer zuerst die Brücke und bieg dann links ab.',
      parts: [
        { text: 'Primero', role: 'adverb' },
        { text: ' cruza', role: 'verb' },
        { text: ' el puente', role: 'object' },
        { text: ' y' },
        { text: ' después', role: 'adverb' },
        { text: ' gira', role: 'verb' },
        { text: ' a la izquierda', role: 'preposition' },
        { text: '.' },
      ],
    },
    { target: 'Habla más despacio, por favor.', german: 'Sprich bitte langsamer.' },
    { target: 'Escribe tu nombre aquí.', german: 'Schreib deinen Namen hierhin.' },
    { target: 'Al final de la calle, gire a la derecha.', german: 'Biegen Sie am Ende der Straße rechts ab.' },
    { target: 'Coge el metro en la plaza.', german: 'Nimm die U-Bahn am Platz.', variant: 'es-ES' },
    { target: 'Camina dos cuadras y dobla a la izquierda.', german: 'Geh zwei Blocks und bieg links ab.', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Gira a la derecha.',
      german: 'Bieg rechts ab.',
      md: 'Deutsch kürzt beim du-Imperativ die Endung („bieg!“). Spanisch nimmt einfach die er/sie-Form: `gira`.',
    },
    {
      type: 'compare',
      target: 'Gire a la derecha.',
      german: 'Biegen Sie rechts ab.',
      md: 'Im Deutschen steht „Sie“ dabei. Im Spanischen lässt man `usted` meist weg – die Form `gire` zeigt die Höflichkeit schon.',
    },
    {
      type: 'compare',
      target: 'Sigue todo recto.',
      german: 'Geh immer geradeaus.',
      md: '`seguir` heißt „weitermachen, folgen“ – also eher „geradeaus weiter“. Gilt für Fußgänger und Autofahrer.',
    },
    {
      type: 'compare',
      target: 'Toma la segunda calle.',
      german: 'Nimm die zweite Straße.',
      md: 'Die Ordnungszahl steht wie im Deutschen vor dem Nomen und passt sich an: `la segunda calle`, `el segundo semáforo`.',
    },
  ],
  mistakes: [
    { wrong: 'Sige todo recto.', right: 'Sigue todo recto.', why: 'Vor `e` braucht das harte g ein stummes u: `gue`. `sige` würde man „si-che“ sprechen.' },
    { wrong: 'Cruze la plaza.', right: 'Cruce la plaza.', why: 'Vor `e` schreibt man `c` statt `z`: `cruzar → cruce`.' },
    { wrong: 'Perdone, señora, gira a la derecha.', right: 'Perdone, señora, gire a la derecha.', why: 'Bei usted auch die usted-Form des Imperativs verwenden.' },
    { wrong: 'Gira en la derecha.', right: 'Gira a la derecha.', why: 'Die Richtung steht mit `a`: `a la derecha`, `a la izquierda`.' },
    { wrong: 'Perdone, ¿dónde es la estación?', right: 'Perdone, ¿dónde está la estación?', why: 'Nach dem Ort fragt man mit `estar`.' },
  ],
  mnemonic: '**tú-Befehl = er/sie-Form** (gira, sigue, toma). **usted-Befehl = Vokal tauschen** (gire, siga, tome).',
  levels: [
    {
      level: 1,
      title: 'Formen erkennen und bilden',
      exercises: [
        {
          id: 'es.g.imperative-tu.L1.01',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 1,
          verb: 'tomar',
          tense: 'Imperativ',
          person: 'tú',
          sentence: '___ la segunda calle a la derecha.',
          answers: ['toma'],
          feedback: {
            rule: 'tú-Imperativ = Präsensform von él/ella: `toma`.',
            why: '`tomas` ist die Aussage „du nimmst“, `tome` die usted-Form.',
            avoid: 'Frag dich: Wie heißt „er nimmt“? → `toma` – das ist dein Befehl.',
          },
        },
        {
          id: 'es.g.imperative-tu.L1.02',
          type: 'matchPairs',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 1,
          instruction: 'Ordne die Anweisungen zu.',
          pairs: [
            { left: 'Sigue recto.', right: 'Geh geradeaus.' },
            { left: 'Gira a la derecha.', right: 'Bieg rechts ab.' },
            { left: 'Gira a la izquierda.', right: 'Bieg links ab.' },
            { left: 'Cruza la calle.', right: 'Überquer die Straße.' },
            { left: 'Toma la primera calle.', right: 'Nimm die erste Straße.' },
          ],
          feedback: {
            rule: 'Die fünf Grundbausteine jeder Wegbeschreibung.',
            why: '`derecha` (rechts) und `izquierda` (links) werden am häufigsten verwechselt.',
            avoid: 'dere**ch**a – re**ch**ts: beide mit „ch“. `izquierda` ist dann links.',
          },
        },
        {
          id: 'es.g.imperative-tu.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 1,
          prompt: 'Du sagst zu einer Freundin: „Sprich bitte langsamer.“',
          options: [
            { text: 'Habla más despacio, por favor.', why: 'Richtig: tú-Imperativ = `habla`.' },
            { text: 'Hablas más despacio, por favor.', why: '`hablas` ist die Aussage „du sprichst“.' },
            { text: 'Hable más despacio, por favor.', why: '`hable` ist die usted-Form – zu förmlich für eine Freundin.' },
          ],
          answer: 0,
          feedback: {
            rule: 'tú-Imperativ ohne -s: `habla`.',
            why: 'Mit -s wird es eine Aussage oder Frage.',
            avoid: 'Befehl an tú = er/sie-Form.',
          },
        },
        {
          id: 'es.g.imperative-tu.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 1,
          audio: 'Sigue todo recto y después gira a la izquierda.',
          question: 'Was sollst du zum Schluss tun?',
          options: ['links abbiegen', 'rechts abbiegen', 'die Straße überqueren'],
          answer: 0,
          feedback: {
            rule: '`gira a la izquierda` = bieg links ab; `después` = danach.',
            why: 'Rechts wäre `a la derecha`, überqueren `cruza`.',
            avoid: 'Achte auf das letzte Wort: _izquierda_ – links.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'tú oder usted?',
      exercises: [
        {
          id: 'es.g.imperative-tu.L2.01',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.imperative-tu', 'es.g.formality'],
          difficulty: 2,
          scenario: 'Du fragst eine ältere Dame auf der Straße nach dem Weg zum Bahnhof.',
          options: [
            { text: 'Perdone, ¿cómo llego a la estación?', why: 'Richtig: höfliches `perdone` (usted) und die feste Frage `¿cómo llego a…?`.' },
            { text: 'Oye, ¿cómo llego a la estación?', why: '`oye` („hör mal“) ist unter Freunden okay, aber bei Fremden zu salopp.' },
            { text: 'Perdone, ¿cómo llegas a la estación?', why: '`llegas` fragt, wie **sie** hinkommt – und mischt usted und tú.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Wegfrage an Fremde: `Perdone, ¿cómo llego a …?`',
            why: '`llego` = ich komme an – du fragst nach deinem eigenen Weg.',
            avoid: 'Lerne den Satz als Ganzes: „Perdone, ¿cómo llego a…?“',
          },
        },
        {
          id: 'es.g.imperative-tu.L2.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 2,
          verb: 'girar',
          tense: 'Imperativ',
          person: 'usted',
          sentence: '___ a la derecha, por favor.',
          answers: ['gire'],
          feedback: {
            rule: 'usted-Imperativ von -ar-Verben: Endung -e → `gire`.',
            why: '`gira` ist die tú-Form.',
            avoid: '-ar → -e, -er/-ir → -a („Vokaltausch“).',
          },
        },
        {
          id: 'es.g.imperative-tu.L2.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 2,
          sentence: 'Perdone, señora: ___ recto y ___ la plaza.',
          german: 'Entschuldigen Sie: Gehen Sie geradeaus und überqueren Sie den Platz.',
          answers: [['siga'], ['cruce']],
          bank: ['sigue', 'siga', 'cruza', 'cruce'],
          feedback: {
            rule: 'usted: `siga`, `cruce` (z → c vor e).',
            why: '`sigue` und `cruza` sind die tú-Formen – passen nicht zu `perdone, señora`.',
            avoid: 'Einmal usted, immer usted.',
          },
        },
        {
          id: 'es.g.imperative-tu.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 2,
          sentence: 'Sige todo recto.',
          german: 'Geh immer geradeaus.',
          answers: ['Sigue todo recto.'],
          feedback: {
            rule: 'Hartes g vor e wird `gu` geschrieben: `sigue`.',
            why: '`sige` spräche man „si-che“.',
            avoid: 'seguir → sigo, **sigue**s, **sigue** – das u bleibt vor e.',
          },
        },
        {
          id: 'es.g.imperative-tu.L2.05',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 2,
          tokens: ['Toma', 'la', 'segunda', 'calle', 'a', 'la', 'izquierda', '.'],
          german: 'Nimm die zweite Straße links.',
          feedback: {
            rule: 'Ordnungszahl vor dem Nomen: `la segunda calle`; Richtung mit `a la …`.',
            why: '`la calle segunda` klingt im Alltag falsch.',
            avoid: 'Wie im Deutschen: „die zweite Straße“.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Wegbeschreibungen geben',
      exercises: [
        {
          id: 'es.g.imperative-tu.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Überquer die Straße und bieg links ab.',
          answers: [
            'Cruza la calle y gira a la izquierda.',
            'Cruza la calle y dobla a la izquierda.',
            'Cruza la calle y después gira a la izquierda.',
          ],
          feedback: {
            rule: 'tú-Imperativ: `cruza`, `gira`; Richtung: `a la izquierda`.',
            why: '`cruzas`/`giras` wären Aussagen, `cruce`/`gire` usted-Formen.',
            avoid: 'Befehl an „du“ = er/sie-Form.',
          },
        },
        {
          id: 'es.g.imperative-tu.L3.02',
          type: 'translate',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 3,
          direction: 'toGerman',
          source: 'Siga recto y tome la primera calle a la derecha.',
          answers: [
            'Gehen Sie geradeaus und nehmen Sie die erste Straße rechts.',
            'Gehen Sie geradeaus und nehmen Sie die erste Straße nach rechts.',
            'Gehen Sie geradeaus und biegen Sie in die erste Straße rechts ab.',
            'Fahren Sie geradeaus und nehmen Sie die erste Straße rechts.',
            'Fahren Sie geradeaus und biegen Sie in die erste Straße rechts ab.',
            'Gehen Sie geradeaus weiter und nehmen Sie die erste Straße rechts.',
          ],
          feedback: {
            rule: '`siga`, `tome` sind usted-Formen → „Gehen Sie …, nehmen Sie …“.',
            why: 'Eine du-Übersetzung („Geh …“) passt nicht zur usted-Form.',
            avoid: 'Endung -e bei -ar-Verben (tome) → „Sie“.',
          },
        },
        {
          id: 'es.g.imperative-tu.L3.03',
          type: 'dialogue',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 3,
          lines: [
            { speaker: 'Turista', text: 'Perdone, ¿cómo llego al museo?', german: 'Entschuldigung, wie komme ich zum Museum?' },
            { speaker: 'Señor', text: 'Siga todo recto y gire a la izquierda.', german: 'Gehen Sie immer geradeaus und biegen Sie links ab.' },
            { speaker: 'Turista', text: 'Muchas gracias.', german: 'Vielen Dank.' },
          ],
          gapIndex: 1,
          options: [
            'Siga todo recto y gire a la izquierda.',
            'Sigo todo recto y giro a la izquierda.',
            'El museo es todo recto a la izquierda.',
          ],
          answer: 0,
          feedback: {
            rule: 'Wegbeschreibung an usted: `siga`, `gire`.',
            why: '`sigo/giro` bedeutet „ich gehe/ich biege ab“; die Lage mit `es` ist falsch.',
            avoid: 'Antwort auf `perdone` → usted-Formen.',
          },
        },
        {
          id: 'es.g.imperative-tu.L3.04',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 3,
          prompt: 'Erkläre einer Freundin (tú) den Weg von deiner Wohnung zum Supermarkt – mit `primero`, `después` und mindestens zwei Imperativen.',
          keywords: ['primero', 'después', 'luego', 'sigue', 'gira', 'toma', 'cruza', 'derecha', 'izquierda', 'recto', 'calle'],
          minMatch: 4,
          sample: 'Primero sigue todo recto. Después gira a la derecha, cruza la calle y el supermercado está a la izquierda.',
          feedback: {
            rule: 'tú-Imperativ = er/sie-Form; Reihenfolge mit primero, después, al final.',
            why: 'Häufig rutscht ein -s hinein (`giras`) – das ist dann eine Aussage.',
            avoid: 'Sprich in kurzen Schritten: Verb + Richtung.',
          },
        },
        {
          id: 'es.g.imperative-tu.L3.05',
          type: 'freeText',
          skills: ['writing', 'grammar'],
          topicIds: ['es.g.imperative-tu'],
          difficulty: 3,
          prompt: 'Schreib eine kurze, höfliche Wegbeschreibung (usted) für einen Touristen – mit drei Schritten.',
          requirements: [
            { pattern: '\\b(siga|gire|tome|cruce)\\b', hint: 'mindestens eine usted-Form (siga, gire, tome, cruce)' },
            { pattern: '(derecha|izquierda|recto)', hint: 'eine Richtung (derecha, izquierda, recto)' },
            { pattern: '(primero|despu[eé]s|luego|al final)', hint: 'ein Ordnungswort (primero, después, luego, al final)' },
          ],
          samples: ['Primero siga recto. Después gire a la derecha y tome la segunda calle a la izquierda.'],
          minWords: 8,
          feedback: {
            rule: 'usted-Imperativ: siga, gire, tome, cruce.',
            why: 'tú-Formen (sigue, gira) wirken bei Fremden zu vertraut.',
            avoid: 'Prüfe jedes Verb: -ar → -e, -er/-ir → -a.',
          },
        },
      ],
    },
  ],
  related: ['es.g.present-regular', 'es.g.formality', 'es.g.prepositions-place'],
};
