import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.ir-a',
  courseId: 'es',
  stageId: 'a1',
  order: 4,
  category: 'Verben',
  title: 'Ir a – Pläne & nahe Zukunft',
  summary: 'Das Verb ir („gehen, fahren“) und die Konstruktion ir a + Infinitiv für alles, was du vorhast.',
  keywords: [
    'ir', 'gehen', 'fahren', 'ir a', 'Zukunft', 'Futur', 'nahe Zukunft', 'Pläne', 'vorhaben', 'werden', 'voy', 'vas', 'va', 'vamos',
    'vais', 'van', 'voy a', 'vamos a', 'lass uns', 'al', 'Wochenende',
  ],
  explanation: [
    {
      type: 'conjugation',
      verb: 'ir',
      translation: 'gehen, fahren',
      tense: 'Präsens (unregelmäßig)',
      rows: [
        { person: 'yo', form: 'voy' },
        { person: 'tú', form: 'vas' },
        { person: 'él / ella / usted', form: 'va' },
        { person: 'nosotros / nosotras', form: 'vamos' },
        { person: 'vosotros / vosotras', form: 'vais', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'van' },
      ],
    },
    {
      type: 'text',
      md: '**1. ir a + Ort** = irgendwohin gehen/fahren: `Voy a Madrid.` · `Vamos a la playa.` · `Voy al cine.` (a + el = al). Das deutsche „zu, nach, in, an“ wird hier einfach `a`.',
    },
    {
      type: 'text',
      md: '**2. ir a + Infinitiv** = etwas vorhaben, gleich tun werden – die **nahe Zukunft**. Nur `ir` wird konjugiert, das zweite Verb bleibt im Infinitiv: `Voy a estudiar.` (Ich werde lernen / Ich lerne gleich.)',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Esta noche', role: 'adverb' },
        { text: ' vamos', role: 'verb' },
        { text: ' a', role: 'preposition' },
        { text: ' cenar', role: 'verb' },
        { text: ' en casa', role: 'object' },
        { text: '.' },
      ],
      german: 'Heute Abend essen wir zu Hause (zu Abend). – ir + a + Infinitiv.',
    },
    {
      type: 'text',
      md: 'Typische Zeitangaben dazu: `mañana` (morgen), `esta tarde` (heute Nachmittag), `esta noche` (heute Abend), `el fin de semana` (am Wochenende), `la semana que viene` (nächste Woche). Und: `¡Vamos a …!` heißt auch **„Lass uns …!“**: `¡Vamos a bailar!`',
    },
    {
      type: 'mistake',
      wrong: 'Voy comer.',
      right: 'Voy a comer.',
      why: 'Das `a` zwischen `ir` und dem Infinitiv ist Pflicht – es fehlt Deutschsprachigen oft, weil „Ich werde essen“ kein Zwischenwort hat.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: `¿Vais a venir a la fiesta?` – „Kommt ihr zur Party?“ (vosotros).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: `¿Van a venir a la fiesta?` (ustedes). Tipp: Sag `Voy a tomar el autobús` („den Bus nehmen“). Das in Spanien übliche `coger` klingt in mehreren Ländern Lateinamerikas vulgär.',
    },
    { type: 'tip', md: '**ir + a + Infinitiv – das kleine a ist die Brücke in die Zukunft.**' },
    { type: 'audio', text: 'Mañana voy a estudiar y el sábado vamos a la playa.', label: 'Pläne anhören' },
  ],
  examples: [
    {
      target: 'Voy a estudiar esta tarde.',
      german: 'Ich werde heute Nachmittag lernen.',
      parts: [
        { text: 'Voy', role: 'verb' },
        { text: ' a', role: 'preposition' },
        { text: ' estudiar', role: 'verb' },
        { text: ' esta tarde', role: 'adverb' },
        { text: '.' },
      ],
    },
    { target: '¿Qué vas a hacer el fin de semana?', german: 'Was machst du am Wochenende?' },
    {
      target: 'Esta noche voy al cine.',
      german: 'Heute Abend gehe ich ins Kino.',
      parts: [
        { text: 'Esta noche', role: 'adverb' },
        { text: ' voy', role: 'verb' },
        { text: ' al', role: 'preposition' },
        { text: ' cine', role: 'noun' },
        { text: '.' },
      ],
    },
    { target: 'Mis padres van a viajar a Perú.', german: 'Meine Eltern werden nach Peru reisen.' },
    { target: 'Vamos a la playa.', german: 'Wir gehen an den Strand.' },
    { target: '¡Vamos a comer!', german: 'Lass uns essen!' },
    { target: '¿Vais a venir a la fiesta?', german: 'Kommt ihr zur Party?', variant: 'es-ES' },
    { target: '¿Van a venir a la fiesta?', german: 'Kommt ihr zur Party?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Voy a comer.',
      german: 'Ich werde essen. / Ich esse gleich.',
      md: 'Im Deutschen reicht oft das Präsens. Im Spanischen ist `ir a` die natürlichste Art, über Pläne zu sprechen.',
    },
    {
      type: 'compare',
      target: 'Mañana voy a trabajar. / Mañana trabajo.',
      german: 'Morgen arbeite ich.',
      md: 'Mit Zeitangabe geht wie im Deutschen auch das Präsens.',
    },
    {
      type: 'compare',
      target: 'Voy al médico · a Berlín · a la playa.',
      german: 'Ich gehe zum Arzt · nach Berlin · an den Strand.',
      md: 'Für alle deutschen Richtungswörter (zu, nach, in, an) steht bei `ir` einfach `a`.',
    },
    {
      type: 'compare',
      target: '¡Vamos a bailar!',
      german: 'Lass uns tanzen!',
      md: '`vamos a` + Infinitiv ist auch eine Einladung.',
    },
  ],
  mistakes: [
    { wrong: 'Voy comer.', right: 'Voy a comer.', why: 'Zwischen ir und Infinitiv steht immer `a`.' },
    { wrong: 'Voy a como.', right: 'Voy a comer.', why: 'Nach `ir a` bleibt das Verb im Infinitiv.' },
    { wrong: 'Voy a el cine.', right: 'Voy al cine.', why: '`a` + `el` = `al`.' },
    { wrong: 'Yo va a estudiar.', right: 'Yo voy a estudiar.', why: 'yo → `voy`.' },
    { wrong: 'Voy en Madrid.', right: 'Voy a Madrid.', why: 'Richtung („nach“) → `a`. `en` bezeichnet den Ort, an dem man ist.' },
  ],
  mnemonic: '**ir + a + Infinitiv – das kleine a ist die Brücke in die Zukunft.**',
  levels: [
    {
      level: 1,
      title: 'Formen von ir',
      exercises: [
        {
          id: 'es.g.ir-a.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ir-a'],
          difficulty: 1,
          instruction: 'Ordne Form und Bedeutung zu.',
          pairs: [
            { left: 'voy', right: 'ich gehe' },
            { left: 'vas', right: 'du gehst' },
            { left: 'va', right: 'er/sie geht' },
            { left: 'vamos', right: 'wir gehen' },
            { left: 'van', right: 'sie gehen' },
          ],
          feedback: {
            rule: 'ir: voy, vas, va, vamos, (vais), van.',
            why: 'Die Formen haben nichts mit dem Infinitiv `ir` gemein – sie beginnen alle mit v.',
            avoid: 'Denk an „v“ wie „voran“: voy, vas, va …',
          },
        },
        {
          id: 'es.g.ir-a.L1.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 1,
          verb: 'ir',
          tense: 'Präsens',
          person: 'yo',
          sentence: 'Mañana ___ a trabajar.',
          answers: ['voy'],
          feedback: {
            rule: 'yo → `voy`.',
            why: '`va` ist die er/sie-Form.',
            avoid: 'voy, soy, estoy – die drei wichtigsten yo-Formen auf -oy.',
          },
        },
        {
          id: 'es.g.ir-a.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ir-a'],
          difficulty: 1,
          prompt: 'Was bedeutet `Voy a comer.`?',
          options: [
            { text: 'Ich werde (gleich) essen.', why: 'Richtig: ir a + Infinitiv = nahe Zukunft.' },
            { text: 'Ich habe gegessen.', why: 'Vergangenheit wäre `He comido` / `Comí`.' },
            { text: 'Ich esse jeden Tag.', why: 'Das wäre `Como todos los días`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`ir a` + Infinitiv drückt Pläne und nahe Zukunft aus.',
            why: 'Die Form `voy` ist zwar Präsens, die ganze Konstruktion zeigt aber nach vorn.',
            avoid: 'voy a … = „Ich habe vor zu …“',
          },
        },
        {
          id: 'es.g.ir-a.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.ir-a'],
          difficulty: 1,
          audio: 'Vamos a la playa.',
          question: 'Wohin gehen sie?',
          options: ['an den Strand', 'ins Kino', 'nach Hause'],
          answer: 0,
          feedback: {
            rule: '`ir a` + Ort: `a la playa` = an den Strand.',
            why: 'Kino wäre `al cine`, nach Hause `a casa`.',
            avoid: 'Hör auf das Nomen nach `a`/`al`.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Pläne formulieren',
      exercises: [
        {
          id: 'es.g.ir-a.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 2,
          sentence: 'Esta noche ___ ___ cenar en casa.',
          german: 'Heute Abend essen wir zu Hause.',
          answers: [['vamos'], ['a']],
          feedback: {
            rule: 'nosotros → `vamos a` + Infinitiv.',
            why: 'Ohne `a` ist die Konstruktion unvollständig.',
            avoid: 'Immer als Dreierblock denken: vamos – a – cenar.',
          },
        },
        {
          id: 'es.g.ir-a.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 2,
          sentence: 'Voy ___ cine y después ___ la playa.',
          german: 'Ich gehe ins Kino und danach an den Strand.',
          answers: [['al'], ['a']],
          bank: ['al', 'a', 'a el', 'en'],
          feedback: {
            rule: '`a` + `el cine` = `al cine`; `a` + `la playa` bleibt getrennt.',
            why: '`a el` gibt es nicht; `en` bezeichnet den Ort, nicht die Richtung.',
            avoid: 'Richtung = a (al vor männlichen Nomen im Singular).',
          },
        },
        {
          id: 'es.g.ir-a.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 2,
          sentence: 'Mañana voy estudiar.',
          german: 'Morgen werde ich lernen.',
          answers: ['Mañana voy a estudiar.'],
          feedback: {
            rule: 'ir + **a** + Infinitiv.',
            why: 'Das `a` fehlt – ein typischer Fehler, weil das Deutsche kein Zwischenwort hat.',
            avoid: 'Nach voy/vas/va … vor einem Infinitiv immer `a` einsetzen.',
          },
        },
        {
          id: 'es.g.ir-a.L2.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Was wirst du am Wochenende machen?',
          answers: ['¿Qué vas a hacer el fin de semana?', '¿Qué vas a hacer este fin de semana?'],
          feedback: {
            rule: '`¿Qué vas a hacer …?` – Fragewort + ir a + Infinitiv.',
            why: '„¿Qué vas hacer?“ (ohne a) oder „¿Qué vas a haces?“ sind falsch.',
            avoid: 'Die Frage nach Plänen ist ein fester Baustein: ¿Qué vas a hacer…?',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Frei planen',
      exercises: [
        {
          id: 'es.g.ir-a.L3.01',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 3,
          verb: 'ir',
          tense: 'Präsens',
          person: 'ellos',
          sentence: 'Mis padres ___ a viajar a Perú.',
          answers: ['van'],
          feedback: {
            rule: 'ellos → `van`.',
            why: '`va` ist Singular, `vamos` heißt „wir“.',
            avoid: 'Plural 3. Person → -n.',
          },
        },
        {
          id: 'es.g.ir-a.L3.02',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 3,
          tokens: ['El', 'sábado', 'vamos', 'a', 'visitar', 'a', 'mis', 'abuelos.'],
          extra: ['al', 'visitamos'],
          alternatives: [['Vamos', 'a', 'visitar', 'a', 'mis', 'abuelos', 'el', 'sábado.']],
          german: 'Am Samstag besuchen wir meine Großeltern.',
          feedback: {
            rule: '`vamos a visitar` + `a mis abuelos` (vor Personen als Objekt steht ein zusätzliches `a`).',
            why: '`visitamos` ist bereits konjugiert und passt nicht nach `vamos a`.',
            avoid: 'Personen als Objekt: `visitar a alguien`.',
          },
        },
        {
          id: 'es.g.ir-a.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Lass uns tanzen!',
          answers: ['¡Vamos a bailar!', '¡Bailemos!'],
          feedback: {
            rule: '„Lass uns …!“ = `¡Vamos a …!` + Infinitiv, z. B. `¡Vamos a bailar!`',
            why: '„Deja nos bailar“ ist eine wörtliche, falsche Übertragung.',
            avoid: 'Einladung zu etwas → ¡Vamos a …!',
          },
        },
        {
          id: 'es.g.ir-a.L3.04',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-a'],
          difficulty: 3,
          variant: 'es-ES',
          verb: 'ir',
          tense: 'Präsens',
          person: 'vosotros',
          sentence: '¿___ a venir a la fiesta?',
          answers: ['vais'],
          feedback: {
            rule: 'vosotros → `vais` (ohne Akzent, einsilbig).',
            why: '`van` gehört zu ustedes.',
            avoid: 'vosotros-Formen enden auf -is.',
          },
        },
        {
          id: 'es.g.ir-a.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.ir-a'],
          difficulty: 3,
          prompt: 'Was hast du am Wochenende vor? Nenne mindestens zwei Pläne.',
          keywords: ['voy a', 'vamos a', 'va a', 'sábado', 'domingo', 'fin de semana'],
          minMatch: 2,
          sample: 'El sábado voy a visitar a mis padres y el domingo vamos a ir a la playa.',
          feedback: {
            rule: 'Pläne: `voy a` / `vamos a` + Infinitiv.',
            why: 'Häufig fehlt das `a` – oder das zweite Verb wird konjugiert.',
            avoid: 'Sprich in Blöcken: „voy a …“, „vamos a …“.',
          },
        },
      ],
    },
  ],
  related: ['es.g.articles', 'es.g.tener', 'es.g.present-regular'],
};
