import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.ir-venir',
  courseId: 'es',
  stageId: 'a1',
  order: 8,
  category: 'Verben',
  title: 'Ir und venir – gehen, fahren, kommen',
  summary: 'ir (voy, vas, va …) und venir (vengo, vienes …): Richtung mit a, Herkunft mit de, Verkehrsmittel mit en – und warum man auf „Kommst du?“ mit „¡Voy!“ antwortet.',
  keywords: [
    'ir', 'venir', 'gehen', 'fahren', 'kommen', 'voy', 'vas', 'va', 'vamos', 'vais', 'van', 'vengo', 'vienes', 'viene',
    'venimos', 'venís', 'vienen', 'Verkehrsmittel', 'en autobús', 'en metro', 'en tren', 'en coche', 'en carro', 'a pie',
    'zu Fuß', 'Richtung', 'adónde', 'de dónde', 'tardar', 'wie lange', 'salir', 'abfahren', 'al', 'del', 'unregelmäßig',
  ],
  explanation: [
    {
      type: 'conjugation',
      verb: 'ir',
      translation: 'gehen, fahren',
      tense: 'Präsens (ganz unregelmäßig)',
      rows: [
        { person: 'yo', form: 'voy', ending: 'oy' },
        { person: 'tú', form: 'vas', ending: 'as' },
        { person: 'él / ella / usted', form: 'va', ending: 'a' },
        { person: 'nosotros / nosotras', form: 'vamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'vais', ending: 'ais', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'van', ending: 'an' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'venir',
      translation: 'kommen',
      tense: 'Präsens (yo auf -go, e → ie)',
      rows: [
        { person: 'yo', form: 'vengo', ending: 'go' },
        { person: 'tú', form: 'vienes', ending: 'es' },
        { person: 'él / ella / usted', form: 'viene', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'venimos', ending: 'imos' },
        { person: 'vosotros / vosotras', form: 'venís', ending: 'ís', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'vienen', ending: 'en' },
      ],
    },
    {
      type: 'text',
      md: '`venir` funktioniert wie `tener`: yo auf **-go** (`vengo`), in den stammbetonten Formen **e → ie** (`vienes`, `viene`, `vienen`). `ir` kennst du schon von `ir a` + Infinitiv.',
    },
    {
      type: 'text',
      md: '**Die Perspektive entscheidet:** `ir` = sich vom Sprecher **weg** bewegen (hin zu einem anderen Ort). `venir` = sich **zum Sprecher hin** bewegen (hierher). Deshalb ruft man auf Spanisch `¡Voy!`, wenn jemand einen ruft – man geht ja zu ihm hin.',
    },
    {
      type: 'table',
      title: 'Richtung, Herkunft, Verkehrsmittel',
      headers: ['Wofür', 'Spanisch', 'Deutsch'],
      rows: [
        ['Ziel: a (+ el = al)', 'Voy a Madrid. · Voy al centro.', 'Ich fahre nach Madrid. · Ich fahre ins Zentrum.'],
        ['Herkunft: de (+ el = del)', 'Vengo de casa. · Vengo del trabajo.', 'Ich komme von zu Hause. · Ich komme von der Arbeit.'],
        ['Verkehrsmittel: en', 'en autobús, en metro, en tren, en avión, en bici', 'mit dem Bus, der U-Bahn, dem Zug, dem Flugzeug, dem Rad'],
        ['zu Fuß: a pie', 'Voy a pie.', 'Ich gehe zu Fuß.'],
        ['Dauer: tardar', '¿Cuánto tarda el autobús? – Tarda veinte minutos.', 'Wie lange braucht der Bus? – Zwanzig Minuten.'],
        ['Abfahrt: salir', '¿A qué hora sale el tren? – Sale a las nueve.', 'Wann fährt der Zug ab? – Um neun.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Voy', role: 'verb' },
        { text: ' al trabajo', role: 'preposition' },
        { text: ' en metro', role: 'preposition' },
        { text: ', pero' },
        { text: ' hoy', role: 'adverb' },
        { text: ' voy', role: 'verb' },
        { text: ' a pie', role: 'preposition' },
        { text: '.' },
      ],
      german: 'Ich fahre mit der U-Bahn zur Arbeit, aber heute gehe ich zu Fuß.',
    },
    {
      type: 'mistake',
      wrong: 'Voy con el autobús.',
      right: 'Voy en autobús.',
      why: 'Das deutsche „mit dem Bus“ wird zu `en` + Verkehrsmittel **ohne Artikel**. Einzige Ausnahme: `a pie` (zu Fuß).',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: `el coche` (Auto), `ir andando` (zu Fuß gehen), `¿Vais al cine?` (vosotros).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: `el carro` (u. a. Mexiko, Kolumbien) bzw. `el auto` (Argentinien, Chile), `ir caminando` (zu Fuß gehen), `el camión` (Bus in Mexiko), `¿Van al cine?` (ustedes).',
    },
    { type: 'tip', md: '**ir = weg von mir, venir = zu mir her.** Fahrzeuge mit `en`, Füße mit `a`: `en metro`, aber `a pie`.' },
    { type: 'audio', text: '¿Vienes a la fiesta? – ¡Sí, voy! Voy en metro, tarda solo diez minutos.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: 'Voy al trabajo en metro.',
      german: 'Ich fahre mit der U-Bahn zur Arbeit.',
      parts: [
        { text: 'Voy', role: 'verb' },
        { text: ' al trabajo', role: 'preposition' },
        { text: ' en metro', role: 'preposition' },
        { text: '.' },
      ],
    },
    { target: '¿Vienes a la fiesta esta noche?', german: 'Kommst du heute Abend zur Party?' },
    { target: 'Mis padres vienen de Berlín.', german: 'Meine Eltern kommen aus Berlin.' },
    { target: '—¿Cómo vas al centro? —Voy a pie.', german: '„Wie kommst du ins Zentrum?“ – „Ich gehe zu Fuß.“' },
    {
      target: '—¿Cuánto tarda el autobús? —Tarda veinte minutos.',
      german: '„Wie lange braucht der Bus?“ – „Er braucht zwanzig Minuten.“',
    },
    {
      target: '¿A qué hora sale el tren a Madrid?',
      german: 'Um wie viel Uhr fährt der Zug nach Madrid ab?',
      parts: [
        { text: '¿A qué hora', role: 'question' },
        { text: ' sale', role: 'verb' },
        { text: ' el tren', role: 'subject' },
        { text: ' a Madrid', role: 'preposition' },
        { text: '?' },
      ],
    },
    { target: '—¡La comida está lista! —¡Ya voy!', german: '„Das Essen ist fertig!“ – „Ich komme schon!“' },
    { target: 'Vamos en coche.', german: 'Wir fahren mit dem Auto.', variant: 'es-ES' },
    { target: 'Vamos en carro.', german: 'Wir fahren mit dem Auto.', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Voy a Madrid en tren.',
      german: 'Ich fahre mit dem Zug nach Madrid.',
      md: 'Spanisch unterscheidet nicht zwischen „gehen“ und „fahren“ – beides ist `ir`. Womit, sagt `en` + Verkehrsmittel.',
    },
    {
      type: 'compare',
      target: '¡Voy!',
      german: 'Ich komme!',
      md: '`venir` nur, wenn die Bewegung zum Sprecher hin geht. Gehst du zu jemand anderem, nimmst du `ir` – auch wenn man im Deutschen „kommen“ sagt: `Mañana voy a tu casa.` (Morgen komme ich zu dir.)',
    },
    {
      type: 'compare',
      target: '¿Vienes conmigo?',
      german: 'Kommst du mit (mir)?',
      md: 'Hier passt `venir`: Die andere Person soll sich zu dir, dem Sprecher, dazugesellen.',
    },
    {
      type: 'compare',
      target: 'Vengo del trabajo.',
      german: 'Ich komme von der Arbeit.',
      md: 'Herkunft und Ausgangspunkt mit `de` – und `de + el` wird zu `del`.',
    },
  ],
  mistakes: [
    { wrong: 'Voy en pie.', right: 'Voy a pie.', why: 'Zu Fuß = `a pie`. Nur Fahrzeuge stehen mit `en`.' },
    { wrong: 'Voy con el autobús.', right: 'Voy en autobús.', why: 'Verkehrsmittel: `en` + Nomen ohne Artikel.' },
    { wrong: '¡Vengo! (wenn man gerufen wird)', right: '¡Voy!', why: 'Du bewegst dich zum Rufenden hin, also weg von deinem Standpunkt → `ir`.' },
    { wrong: 'Voy a el cine.', right: 'Voy al cine.', why: '`a + el` wird immer zu `al`.' },
    { wrong: 'Veno de Alemania.', right: 'Vengo de Alemania.', why: 'yo-Form von venir mit -g-: `vengo` (wie `tengo`).' },
  ],
  mnemonic: '**ir = weg von mir, venir = zu mir her** – und Fahrzeuge fahren mit en, Füße gehen a pie.',
  levels: [
    {
      level: 1,
      title: 'Formen und Präpositionen',
      exercises: [
        {
          id: 'es.g.ir-venir.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 1,
          instruction: 'Ordne Form und Bedeutung zu.',
          pairs: [
            { left: 'voy', right: 'ich gehe / fahre' },
            { left: 'vengo', right: 'ich komme' },
            { left: 'vas', right: 'du gehst / fährst' },
            { left: 'vienes', right: 'du kommst' },
            { left: 'vamos', right: 'wir gehen / fahren' },
            { left: 'vienen', right: 'sie kommen' },
          ],
          feedback: {
            rule: 'ir: voy, vas, va, vamos, (vais), van · venir: vengo, vienes, viene, venimos, (venís), vienen.',
            why: '`vas` (du gehst) und `vienes` (du kommst) klingen am Anfang ähnlich.',
            avoid: 'venir beginnt immer mit **ven-** oder **vien-** (vengo, vienes, venimos); ir hat kurze Formen mit v + Vokal (voy, vas, va, vamos).',
          },
        },
        {
          id: 'es.g.ir-venir.L1.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 1,
          verb: 'venir',
          tense: 'Präsens',
          person: 'yo',
          sentence: 'Yo ___ de Alemania.',
          answers: ['vengo'],
          feedback: {
            rule: 'yo-Form von venir: `vengo`.',
            why: '`veno` oder `vieno` gibt es nicht.',
            avoid: 'Wie `tengo`: -go-Familie.',
          },
        },
        {
          id: 'es.g.ir-venir.L1.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 1,
          sentence: 'Voy ___ trabajo ___ autobús.',
          german: 'Ich fahre mit dem Bus zur Arbeit.',
          answers: [['al'], ['en']],
          bank: ['al', 'a', 'en', 'con', 'del'],
          feedback: {
            rule: 'Ziel: `a + el = al`; Verkehrsmittel: `en` ohne Artikel.',
            why: '`con el autobús` ist eine Lehnübersetzung aus dem Deutschen.',
            avoid: 'Wohin? → a/al. Womit? → en.',
          },
        },
        {
          id: 'es.g.ir-venir.L1.04',
          type: 'imageMatch',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 1,
          instruction: 'Ordne die Verkehrsmittel zu.',
          pairs: [
            { emoji: '🚌', word: 'el autobús' },
            { emoji: '🚇', word: 'el metro' },
            { emoji: '🚆', word: 'el tren' },
            { emoji: '✈️', word: 'el avión' },
            { emoji: '🚲', word: 'la bicicleta' },
            { emoji: '🚶', word: 'a pie' },
          ],
          feedback: {
            rule: 'Mit ir: `en autobús`, `en metro`, `en tren`, `en avión`, `en bicicleta` – aber `a pie`.',
            why: '`autobús` und `avión` tragen einen Akzent auf der letzten Silbe.',
            avoid: 'Lerne die Fahrzeuge gleich mit `en`.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'ir oder venir?',
      exercises: [
        {
          id: 'es.g.ir-venir.L2.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 2,
          prompt: '„Ich gehe zu Fuß.“',
          options: [
            { text: 'Voy a pie.', why: 'Richtig: zu Fuß = `a pie`.' },
            { text: 'Voy en pie.', why: '`en` steht nur bei Fahrzeugen.' },
            { text: 'Voy con pie.', why: 'Wörtlich „mit Fuß“ – so sagt man es nicht.' },
          ],
          answer: 0,
          feedback: {
            rule: '`a pie` ist die feste Wendung für „zu Fuß“.',
            why: 'Weil sonst alle Verkehrsmittel `en` bekommen, liegt `en pie` nahe – ist aber falsch.',
            avoid: 'Füße → a, Fahrzeuge → en.',
          },
        },
        {
          id: 'es.g.ir-venir.L2.02',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 2,
          scenario: 'Deine Mitbewohnerin ruft aus der Küche: „¡El café está listo!“ Du willst antworten: „Ich komme!“',
          options: [
            { text: '¡Voy!', why: 'Richtig: Du bewegst dich zu ihr hin → `ir`.' },
            { text: '¡Vengo!', why: '`venir` bedeutet „hierher zu mir kommen“ – passt aus deiner Sicht nicht.' },
            { text: '¡Vienes!', why: '`vienes` heißt „du kommst“.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Bewegung zum Gesprächspartner hin = `ir`: `¡Voy!`, `¡Ya voy!`.',
            why: 'Das deutsche „Ich komme!“ verleitet zu `vengo`.',
            avoid: 'Frag dich: Komme ich zu **mir** her? Nein → `ir`.',
          },
        },
        {
          id: 'es.g.ir-venir.L2.03',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 2,
          verb: 'venir',
          tense: 'Präsens',
          person: 'tú',
          sentence: '¿___ a la fiesta esta noche?',
          answers: ['vienes'],
          feedback: {
            rule: 'tú-Form von venir: `vienes` (e → ie).',
            why: '`venes` ohne i gibt es nicht – im betonten Stamm wird e zu ie.',
            avoid: 'Stammbetont → ie: vienes, viene, vienen.',
          },
        },
        {
          id: 'es.g.ir-venir.L2.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 2,
          audio: 'El autobús sale a las ocho y tarda veinte minutos.',
          question: 'Wie lange dauert die Fahrt?',
          options: ['20 Minuten', '8 Minuten', '2 Stunden'],
          answer: 0,
          feedback: {
            rule: '`tardar` = (Zeit) brauchen, dauern; `salir` = abfahren.',
            why: '`a las ocho` ist die Abfahrtszeit, nicht die Dauer.',
            avoid: 'tarda + Zeitspanne · sale a las + Uhrzeit.',
          },
        },
        {
          id: 'es.g.ir-venir.L2.05',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 2,
          sentence: '—¿De dónde ___? —___ del trabajo.',
          german: '„Woher kommst du?“ – „Ich komme von der Arbeit.“',
          answers: [['vienes'], ['Vengo']],
          bank: ['vas', 'vienes', 'Voy', 'Vengo'],
          feedback: {
            rule: 'Herkunft: `venir de` → `vienes`, `vengo`.',
            why: '`ir de` passt nicht zu „woher“.',
            avoid: 'de dónde → venir · adónde → ir.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Unterwegs sprechen',
      exercises: [
        {
          id: 'es.g.ir-venir.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Wir fahren mit dem Zug nach Madrid.',
          answers: [
            'Vamos a Madrid en tren.',
            'Vamos en tren a Madrid.',
            'Nosotros vamos a Madrid en tren.',
            'Nosotros vamos en tren a Madrid.',
            'Nosotras vamos a Madrid en tren.',
            'Nosotras vamos en tren a Madrid.',
          ],
          feedback: {
            rule: '„fahren“ = `ir`; Ziel mit `a`, Zug mit `en tren`.',
            why: '„Conducimos“ bedeutet selbst ein Auto steuern – im Zug fährt man mit `ir`.',
            avoid: 'gehen, fahren, fliegen → im Alltag fast immer `ir`.',
          },
        },
        {
          id: 'es.g.ir-venir.L3.02',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 3,
          sentence: 'Voy al centro con el metro.',
          german: 'Ich fahre mit der U-Bahn ins Zentrum.',
          answers: ['Voy al centro en metro.', 'Voy en metro al centro.'],
          feedback: {
            rule: 'Verkehrsmittel: `en metro` (ohne Artikel).',
            why: '`con el metro` ist eine wörtliche Übersetzung von „mit der U-Bahn“.',
            avoid: 'Womit? → en + Fahrzeug.',
          },
        },
        {
          id: 'es.g.ir-venir.L3.03',
          type: 'translate',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 3,
          direction: 'toGerman',
          source: '¿A qué hora sale el tren?',
          answers: [
            'Um wie viel Uhr fährt der Zug ab?',
            'Um wie viel Uhr fährt der Zug?',
            'Wann fährt der Zug ab?',
            'Wann fährt der Zug?',
            'Um welche Uhrzeit fährt der Zug ab?',
            'Um welche Uhrzeit fährt der Zug?',
          ],
          feedback: {
            rule: '`salir` = abfahren, losfahren (auch: hinausgehen).',
            why: '„Wann kommt der Zug an?“ wäre `¿A qué hora llega el tren?`',
            avoid: 'sale = fährt ab · llega = kommt an.',
          },
        },
        {
          id: 'es.g.ir-venir.L3.04',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 3,
          sentence: 'Mis amigos ___ a mi casa y después ___ juntos al cine.',
          german: 'Meine Freunde kommen zu mir, und danach gehen wir zusammen ins Kino.',
          answers: [['vienen'], ['vamos']],
          bank: ['van', 'vienen', 'vamos', 'venimos'],
          feedback: {
            rule: 'Zu mir her → `venir` (vienen); gemeinsam woanders hin → `ir` (vamos).',
            why: '`van a mi casa` sagt jemand, der nicht zu Hause ist; `venimos al cine` sagt man nur, wenn man selbst schon im Kino ist.',
            avoid: 'Stell dich an den Ort des Sprechers: hierher = venir, dorthin = ir.',
          },
        },
        {
          id: 'es.g.ir-venir.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.ir-venir'],
          difficulty: 3,
          prompt: 'Wie kommst du zur Arbeit, zur Uni oder zum Sprachkurs? Womit fährst du und wie lange dauert es?',
          keywords: ['voy', 'a pie', 'metro', 'autobús', 'tren', 'coche', 'carro', 'bicicleta', 'bici', 'tarda', 'minutos', 'al'],
          minMatch: 3,
          sample: 'Voy al trabajo en metro. Tarda veinte minutos. A veces voy a pie.',
          feedback: {
            rule: '`ir` + `a/al` + Ziel, `en` + Verkehrsmittel, `tarda` + Dauer.',
            why: 'Typisch sind `con el metro` oder `en pie`.',
            avoid: 'Bau dir einen Mustersatz: „Voy al … en …, tarda … minutos.“',
          },
        },
      ],
    },
  ],
  related: ['es.g.ir-a', 'es.g.tener', 'es.g.prepositions-place'],
};
