import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.muy-mucho',
  courseId: 'es',
  stageId: 'a1',
  order: 15,
  category: 'Adjektive',
  title: 'Muy oder mucho? – sehr, viel, sehr viel',
  summary: '`muy` steht vor Adjektiven und Adverbien und bleibt immer gleich. `mucho` begleitet Nomen (und passt sich an) oder steht nach dem Verb. Und „sehr viel“ heißt nie „muy mucho“.',
  keywords: [
    'muy', 'mucho', 'mucha', 'muchos', 'muchas', 'muchísimo', 'sehr', 'viel', 'viele', 'sehr viel', 'Adjektiv', 'Adverb', 'Nomen',
    'Verstärkung', 'Intensität', 'Mengenangabe', 'me gusta mucho', 'muy bien', 'mucho mejor', 'Menschen beschreiben',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Die Frage ist immer: **Was folgt – oder was steht davor?**\n- Vor einem **Adjektiv** oder **Adverb** steht `muy` (sehr). Es ändert sich nie.\n- Vor einem **Nomen** steht `mucho` (viel/viele) – es passt sich an wie ein Adjektiv: `mucho, mucha, muchos, muchas`.\n- Nach einem **Verb** steht `mucho` (sehr, viel) – unveränderlich.',
    },
    {
      type: 'table',
      title: 'muy oder mucho?',
      headers: ['Was folgt / steht davor?', 'Wort', 'Beispiel', 'Deutsch'],
      rows: [
        ['Adjektiv', 'muy', 'Es muy simpática.', 'Sie ist sehr nett.'],
        ['Adverb', 'muy', 'Vivo muy cerca.', 'Ich wohne sehr nah.'],
        ['Nomen', 'mucho / mucha / muchos / muchas', 'Tengo muchos amigos.', 'Ich habe viele Freunde.'],
        ['Verb (davor)', 'mucho', 'Trabaja mucho.', 'Er/Sie arbeitet viel.'],
        ['allein (Antwort)', 'mucho', '—¿Te gusta? —Sí, mucho.', '„Gefällt es dir?“ – „Ja, sehr.“'],
        ['mejor, peor, más, menos', 'mucho', 'Es mucho mejor.', 'Das ist viel besser.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Mi hermano', role: 'subject' },
        { text: ' es', role: 'verb' },
        { text: ' muy', role: 'adverb' },
        { text: ' alto', role: 'adjective' },
        { text: ', tiene' , role: 'verb' },
        { text: ' muchos', role: 'adjective' },
        { text: ' amigos', role: 'noun' },
        { text: ' y' },
        { text: ' habla', role: 'verb' },
        { text: ' mucho', role: 'adverb' },
        { text: '.' },
      ],
      german: 'Mein Bruder ist sehr groß, hat viele Freunde und redet viel.',
    },
    {
      type: 'text',
      md: 'Bei den bekannten Ausdrücken mit **Nomen** heißt „sehr“ auf Spanisch `mucho/mucha`: `Tengo mucha hambre` (hambre ist weiblich), `Tengo mucho frío`, `Hace mucho calor`. Und für „sehr viel“ gibt es ein eigenes Wort: `muchísimo` – `Me gusta muchísimo.`',
    },
    {
      type: 'mistake',
      wrong: 'Me gusta muy.',
      right: 'Me gusta mucho.',
      why: '`muy` braucht immer ein Adjektiv oder Adverb dahinter. Nach einem Verb – oder ganz allein – steht `mucho`.',
    },
    {
      type: 'mistake',
      wrong: 'Hay mucho gente.',
      right: 'Hay mucha gente.',
      why: '`gente` ist weiblich und Singular → `mucha gente` (viele Leute).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Umgangssprachlich hört man in Mexiko oft `bien` statt `muy` (`bien bonito` = sehr schön) und in Argentinien die Vorsilbe `re-` (`rebueno` = sehr gut). Mit `muy` liegst du überall richtig.',
    },
    { type: 'tip', md: '**muy + Adjektiv/Adverb. mucho + Nomen oder nach dem Verb.** Nie „muy mucho“ – dafür gibt es `muchísimo`.' },
    { type: 'audio', text: 'Mi hermana es muy simpática, tiene muchos amigos y trabaja mucho.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: 'Mi hermana es muy simpática.',
      german: 'Meine Schwester ist sehr nett.',
      parts: [
        { text: 'Mi hermana', role: 'subject' },
        { text: ' es', role: 'verb' },
        { text: ' muy', role: 'adverb' },
        { text: ' simpática', role: 'adjective' },
        { text: '.' },
      ],
    },
    { target: 'Trabajo mucho y duermo poco.', german: 'Ich arbeite viel und schlafe wenig.' },
    { target: 'Hay mucha gente en la plaza.', german: 'Auf dem Platz sind viele Leute.' },
    {
      target: 'Tengo muchos amigos en Madrid.',
      german: 'Ich habe viele Freunde in Madrid.',
      parts: [
        { text: 'Tengo', role: 'verb' },
        { text: ' muchos', role: 'adjective' },
        { text: ' amigos', role: 'noun' },
        { text: ' en Madrid', role: 'preposition' },
        { text: '.' },
      ],
    },
    { target: '—¿Te gusta Barcelona? —¡Sí, mucho!', german: '„Gefällt dir Barcelona?“ – „Ja, sehr!“' },
    { target: 'El metro es mucho más rápido.', german: 'Die U-Bahn ist viel schneller.' },
    { target: 'Muchas gracias, eres muy amable.', german: 'Vielen Dank, du bist sehr freundlich.' },
    { target: 'Mi abuelo tiene el pelo muy blanco.', german: 'Mein Großvater hat sehr weißes Haar.' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Me gusta mucho.',
      german: 'Es gefällt mir sehr.',
      md: 'Das deutsche „sehr“ nach einem Verb wird zu `mucho` – nicht zu `muy`.',
    },
    {
      type: 'compare',
      target: 'muchas personas',
      german: 'viele Personen',
      md: '„viel/viele“ vor einem Nomen = `mucho`, und es passt sich an wie ein Adjektiv.',
    },
    {
      type: 'compare',
      target: 'Tengo mucho frío.',
      german: 'Mir ist sehr kalt.',
      md: 'Deutsch: „sehr“ + Adjektiv. Spanisch: „viel“ + Nomen (`mucho frío` = viel Kälte).',
    },
    {
      type: 'compare',
      target: 'Es mucho mejor.',
      german: 'Das ist viel besser.',
      md: 'Vor Vergleichswörtern (`mejor`, `peor`, `más`, `menos`) steht wie im Deutschen „viel“ = `mucho`.',
    },
  ],
  mistakes: [
    { wrong: 'Me gusta muy.', right: 'Me gusta mucho.', why: 'Nach dem Verb → `mucho`.' },
    { wrong: 'Es mucho alto.', right: 'Es muy alto.', why: 'Vor einem Adjektiv → `muy`.' },
    { wrong: 'Tengo muy hambre.', right: 'Tengo mucha hambre.', why: '`hambre` ist ein (weibliches) Nomen → `mucha`.' },
    { wrong: 'Es muy mejor.', right: 'Es mucho mejor.', why: 'Vor `mejor/peor/más/menos` → `mucho`.' },
    { wrong: 'Me gusta muy mucho.', right: 'Me gusta muchísimo.', why: '„sehr viel“ = `muchísimo`; `muy mucho` gibt es nicht.' },
  ],
  mnemonic: '**muy + Adjektiv, mucho + Nomen oder nach dem Verb** – und nie „muy mucho“.',
  levels: [
    {
      level: 1,
      title: 'muy oder mucho?',
      exercises: [
        {
          id: 'es.g.muy-mucho.L1.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 1,
          sentence: 'Mi casa está ___ cerca.',
          german: 'Mein Haus ist sehr nah.',
          answers: [['muy']],
          bank: ['muy', 'mucho', 'mucha'],
          feedback: {
            rule: 'Vor einem Adverb (`cerca`) → `muy`.',
            why: '`mucho` steht vor Nomen oder nach dem Verb.',
            avoid: 'Kann man „sehr“ direkt vor ein Eigenschaftswort setzen? → muy.',
          },
        },
        {
          id: 'es.g.muy-mucho.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 1,
          sentence: 'Tengo ___ amigos.',
          german: 'Ich habe viele Freunde.',
          answers: [['muchos']],
          bank: ['muy', 'mucho', 'muchos', 'muchas'],
          feedback: {
            rule: 'Vor einem Nomen im männlichen Plural → `muchos`.',
            why: '`muy` passt nie vor ein Nomen; `mucho` wäre Singular.',
            avoid: 'mucho passt sich an: muchos amigos, muchas amigas.',
          },
        },
        {
          id: 'es.g.muy-mucho.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 1,
          prompt: '„Es gefällt mir sehr.“',
          options: [
            { text: 'Me gusta mucho.', why: 'Richtig: nach dem Verb → `mucho`.' },
            { text: 'Me gusta muy.', why: '`muy` braucht ein Adjektiv danach.' },
            { text: 'Me gusta muy mucho.', why: '`muy mucho` gibt es nicht; „sehr, sehr“ = `muchísimo`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Verb + `mucho`.',
            why: 'Das deutsche „sehr“ verleitet zu `muy`.',
            avoid: 'Nach gustar immer: mucho.',
          },
        },
        {
          id: 'es.g.muy-mucho.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 1,
          audio: 'Mi novio es muy alto y habla mucho.',
          question: 'Was stimmt?',
          options: ['Er ist sehr groß und redet viel.', 'Er ist klein und redet wenig.', 'Er ist groß, aber sehr still.'],
          answer: 0,
          feedback: {
            rule: '`muy alto` = sehr groß; `habla mucho` = redet viel.',
            why: '`poco` wäre „wenig“, `bajo` wäre „klein“.',
            avoid: 'muy + Eigenschaft, Verb + mucho.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Anpassen und Ausnahmen',
      exercises: [
        {
          id: 'es.g.muy-mucho.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 2,
          sentence: 'Hay ___ gente y hace ___ calor.',
          german: 'Es sind viele Leute da und es ist sehr heiß.',
          answers: [['mucha'], ['mucho']],
          bank: ['muy', 'mucho', 'mucha', 'muchos'],
          feedback: {
            rule: '`gente` (f. Sg.) → `mucha`; `calor` (m. Nomen) → `mucho`.',
            why: '`muy calor` ist falsch, weil `calor` ein Nomen ist.',
            avoid: 'Nomen? → mucho/mucha, passend zum Genus.',
          },
        },
        {
          id: 'es.g.muy-mucho.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 2,
          sentence: 'Estoy ___ cansada porque trabajo ___.',
          german: 'Ich bin sehr müde, weil ich viel arbeite.',
          answers: [['muy'], ['mucho']],
          bank: ['muy', 'mucho', 'mucha'],
          feedback: {
            rule: 'Adjektiv `cansada` → `muy`; nach dem Verb `trabajo` → `mucho`.',
            why: '`mucha cansada` ist falsch – `cansada` ist kein Nomen.',
            avoid: 'Schau, was direkt folgt oder davor steht.',
          },
        },
        {
          id: 'es.g.muy-mucho.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho', 'es.g.tener'],
          difficulty: 2,
          sentence: 'Tengo muy hambre.',
          german: 'Ich habe großen Hunger.',
          answers: ['Tengo mucha hambre.'],
          feedback: {
            rule: '`hambre` ist ein weibliches Nomen → `mucha hambre`.',
            why: 'Im Deutschen sagt man „sehr hungrig“ – im Spanischen hat man „viel Hunger“.',
            avoid: 'tener + Nomen → mucho/mucha.',
          },
        },
        {
          id: 'es.g.muy-mucho.L2.04',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 2,
          prompt: '„Das ist viel besser.“',
          options: [
            { text: 'Es mucho mejor.', why: 'Richtig: vor `mejor` → `mucho`.' },
            { text: 'Es muy mejor.', why: 'Vor Vergleichswörtern steht nie `muy`.' },
            { text: 'Es muy bueno.', why: 'Das heißt „Das ist sehr gut“ – kein Vergleich.' },
          ],
          answer: 0,
          feedback: {
            rule: '`mucho mejor / peor / más / menos`.',
            why: '`mejor` ist schon ein Vergleich – man sagt „viel besser“, nicht „sehr besser“.',
            avoid: 'Wie im Deutschen: viel besser → mucho mejor.',
          },
        },
        {
          id: 'es.g.muy-mucho.L2.05',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 2,
          sentence: 'Hay muchos personas en el bar.',
          german: 'In der Bar sind viele Leute.',
          answers: ['Hay muchas personas en el bar.'],
          feedback: {
            rule: '`personas` ist weiblich Plural → `muchas`.',
            why: '`mucho` passt sich wie ein Adjektiv an das Nomen an.',
            avoid: 'la persona → muchas personas.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Menschen und Dinge beschreiben',
      exercises: [
        {
          id: 'es.g.muy-mucho.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Vielen Dank, du bist sehr nett.',
          answers: [
            'Muchas gracias, eres muy amable.',
            'Muchas gracias, eres muy simpático.',
            'Muchas gracias, eres muy simpática.',
            'Muchas gracias, tú eres muy amable.',
            'Muchas gracias, tú eres muy simpático.',
            'Muchas gracias, tú eres muy simpática.',
          ],
          feedback: {
            rule: '`muchas gracias` (Nomen, f. Pl.) und `muy amable` (Adjektiv).',
            why: '„Muy gracias“ ist falsch, weil `gracias` ein Nomen ist.',
            avoid: 'Ein Satz, beide Wörter: mucho vor Nomen, muy vor Adjektiv.',
          },
        },
        {
          id: 'es.g.muy-mucho.L3.02',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Ich arbeite viel.',
          answers: ['Trabajo mucho.', 'Yo trabajo mucho.'],
          feedback: {
            rule: 'Nach dem Verb → `mucho` (unveränderlich).',
            why: '„Trabajo muy“ ist unvollständig: `muy` braucht ein Adjektiv.',
            avoid: 'Verb + mucho.',
          },
        },
        {
          id: 'es.g.muy-mucho.L3.03',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 3,
          tokens: ['Mi', 'hermano', 'es', 'muy', 'alto', 'y', 'come', 'mucho', '.'],
          alternatives: [['Mi', 'hermano', 'come', 'mucho', 'y', 'es', 'muy', 'alto', '.']],
          german: 'Mein Bruder ist sehr groß und isst viel.',
          feedback: {
            rule: '`muy` vor dem Adjektiv (`muy alto`), `mucho` nach dem Verb (`come mucho`).',
            why: '„come muy“ oder „mucho alto“ vertauschen die beiden Wörter.',
            avoid: 'muy klebt am Adjektiv, mucho am Verb.',
          },
        },
        {
          id: 'es.g.muy-mucho.L3.04',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.muy-mucho', 'es.g.gustar'],
          difficulty: 3,
          scenario: 'Eine Freundin fragt: „¿Te gusta la comida mexicana?“ Du magst sie sehr.',
          options: [
            { text: '¡Sí, mucho!', why: 'Richtig: allein stehend → `mucho`.' },
            { text: '¡Sí, muy!', why: '`muy` kann nicht allein stehen.' },
            { text: '¡Sí, muy mucho!', why: '`muy mucho` gibt es nicht.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Kurzantwort: `Sí, mucho.` (oder `Sí, muchísimo.`).',
            why: '„Ja, sehr!“ verleitet zu `muy`.',
            avoid: 'Ohne Adjektiv danach → mucho.',
          },
        },
        {
          id: 'es.g.muy-mucho.L3.05',
          type: 'freeText',
          skills: ['writing', 'grammar'],
          topicIds: ['es.g.muy-mucho'],
          difficulty: 3,
          prompt: 'Beschreibe eine Person, die du gut kennst, in zwei bis drei Sätzen – mit `muy` und mit `mucho`.',
          requirements: [
            { pattern: '\\bmuy\\b', hint: '`muy` vor einem Adjektiv' },
            { pattern: '\\bmuch[oa]s?\\b', hint: 'eine Form von `mucho` (mucho, mucha, muchos, muchas)' },
          ],
          samples: ['Mi amiga Laura es muy simpática. Trabaja mucho y tiene muchos libros.'],
          minWords: 8,
          feedback: {
            rule: '`muy` + Adjektiv, `mucho` + Nomen oder nach dem Verb.',
            why: 'Typisch sind `mucho simpática` oder `me gusta muy`.',
            avoid: 'Lies jeden Satz noch einmal: Was folgt auf muy/mucho?',
          },
        },
      ],
    },
  ],
  related: ['es.g.adjectives', 'es.g.tener', 'es.g.weather'],
};
