import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.numbers',
  courseId: 'es',
  stageId: 'stage0',
  order: 13,
  category: 'Zahlen & Mengen',
  title: 'Zahlen von 0 bis 100',
  summary: 'Die Zahlen bis 100, ihre Schreibung mit und ohne „y“ – und warum aus uno manchmal un oder una wird.',
  keywords: [
    'Zahlen', 'números', 'zählen', 'Grundzahlen', 'cero', 'uno', 'quince', 'dieciséis', 'veinte', 'veintiuno', 'treinta y uno',
    'cien', 'ciento', 'Preis', 'Alter', 'un una', 'sesenta', 'setenta', 'Euro', 'Peso',
  ],
  explanation: [
    {
      type: 'table',
      title: '0 bis 15 – auswendig lernen',
      headers: ['0–5', '6–10', '11–15'],
      rows: [
        ['0 cero', '6 seis', '11 once'],
        ['1 uno', '7 siete', '12 doce'],
        ['2 dos', '8 ocho', '13 trece'],
        ['3 tres', '9 nueve', '14 catorce'],
        ['4 cuatro', '10 diez', '15 quince'],
        ['5 cinco', '', ''],
      ],
    },
    {
      type: 'table',
      title: '16 bis 29 – ein Wort',
      headers: ['16–19', '20–24', '25–29'],
      rows: [
        ['16 dieciséis', '20 veinte', '25 veinticinco'],
        ['17 diecisiete', '21 veintiuno', '26 veintiséis'],
        ['18 dieciocho', '22 veintidós', '27 veintisiete'],
        ['19 diecinueve', '23 veintitrés', '28 veintiocho'],
        ['', '24 veinticuatro', '29 veintinueve'],
      ],
    },
    {
      type: 'table',
      title: 'Die Zehner – ab 31 mit „y“',
      headers: ['Zehner', 'Beispiel'],
      rows: [
        ['30 treinta', '31 treinta y uno'],
        ['40 cuarenta', '45 cuarenta y cinco'],
        ['50 cincuenta', '58 cincuenta y ocho'],
        ['60 sesenta', '66 sesenta y seis'],
        ['70 setenta', '77 setenta y siete'],
        ['80 ochenta', '82 ochenta y dos'],
        ['90 noventa', '99 noventa y nueve'],
        ['100 cien', '101 ciento uno'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Mi', role: 'pronoun' },
        { text: ' abuela', role: 'subject' },
        { text: ' tiene', role: 'verb' },
        { text: ' noventa y dos', role: 'other' },
        { text: ' años', role: 'noun' },
        { text: '.' },
      ],
      german: 'Meine Großmutter ist 92 Jahre alt. – Zehner zuerst, dann „y“, dann Einer.',
    },
    {
      type: 'text',
      md: '**uno passt sich an** – wie ein Artikel: vor männlichen Nomen `un`, vor weiblichen `una`. Das gilt auch in zusammengesetzten Zahlen: `un libro`, `veintiún libros`, `treinta y un años` – aber `una casa`, `veintiuna personas`, `treinta y una sillas`.',
    },
    {
      type: 'text',
      md: '**100** heißt allein oder vor einem Nomen `cien`: `cien personas`. Ab 101 wird daraus `ciento`: `ciento uno`, `ciento veinte`.',
    },
    {
      type: 'mistake',
      wrong: 'veinte y dos',
      right: 'veintidós',
      why: 'Von 16 bis 29 schreibt man die Zahlen **zusammen**. Erst ab 31 kommt „y“ als eigenes Wort: `treinta y dos`.',
    },
    {
      type: 'tip',
      md: '**sesenta** (60) hat ein **s** wie **s**eis, **setenta** (70) ein **t** wie sie**t**e. Und: bis 29 ein Wort, ab 31 drei Wörter.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien zahlt in Euro: `Son tres euros con cincuenta` (3,50 €). Dezimalzeichen ist wie im Deutschen das Komma. „Hundert Prozent“ heißt meist `cien por cien`.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Mexiko, Argentinien, Chile oder Kolumbien zahlt man in Pesos, das Zeichen `$` steht dort für Pesos: `Son cincuenta pesos.` In Mexiko schreibt man Dezimalzahlen mit Punkt (3.50). „Hundert Prozent“ heißt `cien por ciento`.',
    },
    { type: 'audio', text: 'Dieciséis, veintidós, treinta y cinco, sesenta, setenta, cien.', label: 'Zahlen anhören' },
  ],
  examples: [
    { target: 'Tengo treinta y dos años.', german: 'Ich bin 32 Jahre alt.', note: 'Alter mit `tener` („haben“).' },
    { target: 'la habitación dieciséis', german: 'Zimmer 16' },
    { target: 'veintiún libros', german: '21 Bücher', note: 'Vor männlichem Nomen: `veintiún` (mit Akzent).' },
    { target: 'treinta y una personas', german: '31 Personen', note: 'Vor weiblichem Nomen: `una`.' },
    { target: 'Hay cien personas en la sala.', german: 'Im Saal sind hundert Personen.' },
    { target: 'Son cuarenta y cinco euros.', german: 'Das macht 45 Euro.', variant: 'es-ES' },
    { target: 'Son cuarenta y cinco pesos.', german: 'Das macht 45 Pesos.', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'veintidós',
      german: 'zweiundzwanzig',
      md: 'Deutsch nennt zuerst die Einer, Spanisch zuerst die Zehner – genau in der Reihenfolge, in der man die Ziffern schreibt: 2-2 → „zwanzig-zwei“.',
    },
    {
      type: 'compare',
      target: 'setenta y ocho',
      german: 'achtundsiebzig',
      md: '`y` = „und“, aber an anderer Stelle: „siebzig und acht“.',
    },
    {
      type: 'compare',
      target: 'un libro · una casa',
      german: 'ein Buch · ein Haus',
      md: '„eins/ein“ passt sich auch im Deutschen an – im Spanischen zusätzlich in zusammengesetzten Zahlen (`veintiuna casas`).',
    },
    {
      type: 'text',
      md: 'Beim Hören hilft ein Trick: Schreibe die Zahl während des Hörens gleich von links nach rechts mit – das Spanische diktiert dir die Ziffern in Schreibreihenfolge.',
    },
  ],
  mistakes: [
    { wrong: 'veinte y dos', right: 'veintidós', why: '16–29 werden zusammengeschrieben.' },
    { wrong: 'treintiuno', right: 'treinta y uno', why: 'Ab 31 schreibt man drei Wörter – das Muster `veinti-` gilt nur für die Zwanziger.' },
    { wrong: 'uno libro', right: 'un libro', why: 'Vor einem männlichen Nomen wird `uno` zu `un`.' },
    { wrong: 'ciento personas', right: 'cien personas', why: 'Genau 100 heißt `cien`; `ciento` nur in 101–199.' },
    { wrong: 'sesenta (für 70)', right: 'setenta', why: '60 = sesenta (s wie seis), 70 = setenta (t wie siete).' },
  ],
  mnemonic: '**Bis 29 ein Wort, ab 31 mit „y“ – und immer Zehner vor Einer.**',
  levels: [
    {
      level: 1,
      title: 'Zahlen erkennen',
      exercises: [
        {
          id: 'es.g.numbers.L1.01',
          type: 'matchPairs',
          skills: ['vocabulary', 'listening'],
          topicIds: ['es.g.numbers'],
          difficulty: 1,
          instruction: 'Ordne Ziffer und Zahlwort zu.',
          pairs: [
            { left: '7', right: 'siete' },
            { left: '11', right: 'once' },
            { left: '15', right: 'quince' },
            { left: '20', right: 'veinte' },
            { left: '50', right: 'cincuenta' },
          ],
          feedback: {
            rule: '7 siete, 11 once, 15 quince, 20 veinte, 50 cincuenta.',
            why: '`once` (11) sieht aus wie das englische „once“, ist aber eine Zahl.',
            avoid: 'Lerne 0–15 in Dreiergruppen laut: „cero, uno, dos – tres, cuatro, cinco …“.',
          },
        },
        {
          id: 'es.g.numbers.L1.02',
          type: 'mc',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.numbers'],
          difficulty: 1,
          prompt: 'Welche Zahl ist `catorce`?',
          options: [
            { text: '4', why: '4 heißt `cuatro`.' },
            { text: '14', why: 'Richtig: `catorce` = 14.' },
            { text: '40', why: '40 heißt `cuarenta`.' },
          ],
          answer: 1,
          feedback: {
            rule: '4 cuatro · 14 catorce · 40 cuarenta.',
            why: 'Alle drei beginnen mit c – leicht zu verwechseln.',
            avoid: '-ce am Ende (once, doce, trece, catorce, quince) = 11–15.',
          },
        },
        {
          id: 'es.g.numbers.L1.03',
          type: 'listening',
          skills: ['listening', 'vocabulary'],
          topicIds: ['es.g.numbers'],
          difficulty: 1,
          audio: 'dieciséis',
          question: 'Welche Zahl hörst du?',
          options: ['6', '16', '60', '66'],
          answer: 1,
          feedback: {
            rule: '`dieciséis` = diez y seis = 16.',
            why: '6 wäre `seis`, 60 `sesenta`.',
            avoid: '`dieci-` am Anfang = 10 + …',
          },
        },
        {
          id: 'es.g.numbers.L1.04',
          type: 'listening',
          skills: ['listening', 'vocabulary'],
          topicIds: ['es.g.numbers'],
          difficulty: 1,
          audio: 'setenta',
          question: 'Welche Zahl hörst du?',
          options: ['60', '70', '17', '7'],
          answer: 1,
          feedback: {
            rule: '`setenta` = 70 (t wie siete); `sesenta` = 60 (s wie seis).',
            why: 'Die beiden Zehner klingen sehr ähnlich.',
            avoid: 'Achte auf den Konsonanten in der Mitte: -s- oder -t-.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Zahlen schreiben',
      exercises: [
        {
          id: 'es.g.numbers.L2.01',
          type: 'mc',
          skills: ['vocabulary', 'writing'],
          topicIds: ['es.g.numbers'],
          difficulty: 2,
          prompt: 'Wie schreibt man 23?',
          options: [
            { text: 'veintitrés', why: 'Richtig: ein Wort, mit Akzent auf dem e.' },
            { text: 'veinte y tres', why: '16–29 schreibt man zusammen.' },
            { text: 'treinta y dos', why: 'Das ist 32 – Zehner und Einer vertauscht.' },
          ],
          answer: 0,
          feedback: {
            rule: '21–29: `veinti` + Einer in einem Wort (veintidós, veintitrés, veintiséis mit Akzent).',
            why: 'Deutsche denken „drei-und-zwanzig“ und vertauschen gern die Ziffern.',
            avoid: 'Zahl so sagen, wie man sie schreibt: 2 → 3 = veinti-trés.',
          },
        },
        {
          id: 'es.g.numbers.L2.02',
          type: 'translate',
          skills: ['vocabulary', 'writing'],
          topicIds: ['es.g.numbers'],
          difficulty: 2,
          direction: 'toTarget',
          instruction: 'Schreib die Zahl als Wort.',
          source: '35',
          answers: ['treinta y cinco'],
          feedback: {
            rule: 'Ab 31: Zehner + `y` + Einer, getrennt geschrieben.',
            why: '„treinticinco“ (Muster der Zwanziger) und „cinco y treinta“ (Einer zuerst) sind falsch.',
            avoid: 'Drei Wörter: treinta – y – cinco.',
          },
        },
        {
          id: 'es.g.numbers.L2.03',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.numbers'],
          difficulty: 2,
          instruction: 'Hör zu und schreib die Zahl als Wort.',
          audio: 'veintidós',
          german: '22',
          answers: ['veintidós'],
          feedback: {
            rule: '22 = `veintidós`: ein Wort, Akzent auf dem o.',
            why: 'Das Wort endet auf -s und wird hinten betont → Akzent nötig.',
            avoid: 'veintidós, veintitrés, veintiséis tragen einen Akzent.',
          },
        },
        {
          id: 'es.g.numbers.L2.04',
          type: 'cloze',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.numbers'],
          difficulty: 2,
          instruction: 'Schreib die Zahl in Klammern als Wort.',
          sentence: 'Mi abuela tiene ___ (90) años.',
          german: 'Meine Großmutter ist 90 Jahre alt.',
          answers: [['noventa']],
          feedback: {
            rule: '90 = `noventa` (nueve → nov-).',
            why: '„nueventa“ gibt es nicht; 19 wäre `diecinueve`.',
            avoid: 'Die Zehner ab 30 enden alle auf -enta.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'un, una und cien',
      exercises: [
        {
          id: 'es.g.numbers.L3.01',
          type: 'cloze',
          skills: ['grammar', 'vocabulary'],
          topicIds: ['es.g.numbers'],
          difficulty: 3,
          instruction: 'Schreib die Zahl in Klammern als Wort.',
          sentence: 'En la clase hay ___ (21) alumnos.',
          german: 'In der Klasse sind 21 Schüler.',
          answers: [['veintiún']],
          feedback: {
            rule: 'Vor männlichem Nomen wird `veintiuno` zu `veintiún` (mit Akzent).',
            why: '„veintiuno alumnos“ ist falsch – `uno` verkürzt sich vor männlichen Nomen.',
            avoid: 'Zahl direkt vor männlichem Nomen: -ún; allein stehend: -uno.',
          },
        },
        {
          id: 'es.g.numbers.L3.02',
          type: 'cloze',
          skills: ['grammar', 'vocabulary'],
          topicIds: ['es.g.numbers'],
          difficulty: 3,
          instruction: 'Schreib die Zahl in Klammern als Wort.',
          sentence: 'Necesitamos ___ (31) sillas.',
          german: 'Wir brauchen 31 Stühle.',
          answers: [['treinta y una']],
          feedback: {
            rule: '`silla` ist weiblich → `treinta y una sillas`.',
            why: '`treinta y uno` passt nur allein stehend oder beim Zählen.',
            avoid: 'Weibliches Nomen → `una`, auch am Ende einer großen Zahl.',
          },
        },
        {
          id: 'es.g.numbers.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.numbers'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'hundert Personen',
          answers: ['cien personas'],
          feedback: {
            rule: 'Genau 100 vor einem Nomen: `cien`.',
            why: '`ciento` verwendet man nur für 101–199 (ciento uno, ciento veinte).',
            avoid: '100 = cien. Punkt.',
          },
        },
        {
          id: 'es.g.numbers.L3.04',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.numbers'],
          difficulty: 3,
          variant: 'es-ES',
          instruction: 'Hör zu und schreib den Satz – Zahlen als Wort.',
          audio: 'Son sesenta y siete euros.',
          german: 'Das macht 67 Euro.',
          answers: ['Son sesenta y siete euros.'],
          feedback: {
            rule: '67 = `sesenta y siete`; Preise: `Son … euros`.',
            why: '`setenta` wäre 70.',
            avoid: 'sesenta = 6-, setenta = 7-.',
          },
        },
        {
          id: 'es.g.numbers.L3.05',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.numbers'],
          difficulty: 3,
          variant: 'es-LA',
          instruction: 'Hör zu und schreib den Satz – Zahlen als Wort.',
          audio: 'Son sesenta y siete pesos.',
          german: 'Das macht 67 Pesos.',
          answers: ['Son sesenta y siete pesos.'],
          feedback: {
            rule: '67 = `sesenta y siete`; Preise: `Son … pesos`.',
            why: '`setenta` wäre 70.',
            avoid: 'sesenta = 6-, setenta = 7-.',
          },
        },
      ],
    },
  ],
  related: ['es.g.hay', 'es.g.gender-plural', 'es.g.tener'],
};
