import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.numbers-big',
  courseId: 'es',
  stageId: 'a1',
  order: 10,
  category: 'Zahlen & Mengen',
  title: 'Zahlen von 100 bis 1000 – und Preise',
  summary: 'cien oder ciento? Die Hunderter mit -os/-as, die Ausreißer quinientos, setecientos, novecientos, das schlichte mil – und wie man nach Preisen fragt.',
  keywords: [
    'Zahlen', 'hundert', 'tausend', 'Hunderter', 'cien', 'ciento', 'doscientos', 'doscientas', 'trescientos', 'cuatrocientos',
    'quinientos', 'seiscientos', 'setecientos', 'ochocientos', 'novecientos', 'mil', 'Preis', 'Preise', 'kosten',
    'cuánto cuesta', 'cuánto cuestan', 'cuánto es', 'euro', 'euros', 'peso', 'pesos', 'céntimos', 'Kongruenz',
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Hunderter',
      headers: ['Zahl', 'Spanisch', 'Hinweis'],
      rows: [
        ['100', 'cien', 'genau hundert'],
        ['101, 120, 199', 'ciento uno, ciento veinte, ciento noventa y nueve', 'ab 101: ciento'],
        ['200', 'doscientos / doscientas', 'richtet sich nach dem Nomen'],
        ['300', 'trescientos / -as', ''],
        ['400', 'cuatrocientos / -as', ''],
        ['500', 'quinientos / -as', 'Ausreißer! (nicht „cincocientos“)'],
        ['600', 'seiscientos / -as', ''],
        ['700', 'setecientos / -as', 'Ausreißer! (sete-, nicht „siete-“)'],
        ['800', 'ochocientos / -as', ''],
        ['900', 'novecientos / -as', 'Ausreißer! (nove-, nicht „nueve-“)'],
        ['1000', 'mil', 'ohne „un“'],
      ],
    },
    {
      type: 'text',
      md: '**cien oder ciento?** Genau 100 heißt `cien` – auch vor Nomen: `cien euros`, `cien personas`. Sobald etwas folgt, heißt es `ciento`: `ciento cinco`, `ciento cincuenta`. Zwischen Hunderter und Zehner steht **kein** `y`: `ciento veinte`, `trescientos cuarenta`. Das `y` kommt nur zwischen Zehner und Einer: `ciento treinta y cinco`.',
    },
    {
      type: 'text',
      md: 'Die Hunderter von 200 bis 900 **passen sich an** wie Adjektive: `doscientos euros`, aber `doscientas personas`. `ciento` und `mil` bleiben immer gleich. Bei `uno` gilt die bekannte Regel: `ciento un euros`, `ciento una personas`.',
    },
    {
      type: 'colored',
      parts: [
        { text: '¿Cuánto', role: 'question' },
        { text: ' cuestan', role: 'verb' },
        { text: ' las entradas', role: 'subject' },
        { text: '? – ' },
        { text: 'Cuestan', role: 'verb' },
        { text: ' doscientos cincuenta', role: 'adjective' },
        { text: ' pesos', role: 'noun' },
        { text: '.' },
      ],
      german: 'Was kosten die Eintrittskarten? – Sie kosten 250 Pesos.',
    },
    {
      type: 'table',
      title: 'Nach dem Preis fragen',
      headers: ['Frage', 'Antwort', 'Deutsch'],
      rows: [
        ['¿Cuánto cuesta el libro?', 'Cuesta quince euros.', 'Was kostet das Buch? – 15 Euro.'],
        ['¿Cuánto cuestan los tomates?', 'Cuestan dos euros el kilo.', 'Was kosten die Tomaten? – 2 Euro das Kilo.'],
        ['¿Cuánto es (todo)?', 'Son ciento veinte euros.', 'Was macht das (zusammen)? – 120 Euro.'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Cuesta ciento euros.',
      right: 'Cuesta cien euros.',
      why: 'Allein stehend bzw. direkt vor dem Nomen heißt 100 `cien`. `ciento` nur, wenn noch eine Zahl folgt (`ciento diez`).',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: Preise in **euros** mit **céntimos**: `2,50 €` = `dos euros con cincuenta (céntimos)` oder kurz `dos cincuenta`. Dezimalzeichen wie im Deutschen: Komma.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: In Mexiko, Argentinien, Kolumbien oder Chile zahlt man in **pesos** (Zeichen `$`): `$250` = `doscientos cincuenta pesos`. In Mexiko schreibt man Zahlen wie im Englischen (`1,000.50`), in Argentinien wie im Deutschen (`1.000,50`).',
    },
    { type: 'tip', md: '**Genau hundert = cien.** Ab 101 `ciento …`, und **5 – 7 – 9 tanzen aus der Reihe:** quinientos, setecientos, novecientos.' },
    { type: 'audio', text: 'cien, ciento uno, doscientos, trescientos, cuatrocientos, quinientos, seiscientos, setecientos, ochocientos, novecientos, mil', label: 'Hunderter anhören' },
  ],
  examples: [
    { target: 'La bicicleta cuesta cuatrocientos cincuenta euros.', german: 'Das Fahrrad kostet 450 Euro.' },
    { target: '—¿Cuánto cuestan las naranjas? —Dos euros el kilo.', german: '„Was kosten die Orangen?“ – „Zwei Euro das Kilo.“' },
    {
      target: 'En el hotel hay trescientas habitaciones.',
      german: 'Im Hotel gibt es dreihundert Zimmer.',
      parts: [
        { text: 'En el hotel', role: 'preposition' },
        { text: ' hay', role: 'verb' },
        { text: ' trescientas', role: 'adjective' },
        { text: ' habitaciones', role: 'noun' },
        { text: '.' },
      ],
    },
    { target: '—¿Cuánto es todo? —Son ciento veinte euros.', german: '„Was macht das zusammen?“ – „120 Euro.“' },
    { target: 'Mi casa está a setecientos metros de la playa.', german: 'Mein Haus ist 700 Meter vom Strand entfernt.' },
    { target: 'Hay cien personas en la sala.', german: 'Im Saal sind hundert Leute.' },
    { target: '¡Mil gracias!', german: 'Tausend Dank!' },
    { target: 'Son quinientos pesos.', german: 'Das macht 500 Pesos.', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'doscientas personas',
      german: 'zweihundert Personen',
      md: 'Im Deutschen ist die Zahl unveränderlich. Im Spanischen passen sich die Hunderter an: `doscientas` vor weiblichen Nomen.',
    },
    {
      type: 'compare',
      target: 'mil euros',
      german: '(ein)tausend Euro',
      md: 'Kein `un` vor `mil`. Und das Nomen steht im Plural: `euros` – im Deutschen sagt man „Euro“ ohne Endung.',
    },
    {
      type: 'compare',
      target: 'ciento veinte',
      german: 'hundertzwanzig',
      md: 'Spanisch schreibt getrennt und ohne `y` nach dem Hunderter. Die Reihenfolge ist aber wie im Deutschen: erst die Hunderter.',
    },
    {
      type: 'compare',
      target: 'trescientos cuarenta y cinco',
      german: 'dreihundertfünfundvierzig',
      md: 'Nach dem Hunderter kommt die Zahl bis 99 genau so, wie du sie schon kennst – Zehner vor Einer, anders als im Deutschen.',
    },
  ],
  mistakes: [
    { wrong: 'ciento euros', right: 'cien euros', why: 'Genau 100 = `cien`.' },
    { wrong: 'cincocientos', right: 'quinientos', why: '500 ist unregelmäßig: `quinientos`.' },
    { wrong: 'un mil', right: 'mil', why: 'Vor `mil` steht kein `un`.' },
    { wrong: 'doscientos personas', right: 'doscientas personas', why: 'Hunderter passen sich an das weibliche Nomen an.' },
    { wrong: 'ciento y veinte', right: 'ciento veinte', why: '`y` steht nur zwischen Zehner und Einer.' },
  ],
  mnemonic: '**Genau hundert = cien. 5 – 7 – 9 tanzen aus der Reihe: quinientos, setecientos, novecientos. Tausend = mil, ganz ohne un.**',
  levels: [
    {
      level: 1,
      title: 'Hunderter erkennen',
      exercises: [
        {
          id: 'es.g.numbers-big.L1.01',
          type: 'matchPairs',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 1,
          instruction: 'Ordne Zahl und Wort zu.',
          pairs: [
            { left: '100', right: 'cien' },
            { left: '200', right: 'doscientos' },
            { left: '500', right: 'quinientos' },
            { left: '700', right: 'setecientos' },
            { left: '900', right: 'novecientos' },
            { left: '1000', right: 'mil' },
          ],
          feedback: {
            rule: 'Die Ausreißer: 500 `quinientos`, 700 `setecientos`, 900 `novecientos`.',
            why: 'Nach dem Muster „Zahl + cientos“ würde man cinco-, siete-, nueve- erwarten.',
            avoid: '5 – 7 – 9 tanzen aus der Reihe.',
          },
        },
        {
          id: 'es.g.numbers-big.L1.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 1,
          prompt: 'Wie schreibt man 150?',
          options: [
            { text: 'ciento cincuenta', why: 'Richtig: ab 101 `ciento`, ohne `y`.' },
            { text: 'cien cincuenta', why: '`cien` steht nur für genau 100.' },
            { text: 'ciento y cincuenta', why: 'Nach dem Hunderter steht kein `y`.' },
          ],
          answer: 0,
          feedback: {
            rule: '101–199: `ciento` + Rest, ohne `y`.',
            why: '`cien` ist die Kurzform für genau hundert.',
            avoid: 'Folgt noch etwas? → ciento.',
          },
        },
        {
          id: 'es.g.numbers-big.L1.03',
          type: 'listening',
          skills: ['listening', 'vocabulary'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 1,
          audio: 'Son trescientos cuarenta euros.',
          question: 'Wie viel kostet es?',
          options: ['340 €', '430 €', '314 €'],
          answer: 0,
          feedback: {
            rule: '`trescientos` = 300, `cuarenta` = 40.',
            why: '430 wäre `cuatrocientos treinta`, 314 `trescientos catorce`.',
            avoid: 'Hör zuerst auf den Hunderter, dann auf den Rest.',
          },
        },
        {
          id: 'es.g.numbers-big.L1.04',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 1,
          prompt: '„hundert Euro“',
          options: [
            { text: 'cien euros', why: 'Richtig: genau hundert = `cien`.' },
            { text: 'ciento euros', why: '`ciento` braucht eine weitere Zahl danach.' },
            { text: 'un cien euros', why: 'Vor `cien` steht kein `un`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Genau 100 = `cien`, ohne `un`.',
            why: 'Im Deutschen sagt man manchmal „einhundert“ – im Spanischen nie „un cien“.',
            avoid: 'cien euros, cien personas, cien años.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Anpassen und schreiben',
      exercises: [
        {
          id: 'es.g.numbers-big.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 2,
          sentence: 'En el hotel hay ___ habitaciones.',
          german: 'Im Hotel gibt es zweihundert Zimmer.',
          answers: [['doscientas']],
          bank: ['doscientos', 'doscientas', 'dos cientos'],
          feedback: {
            rule: '`habitación` ist weiblich → `doscientas habitaciones`.',
            why: '`doscientos` passt zu männlichen Nomen; getrennt schreibt man es nie.',
            avoid: 'Hunderter verhalten sich wie Adjektive: -os/-as.',
          },
        },
        {
          id: 'es.g.numbers-big.L2.02',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 2,
          audio: 'Cuesta quinientos euros.',
          german: 'Es kostet 500 Euro.',
          answers: ['Cuesta quinientos euros.', 'Cuesta 500 euros.'],
          feedback: {
            rule: '500 = `quinientos` (unregelmäßig).',
            why: '„cincocientos“ gibt es nicht.',
            avoid: 'quin- wie „Quinte“ (die Fünf in der Musik).',
          },
        },
        {
          id: 'es.g.numbers-big.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 2,
          sentence: 'La bicicleta cuesta cincocientos euros.',
          german: 'Das Fahrrad kostet 500 Euro.',
          answers: ['La bicicleta cuesta quinientos euros.'],
          feedback: {
            rule: '500 = `quinientos`.',
            why: 'Die regelmäßige Bildung „cinco + cientos“ ist hier falsch.',
            avoid: 'Merke die drei Ausreißer als Gruppe: quinientos, setecientos, novecientos.',
          },
        },
        {
          id: 'es.g.numbers-big.L2.04',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.numbers-big', 'es.g.stem-change'],
          difficulty: 2,
          verb: 'costar',
          tense: 'Präsens',
          person: 'ellos',
          sentence: '¿Cuánto ___ los zapatos?',
          answers: ['cuestan'],
          feedback: {
            rule: 'Mehrere Dinge → `cuestan` (costar, o → ue).',
            why: '`cuesta` passt nur zu einem Ding, `costan` ignoriert den Stammwechsel.',
            avoid: 'Schau auf das Nomen: Plural → cuestan.',
          },
        },
        {
          id: 'es.g.numbers-big.L2.05',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 2,
          prompt: 'Wie schreibt man 900?',
          options: [
            { text: 'novecientos', why: 'Richtig: nove- statt nueve-.' },
            { text: 'nuevecientos', why: 'Ausreißer: Aus nueve wird nove-.' },
            { text: 'nuevientos', why: 'Diese Form gibt es nicht.' },
          ],
          answer: 0,
          feedback: {
            rule: '900 = `novecientos`.',
            why: 'Wie bei 700 (siete → `setecientos`) verschwindet der Doppellaut: nueve → nove-.',
            avoid: 'sete- und nove- – beide ohne ie/ue.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Preise im Alltag',
      exercises: [
        {
          id: 'es.g.numbers-big.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Was kostet das Fahrrad?',
          answers: ['¿Cuánto cuesta la bicicleta?', '¿Cuánto cuesta la bici?', '¿Cuánto vale la bicicleta?', '¿Cuánto vale la bici?'],
          feedback: {
            rule: 'Preisfrage: `¿Cuánto cuesta` + Singular?',
            why: '„¿Qué cuesta …?“ ist eine Lehnübersetzung von „Was kostet …?“.',
            avoid: '„Was kostet“ = „Wie viel kostet“ → `¿Cuánto cuesta?`',
          },
        },
        {
          id: 'es.g.numbers-big.L3.02',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 3,
          audio: 'En el pueblo viven ochocientas personas.',
          german: 'Im Dorf leben 800 Menschen.',
          answers: ['En el pueblo viven ochocientas personas.', 'En el pueblo viven 800 personas.'],
          feedback: {
            rule: '`personas` ist weiblich → `ochocientas`.',
            why: 'Das -as am Ende des Hunderters hört man deutlich.',
            avoid: 'Achte beim Hören auf die Endung des Hunderters.',
          },
        },
        {
          id: 'es.g.numbers-big.L3.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 3,
          sentence: 'El alquiler cuesta ___ euros al mes.',
          german: 'Die Miete kostet tausend Euro im Monat.',
          answers: [['mil']],
          bank: ['un mil', 'mil', 'miles'],
          feedback: {
            rule: '1000 = `mil` – ohne `un`.',
            why: '`miles` heißt „Tausende“.',
            avoid: 'mil, dos mil, tres mil … – nie „un mil“.',
          },
        },
        {
          id: 'es.g.numbers-big.L3.04',
          type: 'listening',
          skills: ['listening', 'vocabulary'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 3,
          audio: 'Son novecientos noventa pesos.',
          question: 'Welcher Betrag ist gemeint?',
          options: ['990', '909', '199'],
          answer: 0,
          feedback: {
            rule: '`novecientos` = 900, `noventa` = 90.',
            why: '909 wäre `novecientos nueve`, 199 `ciento noventa y nueve`.',
            avoid: 'nove**cientos** (Hunderter) vs. nov**enta** (Zehner) – auf die Endung hören.',
          },
        },
        {
          id: 'es.g.numbers-big.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'vocabulary'],
          topicIds: ['es.g.numbers-big'],
          difficulty: 3,
          prompt: 'Du verkaufst auf dem Flohmarkt drei Dinge. Nenne ihre Preise – alle über 100 (Euro oder Pesos).',
          keywords: ['cien', 'ciento', 'doscientos', 'trescientos', 'cuatrocientos', 'quinientos', 'seiscientos', 'setecientos', 'ochocientos', 'novecientos', 'mil'],
          minMatch: 2,
          sample: 'La bicicleta cuesta ciento cincuenta euros. El sofá cuesta trescientos euros y la mesa doscientos.',
          feedback: {
            rule: 'Hunderter: cien, ciento …, doscientos … novecientos, mil.',
            why: 'Häufig: `ciento` für genau 100 oder `cincocientos`.',
            avoid: 'Überleg vorher: Welche Hunderter brauchst du?',
          },
        },
      ],
    },
  ],
  related: ['es.g.numbers', 'es.g.stem-change', 'es.g.gender-plural'],
};
