import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.polite-requests',
  courseId: 'es',
  stageId: 'a1',
  order: 16,
  category: 'Kommunikation & Anrede',
  title: 'Höflich bitten – ¿Puedes…?, ¿Me pasas…?, Quisiera…',
  summary: 'Wie du auf Spanisch freundlich um etwas bittest: mit poder als Frage, mit einer einfachen Präsensfrage (¿Me pasas la sal?), mit quisiera – und was du auf „gracias“ antwortest.',
  keywords: [
    'höflich', 'Höflichkeit', 'bitten', 'Bitte', 'bitte', 'danke', 'por favor', 'gracias', 'de nada', 'puedes', 'puede', 'me pasas',
    'me das', 'me trae', 'me pone', 'quisiera', 'me gustaría', 'podría', 'aquí tiene', 'perdón', 'Restaurant', 'bestellen',
    'Kellner', 'Anfrage', 'Konjunktiv', 'hätte gern',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Im Spanischen gibt es mehrere Wege, freundlich um etwas zu bitten. Allen gemeinsam: Ein freundlicher Ton und `por favor` machen viel aus. Die wichtigsten Muster:',
    },
    {
      type: 'table',
      title: 'Von locker bis sehr höflich',
      headers: ['Muster', 'Beispiel', 'Deutsch'],
      rows: [
        ['¿Me + Verb (tú)? – unter Freunden', '¿Me pasas la sal?', 'Gibst du mir (mal) das Salz?'],
        ['¿Puedes + Infinitiv? (tú)', '¿Puedes cerrar la ventana, por favor?', 'Kannst du bitte das Fenster zumachen?'],
        ['¿Puede + Infinitiv? (usted)', '¿Puede repetir, por favor?', 'Können Sie das bitte wiederholen?'],
        ['¿Me trae / me da …? (usted)', '¿Me trae la cuenta, por favor?', 'Bringen Sie mir bitte die Rechnung?'],
        ['Quisiera + Nomen/Infinitiv', 'Quisiera una habitación doble.', 'Ich hätte gern ein Doppelzimmer.'],
        ['Me gustaría + Infinitiv', 'Me gustaría reservar una mesa.', 'Ich würde gern einen Tisch reservieren.'],
        ['¿Podría + Infinitiv? (sehr höflich)', '¿Podría ayudarme?', 'Könnten Sie mir helfen?'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: '¿' },
        { text: 'Me', role: 'pronoun' },
        { text: ' pasas', role: 'verb' },
        { text: ' el pan', role: 'object' },
        { text: ', por favor', role: 'other' },
        { text: '?' },
      ],
      german: 'Gibst du mir bitte das Brot?',
    },
    {
      type: 'text',
      md: '`quisiera` und `podría` sind besonders höfliche Formen – ähnlich wie „ich hätte gern“ und „könnten Sie“. Du brauchst sie nicht zu konjugieren: Lerne sie als **feste Wendungen**. Nach `poder`, `quisiera` und `me gustaría` folgt direkt der Infinitiv – **ohne** `a` oder `de`.',
    },
    {
      type: 'table',
      title: 'Danke und bitte',
      headers: ['Situation', 'Spanisch', 'Deutsch'],
      rows: [
        ['du bittest um etwas', 'por favor', 'bitte'],
        ['du bedankst dich', 'gracias · muchas gracias', 'danke · vielen Dank'],
        ['jemand bedankt sich bei dir', 'de nada · no hay de qué', 'bitte · gern geschehen'],
        ['du reichst etwas', 'aquí tiene (usted) · aquí tienes / toma (tú)', 'bitte schön · hier, bitte'],
        ['du hast nicht verstanden', '¿Perdón? · ¿Cómo?', 'Bitte? · Wie bitte?'],
      ],
    },
    {
      type: 'mistake',
      wrong: '—Muchas gracias. —Por favor.',
      right: '—Muchas gracias. —De nada.',
      why: 'Das deutsche „Bitte“ als Antwort auf „Danke“ heißt `de nada`. `por favor` benutzt man nur, wenn man selbst um etwas bittet.',
    },
    {
      type: 'mistake',
      wrong: '¿Puedo tener un café?',
      right: '¿Me pone un café? / ¿Me da un café? / Quisiera un café.',
      why: '„Kann ich … haben?“ wörtlich übersetzt klingt auf Spanisch unnatürlich. Man fragt, ob einem jemand etwas **gibt** oder sagt, was man gern **hätte**.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien bestellt man an der Bar oft ganz kurz: `¿Me pone un café, por favor?` oder sogar nur `Un café, por favor.` – das ist nicht unhöflich. `Quería…` („ich wollte“) ist beim Bestellen ebenfalls sehr üblich.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika sind Höflichkeitsformeln häufiger und wärmer: `¿Me da un café, por favor?`, in Kolumbien auch `¿Me regala un café?` (hier heißt `regalar` nicht „schenken“, sondern einfach „geben“). Auf „gracias“ antwortet man oft `con gusto` oder `a la orden`.',
    },
    { type: 'tip', md: '**Bitten = Frage + por favor.** Auf „gracias“ → `de nada`. Und `quisiera` ist dein spanisches „Ich hätte gern“.' },
    { type: 'audio', text: 'Perdone, ¿me trae la cuenta, por favor? Muchas gracias. – De nada.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: '¿Puedes cerrar la ventana, por favor?',
      german: 'Kannst du bitte das Fenster zumachen?',
      parts: [
        { text: '¿' },
        { text: 'Puedes', role: 'verb' },
        { text: ' cerrar', role: 'verb' },
        { text: ' la ventana', role: 'object' },
        { text: ', por favor' },
        { text: '?' },
      ],
    },
    { target: '¿Me pasas el agua?', german: 'Gibst du mir das Wasser?' },
    { target: '¿Puede repetir, por favor? Hablo poco español.', german: 'Können Sie das bitte wiederholen? Ich spreche wenig Spanisch.' },
    {
      target: 'Quisiera una habitación doble para dos noches.',
      german: 'Ich hätte gern ein Doppelzimmer für zwei Nächte.',
      parts: [
        { text: 'Quisiera', role: 'verb' },
        { text: ' una habitación doble', role: 'object' },
        { text: ' para dos noches', role: 'preposition' },
        { text: '.' },
      ],
    },
    { target: '¿Me trae la cuenta, por favor?', german: 'Bringen Sie mir bitte die Rechnung?' },
    { target: '—Muchas gracias. —De nada.', german: '„Vielen Dank.“ – „Bitte, gern geschehen.“' },
    { target: '¿Me pone una caña, por favor?', german: 'Ein kleines Bier vom Fass, bitte.', variant: 'es-ES' },
    { target: '—Gracias. —Con gusto.', german: '„Danke.“ – „Gern geschehen.“', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'por favor · de nada · ¿perdón?',
      german: 'bitte · bitte · bitte?',
      md: 'Das deutsche „bitte“ hat drei Aufgaben – das Spanische drei verschiedene Wörter: um etwas bitten (`por favor`), auf Dank antworten (`de nada`), nachfragen (`¿perdón?`, `¿cómo?`).',
    },
    {
      type: 'compare',
      target: 'Aquí tiene.',
      german: 'Bitte schön. (beim Überreichen)',
      md: 'Wenn du etwas überreichst: `aquí tiene` (usted) oder `aquí tienes` / `toma` (tú) – wörtlich „hier haben Sie/hast du“.',
    },
    {
      type: 'compare',
      target: '¿Me pasas la sal?',
      german: 'Gibst du mir mal das Salz?',
      md: 'Wie im Deutschen reicht unter Freunden eine einfache Frage im Präsens. Das kleine `me` (mir) steht vor dem Verb.',
    },
    {
      type: 'compare',
      target: 'Quisiera una habitación.',
      german: 'Ich hätte gern ein Zimmer.',
      md: '`quisiera` entspricht „ich hätte gern / ich möchte“ – höflicher als `quiero` (ich will).',
    },
  ],
  mistakes: [
    { wrong: '¿Puedes a cerrar la ventana?', right: '¿Puedes cerrar la ventana?', why: 'Nach `poder` folgt der Infinitiv direkt, ohne `a`.' },
    { wrong: '—Gracias. —Por favor.', right: '—Gracias. —De nada.', why: 'Auf Dank antwortet man mit `de nada`.' },
    { wrong: '¿Puedo tener la cuenta?', right: '¿Me trae la cuenta, por favor?', why: '„Kann ich … haben?“ ist eine Lehnübersetzung.' },
    { wrong: '¿Pasas me la sal?', right: '¿Me pasas la sal?', why: '`me` steht vor dem konjugierten Verb.' },
    { wrong: 'Quiero la cuenta. (ohne Gruß, ohne por favor)', right: 'La cuenta, por favor. / ¿Me trae la cuenta?', why: 'Ein nacktes `quiero` klingt fordernd; mit `por favor` oder als Frage wirkt es freundlich.' },
  ],
  mnemonic: '**Bitten = Frage + por favor. Danke → de nada. „Ich hätte gern“ → quisiera.**',
  levels: [
    {
      level: 1,
      title: 'Bitte und danke',
      exercises: [
        {
          id: 'es.g.polite-requests.L1.01',
          type: 'matchPairs',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 1,
          instruction: 'Welches „Bitte“ ist gemeint? Ordne zu.',
          pairs: [
            { left: 'por favor', right: 'bitte (wenn du um etwas bittest)' },
            { left: 'de nada', right: 'bitte (gern geschehen)' },
            { left: '¿Perdón?', right: 'Bitte? (nicht verstanden)' },
            { left: 'aquí tiene', right: 'bitte schön (beim Überreichen)' },
            { left: 'muchas gracias', right: 'vielen Dank' },
          ],
          feedback: {
            rule: 'Ein deutsches „bitte“ – vier spanische Entsprechungen je nach Situation.',
            why: 'Am häufigsten wird `por favor` fälschlich als Antwort auf `gracias` benutzt.',
            avoid: 'Danke → de nada; ich will etwas → por favor.',
          },
        },
        {
          id: 'es.g.polite-requests.L1.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 1,
          prompt: '„Kannst du bitte das Fenster zumachen?“',
          options: [
            { text: '¿Puedes cerrar la ventana, por favor?', why: 'Richtig: `puedes` + Infinitiv.' },
            { text: '¿Puedes a cerrar la ventana, por favor?', why: 'Nach `poder` steht kein `a`.' },
            { text: '¿Puedes cierras la ventana, por favor?', why: 'Nach `puedes` folgt der Infinitiv, keine konjugierte Form.' },
          ],
          answer: 0,
          feedback: {
            rule: '`¿Puedes/Puede` + Infinitiv?',
            why: 'Zwei konjugierte Verben hintereinander gibt es hier nicht.',
            avoid: 'poder + Infinitiv – wie „können“ + Infinitiv im Deutschen.',
          },
        },
        {
          id: 'es.g.polite-requests.L1.03',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.polite-requests', 'es.g.stem-change'],
          difficulty: 1,
          verb: 'poder',
          tense: 'Präsens',
          person: 'usted',
          sentence: '¿___ hablar más despacio, por favor?',
          answers: ['puede'],
          feedback: {
            rule: 'usted → `puede` (o → ue).',
            why: '`puedes` wäre die tú-Form, `pode` gibt es nicht.',
            avoid: 'Höfliche Bitte an Fremde: ¿Puede …?',
          },
        },
        {
          id: 'es.g.polite-requests.L1.04',
          type: 'listening',
          skills: ['listening', 'vocabulary'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 1,
          audio: '¿Me pasas la sal, por favor?',
          question: 'Was möchte die Person?',
          options: ['das Salz', 'die Rechnung', 'den Zucker'],
          answer: 0,
          feedback: {
            rule: '`¿Me pasas …?` = Gibst du mir …?; `la sal` = das Salz.',
            why: 'Die Rechnung wäre `la cuenta`, Zucker `el azúcar`.',
            avoid: 'la sal (f.) – im Spanischen ist das Salz weiblich.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Die richtige Form wählen',
      exercises: [
        {
          id: 'es.g.polite-requests.L2.01',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 2,
          scenario: 'Du stehst an der Hotelrezeption und möchtest sehr höflich ein Doppelzimmer.',
          options: [
            { text: 'Quisiera una habitación doble, por favor.', why: 'Richtig: `quisiera` = „ich hätte gern“ – sehr höflich.' },
            { text: '¡Dame una habitación doble!', why: 'Ein tú-Befehl ohne `por favor` – viel zu direkt.' },
            { text: '¿Puedo tener una habitación doble?', why: 'Lehnübersetzung von „Kann ich … haben?“ – klingt unnatürlich.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Höflicher Wunsch: `Quisiera` + Nomen, gern mit `por favor`.',
            why: 'Befehle und wörtliche Übersetzungen wirken schnell unhöflich oder fremd.',
            avoid: 'Hotel, Restaurant, Schalter → quisiera.',
          },
        },
        {
          id: 'es.g.polite-requests.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 2,
          sentence: '¿___ pasas el pan, por favor?',
          german: 'Gibst du mir bitte das Brot?',
          answers: [['Me']],
          bank: ['Me', 'Te', 'Yo'],
          feedback: {
            rule: '„mir“ = `me`, vor dem Verb: `¿Me pasas …?`',
            why: '`te` hieße „dir“ – das Brot soll aber zu dir selbst; `yo` passt nicht zur Verbform `pasas`.',
            avoid: 'Bitte an tú: ¿Me + Verb?',
          },
        },
        {
          id: 'es.g.polite-requests.L2.03',
          type: 'dialogue',
          skills: ['speaking', 'vocabulary'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 2,
          lines: [
            { speaker: 'Camarero', text: 'Aquí tiene su café.', german: 'Hier ist Ihr Kaffee.' },
            { speaker: 'Du', text: 'Muchas gracias.', german: 'Vielen Dank.' },
            { speaker: 'Camarero', text: 'De nada.', german: 'Bitte, gern geschehen.' },
          ],
          gapIndex: 2,
          options: ['De nada.', 'Por favor.', 'Aquí tiene.'],
          answer: 0,
          feedback: {
            rule: 'Auf `gracias` antwortet man `de nada`.',
            why: '`por favor` bittet um etwas, `aquí tiene` überreicht etwas.',
            avoid: 'Danke → de nada.',
          },
        },
        {
          id: 'es.g.polite-requests.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 2,
          sentence: '¿Puede a repetir, por favor?',
          german: 'Können Sie das bitte wiederholen?',
          answers: ['¿Puede repetir, por favor?'],
          feedback: {
            rule: '`poder` + Infinitiv – ohne `a`.',
            why: 'Das `a` kommt vermutlich von `ir a` – bei `poder` gehört es nicht hin.',
            avoid: 'puedo/puedes/puede + Infinitiv, direkt.',
          },
        },
        {
          id: 'es.g.polite-requests.L2.05',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 2,
          tokens: ['¿', 'Me', 'trae', 'la', 'cuenta', ',', 'por', 'favor', '?'],
          german: 'Bringen Sie mir bitte die Rechnung?',
          feedback: {
            rule: '`me` vor dem Verb, `por favor` am Ende.',
            why: '„¿Trae me …?“ – das kleine `me` steht nie hinter einer konjugierten Form.',
            avoid: '¿Me + Verb + Ding, por favor?',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Höflich im Alltag',
      exercises: [
        {
          id: 'es.g.polite-requests.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Ich hätte gern einen Milchkaffee, bitte.',
          answers: [
            'Quisiera un café con leche, por favor.',
            'Yo quisiera un café con leche, por favor.',
            'Me gustaría un café con leche, por favor.',
            'Quería un café con leche, por favor.',
          ],
          feedback: {
            rule: '„Ich hätte gern“ = `quisiera` (oder `me gustaría`).',
            why: '`Quiero` ist korrekt, aber direkter („ich will“).',
            avoid: 'Beim Bestellen: Quisiera … por favor.',
          },
        },
        {
          id: 'es.g.polite-requests.L3.02',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Können Sie das bitte wiederholen?',
          answers: [
            '¿Puede repetir, por favor?',
            '¿Puede repetirlo, por favor?',
            '¿Puede repetir eso, por favor?',
            '¿Me lo puede repetir, por favor?',
            '¿Podría repetir, por favor?',
            '¿Podría repetirlo, por favor?',
            'Por favor, ¿puede repetir?',
            '¿Puede usted repetir, por favor?',
          ],
          feedback: {
            rule: 'usted: `¿Puede` + Infinitiv + `por favor`?',
            why: '`¿Puedes …?` wäre die du-Form.',
            avoid: 'Sie → puede · du → puedes.',
          },
        },
        {
          id: 'es.g.polite-requests.L3.03',
          type: 'translate',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 3,
          direction: 'toGerman',
          source: '¿Me pasas el agua?',
          answers: [
            'Gibst du mir das Wasser?',
            'Gibst du mir mal das Wasser?',
            'Reichst du mir das Wasser?',
            'Reichst du mir mal das Wasser?',
            'Kannst du mir das Wasser geben?',
            'Kannst du mir das Wasser reichen?',
            'Kannst du mir mal das Wasser geben?',
            'Kannst du mir mal das Wasser reichen?',
          ],
          feedback: {
            rule: '`pasar` = reichen, herübergeben; `me` = mir.',
            why: '„Gehst du mir …“ verwechselt `pasar` mit „vorbeigehen“.',
            avoid: 'Am Tisch: ¿Me pasas …? = Reichst du mir …?',
          },
        },
        {
          id: 'es.g.polite-requests.L3.04',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 3,
          scenario: 'Du sitzt mit Freunden beim Essen. Das Brot steht am anderen Ende des Tisches.',
          options: [
            { text: '¿Me pasas el pan, por favor?', why: 'Richtig: locker und freundlich unter Freunden.' },
            { text: '¿Puedo tener el pan?', why: 'Lehnübersetzung – so sagt man es nicht.' },
            { text: '¡Quiero el pan!', why: 'Klingt fordernd, fast wie ein Kind.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Unter Freunden: `¿Me pasas …, por favor?`',
            why: 'Die anderen Optionen sind unnatürlich oder zu direkt.',
            avoid: 'Frage + por favor = immer freundlich.',
          },
        },
        {
          id: 'es.g.polite-requests.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.polite-requests'],
          difficulty: 3,
          prompt: 'Du bist in einem Café. Bitte höflich um drei Dinge (z. B. die Karte, ein Getränk, die Rechnung) – mit verschiedenen Formen.',
          keywords: ['por favor', 'quisiera', 'me trae', 'me pone', 'me da', 'puede', 'me gustaría', 'la cuenta', 'gracias'],
          minMatch: 3,
          sample: 'Hola, ¿me trae la carta, por favor? Quisiera un café con leche. Y después, ¿me trae la cuenta? Gracias.',
          feedback: {
            rule: '¿Me trae…?, Quisiera…, ¿Puede…? – immer mit por favor oder gracias.',
            why: 'Häufig fehlt das `por favor`, oder man sagt `¿Puedo tener…?`.',
            avoid: 'Übe drei Chunks: ¿Me trae…? · Quisiera… · La cuenta, por favor.',
          },
        },
      ],
    },
  ],
  related: ['es.g.formality', 'es.g.stem-change', 'es.g.gustar'],
};
