import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.possessives',
  courseId: 'es',
  stageId: 'a1',
  order: 5,
  category: 'Pronomen',
  title: 'Possessivbegleiter – mi, tu, su …',
  summary: 'mein, dein, sein, unser: Die Possessivbegleiter richten sich nach dem Besitz, nicht nach dem Besitzer – und su kann vieles heißen.',
  keywords: [
    'Possessiv', 'Possessivbegleiter', 'Possessivpronomen', 'besitzanzeigend', 'mi', 'mis', 'tu', 'tus', 'su', 'sus', 'nuestro',
    'nuestra', 'vuestro', 'mein', 'dein', 'sein', 'ihr', 'unser', 'euer', 'mío', 'tuyo', 'Familie',
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Possessivbegleiter',
      headers: ['Besitzer', 'ein Besitz', 'mehrere', 'Deutsch'],
      rows: [
        ['yo', 'mi', 'mis', 'mein/e'],
        ['tú', 'tu', 'tus', 'dein/e'],
        ['él / ella / usted', 'su', 'sus', 'sein/e · ihr/e · Ihr/e'],
        ['nosotros/as', 'nuestro / nuestra', 'nuestros / nuestras', 'unser/e'],
        ['vosotros/as (Spanien)', 'vuestro / vuestra', 'vuestros / vuestras', 'euer/eure'],
        ['ellos / ellas / ustedes', 'su', 'sus', 'ihr/e · Ihr/e (· euer in Lateinamerika)'],
      ],
    },
    {
      type: 'text',
      md: 'Die Form richtet sich nach dem **Besitz**, nicht nach dem Besitzer: `mis libros` (meine Bücher), `nuestra casa` (unser Haus – `casa` ist weiblich). Nur `nuestro` und `vuestro` haben eine eigene weibliche Form; `mi`, `tu`, `su` ändern sich nur im Plural.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Mi', role: 'pronoun' },
        { text: ' hermana', role: 'subject' },
        { text: ' y ' },
        { text: 'sus', role: 'pronoun' },
        { text: ' amigos', role: 'subject' },
        { text: ' viven', role: 'verb' },
        { text: ' en ' },
        { text: 'nuestra', role: 'pronoun' },
        { text: ' casa', role: 'noun' },
        { text: '.' },
      ],
      german: 'Meine Schwester und ihre Freunde wohnen in unserem Haus.',
    },
    {
      type: 'text',
      md: '`su`/`sus` kann **sein, ihr, Ihr** und **ihr (Plural)** bedeuten. Meist klärt der Kontext das. Wenn nicht, sagt man es deutlicher: `la casa de él`, `la casa de ella`, `la casa de usted`, `la casa de Ana`.',
    },
    {
      type: 'text',
      md: 'Achtung Akzent: `tu` (dein) ohne Akzent – `tú` (du) mit Akzent. Und nach einem Verb oder allein benutzt man die langen Formen: `Es mío.` (Das gehört mir.) · `¿Es tuyo?` · `un amigo mío` (ein Freund von mir).',
    },
    {
      type: 'mistake',
      wrong: 'Mis vecinos venden sus casa.',
      right: 'Mis vecinos venden su casa.',
      why: 'Deutsche denken an „ihr“ (die Nachbarn = Plural). Entscheidend ist aber der Besitz: **eine** casa → `su`.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: Für „euer“ sagt man `vuestro/vuestra/vuestros/vuestras`: `¿Es vuestro perro?`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: `vuestro` wird nicht benutzt. „euer“ heißt `su/sus` – bei Unklarheit `de ustedes`: `¿Es su perro?` / `¿Es el perro de ustedes?`',
    },
    { type: 'tip', md: '**Der Besitz bestimmt die Form, nicht der Besitzer:** eine Sache → mi/tu/su, mehrere → mis/tus/sus.' },
    { type: 'audio', text: 'Mi hermana y sus amigos viven en nuestra casa.', label: 'Beispiel anhören' },
  ],
  examples: [
    { target: 'Mi madre es de Sevilla.', german: 'Meine Mutter kommt aus Sevilla.' },
    {
      target: 'Tus amigos son muy simpáticos.',
      german: 'Deine Freunde sind sehr sympathisch.',
      parts: [
        { text: 'Tus', role: 'pronoun' },
        { text: ' amigos', role: 'subject' },
        { text: ' son', role: 'verb' },
        { text: ' muy simpáticos', role: 'adjective' },
        { text: '.' },
      ],
    },
    { target: 'Carlos vive con su novia.', german: 'Carlos wohnt mit seiner Freundin zusammen.' },
    {
      target: 'Nuestra casa está cerca del centro.',
      german: 'Unser Haus ist in der Nähe des Zentrums.',
      parts: [
        { text: 'Nuestra', role: 'pronoun' },
        { text: ' casa', role: 'subject' },
        { text: ' está', role: 'verb' },
        { text: ' cerca del centro', role: 'adverb' },
        { text: '.' },
      ],
    },
    { target: 'Nuestros hijos estudian en Madrid.', german: 'Unsere Kinder studieren in Madrid.' },
    { target: 'El libro es mío.', german: 'Das Buch gehört mir.' },
    { target: '¿Es vuestro perro?', german: 'Ist das euer Hund?', variant: 'es-ES' },
    { target: '¿Es el perro de ustedes?', german: 'Ist das euer Hund?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'su casa',
      german: 'sein Haus · ihr Haus · Ihr Haus',
      md: 'Deutsch wählt nach dem **Besitzer** zwischen „sein“ und „ihr“. Spanisch hat für alle nur `su`.',
    },
    {
      type: 'compare',
      target: 'nuestra casa · nuestro perro',
      german: 'unser Haus · unser Hund',
      md: 'Wie im Deutschen („unsere Wohnung, unser Haus“) passt sich die Endung an den Besitz an – nur eben an das spanische Genus (`la casa`).',
    },
    {
      type: 'compare',
      target: 'mis padres',
      german: 'meine Eltern',
      md: 'Mehrere Besitzstücke → -s, genau wie „meine“ im Plural.',
    },
    {
      type: 'compare',
      target: 'Me duele la cabeza.',
      german: 'Mir tut der Kopf weh.',
      md: 'Bei Körperteilen steht wie im Deutschen meist der Artikel, nicht „mein“.',
    },
  ],
  mistakes: [
    { wrong: 'Mi libros', right: 'Mis libros', why: 'Mehrere Bücher → `mis`.' },
    { wrong: 'Nuestro casa', right: 'Nuestra casa', why: '`casa` ist weiblich → `nuestra`.' },
    { wrong: 'La mi casa', right: 'Mi casa', why: 'Kein Artikel vor dem Possessivbegleiter.' },
    { wrong: 'Mis vecinos venden sus casa.', right: 'Mis vecinos venden su casa.', why: 'Eine Sache → `su`, auch bei mehreren Besitzern.' },
    { wrong: 'Tú casa es bonita.', right: 'Tu casa es bonita.', why: '`tu` (dein) ohne Akzent; `tú` mit Akzent heißt „du“.' },
  ],
  mnemonic: '**Der Besitz bestimmt die Form, nicht der Besitzer.** Und `su` ist ein Allrounder: sein, ihr, Ihr.',
  levels: [
    {
      level: 1,
      title: 'Die Formen',
      exercises: [
        {
          id: 'es.g.possessives.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.possessives'],
          difficulty: 1,
          instruction: 'Ordne zu.',
          pairs: [
            { left: 'mi', right: 'mein/e' },
            { left: 'tu', right: 'dein/e' },
            { left: 'su', right: 'sein/e, ihr/e, Ihr/e' },
            { left: 'nuestro', right: 'unser' },
            { left: 'mis', right: 'meine (mehrere)' },
          ],
          feedback: {
            rule: 'mi/mis, tu/tus, su/sus, nuestro/a/os/as.',
            why: '`su` deckt mehrere deutsche Wörter ab.',
            avoid: 'Merke: `su` = alles in der 3. Person und bei usted/ustedes.',
          },
        },
        {
          id: 'es.g.possessives.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 1,
          sentence: '___ padres viven en Colonia.',
          german: 'Meine Eltern wohnen in Köln.',
          answers: [['Mis']],
          bank: ['Mi', 'Mis'],
          feedback: {
            rule: 'Plural-Besitz (`padres`) → `mis`.',
            why: '`mi` passt nur zu einem einzelnen Nomen.',
            avoid: 'Endet das Nomen auf -s, braucht auch mi/tu/su ein -s.',
          },
        },
        {
          id: 'es.g.possessives.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.possessives'],
          difficulty: 1,
          prompt: '„unser Haus“',
          options: [
            { text: 'nuestro casa', why: '`casa` ist weiblich – `nuestro` ist männlich.' },
            { text: 'nuestra casa', why: 'Richtig: weiblich Singular.' },
            { text: 'nuestras casa', why: '`nuestras` ist Plural – es geht um ein Haus.' },
          ],
          answer: 1,
          feedback: {
            rule: '`nuestro` passt sich in Genus und Zahl dem Besitz an.',
            why: '„Haus“ ist im Deutschen neutral, `casa` im Spanischen weiblich.',
            avoid: 'Genus immer vom spanischen Nomen ableiten.',
          },
        },
        {
          id: 'es.g.possessives.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.possessives'],
          difficulty: 1,
          audio: 'Mi hermana vive con su novio.',
          question: 'Mit wem wohnt die Schwester?',
          options: ['mit ihrem Freund', 'mit meinem Freund', 'mit ihrer Freundin'],
          answer: 0,
          feedback: {
            rule: '`su novio` = ihr Freund (Partner) – der Besitzer ist hier die Schwester.',
            why: '„mein“ wäre `mi`; `novia` wäre die Freundin.',
            avoid: 'Beim Hören: `su` → die Person, über die gerade gesprochen wird.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Anpassen',
      exercises: [
        {
          id: 'es.g.possessives.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 2,
          sentence: 'Carlos y Ana venden ___ casa.',
          german: 'Carlos und Ana verkaufen ihr Haus.',
          answers: [['su']],
          bank: ['su', 'sus'],
          feedback: {
            rule: 'Eine Sache → `su`, egal wie viele Besitzer.',
            why: '„ihr“ (Plural) verführt zu `sus` – es gibt aber nur **ein** Haus.',
            avoid: 'Zähle die Besitztümer, nicht die Besitzer.',
          },
        },
        {
          id: 'es.g.possessives.L2.02',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 2,
          sentence: 'Nuestro casa es pequeña.',
          german: 'Unser Haus ist klein.',
          answers: ['Nuestra casa es pequeña.'],
          feedback: {
            rule: '`casa` ist weiblich → `nuestra`.',
            why: 'Das deutsche „unser“ zeigt kein Genus – das spanische schon.',
            avoid: 'Das Adjektiv `pequeña` verrät das Genus bereits.',
          },
        },
        {
          id: 'es.g.possessives.L2.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'meine Eltern und meine Schwester',
          answers: ['mis padres y mi hermana'],
          feedback: {
            rule: 'mehrere → `mis`, eine Person → `mi`.',
            why: '„mi padres“ oder „mis hermana“ passen nicht zur Zahl.',
            avoid: 'Für jedes Nomen einzeln prüfen: Singular oder Plural?',
          },
        },
        {
          id: 'es.g.possessives.L2.04',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 2,
          sentence: '—¿Dónde están ___ llaves? —Están en ___ mochila.',
          german: '„Wo sind deine Schlüssel?“ – „Sie sind in deinem Rucksack.“',
          answers: [['tus'], ['tu']],
          bank: ['tu', 'tus'],
          feedback: {
            rule: 'mehrere Schlüssel → `tus`; ein Rucksack → `tu` (ohne Akzent).',
            why: 'Die Form richtet sich nach dem Besitz: `las llaves` (Plural), `la mochila` (Singular). `tú` mit Akzent wäre das Pronomen „du“.',
            avoid: 'Kurze Possessivbegleiter (mi, tu, su) tragen nie einen Akzent.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'su, vuestro & Co.',
      exercises: [
        {
          id: 'es.g.possessives.L3.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.possessives'],
          difficulty: 3,
          prompt: 'Was kann `su madre` bedeuten?',
          options: [
            { text: 'seine, ihre oder Ihre Mutter – je nach Kontext', why: 'Richtig: `su` ist mehrdeutig.' },
            { text: 'nur „seine Mutter“', why: '`su` unterscheidet nicht zwischen männlichem und weiblichem Besitzer.' },
            { text: 'nur „deine Mutter“', why: '„deine“ wäre `tu`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`su` = sein/ihr/Ihr/ihr (Pl.); zur Klärung: `la madre de él / de ella / de usted`.',
            why: 'Das Spanische markiert den Besitzer in der 3. Person nicht.',
            avoid: 'Bei Missverständnissen `de` + Person verwenden.',
          },
        },
        {
          id: 'es.g.possessives.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 3,
          variant: 'es-ES',
          instruction: 'Spanien: Du fragst eine Gruppe von Freunden.',
          sentence: '¿Es ___ perro, chicos?',
          german: 'Ist das euer Hund, Leute?',
          answers: [['vuestro']],
          bank: ['vuestro', 'vuestra', 'sus'],
          feedback: {
            rule: '„euer“ (Spanien) = `vuestro`; `perro` ist männlich Singular.',
            why: '`vuestra` wäre weiblich, `sus` Plural.',
            avoid: 'vuestro passt sich wie nuestro an den Besitz an.',
          },
        },
        {
          id: 'es.g.possessives.L3.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 3,
          variant: 'es-LA',
          instruction: 'Lateinamerika: Du fragst eine Gruppe von Freunden.',
          sentence: '¿Es ___ perro, chicos?',
          german: 'Ist das euer Hund, Leute?',
          answers: [['su']],
          bank: ['su', 'sus', 'vuestro'],
          feedback: {
            rule: 'In Lateinamerika heißt „euer“ `su` (von ustedes).',
            why: '`vuestro` gibt es dort nicht; `sus` wäre Plural.',
            avoid: 'Bei Unklarheit: `el perro de ustedes`.',
          },
        },
        {
          id: 'es.g.possessives.L3.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Unsere Kinder wohnen in Madrid.',
          answers: ['Nuestros hijos viven en Madrid.'],
          feedback: {
            rule: '`hijos` (männlich Plural, auch gemischt) → `nuestros`.',
            why: '„Nuestro hijos“ oder „nuestras hijos“ passen nicht zu Zahl bzw. Genus.',
            avoid: '„Kinder“ (eigene) = `hijos`; `niños` = Kinder allgemein.',
          },
        },
        {
          id: 'es.g.possessives.L3.05',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.possessives'],
          difficulty: 3,
          sentence: 'Mis vecinos venden sus casa.',
          german: 'Meine Nachbarn verkaufen ihr Haus.',
          answers: ['Mis vecinos venden su casa.'],
          feedback: {
            rule: 'Ein Besitz → `su`.',
            why: 'Die Zahl der Besitzer (`vecinos`) spielt keine Rolle.',
            avoid: 'Schau auf das Nomen direkt nach su/sus.',
          },
        },
      ],
    },
  ],
  related: ['es.g.pronouns', 'es.g.tener', 'es.g.gender-plural'],
};
