import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.prepositions-place',
  courseId: 'es',
  stageId: 'a1',
  order: 6,
  category: 'Präpositionen',
  title: 'Präpositionen des Ortes – wo ist was?',
  summary: 'al lado de, enfrente de, cerca de, entre … – mit estar sagen, wo etwas liegt. Und warum aus de + el immer del wird.',
  keywords: [
    'Präposition', 'Präpositionen', 'Ort', 'Lage', 'wo', 'dónde', 'estar', 'al lado de', 'neben', 'enfrente de', 'gegenüber',
    'delante de', 'vor', 'detrás de', 'hinter', 'cerca de', 'nah', 'in der Nähe', 'lejos de', 'weit', 'entre', 'zwischen',
    'a la derecha de', 'rechts', 'a la izquierda de', 'links', 'encima de', 'auf', 'debajo de', 'unter', 'en', 'in',
    'del', 'al', 'Kontraktion', 'Verschmelzung', 'hay', 'está',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Wenn du sagen willst, **wo** sich etwas Bestimmtes befindet, brauchst du `estar` + **Ortsangabe**: `El banco está al lado del hotel.` Die meisten spanischen Ortspräpositionen bestehen aus mehreren Wörtern und enden auf **de**.',
    },
    {
      type: 'table',
      title: 'Die wichtigsten Ortspräpositionen',
      headers: ['Spanisch', 'Deutsch', 'Beispiel'],
      rows: [
        ['en', 'in, auf, an', 'Las llaves están en la mesa.'],
        ['al lado de', 'neben', 'El banco está al lado del hotel.'],
        ['enfrente de', 'gegenüber (von)', 'La farmacia está enfrente de la estación.'],
        ['delante de', 'vor', 'El taxi está delante del hotel.'],
        ['detrás de', 'hinter', 'El parque está detrás del museo.'],
        ['cerca de', 'in der Nähe von, nah bei', 'El metro está cerca de aquí.'],
        ['lejos de', 'weit weg von', 'La playa está lejos del centro.'],
        ['entre … y …', 'zwischen … und …', 'El bar está entre el banco y la farmacia.'],
        ['a la derecha de', 'rechts von', 'El baño está a la derecha de la cocina.'],
        ['a la izquierda de', 'links von', 'La cocina está a la izquierda del comedor.'],
        ['encima de', 'auf, oben auf', 'El gato está encima del sofá.'],
        ['debajo de', 'unter', 'Los zapatos están debajo de la cama.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'El banco', role: 'subject' },
        { text: ' está', role: 'verb' },
        { text: ' al lado del', role: 'preposition' },
        { text: ' hotel', role: 'noun' },
        { text: '.' },
      ],
      german: 'Die Bank ist neben dem Hotel.',
    },
    {
      type: 'table',
      title: 'Verschmelzung: nur mit el',
      headers: ['Zusammen', 'wird zu', 'Beispiel'],
      rows: [
        ['de + el', 'del', 'cerca del parque'],
        ['a + el', 'al', 'Voy al centro. · ¿Cómo llego al museo?'],
        ['de + la / los / las', 'bleibt getrennt', 'cerca de la plaza · cerca de los bancos'],
      ],
    },
    {
      type: 'text',
      md: 'Die Verschmelzung ist **Pflicht** – `de el` schreibt man nie. Sie passiert aber nur mit dem Artikel `el`. Das betonte Pronomen `él` (er, mit Akzent) verschmilzt nicht: `al lado de él` (neben ihm).',
    },
    {
      type: 'mistake',
      wrong: 'La farmacia está cerca el parque.',
      right: 'La farmacia está cerca del parque.',
      why: 'Das `de` gehört fest zur Präposition: `cerca de`, `al lado de`, `enfrente de`. Vor `el` wird daraus `del`.',
    },
    {
      type: 'text',
      md: '**Wiederholung – hay oder está?** Bei etwas Unbestimmtem (ein, einige, Zahl, kein Artikel) sagst du `hay`: `Hay un banco cerca de aquí.` Bei etwas Bestimmtem (der, die, das, Namen, mein …) sagst du `está/están`: `El banco está cerca de aquí.`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In vielen Ländern Lateinamerikas hört man umgangssprachlich auch `atrás de` (= `detrás de`) und `adelante de` (= `delante de`). Mit `detrás de` und `delante de` liegst du überall richtig.',
    },
    { type: 'tip', md: '**Wo? → estar + Präposition + de.** Und aus `de + el` wird immer `del`, aus `a + el` immer `al`.' },
    { type: 'audio', text: 'El banco está al lado del hotel y la farmacia está enfrente de la estación.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: 'El banco está al lado del hotel.',
      german: 'Die Bank ist neben dem Hotel.',
      parts: [
        { text: 'El banco', role: 'subject' },
        { text: ' está', role: 'verb' },
        { text: ' al lado del', role: 'preposition' },
        { text: ' hotel', role: 'noun' },
        { text: '.' },
      ],
    },
    { target: 'La farmacia está enfrente de la estación.', german: 'Die Apotheke ist gegenüber vom Bahnhof.' },
    {
      target: '—¿Hay un supermercado cerca de aquí? —Sí, detrás de la iglesia.',
      german: '„Gibt es hier in der Nähe einen Supermarkt?“ – „Ja, hinter der Kirche.“',
    },
    { target: 'El museo está lejos del centro.', german: 'Das Museum ist weit weg vom Zentrum.' },
    {
      target: 'La parada está entre el banco y el café.',
      german: 'Die Haltestelle ist zwischen der Bank und dem Café.',
      parts: [
        { text: 'La parada', role: 'subject' },
        { text: ' está', role: 'verb' },
        { text: ' entre', role: 'preposition' },
        { text: ' el banco', role: 'noun' },
        { text: ' y' },
        { text: ' el café', role: 'noun' },
        { text: '.' },
      ],
    },
    { target: 'Mis llaves están encima de la mesa.', german: 'Meine Schlüssel liegen auf dem Tisch.' },
    { target: 'El gato está debajo de la cama.', german: 'Die Katze ist unter dem Bett.' },
    { target: 'Vivo cerca del parque.', german: 'Ich wohne in der Nähe des Parks.' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'al lado del hotel',
      german: 'neben dem Hotel',
      md: 'Deutsch: ein Wort + Dativ („neben dem“). Spanisch: feste Wendung mit `de` – der Artikel bleibt, nur `de + el` verschmilzt zu `del`.',
    },
    {
      type: 'compare',
      target: 'en la mesa · en la caja · en la pared',
      german: 'auf dem Tisch · in der Kiste · an der Wand',
      md: 'Das kleine `en` deckt „in“, „auf“ und „an“ ab. Nur wenn du betonen willst, dass etwas **oben auf** etwas liegt, sagst du `encima de`.',
    },
    {
      type: 'compare',
      target: 'delante de la casa · antes de la clase',
      german: 'vor dem Haus · vor dem Unterricht',
      md: 'Das deutsche „vor“ hat zwei Übersetzungen: räumlich `delante de`, zeitlich `antes de`.',
    },
    {
      type: 'compare',
      target: 'enfrente de la estación',
      german: 'gegenüber vom Bahnhof',
      md: 'Auch „gegenüber“ braucht im Spanischen das `de`. Gleichbedeutend: `frente a la estación`.',
    },
  ],
  mistakes: [
    { wrong: 'cerca el parque', right: 'cerca del parque', why: 'Das `de` gehört zur Präposition und verschmilzt mit `el` zu `del`.' },
    { wrong: 'al lado de el banco', right: 'al lado del banco', why: '`de el` wird immer zu `del` zusammengezogen.' },
    { wrong: 'Está enfrente la estación.', right: 'Está enfrente de la estación.', why: '„gegenüber“ heißt `enfrente de` – ohne `de` fehlt die Verbindung.' },
    { wrong: 'Hay el banco al lado del hotel.', right: 'El banco está al lado del hotel.', why: 'Bestimmte Dinge (mit `el/la`) werden mit `estar` verortet, nicht mit `hay`.' },
    { wrong: 'delante de la clase (zeitlich gemeint)', right: 'antes de la clase', why: 'Zeitliches „vor“ ist `antes de`; `delante de` ist nur räumlich.' },
  ],
  mnemonic: '**Wo? → estar + Präposition + de** – und aus de + el wird immer del.',
  levels: [
    {
      level: 1,
      title: 'Präpositionen kennen',
      exercises: [
        {
          id: 'es.g.prepositions-place.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'vocabulary'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 1,
          instruction: 'Ordne die Präpositionen ihrer Bedeutung zu.',
          pairs: [
            { left: 'al lado de', right: 'neben' },
            { left: 'enfrente de', right: 'gegenüber' },
            { left: 'delante de', right: 'vor' },
            { left: 'detrás de', right: 'hinter' },
            { left: 'entre', right: 'zwischen' },
            { left: 'lejos de', right: 'weit weg von' },
          ],
          feedback: {
            rule: 'Fast alle Ortspräpositionen enden auf `de` – nur `entre` und `en` nicht.',
            why: '`delante de` (vor) und `detrás de` (hinter) werden leicht verwechselt.',
            avoid: 'detrás – „dahinter“: beide haben ein „t-r“.',
          },
        },
        {
          id: 'es.g.prepositions-place.L1.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 1,
          prompt: '„Die Apotheke ist neben der Bank.“',
          options: [
            { text: 'La farmacia está al lado del banco.', why: 'Richtig: `al lado de` + `el banco` → `al lado del banco`.' },
            { text: 'La farmacia está al lado el banco.', why: 'Hier fehlt das `de` der Präposition.' },
            { text: 'La farmacia hay al lado del banco.', why: 'Bestimmte Dinge (la farmacia) verortet man mit `está`, nicht mit `hay`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`estar` + `al lado de`; `de + el` → `del`.',
            why: 'Das deutsche „neben“ ist ein einziges Wort – im Spanischen gehört `de` fest dazu.',
            avoid: 'Lerne die Präpositionen immer mit `de`: „al-lado-de“.',
          },
        },
        {
          id: 'es.g.prepositions-place.L1.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 1,
          sentence: 'El hotel está ___ lado ___ museo.',
          german: 'Das Hotel ist neben dem Museum.',
          answers: [['al'], ['del']],
          bank: ['al', 'el', 'del', 'de'],
          feedback: {
            rule: '„neben“ = `al lado de`; vor `el museo` wird `de el` zu `del`.',
            why: '`de el` schreibt man nie getrennt; `el lado` ohne `a` gibt es in dieser Wendung nicht.',
            avoid: 'Merke die ganze Wendung: `al lado del …` / `al lado de la …`.',
          },
        },
        {
          id: 'es.g.prepositions-place.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 1,
          audio: 'El café está detrás del museo.',
          question: 'Wo ist das Café?',
          options: ['hinter dem Museum', 'vor dem Museum', 'neben dem Museum'],
          answer: 0,
          feedback: {
            rule: '`detrás de` = hinter.',
            why: '„vor“ wäre `delante de`, „neben“ `al lado de`.',
            avoid: 'Achte auf den Anfang: _de-trás_ (hinter) vs. _de-lan-te_ (vor).',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'del, al und hay oder está',
      exercises: [
        {
          id: 'es.g.prepositions-place.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 2,
          sentence: 'La farmacia está cerca ___ parque.',
          german: 'Die Apotheke ist in der Nähe des Parks.',
          answers: [['del']],
          bank: ['de', 'del', 'al', 'el'],
          feedback: {
            rule: '`cerca de` + `el parque` → `cerca del parque`.',
            why: '`cerca de parque` ohne Artikel ist falsch, `cerca el` fehlt das `de`.',
            avoid: 'Steht nach `de` ein männliches `el`, schreibst du `del`.',
          },
        },
        {
          id: 'es.g.prepositions-place.L2.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 2,
          prompt: 'Welcher Satz ist richtig?',
          options: [
            { text: 'La playa está lejos del centro.', why: 'Richtig: `lejos de` + `el centro` → `lejos del centro`.' },
            { text: 'La playa está lejos de el centro.', why: '`de el` muss zu `del` verschmelzen.' },
            { text: 'La playa está lejos el centro.', why: 'Das `de` von `lejos de` fehlt.' },
          ],
          answer: 0,
          feedback: {
            rule: '`de + el = del` – immer.',
            why: 'Im Deutschen gibt es „von dem → vom“ – im Spanischen ist die Verschmelzung sogar Pflicht.',
            avoid: 'Denke an „vom“: `del` ist das spanische „vom“.',
          },
        },
        {
          id: 'es.g.prepositions-place.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 2,
          sentence: 'El banco está enfrente la estación.',
          german: 'Die Bank ist gegenüber vom Bahnhof.',
          answers: ['El banco está enfrente de la estación.', 'El banco está frente a la estación.'],
          feedback: {
            rule: '„gegenüber“ = `enfrente de` (oder `frente a`).',
            why: 'Ohne `de` hängt „la estación“ in der Luft.',
            avoid: 'enfrente **de**, al lado **de**, cerca **de** – das de gehört dazu.',
          },
        },
        {
          id: 'es.g.prepositions-place.L2.04',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.prepositions-place', 'es.g.hay'],
          difficulty: 2,
          sentence: '___ un supermercado cerca de aquí. El supermercado ___ al lado del hotel.',
          german: 'Hier in der Nähe gibt es einen Supermarkt. Der Supermarkt ist neben dem Hotel.',
          answers: [['Hay'], ['está']],
          bank: ['Hay', 'está', 'es'],
          feedback: {
            rule: 'Unbestimmt (`un supermercado`) → `hay`; bestimmt (`el supermercado`) → `está`.',
            why: '`es` beschreibt Eigenschaften, nicht den Ort. `Está un supermercado` klingt falsch, weil `un` Unbekanntes einführt.',
            avoid: 'un/una → hay · el/la → está.',
          },
        },
        {
          id: 'es.g.prepositions-place.L2.05',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 2,
          tokens: ['La', 'parada', 'está', 'entre', 'el', 'banco', 'y', 'el', 'hotel', '.'],
          alternatives: [['La', 'parada', 'está', 'entre', 'el', 'hotel', 'y', 'el', 'banco', '.']],
          german: 'Die Haltestelle ist zwischen der Bank und dem Hotel.',
          feedback: {
            rule: '`entre … y …` = zwischen … und … – ohne `de`.',
            why: '`entre` ist eine der wenigen Ortspräpositionen ohne `de`.',
            avoid: 'entre A **y** B – wie „zwischen A und B“.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Orte beschreiben',
      exercises: [
        {
          id: 'es.g.prepositions-place.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Das Museum ist gegenüber vom Park.',
          answers: ['El museo está enfrente del parque.', 'El museo está frente al parque.'],
          feedback: {
            rule: '`enfrente de` + `el parque` → `enfrente del parque` (oder `frente al parque`).',
            why: '„El museo es enfrente …“ ist falsch – Lage bestimmter Dinge mit `estar`.',
            avoid: 'Wo? → está. Und de + el → del.',
          },
        },
        {
          id: 'es.g.prepositions-place.L3.02',
          type: 'translate',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 3,
          direction: 'toGerman',
          source: 'Vivo cerca del centro.',
          answers: [
            'Ich wohne in der Nähe des Zentrums.',
            'Ich wohne in der Nähe vom Zentrum.',
            'Ich wohne nah am Zentrum.',
            'Ich wohne nahe dem Zentrum.',
            'Ich wohne nahe am Zentrum.',
            'Ich wohne nah beim Zentrum.',
            'Ich lebe in der Nähe des Zentrums.',
            'Ich lebe in der Nähe vom Zentrum.',
          ],
          feedback: {
            rule: '`cerca de` = in der Nähe von; `del` = `de + el`.',
            why: '`lejos` wäre „weit weg“; `centro` ist das (Stadt-)Zentrum.',
            avoid: 'cerca – nah, lejos – fern.',
          },
        },
        {
          id: 'es.g.prepositions-place.L3.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 3,
          sentence: 'Las llaves están encima de el sofá.',
          german: 'Die Schlüssel liegen auf dem Sofa.',
          answers: ['Las llaves están encima del sofá.'],
          feedback: {
            rule: '`de + el` → `del`: `encima del sofá`.',
            why: 'Getrennt geschrieben (`de el`) ist es ein Rechtschreibfehler.',
            avoid: 'Bei `el` nach `de` immer zusammenziehen – bei `la` nie.',
          },
        },
        {
          id: 'es.g.prepositions-place.L3.04',
          type: 'freeText',
          skills: ['writing', 'grammar'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 3,
          prompt: 'Beschreibe dein Viertel: Schreib zwei Sätze darüber, wo etwas liegt – mit `estar` und zwei verschiedenen Ortspräpositionen.',
          requirements: [
            { pattern: '\\best[aá]n?\\b', hint: 'eine Form von estar (está/están)' },
            { pattern: '(al lado|enfrente|delante|detr[aá]s|cerca|lejos|entre|derecha|izquierda|encima|debajo)', hint: 'eine Ortspräposition (al lado de, cerca de …)' },
          ],
          samples: ['El supermercado está al lado de mi casa. La farmacia está enfrente del banco.'],
          minWords: 8,
          feedback: {
            rule: 'Lage bestimmter Dinge: `estar` + Präposition (+ de).',
            why: 'Mit `es` oder `hay` klingt die Ortsangabe bei bestimmten Dingen falsch.',
            avoid: 'Kontrolliere: Steht nach der Präposition `de el`? → `del`.',
          },
        },
        {
          id: 'es.g.prepositions-place.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.prepositions-place'],
          difficulty: 3,
          prompt: 'Beschreibe laut, wo dein Lieblingscafé oder dein Supermarkt liegt – mit mindestens zwei Präpositionen.',
          keywords: ['está', 'al lado', 'cerca', 'lejos', 'enfrente', 'delante', 'detrás', 'entre', 'del', 'derecha', 'izquierda'],
          minMatch: 3,
          sample: 'Mi café favorito está cerca de mi casa, al lado del banco y enfrente del parque.',
          feedback: {
            rule: '`está` + `al lado de`, `cerca de`, `enfrente de` …',
            why: 'Häufig fehlt das `de` oder `de el` wird nicht zusammengezogen.',
            avoid: 'Sprich die Wendungen als Block: „al-lado-del“, „cerca-de-la“.',
          },
        },
      ],
    },
  ],
  related: ['es.g.hay', 'es.g.estar', 'es.g.articles'],
};
