import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.present-regular',
  courseId: 'es',
  stageId: 'stage0',
  order: 12,
  category: 'Verben',
  title: 'Regelmäßige Verben im Präsens',
  summary: 'Die drei Verbgruppen auf -ar, -er und -ir: Stamm + Endung – ein System für Hunderte Verben.',
  keywords: [
    'Präsens', 'Gegenwart', 'presente', 'regelmäßige Verben', 'Konjugation', 'konjugieren', '-ar', '-er', '-ir', 'Endungen',
    'hablar', 'comer', 'vivir', 'trabajar', 'aprender', 'escribir', 'Stamm', 'Verbendung',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Spanische Verben enden im Infinitiv auf **-ar**, **-er** oder **-ir**. Für das Präsens nimmst du die Endung weg und hängst an den **Stamm** die Personalendung: `habl-ar` → `habl-o`. Die Endung zeigt die Person so klar, dass das Pronomen meistens entfällt.',
    },
    {
      type: 'conjugation',
      verb: 'hablar',
      translation: 'sprechen',
      tense: 'Präsens · -ar',
      rows: [
        { person: 'yo', form: 'hablo', ending: 'o' },
        { person: 'tú', form: 'hablas', ending: 'as' },
        { person: 'él / ella / usted', form: 'habla', ending: 'a' },
        { person: 'nosotros / nosotras', form: 'hablamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'habláis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'hablan', ending: 'an' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'comer',
      translation: 'essen',
      tense: 'Präsens · -er',
      rows: [
        { person: 'yo', form: 'como', ending: 'o' },
        { person: 'tú', form: 'comes', ending: 'es' },
        { person: 'él / ella / usted', form: 'come', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'comemos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'coméis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'comen', ending: 'en' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'vivir',
      translation: 'leben, wohnen',
      tense: 'Präsens · -ir',
      rows: [
        { person: 'yo', form: 'vivo', ending: 'o' },
        { person: 'tú', form: 'vives', ending: 'es' },
        { person: 'él / ella / usted', form: 'vive', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'vivimos', ending: 'imos' },
        { person: 'vosotros / vosotras', form: 'vivís', ending: 'ís', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'viven', ending: 'en' },
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Viv', role: 'verb' },
        { text: 'imos', role: 'ending' },
        { text: ' en', role: 'preposition' },
        { text: ' Berlín', role: 'noun' },
        { text: ' y ' },
        { text: 'trabaj', role: 'verb' },
        { text: 'amos', role: 'ending' },
        { text: ' en', role: 'preposition' },
        { text: ' casa', role: 'noun' },
        { text: '.' },
      ],
      german: 'Wir wohnen in Berlin und arbeiten zu Hause. – Stamm + Endung.',
    },
    {
      type: 'tip',
      md: '**-ar-Verben haben ein a in der Endung, -er- und -ir-Verben ein e.** -er und -ir unterscheiden sich nur bei nosotros (`comemos` / `vivimos`) und vosotros (`coméis` / `vivís`).',
    },
    {
      type: 'text',
      md: 'Das Präsens beschreibt wie im Deutschen **Gewohnheiten** (`Trabajo los lunes.`), **Aktuelles** (`Vivo en Madrid.`) und oft auch die **nahe Zukunft** (`Mañana trabajo.`).',
    },
    {
      type: 'mistake',
      wrong: 'Yo hablar español.',
      right: 'Yo hablo español.',
      why: 'Der Infinitiv (`hablar`) wird nie direkt mit einer Person verwendet – er muss konjugiert werden.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika entfällt die vosotros-Form: `ustedes hablan`, `ustedes comen`, `ustedes viven`. In Argentinien und Uruguay sagt man statt `tú hablas` meist `vos hablás`, `vos comés`, `vos vivís` – mit Betonung auf der Endung.',
    },
    { type: 'audio', text: 'Hablo alemán, como mucha fruta y vivo en Colonia.', label: 'Alle drei Gruppen anhören' },
  ],
  examples: [
    {
      target: 'Hablo español y un poco de inglés.',
      german: 'Ich spreche Spanisch und ein bisschen Englisch.',
      parts: [
        { text: 'Habl', role: 'verb' },
        { text: 'o', role: 'ending' },
        { text: ' español y un poco de inglés.' },
      ],
    },
    { target: '¿Trabajas hoy?', german: 'Arbeitest du heute?' },
    { target: 'Mi hermana lee mucho.', german: 'Meine Schwester liest viel.' },
    {
      target: 'Mis padres viven en Colonia.',
      german: 'Meine Eltern wohnen in Köln.',
      parts: [
        { text: 'Mis padres', role: 'subject' },
        { text: ' viv', role: 'verb' },
        { text: 'en', role: 'ending' },
        { text: ' en Colonia.' },
      ],
    },
    { target: 'Aprendemos español porque viajamos mucho.', german: 'Wir lernen Spanisch, weil wir viel reisen.' },
    { target: '¿Vosotros escribís muchos correos?', german: 'Schreibt ihr viele E-Mails?', variant: 'es-ES' },
    { target: '¿Ustedes escriben muchos correos?', german: 'Schreibt ihr viele E-Mails?', variant: 'es-LA' },
    { target: 'Mañana trabajo en casa.', german: 'Morgen arbeite ich zu Hause.' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'hablo · hablas · habla',
      german: 'ich spreche · du sprichst · er spricht',
      md: 'Beide Sprachen konjugieren. Die spanischen Endungen sind aber eindeutiger – deshalb kann das Pronomen wegfallen.',
    },
    {
      type: 'compare',
      target: 'Mañana trabajo.',
      german: 'Morgen arbeite ich.',
      md: 'Wie im Deutschen kann das Präsens mit Zeitangabe die Zukunft ausdrücken.',
    },
    {
      type: 'compare',
      target: 'Vivo en Madrid desde 2020.',
      german: 'Ich wohne seit 2020 in Madrid.',
      md: '„seit“ + Präsens funktioniert im Spanischen genauso: `desde` + Präsens.',
    },
    {
      type: 'text',
      md: 'Im Deutschen ändert sich bei vielen Verben der Vokal („sprechen – du sprichst“). Die regelmäßigen spanischen Verben behalten ihren Stamm immer bei – nur die Endung wechselt.',
    },
  ],
  mistakes: [
    { wrong: 'Yo hablar español.', right: 'Hablo español.', why: 'Infinitiv statt konjugierter Form.' },
    { wrong: 'Nosotros vivemos en Berlín.', right: 'Nosotros vivimos en Berlín.', why: '-ir-Verben haben bei nosotros **-imos**, nicht -emos.' },
    { wrong: 'Tú come mucho.', right: 'Tú comes mucho.', why: 'Die du-Form endet immer auf **-s**.' },
    { wrong: 'Ustedes habláis muy bien.', right: 'Ustedes hablan muy bien.', why: '`ustedes` wird wie ellos konjugiert; -áis gehört zu vosotros.' },
    { wrong: 'Ella escribo una carta.', right: 'Ella escribe una carta.', why: '-o ist nur die yo-Endung; er/sie → -e.' },
  ],
  mnemonic: '**Stamm bleibt, Endung wechselt:** -o, -as/-es, -a/-e, -amos/-emos/-imos, -áis/-éis/-ís, -an/-en.',
  levels: [
    {
      level: 1,
      title: 'Endungen erkennen',
      exercises: [
        {
          id: 'es.g.present-regular.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.present-regular'],
          difficulty: 1,
          instruction: 'Ordne Verbform und Bedeutung zu.',
          pairs: [
            { left: 'hablo', right: 'ich spreche' },
            { left: 'comes', right: 'du isst' },
            { left: 'vive', right: 'er/sie wohnt' },
            { left: 'hablamos', right: 'wir sprechen' },
            { left: 'comen', right: 'sie essen' },
          ],
          feedback: {
            rule: '-o = ich, -as/-es = du, -a/-e = er/sie, -amos/-emos/-imos = wir, -an/-en = sie (Pl.).',
            why: 'Nur die Endung verrät die Person – der Stamm bleibt gleich.',
            avoid: 'Lies das Verb von hinten: Erst die Endung, dann der Stamm.',
          },
        },
        {
          id: 'es.g.present-regular.L1.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 1,
          verb: 'hablar',
          tense: 'Präsens',
          person: 'yo',
          sentence: '___ alemán y español.',
          answers: ['hablo'],
          feedback: {
            rule: 'yo → Stamm + **-o**: `habl-o`.',
            why: '`hablar` ist der Infinitiv, `habla` die er/sie-Form.',
            avoid: 'Die yo-Form endet bei allen regelmäßigen Verben auf -o.',
          },
        },
        {
          id: 'es.g.present-regular.L1.03',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 1,
          verb: 'comer',
          tense: 'Präsens',
          person: 'tú',
          sentence: 'Tú ___ mucha fruta.',
          answers: ['comes'],
          feedback: {
            rule: 'tú → -er-Verb: Stamm + **-es**: `com-es`.',
            why: '`come` ohne -s ist die er/sie-Form; `comas` gehört zu einer anderen Zeitform.',
            avoid: 'Die du-Form endet im Präsens immer auf -s.',
          },
        },
        {
          id: 'es.g.present-regular.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.present-regular'],
          difficulty: 1,
          audio: 'Vivimos en Colonia.',
          question: 'Wer wohnt in Köln?',
          options: ['ich', 'wir', 'ihr', 'sie (Plural)'],
          answer: 1,
          feedback: {
            rule: '`vivimos` = wir wohnen (-imos).',
            why: '„ich“ wäre `vivo`, „sie“ wäre `viven`.',
            avoid: 'Endung -mos = wir – ohne Ausnahme.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Formen bilden',
      exercises: [
        {
          id: 'es.g.present-regular.L2.01',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          verb: 'vivir',
          tense: 'Präsens',
          person: 'nosotros',
          sentence: 'Nosotros ___ en Hamburgo.',
          answers: ['vivimos'],
          feedback: {
            rule: '-ir-Verben: nosotros → **-imos**.',
            why: '„vivemos“ ist ein typischer Fehler – -emos gilt nur für -er-Verben.',
            avoid: 'Der Vokal des Infinitivs taucht in der wir-Form wieder auf: viv**i**r → viv**i**mos.',
          },
        },
        {
          id: 'es.g.present-regular.L2.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          verb: 'escribir',
          tense: 'Präsens',
          person: 'ella',
          sentence: 'Ella ___ un correo.',
          answers: ['escribe'],
          feedback: {
            rule: '-ir-Verben: él/ella → **-e**.',
            why: '„escriba“ ist eine andere Zeitform; „escribo“ ist die yo-Form.',
            avoid: '-er und -ir sind im Singular identisch: come, vive, escribe.',
          },
        },
        {
          id: 'es.g.present-regular.L2.03',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          verb: 'trabajar',
          tense: 'Präsens',
          person: 'mis padres (ellos)',
          sentence: 'Mis padres ___ en un hospital.',
          answers: ['trabajan'],
          feedback: {
            rule: 'ellos → -ar-Verb: Stamm + **-an**.',
            why: '`trabaja` wäre Singular, `trabajamos` hieße „wir“.',
            avoid: 'Mehrere Personen (`mis padres`) → Plural-Endung -an/-en.',
          },
        },
        {
          id: 'es.g.present-regular.L2.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Wir lernen Spanisch.',
          answers: [
            'Aprendemos español.',
            'Nosotros aprendemos español.',
            'Nosotras aprendemos español.',
            'Estudiamos español.',
            'Nosotros estudiamos español.',
            'Nosotras estudiamos español.',
          ],
          feedback: {
            rule: '`aprender` (-er) → `aprendemos`; auch `estudiar` → `estudiamos` ist möglich.',
            why: '„aprendamos“ ist eine andere Zeitform; „aprendimos“ ist Vergangenheit.',
            avoid: '-er-Verben: wir → -emos.',
          },
        },
        {
          id: 'es.g.present-regular.L2.05',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 2,
          sentence: 'Ustedes habláis muy bien español.',
          german: 'Sie sprechen sehr gut Spanisch.',
          answers: ['Ustedes hablan muy bien español.', 'Ustedes hablan español muy bien.'],
          feedback: {
            rule: '`ustedes` → 3. Person Plural: `hablan`.',
            why: '`habláis` gehört ausschließlich zu `vosotros`.',
            avoid: 'ustedes = ellos-Form, in Spanien wie in Lateinamerika.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Im Zusammenhang',
      exercises: [
        {
          id: 'es.g.present-regular.L3.01',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 3,
          variant: 'es-ES',
          verb: 'vivir',
          tense: 'Präsens',
          person: 'vosotros',
          sentence: '¿Vosotros ___ en Madrid?',
          answers: ['vivís'],
          feedback: {
            rule: '-ir-Verben: vosotros → **-ís** (mit Akzent).',
            why: '„viváis“ ist eine andere Zeitform, „vivéis“ gibt es nicht.',
            avoid: 'hablar → habláis, comer → coméis, vivir → vivís.',
          },
        },
        {
          id: 'es.g.present-regular.L3.02',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 3,
          tokens: ['Mis', 'amigos', 'no', 'comen', 'carne', 'y', 'beben', 'mucha', 'agua.'],
          extra: ['come', 'bebe'],
          german: 'Meine Freunde essen kein Fleisch und trinken viel Wasser.',
          feedback: {
            rule: 'Plural-Subjekt → `comen`, `beben` (-en).',
            why: '`come`/`bebe` sind Singular. Übrigens: `agua` ist weiblich, deshalb `mucha agua`.',
            avoid: 'Jedes Verb im Satz muss zum Subjekt passen.',
          },
        },
        {
          id: 'es.g.present-regular.L3.03',
          type: 'translate',
          skills: ['reading', 'grammar'],
          topicIds: ['es.g.present-regular'],
          difficulty: 3,
          direction: 'toGerman',
          source: 'Leo mucho, pero no escribo casi nunca.',
          answers: [
            'Ich lese viel, aber ich schreibe fast nie.',
            'Ich lese viel, aber schreibe fast nie.',
            'Ich lese viel, schreibe aber fast nie.',
          ],
          feedback: {
            rule: '`leo` (leer) = ich lese, `escribo` (escribir) = ich schreibe; `no … casi nunca` = fast nie.',
            why: 'Die -o-Endung zeigt beide Male „ich“.',
            avoid: 'Endung -o → „ich“, auch ohne `yo`.',
          },
        },
        {
          id: 'es.g.present-regular.L3.04',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.present-regular'],
          difficulty: 3,
          audio: '¿Dónde viven ustedes?',
          german: 'Wo wohnen Sie? / Wo wohnt ihr?',
          answers: ['¿Dónde viven ustedes?'],
          feedback: {
            rule: 'ustedes → `viven` (-en).',
            why: 'Man hört das -n am Ende – es zeigt den Plural.',
            avoid: 'Fragewort + Verb + Subjekt: `¿Dónde viven ustedes?`',
          },
        },
        {
          id: 'es.g.present-regular.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.present-regular'],
          difficulty: 3,
          prompt: 'Erzähle in zwei, drei Sätzen: Wo wohnst du? Arbeitest oder studierst du? Welche Sprachen sprichst du?',
          keywords: ['vivo', 'trabajo', 'estudio', 'hablo', 'aprendo'],
          minMatch: 2,
          sample: 'Vivo en Berlín, trabajo en una oficina y hablo alemán, inglés y un poco de español.',
          feedback: {
            rule: 'Über dich selbst: yo-Formen auf -o – `vivo`, `trabajo`, `estudio`, `hablo`.',
            why: 'Häufig rutscht der Infinitiv (`vivir`, `hablar`) hinein – er muss konjugiert werden.',
            avoid: 'Jeder Satz über dich beginnt mit einem Verb auf -o.',
          },
        },
      ],
    },
  ],
  related: ['es.g.pronouns', 'es.g.word-order-negation', 'es.g.questions'],
};
