import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.pronouns',
  courseId: 'es',
  stageId: 'stage0',
  order: 4,
  category: 'Pronomen',
  title: 'Personalpronomen – yo, tú, él …',
  summary: 'Die Subjektpronomen, ihre weiblichen Formen – und warum Spanier sie meistens weglassen.',
  keywords: [
    'Personalpronomen', 'Subjektpronomen', 'Pronomen', 'yo', 'tú', 'él', 'ella', 'usted', 'nosotros', 'nosotras',
    'vosotros', 'vosotras', 'ellos', 'ellas', 'ustedes', 'ich', 'du', 'er', 'sie', 'wir', 'ihr', 'weglassen', 'pro-drop', 'es',
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Subjektpronomen',
      headers: ['Person', 'Singular', 'Plural'],
      rows: [
        ['1.', 'yo – ich', 'nosotros / nosotras – wir'],
        ['2. (vertraut)', 'tú – du', 'vosotros / vosotras – ihr (nur Spanien)'],
        ['3.', 'él – er · ella – sie', 'ellos – sie (m./gemischt) · ellas – sie (nur f.)'],
        ['höflich', 'usted – Sie', 'ustedes – Sie (in Lateinamerika auch „ihr“)'],
      ],
    },
    {
      type: 'text',
      md: 'Im Plural gibt es weibliche Formen: `nosotras` sagen nur Frauen über sich, `ellas` bezeichnet eine Gruppe nur aus Frauen. **Sobald ein Mann dabei ist, nimmst du die männliche Form**: drei Frauen + ein Mann = `ellos`.',
    },
    {
      type: 'text',
      md: 'Das Wichtigste: Spanisch **lässt das Pronomen meistens weg**, weil die Verbendung die Person schon verrät. `Hablo alemán` heißt ohne `yo` „Ich spreche Deutsch“. Das Pronomen setzt man nur zur **Betonung** oder zum **Kontrast**.',
    },
    {
      type: 'conjugation',
      verb: 'hablar',
      translation: 'sprechen',
      tense: 'Präsens – die Endung zeigt die Person',
      rows: [
        { person: 'yo', form: 'hablo', ending: 'o' },
        { person: 'tú', form: 'hablas', ending: 'as' },
        { person: 'él / ella / usted', form: 'habla', ending: 'a' },
        { person: 'nosotros / nosotras', form: 'hablamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'habláis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'hablan', ending: 'an' },
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Yo', role: 'subject' },
        { text: ' hablo', role: 'verb' },
        { text: ' alemán', role: 'object' },
        { text: ' y ' },
        { text: 'ella', role: 'subject' },
        { text: ' habla', role: 'verb' },
        { text: ' español', role: 'object' },
        { text: '.' },
      ],
      german: 'Ich spreche Deutsch und sie spricht Spanisch. – Pronomen hier sinnvoll, weil zwei Personen gegenübergestellt werden.',
    },
    {
      type: 'mistake',
      wrong: 'Ello es fácil.',
      right: 'Es fácil.',
      why: 'Für das deutsche „es“ (Es ist leicht, es regnet) gibt es **kein** Subjektpronomen. Das Verb steht allein.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien sprichst du Freunde in der Gruppe mit `vosotros` (gemischt/männlich) bzw. `vosotras` (nur Frauen) an: `¿Vosotras habláis inglés?`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika gibt es kein vosotros – `ustedes` gilt für jede Gruppe. In Argentinien und Uruguay ersetzt `vos` das `tú` (`vos hablás`).',
    },
    { type: 'tip', md: '**Die Endung spricht schon für dich** – das Pronomen kommt nur, wenn du betonen oder unterscheiden willst.' },
    { type: 'audio', text: 'Yo hablo alemán y ella habla español.', label: 'Kontrast mit Pronomen anhören' },
  ],
  examples: [
    { target: 'Hablo alemán.', german: 'Ich spreche Deutsch.', note: 'Ohne `yo` – ganz natürlich.' },
    {
      target: 'Yo hablo inglés, pero él habla francés.',
      german: 'Ich spreche Englisch, aber er spricht Französisch.',
      parts: [
        { text: 'Yo', role: 'subject' },
        { text: ' hablo', role: 'verb' },
        { text: ' inglés', role: 'object' },
        { text: ', pero ' },
        { text: 'él', role: 'subject' },
        { text: ' habla', role: 'verb' },
        { text: ' francés', role: 'object' },
        { text: '.' },
      ],
      note: 'Kontrast → Pronomen sinnvoll.',
    },
    { target: 'Nosotras hablamos español.', german: 'Wir (Frauen) sprechen Spanisch.' },
    { target: 'Ellos hablan italiano.', german: 'Sie (Männer oder gemischte Gruppe) sprechen Italienisch.' },
    { target: '¿Usted habla alemán?', german: 'Sprechen Sie Deutsch?' },
    { target: '¿Vosotros habláis inglés?', german: 'Sprecht ihr Englisch?', variant: 'es-ES' },
    { target: '¿Ustedes hablan inglés?', german: 'Sprecht ihr Englisch? / Sprechen Sie Englisch?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Hablo español.',
      german: 'Ich spreche Spanisch.',
      md: 'Im Deutschen ist das Pronomen Pflicht („Spreche Spanisch“ klingt abgehackt). Im Spanischen ist es meistens überflüssig.',
    },
    {
      type: 'compare',
      target: 'Es interesante.',
      german: 'Es ist interessant.',
      md: 'Das deutsche Platzhalter-„es“ hat keine Entsprechung.',
    },
    {
      type: 'compare',
      target: 'ella / ellas',
      german: 'sie / sie',
      md: 'Deutsch hat für „sie“ (Singular), „sie“ (Plural) und „Sie“ dasselbe Wort. Spanisch unterscheidet klar: `ella`, `ellos`/`ellas`, `usted`/`ustedes`.',
    },
    {
      type: 'text',
      md: 'Anders als das Deutsche kennt das Spanische ein **weibliches „wir“ und „ihr“**: `nosotras`, `vosotras`.',
    },
  ],
  mistakes: [
    { wrong: 'Yo hablo, yo vivo, yo trabajo …', right: 'Hablo, vivo, trabajo …', why: 'Ständig wiederholtes `yo` klingt sehr betont, fast egozentrisch. Die Endung genügt.' },
    { wrong: '¿Ana y Lucía? Ellos hablan francés.', right: '¿Ana y Lucía? Ellas hablan francés.', why: 'Eine Gruppe nur aus Frauen ist `ellas`.' },
    { wrong: 'Ello es fácil.', right: 'Es fácil.', why: 'Das deutsche „es“ als Subjekt wird im Spanischen nicht übersetzt.' },
    { wrong: 'Yo hablas español.', right: 'Yo hablo español.', why: 'Pronomen und Verbendung müssen zusammenpassen: yo → -o, tú → -as.' },
  ],
  mnemonic: '**Die Endung spricht für dich.** Pronomen nur bei Betonung oder Kontrast – und ein Mann macht die Gruppe männlich.',
  levels: [
    {
      level: 1,
      title: 'Pronomen erkennen',
      exercises: [
        {
          id: 'es.g.pronouns.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'vocabulary'],
          topicIds: ['es.g.pronouns'],
          difficulty: 1,
          instruction: 'Ordne die Pronomen zu.',
          pairs: [
            { left: 'yo', right: 'ich' },
            { left: 'tú', right: 'du' },
            { left: 'él', right: 'er' },
            { left: 'ella', right: 'sie (eine Frau)' },
            { left: 'nosotros', right: 'wir' },
            { left: 'ellos', right: 'sie (mehrere)' },
          ],
          feedback: {
            rule: 'yo = ich, tú = du, él = er, ella = sie (Sg.), nosotros = wir, ellos = sie (Pl.).',
            why: 'Achte auf `él` mit Akzent (er) – ohne Akzent ist `el` der Artikel „der“.',
            avoid: 'Merke: `ella` mit -a = weiblich, `ellos` mit -os = Plural.',
          },
        },
        {
          id: 'es.g.pronouns.L1.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.pronouns'],
          difficulty: 1,
          prompt: 'Drei Frauen und ein Mann – wie heißt „sie“ für diese Gruppe?',
          options: [
            { text: 'ellas', why: '`ellas` nur, wenn ausschließlich Frauen gemeint sind.' },
            { text: 'ellos', why: 'Richtig: Sobald ein Mann dabei ist, steht die männliche Form.' },
            { text: 'ustedes', why: '`ustedes` ist die Anrede („Sie/ihr“), nicht „sie“.' },
          ],
          answer: 1,
          feedback: {
            rule: 'Gemischte Gruppen stehen im Maskulinum: `ellos`, `nosotros`, `vosotros`.',
            why: 'Die weibliche Pluralform gilt nur für reine Frauengruppen.',
            avoid: 'Ein einziger Mann in der Gruppe → männliche Form.',
          },
        },
        {
          id: 'es.g.pronouns.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.pronouns'],
          difficulty: 1,
          prompt: 'Du und deine Schwester sprecht über euch beide. Wie sagt ihr „wir“?',
          options: [
            { text: 'nosotros', why: 'Das wäre richtig, wenn ein Mann dabei wäre.' },
            { text: 'nosotras', why: 'Richtig, wenn du selbst eine Frau bist: nur Frauen → `nosotras`.' },
            { text: 'vosotras', why: '`vosotras` heißt „ihr“ (Frauen), nicht „wir“.' },
          ],
          answer: 1,
          instruction: 'Stell dir vor, du bist eine Frau.',
          feedback: {
            rule: '`nosotras` = wir (nur Frauen), `nosotros` = wir (Männer oder gemischt).',
            why: '`vosotras` meint die Angesprochenen („ihr“), nicht die Sprechenden.',
            avoid: 'nos- = wir, vos- = ihr.',
          },
        },
        {
          id: 'es.g.pronouns.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.pronouns'],
          difficulty: 1,
          audio: 'Ella habla alemán.',
          question: 'Wer spricht Deutsch?',
          options: ['ich', 'er', 'sie (eine Frau)', 'wir'],
          answer: 2,
          feedback: {
            rule: '`ella` = sie (eine Frau); `habla` ist die passende 3. Person Singular.',
            why: '„er“ wäre `él`, „wir“ wäre `nosotros` + `hablamos`.',
            avoid: 'Hör auf den Anfang: „e-ja“ = ella; „el“ = él.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Pronomen und Verb verbinden',
      exercises: [
        {
          id: 'es.g.pronouns.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.pronouns'],
          difficulty: 2,
          sentence: '—¿Y Pedro y Luis? —___ hablan inglés.',
          german: '„Und Pedro und Luis?“ – „Sie sprechen Englisch.“',
          answers: [['Ellos']],
          bank: ['Ellos', 'Ellas', 'Nosotros'],
          feedback: {
            rule: 'Zwei Männer → `ellos` (3. Person Plural, maskulin).',
            why: '`ellas` wäre nur für Frauen, `nosotros` hieße „wir“ und bräuchte `hablamos`.',
            avoid: 'Erst Anzahl, dann Geschlecht prüfen.',
          },
        },
        {
          id: 'es.g.pronouns.L2.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.pronouns'],
          difficulty: 2,
          prompt: 'Wer ist in `Hablamos español.` gemeint – ganz ohne Pronomen?',
          options: [
            { text: 'ich', why: '„ich“ hätte die Endung -o: `hablo`.' },
            { text: 'wir', why: 'Richtig: Die Endung -amos steht für nosotros/nosotras.' },
            { text: 'sie (Plural)', why: '„sie“ (Plural) hätte die Endung -an: `hablan`.' },
          ],
          answer: 1,
          feedback: {
            rule: 'Die Verbendung verrät die Person: -o (ich), -as (du), -a (er/sie/Sie), -amos (wir), -an (sie/Sie Pl.).',
            why: 'Deshalb kann das Pronomen wegfallen, ohne dass der Satz unklar wird.',
            avoid: 'Lies zuerst die Endung – sie ist dein Pronomen.',
          },
        },
        {
          id: 'es.g.pronouns.L2.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.pronouns'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Ich spreche Deutsch.',
          answers: ['Hablo alemán.', 'Yo hablo alemán.'],
          feedback: {
            rule: '`hablo` enthält schon „ich“ – `yo` ist möglich, aber nicht nötig.',
            why: 'Häufiger Fehler: `Yo habla` – die Endung muss zu yo passen (-o).',
            avoid: 'yo → Endung -o.',
          },
        },
        {
          id: 'es.g.pronouns.L2.04',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.pronouns'],
          difficulty: 2,
          verb: 'hablar',
          tense: 'Präsens',
          person: 'ella',
          sentence: 'Ella ___ español.',
          answers: ['habla'],
          feedback: {
            rule: 'él/ella/usted → Endung -a bei -ar-Verben: `habla`.',
            why: '`hablas` ist die du-Form, `hablan` der Plural.',
            avoid: 'Eine Person, über die man spricht → nur -a, kein -s.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Natürlich formulieren',
      exercises: [
        {
          id: 'es.g.pronouns.L3.01',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.pronouns'],
          difficulty: 3,
          sentence: 'Yo hablas español.',
          german: 'Ich spreche Spanisch.',
          answers: ['Yo hablo español.', 'Hablo español.'],
          feedback: {
            rule: 'Pronomen und Verbendung müssen übereinstimmen: yo → `hablo`.',
            why: '`hablas` gehört zu tú.',
            avoid: 'Nach dem Pronomen immer kurz die Endung prüfen.',
          },
        },
        {
          id: 'es.g.pronouns.L3.02',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.pronouns'],
          difficulty: 3,
          tokens: ['Yo', 'hablo', 'alemán,', 'pero', 'ella', 'habla', 'español.'],
          extra: ['hablas', 'ello'],
          german: 'Ich spreche Deutsch, aber sie spricht Spanisch.',
          feedback: {
            rule: 'Bei einem Gegensatz setzt man die Pronomen: `Yo …, pero ella …`.',
            why: '`ello` gibt es als Subjekt nicht, `hablas` passt weder zu yo noch zu ella.',
            avoid: 'Kontrast = Pronomen. Kein Kontrast = Pronomen weglassen.',
          },
        },
        {
          id: 'es.g.pronouns.L3.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.pronouns'],
          difficulty: 3,
          variant: 'es-ES',
          instruction: 'Spanien: Du fragst zwei Freundinnen.',
          sentence: '¿___ habláis inglés?',
          german: 'Sprecht ihr Englisch?',
          answers: [['Vosotras']],
          bank: ['Vosotros', 'Vosotras', 'Ustedes'],
          feedback: {
            rule: 'Vertraut + mehrere Frauen (Spanien) → `vosotras` + `habláis`.',
            why: '`vosotros` wäre für Männer/gemischt, `ustedes` passt nicht zu `habláis`.',
            avoid: 'Endung -áis gehört immer zu vosotros/vosotras.',
          },
        },
        {
          id: 'es.g.pronouns.L3.04',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.pronouns'],
          difficulty: 3,
          variant: 'es-LA',
          instruction: 'Lateinamerika: Du fragst zwei Freundinnen.',
          sentence: '¿___ hablan inglés?',
          german: 'Sprecht ihr Englisch?',
          answers: [['Ustedes']],
          bank: ['Ustedes', 'Ellas', 'Vosotras'],
          feedback: {
            rule: 'In Lateinamerika sprichst du jede Gruppe mit `ustedes` an.',
            why: '`ellas` hieße „sie“ (über andere), `vosotras` benutzt man nur in Spanien.',
            avoid: 'Angesprochene Gruppe in Lateinamerika = `ustedes` + Verb auf -n.',
          },
        },
        {
          id: 'es.g.pronouns.L3.05',
          type: 'translate',
          skills: ['reading', 'grammar'],
          topicIds: ['es.g.pronouns'],
          difficulty: 3,
          direction: 'toGerman',
          source: 'Nosotras hablamos alemán, pero ellos hablan inglés.',
          answers: [
            'Wir sprechen Deutsch, aber sie sprechen Englisch.',
            'Wir sprechen Deutsch, sie aber sprechen Englisch.',
          ],
          feedback: {
            rule: '`nosotras` = wir (Frauen), `ellos` = sie (Plural).',
            why: '`ellos` bezeichnet andere Personen – nicht die Angesprochenen („Sie“).',
            avoid: 'Übersetze die Pronomen mit Blick auf die Verbendung: -amos = wir, -an = sie.',
          },
        },
      ],
    },
  ],
  related: ['es.g.formality', 'es.g.present-regular', 'es.g.ser'],
};
