import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.questions',
  courseId: 'es',
  stageId: 'stage0',
  order: 14,
  category: 'Satzbau',
  title: 'Fragen stellen – ¿qué, dónde, cómo …?',
  summary: 'Ja/Nein-Fragen, die wichtigsten Fragewörter mit Akzent, die richtige Wortstellung – und das umgedrehte Fragezeichen.',
  keywords: [
    'Fragen', 'Fragewörter', 'Interrogativ', 'W-Fragen', 'qué', 'quién', 'dónde', 'de dónde', 'cuándo', 'cómo', 'cuánto', 'cuál',
    'por qué', 'porque', 'Fragezeichen', '¿', 'Wortstellung Frage', 'Intonation', 'was', 'wer', 'wo', 'woher', 'wann', 'wie', 'warum',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Spanische Fragen haben **zwei Fragezeichen**: `¿` am Anfang, `?` am Ende. So weißt du schon beim Vorlesen, dass eine Frage kommt, und kannst die Stimme passend führen.',
    },
    {
      type: 'text',
      md: '**Ja/Nein-Fragen** bildest du oft einfach mit der Stimme: Der Satz bleibt wie eine Aussage, die Stimme geht am Ende **nach oben**: `¿Hablas inglés?` · `¿Ana vive en Madrid?` Möglich ist auch, das Subjekt nach hinten zu stellen: `¿Vive Ana en Madrid?`',
    },
    {
      type: 'table',
      title: 'Die Fragewörter – immer mit Akzent',
      headers: ['Spanisch', 'Deutsch', 'Beispiel'],
      rows: [
        ['¿qué?', 'was? welche/r/s?', '¿Qué haces?'],
        ['¿quién? / ¿quiénes?', 'wer?', '¿Quién es?'],
        ['¿dónde?', 'wo?', '¿Dónde vives?'],
        ['¿de dónde?', 'woher?', '¿De dónde eres?'],
        ['¿cuándo?', 'wann?', '¿Cuándo trabajas?'],
        ['¿cómo?', 'wie?', '¿Cómo te llamas?'],
        ['¿cuánto/a/os/as?', 'wie viel(e)?', '¿Cuántos años tienes?'],
        ['¿cuál? / ¿cuáles?', 'welche/r/s? was?', '¿Cuál es tu número?'],
        ['¿por qué?', 'warum?', '¿Por qué estudias español?'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: '¿Dónde', role: 'question' },
        { text: ' vive', role: 'verb' },
        { text: ' tu', role: 'pronoun' },
        { text: ' hermana', role: 'subject' },
        { text: '?' },
      ],
      german: 'Wo wohnt deine Schwester? – Fragewort, dann Verb, dann Subjekt.',
    },
    {
      type: 'text',
      md: '**Wortstellung:** Nach dem Fragewort folgt direkt das **Verb**, das Subjekt kommt dahinter: `¿Dónde trabaja tu hermano?` Präpositionen stehen **vor** dem Fragewort: `¿De dónde…?`, `¿Con quién…?`, `¿Para qué…?`',
    },
    {
      type: 'text',
      md: '`cuánto` passt sich dem Nomen an: `¿Cuánto dinero?`, `¿Cuánta agua?`, `¿Cuántos años?`, `¿Cuántas personas?` – und `¿Cuánto cuesta?` (Wie viel kostet es?).',
    },
    {
      type: 'mistake',
      wrong: '¿Por qué? – Por qué estoy cansado.',
      right: '¿Por qué? – Porque estoy cansado.',
      why: 'Die Frage „warum?“ schreibt man getrennt mit Akzent (`por qué`), die Antwort „weil“ zusammen ohne Akzent (`porque`).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In der Karibik (Kuba, Puerto Rico, Dominikanische Republik) hörst du oft das Pronomen vor dem Verb: `¿Qué tú quieres?` statt `¿Qué quieres?`. Das ist dort normal – als Lernende/r bleibst du am besten bei der Standardform.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien hängt man gern `¿vale?` an, um Zustimmung zu holen: `Nos vemos a las ocho, ¿vale?` („…, okay?“). Überall verständlich sind `¿verdad?` und `¿no?`.',
    },
    { type: 'tip', md: '**Fragewort – Verb – Subjekt.** Und jedes Fragewort trägt einen Akzent.' },
    { type: 'audio', text: '¿Cómo te llamas? ¿De dónde eres? ¿Dónde vives?', label: 'Fragen mit Satzmelodie anhören' },
  ],
  examples: [
    { target: '¿Cómo te llamas?', german: 'Wie heißt du?' },
    {
      target: '¿De dónde eres?',
      german: 'Woher kommst du?',
      parts: [
        { text: '¿De', role: 'preposition' },
        { text: ' dónde', role: 'question' },
        { text: ' eres', role: 'verb' },
        { text: '?' },
      ],
    },
    {
      target: '¿Dónde trabaja tu hermano?',
      german: 'Wo arbeitet dein Bruder?',
      parts: [
        { text: '¿Dónde', role: 'question' },
        { text: ' trabaja', role: 'verb' },
        { text: ' tu hermano', role: 'subject' },
        { text: '?' },
      ],
    },
    { target: '¿Hablas inglés?', german: 'Sprichst du Englisch?', note: 'Ja/Nein-Frage nur durch die Stimme.' },
    { target: '¿Cuántos años tienes?', german: 'Wie alt bist du?', note: 'Wörtlich: „Wie viele Jahre hast du?“' },
    { target: '¿Cuál es tu número de teléfono?', german: 'Wie ist deine Telefonnummer?' },
    { target: '¿Con quién vives?', german: 'Mit wem wohnst du?' },
    { target: '—¿Por qué estudias español? —Porque viajo mucho.', german: '„Warum lernst du Spanisch?“ – „Weil ich viel reise.“' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: '¿Hablas alemán?',
      german: 'Sprichst du Deutsch?',
      md: 'Deutsch stellt das Verb an den Anfang. Spanisch braucht das nicht – die steigende Stimme macht die Frage.',
    },
    {
      type: 'compare',
      target: '¿De dónde eres?',
      german: 'Woher kommst du?',
      md: '„woher“ ist im Spanischen `de` + `dónde` („von wo“) – und das Verb ist `ser`, nicht „kommen“.',
    },
    {
      type: 'compare',
      target: '¿Cuál es tu dirección?',
      german: 'Wie/Was ist deine Adresse?',
      md: 'Vor `es` + Nomen fragt man meist mit `cuál`, nicht mit `qué`. `¿Qué es…?` fragt nach einer Definition („Was ist das überhaupt?“).',
    },
    {
      type: 'compare',
      target: '¿Por qué? – Porque…',
      german: 'Warum? – Weil…',
      md: 'Nach `porque` bleibt die Wortstellung normal – kein Verb am Ende wie nach „weil“.',
    },
  ],
  mistakes: [
    { wrong: '¿Dónde tu hermano trabaja?', right: '¿Dónde trabaja tu hermano?', why: 'Nach dem Fragewort folgt direkt das Verb.' },
    { wrong: 'Como te llamas?', right: '¿Cómo te llamas?', why: 'Fragewörter tragen einen Akzent; das Fragezeichen gehört auch an den Anfang.' },
    { wrong: '¿Qué es tu nombre?', right: '¿Cuál es tu nombre? / ¿Cómo te llamas?', why: 'Vor `es` + Nomen fragt man mit `cuál`. Am natürlichsten: `¿Cómo te llamas?`' },
    { wrong: '¿Porque estudias español?', right: '¿Por qué estudias español?', why: 'Die Frage „warum?“ sind zwei Wörter mit Akzent: `por qué`. `porque` (zusammen) heißt „weil“.' },
    { wrong: '¿Cuántas años tienes?', right: '¿Cuántos años tienes?', why: '`año` ist männlich → `cuántos`.' },
  ],
  mnemonic: '**Fragewort – Verb – Subjekt.** Jedes Fragewort trägt einen Akzent, jede Frage zwei Fragezeichen.',
  levels: [
    {
      level: 1,
      title: 'Fragewörter kennen',
      exercises: [
        {
          id: 'es.g.questions.L1.01',
          type: 'matchPairs',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.questions'],
          difficulty: 1,
          instruction: 'Ordne die Fragewörter zu.',
          pairs: [
            { left: '¿qué?', right: 'was?' },
            { left: '¿quién?', right: 'wer?' },
            { left: '¿dónde?', right: 'wo?' },
            { left: '¿cuándo?', right: 'wann?' },
            { left: '¿cómo?', right: 'wie?' },
            { left: '¿por qué?', right: 'warum?' },
          ],
          feedback: {
            rule: 'qué = was, quién = wer, dónde = wo, cuándo = wann, cómo = wie, por qué = warum.',
            why: '`quién` (wer) und `qué` (was) werden von Deutschsprachigen oft vertauscht.',
            avoid: 'quién hat ein **n** wie „wer? – **N**ame!“: Es fragt nach einer Person.',
          },
        },
        {
          id: 'es.g.questions.L1.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.questions'],
          difficulty: 1,
          prompt: '„Woher kommst du?“',
          options: [
            { text: '¿De dónde eres?', why: 'Richtig: `de dónde` = woher, `eres` = du bist.' },
            { text: '¿Dónde eres?', why: 'Ohne `de` fehlt das „her/von“.' },
            { text: '¿De dónde estás?', why: 'Herkunft drückt man mit `ser` aus, nicht mit `estar`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Herkunft erfragen: `¿De dónde + ser?`',
            why: '`estar` beschreibt Ort/Zustand, nicht Herkunft.',
            avoid: 'Frage und Antwort gleich bauen: `¿De dónde eres?` – `Soy de…`',
          },
        },
        {
          id: 'es.g.questions.L1.03',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.questions'],
          difficulty: 1,
          audio: '¿Cuándo trabajas?',
          question: 'Wonach wird gefragt?',
          options: ['nach dem Ort', 'nach der Zeit', 'nach dem Grund'],
          answer: 1,
          feedback: {
            rule: '`cuándo` = wann → Zeit.',
            why: 'Ort wäre `dónde`, Grund `por qué`.',
            avoid: 'cuándo ≈ „wann“ – beide mit **n**.',
          },
        },
        {
          id: 'es.g.questions.L1.04',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.questions'],
          difficulty: 1,
          scenario: 'Du lernst eine neue Kollegin kennen (ihr duzt euch) und willst wissen, wie sie heißt.',
          options: [
            { text: '¿Cómo te llamas?', why: 'Richtig: die übliche Frage nach dem Namen.' },
            { text: '¿Cómo estás?', why: 'Das heißt „Wie geht es dir?“.' },
            { text: '¿Dónde vives?', why: 'Das heißt „Wo wohnst du?“.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Nach dem Namen fragt man mit `¿Cómo te llamas?` (wörtlich: „Wie nennst du dich?“).',
            why: '`¿Cómo estás?` fragt nach dem Befinden.',
            avoid: 'Name → `llamarse`; Befinden → `estar`.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Fragen bauen',
      exercises: [
        {
          id: 'es.g.questions.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 2,
          sentence: '—¿___ vives? —Vivo en Hamburgo.',
          german: '„Wo wohnst du?“ – „Ich wohne in Hamburg.“',
          answers: [['Dónde']],
          bank: ['Dónde', 'Cuándo', 'Quién'],
          feedback: {
            rule: 'Frage nach dem Ort → `dónde`.',
            why: 'Die Antwort nennt eine Stadt – also einen Ort.',
            avoid: 'Schau dir die Antwort an: Sie verrät das Fragewort.',
          },
        },
        {
          id: 'es.g.questions.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 2,
          sentence: '¿___ años tienes?',
          german: 'Wie alt bist du?',
          answers: [['Cuántos']],
          bank: ['Cuántos', 'Cuántas', 'Cuánto'],
          feedback: {
            rule: '`cuánto` passt sich an: `año` ist männlich Plural → `cuántos`.',
            why: '`cuántas` wäre weiblich, `cuánto` Singular.',
            avoid: 'Erst das Nomen prüfen, dann die Endung von cuánto wählen.',
          },
        },
        {
          id: 'es.g.questions.L2.03',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 2,
          tokens: ['¿Dónde', 'trabaja', 'tu', 'hermano?'],
          extra: ['Qué'],
          german: 'Wo arbeitet dein Bruder?',
          feedback: {
            rule: 'Fragewort – Verb – Subjekt.',
            why: '„¿Dónde tu hermano trabaja?“ ist im Standardspanisch falsch.',
            avoid: 'Verb direkt hinter das Fragewort.',
          },
        },
        {
          id: 'es.g.questions.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 2,
          sentence: '¿Dónde tu hermana vive?',
          german: 'Wo wohnt deine Schwester?',
          answers: ['¿Dónde vive tu hermana?'],
          feedback: {
            rule: 'Nach dem Fragewort folgt das Verb: `¿Dónde vive…?`',
            why: 'Die Stellung „Subjekt vor Verb“ nach dem Fragewort klingt fehlerhaft.',
            avoid: 'Das Subjekt ans Ende der Frage stellen.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Feinheiten',
      exercises: [
        {
          id: 'es.g.questions.L3.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 3,
          sentence: '¿___ es tu número de teléfono?',
          german: 'Wie ist deine Telefonnummer?',
          answers: [['Cuál']],
          bank: ['Qué', 'Cuál', 'Cómo'],
          feedback: {
            rule: 'Vor `es` + Nomen fragt man nach einem konkreten Wert mit `cuál`.',
            why: '`¿Qué es tu número?` klingt, als wolltest du wissen, was eine Telefonnummer überhaupt ist; `¿Cómo es…?` fragt nach dem Aussehen.',
            avoid: 'Nummer, Name, Adresse, E-Mail → `¿Cuál es…?`',
          },
        },
        {
          id: 'es.g.questions.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 3,
          sentence: '—¿___ aprendes español? —___ viajo mucho a México.',
          german: '„Warum lernst du Spanisch?“ – „Weil ich viel nach Mexiko reise.“',
          answers: [['Por qué'], ['Porque']],
          bank: ['Por qué', 'Porque'],
          feedback: {
            rule: 'Frage: `por qué` (getrennt, Akzent). Antwort: `porque` (zusammen, ohne Akzent).',
            why: 'Die beiden werden gleich ausgesprochen, aber verschieden geschrieben.',
            avoid: 'Fragezeichen in der Nähe? → `por qué`.',
          },
        },
        {
          id: 'es.g.questions.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Mit wem wohnst du?',
          answers: ['¿Con quién vives?', '¿Con quién vives tú?'],
          feedback: {
            rule: 'Präposition + Fragewort am Anfang: `¿Con quién…?`',
            why: 'Die Präposition darf nicht ans Ende („¿Quién vives con?“).',
            avoid: 'Wie im Deutschen: „Mit wem…?“ – Präposition zuerst.',
          },
        },
        {
          id: 'es.g.questions.L3.04',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.questions'],
          difficulty: 3,
          audio: '¿De dónde son ustedes?',
          german: 'Woher kommen Sie? / Woher kommt ihr?',
          answers: ['¿De dónde son ustedes?'],
          feedback: {
            rule: '`¿De dónde` + `son` (ustedes).',
            why: '`dónde` trägt als Fragewort einen Akzent.',
            avoid: 'Fragewörter immer mit Akzent schreiben.',
          },
        },
        {
          id: 'es.g.questions.L3.05',
          type: 'speak',
          skills: ['pronunciation', 'speaking'],
          topicIds: ['es.g.questions'],
          difficulty: 3,
          text: '¿De dónde eres?',
          german: 'Woher kommst du?',
          phonetic: 'de DON-de E-res ↘',
          ipa: '[de ˈðon.de ˈe.ɾes]',
          pronItemId: 'es.p.into.de-donde-eres',
          feedback: {
            rule: 'Fragen mit Fragewort enden meist mit **fallender** Stimme; Ja/Nein-Fragen steigen am Ende.',
            why: 'Deutschsprachige heben bei jeder Frage die Stimme – bei W-Fragen klingt das im Spanischen überrascht oder ungläubig.',
            avoid: 'Betone `DÓN-de` kräftig und lass die Stimme danach ruhig fallen.',
          },
        },
      ],
    },
  ],
  related: ['es.g.stress', 'es.g.word-order-negation', 'es.g.ser'],
};
