import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.reflexive',
  courseId: 'es',
  stageId: 'a1',
  order: 3,
  category: 'Verben',
  title: 'Reflexive Verben – me llamo, me levanto',
  summary: 'Verben mit „se“: Das Reflexivpronomen passt sich der Person an und steht vor dem konjugierten Verb – oder hängt am Infinitiv.',
  keywords: [
    'reflexiv', 'reflexive Verben', 'Reflexivpronomen', 'sich', 'se', 'me', 'te', 'nos', 'os', 'llamarse', 'heißen',
    'levantarse', 'aufstehen', 'ducharse', 'duschen', 'lavarse', 'waschen', 'quedarse', 'bleiben', 'Tagesablauf', 'Alltag',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Reflexive Verben erkennst du am **-se** im Infinitiv: `llamarse` (heißen), `levantarse` (aufstehen), `ducharse` (duschen), `lavarse` (sich waschen), `quedarse` (bleiben). Beim Konjugieren wandert das `se` als passendes Pronomen **vor das Verb**.',
    },
    {
      type: 'conjugation',
      verb: 'llamarse',
      translation: 'heißen (wörtlich: sich nennen)',
      tense: 'Präsens',
      rows: [
        { person: 'yo', form: 'me llamo', ending: 'o' },
        { person: 'tú', form: 'te llamas', ending: 'as' },
        { person: 'él / ella / usted', form: 'se llama', ending: 'a' },
        { person: 'nosotros / nosotras', form: 'nos llamamos', ending: 'amos' },
        { person: 'vosotros / vosotras', form: 'os llamáis', ending: 'áis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'se llaman', ending: 'an' },
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Me', role: 'pronoun' },
        { text: ' levanto', role: 'verb' },
        { text: ' a las siete', role: 'adverb' },
        { text: ' y ' },
        { text: 'me', role: 'pronoun' },
        { text: ' ducho', role: 'verb' },
        { text: '.' },
      ],
      german: 'Ich stehe um sieben auf und dusche (mich).',
    },
    {
      type: 'text',
      md: '**Stellung des Pronomens:**\n- vor dem konjugierten Verb: `Me levanto.` · `No me levanto.`\n- bei Infinitiv: angehängt **oder** vor dem konjugierten Verb: `Tengo que levantarme.` = `Me tengo que levantar.`',
    },
    {
      type: 'text',
      md: 'Bei Körperteilen steht im Spanischen der **Artikel**, nicht das Possessiv: `Me lavo las manos.` (Ich wasche mir die Hände.) – das `me` zeigt ja schon, wessen Hände es sind.',
    },
    {
      type: 'mistake',
      wrong: 'Yo llamo Ana.',
      right: 'Me llamo Ana.',
      why: '`llamo` ohne `me` heißt „ich rufe (an)“. „Ich heiße“ = „ich nenne **mich**“ → `me llamo`.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: `¿A qué hora os levantáis?` – „Wann steht ihr auf?“ (vosotros → `os`).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: `¿A qué hora se levantan?` (ustedes → `se`). In Argentinien: `vos te llamás`, `vos te levantás`.',
    },
    { type: 'tip', md: '**me – te – se – nos – os – se:** Das Pronomen spiegelt das Subjekt und steht vor dem Verb.' },
    { type: 'audio', text: 'Me llamo Julia. Me levanto a las siete y me ducho.', label: 'Tagesablauf anhören' },
  ],
  examples: [
    {
      target: 'Me llamo Julia.',
      german: 'Ich heiße Julia.',
      parts: [{ text: 'Me', role: 'pronoun' }, { text: ' llamo', role: 'verb' }, { text: ' Julia', role: 'noun' }, { text: '.' }],
    },
    { target: '¿Cómo se llama usted?', german: 'Wie heißen Sie?' },
    { target: 'Mi hijo se ducha por la noche.', german: 'Mein Sohn duscht abends.' },
    {
      target: 'Hoy nos quedamos en casa.',
      german: 'Heute bleiben wir zu Hause.',
      parts: [
        { text: 'Hoy', role: 'adverb' },
        { text: ' nos', role: 'pronoun' },
        { text: ' quedamos', role: 'verb' },
        { text: ' en casa', role: 'object' },
        { text: '.' },
      ],
    },
    { target: 'Mañana tengo que levantarme temprano.', german: 'Morgen muss ich früh aufstehen.' },
    { target: 'Me lavo las manos.', german: 'Ich wasche mir die Hände.' },
    { target: '¿A qué hora os levantáis?', german: 'Um wie viel Uhr steht ihr auf?', variant: 'es-ES' },
    { target: '¿A qué hora se levantan?', german: 'Um wie viel Uhr steht ihr auf?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Me lavo.',
      german: 'Ich wasche mich.',
      md: 'Gleiche Idee wie im Deutschen – nur steht das Pronomen **vor** dem Verb.',
    },
    {
      type: 'compare',
      target: 'Me levanto.',
      german: 'Ich stehe auf.',
      md: 'Viele spanische Verben sind reflexiv, obwohl das deutsche Pendant es nicht ist: aufstehen, heißen, bleiben, aufwachen (`despertarse`).',
    },
    {
      type: 'compare',
      target: 'Me llamo Tom.',
      german: 'Ich heiße Tom.',
      md: 'Wörtlich: „Ich nenne mich Tom.“',
    },
    {
      type: 'compare',
      target: 'Me lavo las manos.',
      german: 'Ich wasche mir die Hände.',
      md: 'Beide Sprachen sagen „mir/me“ + Artikel – nicht „meine Hände“.',
    },
  ],
  mistakes: [
    { wrong: 'Yo llamo Ana.', right: 'Me llamo Ana.', why: 'Ohne `me` heißt es „ich rufe“.' },
    { wrong: 'Levanto a las siete.', right: 'Me levanto a las siete.', why: '`levantar` allein heißt „hochheben“.' },
    { wrong: 'Nosotros se levantamos.', right: 'Nosotros nos levantamos.', why: 'Das Pronomen passt sich an: nosotros → `nos`.' },
    { wrong: 'Me lavo mis manos.', right: 'Me lavo las manos.', why: 'Körperteile mit Artikel.' },
    { wrong: 'Tengo que me levantar.', right: 'Tengo que levantarme.', why: 'Das Pronomen hängt am Infinitiv oder steht vor `tengo`: `Me tengo que levantar`.' },
  ],
  mnemonic: '**Das Pronomen spiegelt das Subjekt:** yo → me, tú → te, él → se, nosotros → nos, vosotros → os, ellos → se.',
  levels: [
    {
      level: 1,
      title: 'Pronomen und Formen',
      exercises: [
        {
          id: 'es.g.reflexive.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.reflexive'],
          difficulty: 1,
          instruction: 'Ordne Person und Form zu.',
          pairs: [
            { left: 'yo', right: 'me llamo' },
            { left: 'tú', right: 'te llamas' },
            { left: 'ella', right: 'se llama' },
            { left: 'nosotros', right: 'nos llamamos' },
            { left: 'ellos', right: 'se llaman' },
          ],
          feedback: {
            rule: 'Pronomen + Verbform passen beide zur Person: me llamo, te llamas, se llama …',
            why: '`se` steht für er/sie/Sie **und** sie (Plural) – die Verbendung unterscheidet.',
            avoid: 'Erst das Pronomen, dann die Endung prüfen.',
          },
        },
        {
          id: 'es.g.reflexive.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 1,
          sentence: '___ llamo Carlos.',
          german: 'Ich heiße Carlos.',
          answers: [['Me']],
          bank: ['Me', 'Te', 'Se'],
          feedback: {
            rule: 'yo → `me` + `llamo`.',
            why: '`te` = dich, `se` = sich.',
            avoid: 'Endung -o (ich) → Pronomen `me`.',
          },
        },
        {
          id: 'es.g.reflexive.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.reflexive'],
          difficulty: 1,
          prompt: 'Was bedeutet `Me levanto a las siete.`?',
          options: [
            { text: 'Ich stehe um sieben auf.', why: 'Richtig: `levantarse` = aufstehen.' },
            { text: 'Ich hebe um sieben etwas hoch.', why: 'Das wäre `levanto algo` – ohne `me`.' },
            { text: 'Ich gehe um sieben ins Bett.', why: 'Das wäre `me acuesto`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`levantarse` (reflexiv) = aufstehen; `levantar` = hochheben.',
            why: 'Das Pronomen verändert die Bedeutung.',
            avoid: 'Lerne reflexive Verben immer mit -se.',
          },
        },
        {
          id: 'es.g.reflexive.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.reflexive'],
          difficulty: 1,
          audio: '¿Cómo se llama usted?',
          question: 'Was wird gefragt?',
          options: ['Wie heißen Sie?', 'Wie heißt du?', 'Wo wohnen Sie?'],
          answer: 0,
          feedback: {
            rule: '`se llama` + `usted` = höfliche Frage nach dem Namen.',
            why: '„Wie heißt du?“ wäre `¿Cómo te llamas?`.',
            avoid: 'usted → se + 3. Person.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Den Alltag beschreiben',
      exercises: [
        {
          id: 'es.g.reflexive.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 2,
          instruction: 'Setze „levantarse“ in der richtigen Form ein.',
          sentence: 'Nosotros ___ ___ a las ocho.',
          german: 'Wir stehen um acht auf.',
          answers: [['nos'], ['levantamos']],
          feedback: {
            rule: 'nosotros → `nos levantamos`.',
            why: '„se levantamos“ ist ein häufiger Fehler – das Pronomen muss zur Person passen.',
            avoid: 'nos + -amos: beide Male „wir“.',
          },
        },
        {
          id: 'es.g.reflexive.L2.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 2,
          verb: 'ducharse',
          tense: 'Präsens',
          person: 'él',
          sentence: 'Mi hermano ___ por la mañana.',
          answers: ['se ducha'],
          feedback: {
            rule: 'él → `se ducha` (Pronomen + Verb).',
            why: '`ducha` allein ist unvollständig; `se duchas` mischt zwei Personen.',
            avoid: 'Bei reflexiven Verben immer zwei Teile schreiben.',
          },
        },
        {
          id: 'es.g.reflexive.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 2,
          sentence: 'Nosotros se levantamos tarde.',
          german: 'Wir stehen spät auf.',
          answers: ['Nosotros nos levantamos tarde.', 'Nos levantamos tarde.'],
          feedback: {
            rule: 'nosotros → `nos`.',
            why: '`se` gilt nur für él/ella/usted und ellos/ellas/ustedes.',
            avoid: 'Das Pronomen spiegelt das Subjekt.',
          },
        },
        {
          id: 'es.g.reflexive.L2.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Ich heiße Lena.',
          answers: ['Me llamo Lena.', 'Yo me llamo Lena.', 'Soy Lena.'],
          feedback: {
            rule: '„Ich heiße“ = `me llamo` (oder kurz `soy`).',
            why: '„Yo llamo Lena“ bedeutet „Ich rufe Lena“.',
            avoid: 'Name → me llamo.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Stellung und Feinheiten',
      exercises: [
        {
          id: 'es.g.reflexive.L3.01',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 3,
          tokens: ['Mañana', 'tengo', 'que', 'levantarme', 'temprano.'],
          extra: ['me', 'levanto'],
          alternatives: [['Tengo', 'que', 'levantarme', 'temprano', 'mañana.']],
          german: 'Morgen muss ich früh aufstehen.',
          feedback: {
            rule: 'Nach `tener que` steht der Infinitiv; das Pronomen hängt sich an: `levantarme`.',
            why: '`me levanto` wäre konjugiert und passt nicht nach `tengo que`.',
            avoid: 'Infinitiv + Pronomen = ein Wort: levantar**me**, duchar**me**.',
          },
        },
        {
          id: 'es.g.reflexive.L3.02',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 3,
          sentence: 'Me lavo mis manos.',
          german: 'Ich wasche mir die Hände.',
          answers: ['Me lavo las manos.'],
          feedback: {
            rule: 'Körperteile mit bestimmtem Artikel, nicht mit Possessiv.',
            why: 'Das `me` zeigt bereits, wessen Hände es sind.',
            avoid: 'Wie im Deutschen: „mir die Hände“, nicht „meine Hände“.',
          },
        },
        {
          id: 'es.g.reflexive.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Heute bleiben wir zu Hause.',
          answers: [
            'Hoy nos quedamos en casa.',
            'Nos quedamos en casa hoy.',
            'Hoy nosotros nos quedamos en casa.',
            'Nosotros nos quedamos en casa hoy.',
            'Hoy nosotras nos quedamos en casa.',
            'Nosotras nos quedamos en casa hoy.',
          ],
          feedback: {
            rule: '„bleiben“ = `quedarse` (reflexiv): `nos quedamos`.',
            why: '`quedamos` ohne `nos` bedeutet etwas anderes (in Spanien z. B. „wir verabreden uns“).',
            avoid: 'Bleiben → quedar**se**.',
          },
        },
        {
          id: 'es.g.reflexive.L3.04',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.reflexive'],
          difficulty: 3,
          variant: 'es-ES',
          verb: 'levantarse',
          tense: 'Präsens',
          person: 'vosotros',
          sentence: '¿A qué hora ___ vosotros?',
          answers: ['os levantáis'],
          feedback: {
            rule: 'vosotros → `os levantáis`.',
            why: '`se levantan` gehört zu ustedes.',
            avoid: 'os + -áis: beide Male „ihr“.',
          },
        },
        {
          id: 'es.g.reflexive.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.reflexive'],
          difficulty: 3,
          prompt: 'Beschreibe deinen Morgen: Wann stehst du auf? Duschst du morgens oder abends?',
          keywords: ['me levanto', 'me ducho', 'me lavo', 'me quedo', 'me despierto'],
          minMatch: 2,
          sample: 'Me despierto a las seis y media, me levanto a las siete y me ducho.',
          feedback: {
            rule: 'Über dich selbst: `me` + Verb auf -o.',
            why: 'Häufig fehlt das `me` – dann ändert sich die Bedeutung („levanto“ = ich hebe hoch).',
            avoid: 'Jeder Satz über deinen Tagesablauf beginnt mit `Me …`.',
          },
        },
      ],
    },
  ],
  related: ['es.g.pronouns', 'es.g.present-regular', 'es.g.tener'],
};
