import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.ser-estar',
  courseId: 'es',
  stageId: 'stage0',
  order: 7,
  category: 'Verben',
  title: 'Ser oder estar?',
  summary: 'Die wichtigste Entscheidung der Anfängergrammatik: Wesen und Identität (ser) oder Ort und Zustand (estar)?',
  keywords: [
    'ser', 'estar', 'ser oder estar', 'ser vs estar', 'sein', 'Unterschied', 'Eigenschaft', 'Zustand', 'Ort', 'Identität',
    'aburrido', 'listo', 'rico', 'casado', 'Bedeutungsunterschied',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Beide Verben heißen „sein“, aber sie beantworten verschiedene Fragen:\n- `ser` → **Wer oder was ist es? Wie ist es grundsätzlich?** (Identität, Herkunft, Beruf, Charakter, Aussehen)\n- `estar` → **Wo ist es? Wie geht es / wie ist es gerade?** (Ort, Befinden, Stimmung, Zustand)',
    },
    {
      type: 'table',
      title: 'Ser oder estar – die Übersicht',
      headers: ['ser', 'estar'],
      rows: [
        ['Identität: Soy Marta.', 'Ort: Estoy en el trabajo.'],
        ['Herkunft: Soy de Chile.', 'Befinden: Estoy bien.'],
        ['Beruf: Es profesor.', 'Stimmung: Está contento.'],
        ['Charakter: Es simpática.', 'Zustand: La puerta está abierta.'],
        ['Aussehen: Es alto.', 'Ergebnis: La comida está lista.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Ana', role: 'subject' },
        { text: ' es', role: 'verb' },
        { text: ' muy', role: 'adverb' },
        { text: ' simpática', role: 'adjective' },
        { text: ', pero hoy ' },
        { text: 'está', role: 'verb' },
        { text: ' triste', role: 'adjective' },
        { text: '.' },
      ],
      german: 'Ana ist sehr sympathisch (Charakter), aber heute ist sie traurig (Stimmung).',
    },
    {
      type: 'table',
      title: 'Gleiches Adjektiv – andere Bedeutung',
      headers: ['mit ser', 'mit estar'],
      rows: [
        ['Es aburrido. – Er ist langweilig.', 'Está aburrido. – Ihm ist langweilig.'],
        ['Es listo. – Er ist klug.', 'Está listo. – Er ist fertig/bereit.'],
        ['Es rico. – Er ist reich.', 'Está rico. – Es schmeckt lecker.'],
        ['Es guapa. – Sie ist hübsch.', 'Está guapa. – Sie sieht (heute) hübsch aus.'],
      ],
    },
    {
      type: 'text',
      md: 'Eine Ausnahme merkst du dir extra: **Ereignisse** (Party, Konzert, Kurs) „finden statt“ – dafür nimmt man `ser`, auch wenn es um den Ort geht: `La fiesta es en mi casa.` Personen und Dinge befinden sich dagegen mit `estar`: `Mis amigos están en mi casa.`',
    },
    {
      type: 'mistake',
      wrong: 'Soy cansada.',
      right: 'Estoy cansada.',
      why: 'Müdigkeit ist ein Zustand. `ser` würde bedeuten, dass Müdigkeit zu deinem Wesen gehört.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Beim Familienstand sind beide Verben korrekt. In Lateinamerika hört man häufig `Soy casado` („Ich bin verheiratet“), in Spanien eher `Estoy casado`.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien sagt man bei Krankheit oft `Estoy malo/mala` („Ich bin krank“). Neutral und überall verständlich ist `Estoy enfermo/enferma`.',
    },
    {
      type: 'tip',
      md: '**Wie du dich fühlst und wo du bist, das sagst du mit estar.** Alles, was im Steckbrief steht, sagst du mit ser.',
    },
    { type: 'audio', text: 'Ana es muy simpática, pero hoy está triste.', label: 'Kontrast anhören' },
  ],
  examples: [
    {
      target: 'Soy de Múnich, pero estoy en Valencia.',
      german: 'Ich komme aus München, aber ich bin (gerade) in Valencia.',
      parts: [
        { text: 'Soy', role: 'verb' },
        { text: ' de Múnich, pero ' },
        { text: 'estoy', role: 'verb' },
        { text: ' en Valencia.' },
      ],
    },
    { target: 'Mi hermano es alto y moreno.', german: 'Mein Bruder ist groß und dunkelhaarig.' },
    { target: 'Mi hermano está enfermo.', german: 'Mein Bruder ist krank.' },
    { target: 'La película es aburrida.', german: 'Der Film ist langweilig.' },
    { target: 'Estoy aburrido.', german: 'Mir ist langweilig.' },
    { target: 'La paella está muy rica.', german: 'Die Paella schmeckt sehr lecker.' },
    { target: 'El concierto es en el parque.', german: 'Das Konzert findet im Park statt.', note: 'Ereignis → ser.' },
    { target: '¿Estás lista?', german: 'Bist du fertig/bereit?' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Es aburrido. / Está aburrido.',
      german: 'Er ist langweilig. / Ihm ist langweilig.',
      md: 'Das Deutsche kennt diesen Unterschied auch – es drückt ihn nur mit anderen Mitteln aus.',
    },
    {
      type: 'compare',
      target: 'La sopa está rica.',
      german: 'Die Suppe schmeckt gut.',
      md: 'Wie etwas gerade schmeckt, ist ein Eindruck im Moment → `estar`.',
    },
    {
      type: 'compare',
      target: 'Estoy lista.',
      german: 'Ich bin fertig.',
      md: '„fertig/bereit“ = `estar listo/lista`. Mit `ser` hieße es „klug“.',
    },
    {
      type: 'text',
      md: 'Die Faustregel „dauerhaft = ser, vorübergehend = estar“ hilft oft, stimmt aber nicht immer: `Estoy en Berlín` gilt auch, wenn du dort seit 20 Jahren wohnst (Ort → estar). Frag lieber nach der **Funktion**: Identität/Wesen oder Ort/Zustand?',
    },
  ],
  mistakes: [
    { wrong: 'Soy cansada.', right: 'Estoy cansada.', why: 'Zustand → estar.' },
    { wrong: 'Estoy alemana.', right: 'Soy alemana.', why: 'Nationalität gehört zur Identität → ser.' },
    { wrong: 'Mi madre es en el trabajo.', right: 'Mi madre está en el trabajo.', why: 'Wo sich eine Person befindet → estar.' },
    { wrong: 'La película está aburrida.', right: 'La película es aburrida.', why: 'Der Film hat die Eigenschaft „langweilig“ → ser. `estar aburrido` sagt man über Menschen, denen langweilig ist.' },
    { wrong: 'El concierto está en el parque.', right: 'El concierto es en el parque.', why: 'Ereignisse „finden statt“ → ser.' },
  ],
  mnemonic: '**Steckbrief → ser. Wo und wie gerade → estar.**',
  levels: [
    {
      level: 1,
      title: 'Die Grundregel',
      exercises: [
        {
          id: 'es.g.ser-estar.L1.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 1,
          sentence: 'Yo ___ de Berlín.',
          german: 'Ich komme aus Berlin.',
          answers: [['soy']],
          bank: ['soy', 'estoy'],
          feedback: {
            rule: 'Herkunft → `ser de`.',
            why: '`estoy de` gibt es in dieser Bedeutung nicht.',
            avoid: 'Woher? = Steckbrief = ser.',
          },
        },
        {
          id: 'es.g.ser-estar.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 1,
          sentence: 'Hoy ___ muy cansado.',
          german: 'Heute bin ich sehr müde.',
          answers: [['estoy']],
          bank: ['soy', 'estoy'],
          feedback: {
            rule: 'Zustand/Befinden → `estar`.',
            why: '`soy cansado` würde heißen, dass du ein müder Mensch bist – als Charaktereigenschaft.',
            avoid: 'Signalwort `hoy` (heute) deutet oft auf einen momentanen Zustand.',
          },
        },
        {
          id: 'es.g.ser-estar.L1.03',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 1,
          instruction: 'Warum ser, warum estar? Ordne zu.',
          pairs: [
            { left: 'Soy Luis.', right: 'Identität (ser)' },
            { left: 'Soy de Chile.', right: 'Herkunft (ser)' },
            { left: 'Estoy en casa.', right: 'Ort (estar)' },
            { left: 'Estoy triste.', right: 'Stimmung (estar)' },
          ],
          feedback: {
            rule: 'ser: Identität, Herkunft, Beruf, Charakter. estar: Ort, Befinden, Stimmung, Zustand.',
            why: 'Die Verbform (soy/estoy) verrät schon, welche Funktion der Satz hat.',
            avoid: 'Stelle zu jedem Satz die Frage „Wer/was?“ oder „Wo/wie gerade?“.',
          },
        },
        {
          id: 'es.g.ser-estar.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 1,
          audio: 'Mi hermana está en Madrid.',
          question: 'Was erfährst du über die Schwester?',
          options: ['Sie ist gerade in Madrid.', 'Sie kommt aus Madrid.', 'Sie ist Spanierin.'],
          answer: 0,
          feedback: {
            rule: '`estar en` = sich an einem Ort befinden.',
            why: '„Sie kommt aus Madrid“ hieße `es de Madrid`.',
            avoid: '`está en` → Ort; `es de` → Herkunft.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Beides im Satz',
      exercises: [
        {
          id: 'es.g.ser-estar.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 2,
          sentence: 'Carlos ___ médico y hoy ___ en el hospital.',
          german: 'Carlos ist Arzt und heute ist er im Krankenhaus.',
          answers: [['es'], ['está']],
          bank: ['es', 'está'],
          feedback: {
            rule: 'Beruf → `ser`; Ort → `estar`.',
            why: 'Wer die Verben vertauscht, sagt „Carlos befindet sich Arzt“ bzw. „ist ein Krankenhaus“.',
            avoid: 'Jeden Satzteil einzeln prüfen: Was? → ser, Wo? → estar.',
          },
        },
        {
          id: 'es.g.ser-estar.L2.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 2,
          prompt: 'Die Suppe schmeckt heute richtig gut. Was sagst du?',
          options: [
            { text: 'La sopa está muy rica.', why: 'Richtig: Geschmack im Moment → estar; `rica` passt zu `sopa` (feminin).' },
            { text: 'La sopa es muy rica.', why: 'Mit ser hieße `rico` eher „reich“ – oder eine allgemeine Aussage.' },
            { text: 'La sopa está muy rico.', why: '`sopa` ist feminin – das Adjektiv muss `rica` heißen.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Wie etwas gerade schmeckt oder aussieht → `estar` + Adjektiv (angepasst).',
            why: '`ser rico` bedeutet „reich sein“.',
            avoid: 'Lob fürs Essen: `¡Está riquísimo!` – immer mit estar.',
          },
        },
        {
          id: 'es.g.ser-estar.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 2,
          sentence: 'Mi madre es en el trabajo.',
          german: 'Meine Mutter ist bei der Arbeit.',
          answers: ['Mi madre está en el trabajo.'],
          feedback: {
            rule: 'Wo sich eine Person befindet → `estar`.',
            why: 'Das deutsche „ist“ verleitet zu `es`.',
            avoid: 'Sobald `en` + Ort folgt und eine Person/ein Ding gemeint ist: estar.',
          },
        },
        {
          id: 'es.g.ser-estar.L2.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Ich bin Deutsche, aber ich bin in Spanien.',
          answers: [
            'Soy alemana, pero estoy en España.',
            'Yo soy alemana, pero estoy en España.',
            'Soy alemana pero estoy en España.',
          ],
          feedback: {
            rule: 'Nationalität → `ser` (`soy alemana`); Aufenthaltsort → `estar` (`estoy en España`).',
            why: '„Estoy alemana“ ist falsch – Nationalität ist keine momentane Lage.',
            avoid: 'Zwei „bin“ im deutschen Satz = oft zwei verschiedene spanische Verben.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Feine Unterschiede',
      exercises: [
        {
          id: 'es.g.ser-estar.L3.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 3,
          prompt: 'Was bedeutet `Pablo está listo.`?',
          options: [
            { text: 'Pablo ist fertig / bereit.', why: 'Richtig: `estar listo` = fertig, bereit.' },
            { text: 'Pablo ist klug.', why: 'Das wäre `Pablo es listo`.' },
            { text: 'Pablo ist langweilig.', why: 'Das wäre `Pablo es aburrido`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`ser listo` = klug; `estar listo` = fertig/bereit.',
            why: 'Das Verb ändert bei manchen Adjektiven die Bedeutung.',
            avoid: 'Lerne diese Paare als feste Einheiten: ser listo / estar listo, ser aburrido / estar aburrido.',
          },
        },
        {
          id: 'es.g.ser-estar.L3.02',
          type: 'situation',
          skills: ['grammar', 'speaking'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 3,
          scenario: 'Du bist auf einer Party und langweilst dich. Du flüsterst deiner Freundin zu:',
          options: [
            { text: 'Estoy aburrido.', why: 'Richtig: Mir ist (gerade) langweilig → estar.' },
            { text: 'Soy aburrido.', why: 'Das heißt: „Ich bin ein langweiliger Mensch.“' },
            { text: 'Está aburrido.', why: 'Das heißt „Ihm/Ihr ist langweilig“ oder „Ihnen ist langweilig“ – nicht über dich selbst.' },
          ],
          answer: 0,
          feedback: {
            rule: '`estar aburrido` = sich langweilen; `ser aburrido` = langweilig sein (Charakter).',
            why: 'Mit `soy` beschreibst du deinen Charakter – das willst du hier sicher nicht sagen.',
            avoid: 'Gefühl im Moment → estar. (Frauen sagen `Estoy aburrida`.)',
          },
        },
        {
          id: 'es.g.ser-estar.L3.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 3,
          sentence: 'La fiesta ___ en mi casa, pero mis amigos todavía ___ en el bar.',
          german: 'Die Party findet bei mir zu Hause statt, aber meine Freunde sind noch in der Bar.',
          answers: [['es'], ['están']],
          bank: ['es', 'está', 'son', 'están'],
          feedback: {
            rule: 'Ereignis findet statt → `ser`; Personen befinden sich → `estar`.',
            why: '`La fiesta está en mi casa` klingt für Muttersprachler falsch, weil eine Party kein Gegenstand ist, der sich irgendwo befindet.',
            avoid: 'fiesta, concierto, clase, reunión + Ort → ser.',
          },
        },
        {
          id: 'es.g.ser-estar.L3.04',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 3,
          tokens: ['Ana', 'es', 'muy', 'simpática,', 'pero', 'hoy', 'está', 'triste.'],
          extra: ['estás', 'eres'],
          alternatives: [['Ana', 'es', 'muy', 'simpática,', 'pero', 'está', 'triste', 'hoy.']],
          german: 'Ana ist sehr sympathisch, aber heute ist sie traurig.',
          feedback: {
            rule: 'Charakter → `es simpática`; Stimmung heute → `está triste`.',
            why: '`estás`/`eres` sind du-Formen und passen nicht zu Ana.',
            avoid: 'Ein Satz kann beide Verben brauchen – prüfe jedes Adjektiv einzeln.',
          },
        },
        {
          id: 'es.g.ser-estar.L3.05',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser-estar'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Der Film ist langweilig und mir ist langweilig.',
          answers: [
            'La película es aburrida y estoy aburrido.',
            'La película es aburrida y estoy aburrida.',
            'La película es aburrida y yo estoy aburrido.',
            'La película es aburrida y yo estoy aburrida.',
          ],
          feedback: {
            rule: 'Eigenschaft des Films → `es aburrida`; dein Gefühl → `estoy aburrido/a`.',
            why: '„mir ist langweilig“ wird nicht mit `me` übersetzt, sondern mit `estar aburrido`.',
            avoid: 'Das Adjektiv passt sich an: `película` → aburrid**a**; du → aburrido/aburrida.',
          },
        },
      ],
    },
  ],
  related: ['es.g.ser', 'es.g.estar', 'es.g.adjectives'],
};
