import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.ser',
  courseId: 'es',
  stageId: 'stage0',
  order: 5,
  category: 'Verben',
  title: 'Ser – wer und was du bist',
  summary: 'Das Verb ser („sein“) für Name, Herkunft, Nationalität, Beruf und Eigenschaften – mit allen Formen.',
  keywords: [
    'ser', 'sein', 'soy', 'eres', 'es', 'somos', 'sois', 'son', 'sos', 'Herkunft', 'Nationalität', 'Beruf', 'Eigenschaft',
    'ich bin', 'du bist', 'ser de', 'Identität', 'unregelmäßiges Verb',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Das Deutsche hat ein Verb „sein“, das Spanische zwei: `ser` und `estar`. Hier geht es um `ser`. Mit `ser` sagst du, **wer oder was jemand ist** – Dinge, die zur Identität gehören.',
    },
    {
      type: 'conjugation',
      verb: 'ser',
      translation: 'sein',
      tense: 'Präsens (unregelmäßig)',
      rows: [
        { person: 'yo', form: 'soy' },
        { person: 'tú', form: 'eres' },
        { person: 'él / ella / usted', form: 'es' },
        { person: 'nosotros / nosotras', form: 'somos' },
        { person: 'vosotros / vosotras', form: 'sois', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'son' },
      ],
    },
    {
      type: 'table',
      title: 'Wofür man ser benutzt',
      headers: ['Verwendung', 'Beispiel', 'Deutsch'],
      rows: [
        ['Name / Identität', 'Soy Ana.', 'Ich bin Ana.'],
        ['Herkunft (ser de)', 'Soy de Alemania.', 'Ich komme aus Deutschland.'],
        ['Nationalität', 'Soy alemán / alemana.', 'Ich bin Deutscher / Deutsche.'],
        ['Beruf', 'Soy profesora.', 'Ich bin Lehrerin.'],
        ['Eigenschaft / Charakter', 'Carlos es simpático.', 'Carlos ist sympathisch.'],
        ['Beziehung', 'Es mi amiga.', 'Sie ist meine Freundin.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Soy', role: 'verb' },
        { text: ' de', role: 'preposition' },
        { text: ' Alemania', role: 'noun' },
        { text: ', pero ' },
        { text: 'mi', role: 'pronoun' },
        { text: ' madre', role: 'subject' },
        { text: ' es', role: 'verb' },
        { text: ' de', role: 'preposition' },
        { text: ' México', role: 'noun' },
        { text: '.' },
      ],
      german: 'Ich komme aus Deutschland, aber meine Mutter kommt aus Mexiko.',
    },
    {
      type: 'mistake',
      wrong: 'Soy un profesor.',
      right: 'Soy profesor.',
      why: 'Bei Berufen (und Nationalität, Religion) steht nach `ser` **kein** unbestimmter Artikel – genau wie im Deutschen „Ich bin Lehrer“.',
    },
    {
      type: 'text',
      md: 'Nationalitäten schreibt man **klein** und sie passen sich an: `alemán` → `alemana`, `español` → `española`, `mexicano` → `mexicana`. Endet die Nationalität auf -e oder -a, bleibt sie gleich: `estadounidense`, `belga`.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien fragst du Freunde: `¿De dónde sois?` („Woher kommt ihr?“) – `sois` gehört zu vosotros.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Lateinamerika: `¿De dónde son?` (ustedes). In Argentinien und Uruguay sagt man statt `tú eres` oft `vos sos`: `¿Vos sos de Buenos Aires?`',
    },
    { type: 'tip', md: '**ser = Steckbrief**: Name, Herkunft, Nationalität, Beruf, Charakter – alles, was in einem Personalausweis oder Profil stehen könnte.' },
    { type: 'audio', text: 'Hola, soy Ana. Soy de Berlín y soy profesora.', label: 'Vorstellung anhören' },
  ],
  examples: [
    {
      target: 'Soy Tom y soy de Hamburgo.',
      german: 'Ich bin Tom und ich komme aus Hamburg.',
      parts: [
        { text: 'Soy', role: 'verb' },
        { text: ' Tom', role: 'noun' },
        { text: ' y ' },
        { text: 'soy', role: 'verb' },
        { text: ' de', role: 'preposition' },
        { text: ' Hamburgo', role: 'noun' },
        { text: '.' },
      ],
    },
    { target: '¿De dónde eres?', german: 'Woher kommst du?' },
    { target: 'Mi amiga es mexicana.', german: 'Meine Freundin ist Mexikanerin.' },
    {
      target: 'Somos estudiantes.',
      german: 'Wir sind Studenten.',
      parts: [{ text: 'Somos', role: 'verb' }, { text: ' estudiantes', role: 'noun' }, { text: '.' }],
      note: 'Beruf/Rolle ohne Artikel.',
    },
    { target: 'El profesor es muy simpático.', german: 'Der Lehrer ist sehr sympathisch.' },
    { target: 'Usted es la señora Martín, ¿verdad?', german: 'Sie sind Frau Martín, oder?' },
    { target: '¿Sois hermanos?', german: 'Seid ihr Geschwister?', variant: 'es-ES' },
    { target: '¿Ustedes son hermanos?', german: 'Seid ihr Geschwister?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Soy de Austria.',
      german: 'Ich komme aus Österreich.',
      md: 'Für die Herkunft benutzt Spanisch `ser de` („sein von“), wo Deutsch „kommen aus“ sagt.',
    },
    {
      type: 'compare',
      target: 'Soy médico.',
      german: 'Ich bin Arzt.',
      md: 'Wie im Deutschen ohne Artikel. Achtung: Deutsche Englisch-Lerner sagen oft „a doctor“ – das überträgt sich gern ins Spanische.',
    },
    {
      type: 'compare',
      target: 'Es alemana.',
      german: 'Sie ist Deutsche.',
      md: 'Nationalitäten sind im Spanischen Adjektive und werden kleingeschrieben.',
    },
    {
      type: 'text',
      md: 'Wo Deutsch nur „sein“ hat, musst du im Spanischen entscheiden: Identität/Eigenschaft → `ser`; Ort und momentaner Zustand → `estar` (nächstes Thema).',
    },
  ],
  mistakes: [
    { wrong: 'Soy un profesor.', right: 'Soy profesor.', why: 'Beruf nach ser ohne unbestimmten Artikel.' },
    { wrong: 'Yo es de Berlín.', right: 'Soy de Berlín.', why: '`es` ist die Form für er/sie/Sie. Zu yo gehört `soy`.' },
    { wrong: 'Soy de la Alemania.', right: 'Soy de Alemania.', why: 'Die meisten Ländernamen stehen ohne Artikel.' },
    { wrong: 'Ella es alemán.', right: 'Ella es alemana.', why: 'Nationalitäten passen sich dem Geschlecht an: alemán → alemana.' },
    { wrong: 'Ustedes sois de Chile.', right: 'Ustedes son de Chile.', why: '`ustedes` verlangt die 3. Person Plural `son`; `sois` gehört nur zu vosotros.' },
  ],
  mnemonic: '**ser = Steckbrief**: Wer bin ich, woher komme ich, was mache ich, wie bin ich?',
  levels: [
    {
      level: 1,
      title: 'Formen kennen',
      exercises: [
        {
          id: 'es.g.ser.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ser'],
          difficulty: 1,
          instruction: 'Welche Form gehört zu welchem Pronomen?',
          pairs: [
            { left: 'yo', right: 'soy' },
            { left: 'tú', right: 'eres' },
            { left: 'ella', right: 'es' },
            { left: 'nosotros', right: 'somos' },
            { left: 'ellos', right: 'son' },
          ],
          feedback: {
            rule: 'ser: soy, eres, es, somos, (sois), son.',
            why: '`ser` ist unregelmäßig – die Formen muss man auswendig lernen.',
            avoid: 'Sprich die Reihe laut wie einen Rhythmus: „soy – eres – es – somos – son“.',
          },
        },
        {
          id: 'es.g.ser.L1.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 1,
          sentence: 'Hola, ___ Laura.',
          german: 'Hallo, ich bin Laura.',
          answers: [['soy']],
          bank: ['soy', 'eres', 'es'],
          feedback: {
            rule: 'yo → `soy`.',
            why: '`eres` = du bist, `es` = er/sie ist.',
            avoid: 'Sich vorstellen: `Soy …` – so einfach.',
          },
        },
        {
          id: 'es.g.ser.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.ser'],
          difficulty: 1,
          prompt: 'Wie fragst du jemanden, den du duzt, woher er kommt?',
          options: [
            { text: '¿De dónde eres?', why: 'Richtig: tú → `eres`.' },
            { text: '¿De dónde es?', why: 'Das ist die höfliche Frage (usted) oder „Woher kommt er/sie?“.' },
            { text: '¿Dónde eres?', why: 'Für die Herkunft braucht es `de`: „von wo“.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Herkunft: `¿De dónde + ser?` – beim Duzen `eres`.',
            why: 'Ohne `de` fehlt das „aus/von“.',
            avoid: 'Frage und Antwort spiegeln sich: `¿De dónde eres?` – `Soy de …`',
          },
        },
        {
          id: 'es.g.ser.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.ser'],
          difficulty: 1,
          audio: 'Somos de Colombia.',
          question: 'Wer kommt aus Kolumbien?',
          options: ['ich', 'du', 'wir', 'sie (Plural)'],
          answer: 2,
          feedback: {
            rule: '`somos` = wir sind.',
            why: '„ich“ wäre `soy`, „sie“ (Plural) wäre `son`.',
            avoid: 'Endung -mos = wir – bei fast allen Verben.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Sich und andere vorstellen',
      exercises: [
        {
          id: 'es.g.ser.L2.01',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 2,
          verb: 'ser',
          tense: 'Präsens',
          person: 'ellos',
          sentence: 'Ellos ___ de Perú.',
          answers: ['son'],
          feedback: {
            rule: 'ellos/ellas/ustedes → `son`.',
            why: '`somos` wäre „wir“, `es` nur eine Person.',
            avoid: 'Plural 3. Person endet fast immer auf -n.',
          },
        },
        {
          id: 'es.g.ser.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 2,
          sentence: 'Marta ___ de España. ___ española.',
          german: 'Marta kommt aus Spanien. Sie ist Spanierin.',
          answers: [['es'], ['Es']],
          feedback: {
            rule: 'Eine Person (ella) → `es`; das Pronomen `ella` kann im zweiten Satz entfallen.',
            why: '`son` wäre Plural, `eres` die du-Form.',
            avoid: 'Über eine andere Person sprechen → `es`.',
          },
        },
        {
          id: 'es.g.ser.L2.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Ich bin Lehrerin.',
          answers: ['Soy profesora.', 'Yo soy profesora.', 'Soy maestra.', 'Yo soy maestra.'],
          feedback: {
            rule: 'Beruf: `ser` + Beruf ohne Artikel, weibliche Form auf -a: `profesora`.',
            why: '`Soy una profesora` ist in diesem Kontext falsch; `estoy` passt nicht zu Berufen.',
            avoid: 'Beruf = Steckbrief = ser, kein un/una.',
          },
        },
        {
          id: 'es.g.ser.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 2,
          sentence: 'Mi padre es un médico.',
          german: 'Mein Vater ist Arzt.',
          answers: ['Mi padre es médico.'],
          feedback: {
            rule: 'Nach `ser` steht vor einem Beruf kein unbestimmter Artikel.',
            why: '`un médico` klingt, als würdest du ihn aus einer Gruppe herausgreifen („ein Arzt unter vielen“).',
            avoid: 'Denke deutsch: „Er ist Arzt“ – auch ohne „ein“.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Sicher kombinieren',
      exercises: [
        {
          id: 'es.g.ser.L3.01',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 3,
          tokens: ['Mi', 'amiga', 'es', 'alemana,', 'pero', 'es', 'de', 'Madrid.'],
          extra: ['alemán', 'está'],
          german: 'Meine Freundin ist Deutsche, aber sie ist aus Madrid.',
          feedback: {
            rule: 'Nationalität und Herkunft mit `ser`; die Nationalität passt sich an: `alemana`.',
            why: '`alemán` ist die männliche Form; `está` (estar) passt nicht zur Herkunft.',
            avoid: 'Frau → -a auch bei Nationalitäten.',
          },
        },
        {
          id: 'es.g.ser.L3.02',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 3,
          sentence: 'Ustedes sois de Argentina.',
          german: 'Sie sind aus Argentinien.',
          answers: ['Ustedes son de Argentina.'],
          feedback: {
            rule: '`ustedes` wird immer mit der 3. Person Plural konjugiert: `son`.',
            why: '`sois` gehört ausschließlich zu `vosotros`.',
            avoid: 'ustedes = Verb wie bei ellos.',
          },
        },
        {
          id: 'es.g.ser.L3.03',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 3,
          variant: 'es-ES',
          verb: 'ser',
          tense: 'Präsens',
          person: 'vosotros',
          sentence: '¿De dónde ___ vosotros?',
          answers: ['sois'],
          feedback: {
            rule: 'vosotros → `sois` (Spanien).',
            why: '`son` gehört zu ustedes, `somos` zu nosotros.',
            avoid: 'vosotros-Formen erkennst du an -is: `sois`, `habláis`, `estáis`.',
          },
        },
        {
          id: 'es.g.ser.L3.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.ser'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Wir sind Deutsche, aber wir kommen aus Wien.',
          answers: [
            'Somos alemanes, pero somos de Viena.',
            'Nosotros somos alemanes, pero somos de Viena.',
            'Somos alemanas, pero somos de Viena.',
            'Nosotras somos alemanas, pero somos de Viena.',
          ],
          feedback: {
            rule: 'Nationalität: `ser` + Adjektiv im Plural (`alemanes`/`alemanas`); Herkunft: `ser de` – nicht „venir“.',
            why: '„Deutsche“ ist hier Plural – `alemán` (Singular) passt nicht zu `somos`. Die Nationalität steht ohne Artikel.',
            avoid: 'alemán → alemanes (Akzent fällt weg, weil die Betonung jetzt regelgemäß auf der vorletzten Silbe liegt).',
          },
        },
        {
          id: 'es.g.ser.L3.05',
          type: 'speak',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.ser'],
          difficulty: 3,
          text: 'Soy de Alemania, pero mi madre es de Chile.',
          german: 'Ich komme aus Deutschland, aber meine Mutter kommt aus Chile.',
          phonetic: 'soi de a-le-MA-nja, PE-ro mi MA-dre es de TSCHI-le',
          ipa: '[ˈsoi̯ ðe a.leˈma.nja ˈpe.ɾo mi ˈma.ðɾe ez ðe ˈt͡ʃi.le]',
          feedback: {
            rule: '`soy` (ich) und `es` (sie) – beide Male Herkunft mit `ser de`.',
            why: 'Wer `soy` und `es` verwechselt, ändert die Person des Satzes.',
            avoid: 'Sprich die beiden Verben bewusst deutlich: „SOI“ – „ES“.',
          },
        },
      ],
    },
  ],
  related: ['es.g.estar', 'es.g.ser-estar', 'es.g.pronouns', 'es.g.adjectives'],
};
