import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.stem-change',
  courseId: 'es',
  stageId: 'a1',
  order: 9,
  category: 'Verben',
  title: 'Stammwechsel – e → ie, o → ue, e → i',
  summary: 'querer, poder, pedir & Co.: Der Stammvokal ändert sich, sobald er betont ist – in allen Formen außer nosotros und vosotros. Die „Stiefel“-Regel macht es sichtbar.',
  keywords: [
    'Stammwechsel', 'Stammvokalwechsel', 'Diphthong', 'Stiefel', 'Stiefelverben', 'e ie', 'o ue', 'e i', 'querer', 'quiero',
    'preferir', 'prefiero', 'empezar', 'poder', 'puedo', 'costar', 'cuesta', 'cuestan', 'dormir', 'volver', 'probarse',
    'pedir', 'pido', 'repetir', 'seguir', 'servir', 'jugar', 'juego', 'wollen', 'können', 'bestellen', 'lieber mögen', 'unregelmäßig',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Bei vielen Verben verändert sich der **Vokal im Stamm**, sobald er **betont** ist. Die Endungen bleiben ganz regelmäßig. Es gibt drei Gruppen: **e → ie** (`querer → quiero`), **o → ue** (`poder → puedo`) und **e → i** (`pedir → pido`, nur -ir-Verben).',
    },
    {
      type: 'conjugation',
      verb: 'querer',
      translation: 'wollen, mögen, lieben',
      tense: 'Präsens (e → ie)',
      rows: [
        { person: 'yo', form: 'quiero', ending: 'o' },
        { person: 'tú', form: 'quieres', ending: 'es' },
        { person: 'él / ella / usted', form: 'quiere', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'queremos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'queréis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'quieren', ending: 'en' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'poder',
      translation: 'können, dürfen',
      tense: 'Präsens (o → ue)',
      rows: [
        { person: 'yo', form: 'puedo', ending: 'o' },
        { person: 'tú', form: 'puedes', ending: 'es' },
        { person: 'él / ella / usted', form: 'puede', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'podemos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'podéis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'pueden', ending: 'en' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'pedir',
      translation: 'bestellen, bitten um',
      tense: 'Präsens (e → i)',
      rows: [
        { person: 'yo', form: 'pido', ending: 'o' },
        { person: 'tú', form: 'pides', ending: 'es' },
        { person: 'él / ella / usted', form: 'pide', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'pedimos', ending: 'imos' },
        { person: 'vosotros / vosotras', form: 'pedís', ending: 'ís', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'piden', ending: 'en' },
      ],
    },
    {
      type: 'table',
      title: 'Die Stiefel-Regel 👢 (● = Stammwechsel)',
      headers: ['Singular', 'Plural'],
      rows: [
        ['● yo quiero', '○ nosotros queremos'],
        ['● tú quieres', '○ vosotros queréis'],
        ['● él / ella / usted quiere', '● ellos / ellas / ustedes quieren'],
      ],
    },
    {
      type: 'text',
      md: 'Zieh eine Linie um alle ●: Die ganze linke Spalte plus unten rechts ergibt die Form eines **Stiefels**. Nur `nosotros` und `vosotros` stehen außerhalb – dort liegt die Betonung auf der Endung (`que-RE-mos`), also bleibt der Stamm unverändert.',
    },
    {
      type: 'table',
      title: 'Häufige Stammwechselverben',
      headers: ['Gruppe', 'Verben', 'Beispiel'],
      rows: [
        ['e → ie', 'querer, preferir, empezar, cerrar, pensar, entender', 'Prefiero el pescado.'],
        ['o → ue', 'poder, costar, volver, dormir, encontrar, probarse', '¿Cuánto cuesta?'],
        ['e → i (nur -ir)', 'pedir, repetir, seguir, servir', 'Pido la cuenta.'],
        ['u → ue (nur eins)', 'jugar', 'Juego al tenis.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'De primero', role: 'adverb' },
        { text: ' quiero', role: 'verb' },
        { text: ' la sopa', role: 'object' },
        { text: ' y' },
        { text: ' de segundo', role: 'adverb' },
        { text: ' pido', role: 'verb' },
        { text: ' el pescado', role: 'object' },
        { text: '.' },
      ],
      german: 'Als Vorspeise möchte ich die Suppe und als Hauptgericht bestelle ich den Fisch.',
    },
    {
      type: 'mistake',
      wrong: 'Nosotros quieremos una mesa.',
      right: 'Nosotros queremos una mesa.',
      why: 'Bei nosotros ist die Endung betont – kein Stammwechsel. Der Stiefel hört vor „wir“ auf.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'vosotros bleibt – wie nosotros – ohne Wechsel: `queréis`, `podéis`, `pedís`.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'In Argentinien und Uruguay (vos) ist die Endung betont, deshalb gibt es dort keinen Stammwechsel: `vos querés`, `podés`, `pedís`. Die Regel „betont = Wechsel“ gilt also auch hier.',
    },
    { type: 'tip', md: '**Betonter Stamm → Vokal wechselt.** Alles im Stiefel wechselt, nosotros und vosotros nicht.' },
    { type: 'audio', text: 'Quiero la sopa, puedo pagar con tarjeta y pido la cuenta. Nosotros queremos, podemos y pedimos.', label: 'Formen anhören' },
  ],
  examples: [
    {
      target: 'Quiero un café con leche.',
      german: 'Ich möchte einen Milchkaffee.',
      parts: [
        { text: 'Quiero', role: 'verb' },
        { text: ' un café con leche', role: 'object' },
        { text: '.' },
      ],
    },
    { target: '—¿Qué pides? —Pido la paella.', german: '„Was bestellst du?“ – „Ich bestelle die Paella.“' },
    { target: 'Prefiero el pescado.', german: 'Ich nehme lieber den Fisch.' },
    { target: '¿Puedes venir mañana?', german: 'Kannst du morgen kommen?' },
    { target: '¿Cuánto cuesta el menú del día?', german: 'Was kostet das Tagesmenü?' },
    {
      target: 'Nosotros queremos una mesa para cuatro.',
      german: 'Wir möchten einen Tisch für vier Personen.',
      parts: [
        { text: 'Nosotros', role: 'subject' },
        { text: ' queremos', role: 'verb' },
        { text: ' una mesa', role: 'object' },
        { text: ' para cuatro', role: 'preposition' },
        { text: '.' },
      ],
    },
    { target: '¿Puedo probarme la camisa?', german: 'Kann ich das Hemd anprobieren?' },
    { target: 'Los niños duermen mucho.', german: 'Die Kinder schlafen viel.' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'él pide – nosotros pedimos',
      german: 'er bestellt (nimmt) – wir bestellen (nehmen)',
      md: 'Auch im Deutschen wechselt manchmal der Stammvokal: „ich nehme, du **nimmst**, er **nimmt**, wir nehmen“. Spanisch macht das systematischer – nach der Stiefel-Regel.',
    },
    {
      type: 'compare',
      target: 'puedo – podemos',
      german: 'ich kann – wir können',
      md: 'Singular und „wir“ klingen im Deutschen bei den Modalverben ebenfalls verschieden – ein ähnliches Gefühl.',
    },
    {
      type: 'compare',
      target: 'Quiero un café, por favor.',
      german: 'Ich möchte einen Kaffee, bitte.',
      md: '`quiero` ist wörtlich „ich will“, klingt mit `por favor` im Restaurant aber ganz normal. Noch höflicher: `quisiera`.',
    },
    {
      type: 'compare',
      target: 'Prefiero el té.',
      german: 'Ich trinke lieber Tee.',
      md: 'Das deutsche „lieber“ steckt im Verb `preferir` – kein extra Wort nötig.',
    },
  ],
  mistakes: [
    { wrong: 'quieremos', right: 'queremos', why: 'nosotros/vosotros: Endung betont → kein Stammwechsel.' },
    { wrong: 'Yo podo', right: 'Yo puedo', why: 'o → ue in allen stammbetonten Formen: puedo, puedes, puede, pueden.' },
    { wrong: 'Yo pedo la cuenta.', right: 'Yo pido la cuenta.', why: 'pedir: e → i. Vorsicht: `pedo` ist ein derbes Wort für „Pups“!' },
    { wrong: 'Yo prefero', right: 'Yo prefiero', why: 'preferir wechselt beim zweiten e: pref**ie**ro.' },
    { wrong: 'Nosotros pidimos', right: 'Nosotros pedimos', why: 'Auch bei e → i bleibt nosotros ohne Wechsel.' },
  ],
  mnemonic: '**Alles im Stiefel wechselt – nosotros und vosotros bleiben draußen.** 👢',
  levels: [
    {
      level: 1,
      title: 'Die drei Gruppen',
      exercises: [
        {
          id: 'es.g.stem-change.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.stem-change'],
          difficulty: 1,
          instruction: 'Ordne jedem Infinitiv seine yo-Form zu.',
          pairs: [
            { left: 'querer', right: 'quiero' },
            { left: 'poder', right: 'puedo' },
            { left: 'pedir', right: 'pido' },
            { left: 'dormir', right: 'duermo' },
            { left: 'preferir', right: 'prefiero' },
            { left: 'volver', right: 'vuelvo' },
          ],
          feedback: {
            rule: 'e → ie (quiero, prefiero), o → ue (puedo, duermo, vuelvo), e → i (pido).',
            why: 'Die yo-Form liegt im Stiefel – sie wechselt immer.',
            avoid: 'Sprich die Form laut: Der betonte Vokal ist der, der sich ändert.',
          },
        },
        {
          id: 'es.g.stem-change.L1.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 1,
          verb: 'querer',
          tense: 'Präsens',
          person: 'tú',
          sentence: '¿Qué ___ tomar?',
          answers: ['quieres'],
          feedback: {
            rule: 'tú-Form von querer: `quieres` (e → ie).',
            why: '`queres` ohne i ist falsch; `quiere` ist er/sie.',
            avoid: 'tú liegt im Stiefel → Wechsel.',
          },
        },
        {
          id: 'es.g.stem-change.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.stem-change'],
          difficulty: 1,
          prompt: 'Welche Form hat **keinen** Stammwechsel?',
          options: [
            { text: 'podemos', why: 'Richtig: nosotros liegt außerhalb des Stiefels.' },
            { text: 'pueden', why: 'ellos/ustedes liegt im Stiefel → ue.' },
            { text: 'puedes', why: 'tú liegt im Stiefel → ue.' },
            { text: 'puedo', why: 'yo liegt im Stiefel → ue.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Nur nosotros und vosotros behalten den ursprünglichen Stammvokal.',
            why: 'Dort ist die Endung betont: po-DE-mos.',
            avoid: 'Stiefel zeichnen: wir und ihr stehen draußen.',
          },
        },
        {
          id: 'es.g.stem-change.L1.04',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 1,
          verb: 'pedir',
          tense: 'Präsens',
          person: 'yo',
          sentence: 'De segundo ___ el pescado.',
          answers: ['pido'],
          feedback: {
            rule: 'pedir: e → i → `pido`.',
            why: '`pedo` ist falsch (und ein derbes Wort), `pide` ist er/sie.',
            avoid: 'Im Restaurant: pido, pides, pide.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Die Stiefel-Regel anwenden',
      exercises: [
        {
          id: 'es.g.stem-change.L2.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.stem-change'],
          difficulty: 2,
          prompt: '„Wir wollen ins Kino gehen, aber Ana geht lieber an den Strand.“',
          options: [
            { text: 'Nosotros queremos ir al cine, pero Ana prefiere ir a la playa.', why: 'Richtig: nosotros ohne Wechsel, Ana (ella) mit Wechsel.' },
            { text: 'Nosotros quieremos ir al cine, pero Ana prefiere ir a la playa.', why: 'nosotros liegt außerhalb des Stiefels: `queremos`.' },
            { text: 'Nosotros queremos ir al cine, pero Ana prefere ir a la playa.', why: 'ella liegt im Stiefel: `prefiere`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'nosotros ohne Wechsel (`queremos`), ella mit Wechsel (`prefiere`).',
            why: '`quieremos` und `prefere` verletzen die Stiefel-Regel.',
            avoid: 'Prüfe die Person zuerst: Liegt sie im Stiefel?',
          },
        },
        {
          id: 'es.g.stem-change.L2.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 2,
          verb: 'poder',
          tense: 'Präsens',
          person: 'ustedes',
          sentence: '¿___ repetir, por favor?',
          answers: ['pueden'],
          feedback: {
            rule: 'ustedes → `pueden` (o → ue).',
            why: '`poden` gibt es nicht; ellos/ustedes liegt im Stiefel.',
            avoid: 'Unten rechts im Stiefel: pueden, quieren, piden.',
          },
        },
        {
          id: 'es.g.stem-change.L2.03',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 2,
          sentence: 'Nosotros podemos, pero ellos no poden.',
          german: 'Wir können, aber sie können nicht.',
          answers: ['Nosotros podemos, pero ellos no pueden.'],
          feedback: {
            rule: 'ellos → `pueden` (Stammwechsel), nosotros → `podemos` (kein Wechsel).',
            why: 'Die Form ohne Wechsel gilt nur für nosotros/vosotros.',
            avoid: 'Unten rechts gehört noch zum Stiefel.',
          },
        },
        {
          id: 'es.g.stem-change.L2.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.stem-change'],
          difficulty: 2,
          audio: '¿Cuánto cuestan los zapatos?',
          question: 'Was möchte die Person wissen?',
          options: ['den Preis der Schuhe', 'die Größe der Schuhe', 'die Farbe der Schuhe'],
          answer: 0,
          feedback: {
            rule: '`costar` (o → ue): `cuesta` (Singular), `cuestan` (Plural) – Frage nach dem Preis.',
            why: 'Größe wäre `talla`/`número`, Farbe `color`.',
            avoid: '¿Cuánto cuesta(n)? = Was kostet/kosten …?',
          },
        },
        {
          id: 'es.g.stem-change.L2.05',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 2,
          verb: 'dormir',
          tense: 'Präsens',
          person: 'él',
          sentence: 'Mi hijo ___ ocho horas.',
          answers: ['duerme'],
          feedback: {
            rule: 'dormir: o → ue → `duerme`.',
            why: '`dorme` ohne Wechsel ist falsch.',
            avoid: 'o → ue wie bei poder: puede – duerme.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Im Restaurant und im Alltag',
      exercises: [
        {
          id: 'es.g.stem-change.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Was bestellst du?',
          answers: ['¿Qué pides?', '¿Qué pides tú?', '¿Tú qué pides?'],
          feedback: {
            rule: '„bestellen“ im Restaurant = `pedir`; tú → `pides`.',
            why: '`¿Qué pedes?` ohne Wechsel ist falsch.',
            avoid: 'pedir: pido, pides, pide … pedimos.',
          },
        },
        {
          id: 'es.g.stem-change.L3.02',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Heute kann ich nicht.',
          answers: ['Hoy no puedo.', 'No puedo hoy.', 'Hoy yo no puedo.', 'Yo hoy no puedo.', 'Yo no puedo hoy.'],
          feedback: {
            rule: 'yo-Form von poder: `puedo`; die Verneinung `no` steht direkt vor dem Verb.',
            why: '`No podo` ohne Wechsel ist falsch.',
            avoid: 'Absage-Chunk: „Hoy no puedo, lo siento.“',
          },
        },
        {
          id: 'es.g.stem-change.L3.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 3,
          sentence: '¿___ probarme los zapatos? ¿Y cuánto ___?',
          german: 'Kann ich die Schuhe anprobieren? Und was kosten sie?',
          answers: [['Puedo'], ['cuestan']],
          bank: ['Puedo', 'Podo', 'cuestan', 'costan'],
          feedback: {
            rule: 'poder → `puedo`, costar → `cuestan` (beide o → ue).',
            why: '`podo` und `costan` ignorieren den Stammwechsel.',
            avoid: 'Einkaufs-Chunks: ¿Puedo probarme…? ¿Cuánto cuesta(n)?',
          },
        },
        {
          id: 'es.g.stem-change.L3.04',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stem-change'],
          difficulty: 3,
          tokens: ['¿', 'Prefieres', 'el', 'pescado', 'o', 'la', 'carne', '?'],
          alternatives: [['¿', 'Prefieres', 'la', 'carne', 'o', 'el', 'pescado', '?']],
          german: 'Nimmst du lieber den Fisch oder das Fleisch?',
          feedback: {
            rule: '`preferir` (e → ie): tú → `prefieres`.',
            why: 'Das deutsche „lieber“ ist schon im Verb enthalten.',
            avoid: 'prefiero, prefieres, prefiere … preferimos.',
          },
        },
        {
          id: 'es.g.stem-change.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.stem-change'],
          difficulty: 3,
          prompt: 'Du bist im Restaurant: Sag, was du möchtest, was du lieber magst, und bestelle etwas.',
          keywords: ['quiero', 'prefiero', 'pido', 'puedo', 'queremos', 'preferimos', 'pedimos', 'podemos'],
          minMatch: 2,
          sample: 'De primero quiero una ensalada. De segundo prefiero el pescado. ¿Puedo pedir agua también?',
          feedback: {
            rule: 'quiero, prefiero, pido, puedo – alle mit Stammwechsel.',
            why: 'Beim Sprechen rutschen leicht Formen ohne Wechsel heraus (`quero`, `podo`).',
            avoid: 'Sprich die yo-Formen vorher dreimal laut.',
          },
        },
      ],
    },
  ],
  related: ['es.g.tener', 'es.g.present-regular', 'es.g.yo-irregular'],
};
