import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.stress',
  courseId: 'es',
  stageId: 'stage0',
  order: 3,
  category: 'Aussprache & Schrift',
  title: 'Betonung & Akzentzeichen',
  summary: 'Drei Regeln verraten dir bei jedem Wort die betonte Silbe – der Akzentstrich (tilde) markiert nur die Ausnahmen.',
  keywords: [
    'Betonung', 'Akzent', 'Akzentzeichen', 'tilde', 'acento', 'Silbe', 'betonte Silbe', 'llana', 'aguda', 'esdrújula',
    'á', 'é', 'í', 'ó', 'ú', 'sí si', 'tú tu', 'él el', 'Fragewörter', 'Diphthong',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Im Spanischen verrät die Schreibung, welche Silbe betont wird. Du brauchst nur drei Regeln:\n- **Regel 1:** Endet ein Wort auf **Vokal, -n oder -s**, wird die **vorletzte** Silbe betont: `CA-sa`, `HA-blan`, `za-PA-tos`.\n- **Regel 2:** Endet es auf einen **anderen Konsonanten** (l, r, d, z …), wird die **letzte** Silbe betont: `ha-BLAR`, `ciu-DAD`, `es-pa-ÑOL`.\n- **Regel 3:** Weicht die Betonung davon ab, steht ein **Akzentstrich** auf der betonten Silbe: `ca-FÉ`, `ÁR-bol`, `te-LÉ-fo-no`.',
    },
    {
      type: 'table',
      title: 'Betonung auf einen Blick',
      headers: ['Wortende', 'Betonung ohne Akzent', 'Beispiele', 'Ausnahmen mit Akzent'],
      rows: [
        ['Vokal, -n, -s', 'vorletzte Silbe', 'casa, hablan, lunes', 'café, canción, inglés'],
        ['anderer Konsonant', 'letzte Silbe', 'hablar, ciudad, español', 'árbol, lápiz, fácil'],
        ['egal', 'drittletzte Silbe', '–', 'teléfono, música, sábado (immer mit Akzent)'],
      ],
    },
    {
      type: 'colored',
      parts: [{ text: 'ha' }, { text: 'blo', role: 'ending' }],
      german: 'hablo – „ich spreche“: Betonung auf HA (Regel 1)',
    },
    {
      type: 'colored',
      parts: [{ text: 'ha' }, { text: 'bló', role: 'ending' }],
      german: 'habló – „er/sie sprach“: der Akzent zieht die Betonung ans Ende',
    },
    {
      type: 'text',
      md: '`i` und `u` neben einem anderen Vokal bilden meist **eine** Silbe mit ihm: `bue-no`, `ciu-dad`, `Ale-ma-nia`. Ein Akzent auf i/u trennt sie: `dí-a`, `pa-ís`.',
    },
    {
      type: 'text',
      md: 'Manche kurzen Wörter tragen einen Akzent nur zur **Unterscheidung**: `tú` (du) – `tu` (dein), `él` (er) – `el` (der), `sí` (ja) – `si` (wenn/ob). **Fragewörter** haben immer einen Akzent: `¿qué?`, `¿cómo?`, `¿dónde?`, `¿cuándo?`.',
    },
    {
      type: 'mistake',
      wrong: 'telefono (ohne Akzent)',
      right: 'teléfono',
      why: 'Wird die drittletzte Silbe betont, steht **immer** ein Akzent. Ohne ihn müsste man „te-le-FO-no“ lesen.',
    },
    {
      type: 'tip',
      md: '**Vokal, n, s → vorletzte. Sonst → letzte. Der Strich schlägt alles.**',
    },
    { type: 'audio', text: 'Hablo español y bebo café.', label: 'Betonung im Satz hören' },
  ],
  examples: [
    { target: 'casa', german: 'Haus', note: '`CA-sa` – endet auf Vokal → vorletzte Silbe.' },
    { target: 'hablan', german: 'sie sprechen', note: '`HA-blan` – endet auf -n → vorletzte Silbe.' },
    { target: 'ciudad', german: 'Stadt', note: '`ciu-DAD` – endet auf -d → letzte Silbe; `ciu` ist eine Silbe.' },
    { target: 'café', german: 'Kaffee', note: '`ca-FÉ` – der Akzent zeigt die Ausnahme.' },
    { target: 'árbol', german: 'Baum', note: '`ÁR-bol` – endet auf -l, wird aber vorne betont → Akzent.' },
    { target: 'teléfono', german: 'Telefon', note: '`te-LÉ-fo-no` – drittletzte Silbe → immer Akzent.' },
    {
      target: 'Sí, él habla alemán.',
      german: 'Ja, er spricht Deutsch.',
      parts: [
        { text: 'Sí', role: 'adverb' },
        { text: ', ' },
        { text: 'él', role: 'subject' },
        { text: ' habla', role: 'verb' },
        { text: ' alemán', role: 'object' },
        { text: '.' },
      ],
      note: '`sí` = ja, `él` = er, `alemán` endet auf -n, wird aber hinten betont → Akzent.',
    },
  ],
  germanComparison: [
    {
      type: 'text',
      md: 'Im Deutschen musst du die Betonung jedes Wortes auswendig lernen – die Schrift verrät sie nicht („Ka-**nal**“ vs. „**Ka**-nu“). Im Spanischen reicht ein Blick auf das Wortende und den Akzentstrich.',
    },
    {
      type: 'compare',
      target: 'Alemania',
      german: 'Deutschland',
      md: '`a-le-MA-nia`: endet auf Vokal → vorletzte Silbe; `nia` zählt als **eine** Silbe.',
    },
    {
      type: 'compare',
      target: 'chocolate',
      german: 'Schokolade',
      md: '`cho-co-LA-te`: gleiche Betonung wie im Deutschen – aber das End-e wird klar gesprochen, nicht verschluckt.',
    },
    {
      type: 'compare',
      target: 'hotel',
      german: 'Hotel',
      md: '`ho-TEL`: endet auf -l → letzte Silbe (Regel 2). Das h bleibt stumm.',
    },
    {
      type: 'text',
      md: 'Deutsche verkürzen unbetonte Silben stark („**ha**-ben“ → „habm“). Im Spanischen bleiben auch unbetonte Silben vollständig und klar: `HA-blan`, nicht „HA-bln“.',
    },
  ],
  mistakes: [
    { wrong: 'telefono', right: 'teléfono', why: 'Betonung auf der drittletzten Silbe braucht immer einen Akzent.' },
    { wrong: 'hablo mit Betonung am Ende (ha-BLO)', right: 'HA-blo', why: 'Mit Endbetonung hört man `habló` („er/sie sprach“) – die Betonung ändert die Bedeutung.' },
    { wrong: '¿Como te llamas?', right: '¿Cómo te llamas?', why: 'Fragewörter tragen immer einen Akzent: `cómo`, `qué`, `dónde`, `cuándo`, `quién`.' },
    { wrong: 'Si, soy de Berlín.', right: 'Sí, soy de Berlín.', why: '`sí` mit Akzent heißt „ja“; `si` ohne Akzent heißt „wenn/ob“.' },
  ],
  mnemonic: '**Vokal, n, s → vorletzte. Sonst → letzte. Der Strich schlägt alles.**',
  levels: [
    {
      level: 1,
      title: 'Die betonte Silbe finden',
      exercises: [
        {
          id: 'es.g.stress.L1.01',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.stress'],
          difficulty: 1,
          prompt: 'Welche Silbe ist in `casa` betont?',
          options: [
            { text: 'CA', why: 'Richtig: endet auf Vokal → vorletzte Silbe.' },
            { text: 'SA', why: 'Die letzte Silbe wäre nur mit Akzent betont (`casá` gibt es nicht).' },
          ],
          answer: 0,
          feedback: {
            rule: 'Wörter auf Vokal, -n oder -s ohne Akzent: Betonung auf der vorletzten Silbe.',
            why: '`casa` endet auf -a und hat keinen Akzent.',
            avoid: 'Erst aufs Wortende schauen, dann auf einen möglichen Akzent.',
          },
        },
        {
          id: 'es.g.stress.L1.02',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.stress'],
          difficulty: 1,
          prompt: 'Welche Silbe ist in `hablar` betont?',
          options: [
            { text: 'HA', why: 'Das wäre richtig, wenn das Wort auf Vokal, -n oder -s endete.' },
            { text: 'BLAR', why: 'Richtig: endet auf -r → letzte Silbe.' },
          ],
          answer: 1,
          feedback: {
            rule: 'Wörter auf einen Konsonanten außer -n/-s werden ohne Akzent auf der letzten Silbe betont.',
            why: 'Alle Infinitive (-ar, -er, -ir) enden auf -r – sie sind daher immer endbetont.',
            avoid: 'Infinitiv = Betonung am Ende: `ha-BLAR`, `co-MER`, `vi-VIR`.',
          },
        },
        {
          id: 'es.g.stress.L1.03',
          type: 'listening',
          skills: ['listening', 'pronunciation'],
          topicIds: ['es.g.stress'],
          difficulty: 1,
          audio: 'teléfono',
          question: 'Welche Silbe von `teléfono` hörst du betont?',
          options: ['te', 'lé', 'fo', 'no'],
          answer: 1,
          feedback: {
            rule: 'Der Akzent zeigt die betonte Silbe: `te-LÉ-fo-no`.',
            why: 'Deutsche betonen das Wort gern wie „Te-le-FON“ – im Spanischen liegt die Betonung auf der drittletzten Silbe.',
            avoid: 'Wo ein Akzentstrich steht, dort liegt die Betonung. Immer.',
          },
        },
        {
          id: 'es.g.stress.L1.04',
          type: 'minimalPair',
          skills: ['listening', 'pronunciation'],
          topicIds: ['es.g.stress'],
          difficulty: 1,
          instruction: 'Welches Wort hörst du?',
          options: ['hablo', 'habló'],
          answer: 1,
          hint: 'Achte darauf, ob die erste Silbe (`HA-blo` = ich spreche) oder die letzte (`ha-BLÓ` = er sprach) stärker klingt.',
          feedback: {
            rule: 'Die Betonung kann die Bedeutung ändern: `hablo` (ich spreche) – `habló` (er/sie sprach).',
            why: 'Beide Wörter haben dieselben Laute; nur die betonte Silbe unterscheidet sie.',
            avoid: 'Sprich beide Formen laut nach und übertreibe die Betonung anfangs bewusst.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Regeln anwenden',
      exercises: [
        {
          id: 'es.g.stress.L2.01',
          type: 'mc',
          skills: ['pronunciation', 'writing'],
          topicIds: ['es.g.stress'],
          difficulty: 2,
          prompt: 'Die GROSS geschriebene Silbe ist betont. Welches Wort braucht deshalb einen Akzentstrich?',
          options: [
            { text: 'ca-FE', why: 'Richtig: endet auf Vokal, wird aber hinten betont → `café`.' },
            { text: 'CA-sa', why: 'Endet auf Vokal und wird vorletzt betont – regelgerecht, kein Akzent.' },
            { text: 'HA-blan', why: 'Endet auf -n, vorletzte Silbe betont – regelgerecht.' },
            { text: 'ciu-DAD', why: 'Endet auf -d, letzte Silbe betont – regelgerecht.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Einen Akzent bekommt nur, wer gegen Regel 1 oder 2 verstößt.',
            why: '`café` endet auf Vokal – normal wäre „CA-fe“. Da die letzte Silbe betont wird, braucht es den Strich.',
            avoid: 'Prüfe: Was sagt die Regel? Stimmt das mit der gehörten Betonung überein? Nein → Akzent.',
          },
        },
        {
          id: 'es.g.stress.L2.02',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.stress'],
          difficulty: 2,
          prompt: 'Wie wird `lunes` (Montag) betont?',
          options: [
            { text: 'LU-nes', why: 'Richtig: endet auf -s → vorletzte Silbe.' },
            { text: 'lu-NES', why: 'Dann müsste ein Akzent stehen: „lunés“.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Endung -s zählt wie ein Vokal: Betonung auf der vorletzten Silbe.',
            why: 'Das -s ist oft nur die Pluralendung – die Betonung des Wortes soll dadurch nicht springen (`ca-sa` → `ca-sas`).',
            avoid: 'Vokal, **n**, **s** – diese drei Enden gehören zusammen.',
          },
        },
        {
          id: 'es.g.stress.L2.03',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.stress'],
          difficulty: 2,
          instruction: 'Mit oder ohne Akzent? Ordne die Bedeutung zu.',
          pairs: [
            { left: 'sí', right: 'ja' },
            { left: 'si', right: 'wenn / ob' },
            { left: 'tú', right: 'du' },
            { left: 'tu', right: 'dein' },
            { left: 'él', right: 'er' },
            { left: 'el', right: 'der' },
          ],
          feedback: {
            rule: 'Der diakritische Akzent unterscheidet gleich klingende Wörter: `sí/si`, `tú/tu`, `él/el`.',
            why: 'Aussprache identisch – nur die Schreibung zeigt die Bedeutung.',
            avoid: 'Faustregel: Das Pronomen bzw. das „Ja“ trägt den Akzent.',
          },
        },
        {
          id: 'es.g.stress.L2.04',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.stress'],
          difficulty: 2,
          instruction: 'Hör zu und schreib das Wort – mit Akzent, falls nötig.',
          audio: 'árbol',
          german: 'Baum',
          answers: ['árbol'],
          feedback: {
            rule: '`ÁR-bol` endet auf -l, wird aber vorne betont → Akzent auf dem a.',
            why: 'Ohne Akzent läse man nach Regel 2 „ar-BOL“.',
            avoid: 'Endet ein Wort auf Konsonant (außer n/s) und klingt vorne betont, braucht es einen Strich.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Akzente sicher setzen',
      exercises: [
        {
          id: 'es.g.stress.L3.01',
          type: 'mc',
          skills: ['pronunciation', 'reading'],
          topicIds: ['es.g.stress'],
          difficulty: 3,
          prompt: 'Welches Wort wird auf der **letzten** Silbe betont?',
          options: [
            { text: 'examen', why: '`e-XA-men` – endet auf -n, vorletzte Silbe.' },
            { text: 'lápiz', why: '`LÁ-piz` – der Akzent zieht die Betonung nach vorn.' },
            { text: 'español', why: 'Richtig: `es-pa-ÑOL` – endet auf -l, ohne Akzent → letzte Silbe.' },
            { text: 'música', why: '`MÚ-si-ca` – drittletzte Silbe.' },
          ],
          answer: 2,
          feedback: {
            rule: 'Konsonant außer n/s am Ende + kein Akzent = letzte Silbe betont.',
            why: '`examen` endet auf -n (→ vorletzte), `lápiz` und `música` haben einen Akzent weiter vorn.',
            avoid: 'Reihenfolge beim Prüfen: 1. Akzent? 2. Wortende?',
          },
        },
        {
          id: 'es.g.stress.L3.02',
          type: 'mc',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.stress'],
          difficulty: 3,
          prompt: 'Welcher Mini-Dialog ist richtig geschrieben? („Sprichst du Spanisch?“ – „Ja, ein bisschen.“)',
          options: [
            { text: '—¿Hablas español? —Sí, un poco.', why: 'Richtig: `sí` (ja) trägt einen Akzent, `español` endet auf -l und ist regelmäßig endbetont.' },
            { text: '—¿Hablas español? —Si, un poco.', why: '`si` ohne Akzent heißt „wenn/ob“ – hier ist aber „ja“ gemeint.' },
            { text: '—¿Hablas español? —Sí, ún poco.', why: '`un` ist einsilbig und unbetont – einsilbige Wörter bekommen nur zur Unterscheidung einen Akzent.' },
          ],
          answer: 0,
          feedback: {
            rule: '„Ja“ heißt `sí` – mit Akzent. Einsilbige Wörter wie `un` bekommen sonst keinen Akzent.',
            why: '`si` ohne Akzent bedeutet „wenn“ oder „ob“.',
            avoid: 'Das bejahende `sí` ist betont und bekommt deshalb den Strich.',
          },
        },
        {
          id: 'es.g.stress.L3.03',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.stress'],
          difficulty: 3,
          instruction: 'Hör zu und schreib den Satz.',
          audio: '¿Dónde está el teléfono?',
          german: 'Wo ist das Telefon?',
          answers: ['¿Dónde está el teléfono?'],
          feedback: {
            rule: '`dónde` (Fragewort), `está` (endbetont auf Vokal) und `teléfono` (drittletzte Silbe) brauchen einen Akzent; `el` (Artikel) nicht.',
            why: 'Jeder der drei Akzente zeigt eine Abweichung von den Grundregeln bzw. ein Fragewort.',
            avoid: 'Fragewörter immer mit Akzent; Wörter auf -é/-á mit Endbetonung ebenso.',
          },
        },
        {
          id: 'es.g.stress.L3.04',
          type: 'speak',
          skills: ['pronunciation', 'speaking'],
          topicIds: ['es.g.stress'],
          difficulty: 3,
          text: 'Mi teléfono está en el árbol.',
          german: 'Mein Telefon ist im Baum.',
          phonetic: 'mi te-LE-fo-no es-TA en el AR-bol',
          ipa: '[mi teˈle.fo.no esˈta en el ˈaɾ.βol]',
          pronItemId: 'es.p.stress.telefono',
          feedback: {
            rule: 'Jeder Akzentstrich zeigt die betonte Silbe: te-LÉ-fo-no, es-TÁ, ÁR-bol.',
            why: 'Falsche Betonung macht Wörter schwer erkennbar – oft schwerer als ein falscher Laut.',
            avoid: 'Tippe beim Sprechen auf jede betonte Silbe leicht mit dem Finger.',
          },
        },
      ],
    },
  ],
  related: ['es.g.alphabet-sounds', 'es.g.questions'],
};
