import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.tener',
  courseId: 'es',
  stageId: 'a1',
  order: 1,
  category: 'Verben',
  title: 'Tener – haben, Alter & „müssen“',
  summary: 'tener für Besitz, Familie und Alter, für Hunger, Durst und Kälte – und tener que für „müssen“.',
  keywords: [
    'tener', 'haben', 'tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'tienen', 'Alter', 'wie alt', 'años', 'tener que', 'müssen',
    'Hunger', 'Durst', 'kalt', 'warm', 'Angst', 'hambre', 'sed', 'frío', 'calor', 'sueño', 'miedo', 'unregelmäßig', 'Stammwechsel',
  ],
  explanation: [
    {
      type: 'conjugation',
      verb: 'tener',
      translation: 'haben',
      tense: 'Präsens (unregelmäßig: yo auf -go, e → ie)',
      rows: [
        { person: 'yo', form: 'tengo', ending: 'go' },
        { person: 'tú', form: 'tienes', ending: 'es' },
        { person: 'él / ella / usted', form: 'tiene', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'tenemos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'tenéis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'tienen', ending: 'en' },
      ],
    },
    {
      type: 'text',
      md: '`tener` ist unregelmäßig, aber mit System: Die yo-Form endet auf **-go** (`tengo`). In den Formen, bei denen der Stamm betont ist, wird **e zu ie** (`tienes`, `tiene`, `tienen`). Bei nosotros und vosotros bleibt das e (`tenemos`, `tenéis`).',
    },
    {
      type: 'table',
      title: 'Wofür man tener braucht',
      headers: ['Verwendung', 'Spanisch', 'Deutsch'],
      rows: [
        ['Besitz, Familie', 'Tengo un perro y dos hermanos.', 'Ich habe einen Hund und zwei Geschwister.'],
        ['Alter', 'Tengo treinta años.', 'Ich bin dreißig (Jahre alt).'],
        ['Körpergefühl', 'Tengo hambre / sed / frío / calor / sueño.', 'Ich habe Hunger / Durst; mir ist kalt / warm; ich bin müde.'],
        ['Gefühl', 'Tengo miedo.', 'Ich habe Angst.'],
        ['Pflicht', 'Tengo que trabajar.', 'Ich muss arbeiten.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Tengo', role: 'verb' },
        { text: ' hambre', role: 'object' },
        { text: ', pero ' },
        { text: 'tengo que', role: 'verb' },
        { text: ' trabajar', role: 'verb' },
        { text: '.' },
      ],
      german: 'Ich habe Hunger, aber ich muss arbeiten.',
    },
    {
      type: 'text',
      md: 'In den Gefühls-Ausdrücken steht ein **Nomen**, deshalb verstärkt man mit `mucho/mucha` (nicht mit `muy`): `Tengo mucho frío`, `mucho calor`, `mucho sueño`, `mucho miedo` – aber `mucha hambre`, `mucha sed`, weil `hambre` und `sed` weiblich sind.',
    },
    {
      type: 'mistake',
      wrong: 'Soy treinta años.',
      right: 'Tengo treinta años.',
      why: 'Das Alter „hat“ man im Spanischen: `tener … años`. `ser` + Zahl ergibt keinen Sinn.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: `¿Tenéis hambre?` („Habt ihr Hunger?“ – vosotros).',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: `¿Tienen hambre?` (ustedes). In Argentinien und Uruguay sagt man `vos tenés` statt `tú tienes`.',
    },
    { type: 'tip', md: '**Alter, Hunger, Durst und Kälte „hat“ man auf Spanisch.** Und „müssen“ ist `tener que` + Infinitiv.' },
    { type: 'audio', text: 'Tengo treinta años, tengo dos hermanos y ahora tengo mucha hambre.', label: 'Beispiel anhören' },
  ],
  examples: [
    { target: 'Tengo dos hermanos.', german: 'Ich habe zwei Geschwister.' },
    {
      target: '—¿Cuántos años tienes? —Tengo veintiocho años.',
      german: '„Wie alt bist du?“ – „Ich bin achtundzwanzig.“',
    },
    {
      target: 'Tenemos mucha hambre.',
      german: 'Wir haben großen Hunger.',
      parts: [
        { text: 'Tenemos', role: 'verb' },
        { text: ' mucha', role: 'adjective' },
        { text: ' hambre', role: 'object' },
        { text: '.' },
      ],
    },
    { target: '¿Tienes frío?', german: 'Ist dir kalt?' },
    { target: 'Mi hija tiene miedo de los perros.', german: 'Meine Tochter hat Angst vor Hunden.' },
    {
      target: 'Hoy tengo que trabajar.',
      german: 'Heute muss ich arbeiten.',
      parts: [
        { text: 'Hoy', role: 'adverb' },
        { text: ' tengo que', role: 'verb' },
        { text: ' trabajar', role: 'verb' },
        { text: '.' },
      ],
    },
    { target: '¿Tenéis tiempo mañana?', german: 'Habt ihr morgen Zeit?', variant: 'es-ES' },
    { target: '¿Tienen tiempo mañana?', german: 'Habt ihr morgen Zeit?', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Tengo treinta años.',
      german: 'Ich bin dreißig Jahre alt.',
      md: 'Deutsch: „sein“ + alt. Spanisch: Jahre „haben“.',
    },
    {
      type: 'compare',
      target: 'Tengo frío.',
      german: 'Mir ist kalt.',
      md: 'Deutsch: „mir ist …“. Spanisch: „ich habe Kälte“. `Estoy frío` hieße „Ich bin (vom Körper her) kalt“ – z. B. meine Hände fühlen sich kalt an.',
    },
    {
      type: 'compare',
      target: 'Tengo hambre.',
      german: 'Ich habe Hunger.',
      md: 'Hier sind sich beide Sprachen einig.',
    },
    {
      type: 'compare',
      target: 'Tengo que estudiar.',
      german: 'Ich muss lernen.',
      md: 'Es gibt kein eigenes Modalverb für „müssen“ im Alltag: `tener que` + Infinitiv.',
    },
  ],
  mistakes: [
    { wrong: 'Soy treinta años.', right: 'Tengo treinta años.', why: 'Alter mit tener.' },
    { wrong: 'Estoy frío.', right: 'Tengo frío.', why: 'Kälteempfinden: tener frío. `estar frío` beschreibt, dass etwas kalt ist (die Suppe, die Hände).' },
    { wrong: 'Tengo mucho hambre.', right: 'Tengo mucha hambre.', why: '`hambre` ist weiblich (`el hambre` wegen des betonten a-, aber `mucha hambre`).' },
    { wrong: 'Tengo que trabajo.', right: 'Tengo que trabajar.', why: 'Nach `tener que` steht der Infinitiv.' },
    { wrong: 'Ella tene un gato.', right: 'Ella tiene un gato.', why: 'In den stammbetonten Formen wird e zu ie.' },
  ],
  mnemonic: '**Alter, Hunger, Durst und Kälte „hat“ man – und „müssen“ heißt tener que.**',
  levels: [
    {
      level: 1,
      title: 'Formen und Grundbedeutung',
      exercises: [
        {
          id: 'es.g.tener.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.tener'],
          difficulty: 1,
          instruction: 'Ordne Form und Bedeutung zu.',
          pairs: [
            { left: 'tengo', right: 'ich habe' },
            { left: 'tienes', right: 'du hast' },
            { left: 'tiene', right: 'er/sie hat' },
            { left: 'tenemos', right: 'wir haben' },
            { left: 'tienen', right: 'sie haben' },
          ],
          feedback: {
            rule: 'tener: tengo, tienes, tiene, tenemos, (tenéis), tienen.',
            why: 'Bei nosotros bleibt das e ohne i: `tenemos`.',
            avoid: 'Stammbetont → ie; endungsbetont → e.',
          },
        },
        {
          id: 'es.g.tener.L1.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 1,
          verb: 'tener',
          tense: 'Präsens',
          person: 'yo',
          sentence: 'Yo ___ un perro.',
          answers: ['tengo'],
          feedback: {
            rule: 'yo → `tengo` (unregelmäßig mit -g-).',
            why: '„teno“ oder „tieno“ gibt es nicht.',
            avoid: 'Merke die -go-Familie: tengo, vengo, hago, pongo, salgo.',
          },
        },
        {
          id: 'es.g.tener.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.tener'],
          difficulty: 1,
          prompt: '„Ich bin 25 Jahre alt.“',
          options: [
            { text: 'Tengo veinticinco años.', why: 'Richtig: Alter mit tener.' },
            { text: 'Soy veinticinco años.', why: '`ser` passt nicht zum Alter.' },
            { text: 'Estoy veinticinco años.', why: '`estar` passt nicht zum Alter.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Alter: `tener` + Zahl + `años`.',
            why: 'Das deutsche „bin“ verleitet zu ser/estar.',
            avoid: 'Denke an die Frage: `¿Cuántos años tienes?` – „Wie viele Jahre hast du?“',
          },
        },
        {
          id: 'es.g.tener.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.tener'],
          difficulty: 1,
          audio: 'Tengo mucha sed.',
          question: 'Was braucht die Person?',
          options: ['etwas zu trinken', 'etwas zu essen', 'Schlaf'],
          answer: 0,
          feedback: {
            rule: '`tener sed` = Durst haben.',
            why: 'Essen wäre `hambre`, Schlaf `sueño`.',
            avoid: 'sed – „Durst“: beide kurz und trocken.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'tener-Ausdrücke',
      exercises: [
        {
          id: 'es.g.tener.L2.01',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 2,
          verb: 'tener',
          tense: 'Präsens',
          person: 'ella',
          sentence: 'Ella ___ dos hijos.',
          answers: ['tiene'],
          feedback: {
            rule: 'él/ella → `tiene` (e → ie).',
            why: '„tene“ ist falsch – der betonte Stamm bekommt ie.',
            avoid: 'tiene ≈ „TJE-ne“ – das ie hört man deutlich.',
          },
        },
        {
          id: 'es.g.tener.L2.02',
          type: 'matchPairs',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.tener'],
          difficulty: 2,
          instruction: 'Ordne die Ausdrücke zu.',
          pairs: [
            { left: 'tener hambre', right: 'Hunger haben' },
            { left: 'tener sed', right: 'Durst haben' },
            { left: 'tener frío', right: 'frieren' },
            { left: 'tener calor', right: 'es heiß haben (mir ist heiß)' },
            { left: 'tener sueño', right: 'schläfrig sein' },
            { left: 'tener miedo', right: 'Angst haben' },
          ],
          feedback: {
            rule: 'Körper- und Gefühlszustände: tener + Nomen.',
            why: 'Im Deutschen stehen hier oft „sein“ oder „mir ist …“.',
            avoid: 'Lerne diese sechs als feste Paare.',
          },
        },
        {
          id: 'es.g.tener.L2.03',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 2,
          sentence: 'Tengo ___ hambre.',
          german: 'Ich habe großen Hunger.',
          answers: [['mucha']],
          bank: ['mucho', 'mucha', 'muy'],
          feedback: {
            rule: '`hambre` ist ein weibliches Nomen → `mucha hambre`.',
            why: '`muy` steht vor Adjektiven, nicht vor Nomen; `mucho` wäre männlich.',
            avoid: 'hambre und sed → mucha; frío, calor, sueño, miedo → mucho.',
          },
        },
        {
          id: 'es.g.tener.L2.04',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Mir ist kalt.',
          answers: ['Tengo frío.', 'Yo tengo frío.'],
          feedback: {
            rule: '„Mir ist kalt“ = `Tengo frío`.',
            why: '„Estoy frío“ bedeutet etwas anderes, „Me es frío“ gibt es nicht.',
            avoid: 'Deutsches „mir ist kalt/warm“ → tener frío/calor.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'tener que und freie Anwendung',
      exercises: [
        {
          id: 'es.g.tener.L3.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 3,
          sentence: 'Mañana ___ ___ trabajar.',
          german: 'Morgen muss ich arbeiten.',
          answers: [['tengo'], ['que']],
          feedback: {
            rule: '„müssen“ = `tener que` + Infinitiv: `tengo que trabajar`.',
            why: 'Ohne `que` fehlt das Verbindungswort; „debo“ wäre „sollen/müssen (moralisch)“.',
            avoid: 'tener **que** – das que nie vergessen.',
          },
        },
        {
          id: 'es.g.tener.L3.02',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 3,
          sentence: 'Mi abuelo es ochenta años.',
          german: 'Mein Großvater ist achtzig Jahre alt.',
          answers: ['Mi abuelo tiene ochenta años.'],
          feedback: {
            rule: 'Alter → `tener … años`.',
            why: 'Das deutsche „ist … alt“ lässt sich nicht wörtlich übertragen.',
            avoid: 'Zahl + años → davor steht immer eine Form von tener.',
          },
        },
        {
          id: 'es.g.tener.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Wir müssen Spanisch lernen.',
          answers: [
            'Tenemos que aprender español.',
            'Tenemos que estudiar español.',
            'Nosotros tenemos que aprender español.',
            'Nosotros tenemos que estudiar español.',
            'Nosotras tenemos que aprender español.',
            'Nosotras tenemos que estudiar español.',
          ],
          feedback: {
            rule: '`tenemos que` + Infinitiv.',
            why: '„Tenemos aprender“ (ohne que) oder „Tenemos que aprendemos“ (konjugiert) sind falsch.',
            avoid: 'Nur `tener` wird konjugiert, das zweite Verb bleibt im Infinitiv.',
          },
        },
        {
          id: 'es.g.tener.L3.04',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.tener'],
          difficulty: 3,
          variant: 'es-ES',
          verb: 'tener',
          tense: 'Präsens',
          person: 'vosotros',
          sentence: '¿___ hambre, chicos?',
          answers: ['tenéis'],
          feedback: {
            rule: 'vosotros → `tenéis` (ohne ie, Endung betont).',
            why: '„tienéis“ ist falsch: Wenn die Endung betont ist, bleibt das e.',
            avoid: 'nosotros/vosotros: kein ie – tenemos, tenéis.',
          },
        },
        {
          id: 'es.g.tener.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.tener'],
          difficulty: 3,
          prompt: 'Stell dich kurz vor: Wie alt bist du? Hast du Geschwister oder ein Haustier? Was musst du heute noch machen?',
          keywords: ['tengo', 'años', 'hermano', 'hermana', 'hermanos', 'perro', 'gato', 'que'],
          minMatch: 3,
          sample: 'Tengo treinta y cuatro años. Tengo una hermana y un gato. Hoy tengo que trabajar.',
          feedback: {
            rule: 'Alter, Familie, Haustiere und Pflichten – alles mit `tener`.',
            why: 'Typisch ist `soy … años` – im Spanischen „hat“ man sein Alter.',
            avoid: 'Starte jeden Satz mit `Tengo …`.',
          },
        },
      ],
    },
  ],
  related: ['es.g.numbers', 'es.g.possessives', 'es.g.ser'],
};
