import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.time-dates',
  courseId: 'es',
  stageId: 'a1',
  order: 12,
  category: 'Zeit & Datum',
  title: 'Wochentage, Monate & Datum',
  summary: 'el lunes (am Montag) und los lunes (montags), Monate und Tage klein geschrieben, das Datum mit el + Zahl + de – und wie man nach dem Tag und dem Geburtstag fragt.',
  keywords: [
    'Wochentage', 'Monate', 'Datum', 'Jahreszeiten', 'Kalender', 'Geburtstag', 'cumpleaños', 'fecha', 'qué día', 'am Montag', 'montags',
    'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo', 'fin de semana', 'enero', 'febrero', 'marzo', 'abril',
    'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre', 'primavera', 'verano', 'otoño', 'invierno',
  ],
  explanation: [
    {
      type: 'table',
      title: 'Die Wochentage (alle männlich, klein geschrieben)',
      headers: ['Spanisch', 'Deutsch', 'Plural'],
      rows: [
        ['el lunes', 'Montag', 'los lunes'],
        ['el martes', 'Dienstag', 'los martes'],
        ['el miércoles', 'Mittwoch', 'los miércoles'],
        ['el jueves', 'Donnerstag', 'los jueves'],
        ['el viernes', 'Freitag', 'los viernes'],
        ['el sábado', 'Samstag', 'los sábados'],
        ['el domingo', 'Sonntag', 'los domingos'],
      ],
    },
    {
      type: 'text',
      md: '**Kein „en“ vor Wochentagen!** Der Artikel übernimmt die Rolle von „am“: `el lunes` = am Montag (einmalig). `los lunes` = montags, jeden Montag (regelmäßig). Nur nach `hoy es` / `mañana es` fällt der Artikel weg: `Hoy es lunes.`',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Los viernes', role: 'adverb' },
        { text: ' voy', role: 'verb' },
        { text: ' al gimnasio', role: 'preposition' },
        { text: ', pero ' },
        { text: 'este viernes', role: 'adverb' },
        { text: ' no', role: 'negation' },
        { text: ' puedo', role: 'verb' },
        { text: '.' },
      ],
      german: 'Freitags gehe ich ins Fitnessstudio, aber diesen Freitag kann ich nicht.',
    },
    {
      type: 'table',
      title: 'Monate und Jahreszeiten (Nordhalbkugel)',
      headers: ['Jahreszeit', 'Monate', 'Deutsch'],
      rows: [
        ['el invierno', 'diciembre, enero, febrero', 'Winter: Dezember, Januar, Februar'],
        ['la primavera', 'marzo, abril, mayo', 'Frühling: März, April, Mai'],
        ['el verano', 'junio, julio, agosto', 'Sommer: Juni, Juli, August'],
        ['el otoño', 'septiembre, octubre, noviembre', 'Herbst: September, Oktober, November'],
      ],
    },
    {
      type: 'text',
      md: 'Monate und Jahreszeiten stehen mit **en**: `en mayo` (im Mai), `en verano` (im Sommer). Das **Datum** bildest du mit **el + Grundzahl + de + Monat**: `el cinco de mayo` (der/am 5. Mai). Keine Ordnungszahl, kein Punkt, der Monat klein. Das Jahr hängst du mit `de` an: `el 5 de mayo de 2026`.',
    },
    {
      type: 'table',
      title: 'Fragen und Antworten',
      headers: ['Frage', 'Antwort', 'Deutsch'],
      rows: [
        ['¿Qué día es hoy?', 'Hoy es miércoles.', 'Welcher Tag ist heute? – Heute ist Mittwoch.'],
        ['¿Qué fecha es hoy?', 'Hoy es 12 de octubre.', 'Welches Datum ist heute? – Heute ist der 12. Oktober.'],
        ['¿Cuándo es tu cumpleaños?', 'Es el 3 de marzo.', 'Wann hast du Geburtstag? – Am 3. März.'],
        ['¿Cuándo es la fiesta?', 'Es el sábado.', 'Wann ist die Party? – Am Samstag.'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Voy al cine en el lunes.',
      right: 'Voy al cine el lunes.',
      why: 'Vor Wochentagen steht kein `en` – nur der Artikel: `el lunes` = am Montag.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'Spanien: Für den Ersten des Monats sagt man meist `el uno de mayo`. Nach dem Datum fragt man auch `¿A qué estamos hoy?` – `Estamos a 3 de marzo.`',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Lateinamerika: Für den Ersten ist `el primero de mayo` üblich (`el uno` ist auch möglich). Auf der Südhalbkugel (z. B. Argentinien, Chile) ist Sommer von Dezember bis Februar.',
    },
    { type: 'tip', md: '**Tag → el (kein en). Monat und Jahreszeit → en. Datum → el + Zahl + de + Monat.** Und alles klein!' },
    { type: 'audio', text: 'Hoy es jueves, catorce de noviembre. Mi cumpleaños es el tres de marzo, en primavera.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: 'El lunes tengo clase de español.',
      german: 'Am Montag habe ich Spanischunterricht.',
      parts: [
        { text: 'El lunes', role: 'adverb' },
        { text: ' tengo', role: 'verb' },
        { text: ' clase de español', role: 'object' },
        { text: '.' },
      ],
    },
    { target: 'Los sábados voy al mercado.', german: 'Samstags gehe ich auf den Markt.' },
    { target: '—¿Qué día es hoy? —Hoy es miércoles.', german: '„Welcher Tag ist heute?“ – „Heute ist Mittwoch.“' },
    {
      target: 'Mi cumpleaños es el doce de octubre.',
      german: 'Mein Geburtstag ist am 12. Oktober.',
      parts: [
        { text: 'Mi cumpleaños', role: 'subject' },
        { text: ' es', role: 'verb' },
        { text: ' el doce', role: 'other' },
        { text: ' de octubre', role: 'preposition' },
        { text: '.' },
      ],
    },
    { target: 'En verano vamos a la playa.', german: 'Im Sommer fahren wir ans Meer.' },
    { target: 'La fiesta es el viernes, el tres de junio.', german: 'Die Party ist am Freitag, dem 3. Juni.' },
    { target: 'El uno de enero no trabajo.', german: 'Am 1. Januar arbeite ich nicht.', variant: 'es-ES' },
    { target: 'El primero de enero no trabajo.', german: 'Am 1. Januar arbeite ich nicht.', variant: 'es-LA' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'el lunes',
      german: 'am Montag',
      md: 'Kein `en`: Der bestimmte Artikel bedeutet hier schon „am“.',
    },
    {
      type: 'compare',
      target: 'los lunes',
      german: 'montags / jeden Montag',
      md: 'Der Plural-Artikel macht aus einem Termin eine Gewohnheit. Die Form `lunes` bleibt gleich.',
    },
    {
      type: 'compare',
      target: 'el 5 de mayo',
      german: 'der 5. Mai',
      md: 'Grundzahl statt Ordnungszahl, `de` vor dem Monat, Monat klein geschrieben.',
    },
    {
      type: 'compare',
      target: 'en mayo · en verano',
      german: 'im Mai · im Sommer',
      md: 'Bei Monaten und Jahreszeiten funktioniert es wie im Deutschen: `en` = „im“.',
    },
  ],
  mistakes: [
    { wrong: 'en el lunes', right: 'el lunes', why: 'Wochentage ohne `en`.' },
    { wrong: 'el 3 marzo', right: 'el 3 de marzo', why: 'Zwischen Tag und Monat steht `de`.' },
    { wrong: 'el tercero de marzo', right: 'el tres de marzo', why: 'Im Datum stehen Grundzahlen (einzige Ausnahme: `el primero`).' },
    { wrong: 'Lunes, Mayo', right: 'lunes, mayo', why: 'Wochentage und Monate werden klein geschrieben.' },
    { wrong: 'los luneses', right: 'los lunes', why: 'Tage auf -s bleiben im Plural gleich; nur `sábados`, `domingos` bekommen ein -s.' },
  ],
  mnemonic: '**Tag → el, Monat → en, Datum → el + Zahl + de.** Und alles klein!',
  levels: [
    {
      level: 1,
      title: 'Tage, Monate, Jahreszeiten',
      exercises: [
        {
          id: 'es.g.time-dates.L1.01',
          type: 'matchPairs',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.time-dates'],
          difficulty: 1,
          instruction: 'Ordne die Wochentage zu.',
          pairs: [
            { left: 'lunes', right: 'Montag' },
            { left: 'martes', right: 'Dienstag' },
            { left: 'miércoles', right: 'Mittwoch' },
            { left: 'jueves', right: 'Donnerstag' },
            { left: 'viernes', right: 'Freitag' },
            { left: 'sábado', right: 'Samstag' },
            { left: 'domingo', right: 'Sonntag' },
          ],
          feedback: {
            rule: 'Die Wochentage sind männlich und werden klein geschrieben.',
            why: '`martes` (Dienstag) und `miércoles` (Mittwoch) werden gern verwechselt.',
            avoid: 'martes – Mars, miércoles – Merkur, jueves – Jupiter: Die Namen kommen von den Planeten.',
          },
        },
        {
          id: 'es.g.time-dates.L1.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.time-dates'],
          difficulty: 1,
          prompt: '„am Freitag“',
          options: [
            { text: 'el viernes', why: 'Richtig: Artikel statt „am“.' },
            { text: 'en viernes', why: '`en` steht nicht vor Wochentagen.' },
            { text: 'en el viernes', why: 'Auch mit Artikel kein `en`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Wochentag: nur `el` (einmalig) oder `los` (regelmäßig).',
            why: 'Das deutsche „am“ verleitet zu `en`.',
            avoid: 'el = „am“ bei Tagen.',
          },
        },
        {
          id: 'es.g.time-dates.L1.03',
          type: 'listening',
          skills: ['listening', 'vocabulary'],
          topicIds: ['es.g.time-dates'],
          difficulty: 1,
          audio: 'Mi cumpleaños es el veinte de julio.',
          question: 'Wann hat die Person Geburtstag?',
          options: ['am 20. Juli', 'am 12. Juni', 'am 2. Juli'],
          answer: 0,
          feedback: {
            rule: '`el veinte de julio` = der 20. Juli.',
            why: '`junio` (Juni) und `julio` (Juli) klingen ähnlich – achte auf das l.',
            avoid: 'jun**i**o – Jun**i**; ju**l**io – Ju**l**i.',
          },
        },
        {
          id: 'es.g.time-dates.L1.04',
          type: 'imageMatch',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.time-dates'],
          difficulty: 1,
          instruction: 'Ordne die Jahreszeiten zu.',
          pairs: [
            { emoji: '🌸', word: 'la primavera' },
            { emoji: '☀️', word: 'el verano' },
            { emoji: '🍂', word: 'el otoño' },
            { emoji: '❄️', word: 'el invierno' },
          ],
          feedback: {
            rule: 'la primavera (Frühling), el verano (Sommer), el otoño (Herbst), el invierno (Winter).',
            why: '`primavera` ist das einzige weibliche Wort der vier.',
            avoid: 'primavera – „erster Frühling“: prima + vera.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'el, los, en, de',
      exercises: [
        {
          id: 'es.g.time-dates.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 2,
          sentence: '___ lunes voy al gimnasio.',
          german: 'Montags gehe ich ins Fitnessstudio.',
          answers: [['Los']],
          bank: ['El', 'Los', 'En'],
          feedback: {
            rule: 'Regelmäßig („montags“) → `los lunes`.',
            why: '`El lunes` hieße „am (nächsten) Montag“, `en` passt nicht.',
            avoid: 'jeden … → los.',
          },
        },
        {
          id: 'es.g.time-dates.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 2,
          sentence: 'La fiesta es ___ 15 ___ agosto.',
          german: 'Das Fest ist am 15. August.',
          answers: [['el'], ['de']],
          bank: ['el', 'en', 'de', 'del'],
          feedback: {
            rule: 'Datum: `el` + Zahl + `de` + Monat.',
            why: '`en 15` und `del agosto` sind falsch.',
            avoid: 'el quince de agosto – immer in dieser Reihenfolge.',
          },
        },
        {
          id: 'es.g.time-dates.L2.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Welcher Tag ist heute?',
          answers: ['¿Qué día es hoy?', '¿Hoy qué día es?'],
          feedback: {
            rule: '`¿Qué día es hoy?` – feste Frage.',
            why: '„¿Cuál día …?“ ist unüblich; direkt vor einem Nomen fragt man mit `qué`.',
            avoid: 'qué + Nomen: qué día, qué hora, qué fecha.',
          },
        },
        {
          id: 'es.g.time-dates.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 2,
          sentence: 'Mi cumpleaños es en el 3 de marzo.',
          german: 'Mein Geburtstag ist am 3. März.',
          answers: ['Mi cumpleaños es el 3 de marzo.', 'Mi cumpleaños es el tres de marzo.'],
          feedback: {
            rule: 'Datum ohne `en`: `el 3 de marzo`.',
            why: '`en` steht nur bei Monat oder Jahreszeit allein (`en marzo`).',
            avoid: 'Mit Tageszahl → el; nur Monat → en.',
          },
        },
        {
          id: 'es.g.time-dates.L2.05',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 2,
          audio: 'Hoy es jueves, catorce de noviembre.',
          german: 'Heute ist Donnerstag, der 14. November.',
          answers: ['Hoy es jueves, catorce de noviembre.', 'Hoy es jueves, 14 de noviembre.'],
          feedback: {
            rule: 'Wochentag und Monat klein; Datum mit `de`.',
            why: 'Großgeschriebene Tage und Monate sind im Spanischen Rechtschreibfehler.',
            avoid: 'Nur am Satzanfang groß.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Über Termine sprechen',
      exercises: [
        {
          id: 'es.g.time-dates.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Im Sommer fahren wir ans Meer.',
          answers: [
            'En verano vamos a la playa.',
            'En el verano vamos a la playa.',
            'En verano vamos al mar.',
            'En el verano vamos al mar.',
            'Vamos a la playa en verano.',
            'Vamos al mar en verano.',
            'En verano nosotros vamos a la playa.',
            'Nosotros vamos a la playa en verano.',
          ],
          feedback: {
            rule: 'Jahreszeit mit `en` (Artikel optional): `en verano`.',
            why: '„El verano vamos …“ ohne `en` ist falsch – das gilt nur für Wochentage.',
            avoid: 'Tag → el; Jahreszeit → en.',
          },
        },
        {
          id: 'es.g.time-dates.L3.02',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 3,
          tokens: ['Mi', 'cumpleaños', 'es', 'el', 'doce', 'de', 'octubre', '.'],
          german: 'Mein Geburtstag ist am 12. Oktober.',
          feedback: {
            rule: '`el` + Zahl + `de` + Monat.',
            why: '„de octubre el doce“ entspricht nicht der spanischen Datumsreihenfolge.',
            avoid: 'Wie im Deutschen: erst der Tag, dann der Monat.',
          },
        },
        {
          id: 'es.g.time-dates.L3.03',
          type: 'situation',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.time-dates'],
          difficulty: 3,
          scenario: 'Eine Kollegin fragt: „¿Cuándo es tu cumpleaños?“ Du hast am 1. April Geburtstag.',
          options: [
            { text: 'Es el uno de abril.', why: 'Richtig. In Lateinamerika sagt man auch gern `el primero de abril`.' },
            { text: 'Es en abril uno.', why: 'Falsche Reihenfolge und falsches `en`.' },
            { text: 'Es el abril uno.', why: 'Die Zahl steht vor dem Monat, verbunden mit `de`.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Datum: `el` + Zahl + `de` + Monat.',
            why: 'Die englische Reihenfolge („April 1“) gibt es im Spanischen nicht.',
            avoid: 'Tag – de – Monat, wie im Deutschen.',
          },
        },
        {
          id: 'es.g.time-dates.L3.04',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.time-dates'],
          difficulty: 3,
          sentence: 'Mi cumpleaños es ___ primavera, ___ abril.',
          german: 'Mein Geburtstag ist im Frühling, im April.',
          answers: [['en'], ['en']],
          bank: ['en', 'el', 'de'],
          feedback: {
            rule: 'Jahreszeit und Monat ohne Tageszahl → `en`.',
            why: '`el abril` ist falsch; `el` steht nur beim Datum mit Zahl (`el 5 de abril`).',
            avoid: 'im … → en … (Monat, Jahreszeit).',
          },
        },
        {
          id: 'es.g.time-dates.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'vocabulary'],
          topicIds: ['es.g.time-dates'],
          difficulty: 3,
          prompt: 'Erzähl: Wann hast du Geburtstag? Was machst du normalerweise samstags oder sonntags? Welche Jahreszeit magst du?',
          keywords: [
            'cumpleaños', 'sábados', 'domingos', 'lunes', 'viernes', 'verano', 'invierno', 'primavera', 'otoño', 'enero', 'febrero',
            'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre',
          ],
          minMatch: 3,
          sample: 'Mi cumpleaños es el diez de marzo. Los sábados voy al mercado y los domingos descanso. Me gusta mucho el verano.',
          feedback: {
            rule: 'Datum mit `el … de …`, Gewohnheiten mit `los sábados`, Jahreszeiten mit `en` bzw. `me gusta el verano`.',
            why: 'Typisch sind `en el sábado` oder `el 10 marzo`.',
            avoid: 'Tag → el/los, Monat → en, Datum → el + Zahl + de.',
          },
        },
      ],
    },
  ],
  related: ['es.g.numbers', 'es.g.articles', 'es.g.weather'],
};
