import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.weather',
  courseId: 'es',
  stageId: 'a1',
  order: 13,
  category: 'Verben',
  title: 'Das Wetter – hace, está, hay, llueve',
  summary: 'Hace calor, está nublado, hay niebla, llueve: Welches Verb zu welchem Wetter gehört, warum es „mucho calor“ heißt – und weshalb Weihnachten in Buenos Aires in den Sommer fällt.',
  keywords: [
    'Wetter', 'tiempo', 'qué tiempo hace', 'hace', 'hacer', 'calor', 'frío', 'sol', 'viento', 'buen tiempo', 'mal tiempo', 'nublado',
    'está nublado', 'llueve', 'llover', 'nieva', 'nevar', 'niebla', 'hay niebla', 'tormenta', 'grados', 'Temperatur', 'Regen',
    'Schnee', 'Wind', 'Nebel', 'Sonne', 'bewölkt', 'heiß', 'kalt', 'Jahreszeiten', 'Südhalbkugel',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Nach dem Wetter fragt man mit `¿Qué tiempo hace?` (Wie ist das Wetter?). `el tiempo` heißt hier „das Wetter“, nicht „die Zeit“. Für die Antwort brauchst du **vier Muster** – ein „es“ wie im Deutschen gibt es nicht.',
    },
    {
      type: 'table',
      title: 'Welches Verb für welches Wetter?',
      headers: ['Muster', 'Spanisch', 'Deutsch'],
      rows: [
        ['hace + Nomen', 'Hace calor / frío / sol / viento.', 'Es ist heiß / kalt / sonnig / windig.'],
        ['hace + buen/mal tiempo', 'Hace buen tiempo. · Hace mal tiempo.', 'Das Wetter ist schön. · Das Wetter ist schlecht.'],
        ['está + Adjektiv', 'Está nublado. · Está despejado.', 'Es ist bewölkt. · Es ist klar.'],
        ['hay + Nomen', 'Hay niebla. · Hay tormenta.', 'Es ist neblig. · Es gibt ein Gewitter.'],
        ['eigenes Verb', 'Llueve. · Nieva.', 'Es regnet. · Es schneit.'],
        ['Temperatur', 'Estamos a 30 grados. · Hace 30 grados.', 'Es sind 30 Grad.'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Hoy', role: 'adverb' },
        { text: ' hace', role: 'verb' },
        { text: ' mucho', role: 'adjective' },
        { text: ' calor', role: 'noun' },
        { text: ', pero ' },
        { text: 'mañana', role: 'adverb' },
        { text: ' va a llover', role: 'verb' },
        { text: '.' },
      ],
      german: 'Heute ist es sehr heiß, aber morgen wird es regnen.',
    },
    {
      type: 'text',
      md: '`calor`, `frío`, `sol` und `viento` sind **Nomen**. Darum verstärkst du sie mit `mucho` (viel), nicht mit `muy`: `Hace mucho calor`, `Hace mucho viento`. `llover` (o → ue) und `nevar` (e → ie) sind Stammwechselverben, die man praktisch nur in der 3. Person braucht: `llueve`, `nieva`.',
    },
    {
      type: 'table',
      title: 'Kälte dreimal anders',
      headers: ['Spanisch', 'Bedeutung', 'Deutsch'],
      rows: [
        ['Hace frío.', 'Wetter', 'Es ist kalt (draußen).'],
        ['Tengo frío.', 'Person', 'Mir ist kalt.'],
        ['La sopa está fría.', 'Sache', 'Die Suppe ist kalt.'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Es calor.',
      right: 'Hace calor.',
      why: 'Wetter mit Nomen (calor, frío, sol, viento) steht mit `hacer`. „Es“ wird nicht übersetzt.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Auf der **Südhalbkugel** (Argentinien, Chile, Uruguay, Paraguay) sind die Jahreszeiten umgekehrt: Im Januar `hace calor`, im Juli `hace frío`, Weihnachten fällt in den Sommer. In tropischen Ländern wie Kolumbien oder Venezuela spricht man eher von der `temporada de lluvias` (Regenzeit) und der `temporada seca` (Trockenzeit).',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'In Spanien hört man oft `¡Qué calor hace!` und im Sommer `Estamos a cuarenta grados` – in Andalusien keine Seltenheit.',
    },
    { type: 'tip', md: '**hace + Nomen, está + Adjektiv, hay + Nomen – und Regen und Schnee sind eigene Verben: llueve, nieva.**' },
    { type: 'audio', text: '¿Qué tiempo hace hoy? Hace sol y mucho calor. En invierno hace frío y a veces nieva.', label: 'Beispiel anhören' },
  ],
  examples: [
    {
      target: '—¿Qué tiempo hace hoy? —Hace sol y mucho calor.',
      german: '„Wie ist das Wetter heute?“ – „Die Sonne scheint und es ist sehr heiß.“',
    },
    {
      target: 'En invierno hace frío y nieva.',
      german: 'Im Winter ist es kalt und es schneit.',
      parts: [
        { text: 'En invierno', role: 'adverb' },
        { text: ' hace', role: 'verb' },
        { text: ' frío', role: 'noun' },
        { text: ' y' },
        { text: ' nieva', role: 'verb' },
        { text: '.' },
      ],
    },
    { target: 'Hoy está nublado, pero no llueve.', german: 'Heute ist es bewölkt, aber es regnet nicht.' },
    { target: 'Por la mañana hay niebla.', german: 'Morgens ist es neblig.' },
    { target: 'Hace buen tiempo: ¡vamos a la playa!', german: 'Das Wetter ist schön: Lass uns an den Strand gehen!' },
    { target: 'En Buenos Aires hace calor en enero.', german: 'In Buenos Aires ist es im Januar heiß.' },
    { target: 'Estamos a treinta grados.', german: 'Es sind dreißig Grad.' },
    { target: '¡Qué frío hace!', german: 'Ist das kalt!' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Hace frío.',
      german: 'Es ist kalt.',
      md: 'Deutsch: „es ist“ + Adjektiv. Spanisch: wörtlich „es macht Kälte“ – `hacer` + Nomen.',
    },
    {
      type: 'compare',
      target: 'Llueve.',
      german: 'Es regnet.',
      md: 'Kein Subjekt: Das deutsche „es“ fällt einfach weg. Das Verb allein ist ein vollständiger Satz.',
    },
    {
      type: 'compare',
      target: 'Está nublado.',
      german: 'Es ist bewölkt.',
      md: 'Hier gibt es ein Adjektiv – und für einen vorübergehenden Zustand nimmst du `estar`.',
    },
    {
      type: 'compare',
      target: 'Hace mucho calor.',
      german: 'Es ist sehr heiß.',
      md: 'Deutsch „sehr“ + Adjektiv → Spanisch „viel“ + Nomen: `mucho calor`.',
    },
  ],
  mistakes: [
    { wrong: 'Es calor.', right: 'Hace calor.', why: 'Wetter + Nomen → `hacer`.' },
    { wrong: 'Hace muy frío.', right: 'Hace mucho frío.', why: '`frío` ist hier ein Nomen → `mucho`.' },
    { wrong: 'Hace nublado.', right: 'Está nublado.', why: '`nublado` ist ein Adjektiv → `estar`.' },
    { wrong: 'Es lluvia.', right: 'Llueve.', why: 'Für Regen gibt es das Verb `llover` → `llueve`.' },
    { wrong: 'Está sol.', right: 'Hace sol.', why: '`sol` ist ein Nomen → `hace sol`.' },
  ],
  mnemonic: '**hace + Nomen, está + Adjektiv, hay + Nomen – llueve und nieva allein.**',
  levels: [
    {
      level: 1,
      title: 'Wetter benennen',
      exercises: [
        {
          id: 'es.g.weather.L1.01',
          type: 'imageMatch',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.weather'],
          difficulty: 1,
          instruction: 'Ordne das Wetter zu.',
          pairs: [
            { emoji: '☀️', word: 'hace sol' },
            { emoji: '🌧️', word: 'llueve' },
            { emoji: '❄️', word: 'nieva' },
            { emoji: '🌬️', word: 'hace viento' },
            { emoji: '☁️', word: 'está nublado' },
            { emoji: '🌫️', word: 'hay niebla' },
          ],
          feedback: {
            rule: 'hace sol/viento · está nublado · hay niebla · llueve · nieva.',
            why: 'Jedes Wetter hat sein eigenes Muster – lerne es mit dem Verb.',
            avoid: 'Lerne nie nur „sol“, sondern immer „hace sol“.',
          },
        },
        {
          id: 'es.g.weather.L1.02',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.weather'],
          difficulty: 1,
          prompt: '„Es ist heiß.“ (das Wetter)',
          options: [
            { text: 'Hace calor.', why: 'Richtig: Wetter + Nomen → `hace`.' },
            { text: 'Es calor.', why: '`ser` beschreibt kein Wetter.' },
            { text: 'Tengo calor.', why: '`Tengo calor` = Mir ist heiß (Körpergefühl), nicht das Wetter.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Wetter: `hace calor`; Person: `tengo calor`.',
            why: 'Das deutsche „Es ist …“ verleitet zu `es`.',
            avoid: 'Draußen → hace, in mir → tengo.',
          },
        },
        {
          id: 'es.g.weather.L1.03',
          type: 'listening',
          skills: ['listening', 'vocabulary'],
          topicIds: ['es.g.weather'],
          difficulty: 1,
          audio: 'Hoy está nublado y hace frío.',
          question: 'Wie ist das Wetter?',
          options: ['bewölkt und kalt', 'sonnig und heiß', 'regnerisch und windig'],
          answer: 0,
          feedback: {
            rule: '`nublado` = bewölkt, `frío` = Kälte.',
            why: 'Sonnig wäre `hace sol`, Regen `llueve`.',
            avoid: 'nublado – von `nube` (Wolke).',
          },
        },
        {
          id: 'es.g.weather.L1.04',
          type: 'matchPairs',
          skills: ['vocabulary', 'reading'],
          topicIds: ['es.g.weather'],
          difficulty: 1,
          instruction: 'Ordne die Sätze zu.',
          pairs: [
            { left: 'Hace buen tiempo.', right: 'Das Wetter ist schön.' },
            { left: 'Hace mal tiempo.', right: 'Das Wetter ist schlecht.' },
            { left: 'Hace viento.', right: 'Es ist windig.' },
            { left: 'Hay niebla.', right: 'Es ist neblig.' },
            { left: 'Nieva.', right: 'Es schneit.' },
          ],
          feedback: {
            rule: '`buen/mal tiempo` mit `hace`; Nebel mit `hay`.',
            why: '`buen` und `mal` sind die Kurzformen vor männlichen Nomen (`el tiempo`).',
            avoid: 'buen tiempo = gutes Wetter – nie „bueno tiempo“.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'hace, está oder hay?',
      exercises: [
        {
          id: 'es.g.weather.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.weather'],
          difficulty: 2,
          sentence: 'En verano ___ calor, pero en invierno ___.',
          german: 'Im Sommer ist es heiß, aber im Winter schneit es.',
          answers: [['hace'], ['nieva']],
          bank: ['hace', 'está', 'hay', 'nieva', 'llueve'],
          feedback: {
            rule: '`hace calor`; Schnee = eigenes Verb: `nieva`.',
            why: '`llueve` wäre „es regnet“.',
            avoid: 'nevar → nieva (e → ie), llover → llueve (o → ue).',
          },
        },
        {
          id: 'es.g.weather.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.weather'],
          difficulty: 2,
          sentence: 'Hoy ___ nublado y ___ niebla.',
          german: 'Heute ist es bewölkt und neblig.',
          answers: [['está'], ['hay']],
          bank: ['hace', 'está', 'hay'],
          feedback: {
            rule: 'Adjektiv `nublado` → `está`; Nomen `niebla` → `hay`.',
            why: '`hace nublado` ist falsch, weil `nublado` kein Nomen ist.',
            avoid: 'Adjektiv → está · Nebel → hay.',
          },
        },
        {
          id: 'es.g.weather.L2.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.weather'],
          difficulty: 2,
          prompt: 'Welcher Satz ist richtig?',
          options: [
            { text: 'Hace mucho frío.', why: 'Richtig: `frío` ist ein Nomen → `mucho`.' },
            { text: 'Hace muy frío.', why: '`muy` steht vor Adjektiven, nicht vor Nomen.' },
            { text: 'Es mucho frío.', why: 'Wetter mit Nomen braucht `hace`.' },
          ],
          answer: 0,
          feedback: {
            rule: '`hace mucho frío/calor/viento/sol`.',
            why: 'Im Deutschen sagt man „sehr kalt“ – daher die Versuchung, `muy` zu nehmen.',
            avoid: 'Nach hace → mucho.',
          },
        },
        {
          id: 'es.g.weather.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.weather'],
          difficulty: 2,
          sentence: 'Hoy es mucho calor.',
          german: 'Heute ist es sehr heiß.',
          answers: ['Hoy hace mucho calor.'],
          feedback: {
            rule: 'Wetter + Nomen → `hace`.',
            why: '`es` ist die wörtliche Übersetzung von „es ist“ – passt aber nicht.',
            avoid: 'Denke „es macht Hitze“: hace calor.',
          },
        },
        {
          id: 'es.g.weather.L2.05',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.weather', 'es.g.stem-change'],
          difficulty: 2,
          verb: 'llover',
          tense: 'Präsens',
          person: '3. Person Singular (Wetter)',
          sentence: 'En abril ___ mucho.',
          answers: ['llueve'],
          feedback: {
            rule: '`llover` (o → ue) → `llueve`.',
            why: '`llove` ohne Stammwechsel ist falsch, `lluvia` ist das Nomen (der Regen).',
            avoid: 'llover – llueve, wie poder – puede.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Über das Wetter sprechen',
      exercises: [
        {
          id: 'es.g.weather.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.weather'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Heute ist schönes Wetter.',
          answers: ['Hoy hace buen tiempo.', 'Hace buen tiempo hoy.'],
          feedback: {
            rule: '„schönes Wetter“ = `buen tiempo` mit `hace`.',
            why: '„Hoy es buen tiempo“ ist falsch; `bueno` wird vor dem Nomen zu `buen`.',
            avoid: 'Wetter = hace + (buen/mal) tiempo.',
          },
        },
        {
          id: 'es.g.weather.L3.02',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.weather'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Es regnet und es ist windig.',
          answers: ['Llueve y hace viento.', 'Está lloviendo y hace viento.', 'Hace viento y llueve.'],
          feedback: {
            rule: 'Regen: `llueve`; Wind: `hace viento`.',
            why: '„Es lluvia y es viento“ überträgt das deutsche „es“ wörtlich.',
            avoid: 'Kein „es“ im Spanischen – das Verb reicht.',
          },
        },
        {
          id: 'es.g.weather.L3.03',
          type: 'situation',
          skills: ['reading', 'vocabulary'],
          topicIds: ['es.g.weather'],
          difficulty: 3,
          scenario: 'Du rufst im Juli eine Freundin in Buenos Aires an und fragst: „¿Qué tiempo hace allí?“ Was antwortet sie am wahrscheinlichsten?',
          options: [
            { text: 'Aquí hace frío, es invierno.', why: 'Richtig: Auf der Südhalbkugel ist im Juli Winter.' },
            { text: 'Aquí hace mucho calor, es verano.', why: 'Sommer ist in Buenos Aires von Dezember bis Februar.' },
            { text: 'Aquí nieva siempre en julio.', why: 'Schnee ist in Buenos Aires extrem selten.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Südhalbkugel: Juni–August = Winter, Dezember–Februar = Sommer.',
            why: 'Die Jahreszeiten sind gegenüber Europa vertauscht.',
            avoid: 'Weihnachten am Strand – so merkst du dir den Sommer in Argentinien.',
          },
        },
        {
          id: 'es.g.weather.L3.04',
          type: 'dictation',
          skills: ['listening', 'writing'],
          topicIds: ['es.g.weather'],
          difficulty: 3,
          audio: 'Estamos a veinticinco grados y hace sol.',
          german: 'Es sind 25 Grad und die Sonne scheint.',
          answers: ['Estamos a veinticinco grados y hace sol.', 'Estamos a 25 grados y hace sol.'],
          feedback: {
            rule: 'Temperatur: `Estamos a … grados`; Sonne: `hace sol`.',
            why: '`veinticinco` wird zusammen geschrieben.',
            avoid: '21–29 immer in einem Wort: veintiuno … veintinueve.',
          },
        },
        {
          id: 'es.g.weather.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'vocabulary'],
          topicIds: ['es.g.weather'],
          difficulty: 3,
          prompt: 'Beschreibe das Wetter heute bei dir und in deiner Lieblingsjahreszeit.',
          keywords: ['hace', 'calor', 'frío', 'sol', 'viento', 'llueve', 'nieva', 'nublado', 'niebla', 'buen tiempo', 'mal tiempo', 'grados'],
          minMatch: 3,
          sample: 'Hoy está nublado y hace un poco de frío. En verano hace sol y mucho calor.',
          feedback: {
            rule: 'hace + Nomen, está + Adjektiv, hay + Nomen, llueve/nieva.',
            why: 'Typisch: `es frío`, `hace muy calor`.',
            avoid: 'Starte mit „Hoy hace …“ oder „Hoy está …“.',
          },
        },
      ],
    },
  ],
  related: ['es.g.time-dates', 'es.g.tener', 'es.g.muy-mucho'],
};
