import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.word-order-negation',
  courseId: 'es',
  stageId: 'stage0',
  order: 11,
  category: 'Satzbau',
  title: 'Satzstellung & Verneinung',
  summary: 'Subjekt – Verb – Objekt, „no“ direkt vor dem Verb und die doppelte Verneinung mit nada, nunca, nadie.',
  keywords: [
    'Satzstellung', 'Wortstellung', 'Satzbau', 'Verneinung', 'Negation', 'no', 'nicht', 'kein', 'nada', 'nichts', 'nunca', 'nie',
    'nadie', 'niemand', 'tampoco', 'auch nicht', 'doppelte Verneinung', 'Verbzweitstellung', 'Nebensatz', 'porque',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Die Grundordnung ist **Subjekt – Verb – Objekt**: `Ana habla español.` Das Subjekt fällt oft weg: `Hablo español.` Anders als im Deutschen rutscht das Verb **nie ans Satzende** und muss auch nicht an Position 2 stehen.',
    },
    {
      type: 'colored',
      parts: [
        { text: 'Ana', role: 'subject' },
        { text: ' no', role: 'negation' },
        { text: ' habla', role: 'verb' },
        { text: ' alemán', role: 'object' },
        { text: '.' },
      ],
      german: 'Ana spricht kein Deutsch.',
    },
    {
      type: 'text',
      md: '**Verneinung:** Ein einfaches `no` steht **direkt vor dem Verb**. Das deutsche „nicht“ und „kein“ werden beide zu `no` + Verb: `No hablo inglés.` (Ich spreche kein Englisch.) · `No vivo en Madrid.` (Ich wohne nicht in Madrid.)',
    },
    {
      type: 'table',
      title: 'Verneinungswörter',
      headers: ['Spanisch', 'Deutsch', 'Beispiel'],
      rows: [
        ['no … nada', 'nichts', 'No como nada. – Ich esse nichts.'],
        ['no … nunca', 'nie', 'No bebo nunca café. / Nunca bebo café.'],
        ['no … nadie', 'niemand', 'No hay nadie. / Nadie habla alemán.'],
        ['tampoco', 'auch nicht', 'Yo tampoco. – Ich auch nicht.'],
      ],
    },
    {
      type: 'text',
      md: '**Doppelte Verneinung ist im Spanischen Pflicht:** Steht `nada`, `nunca` oder `nadie` **hinter** dem Verb, braucht es zusätzlich `no` davor. Steht es **vor** dem Verb, entfällt das `no`: `No trabajo nunca los domingos.` = `Nunca trabajo los domingos.`',
    },
    {
      type: 'mistake',
      wrong: 'Hablo no inglés.',
      right: 'No hablo inglés.',
      why: 'Das deutsche „nicht/kein“ steht oft weit hinten. Spanisch setzt `no` immer direkt vor das Verb.',
    },
    {
      type: 'compare',
      target: '—¿Hablas inglés? —No, no hablo inglés.',
      german: '„Sprichst du Englisch?“ – „Nein, ich spreche kein Englisch.“',
      md: 'Das erste `no` heißt „nein“, das zweite verneint das Verb.',
    },
    { type: 'tip', md: '**`no` klebt vor dem Verb.** Und: nada, nunca, nadie hinter dem Verb? Dann braucht es vorne ein `no`.' },
    { type: 'audio', text: 'No, no hablo alemán. No hablo nada.', label: 'Verneinung anhören' },
  ],
  examples: [
    {
      target: 'No vivo en Madrid.',
      german: 'Ich wohne nicht in Madrid.',
      parts: [
        { text: 'No', role: 'negation' },
        { text: ' vivo', role: 'verb' },
        { text: ' en Madrid', role: 'object' },
        { text: '.' },
      ],
    },
    { target: 'Mi hermano no es médico.', german: 'Mein Bruder ist kein Arzt.' },
    {
      target: 'No como nada.',
      german: 'Ich esse nichts.',
      parts: [
        { text: 'No', role: 'negation' },
        { text: ' como', role: 'verb' },
        { text: ' nada', role: 'negation' },
        { text: '.' },
      ],
    },
    { target: 'Nunca bebo café por la noche.', german: 'Ich trinke abends nie Kaffee.' },
    { target: 'Nadie habla alemán aquí.', german: 'Hier spricht niemand Deutsch.' },
    { target: '—No me gusta el té. —A mí tampoco.', german: '„Ich mag keinen Tee.“ – „Ich auch nicht.“' },
    { target: 'Hoy no trabajo porque estoy cansada.', german: 'Heute arbeite ich nicht, weil ich müde bin.' },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Hoy trabajo en casa.',
      german: 'Heute arbeite ich zu Hause.',
      md: 'Deutsch: Verb an Position 2, das Subjekt wandert hinter das Verb. Spanisch: keine solche Regel – `hoy` + Verb, das Subjekt entfällt meist.',
    },
    {
      type: 'compare',
      target: '… porque estoy cansado.',
      german: '… weil ich müde bin.',
      md: 'Im deutschen Nebensatz steht das Verb am Ende. Im Spanischen bleibt die normale Reihenfolge.',
    },
    {
      type: 'compare',
      target: 'No tengo tiempo.',
      german: 'Ich habe keine Zeit.',
      md: '„kein/keine“ gibt es nicht als Artikel – man verneint das Verb.',
    },
    {
      type: 'compare',
      target: 'No veo a nadie.',
      german: 'Ich sehe niemanden.',
      md: 'Im Deutschen hebt sich „nicht niemand“ auf. Im Spanischen verstärkt die doppelte Verneinung – sie ist korrekt und Pflicht.',
    },
  ],
  mistakes: [
    { wrong: 'Hablo no inglés.', right: 'No hablo inglés.', why: '`no` steht direkt vor dem Verb.' },
    { wrong: 'Como nada.', right: 'No como nada.', why: '`nada` hinter dem Verb braucht ein `no` davor.' },
    { wrong: 'Nadie no habla alemán.', right: 'Nadie habla alemán.', why: 'Steht das Verneinungswort vor dem Verb, fällt `no` weg.' },
    { wrong: 'Porque yo cansado estoy.', right: 'Porque estoy cansado.', why: 'Keine Verb-Endstellung im Nebensatz.' },
  ],
  mnemonic: '**`no` klebt vor dem Verb** – und zwei Verneinungen machen im Spanischen kein Ja.',
  levels: [
    {
      level: 1,
      title: 'Einfach verneinen',
      exercises: [
        {
          id: 'es.g.word-order-negation.L1.01',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 1,
          prompt: '„Ich spreche kein Französisch.“ – Welcher Satz ist richtig?',
          options: [
            { text: 'No hablo francés.', why: 'Richtig: `no` direkt vor dem Verb.' },
            { text: 'Hablo no francés.', why: '`no` darf nicht hinter dem Verb stehen.' },
            { text: 'Hablo francés no.', why: 'Das klingt wie „Ich spreche Französisch – nein.“' },
          ],
          answer: 0,
          feedback: {
            rule: '`no` + Verb; „kein“ wird nicht extra übersetzt.',
            why: 'Die deutsche Position von „nicht/kein“ ist im Spanischen falsch.',
            avoid: 'Erst `no`, dann sofort das Verb.',
          },
        },
        {
          id: 'es.g.word-order-negation.L1.02',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 1,
          tokens: ['Ana', 'no', 'vive', 'en', 'Madrid.'],
          extra: ['nada'],
          german: 'Ana wohnt nicht in Madrid.',
          feedback: {
            rule: 'Subjekt – `no` – Verb – Rest.',
            why: '`nada` heißt „nichts“ und passt hier nicht.',
            avoid: 'Das `no` steht zwischen Subjekt und Verb.',
          },
        },
        {
          id: 'es.g.word-order-negation.L1.03',
          type: 'matchPairs',
          skills: ['vocabulary', 'grammar'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 1,
          instruction: 'Ordne die Verneinungswörter zu.',
          pairs: [
            { left: 'nada', right: 'nichts' },
            { left: 'nunca', right: 'nie' },
            { left: 'nadie', right: 'niemand' },
            { left: 'tampoco', right: 'auch nicht' },
          ],
          feedback: {
            rule: 'nada = nichts, nunca = nie, nadie = niemand, tampoco = auch nicht.',
            why: '`nada` und `nadie` sehen ähnlich aus – `nadie` ist die Person.',
            avoid: 'nad**ie** – „ie“ wie in „n**ie**mand“.',
          },
        },
        {
          id: 'es.g.word-order-negation.L1.04',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 1,
          audio: 'No, no hablo alemán.',
          question: 'Was sagt die Person?',
          options: ['Sie spricht kein Deutsch.', 'Sie spricht Deutsch.', 'Sie spricht ein bisschen Deutsch.'],
          answer: 0,
          feedback: {
            rule: '`No, no hablo …` = „Nein, ich spreche kein …“.',
            why: 'Das doppelte `no` ist kein Ja – das erste antwortet, das zweite verneint.',
            avoid: 'Achte auf das `no` direkt vor dem Verb.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Doppelte Verneinung',
      exercises: [
        {
          id: 'es.g.word-order-negation.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 2,
          sentence: 'No como ___ por la mañana.',
          german: 'Morgens esse ich nichts.',
          answers: [['nada']],
          bank: ['nada', 'algo', 'nadie'],
          feedback: {
            rule: '`no` + Verb + `nada` = nichts.',
            why: '`algo` (etwas) passt nicht zur Verneinung; `nadie` bezieht sich auf Personen.',
            avoid: 'Verneinter Satz → verneintes Wort: nada statt algo.',
          },
        },
        {
          id: 'es.g.word-order-negation.L2.02',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 2,
          sentence: 'Hablo no italiano.',
          german: 'Ich spreche kein Italienisch.',
          answers: ['No hablo italiano.', 'Yo no hablo italiano.'],
          feedback: {
            rule: '`no` steht vor dem konjugierten Verb.',
            why: 'Die deutsche Stellung („spreche … nicht“) lässt sich nicht übertragen.',
            avoid: 'Stell dir `no` und das Verb als ein Wort vor: `nohablo`.',
          },
        },
        {
          id: 'es.g.word-order-negation.L2.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 2,
          direction: 'toTarget',
          source: 'Ich wohne nicht in Berlin.',
          answers: ['No vivo en Berlín.', 'Yo no vivo en Berlín.'],
          feedback: {
            rule: '`no` + `vivo` + Ortsangabe.',
            why: '„Vivo no en Berlín“ ist falsch – `no` gehört vor das Verb.',
            avoid: '„nicht“ = `no` vor dem Verb, egal wo es im Deutschen steht.',
          },
        },
        {
          id: 'es.g.word-order-negation.L2.04',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 2,
          prompt: '„Niemand spricht Deutsch.“ – Welcher Satz ist korrekt?',
          options: [
            { text: 'Nadie habla alemán.', why: 'Richtig: `nadie` steht vor dem Verb, daher kein zusätzliches `no`.' },
            { text: 'Nadie no habla alemán.', why: 'Steht `nadie` vor dem Verb, fällt `no` weg.' },
            { text: 'No nadie habla alemán.', why: '`no` und `nadie` stehen nie direkt hintereinander vor dem Verb.' },
          ],
          answer: 0,
          feedback: {
            rule: 'Verneinungswort **vor** dem Verb → kein `no`; **hinter** dem Verb → `no` davor.',
            why: '`No habla nadie alemán` wäre auch korrekt – aber nicht in dieser Reihenfolge.',
            avoid: 'Genau ein Verneinungswort vor dem Verb.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Natürlich formulieren',
      exercises: [
        {
          id: 'es.g.word-order-negation.L3.01',
          type: 'order',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 3,
          tokens: ['No', 'como', 'nunca', 'carne.'],
          extra: ['nada', 'nadie'],
          alternatives: [['No', 'como', 'carne', 'nunca.']],
          german: 'Ich esse nie Fleisch.',
          feedback: {
            rule: '`nunca` hinter dem Verb → `no` davor.',
            why: 'Ohne `no` wäre der Satz falsch; `nada` würde „nichts“ bedeuten.',
            avoid: 'Alternative ohne `no`: `Nunca como carne.`',
          },
        },
        {
          id: 'es.g.word-order-negation.L3.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 3,
          sentence: '—No hablo francés. —Yo ___.',
          german: '„Ich spreche kein Französisch.“ – „Ich auch nicht.“',
          answers: [['tampoco']],
          bank: ['también', 'tampoco', 'nunca'],
          feedback: {
            rule: 'Zustimmung zu einer verneinten Aussage: `tampoco` (auch nicht).',
            why: '`también` (auch) passt nur zu bejahten Aussagen.',
            avoid: 'Verneinung + „ich auch“ → `yo tampoco`.',
          },
        },
        {
          id: 'es.g.word-order-negation.L3.03',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Heute arbeite ich nicht, weil ich müde bin.',
          answers: [
            'Hoy no trabajo porque estoy cansado.',
            'Hoy no trabajo porque estoy cansada.',
            'Hoy no trabajo, porque estoy cansado.',
            'Hoy no trabajo, porque estoy cansada.',
            'No trabajo hoy porque estoy cansado.',
            'No trabajo hoy porque estoy cansada.',
            'Hoy yo no trabajo porque estoy cansado.',
            'Hoy yo no trabajo porque estoy cansada.',
          ],
          feedback: {
            rule: '`no` vor dem Verb; nach `porque` bleibt die normale Wortstellung (`estoy cansado/a`).',
            why: 'Weder Verbzweitstellung („Hoy trabajo yo no“) noch Verb am Satzende („porque cansado estoy“).',
            avoid: 'Spanische Nebensätze sind gebaut wie Hauptsätze.',
          },
        },
        {
          id: 'es.g.word-order-negation.L3.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.word-order-negation'],
          difficulty: 3,
          sentence: 'Nadie no habla alemán aquí.',
          german: 'Hier spricht niemand Deutsch.',
          answers: ['Nadie habla alemán aquí.', 'Aquí nadie habla alemán.', 'Aquí no habla nadie alemán.', 'No habla nadie alemán aquí.'],
          feedback: {
            rule: '`nadie` vor dem Verb → ohne `no`.',
            why: '`no` wird nur gebraucht, wenn das Verneinungswort hinter dem Verb steht.',
            avoid: 'Zähle die Verneinungen vor dem Verb: Es darf nur eine sein.',
          },
        },
      ],
    },
  ],
  related: ['es.g.present-regular', 'es.g.questions'],
};
