import type { GrammarTopic } from '../../types';

export const topic: GrammarTopic = {
  id: 'es.g.yo-irregular',
  courseId: 'es',
  stageId: 'a1',
  order: 14,
  category: 'Verben',
  title: 'Unregelmäßige yo-Formen – hago, salgo, sé, conozco',
  summary: 'Viele Verben sind nur in der ich-Form unregelmäßig: hago, pongo, salgo, traigo (… -go), sé, veo, doy – und conozco. Ab tú ist alles wieder normal. Dazu: saber oder conocer?',
  keywords: [
    'unregelmäßig', 'yo-Form', 'ich-Form', 'go-Verben', 'hacer', 'hago', 'poner', 'pongo', 'salir', 'salgo', 'traer', 'traigo',
    'tener', 'tengo', 'venir', 'vengo', 'saber', 'sé', 'conocer', 'conozco', 'ver', 'veo', 'dar', 'doy', 'machen', 'ausgehen',
    'wissen', 'kennen', 'können', 'saber oder conocer',
  ],
  explanation: [
    {
      type: 'text',
      md: 'Bei einer ganzen Reihe wichtiger Verben ist **nur die yo-Form unregelmäßig**. Alle anderen Formen folgen dem normalen Muster der -er- oder -ir-Verben. Du musst dir also pro Verb nur **eine** Form extra merken.',
    },
    {
      type: 'conjugation',
      verb: 'hacer',
      translation: 'machen, tun',
      tense: 'Präsens (nur yo unregelmäßig)',
      rows: [
        { person: 'yo', form: 'hago', ending: 'go' },
        { person: 'tú', form: 'haces', ending: 'es' },
        { person: 'él / ella / usted', form: 'hace', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'hacemos', ending: 'emos' },
        { person: 'vosotros / vosotras', form: 'hacéis', ending: 'éis', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'hacen', ending: 'en' },
      ],
    },
    {
      type: 'conjugation',
      verb: 'salir',
      translation: 'ausgehen, weggehen, abfahren',
      tense: 'Präsens (nur yo unregelmäßig)',
      rows: [
        { person: 'yo', form: 'salgo', ending: 'go' },
        { person: 'tú', form: 'sales', ending: 'es' },
        { person: 'él / ella / usted', form: 'sale', ending: 'e' },
        { person: 'nosotros / nosotras', form: 'salimos', ending: 'imos' },
        { person: 'vosotros / vosotras', form: 'salís', ending: 'ís', variant: 'es-ES' },
        { person: 'ellos / ellas / ustedes', form: 'salen', ending: 'en' },
      ],
    },
    {
      type: 'table',
      title: 'Die wichtigsten Verben mit besonderer yo-Form',
      headers: ['Gruppe', 'Infinitiv', 'yo', 'tú', 'Deutsch'],
      rows: [
        ['-go', 'hacer', 'hago', 'haces', 'machen, tun'],
        ['-go', 'poner', 'pongo', 'pones', 'legen, stellen'],
        ['-go', 'salir', 'salgo', 'sales', 'ausgehen'],
        ['-go', 'traer', 'traigo', 'traes', '(mit)bringen'],
        ['-go + Stammwechsel', 'tener', 'tengo', 'tienes', 'haben'],
        ['-go + Stammwechsel', 'venir', 'vengo', 'vienes', 'kommen'],
        ['-zco', 'conocer', 'conozco', 'conoces', 'kennen'],
        ['Sonderform', 'saber', 'sé', 'sabes', 'wissen, können'],
        ['Sonderform', 'ver', 'veo', 'ves', 'sehen'],
        ['Sonderform', 'dar', 'doy', 'das', 'geben'],
      ],
    },
    {
      type: 'colored',
      parts: [
        { text: 'Los viernes', role: 'adverb' },
        { text: ' salgo', role: 'verb' },
        { text: ' con mis amigos', role: 'preposition' },
        { text: ', pero hoy ' },
        { text: 'hago', role: 'verb' },
        { text: ' la cena', role: 'object' },
        { text: ' en casa', role: 'preposition' },
        { text: '.' },
      ],
      german: 'Freitags gehe ich mit meinen Freunden aus, aber heute koche ich zu Hause.',
    },
    {
      type: 'table',
      title: 'saber oder conocer?',
      headers: ['Verb', 'wofür', 'Beispiel'],
      rows: [
        ['saber', 'Wissen, Fakten, Informationen', 'No sé dónde está la estación.'],
        ['saber + Infinitiv', 'gelernte Fähigkeit („können“)', 'Sé nadar. · ¿Sabes cocinar?'],
        ['conocer', 'Personen, Orte, Dinge kennen', 'Conozco Madrid. · Conozco un bar muy bueno.'],
        ['conocer a', 'eine Person kennen (mit a!)', '¿Conoces a Marta?'],
      ],
    },
    {
      type: 'mistake',
      wrong: 'Yo sabo la respuesta.',
      right: 'Yo sé la respuesta.',
      why: 'Die yo-Form von `saber` ist `sé` – mit Akzent, damit man sie vom Pronomen `se` unterscheidet.',
    },
    {
      type: 'variant',
      variant: 'es-ES',
      md: 'vosotros ist regelmäßig: `hacéis`, `ponéis`, `salís`, `sabéis`, `conocéis`.',
    },
    {
      type: 'variant',
      variant: 'es-LA',
      md: 'Die yo-Formen sind überall gleich. In Argentinien und Uruguay heißt es bei vos: `vos hacés`, `salís`, `sabés`, `conocés`.',
    },
    { type: 'tip', md: '**Nur „ich“ tanzt aus der Reihe:** hago, pongo, salgo, traigo, tengo, vengo – sé, veo, doy – conozco. Ab tú wieder normal.' },
    { type: 'audio', text: 'Hago la cena, pongo la mesa, salgo a las ocho. Sé cocinar y conozco un restaurante muy bueno.', label: 'Formen anhören' },
  ],
  examples: [
    { target: 'Los sábados hago deporte.', german: 'Samstags mache ich Sport.' },
    {
      target: '—¿Qué haces esta noche? —Salgo con mis amigos.',
      german: '„Was machst du heute Abend?“ – „Ich gehe mit meinen Freunden aus.“',
    },
    {
      target: 'No sé dónde está la estación.',
      german: 'Ich weiß nicht, wo der Bahnhof ist.',
      parts: [
        { text: 'No', role: 'negation' },
        { text: ' sé', role: 'verb' },
        { text: ' dónde', role: 'question' },
        { text: ' está', role: 'verb' },
        { text: ' la estación', role: 'subject' },
        { text: '.' },
      ],
    },
    { target: 'Conozco un restaurante muy bueno.', german: 'Ich kenne ein sehr gutes Restaurant.' },
    { target: 'Pongo la mesa y después cenamos.', german: 'Ich decke den Tisch und danach essen wir zu Abend.' },
    { target: 'Traigo el vino, ¿vale?', german: 'Ich bringe den Wein mit, okay?', variant: 'es-ES' },
    { target: 'Yo traigo el vino, ¿está bien?', german: 'Ich bringe den Wein mit, okay?', variant: 'es-LA' },
    {
      target: '—¿Conoces a Marta? —Sí, pero no sé su número.',
      german: '„Kennst du Marta?“ – „Ja, aber ich weiß ihre Nummer nicht.“',
      parts: [
        { text: '—¿' },
        { text: 'Conoces', role: 'verb' },
        { text: ' a Marta', role: 'object' },
        { text: '? —Sí, pero ' },
        { text: 'no', role: 'negation' },
        { text: ' sé', role: 'verb' },
        { text: ' su número', role: 'object' },
        { text: '.' },
      ],
    },
  ],
  germanComparison: [
    {
      type: 'compare',
      target: 'Sé nadar.',
      german: 'Ich kann schwimmen.',
      md: 'Eine gelernte Fähigkeit ist `saber` + Infinitiv, nicht `poder`. `Puedo nadar` heißt eher: Ich darf/kann (jetzt) schwimmen – z. B. weil das Wasser warm genug ist.',
    },
    {
      type: 'compare',
      target: 'Conozco Madrid. · Sé la dirección.',
      german: 'Ich kenne Madrid. · Ich weiß die Adresse.',
      md: 'Wie im Deutschen: „kennen“ = `conocer`, „wissen“ = `saber`. Die Unterscheidung fällt Deutschsprachigen deshalb leicht.',
    },
    {
      type: 'compare',
      target: 'Pongo la mesa.',
      german: 'Ich decke den Tisch.',
      md: '`poner` = legen, stellen, setzen – ein Verb für alles, wobei man etwas irgendwohin tut.',
    },
    {
      type: 'compare',
      target: 'Hago la cena.',
      german: 'Ich mache/koche das Abendessen.',
      md: '`hacer` deckt „machen“ und „tun“ ab: `hacer deporte`, `hacer la compra` (einkaufen, es-ES), `¿Qué haces?`.',
    },
  ],
  mistakes: [
    { wrong: 'Yo hace la cena.', right: 'Yo hago la cena.', why: 'yo-Form von hacer: `hago`.' },
    { wrong: 'Yo sabo', right: 'Yo sé', why: 'saber: yo → `sé` (mit Akzent).' },
    { wrong: 'Yo conoco', right: 'Yo conozco', why: 'Verben auf -cer: yo → -zco.' },
    { wrong: 'Yo salo', right: 'Yo salgo', why: 'salir gehört zur -go-Familie.' },
    { wrong: 'Conozco que viene mañana.', right: 'Sé que viene mañana.', why: 'Wissen/Informationen (auch „dass …“) → `saber`.' },
  ],
  mnemonic: '**Nur „ich“ tanzt aus der Reihe:** hago, pongo, salgo, traigo – sé, veo, doy – conozco.',
  levels: [
    {
      level: 1,
      title: 'Die yo-Formen',
      exercises: [
        {
          id: 'es.g.yo-irregular.L1.01',
          type: 'matchPairs',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 1,
          instruction: 'Ordne jedem Infinitiv seine yo-Form zu.',
          pairs: [
            { left: 'hacer', right: 'hago' },
            { left: 'poner', right: 'pongo' },
            { left: 'salir', right: 'salgo' },
            { left: 'saber', right: 'sé' },
            { left: 'conocer', right: 'conozco' },
            { left: 'venir', right: 'vengo' },
          ],
          feedback: {
            rule: '-go: hago, pongo, salgo, vengo · -zco: conozco · Sonderform: sé.',
            why: '`sé` ist die kürzeste und überraschendste Form.',
            avoid: 'Lerne die -go-Familie als Reihe: hago, pongo, salgo, traigo, tengo, vengo.',
          },
        },
        {
          id: 'es.g.yo-irregular.L1.02',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 1,
          verb: 'hacer',
          tense: 'Präsens',
          person: 'yo',
          sentence: 'Los domingos ___ la comida para toda la familia.',
          answers: ['hago'],
          feedback: {
            rule: 'hacer: yo → `hago`.',
            why: '`hace` ist er/sie, `haco` gibt es nicht.',
            avoid: 'hacer – hago, wie tener – tengo.',
          },
        },
        {
          id: 'es.g.yo-irregular.L1.03',
          type: 'mc',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 1,
          prompt: '„Ich weiß es nicht.“',
          options: [
            { text: 'No lo sé.', why: 'Richtig: saber → `sé`.' },
            { text: 'No lo sabo.', why: '„sabo“ gibt es nicht.' },
            { text: 'No lo conozco.', why: '`conocer` heißt „kennen“ – für Personen und Orte.' },
          ],
          answer: 0,
          feedback: {
            rule: '„wissen“ = `saber`, yo → `sé`.',
            why: 'Die regelmäßige Form „sabo“ liegt nahe, ist aber falsch.',
            avoid: '`No lo sé` – einer der häufigsten Sätze überhaupt: als Chunk lernen.',
          },
        },
        {
          id: 'es.g.yo-irregular.L1.04',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 1,
          verb: 'salir',
          tense: 'Präsens',
          person: 'yo',
          sentence: 'Hoy no ___ de casa.',
          answers: ['salgo'],
          feedback: {
            rule: 'salir: yo → `salgo`.',
            why: '`salo` gibt es nicht.',
            avoid: 'salir – salgo, poner – pongo: -go.',
          },
        },
      ],
    },
    {
      level: 2,
      title: 'Formen im Satz und saber vs. conocer',
      exercises: [
        {
          id: 'es.g.yo-irregular.L2.01',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 2,
          sentence: 'Yo ___ la mesa y tú ___ el vino.',
          german: 'Ich decke den Tisch und du bringst den Wein mit.',
          answers: [['pongo'], ['traes']],
          bank: ['pongo', 'pones', 'traigo', 'traes'],
          feedback: {
            rule: 'yo → `pongo` (unregelmäßig), tú → `traes` (regelmäßig).',
            why: 'Nur die yo-Form hat das -g-; `traigo` wäre „ich bringe“.',
            avoid: 'Ab tú: normale Endungen.',
          },
        },
        {
          id: 'es.g.yo-irregular.L2.02',
          type: 'cloze',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 2,
          sentence: '¿___ a Pedro? —Sí, pero no ___ dónde vive.',
          german: '„Kennst du Pedro?“ – „Ja, aber ich weiß nicht, wo er wohnt.“',
          answers: [['Conoces'], ['sé']],
          bank: ['Conoces', 'Sabes', 'sé', 'conozco'],
          feedback: {
            rule: 'Person kennen → `conocer a`; Information wissen → `saber`.',
            why: '`Sabes a Pedro` ist falsch; `no conozco dónde` ebenso.',
            avoid: 'kennen = conocer, wissen = saber – wie im Deutschen.',
          },
        },
        {
          id: 'es.g.yo-irregular.L2.03',
          type: 'conjugate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 2,
          verb: 'conocer',
          tense: 'Präsens',
          person: 'yo',
          sentence: '___ un bar muy bueno cerca de aquí.',
          answers: ['conozco'],
          feedback: {
            rule: 'conocer: yo → `conozco`.',
            why: '`conoco` oder `conosco` sind falsch.',
            avoid: 'Verben auf -cer: yo auf -zco (conozco, parezco, ofrezco).',
          },
        },
        {
          id: 'es.g.yo-irregular.L2.04',
          type: 'fixError',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 2,
          sentence: 'Esta noche yo salo con Ana.',
          german: 'Heute Abend gehe ich mit Ana aus.',
          answers: ['Esta noche yo salgo con Ana.', 'Esta noche salgo con Ana.'],
          feedback: {
            rule: 'salir: yo → `salgo`.',
            why: 'Die regelmäßige Bildung „salo“ gibt es nicht.',
            avoid: 'salgo – mit g wie „gehen“.',
          },
        },
        {
          id: 'es.g.yo-irregular.L2.05',
          type: 'listening',
          skills: ['listening', 'grammar'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 2,
          audio: 'Hoy no salgo: hago la cena y veo una película en casa.',
          question: 'Was macht die Person heute Abend?',
          options: [
            'Sie bleibt zu Hause, kocht und schaut einen Film.',
            'Sie geht mit Freunden essen.',
            'Sie geht ins Kino.',
          ],
          answer: 0,
          feedback: {
            rule: '`no salgo` = ich gehe nicht aus; `hago la cena` = ich koche; `veo` = ich sehe.',
            why: '`película` allein bedeutet nicht Kino – sie schaut den Film `en casa`.',
            avoid: 'Hör auf die Verneinung am Anfang: _no salgo_.',
          },
        },
      ],
    },
    {
      level: 3,
      title: 'Freizeit und Verabredungen',
      exercises: [
        {
          id: 'es.g.yo-irregular.L3.01',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Ich weiß nicht, wo das Museum ist.',
          answers: ['No sé dónde está el museo.', 'Yo no sé dónde está el museo.'],
          feedback: {
            rule: '`No sé` + Fragewort mit Akzent + `está`.',
            why: '`No conozco dónde …` ist falsch; das Fragewort `dónde` behält seinen Akzent.',
            avoid: 'wissen, wo/wann/wie → saber.',
          },
        },
        {
          id: 'es.g.yo-irregular.L3.02',
          type: 'translate',
          skills: ['grammar', 'writing'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 3,
          direction: 'toTarget',
          source: 'Ich kenne ein gutes Restaurant.',
          answers: [
            'Conozco un buen restaurante.',
            'Conozco un restaurante bueno.',
            'Yo conozco un buen restaurante.',
            'Yo conozco un restaurante bueno.',
          ],
          feedback: {
            rule: 'Einen Ort kennen → `conozco`; `bueno` vor dem Nomen → `buen`.',
            why: '`Sé un restaurante` ist falsch – Orte „kennt“ man.',
            avoid: 'Personen, Orte, Lokale → conocer.',
          },
        },
        {
          id: 'es.g.yo-irregular.L3.03',
          type: 'translate',
          skills: ['grammar', 'reading'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 3,
          direction: 'toGerman',
          source: 'Los viernes salgo con mis amigos.',
          answers: [
            'Freitags gehe ich mit meinen Freunden aus.',
            'Freitags gehe ich mit meinen Freundinnen aus.',
            'Jeden Freitag gehe ich mit meinen Freunden aus.',
            'Freitags gehe ich mit meinen Freunden weg.',
            'Freitags treffe ich mich mit meinen Freunden.',
          ],
          feedback: {
            rule: '`salir` = ausgehen; `los viernes` = freitags (regelmäßig).',
            why: '„Am Freitag“ wäre `el viernes` (einmalig).',
            avoid: 'los + Wochentag = jeden …',
          },
        },
        {
          id: 'es.g.yo-irregular.L3.04',
          type: 'dialogue',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 3,
          lines: [
            { speaker: 'Marta', text: '¿Qué haces el sábado?', german: 'Was machst du am Samstag?' },
            { speaker: 'Du', text: 'Salgo con Laura. Vamos al cine.', german: 'Ich gehe mit Laura aus. Wir gehen ins Kino.' },
            { speaker: 'Marta', text: '¡Qué bien! ¿Puedo ir también?', german: 'Wie schön! Kann ich auch mitkommen?' },
          ],
          gapIndex: 1,
          options: ['Salgo con Laura. Vamos al cine.', 'Sale con Laura. Van al cine.', 'Salo con Laura. Vamos al cine.'],
          answer: 0,
          feedback: {
            rule: 'Über dich selbst: `salgo` (yo).',
            why: '`sale` wäre er/sie, `salo` gibt es nicht.',
            avoid: 'Auf `¿Qué haces?` antwortest du mit einer yo-Form.',
          },
        },
        {
          id: 'es.g.yo-irregular.L3.05',
          type: 'speakFree',
          skills: ['speaking', 'grammar'],
          topicIds: ['es.g.yo-irregular'],
          difficulty: 3,
          prompt: 'Beschreibe deinen typischen Freitagabend: Was machst du, gehst du aus, wen triffst du?',
          keywords: ['hago', 'salgo', 'pongo', 'vengo', 'traigo', 'sé', 'conozco', 'veo', 'tengo'],
          minMatch: 2,
          sample: 'Los viernes salgo con mis amigos. Normalmente hago la cena en casa y después veo una película.',
          feedback: {
            rule: 'yo-Formen: hago, salgo, veo, conozco …',
            why: 'Beim Sprechen rutschen leicht regelmäßige Formen heraus (`hace`, `salo`).',
            avoid: 'Bereite zwei Sätze vor: „Los viernes salgo …“, „Hago …“.',
          },
        },
      ],
    },
  ],
  related: ['es.g.tener', 'es.g.stem-change', 'es.g.present-regular'],
};
