import type { Stage } from '../types';

export const stages: Stage[] = [
  {
    id: 'stage0',
    courseId: 'pt-BR',
    title: 'Stufe 0 – Erste Schritte & brasilianischer Klang',
    short: 'Stufe 0',
    description:
      'Dein Start ins brasilianische Portugiesisch: Du lernst die typischen **Laute** (Nasalvokale, -ão, „tsch“ vor i), **grüßt** passend, stellst dich mit **ser** und **estar** vor, benennst Dinge mit **Artikel und Plural**, zählst bis **100** und stellst die ersten **Fragen**.',
    goals: [
      'Ich kann Menschen passend begrüßen und mich verabschieden – mit você oder o senhor / a senhora.',
      'Ich spreche die typischen brasilianischen Laute verständlich aus.',
      'Ich kann mich vorstellen: Name, Herkunft, Wohnort, Alter, Sprachen.',
      'Ich unterscheide ser und estar in einfachen Sätzen.',
      'Ich verwende Artikel, Plural und Kontraktionen (do, na …) korrekt.',
      'Ich verstehe und nenne Zahlen bis 100 und einfache Preise.',
    ],
    grammarTopics: [
      'Anrede: você, o senhor, a senhora',
      'Aussprache-Grundlagen',
      'Personalpronomen & a gente',
      'ser',
      'estar',
      'ser oder estar?',
      'Artikel & Genus',
      'Plural',
      'Kontraktionen (do, da, no, na)',
      'Präsens der regelmäßigen Verben',
      'Zahlen 0–100',
      'Fragen & Fragewörter',
    ],
    vocabFields: ['Begrüßung & Abschied', 'Personen & Familie', 'Herkunft & Nationalitäten', 'Berufe', 'Befinden', 'Gegenstände & Orte', 'Zahlen & Preise', 'Sprachen'],
    pronFocus: ['Nasalvokale & -ão', 't/d vor i („tsch“/„dsch“)', 'R am Wortanfang wie „h“', 'lh & nh', 'L am Silbenende wie „u“', 'offene vs. geschlossene Vokale'],
    dialogues: ['Begrüßung unter Freunden', 'Höflich grüßen (o senhor / a senhora)', 'Sich vorstellen', 'Am Kiosk: Wie viel kostet das?'],
    chapters: [
      {
        id: 'pt.s0.c1',
        title: 'Oi, Brasil!',
        description: 'Begrüßen, die Laute des Portugiesischen und die Personalpronomen.',
        lessonIds: ['pt.s0.l01', 'pt.s0.l02', 'pt.s0.l03'],
      },
      {
        id: 'pt.s0.c2',
        title: 'Sein & Dinge benennen',
        description: 'ser und estar, Artikel, Genus, Plural und Kontraktionen.',
        lessonIds: ['pt.s0.l04', 'pt.s0.l05'],
      },
      {
        id: 'pt.s0.c3',
        title: 'Zahlen & Vorstellen',
        description: 'Zahlen bis 100, Preise, regelmäßige Verben und die ersten Fragen.',
        lessonIds: ['pt.s0.l06', 'pt.s0.l07'],
      },
    ],
    finalExamId: 'pt.exam.s0.final',
    bossExamId: 'pt.exam.s0.boss',
    mastery: { finalPct: 70, bossPct: 70, minSkills: { grammar: 40, listening: 30, vocabulary: 30 } },
    available: true,
  },
  {
    id: 'a1',
    courseId: 'pt-BR',
    title: 'A1 – Alltag in Brasilien',
    short: 'A1',
    description:
      'Du bewältigst einfache Alltagssituationen: über Familie, Wohnung und Tagesablauf sprechen, einkaufen, im Restaurant bestellen, nach dem Weg fragen, Pläne machen. Dazu kommen die wichtigsten unregelmäßigen Verben und typisch brasilianische Strukturen wie `estar + Gerundium` und `tem` für „es gibt“.',
    goals: [
      'Ich kann über meine Familie, meine Wohnung und meinen Alltag sprechen.',
      'Ich kann im Restaurant bestellen und einkaufen.',
      'Ich kann Uhrzeiten und Termine vereinbaren.',
      'Ich kann über Pläne sprechen (vou + Infinitiv).',
      'Ich kann sagen, was ich mag und was nicht (gostar de).',
    ],
    grammarTopics: [
      'Unregelmäßige Verben: ter, ir, fazer, poder, querer',
      'ir + Infinitiv (nahe Zukunft)',
      'estar + Gerundium (estou falando)',
      'tem = es gibt',
      'gostar de',
      'Possessivbegleiter (meu, seu, dele, dela)',
      'Reflexive Verben (me chamo, se levantar)',
      'Adjektive: Stellung und Angleichung',
      'Uhrzeit & Datum',
      'Verneinung und kurze Antworten (não, nunca, nada)',
    ],
    vocabFields: ['Familie', 'Wohnen', 'Tagesablauf', 'Essen & Trinken', 'Einkaufen', 'Stadt & Wege', 'Freizeit', 'Wetter'],
    pronFocus: ['R am Silbenende (regionale Varianten)', 's/z am Wortende und vor Konsonant', 'Verbindung von Vokalen im Satz', 'Frage- und Aussagemelodie'],
    dialogues: ['Im Restaurant bestellen', 'Auf dem Markt (feira)', 'Nach dem Weg fragen', 'Verabredung per Telefon', 'Über das Wochenende sprechen'],
    chapters: [
      { id: 'pt.a1.c1', title: 'Familie & Zuhause', description: 'Familie beschreiben, Wohnung, Possessivbegleiter, tem = es gibt.', lessonIds: [] },
      { id: 'pt.a1.c2', title: 'Mein Tag', description: 'Tagesablauf, Uhrzeit, reflexive Verben, estar + Gerundium.', lessonIds: [] },
      { id: 'pt.a1.c3', title: 'Essen, Trinken & Einkaufen', description: 'Bestellen, Preise, gostar de, querer und poder.', lessonIds: [] },
      { id: 'pt.a1.c4', title: 'Unterwegs & Pläne', description: 'Wege, Verkehrsmittel, ir + Infinitiv, Verabredungen.', lessonIds: [] },
    ],
    mastery: { finalPct: 70, bossPct: 70, minSkills: { grammar: 50, listening: 40, speaking: 35, vocabulary: 40 } },
    available: false,
  },
  {
    id: 'a2',
    courseId: 'pt-BR',
    title: 'A2 – Erlebnisse & Vergangenheit',
    short: 'A2',
    description:
      'Du erzählst von Erlebnissen und Gewohnheiten in der Vergangenheit, vergleichst Dinge, gibst Anweisungen und verstehst die Grundzüge der gesprochenen Umgangssprache – etwa Objektpronomen im Stil `eu vi ele`.',
    goals: [
      'Ich kann von vergangenen Ereignissen erzählen.',
      'Ich kann beschreiben, wie etwas früher war.',
      'Ich kann Dinge und Menschen vergleichen.',
      'Ich kann einfache Anweisungen geben und verstehen.',
    ],
    grammarTopics: [
      'Pretérito perfeito (regelmäßig und unregelmäßig)',
      'Pretérito imperfeito',
      'Perfeito vs. imperfeito',
      'Vergleiche (mais … do que, tão … quanto)',
      'Objektpronomen – Norm und brasilianische Umgangssprache',
      'Imperativ (brasilianischer Gebrauch)',
      'já, ainda, ainda não',
      'Präpositionen des Ortes und der Zeit',
    ],
    vocabFields: ['Reisen', 'Gesundheit', 'Arbeit & Studium', 'Kleidung', 'Gefühle', 'Feste & Traditionen'],
    pronFocus: ['Betonung in Verbformen (falou, falamos)', 'Reduktion unbetonter Vokale', 'Rhythmus längerer Sätze'],
    dialogues: ['Vom Urlaub erzählen', 'Beim Arzt', 'Im Hotel reklamieren', 'Kindheitserinnerungen'],
    chapters: [
      { id: 'pt.a2.c1', title: 'Was ist passiert?', description: 'Pretérito perfeito und Zeitangaben.', lessonIds: [] },
      { id: 'pt.a2.c2', title: 'Früher war alles …', description: 'Pretérito imperfeito, Gewohnheiten, Beschreibungen.', lessonIds: [] },
      { id: 'pt.a2.c3', title: 'Vergleiche & Anweisungen', description: 'Komparativ, Imperativ, Objektpronomen.', lessonIds: [] },
    ],
    mastery: { finalPct: 70, bossPct: 70, minSkills: { grammar: 55, listening: 45, speaking: 40, vocabulary: 45 } },
    available: false,
  },
  {
    id: 'b1',
    courseId: 'pt-BR',
    title: 'B1 – Meinungen & Möglichkeiten',
    short: 'B1',
    description:
      'Du äußerst Wünsche, Zweifel und Meinungen, sprichst über Bedingungen und Zukunft und kommst in den meisten Alltags- und Reisesituationen selbstständig zurecht. Kernthema ist der **Subjuntivo**.',
    goals: [
      'Ich kann Wünsche, Hoffnungen und Zweifel ausdrücken.',
      'Ich kann meine Meinung begründen.',
      'Ich kann über Bedingungen und Pläne sprechen.',
      'Ich verstehe die Hauptaussagen von Gesprächen in Standardsprache.',
    ],
    grammarTopics: [
      'Presente do subjuntivo',
      'Futuro do subjuntivo (quando eu tiver …)',
      'Futuro do pretérito (Konditional)',
      'Pretérito perfeito composto (tenho feito)',
      'Relativsätze (que, onde, quem)',
      'Konnektoren (embora, porque, então)',
    ],
    vocabFields: ['Arbeit & Bewerbung', 'Umwelt', 'Medien', 'Wohnen & Nachbarschaft', 'Beziehungen'],
    pronFocus: ['Satzmelodie bei Meinungsäußerungen', 'Umgangssprachliche Verkürzungen (tá, pra, cê)'],
    dialogues: ['Diskussion unter Freunden', 'Vorstellungsgespräch', 'Beschwerde am Telefon'],
    chapters: [
      { id: 'pt.b1.c1', title: 'Wünsche & Zweifel', description: 'Presente do subjuntivo.', lessonIds: [] },
      { id: 'pt.b1.c2', title: 'Wenn … dann', description: 'Futuro do subjuntivo und Konditional.', lessonIds: [] },
      { id: 'pt.b1.c3', title: 'Meine Meinung', description: 'Argumentieren, Relativsätze, Konnektoren.', lessonIds: [] },
    ],
    mastery: { finalPct: 70, bossPct: 70, minSkills: { grammar: 60, listening: 50, speaking: 45, reading: 50 } },
    available: false,
  },
  {
    id: 'b2',
    courseId: 'pt-BR',
    title: 'B2 – Diskutieren & Erzählen',
    short: 'B2',
    description:
      'Du verstehst komplexere Texte und Gespräche, diskutierst spontan und erzählst zusammenhängend. Hinzu kommen der **Imperfeito do subjuntivo**, der **persönliche Infinitiv** und das Passiv.',
    goals: [
      'Ich kann an Diskussionen aktiv teilnehmen.',
      'Ich kann Hypothesen bilden (se eu fosse …).',
      'Ich kann Berichte und Nachrichten verstehen.',
      'Ich kann Erlebtes detailliert und strukturiert erzählen.',
    ],
    grammarTopics: [
      'Imperfeito do subjuntivo',
      'Irreale Bedingungssätze',
      'Infinitivo pessoal (para eles fazerem)',
      'Passiv (ser + Partizip, se-Passiv)',
      'Indirekte Rede',
      'Fortgeschrittene Konnektoren',
    ],
    vocabFields: ['Politik & Gesellschaft', 'Wirtschaft', 'Kultur & Kunst', 'Wissenschaft'],
    pronFocus: ['Regionale Akzente verstehen (Rio, São Paulo, Nordeste, Sul)', 'Schnelles Sprechtempo'],
    dialogues: ['Debatte', 'Präsentation', 'Nachrichten besprechen'],
    chapters: [
      { id: 'pt.b2.c1', title: 'Was wäre, wenn …', description: 'Imperfeito do subjuntivo, irreale Bedingungen.', lessonIds: [] },
      { id: 'pt.b2.c2', title: 'Präzise formulieren', description: 'Persönlicher Infinitiv, Passiv, indirekte Rede.', lessonIds: [] },
    ],
    mastery: { finalPct: 75, bossPct: 75, minSkills: { grammar: 65, listening: 60, speaking: 55, reading: 60 } },
    available: false,
  },
  {
    id: 'c1',
    courseId: 'pt-BR',
    title: 'C1 – Nuancen & Register',
    short: 'C1',
    description:
      'Du bewegst dich sicher zwischen Registern – vom formellen Schreiben bis zur Gíria (Slang) – und verstehst implizite Bedeutungen, Ironie und kulturelle Anspielungen.',
    goals: [
      'Ich kann formelle Texte (E-Mails, Berichte) verfassen.',
      'Ich verstehe Umgangssprache und regionale Ausdrücke.',
      'Ich kann Nuancen und Ironie erkennen.',
    ],
    grammarTopics: [
      'Mais-que-perfeito (simples und composto)',
      'Formelle Pronomenstellung (Enklise, Mesoklise erkennen)',
      'Register: formell vs. umgangssprachlich',
      'Idiomatische Wendungen und Gírias',
    ],
    vocabFields: ['Beruf & Verhandlung', 'Recht & Verwaltung', 'Literatur', 'Humor & Redewendungen'],
    pronFocus: ['Feinheiten der Satzmelodie', 'Emphatische Betonung'],
    dialogues: ['Verhandlung', 'Formelle Rede', 'Stammtischgespräch'],
    chapters: [
      { id: 'pt.c1.c1', title: 'Formell schreiben', description: 'Register, Pronomenstellung, formelle Textsorten.', lessonIds: [] },
      { id: 'pt.c1.c2', title: 'Wie Brasilianer reden', description: 'Gírias, Redewendungen, Ironie.', lessonIds: [] },
    ],
    mastery: { finalPct: 75, bossPct: 75, minSkills: { grammar: 70, listening: 65, speaking: 60, reading: 65, writing: 60 } },
    available: false,
  },
  {
    id: 'c2',
    courseId: 'pt-BR',
    title: 'C2 – Souveräne Sprachbeherrschung',
    short: 'C2',
    description: 'Du verstehst praktisch alles, was du hörst oder liest, und drückst dich spontan, sehr flüssig und präzise aus – auch bei komplexen Themen.',
    goals: [
      'Ich verstehe Literatur, Fachtexte und schnelle Umgangssprache.',
      'Ich kann feine Bedeutungsunterschiede ausdrücken.',
      'Ich kann Stil und Register bewusst wählen.',
    ],
    grammarTopics: ['Stilistische Varianten', 'Literarische Zeitformen', 'Komplexe Satzgefüge'],
    vocabFields: ['Literatur & Poesie', 'Fachsprachen', 'Regionale Wortschätze'],
    pronFocus: ['Akzentreduktion', 'Prosodie in langen Redebeiträgen'],
    dialogues: ['Literaturgespräch', 'Fachvortrag', 'Spontane Diskussion'],
    chapters: [
      { id: 'pt.c2.c1', title: 'Stil & Präzision', description: 'Feine Unterschiede, literarische Sprache.', lessonIds: [] },
    ],
    mastery: { finalPct: 80, bossPct: 80, minSkills: { grammar: 75, listening: 70, speaking: 70, reading: 70, writing: 65 } },
    available: false,
  },
  {
    id: 'native',
    courseId: 'pt-BR',
    title: 'Native Mastery – Trainingsstufe',
    short: 'Native',
    description:
      'Eine **Trainingsstufe** für alle, die über C2 hinaus an Natürlichkeit arbeiten wollen: Aussprache-Feinschliff, regionale Varietäten, Humor, Wortspiele und Alltagskultur. Sie verspricht keinen „Muttersprachler-Status“ – sie bietet gezieltes Training.',
    goals: [
      'Ich trainiere Aussprache und Rhythmus in Richtung einer regionalen Varietät.',
      'Ich verstehe Humor, Wortspiele und kulturelle Anspielungen.',
      'Ich reagiere in schnellen Alltagsgesprächen natürlich.',
    ],
    grammarTopics: ['Umgangssprachliche Grammatik (a gente, ter = haver, Objektpronomen)', 'Regionale Formen (tu, oxente, bah, uai)'],
    vocabFields: ['Gírias nach Region', 'Humor & Memes', 'Popkultur'],
    pronFocus: ['Carioca, Paulistano, Nordestino, Gaúcho – Merkmale erkennen und imitieren'],
    dialogues: ['Schnelles Gespräch unter Freunden', 'Witze erzählen', 'Diskussion über Fußball'],
    chapters: [
      { id: 'pt.native.c1', title: 'Brasilien regional', description: 'Akzente und Wortschätze der Regionen.', lessonIds: [] },
      { id: 'pt.native.c2', title: 'Humor & Kultur', description: 'Wortspiele, Anspielungen, Alltagskultur.', lessonIds: [] },
    ],
    mastery: { finalPct: 80, bossPct: 80, minSkills: {} },
    available: false,
  },
];
