/**
 * Gemeinsame Glossar-Einträge (Funktionswörter) für die brasilianisch-portugiesischen Demo-Lieder.
 * `buildSong` übernimmt nur die Einträge, die ein Song tatsächlich benutzt.
 * Aussprachehilfen: GROSS = betonte Silbe, ã/õ/ẽ/ĩ/ũ = nasal (Luft auch durch die Nase),
 * „sch“ vor Vokal weich wie in „Garage“, „w“ = deutsches w (portugiesisches v).
 */
import type { GlossEntry } from '../types';
import { gl } from './_layout';

export const COMMON_PT: Record<string, GlossEntry> = {
  o: gl('o', 'Artikel (m. Sg.)', 'der/die/das (bestimmter Artikel, männlich)', 'u',
    [['o sol', 'die Sonne'], ['o quintal', 'der Hof']],
    'Ständig.',
    { grammar: 'Unbetontes `o` klingt in Brasilien wie **u** – als Artikel und am Wortende (`bolo` → „BO-lu“).' }),
  a: gl('a', 'Artikel (f. Sg.)', 'die/der/das (bestimmter Artikel, weiblich)', 'a',
    [['a janela', 'das Fenster'], ['a Maria', 'Maria']],
    'Ständig.',
    { grammar: 'Im brasilianischen Alltag steht oft ein Artikel vor Vornamen: `a Maria`, `o João`.' }),
  um: gl('um', 'Artikel (m. Sg.)', 'ein (unbestimmter Artikel, männlich)', 'ũ',
    [['um passarinho', 'ein Vögelchen'], ['um passo', 'ein Schritt']],
    'Ständig.',
    { grammar: 'Nasal: Die Lippen schließen sich kaum – kein deutliches m am Ende. Weiblich: `uma`.' }),
  de: gl('de', 'Präposition', 'von, aus; (Material, Art)', 'dschi',
    [['bolo de milho', 'Maiskuchen'], ['dia de festa', 'Festtag']],
    'Eines der häufigsten Wörter.',
    { grammar: 'Unbetontes `de` klingt in Brasilien meist wie „dschi“ (d vor i-Laut). Mit Artikel: `do`, `da`.' }),
  do: gl('do', 'Präposition + Artikel', 'des, vom (de + o)', 'du',
    [['a sanfona do vovô', 'Opas Akkordeon'], ['Sou do Rio.', 'Ich bin aus Rio.']],
    'Ständig.',
    { form: 'Verschmelzung von `de` + `o`', grammar: '`de` verschmilzt mit Artikeln: `do`, `da`, `dos`, `das`.' }),
  no: gl('no', 'Präposition + Artikel', 'im, am, auf dem (em + o)', 'nu',
    [['no Rio', 'in Rio'], ['no quintal', 'im Hof']],
    'Ständig.',
    { form: 'Verschmelzung von `em` + `o`', grammar: '`em` verschmilzt mit Artikeln: `no`, `na`, `nos`, `nas`.' }),
  na: gl('na', 'Präposition + Artikel', 'in der, an der, auf der (em + a)', 'na',
    [['na janela', 'am Fenster'], ['na praça', 'auf dem Platz']],
    'Ständig.',
    { form: 'Verschmelzung von `em` + `a`' }),
  com: gl('com', 'Präposition', 'mit', 'kõ',
    [['com a gente', 'mit uns'], ['café com leite', 'Milchkaffee']],
    'Ständig.',
    { grammar: 'Nasal ausgesprochen: „kõ“. Besondere Formen: `comigo` (mit mir), `com você` (mit dir).' }),
  e: gl('e', 'Konjunktion', 'und', 'i',
    [['bolo e pinhão', 'Kuchen und Araukariensamen (Pinhão)']],
    'Ständig.',
    { grammar: '`e` (und) klingt wie „i“; `é` (ist) dagegen offen wie „ä“.' }),
  para: gl('para', 'Präposition', 'für; nach; um … zu', 'PA-ra',
    [['para mim', 'für mich'], ['Vou para casa.', 'Ich gehe nach Hause.']],
    'Sehr häufig – gesprochen meist `pra`.'),
  pra: gl('para', 'Präposition (umgangssprachlich)', 'für; nach; um … zu', 'pra',
    [['pra tomar', 'zum Trinken'], ['Vou pra casa.', 'Ich gehe nach Hause.']],
    'Im Gespräch fast immer statt `para`; in formellen Texten `para` schreiben.',
    { form: 'gesprochene Kurzform von `para`', register: 'umgangssprachlich',
      colloquial: '`pra` ist in Brasilien die normale gesprochene Form – überhaupt nicht nachlässig, nur eben nicht schriftlich-formell.' }),
  pro: gl('para o', 'Präposition + Artikel (umgangssprachlich)', 'zum, in den (para + o)', 'pru',
    [['Bora pro quintal!', 'Ab in den Hof!'], ['Vou pro trabalho.', 'Ich gehe zur Arbeit.']],
    'Im Gespräch sehr häufig; weiblich: `pra` (= `para a`).',
    { form: 'gesprochene Verschmelzung von `para` + `o`', register: 'umgangssprachlich',
      colloquial: 'Gesprochenes Brasilianisch: `pro` = `para o`, `pra` = `para a`.' }),
  eu: gl('eu', 'Personalpronomen', 'ich', 'E-u',
    [['Eu estou feliz.', 'Ich bin glücklich.']],
    'Ständig.',
    { grammar: 'Wie ein kurzes „e“ mit angehängtem „u“ – nicht wie deutsches „eu“ (oi)! In Brasilien wird `eu` oft mitgesagt, obwohl die Verbform die Person zeigt.' }),
  meu: gl('meu', 'Possessivbegleiter (m.)', 'mein', 'ME-u',
    [['meu amigo', 'mein Freund']],
    'Ständig.',
    { grammar: 'Passt sich an das Nomen an: `meu amigo`, `minha amiga`, `meus amigos`.' }),
  me: gl('me', 'Objektpronomen', 'mich, mir', 'mi',
    [['O sol vem me acordar.', 'Die Sonne kommt mich wecken.'], ['Me ajuda?', 'Hilfst du mir?']],
    'Ständig.',
    { grammar: 'In Brasilien steht `me` meist **vor** dem Verb bzw. Infinitiv: `me acordar`, `me ajuda`.' }),
};
