/**
 * Gemeinsame Glossar-Einträge (Funktionswörter) für die spanischen Demo-Lieder.
 * `buildSong` übernimmt nur die Einträge, die ein Song tatsächlich benutzt.
 * Aussprachehilfen sind variantenneutral (keine c/z-Wörter).
 */
import type { GlossEntry } from '../types';
import { gl } from './_layout';

export const COMMON_ES: Record<string, GlossEntry> = {
  el: gl('el', 'Artikel (m. Sg.)', 'der/die/das (bestimmter Artikel, männlich)', 'el',
    [['el sol', 'die Sonne'], ['el corazón', 'das Herz']],
    'Ständig – steht vor männlichen Nomen im Singular.',
    { grammar: 'Ohne Akzent = Artikel; mit Akzent (`él`) = „er“.' }),
  la: gl('la', 'Artikel (f. Sg.)', 'die/der/das (bestimmter Artikel, weiblich)', 'la',
    [['la calle', 'die Straße'], ['la lluvia', 'der Regen']],
    'Ständig – steht vor weiblichen Nomen im Singular.',
    { grammar: 'Das Geschlecht stimmt oft nicht mit dem Deutschen überein: `la calle` (die Straße), aber `la lluvia` (der Regen).' }),
  los: gl('los', 'Artikel (m. Pl.)', 'die (Plural, männlich oder gemischt)', 'los',
    [['todos los colores', 'alle Farben'], ['los amigos', 'die Freunde']],
    'Ständig.'),
  las: gl('las', 'Artikel (f. Pl.)', 'die (Plural, weiblich)', 'las',
    [['las flores', 'die Blumen'], ['las manos', 'die Hände']],
    'Ständig.'),
  un: gl('un', 'Artikel (m. Sg.)', 'ein (unbestimmter Artikel, männlich)', 'un',
    [['un señor', 'ein Herr'], ['un día', 'ein Tag']],
    'Ständig.',
    { grammar: 'Weiblich: `una`. Plural `unos/unas` = einige.' }),
  una: gl('una', 'Artikel (f. Sg.)', 'eine (unbestimmter Artikel, weiblich)', 'U-na',
    [['una canción', 'ein Lied'], ['una sonrisa', 'ein Lächeln']],
    'Ständig.'),
  a: gl('a', 'Präposition', 'zu, nach, an; um (Uhrzeit)', 'a',
    [['Voy a la plaza.', 'Ich gehe zum Platz.'], ['a las once', 'um elf Uhr']],
    'Eines der häufigsten Wörter.',
    { grammar: '`a` + `el` wird zu `al`. In `ir a` + Infinitiv drückt es Pläne aus: `vamos a bailar`. Vor Personen als Objekt: `a mi abuela`.' }),
  al: gl('al', 'Präposition + Artikel', 'zum, zur; beim (a + el)', 'al',
    [['al pasar', 'im Vorbeigehen'], ['Voy al parque.', 'Ich gehe zum Park.']],
    'Sehr häufig.',
    { form: 'Verschmelzung von `a` + `el`', grammar: '`al` + Infinitiv = „beim …“ / „als …“: `al llegar` = beim Ankommen.' }),
  de: gl('de', 'Präposition', 'von, aus; (Zugehörigkeit, Material)', 'de',
    [['noches de Madrid', 'Madrider Nächte'], ['Soy de Berlín.', 'Ich komme aus Berlin.']],
    'Eines der häufigsten Wörter.',
    { grammar: 'Spanisch verbindet Nomen oft mit `de`, wo Deutsch ein zusammengesetztes Wort bildet: `pan de maíz` = Maisbrot.' }),
  en: gl('en', 'Präposition', 'in, an, auf', 'en',
    [['en la plaza', 'auf dem Platz'], ['en mi ventana', 'an meinem Fenster']],
    'Ständig.',
    { grammar: '`en` deckt deutsch „in“, „an“ und „auf“ ab – immer dann, wenn etwas irgendwo **ist**.' }),
  con: gl('con', 'Präposition', 'mit', 'kon',
    [['con el corazón', 'von Herzen'], ['café con leche', 'Milchkaffee']],
    'Ständig.',
    { grammar: 'Besondere Formen: `conmigo` (mit mir), `contigo` (mit dir).' }),
  para: gl('para', 'Präposition', 'für; um … zu', 'PA-ra',
    [['para ti', 'für dich'], ['para empezar', 'zum Anfangen']],
    'Sehr häufig.',
    { grammar: 'Nach `para` stehen `mí` und `ti` (nicht `yo`/`tú`): `para mí`, `para ti`. Mit Infinitiv: Zweck („um … zu“).' }),
  por: gl('por', 'Präposition', 'durch, entlang; wegen; für', 'por',
    [['por la Gran Vía', 'die Gran Vía entlang'], ['por la mañana', 'am Morgen']],
    'Sehr häufig.',
    { grammar: '`por` zeigt Weg, Grund oder Zeitraum; `para` zeigt Ziel und Zweck.' }),
  sobre: gl('sobre', 'Präposition', 'auf, über', 'ßO-bre',
    [['sobre la mesa', 'auf dem Tisch'], ['un libro sobre Madrid', 'ein Buch über Madrid']],
    'Häufig.'),
  y: gl('y', 'Konjunktion', 'und', 'i',
    [['tú y yo', 'du und ich']],
    'Ständig.',
    { grammar: 'Vor einem i-Laut (`i-`, `hi-`) wird `y` zu `e`: `padre e hijo` – aber `agua y hielo`, weil `hie-` wie „je“ klingt.' }),
  pero: gl('pero', 'Konjunktion', 'aber', 'PE-ro',
    [['Es pequeña, pero bonita.', 'Sie ist klein, aber hübsch.']],
    'Ständig.',
    { grammar: 'Einfaches r: Die Zunge tippt nur einmal an. `pero` (aber) ≠ `perro` (Hund, gerolltes rr).' }),
  que: gl('que', 'Relativpronomen', 'der, die, das (welcher …)', 'ke',
    [['un señor que vende flores', 'ein Herr, der Blumen verkauft']],
    'Ständig.',
    { grammar: 'Ohne Akzent verbindet `que` Sätze. Mit Akzent (`qué`) fragt es „was?“.' }),
  'que.conj': gl('que', 'Konjunktion', 'dass', 'ke',
    [['Decid que sí.', 'Sagt ja. (wörtl.: Sagt, dass ja.)'], ['Creo que sí.', 'Ich glaube schon.']],
    'Ständig.',
    { grammar: '`decir que sí/no` = ja/nein sagen. Im Spanischen darf `que` nie weggelassen werden (anders als deutsch „ich glaube, er kommt“).' }),
  'que.causal': gl('que', 'Konjunktion', 'denn, weil (begründend)', 'ke',
    [['Date prisa, que llegamos tarde.', 'Beeil dich, sonst kommen wir zu spät.']],
    'Im Gespräch sehr häufig, in Texten seltener.',
    { register: 'umgangssprachlich', colloquial: 'Typisch gesprochen: `que` am Satzanfang liefert eine schnelle Begründung – wie deutsch „…, denn …“ oder „…, ist ja …“.' }),
  yo: gl('yo', 'Personalpronomen', 'ich', 'jo',
    [['Yo estoy bien.', 'Mir geht es gut.']],
    'Häufig – aber oft weggelassen.',
    { grammar: 'Die Verbendung zeigt schon die Person. `yo` steht nur zur Betonung: „ICH jedenfalls …“.' }),
  'tú': gl('tú', 'Personalpronomen', 'du', 'tu',
    [['¿Y tú?', 'Und du?']],
    'Häufig, informell.',
    { grammar: 'Mit Akzent = „du“; ohne Akzent (`tu`) = „dein“.' }),
  'mí': gl('mí', 'Pronomen (nach Präposition)', 'mich, mir (betont)', 'mi',
    [['para mí', 'für mich'], ['A mí me gusta.', 'Mir gefällt es.']],
    'Sehr häufig.',
    { grammar: 'Mit Akzent = Pronomen nach Präpositionen; ohne Akzent (`mi`) = „mein“. Ausnahme: `conmigo` (mit mir).' }),
  ti: gl('ti', 'Pronomen (nach Präposition)', 'dich, dir (betont)', 'ti',
    [['para ti', 'für dich'], ['A ti te gusta.', 'Dir gefällt es.']],
    'Sehr häufig.',
    { grammar: '`ti` hat nie einen Akzent. Ausnahme: `contigo` (mit dir).' }),
  me: gl('me', 'Objekt-/Reflexivpronomen', 'mich, mir', 'me',
    [['Me llama.', 'Er/Sie ruft mich an.'], ['Me ducho.', 'Ich dusche (mich).']],
    'Ständig.',
    { grammar: 'Steht vor dem konjugierten Verb: reflexiv (`me ducho`), direktes Objekt (`me llama`) oder indirektes Objekt (`me gusta`).' }),
  te: gl('te', 'Objekt-/Reflexivpronomen', 'dich, dir', 'te',
    [['¿Te gusta?', 'Gefällt es dir?']],
    'Ständig.',
    { grammar: 'Ohne Akzent! `té` mit Akzent heißt „Tee“.' }),
  le: gl('le', 'indirektes Objektpronomen', 'ihm, ihr, Ihnen', 'le',
    [['A mi abuela le gusta bailar.', 'Meine Oma tanzt gern.']],
    'Sehr häufig.',
    { grammar: 'Bei `gustar` nennt man die Person oft doppelt: `a mi abuela` + `le`. Das ist korrekt und üblich.' }),
  nos: gl('nos', 'Objekt-/Reflexivpronomen', 'uns', 'nos',
    [['Nos vemos.', 'Wir sehen uns.'], ['¿Qué nos gusta?', 'Was gefällt uns?']],
    'Ständig.'),
  se: gl('se', 'Reflexivpronomen (3. Person)', 'sich', 'ße',
    [['La gente se ríe.', 'Die Leute lachen.'], ['Se pone a tocar.', 'Er fängt an zu spielen.']],
    'Ständig.',
    { grammar: 'Gehört zu reflexiven Verben wie `reírse`, `ponerse`. Im Deutschen fällt das „sich“ oft weg.' }),
  mi: gl('mi', 'Possessivbegleiter', 'mein, meine', 'mi',
    [['mi vecina', 'meine Nachbarin'], ['mi corazón', 'mein Herz']],
    'Ständig.',
    { grammar: '`mi` gilt für männliche und weibliche Nomen; Plural: `mis`. Ohne Akzent (mit Akzent `mí` = mich/mir).' }),
  mis: gl('mis', 'Possessivbegleiter (Pl.)', 'meine', 'mis',
    [['mis manos', 'meine Hände'], ['mis amigos', 'meine Freunde']],
    'Ständig.'),
  tu: gl('tu', 'Possessivbegleiter', 'dein, deine', 'tu',
    [['tu voz', 'deine Stimme'], ['tu casa', 'dein Haus']],
    'Ständig.',
    { grammar: 'Ohne Akzent = „dein“; mit Akzent (`tú`) = „du“. Plural: `tus`.' }),
  sus: gl('sus', 'Possessivbegleiter (Pl.)', 'seine, ihre, Ihre', 'ßus',
    [['sus tejas', 'seine Dachziegel (die des Hauses)'], ['sus amigos', 'seine/ihre Freunde']],
    'Ständig.',
    { grammar: '`su/sus` kann „sein“, „ihr“ und „Ihr“ (Sie-Form) bedeuten – der Zusammenhang entscheidet.' }),
  no: gl('no', 'Adverb (Verneinung)', 'nicht; nein', 'no',
    [['No es triste.', 'Er ist nicht traurig.'], ['No, gracias.', 'Nein, danke.']],
    'Ständig.',
    { grammar: '`no` steht direkt vor dem Verb – und vor Objektpronomen: `no me gusta`.' }),
  ya: gl('ya', 'Adverb', 'schon; jetzt, gleich', 'ja',
    [['Ya sale el sol.', 'Schon geht die Sonne auf.'], ['¡Ya voy!', 'Ich komme gleich!']],
    'Sehr häufig.'),
  todos: gl('todos', 'Begleiter/Pronomen (m. Pl.)', 'alle', 'TO-dos',
    [['todos los colores', 'alle Farben'], ['Todos bailamos.', 'Wir tanzen alle.']],
    'Sehr häufig.',
    { grammar: 'Vor einem Nomen folgt noch der Artikel: `todos los días` (jeden Tag).' }),
};
