/**
 * „Bom dia, Rio“ – Originales Lernlied (Bossa Nova, pt-BR, A1).
 * Tempo halbiert notiert (64 statt 128 bpm): ein Takt = zwei Bossa-Takte; jede Zeile füllt genau einen Takt.
 * Lautschrift: GROSS = betont, ã/õ/ẽ/ĩ/ũ = nasal, „w“ = portugiesisches v, „sch“ vor Vokal weich wie in „Garage“.
 */
import type { Song } from '../types';
import { COMMON_PT } from './_common-pt';
import { buildSong, gl, type LineDraft } from './_layout';

const verse1: LineDraft[] = [
  {
    src: 'Bom{bom-dia} dia{bom-dia}, Rio! Bom{bom-dia} dia{bom-dia}, mar!',
    bars: 1,
    natural: 'Guten Morgen, Rio! Guten Morgen, Meer!',
    literal: 'Guter Tag, Rio! Guter Tag, Meer!',
    phonetic: 'bõ DSCHI-a, HI-u! bõ DSCHI-a, MAH!',
    ipa: 'bõ ˈdʒi.ɐ ˈhi.u | bõ ˈdʒi.ɐ ˈmah',
    difficulty: 1,
    summary: 'Die Sängerin begrüßt am Morgen ihre Stadt und das Meer.',
    grammar: [
      ['bom dia – Singular', 'Anders als im Spanischen steht der Gruß im **Singular**: `bom dia`. Nachmittags `boa tarde`, abends `boa noite`.'],
      ['d vor i = „dsch“', '`dia` klingt in Brasilien wie „DSCHI-a“: **d** vor i (und vor unbetontem e) wird zu „dsch“. Das r am Wortanfang (`Rio`) klingt wie ein kräftiges h.'],
    ],
    culture: '**Rio de Janeiro** liegt direkt am Atlantik – vom Zuckerhut bis Copacabana ist das Meer überall. Die Menschen aus Rio heißen `cariocas`.',
    alternatives: [
      ['Olá, Rio! Olá, mar!', 'Hallo, Rio! Hallo, Meer!'],
      ['Bom dia, cidade!', 'Guten Morgen, Stadt!'],
    ],
    everyday: '`Bom dia!` sagst du bis Mittag zu allen – im Bus, beim Bäcker, im Aufzug.',
  },
  {
    src: 'O sol já vem me acordar.',
    bars: 1,
    natural: 'Die Sonne kommt schon, um mich zu wecken.',
    literal: 'Die Sonne schon kommt mich wecken.',
    phonetic: 'u ßÓU SCHA wẽj mi a-koh-DAH',
    difficulty: 2,
    summary: 'Die Sonne weckt die Sängerin – ein sanfter, heller Morgen.',
    grammar: [
      ['Pronomen vor dem Verb', '`me acordar` = mich wecken. In Brasilien steht das Pronomen meist **vor** dem Verb bzw. Infinitiv – in Portugal eher dahinter (`acordar-me`).', 'pt.g.pronouns'],
      ['vir + Infinitiv', '`vem me acordar` = kommt, um mich zu wecken. Nach Bewegungsverben folgt der Infinitiv direkt.'],
    ],
    alternatives: [
      ['O sol me acorda.', 'Die Sonne weckt mich.'],
      ['O sol já está me acordando.', 'Die Sonne weckt mich schon.', 'Verlaufsform'],
    ],
    everyday: '`Me acorda às sete?` – Weckst du mich um sieben? – ganz alltäglich.',
    verbs: [
      ['vem', 'vir', 'Presente, 3. Person Singular – unregelmäßig'],
      ['acordar', 'acordar', 'Infinitiv – wecken / aufwachen'],
    ],
  },
  {
    src: 'Na janela, um passarinho',
    natural: 'Am Fenster sitzt ein Vögelchen',
    literal: 'Im Fenster, ein Vögelchen',
    phonetic: 'na scha-NÄ-la, ũ pa-ßa-RI-nju',
    difficulty: 1,
    summary: 'Ein kleiner Vogel sitzt am Fenster.',
    grammar: [
      ['na = em + a', '`na janela` = am/im Fenster. **em + a** verschmilzt zu **na** – wie deutsch „in dem“ → „im“.', 'pt.g.contractions'],
      ['Verkleinerung -inho', '`passarinho` = `pássaro` + **-inho**: kleiner Vogel – klingt zärtlich.'],
    ],
    alternatives: [
      ['Tem um passarinho na janela.', 'Am Fenster ist ein Vögelchen.', 'gesprochen: tem = es gibt'],
      ['Na janela há um pássaro.', 'Am Fenster ist ein Vogel.', 'eher schriftlich'],
    ],
    everyday: '`passarinho` ist im Alltag viel häufiger als `pássaro` – Brasilien liebt Verkleinerungen.',
  },
  {
    src: 'Canta para mim baixinho.',
    natural: 'und singt leise für mich.',
    literal: 'Singt für mich leisechen.',
    phonetic: 'KÃN-ta PA-ra MĨ bai-SCHI-nju',
    difficulty: 1,
    summary: 'Der Vogel singt leise – nur für die Sängerin.',
    grammar: [
      ['Präsens: er/sie/es-Form', '`canta` = (er/sie/es) singt. Verben auf **-ar**: `cantar` → `canta`.', 'pt.g.present-regular'],
      ['para mim', 'Nach Präpositionen steht `mim`: `para mim` (für mich). Nasal: „mĩ“ – kein deutliches m am Ende.', 'pt.g.pronouns'],
    ],
    alternatives: [
      ['Canta pra mim baixinho.', 'Singt leise für mich.', 'gesprochen: pra statt para'],
      ['Canta bem baixinho.', 'Singt ganz leise.'],
    ],
    everyday: 'Gesprochen sagt man meist `pra mim`. `baixinho` = ganz leise: `Fala baixinho!` (Sprich leise!)',
    verbs: [['canta', 'cantar', 'Presente, 3. Person Singular – regelmäßiges -ar-Verb']],
  },
];

const chorus: LineDraft[] = [
  {
    src: 'Bom{bom-dia} dia{bom-dia}, Rio, tudo{tudo-bem} bem{tudo-bem}?',
    natural: 'Guten Morgen, Rio, alles gut?',
    literal: 'Guter Tag, Rio, alles gut?',
    phonetic: 'bõ DSCHI-a, HI-u, TU-du BẼJ?',
    difficulty: 1,
    summary: 'Der Refrain: ein freundlicher Gruß an die Stadt – wie an eine alte Freundin.',
    grammar: [
      ['Frage nur mit der Stimme', 'Ja/Nein-Fragen bildet man im Portugiesischen oft nur mit der **Stimme** (am Ende steigend): `Tudo bem?`', 'pt.g.questions'],
    ],
    idioms: [['Tudo bem?', 'Alles gut? / Wie geht’s?', 'Antwort: `Tudo bem!` oder `Tudo ótimo!`']],
    colloquial: '`Tudo bem?` ist der lockere Alltagsgruß in Brasilien – man fragt und antwortet oft mit denselben Worten: „Tudo bem?“ – „Tudo bem!“. Ebenso üblich: `Tudo bom?`, `Beleza?`',
    alternatives: [
      ['Bom dia, Rio, como vai?', 'Guten Morgen, Rio, wie geht’s?', 'etwas förmlicher'],
      ['Oi, Rio, tudo bom?', 'Hi, Rio, alles gut?', 'sehr locker'],
    ],
    everyday: 'Du wirst `Tudo bem?` dutzendfach am Tag hören – unverzichtbar!',
  },
  {
    src: 'Eu estou feliz, meu{meu-bem} bem{meu-bem}.',
    natural: 'Ich bin glücklich, mein Schatz.',
    literal: 'Ich bin glücklich, mein Gut.',
    phonetic: 'E-u is-TO fe-LIS, ME-u BẼJ',
    difficulty: 1,
    summary: 'Die Antwort: Es geht gut, die Sängerin ist glücklich.',
    grammar: [
      ['estar für Gefühle', '`estou feliz` = ich bin (gerade) glücklich. Stimmungen → **estar**. `Sou feliz` = ich bin ein glücklicher Mensch.', 'pt.g.ser-estar'],
      ['estou', '`estar` im Präsens: `estou, está, estamos, estão`.', 'pt.g.estar'],
    ],
    idioms: [['meu bem', 'mein Schatz, Liebling', 'wörtlich „mein Gut“ – sehr verbreitetes Kosewort']],
    alternatives: [
      ['Tô feliz, meu bem.', 'Bin glücklich, Schatz.', 'gesprochen: tô = estou'],
      ['Estou muito feliz.', 'Ich bin sehr glücklich.'],
    ],
    everyday: '`Estou feliz` ist alltäglich; gesprochen oft `tô feliz`. `Meu bem` hört man unter Paaren, in der Familie und in Liedern.',
    verbs: [['estou', 'estar', 'Presente, 1. Person Singular – unregelmäßig']],
  },
  {
    src: 'A vida é boa no Rio',
    bars: 1,
    natural: 'Das Leben in Rio ist schön,',
    literal: 'Das Leben ist gut im Rio',
    phonetic: 'a WI-da Ä BO-a nu HI-u',
    difficulty: 1,
    summary: 'Eine Liebeserklärung an die Stadt: Hier lässt es sich gut leben.',
    grammar: [
      ['ser für Eigenschaften', '`a vida é boa` – eine allgemeine Einschätzung → **ser**.', 'pt.g.ser'],
      ['no = em + o', '`no Rio` = in Rio. Die Stadt hat einen Artikel (`o Rio`), deshalb **em + o = no**. Bei São Paulo dagegen: `em São Paulo`.', 'pt.g.contractions'],
      ['boa – weiblich', '`bom` (m) → `boa` (f): `a vida é boa`, `o dia é bom`.', 'pt.g.articles-gender'],
    ],
    ambiguity: '`rio` heißt wörtlich „Fluss“: Rio de Janeiro bedeutet „Fluss des Januar“ – die Portugiesen hielten die Bucht im Januar 1502 für eine Flussmündung.',
    alternatives: [
      ['A vida no Rio é boa.', 'Das Leben in Rio ist gut.'],
      ['É bom viver no Rio.', 'Es ist schön, in Rio zu leben.'],
    ],
    everyday: '`A vida é boa` ist eine typisch brasilianische, gelassene Feststellung.',
    verbs: [['é', 'ser', 'Presente, 3. Person Singular']],
  },
  {
    src: 'O ano inteiro.',
    natural: 'das ganze Jahr über.',
    literal: 'Das Jahr ganz.',
    phonetic: 'u Ã-nu ĩ-TEJ-ru',
    difficulty: 1,
    summary: 'Nicht nur im Urlaub: In Rio ist das Leben das ganze Jahr über schön.',
    grammar: [
      ['Adjektiv hinter dem Nomen', '`o ano inteiro` = das ganze Jahr. `inteiro` (ganz) steht hinter dem Nomen und passt sich an: `a semana inteira` (die ganze Woche).', 'pt.g.articles-gender'],
    ],
    culture: 'Auch im Rio-„Winter“ (Juni bis August) ist es meist über 20 °C warm – Strandwetter gibt es fast das ganze Jahr.',
    alternatives: [
      ['O ano todo.', 'Das ganze Jahr.', 'sehr alltäglich'],
      ['Todos os dias.', 'Jeden Tag.'],
    ],
    everyday: '`o ano inteiro` und `o ano todo` sind beide ganz alltäglich.',
  },
];

const verse2: LineDraft[] = [
  {
    src: 'A{a-gente} gente{a-gente} toma um cafezinho',
    natural: 'Wir trinken einen kleinen Kaffee',
    literal: 'Die Leute nimmt ein Käffchen',
    phonetic: 'a SCHẼN-tschi TO-ma ũ ka-fä-SI-nju',
    difficulty: 2,
    summary: 'Gemeinsames Kaffeetrinken – ein kleines Ritual am Morgen.',
    grammar: [
      ['a gente = wir', '`a gente` (wörtlich „die Leute“) heißt im Alltag **wir**. Das Verb steht aber in der **3. Person Singular**: `a gente toma` (nicht `tomamos`).', 'pt.g.pronouns'],
      ['tomar café', 'Getränke „nimmt“ man: `tomar café`, `tomar água`.', 'pt.g.present-regular'],
    ],
    colloquial: '`a gente` statt `nós` ist in Brasilien die normale gesprochene Form für „wir“. `nós` klingt im Gespräch oft etwas förmlicher.',
    culture: 'Der **cafezinho** ist ein kleiner, starker, meist süßer Kaffee – in Brasilien ein Zeichen von Gastfreundschaft. Man bietet ihn Gästen, Kunden und Kollegen an.',
    alternatives: [
      ['Nós tomamos um cafezinho.', 'Wir trinken einen Kaffee.', 'Standardsprache mit nós'],
      ['Vamos tomar um café?', 'Trinken wir einen Kaffee?'],
    ],
    everyday: '`Aceita um cafezinho?` (Möchten Sie einen Kaffee?) hörst du überall in Brasilien.',
    verbs: [['toma', 'tomar', 'Presente, 3. Person Singular – mit a gente („wir“)']],
  },
  {
    src: 'E conversa um pouquinho.',
    natural: 'und plaudern ein bisschen.',
    literal: 'Und unterhält-sich ein bisschen.',
    phonetic: 'i kõ-WÄH-ßa ũ po-KI-nju',
    difficulty: 1,
    summary: 'Zum Kaffee gehört ein kleiner Plausch.',
    grammar: [
      ['Subjekt bleibt a gente', '`conversa` steht in der 3. Person Singular, weil das Subjekt noch `a gente` ist (= wir plaudern).', 'pt.g.pronouns'],
      ['um pouquinho', '`um pouco` = ein bisschen; `um pouquinho` = ein klein bisschen (Verkleinerung).'],
    ],
    alternatives: [
      ['E a gente conversa um pouco.', 'Und wir plaudern ein wenig.'],
      ['E a gente bate um papo.', 'Und wir quatschen ein bisschen.', 'bater papo = quatschen (umgangssprachlich)'],
    ],
    everyday: '`conversar` = sich unterhalten – ganz alltäglich. `um pouquinho` klingt freundlich und bescheiden.',
    verbs: [['conversa', 'conversar', 'Presente, 3. Person Singular – Subjekt a gente']],
  },
  {
    src: 'Meu amigo está na praça,',
    natural: 'Mein Freund ist auf dem Platz,',
    literal: 'Mein Freund ist in-dem Platz,',
    phonetic: 'ME-u a-MI-gu is-TA na PRA-ßa',
    difficulty: 1,
    summary: 'Ein Freund ist draußen auf dem Platz.',
    grammar: [
      ['estar für den Ort', 'Wo sich jemand gerade befindet → **estar**: `está na praça`.', 'pt.g.estar'],
      ['na = em + a', '`na praça` = auf dem Platz. `praça` ist weiblich → `na`.', 'pt.g.contractions'],
    ],
    alternatives: [
      ['Meu amigo tá na praça.', 'Mein Freund ist auf dem Platz.', 'gesprochen: tá = está'],
      ['Minha amiga está na praça.', 'Meine Freundin ist auf dem Platz.'],
    ],
    everyday: 'Ganz alltäglich. Gesprochen oft `tá` statt `está`.',
    verbs: [['está', 'estar', 'Presente, 3. Person Singular – Ort']],
  },
  {
    src: 'Toca violão de{de-graca} graça{de-graca}.',
    natural: 'Er spielt einfach so Gitarre – gratis.',
    literal: 'Spielt Gitarre aus Gnade.',
    phonetic: 'TO-ka wi-o-LÃU dschi GRA-ßa',
    difficulty: 2,
    summary: 'Der Freund spielt Gitarre für alle – ohne Geld dafür zu verlangen.',
    grammar: [
      ['tocar = spielen (Instrument)', '`tocar violão` = Gitarre spielen. Bei Instrumenten steht im Brasilianischen oft **kein Artikel**.', 'pt.g.present-regular'],
      ['-ão', '`violão` endet auf den Nasal-Doppellaut **ão**: Mund öffnen, „au“ durch die Nase.'],
    ],
    idioms: [['de graça', 'umsonst, gratis']],
    ambiguity: '`graça` heißt auch „Anmut“ und „Witz“ (`Que graça!` = Wie süß!). `de graça` = gratis – aber man hört mit: Er spielt mit Anmut.',
    culture: 'Der **violão** (Akustikgitarre mit Nylonsaiten) ist das Herz der Bossa Nova. Achtung: `guitarra` ist in Brasilien die E-Gitarre!',
    alternatives: [
      ['Toca violão sem cobrar nada.', 'Er spielt Gitarre, ohne etwas zu verlangen.'],
      ['Toca violão pra todo mundo.', 'Er spielt Gitarre für alle.'],
    ],
    everyday: '`de graça` brauchst du oft: `A entrada é de graça.` – Der Eintritt ist frei.',
    verbs: [['toca', 'tocar', 'Presente, 3. Person Singular – regelmäßiges -ar-Verb']],
  },
];

const bridge: LineDraft[] = [
  {
    src: 'Que{que-horas} horas{que-horas} são{que-horas}? Tanto{tanto-faz} faz{tanto-faz}!',
    natural: 'Wie spät ist es? Egal!',
    literal: 'Welche Stunden sind? So-viel macht!',
    phonetic: 'ki O-ras ßÃU? TÃN-tu FAS',
    difficulty: 2,
    summary: 'Die Zeit spielt keine Rolle – heute gibt es keinen Stress.',
    grammar: [
      ['Que horas são?', 'Nach der Uhrzeit fragt man im **Plural**: `Que horas são?` (wörtlich „Welche Stunden sind es?“). Antwort: `São duas horas.` / `É uma hora.`', 'pt.g.questions'],
    ],
    idioms: [['Tanto faz!', 'Egal! / Ist mir gleich.', 'sehr häufig im Alltag']],
    alternatives: [
      ['Que horas são? Não importa!', 'Wie spät ist es? Egal!'],
      ['Que horas são? Não sei.', 'Wie spät ist es? Weiß nicht.'],
    ],
    everyday: 'Beides brauchst du täglich: `Que horas são?` und `Tanto faz` (z. B. „Kino oder Strand?“ – „Tanto faz!“).',
    verbs: [
      ['são', 'ser', 'Presente, 3. Person Plural – Uhrzeit'],
      ['faz', 'fazer', 'Presente, 3. Person Singular – in der Wendung tanto faz'],
    ],
  },
  {
    src: 'Hoje eu vivo devagar.',
    natural: 'Heute lebe ich ganz langsam.',
    literal: 'Heute ich lebe langsam.',
    phonetic: 'O-schi E-u WI-wu dschi-wa-GAH',
    difficulty: 1,
    summary: 'Der Vorsatz für den Tag: langsam leben, ohne Eile.',
    grammar: [
      ['Präsens: ich-Form auf -o', '`vivo` = ich lebe. Verben auf **-er/-ir** enden in der ich-Form auf **-o**: `viver` → `vivo`.', 'pt.g.present-regular'],
    ],
    culture: 'Die Bossa Nova besingt oft genau das: den entspannten Rhythmus des Lebens am Meer.',
    alternatives: [
      ['Hoje eu vou devagar.', 'Heute lasse ich es langsam angehen.'],
      ['Hoje não tenho pressa.', 'Heute habe ich keine Eile.'],
    ],
    everyday: '`devagar` hörst du oft: `Fala devagar, por favor!` – Sprich bitte langsam!',
    verbs: [['vivo', 'viver', 'Presente, 1. Person Singular – regelmäßiges -er-Verb']],
  },
  {
    src: 'Onde você está, amor?',
    natural: 'Wo bist du, Liebling?',
    literal: 'Wo du bist, Liebe?',
    phonetic: 'ÕN-dschi wo-ßE is-TA, a-MOH?',
    difficulty: 1,
    summary: 'Die Sängerin sucht jemanden – die geliebte Person fehlt noch.',
    grammar: [
      ['Fragewort onde', '`Onde …?` = Wo? Die Wortstellung bleibt oft wie im Aussagesatz: `Onde você está?`', 'pt.g.questions'],
      ['você = du', 'In Brasilien ist **você** die normale Anrede für „du“ – mit dem Verb in der 3. Person: `você está`.', 'pt.g.pronouns'],
    ],
    alternatives: [
      ['Cadê você, amor?', 'Wo bist du, Liebling?', 'umgangssprachlich: cadê = wo ist'],
      ['Onde você está agora?', 'Wo bist du jetzt?'],
    ],
    everyday: '`Onde você está?` – der Klassiker am Telefon.',
    verbs: [['está', 'estar', 'Presente, 3. Person Singular – mit você']],
  },
  {
    src: 'Estou aqui, no calor.',
    natural: 'Ich bin hier, in der Wärme.',
    literal: 'Bin-ich hier, in-der Hitze.',
    phonetic: 'is-TO a-KI, nu ka-LOH',
    difficulty: 1,
    summary: 'Die Antwort: Ich bin hier – in der Sonne und Wärme von Rio.',
    grammar: [
      ['Subjekt weglassen', '`Estou aqui` – `eu` kann wegfallen, die Verbform zeigt die Person.', 'pt.g.estar'],
      ['no calor', '`no calor` = in der Hitze/Wärme (em + o = no).', 'pt.g.contractions'],
    ],
    alternatives: [
      ['Tô aqui, no calor.', 'Bin hier, in der Hitze.', 'gesprochen'],
      ['Estou aqui, na praia.', 'Ich bin hier, am Strand.'],
    ],
    everyday: '`Estou aqui!` – Ich bin hier! – brauchst du oft. `Que calor!` (Was für eine Hitze!) sagst du in Rio fast täglich.',
    verbs: [['estou', 'estar', 'Presente, 1. Person Singular']],
  },
];

const glossary = {
  'bom-dia': gl('bom dia', 'Wendung', 'Guten Morgen / Guten Tag (vormittags)', 'bõ DSCHI-a', [['Bom dia, tudo bem?', 'Guten Morgen, alles gut?']],
    'Der Standardgruß bis Mittag.', { literal: 'guter Tag', grammar: 'Singular (anders als spanisch `buenos días`). Danach: `boa tarde`, `boa noite`.', ipa: 'bõ ˈdʒi.ɐ' }),
  rio: gl('Rio (de Janeiro)', 'Eigenname', 'Rio de Janeiro; kleingeschrieben: Fluss', 'HI-u', [['Eu moro no Rio.', 'Ich wohne in Rio.']],
    'Brasilianer sagen meist kurz `o Rio`.', { grammar: 'Mit Artikel: `o Rio` → `no Rio` (in Rio), `do Rio` (aus Rio). Das R am Wortanfang klingt wie ein kräftiges h.', ipa: 'ˈhi.u' }),
  mar: gl('mar', 'Nomen (m)', 'Meer', 'mah', [['Vamos ver o mar?', 'Gehen wir das Meer anschauen?']],
    'Alltagswort.', { grammar: 'r am Wortende klingt in Rio wie ein gehauchtes h oder ch.' }),
  sol: gl('sol', 'Nomen (m)', 'Sonne', 'ßóu', [['Hoje tem sol.', 'Heute scheint die Sonne.']],
    'Alltagswort.', { grammar: 'Offenes o; l am Silbenende klingt wie u: „ßóu“. Männlich: `o sol`.', ipa: 'ˈsɔw' }),
  'já': gl('já', 'Adverb', 'schon; gleich, sofort', 'scha', [['Já vou!', 'Ich komme gleich!']],
    'Sehr häufig.', { grammar: '`j` klingt wie weiches „sch“ (wie in „Garage“).' }),
  vem: gl('vir', 'Verb', 'kommen', 'wẽj', [['Ela vem amanhã.', 'Sie kommt morgen.']],
    'Sehr häufig.', { form: '3. Person Singular Presente von `vir`', grammar: 'Unregelmäßig: `venho, vem, vimos, vêm`.' }),
  acordar: gl('acordar', 'Verb', 'aufwachen; wecken', 'a-koh-DAH', [['Acordo às sete.', 'Ich wache um sieben auf.']],
    'Alltagswort.', { grammar: 'Falscher Freund: Spanisch `acordar(se)` = vereinbaren/sich erinnern – portugiesisch `acordar` = aufwachen/wecken.' }),
  janela: gl('janela', 'Nomen (f)', 'Fenster', 'scha-NÄ-la', [['Abre a janela, por favor.', 'Mach bitte das Fenster auf.']],
    'Alltagswort.', { ipa: 'ʒaˈnɛlɐ' }),
  passarinho: gl('passarinho', 'Nomen (m)', 'Vögelchen, kleiner Vogel', 'pa-ßa-RI-nju', [['O passarinho canta.', 'Das Vögelchen singt.']],
    'Im Alltag häufiger als `pássaro`.', { form: 'Verkleinerungsform von `pássaro`', grammar: '`nh` klingt wie „nj“.' }),
  canta: gl('cantar', 'Verb', 'singen', 'KÃN-ta', [['Ela canta bossa nova.', 'Sie singt Bossa Nova.']],
    'Sehr häufig.', { form: '3. Person Singular Presente von `cantar`' }),
  mim: gl('mim', 'Pronomen (nach Präposition)', 'mich, mir (betont)', 'mĩ', [['É para mim?', 'Ist das für mich?']],
    'Sehr häufig.', { grammar: 'Nach Präpositionen: `para mim`, `de mim`. Aber: `comigo` (mit mir). Nasal ausgesprochen.' }),
  baixinho: gl('baixinho', 'Adverb', 'ganz leise', 'bai-SCHI-nju', [['Fala baixinho, o bebê está dormindo.', 'Sprich leise, das Baby schläft.']],
    'Sehr häufig.', { form: 'Verkleinerungsform von `baixo` (leise; niedrig)', grammar: '`x` klingt hier wie „sch“.' }),
  'tudo-bem': gl('tudo bem', 'Wendung', 'Alles gut? / Wie geht’s?; alles gut', 'TU-du BẼJ', [['—Tudo bem? —Tudo bem!', '– Alles gut? – Alles gut!']],
    'Der häufigste lockere Gruß Brasiliens.', { literal: 'alles gut', register: 'umgangssprachlich', colloquial: 'Informell, aber überall üblich – auch mit Unbekannten in lockeren Situationen.' }),
  estou: gl('estar', 'Verb', 'sein (Zustand, Gefühl, Ort)', 'is-TO', [['Estou cansada.', 'Ich bin müde.']],
    'Sehr häufig; gesprochen oft `tô`.', { form: '1. Person Singular Presente von `estar`' }),
  feliz: gl('feliz', 'Adjektiv', 'glücklich', 'fe-LIS', [['Feliz aniversário!', 'Alles Gute zum Geburtstag!']],
    'Alltagswort.', { grammar: 'Gleiche Form für m und f; Plural `felizes`.' }),
  'meu-bem': gl('meu bem', 'Wendung (Kosewort)', 'mein Schatz, Liebling', 'ME-u BẼJ', [['Tudo bem, meu bem?', 'Alles gut, Schatz?']],
    'Unter Paaren und in der Familie sehr verbreitet.', { literal: 'mein Gut' }),
  vida: gl('vida', 'Nomen (f)', 'Leben', 'WI-da', [['A vida é bela.', 'Das Leben ist schön.']],
    'Alltagswort – auch als Kosewort: `minha vida`.'),
  'é': gl('ser', 'Verb', 'sein (Eigenschaft, Identität)', 'ä', [['O Rio é lindo.', 'Rio ist wunderschön.']],
    'Eines der wichtigsten Wörter.', { form: '3. Person Singular Presente von `ser`', grammar: 'Mit Akzent und offen („ä“) – `e` ohne Akzent heißt „und“.' }),
  boa: gl('bom', 'Adjektiv', 'gut, schön', 'BO-a', [['Boa noite!', 'Guten Abend!']],
    'Alltagswort.', { form: 'weibliche Form von `bom`' }),
  ano: gl('ano', 'Nomen (m)', 'Jahr', 'Ã-nu', [['Feliz Ano Novo!', 'Frohes neues Jahr!'], ['Tenho trinta anos.', 'Ich bin dreißig Jahre alt.']],
    'Alltagswort.', { grammar: 'Vor n klingt das a leicht nasal: „Ã-nu“.' }),
  inteiro: gl('inteiro', 'Adjektiv', 'ganz', 'ĩ-TEJ-ru', [['o dia inteiro', 'den ganzen Tag']],
    'Häufig; gleichbedeutend: `o ano todo`.', { grammar: 'Weiblich: `inteira` – `a noite inteira` (die ganze Nacht).' }),
  'a-gente': gl('a gente', 'Pronomen (umgangssprachlich)', 'wir; uns', 'a SCHẼN-tschi', [['A gente vai à praia.', 'Wir gehen an den Strand.'], ['Vem com a gente!', 'Komm mit uns!']],
    'Im gesprochenen Brasilianisch die normale Form für „wir“.',
    { literal: 'die Leute', register: 'umgangssprachlich', grammar: 'Verb in der 3. Person Singular: `a gente vai`, `a gente toma`.', colloquial: 'In Gesprächen häufiger als `nós`; in formellen Texten `nós`.' }),
  toma: gl('tomar', 'Verb', 'nehmen; trinken', 'TO-ma', [['Toma um café?', 'Trinkst du einen Kaffee?']],
    'Sehr häufig.', { form: '3. Person Singular Presente von `tomar`' }),
  cafezinho: gl('cafezinho', 'Nomen (m)', 'kleiner (starker) Kaffee', 'ka-fä-SI-nju', [['Aceita um cafezinho?', 'Möchten Sie einen Kaffee?']],
    'Überall in Brasilien – Symbol der Gastfreundschaft.', { form: 'Verkleinerungsform von `café`' }),
  conversa: gl('conversar', 'Verb', 'sich unterhalten, plaudern', 'kõ-WÄH-ßa', [['A gente conversa depois.', 'Wir reden später.']],
    'Alltagswort.', { form: '3. Person Singular Presente von `conversar`' }),
  pouquinho: gl('pouquinho', 'Nomen/Adverb', 'ein klein bisschen', 'po-KI-nju', [['Só um pouquinho.', 'Nur ein kleines bisschen.']],
    'Sehr häufig in `um pouquinho`.', { form: 'Verkleinerungsform von `pouco`' }),
  amigo: gl('amigo', 'Nomen (m)', 'Freund', 'a-MI-gu', [['Ele é meu melhor amigo.', 'Er ist mein bester Freund.']],
    'Alltagswort; weiblich `amiga`.'),
  'está': gl('estar', 'Verb', 'sein (Ort, Zustand)', 'is-TA', [['Onde está a chave?', 'Wo ist der Schlüssel?']],
    'Sehr häufig; gesprochen oft `tá`.', { form: '3. Person Singular Presente von `estar` (auch mit `você`)' }),
  'praça': gl('praça', 'Nomen (f)', 'Platz (in der Stadt)', 'PRA-ßa', [['A feira é na praça.', 'Der Markt ist auf dem Platz.']],
    'Alltagswort.', { grammar: '`ç` klingt wie ß.' }),
  toca: gl('tocar', 'Verb', 'spielen (Instrument); berühren', 'TO-ka', [['Ele toca piano.', 'Er spielt Klavier.']],
    'Alltagswort.', { form: '3. Person Singular Presente von `tocar`' }),
  'violão': gl('violão', 'Nomen (m)', '(akustische) Gitarre', 'wi-o-LÃU', [['Eu toco violão.', 'Ich spiele Gitarre.']],
    'Alltagswort; E-Gitarre = `guitarra`.', { grammar: 'Plural `violões`.', ipa: 'vi.oˈlɐ̃w̃' }),
  'de-graca': gl('de graça', 'Wendung', 'umsonst, gratis', 'dschi GRA-ßa', [['O show é de graça.', 'Das Konzert ist gratis.']],
    'Sehr häufig.', { literal: 'aus Gnade' }),
  'que-horas': gl('Que horas são?', 'Wendung', 'Wie spät ist es?', 'ki O-ras ßÃU', [['Que horas são? – São dez horas.', 'Wie spät ist es? – Zehn Uhr.']],
    'Täglich gebraucht.', { literal: 'Welche Stunden sind (es)?' }),
  'tanto-faz': gl('tanto faz', 'Wendung', 'egal, ist mir gleich', 'TÃN-tu FAS', [['Praia ou piscina? Tanto faz!', 'Strand oder Pool? Egal!']],
    'Sehr häufig.', { literal: 'so viel macht' }),
  hoje: gl('hoje', 'Adverb', 'heute', 'O-schi', [['Hoje é domingo.', 'Heute ist Sonntag.']],
    'Alltagswort.', { grammar: 'h stumm; `j` weich wie „sch“; End-e wie i.' }),
  vivo: gl('viver', 'Verb', 'leben', 'WI-wu', [['Eu vivo no Brasil.', 'Ich lebe in Brasilien.']],
    'Alltagswort.', { form: '1. Person Singular Presente von `viver`' }),
  devagar: gl('devagar', 'Adverb', 'langsam', 'dschi-wa-GAH', [['Mais devagar, por favor.', 'Langsamer, bitte.']],
    'Sehr nützlich beim Sprachenlernen!', { grammar: 'Unbetontes `de` am Anfang klingt oft wie „dschi“.' }),
  onde: gl('onde', 'Fragewort', 'wo', 'ÕN-dschi', [['Onde fica a praia?', 'Wo ist der Strand?']],
    'Sehr häufig.', { grammar: 'Wohin = `aonde` bzw. `para onde`.' }),
  'você': gl('você', 'Personalpronomen', 'du (Brasilien); Sie', 'wo-ßE', [['Você é daqui?', 'Bist du von hier?']],
    'Die normale Anrede in Brasilien.', { grammar: 'Verb in der 3. Person: `você está`, `você vem`. Gesprochen oft `cê`.' }),
  amor: gl('amor', 'Nomen (m)', 'Liebe; Liebling (Kosewort)', 'a-MOH', [['Oi, amor!', 'Hallo, Liebling!']],
    'Als Kosewort sehr verbreitet.'),
  aqui: gl('aqui', 'Adverb', 'hier', 'a-KI', [['Estou aqui!', 'Ich bin hier!']],
    'Alltagswort.'),
  calor: gl('calor', 'Nomen (m)', 'Hitze, Wärme', 'ka-LOH', [['Que calor!', 'Was für eine Hitze!']],
    'Alltagswort – in Rio fast täglich.', { grammar: '`Faz calor` / `Está quente` = es ist heiß.' }),
};

const song: Song = buildSong({
  id: 'song.pt.bom-dia-rio',
  courseId: 'pt-BR',
  variant: 'pt-BR',
  title: 'Bom dia, Rio',
  artist: 'Clara Maré',
  cover: { from: '#43CEA2', to: '#185A9D', emoji: '🏖️' },
  genre: 'Bossa Nova',
  level: 'A1',
  speed: 'langsam',
  themes: ['Morgen', 'Begrüßung', 'Strand', 'Rio de Janeiro'],
  grammarTags: ['pt.g.ser-estar', 'pt.g.contractions', 'pt.g.pronouns', 'pt.g.questions', 'pt.g.present-regular'],
  backing: { bpm: 64, style: 'bossa', key: 'C', chords: ['Cmaj7', 'A7', 'Dm7', 'G7', 'Em7', 'A7', 'Dm7', 'G7'] },
  sections: [
    { id: 'v1', label: 'Strophe 1', lines: verse1 },
    { id: 'c1', label: 'Refrain', lines: chorus },
    { id: 'v2', label: 'Strophe 2', lines: verse2 },
    { id: 'c2', label: 'Refrain', lines: chorus },
    { id: 'br', label: 'Bridge', lines: bridge },
    { id: 'c3', label: 'Refrain', lines: chorus },
  ],
  glossary,
  common: COMMON_PT,
});

export default song;
