/** „Buenos días, ciudad“ – Originales Lernlied (Pop, es-LA, A1). */
import type { Song } from '../types';
import { COMMON_ES } from './_common-es';
import { buildSong, gl, type LineDraft } from './_layout';

const verse1: LineDraft[] = [
  {
    src: 'Abro la ventana, ya sale el sol,',
    natural: 'Ich öffne das Fenster, schon geht die Sonne auf,',
    literal: 'Öffne-ich das Fenster, schon kommt-heraus die Sonne,',
    phonetic: 'A-bro la ben-TA-na, ja ßA-le el ßOL',
    difficulty: 1,
    summary: 'Der Morgen beginnt: Die Person öffnet das Fenster und sieht, wie die Sonne aufgeht.',
    grammar: [
      ['Präsens: ich-Form auf -o', '`abro` = ich öffne. Die Endung **-o** zeigt „ich“ – deshalb braucht es kein `yo`. Grundform: `abrir`.', 'es.g.present-regular'],
      ['Verb vor dem Subjekt', '`sale el sol` – im Spanischen steht das Subjekt oft **hinter** dem Verb. `salir` heißt „hinausgehen“, bei der Sonne „aufgehen“.'],
    ],
    alternatives: [
      ['Abro la ventana y sale el sol.', 'Ich öffne das Fenster und die Sonne geht auf.'],
      ['El sol ya sale.', 'Die Sonne geht schon auf.', 'normale Wortstellung, weniger liedhaft'],
    ],
    everyday: '`Abro la ventana` sagst du genau so im Alltag. `Sale el sol` ist die übliche Wendung für den Sonnenaufgang.',
    verbs: [
      ['abro', 'abrir', 'Präsens, 1. Person Singular (yo) – regelmäßig'],
      ['sale', 'salir', 'Präsens, 3. Person Singular (él/ella) – die yo-Form ist unregelmäßig: salgo'],
    ],
  },
  {
    src: 'La radio canta una canción.',
    natural: 'Das Radio spielt ein Lied.',
    literal: 'Das Radio singt ein Lied.',
    phonetic: 'la RRA-djo KAN-ta U-na kan-ßJON',
    difficulty: 1,
    summary: 'Im Radio läuft ein Lied – das Radio „singt“ (eine kleine Vermenschlichung).',
    grammar: [
      ['Präsens: er/sie/es-Form auf -a', '`canta` = (es) singt. Verben auf **-ar** enden in der 3. Person Singular auf **-a**: `cantar` → `canta`.', 'es.g.present-regular'],
      ['la radio – weiblich', '`radio` endet auf -o, ist aber weiblich: `la radio` (Kurzform von `la radiodifusión`).', 'es.g.articles'],
    ],
    culture: 'In Mexiko und Mittelamerika sagt man für das Gerät oft `el radio`, für das Programm `la radio`. Beides ist korrekt.',
    alternatives: [
      ['En la radio ponen una canción.', 'Im Radio spielen sie ein Lied.', 'alltäglicher'],
      ['Suena una canción en la radio.', 'Im Radio läuft ein Lied.'],
    ],
    everyday: 'Im Alltag sagst du eher `En la radio ponen una canción`. `La radio canta` klingt verspielt – typisch Lied.',
    verbs: [['canta', 'cantar', 'Präsens, 3. Person Singular – regelmäßiges -ar-Verb']],
  },
  {
    src: 'Estoy despierto, estoy feliz,',
    natural: 'Ich bin wach, ich bin glücklich,',
    literal: 'Bin-ich wach, bin-ich glücklich,',
    phonetic: 'es-TOI des-PJER-to, es-TOI fe-LIß',
    difficulty: 1,
    summary: 'Die Person beschreibt, wie es ihr am Morgen geht: wach und gut gelaunt.',
    grammar: [
      ['estar für Zustände', '`estoy` = ich bin (gerade). **estar** beschreibt Zustände und Stimmungen, die sich ändern können: wach, müde, glücklich.', 'es.g.estar'],
      ['Adjektiv passt sich an', '`despierto` sagt ein Mann; eine Frau sagt `despierta`. `feliz` bleibt für beide gleich.', 'es.g.adjectives'],
    ],
    ambiguity: '`feliz` geht mit `ser` und `estar`: `soy feliz` = ich bin (grundsätzlich) ein glücklicher Mensch; `estoy feliz` = ich bin gerade glücklich.',
    alternatives: [
      ['Estoy despierta, estoy feliz.', 'Ich bin wach, ich bin glücklich.', 'wenn eine Frau singt'],
      ['Estoy contento.', 'Ich bin froh.'],
    ],
    everyday: '`Estoy despierto` und `Estoy feliz` kannst du genau so sagen.',
    verbs: [['estoy', 'estar', 'Präsens, 1. Person Singular (yo) – unregelmäßig (Endung -oy)']],
  },
  {
    src: 'Hoy es un día para mí.',
    natural: 'Heute ist mein Tag.',
    literal: 'Heute ist ein Tag für mich.',
    phonetic: 'oi es un DI-a PA-ra MI',
    difficulty: 1,
    summary: 'Ein positiver Gedanke: Heute ist ein guter Tag – ein Tag, der der Person gehört.',
    grammar: [
      ['ser für Tage und Zeit', '`es un día` – für Tage, Daten und Uhrzeiten nimmt man **ser**: `Hoy es lunes`.', 'es.g.ser'],
      ['para mí – mit Akzent', 'Nach Präpositionen wie `para` steht `mí` mit Akzent. Ohne Akzent ist `mi` = „mein“.', 'es.g.pronouns'],
    ],
    alternatives: [
      ['Hoy es mi día.', 'Heute ist mein Tag.'],
      ['Hoy es un buen día.', 'Heute ist ein guter Tag.'],
    ],
    everyday: '`Hoy es mi día` ist eine häufige, positive Redewendung. `Hoy es un día para mí` klingt etwas liedhafter.',
    verbs: [['es', 'ser', 'Präsens, 3. Person Singular – unregelmäßig']],
  },
];

const chorus: LineDraft[] = [
  {
    src: '¡Buenos{buenos-dias} días{buenos-dias}, ciudad!',
    natural: 'Guten Morgen, Stadt!',
    literal: 'Gute Tage, Stadt!',
    phonetic: 'BUE-nos DI-as, ßju-DAD',
    ipa: 'ˈbwenoz ˈði.as sjuˈðað',
    difficulty: 1,
    summary: 'Die Person begrüßt ihre Stadt wie eine gute Freundin – Titel und Kern des Liedes.',
    grammar: [
      ['Buenos días – immer Plural', 'Der Gruß steht im Plural: **buenos días** (wörtlich „gute Tage“). Bis etwa Mittag; danach `buenas tardes`, abends `buenas noches`.'],
      ['¡…! – Ausrufezeichen vorne', 'Spanisch setzt ein umgedrehtes **¡** an den Anfang eines Ausrufs und **!** ans Ende.'],
    ],
    culture: 'In Lateinamerika grüßt man sehr gern – im Bus, im Laden, im Aufzug. Ein freundliches `¡Buenos días!` gehört einfach dazu.',
    alternatives: [
      ['¡Buen día, ciudad!', 'Guten Morgen, Stadt!', 'v. a. Argentinien, Uruguay, auch Mexiko'],
      ['¡Hola, ciudad!', 'Hallo, Stadt!'],
    ],
    everyday: '`¡Buenos días!` ist der Standardgruß am Vormittag – überall, formell wie informell.',
  },
  {
    src: '¿Cómo estás? ¿Qué{qué-tal} tal{qué-tal}?',
    natural: 'Wie geht’s dir? Alles klar?',
    literal: 'Wie bist-du? Was so?',
    phonetic: 'KO-mo es-TAS? ke TAL',
    difficulty: 1,
    summary: 'Zwei typische Fragen nach dem Befinden – hier an die Stadt gerichtet.',
    grammar: [
      ['Fragen mit ¿…?', 'Fragen beginnen mit **¿** und enden mit **?**. Fragewörter tragen einen Akzent: `cómo`, `qué`.', 'es.g.questions'],
      ['estar für das Befinden', '`¿Cómo estás?` fragt nach dem momentanen Befinden → **estar**.', 'es.g.estar'],
      ['du oder Sie?', '`estás` = du bist. Höflich mit `usted`: `¿Cómo está?`', 'es.g.formality'],
    ],
    idioms: [['¿Qué tal?', 'Wie geht’s? / Wie war’s?', 'Kurz und freundlich; auch: `¿Qué tal el día?` – Wie war dein Tag?']],
    alternatives: [
      ['¿Cómo está usted?', 'Wie geht es Ihnen?', 'höflich (usted)'],
      ['¿Cómo te va?', 'Wie läuft’s bei dir?'],
    ],
    everyday: 'Beide Fragen brauchst du täglich. `¿Qué tal?` passt fast immer, `¿Cómo estás?` unter Menschen, die du duzt.',
    verbs: [['estás', 'estar', 'Präsens, 2. Person Singular (tú)']],
  },
  {
    src: 'Yo estoy bien, estoy aquí,',
    natural: 'Mir geht’s gut, ich bin hier,',
    literal: 'Ich bin gut, bin-ich hier,',
    phonetic: 'jo es-TOI BJEN, es-TOI a-KI',
    difficulty: 1,
    summary: 'Die Antwort auf die Frage: Es geht gut – und die Person ist da, mitten in ihrer Stadt.',
    grammar: [
      ['estar bien', 'Wie es einem geht: **estar + bien/mal**. `Estoy bien` = mir geht es gut (wörtlich „ich bin gut“).', 'es.g.estar'],
      ['estar für den Ort', '`estoy aquí` = ich bin hier. Wo sich jemand befindet, sagt man mit **estar**.', 'es.g.ser-estar'],
    ],
    alternatives: [
      ['Estoy muy bien, gracias.', 'Mir geht’s sehr gut, danke.'],
      ['Aquí estoy.', 'Hier bin ich.', 'betont, liedhaft'],
    ],
    everyday: '`Estoy bien` ist die häufigste Antwort auf `¿Cómo estás?`. Das `yo` betont hier: „ICH jedenfalls …“.',
    verbs: [['estoy', 'estar', 'Präsens, 1. Person Singular (yo) – Befinden und Ort']],
  },
  {
    src: '¡Buenos{buenos-dias} días{buenos-dias} para ti!',
    natural: 'Einen guten Morgen für dich!',
    literal: 'Gute Tage für dich!',
    phonetic: 'BUE-nos DI-as PA-ra TI',
    difficulty: 1,
    summary: 'Der Gruß geht zurück – an die Stadt und an alle, die zuhören.',
    grammar: [
      ['para ti – ohne Akzent', 'Nach Präpositionen: `para mí` (mit Akzent), aber `para ti` (ohne Akzent – es gibt kein anderes „ti“).', 'es.g.pronouns'],
    ],
    alternatives: [
      ['¡Buenos días a ti también!', 'Dir auch einen guten Morgen!'],
      ['¡Igualmente!', 'Gleichfalls!', 'übliche Antwort auf einen Gruß'],
    ],
    everyday: 'Im Alltag antwortet man meist `¡Buenos días!` oder `¡Igualmente!`. `Para ti` macht den Gruß persönlich und herzlich.',
  },
];

const verse2: LineDraft[] = [
  {
    src: 'Mi vecina está en el balcón,',
    natural: 'Meine Nachbarin steht auf dem Balkon,',
    literal: 'Meine Nachbarin ist auf dem Balkon,',
    phonetic: 'mi be-ßI-na es-TA en el bal-KON',
    difficulty: 1,
    summary: 'Ein Blick in die Nachbarschaft: Die Nachbarin ist draußen auf ihrem Balkon.',
    grammar: [
      ['estar + Ort', '`está en el balcón` – wo jemand ist, sagt man mit **estar**.', 'es.g.estar'],
      ['Possessivbegleiter mi', '`mi vecina` = meine Nachbarin. `mi` bleibt gleich für männlich und weiblich.', 'es.g.possessives'],
    ],
    alternatives: [
      ['Mi vecino está en el balcón.', 'Mein Nachbar ist auf dem Balkon.'],
      ['Mi vecina sale al balcón.', 'Meine Nachbarin kommt auf den Balkon.'],
    ],
    everyday: 'Ganz normaler Satz. Deutsch sagt „steht/sitzt auf dem Balkon“ – Spanisch reicht `está`.',
    verbs: [['está', 'estar', 'Präsens, 3. Person Singular – Ort']],
  },
  {
    src: 'Me saluda con el corazón.',
    natural: 'Sie grüßt mich von Herzen.',
    literal: 'Mich grüßt-sie mit dem Herzen.',
    phonetic: 'me ßa-LU-da kon el ko-ra-ßON',
    difficulty: 1,
    summary: 'Die Nachbarin grüßt herzlich – `con el corazón` heißt „von ganzem Herzen“.',
    grammar: [
      ['Objektpronomen vor dem Verb', '`me saluda` = sie grüßt **mich**. Das Pronomen `me` steht vor dem konjugierten Verb.', 'es.g.pronouns'],
      ['Präsens -ar', '`saludar` → `saluda` (sie grüßt).', 'es.g.present-regular'],
    ],
    idioms: [['con el corazón', 'von Herzen, herzlich']],
    alternatives: [
      ['Me saluda con cariño.', 'Sie grüßt mich liebevoll.'],
      ['Me dice hola.', 'Sie sagt Hallo zu mir.'],
    ],
    everyday: '`Me saluda` ist alltäglich. `Con el corazón` klingt warm und etwas poetisch – im Gespräch eher `con mucho cariño`.',
    verbs: [['saluda', 'saludar', 'Präsens, 3. Person Singular – regelmäßiges -ar-Verb']],
  },
  {
    src: 'El panadero está en la puerta,',
    natural: 'Der Bäcker steht in der Tür,',
    literal: 'Der Bäcker ist in der Tür,',
    phonetic: 'el pa-na-DE-ro es-TA en la PUER-ta',
    difficulty: 1,
    summary: 'Auch der Bäcker ist schon auf und steht in seiner Ladentür.',
    grammar: [
      ['estar + Ort', 'Wieder **estar** für den Ort: `está en la puerta`.', 'es.g.estar'],
      ['Berufe auf -ero/-era', '`panadero` (Bäcker) kommt von `pan` (Brot); weiblich: `panadera`.', 'es.g.gender-plural'],
    ],
    culture: 'In vielen lateinamerikanischen Vierteln öffnen kleine Bäckereien (`panaderías`) sehr früh – der Duft von frischem Brot gehört zum Morgen.',
    alternatives: [
      ['La panadera está en la puerta.', 'Die Bäckerin steht in der Tür.'],
      ['El panadero abre la puerta.', 'Der Bäcker öffnet die Tür.'],
    ],
    everyday: 'Alltagstauglich. `Estar en la puerta` = in der Tür stehen / vor der Tür sein.',
    verbs: [['está', 'estar', 'Präsens, 3. Person Singular – Ort']],
  },
  {
    src: 'La calle entera ya está despierta.',
    natural: 'Die ganze Straße ist schon wach.',
    literal: 'Die Straße ganze schon ist wach.',
    phonetic: 'la KA-je en-TE-ra ja es-TA des-PJER-ta',
    difficulty: 2,
    summary: 'Die ganze Straße ist aufgewacht – ein Bild für das erwachende Viertel.',
    grammar: [
      ['Adjektiv nach dem Nomen', '`la calle entera` = die ganze Straße. Adjektive stehen meist **hinter** dem Nomen und passen sich an: `calle` ist weiblich → `entera`, `despierta`.', 'es.g.adjectives'],
      ['estar + Zustand', '`está despierta` – wach sein ist ein Zustand → **estar**.', 'es.g.estar'],
    ],
    ambiguity: 'Eine Straße kann nicht wirklich „wach“ sein – gemeint sind die Menschen darin. Auch Deutsch kennt das Bild: „Die Stadt erwacht.“',
    alternatives: [
      ['Toda la calle ya está despierta.', 'Die ganze Straße ist schon wach.', 'gleiche Bedeutung, im Alltag häufiger'],
      ['El barrio ya se despertó.', 'Das Viertel ist schon aufgewacht.'],
    ],
    everyday: 'Im Alltag sagt man eher `toda la calle`. `La calle entera` betont „die GANZE Straße“.',
    verbs: [['está', 'estar', 'Präsens, 3. Person Singular – Zustand']],
  },
];

const bridge: LineDraft[] = [
  {
    src: 'Un cafecito, un pan{pan-dulce} dulce{pan-dulce},',
    natural: 'Ein Käffchen, ein süßes Teilchen,',
    literal: 'Ein Kaffeechen, ein Brot süßes,',
    phonetic: 'un ka-fe-ßI-to, un pan DUL-ße',
    difficulty: 2,
    summary: 'Das kleine Frühstück: ein Kaffee und süßes Gebäck – typisch für den Morgen in Mexiko.',
    grammar: [
      ['Verkleinerung mit -ito', '`cafecito` = `café` + **-cito**. Das klingt liebevoll und gemütlich – nicht unbedingt „kleiner Kaffee“.'],
      ['Adjektiv hinter dem Nomen', '`pan dulce` = süßes Brot/Gebäck: Das Adjektiv steht hinter dem Nomen.', 'es.g.adjectives'],
    ],
    colloquial: '`cafecito` ist typisch für die lockere Alltagssprache in Lateinamerika: Die Verkleinerung macht alles freundlicher – `un cafecito`, `un momentito`, `ahorita`.',
    culture: '**Pan dulce** heißt in Mexiko das süße Gebäck vom Bäcker, z. B. `conchas` mit Zuckerkruste. Dazu Kaffee oder heiße Schokolade – ein Frühstücksklassiker.',
    alternatives: [
      ['Un café y un pan dulce.', 'Ein Kaffee und ein süßes Teilchen.', 'neutral'],
      ['Un cafecito con leche.', 'Ein Milchkaffee.'],
    ],
    everyday: '`¿Un cafecito?` hörst du ständig – als freundliche Einladung. Sehr natürlich.',
  },
  {
    src: 'Una sonrisa para empezar.',
    natural: 'Ein Lächeln zum Start.',
    literal: 'Ein Lächeln, um anzufangen.',
    phonetic: 'U-na ßon-RRI-ßa PA-ra em-pe-ßAR',
    difficulty: 1,
    summary: 'Zum guten Start in den Tag gehört auch ein Lächeln.',
    grammar: [
      ['para + Infinitiv', '`para empezar` = um anzufangen / zum Anfangen. Nach **para** steht die Grundform (Infinitiv).'],
    ],
    alternatives: [
      ['Una sonrisa para comenzar.', 'Ein Lächeln zum Beginnen.', 'comenzar = empezar'],
      ['Para empezar, un café.', 'Zum Anfang einen Kaffee.'],
    ],
    everyday: '`Para empezar` benutzt man oft – auch im Restaurant: „Und für den Anfang …?“',
    verbs: [['empezar', 'empezar', 'Infinitiv nach para']],
  },
  {
    src: '¿Qué{qué-onda} onda{qué-onda}, amigo? ¿Todo{todo-bien} bien{todo-bien}?',
    natural: 'Was geht, mein Freund? Alles gut?',
    literal: 'Welche Welle, Freund? Alles gut?',
    phonetic: 'ke ON-da, a-MI-go? TO-do BJEN',
    difficulty: 2,
    summary: 'Eine lockere Begrüßung unter Freunden auf dem Weg zur Arbeit.',
    grammar: [
      ['Kurze Fragen', 'Im Gespräch reichen oft Fragen ohne Verb: `¿Todo bien?` = Alles gut?', 'es.g.questions'],
    ],
    idioms: [
      ['¿Qué onda?', 'Was geht? / Wie läuft’s?', 'wörtlich „Welche Welle?“ – typisch mexikanisch'],
      ['¿Todo bien?', 'Alles gut?'],
    ],
    colloquial: '`¿Qué onda?` ist **mexikanisch** (auch in Mittelamerika verbreitet) und sehr locker – nur unter Freunden. In Spanien sagt man eher `¿Qué pasa?` oder `¿Qué tal?`.',
    alternatives: [
      ['¿Qué tal, amigo? ¿Todo bien?', 'Wie geht’s, Freund? Alles gut?', 'neutral, überall verständlich'],
      ['¿Quiubo?', 'Was geht?', 'Kolumbien und Mexiko, ebenfalls locker'],
    ],
    everyday: 'Mit Freunden in Mexiko absolut natürlich. Gegenüber Fremden oder im Büro lieber `¿Cómo está?`.',
  },
  {
    src: '¡Nos{nos-vemos} vemos{nos-vemos} luego, a trabajar!',
    natural: 'Bis später – ab zur Arbeit!',
    literal: 'Uns sehen-wir später, zu arbeiten!',
    phonetic: 'nos BE-mos LUE-go, a tra-ba-CHAR',
    difficulty: 2,
    summary: 'Man verabschiedet sich und geht los – der Arbeitstag beginnt.',
    grammar: [
      ['nos vemos – wir sehen uns', '`nos vemos` = wir sehen **uns**. Das Pronomen `nos` steht vor dem Verb.', 'es.g.reflexive'],
      ['a + Infinitiv als Aufforderung', '`¡A trabajar!` = An die Arbeit! Genauso: `¡A comer!` (Essen!), `¡A bailar!`'],
    ],
    idioms: [
      ['Nos vemos (luego).', 'Bis später. / Wir sehen uns.'],
      ['¡A trabajar!', 'An die Arbeit!'],
    ],
    alternatives: [
      ['¡Hasta luego!', 'Bis später!'],
      ['Nos vemos más tarde.', 'Wir sehen uns später.'],
    ],
    everyday: '`Nos vemos` und `Hasta luego` sind die häufigsten Abschiedsformeln – ganz alltäglich.',
    verbs: [
      ['vemos', 'ver', 'Präsens, 1. Person Plural (nosotros)'],
      ['trabajar', 'trabajar', 'Infinitiv nach a (Aufforderung)'],
    ],
  },
];

const glossary = {
  abro: gl('abrir', 'Verb', 'öffnen, aufmachen', 'A-bro', [['Abro la puerta.', 'Ich öffne die Tür.']],
    'Sehr häufig: für Fenster, Türen, Läden, Apps.', { form: '1. Person Singular Präsens von `abrir`' }),
  ventana: gl('ventana', 'Nomen (f)', 'Fenster', 'ben-TA-na', [['Abre la ventana, por favor.', 'Mach bitte das Fenster auf.']],
    'Alltagswort.', { grammar: 'weiblich: `la ventana`, Plural `las ventanas`. Das v klingt wie b.' }),
  sale: gl('salir', 'Verb', 'hinausgehen; (Sonne) aufgehen', 'ßA-le', [['Sale el sol.', 'Die Sonne geht auf.'], ['Salgo a las ocho.', 'Ich gehe um acht aus dem Haus.']],
    'Sehr häufig: hinausgehen, ausgehen, abfahren – und die Sonne „geht auf“.', { form: '3. Person Singular Präsens von `salir` (yo-Form: `salgo`)' }),
  sol: gl('sol', 'Nomen (m)', 'Sonne', 'ßol', [['Hace sol.', 'Die Sonne scheint.']],
    'Alltagswort; `hace sol` = es ist sonnig.', { grammar: 'männlich: `el sol` – im Deutschen weiblich!' }),
  radio: gl('radio', 'Nomen (f)', 'Radio', 'RRA-djo', [['Escucho la radio.', 'Ich höre Radio.']],
    'Alltagswort. In Mexiko und Mittelamerika für das Gerät oft `el radio`.', { grammar: 'Trotz -o weiblich: `la radio`. Das r am Wortanfang wird gerollt.' }),
  canta: gl('cantar', 'Verb', 'singen', 'KAN-ta', [['Ella canta muy bien.', 'Sie singt sehr gut.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `cantar`' }),
  'canción': gl('canción', 'Nomen (f)', 'Lied', 'kan-ßJON', [['Es mi canción favorita.', 'Das ist mein Lieblingslied.']],
    'Alltagswort.', { grammar: 'Wörter auf -ción sind weiblich; Plural `canciones` (ohne Akzent).', ipa: 'kanˈsjon' }),
  estoy: gl('estar', 'Verb', 'sein (Zustand, Ort, Befinden)', 'es-TOI', [['Estoy cansado.', 'Ich bin müde.'], ['Estoy en casa.', 'Ich bin zu Hause.']],
    'Eines der wichtigsten Verben überhaupt.', { form: '1. Person Singular Präsens von `estar`' }),
  despierto: gl('despierto', 'Adjektiv', 'wach', 'des-PJER-to', [['¿Estás despierto?', 'Bist du wach?']],
    'Ganz normal im Alltag; weiblich `despierta`.', { grammar: 'Mit `estar`: `estoy despierto`.' }),
  feliz: gl('feliz', 'Adjektiv', 'glücklich, froh', 'fe-LIß', [['Estoy feliz.', 'Ich bin glücklich.'], ['¡Feliz cumpleaños!', 'Alles Gute zum Geburtstag!']],
    'Sehr häufig, auch in Glückwünschen: `¡Feliz Navidad!`', { grammar: 'Gleiche Form für m und f; Plural `felices`. Geht mit `ser` und `estar`.' }),
  hoy: gl('hoy', 'Adverb', 'heute', 'oi', [['Hoy es lunes.', 'Heute ist Montag.']],
    'Alltagswort.', { grammar: 'Das h wird nie gesprochen.' }),
  es: gl('ser', 'Verb', 'sein (Wesen, Identität, Zeit)', 'es', [['Hoy es un buen día.', 'Heute ist ein guter Tag.']],
    'Eines der wichtigsten Verben.', { form: '3. Person Singular Präsens von `ser`' }),
  'día': gl('día', 'Nomen (m)', 'Tag', 'DI-a', [['Buen día.', 'Guten Tag.'], ['todos los días', 'jeden Tag']],
    'Alltagswort.', { grammar: 'Trotz -a männlich: `el día`.' }),
  'buenos-dias': gl('buenos días', 'Wendung', 'Guten Morgen / Guten Tag (vormittags)', 'BUE-nos DI-as', [['¡Buenos días a todos!', 'Guten Morgen zusammen!']],
    'Der Standardgruß bis etwa Mittag – immer passend.', { literal: 'gute Tage', grammar: 'Immer im Plural. Danach `buenas tardes`, abends `buenas noches`.' }),
  ciudad: gl('ciudad', 'Nomen (f)', 'Stadt', 'ßju-DAD', [['Vivo en una ciudad grande.', 'Ich wohne in einer großen Stadt.']],
    'Alltagswort.', { grammar: 'Wörter auf -dad sind weiblich. Das d am Ende ist sehr weich, fast stumm.', ipa: 'sjuˈðað' }),
  'cómo': gl('cómo', 'Fragewort', 'wie', 'KO-mo', [['¿Cómo te llamas?', 'Wie heißt du?']],
    'Sehr häufig.', { grammar: 'Als Fragewort mit Akzent: `¿cómo?`.' }),
  'estás': gl('estar', 'Verb', 'sein (Befinden, Zustand, Ort)', 'es-TAS', [['¿Dónde estás?', 'Wo bist du?']],
    'Sehr häufig unter Menschen, die sich duzen.', { form: '2. Person Singular Präsens von `estar` (tú)' }),
  'qué-tal': gl('¿qué tal?', 'Wendung', 'Wie geht’s? / Wie ist …?', 'ke TAL', [['¿Qué tal el trabajo?', 'Wie läuft die Arbeit?']],
    'Kurz, freundlich und passt fast immer – informell bis neutral.', { literal: 'was so?' }),
  bien: gl('bien', 'Adverb', 'gut', 'bjen', [['Estoy bien, gracias.', 'Mir geht’s gut, danke.']],
    'Alltagswort.', { grammar: '`bien` ist ein Adverb: `estoy bien` (nicht `estoy bueno`).' }),
  'aquí': gl('aquí', 'Adverb', 'hier', 'a-KI', [['Estoy aquí.', 'Ich bin hier.']],
    'Alltagswort.', { grammar: 'Betonung auf der letzten Silbe (deshalb der Akzent).' }),
  vecina: gl('vecina', 'Nomen (f)', 'Nachbarin', 'be-ßI-na', [['Mi vecina es muy simpática.', 'Meine Nachbarin ist sehr nett.']],
    'Alltagswort; männlich `vecino`.'),
  'está': gl('estar', 'Verb', 'sein (Ort, Zustand)', 'es-TA', [['¿Dónde está el baño?', 'Wo ist die Toilette?']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `estar`', grammar: 'Mit Akzent! `esta` ohne Akzent heißt „diese“.' }),
  'balcón': gl('balcón', 'Nomen (m)', 'Balkon', 'bal-KON', [['Desayuno en el balcón.', 'Ich frühstücke auf dem Balkon.']],
    'Alltagswort.', { grammar: 'Plural `balcones` (ohne Akzent).' }),
  saluda: gl('saludar', 'Verb', 'grüßen', 'ßa-LU-da', [['Siempre me saluda.', 'Er/Sie grüßt mich immer.']],
    'Häufig. `¡Saludos!` = Grüße (auch als Briefschluss).', { form: '3. Person Singular Präsens von `saludar`' }),
  'corazón': gl('corazón', 'Nomen (m)', 'Herz', 'ko-ra-ßON', [['Te quiero con todo mi corazón.', 'Ich liebe dich von ganzem Herzen.']],
    'Häufig – auch als Kosewort: `¡Hola, corazón!`', { grammar: 'Plural `corazones`.' }),
  panadero: gl('panadero', 'Nomen (m)', 'Bäcker', 'pa-na-DE-ro', [['El panadero abre a las seis.', 'Der Bäcker öffnet um sechs.']],
    'Alltagswort; `panadería` = Bäckerei.'),
  puerta: gl('puerta', 'Nomen (f)', 'Tür', 'PUER-ta', [['Cierra la puerta, por favor.', 'Mach bitte die Tür zu.']],
    'Alltagswort.'),
  calle: gl('calle', 'Nomen (f)', 'Straße', 'KA-je', [['Vivo en esta calle.', 'Ich wohne in dieser Straße.']],
    'Alltagswort.', { grammar: '`ll` klingt in fast allen Regionen wie deutsches j.', ipa: 'ˈkaʝe' }),
  entera: gl('entero', 'Adjektiv', 'ganz', 'en-TE-ra', [['el día entero', 'den ganzen Tag']],
    'Häufig, aber `todo el día` ist noch üblicher.', { form: 'weibliche Form von `entero`' }),
  despierta: gl('despierto', 'Adjektiv', 'wach', 'des-PJER-ta', [['La ciudad está despierta.', 'Die Stadt ist wach.']],
    'Alltagswort.', { form: 'weibliche Form von `despierto`' }),
  cafecito: gl('cafecito', 'Nomen (m)', 'Käffchen, (gemütlicher) Kaffee', 'ka-fe-ßI-to', [['¿Nos tomamos un cafecito?', 'Trinken wir zusammen einen Kaffee?']],
    'In Lateinamerika sehr häufig – klingt freundlich und einladend.',
    { form: 'Verkleinerungsform von `café`', register: 'umgangssprachlich', colloquial: 'Die Verkleinerung (-cito) zeigt Herzlichkeit – typisch lateinamerikanische Alltagssprache.' }),
  'pan-dulce': gl('pan dulce', 'Nomen (m)', 'süßes Gebäck (Mexiko)', 'pan DUL-ße', [['Compramos pan dulce para el desayuno.', 'Wir kaufen süßes Gebäck fürs Frühstück.']],
    'In Mexiko ein Alltagswort; anderswo versteht man es als „süßes Brot“.', { literal: 'süßes Brot' }),
  sonrisa: gl('sonrisa', 'Nomen (f)', 'Lächeln', 'ßon-RRI-ßa', [['Tienes una sonrisa bonita.', 'Du hast ein schönes Lächeln.']],
    'Alltagswort.', { grammar: 'Nach n wird r gerollt: son-**rr**i-sa.' }),
  empezar: gl('empezar', 'Verb', 'anfangen, beginnen', 'em-pe-ßAR', [['¿A qué hora empieza?', 'Wann fängt es an?']],
    'Sehr häufig.', { grammar: 'Stammwechsel e → ie: `empiezo`, `empiezas`, `empieza`.' }),
  'qué-onda': gl('¿qué onda?', 'Wendung', 'Was geht? / Wie läuft’s?', 'ke ON-da', [['¿Qué onda? ¿Cómo estás?', 'Was geht? Wie geht’s dir?']],
    'Unter Freunden in Mexiko sehr natürlich; nicht im Büro oder bei Fremden.',
    { literal: 'welche Welle?', register: 'umgangssprachlich', colloquial: 'Typisch **mexikanisch**, auch in Mittelamerika. Locker und jugendlich.' }),
  amigo: gl('amigo', 'Nomen (m)', 'Freund', 'a-MI-go', [['Es mi mejor amigo.', 'Er ist mein bester Freund.']],
    'Alltagswort; weiblich `amiga`. Auch als lockere Anrede.'),
  'todo-bien': gl('¿todo bien?', 'Wendung', 'Alles gut?', 'TO-do BJEN', [['—¿Todo bien? —Sí, todo bien.', '– Alles gut? – Ja, alles gut.']],
    'Sehr häufig als Frage und als Antwort.'),
  'nos-vemos': gl('nos vemos', 'Wendung', 'Wir sehen uns / Bis bald', 'nos BE-mos', [['Nos vemos mañana.', 'Bis morgen.']],
    'Einer der häufigsten Abschiede.', { form: '`nos` + 1. Person Plural Präsens von `ver`' }),
  luego: gl('luego', 'Adverb', 'später; dann', 'LUE-go', [['Hasta luego.', 'Bis später.']],
    'Sehr häufig, besonders in `hasta luego`.'),
  trabajar: gl('trabajar', 'Verb', 'arbeiten', 'tra-ba-CHAR', [['Trabajo en una oficina.', 'Ich arbeite in einem Büro.']],
    'Alltagswort.', { grammar: 'j klingt wie deutsches „ch“ in „Bach“.' }),
};

const song: Song = buildSong({
  id: 'song.es.buenos-dias',
  courseId: 'es',
  variant: 'es-LA',
  title: 'Buenos días, ciudad',
  artist: 'Los Aprendices',
  cover: { from: '#FFB75E', to: '#ED8F03', emoji: '🌅' },
  genre: 'Pop',
  level: 'A1',
  speed: 'langsam',
  themes: ['Morgen', 'Begrüßung', 'Stadt', 'Nachbarschaft'],
  grammarTags: ['es.g.estar', 'es.g.ser-estar', 'es.g.questions', 'es.g.present-regular', 'es.g.possessives', 'es.g.formality'],
  backing: { bpm: 100, style: 'pop', key: 'C', chords: ['C', 'G', 'Am', 'F'] },
  sections: [
    { id: 'v1', label: 'Strophe 1', lines: verse1 },
    { id: 'c1', label: 'Refrain', lines: chorus },
    { id: 'v2', label: 'Strophe 2', lines: verse2 },
    { id: 'c2', label: 'Refrain', lines: chorus },
    { id: 'br', label: 'Bridge', lines: bridge },
    { id: 'c3', label: 'Refrain', lines: chorus },
  ],
  glossary,
  common: COMMON_ES,
});

export default song;
