/** „Canción de la lluvia“ – Originales Lernlied (Ballade, es-ES, A2, poetisch). Lautschrift: „th“ = gelispeltes s wie engl. „think“. */
import type { Song } from '../types';
import { COMMON_ES } from './_common-es';
import { buildSong, gl, type LineDraft } from './_layout';

const verse1: LineDraft[] = [
  {
    src: 'La lluvia canta en mi ventana,',
    natural: 'Der Regen singt an meinem Fenster,',
    literal: 'Der Regen singt an meinem Fenster,',
    phonetic: 'la JU-bja KAN-ta en mi ben-TA-na',
    difficulty: 1,
    summary: 'Das Anfangsbild: Regentropfen trommeln an die Scheibe, als würden sie singen.',
    grammar: [
      ['en = an', '`en mi ventana` = an meinem Fenster. **en** deckt „in“, „an“ und „auf“ ab.'],
      ['Possessivbegleiter mi', '`mi ventana` = mein Fenster.', 'es.g.possessives'],
    ],
    ambiguity: '**Vermenschlichung**: Der Regen „singt“. Gemeint ist das Geräusch der Tropfen – und die Stimmung der Person, die zuhört.',
    alternatives: [
      ['La lluvia golpea mi ventana.', 'Der Regen klopft an mein Fenster.', 'realistischer'],
      ['Está lloviendo.', 'Es regnet gerade.', 'ganz alltäglich'],
    ],
    everyday: 'Poetisch – im Alltag sagst du `Está lloviendo` (Es regnet gerade).',
    verbs: [['canta', 'cantar', 'Präsens, 3. Person Singular – regelmäßiges -ar-Verb']],
  },
  {
    src: 'La calle está gris y callada.',
    natural: 'Die Straße ist grau und still.',
    literal: 'Die Straße ist grau und schweigsam.',
    phonetic: 'la KA-je es-TA GRIS i ka-JA-da',
    difficulty: 2,
    summary: 'Wegen des Regens ist draußen alles grau, und niemand ist unterwegs.',
    grammar: [
      ['estar + Adjektiv = Zustand', '`está gris` – heute, wegen des Regens. Mit `ser` (`es gris`) wäre die Straße immer grau.', 'es.g.ser-estar'],
      ['Adjektive angleichen', '`callada` ist weiblich, weil `calle` weiblich ist. `gris` hat für m und f dieselbe Form.', 'es.g.adjectives'],
    ],
    ambiguity: '`callado/a` sagt man eigentlich über Menschen („schweigsam“). Die Straße „schweigt“ – wieder ein Bild für die stille Stimmung.',
    alternatives: [
      ['La calle está gris y en silencio.', 'Die Straße ist grau und still.'],
      ['No hay nadie en la calle.', 'Niemand ist auf der Straße.', 'ganz alltäglich'],
    ],
    everyday: '`estar callado/a` benutzt man für Menschen: `¿Por qué estás tan callada?` – Warum bist du so still?',
    verbs: [['está', 'estar', 'Präsens, 3. Person Singular – Zustand']],
  },
  {
    src: 'Tu voz es dulce, tu mirada es clara,',
    natural: 'Deine Stimme ist sanft, dein Blick ist klar,',
    literal: 'Deine Stimme ist süß, dein Blick ist klar,',
    phonetic: 'tu BOTH es DUL-the, tu mi-RA-da es KLA-ra',
    ipa: 'tu ˈβoθ es ˈðulθe | tu miˈɾaða es ˈklaɾa',
    difficulty: 2,
    summary: 'Beschreibung der geliebten Person – wie sie grundsätzlich ist: sanft und ehrlich.',
    grammar: [
      ['ser für Eigenschaften', '`es dulce`, `es clara` – bleibende Eigenschaften → **ser**.', 'es.g.ser'],
      ['Possessivbegleiter tu', '`tu voz`, `tu mirada` = deine … (ohne Akzent; `tú` mit Akzent = du).', 'es.g.possessives'],
    ],
    ambiguity: '`dulce` heißt „süß“ – bei einer Stimme: sanft, zärtlich. `clara` ist doppeldeutig: Ein „klarer“ Blick ist hell **und** ehrlich, ohne Geheimnisse.',
    alternatives: [
      ['Tienes una voz dulce y una mirada clara.', 'Du hast eine sanfte Stimme und einen klaren Blick.'],
      ['Tu voz es suave.', 'Deine Stimme ist sanft.'],
    ],
    everyday: '`Tiene una voz muy dulce` ist ein ganz normales Kompliment.',
    verbs: [['es', 'ser', 'Präsens, 3. Person Singular – Eigenschaft']],
  },
  {
    src: 'Pero esta noche estás cansada.',
    natural: 'Aber heute Abend bist du müde.',
    literal: 'Aber diese Nacht bist-du müde.',
    phonetic: 'PE-ro ES-ta NO-tsche es-TAS kan-ßA-da',
    difficulty: 1,
    summary: 'Der Gegensatz: Heute ist die geliebte Person erschöpft – ein vorübergehender Zustand.',
    grammar: [
      ['ser oder estar?', 'Die Zeile davor: wie sie **ist** (`ser`). Diese Zeile: wie es ihr **gerade geht** (`estar`). `estás cansada` = du bist (gerade) müde.', 'es.g.ser-estar'],
      ['esta noche', '`esta noche` = heute Abend / heute Nacht (wörtlich „diese Nacht“).'],
    ],
    ambiguity: '`cansada` kann körperlich müde oder seelisch erschöpft bedeuten – im Regen-Lied schwingt beides mit.',
    alternatives: [
      ['Pero hoy estás cansada.', 'Aber heute bist du müde.'],
      ['Pero esta noche pareces cansada.', 'Aber heute Abend wirkst du müde.'],
    ],
    everyday: '`Estoy cansado/a` gehört zu den häufigsten Sätzen überhaupt.',
    verbs: [['estás', 'estar', 'Präsens, 2. Person Singular (tú) – Zustand']],
  },
];

const chorus: LineDraft[] = [
  {
    src: 'Llueve en la calle, llueve en mí,',
    natural: 'Es regnet auf der Straße, es regnet in mir,',
    literal: 'Regnet in der Straße, regnet in mir,',
    phonetic: 'JUE-be en la KA-je, JUE-be en MI',
    ipa: 'ˈʝweβe en la ˈkaʝe | ˈʝweβe en ˈmi',
    difficulty: 2,
    summary: 'Draußen regnet es – und drinnen, im Herzen, auch: Die Person ist traurig.',
    grammar: [
      ['llover – ohne Subjekt', '`llueve` = es regnet. Wetterverben brauchen kein Subjekt, auch kein „es“. Stammwechsel **o → ue**: `llover` → `llueve`.'],
      ['en mí – mit Akzent', 'Nach Präpositionen: `en mí` (in mir) – `mí` mit Akzent.', 'es.g.pronouns'],
    ],
    ambiguity: '**Metapher**: `llueve en mí` = ich bin traurig, vielleicht weine ich. Der Regen draußen spiegelt das Gefühl drinnen.',
    alternatives: [
      ['Llueve fuera y llueve dentro de mí.', 'Es regnet draußen und in mir drin.'],
      ['Estoy triste como la lluvia.', 'Ich bin traurig wie der Regen.', 'direkt statt Metapher'],
    ],
    everyday: '`Llueve` / `Está lloviendo` brauchst du fürs Wetter täglich. `Llueve en mí` ist reine Poesie.',
    verbs: [['llueve', 'llover', 'Präsens, 3. Person Singular – Wetterverb, Stammwechsel o → ue']],
  },
  {
    src: 'Mi corazón es un paraguas gris.',
    natural: 'Mein Herz ist ein grauer Regenschirm.',
    literal: 'Mein Herz ist ein Regenschirm grau.',
    phonetic: 'mi ko-ra-THON es un pa-RA-guas GRIS',
    difficulty: 2,
    summary: 'Ein starkes Bild: Das Herz schützt sich wie ein Schirm – aber es ist grau, also traurig.',
    grammar: [
      ['ser für Metaphern', '„A ist B“ – Identität oder Vergleich → **ser**: `mi corazón es un paraguas`.', 'es.g.ser'],
      ['Farbe hinter dem Nomen', '`un paraguas gris` – Farben stehen hinter dem Nomen.', 'es.g.adjectives'],
    ],
    ambiguity: '**Doppeldeutig**: Ein Schirm schützt vor Regen – das Herz schützt sich vor Schmerz. Aber ein Schirm hält auch alles ab, sogar Schönes. Und `gris` steht auf Spanisch wie auf Deutsch für Traurigkeit und Eintönigkeit.',
    alternatives: [
      ['Mi corazón está triste.', 'Mein Herz ist traurig.', 'ohne Bild'],
      ['Tengo el corazón gris.', 'Mein Herz ist grau.'],
    ],
    everyday: '`paraguas` brauchst du im Alltag: `¿Llevas paraguas?` – Hast du einen Schirm dabei?',
    verbs: [['es', 'ser', 'Präsens, 3. Person Singular – Identität/Metapher']],
  },
  {
    src: 'Mañana el cielo va a estar azul,',
    natural: 'Morgen wird der Himmel blau sein,',
    literal: 'Morgen der Himmel geht zu sein blau,',
    phonetic: 'ma-NJA-na el THJE-lo ba a es-TAR a-THUL',
    difficulty: 2,
    summary: 'Hoffnung: Der Regen geht vorbei, morgen ist der Himmel wieder klar.',
    grammar: [
      ['ir a + Infinitiv', '`va a estar` = wird sein. **ir a + Infinitiv** für Vorhersagen und Pläne.', 'es.g.ir-a'],
      ['estar azul', 'Der Himmel **ist** morgen blau – ein wechselnder Zustand → `estar`.', 'es.g.ser-estar'],
    ],
    ambiguity: 'Anders als englisch „blue“ (traurig) oder deutsch „blau“ (betrunken) hat spanisch `azul` keine solche Nebenbedeutung – hier steht es für klares Wetter und Zuversicht.',
    alternatives: [
      ['Mañana va a hacer buen tiempo.', 'Morgen wird das Wetter schön.', 'Standard beim Wetter'],
      ['Mañana saldrá el sol.', 'Morgen kommt die Sonne heraus.', 'mit Futur'],
    ],
    everyday: '`Mañana va a llover / va a hacer sol` – so klingt der Wetterbericht im Gespräch.',
    verbs: [
      ['va', 'ir', 'Präsens, 3. Person Singular – ir a + Infinitiv'],
      ['estar', 'estar', 'Infinitiv'],
    ],
  },
  {
    src: 'Y tú vas a ser mi luz.',
    natural: 'Und du wirst mein Licht sein.',
    literal: 'Und du gehst zu sein mein Licht.',
    phonetic: 'i TU bas a ßER mi LUTH',
    difficulty: 2,
    summary: 'Die geliebte Person wird zur Hoffnung, zum Licht nach dem Regen.',
    grammar: [
      ['ser für Identität', '`vas a ser mi luz` – was jemand (für mich) **ist** → `ser`. Vergleiche die Zeile davor: `va a estar azul` (Zustand).', 'es.g.ser-estar'],
      ['tú – betont', '`tú` mit Akzent = du. Hier betont: „und DU …“', 'es.g.pronouns'],
    ],
    ambiguity: '`mi luz` = „mein Licht“: Hoffnung und Orientierung – und zugleich ein zärtliches Kosewort (`luz de mi vida` = Licht meines Lebens).',
    alternatives: [
      ['Y tú vas a ser mi sol.', 'Und du wirst meine Sonne sein.'],
      ['Tú eres mi luz.', 'Du bist mein Licht.', 'im Präsens'],
    ],
    everyday: 'Als Kosewort romantisch, aber echt: `Eres mi luz.` Im Alltag eher `cariño` oder `cielo`.',
    verbs: [
      ['vas', 'ir', 'Präsens, 2. Person Singular – ir a + Infinitiv'],
      ['ser', 'ser', 'Infinitiv'],
    ],
  },
];

const verse2: LineDraft[] = [
  {
    src: 'Nuestra casa es pequeña y vieja,',
    natural: 'Unser Haus ist klein und alt,',
    literal: 'Unser Haus ist klein und alt,',
    phonetic: 'NUES-tra KA-ßa es pe-KE-nja i BJE-cha',
    difficulty: 1,
    summary: 'Das gemeinsame Zuhause: bescheiden, aber voller Geschichte.',
    grammar: [
      ['nuestro/nuestra', '`nuestra casa` – **nuestro** passt sich an das Nomen an: `nuestra casa`, `nuestro barrio`, `nuestras cosas`.', 'es.g.possessives'],
      ['ser + Eigenschaften', 'Größe und Alter als Merkmal → **ser**: `es pequeña y vieja`.', 'es.g.ser'],
    ],
    alternatives: [
      ['Nuestro piso es pequeño y antiguo.', 'Unsere Wohnung ist klein und alt.', 'Spanien: piso = Wohnung'],
      ['Vivimos en una casa pequeña.', 'Wir wohnen in einem kleinen Haus.'],
    ],
    everyday: 'Sehr alltäglich – über Häuser sagt man freundlicher `antigua` statt `vieja`.',
    verbs: [['es', 'ser', 'Präsens, 3. Person Singular – Eigenschaften']],
  },
  {
    src: 'La lluvia baila sobre sus tejas.',
    natural: 'Der Regen tanzt auf seinen Dachziegeln.',
    literal: 'Der Regen tanzt auf seinen Ziegeln.',
    phonetic: 'la JU-bja BAI-la ßO-bre ßus TE-chas',
    difficulty: 2,
    summary: 'Der Regen „tanzt“ auf dem Dach – ein freundliches, fast fröhliches Bild.',
    grammar: [
      ['sus = seine/ihre', '`sus tejas` = die Ziegel **des Hauses**. `su/sus` kann „sein“, „ihr“ oder „Ihr“ bedeuten.', 'es.g.possessives'],
    ],
    ambiguity: '`sus` ist mehrdeutig: seine (des Hauses), ihre (einer Frau oder mehrerer), Ihre (Sie-Form). Hier klar: die Ziegel unseres Hauses. Und der Regen „tanzt“ – nach dem „Singen“ in Strophe 1 wird er fröhlicher.',
    alternatives: [
      ['La lluvia cae sobre el tejado.', 'Der Regen fällt auf das Dach.', 'alltäglich'],
      ['Llueve sobre el tejado.', 'Es regnet aufs Dach.'],
    ],
    everyday: '`teja` (Dachziegel) ist ein eher seltenes Wort; `tejado` (Dach) brauchst du öfter.',
    verbs: [['baila', 'bailar', 'Präsens, 3. Person Singular']],
  },
  {
    src: 'Mis manos están frías, las tuyas también,',
    natural: 'Meine Hände sind kalt, deine auch,',
    literal: 'Meine Hände sind kalt, die deinen auch,',
    phonetic: 'mis MA-nos es-TAN FRI-as, las TU-jas tam-BJEN',
    difficulty: 2,
    summary: 'Beide frieren – Nähe als Trost im kalten Regen.',
    grammar: [
      ['estar + Adjektiv', '`están frías` – kalt **gerade jetzt** → `estar`.', 'es.g.ser-estar'],
      ['Possessivpronomen las tuyas', '`las tuyas` = deine (Hände) – ersetzt `tus manos` und richtet sich nach dem Nomen: `la tuya`, `los tuyos`, `las tuyas`.', 'es.g.possessives'],
      ['la mano – weiblich', '`mano` endet auf -o, ist aber weiblich: `la mano`, `las manos frías`.', 'es.g.gender-plural'],
    ],
    ambiguity: 'Mit `ser` hieße `son frías` „sie sind gefühlskalt“. Mit `estar` sind die Hände einfach kalt vom Wetter – ein kleines Wort, ein großer Unterschied.',
    alternatives: [
      ['Tengo las manos frías y tú también.', 'Ich habe kalte Hände und du auch.', 'sehr alltäglich'],
      ['Tenemos frío.', 'Uns ist kalt.'],
    ],
    everyday: 'Im Alltag sagt man meist `Tengo las manos frías`.',
    verbs: [['están', 'estar', 'Präsens, 3. Person Plural – Zustand']],
  },
  {
    src: 'Pero juntos estamos bien.',
    natural: 'Aber zusammen geht es uns gut.',
    literal: 'Aber zusammen sind-wir gut.',
    phonetic: 'PE-ro CHUN-tos es-TA-mos BJEN',
    difficulty: 1,
    summary: 'Die Kernaussage der Strophe: Trotz Kälte und Regen – zusammen ist alles gut.',
    grammar: [
      ['estar bien', '`estamos bien` = es geht uns gut. **estar + bien** für das Befinden.', 'es.g.estar'],
      ['juntos passt sich an', '`juntos` (m. oder gemischt), `juntas` (nur Frauen).', 'es.g.adjectives'],
    ],
    alternatives: [
      ['Pero juntos todo está bien.', 'Aber zusammen ist alles gut.'],
      ['Contigo estoy bien.', 'Mit dir geht es mir gut.'],
    ],
    everyday: 'Ganz natürlich – `Estamos bien` ist auch die Antwort auf `¿Cómo estáis?`.',
    verbs: [['estamos', 'estar', 'Präsens, 1. Person Plural – Befinden']],
    bars: 2,
  },
];

const bridge: LineDraft[] = [
  {
    src: 'Cada gota es una palabra,',
    natural: 'Jeder Tropfen ist ein Wort,',
    literal: 'Jeder Tropfen ist ein Wort,',
    phonetic: 'KA-da GO-ta es U-na pa-LA-bra',
    difficulty: 2,
    summary: 'Der Regen spricht: Jeder Tropfen wird zu einem Wort.',
    grammar: [
      ['cada – unveränderlich', '`cada` (jede/r/s) bleibt immer gleich: `cada gota`, `cada día`.'],
      ['ser für Metaphern', '`es una palabra` – „A ist B“ → `ser`.', 'es.g.ser'],
    ],
    ambiguity: '**Metapher**: Regentropfen als Worte – vielleicht das, was man sich nicht zu sagen traut und was nun der Regen „ausspricht“.',
    alternatives: [
      ['Cada gota dice algo.', 'Jeder Tropfen sagt etwas.'],
    ],
    everyday: '`cada` brauchst du täglich: `cada día`, `cada semana`.',
    verbs: [['es', 'ser', 'Präsens, 3. Person Singular']],
  },
  {
    src: 'Cada palabra es una canción.',
    natural: 'Jedes Wort ist ein Lied.',
    literal: 'Jedes Wort ist ein Lied.',
    phonetic: 'KA-da pa-LA-bra es U-na kan-THJON',
    difficulty: 1,
    summary: 'Die Kette geht weiter: Aus Tropfen werden Worte, aus Worten wird ein Lied – dieses Lied.',
    grammar: [
      ['Wiederholung als Stilmittel', 'Das letzte Wort einer Zeile (`palabra`) beginnt die nächste – ein klassisches Stilmittel in Liedern und Gedichten.'],
    ],
    ambiguity: 'Die `canción` ist auch das Lied, das du gerade hörst – die `Canción de la lluvia`.',
    alternatives: [
      ['Y cada palabra, una canción.', 'Und jedes Wort ein Lied.', 'mit ausgelassenem Verb'],
    ],
    everyday: 'Poetisch. Aber `canción` und `palabra` sind wichtige Alltagswörter.',
    verbs: [['es', 'ser', 'Präsens, 3. Person Singular']],
  },
  {
    src: 'La lluvia no es triste, está cansada,',
    natural: 'Der Regen ist nicht traurig, er ist müde,',
    literal: 'Der Regen nicht ist traurig, ist müde,',
    phonetic: 'la JU-bja no es TRIS-te, es-TA kan-ßA-da',
    difficulty: 2,
    summary: 'Wendepunkt: Der Regen ist gar nicht traurig – er ist nur müde und hört bald auf.',
    grammar: [
      ['ser und estar in einer Zeile', '`no es triste` = er ist nicht (von Natur aus) traurig; `está cansada` = er ist (gerade) müde. **Wesen oder Zustand** – das Herz dieses Liedes.', 'es.g.ser-estar'],
      ['Verneinung', '`no` steht direkt vor dem Verb: `no es`.', 'es.g.word-order-negation'],
    ],
    ambiguity: '**Doppeldeutig**: Ein „müder“ Regen ist ein Regen, der nachlässt. Gleichzeitig spricht die Person über sich selbst: Sie ist nicht grundsätzlich traurig, nur erschöpft.',
    alternatives: [
      ['La lluvia no está triste, está cansada.', 'Der Regen ist gerade nicht traurig, sondern müde.', 'mit estar: „im Moment nicht traurig“'],
    ],
    everyday: 'Die Gegenüberstellung `no es …, está …` ist ein perfektes Merkbeispiel für ser und estar.',
    verbs: [
      ['es', 'ser', 'Präsens, 3. Person Singular – Wesen'],
      ['está', 'estar', 'Präsens, 3. Person Singular – Zustand'],
    ],
  },
  {
    src: 'Y duerme en mi corazón.',
    natural: 'und schläft in meinem Herzen.',
    literal: 'Und schläft in meinem Herzen.',
    phonetic: 'i DUER-me en mi ko-ra-THON',
    difficulty: 2,
    summary: 'Der Regen kommt zur Ruhe – im Herzen der Person. Aus Traurigkeit wird Frieden.',
    grammar: [
      ['Stammwechsel o → ue', '`dormir` → `duerme` (er/sie/es schläft). Ebenso `duermo`, `duermes` – aber `dormimos`.'],
    ],
    ambiguity: 'Der Regen „schläft“ im Herzen: Die Trauer ist nicht weg, aber sie ist ruhig geworden. Dieselbe Zeile kann tröstlich oder wehmütig klingen.',
    alternatives: [
      ['Y se queda en mi corazón.', 'Und bleibt in meinem Herzen.'],
    ],
    everyday: '`¿Duermes bien?` – Schläfst du gut? – `dormir` brauchst du täglich.',
    verbs: [['duerme', 'dormir', 'Präsens, 3. Person Singular – Stammwechsel o → ue']],
  },
];

const glossary = {
  lluvia: gl('lluvia', 'Nomen (f)', 'Regen', 'JU-bja', [['Hoy hay mucha lluvia.', 'Heute regnet es viel.']],
    'Alltagswort.', { grammar: 'weiblich: `la lluvia` – im Deutschen „der Regen“.', ipa: 'ˈʝuβja' }),
  canta: gl('cantar', 'Verb', 'singen', 'KAN-ta', [['El pájaro canta.', 'Der Vogel singt.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `cantar`' }),
  ventana: gl('ventana', 'Nomen (f)', 'Fenster', 'ben-TA-na', [['Cierra la ventana, que llueve.', 'Mach das Fenster zu, es regnet.']],
    'Alltagswort.'),
  calle: gl('calle', 'Nomen (f)', 'Straße', 'KA-je', [['La calle está mojada.', 'Die Straße ist nass.']],
    'Alltagswort.'),
  'está': gl('estar', 'Verb', 'sein (Zustand, Ort)', 'es-TA', [['El cielo está gris.', 'Der Himmel ist grau.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `estar`', grammar: 'Mit Akzent! `esta` ohne Akzent = „diese“.' }),
  gris: gl('gris', 'Adjektiv', 'grau', 'gris', [['un día gris', 'ein grauer Tag']],
    'Alltagswort – auch für trübe Stimmung.', { grammar: 'Gleiche Form für m und f; Plural `grises`.' }),
  callada: gl('callado', 'Adjektiv', 'still, schweigsam', 'ka-JA-da', [['Hoy estás muy callada.', 'Heute bist du sehr still.']],
    'Häufig über Menschen; über Orte poetisch.', { form: 'weibliche Form von `callado`', register: 'poetisch' }),
  voz: gl('voz', 'Nomen (f)', 'Stimme', 'both', [['Tienes una voz bonita.', 'Du hast eine schöne Stimme.']],
    'Alltagswort.', { grammar: 'Plural `voces` (z → c).', ipa: 'boθ' }),
  es: gl('ser', 'Verb', 'sein (Eigenschaft, Identität)', 'es', [['Es muy simpática.', 'Sie ist sehr nett.']],
    'Eines der wichtigsten Verben.', { form: '3. Person Singular Präsens von `ser`' }),
  dulce: gl('dulce', 'Adjektiv', 'süß; sanft, zärtlich', 'DUL-the', [['Este pastel es muy dulce.', 'Dieser Kuchen ist sehr süß.']],
    'Alltagswort – für Geschmack und für Menschen/Stimmen.', { ipa: 'ˈdulθe' }),
  mirada: gl('mirada', 'Nomen (f)', 'Blick', 'mi-RA-da', [['Tiene una mirada triste.', 'Sie hat einen traurigen Blick.']],
    'Häufig, leicht gehoben.', { grammar: 'Von `mirar` (schauen).' }),
  clara: gl('claro', 'Adjektiv', 'klar, hell; eindeutig', 'KLA-ra', [['El agua está clara.', 'Das Wasser ist klar.']],
    'Sehr häufig; `¡claro!` = klar!, natürlich!', { form: 'weibliche Form von `claro`' }),
  esta: gl('este', 'Demonstrativbegleiter', 'diese(r/s)', 'ES-ta', [['esta noche', 'heute Abend/heute Nacht']],
    'Sehr häufig.', { form: 'weibliche Form von `este`', grammar: 'Ohne Akzent! `está` ist das Verb.' }),
  noche: gl('noche', 'Nomen (f)', 'Nacht; Abend', 'NO-tsche', [['Buenas noches.', 'Gute Nacht.']],
    'Alltagswort.'),
  'estás': gl('estar', 'Verb', 'sein (Zustand)', 'es-TAS', [['¿Estás bien?', 'Geht es dir gut?']],
    'Sehr häufig.', { form: '2. Person Singular Präsens von `estar` (tú)' }),
  cansada: gl('cansado', 'Adjektiv', 'müde, erschöpft', 'kan-ßA-da', [['Estoy muy cansada.', 'Ich bin sehr müde.']],
    'Alltagswort.', { form: 'weibliche Form von `cansado`', grammar: 'Fast immer mit `estar`.' }),
  llueve: gl('llover', 'Verb', 'regnen', 'JUE-be', [['Hoy llueve mucho.', 'Heute regnet es viel.']],
    'Alltagswort.', { form: '3. Person Singular Präsens von `llover` (Stammwechsel o → ue)', ipa: 'ˈʝweβe' }),
  'corazón': gl('corazón', 'Nomen (m)', 'Herz', 'ko-ra-THON', [['Tienes buen corazón.', 'Du hast ein gutes Herz.']],
    'Häufig, auch als Kosewort.', { ipa: 'koɾaˈθon' }),
  paraguas: gl('paraguas', 'Nomen (m)', 'Regenschirm', 'pa-RA-guas', [['Coge el paraguas.', 'Nimm den Schirm mit.']],
    'Alltagswort.', { literal: '(etwas, das) Wasser abhält', grammar: 'Singular und Plural gleich: `el paraguas`, `los paraguas`.' }),
  'mañana': gl('mañana', 'Adverb', 'morgen', 'ma-NJA-na', [['Mañana va a llover.', 'Morgen regnet es.']],
    'Alltagswort.', { grammar: 'Als Nomen `la mañana` = der Morgen.' }),
  cielo: gl('cielo', 'Nomen (m)', 'Himmel', 'THJE-lo', [['El cielo está azul.', 'Der Himmel ist blau.']],
    'Alltagswort – auch als Kosewort: `¡Hola, cielo!`', { ipa: 'ˈθjelo' }),
  va: gl('ir', 'Verb', 'gehen; (va a …) wird', 'ba', [['Va a llover.', 'Es wird regnen.']],
    'Ständig.', { form: '3. Person Singular Präsens von `ir`' }),
  estar: gl('estar', 'Verb', 'sein (Zustand, Ort)', 'es-TAR', [['Voy a estar en casa.', 'Ich werde zu Hause sein.']],
    'Sehr häufig.', { form: 'Infinitiv' }),
  azul: gl('azul', 'Adjektiv', 'blau', 'a-THUL', [['el mar azul', 'das blaue Meer']],
    'Alltagswort.', { grammar: 'Gleiche Form für m und f; Plural `azules`.', ipa: 'aˈθul' }),
  vas: gl('ir', 'Verb', 'gehen; (vas a …) du wirst', 'bas', [['¿Vas a venir?', 'Kommst du?']],
    'Ständig.', { form: '2. Person Singular Präsens von `ir` (tú)' }),
  ser: gl('ser', 'Verb', 'sein (Wesen, Identität)', 'ßer', [['Quiero ser profesora.', 'Ich will Lehrerin werden.']],
    'Eines der wichtigsten Verben.', { form: 'Infinitiv' }),
  luz: gl('luz', 'Nomen (f)', 'Licht', 'luth', [['Enciende la luz.', 'Mach das Licht an.']],
    'Alltagswort; poetisch auch Kosewort.', { grammar: 'Plural `luces` (z → c).', ipa: 'luθ' }),
  nuestra: gl('nuestro', 'Possessivbegleiter', 'unser, unsere', 'NUES-tra', [['nuestra casa', 'unser Haus']],
    'Sehr häufig.', { form: 'weibliche Form von `nuestro`', grammar: 'Passt sich an: `nuestro, nuestra, nuestros, nuestras`.' }),
  casa: gl('casa', 'Nomen (f)', 'Haus; Zuhause', 'KA-ßa', [['Estoy en casa.', 'Ich bin zu Hause.']],
    'Alltagswort.'),
  'pequeña': gl('pequeño', 'Adjektiv', 'klein', 'pe-KE-nja', [['Mi piso es pequeño.', 'Meine Wohnung ist klein.']],
    'Alltagswort.', { form: 'weibliche Form von `pequeño`' }),
  vieja: gl('viejo', 'Adjektiv', 'alt', 'BJE-cha', [['una casa vieja', 'ein altes Haus']],
    'Alltagswort; über Menschen höflicher `mayor`.', { form: 'weibliche Form von `viejo`' }),
  baila: gl('bailar', 'Verb', 'tanzen', 'BAI-la', [['Baila muy bien.', 'Sie tanzt sehr gut.']],
    'Alltagswort.', { form: '3. Person Singular Präsens von `bailar`' }),
  tejas: gl('teja', 'Nomen (f, Pl.)', 'Dachziegel', 'TE-chas', [['Las tejas son rojas.', 'Die Dachziegel sind rot.']],
    'Eher selten im Alltag.', { form: 'Plural von `teja`' }),
  manos: gl('mano', 'Nomen (f, Pl.)', 'Hände', 'MA-nos', [['Lávate las manos.', 'Wasch dir die Hände.']],
    'Alltagswort.', { form: 'Plural von `mano`', grammar: 'Trotz -o weiblich: `la mano`.' }),
  'están': gl('estar', 'Verb', 'sein (Zustand, Ort)', 'es-TAN', [['Están en casa.', 'Sie sind zu Hause.']],
    'Sehr häufig.', { form: '3. Person Plural Präsens von `estar`' }),
  'frías': gl('frío', 'Adjektiv', 'kalt', 'FRI-as', [['Tengo las manos frías.', 'Ich habe kalte Hände.']],
    'Alltagswort.', { form: 'weibliche Pluralform von `frío`' }),
  tuyas: gl('tuyo', 'Possessivpronomen', 'deine (ersetzt ein Nomen)', 'TU-jas', [['Mis llaves y las tuyas', 'meine Schlüssel und deine']],
    'Häufig.', { form: 'weibliche Pluralform von `tuyo`', grammar: 'Mit Artikel ersetzt es das Nomen: `las tuyas` = deine (Hände).' }),
  'también': gl('también', 'Adverb', 'auch', 'tam-BJEN', [['Yo también.', 'Ich auch.']],
    'Ständig.'),
  juntos: gl('junto', 'Adjektiv', 'zusammen', 'CHUN-tos', [['Vamos juntos.', 'Wir gehen zusammen.']],
    'Sehr häufig.', { form: 'männliche Pluralform von `junto`' }),
  estamos: gl('estar', 'Verb', 'sein (Befinden, Zustand)', 'es-TA-mos', [['Estamos bien.', 'Uns geht es gut.']],
    'Sehr häufig.', { form: '1. Person Plural Präsens von `estar`' }),
  bien: gl('bien', 'Adverb', 'gut', 'bjen', [['Todo está bien.', 'Alles ist gut.']],
    'Alltagswort.'),
  cada: gl('cada', 'Begleiter', 'jede(r/s)', 'KA-da', [['cada día', 'jeden Tag']],
    'Sehr häufig.', { grammar: 'Unveränderlich – für m und f gleich.' }),
  gota: gl('gota', 'Nomen (f)', 'Tropfen', 'GO-ta', [['una gota de agua', 'ein Wassertropfen']],
    'Häufig.'),
  palabra: gl('palabra', 'Nomen (f)', 'Wort', 'pa-LA-bra', [['¿Qué significa esta palabra?', 'Was bedeutet dieses Wort?']],
    'Alltagswort – besonders beim Sprachenlernen!'),
  'canción': gl('canción', 'Nomen (f)', 'Lied', 'kan-THJON', [['Una canción de amor', 'ein Liebeslied']],
    'Alltagswort.', { ipa: 'kanˈθjon' }),
  triste: gl('triste', 'Adjektiv', 'traurig', 'TRIS-te', [['¿Por qué estás triste?', 'Warum bist du traurig?']],
    'Alltagswort.', { grammar: 'Mit `estar` = gerade traurig; mit `ser` = traurig machend/trist (`una canción triste`).' }),
  duerme: gl('dormir', 'Verb', 'schlafen', 'DUER-me', [['El niño duerme.', 'Das Kind schläft.']],
    'Alltagswort.', { form: '3. Person Singular Präsens von `dormir` (Stammwechsel o → ue)' }),
};

const song: Song = buildSong({
  id: 'song.es.cancion-de-lluvia',
  courseId: 'es',
  variant: 'es-ES',
  title: 'Canción de la lluvia',
  artist: 'Luna Mar',
  cover: { from: '#4B6CB7', to: '#182848', emoji: '🌧️' },
  genre: 'Ballade',
  level: 'A2',
  speed: 'langsam',
  themes: ['Regen', 'Liebe', 'Gefühle', 'Zuhause'],
  grammarTags: ['es.g.ser-estar', 'es.g.adjectives', 'es.g.possessives', 'es.g.estar', 'es.g.ir-a'],
  backing: { bpm: 76, style: 'ballad', key: 'D', chords: ['D', 'Bm', 'G', 'A', 'D', 'F#m', 'Em', 'A'] },
  sections: [
    { id: 'v1', label: 'Strophe 1', lines: verse1 },
    { id: 'c1', label: 'Refrain', lines: chorus },
    { id: 'v2', label: 'Strophe 2', lines: verse2 },
    { id: 'c2', label: 'Refrain', lines: chorus },
    { id: 'br', label: 'Bridge', lines: bridge },
    { id: 'c3', label: 'Refrain', lines: chorus },
  ],
  glossary,
  common: COMMON_ES,
});

export default song;
