/** „En la plaza“ – Originales Lernlied (Cumbia, es-LA, A2). */
import type { Song } from '../types';
import { COMMON_ES } from './_common-es';
import { buildSong, gl, type LineDraft } from './_layout';

const verse1: LineDraft[] = [
  {
    src: 'En la plaza hay música y color,',
    natural: 'Auf dem Platz gibt es Musik und Farben,',
    literal: 'Auf dem Platz gibt-es Musik und Farbe,',
    phonetic: 'en la PLA-ßa ai MU-ßi-ka i ko-LOR',
    difficulty: 1,
    summary: 'Der Platz ist voller Leben: Musik und bunte Farben, wohin man schaut.',
    grammar: [
      ['hay = es gibt', '**hay** sagt, dass etwas da ist. Die Form bleibt immer gleich – für Singular und Plural.', 'es.g.hay'],
    ],
    culture: 'Die `plaza` ist in lateinamerikanischen Orten das Herz des Lebens: Man trifft sich, isst, tanzt – besonders am Wochenende.',
    alternatives: [
      ['En la plaza se oye música.', 'Auf dem Platz hört man Musik.'],
      ['La plaza está llena de color.', 'Der Platz ist voller Farbe.'],
    ],
    everyday: 'Muster fürs Leben: `En … hay …` – `En mi calle hay una farmacia.` (In meiner Straße gibt es eine Apotheke.)',
    verbs: [['hay', 'haber', 'unpersönliche Form „es gibt“ (Präsens)']],
  },
  {
    src: 'Hay chavos, hay palomas, hay calor.',
    natural: 'Da sind junge Leute, Tauben – und es ist heiß.',
    literal: 'Es-gibt Jungs, es-gibt Tauben, es-gibt Hitze.',
    phonetic: 'ai TSCHA-bos, ai pa-LO-mas, ai ka-LOR',
    difficulty: 2,
    summary: 'Eine Aufzählung wie ein Rundblick: junge Leute, Tauben und die warme Luft.',
    grammar: [
      ['hay + Plural', '`hay chavos`, `hay palomas` – **hay** bleibt auch vor Plural unverändert.', 'es.g.hay'],
      ['hay calor / hace calor', 'Für Hitze sagt man meist `hace calor`; `hay (mucho) calor` hört man in Lateinamerika aber auch oft – hier passt es in die Reihe.'],
    ],
    colloquial: '`chavos` (Singular `chavo`, weiblich `chava`) ist **mexikanisch** für „Jungs, junge Leute“. Neutral: `jóvenes` oder `chicos`.',
    ambiguity: 'Vorsicht, regional verschieden: In Puerto Rico bedeutet `chavos` „Geld“.',
    alternatives: [
      ['Hay jóvenes, hay palomas, hace calor.', 'Da sind junge Leute, Tauben, und es ist heiß.', 'neutral'],
      ['Hay chicos y palomas, y hace calor.', 'Da sind Jugendliche und Tauben, und es ist heiß.'],
    ],
    everyday: '`chavos` hörst du in Mexiko ständig. In anderen Ländern verstehen es viele, sagen es aber nicht.',
    verbs: [['hay', 'haber', 'unpersönlich „es gibt“ – dreimal wiederholt']],
  },
  {
    src: 'Hay un señor que vende flores,',
    natural: 'Ein Mann verkauft Blumen,',
    literal: 'Es-gibt einen Herrn, der verkauft Blumen,',
    phonetic: 'ai un ße-NJOR ke BEN-de FLO-res',
    difficulty: 2,
    summary: 'Ein Blumenverkäufer steht mit seinem Stand auf dem Platz.',
    grammar: [
      ['hay + un/una', 'Nach **hay** steht der unbestimmte Artikel (`un`, `una`) oder gar keiner – nie `el`/`la`.', 'es.g.hay'],
      ['Relativsatz mit que', '`un señor que vende flores` = ein Herr, **der** Blumen verkauft. `que` passt für Personen und Dinge.'],
    ],
    alternatives: [
      ['Un señor vende flores.', 'Ein Herr verkauft Blumen.'],
      ['Hay una señora que vende elotes.', 'Da ist eine Frau, die Maiskolben verkauft.', 'elote = Maiskolben (Mexiko)'],
    ],
    everyday: '`señor` ist die höfliche Bezeichnung für einen erwachsenen Mann – auch als Anrede: `¡Disculpe, señor!`',
    verbs: [
      ['hay', 'haber', 'unpersönlich „es gibt“'],
      ['vende', 'vender', 'Präsens, 3. Person Singular – regelmäßiges -er-Verb'],
    ],
  },
  {
    src: 'Flores de todos los colores.',
    natural: 'Blumen in allen Farben.',
    literal: 'Blumen von allen den Farben.',
    phonetic: 'FLO-res de TO-dos los ko-LO-res',
    difficulty: 1,
    summary: 'Die Blumen sind bunt – es gibt sie in allen Farben.',
    grammar: [
      ['todos los + Plural', '`todos los colores` = alle Farben. Anders als im Deutschen steht nach `todos` noch der Artikel.', 'es.g.articles'],
      ['Plural auf -es', '`color` → `colores`, `flor` → `flores`: Nach Konsonant hängt man **-es** an.', 'es.g.gender-plural'],
    ],
    alternatives: [
      ['Flores de muchos colores.', 'Blumen in vielen Farben.'],
      ['Flores de colores.', 'Bunte Blumen.'],
    ],
    everyday: '`de todos los colores` ist eine feste, häufige Wendung: „in allen Farben“.',
  },
];

const chorus: LineDraft[] = [
  {
    src: '¿Te gusta la cumbia? ¡A mí me encanta!',
    natural: 'Magst du Cumbia? Ich liebe sie!',
    literal: 'Dir gefällt die Cumbia? Mir mir begeistert-sie!',
    phonetic: 'te GUS-ta la KUM-bja? a MI me en-KAN-ta',
    ipa: 'te ˈɣusta la ˈkumbja | a ˈmi me enˈkanta',
    difficulty: 2,
    summary: 'Die zentrale Frage des Refrains: Magst du Cumbia? Die Antwort: begeistert ja!',
    grammar: [
      ['gustar = gefallen', '`te gusta` = **es gefällt dir**. Was gefällt (`la cumbia`), ist das Subjekt; die Person steht als Pronomen davor: `me, te, le, nos …`', 'es.g.gustar'],
      ['encantar = total mögen', '`me encanta` funktioniert wie `gustar`, ist aber stärker: „ich liebe es“.', 'es.g.gustar'],
      ['A mí … – Betonung', '`A mí me …` betont die Person: „MIR jedenfalls …“ – typisch in Antworten.', 'es.g.pronouns'],
    ],
    culture: 'Die **Cumbia** stammt von der Karibikküste Kolumbiens und ist heute in ganz Lateinamerika zu Hause – besonders beliebt in Mexiko, Peru und Argentinien. Typisch: Akkordeon, Trommeln und ein wiegender Rhythmus.',
    alternatives: [
      ['¿Te gusta bailar? ¡Me encanta!', 'Tanzt du gern? Total gern!'],
      ['Sí, me gusta mucho.', 'Ja, sehr.'],
    ],
    everyday: 'Das Muster `¿Te gusta …? – ¡Me encanta!` brauchst du ständig.',
    verbs: [
      ['gusta', 'gustar', 'Präsens, 3. Person Singular – „es gefällt“'],
      ['encanta', 'encantar', 'Präsens, 3. Person Singular – „es begeistert“'],
    ],
  },
  {
    src: '¿Te gustan las flores? ¡A mí también!',
    natural: 'Magst du die Blumen? Ich auch!',
    literal: 'Dir gefallen die Blumen? Mir auch!',
    phonetic: 'te GUS-tan las FLO-res? a MI tam-BJEN',
    difficulty: 2,
    summary: 'Noch eine Frage mit gustar – diesmal im Plural. Die Sängerin nimmt die Antwort vorweg: Mir gefallen sie auch!',
    grammar: [
      ['gustan – Plural', 'Steht das, was gefällt, im Plural, steht auch das Verb im Plural: `me gusta la flor` → `me gustan las flores`.', 'es.g.gustar'],
      ['A mí también', 'Zustimmung bei `gustar`: **A mí también** (mir auch) – nicht `yo también`.', 'es.g.gustar'],
    ],
    alternatives: [
      ['¿Te gustan las flores? ¡Sí, mucho!', 'Magst du Blumen? Ja, sehr!'],
      ['A mí no.', 'Ich nicht.', 'Widerspruch'],
    ],
    everyday: '`A mí también` und `A mí tampoco` (mir auch nicht) sind im Gespräch extrem häufig.',
    verbs: [['gustan', 'gustar', 'Präsens, 3. Person Plural – „sie gefallen“']],
  },
  {
    src: '¿Bailamos un ratito? ¡Órale, ven!',
    natural: 'Tanzen wir ein bisschen? Na los, komm!',
    literal: 'Tanzen-wir ein Weilchen? Los, komm!',
    phonetic: 'bai-LA-mos un rra-TI-to? O-ra-le, BEN',
    difficulty: 2,
    summary: 'Eine Einladung zum Tanzen – kurz, direkt und herzlich.',
    grammar: [
      ['Vorschlag mit der wir-Form', '`¿Bailamos?` = Tanzen wir? Mit der wir-Form im Präsens macht man Vorschläge.', 'es.g.present-regular'],
      ['Imperativ ven', '`ven` = komm! (du-Form von `venir`, unregelmäßig).'],
    ],
    colloquial: '`¡Órale!` ist **mexikanisch**: „Los!“, „Na komm!“ oder „Okay!“ – je nach Tonfall. `un ratito` (ein Weilchen) ist die typisch lateinamerikanische Verkleinerung von `un rato`.',
    ambiguity: '`¡Órale!` hat viele Bedeutungen: Aufforderung („los!“), Zustimmung („alles klar!“) oder Staunen („wow!“). Hier ist es eine Aufforderung.',
    alternatives: [
      ['¿Bailamos un rato? ¡Vamos, ven!', 'Tanzen wir ein bisschen? Komm schon!', 'neutral'],
      ['¿Quieres bailar conmigo?', 'Willst du mit mir tanzen?'],
    ],
    everyday: '`¿Bailamos?` ist die klassische Tanzaufforderung. `¡Órale!` am besten nur locker und in Mexiko.',
    verbs: [
      ['bailamos', 'bailar', 'Präsens, 1. Person Plural (nosotros) – als Vorschlag'],
      ['ven', 'venir', 'Imperativ, 2. Person Singular (tú) – unregelmäßig'],
    ],
  },
  {
    src: '¡En la plaza todo{todo-el-mundo} el{todo-el-mundo} mundo{todo-el-mundo} canta!',
    natural: 'Auf dem Platz singen alle mit!',
    literal: 'Auf dem Platz die ganze Welt singt!',
    phonetic: 'en la PLA-ßa TO-do el MUN-do KAN-ta',
    difficulty: 2,
    summary: 'Alle singen mit – die Stimmung auf dem Platz ist ansteckend.',
    grammar: [
      ['todo el mundo + Singular', '`todo el mundo` = alle (Leute). Das Verb steht im **Singular**: `todo el mundo canta` (nicht `cantan`).', 'es.g.present-regular'],
    ],
    idioms: [['todo el mundo', 'alle, jeder', 'wörtlich „die ganze Welt“']],
    ambiguity: '`todo el mundo` kann wörtlich „die ganze Welt“ heißen – im Alltag bedeutet es fast immer einfach „alle“.',
    alternatives: [['En la plaza todos cantan.', 'Auf dem Platz singen alle.', 'todos + Plural']],
    everyday: 'Sehr häufig: `Todo el mundo lo sabe.` – Das weiß jeder.',
    verbs: [['canta', 'cantar', 'Präsens, 3. Person Singular – passend zu todo el mundo']],
  },
];

const verse2: LineDraft[] = [
  {
    src: '¿Qué{qué-más} más{qué-más}, parce? ¿Cómo vas?',
    natural: 'Na, Kumpel? Wie läuft’s?',
    literal: 'Was mehr, Partner? Wie gehst-du?',
    phonetic: 'ke MAS, PAR-ße? KO-mo BAS',
    difficulty: 3,
    summary: 'Ein Freund grüßt locker im kolumbianischen Stil.',
    grammar: [
      ['Fragen mit Fragewort', '`¿Cómo vas?` – Fragewort + Verb, Fragezeichen vorne und hinten.', 'es.g.questions'],
    ],
    idioms: [
      ['¿Qué más?', 'Wie geht’s? / Was gibt’s Neues?', 'typischer Gruß in Kolumbien'],
      ['¿Cómo vas?', 'Wie läuft’s (bei dir)?'],
    ],
    colloquial: '**Kolumbianisch**: `¿Qué más?` ist ein Gruß („Wie geht’s?“), `parce` (von `parcero`) heißt „Kumpel“ – typisch für Medellín und Bogotá. Nur unter Freunden!',
    alternatives: [
      ['¿Qué tal, amigo? ¿Cómo estás?', 'Hallo, Freund, wie geht’s?', 'neutral'],
      ['¿Qué onda, cuate?', 'Was geht, Kumpel?', 'mexikanische Variante'],
    ],
    everyday: 'In Kolumbien unter Freunden sehr natürlich. Verstehen solltest du es – benutzen am besten erst, wenn du die Leute kennst.',
    verbs: [['vas', 'ir', 'Präsens, 2. Person Singular (tú) – unregelmäßig']],
  },
  {
    src: 'Me pregunta Carlos al pasar.',
    natural: 'fragt mich Carlos im Vorbeigehen.',
    literal: 'Mich fragt Carlos beim Vorbeigehen.',
    phonetic: 'me pre-GUN-ta KAR-los al pa-ßAR',
    difficulty: 2,
    summary: 'Carlos stellt die Fragen, während er am Platz vorbeikommt.',
    grammar: [
      ['Subjekt hinter dem Verb', '`Me pregunta Carlos` – das Subjekt (`Carlos`) darf hinter dem Verb stehen, besonders nach wörtlicher Rede.', 'es.g.word-order-negation'],
      ['al + Infinitiv', '`al pasar` = beim Vorbeigehen, als er vorbeikommt. **al + Infinitiv** drückt Gleichzeitigkeit aus.'],
    ],
    alternatives: [
      ['Carlos me pregunta cuando pasa.', 'Carlos fragt mich, als er vorbeikommt.'],
      ['Me dice Carlos al pasar.', 'sagt Carlos im Vorbeigehen.'],
    ],
    everyday: '`al + Infinitiv` ist sehr praktisch: `al llegar` (beim Ankommen), `al salir` (beim Hinausgehen).',
    verbs: [
      ['pregunta', 'preguntar', 'Präsens, 3. Person Singular – regelmäßiges -ar-Verb'],
      ['pasar', 'pasar', 'Infinitiv nach al'],
    ],
  },
  {
    src: '¿Dónde es la fiesta? ¿Cuándo empieza?',
    natural: 'Wo ist die Party? Wann geht’s los?',
    literal: 'Wo ist die Party? Wann beginnt-sie?',
    phonetic: 'DON-de es la FJES-ta? KUAN-do em-PJE-ßa',
    difficulty: 2,
    summary: 'Die wichtigen Fragen zur Party: wo und wann.',
    grammar: [
      ['ser für Veranstaltungen', 'Wo eine **Veranstaltung** stattfindet, sagt man mit **ser**: `¿Dónde es la fiesta?`. Für Personen und Dinge dagegen `estar`: `¿Dónde está Carlos?`', 'es.g.ser-estar'],
      ['Fragewörter mit Akzent', '`dónde` (wo), `cuándo` (wann) – als Fragewörter immer mit Akzent.', 'es.g.questions'],
      ['Stammwechsel e → ie', '`empezar` → `empieza` (es fängt an).'],
    ],
    ambiguity: 'Im Alltag hört man auch `¿Dónde está la fiesta?`. Nach der Regel ist `es` richtig, weil eine Party ein Ereignis ist.',
    alternatives: [
      ['¿Dónde es la fiesta? ¿A qué hora empieza?', 'Wo ist die Party? Um wie viel Uhr fängt sie an?'],
      ['¿Dónde y cuándo es la fiesta?', 'Wo und wann ist die Party?'],
    ],
    everyday: 'Diese beiden Fragen brauchst du für jede Verabredung.',
    verbs: [
      ['es', 'ser', 'Präsens, 3. Person Singular – Ort einer Veranstaltung'],
      ['empieza', 'empezar', 'Präsens, 3. Person Singular – Stammwechsel e → ie'],
    ],
  },
  {
    src: '¡Ahorita, cerquita de la iglesia!',
    natural: 'Gleich – ganz in der Nähe der Kirche!',
    literal: 'Jetztchen, nahechen von der Kirche!',
    phonetic: 'a-o-RI-ta, ßer-KI-ta de la i-GLE-ßja',
    difficulty: 2,
    summary: 'Die Antwort: Es geht gleich los, und zwar ganz nah bei der Kirche.',
    grammar: [
      ['cerca de + Ort', '`cerca de la iglesia` = in der Nähe der Kirche. `cerquita` ist die Verkleinerung: „ganz nah“.'],
      ['Verkleinerung bei Adverbien', 'Lateinamerika verkleinert sogar Adverbien: `ahora` → `ahorita`, `cerca` → `cerquita` (c → qu, damit der k-Laut bleibt).'],
    ],
    colloquial: '`ahorita` und `cerquita` sind typisch lateinamerikanische Verkleinerungen, besonders in **Mexiko** und **Kolumbien**.',
    ambiguity: '**Vorsicht bei `ahorita`!** In Mexiko kann es „sofort“, „gleich“ oder „irgendwann später“ heißen – der Tonfall entscheidet. In Kolumbien und Venezuela heißt es oft „vorhin“ oder „gleich“.',
    culture: 'In vielen lateinamerikanischen Orten steht die Kirche direkt an der Plaza – ein beliebter Treffpunkt.',
    alternatives: [
      ['¡Ahora mismo, cerca de la iglesia!', 'Jetzt gleich, in der Nähe der Kirche!', 'neutral'],
      ['Enseguida, al lado de la iglesia.', 'Sofort, neben der Kirche.'],
    ],
    everyday: '`ahorita` wirst du in Mexiko ständig hören – rechne damit, dass es nicht immer „sofort“ bedeutet.',
  },
];

const bridge: LineDraft[] = [
  {
    src: 'A mi abuela le gusta el danzón,',
    natural: 'Meine Oma mag Danzón,',
    literal: 'Meiner Großmutter ihr gefällt der Danzón,',
    phonetic: 'a mi a-BUE-la le GUS-ta el dan-ßON',
    difficulty: 2,
    summary: 'Jede Generation hat ihre Musik – die Oma liebt den klassischen Danzón.',
    grammar: [
      ['gustar mit le', '`le gusta` = es gefällt **ihm/ihr**. Mit `a mi abuela` wird klar, wem – beides zusammen ist normal.', 'es.g.gustar'],
      ['Possessivbegleiter', '`mi abuela` = meine Großmutter.', 'es.g.possessives'],
    ],
    culture: 'Der **Danzón** kommt aus Kuba und ist in Mexiko sehr beliebt – etwa in Veracruz oder Mexiko-Stadt, wo ältere Paare am Wochenende auf öffentlichen Plätzen elegant Danzón tanzen.',
    alternatives: [
      ['Mi abuela prefiere el danzón.', 'Meine Oma mag lieber Danzón.'],
      ['A mi abuelo le gusta el bolero.', 'Mein Opa mag Bolero.'],
    ],
    everyday: 'Das Muster `A + Person + le gusta …` ist Alltag: `A mi hermana le gusta leer.` (Meine Schwester liest gern.)',
    verbs: [['gusta', 'gustar', 'Präsens, 3. Person Singular']],
  },
  {
    src: 'A mi hermano le gusta el reguetón,',
    natural: 'mein Bruder mag Reggaeton,',
    literal: 'Meinem Bruder ihm gefällt der Reggaeton,',
    phonetic: 'a mi er-MA-no le GUS-ta el rre-ge-TON',
    difficulty: 2,
    summary: 'Der Bruder hört lieber modernen Reggaeton.',
    grammar: [
      ['Gleiches Muster', '`A mi hermano le gusta …` – dieselbe Struktur wie davor. `le` steht für „ihm“ wie für „ihr“.', 'es.g.gustar'],
    ],
    culture: '**Reggaeton** (spanisch `reguetón`) entstand in Puerto Rico und Panama und ist heute einer der erfolgreichsten Musikstile aus Lateinamerika.',
    alternatives: [
      ['A mi hermana le gusta el pop.', 'Meine Schwester mag Pop.'],
      ['Mi hermano escucha reguetón.', 'Mein Bruder hört Reggaeton.'],
    ],
    everyday: 'Über Musikgeschmack spricht man ständig – dieses Muster ist Gold wert.',
    verbs: [['gusta', 'gustar', 'Präsens, 3. Person Singular']],
  },
  {
    src: 'Y a nosotros, ¿qué nos gusta?',
    natural: 'Und was mögen wir?',
    literal: 'Und uns, was uns gefällt?',
    phonetic: 'i a no-ßO-tros, KE nos GUS-ta',
    difficulty: 2,
    summary: 'Und die Clique? Die Frage leitet zur Antwort über.',
    grammar: [
      ['gustar mit nos', '`nos gusta` = es gefällt **uns**. `a nosotros` betont: „und UNS?“', 'es.g.gustar'],
      ['Fragewort qué', '`¿qué?` = was? – mit Akzent. Das **¿** steht dort, wo die Frage beginnt – auch mitten im Satz.', 'es.g.questions'],
    ],
    alternatives: [
      ['¿Y qué nos gusta a nosotros?', 'Und was mögen wir?'],
      ['¿Y a vosotros qué os gusta?', 'Und was mögt ihr?', 'Spanien (vosotros)'],
    ],
    everyday: 'Nützlich: `¿Qué te gusta?` (du) / `¿Qué les gusta?` (ihr, Lateinamerika).',
    verbs: [['gusta', 'gustar', 'Präsens, 3. Person Singular']],
  },
  {
    src: '¡La cumbia con acordeón!',
    natural: 'Cumbia mit Akkordeon!',
    literal: 'Die Cumbia mit Akkordeon!',
    phonetic: 'la KUM-bja kon a-kor-de-ON',
    difficulty: 1,
    summary: 'Die Antwort der Freunde: klassische Cumbia – mit Akkordeon!',
    grammar: [
      ['Artikel bei Vorlieben', 'Bei Vorlieben steht der bestimmte Artikel: `la cumbia`, `el danzón` – auch wo Deutsch keinen hat.', 'es.g.articles'],
    ],
    culture: 'Das **Akkordeon** prägt viele Cumbia-Stile – von der kolumbianischen Karibikküste bis zur Cumbia im Norden Mexikos.',
    alternatives: [
      ['¡Nos gusta la cumbia!', 'Wir mögen Cumbia!'],
      ['¡La cumbia, claro!', 'Cumbia natürlich!'],
    ],
    everyday: 'Kurzantworten ohne Verb sind im Gespräch normal: `—¿Qué te gusta? —¡El fútbol!`',
  },
];

const glossary = {
  plaza: gl('plaza', 'Nomen (f)', 'Platz (in der Stadt)', 'PLA-ßa', [['Nos vemos en la plaza.', 'Wir sehen uns auf dem Platz.']],
    'Alltagswort. Hauptplatz: `la plaza mayor`, in Mexiko `el zócalo`.'),
  hay: gl('haber', 'Verb (unpersönlich)', 'es gibt', 'ai', [['Hay un problema.', 'Es gibt ein Problem.'], ['¿Hay pan?', 'Gibt es Brot?']],
    'Eines der nützlichsten Wörter überhaupt.', { form: 'unpersönliche Form von `haber` im Präsens', grammar: 'Immer gleich, auch im Plural: `hay flores`. Das h ist stumm: „ai“.' }),
  'música': gl('música', 'Nomen (f)', 'Musik', 'MU-ßi-ka', [['¿Qué música te gusta?', 'Welche Musik magst du?']],
    'Alltagswort.', { grammar: 'Betonung auf der ersten Silbe (Akzent!).' }),
  color: gl('color', 'Nomen (m)', 'Farbe', 'ko-LOR', [['¿De qué color es?', 'Welche Farbe hat es?']],
    'Alltagswort.', { grammar: 'männlich: `el color` – im Deutschen „die Farbe“.' }),
  chavos: gl('chavo', 'Nomen (m, Pl.)', 'Jungs, junge Leute (Mexiko)', 'TSCHA-bos', [['Los chavos juegan fútbol.', 'Die Jungs spielen Fußball.']],
    'In Mexiko sehr häufig; anderswo eher `chicos` oder `jóvenes`.',
    { form: 'Plural von `chavo`', register: 'umgangssprachlich', colloquial: '**Mexikanisch**. Weiblich: `chava`. In Puerto Rico heißt `chavos` dagegen „Geld“.' }),
  palomas: gl('paloma', 'Nomen (f, Pl.)', 'Tauben', 'pa-LO-mas', [['Hay muchas palomas en la plaza.', 'Auf dem Platz gibt es viele Tauben.']],
    'Alltagswort.', { form: 'Plural von `paloma`' }),
  calor: gl('calor', 'Nomen (m)', 'Hitze, Wärme', 'ka-LOR', [['Hace mucho calor.', 'Es ist sehr heiß.']],
    'Alltagswort. `Tengo calor` = mir ist heiß.', { grammar: 'männlich: `el calor`.' }),
  'señor': gl('señor', 'Nomen (m)', 'Herr, Mann', 'ße-NJOR', [['Buenos días, señor.', 'Guten Morgen, mein Herr.']],
    'Höflich und sehr häufig, auch als Anrede.', { grammar: '`ñ` klingt wie „nj“. Weiblich: `señora`.' }),
  vende: gl('vender', 'Verb', 'verkaufen', 'BEN-de', [['Vende frutas en el mercado.', 'Er verkauft Obst auf dem Markt.']],
    'Alltagswort.', { form: '3. Person Singular Präsens von `vender`' }),
  flores: gl('flor', 'Nomen (f, Pl.)', 'Blumen', 'FLO-res', [['Te traigo flores.', 'Ich bringe dir Blumen.']],
    'Alltagswort.', { form: 'Plural von `flor`' }),
  colores: gl('color', 'Nomen (m, Pl.)', 'Farben', 'ko-LO-res', [['Me gustan los colores vivos.', 'Ich mag kräftige Farben.']],
    'Alltagswort.', { form: 'Plural von `color`' }),
  gusta: gl('gustar', 'Verb', 'gefallen (→ mögen)', 'GUS-ta', [['Me gusta el café.', 'Ich mag Kaffee.'], ['¿Te gusta?', 'Gefällt es dir?']],
    'Eines der wichtigsten Verben im Alltag.', { form: '3. Person Singular Präsens von `gustar`', grammar: 'Was gefällt, ist das Subjekt: `me gusta la música` (Singular) / `me gustan las flores` (Plural).' }),
  cumbia: gl('cumbia', 'Nomen (f)', 'Cumbia (Musik- und Tanzstil)', 'KUM-bja', [['Bailamos cumbia toda la noche.', 'Wir tanzen die ganze Nacht Cumbia.']],
    'In ganz Lateinamerika bekannt.'),
  encanta: gl('encantar', 'Verb', 'sehr gefallen, begeistern (→ lieben)', 'en-KAN-ta', [['Me encanta esta canción.', 'Ich liebe dieses Lied.']],
    'Sehr häufig – stärker als `gustar`.', { form: '3. Person Singular Präsens von `encantar`', grammar: 'Wie `gustar`: `me encanta` / `me encantan`. Braucht kein `mucho` – es ist schon stark.' }),
  gustan: gl('gustar', 'Verb', 'gefallen (→ mögen)', 'GUS-tan', [['Me gustan los perros.', 'Ich mag Hunde.']],
    'Sehr häufig.', { form: '3. Person Plural Präsens von `gustar`' }),
  'también': gl('también', 'Adverb', 'auch', 'tam-BJEN', [['Yo también.', 'Ich auch.'], ['A mí también.', 'Mir auch.']],
    'Ständig.', { grammar: 'Verneint: `tampoco` (auch nicht).' }),
  bailamos: gl('bailar', 'Verb', 'tanzen', 'bai-LA-mos', [['¿Bailamos?', 'Tanzen wir?']],
    'Die klassische Tanzaufforderung.', { form: '1. Person Plural Präsens von `bailar`' }),
  ratito: gl('ratito', 'Nomen (m)', 'Weilchen, kurze Zeit', 'rra-TI-to', [['Espera un ratito.', 'Warte kurz.']],
    'In Lateinamerika sehr häufig.', { form: 'Verkleinerungsform von `rato`', register: 'umgangssprachlich', colloquial: 'Verkleinerung (-ito) – freundlich und typisch lateinamerikanisch.' }),
  'órale': gl('¡órale!', 'Interjektion', 'los!, na komm!; okay!; wow!', 'O-ra-le', [['¡Órale, vámonos!', 'Los, gehen wir!']],
    'In Mexiko sehr häufig, außerhalb kaum.', { register: 'umgangssprachlich', colloquial: '**Mexikanisch.** Die Bedeutung hängt vom Tonfall ab: Aufforderung, Zustimmung oder Staunen.' }),
  ven: gl('venir', 'Verb', 'kommen', 'ben', [['¡Ven aquí!', 'Komm her!']],
    'Sehr häufig.', { form: 'Imperativ 2. Person Singular (tú) von `venir`' }),
  'todo-el-mundo': gl('todo el mundo', 'Wendung', 'alle, jeder', 'TO-do el MUN-do', [['Todo el mundo está aquí.', 'Alle sind da.']],
    'Sehr häufig.', { literal: 'die ganze Welt', grammar: 'Mit Verb im Singular: `todo el mundo canta`.' }),
  canta: gl('cantar', 'Verb', 'singen', 'KAN-ta', [['Mi abuela canta muy bien.', 'Meine Oma singt sehr gut.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `cantar`' }),
  'qué-más': gl('¿qué más?', 'Wendung', 'Wie geht’s? (Gruß, Kolumbien)', 'ke MAS', [['¿Qué más, cómo estás?', 'Na, wie geht’s dir?']],
    'In Kolumbien ein ganz normaler lockerer Gruß.', { literal: 'was mehr?', register: 'umgangssprachlich', colloquial: '**Kolumbianisch.** Anderswo heißt `¿qué más?` einfach „was noch?“.' }),
  parce: gl('parce', 'Nomen (m/f)', 'Kumpel, Freund(in)', 'PAR-ße', [['¿Qué más, parce?', 'Na, Kumpel?']],
    'Unter Freunden in Kolumbien sehr häufig.', { form: 'Kurzform von `parcero/parcera`', register: 'umgangssprachlich', colloquial: '**Kolumbianisch**, besonders Medellín und Bogotá.' }),
  'cómo': gl('cómo', 'Fragewort', 'wie', 'KO-mo', [['¿Cómo te llamas?', 'Wie heißt du?']],
    'Sehr häufig.', { grammar: 'Als Fragewort mit Akzent.' }),
  vas: gl('ir', 'Verb', 'gehen, fahren', 'bas', [['¿Adónde vas?', 'Wohin gehst du?']],
    'Sehr häufig.', { form: '2. Person Singular Präsens von `ir` (tú)', grammar: '`ir` ist ganz unregelmäßig: `voy, vas, va, vamos, van`.' }),
  pregunta: gl('preguntar', 'Verb', 'fragen', 'pre-GUN-ta', [['Me pregunta la hora.', 'Er fragt mich nach der Uhrzeit.']],
    'Alltagswort.', { form: '3. Person Singular Präsens von `preguntar`' }),
  carlos: gl('Carlos', 'Eigenname (m)', 'Carlos (Vorname)', 'KAR-los', [['Carlos es de Bogotá.', 'Carlos kommt aus Bogotá.']],
    'Häufiger Vorname in der ganzen spanischsprachigen Welt.'),
  pasar: gl('pasar', 'Verb', 'vorbeigehen, vorbeikommen; passieren', 'pa-ßAR', [['¿Qué pasa?', 'Was ist los?'], ['Paso por tu casa.', 'Ich komme bei dir vorbei.']],
    'Sehr vielseitig und häufig.'),
  'dónde': gl('dónde', 'Fragewort', 'wo', 'DON-de', [['¿Dónde vives?', 'Wo wohnst du?']],
    'Sehr häufig.', { grammar: 'Wohin = `adónde`, woher = `de dónde`.' }),
  es: gl('ser', 'Verb', 'sein; stattfinden (Veranstaltung)', 'es', [['La fiesta es en mi casa.', 'Die Party ist bei mir zu Hause.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `ser`', grammar: 'Für Veranstaltungen nimmt man `ser`, auch beim Ort: `La clase es aquí.`' }),
  fiesta: gl('fiesta', 'Nomen (f)', 'Party, Fest', 'FJES-ta', [['Hay una fiesta el sábado.', 'Am Samstag gibt es eine Party.']],
    'Alltagswort.'),
  'cuándo': gl('cuándo', 'Fragewort', 'wann', 'KUAN-do', [['¿Cuándo llegas?', 'Wann kommst du an?']],
    'Sehr häufig.', { grammar: 'Mit Akzent als Fragewort; ohne Akzent (`cuando`) = „wenn/als“.' }),
  empieza: gl('empezar', 'Verb', 'anfangen, beginnen', 'em-PJE-ßa', [['La película empieza a las ocho.', 'Der Film fängt um acht an.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `empezar` (Stammwechsel e → ie)' }),
  ahorita: gl('ahorita', 'Adverb', 'gleich, sofort; (je nach Land auch) vorhin oder irgendwann', 'a-o-RI-ta', [['Ahorita vengo.', 'Ich komme gleich.']],
    'In Mexiko und Kolumbien ständig zu hören.',
    { form: 'Verkleinerungsform von `ahora`', register: 'umgangssprachlich', colloquial: 'Typisch lateinamerikanisch. In Mexiko berühmt vieldeutig: von „sofort“ bis „vielleicht später“.' }),
  cerquita: gl('cerquita', 'Adverb', 'ganz nah', 'ßer-KI-ta', [['Vivo cerquita de aquí.', 'Ich wohne ganz in der Nähe.']],
    'In Lateinamerika häufig.', { form: 'Verkleinerungsform von `cerca`', register: 'umgangssprachlich', colloquial: 'Die Verkleinerung macht aus „nah“ ein freundliches „ganz nah“.' }),
  iglesia: gl('iglesia', 'Nomen (f)', 'Kirche', 'i-GLE-ßja', [['La iglesia está en la plaza.', 'Die Kirche steht am Platz.']],
    'Alltagswort, oft als Orientierungspunkt.'),
  abuela: gl('abuela', 'Nomen (f)', 'Großmutter, Oma', 'a-BUE-la', [['Mi abuela tiene ochenta años.', 'Meine Oma ist achtzig.']],
    'Alltagswort; männlich `abuelo`. Liebevoll: `abuelita`.'),
  'danzón': gl('danzón', 'Nomen (m)', 'Danzón (eleganter Paartanz aus Kuba)', 'dan-ßON', [['Los sábados bailan danzón.', 'Samstags tanzen sie Danzón.']],
    'Vor allem in Kuba und Mexiko bekannt.'),
  hermano: gl('hermano', 'Nomen (m)', 'Bruder', 'er-MA-no', [['Tengo un hermano.', 'Ich habe einen Bruder.']],
    'Alltagswort; `hermana` = Schwester, `hermanos` = Geschwister.', { grammar: 'Das h ist stumm.' }),
  'reguetón': gl('reguetón', 'Nomen (m)', 'Reggaeton (Musikstil)', 'rre-ge-TON', [['En la fiesta ponen reguetón.', 'Auf der Party läuft Reggaeton.']],
    'Sehr verbreitet.', { grammar: 'Spanische Schreibweise laut Wörterbuch; auch `reggaetón` ist üblich.' }),
  nosotros: gl('nosotros', 'Personalpronomen', 'wir; uns (nach Präposition)', 'no-ßO-tros', [['Nosotros vamos también.', 'Wir kommen auch.'], ['a nosotros', 'uns']],
    'Häufig.', { grammar: 'Weiblich: `nosotras`. Nach `a` betont es „uns“: `a nosotros nos gusta`.' }),
  'qué': gl('qué', 'Fragewort', 'was; welche(r/s)', 'ke', [['¿Qué quieres?', 'Was willst du?']],
    'Ständig.', { grammar: 'Mit Akzent als Fragewort; ohne Akzent (`que`) verbindet es Sätze.' }),
  'acordeón': gl('acordeón', 'Nomen (m)', 'Akkordeon', 'a-kor-de-ON', [['Mi tío toca el acordeón.', 'Mein Onkel spielt Akkordeon.']],
    'Bekannt – besonders in Kolumbien und Nordmexiko.'),
};

const song: Song = buildSong({
  id: 'song.es.en-la-plaza',
  courseId: 'es',
  variant: 'es-LA',
  title: 'En la plaza',
  artist: 'Sonido Colibrí',
  cover: { from: '#11998E', to: '#38EF7D', emoji: '🪗' },
  genre: 'Cumbia',
  level: 'A2',
  speed: 'mittel',
  themes: ['Plaza', 'Musik & Tanz', 'Vorlieben', 'Freunde'],
  grammarTags: ['es.g.hay', 'es.g.gustar', 'es.g.questions', 'es.g.ser-estar', 'es.g.present-regular'],
  backing: { bpm: 96, style: 'cumbia', key: 'Am', chords: ['Am', 'Dm', 'G', 'C', 'F', 'Dm', 'E7', 'Am'] },
  sections: [
    { id: 'v1', label: 'Strophe 1', lines: verse1 },
    { id: 'c1', label: 'Refrain', lines: chorus },
    { id: 'v2', label: 'Strophe 2', lines: verse2 },
    { id: 'c2', label: 'Refrain', lines: chorus },
    { id: 'br', label: 'Bridge', lines: bridge },
    { id: 'c3', label: 'Refrain', lines: chorus },
  ],
  glossary,
  common: COMMON_ES,
});

export default song;
