/**
 * „Festa no quintal“ – Originales Lernlied (Forró, pt-BR, A2, viel Umgangssprache).
 * Lautschrift: GROSS = betont, ã/õ/ẽ/ĩ/ũ = nasal, „w“ = portugiesisches v, „sch“ vor Vokal weich wie in „Garage“,
 * „h“ = brasilianisches r/rr (kräftig gehaucht).
 */
import type { Song } from '../types';
import { COMMON_PT } from './_common-pt';
import { buildSong, gl, type LineDraft } from './_layout';

const verse1: LineDraft[] = [
  {
    src: 'Sábado é dia de festa no quintal,',
    natural: 'Am Samstag steigt die Party im Hof,',
    literal: 'Samstag ist Tag von Fest im Hof,',
    phonetic: 'ßA-ba-du Ä DSCHI-a dschi FÄS-ta nu kĩ-TAU',
    difficulty: 2,
    summary: 'Die Einladung: Am Samstag wird im Hof gefeiert.',
    grammar: [
      ['ser für Tage und Termine', '`Sábado é dia de festa` – Tage und Termine mit **ser**.', 'pt.g.ser'],
      ['no = em + o', '`no quintal` = im Hof.', 'pt.g.contractions'],
      ['l am Silbenende = „u“', '`quintal` klingt wie „kĩ-TAU“: **l am Silbenende** wird in Brasilien zu u.'],
    ],
    culture: '**Festas no quintal** (Hoffeste) sind in Brasilien beliebt – besonders im Juni bei den **Festas Juninas** mit Forró, Maisgerichten und Lagerfeuer.',
    alternatives: [
      ['No sábado tem festa no quintal.', 'Am Samstag gibt’s eine Party im Hof.', 'gesprochen: tem = es gibt'],
      ['Sábado vai ter festa lá em casa.', 'Samstag gibt’s eine Party bei uns.'],
    ],
    everyday: '`dia de festa` = Festtag, Party-Tag – ganz natürlich.',
    verbs: [['é', 'ser', 'Presente, 3. Person Singular']],
  },
  {
    src: 'Vem{vem.imp} com a{a-gente} gente{a-gente}, traz o pessoal!',
    natural: 'Komm mit uns und bring die Leute mit!',
    literal: 'Komm mit den Leuten, bring das Personal!',
    phonetic: 'wẽj kõ a SCHẼN-tschi, TRAS u pe-ßo-AU',
    difficulty: 2,
    summary: 'Alle sind eingeladen – und sollen ihre Freunde gleich mitbringen.',
    grammar: [
      ['Befehlsform im Alltag', '`vem!` (komm!) und `traz!` (bring!) sind die umgangssprachlichen Befehlsformen – in Brasilien üblich, auch wenn man `você` sagt. Schriftlich: `venha`, `traga`.'],
      ['com a gente = mit uns', '`a gente` = wir/uns: `com a gente` = mit uns.', 'pt.g.pronouns'],
    ],
    colloquial: '`a gente` (wir/uns) und `o pessoal` (die Leute, die Clique) sind typische Alltagssprache. Die kurzen Befehle `vem!`, `traz!` klingen locker und herzlich.',
    alternatives: [
      ['Venha com a gente e traga seus amigos!', 'Kommen Sie mit und bringen Sie Ihre Freunde mit!', 'höflich/schriftlich'],
      ['Vem com a gente, chama a galera!', 'Komm mit, sag der Clique Bescheid!', 'sehr locker (galera = Clique)'],
    ],
    everyday: '`Vem com a gente!` hörst du oft, wenn Leute dich spontan einladen – sehr natürlich.',
    verbs: [
      ['vem', 'vir', 'Befehlsform (umgangssprachlich, du) – „komm!“'],
      ['traz', 'trazer', 'Befehlsform (umgangssprachlich, du) – „bring!“'],
    ],
  },
  {
    src: 'Milho, bolo, pé{pe-de-moleque} de{pe-de-moleque} moleque{pe-de-moleque} e pinhão,',
    natural: 'Mais, Kuchen, Erdnusskrokant und Araukariensamen,',
    literal: 'Mais, Kuchen, Fuß von Gassenjunge und Araukarienkern,',
    phonetic: 'MI-lju, BO-lu, PÄ dschi mo-LÄ-ki i pi-NJÃU',
    ipa: 'ˈmiʎu ˈbolu ˈpɛ dʒi moˈlɛki i piˈɲɐ̃w̃',
    difficulty: 3,
    summary: 'Das Buffet: typische Leckereien der brasilianischen Junifeste.',
    grammar: [
      ['lh und nh', '`milho` (lh ≈ „lj“) und `pinhão` (nh ≈ „nj“) – zwei typisch portugiesische Laute.'],
      ['Aufzählung ohne Artikel', 'In Aufzählungen fallen Artikel oft weg – wie im Deutschen: „Mais, Kuchen, …“', 'pt.g.articles-gender'],
    ],
    idioms: [['pé de moleque', 'Erdnusskrokant (Süßigkeit)', 'wörtlich „Fuß eines Gassenjungen“']],
    culture: 'Alles typische **Festa-Junina**-Speisen: `milho` (gekochter oder gegrillter Mais), `bolo` (etwa `bolo de milho`, Maiskuchen), `pé de moleque` (Erdnusskrokant mit Rohrzucker) und `pinhão` (gekochte Araukariensamen – besonders im Süden und Südosten beliebt).',
    ambiguity: '`pé de moleque` klingt wörtlich seltsam („Fuß eines Gassenjungen“) – gemeint ist eine Süßigkeit. Woher der Name kommt, ist nicht sicher; eine beliebte Erklärung: Verkäuferinnen riefen naschenden Kindern „Pede, moleque!“ zu – „Frag doch, Junge!“.',
    alternatives: [
      ['Tem milho, bolo e pamonha.', 'Es gibt Mais, Kuchen und Pamonha.', 'pamonha = Maisspeise im Maisblatt'],
      ['Tem muita comida boa.', 'Es gibt viel gutes Essen.'],
    ],
    everyday: '`milho` und `bolo` brauchst du oft. `pé de moleque` bekommst du im Juni an jeder Ecke.',
  },
  {
    src: 'E a sanfona do vovô, que{que.excl} emoção!',
    natural: 'Und Opas Akkordeon – wie schön!',
    literal: 'Und das Akkordeon des Opas, welche Rührung!',
    phonetic: 'i a ßã-FO-na du wo-WO, ki e-mo-ßÃU',
    difficulty: 2,
    summary: 'Der Opa spielt Akkordeon – der bewegende Höhepunkt des Festes.',
    grammar: [
      ['do = de + o', '`do vovô` = des Opas / von Opa. **de + o** verschmilzt zu **do**.', 'pt.g.contractions'],
      ['Que + Nomen!', '`Que emoção!` = Wie bewegend! Ausrufe mit **que** + Nomen: `Que calor!`, `Que confusão!`'],
    ],
    culture: 'Die **sanfona** (Akkordeon) bildet mit `zabumba` (große Trommel) und `triângulo` (Triangel) das klassische Forró-Trio aus dem Nordosten Brasiliens.',
    alternatives: [
      ['E o vovô tocando sanfona, que alegria!', 'Und Opa spielt Akkordeon, welche Freude!'],
      ['E a sanfona do avô, que emoção!', 'Und Großvaters Akkordeon, wie bewegend!', 'neutral: avô statt vovô'],
    ],
    everyday: '`Que emoção!` sagt man, wenn etwas berührt oder aufregt – sehr alltäglich.',
  },
];

const chorus: LineDraft[] = [
  {
    src: 'Bora dançar, bora pro quintal!',
    natural: 'Los, lasst uns tanzen, ab in den Hof!',
    literal: 'Gehen-wir tanzen, gehen-wir zum Hof!',
    phonetic: 'BÓ-ra dã-ßAH, BÓ-ra pru kĩ-TAU',
    difficulty: 2,
    summary: 'Der Aufruf des Refrains: Alle sollen in den Hof kommen und tanzen.',
    grammar: [
      ['bora + Infinitiv', '`bora dançar` = lass uns tanzen. `bora` wirkt wie `vamos`.'],
      ['pro = para + o', '`pro quintal` = in den Hof – gesprochene Verschmelzung von **para + o**.', 'pt.g.contractions'],
    ],
    colloquial: '`bora` (aus `vamos embora`) ist sehr umgangssprachlich: „Los!“, „Auf geht’s!“. `pro` ist die gesprochene Form von `para o`. Beides hörst du in Brasilien ständig.',
    alternatives: [
      ['Vamos dançar, vamos pro quintal!', 'Lass uns tanzen, ab in den Hof!', 'etwas neutraler'],
      ['Vamos dançar no quintal!', 'Lass uns im Hof tanzen!', 'neutral'],
    ],
    everyday: '`Bora?` – „Gehen wir?“ – ist unter Freunden eine der häufigsten Fragen überhaupt.',
    verbs: [
      ['bora', 'ir', 'umgangssprachliche Kurzform von „vamos embora“ – los, lass uns …'],
      ['dançar', 'dançar', 'Infinitiv'],
    ],
  },
  {
    src: 'Cê vem também? Vai ser legal!',
    natural: 'Kommst du auch? Das wird super!',
    literal: 'Du kommst auch? Geht sein toll!',
    phonetic: 'ße wẽj tã-BẼJ? wai ßeh le-GAU',
    difficulty: 2,
    summary: 'Die persönliche Einladung: Du kommst doch auch, oder?',
    grammar: [
      ['ir + Infinitiv = Zukunft', '`vai ser` = wird sein. Im Alltag bildet man die Zukunft fast immer mit **ir + Infinitiv**.'],
      ['cê = você', '`cê` ist die gesprochene Kurzform von `você` (du).', 'pt.g.pronouns'],
    ],
    colloquial: '`cê` (= `você`) und `legal` (= cool, toll) sind typisch brasilianische Umgangssprache. `cê` spricht man nur – geschrieben höchstens im Chat.',
    alternatives: [
      ['Você vem também? Vai ser ótimo!', 'Kommst du auch? Das wird großartig!', 'neutral'],
      ['Bora? Vai ser massa!', 'Kommst du? Wird mega!', 'Nordosten: massa = cool'],
    ],
    everyday: '`Legal!` ist DAS Wort für „cool, schön“ in Brasilien – sehr häufig.',
    verbs: [
      ['vem', 'vir', 'Presente, 3. Person Singular – mit cê/você'],
      ['vai', 'ir', 'Presente, 3. Person Singular – ir + Infinitiv (Zukunft)'],
      ['ser', 'ser', 'Infinitiv'],
    ],
  },
  {
    src: 'Um passo à frente, um passo atrás,',
    natural: 'Ein Schritt nach vorn, ein Schritt zurück,',
    literal: 'Ein Schritt zur Front, ein Schritt hinten,',
    phonetic: 'ũ PA-ßu a FRẼN-tschi, ũ PA-ßu a-TRAS',
    difficulty: 2,
    summary: 'Die Tanzschritte: vor und zurück – im Forró-Rhythmus.',
    grammar: [
      ['à = a + a', '`à frente` = nach vorn. **a + a** verschmilzt zu **à** (mit Gravis-Akzent).', 'pt.g.contractions'],
    ],
    ambiguity: 'Auch bildlich: „ein Schritt vor, einer zurück“ – so geht es im Leben manchmal. Hier aber ganz wörtlich: Tanzen!',
    culture: 'Forró tanzt man eng zu zweit mit kleinen, federnden Schritten – je nach Stil seitlich oder vor und zurück.',
    alternatives: [
      ['Um passo pra frente, um pra trás.', 'Ein Schritt vor, einer zurück.', 'gesprochen'],
      ['Pra frente e pra trás.', 'Vor und zurück.'],
    ],
    everyday: '`à frente` und `atrás` brauchst du auch für Wegbeschreibungen: `O banco fica atrás da igreja.`',
  },
  {
    src: 'Essa noite ninguém vai parar!',
    natural: 'Heute Nacht hört keiner auf!',
    literal: 'Diese Nacht niemand geht aufhören!',
    phonetic: 'Ä-ßa NOI-tschi nĩ-GẼJ wai pa-RAH',
    difficulty: 2,
    summary: 'Das Versprechen: Die Party geht die ganze Nacht.',
    grammar: [
      ['ir + Infinitiv', '`vai parar` = wird aufhören – hier verneint durch `ninguém` (niemand).'],
      ['essa statt esta', 'Im brasilianischen Alltag sagt man meist `essa` statt `esta`: `essa noite` = heute Nacht.'],
    ],
    ambiguity: '`essa noite` kann je nach Zusammenhang auch „letzte Nacht“ heißen. Hier ist wegen `vai parar` (Zukunft) klar: die kommende Nacht.',
    alternatives: [
      ['Hoje ninguém vai parar!', 'Heute hört keiner auf!'],
      ['A festa vai até de manhã!', 'Die Party geht bis zum Morgen!'],
    ],
    everyday: '`Ninguém vai parar` – typischer Party-Satz.',
    verbs: [
      ['vai', 'ir', 'Presente, 3. Person Singular – Zukunft mit ir'],
      ['parar', 'parar', 'Infinitiv – aufhören'],
    ],
  },
];

const verse2: LineDraft[] = [
  {
    src: 'Olha a Maria dançando com o João,',
    natural: 'Schau, Maria tanzt mit João,',
    literal: 'Schau die Maria tanzend mit dem João,',
    phonetic: 'Ó-lja a ma-RI-a dã-ßÃN-du kõ u schu-ÃU',
    difficulty: 2,
    summary: 'Ein Blick auf die Tanzfläche: Maria und João tanzen zusammen.',
    grammar: [
      ['Artikel vor Namen', '`a Maria`, `o João` – im brasilianischen Alltag steht vor Vornamen oft der Artikel.', 'pt.g.articles-gender'],
      ['Gerundium -ndo', '`dançando` = tanzend. Brasilien benutzt das Gerundium sehr oft: `estou dançando` = ich tanze gerade.'],
    ],
    alternatives: [
      ['Olha só: a Maria está dançando com o João!', 'Schau mal: Maria tanzt mit João!'],
      ['A Maria dança com o João.', 'Maria tanzt mit João.'],
    ],
    everyday: '`Olha!` / `Olha só!` (Schau mal!) hörst du ständig – zum Zeigen und zum Betonen.',
    verbs: [
      ['olha', 'olhar', 'Befehlsform (umgangssprachlich) – „schau!“'],
      ['dançando', 'dançar', 'Gerundium'],
    ],
  },
  {
    src: 'Ele pisa no pé, que{que.excl} confusão!',
    natural: 'Er tritt ihr auf den Fuß – was für ein Durcheinander!',
    literal: 'Er tritt auf-den Fuß, welche Verwirrung!',
    phonetic: 'E-li PI-sa nu PÄ, ki kõ-fu-SÃU',
    difficulty: 2,
    summary: 'Ein kleines Missgeschick: João tritt Maria auf den Fuß.',
    grammar: [
      ['pisar em', '`pisar no pé` = auf den Fuß treten. `pisar` verlangt **em** → `em + o = no`.', 'pt.g.contractions'],
      ['Que + Nomen!', '`Que confusão!` = Was für ein Durcheinander!'],
    ],
    idioms: [['Que confusão!', 'Was für ein Chaos!']],
    ambiguity: 'Die Redewendung `pisar na bola` (wörtlich „auf den Ball treten“) heißt „Mist bauen“ – hier aber ganz wörtlich: ein Tritt auf den Fuß.',
    alternatives: [
      ['Ele pisa no pé dela, que vergonha!', 'Er tritt ihr auf den Fuß, wie peinlich!'],
      ['Ele erra o passo.', 'Er macht einen falschen Schritt.'],
    ],
    everyday: '`Desculpa, pisei no seu pé!` – Entschuldige, ich bin dir auf den Fuß getreten! – nützlich beim Tanzen.',
    verbs: [['pisa', 'pisar', 'Presente, 3. Person Singular – regelmäßiges -ar-Verb']],
  },
  {
    src: 'Ela ri e diz: tá tudo{tudo-bem} bem{tudo-bem},',
    natural: 'Sie lacht und sagt: Alles gut,',
    literal: 'Sie lacht und sagt: ist alles gut,',
    phonetic: 'Ä-la HI i DSCHIS: TA TU-du BẼJ',
    difficulty: 2,
    summary: 'Maria nimmt es gelassen – kein Problem!',
    grammar: [
      ['tá = está', '`tá` ist die gesprochene Form von `está`: `tá tudo bem` = alles ist gut.', 'pt.g.estar'],
      ['Unregelmäßig: rir, dizer', '`ri` (von `rir`, lachen) und `diz` (von `dizer`, sagen) sind unregelmäßig.'],
    ],
    colloquial: '`tá` (= `está`) ist extrem häufig im gesprochenen Brasilianisch: `Tá bom!` (Okay!), `Tá certo.` (Stimmt.), `Tá tudo bem.` (Alles gut.)',
    alternatives: [
      ['Ela ri e diz: está tudo bem.', 'Sie lacht und sagt: Alles in Ordnung.', 'Standard'],
      ['Ela ri e diz: não foi nada.', 'Sie lacht und sagt: Nicht schlimm.'],
    ],
    everyday: '`Tá tudo bem` ist die typische Beruhigung: Alles gut, kein Problem.',
    verbs: [
      ['ri', 'rir', 'Presente, 3. Person Singular – unregelmäßig'],
      ['diz', 'dizer', 'Presente, 3. Person Singular – unregelmäßig'],
      ['tá', 'estar', 'Presente, 3. Person Singular – gesprochene Kurzform von „está“'],
    ],
  },
  {
    src: 'No forró, errar faz{faz-parte} parte{faz-parte} também.',
    natural: 'Beim Forró gehören Fehler einfach dazu.',
    literal: 'Im Forró, sich-irren macht Teil auch.',
    phonetic: 'nu fo-HÓ, e-HAH fas PAH-tschi tã-BẼJ',
    difficulty: 3,
    summary: 'Die Moral von der Geschicht’: Fehler gehören dazu – beim Tanzen wie beim Sprachenlernen!',
    grammar: [
      ['Infinitiv als Subjekt', '`errar faz parte` = (das) Fehlermachen gehört dazu. Der Infinitiv kann wie ein Nomen Subjekt sein.'],
      ['rr = h-Laut', '`errar`, `forró`: **rr** klingt in Brasilien wie ein kräftiges deutsches h oder ch („e-HAH“).'],
    ],
    idioms: [['fazer parte', 'dazugehören, Teil von etwas sein']],
    culture: '**Forró** ist ein Paartanz aus dem Nordosten Brasiliens – heute im ganzen Land beliebt, besonders bei den Junifesten.',
    alternatives: [
      ['No forró, todo mundo erra.', 'Beim Forró macht jeder Fehler.'],
      ['Errar é normal.', 'Fehler sind normal.'],
    ],
    everyday: '`Faz parte!` (Gehört dazu!) sagen Brasilianer oft, um jemanden zu trösten – super alltagstauglich.',
    verbs: [
      ['errar', 'errar', 'Infinitiv – als Subjekt'],
      ['faz', 'fazer', 'Presente, 3. Person Singular – in fazer parte'],
    ],
  },
];

const bridge: LineDraft[] = [
  {
    src: 'Quer mais bolo? Quer dançar?',
    natural: 'Noch Kuchen? Willst du tanzen?',
    literal: 'Willst mehr Kuchen? Willst tanzen?',
    phonetic: 'KÄH MAIS BO-lu? KÄH dã-ßAH',
    difficulty: 1,
    summary: 'Gastfreundschaft pur: Essen und Tanzen werden angeboten.',
    grammar: [
      ['Fragen ohne Fragewort', 'Ja/Nein-Fragen erkennt man an der **Stimme**, die Wortstellung bleibt: `Quer dançar?`', 'pt.g.questions'],
      ['querer + Infinitiv', '`Quer dançar?` = Willst du tanzen? Das Subjekt (`você`) fällt oft weg.'],
    ],
    alternatives: [
      ['Você quer mais bolo?', 'Möchtest du noch Kuchen?', 'mit Subjekt'],
      ['Aceita mais um pedaço?', 'Nehmen Sie noch ein Stück?', 'höflich'],
    ],
    everyday: '`Quer mais?` – Willst du noch? – hörst du bei jedem brasilianischen Essen.',
    verbs: [
      ['quer', 'querer', 'Presente, 3. Person Singular (mit você = du willst) – unregelmäßig'],
      ['dançar', 'dançar', 'Infinitiv'],
    ],
  },
  {
    src: 'Tem suco de caju pra tomar!',
    natural: 'Es gibt Cashewsaft zu trinken!',
    literal: 'Hat Saft von Caju zum Nehmen!',
    phonetic: 'tẽj ßU-ku dschi ka-SCHU pra to-MAH',
    difficulty: 2,
    summary: 'Und zu trinken gibt es den typischen Saft aus der Cashewfrucht.',
    grammar: [
      ['ter = es gibt', 'Im gesprochenen Brasilianisch heißt **tem** oft „es gibt“: `tem suco` = es gibt Saft (schriftlich: `há`).'],
      ['pra + Infinitiv', '`pra tomar` = zum Trinken.'],
    ],
    colloquial: '`tem` im Sinn von „es gibt“ und `pra` (= `para`) sind typisch gesprochenes Brasilianisch.',
    culture: 'Der **caju** ist die fleischige Frucht, an der die Cashewnuss hängt. Sein Saft ist besonders im Nordosten Brasiliens beliebt – süß-herb und erfrischend.',
    alternatives: [
      ['Há suco de caju para beber.', 'Es gibt Cashewsaft zu trinken.', 'schriftlich/förmlich'],
      ['Tem suco de caju, quer?', 'Es gibt Cashewsaft, willst du?'],
    ],
    everyday: '`Tem …?` ist DIE Frage im Laden: `Tem pão?` – Gibt es Brot?',
    verbs: [
      ['tem', 'ter', 'Presente, 3. Person Singular – umgangssprachlich „es gibt“'],
      ['tomar', 'tomar', 'Infinitiv – trinken'],
    ],
  },
  {
    src: 'A lua tá cheia, o quintal também,',
    natural: 'Der Mond ist voll, der Hof auch,',
    literal: 'Der Mond ist voll, der Hof auch,',
    phonetic: 'a LU-a TA SCHEJ-a, u kĩ-TAU tã-BẼJ',
    difficulty: 2,
    summary: 'Vollmond am Himmel – und ein Hof voller Gäste.',
    grammar: [
      ['estar cheio/cheia', '`tá cheia` = ist voll. Ein Zustand → **estar** (hier gesprochen `tá`).', 'pt.g.estar'],
      ['Adjektiv angleichen', '`a lua` ist weiblich → `cheia`; der Hof wäre `cheio`.', 'pt.g.articles-gender'],
    ],
    colloquial: '`tá` statt `está` – gesprochenes Brasilianisch.',
    ambiguity: '**Wortspiel mit `cheia`**: `lua cheia` = Vollmond; `o quintal (está) cheio` = der Hof ist voll (mit Leuten). Ein Wort, zwei Bilder.',
    alternatives: [
      ['É lua cheia e o quintal está cheio.', 'Es ist Vollmond, und der Hof ist voll.', 'Standard'],
    ],
    everyday: '`Tá cheio!` (Es ist voll!) sagst du über Busse, Bars und Strände.',
    verbs: [['tá', 'estar', 'Presente, 3. Person Singular – gesprochene Kurzform']],
  },
  {
    src: 'E ninguém quer ir{ir-embora} embora{ir-embora}, ninguém!',
    natural: 'Und keiner will nach Hause – keiner!',
    literal: 'Und niemand will gehen weg, niemand!',
    phonetic: 'i nĩ-GẼJ KÄH IH ẽ-BÓ-ra, nĩ-GẼJ',
    difficulty: 2,
    summary: 'Das Fest ist so schön, dass niemand gehen will.',
    grammar: [
      ['ir embora = weggehen', '`ir embora` = (nach Hause) gehen, aufbrechen. Sehr häufig: `Vou embora!` = Ich gehe jetzt!'],
      ['Verneinung mit ninguém', '`ninguém` (niemand) vor dem Verb reicht als Verneinung – kein `não` nötig.'],
    ],
    idioms: [['ir embora', 'weggehen, nach Hause gehen']],
    alternatives: [
      ['E ninguém quer voltar pra casa.', 'Und keiner will nach Hause.'],
      ['Ninguém quer que a festa acabe.', 'Keiner will, dass das Fest endet.', 'mit Subjuntivo'],
    ],
    everyday: '`Já vai embora?` – Gehst du schon? – hörst du auf jeder Party.',
    verbs: [
      ['quer', 'querer', 'Presente, 3. Person Singular'],
      ['ir', 'ir', 'Infinitiv – in ir embora'],
    ],
  },
];

const glossary = {
  'sábado': gl('sábado', 'Nomen (m)', 'Samstag', 'ßA-ba-du', [['Sábado eu não trabalho.', 'Samstags arbeite ich nicht.']],
    'Alltagswort.', { grammar: 'Wochentage schreibt man klein. „Am Samstag“ = `no sábado` oder einfach `sábado`.' }),
  'é': gl('ser', 'Verb', 'sein', 'ä', [['Hoje é sábado.', 'Heute ist Samstag.']],
    'Eines der wichtigsten Wörter.', { form: '3. Person Singular Presente von `ser`' }),
  dia: gl('dia', 'Nomen (m)', 'Tag', 'DSCHI-a', [['dia de festa', 'Festtag']],
    'Alltagswort.', { grammar: 'Trotz -a männlich: `o dia`.' }),
  festa: gl('festa', 'Nomen (f)', 'Fest, Party', 'FÄS-ta', [['Vai ter festa hoje?', 'Gibt es heute eine Party?']],
    'Alltagswort. `Festa junina` = Junifest.'),
  quintal: gl('quintal', 'Nomen (m)', 'Hinterhof, Garten hinterm Haus', 'kĩ-TAU', [['As crianças brincam no quintal.', 'Die Kinder spielen im Hof.']],
    'Alltagswort in Brasilien.', { grammar: 'Plural `quintais`.', ipa: 'kĩˈtaw' }),
  'vem.imp': gl('vir', 'Verb', 'komm! (Befehlsform)', 'wẽj', [['Vem cá!', 'Komm her!']],
    'Im Alltag die übliche Befehlsform, auch wenn man `você` sagt.',
    { form: 'Befehlsform 2. Person Singular (tu) von `vir`', register: 'umgangssprachlich', colloquial: 'Schriftlich/höflich mit `você`: `Venha!`' }),
  'a-gente': gl('a gente', 'Pronomen (umgangssprachlich)', 'wir; uns', 'a SCHẼN-tschi', [['Vem com a gente!', 'Komm mit uns!']],
    'Im gesprochenen Brasilianisch die normale Form für „wir/uns“.',
    { literal: 'die Leute', register: 'umgangssprachlich', grammar: 'Als Subjekt mit Verb in der 3. Person Singular: `a gente vai`.', colloquial: 'Im Gespräch häufiger als `nós`.' }),
  traz: gl('trazer', 'Verb', 'bring! (Befehlsform)', 'tras', [['Traz uma cadeira!', 'Bring einen Stuhl mit!']],
    'Im Alltag sehr häufig.', { form: 'Befehlsform 2. Person Singular (tu) von `trazer`', register: 'umgangssprachlich', colloquial: 'Schriftlich/höflich: `Traga!`' }),
  pessoal: gl('pessoal', 'Nomen (m, Sammelwort)', 'die Leute, die Clique; Leute! (Anrede)', 'pe-ßo-AU', [['Oi, pessoal!', 'Hallo, Leute!']],
    'Unter Freunden ständig.', { register: 'umgangssprachlich', colloquial: 'Als Anrede für eine Gruppe: `Pessoal, …` = „Leute, …“. Als Adjektiv heißt `pessoal` „persönlich“.' }),
  milho: gl('milho', 'Nomen (m)', 'Mais', 'MI-lju', [['Milho verde é típico em junho.', 'Frischer Mais ist typisch im Juni.']],
    'Alltagswort.', { grammar: '`lh` klingt wie „lj“.', ipa: 'ˈmiʎu' }),
  bolo: gl('bolo', 'Nomen (m)', 'Kuchen', 'BO-lu', [['bolo de chocolate', 'Schokoladenkuchen']],
    'Alltagswort.'),
  'pe-de-moleque': gl('pé de moleque', 'Nomen (m)', 'Erdnusskrokant (Süßigkeit)', 'PÄ dschi mo-LÄ-ki', [['Adoro pé de moleque!', 'Ich liebe Erdnusskrokant!']],
    'Typische Süßigkeit, besonders bei den Junifesten.', { literal: 'Fuß eines Gassenjungen', grammar: 'Seit der Rechtschreibreform ohne Bindestriche geschrieben.' }),
  'pinhão': gl('pinhão', 'Nomen (m)', 'Araukariensamen („Pinienkern“ der Araukarie)', 'pi-NJÃU', [['No inverno a gente come pinhão.', 'Im Winter essen wir Pinhão.']],
    'Im Süden und Südosten Brasiliens bekannt.', { grammar: 'Plural `pinhões`.', ipa: 'piˈɲɐ̃w̃' }),
  sanfona: gl('sanfona', 'Nomen (f)', 'Akkordeon (Brasilien)', 'ßã-FO-na', [['Ele toca sanfona.', 'Er spielt Akkordeon.']],
    'Im Nordosten das Wort für Akkordeon; auch `acordeão`.'),
  'vovô': gl('vovô', 'Nomen (m)', 'Opa', 'wo-WO', [['O vovô conta histórias.', 'Opa erzählt Geschichten.']],
    'Liebevolles Familienwort.', { grammar: 'Oma = `vovó` (offenes ó!). Neutral: `avô`/`avó`.' }),
  'que.excl': gl('que', 'Ausrufewort', 'was für ein!, wie!', 'ki', [['Que calor!', 'Was für eine Hitze!']],
    'Ständig.', { grammar: 'Ausruf: `Que + Nomen/Adjektiv!` – `Que legal!` (Wie cool!).' }),
  'emoção': gl('emoção', 'Nomen (f)', 'Rührung, Aufregung, Gefühl', 'e-mo-ßÃU', [['Que emoção!', 'Wie bewegend!']],
    'Häufig.', { grammar: 'Plural `emoções`.' }),
  bora: gl('bora', 'Interjektion', 'los!, lass(t) uns …!', 'BÓ-ra', [['Bora pra praia!', 'Ab an den Strand!']],
    'Unter Freunden ständig.', { form: 'Kurzform von `vamos embora`', register: 'umgangssprachlich', colloquial: 'Sehr locker – nicht im Büro-Mail, aber überall im Gespräch.' }),
  'dançar': gl('dançar', 'Verb', 'tanzen', 'dã-ßAH', [['Você sabe dançar forró?', 'Kannst du Forró tanzen?']],
    'Alltagswort.'),
  'cê': gl('você', 'Personalpronomen (umgangssprachlich)', 'du', 'ße', [['Cê tá bem?', 'Geht’s dir gut?']],
    'Im gesprochenen Brasilianisch sehr häufig.', { form: 'gesprochene Kurzform von `você`', register: 'umgangssprachlich', colloquial: 'Nur im Gespräch oder Chat – schriftlich immer `você`.' }),
  vem: gl('vir', 'Verb', 'kommen', 'wẽj', [['Você vem amanhã?', 'Kommst du morgen?']],
    'Sehr häufig.', { form: '3. Person Singular Presente von `vir` (auch mit `você`/`cê`)' }),
  'também': gl('também', 'Adverb', 'auch', 'tã-BẼJ', [['Eu também!', 'Ich auch!']],
    'Ständig.', { ipa: 'tɐ̃ˈbẽj' }),
  vai: gl('ir', 'Verb', 'gehen; (vai + Infinitiv) wird', 'wai', [['Vai chover.', 'Es wird regnen.']],
    'Ständig.', { form: '3. Person Singular Presente von `ir`' }),
  ser: gl('ser', 'Verb', 'sein', 'ßeh', [['Vai ser ótimo!', 'Das wird toll!']],
    'Sehr häufig.', { form: 'Infinitiv' }),
  legal: gl('legal', 'Adjektiv', 'cool, toll, nett', 'le-GAU', [['Que legal!', 'Wie cool!']],
    'DAS Alltagswort für „cool“ in Brasilien.', { register: 'umgangssprachlich', colloquial: 'Achtung: `legal` heißt in Brasilien meist „cool“, nicht nur „gesetzlich“.' }),
  passo: gl('passo', 'Nomen (m)', 'Schritt', 'PA-ßu', [['passo a passo', 'Schritt für Schritt']],
    'Alltagswort.'),
  'à': gl('à', 'Präposition + Artikel', 'an die, zur, nach (a + a)', 'a', [['Vou à praia.', 'Ich gehe an den Strand.']],
    'Häufig, vor allem geschrieben; gesprochen oft `pra`.', { form: 'Verschmelzung von `a` + `a`', grammar: 'Der Gravis-Akzent zeigt die Verschmelzung an: `à frente` (nach vorn).' }),
  frente: gl('frente', 'Nomen (f)', 'Vorderseite; (à frente) vorn, nach vorn', 'FRẼN-tschi', [['Siga em frente.', 'Gehen Sie geradeaus.']],
    'Häufig in Wegbeschreibungen.'),
  'atrás': gl('atrás', 'Adverb', 'hinten, zurück', 'a-TRAS', [['Fica atrás da porta.', 'Es ist hinter der Tür.']],
    'Häufig.'),
  essa: gl('esse', 'Demonstrativbegleiter', 'diese(r/s)', 'Ä-ßa', [['essa noite', 'heute Nacht']],
    'Im brasilianischen Alltag häufiger als `esta`.', { form: 'weibliche Form von `esse`' }),
  noite: gl('noite', 'Nomen (f)', 'Nacht; Abend', 'NOI-tschi', [['Boa noite!', 'Guten Abend! / Gute Nacht!']],
    'Alltagswort.'),
  'ninguém': gl('ninguém', 'Pronomen', 'niemand', 'nĩ-GẼJ', [['Ninguém sabe.', 'Niemand weiß es.']],
    'Häufig.', { grammar: 'Vor dem Verb reicht `ninguém` als Verneinung; nach dem Verb: `Não vi ninguém.`' }),
  parar: gl('parar', 'Verb', 'aufhören; anhalten', 'pa-RAH', [['Para aqui, por favor.', 'Halt bitte hier an.']],
    'Alltagswort.'),
  olha: gl('olhar', 'Verb', 'schau!, sieh mal!', 'Ó-lja', [['Olha só!', 'Schau mal!']],
    'Ständig – auch als Füllwort („also …“).', { form: 'Befehlsform (umgangssprachlich) von `olhar`' }),
  maria: gl('Maria', 'Eigenname (f)', 'Maria (Vorname)', 'ma-RI-a', [['A Maria é minha prima.', 'Maria ist meine Cousine.']],
    'Einer der häufigsten Vornamen Brasiliens.'),
  'dançando': gl('dançar', 'Verb', 'tanzen', 'dã-ßÃN-du', [['Estou dançando.', 'Ich tanze gerade.']],
    'Häufig.', { form: 'Gerundium von `dançar`' }),
  'joão': gl('João', 'Eigenname (m)', 'João (Vorname, = Johannes)', 'schu-ÃU', [['O João toca zabumba.', 'João spielt Zabumba.']],
    'Sehr häufiger Vorname.', { ipa: 'ʒuˈɐ̃w̃' }),
  ele: gl('ele', 'Personalpronomen', 'er', 'E-li', [['Ele é legal.', 'Er ist nett.']],
    'Ständig.', { grammar: 'Mit geschlossenem e; `dele` = sein (von ihm).' }),
  pisa: gl('pisar', 'Verb', 'treten (auf)', 'PI-sa', [['Não pisa na grama!', 'Tritt nicht auf den Rasen!']],
    'Alltagswort.', { form: '3. Person Singular Presente von `pisar`', grammar: 'Mit `em`: `pisar no pé`.' }),
  'pé': gl('pé', 'Nomen (m)', 'Fuß', 'pä', [['Meu pé dói.', 'Mir tut der Fuß weh.']],
    'Alltagswort.', { grammar: 'Offenes é („ä“). `a pé` = zu Fuß.' }),
  'confusão': gl('confusão', 'Nomen (f)', 'Durcheinander, Chaos; Ärger', 'kõ-fu-SÃU', [['Que confusão!', 'Was für ein Chaos!']],
    'Häufig.', { grammar: 'Plural `confusões`.' }),
  ela: gl('ela', 'Personalpronomen', 'sie (Singular)', 'Ä-la', [['Ela dança bem.', 'Sie tanzt gut.']],
    'Ständig.', { grammar: 'Mit offenem e („ä“); `dela` = ihr (von ihr).' }),
  ri: gl('rir', 'Verb', 'lachen', 'hi', [['Ela ri muito.', 'Sie lacht viel.']],
    'Alltagswort.', { form: '3. Person Singular Presente von `rir`' }),
  diz: gl('dizer', 'Verb', 'sagen', 'dschis', [['O que ele diz?', 'Was sagt er?']],
    'Sehr häufig.', { form: '3. Person Singular Presente von `dizer`' }),
  'tá': gl('estar', 'Verb (umgangssprachlich)', 'ist (Zustand, Ort)', 'ta', [['Tá bom!', 'Okay!'], ['Tá frio hoje.', 'Heute ist es kalt.']],
    'Im Gespräch fast immer statt `está`.', { form: 'gesprochene Kurzform von `está`', register: 'umgangssprachlich', colloquial: 'Absolut normal im gesprochenen Brasilianisch; schriftlich `está`.' }),
  'tudo-bem': gl('tudo bem', 'Wendung', 'alles gut; in Ordnung', 'TU-du BẼJ', [['Tá tudo bem.', 'Alles ist gut.']],
    'Sehr häufig.', { literal: 'alles gut' }),
  'forró': gl('forró', 'Nomen (m)', 'Forró (Musik- und Paartanz aus dem Nordosten)', 'fo-HÓ', [['Vamos dançar forró?', 'Tanzen wir Forró?']],
    'In Brasilien jedem bekannt.', { ipa: 'foˈhɔ' }),
  errar: gl('errar', 'Verb', 'sich irren, einen Fehler machen', 'e-HAH', [['Errar é humano.', 'Irren ist menschlich.']],
    'Häufig.', { grammar: '`rr` klingt wie ein kräftiges h.' }),
  'faz-parte': gl('fazer parte', 'Wendung', 'dazugehören', 'fas PAH-tschi', [['Faz parte!', 'Gehört dazu!']],
    'Sehr häufig – auch als Trost.', { form: '`faz` = 3. Person Singular Presente von `fazer`', literal: 'macht Teil' }),
  quer: gl('querer', 'Verb', 'wollen, möchten', 'käh', [['Quer um café?', 'Möchtest du einen Kaffee?']],
    'Sehr häufig.', { form: '3. Person Singular Presente von `querer` (auch mit `você`)' }),
  mais: gl('mais', 'Adverb', 'mehr, noch', 'mais', [['Mais um pouco?', 'Noch ein bisschen?']],
    'Ständig.'),
  tem: gl('ter', 'Verb', 'haben; (umgangssprachlich) es gibt', 'tẽj', [['Tem pão?', 'Gibt es Brot?']],
    'Ständig.', { form: '3. Person Singular Presente von `ter`', register: 'umgangssprachlich', colloquial: 'Als „es gibt“ typisch gesprochen; schriftlich `há`.' }),
  suco: gl('suco', 'Nomen (m)', 'Saft', 'ßU-ku', [['Um suco de laranja, por favor.', 'Einen Orangensaft, bitte.']],
    'Alltagswort (in Portugal: `sumo`).'),
  caju: gl('caju', 'Nomen (m)', 'Cashewfrucht', 'ka-SCHU', [['Suco de caju é delicioso.', 'Cashewsaft ist köstlich.']],
    'In Brasilien bekannt, besonders im Nordosten.', { grammar: 'Die Nuss heißt `castanha de caju`.' }),
  tomar: gl('tomar', 'Verb', 'nehmen; trinken', 'to-MAH', [['Vamos tomar um suco?', 'Trinken wir einen Saft?']],
    'Sehr häufig.'),
  lua: gl('lua', 'Nomen (f)', 'Mond', 'LU-a', [['Hoje tem lua cheia.', 'Heute ist Vollmond.']],
    'Alltagswort.', { grammar: 'weiblich: `a lua` – im Deutschen „der Mond“.' }),
  cheia: gl('cheio', 'Adjektiv', 'voll', 'SCHEJ-a', [['lua cheia', 'Vollmond'], ['O ônibus está cheio.', 'Der Bus ist voll.']],
    'Alltagswort.', { form: 'weibliche Form von `cheio`' }),
  'ir-embora': gl('ir embora', 'Wendung', 'weggehen, nach Hause gehen', 'IH ẽ-BÓ-ra', [['Já vou embora.', 'Ich gehe jetzt.']],
    'Sehr häufig.'),
};

const song: Song = buildSong({
  id: 'song.pt.festa-no-quintal',
  courseId: 'pt-BR',
  variant: 'pt-BR',
  title: 'Festa no quintal',
  artist: 'Trio Calçada',
  cover: { from: '#F12711', to: '#F5AF19', emoji: '🌽' },
  genre: 'Forró',
  level: 'A2',
  speed: 'mittel',
  themes: ['Fest', 'Tanz', 'Familie', 'Essen'],
  grammarTags: ['pt.g.contractions', 'pt.g.pronouns', 'pt.g.estar', 'pt.g.questions', 'pt.g.present-regular'],
  backing: { bpm: 116, style: 'samba', key: 'G', chords: ['G', 'C', 'D7', 'G', 'G', 'Em', 'Am', 'D7'] },
  sections: [
    { id: 'v1', label: 'Strophe 1', lines: verse1 },
    { id: 'c1', label: 'Refrain', lines: chorus },
    { id: 'v2', label: 'Strophe 2', lines: verse2 },
    { id: 'c2', label: 'Refrain', lines: chorus },
    { id: 'br', label: 'Bridge', lines: bridge },
    { id: 'c3', label: 'Refrain', lines: chorus },
  ],
  glossary,
  common: COMMON_PT,
});

export default song;
