/** „Noches de Madrid“ – Originales Lernlied (Flamenco-Pop, es-ES, B1). Lautschrift: „th“ = gelispeltes s wie engl. „think“. */
import type { Song } from '../types';
import { COMMON_ES } from './_common-es';
import { buildSong, gl, type LineDraft } from './_layout';

const verse1: LineDraft[] = [
  {
    src: 'Me ducho, me visto y me peino deprisa,',
    natural: 'Ich dusche, zieh mich an und kämme mich schnell,',
    literal: 'Mich dusche-ich, mich kleide-ich und mich kämme-ich eilig,',
    phonetic: 'me DU-tscho, me BIS-to i me PEJ-no de-PRI-ßa',
    ipa: 'me ˈðutʃo | me ˈβisto i me ˈpei̯no ðeˈpɾisa',
    difficulty: 2,
    summary: 'Die Vorbereitung auf den Abend im Schnelldurchlauf: duschen, anziehen, kämmen.',
    grammar: [
      ['Reflexive Verben', '`ducharse`, `vestirse`, `peinarse` sind **reflexiv**: Das Pronomen `me` zeigt, dass man es an sich selbst tut. Es steht vor dem konjugierten Verb.', 'es.g.reflexive'],
      ['vestirse: e → i', '`vestir` wechselt im Stamm: `me visto`, `te vistes`, `se viste` – aber `nos vestimos`.'],
    ],
    alternatives: [
      ['Me arreglo deprisa.', 'Ich mache mich schnell fertig.', 'arreglarse = sich zurechtmachen'],
      ['Me ducho y me visto rápido.', 'Ich dusche und ziehe mich schnell an.'],
    ],
    everyday: 'Genau so beschreibt man die eigene Routine. `deprisa` ist in Spanien üblich; überall verstanden wird `rápido`.',
    verbs: [
      ['ducho', 'ducharse', 'Präsens, 1. Person Singular – reflexiv (me ducho)'],
      ['visto', 'vestirse', 'Präsens, 1. Person Singular – reflexiv, Stammwechsel e → i'],
      ['peino', 'peinarse', 'Präsens, 1. Person Singular – reflexiv'],
    ],
  },
  {
    src: 'Me pongo la chaqueta y mi mejor sonrisa.',
    natural: 'Ich zieh die Jacke an und setz mein schönstes Lächeln auf.',
    literal: 'Mir setze-ich die Jacke und mein bestes Lächeln.',
    phonetic: 'me PON-go la tscha-KE-ta i mi me-CHOR ßon-RRI-ßa',
    difficulty: 2,
    summary: 'Jacke an, Lächeln an – gute Laune gehört zum Outfit.',
    grammar: [
      ['ponerse = anziehen', '`ponerse` + Kleidung = etwas anziehen. Spanisch sagt `la chaqueta` (nicht „meine“): Das `me` zeigt schon, wem sie gehört.', 'es.g.reflexive'],
      ['yo-Form auf -go', '`poner` → `pongo` (unregelmäßige yo-Form, wie `tengo`, `salgo`).'],
    ],
    ambiguity: '**Wortspiel**: `ponerse` passt zur Jacke UND zum Lächeln. Deutsch zieht eine Jacke „an“, setzt ein Lächeln aber „auf“ – Spanisch braucht für beides nur ein Verb.',
    alternatives: [
      ['Me pongo la chaqueta y sonrío.', 'Ich ziehe die Jacke an und lächle.'],
      ['Me pongo el abrigo.', 'Ich ziehe den Mantel an.'],
    ],
    everyday: '`Me pongo …` für Kleidung ist absolut alltäglich: `Me pongo los zapatos.`',
    verbs: [['pongo', 'ponerse', 'Präsens, 1. Person Singular – unregelmäßig (-go), reflexiv']],
  },
  {
    src: 'Me llama Lucía: tía, ¿dónde estás?',
    natural: 'Lucía ruft an: „Hey, wo bleibst du?“',
    literal: 'Mich ruft Lucía: Tante, wo bist-du?',
    phonetic: 'me JA-ma lu-THI-a: TI-a, DON-de es-TAS',
    difficulty: 2,
    summary: 'Die Freundin Lucía wartet schon und ruft an.',
    grammar: [
      ['llamar = anrufen', '`me llama` = sie ruft **mich** an. `llamar` = rufen/anrufen; `llamarse` = heißen.', 'es.g.pronouns'],
      ['estar für den Ort', '`¿Dónde estás?` – der Aufenthaltsort → **estar**.', 'es.g.estar'],
    ],
    colloquial: '`tía` heißt eigentlich „Tante“. In **Spanien** reden sich Freundinnen und Freunde locker mit `tía`/`tío` an – ungefähr wie „hey, du“ oder „Alte/Alter“ unter Freunden. Nicht gegenüber Fremden oder im Job!',
    ambiguity: 'Nicht verwechseln: `Me llama Lucía` = Lucía ruft mich an; `Me llamo Lucía` = Ich heiße Lucía. Und `tía` ist hier keine Tante, sondern eine lockere Anrede.',
    alternatives: [
      ['Me llama Lucía: oye, ¿dónde estás?', 'Lucía ruft an: Hör mal, wo bist du?', 'neutraler'],
      ['Lucía me llama y me pregunta dónde estoy.', 'Lucía ruft mich an und fragt, wo ich bin.', 'indirekte Rede'],
    ],
    everyday: '`¿Dónde estás?` brauchst du täglich. `tía/tío` als Anrede nur unter Freunden in Spanien – in Lateinamerika klingt es fremd.',
    verbs: [
      ['llama', 'llamar', 'Präsens, 3. Person Singular'],
      ['estás', 'estar', 'Präsens, 2. Person Singular (tú)'],
    ],
  },
  {
    src: 'Tranqui, que{que.causal} llego en diez minutos, nada{nada-más} más{nada-más}.',
    natural: 'Keine Panik, ich bin in zehn Minuten da – höchstens.',
    literal: 'Ruhig, denn komme-an-ich in zehn Minuten, nichts mehr.',
    phonetic: 'TRAN-ki, ke JE-go en DJETH mi-NU-tos, NA-da MAS',
    difficulty: 2,
    summary: 'Die Antwort an Lucía: Entspann dich, ich bin gleich da.',
    grammar: [
      ['Präsens für die nahe Zukunft', '`llego en diez minutos` – Spanisch nutzt oft das **Präsens** für gleich Kommendes, wie deutsch „ich komme gleich“.', 'es.g.present-regular'],
      ['que am Satzanfang', '`…, que llego …` – dieses `que` begründet: „…, denn ich komme …“.'],
    ],
    colloquial: '`tranqui` ist die Kurzform von `tranquilo/tranquila` („ruhig“) – sehr locker, typisch Spanien. Das begründende `que` ist typisch gesprochene Sprache.',
    idioms: [['nada más', 'nicht mehr; nur', 'hier: „nur zehn Minuten, nicht länger“']],
    alternatives: [
      ['Tranquila, llego en diez minutos.', 'Keine Sorge, ich bin in zehn Minuten da.', 'neutral'],
      ['No te preocupes, ya voy.', 'Keine Sorge, ich komme schon.'],
    ],
    everyday: '`Tranqui` hörst du in Spanien ständig unter Freunden. `Llego en diez minutos` ist der Klassiker beim Zuspätkommen.',
    verbs: [['llego', 'llegar', 'Präsens, 1. Person Singular – für die nahe Zukunft']],
  },
];

const chorus: LineDraft[] = [
  {
    src: '¿Qué vais a hacer esta noche? ¿Os venís?',
    natural: 'Was habt ihr heute Abend vor? Kommt ihr mit?',
    literal: 'Was geht-ihr zu machen diese Nacht? Euch kommt-ihr?',
    phonetic: 'ke BAIS a a-THER ES-ta NO-tsche? os be-NIS',
    ipa: 'ˈke ˈβai̯s a aˈθeɾ ˈesta ˈnotʃe | os βeˈnis',
    difficulty: 3,
    summary: 'Die Einladung an die Clique: Was habt ihr vor? Kommt ihr mit?',
    grammar: [
      ['vosotros – „ihr“ in Spanien', '`vais`, `venís` sind **vosotros**-Formen: die lockere Anrede für mehrere Personen – typisch für Spanien. In Lateinamerika: `ustedes van`, `¿se vienen?`.', 'es.g.pronouns'],
      ['ir a + Infinitiv', '`¿Qué vais a hacer?` = Was habt ihr vor? **ir a + Infinitiv** drückt Pläne und nahe Zukunft aus.', 'es.g.ir-a'],
      ['venirse = mitkommen', '`¿Os venís?` = Kommt ihr mit? Das reflexive `venirse` betont „sich anschließen“.', 'es.g.reflexive'],
    ],
    alternatives: [
      ['¿Qué hacéis esta noche? ¿Venís?', 'Was macht ihr heute Abend? Kommt ihr?'],
      ['¿Qué van a hacer esta noche? ¿Se vienen?', 'Was habt ihr heute Abend vor? Kommt ihr mit?', 'Lateinamerika (ustedes)'],
    ],
    everyday: 'Klassische Einladung unter Freunden in Spanien. Für eine Person: `¿Te vienes?` (Kommst du mit?).',
    verbs: [
      ['vais', 'ir', 'Präsens, 2. Person Plural (vosotros) – unregelmäßig'],
      ['hacer', 'hacer', 'Infinitiv nach ir a'],
      ['venís', 'venirse', 'Präsens, 2. Person Plural (vosotros) – reflexiv: mitkommen'],
    ],
  },
  {
    src: 'Quedamos en Sol{sol.plaza}, ¿vale? ¡Decid que{que.conj} sí!',
    natural: 'Wir treffen uns an der Puerta del Sol, okay? Sagt ja!',
    literal: 'Verabreden-wir in Sol, gilt-es? Sagt dass ja!',
    phonetic: 'ke-DA-mos en ßOL, BA-le? de-THID ke ßI',
    difficulty: 3,
    summary: 'Treffpunkt: die Puerta del Sol im Zentrum Madrids. Jetzt fehlt nur noch das Ja der Freunde.',
    grammar: [
      ['quedar = sich verabreden', '`quedamos en …` = wir treffen uns in/an … – **quedar** heißt hier „sich verabreden“. Das Präsens steht für feste Pläne.', 'es.g.present-regular'],
      ['Imperativ vosotros', '`decid` = sagt! Die vosotros-Befehlsform: Infinitiv, **-r** wird zu **-d**: `decir` → `decid`, `venir` → `venid`.', 'es.g.pronouns'],
      ['decir que sí', '`decir que sí/no` = ja/nein sagen.'],
    ],
    colloquial: '`¿vale?` ist **typisch Spanien**: „okay?“, „einverstanden?“. `quedar` für Verabredungen ist spanische Alltagssprache: `¿Quedamos?` = Treffen wir uns?',
    culture: '**Sol** ist die Kurzform für die **Puerta del Sol**, den zentralen Platz Madrids – mit der berühmten Uhr, unter der Spanien Silvester feiert, und dem „Kilometer 0“ der spanischen Straßen. `Quedamos en Sol` sagen Madrileños ständig.',
    ambiguity: '**Doppeldeutig**: `Sol` ist der Platz, `el sol` die Sonne. Im Refrain treffen sich beide: Man trifft sich an der „Sol“ und tanzt, bis die Sonne aufgeht.',
    alternatives: [
      ['Nos vemos en Sol, ¿de acuerdo?', 'Wir sehen uns an der Sol, einverstanden?', 'neutral'],
      ['¿Quedamos en Sol a las once?', 'Treffen wir uns um elf an der Sol?'],
    ],
    everyday: '`Quedamos a las … en …, ¿vale?` ist DIE Formel für Verabredungen in Spanien.',
    verbs: [
      ['quedamos', 'quedar', 'Präsens, 1. Person Plural – sich verabreden'],
      ['decid', 'decir', 'Imperativ, 2. Person Plural (vosotros)'],
    ],
  },
  {
    src: 'Vamos a bailar hasta ver salir el sol,',
    natural: 'Wir tanzen, bis wir die Sonne aufgehen sehen,',
    literal: 'Gehen-wir zu tanzen bis sehen herauskommen die Sonne,',
    phonetic: 'BA-mos a bai-LAR AS-ta BER ßa-LIR el ßOL',
    ipa: 'ˈbamos a βai̯ˈlaɾ ˈasta ˈβeɾ saˈliɾ el ˈsol',
    difficulty: 3,
    summary: 'Das Versprechen der Nacht: tanzen bis zum Sonnenaufgang.',
    grammar: [
      ['ir a + Infinitiv', '`vamos a bailar` = wir werden tanzen / lasst uns tanzen. `vamos a …` ist Plan und Aufforderung zugleich.', 'es.g.ir-a'],
      ['hasta + Infinitiv', '`hasta ver` = bis (wir) sehen. Ist das Subjekt dasselbe, folgt auf **hasta** einfach der Infinitiv.'],
      ['ver + Infinitiv', '`ver salir el sol` = die Sonne aufgehen sehen. Nach Wahrnehmungsverben (`ver`, `oír`) steht der Infinitiv – wie im Deutschen „aufgehen sehen“.'],
    ],
    ambiguity: '`vamos a bailar` kann „wir werden tanzen“ oder „lasst uns tanzen!“ heißen. Und `el sol` spielt mit „Sol“ aus der Zeile davor.',
    alternatives: [
      ['Bailamos hasta el amanecer.', 'Wir tanzen bis zum Morgengrauen.'],
      ['Vamos a bailar toda la noche.', 'Wir tanzen die ganze Nacht.'],
    ],
    everyday: '`Vamos a + Infinitiv` ist extrem häufig: `Vamos a comer.` (Lass uns essen.)',
    verbs: [
      ['vamos', 'ir', 'Präsens, 1. Person Plural – ir a + Infinitiv'],
      ['bailar', 'bailar', 'Infinitiv'],
      ['ver', 'ver', 'Infinitiv nach hasta'],
      ['salir', 'salir', 'Infinitiv nach ver (Wahrnehmungsverb)'],
    ],
  },
  {
    src: 'Noches de Madrid, noches de calor.',
    natural: 'Madrider Nächte, heiße Nächte.',
    literal: 'Nächte von Madrid, Nächte von Hitze.',
    phonetic: 'NO-tsches de ma-DRID, NO-tsches de ka-LOR',
    difficulty: 1,
    summary: 'Der Titel als Refrain-Hook: die warmen Sommernächte in Madrid.',
    grammar: [
      ['Nomen + de + Nomen', '`noches de calor` = heiße Nächte (wörtlich „Nächte der Hitze“). Spanisch verbindet mit **de**, wo Deutsch ein Adjektiv oder ein zusammengesetztes Wort nimmt.', 'es.g.gender-plural'],
    ],
    culture: 'Im Madrider Sommer wird es erst spät kühler – das Leben spielt sich draußen ab, Abendessen um 22 Uhr ist normal, und viele gehen erst nach Mitternacht richtig aus.',
    alternatives: [
      ['Noches calurosas en Madrid.', 'Heiße Nächte in Madrid.'],
      ['Las noches de verano en Madrid.', 'Die Sommernächte in Madrid.'],
    ],
    everyday: '`noches de verano` (Sommernächte), `día de fiesta` (Feiertag) – das Muster **Nomen + de + Nomen** ist überall.',
  },
];

const verse2: LineDraft[] = [
  {
    src: 'Bajamos por la Gran{gran-via} Vía{gran-via} cantando,',
    natural: 'Wir ziehen singend die Gran Vía hinunter,',
    literal: 'Gehen-hinunter-wir durch die Große Straße singend,',
    phonetic: 'ba-CHA-mos por la gran BI-a kan-TAN-do',
    difficulty: 2,
    summary: 'Die Clique zieht singend über die berühmteste Straße Madrids.',
    grammar: [
      ['Gerundium', '`cantando` = singend. Das **Gerundium** (-ando/-iendo) beschreibt, wie man etwas tut.'],
      ['por = entlang', '`bajar por la calle` = die Straße hinuntergehen. **por** zeigt den Weg.'],
    ],
    culture: 'Die **Gran Vía** ist Madrids Prachtstraße mit Theatern, Kinos und Leuchtreklamen – nachts voller Menschen.',
    alternatives: [
      ['Vamos por la Gran Vía cantando.', 'Wir ziehen singend die Gran Vía entlang.'],
      ['Bajamos cantando por la Gran Vía.', 'gleiche Bedeutung, andere Wortstellung'],
    ],
    everyday: '`bajar/subir por la calle` benutzt man für Wege in der Stadt ständig.',
    verbs: [
      ['bajamos', 'bajar', 'Präsens, 1. Person Plural'],
      ['cantando', 'cantar', 'Gerundium'],
    ],
  },
  {
    src: 'La gente se ríe, la ciudad está brillando.',
    natural: 'Die Leute lachen, die Stadt leuchtet.',
    literal: 'Die Leute sich lacht, die Stadt ist leuchtend.',
    phonetic: 'la CHEN-te ße RRI-e, la thju-DAD es-TA bri-JAN-do',
    difficulty: 2,
    summary: 'Überall gute Laune: Die Menschen lachen, die Lichter der Stadt strahlen.',
    grammar: [
      ['la gente + Singular', '`la gente` (die Leute) ist grammatisch **Singular**: `la gente se ríe` (nicht `se ríen`).', 'es.g.gender-plural'],
      ['reírse', '`reírse` = lachen – meist reflexiv: `me río`, `se ríe`.', 'es.g.reflexive'],
      ['estar + Gerundium', '`está brillando` = leuchtet gerade – Verlaufsform mit **estar**.', 'es.g.estar'],
    ],
    alternatives: [
      ['La gente ríe y la ciudad brilla.', 'Die Leute lachen und die Stadt strahlt.'],
      ['Todo el mundo se ríe.', 'Alle lachen.'],
    ],
    everyday: '`la gente` + Verb im Plural ist ein typischer Fehler Deutschsprachiger – hier siehst du es richtig.',
    verbs: [
      ['ríe', 'reírse', 'Präsens, 3. Person Singular – reflexiv (se ríe)'],
      ['está', 'estar', 'Präsens, 3. Person Singular – Hilfsverb der Verlaufsform'],
      ['brillando', 'brillar', 'Gerundium'],
    ],
  },
  {
    src: 'Un tío con guitarra se pone a tocar,',
    natural: 'Ein Typ mit Gitarre fängt an zu spielen,',
    literal: 'Ein Onkel mit Gitarre sich setzt zu spielen,',
    phonetic: 'un TI-o kon gi-TA-rra ße PO-ne a to-KAR',
    difficulty: 3,
    summary: 'Ein Straßenmusiker packt die Gitarre aus – die Party beginnt auf der Straße.',
    grammar: [
      ['ponerse a + Infinitiv', '`se pone a tocar` = er fängt an zu spielen. **ponerse a** + Infinitiv = (plötzlich) mit etwas anfangen.', 'es.g.reflexive'],
      ['tocar = spielen (Instrument)', 'Ein Instrument spielt man mit **tocar** – `jugar` ist für Spiele und Sport.'],
    ],
    colloquial: '`un tío` heißt in **Spanien** umgangssprachlich „ein Typ“; `una tía` = „eine Frau“ (locker). Wörtlich: Onkel/Tante.',
    ambiguity: '`tío` = „Onkel“ oder „Typ“ – der Zusammenhang entscheidet. Hier ist ganz sicher kein Onkel gemeint.',
    culture: 'Flamenco-Gitarre und spontane `rumba` auf der Straße: In Madrid gehören Straßenmusiker zum Nachtleben.',
    alternatives: [
      ['Un chico con guitarra empieza a tocar.', 'Ein junger Mann mit Gitarre beginnt zu spielen.', 'neutral'],
      ['Un músico se pone a tocar.', 'Ein Musiker fängt an zu spielen.'],
    ],
    everyday: '`ponerse a` ist sehr häufig: `Se puso a llover.` (Es fing an zu regnen.)',
    verbs: [
      ['pone', 'ponerse', 'Präsens, 3. Person Singular – in ponerse a + Infinitiv'],
      ['tocar', 'tocar', 'Infinitiv – ein Instrument spielen'],
    ],
  },
  {
    src: '¡Qué{qué.excl} guay! Nos ponemos todos a bailar.',
    natural: 'Wie cool! Wir fangen alle an zu tanzen.',
    literal: 'Wie toll! Uns setzen-wir alle zu tanzen.',
    phonetic: 'ke GUAI! nos po-NE-mos TO-dos a bai-LAR',
    difficulty: 2,
    summary: 'Begeisterung: Alle machen mit und tanzen.',
    grammar: [
      ['¡Qué + Adjektiv!', '`¡Qué guay!` = Wie cool! Ausrufe mit **qué** + Adjektiv oder Nomen: `¡Qué bonito!`, `¡Qué calor!`'],
      ['ponerse a + Infinitiv', '`nos ponemos a bailar` = wir fangen an zu tanzen.', 'es.g.reflexive'],
    ],
    colloquial: '`guay` ist **typisch Spanien** für „cool, toll“. In Mexiko sagt man `padre` oder `chido`, in Kolumbien `bacano`.',
    alternatives: [
      ['¡Qué bien! Todos empezamos a bailar.', 'Wie schön! Wir alle beginnen zu tanzen.', 'neutral'],
      ['¡Qué pasada!', 'Wie genial!', 'Spanien, sehr locker'],
    ],
    everyday: '`¡Qué guay!` hörst du in Spanien ständig – bei Jugendlichen wie Erwachsenen.',
    verbs: [
      ['ponemos', 'ponerse', 'Präsens, 1. Person Plural – reflexiv (nos ponemos)'],
      ['bailar', 'bailar', 'Infinitiv'],
    ],
  },
];

const bridge: LineDraft[] = [
  {
    src: 'Mañana nos vamos a levantar tarde,',
    natural: 'Morgen stehen wir spät auf,',
    literal: 'Morgen uns gehen-wir zu aufstehen spät,',
    phonetic: 'ma-NJA-na nos BA-mos a le-ban-TAR TAR-de',
    difficulty: 3,
    summary: 'Der Gedanke an morgen: ausschlafen – kein Problem.',
    grammar: [
      ['ir a + reflexives Verb', 'Das Pronomen darf **vor** `ir` stehen oder am Infinitiv hängen: `nos vamos a levantar` = `vamos a levantarnos`. Beides ist korrekt.', 'es.g.ir-a'],
      ['levantarse', '`levantarse` = aufstehen (reflexiv). Ohne Pronomen: `levantar` = etwas hochheben.', 'es.g.reflexive'],
    ],
    ambiguity: '`mañana` = „morgen“; `la mañana` = „der Morgen/Vormittag“. `mañana por la mañana` = morgen früh.',
    alternatives: [
      ['Mañana vamos a levantarnos tarde.', 'Morgen stehen wir spät auf.', 'Pronomen angehängt'],
      ['Mañana dormimos hasta tarde.', 'Morgen schlafen wir aus.'],
    ],
    everyday: '`Mañana me levanto tarde` – typischer Satz vor dem Wochenende.',
    verbs: [
      ['vamos', 'ir', 'Präsens, 1. Person Plural – ir a + Infinitiv'],
      ['levantar', 'levantarse', 'Infinitiv – reflexiv (nos … levantar)'],
    ],
  },
  {
    src: 'Que{que.causal} esta noche el corazón me arde.',
    natural: 'Denn heute Nacht brennt mir das Herz.',
    literal: 'Denn diese Nacht das Herz mir brennt.',
    phonetic: 'ke ES-ta NO-tsche el ko-ra-THON me AR-de',
    difficulty: 3,
    summary: 'Die Begründung – poetisch: Heute Nacht ist die Lebenslust zu groß, um an Schlaf zu denken.',
    grammar: [
      ['me arde – Pronomen statt „mein“', '`el corazón me arde` = mir brennt das Herz. Bei Körperteilen zeigt ein Pronomen (`me`), wem sie gehören – statt `mi corazón`.', 'es.g.pronouns'],
      ['que = denn', 'Das `que` am Anfang knüpft an die Zeile davor an: „…, denn …“.'],
    ],
    ambiguity: '`arder` (brennen) ist hier ein Bild für Leidenschaft, Aufregung und Lebenslust – keine Krankheit! Flamenco liebt solche Feuerbilder.',
    culture: 'Feuer, Herz und Nacht sind klassische Bilder im Flamenco und in der spanischen Popmusik mit Flamenco-Einfluss.',
    alternatives: [
      ['Porque esta noche estoy a tope.', 'Denn heute Nacht bin ich voll in Fahrt.', 'Spanien, locker'],
      ['Esta noche tengo mucha energía.', 'Heute Nacht habe ich viel Energie.', 'neutral'],
    ],
    everyday: 'Poetisch – im Alltag sagt man das kaum. Aber `Me duele la cabeza` (mir tut der Kopf weh) folgt demselben Muster.',
    verbs: [['arde', 'arder', 'Präsens, 3. Person Singular – regelmäßiges -er-Verb']],
  },
  {
    src: '¿Y vosotros? ¿Os vais a quedar?',
    natural: 'Und ihr? Bleibt ihr noch?',
    literal: 'Und ihr? Euch geht-ihr zu bleiben?',
    phonetic: 'i bo-ßO-tros? os BAIS a ke-DAR',
    difficulty: 3,
    summary: 'Die Frage an die Freunde: Bleibt ihr noch oder geht ihr nach Hause?',
    grammar: [
      ['vosotros', '`vosotros` = ihr (locker, Spanien). Passend dazu: `os` (euch) und `vais` (ihr geht).', 'es.g.pronouns'],
      ['quedar oder quedarse?', '`quedar` = sich verabreden (`quedamos en Sol`); **quedarse** = bleiben (`os vais a quedar`). Das kleine Pronomen ändert die Bedeutung!', 'es.g.reflexive'],
      ['ir a + Infinitiv', '`os vais a quedar` = werdet ihr bleiben?', 'es.g.ir-a'],
    ],
    alternatives: [
      ['¿Y vosotros? ¿Os quedáis?', 'Und ihr? Bleibt ihr?', 'Präsens statt ir a'],
      ['¿Y ustedes? ¿Se van a quedar?', 'Und ihr? Bleibt ihr?', 'Lateinamerika'],
    ],
    everyday: '`¿Te quedas?` / `¿Os quedáis?` – typische Frage am Ende eines Abends.',
    verbs: [
      ['vais', 'ir', 'Präsens, 2. Person Plural (vosotros)'],
      ['quedar', 'quedarse', 'Infinitiv – reflexiv: bleiben (os … quedar)'],
    ],
  },
  {
    src: '¡Venga, que{que.causal} Madrid no sabe descansar!',
    natural: 'Na los – Madrid kennt keine Pause!',
    literal: 'Komm, denn Madrid nicht weiß ausruhen!',
    phonetic: 'BEN-ga, ke ma-DRID no ßA-be des-kan-ßAR',
    difficulty: 2,
    summary: 'Der Schlachtruf der Nacht: Madrid schläft nie.',
    grammar: [
      ['saber + Infinitiv', '`saber` + Infinitiv = etwas können (gelernt): `sé nadar` = ich kann schwimmen. Hier bildlich: Madrid „kann“ sich nicht ausruhen.'],
      ['Verneinung vor dem Verb', '`no sabe` – **no** steht direkt vor dem Verb.', 'es.g.word-order-negation'],
    ],
    colloquial: '`¡Venga!` ist **typisch Spanien**: „Los!“, „Komm schon!“ – am Telefon auch „Okay, tschüss!“. Das `que` danach begründet locker.',
    culture: 'Madrid gilt als Stadt, die nie schläft: Bars, Konzerte und Straßenleben bis spät in die Nacht – besonders im Sommer.',
    alternatives: [
      ['¡Vamos, que Madrid nunca duerme!', 'Los, Madrid schläft nie!'],
      ['¡Venga, vamos!', 'Komm, los geht’s!'],
    ],
    everyday: '`¡Venga!` ist in Spanien eines der häufigsten Wörter überhaupt.',
    verbs: [
      ['venga', 'venir', 'erstarrte Befehlsform (usted) als Ausruf: „los!“'],
      ['sabe', 'saber', 'Präsens, 3. Person Singular – unregelmäßig (yo sé)'],
      ['descansar', 'descansar', 'Infinitiv'],
    ],
  },
];

const glossary = {
  ducho: gl('ducharse', 'Verb (reflexiv)', 'duschen', 'DU-tscho', [['Me ducho por la mañana.', 'Ich dusche morgens.']],
    'Alltagswort.', { form: '1. Person Singular Präsens von `ducharse` (me ducho)' }),
  visto: gl('vestirse', 'Verb (reflexiv)', 'sich anziehen', 'BIS-to', [['Me visto y salgo.', 'Ich ziehe mich an und gehe raus.']],
    'Alltagswort.', { form: '1. Person Singular Präsens von `vestirse` (Stammwechsel e → i)' }),
  peino: gl('peinarse', 'Verb (reflexiv)', 'sich kämmen', 'PEJ-no', [['Me peino delante del espejo.', 'Ich kämme mich vor dem Spiegel.']],
    'Alltagswort.', { form: '1. Person Singular Präsens von `peinarse`' }),
  deprisa: gl('deprisa', 'Adverb', 'schnell, eilig', 'de-PRI-ßa', [['¡Ven deprisa!', 'Komm schnell!']],
    'In Spanien häufig; überall verstanden: `rápido`.', { grammar: 'Auch getrennt geschrieben: `de prisa`. `Darse prisa` = sich beeilen.' }),
  pongo: gl('ponerse', 'Verb (reflexiv)', 'anziehen (Kleidung); werden', 'PON-go', [['Me pongo el abrigo.', 'Ich ziehe den Mantel an.']],
    'Sehr häufig.', { form: '1. Person Singular Präsens von `ponerse` (unregelmäßig: -go)' }),
  chaqueta: gl('chaqueta', 'Nomen (f)', 'Jacke', 'tscha-KE-ta', [['Hace frío, ponte la chaqueta.', 'Es ist kalt, zieh die Jacke an.']],
    'Alltagswort in Spanien; in Lateinamerika oft `chamarra` (Mexiko) oder `chaqueta`.'),
  mejor: gl('mejor', 'Adjektiv', 'besser; beste(r/s)', 'me-CHOR', [['Es mi mejor amiga.', 'Sie ist meine beste Freundin.']],
    'Sehr häufig.', { grammar: 'Steigerung von `bueno`: `bueno – mejor – el/la mejor`. Steht vor dem Nomen.' }),
  sonrisa: gl('sonrisa', 'Nomen (f)', 'Lächeln', 'ßon-RRI-ßa', [['¡Qué sonrisa tan bonita!', 'Was für ein schönes Lächeln!']],
    'Alltagswort.', { grammar: 'Nach n wird r gerollt.' }),
  llama: gl('llamar', 'Verb', 'rufen; anrufen', 'JA-ma', [['Te llamo luego.', 'Ich rufe dich später an.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `llamar`', grammar: '`llamarse` (reflexiv) = heißen: `Se llama Lucía.`' }),
  'lucía': gl('Lucía', 'Eigenname (f)', 'Lucía (Vorname)', 'lu-THI-a', [['Lucía vive en Madrid.', 'Lucía wohnt in Madrid.']],
    'Einer der beliebtesten Mädchennamen Spaniens.', { ipa: 'luˈθi.a' }),
  'tía': gl('tía', 'Nomen (f)', 'Tante; (Spanien, locker) Freundin, „hey du“', 'TI-a', [['¡Tía, qué bien te veo!', 'Hey, du siehst super aus!']],
    'Als Anrede nur unter Freunden in Spanien.', { register: 'umgangssprachlich', colloquial: 'In Spanien locker für Freundinnen (und Frauen allgemein); männlich `tío`.' }),
  'dónde': gl('dónde', 'Fragewort', 'wo', 'DON-de', [['¿Dónde quedamos?', 'Wo treffen wir uns?']],
    'Sehr häufig.', { grammar: 'Mit Akzent als Fragewort.' }),
  'estás': gl('estar', 'Verb', 'sein (Ort, Zustand)', 'es-TAS', [['¿Estás en casa?', 'Bist du zu Hause?']],
    'Sehr häufig.', { form: '2. Person Singular Präsens von `estar` (tú)' }),
  tranqui: gl('tranqui', 'Adjektiv/Interjektion', 'ruhig; keine Sorge, entspann dich', 'TRAN-ki', [['Tranqui, no pasa nada.', 'Keine Sorge, alles gut.']],
    'Unter Freunden in Spanien sehr häufig.', { form: 'Kurzform von `tranquilo/tranquila`', register: 'umgangssprachlich', colloquial: 'Locker und freundlich – gegenüber Fremden lieber `tranquilo/a` oder `no se preocupe`.' }),
  llego: gl('llegar', 'Verb', 'ankommen', 'JE-go', [['Llego a las nueve.', 'Ich komme um neun an.']],
    'Sehr häufig.', { form: '1. Person Singular Präsens von `llegar`' }),
  diez: gl('diez', 'Zahlwort', 'zehn', 'djeth', [['diez minutos', 'zehn Minuten']],
    'Alltagswort.', { grammar: 'In Spanien spricht man `z` wie engl. „th“ (θ), in Lateinamerika wie s.', ipa: 'djeθ' }),
  minutos: gl('minuto', 'Nomen (m, Pl.)', 'Minuten', 'mi-NU-tos', [['Espera cinco minutos.', 'Warte fünf Minuten.']],
    'Alltagswort.', { form: 'Plural von `minuto`' }),
  'nada-más': gl('nada más', 'Wendung', 'nur; nicht mehr', 'NA-da MAS', [['Un café, nada más.', 'Nur einen Kaffee, sonst nichts.']],
    'Sehr häufig.', { literal: 'nichts mehr' }),
  'qué': gl('qué', 'Fragewort', 'was', 'ke', [['¿Qué haces?', 'Was machst du?']],
    'Ständig.', { grammar: 'Mit Akzent als Fragewort.' }),
  vais: gl('ir', 'Verb', 'gehen, fahren', 'bais', [['¿Adónde vais?', 'Wohin geht ihr?']],
    'In Spanien sehr häufig.', { form: '2. Person Plural Präsens von `ir` (vosotros)' }),
  hacer: gl('hacer', 'Verb', 'machen, tun', 'a-THER', [['¿Qué vas a hacer?', 'Was hast du vor?']],
    'Eines der häufigsten Verben.', { grammar: 'Das h ist stumm; yo-Form: `hago`.' }),
  esta: gl('este', 'Demonstrativbegleiter', 'diese(r/s)', 'ES-ta', [['esta noche', 'heute Abend / heute Nacht'], ['esta semana', 'diese Woche']],
    'Sehr häufig.', { form: 'weibliche Form von `este`', grammar: 'Ohne Akzent! `está` mit Akzent ist ein Verb („ist“).' }),
  noche: gl('noche', 'Nomen (f)', 'Nacht; Abend', 'NO-tsche', [['Buenas noches.', 'Guten Abend. / Gute Nacht.']],
    'Alltagswort.', { grammar: '`esta noche` = heute Abend/heute Nacht.' }),
  os: gl('os', 'Objekt-/Reflexivpronomen', 'euch', 'os', [['¿Os gusta?', 'Gefällt es euch?']],
    'In Spanien sehr häufig; in Lateinamerika sagt man `les`/`se`.', { grammar: 'Gehört zu `vosotros`: `os venís`, `os quedáis`.' }),
  'venís': gl('venirse', 'Verb (reflexiv)', 'mitkommen', 'be-NIS', [['¿Os venís al cine?', 'Kommt ihr mit ins Kino?']],
    'In Spanien sehr häufig.', { form: '2. Person Plural Präsens von `venir(se)` (vosotros)' }),
  quedamos: gl('quedar', 'Verb', 'sich verabreden, sich treffen', 'ke-DA-mos', [['¿Quedamos mañana?', 'Treffen wir uns morgen?']],
    'In Spanien das Verb für Verabredungen.', { form: '1. Person Plural Präsens von `quedar`', register: 'umgangssprachlich', colloquial: '`quedar` in diesem Sinn ist typisch für das Spanische in Spanien.' }),
  'sol.plaza': gl('Sol (Puerta del Sol)', 'Eigenname', 'Puerta del Sol (zentraler Platz in Madrid)', 'ßol', [['Quedamos en Sol.', 'Wir treffen uns an der Puerta del Sol.']],
    'In Madrid sagt jeder kurz `Sol`.', { literal: 'Sonne (Tor der Sonne)' }),
  vale: gl('¿vale?', 'Interjektion', 'okay?, einverstanden?; okay', 'BA-le', [['—¿A las diez? —Vale.', '– Um zehn? – Okay.']],
    'In Spanien ständig.', { register: 'umgangssprachlich', colloquial: '**Typisch Spanien.** In Lateinamerika sagt man eher `¿está bien?`, `¿sale?` (Mexiko) oder `¿dale?` (Argentinien).' }),
  decid: gl('decir', 'Verb', 'sagen', 'de-THID', [['¡Decid la verdad!', 'Sagt die Wahrheit!']],
    'Befehlsform für „ihr“ – nur in Spanien.', { form: 'Imperativ 2. Person Plural (vosotros) von `decir`' }),
  'sí': gl('sí', 'Adverb', 'ja', 'ßi', [['Creo que sí.', 'Ich glaube schon.']],
    'Ständig.', { grammar: 'Mit Akzent = „ja“; ohne Akzent (`si`) = „wenn/ob“.' }),
  vamos: gl('ir', 'Verb', 'gehen; (vamos a …) wir werden / lasst uns', 'BA-mos', [['¡Vamos!', 'Los!'], ['Vamos a cenar.', 'Lass uns zu Abend essen.']],
    'Ständig.', { form: '1. Person Plural Präsens von `ir`' }),
  bailar: gl('bailar', 'Verb', 'tanzen', 'bai-LAR', [['¿Quieres bailar?', 'Willst du tanzen?']],
    'Alltagswort.'),
  hasta: gl('hasta', 'Präposition', 'bis', 'AS-ta', [['Hasta mañana.', 'Bis morgen.']],
    'Ständig.', { grammar: 'Bei gleichem Subjekt folgt der Infinitiv: `hasta ver` = bis (wir) sehen. Das h ist stumm.' }),
  ver: gl('ver', 'Verb', 'sehen', 'ber', [['¿Vamos a ver una película?', 'Schauen wir einen Film?']],
    'Eines der häufigsten Verben.', { form: 'Infinitiv', grammar: 'Mit Infinitiv: `ver salir el sol` = die Sonne aufgehen sehen.' }),
  salir: gl('salir', 'Verb', 'hinausgehen; ausgehen; (Sonne) aufgehen', 'ßa-LIR', [['Salimos esta noche.', 'Wir gehen heute Abend aus.'], ['Sale el sol.', 'Die Sonne geht auf.']],
    'Sehr häufig – auch für „ausgehen“ am Abend.', { form: 'Infinitiv', grammar: 'Unregelmäßige yo-Form: `salgo`.' }),
  sol: gl('sol', 'Nomen (m)', 'Sonne', 'ßol', [['Hace sol.', 'Die Sonne scheint.']],
    'Alltagswort.', { grammar: 'männlich: `el sol`.' }),
  noches: gl('noche', 'Nomen (f, Pl.)', 'Nächte; Abende', 'NO-tsches', [['las noches de verano', 'die Sommernächte']],
    'Alltagswort.', { form: 'Plural von `noche`' }),
  madrid: gl('Madrid', 'Eigenname', 'Madrid (Hauptstadt Spaniens)', 'ma-DRID', [['Vivo en Madrid.', 'Ich wohne in Madrid.']],
    'Die Einwohner heißen `madrileños`.', { grammar: 'Das d am Ende ist sehr schwach; viele Madrileños sprechen es fast wie „th“.' }),
  calor: gl('calor', 'Nomen (m)', 'Hitze, Wärme', 'ka-LOR', [['¡Qué calor!', 'Was für eine Hitze!']],
    'Alltagswort.', { grammar: '`Hace calor` = es ist heiß; `tengo calor` = mir ist heiß.' }),
  bajamos: gl('bajar', 'Verb', 'hinuntergehen', 'ba-CHA-mos', [['Bajamos a la calle.', 'Wir gehen auf die Straße hinunter.']],
    'Alltagswort.', { form: '1. Person Plural Präsens von `bajar`' }),
  'gran-via': gl('Gran Vía', 'Eigenname', 'Gran Vía (Prachtstraße in Madrid)', 'gran BI-a', [['Los cines de la Gran Vía', 'die Kinos der Gran Vía']],
    'Bekannte Straße im Zentrum Madrids.', { literal: 'große Straße' }),
  cantando: gl('cantar', 'Verb', 'singen', 'kan-TAN-do', [['Llega cantando.', 'Er kommt singend an.']],
    'Häufig.', { form: 'Gerundium von `cantar`' }),
  gente: gl('gente', 'Nomen (f, Sg.)', 'Leute', 'CHEN-te', [['Hay mucha gente.', 'Es sind viele Leute da.']],
    'Alltagswort.', { grammar: 'Grammatisch Singular: `la gente es…` (nicht `son`).' }),
  'ríe': gl('reírse', 'Verb (reflexiv)', 'lachen', 'RRI-e', [['Se ríe mucho.', 'Er/Sie lacht viel.']],
    'Alltagswort.', { form: '3. Person Singular Präsens von `reír(se)`' }),
  ciudad: gl('ciudad', 'Nomen (f)', 'Stadt', 'thju-DAD', [['Madrid es una ciudad grande.', 'Madrid ist eine große Stadt.']],
    'Alltagswort.', { ipa: 'θjuˈðað' }),
  'está': gl('estar', 'Verb', 'sein (Zustand, Ort); Hilfsverb der Verlaufsform', 'es-TA', [['Está lloviendo.', 'Es regnet gerade.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `estar`' }),
  brillando: gl('brillar', 'Verb', 'leuchten, glänzen', 'bri-JAN-do', [['Las estrellas están brillando.', 'Die Sterne leuchten.']],
    'Häufig.', { form: 'Gerundium von `brillar`' }),
  'tío': gl('tío', 'Nomen (m)', 'Onkel; (Spanien, locker) Typ, Kerl', 'TI-o', [['¡Tío, qué bien!', 'Alter, wie cool!']],
    'Als „Typ“ nur locker und nur in Spanien.', { register: 'umgangssprachlich', colloquial: 'In Spanien locker für „Typ“ oder als Anrede unter Freunden; weiblich `tía`.' }),
  guitarra: gl('guitarra', 'Nomen (f)', 'Gitarre', 'gi-TA-rra', [['Toco la guitarra.', 'Ich spiele Gitarre.']],
    'Alltagswort.', { grammar: '`gui` = „gi“ (u stumm); `rr` wird gerollt.' }),
  pone: gl('ponerse', 'Verb (reflexiv)', '(ponerse a) anfangen zu', 'PO-ne', [['Se pone a llorar.', 'Er fängt an zu weinen.']],
    'Häufig.', { form: '3. Person Singular Präsens von `ponerse`' }),
  tocar: gl('tocar', 'Verb', 'spielen (Instrument); berühren', 'to-KAR', [['¿Tocas el piano?', 'Spielst du Klavier?']],
    'Alltagswort.', { grammar: 'Instrumente: `tocar`; Spiele/Sport: `jugar`.' }),
  'qué.excl': gl('qué', 'Ausrufewort', 'wie!, was für ein!', 'ke', [['¡Qué bonito!', 'Wie schön!'], ['¡Qué calor!', 'Was für eine Hitze!']],
    'Ständig.', { grammar: 'In Ausrufen mit Akzent: `¡qué …!`' }),
  guay: gl('guay', 'Adjektiv', 'cool, toll', 'guai', [['¡Qué guay!', 'Wie cool!']],
    'In Spanien sehr häufig.', { register: 'umgangssprachlich', colloquial: '**Typisch Spanien.** Unveränderlich; Plural umgangssprachlich `guais`.' }),
  ponemos: gl('ponerse', 'Verb (reflexiv)', '(ponerse a) anfangen zu', 'po-NE-mos', [['Nos ponemos a cantar.', 'Wir fangen an zu singen.']],
    'Häufig.', { form: '1. Person Plural Präsens von `ponerse`' }),
  'mañana': gl('mañana', 'Adverb', 'morgen', 'ma-NJA-na', [['Hasta mañana.', 'Bis morgen.']],
    'Alltagswort.', { grammar: 'Als Nomen `la mañana` = der Morgen/Vormittag.' }),
  levantar: gl('levantarse', 'Verb (reflexiv)', 'aufstehen', 'le-ban-TAR', [['Me levanto a las siete.', 'Ich stehe um sieben auf.']],
    'Alltagswort.', { form: 'Infinitiv (hier mit vorangestelltem `nos`)' }),
  tarde: gl('tarde', 'Adverb', 'spät', 'TAR-de', [['Es tarde.', 'Es ist spät.']],
    'Alltagswort.', { grammar: 'Als Nomen `la tarde` = der Nachmittag/frühe Abend.' }),
  'corazón': gl('corazón', 'Nomen (m)', 'Herz', 'ko-ra-THON', [['Me late el corazón.', 'Mir klopft das Herz.']],
    'Häufig, auch als Kosewort.', { ipa: 'koɾaˈθon' }),
  arde: gl('arder', 'Verb', 'brennen', 'AR-de', [['La leña arde.', 'Das Holz brennt.']],
    'Eher gehoben/poetisch; im Alltag oft `quemar`.', { form: '3. Person Singular Präsens von `arder`', register: 'poetisch' }),
  vosotros: gl('vosotros', 'Personalpronomen', 'ihr (informell, Spanien)', 'bo-ßO-tros', [['¿Y vosotros?', 'Und ihr?']],
    'In Spanien Alltag; in Lateinamerika sagt man `ustedes`.', { grammar: 'Weiblich: `vosotras`.' }),
  quedar: gl('quedarse', 'Verb (reflexiv)', 'bleiben', 'ke-DAR', [['Me quedo en casa.', 'Ich bleibe zu Hause.']],
    'Sehr häufig.', { form: 'Infinitiv (hier mit vorangestelltem `os`)', grammar: '`quedar` = sich verabreden; `quedarse` = bleiben.' }),
  venga: gl('¡venga!', 'Interjektion', 'los!, komm schon!; okay!', 'BEN-ga', [['¡Venga, vámonos!', 'Los, gehen wir!']],
    'In Spanien ständig.', { form: 'erstarrte Befehlsform von `venir`', register: 'umgangssprachlich', colloquial: '**Typisch Spanien** – zum Antreiben, Zustimmen und sogar zum Verabschieden.' }),
  sabe: gl('saber', 'Verb', 'wissen; (+ Infinitiv) können', 'ßA-be', [['No sabe nadar.', 'Er kann nicht schwimmen.']],
    'Sehr häufig.', { form: '3. Person Singular Präsens von `saber`' }),
  descansar: gl('descansar', 'Verb', 'sich ausruhen', 'des-kan-ßAR', [['Necesito descansar.', 'Ich muss mich ausruhen.']],
    'Alltagswort.'),
};

const song: Song = buildSong({
  id: 'song.es.noches-de-madrid',
  courseId: 'es',
  variant: 'es-ES',
  title: 'Noches de Madrid',
  artist: 'Duende Urbano',
  cover: { from: '#2C0E37', to: '#C0392B', emoji: '💃' },
  genre: 'Flamenco-Pop',
  level: 'B1',
  speed: 'schnell',
  themes: ['Ausgehen', 'Freunde', 'Nachtleben', 'Madrid'],
  grammarTags: ['es.g.reflexive', 'es.g.ir-a', 'es.g.pronouns', 'es.g.formality', 'es.g.present-regular'],
  backing: { bpm: 100, style: 'pop', key: 'Am', chords: ['Am', 'G', 'F', 'E'] },
  sections: [
    { id: 'v1', label: 'Strophe 1', lines: verse1 },
    { id: 'c1', label: 'Refrain', lines: chorus },
    { id: 'v2', label: 'Strophe 2', lines: verse2 },
    { id: 'c2', label: 'Refrain', lines: chorus },
    { id: 'br', label: 'Bridge', lines: bridge },
    { id: 'c3', label: 'Refrain', lines: chorus },
  ],
  glossary,
  common: COMMON_ES,
});

export default song;
